Bhí	﻿Bhí	﻿bí-V	Vmis
Fionn	Fionn	Fionn-N	Npmsc
mac	mac	Mac-U	Up
Cumhaill	Cumhaill	Cumhaill-N	Npmsc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
Fianna	Fianna	Fiann-N	Ncfpc
ag	ag	ag-S	Sp
fiach	fiach	fiach-N	Nv
lá	lá	lá-N	Ncmsc
amháin	amháin	amháin-A	Aqp
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
siad	siad	siad-P	Pp3-pn
cailín	cailín	cailín-N	Ncmsc
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
marcaíocht	marcaíocht	marcaigh-N	Nv
ar	ar	ar-S	Sp
chapall	chapall	capall-N	Ncmsc
bán	bán	bán-A	Aq-msc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
siad	siad	siad-P	Pp3-pn
riamh	riamh	riamh-R	Rg
cailín	cailín	cailín-N	Ncmsc
chomh	chomh	chomh-R	Ri
hálainn	hálainn	álainn-A	Aqp
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
'	'	'-F	Fa
Cé	Cé	cé-W	W--q
thusa	thusa	tú-P	Pp2-s-e
,	,	,-F	Fi
a	a	a-U	Uv
chailín	chailín	cailín-N	Ncmsv
álainn	álainn	álainn-A	Aq-msv
óg	óg	óg-A	Aq-msc
?	?	?-F	Fq
'	'	'-F	Fa
a	a	a-Q	Q-r
deir	deir	abair-V	Vmip
Fionn	Fionn	Fionn-N	Npmsc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
'	'	'-F	Fa
Mise	Mise	mé-P	Pp1-s-e
Niamh	Niamh	Niamh-N	Npfsc
Chinn	Chinn	ceann-N	Ncmsg
Óir	Óir	ór-N	Ncmsg
'	'	'-F	Fa
,	,	,-F	Fi
a	a	a-Q	Q-r
deir	deir	abair-V	Vmip
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
'	'	'-F	Fa
Agus	Agus	agus-C	Cc
cad	cad	cad-W	W--q
as	as	as-P	Pr3ms
duit	duit	do-P	Pr2-s
?	?	?-F	Fq
'	'	'-F	Fa
Ó	Ó	ó-S	Sp
Thír	Thír	tír-N	Npfsc
na	na	na-T	Td-p
nÓg	nÓg	óg-N	Npmpg
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
m'athair	m'athair	athair-N	Ncmsc
ina	ina	i-S	Spp-s
rí	rí	rí-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
tír	tír	tír-N	Ncfsc
sin	sin	sin-D	Dd
.	.	.-F	Fe
Tír	Tír	tír-N	Ncfsc
álainn	álainn	álainn-A	Aq-fsc
is	is	is-W	Wpri
ea	ea	ea-P	Pp3-s
í	í	í-P	Pp3fs
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
bíonn	bíonn	bí-V	Vmig
gach	gach	gach-D	Dq
duine	duine	duine-N	Ncmsc
inti	inti	i-P	Pr3fs
óg	óg	óg-A	Aqp
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Labhair	Labhair	labhair-V	Vmis
Niamh	Niamh	Niamh-N	Npfsc
le	le	le-S	Sp
hOisín	hOisín	Oisín-N	Npmsc
mac	mac	Mac-U	Up
Fhinn	Fhinn	Finn-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
An	An	an-Q	Qq
dtiocfaidh	dtiocfaidh	tar-V	Vmif
tú	tú	tú-P	Pp2-s
liom	liom	le-P	Pr1-s
go	go	go-S	Sp
Tír	Tír	tír-N	Ncfsc
na	na	na-T	Td-p
nÓg	nÓg	óg-N	Npmpg
?	?	?-F	Fq
'	'	'-F	Fa
a	a	a-Q	Q-r
deir	deir	abair-V	Vmip
sí	sí	sí-P	Pp3fsn
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
'	'	'-F	Fa
Rachaidh	Rachaidh	téigh-V	Vmif
mé	mé	mé-P	Pp1-s
leat	leat	le-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
chailín	chailín	cailín-N	Ncmsv
álainn	álainn	álainn-A	Aq-msv
'	'	'-F	Fa
a	a	a-Q	Q-r
deir	deir	abair-V	Vmip
Oisín	Oisín	Oisín-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Béarfaidh	Béarfaidh	beir-V	Vmif
an	an	an-T	Td-s
capall	capall	capall-N	Ncmsc
bán	bán	bán-A	Aq-msc
go	go	go-S	Sp
Tír	Tír	tír-N	Ncfsc
na	na	na-T	Td-p
nÓg	nÓg	óg-N	Npmpg
sinn	sinn	sinn-P	Pp1-p
'	'	'-F	Fa
a	a	a-Q	Q-r
deir	deir	abair-V	Vmip
Niamh	Niamh	Niamh-N	Npfsc
le	le	le-S	Sp
hOisín	hOisín	Oisín-N	Npmsc
.	.	.-F	Fe
D'fhág	D'fhág	fág-V	Vmis
Oisín	Oisín	Oisín-N	Npmsc
slán	slán	slán-A	Aq-msc
ag	ag	ag-S	Sp
Fionn	Fionn	Fionn-N	Npmsc
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
na	na	na-T	Td-p
Fianna	Fianna	Fiann-N	Ncfpc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
brón	brón	brón-N	Ncmsc
ar	ar	ar-S	Sp
a	a	a-P	P-3ms
mhuintir	mhuintir	muintir-N	Ncfsc
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
ag	ag	ag-S	Sp
imeacht	imeacht	imigh-N	Nv
.	.	.-F	Fe
Gheall	Gheall	geall-V	Vmis
siad	siad	siad-P	Pp3-pn
go	go	go-Q	Q
dtiocfadh	dtiocfadh	tar-V	Vmc
siad	siad	siad-P	Pp3-pn
ar ais	ar ais	ar_ais-R	Rd
ar	ar	ar-S	Sp
chuairt	chuairt	cuairt-N	Ncfsc
.	.	.-F	Fe
Rith	Rith	rith-V	Vmis
an	an	an-T	Td-s
capall	capall	capall-N	Ncmsc
bán	bán	bán-A	Aq-msc
ar nós	ar nós	ar_nós-S	Spc
na	na	na-T	Tdfsg
gaoithe	gaoithe	gaoth-N	Ncfsg
.	.	.-F	Fe
Rith	Rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
thar	thar	thar-S	Sp
sliabh	sliabh	sliabh-N	Ncmsc
agus	agus	agus-C	Cc
rith	rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
thar	thar	thar-S	Sp
loch	loch	loch-N	Ncmsc
.	.	.-F	Fe
Rith	Rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
thar	thar	thar-S	Sp
tír	tír	tír-N	Ncfsc
agus	agus	agus-C	Cc
rith	rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
thar	thar	thar-S	Sp
farraige	farraige	farraige-N	Ncfsc
go dtí	go dtí	go_dtí-S	Spc
gur	gur	gur-Q	Q--s
tháinig	tháinig	tar-V	Vmis
siad	siad	siad-P	Pp3-pn
go	go	go-S	Sp
Tír	Tír	tír-N	Ncfsc
na	na	na-T	Td-p
nÓg	nÓg	óg-N	Npmpg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
bláthanna	bláthanna	bláth-N	Ncmpc
áille	áille	álainn-A	Aq--pc
sna	sna	i-S	Spa-p
páirceanna	páirceanna	páirc-N	Ncfpc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
úlla	úlla	úll-N	Ncmpc
dearga	dearga	dearg-A	Aq--pc
milse	milse	milis-A	Aq--pc
ar	ar	ar-S	Sp
na	na	na-T	Td-p
crainn	crainn	crann-N	Ncmpc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
na	na	na-T	Td-p
héin	héin	éan-N	Ncmpc
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
ceoil	ceoil	ceol-N	Ncmsg
,	,	,-F	Fi
agus	agus	agus-C	Cc
an	an	an-T	Td-s
ghrian	ghrian	grian-N	Ncfsc
ag	ag	ag-S	Sp
taitneamh	taitneamh	taitin-N	Nv
ann	ann	ann-R	Rl
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
áthas	áthas	áthas-N	Ncmsc
ar	ar	ar-S	Sp
gach	gach	gach-D	Dq
duine	duine	duine-N	Ncmsc
i	i	i-S	Sp
dTír	dTír	tír-N	Ncfsc
na	na	na-T	Td-p
nÓg	nÓg	óg-N	Npmpg
,	,	,-F	Fi
agus	agus	agus-C	Cc
gan	gan	gan-S	Sp
brón	brón	brón-N	Ncmsc
ná	ná	ná-C	Cc
tinneas	tinneas	tinneas-N	Ncmsc
ná	ná	ná-C	Cc
seanaois	seanaois	seanaois-N	Ncfsc
ar	ar	ar-S	Sp
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
an	an	an-T	Td-s
Rí	Rí	rí-N	Ncmsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
Bhanríon	Bhanríon	banríon-N	Ncfsc
fáilte	fáilte	fáilte-N	Ncfsc
roimh	roimh	roimh-S	Sp
Niamh	Niamh	Niamh-N	Npfsc
agus	agus	agus-C	Cc
roimh	roimh	roimh-S	Sp
Oisín	Oisín	Oisín-N	Npmsc
.	.	.-F	Fe
D'fhan	fhan	fan-V	Vmis
Oisín	Oisín	Oisín-N	Npmsc
i	i	i-S	Sp
dTír	dTír	tír-N	Ncfsc
na	na	na-T	Td-p
nÓg	nÓg	óg-N	Ncmpg
go ceann	go ceann	go_ceann-S	Spc
trí	trí	trí-M	Mc
chéad	chéad	céad-M	Mc
bliain	bliain	bliain-N	Ncfsc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
lá	lá	lá-N	Ncmsc
aoise	aoise	aois-N	Ncfsg
níor	níor	níor-Q	Qn-s
tháinig	tháinig	tar-V	Vmis---n
air	air	ar-P	Pr3ms
,	,	,-F	Fi
ach	ach	ach-C	Cs
é	é	é-P	Pp3ms
óg	óg	óg-A	Aqp
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
.	.	.-F	Fe
Labhair	Labhair	labhair-V	Vmis
sé	sé	sé-P	Pp3msn
le	le	le-S	Sp
Niamh	Niamh	Niamh-N	Npfsc
lá	lá	lá-N	Ncmsc
amháin	amháin	amháin-A	Aqp
.	.	.-F	Fe
'	'	'-F	Fa
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liom	liom	le-P	Pr1-s
dul	dul	téigh-N	Nv
go	go	go-S	Sp
hÉirinn	hÉirinn	Éire-N	Npfsd
'	'	'-F	Fa
a	a	a-Q	Q-r
deir	deir	abair-V	Vmip
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
'	'	'-F	Fa
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liom	liom	le-P	Pr1-s
m'athair	m'athair	athair-N	Ncmsc
agus	agus	agus-C	Cc
mo	mo	mo-P	P-1-s
mháthair	mháthair	máthair-N	Ncfsc
agus	agus	agus-C	Cc
mo	mo	mo-P	P-1-s
mhuintir	mhuintir	muintir-N	Ncfsc
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
arís	arís	arís-R	Rg
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Tabharfaidh	Tabharfaidh	tabhair-V	Vmif
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
capall	capall	capall-N	Ncmsc
bán	bán	bán-A	Aq-msc
duit	duit	do-P	Pr2-s
'	'	'-F	Fa
,	,	,-F	Fi
a	a	a-Q	Q-r
deir	deir	abair-V	Vmip
Niamh	Niamh	Niamh-N	Npfsc
.	.	.-F	Fe
'	'	'-F	Fa
Béarfaidh	Béarfaidh	beir-V	Vmif
an	an	an-T	Td-s
capall	capall	capall-N	Ncmsc
bán	bán	bán-A	Aq-msc
go	go	go-S	Sp
hÉirinn	hÉirinn	Éire-N	Npfsd
thú	thú	tú-P	Pp2-s
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ar	ar	ar-S	Sp
do	do	do-P	P-2-s
bhás	bhás	bás-N	Ncmsc
,	,	,-F	Fi
ná	ná	ná-Q	Qnm
tar	tar	tar-V	Vmm-2s-n
anuas	anuas	anuas-R	Rd
den	den	de-S	Spa-s
chapall	chapall	capall-N	Ncmsc
go dtí	go dtí	go_dtí-S	Spc
go	go	go-Q	Q
dtiocfaidh	dtiocfaidh	tar-V	Vmif
tú	tú	tú-P	Pp2-s
ar ais	ar ais	ar_ais-R	Rd
go	go	go-S	Sp
Tír	Tír	tír-N	Npfsc
na	na	na-T	Td-p
nÓg	nÓg	óg-N	Npmpg
arís	arís	arís-R	Rg
'	'	'-F	Fa
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
thiocfaidh	thiocfaidh	tar-V	Vmif---n
mé	mé	mé-P	Pp1-s
anuas	anuas	anuas-R	Rd
den	den	de-S	Spa-s
chapall	chapall	capall-N	Ncmsc
go	go	go-Q	Q
dtiocfaidh	dtiocfaidh	tar-V	Vmif
mé	mé	mé-P	Pp1-s
ar ais	ar ais	ar_ais-R	Rd
go	go	go-S	Sp
Tír	Tír	tír-N	Npfsc
na	na	na-T	Td-p
nÓg	nÓg	óg-N	Npmpg
a	a	a-Q	Q-r
deir	deir	abair-V	Vmip
Oisín	Oisín	Oisín-N	Npmsc
.	.	.-F	Fe
Suas	Suas	suas-R	Rd
le	le	le-S	Sp
Oisín	Oisín	Oisín-N	Npmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcapall	gcapall	capall-N	Ncmsc
bán	bán	bán-A	Aq-msc
.	.	.-F	Fe
Rith	Rith	rith-V	Vmis
an	an	an-T	Td-s
capall	capall	capall-N	Ncmsc
ar nós	ar nós	ar_nós-S	Spc
na	na	na-T	Tdfsg
gaoithe	gaoithe	gaoth-N	Ncfsg
.	.	.-F	Fe
Rith	Rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
thar	thar	thar-S	Sp
sliabh	sliabh	sliabh-N	Ncmsc
agus	agus	agus-C	Cc
rith	rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
thar	thar	thar-S	Sp
loch	loch	loch-N	Ncmsc
.	.	.-F	Fe
Rith	Rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
thar	thar	thar-S	Sp
tír	tír	tír-N	Ncfsc
agus	agus	agus-C	Cc
rith	rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
thar	thar	thar-S	Sp
farraige	farraige	farraige-N	Ncfsc
go dtí	go dtí	go_dtí-S	Spc
gur	gur	gur-Q	Q--s
tháinig	tháinig	tar-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-S	Sp
hÉirinn	hÉirinn	Éire-N	Npfsd
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
Oisín	Oisín	Oisín-N	Npmsc
timpeall	timpeall	timpeall-S	Sp
na	na	na-T	Tdfsg
hÉireann	hÉireann	Éire-N	Npfsg
ach	ach	ach-C	Cs
ní	ní	ní-Q	Qn
bhfuair	bhfuair	faigh-V	Vmis
sé	sé	sé-P	Pp3msn
duine	duine	duine-N	Ncmsc
dá	dá	do-S	Spp-s
mhuintir	mhuintir	muintir-N	Ncfsc
in	in	i-S	Sp
aon	aon	aon-D	Dq
áit	áit	áit-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
marbh	marbh	marbh-A	Aqp
le	le	le-S	Sp
na	na	na-T	Td-p
céadta	céadta	céad-N	Ncmpc
bliain	bliain	bliain-N	Ncfsc
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-S	Sp
gleann	gleann	gleann-N	Ncmsc
álainn	álainn	álainn-A	Aq-msc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
fir	fir	fear-N	Ncmpc
ansin	ansin	ansin-R	Rl
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
cloch	cloch	cloch-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
a	a	a-U	U
thógáil	thógáil	tóg-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
chloch	chloch	cloch-N	Ncfsc
róthrom	róthrom	trom-A	Aqp
dóibh	dóibh	do-P	Pr3-p
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
fhéad	fhéad	féad-V	Vmis---n
siad	siad	siad-P	Pp3-pn
í	í	í-P	Pp3fs
a	a	a-U	U
thógáil	thógáil	tóg-N	Nv
den	den	de-S	Spa-s
talamh	talamh	talamh-N	Ncfsc
.	.	.-F	Fe
Chrom	Chrom	crom-V	Vmis
Oisín	Oisín	Oisín-N	Npmsc
síos	síos	síos-R	Rd
.	.	.-F	Fe
Rug	Rug	beir-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcloch	gcloch	cloch-N	Ncfsc
agus	agus	agus-C	Cc
thóg	thóg	tóg-V	Vmis
sé	sé	sé-P	Pp3msn
í	í	í-P	Pp3fs
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
faraor	faraor	faraor-X	Xsc
,	,	,-F	Fi
thit	thit	tit-V	Vmis
sé	sé	sé-P	Pp3msn
den	den	de-S	Spa-s
chapall	chapall	capall-N	Ncmsc
bán	bán	bán-A	Aq-msc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
thit	thit	tit-V	Vmis
Oisín	Oisín	Oisín-N	Npmsc
den	den	de-S	Spa-s
chapall	chapall	capall-N	Ncmsc
,	,	,-F	Fi
rith	rith	rith-V	Vmis
an	an	an-T	Td-s
capall	capall	capall-N	Ncmsc
leis	leis	le-P	Pr3ms
,	,	,-F	Fi
ar ais	ar ais	ar_ais-R	Rd
go	go	go-S	Sp
Tír	Tír	tír-N	Npfsc
na	na	na-T	Td-p
nÓg	nÓg	óg-N	Npmpg
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
d'fhan	d'fhan	fan-V	Vmis
Oisín	Oisín	Oisín-N	Npmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
talamh	talamh	talamh-N	Ncfsc
,	,	,-F	Fi
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
in	in	i-S	Sp
a	a	a-P	P-3ms
sheanduine	sheanduine	seanduine-N	Ncmsc
caite	caite	caith-A	Av
lag	lag	lag-A	Aqp
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
dheachaigh	dheachaigh	téigh-V	Vmis---n
sé	sé	sé-P	Pp3msn
riamh	riamh	riamh-R	Rg
ar ais	ar ais	ar_ais-R	Rd
go	go	go-S	Sp
Tír	Tír	tír-N	Ncfsc
na	na	na-T	Td-p
nÓg	nÓg	óg-N	Ncmpg
.	.	.-F	Fe
Ná	Ná	ná-C	Cs
ní	ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
sé	sé	sé-P	Pp3msn
Niamh	Niamh	Niamh-N	Npfsc
Chinn	Chinn	ceann-N	Ncmsg
Óir	Óir	ór-N	Ncmsg
riamh	riamh	riamh-R	Rg
arís	arís	arís-R	Rg
.	.	.-F	Fe
