Nuair	﻿Nuair	﻿Nuair-C	Cs
bhí	bhí	bí-V	Vmis
Fionn	Fionn	Fionn-N	Npmsc
mac	mac	Mac-U	Up
Cumhaill	Cumhaill	Cumhaill-N	Npmsc
in	in	i-S	Sp
a	a	a-P	P-3ms
bhuachaill	bhuachaill	buachaill-N	Ncmsc
óg	óg	óg-A	Aq-msc
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
chónaí	chónaí	cónaí-N	Ncmsc
lena	lena	le-S	Spp-s
mháistir	mháistir	máistir-N	Ncmsc
.	.	.-F	Fe
Finnéigeas	Finnéigeas	Finnéigeas-N	Npmsc
an	an	an-T	Td-s
t-ainm	t-ainm	ainm-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
teach	teach	teach-N	Ncmsc
aige	aige	ag-P	Pr3ms
cois	cois	cois-S	Sp
abhainn	abhainn	abhainn-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
bradán	bradán	bradán-N	Ncmsc
san	san	i-S	Spa-s
abhainn	abhainn	abhainn-N	Ncfsc
.	.	.-F	Fe
Bradán	Bradán	bradán-N	Ncmsc
feasa	feasa	fios-N	Ncmsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
An	An	an-T	Td-s
chéad	chéad	céad-M	Mo
duine	duine	duine-N	Ncmsc
a	a	a-Q	Q-r
d'íosfadh	íosfadh	ith-V	Vmc
é	é	é-P	Pp3ms
,	,	,-F	Fi
bheadh	bheadh	bí-V	Vmc
a	a	a-P	P-3ms
fhios	fhios	fios-N	Ncmsc
aige	aige	ag-P	Pr3ms
nó	nó	nó-C	Cc
aici	aici	ag-P	Pr3fs
gach	gach	gach-D	Dq
rud	rud	rud-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
le	le	le-S	Sp
teacht	teacht	tar-N	Nv
.	.	.-F	Fe
Mharaigh	Mharaigh	maraigh-V	Vmis
Finnéigeas	Finnéigeas	Finnéigeas-N	Npmsc
an	an	an-T	Td-s
bradán	bradán	bradán-N	Ncmsc
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
tine	tine	tine-N	Ncfsc
é	é	é-P	Pp3ms
,	,	,-F	Fi
lena	lena	le-S	Spp-s
róstadh	róstadh	róst-N	Nv
.	.	.-F	Fe
Íosfaidh	Íosfaidh	ith-V	Vmif
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
bradán	bradán	bradán-N	Ncmsc
,	,	,-F	Fi
a	a	a-Q	Q-r
deir	deir	abair-V	Vmip
Finnéigeas	Finnéigeas	Finnéigeas-N	Npmsc
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
beidh	beidh	bí-V	Vmif
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
gach	gach	gach-D	Dq
rud	rud	rud-N	Ncmsc
atá	atá	bí-V	Vmip---r
le	le	le-S	Sp
teacht	teacht	tar-N	Nv
.	.	.-F	Fe
Seo	Seo	seo-W	W
a	a	a-P	P-3ms
bhuachaill	bhuachaill	buachaill-N	Ncmsc
,	,	,-F	Fi
a	a	a-Q	Q-r
deir	deir	abair-V	Vmip
sé	sé	sé-P	Pp3msn
le	le	le-S	Sp
Fionn	Fionn	Fionn-N	Npmsc
.	.	.-F	Fe
Tabhair	Tabhair	tabhair-V	Vmm-2s
aire	aire	aire-N	Ncfsc
don	don	do-S	Spa-s
bhradán	bhradán	bradán-N	Ncmsc
seo	seo	seo-D	Dd
.	.	.-F	Fe
Ná	Ná	ná-Q	Qnm
dóigh	dóigh	dóigh-V	Vmm-2s-n
é	é	é-P	Pp3ms
agus	agus	agus-C	Cc
ná	ná	ná-Q	Qnm
hith	hith	ith-V	Vmm-2s-n
aon	aon	aon-D	Dq
chuid	chuid	cuid-N	Ncfsc
de	de	de-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
tine	tine	tine-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
faoin	faoin	faoi-S	Spa-s
mbradán	mbradán	bradán-N	Ncmsc
.	.	.-F	Fe
D'éirigh	éirigh	éirigh-V	Vmis
clog	clog	clog-N	Ncmsc
ar	ar	ar-S	Sp
a	a	a-P	P-3ms
chraiceann	chraiceann	craiceann-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Ó	Ó	Ó-I	I
'	'	'-F	Fa
a	a	a-Q	Q-r
deir	deir	abair-V	Vmip
Fionn	Fionn	Fionn-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
dóite	dóite	dóigh-A	Av
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
'	'	'-F	Fa
Bhuail	Bhuail	buail-V	Vmis
Fionn	Fionn	Fionn-N	Npmsc
a	a	a-P	P-3ms
ordóg	ordóg	ordóg-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gclog	gclog	clog-N	Ncmsc
,	,	,-F	Fi
chun	chun	chun-S	Sp
é	é	é-P	Pp3ms
a	a	a-U	U
bhriseadh	bhriseadh	bris-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
craiceann	craiceann	craiceann-N	Ncmsc
te	te	te-A	Aq-msc
.	.	.-F	Fe
Dhóigh	Dhóigh	dóigh-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-P	P-3ms
ordóg	ordóg	ordóg-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-P	P-3ms
ordóg	ordóg	ordóg-N	Ncfsc
tinn	tinn	tinn-A	Aqp
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
Fionn	Fionn	Fionn-N	Npmsc
ina	ina	i-S	Spp-s
bhéal	bhéal	béal-N	Ncmsc
í	í	í-P	Pp3fs
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
Finnéigeas	Finnéigeas	Finnéigeas-N	Npmsc
abhaile	abhaile	abhaile-R	Rd
.	.	.-F	Fe
Ar	Ar	ar-Q	Qq-s
ith	ith	ith-V	Vmis
tú	tú	tú-P	Pp2-s
aon	aon	aon-D	Dq
chuid	chuid	cuid-N	Ncfsc
den	den	de-S	Spa-s
bhradán	bhradán	bradán-N	Ncmsc
?	?	?-F	Fq
a	a	a-Q	Q-r
deir	deir	abair-V	Vmip
Finnéigeas	Finnéigeas	Finnéigeas-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
tine	tine	tine-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
faoin	faoin	faoi-S	Spa-s
mbradán	mbradán	bradán-N	Ncmsc
,	,	,-F	Fi
'	'	'-F	Fa
a	a	a-Q	Q-r
deir	deir	abair-V	Vmip
Fionn	Fionn	Fionn-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
D'éirigh	éirigh	éirigh-V	Vmis
clog	clog	clog-N	Ncmsc
ar	ar	ar-S	Sp
a	a	a-P	P-3ms
chraiceann	chraiceann	craiceann-N	Ncmsc
.	.	.-F	Fe
Bhuail	Bhuail	buail-V	Vmis
mé	mé	mé-P	Pp1-s
m'ordóg	m'ordóg	ordóg-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gclog	gclog	clog-N	Ncmsc
chun	chun	chun-S	Sp
é	é	é-P	Pp3ms
a	a	a-U	U
bhriseadh	bhriseadh	bris-N	Nv
.	.	.-F	Fe
Dhóigh	Dhóigh	dóigh-V	Vmis
mé	mé	mé-P	Pp1-s
m'ordóg	m'ordóg	ordóg-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
m'ordóg	m'ordóg	ordóg-N	Ncfsc
tinn	tinn	tinn-A	Aqp
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
mé	mé	mé-P	Pp1-s
i	i	i-S	Sp
mo	mo	mo-P	P-1-s
bhéal	bhéal	béal-N	Ncmsc
í	í	í-P	Pp3fs
.	.	.-F	Fe
D'ith	ith	ith-V	Vmis
mé	mé	mé-P	Pp1-s
píosa	píosa	píosa-N	Ncmsc
beag	beag	beag-A	Aq-msc
den	den	de-S	Spa-s
bhradán	bhradán	bradán-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ar	ar	ar-S	Sp
m'ordóg	m'ordóg	ordóg-N	Ncfsc
.	.	.-F	Fe
Sin	Sin	sin-W	W
é	é	é-P	Pp3ms
an	an	an-T	Td-s
méid	méid	méid-N	Ncmsc
,	,	,-F	Fi
a	a	a-U	Uv
mháistir	mháistir	máistir-N	Ncmsv
.	.	.-F	Fe
'	'	'-F	Fa
Bradán	Bradán	bradán-N	Ncmsc
feasa	feasa	fios-N	Ncmsg
é	é	é-P	Pp3ms
sin	sin	sin-P	Pd
,	,	,-F	Fi
'	'	'-F	Fa
a	a	a-Q	Q-r
deir	deir	abair-V	Vmip
Finnéigeas	Finnéigeas	Finnéigeas-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Is	Is	is-W	Wp-i
tusa	tusa	tú-P	Pp2-s-e
an	an	an-T	Td-s
chéad	chéad	céad-M	Mo
duine	duine	duine-N	Ncmsc
a	a	a-Q	Q-r
d'ith	ith	ith-V	Vmis
cuid	cuid	cuid-N	Ncfsc
de	de	de-P	Pr3ms
.	.	.-F	Fe
Beidh	Beidh	bí-V	Vmif
fios	fios	fios-N	Ncmsc
agat	agat	ag-P	Pr2-s
as	as	as-S	Sp
seo	seo	seo-P	Pd
amach	amach	amach-R	Rd
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuirfidh	chuirfidh	cuir-V	Vmif
tú	tú	tú-P	Pp2-s
d'ordóg	d'ordóg	ordóg-N	Ncfsc
i	i	i-S	Sp
do	do	do-P	P-2-s
bhéal	bhéal	béal-N	Ncmsc
,	,	,-F	Fi
beidh	beidh	bí-V	Vmif
a	a	a-P	P-3ms
fhios	fhios	fios-N	Ncmsc
agat	agat	ag-P	Pr2-s
gach	gach	gach-D	Dq
rud	rud	rud-N	Ncmsc
atá	atá	bí-V	Vmip---r
le	le	le-S	Sp
teacht	teacht	tar-N	Nv
.	.	.-F	Fe
'	'	'-F	Fa
Mar	Mar	mar-S	Sp
sin	sin	sin-P	Pd
is	is	is-W	Wpri
ea	ea	ea-P	Pp3-s
a	a	a-Q	Q-r
fuair	fuair	faigh-V	Vmis
Fionn	Fionn	Fionn-N	Npmsc
fios	fios	fios-N	Ncmsc
.	.	.-F	Fe
