Bhí	﻿Bhí	﻿Bhí-V	Vmis
fear	fear	fear-N	Ncmsc
ann	ann	i-P	Pr3ms
fadó	fadó	fadó-R	Rg
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
an-bhocht	an-bhocht	bocht-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
deartháir	deartháir	deartháir-N	Ncmsc
saibhir	saibhir	saibhir-A	Aq-msc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Lá	Lá	lá-N	Ncmsc
amháin	amháin	amháin-A	Aqp
chuaigh	chuaigh	téigh-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
bocht	bocht	bocht-A	Aq-msc
amach	amach	amach-R	Rd
ag	ag	ag-S	Sp
díol	díol	díol-N	Nv
bó	bó	bó-N	Ncfsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
gur	gur	gur-Q	Q--s
tháinig	tháinig	tar-V	Vmis
sé	sé	sé-P	Pp3msn
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
áit	áit	áit-N	Ncfsc
ina	ina	i-S	Spr
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
aonach	aonach	aonach-N	Ncmsc
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
fear	fear	fear-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ar	ar	ar-S	Sp
tí	tí	tí-N	Ncfsc
crochadh	crochadh	crochadh-N	Nv
mar	mar	mar-S	Sp
gheall	gheall	geall-N	Ncmsc
go	go	go-Q	Q
ndearna	ndearna	déan-V	Vmis---d
sé	sé	sé-P	Pp3msn
rud	rud	rud-N	Ncmsc
éigint	éigint	éigint-A	Aq-msc
as	as	as-S	Sp
bealach	bealach	bealach-N	Ncmsc
.	.	.-F	Fe
Dúirt	Dúirt	abair-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
bocht	bocht	bocht-A	Aq-msc
leis	leis	le-S	Sp
na	na	na-T	Td-p
daoine	daoine	duine-N	Ncmpc
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
a	a	a-U	U
ligean	ligean	lig-N	Nv
saor	saor	saor-A	Aqp
,	,	,-F	Fi
agus	agus	agus-C	Cc
go	go	go-Q	Q
dtabharfadh	dtabharfadh	tabhair-V	Vmc
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
bhó	bhó	bó-N	Ncfsc
dóibh	dóibh	do-P	Pr3-p
.	.	.-F	Fe
Ligeadar	Ligeadar	lig-V	Vmis3p
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
saor	saor	saor-A	Aqp
agus	agus	agus-C	Cc
thugadar	thugadar	tabhair-V	Vmis3p
an	an	an-T	Td-s
bhó	bhó	bó-N	Ncfsc
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
bocht	bocht	bocht-A	Aq-msc
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
le	le	le-S	Sp
crochadh	crochadh	croch-N	Nv
go dtí	go dtí	go_dtí-S	Spc
a	a	a-P	P-3ms
theach	theach	teach-N	Ncmsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
sé	sé	sé-P	Pp3msn
isteach	isteach	isteach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
,	,	,-F	Fi
d'fhiafraigh	d'fhiafraigh	fiafraigh-V	Vmis
a	a	a-P	P-3ms
bhean	bhean	bean-N	Ncfsc
de	de	de-P	Pr3ms
,	,	,-F	Fi
céard	céard	cé-W	W--q
a	a	a-Q	Q-r
fuair	fuair	faigh-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbó	mbó	bó-N	Ncfsc
.	.	.-F	Fe
D'inis	D'inis	inis-V	Vmis
sé	sé	sé-P	Pp3msn
di	di	do-P	Pr3fs
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
caoineadh	caoineadh	caoin-N	Nv
.	.	.-F	Fe
Ná	Ná	ná-Q	Qnm
bí	bí	bí-V	Vmm-2s-n
ag	ag	ag-S	Sp
caoineadh	caoineadh	caoin-N	Nv
arsa	arsa	arsa-V	Vmis
Luach	Luach	luach-N	Ncmsc
Na	Na	na-T	Td-p
Bó	Bó	bó-N	Ncfpg
ach	ach	ach-C	Cs
luigh	luigh	luigh-V	Vmm-2s
siar	siar	siar-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
leaba	leaba	leaba-N	Ncfsc
thú	thú	tú-P	Pp2-s
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
.	.	.-F	Fe
D'imigh	D'imigh	imigh-V	Vmis
Luach	Luach	luach-N	Ncmsc
Na	Na	na-T	Td-p
Bó	Bó	bó-N	Ncfpg
amach	amach	amach-R	Rd
ansin	ansin	ansin-R	Rt
agus	agus	agus-C	Cc
chuaigh	chuaigh	téigh-V	Vmis
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
áit	áit	áit-N	Ncfsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
bulláin	bulláin	bullán-N	Ncmpc
an	an	an-T	Td-s
dearthár	dearthár	deartháir-N	Ncmsg
saibhir	saibhir	saibhir-A	Aq-msc
.	.	.-F	Fe
Chroch	Chroch	croch-V	Vmis
sé	sé	sé-P	Pp3msn
leis	leis	le-P	Pr3ms
péire	péire	péire-N	Ncmsc
acu	acu	ag-P	Pr3-p
agus	agus	agus-C	Cc
mharaigh	mharaigh	maraigh-V	Vmis
sé	sé	sé-P	Pp3msn
iad	iad	iad-P	Pp3-p
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt
bhí	bhí	bí-V	Vmis
neart	neart	neart-N	Ncmsc
le	le	le-S	Sp
nithe	nithe	ní-N	Nv
ag	ag	ag-S	Sp
an	an	an-T	Td-s
bhfear	bhfear	fear-N	Ncmsc
bhocht	bhocht	bocht-A	Aq-msc
agus	agus	agus-C	Cc
a	a	a-P	P-3ms
bhean	bhean	bean-N	Ncfsc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
.	.	.-F	Fe
Lá	Lá	lá-N	Ncmsc
arna	arna	arna-S	Spc
mhárach	mhárach	márach-N	Ns-s
d'imigh	d'imigh	imigh-V	Vmis
Luach	Luach	luach-N	Ncmsc
Na	Na	na-T	Td-p
Bó	Bó	bó-N	Ncfpg
amach	amach	amach-R	Rd
agus	agus	agus-C	Cc
chuaigh	chuaigh	téigh-V	Vmis
sé	sé	sé-P	Pp3msn
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
áit	áit	áit-N	Ncfsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
caoirigh	caoirigh	caora-N	Ncfpc
agus	agus	agus-C	Cc
bulláin	bulláin	bullán-N	Ncmpc
an	an	an-T	Td-s
dearthár	dearthár	deartháir-N	Ncmsg
saibhir	saibhir	saibhir-A	Aq-msc
agus	agus	agus-C	Cc
chroch	chroch	croch-V	Vmis
sé	sé	sé-P	Pp3msn
leis	leis	le-P	Pr3ms
dhá	dhá	dó-M	Mc
chaora	chaora	caora-N	Ncfsc
faoin	faoin	faoi-S	Spa-s
a	a	a-P	P-3fs
ascaill	ascaill	ascaill-N	Ncfsc
,	,	,-F	Fi
mar	mar	mar-C	Cs
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
an-láidir	an-láidir	láidir-A	Aqp
.	.	.-F	Fe
Mharaigh	Mharaigh	maraigh-V	Vmis
sé	sé	sé-P	Pp3msn
iad	iad	iad-P	Pp3-p
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
neart	neart	neart-N	Ncmsc
caoireoil	caoireoil	caoireoil-N	Ncfsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
bhfear	bhfear	fear-N	Ncmsc
bhocht	bhocht	bocht-A	Aq-msc
agus	agus	agus-C	Cc
a	a	a-P	P-3ms
chlann	chlann	clann-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Luach	Luach	luach-N	Ncmsc
Na	Na	na-T	Td-p
Bó	Bó	bó-N	Ncfpg
ag	ag	ag-S	Sp
tabhairt	tabhairt	tabhair-N	Nv
bulláin	bulláin	bullán-N	Ncmsg
agus	agus	agus-C	Cc
caoirigh	caoirigh	caora-N	Ncfpc
as	as	as-S	Sp
garraí	garraí	garra-N	Ncmsc
an	an	an-T	Td-s
fhir	fhir	fear-N	Ncmsg
shaibhir	shaibhir	saibhir-A	Aq-msg
go	go	go-S	Sp
cheann	cheann	ceann-N	Ncmsc
coicíse	coicíse	coicís-N	Ncfsg
.	.	.-F	Fe
Lá	Lá	lá-N	Ncmsc
amháin	amháin	amháin-A	Aqp
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
deartháir	deartháir	deartháir-N	Ncmsc
saibhir	saibhir	saibhir-A	Aq-msc
lena	lena	le-S	Spp-s
bhean	bhean	bean-N	Ncfsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
na	na	na-T	Td-p
bulláin	bulláin	bullán-N	Ncmpc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
caoirigh	caoirigh	caora-N	Ncfpc
ag	ag	ag-S	Sp
imeacht	imeacht	imigh-N	Nv
uaidh	uaidh	ó-P	Pr3ms
.	.	.-F	Fe
Dúirt	Dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
leis	leis	le-P	Pr3ms
go	go	go-C	Cs
mb'fhéidir	mb'fhéidir	féidir-N	Ns-s
gurb	gurb	is-W	Wpdi
é	é	é-P	Pp3ms
a	a	a-P	P-3ms
dheartháir	dheartháir	deartháir-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
dhá	dhá	do-S	Spp
ghoid	ghoid	goid-N	Nv
uaidh	uaidh	ó-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
máthair	máthair	máthair-N	Ncfsc
an	an	an-T	Td-s
dá	dá	dó-M	Mc
deartháir	deartháir	deartháir-N	Ncmsc
beo	beo	beo-A	Aqp
fós	fós	fós-R	Rg
.	.	.-F	Fe
Bhíodh	Bhíodh	bí-V	Vmih
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
ceangail	ceangail	ceangal-N	Nv
cnámhaí	cnámhaí	cnámh-N	Ncfsg
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
.	.	.-F	Fe
Dúirt	Dúirt	abair-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
saibhir	saibhir	saibhir-A	Aq-msc
go	go	go-Q	Q
gcuirfeadh	gcuirfeadh	cuir-V	Vmc
sé	sé	sé-P	Pp3msn
a	a	a-P	P-3ms
mháthair	mháthair	máthair-N	Ncfsc
síos	síos	síos-R	Rd
i	i	i-S	Sp
mbosca	mbosca	bosca-N	Ncmsc
agus	agus	agus-C	Cc
go	go	go-Q	Q
dtabharfadh	dtabharfadh	tabhair-V	Vmc
sé	sé	sé-P	Pp3msn
soir	soir	soir-R	Rd
go dtí	go dtí	go_dtí-S	Spc
teach	teach	teach-N	Ncmsc
a	a	a-P	P-3ms
dhearthár	dhearthár	deartháir-N	Ncmsg
í	í	í-P	Pp3fs
agus	agus	agus-C	Cc
dá	dá	dá-C	Cs
bhfeicfeadh	bhfeicfeadh	feic-V	Vmc
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
ithe	ithe	ith-N	Nv
feola	feola	feoil-N	Ncfsg
iad	iad	iad-P	Pp3-p
a	a	a-U	U
insint	insint	inis-N	Nv
dóibh	dóibh	do-P	Pr3-p
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
thiocfadh	thiocfadh	tar-V	Vmc
sí	sí	sí-P	Pp3fsn
ar ais	ar ais	ar_ais-R	Rd
.	.	.-F	Fe
Lá	Lá	lá-N	Ncmsc
ar	ar	ar-S	Sp
na	na	na-T	Tdfsg
mhárach	mhárach	márach-N	Ns-s
chuaigh	chuaigh	téigh-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
saibhir	saibhir	saibhir-A	Aq-msc
soir	soir	soir-R	Rd
go dtí	go dtí	go_dtí-S	Spc
teach	teach	teach-N	Ncmsc
a	a	a-P	P-3ms
dhearthár	dhearthár	deartháir-N	Ncmsg
agus	agus	agus-C	Cc
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
leo	leo	le-P	Pr3-p
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
bosca	bosca	bosca-N	Ncmsc
sa	sa	i-S	Spa-s
mbealach	mbealach	bealach-N	Ncmsc
air	air	ar-P	Pr3ms
mar	mar	mar-C	Cs
bhí	bhí	bí-V	Vmis
damhsa	damhsa	damhsa-N	Ncmsc
le	le	le-S	Sp
beith	beith	bí-N	Nv
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-P	P-3ms
mháthair	mháthair	máthair-N	Ncfsc
istigh	istigh	istigh-R	Rl
sa	sa	i-S	Spa-s
mbosca	mbosca	bosca-N	Ncmsc
.	.	.-F	Fe
An	An	an-T	Td-s
tráthnóna	tráthnóna	tráthnóna-N	Ncmsc
sin	sin	sin-D	Dd
d'imigh	d'imigh	imigh-V	Vmis
Luach	Luach	luach-N	Ncmsc
Na	Na	na-T	Td-p
Bó	Bó	bó-N	Ncfpg
amach	amach	amach-R	Rd
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
sé	sé	sé-P	Pp3msn
bullán	bullán	bullán-N	Ncmsc
eile	eile	eile-D	Dd
as	as	as-S	Sp
garraí	garraí	garra-N	Ncmpc
a	a	a-P	P-3ms
dhearthár	dhearthár	deartháir-N	Ncmsg
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
dhá	dhá	do-S	Spp
mharú	mharú	marú-N	Nv
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
páistí	páistí	páiste-N	Ncmpc
an	an	an-T	Td-s
fhir	fhir	fear-N	Ncmsg
bhoicht	bhoicht	bocht-A	Aq-msg
ag	ag	ag-S	Sp
spraoi	spraoi	spraoi-N	Nv
timpeall	timpeall	timpeall-S	Sp
an	an	an-T	Td-s
bhosca	bhosca	bosca-N	Ncmsg
.	.	.-F	Fe
Lig	Lig	lig-V	Vmis
duine	duine	duine-N	Ncmsc
acu	acu	ag-P	Pr3-p
scréach	scréach	scréach-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
Ó	Ó	ó-I	I
a	a	a-U	Uv
Dhaide	Dhaide	Dhaide-N	Npmsv
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
,	,	,-F	Fi
féach	féach	féach-V	Vmm-2s
an	an	an-T	Td-s
súil	súil	súil-N	Ncfsc
atá	atá	bí-V	Vmip---r
istigh	istigh	istigh-R	Rl
sa	sa	i-S	Spa-s
mbosca	mbosca	bosca-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
D'éirigh	D'éirigh	éirigh-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
bocht	bocht	bocht-A	Aq-msc
agus	agus	agus-C	Cc
d'oscail	d'oscail	oscail-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
bosca	bosca	bosca-N	Ncmsc
.	.	.-F	Fe
Bheir	Bheir	bí-V	Vmif2s
Luach	Luach	luach-N	Ncmsc
Na	Na	na-T	Td-p
Bó	Bó	bó-N	Ncfpg
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcailleach	gcailleach	cailleach-N	Ncfsc
agus	agus	agus-C	Cc
thacht	thacht	tacht-V	Vmis
sé	sé	sé-P	Pp3msn
í	í	í-P	Pp3fs
leis	leis	le-S	Sp
an	an	an-T	Td-s
gcnámh	gcnámh	cnámh-N	Ncfsc
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
ceangail	ceangail	ceangail-N	Nv
.	.	.-F	Fe
Cúpla	Cúpla	cúpla-N	Ncmsc
lá	lá	lá-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd
,	,	,-F	Fi
tháinig	tháinig	tar-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
saibhir	saibhir	saibhir-A	Aq-msc
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
an	an	an-T	Td-s
bosca	bosca	bosca-N	Ncmsg
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
d'oscail	d'oscail	oscail-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
bosca	bosca	bosca-N	Ncmsc
agus	agus	agus-C	Cc
fuair	fuair	faigh-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-P	P-3ms
mháthair	mháthair	máthair-N	Ncfsc
caillte	caillte	caill-A	Av
.	.	.-F	Fe
'	'	'-F	Fa
Is	Is	is-W	Wp-i
maith	maith	maith-A	Aqp
a	a	a-Q	Q-r
rinne	rinne	déan-V	Vmis
na	na	na-T	Td-p
cnámha	cnámha	cnámh-N	Ncfpc
duit	duit	do-P	Pr2-s
,	,	,-F	Fi
'	'	'-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt
bhí	bhí	bí-V	Vmis
tórramh	tórramh	tórramh-N	Ncmsc
míosa	míosa	mí-N	Ncfsg
uirthi	uirthi	ar-P	Pr3fs
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
an-spraoi	an-spraoi	spraoi-N	Ncmsc
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Cuireadh	Cuireadh	cuir-V	Vmis0
í	í	í-P	Pp3fs
ansin	ansin	ansin-R	Rt
agus	agus	agus-C	Cc
cuireadh	cuireadh	cuir-V	Vmis0
céad	céad	céad-M	Mc
punt	punt	punt-N	Ncmsc
síos	síos	síos-R	Rd
sa	sa	i-S	Spa-s
talamh	talamh	talamh-N	Ncfsc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
An	An	an-T	Td-s
oíche	oíche	oíche-N	Ncfsc
tar éis	tar éis	tar_éis-S	Spc
í	í	í-P	Pp3fs
a	a	a-P	P-3fs
chur	chur	cuir-N	Nv
d'imigh	d'imigh	imigh-V	Vmis
Luach	Luach	luach-N	Ncmsc
Na	Na	na-T	Td-p
Bó	Bó	bó-N	Ncfpg
amach	amach	amach-R	Rd
agus	agus	agus-C	Cc
thóg	thóg	tóg-V	Vmis
sé	sé	sé-P	Pp3msn
aníos	aníos	aníos-R	Rd
í	í	í-P	Pp3fs
,	,	,-F	Fi
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
seasamh	seasamh	seasamh-N	Ncmsc
ag	ag	ag-S	Sp
doras	doras	doras-N	Ncmsc
an	an	an-T	Td-s
dearthár	dearthár	deartháir-N	Ncmsg
saibhir	saibhir	saibhir-A	Aq-msc
í	í	í-P	Pp3fs
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
d'éirigh	d'éirigh	éirigh-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
saibhir	saibhir	saibhir-A	Aq-msc
lá	lá	lá-N	Ncmsc
ar	ar	ar-S	Sp
na	na	na-T	Tdfsg
mhárach	mhárach	márach-N	Ns-s
,	,	,-F	Fi
d'oscail	d'oscail	oscail-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
agus	agus	agus-C	Cc
thit	thit	tit-V	Vmis
a	a	a-P	P-3ms
mháthair	mháthair	máthair-N	Ncfsc
isteach	isteach	isteach-R	Rd
ina	ina	i-S	Spp-s
dhá	dhá	dó-M	Mc
lámh	lámh	lámh-N	Ncfsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
beag	beag	beag-A	Aqp
nár	nár	nár-Q	Qnrs
thit	thit	tit-V	Vmis---n
sé	sé	sé-P	Pp3msn
mín	mín	mín-A	Aqp
marbh	marbh	marbh-A	Aqp
le	le	le-S	Sp
scanradh	scanradh	scanradh-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
tórramh	tórramh	tórramh-N	Ncmsc
míosa	míosa	mí-N	Ncfsg
eile	eile	eile-D	Dd
uirthi	uirthi	ar-P	Pr3fs
agus	agus	agus-C	Cc
cuireadh	cuireadh	cuir-V	Vmis0
í	í	í-P	Pp3fs
arís	arís	arís-R	Rg
,	,	,-F	Fi
agus	agus	agus-C	Cc
cuireadh	cuireadh	cuir-V	Vmis0
dhá	dhá	dó-M	Mc
chéad	chéad	céad-M	Mc
punt	punt	punt-N	Ncmsc
síos	síos	síos-R	Rd
léi	léi	le-P	Pr3fs
,	,	,-F	Fi
mar	mar	mar-C	Cs
shíl	shíl	síl-V	Vmis
sé	sé	sé-P	Pp3msn
nár	nár	nár-Q	Qnrs
chuir	chuir	cuir-V	Vmis---n
sé	sé	sé-P	Pp3msn
a	a	a-P	P-3-p
ndóthain	ndóthain	dóthain-N	Ncfsc
airgid	airgid	airgead-N	Ncmsg
síos	síos	síos-R	Rd
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
D'imigh	D'imigh	imigh-V	Vmis
Luach	Luach	luach-N	Ncmsc
Na	Na	na-T	Td-p
Bó	Bó	bó-N	Ncfpg
amach	amach	amach-R	Rd
,	,	,-F	Fi
thóg	thóg	tóg-V	Vmis
sé	sé	sé-P	Pp3msn
aníos	aníos	aníos-R	Rd
an	an	an-T	Td-s
corp	corp	corp-N	Ncmsc
arís	arís	arís-R	Rg
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
dá	dá	dó-M	Mc
céad	céad	céad-M	Mc
punt	punt	punt-N	Ncmsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Thóg	Thóg	tóg-V	Vmis
sé	sé	sé-P	Pp3msn
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
scioból	scioból	scioból-N	Ncmsc
í	í	í-P	Pp3fs
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
suí	suí	suí-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcapall	gcapall	capall-N	Ncmsc
í	í	í-P	Pp3fs
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
d'éirigh	d'éirigh	éirigh-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
saibhir	saibhir	saibhir-A	Aq-msc
agus	agus	agus-C	Cc
nuair	nuair	nuair-C	Cs
chuaigh	chuaigh	téigh-V	Vmis
sé	sé	sé-P	Pp3msn
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
scioból	scioból	scioból-N	Ncmsc
chonaic	chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-P	P-3ms
mháthair	mháthair	máthair-N	Ncfsc
ina	ina	i-S	Spp-s
suí	suí	suí-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcapall	gcapall	capall-N	Ncmsc
agus	agus	agus-C	Cc
scanraíodh	scanraíodh	scanraigh-V	Vmis0
arís	arís	arís-R	Rg
é	é	é-P	Pp3ms
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
fógra	fógra	fógra-N	Ncmsc
amach	amach	amach-R	Rd
d'aon	d'aon	aon-D	Dq
fhear	fhear	fear-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbaile	mbaile	baile-N	Ncmsc
a	a	a-Q	Q-r
fhairfeadh	fhairfeadh	fair-V	Vmc
an	an	an-T	Td-s
corp	corp	corp-N	Ncmsc
dó	dó	do-P	Pr3ms
go	go	go-Q	Q
dtabharfadh	dtabharfadh	tabhair-V	Vmc
sé	sé	sé-P	Pp3msn
cúig	cúig	cúig-M	Mc
céad	céad	céad-M	Mc
punt	punt	punt-N	Ncmsc
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
fios	fios	fios-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
sagart	sagart	sagart-N	Ncmsc
le	le	le-S	Sp
haghaidh	haghaidh	aghaidh-N	Ncfsc
an	an	an-T	Td-s
corp	corp	corp-N	Ncmsc
a	a	a-U	U
fhaire	fhaire	fair-N	Nv
agus	agus	agus-C	Cc
tháinig	tháinig	tar-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
oíche	oíche	oíche-N	Ncfsc
seo	seo	seo-D	Dd
ag	ag	ag-S	Sp
faire	faire	fair-N	Nv
an	an	an-T	Td-s
choirp	choirp	corp-N	Ncmsg
.	.	.-F	Fe
Fuair	Fuair	faigh-V	Vmis
Luach	Luach	luach-N	Ncmsc
Na	Na	na-T	Td-p
Bó	Bó	bó-N	Ncfpg
clocha	clocha	cloch-N	Ncfpc
beaga	beaga	beag-A	Aq--pc
agus	agus	agus-C	Cc
dhearg	dhearg	dearg-V	Vmis
sé	sé	sé-P	Pp3msn
sa	sa	i-S	Spa-s
tine	tine	tine-N	Ncfsc
iad	iad	iad-P	Pp3-p
.	.	.-F	Fe
Fuair	Fuair	faigh-V	Vmis
sé	sé	sé-P	Pp3msn
buicéad	buicéad	buicéad-N	Ncmsc
ansin	ansin	ansin-R	Rt
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
isteach	isteach	isteach-R	Rd
ann	ann	i-R	Rl
iad	iad	iad-P	Pp3-p
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
sé	sé	sé-P	Pp3msn
leis	leis	le-P	Pr3ms
iad	iad	iad-P	Pp3-p
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
an	an	an-T	Td-s
reilig	reilig	reilig-N	Ncfsc
agus	agus	agus-C	Cc
d'fhan	d'fhan	fan-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-Q	Q
bhfaca	bhfaca	feic-V	Vmis---d
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
sagart	sagart	sagart-N	Ncmsc
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
caitheamh	caitheamh	caith-N	Nv
na	na	na-T	Td-p
clocha	clocha	cloch-N	Ncfpc
dearga	dearga	dearg-A	Aq--pc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
an	an	an-T	Td-s
sagart	sagart	sagart-N	Ncmsc
do	do	do-S	Sp
na	na	na-T	Td-p
boinn	boinn	bonn-N	Ncmpc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Thóg	Thóg	tóg-V	Vmis
Luach	Luach	luach-N	Ncmsc
Na	Na	na-T	Td-p
Bó	Bó	bó-N	Ncfpg
aníos	aníos	aníos-R	Rd
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
arís	arís	arís-R	Rg
agus	agus	agus-C	Cc
rinne	rinne	déan-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
rud	rud	rud-N	Ncmsc
céanna	céanna	céanna-A	Aqp
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
saibhir	saibhir	saibhir-A	Aq-msc
beagnach	beagnach	beagnach-R	Rg
bochtaithe	bochtaithe	bochtaigh-A	Av
anois	anois	anois-R	Rt
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
sé	sé	sé-P	Pp3msn
soir	soir	soir-R	Rd
ag	ag	ag-S	Sp
teach	teach	teach-N	Ncmsc
a	a	a-P	P-3ms
dhearthár	dhearthár	deartháir-N	Ncmsg
agus	agus	agus-C	Cc
d'fhiafraigh	d'fhiafraigh	fiafraigh-V	Vmis
sé	sé	sé-P	Pp3msn
de	de	de-P	Pr3ms
an	an	an-Q	Qq
bhfairfeadh	bhfairfeadh	fair-V	Vmc
sé	sé	sé-P	Pp3msn
a	a	a-P	P-3ms
mháthair	mháthair	máthair-N	Ncfsc
dó	dó	do-P	Pr3ms
agus	agus	agus-C	Cc
go	go	go-Q	Q
dtabharfadh	dtabharfadh	tabhair-V	Vmc
sé	sé	sé-P	Pp3msn
cúig	cúig	cúig-M	Mc
céad	céad	céad-M	Mc
punt	punt	punt-N	Ncmsc
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
Dúirt	Dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
leis	leis	le-P	Pr3ms
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
fear	fear	fear-N	Ncmsc
aige	aige	ag-P	Pr3ms
a	a	a-Q	Q-p
bhfairfeadh	bhfairfeadh	fair-V	Vmc
í	í	í-P	Pp3fs
.	.	.-F	Fe
Glaoigh	Ghlaoigh	glaoigh-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
Luach	Luach	luach-N	Ncmsc
Na	Na	na-T	Td-p
Bó	Bó	bó-N	Ncfpg
ansin	ansin	ansin-R	Rt
agus	agus	agus-C	Cc
d'fhiafraigh	d'fhiafraigh	fiafraigh-V	Vmis
sé	sé	sé-P	Pp3msn
de	de	de-P	Pr3ms
an	an	an-Q	Qq
bhfairfeadh	bhfairfeadh	fair-V	Vmc
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
corp	corp	corp-N	Ncmsc
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
Dúirt	Dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-Q	Q
bhfairfeadh	bhfairfeadh	fair-V	Vmc
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
Luach	Luach	luach-N	Ncmsc
Na	Na	na-T	Td-p
Bó	Bó	bó-N	Ncfpg
amach	amach	amach-R	Rd
ansin	ansin	ansin-R	Rt
ag	ag	ag-S	Sp
faire	faire	faireadh-N	Nv
an	an	an-T	Td-s
choirp	choirp	corp-N	Ncmsg
ach	ach	ach-C	Cs
chuaigh	chuaigh	téigh-V	Vmis
sé	sé	sé-P	Pp3msn
siar	siar	siar-R	Rd
ag	ag	ag-S	Sp
teach	teach	teach-N	Ncmsc
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
bocht	bocht	bocht-A	Aq-msc
agus	agus	agus-C	Cc
chuaigh	chuaigh	téigh-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
chodladh	chodladh	codladh-N	Nv
go	go	go-S	Sp
maidin	maidin	maidin-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
shuí	shuí	suí-N	Nv
ag	ag	ag-S	Sp
breacadh	breacadh	breac-N	Nv
an	an	an-T	Td-s
lae	lae	lá-N	Ncmsg
agus	agus	agus-C	Cc
chuaigh	chuaigh	téigh-V	Vmis
sé	sé	sé-P	Pp3msn
go dtí	go dtí	go_dtí-S	Spc
teach	teach	teach-N	Ncmsc
an	an	an-T	Td-s
fhir	fhir	fear-N	Ncmsg
saibhir	saibhir	saibhir-A	Aq-msc
.	.	.-F	Fe
D'fhiafraigh	D'fhiafraigh	fiafraigh-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
saibhir	saibhir	saibhir-A	Aq-msc
de	de	de-P	Pr3ms
an	an	an-Q	Qq
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
a	a	a-U	U
theacht	theacht	tar-N	Nv
aníos	aníos	aníos-R	Rd
.	.	.-F	Fe
Dúirt	Dúirt	abair-V	Vmis
Luach	Luach	luach-N	Ncmsc
Na	Na	na-T	Td-p
Bó	Bó	bó-N	Ncfpg
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an-trioblóid	an-trioblóid	trioblóid-N	Ncfsc
aige	aige	ag-P	Pr3ms
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
í	í	í-P	Pp3fs
a	a	a-U	U
choinneáil	choinneáil	coinnigh-N	Nv
síos	síos	síos-R	Rd
.	.	.-F	Fe
Fuair	Fuair	faigh-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
cúig	cúig	cúig-M	Mc
céad	céad	céad-M	Mc
agus	agus	agus-C	Cc
d'imigh	d'imigh	imigh-V	Vmis
sé	sé	sé-P	Pp3msn
abhaile	abhaile	abhaile-R	Rd
go	go	go-S	Sp
teach	teach	teach-N	Ncmsc
an	an	an-T	Td-s
dearthár	dearthár	deartháir-N	Ncmsg
bocht	bocht	bocht-A	Aq-msc
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
saibhir	saibhir	saibhir-A	Aqp
as	as	as-S	Sp
sin	sin	sin-P	Pd
amach	amach	amach-R	Rd
.	.	.-F	Fe
Críoch	Críoch	críoch-N	Ncfsc
.	.	.-F	Fe
