Bhí	Bhí	bí-V	Vmis
mo	mo	mo-D	Dp1-s
sheanathair	sheanathair	seanathair-N	Ncmsc
ina	ina	i-S	Spp-s
shuí	shuí	suí-N	Nv
le	le	le-S	Sp
solas	solas	solas-N	Ncmsc
an	an	an-T	Td-s
lae	lae	lá-N	Ncmsg
lá	lá	lá-N	Ncmsc
fadó	fadó	fadó-R	Rg
agus	agus	agus-C	Cc
chuaidh	chuaidh	téigh-V	Vmis
sé	sé	sé-P	Pp3msn
amach	amach	amach-R	Rd
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
tríd	tríd	trí-S	Sp
a	a	a-D	Dp3ms
chuid	chuid	cuid-N	Ncfsc
talún	talún	talamh-N	Ncfsg
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
leipreachán	leipreachán	leipreachán-N	Ncmsc
ina	ina	i-S	Spp-s
chodladh	chodladh	codladh-N	Ncfsc
dó	dhó	do-P	Pr3ms
féin	féin	féin-P	Px
ar	ar	ar-S	Sp
a	a	a-D	Dp3ms
thulán	thulán	tulán-N	Ncmsc
féir	féir	féar-N	Ncmsg
.	.	.-F	Fe
Rith	Rith	rith-V	Vmis
mo	mo	mo-D	Dp1-s
sheanathair	sheanathair	seanathair-N	Ncmsc
chuige	chuige	chuig-P	Pr3ms
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
sé	sé	sé-P	Pp3msn
leis	leis	le-P	Pr3ms
abhaile	abhaile	abhaile-R	Rd
é	é	é-P	Pp3ms
.	.	.-F	Fe
Shíl	Shíl	síl-V	Vmis
sé	sé	sé-P	Pp3msn
airgead	airgead	airgead-N	Ncmsc
a	a	a-U	U
fháil	fháil	faigh-N	Nv
ón	ón	ó-S	Spa-s
leipreachán	leipreachán	leipreachán-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
airgead	airgead	airgead-N	Ncmsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
leipreachán	leipreachán	leipreachán-N	Ncmsc
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
,	,	,-F	Fi
chuir	chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
mbosca	mbosca	bosca-N	Ncmsc
é	é	é-P	Pp3ms
go ceann	go ceann	go_ceann-S	Spc
seacht	seacht	seacht-M	Mc
mbliana	mbliana	bliain-N	Ncfpc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
seacht	seacht	seacht-M	Mc
mbliana	mbliana	bliain-N	Ncfpc
sa	sa	i-S	Spa-s
mbosca	mbosca	bosca-N	Ncmsc
bhí	bhí	bí-V	Vmis
mo	mo	mo-D	Dp1-s
sheanathair	sheanathair	seanathair-N	Ncmsc
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
cois	cois	cois-S	Sp
na	na	na-T	Tdfsg
farraige	farraige	farraige-N	Ncfsg
lá	lá	lá-N	Ncmsc
,	,	,-F	Fi
agus	agus	agus-C	Cc
chonaic	chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
píosa	píosa	píosa-N	Ncmsc
mór	mór	mór-A	Aqmsc
adhmaid	adhmaid	adhmad-N	Ncmsg
ar	ar	ar-S	Sp
an	an	an-T	Td-s
trá	trá	trá-N	Ncfsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
sé	sé	sé-P	Pp3msn
abhaile	abhaile	abhaile-R	Rd
d'inis	d'inis	inis-V	Vmis
sé	sé	sé-P	Pp3msn
do	do	do-S	Sp
mhuintir	mhuintir	muintir-N	Ncfsc
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
go	go	go-Q	Q
bhfaca	bhfaca	feic-V	Vmis---d
sé	sé	sé-P	Pp3msn
píosa	píosa	píosa-N	Ncmsc
mór	mór	mór-A	Aqmsc
adhmaid	adhmaid	adhmad-N	Ncmsg
ar	ar	ar-S	Sp
an	an	an-T	Td-s
trá	trá	trá-N	Ncfsc
agus	agus	agus-C	Cc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
ró-throm	ró-throm	trom-A	Aqp
le	le	le-S	Sp
tabhairt	tabhairt	tabhair-N	Nv
abhaile	abhaile	abhaile-R	Rd
agus	agus	agus-C	Cc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
faitíos	faitíos	faitíos-N	Ncmsc
air	air	ar-P	Pr3ms
go	go	go-Q	Q
dtabharfadh	dtabharfadh	tabhair-V	Vmc
an	an	an-T	Td-s
taoille	taoille	taoille-N	Ncfsc
amach	amach	amach-R	Rd
é	é	é-P	Pp3ms
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
an	an	an-T	Td-s
leipreachán	leipreachán	leipreachán-N	Ncmsc
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
mar	mar	mar-S	Sp
sin	sin	sin-P	Pd
thosaigh	thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
gáire	gáire	gáir-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
iontas	iontas	iontas-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhfear	bhfear	fear-N	Ncmsc
an	an	an-T	Td-s
leipreachán	leipreachán	leipreachán-N	Ncmsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
gáire	gáire	gáir-N	Nv
mar	mar	mar-S	Sp
sin	sin	sin-P	Pd
ach	ach	ach-C	Cs
níor	níor	níor-Q	Qn-s
bhac	bhac	bac-V	Vmis---n
sé	sé	sé-P	Pp3msn
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
muintir	muintir	muintir-N	Ncfsc
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
ag	ag	ag-S	Sp
ithe	ithe	ith-N	Nv
a	a	a-D	Dp3-p
ndinnéir	ndinnéir	dinnéar-N	Ncmpc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
fear	fear	fear-N	Ncmsc
siúil	siúil	siúl-N	Nv
isteach	isteach	isteach-R	Rd
.	.	.-F	Fe
Diarr	d'iarr	iarr-V	Vmis
mo	mo	mo-D	Dp1-s
sheanathair	sheanathair	seanathair-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhfear	bhfear	fear-N	Ncmsc
siúil	siúil	siúl-N	Nv
suí	suí	suigh-N	Nv
isteach	isteach	isteach-R	Rd
ag	ag	ag-S	Sp
ithe	ithe	ith-N	Nv
.	.	.-F	Fe
'	'	'-F	Fa
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
maith	maith	maith-N	Ncfsc
agat	agat	ag-P	Pr2-s
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
siúil	siúil	siúl-N	Ncmsg
,	,	,-F	Fi
'	'	'-F	Fa
Níl	Níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
ocras	ocras	ocras-N	Ncmsc
orm	orm	ar-P	Pr1-s
'	'	'-F	Fa
.	.	.-F	Fe
Mí	Mí	Mí-N	Npfsc
ón	ón	ó-S	Spa-s
lá	lá	lá-N	Ncmsc
sin	sin	sin-D	Dd
chuaigh	chuaigh	téigh-V	Vmis
mo	mo	mo-D	Dp1-s
sheanathair	sheanathair	seanathair-N	Ncmsc
ar	ar	ar-S	Sp
aonach	aonach	aonach-N	Ncmsc
agus	agus	agus-C	Cc
casadh	casadh	cas-N	Nv
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
siúil	siúil	siúl-N	Ncmsg
dó	dó	do-P	Pr3ms
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosach-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
siúil	siúil	siúl-N	Ncmsg
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
leis	leis	le-P	Pr3ms
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bpíosa	bpíosa	píosa-N	Ncmsc
adhmaid	adhmaid	adhmad-N	Ncmsg
a	a	a-Q	Q-r
casadh	casadh	cas-V	Vmis0
sa	sa	i-S	Spa-s
trá	trá	trá-N	Ncfsc
leis	leis	le-P	Pr3ms
mí	mí	mí-N	Ncfsc
ó	ó	ó-S	Sp
shin	shin	sin-P	Pd
.	.	.-F	Fe
Dúirt	Dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
leis	leis	le-P	Pr3ms
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
píosa	píosa	píosa-N	Ncmsc
adhmaid	adhmaid	adhmad-N	Ncmsg
sin	sin	sin-D	Dd
lán	lán	lán-N	Ncmsc
le	le	le-S	Sp
airgead	airgead	airgead-N	Ncmsc
istigh	istigh	istigh-R	Rl
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Chomh	Chomh	chomh-R	Ri
luath	luath	luath-A	Aqp
is	is	agus-C	Cc
a	a	a-Q	Q-i
chuaigh	chuaigh	téigh-V	Vmis
mo	mo	mo-D	Dp1-s
sheanathair	sheanathair	seanathair-N	Ncmsc
abhaile	abhaile	abhaile-R	Rd
chuaigh	chuaigh	téigh-V	Vmis
sé	sé	sé-P	Pp3msn
síos	síos	síos-R	Rd
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
fharraige	fharraige	farraige-N	Ncfsc
agus	agus	agus-C	Cc
fuair	fuair	faigh-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
píosa	píosa	píosa-N	Ncmsc
adhmaid	adhmaid	adhmad-N	Ncmsg
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
lán	lán	lán-A	Aqp
le	le	le-S	Sp
airgead	airgead	airgead-N	Ncmsc
istigh	istigh	istigh-R	Rl
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Scaoil	Scaoil	scaoil-V	Vmis
sé	sé	sé-P	Pp3msn
amach	amach	amach-R	Rd
an	an	an-T	Td-s
t-éan	t-éan	éan-N	Ncmsc
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
saibhir	saibhir	saibhir-A	Aqp
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
.	.	.-F	Fe
