Lá	Lá	lá-N	Ncmsc
amháin	amháin	amháin-A	Aqp
bhí	bhí	bí-V	Vmis
Sicín	Sicín	sicín-N	Npmsc
Licín	Licín	licín-N	Npfsc
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
abhaile	abhaile	abhaile-R	Rd
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
thit	thit	tit-V	Vmis
cnó	cnó	cnó-N	Ncmsc
ar	ar	ar-S	Sp
a	a	a-P	P-3fs
ceann	ceann	ceann-N	Ncmsc
.	.	.-F	Fe
A	A	an-T	Td-s
thiarcais	thiarcais	tiarcais-N	Ns-s
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
spéir	spéir	spéir-N	Ncfsc
ag	ag	ag-S	Sp
titim	titim	tit-N	Nv
!	!	!-F	Fe
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
insint	insint	insint-N	Nv
don	don	do-S	Spa-s
Uachtarán	Uachtarán	uachtarán-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Ar	Ar	ar-S	Sp
aghaidh	aghaidh	aghaidh-N	Ncfsc
léi	léi	le-P	Pr3fs
go	go	go-S	Sp
hÁras	hÁras	áras-N	Ncmsc
an	an	an-T	Td-s
Uachtaráin	Uachtaráin	uachtarán-N	Ncmsg
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
an	an	an-T	Td-s
mbealach	mbealach	bealach-N	Ncmsc
bhuail	bhuail	buail-V	Vmis
sí	sí	sí-P	Pp3fsn
le	le	le-S	Sp
Lacha	Lacha	lacha-N	Npfsc
Macha	Macha	Macha-N	Npmsc
.	.	.-F	Fe
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
?	?	?-F	Fq
a	a	a-Q	Q-r
d'fhiafraigh	d'fhiafraigh	fiafraigh-V	Vmis
Lacha	Lacha	lacha-N	Npfsc
Macha	Macha	Macha-N	Npmsc
di	di	do-P	Pr3fs
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
spéir	spéir	spéir-N	Ncfsc
ag	ag	ag-S	Sp
titim	titim	tit-N	Nv
!	!	!-F	Fe
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
insint	insint	insint-N	Nv
don	don	do-S	Spa-s
Uachtarán	Uachtarán	uachtarán-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Rachaidh	Rachaidh	téigh-V	Vmif
mé	mé	mé-P	Pp1-s
leat	leat	le-P	Pr2-s
,	,	,-F	Fi
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
Lacha	Lacha	lacha-N	Npfsc
Macha	Macha	Macha-N	Npmsc
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
aghaidh	aghaidh	aghaidh-N	Ncfsc
le	le	le-S	Sp
Sicín	Sicín	sicín-N	Npmsc
Licín	Licín	licín-N	Npfsg
agus	agus	agus-C	Cc
Lacha	Lacha	lacha-N	Npfsc
Macha	Macha	Macha-N	Npmsc
go	go	go-S	Sp
hÁras	hÁras	áras-N	Ncmsc
an	an	an-T	Td-s
Uachtaráin	Uachtaráin	uachtarán-N	Ncmsg
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
an	an	an-T	Td-s
mbealach	mbealach	bealach-N	Ncmsc
bhuail	bhuail	buail-V	Vmis
siad	siad	siad-P	Pp3-pn
le	le	le-S	Sp
Turcaí	Turcaí	Turcaí-N	Npmsc
Lurcaí	Lurcaí	Lurcaí-N	Npmsc
.	.	.-F	Fe
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
sibh	sibh	sibh-P	Pp2-p
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
?	?	?-F	Fq
a	a	a-Q	Q-r
d'fhiafraigh	d'fhiafraigh	fiafraigh-V	Vmis
Turcaí	Turcaí	Turcaí-N	Npmsc
Lurcaí	Lurcaí	Lurcaí-N	Npmsc
di	di	do-P	Pr3fs
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
spéir	spéir	spéir-N	Ncfsc
ag	ag	ag-S	Sp
titim	titim	tit-N	Nv
!	!	!-F	Fe
Caithfimid	Caithfimid	caith-V	Vmif1p
insint	insint	insint-N	Nv
don	don	do-S	Spa-s
Uachtarán	Uachtarán	uachtarán-N	Ncmsc
'	'	'-F	Fa
,	,	,-F	Fi
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
siad	siad	siad-P	Pp3-pn
.	.	.-F	Fe
Rachaidh	Rachaidh	téigh-V	Vmif
mé	mé	mé-P	Pp1-s
libh	libh	le-P	Pr2-p
,	,	,-F	Fi
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
Turcaí	Turcaí	Turcaí-N	Npmsc
Lurcaí	Lurcaí	Lurcaí-N	Npmsc
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
aghaidh	aghaidh	aghaidh-N	Ncfsc
le	le	le-S	Sp
Sicín	Sicín	sicín-N	Npmsc
Licín	Licín	licín-N	Npfsg
,	,	,-F	Fi
Lacha	Lacha	lacha-N	Npfsc
Macha	Macha	Macha-N	Npmsc
agus	agus	agus-C	Cc
Turcaí	Turcaí	Turcaí-N	Npmsc
Lurcaí	Lurcaí	Lurcaí-N	Npmsc
go	go	go-S	Sp
hÁras	hÁras	áras-N	Ncmsc
an	an	an-T	Td-s
Uachtaráin	Uachtaráin	uachtarán-N	Ncmsg
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
an	an	an-T	Td-s
mbealach	mbealach	bealach-N	Ncmsc
bhuail	bhuail	buail-V	Vmis
siad	siad	siad-P	Pp3-pn
le	le	le-S	Sp
Gé	Gé	gé-N	Npfsc
Huiré	Huiré	Huiré-N	Npmsc
.	.	.-F	Fe
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
sibh	sibh	sibh-P	Pp2-p
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
?	?	?-F	Fq
a	a	a-Q	Q-r
d'fhiafraigh	d'fhiafraigh	fiafraigh-V	Vmis
Gé	Gé	gé-N	Npfsc
Huiré	Huiré	Huiré-N	Npmsc
di	di	do-P	Pr3fs
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
spéir	spéir	spéir-N	Ncfsc
ag	ag	ag-S	Sp
titim	titim	tit-N	Nv
!	!	!-F	Fe
Caithfimid	Caithfimid	caith-V	Vmif1p
insint	insint	insint-N	Nv
don	don	do-S	Spa-s
Uachtarán	Uachtarán	uachtarán-N	Ncmsc
'	'	'-F	Fa
,	,	,-F	Fi
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
siad	siad	siad-P	Pp3-pn
.	.	.-F	Fe
Rachaidh	Rachaidh	téigh-V	Vmif
mé	mé	mé-P	Pp1-s
libh	libh	le-P	Pr2-p
,	,	,-F	Fi
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
Gé	Gé	gé-N	Npfsc
Huiré	Huiré	Huiré-N	Npmsc
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
aghaidh	aghaidh	aghaidh-N	Ncfsc
le	le	le-S	Sp
Sicín	Sicín	sicín-N	Npmsc
Licín	Licín	licín-N	Npfsg
,	,	,-F	Fi
Lacha	Lacha	lacha-N	Npfsc
Macha	Macha	Macha-N	Npmsc
,	,	,-F	Fi
Turcaí	Turcaí	Turcaí-N	Npmsc
Lurcaí	Lurcaí	Lurcaí-N	Npmsc
agus	agus	agus-C	Cc
Gé	Gé	gé-N	Npfsc
Huiré	Huiré	Huiré-N	Npmsc
go	go	go-S	Sp
hÁras	hÁras	áras-N	Ncmsc
an	an	an-T	Td-s
Uachtaráin	Uachtaráin	uachtarán-N	Ncmsg
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
an	an	an-T	Td-s
mbealach	mbealach	bealach-N	Ncmsc
bhuail	bhuail	buail-V	Vmis
siad	siad	siad-P	Pp3-pn
le	le	le-S	Sp
Sionnach	Sionnach	sionnach-N	Npmsc
Gliondrach	Gliondrach	gliondrach-N	Npmsc
.	.	.-F	Fe
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
sibh	sibh	sibh-P	Pp2-p
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
?	?	?-F	Fq
a	a	a-Q	Q-r
d'fhiafraigh	d'fhiafraigh	fiafraigh-V	Vmis
Sionnach	Sionnach	sionnach-N	Npmsc
Gliondrach	Gliondrach	gliondrach-N	Npmsc
di	di	do-P	Pr3fs
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
spéir	spéir	spéir-N	Ncfsc
ag	ag	ag-S	Sp
titim	titim	tit-N	Nv
!	!	!-F	Fe
Caithfimid	Caithfimid	caith-V	Vmif1p
insint	insint	insint-N	Nv
don	don	do-S	Spa-s
Uachtarán	Uachtarán	uachtarán-N	Ncmsc
'	'	'-F	Fa
,	,	,-F	Fi
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
siad	siad	siad-P	Pp3-pn
.	.	.-F	Fe
'	'	'-F	Fa
Lean	Lean	Lean-V	Vmms2s
mise	mise	mé-P	Pp1-s-e
,	,	,-F	Fi
tá	tá	bí-V	Vmip
an	an	an-T	Td-s
bealach	bealach	bealach-N	Ncmsc
ar	ar	ar-S	Sp
eolas	eolas	eolas-N	Ncmsc
agam	agam	ag-P	Pr1-s
'	'	'-F	Fa
,	,	,-F	Fi
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
Sionnach	Sionnach	sionnach-N	Npmsc
Gliondrach	Gliondrach	gliondrach-N	Npmsc
.	.	.-F	Fe
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
maith	maith	maith-N	Ncfsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
siad	siad	siad-P	Pp3-pn
agus	agus	agus-C	Cc
lean	lean	lean-V	Vmis
siad	siad	siad-P	Pp3-pn
an	an	an-T	Td-s
sionnach	sionnach	sionnach-N	Ncmsc
.	.	.-F	Fe
Thóg	Thóg	tóg-V	Vmis
sé	sé	sé-P	Pp3msn
iad	iad	iad-P	Pp3-p
go dtí	go dtí	go_dtí-S	Spc
a	a	a-P	P-3ms
phluais	phluais	pluais-N	Ncfsc
féin	féin	féin-P	Px
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
béile	béile	béile-N	Ncmsc
iontach	iontach	iontach-A	Aq-msc
ag	ag	ag-S	Sp
a	a	a-P	P-3ms
chlann	chlann	clann-N	Ncfsc
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
sin	sin	sin-D	Dd
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
dheachaigh	dheachaigh	téigh-V	Vmis---n
Sicín	Sicín	sicín-N	Npmsc
Licín	Licín	licín-N	Npfsc
,	,	,-F	Fi
Lacha	Lacha	lacha-N	Npfsc
Macha	Macha	Macha-N	Npmsc
,	,	,-F	Fi
Turcaí	Turcaí	Turcaí-N	Npmsc
Lurcaí	Lurcaí	Lurcaí-N	Npmsc
ná	ná	ná-C	Cc
Gé	Gé	gé-N	Npfsc
Huiré	Huiré	Huiré-N	Npmsc
go	go	go-S	Sp
hÁras	hÁras	áras-N	Ncmsc
an	an	an-T	Td-s
Uachtaráin	Uachtaráin	uachtarán-N	Ncmsg
,	,	,-F	Fi
ach	ach	ach-C	Cs
níor	níor	níor-Q	Qn-s
thit	thit	tit-V	Vmis---n
an	an	an-T	Td-s
spéir	spéir	spéir-N	Ncfsc
ach	ach	ach-S	Sp
oiread	oiread	oiread-N	Ns-s
.	.	.-F	Fe
