Seo	Seo	seo-W	W
scéal	scéal	scéal-N	Ncmsc
faoi	faoi	faoi-S	Sp
Hansel	Hansel	Hansel-N	Npmsc
agus	agus	agus-C	Cc
Gretel	Gretel	Gretel-N	Npfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
sa	sa	i-S	Spa-s
choill	choill	coill-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
ocras	ocras	ocras-N	Ncmsc
orthu	orthu	ar-P	Pr3-p
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
bhia	bhia	bia-N	Ncmsc
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
siad	siad	siad-P	Pp3-pn
go dtí	go dtí	go_dtí-S	Spc
teach	teach	teach-N	Ncmsc
beag	beag	beag-A	Aq-msc
deas	deas	deas-A	Aq-msc
.	.	.-F	Fe
'	'	'-F	Fa
Ó	Ó	ó-C	Cs
féach	féach	féach-V	Vmm-2s
,	,	,-F	Fi
tá	tá	bí-V	Vmip
milseáin	milseáin	milseán-N	Ncmpc
agus	agus	agus-C	Cc
seacláid	seacláid	seacláid-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
teach	teach	teach-N	Ncmsc
'	'	'-F	Fa
,	,	,-F	Fi
arsa	arsa	arsa-V	Vmis
Gretel	Gretel	Gretel-N	Npfsc
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
cailleach	cailleach	cailleach-N	Ncfsc
amach	amach	amach-R	Rd
.	.	.-F	Fe
'	'	'-F	Fa
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
ocras	ocras	ocras-N	Ncmsc
oraibh	oraibh	ar-P	Pr2-p
,	,	,-F	Fi
a	a	a-U	Uv
pháistí	pháistí	páiste-N	Ncmpv
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
chailleach	chailleach	cailleach-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
an-ocras	an-ocras	ocras-N	Ncmsc
orainn	orainn	ar-P	Pr1-p
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
.	.	.-F	Fe
'	'	'-F	Fa
Féach	Féach	féach-V	Vmm-2s
,	,	,-F	Fi
tá	tá	bí-V	Vmip
milseáin	milseáin	milseán-N	Ncmpc
,	,	,-F	Fi
seacláid	seacláid	seacláid-N	Ncfsc
,	,	,-F	Fi
subh	subh	subh-N	Ncfsc
,	,	,-F	Fi
cácaí	cácaí	cáca-N	Ncmpc
agus	agus	agus-C	Cc
úlla	úlla	úll-N	Ncmpc
agamsa	agamsa	ag-P	Pr1-s-e
sa	sa	i-S	Spa-s
teach	teach	teach-N	Ncmsc
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
chailleach	chailleach	cailleach-N	Ncfsc
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
teach	teach	teach-N	Ncmsc
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
siad	siad	siad-P	Pp3-pn
a lán	a lán	a_lán-N	Ns-s
bianna	bianna	bia-N	Ncmpc
.	.	.-F	Fe
Go	Go	go-U	Ua
tobann	tobann	tobann-A	Aqp
,	,	,-F	Fi
rug	rug	beir-V	Vmis
an	an	an-T	Td-s
chailleach	chailleach	cailleach-N	Ncfsc
ar	ar	ar-S	Sp
Hansel	Hansel	Hansel-N	Npmsc
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
sí	sí	sí-P	Pp3fsn
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
gcás	gcás	cás-N	Ncmsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Rith	Rith	rith-V	Vmis
Gretel	Gretel	Gretel-N	Npfsc
amach	amach	amach-R	Rd
ach	ach	ach-C	Cs
ní	ní	ní-Q	Qn
dheachaigh	dheachaigh	téigh-V	Vmis---n
sí	sí	sí-P	Pp3fsn
abhaile	abhaile	abhaile-R	Rd
.	.	.-F	Fe
Lá	Lá	lá-N	Ncmsc
amháin	amháin	amháin-A	Aqp
tháinig	tháinig	tar-V	Vmis
an	an	an-T	Td-s
chailleach	chailleach	cailleach-N	Ncfsc
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
cás	cás	cás-N	Ncmsc
.	.	.-F	Fe
Dúirt	Dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
,	,	,-F	Fi
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
ocras	ocras	ocras-N	Ncmsc
orm	orm	ar-P	Pr1-s
,	,	,-F	Fi
tabhair	tabhair	tabhair-V	Vmm-2s
dom	dom	do-P	Pr1-s
do	do	do-S	Sp
méar	méar	méar-N	Ncfsc
'	'	'-F	Fa
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
níor	níor	níor-Q	Qn-s
thug	thug	tabhair-V	Vmis---n
Hansel	Hansel	Hansel-N	Npmsc
a	a	a-P	P-3ms
mhéar	mhéar	méar-N	Ncfsc
di	di	do-P	Pr3fs
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
sé	sé	sé-P	Pp3msn
cnámh	cnámh	cnámh-N	Ncfsc
sicín	sicín	sicín-N	Ncmsc
di	di	do-P	Pr3fs
.	.	.-F	Fe
Dúirt	Dúirt	abair-V	Vmis
an	an	an-T	Td-s
chailleach	chailleach	cailleach-N	Ncfsc
,	,	,-F	Fi
'	'	'-F	Fa
Níl	Níl	bí-V	Vmip---n
tú	tú	tú-P	Pp2-s
ramhar	ramhar	ramhar-A	Aqp
go leor	go leor	go_leor-A	Aq
,	,	,-F	Fi
tá	tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
róthanaí	róthanaí	tanaí-A	Aqp
'	'	'-F	Fa
,	,	,-F	Fi
agus	agus	agus-C	Cc
d'fhág	d'fhág	fág-V	Vmis
sí	sí	sí-P	Pp3fsn
Hansel	Hansel	Hansel-N	Npmsc
sa	sa	i-S	Spa-s
chás	chás	cás-N	Ncmsc
.	.	.-F	Fe
Lá	Lá	lá-N	Ncmsc
eile	eile	eile-D	Dd
bhí	bhí	bí-V	Vmis
ocras	ocras	ocras-N	Ncmsc
an	an	an-T	Td-s
domhain	domhain	domhan-N	Ncmsg
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcailleach	gcailleach	cailleach-N	Ncfsc
.	.	.-F	Fe
Dúirt	Dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
,	,	,-F	Fi
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
ocras	ocras	ocras-N	Ncmsc
an	an	an-T	Td-s
domhain	domhain	domhan-N	Ncmsg
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
Íosfaidh	Íosfaidh	ith-V	Vmif
mé	mé	mé-P	Pp1-s
Hansel	Hansel	Hansel-N	Npmsc
inniu	inniu	inniu-R	Rt
'	'	'-F	Fa
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
thall	thall	thall-R	Rd
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
tine	tine	tine-N	Ncfsc
sa	sa	i-S	Spa-s
chistin	chistin	cistin-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Gretel	Gretel	Gretel-N	Npfsc
i	i	i-S	Sp
bhfolach	bhfolach	folach-N	Ncmsc
sa	sa	i-S	Spa-s
chistin	chistin	cistin-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
féachaint	féachaint	féach-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcailleach	gcailleach	cailleach-N	Ncfsc
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
éisteacht	éisteacht	éist-N	Nv
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Go	Go	go-U	Ua
tobann	tobann	tobann-A	Aqp
thug	thug	tabhair-V	Vmis
Gretel	Gretel	Gretel-N	Npfsc
cic	cic	cic-N	Ncmsc
mór	mór	mór-A	Aq-msc
don	don	do-S	Spa-s
chailleach	chailleach	cailleach-N	Ncfsc
agus	agus	agus-C	Cc
thit	thit	tit-V	Vmis
an	an	an-T	Td-s
chailleach	chailleach	cailleach-N	Ncfsc
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
tine	tine	tine-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
chailleach	chailleach	cailleach-N	Ncfsc
marbh	marbh	marbh-A	Aqp
.	.	.-F	Fe
D'oscail	D'oscail	oscail-V	Vmis
Gretel	Gretel	Gretel-N	Npfsc
an	an	an-T	Td-s
cás	cás	cás-N	Ncmsc
.	.	.-F	Fe
Amach	Amach	amach-R	Rd
le	le	le-S	Sp
Hansel	Hansel	Hansel-N	Npmsc
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
acu	acu	ag-P	Pr3-p
abhaile	abhaile	abhaile-R	Rd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
milseáin	milseáin	milseán-N	Ncmpc
agus	agus	agus-C	Cc
úlla	úlla	úll-N	Ncmpc
acu	acu	ag-P	Pr3-p
sa	sa	i-S	Spa-s
bhaile	bhaile	baile-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
áthas	áthas	áthas-N	Ncmsc
orthu	orthu	ar-P	Pr3-p
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
bia	bia	bia-N	Ncmsc
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
áthas	áthas	áthas-N	Ncmsc
orthu	orthu	ar-P	Pr3-p
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
Hansel	Hansel	Hansel-N	Npmsc
beo	beo	beo-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
áthas	áthas	áthas-N	Ncmsc
orthu	orthu	ar-P	Pr3-p
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
chailleach	chailleach	cailleach-N	Ncfsc
marbh	marbh	marbh-A	Aqp
.	.	.-F	Fe
