Rith	Rith	rith-V	Vmis
Cáit	Cáit	Cáit-N	Npfsc
amach	amach	amach-R	Rd
as	as	as-S	Sp
an	an	an-T	Td-s
naíonra	naíonra	naíonr-N	Ncmpc
.	.	.-F	Fe
An	An	is-W	Wp-q
maith	maith	maith-A	Aqp
leat	leat	le-P	Pr2-s
mo	mo	mo-D	Dp1-s
chaisleán	chaisleán	caisleán-N	Ncmsc
,	,	,-F	Fi
a	a	a-U	Uv
Dhaid	Dhaid	Daid-N	Npm-v
?	?	?-F	Fq
Ó	Ó	Ó-I	I
,	,	,-F	Fi
nach	nach	is-W	Wpsin|Wpdin
deas	deas	deas-A	Aqp
é	é	é-P	Pp3ms
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
Cáit	Cáit	Cáit-N	Npfsc
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
chistin	chistin	cistin-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Mam	Mam	mam-N	Ncfsc
ann	ann	i-R	Rl|Pr3ms
roimpi	roimpi	roimh-P	Pr3fs
.	.	.-F	Fe
Ó	Ó	Ó-I	I
,	,	,-F	Fi
nach	nach	is-W	Wpsin|Wpdin
deas	deas	deas-A	Aqp
é	é	é-P	Pp3ms
.	.	.-F	Fe
An	An	is-W	Wp-q
maith	maith	maith-A	Aqp
leat	leat	le-P	Pr2-s
mo	mo	mo-D	Dp1-s
chaisleán	chaisleán	caisleán-N	Ncmsc
,	,	,-F	Fi
a	a	a-U	Uv
Mham	Mham	mam-N	Ncfsv
?	?	?-F	Fq
Chuir	Chuir	cuir-V	Vmis
Mam	Mam	mam-N	Ncfsc
an	an	an-T	Td-s
caisleán	caisleán	caisleán-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
urlár	urlár	urlár-N	Ncmsc
.	.	.-F	Fe
Yipí	Yipí	Yipí-X	Xf
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
Róisín	Róisín	Róisín-N	Npfsc
agus	agus	agus-C	Cc
Sciob	Sciob	sciob-V	Vmm-2s
anseo	anseo	anseo-R	Rl
!	!	!-F	Fe
Amach	Amach	amach-R	Rd
le	le	le-S	Sp
Cáit	Cáit	Cáit-N	Npfsc
sa	sa	i-S	Spa-s
ghairdín	ghairdín	gairdín-N	Ncmsc
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
le	le	le-S	Sp
Liam	Liam	Liam-N	Npmsc
agus	agus	agus-C	Cc
le	le	le-S	Sp
hEoin	hEoin	hEoin-N	Nc
.	.	.-F	Fe
Ó	Ó	Ó-I	I
!	!	!-F	Fe
Cé	Cé	cé-W	W--q
leis	leis	le-S	Sp
an	an	an-T	Td-s
caisleán	caisleán	caisleán-N	Ncmsc
seo	seo	seo-D	Dd
?	?	?-F	Fq
Is	Is	is-W	Wp-i
le	le	le-S	Sp
Cáit	Cáit	Cáit-N	Npfsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Ó	Ó	Ó-I	I
,	,	,-F	Fi
nach	nach	is-W	Wpsin|Wpdin
deas	deas	deas-A	Aqp
é	é	é-P	Pp3ms
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
le	le	le-S	Sp
Sciob	Sciob	sciob-V	Vmis
.	.	.-F	Fe
Nach	Nach	is-W	Wpsin
deas	deas	deas-A	Aqp
an	an	an-T	Td-s
caisleán	caisleán	caisleán-N	Ncmsc
é	é	é-P	Pp3ms
sin	sin	sin-W	W
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfaca	bhfaca	feic-V	Vmis---d
tú	tú	tú-P	Pp2-s
mo	mo	mo-D	Dp1-s
chaisleán	chaisleán	caisleán-N	Ncmsc
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cáit	Cáit	Cáit-N	Npfsc
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
mé	mé	mé-P	Pp1-s
sa	sa	i-S	Spa-s
halla	halla	halla-N	Ncmsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
mé	mé	mé-P	Pp1-s
sa	sa	i-S	Spa-s
seomra	seomra	seomra-N	Ncmsc
suite	suite	suigh-A	Aqp|Av
é	é	é-P	Pp3ms
.	.	.-F	Fe
Níl	Níl	bí-V	Vmip---n
sé	sé	sé-P	Pp3msn
anseo	anseo	anseo-R	Rl
.	.	.-F	Fe
An	An	an-Q	Qq
bhfaca	bhfaca	feic-V	Vmis---d
tusa	tusa	tú-P	Pp2-s-e
é	é	é-P	Pp3ms
,	,	,-F	Fi
a	a	a-U	Uv
Eoin	Eoin	Eoin-N	Npm-v
?	?	?-F	Fq
Níl	Níl	bí-V	Vmip---n
sé	sé	sé-P	Pp3msn
anseo	anseo	anseo-R	Rl
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
mo	mo	mo-D	Dp1-s
chaisleán	chaisleán	caisleán-N	Ncmsc
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cáit	Cáit	Cáit-N	Npfsc
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
le	le	le-S	Sp
Cáit	Cáit	Cáit-N	Npfsc
sa	sa	i-S	Spa-s
chistin	chistin	cistin-N	Ncfsc
.	.	.-F	Fe
Ó	Ó	Ó-I	I
,	,	,-F	Fi
mo	mo	mo-D	Dp1-s
chaisleán	chaisleán	caisleán-N	Ncmsc
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
súile	súile	súil-N	Ncfpc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
tá	tá	bí-V	Vmip
cosa	cosa	cos-N	Ncfpc
faoi	faoi	faoi-P	Pr3ms
.	.	.-F	Fe
Is	Is	is-W	Wp-i
é	é	é-P	Pp3ms
Sciob	Sciob	sciob-V	Vmis
atá	atá	bí-V	Vmip---r
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Tar	Tar	thar-S	Sp
anseo	anseo	anseo-R	Rl
,	,	,-F	Fi
a	a	a-Q	Q-r
Sciob	Sciob	sciob-V	Vmis
!	!	!-F	Fe
Bhuf	Bhuf	Bhuf-N	Npmsc
!	!	!-F	Fe
Bhuf	Bhuf	Bhuf-N	Npmsc
!	!	!-F	Fe
Amach	Amach	amach-R	Rd
leat	leat	le-P	Pr2-s
!	!	!-F	Fe
Bhuf	Bhuf	Bhuf-N	Npmsc
!	!	!-F	Fe
Bhuf	Bhuf	Bhuf-N	Npmsc
!	!	!-F	Fe
