Lá	Lá	lá-N	Ncmsc
breithe	breithe	beir-N	Ncfsg|Nv--g
Mham	Mham	mam-N	Ncfsc
atá	atá	bí-V	Vmip---r
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
Daid	Daid	Daid-N	Npmsc
,	,	,-F	Fi
Liam	Liam	Liam-N	Npmsc
agus	agus	agus-C	Cc
Eoin	Eoin	Eoin-N	Npm-g|Npmsc
ag	ag	ag-S	Sp
siopadóireacht	siopadóireacht	siopadóir-N	Nv-----n
.	.	.-F	Fe
Cheannaigh	Cheannaigh	ceannaigh-V	Vmis
Eoin	Eoin	Eoin-N	Npmsc
bosca	bosca	bosca-N	Ncmsg|Ncmsc
seacláidí	seacláidí	seacláid-N	Ncfpg|Ncfpc|Ncfpg
do	do	do-S	Sp
Mham	Mham	mam-N	Ncfsc
.	.	.-F	Fe
Seo	Seo	seo-W	W
leabhar	leabhar	leabhar-N	Ncmsc
deas	deas	deas-A	Aq-msc
.	.	.-F	Fe
Cheannaigh	Cheannaigh	ceannaigh-V	Vmis
Liam	Liam	Liam-N	Npmsc
leabhar	leabhar	leabhar-N	Ncmsc
di	di	do-P	Pr3fs
.	.	.-F	Fe
Cheannaigh	Cheannaigh	ceannaigh-V	Vmis
Daid	Daid	Daid-N	Npmsc
bláthanna	bláthanna	bláth-N	Ncmpc
di	di	do-P	Pr3fs
.	.	.-F	Fe
Fuair	Fuair	faigh-V	Vmis
mé	mé	mé-P	Pp1-s
bronntanas	bronntanas	bronntanas-N	Ncmsc
duit	duit	do-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Mham	Mham	mam-N	Ncfsv
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
bosca	bosca	bosca-N	Ncmsc
seacláidí	seacláidí	seacláid-N	Ncfpg|Ncfpc
di	di	do-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Mam	Mam	mam-N	Ncfsc
an-sásta	an-sásta	sásta-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
seacláidí	seacláidí	seacláid-N	Ncfpc
deasa	deasa	deas-A	Aq--pv|Aq--pg|Aq--pc
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
maith	maith	maith-N	Ncfsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
stór	stór	stór-N	Ncmsv
.	.	.-F	Fe
Fuair	Fuair	faigh-V	Vmis
mé	mé	mé-P	Pp1-s
bronntanas	bronntanas	bronntanas-N	Ncmsc
duit	duit	do-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Mham	Mham	mam-N	Ncfsv
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
leabhar	leabhar	leabhar-N	Ncmsc
di	di	do-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Mam	Mam	mam-N	Ncfsc
an-sásta	an-sásta	sásta-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
seo	seo	seo-P	Pd
leabhar	leabhar	leabhar-N	Ncmsc
deas	deas	deas-A	Aq-msc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
maith	maith	maith-N	Ncfsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
stór	stór	stór-N	Ncmsv
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
le	le	le-S	Sp
Cáit	Cáit	Cáit-N	Npfsc
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
sí	sí	sí-P	Pp3fsn
cárta	cárta	cárta-N	Ncmsc
do	do	do-S	Sp
Mham	Mham	mam-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
nach	nach	is-C	Cs|Wpdin|Wpsin
deas	deas	deas-N	Ns-s|Aqp
an	an	an-T	Td-s
cárta	cárta	cárta-N	Ncmsg|Ncmsc
é	é	é-P	Pp3ms
,	,	,-F	Fi
a	a	a-U	Uv
stóirín	stóirín	stór-N	Ncmsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mam	Mam	mam-N	Ncfsc
.	.	.-F	Fe
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
míle	míle	míle-M	Mc
maith	maith	maith-N	Ncfsc
agat	agat	ag-P	Pr2-s
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
Daid	Daid	Daid-N	Npmsc
na	na	na-T	Td-p
bláthanna	bláthanna	bláth-N	Ncmpg
do	do	do-S	Sp
Mham	Mham	mam-N	Ncfsc
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
Mam	Mam	mam-N	Ncfsc
póg	póg	póg-N	Ncfsc
do	do	do-S	Sp
Dhaid	Dhaid	Daid-N	Npmsc
.	.	.-F	Fe
