A	A	a-U	Uv
Dhaideo	Dhaideo	daideo-N	Ncmsv
,	,	,-F	Fi
an	an	an-Q	Qq
raibh	raibh	bí-V	Vmis---d
tusa	tusa	tú-P	Pp2-s-e
óg	óg	óg-A	Aqp
uair	uair	uair-N	Ncfsc
amháin	amháin	amháin-A	Aqp
?	?	?-F	Fq
Bhí	Bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
,	,	,-F	Fi
a	a	a-U	Uv
stór	stór	stór-N	Ncmsv
.	.	.-F	Fe
An	An	an-Q	Qq
raibh	raibh	bí-V	Vmis---d
teilifís	teilifís	teilifís-N	Ncfsc
agaibh	agaibh	ag-P	Pr2-p
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
tú	tú	tú-P	Pp2-s
óg	óg	óg-A	Aqp
?	?	?-F	Fq
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
,	,	,-F	Fi
a	a	a-U	Uv
stór	stór	stór-N	Ncmsv
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
d	d	d-X	Xl
’	’	’-F	Fa
inis	inis	inis-V	Vmm-2s
mo	mo	mo-D	Dp1-s
Dhaideo	Dhaideo	daideo-N	Ncmsc
scéalta	scéalta	scéal-N	Ncmpc
deasa	deasa	deas-A	Aq--pc
dom	dom	do-P	Pr1-s
.	.	.-F	Fe
An	An	an-Q	Qq
raibh	raibh	bí-V	Vmis---d
scoil	scoil	scoil-N	Ncfsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
ann	ann	i-P	Pr3ms
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
tusa	tusa	tú-P	Pp2-s-e
óg	óg	óg-A	Aqp
?	?	?-F	Fq
Bhí	Bhí	bí-V	Vmis
,	,	,-F	Fi
a	a	a-U	Uv
stór	stór	stór-N	Ncmsv
.	.	.-F	Fe
Ar	Ar	ar-Q	Qq-s
thug	thug	tabhair-V	Vmis
do	do	do-S	Sp
Mhamaí	Mhamaí	mama-N	Ncfsc|Ncmpc
ar	ar	ar-S	Sp
scoil	scoil	scoil-N	Ncfsc
sa	sa	i-S	Spa-s
charr	charr	carr-N	Ncmsc|Ncfsc
tú	tú	tú-P	Pp2-s
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
tú	tú	tú-P	Pp2-s
óg	óg	óg-A	Aqp
?	?	?-F	Fq
Níor	Níor	níor-Q	Qn-s
thug	thug	tabhair-V	Vmis---n
,	,	,-F	Fi
a	a	a-U	Uv
stór	stór	stór-N	Ncmsv
.	.	.-F	Fe
Ar	Ar	ar-Q	Qq-s
tháinig	tháinig	tar-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
na	na	na-T	Tdfsg
Nollag	Nollag	Nollaig-N	Ncfsg
chugat	chugat	chuig-P	Pr2-s
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
tú	tú	tú-P	Pp2-s
óg	óg	óg-A	Aqp
?	?	?-F	Fq
Ó	Ó	Ó-I	I
,	,	,-F	Fi
tháinig	tháinig	tar-V	Vmis
,	,	,-F	Fi
a	a	a-U	Uv
stór	stór	stór-N	Ncmsv
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
sé	sé	sé-P	Pp3msn
chugam	chugam	chuig-P	Pr1-s
le	le	le-S	Sp
camán	camán	camán-N	Ncmsc
agus	agus	agus-C	Cc
sliotar	sliotar	sliotar-N	Ncmpg|Ncmsc|Ncmpg
.	.	.-F	Fe
An	An	an-Q	Qq
raibh	raibh	bí-V	Vmis---d
tú	tú	tú-P	Pp2-s
sona	sona	sona-A	Aqp
sásta	sásta	sásta-A	Aqp
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
tú	tú	tú-P	Pp2-s
óg	óg	óg-A	Aqp
?	?	?-F	Fq
Bhí	Bhí	bí-V	Vmis
,	,	,-F	Fi
a	a	a-U	Uv
stór	stór	stór-N	Ncmsv
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
tá	tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
níos	níos	níos-U	Uc
sásta	sásta	sásta-A	Aqc
anois	anois	anois-R	Rt
mar	mar	mar-C	Cs
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
tusa	tusa	tú-P	Pp2-s-e
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
a	a	a-U	Uv
stór	stór	stór-N	Ncmsv
.	.	.-F	Fe
