Níl	Níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
bhainne	bhainne	bainne-N	Ncmsc
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Áine	Áine	Áine-N	Npfsc
ag	ag	ag-S	Sp
ithe	ithe	ith-N	Nv
a	a	a-D	Dp3
lóin	lóin	lón-N	Ncmsg
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
bhainne	bhainne	bainne-N	Ncmsc
aici	aici	ag-P	Pr3fs
don	don	do-S	Spa-s
tae	tae	tae-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
dul	dul	téigh-N	Ncmsc|Nv
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
siopa	siopa	siopa-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Áine	Áine	Áine-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
dul	dul	téigh-N	Nv
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
leat	leat	le-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Léiní	Léiní	Léiní-N	Npmsc
le	le	le-S	Sp
hÁine	hÁine	Áine-N	Npf-g
.	.	.-F	Fe
‘	‘	‘-X	Xx
Isteach	Isteach	isteach-R	Rd
leat	leat	le-P	Pr2-s
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
mhála	mhála	mála-N	Ncmsc
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Áine	Áine	Áine-N	Npfsc
.	.	.-F	Fe
Léim	Léim	léim-V	Vmip1s|Vmis
Léiní	Léiní	Léiní-N	Npmsc
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
mála	mála	mála-N	Ncmsc
Áine	Áine	Áine-N	Npf-g
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Léiní	Léiní	Léiní-N	Npmsc
an-sásta	an-sásta	sásta-A	Aqp
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
Táimse	Táimse	bí-V	Vmip1s--e
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
siopa	siopa	siopa-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmm-2s
Áine	Áine	Áine-N	Npfsc
léi	léi	le-P	Pr3fs
síos	síos	síos-R	Rd
an	an	an-T	Td-s
bóthar	bóthar	bóthar-N	Ncmsc
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
siopa	siopa	siopa-N	Ncmsc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Is	Is	is-W	Wp-i
maith	maith	maith-A	Aqp
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
siopa	siopa	siopa-N	Ncmsc
.	.	.-F	Fe
Sháigh	Sháigh	sáigh-V	Vmis
Léiní	Léiní	Léiní-N	Npmsc
amach	amach	amach-R	Rd
a	a	a-D	Dp3
srón	srón	srón-N	Ncfsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
an	an	an-T	Td-s
siopadóir	siopadóir	siopadóir-N	Ncmsc
í	í	í-P	Pp3fs
.	.	.-F	Fe
Sháigh	Sháigh	sáigh-V	Vmis
sí	sí	sí-P	Pp3fsn
amach	amach	amach-R	Rd
a	a	a-D	Dp3
ceann	ceann	ceann-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
an	an	an-T	Td-s
siopadóir	siopadóir	siopadóir-N	Ncmsc
í	í	í-P	Pp3fs
.	.	.-F	Fe
Sháigh	Sháigh	sáigh-V	Vmis
sí	sí	sí-P	Pp3fsn
amach	amach	amach-R	Rd
a	a	a-D	Dp3
lapa	lapa	lapa-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
an	an	an-T	Td-s
siopadóir	siopadóir	siopadóir-N	Ncmsc
í	í	í-P	Pp3fs
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
léim	léim	léim-V	Vmip1s|Vmis
Léiní	Léiní	Léiní-N	Npmsc
amach	amach	amach-R	Rd
as	as	as-S	Sp
an	an	an-T	Td-s
mála	mála	mála-N	Ncmsc
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
sí	sí	sí-P	Pp3fsn
doras	doras	doras-N	Ncmsc
beag	beag	beag-A	Aq-msc
.	.	.-F	Fe
Rith	Rith	rith-V	Vmis
Léiní	Léiní	Léiní-N	Npmsc
chomh	chomh	chomh-R	Ri
fada	fada	fada-A	Aqp
leis	leis	le-S	Sp
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
Sháigh	Sháigh	sáigh-V	Vmis
sí	sí	sí-P	Pp3fsn
isteach	isteach	isteach-R	Rd
a	a	a-D	Dp3
srón	srón	srón-N	Ncfsc
.	.	.-F	Fe
Cé	Cé	cé-P	Pq
atá	atá	bí-V	Vmip---r
istigh	istigh	istigh-R	Rl
ansin	ansin	ansin-R	Rt|Rl
?	?	?-F	Fq
Mise	Mise	mé-P	Pp1-s-e
Séimí	Séimí	Séimí-N	Npmsc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
cé	cé	cé-W	W--q
hé	hé	é-P	Pp3ms
tusa	tusa	tú-P	Pp2-s-e
?	?	?-F	Fq
Mise	Mise	mé-P	Pp1-s-e
Léiní	Léiní	Léiní-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tar	Tar	thar-S	Sp
isteach	isteach	isteach-R	Rd
,	,	,-F	Fi
a	a	a-U	Uv
Léiní	Léiní	Léiní-N	Npmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Séimí	Séimí	Séimí-N	Npmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmm-2s
Léiní	Léiní	Léiní-N	Npmsc
isteach	isteach	isteach-R	Rd
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
le	le	le-S	Sp
Séimí	Séimí	Séimí-N	Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
crandaí	crandaí	crandaí-N	Ncmsc
bogadaí	bogadaí	bogadach-N	Ncfsg
taobh istigh	taobh istigh	taobh_istigh-R	Rl
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
acu	acu	ag-P	Pr3-p
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcrandaí	gcrandaí	crandaí-N	Ncmsc
bogadaí	bogadaí	bogadach-N	Ncfsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
luascán	luascán	luascán-N	Ncmsc
taobh istigh	taobh istigh	taobh_istigh-R	Rl
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
acu	acu	ag-P	Pr3-p
ar	ar	ar-S	Sp
an	an	an-T	Td-s
luascán	luascán	luascán-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sleamhnán	sleamhnán	sleamhnán-N	Ncmsc
taobh istigh	taobh istigh	taobh_istigh-R	Rl
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
acu	acu	ag-P	Pr3-p
‘	‘	‘-X	Xx
Is	Is	is-W	Wpri
maith	maith	maith-A	Aqp
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
áit	áit	áit-N	Ncfsc
seo	seo	seo-D	Dd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Léiní	Léiní	Léiní-N	Npmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ansin	ansin	ansin-R	Rt|Rl
chuala	chuala	clois-V	Vmis
sí	sí	sí-P	Pp3fsn
Áine	Áine	Áine-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	an-T	Td-s
Léiní	Léiní	Léiní-N	Npmsc
,	,	,-F	Fi
cá	cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Áine	Áine	Áine-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
in	in	i-S	Sp
am	am	am-N	Ncmsc
againn	againn	ag-P	Pr1-p
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
abhaile	abhaile	abhaile-R	Rd
.	.	.-F	Fe
’	’	’-F	Fa
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
?	?	?-F	Fq
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
imeacht	imeacht	imigh-N	Nv
anois	anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Léiní	Léiní	Léiní-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Lá	Lá	lá-N	Ncmsc
maith	maith	maith-A	Aq-msc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Shéimí	Shéimí	Séimí-N	Npm-v
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
agat	agat	ag-P	Pr2-s
féin	féin	féin-P	Px
,	,	,-F	Fi
a	a	a-U	Uv
Léiní	Léiní	Léiní-N	Npmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Séimí	Séimí	Séimí-N	Npmsc
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
Léiní	Léiní	Léiní-N	Npmsc
amach	amach	amach-R	Rd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Isteach	Isteach	isteach-R	Rd
anois	anois	anois-R	Rt
leat	leat	le-P	Pr2-s
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
mhála	mhála	mála-N	Ncmsc
,	,	,-F	Fi
a	a	a-U	Uv
Léiní	Léiní	Léiní-N	Npmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Áine	Áine	Áine-N	Npfsc
.	.	.-F	Fe
Fan	Fan	fan-V	Vmm-2s
ansin	ansin	ansin-R	Rt|Rl
anois	anois	anois-R	Rt
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
cara	cara	cara-N	Ncmsc
anois	anois	anois-R	Rt
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Léiní	Léiní	Léiní-N	Npmsc
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
a	a	a-D	Dp3
Liam	Liam	Liam-N	Npmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Eoin	Eoin	Eoin-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Faigh	Faigh	faigh-V	Vmm-2s
do	do	do-S	Sp
shliotar	shliotar	sliotar-N	Ncmsc
agus	agus	agus-C	Cc
beidh	beidh	bí-V	Vmif
cluiche	cluiche	cluiche-N	Ncmsc
iománaíochta	iománaíochta	iománaíocht-N	Ncfsg
againn	againn	ag-P	Pr1-p
.	.	.-F	Fe
’	’	’-F	Fa
