Bhí	Bhí	bí-V	Vmis
gairdín	gairdín	gairdín-N	Ncmsc
nua	nua	nua-A	Aqp
ag	ag	ag-S	Sp
Sciob	Sciob	sciob-V	Vmis
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sé	sé	sé-P	Pp3msn
sásta	sásta	sásta-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
cró	cró	cró-N	Ncmsc
nua	nua	nua-A	Aqp
ag	ag	ag-S	Sp
Sciob	Sciob	sciob-V	Vmis
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sé	sé	sé-P	Pp3msn
sásta	sásta	sásta-A	Aqp
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
maith	maith	maith-A	Aqp
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
gairdín	gairdín	gairdín-N	Ncmsc
nua	nua	nua-A	Aqp
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
maith	maith	maith-A	Aqp
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
cró	cró	cró-N	Ncmsc
nua	nua	nua-A	Aqp
.	.	.-F	Fe
Amach	Amach	amach-R	Rd
as	as	as-S	Sp
an	an	an-T	Td-s
ngairdín	ngairdín	gairdín-N	Ncmsc
le	le	le-S	Sp
Sciob	Sciob	sciob-V	Vmis
.	.	.-F	Fe
Síos	Síos	síos-R	Rd
an	an	an-T	Td-s
bóthar	bóthar	bóthar-N	Ncmsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Rith	Rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
agus	agus	agus-C	Cc
rith	rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
stop	stop	stop-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
mé	mé	mé-P	Pp1-s
?	?	?-F	Fq
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
mé	mé	mé-P	Pp1-s
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Sciob	Sciob	sciob-V	Vmis
.	.	.-F	Fe
Is	Is	is-W	Wp-i
ansin	ansin	ansin-R	Rt|Rl
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
Sciob	Sciob	sciob-V	Vmis
na	na	na-T	Td-p
madraí	madraí	madra-N	Ncmpc
móra	móra	mór-A	Aq--pv|Aq--pg|Aq--pc
.	.	.-F	Fe
Bhuf	Bhuf	Bhuf-N	Npmsc
!	!	!-F	Fe
Bhuf	Bhuf	Bhuf-N	Npmsc
!	!	!-F	Fe
Rith	Rith	rith-N	Ncmsc
Sciob	Sciob	sciob-V	Vmis
.	.	.-F	Fe
Rith	Rith	rith-V	Vmm-2s|Vmis
na	na	na-T	Td-p
madraí	madraí	madra-N	Ncmpc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
.	.	.-F	Fe
Grr-rr-rr	Grr-rr-rr	Grr-rr-rr-N	Nc
!	!	!-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
chonaic	chonaic	feic-V	Vmis
Sciob	Sciob	sciob-V	Vmis
a	a	a-D	Dp3
ghairdín	ghairdín	gairdín-N	Ncmsc
féin	féin	féin-P	Px
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
Deaide	Deaide	Deaide-N	Npmsc
agus	agus	agus-C	Cc
Róisín	Róisín	Róisín-N	Npf-g|Npfsc
sa	sa	i-S	Spa-s
ghairdín	ghairdín	gairdín-N	Ncmsc
.	.	.-F	Fe
Ó	Ó	Ó-I	I
,	,	,-F	Fi
a	a	a-Q	Q-r
Sciob	Sciob	sciob-V	Vmis
!	!	!-F	Fe
Cá	Cá	cá-R	Rq
raibh	raibh	bí-V	Vmis---d
tú	tú	tú-P	Pp2-s
?	?	?-F	Fq
Bhuf	Bhuf	Bhuf-N	Npmsc
!	!	!-F	Fe
Bhuf	Bhuf	Bhuf-N	Npmsc
!	!	!-F	Fe
