Bhí	Bhí	bí-V	Vmis
Áine	Áine	Áine-N	Npfsc
ag	ag	ag-S	Sp
ithe	ithe	ith-N	Nv
a	a	a-D	Dp3
dinnéir	dinnéir	dinnéar-N	Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
mo	mo	mo-D	Dp1-s
rang	rang	rang-N	Ncmsc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
mé	mé	mé-P	Pp1-s
deireanach	deireanach	deireanach-A	Aqp
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
mise	mise	mé-P	Pp1-s-e
riamh	riamh	riamh-R	Rg
ag	ag	ag-S	Sp
rang	rang	rang-N	Ncmsc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Léiní	Léiní	Léiní-N	Npmsc
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
Léim	Léim	léim-V	Vmip1s|Vmis
Léiní	Léiní	Léiní-N	Npmsc
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
gcás	gcás	cás-N	Ncmsc
an	an	an-T	Td-s
veidhlín	veidhlín	veidhlín-N	Ncmsg
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
Áine	Áine	Áine-N	Npfsc
í	í	í-P	Pp3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Léiní	Léiní	Léiní-N	Npmsc
an-sásta	an-sásta	sásta-A	Aqp
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
mise	mise	mé-P	Pp1-s-e
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
rang	rang	rang-N	Ncmsc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmm-2s
Áine	Áine	Áine-N	Npfsc
léi	léi	le-P	Pr3fs
síos	síos	síos-R	Rd
an	an	an-T	Td-s
bóthar	bóthar	bóthar-N	Ncmsc
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
seomra	seomra	seomra-N	Ncmsc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Tharraing	Tharraing	tarraing-V	Vmis
sí	sí	sí-P	Pp3fsn
amach	amach	amach-R	Rd
an	an	an-T	Td-s
veidhlín	veidhlín	veidhlín-N	Ncmsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
tharraing	tharraing	tarraing-V	Vmis
sí	sí	sí-P	Pp3fsn
amach	amach	amach-R	Rd
an	an	an-T	Td-s
bogha	bogha	bogha-N	Ncmsc
agus	agus	agus-C	Cc
sheinn	sheinn	seinn-V	Vmis
sí	sí	sí-P	Pp3fsn
port	port	port-N	Ncmsc
.	.	.-F	Fe
Thaitin	Thaitin	taitin-V	Vmis
an	an	an-T	Td-s
ceol	ceol	ceol-N	Ncmsc
le	le	le-S	Sp
Léiní	Léiní	Léiní-N	Npmsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
maith	maith	maith-A	Aqp
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
port	port	port-N	Ncmsc
sin	sin	sin-D	Dd
.	.	.-F	Fe
Sháigh	Sháigh	sáigh-V	Vmis
sí	sí	sí-P	Pp3fsn
amach	amach	amach-R	Rd
a	a	a-D	Dp3
srón	srón	srón-N	Ncfsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
í	í	í-P	Pp3fs
.	.	.-F	Fe
Sháigh	Sháigh	sáigh-V	Vmis
sí	sí	sí-P	Pp3fsn
amach	amach	amach-R	Rd
a	a	a-D	Dp3
ceann	ceann	ceann-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
í	í	í-P	Pp3fs
.	.	.-F	Fe
Sháigh	Sháigh	sáigh-V	Vmis
sí	sí	sí-P	Pp3fsn
amach	amach	amach-R	Rd
a	a	a-D	Dp3
lapa	lapa	lapa-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
í	í	í-P	Pp3fs
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
léim	léim	léim-V	Vmip1s|Vmis
Léiní	Léiní	Léiní-N	Npmsc
amach	amach	amach-R	Rd
as	as	as-S	Sp
cás	cás	cás-N	Ncmsc
an	an	an-T	Td-s
veidhlín	veidhlín	veidhlín-N	Ncmsg
.	.	.-F	Fe
Suas	Suas	suas-R	Rd
le	le	le-S	Sp
Léiní	Léiní	Léiní-N	Npmsc
ar	ar	ar-S	Sp
bharr	bharr	barr-N	Ncmsc
an	an	an-T	Td-s
phianó	phianó	pianó-N	Ncmsg
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
rince	rince	rinc-N	Nv
.	.	.-F	Fe
A	A	a-U	Um
haon	haon	aon-M	Mc
,	,	,-F	Fi
a	a	a-U	Um
dó	dó	dó-M	Mc
,	,	,-F	Fi
a	a	a-U	Um
trí	trí	trí-M	Mc
,	,	,-F	Fi
is	is	is-W	Wp-i
a	a	a-U	Um
haon	haon	aon-M	Mc
,	,	,-F	Fi
a	a	a-U	Um
dó	dó	dó-M	Mc
,	,	,-F	Fi
a	a	a-U	Um
trí	trí	trí-M	Mc
…	…	…-F	Fi
Ní	Ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
an	an	an-T	Td-s
múinteoir	múinteoir	múinteoir-N	Ncmsc
í	í	í-P	Pp3fs
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
Áine	Áine	Áine-N	Npfsc
í	í	í-P	Pp3fs
.	.	.-F	Fe
Go	Go	go-U	Ua
tobann	tobann	tobann-A	Aqp
sciorr	sciorr	sciorr-V	Vmis
a	a	a-D	Dp3
cos	cos	cos-N	Ncfsc
ar	ar	ar-S	Sp
Léiní	Léiní	Léiní-N	Npmsc
agus	agus	agus-C	Cc
thit	thit	tit-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
Síos	Síos	síos-R	Rd
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Baineadh	Baineadh	bain-V	Vmis0
geit	geit	geit-N	Ncfsc
as	as	as-S	Sp
an	an	an-T	Td-s
múinteoir	múinteoir	múinteoir-N	Ncmsc
.	.	.-F	Fe
Lig	Lig	lig-V	Vmis
sí	sí	sí-P	Pp3fsn
béic	béic	béic-N	Ncfsc
aisti	aisti	as-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
luch	luch	luch-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bpianó	bpianó	pianó-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
múinteoir	múinteoir	múinteoir-N	Ncmsc
agus	agus	agus-C	Cc
léim	léim	léim-V	Vmis
sí	sí	sí-P	Pp3fsn
in	in	i-S	Sp
airde	airde	aird-N	Ncfsc|Ncfpc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcathaoir	gcathaoir	cathaoir-N	Ncfsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
luch	luch	luch-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bpianó	bpianó	pianó-N	Ncmsc
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
Áine	Áine	Áine-N	Npfsc
Léiní	Léiní	Léiní-N	Npmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bpianó	bpianó	pianó-N	Ncmsc
.	.	.-F	Fe
Ó	Ó	Ó-I	I
!	!	!-F	Fe
Is	Is	is-W	Wp-i
tusa	tusa	tú-P	Pp2-s-e
atá	atá	bí-V	Vmip---r
ann	ann	i-P	Pr3ms
,	,	,-F	Fi
a	a	a-U	Uv
Léiní	Léiní	Léiní-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nach	Nach	is-C	Cs|Wpdin|Wpsin
tú	tú	tú-P	Pp2-s
atá	atá	bí-V	Vmip---r
dána	dána	dána-A	Aqc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Áine	Áine	Áine-N	Npfsc
le	le	le-S	Sp
Léiní	Léiní	Léiní-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
peata	peata	peata-N	Ncmsc
liomsa	liomsa	le-P	Pr1-s-e
í	í	í-P	Pp3fs
seo	seo	seo-P	Pd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Áine	Áine	Áine-N	Npfsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
múinteoir	múinteoir	múinteoir-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Léiní	Léiní	Léiní-N	Npmsc
an	an	an-T	Td-s
t-ainm	t-ainm	ainm-N	Ncmsc
atá	atá	bí-V	Vmip---r
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
!	!	!-F	Fe
Is	Is	is-W	Wp-i
peata	peata	peata-N	Ncmsc
leatsa	leatsa	le-P	Pr2-s-e
í	í	í-P	Pp3fs
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
múinteoir	múinteoir	múinteoir-N	Ncmsc
agus	agus	agus-C	Cc
léim	léim	léim-V	Vmis
sí	sí	sí-P	Pp3fsn
anuas	anuas	anuas-R	Rd
den	den	de-S	Spa-s
chathaoir	chathaoir	cathaoir-N	Ncfsc
.	.	.-F	Fe
Ó	Ó	Ó-I	I
!	!	!-F	Fe
Is	Is	is-W	Wp-i
peata	peata	peata-N	Ncmsc
leatsa	leatsa	le-P	Pr2-s-e
í	í	í-P	Pp3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
mise	mise	mé-P	Pp1-s-e
riamh	riamh	riamh-R	Rg
ag	ag	ag-S	Sp
rang	rang	rang-N	Ncmsc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Léiní	Léiní	Léiní-N	Npmsc
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
