Is	Is	is-W	Wp-i
coinín	coinín	coinín-N	Ncmsc
mise	mise	mé-P	Pp1-s-e
.	.	.-F	Fe
Duibhín	Duibhín	Duibhín-N	Npmsc
an	an	an-T	Td-s
t-ainm	t-ainm	ainm-N	Ncmsc
atá	atá	bí-V	Vmip---r
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
is	is	is-W	Wp-i
coinín	coinín	coinín-N	Ncmsc
mise	mise	mé-P	Pp1-s-e
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
.	.	.-F	Fe
Báinín	Báinín	báinín-N	Ncmsc
an	an	an-T	Td-s
t-ainm	t-ainm	ainm-N	Ncmsc
atá	atá	bí-V	Vmip---r
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
púirín	púirín	púirín-N	Ncmsc
deas	deas	deas-A	Aq-msc
againn	againn	ag-P	Pr1-p
.	.	.-F	Fe
Ithimse	Ithimse	ith-V	Vmip1s--e
cairéid	cairéid	cairéad-N	Ncmpc
.	.	.-F	Fe
Ithimse	Ithimse	ith-V	Vmip1s--e
féar	féar	féar-N	Ncmsc
.	.	.-F	Fe
Bím	Bím	bí-V	Vmig1s
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
Báinín	Báinín	báinín-N	Ncmsc
ag	ag	ag-S	Sp
rith	rith	rith-N	Nv
.	.	.-F	Fe
Bím	Bím	bí-V	Vmig1s
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
Duibhín	Duibhín	Duibhín-N	Npmsc
ag	ag	ag-S	Sp
léim	léim	léim-N	Nv
.	.	.-F	Fe
Is	Is	is-W	Wp-i
maith	maith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
Báinín	Báinín	báinín-N	Ncmsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
maith	maith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
Duibhín	Duibhín	Duibhín-N	Npmsc
.	.	.-F	Fe
