Maidin	Maidin	maidin-N	Ncfsc
Dé	Dé	Dé-N	Ns-s
Sathairn	Sathairn	Satharn-N	Ncmsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
mise	mise	mé-P	Pp1-s-e
ag	ag	ag-S	Sp
gabháil	gabháil	gabh-N	Nv
síos	síos	síos-R	Rd
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
siopa	siopa	siopa-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Deaide	Deaide	Deaide-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
adhmad	adhmad	adhmad-N	Ncmsc
a	a	a-U	U
cheannach	cheannach	ceannaigh-N	Nv
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhféadfaidh	bhféadfaidh	féad-V	Vmif
mé	mé	mé-P	Pp1-s
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
leat	leat	le-P	Pr2-s
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Féadfaidh	Féadfaidh	féad-V	Vmif
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Deaide	Deaide	Deaide-N	Npmsc
.	.	.-F	Fe
Cheannaigh	Cheannaigh	ceannaigh-V	Vmis
Deaide	Deaide	Deaide-N	Npmsc
an	an	an-T	Td-s
t-adhmad	t-adhmad	adhmad-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cén	Cén	cé-D	Dw--s
fáth	fáth	fáth-N	Ncmsc
a	a	a-Q	Q-i
bhfuil	bhfuil	bí-V	Vmip---d
an	an	an-T	Td-s
t-adhmad	t-adhmad	adhmad-N	Ncmsc
sin	sin	sin-D	Dd
uait	uait	ó-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Dheaide	Dheaide	Dheaide-N	Npmsc
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Le	Le	le-S	Sp
cliabhán	cliabhán	cliabhán-N	Ncmsc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
d	d	d-X	Xl
’	’	’-F	Fa
Ailbhe	Ailbhe	Ailbhe-N	Npmsc|Npfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Deaide	Deaide	Deaide-N	Npmsc
.	.	.-F	Fe
Cén	Cén	cé-D	Dw--s
fáth	fáth	fáth-N	Ncmsc
a	a	a-Q	Q-i
bhfuil	bhfuil	bí-V	Vmip---d
an	an	an-T	Td-s
t-adhmad	t-adhmad	adhmad-N	Ncmsc
sin	sin	sin-D	Dd
uait	uait	ó-P	Pr2-s
?	?	?-F	Fq
‘	‘	‘-X	Xx
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
go dtí	go dtí	go_dtí-S	Spc
siopa	siopa	siopa-N	Ncmsc
na	na	na-T	Td-p
mbréagán	mbréagán	bréagán-N	Ncmpg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
am	am	am-N	Ncmsc
anois	anois	anois-R	Rt
againn	againn	ag-P	Pr1-p
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Deaide	Deaide	Deaide-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
obair	obair	obair-N	Ncfsc
le	le	le-S	Sp
déanamh	déanamh	déan-N	Nv
agamsa	agamsa	ag-P	Pr1-s-e
.	.	.-F	Fe
’	’	’-F	Fa
Tá	Tá	bí-V	Vmip
obair	obair	obair-N	Ncfsc
le	le	le-S	Sp
déanamh	déanamh	déan-N	Nv
agamsa	agamsa	ag-P	Pr1-s-e
.	.	.-F	Fe
Siúd	Siúd	siúd-P	Pd
abhaile	abhaile	abhaile-R	Rd
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbeirt	mbeirt	beirt-N	Ncfsc
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
Deaide	Deaide	Deaide-N	Npmsc
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
ngaráiste	ngaráiste	garáiste-N	Ncmsc
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
obair	obair	obair-N	Nv-----n
.	.	.-F	Fe
Tamall	Tamall	tamall-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|Dd
tháinig	tháinig	tar-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
isteach	isteach	isteach-R	Rd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhí	Bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
breathnú	breathnú	breathnaigh-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
teilifís	teilifís	teilifís-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
,	,	,-F	Fi
‘	‘	‘-X	Xx
ach	ach	ach-C	Cs
níl	níl	bí-V	Vmip---n
cuma	cuma	cuma-N	Ncfsc
ná	ná	ná-C	Cs|Cc
caoi	caoi	caoi-N	Ncfsg|Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gclár	gclár	clár-N	Ncmsc
atá	atá	bí-V	Vmip---r
ar	ar	ar-S	Sp
siúl	siúl	siúil-N	Nv
.	.	.-F	Fe
An	An	an-Q	Qq
bhféadfaidh	bhféadfaidh	féad-V	Vmif
mé	mé	mé-P	Pp1-s
breathnú	breathnú	breathnaigh-N	Ncmsc|Nv
ortsa	ortsa	ar-P	Pr2-s-e
ag	ag	ag-S	Sp
obair	obair	obair-N	Nv-----n
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Féadfaidh	Féadfaidh	féad-V	Vmif
,	,	,-F	Fi
cinnte	cinnte	cinnte-A	Av|Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Deaide	Deaide	Deaide-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Déanfaidh	Déanfaidh	déan-V	Vmif
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
againn	againn	ag-P	Pr1-p
an	an	an-T	Td-s
cliabhán	cliabhán	cliabhán-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
Rug	Rug	beir-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
sábh	sábh	sábh-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
é	é	é-P	Pp3ms
seo	seo	seo-P	Pd
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seachain	Seachain	seachain-V	Vmm-2s
tú	tú	tú-P	Pp2-s
féin	féin	féin-P	Px
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Deaide	Deaide	Deaide-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Sin	Sin	sin-W	W
sábh	sábh	sábh-N	Ncmsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
an-ghéar	an-ghéar	géar-A	Aqp
.	.	.-F	Fe
’	’	’-F	Fa
Agus	Agus	agus-C	Cc
thóg	thóg	tóg-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
sábh	sábh	sábh-N	Ncmsc
uaithi	uaithi	ó-P	Pr3fs
.	.	.-F	Fe
Seachain	Seachain	seachain-V	Vmm-2s
tú	tú	tú-P	Pp2-s
féin	féin	féin-P	Px
ar	ar	ar-S	Sp
an	an	an-T	Td-s
sábh	sábh	sábh-N	Ncmsc
.	.	.-F	Fe
Rug	Rug	beir-V	Vmis
Deaide	Deaide	Deaide-N	Npmsc
ar	ar	ar-S	Sp
phíosa	phíosa	píosa-N	Ncmsc
adhmaid	adhmaid	adhmad-N	Ncmsg
agus	agus	agus-C	Cc
thomhais	thomhais	tomhais-V	Vmis
sé	sé	sé-P	Pp3msn
é	é	é-P	Pp3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
atá	atá	bí-V	Vmip---r
tú	tú	tú-P	Pp2-s
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
anois	anois	anois-R	Rt
,	,	,-F	Fi
a	a	a-U	Uv
Dheaide	Dheaide	Dheaide-N	Npmsc
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
píosa	píosa	píosa-N	Ncmsc
adhmaid	adhmaid	adhmad-N	Ncmsg
seo	seo	seo-D	Dd
rófhada	rófhada	fada-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Deaide	Deaide	Deaide-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
é	é	é-P	Pp3ms
a	a	a-U	U
ghearradh	ghearradh	gearr-N	Nv
.	.	.-F	Fe
Seachain	Seachain	seachain-V	Vmm-2s
tú	tú	tú-P	Pp2-s
féin	féin	féin-P	Px
ar	ar	ar-S	Sp
an	an	an-T	Td-s
sábh	sábh	sábh-N	Ncmsc
,	,	,-F	Fi
a	a	a-U	Uv
stór	stór	stór-N	Ncmsv
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
an-ghéar	an-ghéar	géar-A	Aqp
.	.	.-F	Fe
’	’	’-F	Fa
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
seo	seo	seo-P	Pd
rófhada	rófhada	fada-A	Aqp
.	.	.-F	Fe
Fuair	Fuair	faigh-V	Vmis
Deaide	Deaide	Deaide-N	Npmsc
an	an	an-T	Td-s
sábh	sábh	sábh-N	Ncmsc
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
gearradh	gearradh	gearr-N	Nv
an	an	an-T	Td-s
adhmaid	adhmaid	adhmad-N	Ncmsg
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
thomhais	thomhais	tomhais-V	Vmis
sé	sé	sé-P	Pp3msn
agus	agus	agus-C	Cc
ghearr	ghearr	gearr-V	Vmis
sé	sé	sé-P	Pp3msn
na	na	na-T	Td-p
píosaí	píosaí	píosa-N	Ncmpc
eile	eile	eile-D	Dd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
céard	céard	cé-W	W--q
atá	atá	bí-V	Vmip---r
tú	tú	tú-P	Pp2-s
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
anois	anois	anois-R	Rt
,	,	,-F	Fi
a	a	a-U	Uv
Dheaide	Dheaide	Dheaide-N	Npmsc
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
gliú	gliú	gliú-N	Ncmsc
a	a	a-U	U
chur	chur	cuir-N	Nv
air	air	ar-N	Ncmsg
seo	seo	seo-P	Pd|Dd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Deaide	Deaide	Deaide-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Sín	Sín	Sín-N	Npfsc
chugam	chugam	chuig-P	Pr1-s
an	an	an-T	Td-s
gliú	gliú	gliú-N	Ncmsg|Ncmsc
sin	sin	sin-D	Dd
,	,	,-F	Fi
a	a	a-U	Uv
Róisín	Róisín	Róisín-N	Npf-v
.	.	.-F	Fe
’	’	’-F	Fa
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
gliú	gliú	gliú-N	Ncmsc
a	a	a-U	U
chur	chur	cuir-N	Nv
air	air	ar-N	Ncmsg
seo	seo	seo-P	Pd|Dd
.	.	.-F	Fe
Bhreathnaigh	Bhreathnaigh	breathnaigh-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
thart	thart	thart-R	Rd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ab	Ab	is-W	Wsri
shiod	shiod	shiod-N	Ncmsc
gliú	gliú	gliú-N	Ncmsg|Ncmsc
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
agus	agus	agus-C	Cc
shín	shín	sín-V	Vmis
sí	sí	sí-P	Pp3fsn
buidéal	buidéal	buidéal-N	Ncmsc
chuige	chuige	chuig-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
ea	ea	ea-P	Pp3-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Deaide	Deaide	Deaide-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Maith	Maith	Maith-N	Npmsc
an	an	an-T	Td-s
cailín	cailín	cailín-N	Ncmsg
.	.	.-F	Fe
’	’	’-F	Fa
Ab	Ab	is-W	Wsri
shiod	shiod	shiod-N	Ncmsc
gliú	gliú	gliú-N	Ncmsg|Ncmsc
?	?	?-F	Fq
Bhí	Bhí	bí-V	Vmis
Deaide	Deaide	Deaide-N	Npmsc
ag	ag	ag-S	Sp
obair	obair	obair-N	Nv-----n
leis	leis	le-P	Pr3ms
go	go	go-U	Ua
sásta	sásta	sásta-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
ag	ag	ag-S	Sp
síneadh	síneadh	sín-N	Nv
an	an	an-T	Td-s
bhuidéil	bhuidéil	buidéal-N	Ncmsg
ghliú	ghliú	gliú-N	Ncmsg
chuige	chuige	chuig-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
an	an	an-T	Td-s
cliabhán	cliabhán	cliabhán-N	Ncmsc
déanta	déanta	déan-A	Aqp|Av
anois	anois	anois-R	Rt
againn	againn	ag-P	Pr1-p
,	,	,-F	Fi
a	a	a-U	Uv
Dheaide	Dheaide	Dheaide-N	Npmsc
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
tar éis	tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
fada	fada	fada-A	Aqp
anois	anois	anois-R	Rt
go	go	go-Q	Q
mbeidh	mbeidh	bí-V	Vmif
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Deaide	Deaide	Deaide-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
caithfidh	caithfidh	caith-V	Vmif
muid	muid	muid-P	Pp1-p
é	é	é-P	Pp3ms
a	a	a-Q	Q-r
phéinteáil	phéinteáil	péinteáil-V	Vmis
amárach	amárach	amárach-N	Ns-s|Rt
.	.	.-F	Fe
’	’	’-F	Fa
Ní	Ní	is-W	Wp-in
fada	fada	fada-A	Aqp
anois	anois	anois-R	Rt
go	go	go-Q	Q
mbeidh	mbeidh	bí-V	Vmif
.	.	.-F	Fe
‘	‘	‘-X	Xx
Breathnaigh	Breathnaigh	breathnaigh-V	Vmm-2s
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcliabhán	gcliabhán	cliabhán-N	Ncmsc
deas	deas	deas-A	Aq-msc
atá	atá	bí-V	Vmip---r
déanta	déanta	déan-A	Av
againn	againn	ag-P	Pr1-p
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Fan	Fan	fan-V	Vmm-2s
go	go	go-Q	Q
bhfeicfidh	bhfeicfidh	feic-V	Vmif
Mama	Mama	mama-N	Ncmsc|Xfen
é	é	é-P	Pp3ms
.	.	.-F	Fe
’	’	’-F	Fa
Agus	Agus	agus-C	Cc
rith	rith	rith-V	Vmis
sí	sí	sí-P	Pp3fsn
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
teach	teach	teach-N	Ncmsc
.	.	.-F	Fe
Fan	Fan	fan-V	Vmm-2s
go	go	go-Q	Q
bhfeicfidh	bhfeicfidh	feic-V	Vmif
Mama	Mama	mama-N	Ncmsc|Xfen
é	é	é-P	Pp3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Mama	Mama	mama-N	Ncmsc|Xfen
thar a bheith	thar a bheith	thar_a_bheith-R	Ri
sásta	sásta	sásta-A	Aqp
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
cliabhán	cliabhán	cliabhán-N	Ncmsc
nua	nua	nua-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
!	!	!-F	Fe
Nach	Nach	is-W	Wpsin
deas	deas	deas-A	Aqp
an	an	an-T	Td-s
cliabhán	cliabhán	cliabhán-N	Ncmsc
é	é	é-P	Pp3ms
!	!	!-F	Fe
Maith	Maith	Maith-N	Npmsc
sibh	sibh	sibh-P	Pp2-p
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
agus	agus	agus-C	Cc
…	…	…-F	Fi
Nach	Nach	nach-W	Wprin|Wpdin|Wpsin|Cs
deas	deas	deas-N	Ns-s|Aqp
an	an	an-T	Td-s
cliabhán	cliabhán	cliabhán-N	Ncmsc
é	é	é-P	Pp3ms
!	!	!-F	Fe
…	…	…-F	Fi
thug	thug	tabhair-V	Vmis
sí	sí	sí-P	Pp3fsn
póigín	póigín	póg-N	Ncfsc
do	do	do-S	Sp
Dheaide	Dheaide	deaide-N	Npmsc
!	!	!-F	Fe
