Bhí	Bhí	bí-V	Vmis
Sciob	Sciob	sciob-V	Vmis
ina	ina	i-S	Spp-s
chodladh	chodladh	codladh-N	Ncfsc
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
Sciob	Sciob	sciob-V	Vmis
an	an	an-T	Td-s
chuileog	chuileog	cuileog-N	Ncfsc
.	.	.-F	Fe
Ó	Ó	Ó-I	I
,	,	,-F	Fi
cuileog	cuileog	cuileog-N	Ncfsc
!	!	!-F	Fe
Neam	Neam	Neam-N	Npmsc
!	!	!-F	Fe
Neam	Neam	Neam-N	Npmsc
!	!	!-F	Fe
Léim	Léim	léim-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Rith	Rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
diaidh	diaidh	diaidh-N	Ns-s
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
agam	agam	ag-P	Pr1-s
!	!	!-F	Fe
Léim	Léim	léim-N	Ncfsc
Sciob	Sciob	sciob-V	Vmis
suas	suas	suas-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcófra	gcófra	cófra-N	Ncmsc
.	.	.-F	Fe
Rith	Rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
amach	amach	amach-R	Rd
sa	sa	i-S	Spa-s
halla	halla	halla-N	Ncmsc
.	.	.-F	Fe
Léim	Léim	léim-V	Vmis
sé	sé	sé-P	Pp3msn
arís	arís	arís-R	Rg
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
agam	agam	ag-P	Pr1-s
anois	anois	anois-R	Rt
!	!	!-F	Fe
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
an	an	an-T	Td-s
chuileog	chuileog	cuileog-N	Ncfsc
sin	sin	sin-D	Dd
?	?	?-F	Fq
Rith	Rith	rith-N	Ncmsc
Sciob	Sciob	sciob-V	Vmis
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
seomra	seomra	seomra-N	Ncmsc
suite	suite	suigh-A	Aqp|Av
.	.	.-F	Fe
Níl	Níl	bí-V	Vmip---n
sí	sí	sí-P	Pp3fsn
anseo	anseo	anseo-R	Rl
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
an	an	an-T	Td-s
chuileog	chuileog	cuileog-N	Ncfsc
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Rith	Rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
chistin	chistin	cistin-N	Ncfsc
.	.	.-F	Fe
Níl	Níl	bí-V	Vmip---n
sí	sí	sí-P	Pp3fsn
anseo	anseo	anseo-R	Rl
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
oiread	oiread	oiread-N	Ns-s
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
an	an	an-T	Td-s
chuileog	chuileog	cuileog-N	Ncfsc
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Rith	Rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
amach	amach	amach-R	Rd
sa	sa	i-S	Spa-s
halla	halla	halla-N	Ncmsc
.	.	.-F	Fe
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
an	an	an-T	Td-s
chuileog	chuileog	cuileog-N	Ncfsc
?	?	?-F	Fq
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
an	an	an-T	Td-s
chuileog	chuileog	cuileog-N	Ncfsc
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Sciob	Sciob	sciob-V	Vmis
tuirseach	tuirseach	tuirseach-N	Ncmsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
tuirseach	tuirseach	tuirseach-A	Aqp
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
leis	leis	le-P	Pr3ms
ina	ina	i-S	Spp-s
chiseán	chiseán	ciseán-N	Ncmsc
.	.	.-F	Fe
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
Sciob	Sciob	sciob-V	Vmis
?	?	?-F	Fq
Is	Is	is-W	Wp-i
ansin	ansin	ansin-R	Rt|Rl
atá	atá	bí-V	Vmip---r
tú	tú	tú-P	Pp2-s
.	.	.-F	Fe
Nach	Nach	is-W	Wpsin
tusa	tusa	tú-P	Pp2-s-e
atá	atá	bí-V	Vmip---r
dána	dána	dána-A	Aqc
!	!	!-F	Fe
