Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
mo	mo	mo-D	Dp1-s
mhála	mhála	mála-N	Ncmsc
scoile	scoile	scoil-N	Ncfsg
?	?	?-F	Fq
An	An	an-Q	Qq
bhfaca	bhfaca	feic-V	Vmis---d
tusa	tusa	tú-P	Pp2-s-e
é	é	é-P	Pp3ms
?	?	?-F	Fq
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Mhamaí	Mhamaí	mama-N	Ncfsv|Ncmpv
,	,	,-F	Fi
Cár	Cár	cá-R	Rq
imigh	imigh	imigh-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
strae	strae	strae-N	Ncmsc
?	?	?-F	Fq
Níl	Níl	bí-V	Vmip---n
sé	sé	sé-P	Pp3msn
sa	sa	i-S	Spa-s
chistin	chistin	cistin-N	Ncfsc
,	,	,-F	Fi
Ná	Ná	ná-C	Cc
sa	sa	i-S	Spa-s
seomra	seomra	seomra-N	Ncmsc
suí	suí	suigh-N	Ncmsc|Ncmsg|Nv
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
thug	thug	tabhair-V	Vmis---n
mé	mé	mé-P	Pp1-s
suas	suas	suas-R	Rd
an	an	an-T	Td-s
staighre	staighre	staighre-N	Ncmsc
é	é	é-P	Pp3ms
,	,	,-F	Fi
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuaigh	chuaigh	téigh-V	Vmis
mé	mé	mé-P	Pp1-s
féin	féin	féin-P	Px
a	a	a-U	U
luí	luí	luigh-N	Nv
.	.	.-F	Fe
Cinnte	Cinnte	cinn-A	Av
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
agam	agam	ag-P	Pr1-s
Ar	Ar	ar-N	Ncmsc
mo	mo	mo-D	Dp1-s
theacht	theacht	teacht-V	Vmis|Nv|Ncmsc
ón	ón	ó-S	Spa-s
scoil	scoil	scoil-N	Ncfsc
inné	inné	inné-A	Aqp
.	.	.-F	Fe
Mar	Mar	mar-C	Cs
chríochnaigh	chríochnaigh	críochnaigh-V	Vmis
mé	mé	mé-P	Pp1-s
mo	mo	mo-D	Dp1-s
cheachtanna	cheachtanna	ceacht-N	Ncmpc
Go	Go	go-U	Ua
díreach	díreach	díreach-A	Aqp
tar éis	tar éis	tar_éis-S	Spc
an	an	an-T	Td-s
tae	tae	tae-N	Ncmsg
.	.	.-F	Fe
Sin	Sin	sin-W	W
é	é	é-P	Pp3ms
do	do	do-S	Sp
mhála	mhála	mála-N	Ncmsc
scoile	scoile	scoil-N	Ncfsg
,	,	,-F	Fi
Is	Is	agus-C	Cc
níor	níor	níor-Q	Qn-s
imigh	imigh	imigh-V	Vmis---n
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
strae	strae	strae-N	Ncmsc
.	.	.-F	Fe
Thiar	Thiar	thiar-R	Rd
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
do	do	do-S	Sp
dhroim	dhroim	droim-N	Ncmsc
atá	atá	bí-V	Vmip---r
sé	sé	sé-P	Pp3msn
,	,	,-F	Fi
Agus	Agus	agus-C	Cc
tú	tú	tú-P	Pp2-s
féin	féin	féin-P	Px
a	a	a-Q	Q-r
chuir	chuir	cuir-V	Vmis
ann	ann	i-P	Pr3ms
é	é	é-P	Pp3ms
!	!	!-F	Fe
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
mo	mo	mo-D	Dp1-s
mhála	mhála	mála-N	Ncmsc
scoile	scoile	scoil-N	Ncfsg
?	?	?-F	Fq
An	An	an-Q	Qq
bhfaca	bhfaca	feic-V	Vmis---d
tusa	tusa	tú-P	Pp2-s-e
é	é	é-P	Pp3ms
?	?	?-F	Fq
