‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
in	in	i-S	Sp
am	am	am-N	Ncmsc
lóin	lóin	lón-N	Ncmsg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
múinteoir	múinteoir	múinteoir-N	Ncmsc
.	.	.-F	Fe
Amach	Amach	amach-R	Rd
leis	leis	le-S	Sp
an	an	an-T	Td-s
rang	rang	rang-N	Ncmsc
.	.	.-F	Fe
Amach	Amach	amach-R	Rd
leis	leis	le-S	Sp
an	an	an-T	Td-s
múinteoir	múinteoir	múinteoir-N	Ncmsc
ina	ina	i-S	Spp-p
ndiaidh	ndiaidh	diaidh-N	Ns-s
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Lug	Lug	lug-N	Ncmsc
agus	agus	agus-C	Cc
Gug	Gug	Gug-N	Npmsc
fós	fós	fós-R	Rg
sa	sa	i-S	Spa-s
seomra	seomra	seomra-N	Ncmsc
ranga	ranga	rang-N	Ncmsg
.	.	.-F	Fe
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
dul	dul	téigh-N	Nv
amach	amach	amach-R	Rd
sa	sa	i-S	Spa-s
chlós	chlós	clós-N	Ncmsc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
ba	ba	is-W	Ws|Ws-i
mhaith	mhaith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
dul	dul	téigh-N	Nv
amach	amach	amach-R	Rd
sa	sa	i-S	Spa-s
chlós	chlós	clós-N	Ncmsc
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
.	.	.-F	Fe
Seo	Seo	seo-W	W
,	,	,-F	Fi
amach	amach	amach-R	Rd
linn	linn	le-P	Pr1-p
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
.	.	.-F	Fe
Léim	Léim	léim-V	Vmip1s|Vmm-2s|Vmis|Ncfsc
Lug	Lug	lug-N	Ncmsc|Xfev
anuas	anuas	anuas-R	Rd
den	den	de-S	Spa-s
tseilf	tseilf	seilf-N	Ncfsc
.	.	.-F	Fe
Léim	Léim	léim-V	Vmip1s|Vmis
Gug	Gug	Gug-N	Npmsc
anuas	anuas	anuas-R	Rd
den	den	de-S	Spa-s
tseilf	tseilf	seilf-N	Ncfsc
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
féidir	féidir	féidir-N	Ns-s
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
a	a	a-U	U
oscailt	oscailt	oscail-N	Nv
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
féidir	féidir	féidir-N	Ns-s
liomsa	liomsa	le-P	Pr1-s-e
é	é	é-P	Pp3ms
a	a	a-U	U
oscailt	oscailt	oscail-N	Nv
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
oiread	oiread	oiread-N	Ns-s
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
féidir	féidir	féidir-N	Ns-s
linn	linn	le-P	Pr1-p
dul	dul	téigh-N	Nv
amach	amach	amach-R	Rd
sa	sa	i-S	Spa-s
chlós	chlós	clós-N	Ncmsc
.	.	.-F	Fe
Tóg	Tóg	tóg-V	Vmm-2s
anuas	anuas	anuas-R	Rd
an	an	an-T	Td-s
tarracóir	tarracóir	tarracóir-N	Ncmsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
cairrín	cairrín	cairrín-N	Ncmsg|Ncmsc
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
.	.	.-F	Fe
