Bhí	Bhí	bí-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
ag	ag	ag-S	Sp
ithe	ithe	ith-N	Nv
a	a	a-D	Dp3
lóin	lóin	lón-N	Ncmsg
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
lón	lón	lón-N	Ncmsc
deas	deas	deas-A	Aq-msc
agam	agam	ag-P	Pr1-s
inniu	inniu	inniu-R	Rt
.	.	.-F	Fe
Rith	Rith	rith-N	Ncmsc
Sciob	Sciob	sciob-V	Vmis
isteach	isteach	isteach-R	Rd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
fliuch	fliuch	fliuch-A	Aqp
báite	báite	báigh-A	Av
.	.	.-F	Fe
Ó	Ó	Ó-I	I
,	,	,-F	Fi
a	a	a-Q	Q-r
Sciob	Sciob	sciob-V	Vmis
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
fliuch	fliuch	fliuch-A	Aqp
báite	báite	báigh-A	Av
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
ocras	ocras	ocras-N	Ncmsc
ar	ar	ar-Q	Q-p
Sciob	Sciob	sciob-V	Vmis
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
ocras	ocras	ocras-N	Ncmsc
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
Léim	Léim	léim-V	Vmis
sé	sé	sé-P	Pp3msn
suas	suas	suas-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbord	mbord	bord-N	Ncmsc
.	.	.-F	Fe
Amach	Amach	amach-R	Rd
leat	leat	le-P	Pr2-s
,	,	,-F	Fi
a	a	a-Q	Q-r
Sciob	Sciob	sciob-V	Vmis
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
fliuch	fliuch	fliuch-A	Aqp
báite	báite	báigh-A	Av
.	.	.-F	Fe
Rith	Rith	rith-N	Ncmsc
Sciob	Sciob	sciob-V	Vmis
amach	amach	amach-R	Rd
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
Mama	Mama	mama-N	Ncmsc|Xfen
isteach	isteach	isteach-R	Rd
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
Sciob	Sciob	sciob-V	Vmis
isteach	isteach	isteach-R	Rd
,	,	,-F	Fi
a	a	a-U	Uv
Mhama	Mhama	mama-N	Ncmsv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
fliuch	fliuch	fliuch-A	Aqp
báite	báite	báigh-A	Av
.	.	.-F	Fe
Tut	Tut	Tut-N	Npmsc
!	!	!-F	Fe
Tut	Tut	Tut-N	Npmsc
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
Sciob	Sciob	sciob-V	Vmis
an-dána	an-dána	dána-A	Aqp
.	.	.-F	Fe
Maith	Maith	Maith-N	Npmsc
an	an	an-T	Td-s
cailín	cailín	cailín-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Maith	Maith	Maith-N	Npmsc
an	an	an-T	Td-s
cailín	cailín	cailín-N	Ncmsg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mama	Mama	mama-N	Ncmsc|Xfen
.	.	.-F	Fe
‘	‘	‘-X	Xx
Suigh	Suigh	suigh-V	Vmm-2s
síos	síos	síos-R	Rd
anois	anois	anois-R	Rt
agus	agus	agus-C	Cc
ith	ith	ith-V	Vmm-2s
do	do	do-S	Sp
lón	lón	lón-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
níl	níl	bí-V	Vmip---n
mo	mo	mo-D	Dp1-s
lón	lón	lón-N	Ncmsc
anseo	anseo	anseo-R	Rl
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
mo	mo	mo-D	Dp1-s
lón	lón	lón-N	Ncmsc
?	?	?-F	Fq
’	’	’-F	Fa
