Bhí	Bhí	bí-V	Vmis
Brídín	Brídín	Brídín-N	Npfsc
ag	ag	ag-S	Sp
imirt	imirt	imir-N	Nv
camógaíochta	camógaíochta	camógaíocht-N	Ncfsg
.	.	.-F	Fe
Thit	Thit	tit-V	Vmis
sí	sí	sí-P	Pp3fsn
agus	agus	agus-C	Cc
ghortaigh	ghortaigh	gortaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
í	í	í-P	Pp3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
Ó	Ó	Ó-I	I
,	,	,-F	Fi
tá	tá	bí-V	Vmip
mo	mo	mo-D	Dp1-s
chos	chos	cos-N	Ncfsc
gortaithe	gortaithe	gortaigh-A	Av
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
pian	pian	pian-N	Ncfsc
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
tá	tá	bí-V	Vmip
mo	mo	mo-D	Dp1-s
lámh	lámh	lámh-N	Ncfsc
gortaithe	gortaithe	gortaigh-A	Av
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
an	an	an-T	Td-s
dochtúir	dochtúir	dochtúir-N	Ncmsc
.	.	.-F	Fe
Brídín	Brídín	Brídín-N	Npfsc
bhocht	bhocht	bocht-A	Aq-fsc|Aq-fsv
!	!	!-F	Fe
Thit	Thit	tit-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
do	do	do-S	Sp
chos	chos	cos-N	Ncfsc
briste	briste	bris-A	Aqp|Av
,	,	,-F	Fi
a	a	a-U	Uv
Bhrídín	Bhrídín	Brídín-N	Npf-v
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
dochtúir	dochtúir	dochtúir-N	Ncmsc
.	.	.-F	Fe
Caithfidh	Caithfidh	caith-V	Vmif
tú	tú	tú-P	Pp2-s
dul	dul	téigh-N	Ncmsc|Nv
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
t-ospidéal	t-ospidéal	ospidéal-N	Ncmsc
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
an	an	an-T	Td-s
t-otharcharr	t-otharcharr	otharcharr-N	Ncmsc
.	.	.-F	Fe
Brídín	Brídín	Brídín-N	Npfsc
bhocht	bhocht	bocht-A	Aq-fsc|Aq-fsv
!	!	!-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
mo	mo	mo-D	Dp1-s
chos	chos	cos-N	Ncfsc
briste	briste	bris-A	Aqp|Av
agus	agus	agus-C	Cc
tá	tá	bí-V	Vmip
mo	mo	mo-D	Dp1-s
lámh	lámh	lámh-N	Ncfsc
gortaithe	gortaithe	gortaigh-A	Av
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Brídín	Brídín	Brídín-N	Npfsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
pian	pian	pian-N	Ncfsc
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
Brídín	Brídín	Brídín-N	Npfsc
bhocht	bhocht	bocht-A	Aq-fsc|Aq-fsv
!	!	!-F	Fe
Thug	Thug	tabhair-V	Vmis
an	an	an-T	Td-s
t-otharcharr	t-otharcharr	otharcharr-N	Ncmsc
Brídín	Brídín	Brídín-N	Npf-g|Npfsc
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
t-ospidéal	t-ospidéal	ospidéal-N	Ncmsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
tháinig	tháinig	tar-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
t-ospidéal	t-ospidéal	ospidéal-N	Ncmsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
mo	mo	mo-D	Dp1-s
chos	chos	cos-N	Ncfsc
briste	briste	bris-A	Aqp|Av
,	,	,-F	Fi
a	a	a-U	Uv
Dhaidí	Dhaidí	daidí-N	Ncmsv
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
pian	pian	pian-N	Ncfsc
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
dochtúir	dochtúir	dochtúir-N	Ncmsc
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
anois	anois	anois-R	Rt
,	,	,-F	Fi
a	a	a-U	Uv
stóirín	stóirín	stór-N	Ncmsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
.	.	.-F	Fe
Brídín	Brídín	Brídín-N	Npfsc
bhocht	bhocht	bocht-A	Aq-fsc|Aq-fsv
!	!	!-F	Fe
Thug	Thug	tabhair-V	Vmis
an	an	an-T	Td-s
dochtúir	dochtúir	dochtúir-N	Ncmsc
instealladh	instealladh	insteall-V	Vmih
do	do	do-S	Sp
Bhrídín	Bhrídín	Brídín-N	Npfsc
.	.	.-F	Fe
Thit	Thit	tit-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
!	!	!-F	Fe
Daidí	Daidí	daidí-N	Ncmsc
bocht	bocht	bocht-A	Aq-msc
!	!	!-F	Fe
