Rith	Rith	rith-V	Vmis
Cáit	Cáit	Cáit-N	Npfsc
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
é	é	é-P	Pp3ms
Daideo	Daideo	daideo-N	Ncmsc
atá	atá	bí-V	Vmip---r
ann	ann	i-P	Pr3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
Cheannaigh	Cheannaigh	ceannaigh-V	Vmis
mé	mé	mé-P	Pp1-s
bronntanas	bronntanas	bronntanas-N	Ncmsc
daoibh	daoibh	do-P	Pr2-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cheannaigh	Cheannaigh	ceannaigh-V	Vmis
mé	mé	mé-P	Pp1-s
bronntanas	bronntanas	bronntanas-N	Ncmsc
daoibh	daoibh	do-P	Pr2-p
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daideo	Daideo	daideo-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Oscail	Oscail	oscail-V	Vmis
é	é	é-P	Pp3ms
,	,	,-F	Fi
a	a	a-U	Uv
Cháit	Cháit	Cáit-N	Npf-v
.	.	.-F	Fe
’	’	’-F	Fa
Chuir	Chuir	cuir-V	Vmis
Cáit	Cáit	Cáit-N	Npfsc
an	an	an-T	Td-s
bronntanas	bronntanas	bronntanas-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
tolg	tolg	tolg-N	Ncmsc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmis
sí	sí	sí-P	Pp3fsn
é	é	é-P	Pp3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Liathróid	Liathróid	liathróid-N	Ncfsc
atá	atá	bí-V	Vmip---r
ann	ann	i-P	Pr3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cáit	Cáit	Cáit-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Liathróid	Liathróid	liathróid-N	Ncfsc
bhreá	bhreá	breá-A	Aq-fsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Eoin	Eoin	Eoin-N	Npmsc
.	.	.-F	Fe
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
maith	maith	maith-N	Ncfsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Dhaideo	Dhaideo	daideo-N	Ncmsv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
libh	libh	le-P	Pr2-p
!	!	!-F	Fe
Beidh	Beidh	bí-V	Vmif
cluiche	cluiche	cluiche-N	Ncmsc
peile	peile	peil-N	Ncfsg
againn	againn	ag-P	Pr1-p
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Eoin	Eoin	Eoin-N	Npmsc
.	.	.-F	Fe
Rith	Rith	rith-V	Vmm-2s|Vmis
an	an	an-T	Td-s
triúr	triúr	triúr-N	Ncmsc
acu	acu	ag-P	Pr3-p
amach	amach	amach-R	Rd
sa	sa	i-S	Spa-s
ghairdín	ghairdín	gairdín-N	Ncmsc
.	.	.-F	Fe
Tharraing	Tharraing	tarraing-V	Vmis
Eoin	Eoin	Eoin-N	Npmsc
cic	cic	cic-N	Ncfsc|Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
liathróid	liathróid	liathróid-N	Ncfsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
liathróid	liathróid	liathróid-N	Ncfsc
bhreá	bhreá	breá-A	Aq-fsc
í	í	í-P	Pp3fs
seo	seo	seo-P	Pd
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
amach	amach	amach-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbóthar	mbóthar	bóthar-N	Ncmsc
í	í	í-P	Pp3fs
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
tharraing	tharraing	tarraing-V	Vmis
Liam	Liam	Liam-N	Npmsc
cic	cic	cic-N	Ncfsc|Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
liathróid	liathróid	liathróid-N	Ncfsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
liathróid	liathróid	liathróid-N	Ncfsc
bhreá	bhreá	breá-A	Aq-fsc
í	í	í-P	Pp3fs
seo	seo	seo-P	Pd
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
isteach	isteach	isteach-R	Rd
sna	sna	i-S	Spa-p
sceacha	sceacha	sceach-N	Ncfpc
í	í	í-P	Pp3fs
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
chonaic	chonaic	feic-V	Vmis
siad	siad	siad-P	Pp3-pn
Daideo	Daideo	daideo-N	Ncmsc
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
sa	sa	i-S	Spa-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
tú	tú	tú-P	Pp2-s
imirt	imirt	imir-N	Ncfsc|Nv
linn	linn	le-P	Pr1-p
,	,	,-F	Fi
a	a	a-U	Uv
Dhaideo	Dhaideo	daideo-N	Ncmsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Eoin	Eoin	Eoin-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
mise	mise	mé-P	Pp1-s-e
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
chúl	chúl	cúl-N	Ncmsc
báire	báire	báire-N	Ncmsg|Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
A	A	a-U	Um
haon	haon	aon-M	Mc
,	,	,-F	Fi
a	a	a-U	Um
dó	dó	dó-M	Mc
,	,	,-F	Fi
a	a	a-U	Um
trí	trí	trí-M	Mc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daideo	Daideo	daideo-N	Ncmsc
agus	agus	agus-C	Cc
tharraing	tharraing	tarraing-V	Vmis
sé	sé	sé-P	Pp3msn
cic	cic	cic-N	Ncfsc|Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
liathróid	liathróid	liathróid-N	Ncfsc
.	.	.-F	Fe
A	A	a-U	Um
haon	haon	aon-M	Mc
,	,	,-F	Fi
a	a	a-U	Um
dó	dó	dó-M	Mc
,	,	,-F	Fi
a	a	a-U	Um
trí	trí	trí-M	Mc
.	.	.-F	Fe
Suas	Suas	suas-R	Rd
san	san	i-S	Spa-s
aer	aer	aer-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
liathróid	liathróid	liathróid-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Anois	Anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daideo	Daideo	daideo-N	Ncmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
nach	nach	nach-W	Wprin|Wpdin|Wpsin|Cs
iontach	iontach	iontach-A	Aqp
an	an	an-T	Td-s
peileadóir	peileadóir	peileadóir-N	Ncmsc
mé	mé	mé-P	Pp1-s
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
cá	cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
an	an	an-T	Td-s
liathróid	liathróid	liathróid-N	Ncfsc
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cáit	Cáit	Cáit-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
fhuinneog	fhuinneog	fuinneog-N	Ncfsc
briste	briste	bris-A	Av
ag	ag	ag-S	Sp
Daideo	Daideo	daideo-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Liam	Liam	Liam-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
cá	cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
sé	sé	sé-P	Pp3msn
imithe	imithe	imigh-A	Av
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Eoin	Eoin	Eoin-N	Npmsc
.	.	.-F	Fe
Tásc	Tásc	tásc-N	Ncmsc
ná	ná	ná-C	Cs|Cc
tuairisc	tuairisc	tuairisc-N	Ncfsc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ar	ar	ar-S	Sp
Dhaideo	Dhaideo	daideo-N	Ncmsc
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
Daid	Daid	Daid-N	Npmsc
amach	amach	amach-R	Rd
.	.	.-F	Fe
Lig	Lig	lig-V	Vmis
sé	sé	sé-P	Pp3msn
béic	béic	béic-N	Ncfsc
as	as	as-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cé	Cé	cé-P	Pq
a	a	a-Q	Q-r
bhris	bhris	bris-V	Vmis
an	an	an-T	Td-s
fhuinneog	fhuinneog	fuinneog-N	Ncfsc
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
mise	mise	mé-P	Pp1-s-e
a	a	a-Q	Q-r
bhris	bhris	bris-V	Vmis
í	í	í-P	Pp3fs
.	.	.-F	Fe
Ná	Ná	ná-C	Cc
mise	mise	mé-P	Pp1-s-e
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
oiread	oiread	oiread-N	Ns-s
.	.	.-F	Fe
Ná	Ná	ná-C	Cc
mise	mise	mé-P	Pp1-s-e
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
mise	mise	mé-P	Pp1-s-e
a	a	a-Q	Q-r
bhris	bhris	bris-V	Vmis
í	í	í-P	Pp3fs
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Eoin	Eoin	Eoin-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-C	Cs|Cc
mise	mise	mé-P	Pp1-s-e
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Liam	Liam	Liam-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-C	Cs|Cc
mise	mise	mé-P	Pp1-s-e
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
oiread	oiread	oiread-N	Ns-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cáit	Cáit	Cáit-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
sibh	sibh	sibh-P	Pp2-p
dul	dul	téigh-N	Ncmsc|Nv
isteach	isteach	isteach-R	Rd
anois	anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daid	Daid	Daid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
tabhair	tabhair	tabhair-V	Vmm-2s
dom	dom	do-P	Pr1-s
an	an	an-T	Td-s
tseanliathróid	tseanliathróid	liathróid-N	Ncfsc
sin	sin	sin-D	Dd
.	.	.-F	Fe
’	’	’-F	Fa
Thug	Thug	tabhair-V	Vmis
Eoin	Eoin	Eoin-N	Npmsc
an	an	an-T	Td-s
liathróid	liathróid	liathróid-N	Ncfsc
do	do	do-S	Sp
Dhaid	Dhaid	Daid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
a	a	a-U	Uv
Dhaid	Dhaid	Daid-N	Npm-v
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
,	,	,-F	Fi
‘	‘	‘-X	Xx
is	is	is-W	Wpri
é	é	é-P	Pp3ms
Daideo	Daideo	daideo-N	Ncmsc
…	…	…-F	Fi
’	’	’-F	Fa
Ná	Ná	ná-Q	Qnm
bac	bac	bac-V	Vmm-2s-n
le	le	le-S	Sp
Daideo	Daideo	daideo-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
bac	bac	bac-V	Vmm-2s-n
le	le	le-S	Sp
Daideo	Daideo	daideo-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daid	Daid	Daid-N	Npmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
ach	ach	ach-C	Cs
isteach	isteach	isteach-R	Rd
libh	libh	le-P	Pr2-p
anois	anois	anois-R	Rt
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
Daideo	Daideo	daideo-N	Ncmsc
imithe	imithe	imigh-A	Av
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Liam	Liam	Liam-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Eoin	Eoin	Eoin-N	Npmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
ach	ach	ach-C	Cs
fan	fan	fan-V	Vmm-2s
go	go	go-Q	Q
bhfaighidh	bhfaighidh	faigh-V	Vmif---d
mise	mise	mé-P	Pp1-s-e
greim	greim	greim-N	Ncmsc
air	air	ar-P	Pr3ms
!	!	!-F	Fe
’	’	’-F	Fa
