Seo	Seo	seo-W	W
é	é	é-P	Pp3ms
Liam	Liam	Liam-N	Npmsc
ar	ar	ar-S	Sp
chúl	chúl	cúl-N	Ncmsc
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
.	.	.-F	Fe
Seo	Seo	seo-W	W
í	í	í-P	Pp3fs
Cáit	Cáit	Cáit-N	Npfsc
ar	ar	is-W	Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
rothar	rothar	rothar-N	Ncmsc
buí	buí	buí-A	Aqp
.	.	.-F	Fe
Seo	Seo	seo-W	W
í	í	í-P	Pp3fs
Mam	Mam	mam-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhfón	bhfón	fón-N	Ncmsc
.	.	.-F	Fe
Seo	Seo	seo-W	W
é	é	é-P	Pp3ms
Eoin	Eoin	Eoin-N	Npmsc
ar	ar	is-W	Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
thóin	thóin	tóin-N	Ncfsc
.	.	.-F	Fe
Seo	Seo	seo-W	W
é	é	é-P	Pp3ms
Daid	Daid	Daid-N	Npmsc
le	le	le-S	Sp
huirlisí	huirlisí	uirlis-N	Ncfpc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
.	.	.-F	Fe
Seo	Seo	seo-W	W
í	í	í-P	Pp3fs
Mamó	Mamó	mamó-N	Ncfsc
ar	ar	is-W	Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
tarracóir	tarracóir	tarracóir-N	Ncmsc
.	.	.-F	Fe
Seo	Seo	seo-W	W
é	é	é-P	Pp3ms
Hiúdaí	Hiúdaí	Hiúdaí-N	Npmsc
ina	ina	i-S	Spp-s|Spp-p
luí	luí	luí-N	Ncmsc
.	.	.-F	Fe
Seo	Seo	seo-W	W
é	é	é-P	Pp3ms
Daideo	Daideo	daideo-N	Ncmsc
ina	ina	i-S	Spp-s
shuí	shuí	suí-N	Ncmsc
.	.	.-F	Fe
