Chuaigh	Chuaigh	téigh-V	Vmis
Cití	Cití	Cití-N	Npfsc
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
seomra	seomra	seomra-N	Ncmsc
codlata	codlata	codail-A	Av
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
scáthán	scáthán	scáthán-N	Ncmsc
sa	sa	i-S	Spa-s
seomra	seomra	seomra-N	Ncmsc
codlata	codlata	codail-A	Av
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
Cití	Cití	Cití-N	Npfsc
cat	cat	cat-X	Xfen|Ncmsc
eile	eile	eile-D	Dd
sa	sa	i-S	Spa-s
scáthán	scáthán	scáthán-N	Ncmsc
.	.	.-F	Fe
Léim	Léim	léim-V	Vmip1s|Vmis|Ncfsc
Cití	Cití	Cití-N	Npf-g|Npfsc
suas	suas	suas-R	Rd
san	san	sin-S	Spa-s|Pd
aer	aer	aer-N	Ncmpg|Ncmsc
.	.	.-F	Fe
Léim	Léim	léim-V	Vmip1s|Vmm-2s|Vmis
an	an	an-T	Td-s
cat	cat	cat-N	Ncmsc
eile	eile	eile-D	Dd
suas	suas	suas-R	Rd
san	san	sin-S	Spa-s|Pd
aer	aer	aer-N	Ncmpg|Ncmsc
.	.	.-F	Fe
Shuigh	Shuigh	suigh-V	Vmis
Cití	Cití	Cití-N	Npfsc
síos	síos	síos-R	Rd
.	.	.-F	Fe
Shuigh	Shuigh	suigh-V	Vmis
an	an	an-T	Td-s
cat	cat	cat-N	Ncmsc
eile	eile	eile-D	Dd
síos	síos	síos-R	Rd
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
Cití	Cití	Cití-N	Npfsc
a	a	a-D	Dp3
cosa	cosa	cos-N	Ncfpc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
scáthán	scáthán	scáthán-N	Ncmsc
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
an	an	an-T	Td-s
cat	cat	cat-N	Ncmsc
eile	eile	eile-D	Dd
a	a	a-D	Dp3
chosa	chosa	cos-N	Ncfpc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
scáthán	scáthán	scáthán-N	Ncmsc
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
Cití	Cití	Cití-N	Npfsc
a	a	a-D	Dp3
srón	srón	srón-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
scáthán	scáthán	scáthán-N	Ncmsc
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
an	an	an-T	Td-s
cat	cat	cat-N	Ncmsc
eile	eile	eile-D	Dd
a	a	a-D	Dp3
shrón	shrón	srón-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
scáthán	scáthán	scáthán-N	Ncmsc
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
Cití	Cití	Cití-N	Npfsc
cuma	cuma	cuma-A	Aqp
throda	throda	troid-N	Ncfsg|Nv--g
uirthi	uirthi	ar-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
an	an	an-T	Td-s
cat	cat	cat-N	Ncmsc
eile	eile	eile-D	Dd
cuma	cuma	cuma-N	Ncfsc
throda	throda	troid-N	Ncfsg|Nv--g
air	air	ar-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
Baineadh	Baineadh	bain-V	Vmis0
geit	geit	geit-N	Ncfsc
as	as	as-S	Sp
Cití	Cití	Cití-N	Npfsc
.	.	.-F	Fe
Baineadh	Baineadh	bain-V	Vmis0
geit	geit	geit-N	Ncfsc
as	as	as-S	Sp
an	an	an-T	Td-s
gcat	gcat	cat-N	Ncmsc
eile	eile	eile-D	Dd
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
Cití	Cití	Cití-N	Npfsc
ag	ag	ag-S	Sp
troid	troid	troid-N	Nv
leis	leis	le-S	Sp
an	an	an-T	Td-s
gcat	gcat	cat-N	Ncmsc
sa	sa	i-S	Spa-s
scáthán	scáthán	scáthán-N	Ncmsc
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
an	an	an-T	Td-s
cat	cat	cat-N	Ncmsc
sa	sa	i-S	Spa-s
scáthán	scáthán	scáthán-N	Ncmsc
ag	ag	ag-S	Sp
troid	troid	troid-N	Nv
le	le	le-S	Sp
Cití	Cití	Cití-N	Npfsc
.	.	.-F	Fe
Go	Go	go-U	Ua
tobann	tobann	tobann-A	Aqp
thit	thit	tit-V	Vmis
an	an	an-T	Td-s
scáthán	scáthán	scáthán-N	Ncmsc
!	!	!-F	Fe
Rith	Rith	rith-V	Vmm-2s|Vmis
Daidí	Daidí	daidí-N	Ncmsc
isteach	isteach	isteach-R	Rd
.	.	.-F	Fe
Lig	Lig	lig-V	Vmis
sé	sé	sé-P	Pp3msn
béic	béic	béic-N	Ncfsc
as	as	as-P	Pr3ms
.	.	.-F	Fe
Cé	Cé	cé-P	Pq
a	a	a-Q	Q-r
bhris	bhris	bris-V	Vmis
an	an	an-T	Td-s
scáthán	scáthán	scáthán-N	Ncmsc
?	?	?-F	Fq
‘	‘	‘-X	Xx
Cé	Cé	cé-P	Pq
a	a	a-Q	Q-r
bhris	bhris	bris-V	Vmis
an	an	an-T	Td-s
scáthán	scáthán	scáthán-N	Ncmsc
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
cá	cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
an	an	an-T	Td-s
cat	cat	cat-N	Ncmsc
eile	eile	eile-D	Dd
?	?	?-F	Fq
Chuaigh	Chuaigh	téigh-V	Vmis
Cití	Cití	Cití-N	Npfsc
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
seomra	seomra	seomra-N	Ncmsc
codlata	codlata	codail-A	Av
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
scáthán	scáthán	scáthán-N	Ncmsc
sa	sa	i-S	Spa-s
seomra	seomra	seomra-N	Ncmsc
codlata	codlata	codail-A	Av
…	…	…-F	Fi
