A	A	a-U	Uv
Dhaidí	Dhaidí	daidí-N	Ncmsv
!	!	!-F	Fe
A	A	a-U	Uv
Dhaidí	Dhaidí	daidí-N	Ncmsv
,	,	,-F	Fi
cá	cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
?	?	?-F	Fq
Bú	Bú	bú-N	Ncmsc
!	!	!-F	Fe
Hú	Hú	Hú-N	Npmsc
!	!	!-F	Fe
Hú	Hú	Hú-N	Npmsc
!	!	!-F	Fe
An	An	an-Q	Qq
bhfaca	bhfaca	feic-V	Vmis---d
tú	tú	tú-P	Pp2-s
Daidí	Daidí	daidí-N	Ncmsc
?	?	?-F	Fq
Cén	Cén	cé-W	W--q
t-ainm	t-ainm	ainm-N	Ncmsc
atá	atá	bí-V	Vmip---r
air	air	ar-P	Pr3ms
?	?	?-F	Fq
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
An	An	is-W	Wp-q
fear	fear	fear-N	Ncmsc
ard	ard	ard-A	Aq-msc
é	é	é-P	Pp3ms
do	do	do-S	Sp
Dhaidí	Dhaidí	daidí-N	Ncmsc
?	?	?-F	Fq
Is	Is	is-W	Wp-i
ea	ea	ea-P	Pp3-s
.	.	.-F	Fe
Ab	Ab	is-W	Wsri
in	in	sin-P	Pd
é	é	é-P	Pp3ms
do	do	do-S	Sp
Dhaidí	Dhaidí	daidí-N	Ncmsc
?	?	?-F	Fq
Ní	Ní	is-W	Wp-in
hé	hé	é-P	Pp3ms
.	.	.-F	Fe
An	An	is-W	Wp-q
fear	fear	fear-N	Ncmsc
caol	caol	caol-A	Aq-msc
é	é	é-P	Pp3ms
do	do	do-S	Sp
Dhaidí	Dhaidí	daidí-N	Ncmsc
?	?	?-F	Fq
Is	Is	is-W	Wp-i
ea	ea	ea-P	Pp3-s
.	.	.-F	Fe
Fear	Fear	fear-N	Ncmsc
caol	caol	caol-A	Aq-msc
ard	ard	ard-A	Aq-msc
.	.	.-F	Fe
Ab	Ab	is-W	Wsri
in	in	sin-P	Pd
é	é	é-P	Pp3ms
do	do	do-S	Sp
Dhaidí	Dhaidí	daidí-N	Ncmsc
?	?	?-F	Fq
Ní	Ní	is-W	Wp-in
hé	hé	é-P	Pp3ms
.	.	.-F	Fe
Cén	Cén	cé-W	W--q
dath	dath	dath-N	Ncmsc
atá	atá	bí-V	Vmip---r
ar	ar	ar-S	Sp
ghruaig	ghruaig	gruaig-N	Ncfsc
do	do	do-S	Sp
Dhaidí	Dhaidí	daidí-N	Ncmsc
?	?	?-F	Fq
Rua	Rua	Rua-N	Npmsc
.	.	.-F	Fe
Fear	Fear	fear-N	Ncmsc
caol	caol	caol-A	Aq-msc
ard	ard	ard-A	Aq-msc
rua	rua	rua-A	Aqp
.	.	.-F	Fe
Ab	Ab	is-W	Wsri
in	in	sin-P	Pd
é	é	é-P	Pp3ms
do	do	do-S	Sp
Dhaidí	Dhaidí	daidí-N	Ncmsc
?	?	?-F	Fq
Ní	Ní	is-W	Wp-in
hé	hé	é-P	Pp3ms
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
cóta	cóta	cóta-N	Ncmsc
ar	ar	ar-N	Ncmsc|Sp
mo	mo	mo-D	Dp1-s
Dhaidíse	Dhaidíse	daidí-N	Ncmsc-e
.	.	.-F	Fe
Fear	Fear	fear-N	Ncmsc
caol	caol	caol-A	Aq-msc
ard	ard	ard-A	Aq-msc
rua	rua	rua-A	Aqp
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
cóta	cóta	cóta-N	Ncmsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Ab	Ab	is-W	Wsri
in	in	sin-P	Pd
é	é	é-P	Pp3ms
do	do	do-S	Sp
Dhaidí	Dhaidí	daidí-N	Ncmsc
?	?	?-F	Fq
Ní	Ní	is-W	Wp-in
hé	hé	é-P	Pp3ms
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
caipín	caipín	caipín-N	Ncmsc
ar	ar	ar-N	Ncmsc|Sp
mo	mo	mo-D	Dp1-s
Dhaidíse	Dhaidíse	daidí-N	Ncmsc-e
.	.	.-F	Fe
Fear	Fear	fear-N	Ncmsc
caol	caol	caol-A	Aq-msc
ard	ard	ard-A	Aq-msc
rua	rua	rua-A	Aqp
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
cóta	cóta	cóta-N	Ncmsc
agus	agus	agus-C	Cc
caipín	caipín	caipín-N	Ncmsg|Ncmsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Ab	Ab	is-W	Wsri
in	in	sin-P	Pd
é	é	é-P	Pp3ms
do	do	do-S	Sp
Dhaidí	Dhaidí	daidí-N	Ncmsc
?	?	?-F	Fq
Is	Is	is-W	Wp-i
é	é	é-P	Pp3ms
!	!	!-F	Fe
Is	Is	is-W	Wp-i
é	é	é-P	Pp3ms
!	!	!-F	Fe
Buíochas	Buíochas	buíochas-N	Ncmsc
le	le	le-S	Sp
Dia	Dia	dia-N	Ncmsc
!	!	!-F	Fe
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
maith	maith	maith-N	Ncfsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Gharda	Gharda	garda-N	Ncmsv
.	.	.-F	Fe
Yipí	Yipí	Yipí-X	Xf
!	!	!-F	Fe
