A	A	a-U	Uv
Liam	Liam	Liam-N	Npm-v
!	!	!-F	Fe
A	A	a-U	Uv
Liam	Liam	Liam-N	Npm-v
,	,	,-F	Fi
tá	tá	bí-V	Vmip
sneachta	sneachta	sneachta-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
talamh	talamh	talamh-N	Ncfsc
.	.	.-F	Fe
Ó	Ó	Ó-I	I
!	!	!-F	Fe
Is	Is	is-W	Wp-i
maith	maith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
an	an	an-T	Td-s
sneachta	sneachta	sneachta-N	Ncmsc
.	.	.-F	Fe
A	A	a-U	Uv
Mham	Mham	mam-N	Ncfsv
!	!	!-F	Fe
A	A	a-U	Uv
Mham	Mham	mam-N	Ncfsv
,	,	,-F	Fi
tá	tá	bí-V	Vmip
sneachta	sneachta	sneachta-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
talamh	talamh	talamh-N	Ncfsc
.	.	.-F	Fe
Ó	Ó	Ó-I	I
!	!	!-F	Fe
Is	Is	is-W	Wp-i
maith	maith	maith-A	Aqp
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
sneachta	sneachta	sneachta-N	Ncmsc
.	.	.-F	Fe
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
cótaí	cótaí	cóta-N	Ncmpc
oraibh	oraibh	ar-P	Pr2-p
?	?	?-F	Fq
Tá	Tá	bí-V	Vmip
.	.	.-F	Fe
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
hataí	hataí	hata-N	Ncmpc
oraibh	oraibh	ar-P	Pr2-p
?	?	?-F	Fq
Tá	Tá	bí-V	Vmip
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
an	an	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
lámhainní	lámhainní	lámhainn-N	Ncfpc
oraibh	oraibh	ar-P	Pr2-p
?	?	?-F	Fq
Tá	Tá	bí-V	Vmip
.	.	.-F	Fe
Amach	Amach	amach-R	Rd
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
Seo	Seo	seo-W	W
fear	fear	fear-N	Ncmsc
sneachta	sneachta	sneachta-N	Ncmsc
breá	breá	breá-A	Aq-msc
.	.	.-F	Fe
Amach	Amach	amach-R	Rd
le	le	le-S	Sp
Cáit	Cáit	Cáit-N	Npfsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
liathróid	liathróid	liathróid-N	Ncfsc
bhreá	bhreá	breá-A	Aq-fsc
déanta	déanta	déan-A	Av
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
Ó	Ó	Ó-I	I
,	,	,-F	Fi
a	a	a-U	Uv
Cháit	Cháit	Cáit-N	Npf-v
!	!	!-F	Fe
Anois	Anois	anois-R	Rt
an	an	is-W	Wpdq|Wp-q
maith	maith	maith-A	Aqp
le	le	le-S	Sp
Mam	Mam	mam-N	Ncfsc
an	an	an-T	Td-s
sneachta	sneachta	sneachta-N	Ncmsg
?	?	?-F	Fq
