‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
é	é	é-P	Pp3ms
seo	seo	seo-P	Pd
an	an	an-T	Td-s
chéad	chéad	céad-M	Mo
lá	lá	lá-N	Ncmsc
agam	agam	ag-P	Pr1-s
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
ar	ar	ar-S	Sp
scoil	scoil	scoil-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Sibéal	Sibéal	Sibéal-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
cailín	cailín	cailín-N	Ncmsc
mór	mór	mór-A	Aq-msc
anois	anois	anois-R	Rt
mé	mé	mé-P	Pp1-s
.	.	.-F	Fe
’	’	’-F	Fa
Is	Is	is-W	Wp-i
cailín	cailín	cailín-N	Ncmsc
mór	mór	mór-A	Aq-msc
anois	anois	anois-R	Rt
mé	mé	mé-P	Pp1-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
mála	mála	mála-N	Ncmsc
scoile	scoile	scoil-N	Ncfsg
uaim	uaim	ó-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Sibéal	Sibéal	Sibéal-N	Npfsc
le	le	le-S	Sp
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
.	.	.-F	Fe
Beidh	Beidh	bí-V	Vmif
mála	mála	mála-N	Ncmsc
scoile	scoile	scoil-N	Ncfsg
uaim	uaim	ó-P	Pr1-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
anseo	anseo	anseo-R	Rl
agam	agam	ag-P	Pr1-s
duit	duit	do-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
stóirín	stóirín	stór-N	Ncmsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Slán	Slán	slán-N	Ncmsc
,	,	,-F	Fi
a	a	a-U	Uv
Mhamaí	Mhamaí	mama-N	Ncfsv|Ncmpv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Sibéal	Sibéal	Sibéal-N	Npfsc
agus	agus	agus-C	Cc
amach	amach	amach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
cara	cara	cara-N	Ncmsc
Aoife	Aoife	Aoife-N	Npf-g|Npfsc
ag	ag	ag-S	Sp
fanacht	fanacht	fan-N	Nv
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Síos	Síos	síos-R	Rd
an	an	an-T	Td-s
bóthar	bóthar	bóthar-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbeirt	mbeirt	beirt-N	Ncfsc
acu	acu	ag-P	Pr3-p
go	go	go-U	Ua
sona	sona	sona-A	Aqp
sásta	sásta	sásta-A	Aqp
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
siad	siad	siad-P	Pp3-pn
an	an	an-T	Td-s
múinteoir	múinteoir	múinteoir-N	Ncmsc
ag	ag	ag-S	Sp
geata	geata	geata-N	Ncmsc
na	na	na-T	Tdfsg
scoile	scoile	scoil-N	Ncfsg
.	.	.-F	Fe
Is	Is	is-W	Wp-i
mise	mise	mé-P	Pp1-s-e
an	an	an-T	Td-s
Múinteoir	Múinteoir	múinteoir-N	Ncmsc
Máire	Máire	Máire-N	Npf-g|Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Fáilte	Fáilte	fáilte-N	Ncfsc
romhaibh	romhaibh	roimh-P	Pr2-p
go	go	go-S	Sp
Scoil	Scoil	scoil-N	Ncfsc
na	na	na-T	Tdfsg
Sí	Sí	is-W	Wp-i-3
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
múinteoir	múinteoir	múinteoir-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
mise	mise	mé-P	Pp1-s-e
an	an	an-T	Td-s
Múinteoir	Múinteoir	múinteoir-N	Ncmsc
Máire	Máire	Máire-N	Npf-g|Npfsc
.	.	.-F	Fe
’	’	’-F	Fa
Thug	Thug	tabhair-V	Vmis
an	an	an-T	Td-s
múinteoir	múinteoir	múinteoir-N	Ncmsc
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
acu	acu	ag-P	Pr3-p
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
seomra	seomra	seomra-N	Ncmsc
ranga	ranga	rang-N	Ncmsg
.	.	.-F	Fe
Is	Is	is-W	Wp-i
maith	maith	maith-A	Aqp
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
scoil	scoil	scoil-N	Ncfsc
seo	seo	seo-D	Dd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
maith	maith	maith-A	Aqp
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
scoil	scoil	scoil-N	Ncfsc
seo	seo	seo-D	Dd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Sibéal	Sibéal	Sibéal-N	Npfsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
tháinig	tháinig	tar-V	Vmis
sióga	sióga	sióg-N	Ncfpc
eile	eile	eile-D	Dd
isteach	isteach	isteach-R	Rd
.	.	.-F	Fe
Is	Is	is-W	Wp-i
mise	mise	mé-P	Pp1-s-e
an	an	an-T	Td-s
Múinteoir	Múinteoir	múinteoir-N	Ncmsc
Máire	Máire	Máire-N	Npf-g|Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Fáilte	Fáilte	fáilte-N	Ncfsc
romhaibh	romhaibh	roimh-P	Pr2-p
go	go	go-S	Sp
Scoil	Scoil	scoil-N	Ncfsc
na	na	na-T	Tdfsg
Sí	Sí	is-W	Wp-i-3
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Múinteoir	Múinteoir	múinteoir-N	Ncmsc
Máire	Máire	Máire-N	Npf-g|Npfsc
leis	leis	le-S	Sp
na	na	na-T	Td-p
sióga	sióga	sióg-N	Ncfpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
mise	mise	mé-P	Pp1-s-e
an	an	an-T	Td-s
Múinteoir	Múinteoir	múinteoir-N	Ncmsc
Máire	Máire	Máire-N	Npf-g|Npfsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Anois	Anois	anois-R	Rt
beidh	beidh	bí-V	Vmif
ceacht	ceacht	ceacht-N	Ncmsc
eitilte	eitilte	eitil-A	Av
againn	againn	ag-P	Pr1-p
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Múinteoir	Múinteoir	múinteoir-N	Ncmsc
Máire	Máire	Máire-N	Npf-g|Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
mar	mar	mar-S	Sp
seo	seo	seo-P	Pd
a	a	a-Q	Q-r
dhéantar	dhéantar	déan-V	Vmip0
é	é	é-P	Pp3ms
,	,	,-F	Fi
’	’	’-F	Fa
agus	agus	agus-C	Cc
shín	shín	sín-V	Vmis
sí	sí	sí-P	Pp3fsn
amach	amach	amach-R	Rd
a	a	a-D	Dp3
sciatháin	sciatháin	sciathán-N	Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	a-U	Um
haon	haon	aon-M	Mc
,	,	,-F	Fi
a	a	a-U	Um
dó	dó	dó-M	Mc
,	,	,-F	Fi
a	a	a-U	Um
trí	trí	trí-M	Mc
.	.	.-F	Fe
Tosaígí	Tosaígí	tosaigh-V	Vmm-2p
.	.	.-F	Fe
’	’	’-F	Fa
.	.	.-F	Fe
.	.	.-F	Fe
A	A	a-U	Um
haon	haon	aon-M	Mc
,	,	,-F	Fi
a	a	a-U	Um
dó	dó	dó-M	Mc
,	,	,-F	Fi
a	a	a-U	Um
trí	trí	trí-M	Mc
.	.	.-F	Fe
Tosaígí	Tosaígí	tosaigh-V	Vmm-2p
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
na	na	na-T	Td-p
sióga	sióga	sióg-N	Ncfpc
eile	eile	eile-D	Dd
ag	ag	ag-S	Sp
eitilt	eitilt	eitil-N	Nv
ach	ach	ach-C	Cs
d	d	d-X	Xl
’	’	’-F	Fa
fhan	fhan	fan-V	Vmis
Sibéal	Sibéal	Sibéal-N	Npfsc
ina	ina	i-S	Spp-p|Spp-s
suí	suí	suí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Sín	Sín	Sín-N	Npfsc
amach	amach	amach-R	Rd
do	do	do-S	Sp
sciatháin	sciatháin	sciathán-N	Ncmpc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Aoife	Aoife	Aoife-N	Npfsc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Bú	Bú	bú-N	Ncmsc
!	!	!-F	Fe
Hú	Hú	Hú-N	Npmsc
!	!	!-F	Fe
Hú	Hú	Hú-N	Npmsc
!	!	!-F	Fe
‘	‘	‘-X	Xx
Nach	Nach	nach-Q	Qnr|Qnq
bhfuil	bhfuil	bí-V	Vmip---d|Vmip---n
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
eitilt	eitilt	eitil-N	Nv
,	,	,-F	Fi
a	a	a-U	Uv
Shibéal	Shibéal	Sibéal-N	Npf-v
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
múinteoir	múinteoir	múinteoir-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bú	Bú	bú-N	Ncmsc
!	!	!-F	Fe
Hú	Hú	Hú-N	Npmsc
!	!	!-F	Fe
Hú	Hú	Hú-N	Npmsc
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Sibéal	Sibéal	Sibéal-N	Npfsc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
fhan	fhan	fan-V	Vmis
sí	sí	sí-P	Pp3fsn
ina	ina	i-S	Spp-p|Spp-s
suí	suí	suí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Sín	Sín	Sín-N	Npfsc
amach	amach	amach-R	Rd
do	do	do-S	Sp
sciatháin	sciatháin	sciathán-N	Ncmpc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
múinteoir	múinteoir	múinteoir-N	Ncmsc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bú	Bú	bú-N	Ncmsc
!	!	!-F	Fe
Hú	Hú	Hú-N	Npmsc
!	!	!-F	Fe
Hú	Hú	Hú-N	Npmsc
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Sibéal	Sibéal	Sibéal-N	Npfsc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
fhan	fhan	fan-V	Vmis
sí	sí	sí-P	Pp3fsn
ina	ina	i-S	Spp-p|Spp-s
suí	suí	suí-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Síle	Síle	Síle-N	Ncfsc|Npfsc
Sióg	Sióg	sióg-N	Ncfsc|Ncfpg
ag	ag	ag-S	Sp
eitilt	eitilt	eitil-N	Nv
thar	thar	thar-S	Sp
bráid	bráid	bráid-N	Ncfsc
.	.	.-F	Fe
Ai	Ai	Ai-N	Npmsc
…	…	…-F	Fi
tiú	tiú	tiú-A	Aq
!	!	!-F	Fe
Baineadh	Baineadh	bain-V	Vmis0
geit	geit	geit-N	Ncfsc
as	as	as-S	Sp
Sibéal	Sibéal	Sibéal-N	Npfsc
.	.	.-F	Fe
Shín	Shín	Sín-N	Npfsc
sí	sí	sí-P	Pp3fsn
amach	amach	amach-R	Rd
a	a	a-D	Dp3
sciatháin	sciatháin	sciathán-N	Ncmpc
AGUS	AGUS	agus-C	Cc
…	…	…-F	Fi
Thosaigh	Thosaigh	tosaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
eitilt	eitilt	eitil-N	Nv
.	.	.-F	Fe
Ó	Ó	Ó-I	I
!	!	!-F	Fe
Táim	Táim	bí-V	Vmip1s
ag	ag	ag-S	Sp
eitilt	eitilt	eitil-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
!	!	!-F	Fe
Táim	Táim	bí-V	Vmip1s
ag	ag	ag-S	Sp
eitilt	eitilt	eitil-N	Nv
!	!	!-F	Fe
Táim	Táim	bí-V	Vmip1s
ag	ag	ag-S	Sp
eitilt	eitilt	eitil-N	Nv
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Sibéal	Sibéal	Sibéal-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Táim	Táim	bí-V	Vmip1s
ag	ag	ag-S	Sp
eitilt	eitilt	eitil-N	Nv
,	,	,-F	Fi
a	a	a-U	Uv
Aoife	Aoife	Aoife-N	Npf-v
!	!	!-F	Fe
Táim	Táim	bí-V	Vmip1s
ag	ag	ag-S	Sp
eitilt	eitilt	eitil-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Sibéal	Sibéal	Sibéal-N	Npfsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
eitil	eitil	eitil-V	Vmis
sí	sí	sí-P	Pp3fsn
suas	suas	suas-R	Rd
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
eitil	eitil	eitil-V	Vmis
sí	sí	sí-P	Pp3fsn
síos	síos	síos-R	Rd
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
go	go	go-U	Ua
maith	maith	maith-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
go	go	go-U	Ua
maith	maith	maith-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Aoife	Aoife	Aoife-N	Npfsc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
eitil	eitil	eitil-N	Ncfsc
Sibéal	Sibéal	Sibéal-N	Npf-g|Npfsc
soir	soir	soir-A	Aqp
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
eitil	eitil	eitil-V	Vmis
sí	sí	sí-P	Pp3fsn
siar	siar	siar-R	Rd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
go	go	go-U	Ua
maith	maith	maith-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Aoife	Aoife	Aoife-N	Npfsc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Táim	Táim	bí-V	Vmip1s
ag	ag	ag-S	Sp
eitilt	eitilt	eitil-N	Nv
anois	anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Sibéal	Sibéal	Sibéal-N	Npfsc
le	le	le-S	Sp
Síle	Síle	Síle-N	Npfsc|Ncfsc
Sióg	Sióg	sióg-N	Ncfpg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
is	is	is-W	Wp-i
TUSA	TUSA	tú-P	Pp2-s-e
a	a	a-Q	Q-r
chuir	chuir	cuir-V	Vmis
ag	ag	ag-S	Sp
eitilt	eitilt	eitil-N	Nv
mé	mé	mé-P	Pp1-s
.	.	.-F	Fe
’	’	’-F	Fa
Is	Is	is-W	Wp-i
TUSA	TUSA	tú-P	Pp2-s-e
a	a	a-Q	Q-r
chuir	chuir	cuir-V	Vmis
ag	ag	ag-S	Sp
eitilt	eitilt	eitil-N	Nv
mé	mé	mé-P	Pp1-s
.	.	.-F	Fe
Ai	Ai	Ai-N	Npmsc
…	…	…-F	Fi
tiú	tiú	tiú-A	Aq
!	!	!-F	Fe
‘	‘	‘-X	Xx
Ai	Ai	Ai-N	Npmsc
…	…	…-F	Fi
tiú	tiú	tiú-A	Aq
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Síle	Síle	Síle-N	Ncfsc|Npfsc
Sióg	Sióg	sióg-N	Ncfsc|Ncfpg
.	.	.-F	Fe
