‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
linn	linn	le-P	Pr1-p
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
linn	linn	linn-N	Ncfsc
snámha	snámha	snámh-N	Nv--g|Ncmsg
.	.	.-F	Fe
Cuirfidh	Cuirfidh	cuir-V	Vmif
mise	mise	mé-P	Pp1-s-e
ag	ag	ag-S	Sp
snámh	snámh	snámh-N	Nv
thú	thú	tú-P	Pp2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Seona	Seona	Seona-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liom	liom	le-P	Pr1-s
snámh	snámh	snámh-N	Nv
a	a	a-U	U
bheith	bheith	bí-N	Nv
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
.	.	.-F	Fe
Fuair	Fuair	faigh-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
culaith	culaith	culaith-N	Ncfsc
shnámha	shnámha	snámh-N	Nv--g|Ncmsg
,	,	,-F	Fi
hata	hata	hata-N	Ncmsc
snámha	snámha	snámh-N	Nv--g|Ncmsg
agus	agus	agus-C	Cc
spéaclaí	spéaclaí	spéacla-N	Ncmpg|Ncmpc|Ncmpg
snámha	snámha	snámh-N	Nv--g|Ncmsg|Nv--g
.	.	.-F	Fe
Seo	Seo	seo-W	W
linn	linn	le-P	Pr1-p
anois	anois	anois-R	Rt
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
linn	linn	le-P	Pr1-p
anois	anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
mhuinchille	mhuinchille	muinchille-N	Ncfsc
shnámha	shnámha	snámh-N	Nv--g|Ncmsg
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
.	.	.-F	Fe
Cuir	Cuir	cuir-V	Vmm-2s
ort	ort	ar-P	Pr2-s
iad	iad	iad-P	Pp3-p
seo	seo	seo-P	Pd
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
le	le	le-S	Sp
Seona	Seona	Seona-N	Npmsc
sa	sa	i-S	Spa-s
linn	linn	linn-N	Ncfsc
snámha	snámha	snámh-N	Nv--g|Ncmsg
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
le	le	le-S	Sp
Mamó	Mamó	mamó-N	Ncfsc
ina	ina	i-S	Spp-s
diaidh	diaidh	diaidh-N	Ns-s
.	.	.-F	Fe
Tabharfaidh	Tabharfaidh	tabhair-V	Vmif
mise	mise	mé-P	Pp1-s-e
aire	aire	aire-N	Ncmsc|Ncfsc
duit	duit	do-P	Pr2-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tabharfaidh	Tabharfaidh	tabhair-V	Vmif
mise	mise	mé-P	Pp1-s-e
aire	aire	aire-N	Ncmsc|Ncfsc
duit	duit	do-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Mhamó	Mhamó	mamó-N	Ncfsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Seona	Seona	Seona-N	Npmsc
.	.	.-F	Fe
Tosaigh	Tosaigh	tosaigh-V	Vmm-2s
ag	ag	ag-S	Sp
lapadaíl	lapadaíl	lapadaíl-N	Ncfsc
anois	anois	anois-R	Rt
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
ag	ag	ag-S	Sp
lapadaíl	lapadaíl	lapadaíl-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
go	go	go-U	Ua
maith	maith	maith-A	Aqp
,	,	,-F	Fi
a	a	a-U	Uv
Mhamó	Mhamó	mamó-N	Ncfsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Seona	Seona	Seona-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhain	Bhain	bain-V	Vmis
mé	mé	mé-P	Pp1-s
an-sásamh	an-sásamh	sásaigh-N	Ncmsc|Nv
as	as	as-S	Sp
sin	sin	sin-P	Pd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Luigh	Luigh	luigh-V	Vmis
siar	siar	siar-R	Rd
anois	anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Seona	Seona	Seona-N	Npmsc
agus	agus	agus-C	Cc
rug	rug	beir-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
Mhamó	Mhamó	mamó-N	Ncfsc
.	.	.-F	Fe
Tabharfaidh	Tabharfaidh	tabhair-V	Vmif
mise	mise	mé-P	Pp1-s-e
aire	aire	aire-N	Ncmsc|Ncfsc
duit	duit	do-P	Pr2-s
.	.	.-F	Fe
Luigh	Luigh	luigh-V	Vmis|Vmm-2s
Mamó	Mamó	mamó-N	Ncfsc
siar	siar	siar-R	Rd
agus	agus	agus-C	Cc
rug	rug	beir-V	Vmis
Seona	Seona	Seona-N	Npmsc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
go	go	go-U	Ua
maith	maith	maith-A	Aqp
,	,	,-F	Fi
a	a	a-U	Uv
Mhamó	Mhamó	mamó-N	Ncfsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Seona	Seona	Seona-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Luigh	Luigh	luigh-V	Vmis
ar	ar	ar-N	Ncmsc
do	do	do-Q	Q
bholg	bholg	bolg-V	Vmis
anois	anois	anois-R	Rt
agus	agus	agus-C	Cc
tosaigh	tosaigh	tosaigh-V	Vmm-2s
ag	ag	ag-S	Sp
ciceáil	ciceáil	ciceáil-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Seona	Seona	Seona-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tabharfaidh	Tabharfaidh	tabhair-V	Vmif
mise	mise	mé-P	Pp1-s-e
aire	aire	aire-N	Ncmsc|Ncfsc
duit	duit	do-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Mhamó	Mhamó	mamó-N	Ncfsv
.	.	.-F	Fe
’	’	’-F	Fa
Tabharfaidh	Tabharfaidh	tabhair-V	Vmif
mise	mise	mé-P	Pp1-s-e
aire	aire	aire-N	Ncmsc|Ncfsc
duit	duit	do-P	Pr2-s
.	.	.-F	Fe
Luigh	Luigh	luigh-V	Vmis|Vmm-2s
Mamó	Mamó	mamó-N	Ncfsc
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
bolg	bolg	bolg-N	Ncmsc
agus	agus	agus-C	Cc
rug	rug	beir-V	Vmis
Seona	Seona	Seona-N	Npmsc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
ag	ag	ag-S	Sp
ciceáil	ciceáil	ciceáil-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
go	go	go-U	Ua
maith	maith	maith-A	Aqp
,	,	,-F	Fi
a	a	a-U	Uv
Mhamó	Mhamó	mamó-N	Ncfsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Seona	Seona	Seona-N	Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhain	Bhain	bain-V	Vmis
mé	mé	mé-P	Pp1-s
an-sásamh	an-sásamh	sásaigh-N	Ncmsc|Nv
as	as	as-S	Sp
sin	sin	sin-P	Pd
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
Anois	Anois	anois-R	Rt
,	,	,-F	Fi
a	a	a-U	Uv
Mhamó	Mhamó	mamó-N	Ncfsv
,	,	,-F	Fi
caithfidh	caithfidh	caith-V	Vmif
tú	tú	tú-P	Pp2-s
dul	dul	téigh-N	Ncmsc|Nv
faoin	faoin	faoi-S	Spa-s
uisce	uisce	uisce-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Seona	Seona	Seona-N	Npmsc
.	.	.-F	Fe
Tharraing	Tharraing	tarraing-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
a	a	a-D	Dp3
hanáil	hanáil	anáil-N	Ncfsc
agus	agus	agus-C	Cc
síos	síos	síos-R	Rd
léi	léi	le-P	Pr3fs
faoin	faoin	faoi-S	Spa-s
uisce	uisce	uisce-N	Ncmsc
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
cosa	cosa	cos-N	Ncfpc
Sheona	Sheona	Sheona-N	Npmsc
faoin	faoin	faoi-S	Spa-s
uisce	uisce	uisce-N	Ncmsc
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
sí	sí	sí-P	Pp3fsn
cosa	cosa	cos-N	Ncfpc
eile	eile	eile-D	Dd
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
.	.	.-F	Fe
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
?	?	?-F	Fq
‘	‘	‘-X	Xx
A	A	an-T	Td-s
Mhamó	Mhamó	mamó-N	Ncfsc
!	!	!-F	Fe
A	A	a-U	Uv
Mhamó	Mhamó	mamó-N	Ncfsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Seona	Seona	Seona-N	Npmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
cá	cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
?	?	?-F	Fq
’	’	’-F	Fa
Ach	Ach	ach-S	Sp
tásc	tásc	tásc-N	Ncmsc
ná	ná	ná-C	Cs|Cc
tuairisc	tuairisc	tuairisc-N	Ncfsc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ar	ar	ar-S	Sp
Mhamó	Mhamó	mamó-N	Ncfsc
.	.	.-F	Fe
Tharraing	Tharraing	tarraing-V	Vmis
Seona	Seona	Seona-N	Npmsc
a	a	a-D	Dp3
hanáil	hanáil	anáil-N	Ncfsc
agus	agus	agus-C	Cc
síos	síos	síos-R	Rd
léi	léi	le-P	Pr3fs
faoin	faoin	faoi-S	Spa-s
uisce	uisce	uisce-N	Ncmsc
.	.	.-F	Fe
Rug	Rug	beir-V	Vmis
Seona	Seona	Seona-N	Npmsc
ar	ar	ar-S	Sp
Mhamó	Mhamó	mamó-N	Ncfsc
agus	agus	agus-C	Cc
tharraing	tharraing	tarraing-V	Vmis
sí	sí	sí-P	Pp3fsn
aníos	aníos	aníos-R	Rd
í	í	í-P	Pp3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhain	Bhain	bain-V	Vmis
mé	mé	mé-P	Pp1-s
an-sásamh	an-sásamh	sásaigh-N	Ncmsc|Nv
as	as	as-S	Sp
sin	sin	sin-P	Pd
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
Bhain	Bhain	bain-V	Vmis
mé	mé	mé-P	Pp1-s
an-sásamh	an-sásamh	sásaigh-N	Ncmsc|Nv
as	as	as-S	Sp
sin	sin	sin-P	Pd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
in	in	i-S	Sp
am	am	am-N	Ncmsc
againn	againn	ag-P	Pr1-p
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
abhaile	abhaile	abhaile-R	Rd
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Seona	Seona	Seona-N	Npmsc
.	.	.-F	Fe
Bhain	Bhain	bain-V	Vmis
mé	mé	mé-P	Pp1-s
an-sásamh	an-sásamh	sásaigh-N	Ncmsc|Nv
as	as	as-S	Sp
sin	sin	sin-P	Pd
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
abhaile	abhaile	abhaile-R	Rd
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liom	liom	le-P	Pr1-s
snámh	snámh	snámh-N	Nv
a	a	a-U	U
bheith	bheith	bí-N	Nv
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
.	.	.-F	Fe
