‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
bhainne	bhainne	bainne-N	Ncmsc
agam	agam	ag-P	Pr1-s
don	don	do-S	Spa-s
tae	tae	tae-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mama	Mama	mama-N	Ncmsc|Xfen
le	le	le-S	Sp
Róisín	Róisín	Róisín-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
leat	leat	le-P	Pr2-s
síos	síos	síos-R	Rd
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
siopa	siopa	siopa-N	Ncmsc
agus	agus	agus-C	Cc
ceannaigh	ceannaigh	ceannach-V	Vmm-2s|Ncmpc|Ncmsg
lítear	lítear	lítear-N	Ncmpg|Ncmsc|Ncmpg
bainne	bainne	bainne-N	Ncmsg|Ncmsc
dom	dom	do-P	Pr1-s
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
An	An	an-Q	Qq
dtabharfaidh	dtabharfaidh	tabhair-V	Vmif
mé	mé	mé-P	Pp1-s
Sciob	Sciob	sciob-V	Vmis
liom	liom	le-P	Pr1-s
,	,	,-F	Fi
a	a	a-U	Uv
Mhama	Mhama	mama-N	Ncmsv
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tabhair	Tabhair	tabhair-V	Vmm-2s
,	,	,-F	Fi
ach	ach	ach-C	Cs
ná	ná	nach-Q	Qnr
scaoil	scaoil	scaoil-V	Vmm-2s-n
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
siopa	siopa	siopa-N	Ncmsc
é	é	é-P	Pp3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mama	Mama	mama-N	Ncmsc|Xfen
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ceangail	Ceangail	ceangal-N	Ncmpc
taobh amuigh	taobh amuigh	taobh_amuigh-R	Rl
é	é	é-P	Pp3ms
.	.	.-F	Fe
’	’	’-F	Fa
Cheangail	Cheangail	ceangail-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
Sciob	Sciob	sciob-V	Vmis
taobh amuigh	taobh amuigh	taobh_amuigh-R	Rl
den	den	de-S	Spa-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
Fan	Fan	fan-V	Vmm-2s
ansin	ansin	ansin-R	Rt|Rl
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
léi	léi	le-P	Pr3fs
sa	sa	i-S	Spa-s
siopa	siopa	siopa-N	Ncmsc
.	.	.-F	Fe
Lítear	Lítear	lítear-N	Ncmsc
bainne	bainne	bainne-N	Ncmsg|Ncmsc
,	,	,-F	Fi
más	más	má-C	Csw
é	é	é-P	Pp3ms
do	do	do-S	Sp
thoil	thoil	toil-N	Ncfsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
Sciob	Sciob	sciob-V	Vmis
cat	cat	cat-X	Xfen|Ncmsc
ag	ag	ag-S	Sp
doras	doras	doras-N	Ncmsc
an	an	an-T	Td-s
tsiopa	tsiopa	siopa-N	Ncmsg
.	.	.-F	Fe
Grr-rr-rr	Grr-rr-rr	Grr-rr-rr-N	Nc
.	.	.-F	Fe
Tharraing	Tharraing	tarraing-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
téad	téad	téad-N	Ncfsc
.	.	.-F	Fe
Tharraing	Tharraing	tarraing-V	Vmis
sé	sé	sé-P	Pp3msn
arís	arís	arís-R	Rg
í	í	í-P	Pp3fs
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
…	…	…-F	Fi
siúd	siúd	siúd-P	Pd
leis	leis	le-P	Pr3ms
!	!	!-F	Fe
Rith	Rith	rith-N	Ncmsc
Sciob	Sciob	sciob-V	Vmis
i ndiaidh	i ndiaidh	i_ndiaidh-S	Spc
an	an	an-T	Td-s
chait	chait	cat-N	Ncmsg
.	.	.-F	Fe
Mí-abha	Mí-abha	abha-N	Ncfsc
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
siopa	siopa	siopa-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
gcat	gcat	cat-N	Ncmsc
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
le	le	le-S	Sp
Sciob	Sciob	sciob-V	Vmis
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
.	.	.-F	Fe
Leag	Leag	leag-V	Vmis|Vmm-2s
an	an	an-T	Td-s
cat	cat	cat-N	Ncmsc
na	na	na-T	Td-p
calóga	calóga	calóg-N	Ncfpc
arbhair	arbhair	arbhar-N	Ncmsg|Ncmpc|Ncmsg
.	.	.-F	Fe
Leag	Leag	leag-V	Vmm-2s
Sciob	Sciob	sciob-V	Vmis
na	na	na-T	Td-p
brioscaí	brioscaí	briosca-N	Ncmpc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
agam	agam	ag-P	Pr1-s
!	!	!-F	Fe
Cliotar	Cliotar	cliotar-N	Ncmsc
!	!	!-F	Fe
Cleatar	Cleatar	cleatar-N	Ncmsc
!	!	!-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
an	an	an-T	Td-s
siopadóir	siopadóir	siopadóir-N	Ncmsc
róshásta	róshásta	sásta-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	is-W	Wpdq|Wp-q
leatsa	leatsa	le-P	Pr2-s-e
an	an	an-T	Td-s
madra	madra	madra-N	Ncmsc
sin	sin	sin-D	Dd
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
siopadóir	siopadóir	siopadóir-N	Ncmsc
le	le	le-S	Sp
Róisín	Róisín	Róisín-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
liom	liom	le-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhuel	Bhuel	bhuel-X	Xsc
,	,	,-F	Fi
ceangail	ceangail	ceangail-V	Vmm-2s
taobh amuigh	taobh amuigh	taobh_amuigh-R	Rl
é	é	é-P	Pp3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
siopadóir	siopadóir	siopadóir-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
brón	brón	brón-N	Ncmsc
orm	orm	ar-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
siopadóir	siopadóir	siopadóir-N	Ncmsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
brón	brón	brón-N	Ncmsc
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
Sciob	Sciob	sciob-V	Vmis
amach	amach	amach-R	Rd
agus	agus	agus-C	Cc
cheangail	cheangail	ceangail-V	Vmis
sí	sí	sí-P	Pp3fsn
taobh amuigh	taobh amuigh	taobh_amuigh-R	Rl
den	den	de-S	Spa-s
doras	doras	doras-N	Ncmsc
arís	arís	arís-R	Rg
é	é	é-P	Pp3ms
.	.	.-F	Fe
Fan	Fan	fan-V	Vmm-2s
ansin	ansin	ansin-R	Rt|Rl
anois	anois	anois-R	Rt
!	!	!-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
siopa	siopa	siopa-N	Ncmsc
arís	arís	arís-R	Rg
agus	agus	agus-C	Cc
cheannaigh	cheannaigh	ceannaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
bainne	bainne	bainne-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
siopa	siopa	siopa-N	Ncmsc
liomsa	liomsa	le-P	Pr1-s-e
arís	arís	arís-R	Rg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
le	le	le-S	Sp
Sciob	Sciob	sciob-V	Vmis
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
an-dána	an-dána	dána-A	Aqp
.	.	.-F	Fe
