Is	Is	is-W	Wp-i
deas	deas	deas-A	Aqp
an	an	an-T	Td-s
t-éan	t-éan	éan-N	Ncmsc
í	í	í-P	Pp3fs
an	an	an-T	Td-s
spideog	spideog	spideog-N	Ncfsc
.	.	.-F	Fe
Dath	Dath	dath-V	Vmm-2s|Ncmsc
donn	donn	donn-N	Ncmpg|Ncmsc|Aqp|Aq-msc
,	,	,-F	Fi
dath	dath	dath-V	Vmm-2s
dearg	dearg	dearg-N	Ncmsc|Ncfsc
agus	agus	agus-C	Cc
dath	dath	dath-V	Vmm-2s|Ncmsc
bán	bán	bán-N	Ncmpg|Ncmsc|Aqp|Aq-msc
a	a	a-Q	Q-r
bhíonn	bhíonn	bí-V	Vmig
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
need	need	need-X	Xfen
ag	ag	ag-S	Sp
an	an	an-T	Td-s
spideoog	spideoog	spideoog-N	Ncmsc
sa	sa	i-S	Spa-s
chrann	chrann	crann-N	Ncmsc
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
canadh	canadh	can-N	Nv
go	go	go-U	Ua
binn	binn	binn-A	Aqp
.	.	.-F	Fe
Itheann	Itheann	ith-V	Vmip
an	an	an-T	Td-s
spideog	spideog	spideog-N	Ncfsc
péisteanna	péisteanna	péist-N	Ncfpg|Ncfpc
.	.	.-F	Fe
Itheann	Itheann	ith-V	Vmip
sí	sí	sí-P	Pp3fsn
torthaí	torthaí	toradh-N	Ncmpc
.	.	.-F	Fe
Itheann	Itheann	ith-V	Vmip
sí	sí	sí-P	Pp3fsn
síolta	síolta	síol-N	Ncfsc|Ncmpc
.	.	.-F	Fe
Itheann	Itheann	ith-V	Vmip
sí	sí	sí-P	Pp3fsn
feithidí	feithidí	feithid-N	Ncfpc
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
ocras	ocras	ocras-N	Ncmsc
agus	agus	agus-C	Cc
tart	tart	tart-N	Ncmsc|Xfea|Xfen
ar	ar	ar-S	Sp
an	an	an-T	Td-s
spideog	spideog	spideog-N	Ncfsc
sa	sa	i-S	Spa-s
gheimhreadh	gheimhreadh	geimhreadh-N	Ncmsc
.	.	.-F	Fe
Cuireann	Cuireann	cuir-V	Vmip
daoine	daoine	duine-N	Ncmpc
amach	amach	amach-R	Rd
bia	bia	bia-N	Ncmsc
di	di	do-P	Pr3fs
.	.	.-F	Fe
Cuireann	Cuireann	cuir-V	Vmip
daoine	daoine	duine-N	Ncmpc
amach	amach	amach-R	Rd
uisce	uisce	uisce-N	Ncmsc
di	di	do-P	Pr3fs
.	.	.-F	Fe
Is	Is	is-W	Wp-i
maith	maith	maith-A	Aqp
linn	linn	le-P	Pr1-p
an	an	an-T	Td-s
spideog	spideog	spideog-N	Ncfsc
.	.	.-F	Fe
