‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
,	,	,-F	Fi
a	a	a-U	Uv
Liam	Liam	Liam-N	Npm-v
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Eoin	Eoin	Eoin-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Faigh	Faigh	faigh-V	Vmm-2s
do	do	do-S	Sp
shliotar	shliotar	sliotar-N	Ncmsc
agus	agus	agus-C	Cc
beidh	beidh	bí-V	Vmif
cluiche	cluiche	cluiche-N	Ncmsc
iomána	iomána	iomáin-N	Ncfsg|Nv--g
againn	againn	ag-P	Pr1-p
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfaca	bhfaca	feic-V	Vmis---d
tú	tú	tú-P	Pp2-s
mo	mo	mo-D	Dp1-s
shliotar	shliotar	sliotar-N	Ncmsc
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Liam	Liam	Liam-N	Npmsc
le	le	le-S	Sp
Mam	Mam	mam-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mam	Mam	mam-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ar	Ar	ar-Q	Qq-s
chuir	chuir	cuir-V	Vmis
tú	tú	tú-P	Pp2-s
faoin	faoin	faoi-S	Spa-s
gcathaoir	gcathaoir	cathaoir-N	Ncfsc
é	é	é-P	Pp3ms
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Níor	Níor	níor-Q	Qn-s
chuir	chuir	cuir-V	Vmis---n
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Liam	Liam	Liam-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfaca	bhfaca	feic-V	Vmis---d
tú	tú	tú-P	Pp2-s
mo	mo	mo-D	Dp1-s
shliotar	shliotar	sliotar-N	Ncmsc
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Liam	Liam	Liam-N	Npmsc
le	le	le-S	Sp
Daid	Daid	Daid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daid	Daid	Daid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ar	Ar	ar-Q	Qq-s
chuir	chuir	cuir-V	Vmis
tú	tú	tú-P	Pp2-s
taobh	taobh	taobh-N	Ncmsc
thiar	thiar	thiar-R	Rd
den	den	de-S	Spa-s
leaba	leaba	leaba-N	Ncfsc
é	é	é-P	Pp3ms
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Níor	Níor	níor-Q	Qn-s
chuir	chuir	cuir-V	Vmis---n
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Liam	Liam	Liam-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ar	Ar	ar-Q	Qq-s
chuir	chuir	cuir-V	Vmis
tú	tú	tú-P	Pp2-s
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
bhosca	bhosca	bosca-N	Ncmsc
bréagán	bréagán	bréagán-N	Ncmpg|Ncmsc
é	é	é-P	Pp3ms
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cáit	Cáit	Cáit-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níor	Níor	níor-Q	Qn-s
chuir	chuir	cuir-V	Vmis---n
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Liam	Liam	Liam-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nó	Nó	nó-C	Cc
os cionn	os cionn	os_cionn-S	Spc
an	an	an-T	Td-s
chófra	chófra	cófra-N	Ncmsg
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mam	Mam	mam-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níor	Níor	níor-Q	Qn-s
chuir	chuir	cuir-V	Vmis---n
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Liam	Liam	Liam-N	Npmsc
.	.	.-F	Fe
An	An	an-Q	Qq
bhfaca	bhfaca	feic-V	Vmis---d
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
mo	mo	mo-D	Dp1-s
shliotar	shliotar	sliotar-N	Ncmsc
?	?	?-F	Fq
Níl	Níl	bí-V	Vmip---n
sé	sé	sé-P	Pp3msn
faoin	faoin	faoi-S	Spa-s
gcathaoir	gcathaoir	cathaoir-N	Ncfsc
.	.	.-F	Fe
Níl	Níl	bí-V	Vmip---n
sé	sé	sé-P	Pp3msn
taobh	taobh	taobh-N	Ncmsc
thiar	thiar	thiar-R	Rd
den	den	de-S	Spa-s
leaba	leaba	leaba-N	Ncfsc
.	.	.-F	Fe
Níl	Níl	bí-V	Vmip---n
sé	sé	sé-P	Pp3msn
istigh	istigh	istigh-R	Rl
sa	sa	i-S	Spa-s
bhosca	bhosca	bosca-N	Ncmsc
bréagán	bréagán	bréagán-N	Ncmpg|Ncmsc
.	.	.-F	Fe
Níl	Níl	bí-V	Vmip---n
sé	sé	sé-P	Pp3msn
os cionn	os cionn	os_cionn-S	Spc
an	an	an-T	Td-s
chófra	chófra	cófra-N	Ncmsg
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
le	le	le-S	Sp
hEoin	hEoin	hEoin-N	Nc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfuair	bhfuair	faigh-V	Vmis
tú	tú	tú-P	Pp2-s
do	do	do-S	Sp
shliotar	shliotar	sliotar-N	Ncmsc
,	,	,-F	Fi
a	a	a-U	Uv
Liam	Liam	Liam-N	Npm-v
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
Rug	Rug	beir-V	Vmis
Eoin	Eoin	Eoin-N	Npmsc
ar	ar	ar-S	Sp
chamán	chamán	camán-N	Ncmsc
Liam	Liam	Liam-N	Npm-g
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
taobh	taobh	taobh-N	Ncmsc
thiar	thiar	thiar-R	Rd
den	den	de-S	Spa-s
chamán	chamán	camán-N	Ncmsc
chonaic	chonaic	feic-V	Vmis
Liam	Liam	Liam-N	Npmsc
…	…	…-F	Fi
…	…	…-F	Fi
a	a	a-D	Dp3
shliotar	shliotar	sliotar-N	Ncmsc
!	!	!-F	Fe
‘	‘	‘-X	Xx
Sin	Sin	sin-W	W
é	é	é-P	Pp3ms
an	an	an-T	Td-s
áit	áit	áit-N	Ncfsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
mo	mo	mo-D	Dp1-s
shliotar	shliotar	sliotar-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Liam	Liam	Liam-N	Npmsc
agus	agus	agus-C	Cc
amach	amach	amach-R	Rd
leis	leis	le-P	Pr3ms
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
le	le	le-S	Sp
hEoin	hEoin	hEoin-N	Nc
.	.	.-F	Fe
faoin	faoin	faoi-S	Spa-s
gcathaoir	gcathaoir	cathaoir-N	Ncfsc
taobh	taobh	taobh-N	Ncmsc
thiar	thiar	thiar-R	Rd
den	den	de-S	Spa-s
leaba	leaba	leaba-N	Ncfsc
sa	sa	i-S	Spa-s
bhosca	bhosca	bosca-N	Ncmsc
bréagán	bréagán	bréagán-N	Ncmpg|Ncmsc
os cionn	os cionn	os_cionn-S	Spc
an	an	an-T	Td-s
chófra	chófra	cófra-N	Ncmsg
‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
,	,	,-F	Fi
a	a	a-U	Uv
Liam	Liam	Liam-N	Npm-v
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Eoin	Eoin	Eoin-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Faigh	Faigh	faigh-V	Vmm-2s
do	do	do-S	Sp
shliotar	shliotar	sliotar-N	Ncmsc
agus	agus	agus-C	Cc
beidh	beidh	bí-V	Vmif
cluiche	cluiche	cluiche-N	Ncmsc
iomána	iomána	iomáin-N	Ncfsg|Nv--g
againn	againn	ag-P	Pr1-p
.	.	.-F	Fe
’	’	’-F	Fa
