‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
duine	duine	duine-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Oisín	Oisín	Oisín-N	Npmsc
.	.	.-F	Fe
Siúd	Siúd	siúd-P	Pd
amach	amach	amach-R	Rd
le	le	le-S	Sp
Cian	Cian	Cian-N	Npmsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
í	í	í-P	Pp3fs
Aintín	Aintín	aintín-N	Ncfsc
Niamh	Niamh	Niamh-N	Npfsg|Npfsc
atá	atá	bí-V	Vmip---r
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
í	í	í-P	Pp3fs
Aintín	Aintín	aintín-N	Ncfsc
Niamh	Niamh	Niamh-N	Npfsg|Npfsc
atá	atá	bí-V	Vmip---r
ann	ann	i-P	Pr3ms
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
,	,	,-F	Fi
‘	‘	‘-X	Xx
agus	agus	agus-C	Cc
tá	tá	bí-V	Vmip
Cleasaí	Cleasaí	cleasaí-N	Ncmsc
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
’	’	’-F	Fa
Siúd	Siúd	siúd-P	Pd
amach	amach	amach-R	Rd
le	le	le-S	Sp
hOisín	hOisín	Oisín-N	Npmsc
ansin	ansin	ansin-R	Rt|Rl
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tabharfaidh	Tabharfaidh	tabhair-V	Vmif
mé	mé	mé-P	Pp1-s
féin	féin	féan-N	Ncmpc
agus	agus	agus-C	Cc
Cian	Cian	Cian-N	Npm-g|Npmsc
aire	aire	aire-N	Ncmsc|Ncmsg|Ncfsc|Ncfsg
do	do	do-S	Sp
Chleasaí	Chleasaí	cleasaí-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
le	le	le-S	Sp
hAintín	hAintín	aintín-N	Ncfsc
Niamh	Niamh	Niamh-N	Npfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
go	go	go-U	Ua
maith	maith	maith-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Aintín	Aintín	aintín-N	Ncfsc
Niamh	Niamh	Niamh-N	Npfsg|Npfsc
agus	agus	agus-C	Cc
isteach	isteach	isteach-R	Rd
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Chaith	Chaith	caith-V	Vmis
Oisín	Oisín	Oisín-N	Npmsc
agus	agus	agus-C	Cc
Cian	Cian	Cian-N	Npm-g|Npmsc
tamall	tamall	tamall-N	Ncmpg|Ncmsc
amuigh	amuigh	amuigh-R	Rl
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
le	le	le-S	Sp
Cleasaí	Cleasaí	cleasaí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
Aintín	Aintín	aintín-N	Ncfsc
Niamh	Niamh	Niamh-N	Npfsg|Npfsc
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
ar	ar	ar-S	Sp
laethanta	laethanta	lá-N	Ncmpc
saoire	saoire	saoire-N	Ncfsg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
leo	leo	le-P	Pr3-p
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
siad	siad	siad-P	Pp3-pn
isteach	isteach	isteach-R	Rd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
sibhse	sibhse	sibh-P	Pp2-p-e
aire	aire	aire-N	Ncmsc|Ncfsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
do	do	do-S	Sp
Chleasaí	Chleasaí	cleasaí-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Aintín	Aintín	aintín-N	Ncfsc
Niamh	Niamh	Niamh-N	Npfsg|Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
!	!	!-F	Fe
Is	Is	is-W	Wp-i
maith	maith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
tabhairt	tabhairt	tabhair-N	Nv
aire	aire	aire-N	Ncfsg|Ncmsg|Ncfsg
do	do	do-S	Sp
Chleasaí	Chleasaí	cleasaí-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Oisín	Oisín	Oisín-N	Npmsc
.	.	.-F	Fe
Caithfidh	Caithfidh	caith-V	Vmif
sibhse	sibhse	sibh-P	Pp2-p-e
aire	aire	aire-N	Ncmsc|Ncfsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
do	do	do-S	Sp
Chleasaí	Chleasaí	cleasaí-N	Ncmsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
shín	shín	sín-V	Vmis
Aintín	Aintín	aintín-N	Ncfsc
Niamh	Niamh	Niamh-N	Npfsg|Npfsc
iall	iall	iall-N	Ncfsc
Chleasaí	Chleasaí	cleasaí-N	Ncmsg
chucu	chucu	chuig-P	Pr3-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
sibh	sibh	sibh-P	Pp2-p
Cleasaí	Cleasaí	cleasaí-N	Ncmsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
amach	amach	amach-R	Rd
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
ar	ar	ar-S	Sp
maidin	maidin	maidin-N	Ncfsc
agus	agus	agus-C	Cc
arís	arís	arís-R	Rg
tráthnóna	tráthnóna	tráthnóna-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
go	go	go-U	Ua
maith	maith	maith-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cian	Cian	Cian-N	Npmsc
.	.	.-F	Fe
Caithfidh	Caithfidh	caith-V	Vmif
sibh	sibh	sibh-P	Pp2-p
é	é	é-P	Pp3ms
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
amach	amach	amach-R	Rd
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
sibh	sibh	sibh-P	Pp2-p
é	é	é-P	Pp3ms
a	a	a-U	U
ní	ní	nigh-N	Nv
má	má	má-C	Cs
bhíonn	bhíonn	bí-V	Vmig
sé	sé	sé-P	Pp3msn
salach	salach	salach-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Aintín	Aintín	aintín-N	Ncfsc
Niamh	Niamh	Niamh-N	Npfsg|Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
go	go	go-U	Ua
maith	maith	maith-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Oisín	Oisín	Oisín-N	Npmsc
.	.	.-F	Fe
Caithfidh	Caithfidh	caith-V	Vmif
sibh	sibh	sibh-P	Pp2-p
é	é	é-P	Pp3ms
a	a	a-U	U
ní	ní	nigh-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
sibh	sibh	sibh-P	Pp2-p
bia	bia	bia-N	Ncmsc
a	a	a-U	U
chur	chur	cuir-N	Nv
sa	sa	i-S	Spa-s
mhias	mhias	mias-N	Ncfsc
seo	seo	seo-D	Dd
dó	dó	do-P	Pr3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Aintín	Aintín	aintín-N	Ncfsc
Niamh	Niamh	Niamh-N	Npfsg|Npfsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
agus	agus	agus-C	Cc
uisce	uisce	uisce-N	Ncmsc
glan	glan	glan-A	Aq-msc
sa	sa	i-S	Spa-s
mhias	mhias	mias-N	Ncfsc
seo	seo	seo-D	Dd
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
go	go	go-U	Ua
maith	maith	maith-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cian	Cian	Cian-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
deas	deas	deas-A	Aqp
an	an	an-T	Td-s
madra	madra	madra-N	Ncmsc
é	é	é-P	Pp3ms
Cleasaí	Cleasaí	cleasaí-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Oisín	Oisín	Oisín-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
gceannóidh	gceannóidh	ceannaigh-V	Vmif
tú	tú	tú-P	Pp2-s
madra	madra	madra-N	Ncmsc
dúinne	dúinne	do-P	Pr1-p-e
,	,	,-F	Fi
a	a	a-U	Uv
Mhamaí	Mhamaí	mama-N	Ncfsv|Ncmpv
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cian	Cian	Cian-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
B	B	B-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
go	go	go-Q	Q
gceannóidh	gceannóidh	ceannaigh-V	Vmif
sí	sí	sí-P	Pp3fsn
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Aintín	Aintín	aintín-N	Ncfsc
Niamh	Niamh	Niamh-N	Npfsg|Npfsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
má	má	má-C	Cs
thugann	thugann	tabhair-V	Vmip
sibh	sibh	sibh-P	Pp2-p
aire	aire	aire-N	Ncfsc
mhaith	mhaith	maith-A	Aq-fsc
do	do	do-S	Sp
Chleasaí	Chleasaí	cleasaí-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
Is	Is	is-W	Wp-i
deas	deas	deas-A	Aqp
an	an	an-T	Td-s
madra	madra	madra-N	Ncmsc
é	é	é-P	Pp3ms
Cleasaí	Cleasaí	cleasaí-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhág	fhág	fág-V	Vmis
Aintín	Aintín	aintín-N	Ncfsc
Niamh	Niamh	Niamh-N	Npfsc
slán	slán	slán-A	Aqp
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Lá	Lá	lá-N	Ncmsc
maith	maith	maith-A	Aq-msc
agaibh	agaibh	ag-P	Pr2-p
anois	anois	anois-R	Rt
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tabhair	Tabhair	tabhair-V	Vmm-2s
aire	aire	aire-N	Ncfsc
mhaith	mhaith	maith-A	Aq-fsc
do	do	do-S	Sp
Chleasaí	Chleasaí	cleasaí-N	Ncmsc
anois	anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Aintín	Aintín	aintín-N	Ncfsc
Niamh	Niamh	Niamh-N	Npfsg|Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tabharfaidh	Tabharfaidh	tabhair-V	Vmif
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Oisín	Oisín	Oisín-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bain	Bain	bain-N	Npmsc
sásamh	sásamh	sásamh-N	Ncmpg|Nv|Ncmsc
as	as	as-S	Sp
na	na	na-T	Td-p
laethanta	laethanta	lá-N	Ncmpc
saoire	saoire	saoire-N	Ncfsg|Ncfsc
,	,	,-F	Fi
a	a	a-U	Uv
Niamh	Niamh	Niamh-N	Npf-v
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nach	Nach	nach-Q	Qnr|Qnq
bhfuil	bhfuil	bí-V	Vmip---d|Vmip---n
sé	sé	sé-P	Pp3msn
in	in	i-S	Sp
am	am	am-N	Ncmsc
Cleasaí	Cleasaí	cleasaí-N	Ncmsg
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
amach	amach	amach-R	Rd
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Oisín	Oisín	Oisín-N	Npmsc
le	le	le-S	Sp
Cian	Cian	Cian-N	Npmsc
tráthnóna	tráthnóna	tráthnóna-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
ceart	ceart	ceart-N	Ncmsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cian	Cian	Cian-N	Npmsc
.	.	.-F	Fe
Siúd	Siúd	siúd-P	Pd
leo	leo	le-P	Pr3-p
síos	síos	síos-R	Rd
an	an	an-T	Td-s
bóthar	bóthar	bóthar-N	Ncmsc
.	.	.-F	Fe
Tamall	Tamall	tamall-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|Dd
chonaic	chonaic	feic-V	Vmis
Cleasaí	Cleasaí	cleasaí-N	Ncmsc
madra	madra	madra-N	Ncmsc
eile	eile	eile-D	Dd
agus	agus	agus-C	Cc
rith	rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
.	.	.-F	Fe
Léim	Léim	léim-V	Vmip1s|Vmm-2s|Vmis|Ncfsc
an	an	an-T	Td-s
madra	madra	madra-N	Ncmsg|Ncmsc
suas	suas	suas-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbosca	mbosca	bosca-N	Ncmsc
bruscair	bruscair	bruscar-N	Ncmsg|Ncmpc
.	.	.-F	Fe
Léim	Léim	léim-V	Vmip1s|Vmm-2s|Vmis
Cleasaí	Cleasaí	cleasaí-N	Ncmsc
suas	suas	suas-R	Rd
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
agus	agus	agus-C	Cc
…	…	…-F	Fi
…	…	…-F	Fi
leag	leag	leag-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
bosca	bosca	bosca-N	Ncmsc
bruscair	bruscair	bruscar-N	Ncmsg|Ncmpc
!	!	!-F	Fe
Tháinig	Tháinig	tar-V	Vmis
fear	fear	fear-N	Ncmsc
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
amach	amach	amach-R	Rd
agus	agus	agus-C	Cc
lig	lig	lig-V	Vmis
sé	sé	sé-P	Pp3msn
béic	béic	béic-N	Ncfsc
as	as	as-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	is-W	Wpdq|Wp-q
libhse	libhse	le-P	Pr2-p-e
an	an	an-T	Td-s
madra	madra	madra-N	Ncmsc
sin	sin	sin-D	Dd
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
linn	linn	le-P	Pr1-p
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cian	Cian	Cian-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
le	le	le-S	Sp
hAintín	hAintín	aintín-N	Ncfsc
Niamh	Niamh	Niamh-N	Npfsg
é	é	é-P	Pp3ms
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
sí	sí	sí-P	Pp3fsn
imithe	imithe	imigh-A	Av
ar	ar	ar-S	Sp
laethanta	laethanta	lá-N	Ncmpc
saoire	saoire	saoire-N	Ncfsg
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Bhuel	Bhuel	bhuel-X	Xsc
,	,	,-F	Fi
caithfidh	caithfidh	caith-V	Vmif
sibh	sibh	sibh-P	Pp2-p
iall	iall	iall-N	Ncfsc
a	a	a-U	U
chur	chur	cuir-N	Nv
air	air	ar-P	Pr3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
.	.	.-F	Fe
An	An	is-W	Wp-q
libhse	libhse	le-P	Pr2-p-e
an	an	an-T	Td-s
madra	madra	madra-N	Ncmsc
sin	sin	sin-D	Dd
?	?	?-F	Fq
Is	Is	is-W	Wp-i
le	le	le-S	Sp
hAintín	hAintín	aintín-N	Ncfsc
Niamh	Niamh	Niamh-N	Npfsg
é	é	é-P	Pp3ms
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
mó	mó	mó-A	Aqc|Aqp
ná	ná	ná-C	Cs|Cc
sásta	sásta	sásta-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
Aintín	Aintín	aintín-N	Ncfsc
Niamh	Niamh	Niamh-N	Npfsg|Npfsc
róshásta	róshásta	sásta-A	Aqp
libh	libh	le-P	Pr2-p
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nach	Nach	nach-Q	Qnr|Qnq
bhfuil	bhfuil	bí-V	Vmip---d|Vmip---n
sé	sé	sé-P	Pp3msn
in	in	i-S	Sp
am	am	am-N	Ncmsc
Cleasaí	Cleasaí	cleasaí-N	Ncmsg
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
amach	amach	amach-R	Rd
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
,	,	,-F	Fi
a	a	a-U	Uv
bhuachaillí	bhuachaillí	buachaill-N	Ncmpv
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
lá	lá	lá-N	Ncmsc
arna	arna	arna-S	Spc
mhárach	mhárach	márach-N	Ns-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tabharfaidh	Tabharfaidh	tabhair-V	Vmif
Cian	Cian	Cian-N	Npmsc
amach	amach	amach-R	Rd
é	é	é-P	Pp3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Oisín	Oisín	Oisín-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tabharfaidh	Tabharfaidh	tabhair-V	Vmif
Oisín	Oisín	Oisín-N	Npmsc
amach	amach	amach-R	Rd
é	é	é-P	Pp3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cian	Cian	Cian-N	Npmsc
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
mó	mó	mó-A	Aqc|Aqp
ná	ná	ná-C	Cs|Cc
sásta	sásta	sásta-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tabharfaidh	Tabharfaidh	tabhair-V	Vmif
mé	mé	mé-P	Pp1-s
féin	féin	féan-N	Ncmpc
amach	amach	amach-R	Rd
é	é	é-P	Pp3ms
,	,	,-F	Fi
más	más	má-C	Csw
ea	ea	ea-P	Pp3-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Cleasaí	Cleasaí	cleasaí-N	Ncmsc
lofa	lofa	lobh-A	Aqp|Av
salach	salach	salach-A	Aqp
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
sé	sé	sé-P	Pp3msn
ar ais	ar ais	ar_ais-R	Rd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
tú	tú	tú-P	Pp2-s
Cleasaí	Cleasaí	cleasaí-N	Ncmsc
a	a	a-U	U
ní	ní	nigh-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
le	le	le-S	Sp
hOisín	hOisín	Oisín-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nífidh	Nífidh	nigh-V	Vmif
Cian	Cian	Cian-N	Npmsc
é	é	é-P	Pp3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Oisín	Oisín	Oisín-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
tá	tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
lofa	lofa	lobh-A	Aqp|Av
salach	salach	salach-A	Aqp
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cian	Cian	Cian-N	Npmsc
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
mó	mó	mó-A	Aqc|Aqp
ná	ná	ná-C	Cs|Cc
sásta	sásta	sásta-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nífidh	Nífidh	nigh-V	Vmif
mé	mé	mé-P	Pp1-s
féin	féin	féin-P	Px
é	é	é-P	Pp3ms
,	,	,-F	Fi
más	más	má-C	Csw
ea	ea	ea-P	Pp3-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
Nífidh	Nífidh	nigh-V	Vmif
mé	mé	mé-P	Pp1-s
féin	féin	féin-P	Px
é	é	é-P	Pp3ms
,	,	,-F	Fi
más	más	má-C	Csw
ea	ea	ea-P	Pp3-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nach	Nach	nach-Q	Qnr|Qnq
bhfuil	bhfuil	bí-V	Vmip---d|Vmip---n
sé	sé	sé-P	Pp3msn
in	in	i-S	Sp
am	am	am-N	Ncmsc
bia	bia	bia-N	Ncmsg
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
do	do	do-S	Sp
Chleasaí	Chleasaí	cleasaí-N	Ncmsc
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
tamall	tamall	tamall-N	Ncmpg|Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|Dd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
ocras	ocras	ocras-N	Ncmsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Déanfaidh	Déanfaidh	déan-V	Vmif
Oisín	Oisín	Oisín-N	Npmsc
é	é	é-P	Pp3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cian	Cian	Cian-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Déanfaidh	Déanfaidh	déan-V	Vmif
Cian	Cian	Cian-N	Npmsc
é	é	é-P	Pp3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Oisín	Oisín	Oisín-N	Npmsc
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
mó	mó	mó-A	Aqc|Aqp
ná	ná	ná-C	Cs|Cc
sásta	sásta	sásta-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Déanfaidh	Déanfaidh	déan-V	Vmif
mé	mé	mé-P	Pp1-s
féin	féin	féin-P	Px
é	é	é-P	Pp3ms
,	,	,-F	Fi
más	más	má-C	Csw
ea	ea	ea-P	Pp3-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
Cúpla	Cúpla	cúpla-N	Ncmsc|Dq
lá	lá	lá-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|Dd
tháinig	tháinig	tar-V	Vmis
Aintín	Aintín	aintín-N	Ncfsc
Niamh	Niamh	Niamh-N	Npfsg|Npfsc
ar ais	ar ais	ar_ais-R	Rd
óna	óna	ó-S	Spp-s|Spp-p
laethanta	laethanta	lá-N	Ncmpc
saoire	saoire	saoire-N	Ncfsg|Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ar	Ar	ar-Q	Qq-s
thug	thug	tabhair-V	Vmis
sibh	sibh	sibh-P	Pp2-p
aire	aire	aire-N	Ncfsc
mhaith	mhaith	maith-A	Aq-fsc
do	do	do-S	Sp
Chleasaí	Chleasaí	cleasaí-N	Ncmsc
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
Aintín	Aintín	aintín-N	Ncfsc
Niamh	Niamh	Niamh-N	Npfsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
focal	focal	focal-N	Ncmsc
as	as	as-S	Sp
an	an	an-T	Td-s
mbeirt	mbeirt	beirt-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níor	Níor	níor-Q	Qn-s
thug	thug	tabhair-V	Vmis---n
,	,	,-F	Fi
muise	muise	muise-X	Xsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Cleasaí	Cleasaí	cleasaí-N	Ncmsc
an-sásta	an-sásta	sásta-A	Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
Aintín	Aintín	aintín-N	Ncfsc
Niamh	Niamh	Niamh-N	Npfsg|Npfsc
tagtha	tagtha	tar-A	Av
ar ais	ar ais	ar_ais-R	Rd
.	.	.-F	Fe
Bhuf	Bhuf	Bhuf-N	Npmsc
!	!	!-F	Fe
Bhuf	Bhuf	Bhuf-N	Npmsc
!	!	!-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
deas	deas	deas-A	Aqp
an	an	an-T	Td-s
madra	madra	madra-N	Ncmsc
é	é	é-P	Pp3ms
Cleasaí	Cleasaí	cleasaí-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cian	Cian	Cian-N	Npmsc
cúpla	cúpla	cúpla-N	Ncmsg|Ncmsc|Dq
lá	lá	lá-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|Dd
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
gceannóidh	gceannóidh	ceannaigh-V	Vmif
tú	tú	tú-P	Pp2-s
madra	madra	madra-N	Ncmsc
dúinne	dúinne	do-P	Pr1-p-e
,	,	,-F	Fi
a	a	a-U	Uv
Mhamaí	Mhamaí	mama-N	Ncfsv|Ncmpv
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
cé	cé	cé-P	Pq
a	a	a-Q	Q-r
thabharfaidh	thabharfaidh	tabhair-V	Vmif
aire	aire	aire-N	Ncfsc
dó	dó	do-P	Pr3ms
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
focal	focal	focal-N	Ncmsc
as	as	as-S	Sp
an	an	an-T	Td-s
mbeirt	mbeirt	beirt-N	Ncfsc
.	.	.-F	Fe
Cleasaí	Cleasaí	cleasaí-N	Ncmsc
iall	iall	iall-N	Ncfsc
bia	bia	bia-N	Ncmsg|Ncmsc
uisce	uisce	uisce-N	Ncmsg|Ncmsc
‘	‘	‘-X	Xx
An	An	an-Q	Qq
gceannóidh	gceannóidh	ceannaigh-V	Vmif
tú	tú	tú-P	Pp2-s
madra	madra	madra-N	Ncmsc
dúinn	dúinn	do-P	Pr1-p
,	,	,-F	Fi
a	a	a-U	Uv
Mhamaí	Mhamaí	mama-N	Ncfsv|Ncmpv
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
Cian	Cian	Cian-N	Npmsc
.	.	.-F	Fe
