Maidin	Maidin	maidin-N	Ncfsc
amháin	amháin	amháin-A	Aqp
chonaic	chonaic	feic-V	Vmis
Clíodhna	Clíodhna	Clíodhna-N	Np
gráinneog	gráinneog	gráinneog-N	Ncfpg|Ncfsc
sa	sa	i-S	Spa-s
ghairdín	ghairdín	gairdín-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
ghráinneog	ghráinneog	gráinneog-N	Ncfsc
ina	ina	i-S	Spp-s
codladh	codladh	codladh-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	an-T	Td-s
Mhúinteoir	Mhúinteoir	múinteoir-N	Ncmsc
,	,	,-F	Fi
chonaic	chonaic	feic-V	Vmis
mise	mise	mé-P	Pp1-s-e
gráinneog	gráinneog	gráinneog-N	Ncfsc
ar	ar	ar-S	Sp
maidin	maidin	maidin-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Clíodhna	Clíodhna	Clíodhna-N	Np
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agaibh	agaibh	ag-P	Pr2-p
go	go	go-Q	Q
n-itheann	n-itheann	ith-V	Vmip
an	an	an-T	Td-s
ghráinneog	ghráinneog	gráinneog-N	Ncfsc
péisteanna	péisteanna	péist-N	Ncfpg|Ncfpc
agus	agus	agus-C	Cc
froganna	froganna	frog-N	Ncmpg|Ncmpc
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
múinteoir	múinteoir	múinteoir-N	Ncmsc
.	.	.-F	Fe
Péisteanna	Péisteanna	péist-N	Ncfpc
!	!	!-F	Fe
Froganna	Froganna	frog-N	Ncmpc
!	!	!-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
Clíodhna	Clíodhna	Clíodhna-N	Np
abhaile	abhaile	abhaile-R	Rd
ón	ón	ó-S	Spa-s
scoil	scoil	scoil-N	Ncfsc
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
ghráinneog	ghráinneog	gráinneog-N	Ncfsc
fós	fós	fós-R	Rg
sa	sa	i-S	Spa-s
ghairdín	ghairdín	gairdín-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
B	B	B-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
ocras	ocras	ocras-N	Ncmsc
ort	ort	ar-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
ghráinneoigín	ghráinneoigín	gráinneog-N	Ncfsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Clíodhna	Clíodhna	Clíodhna-N	Np
.	.	.-F	Fe
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
ocras	ocras	ocras-N	Ncmsc
ort	ort	ar-P	Pr2-s
?	?	?-F	Fq
Isteach	Isteach	isteach-R	Rd
léi	léi	le-P	Pr3fs
sa	sa	i-S	Spa-s
chistin	chistin	cistin-N	Ncfsc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
cuisneoir	cuisneoir	cuisneoir-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
phéisteanna	phéisteanna	péist-N	Ncfpc
ná	ná	ná-C	Cs|Cc
froganna	froganna	frog-N	Ncmpg|Ncmpc
anseo	anseo	anseo-R	Rl
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Clíodhna	Clíodhna	Clíodhna-N	Np
,	,	,-F	Fi
‘	‘	‘-X	Xx
ach	ach	ach-C	Cs
tá	tá	bí-V	Vmip
barra	barra	barra-N	Ncmsc
seacláide	seacláide	seacláid-N	Ncfsg
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
’	’	’-F	Fa
Tabharfaidh	Tabharfaidh	tabhair-V	Vmif
mé	mé	mé-P	Pp1-s
píosa	píosa	píosa-N	Ncmsc
seacláide	seacláide	seacláid-N	Ncfsg
don	don	do-S	Spa-s
ghráinneog	ghráinneog	gráinneog-N	Ncfsc
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
Clíodhna	Clíodhna	Clíodhna-N	Np
amach	amach	amach-R	Rd
sa	sa	i-S	Spa-s
ghairdín	ghairdín	gairdín-N	Ncmsc
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
sí	sí	sí-P	Pp3fsn
píosa	píosa	píosa-N	Ncmsc
seacláide	seacláide	seacláid-N	Ncfsg
don	don	do-S	Spa-s
ghráinneog	ghráinneog	gráinneog-N	Ncfsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
bia	bia	bia-N	Ncmsc
agam	agam	ag-P	Pr1-s
duit	duit	do-P	Pr2-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
duit	duit	do-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
ghráinneoigín	ghráinneoigín	gráinneog-N	Ncfsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Clíodhna	Clíodhna	Clíodhna-N	Np
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
bia	bia	bia-N	Ncmsc
agam	agam	ag-P	Pr1-s
duit	duit	do-P	Pr2-s
.	.	.-F	Fe
’	’	’-F	Fa
Níor	Níor	níor-Q	Qn-s
ith	ith	ith-V	Vmis---n
sí	sí	sí-P	Pp3fsn
é	é	é-P	Pp3ms
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
amach	amach	amach-R	Rd
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	an-T	Td-s
Mhamaí	Mhamaí	mamaí-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Clíodhna	Clíodhna	Clíodhna-N	Np
,	,	,-F	Fi
‘	‘	‘-X	Xx
thug	thug	tabhair-V	Vmis
mé	mé	mé-P	Pp1-s
píosa	píosa	píosa-N	Ncmsc
seacláide	seacláide	seacláid-N	Ncfsg
don	don	do-S	Spa-s
ghráinneog	ghráinneog	gráinneog-N	Ncfsc
ach	ach	ach-C	Cs
níor	níor	is-W	Ws-in
ith	ith	ith-V	Vmis
sí	sí	sí-P	Pp3fsn
é	é	é-P	Pp3ms
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
tá	tá	bí-V	Vmip
an	an	an-T	Td-s
ghráinneog	ghráinneog	gráinneog-N	Ncfsc
ina	ina	i-S	Spp-s
codladh	codladh	codladh-N	Ncfsc
,	,	,-F	Fi
a	a	a-U	Uv
stóirín	stóirín	stór-N	Ncmsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
Clíodhna	Clíodhna	Clíodhna-N	Np
a	a	a-U	U
chodladh	chodladh	codail-N	Nv
go	go	go-U	Ua
luath	luath	luath-A	Aqp
an	an	an-T	Td-s
oíche	oíche	oíche-N	Ncfsc
sin	sin	sin-D	Dd
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
isteach	isteach	isteach-R	Rd
agus	agus	agus-C	Cc
léigh	léigh	léigh-V	Vmis
sé	sé	sé-P	Pp3msn
scéal	scéal	scéal-N	Ncmsc
di	di	do-P	Pr3fs
.	.	.-F	Fe
Oíche	Oíche	oíche-N	Ncfsc
mhaith	mhaith	maith-A	Aq-fsc
,	,	,-F	Fi
a	a	a-U	Uv
Dhaidí	Dhaidí	daidí-N	Ncmsv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Oíche	Oíche	oíche-N	Ncfsc
mhaith	mhaith	maith-A	Aq-fsc
,	,	,-F	Fi
a	a	a-U	Uv
Dhaidí	Dhaidí	daidí-N	Ncmsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Clíodhna	Clíodhna	Clíodhna-N	Np
.	.	.-F	Fe
‘	‘	‘-X	Xx
Oíche	Oíche	oíche-N	Ncfsc
mhaith	mhaith	maith-A	Aq-fsc
,	,	,-F	Fi
a	a	a-U	Uv
stóirín	stóirín	stór-N	Ncmsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
agus	agus	agus-C	Cc
codladh	codladh	codladh-N	Ncfsc
sámh	sámh	sámh-A	Aqp
.	.	.-F	Fe
’	’	’-F	Fa
Tamall	Tamall	tamall-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|Dd
chuala	chuala	clois-V	Vmis
Clíodhna	Clíodhna	Clíodhna-N	Np
an	an	an-T	Td-s
bháisteach	bháisteach	báisteach-N	Ncfsc
.	.	.-F	Fe
Léim	Léim	léim-V	Vmis
sí	sí	sí-P	Pp3fsn
amach	amach	amach-R	Rd
as	as	as-S	Sp
an	an	an-T	Td-s
leaba	leaba	leaba-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-T	Td-s
ghráinneog	ghráinneog	gráinneog-N	Ncfsc
bhocht	bhocht	bocht-A	Aq-fsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Clíodhna	Clíodhna	Clíodhna-N	Np
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
sí	sí	sí-P	Pp3fsn
fliuch	fliuch	fliuch-A	Aqp
báite	báite	báigh-A	Av
.	.	.-F	Fe
’	’	’-F	Fa
Beidh	Beidh	bí-V	Vmif
sí	sí	sí-P	Pp3fsn
fliuch	fliuch	fliuch-A	Aqp
báite	báite	báigh-A	Av
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmm-2s
Clíodhna	Clíodhna	Clíodhna-N	Np
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
go	go	go-U	Ua
ciúin	ciúin	ciúin-A	Aqp
agus	agus	agus-C	Cc
amach	amach	amach-R	Rd
léi	léi	le-P	Pr3fs
sa	sa	i-S	Spa-s
ghairdín	ghairdín	gairdín-N	Ncmsc
.	.	.-F	Fe
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
,	,	,-F	Fi
a	a	a-U	Uv
ghráinneoigín	ghráinneoigín	gráinneog-N	Ncfsv
?	?	?-F	Fq
‘	‘	‘-X	Xx
A	A	an-T	Td-s
ghráinneoigín	ghráinneoigín	gráinneog-N	Ncfsc
bhocht	bhocht	bocht-A	Aq-fsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Clíodhna	Clíodhna	Clíodhna-N	Np
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
fliuch	fliuch	fliuch-A	Aqp
.	.	.-F	Fe
Fliuch	Fliuch	fliuch-V	Vmm-2s
báite	báite	báigh-A	Av
!	!	!-F	Fe
’	’	’-F	Fa
Tabharfaidh	Tabharfaidh	tabhair-V	Vmif
mé	mé	mé-P	Pp1-s
isteach	isteach	isteach-R	Rd
thú	thú	tú-P	Pp2-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
tú	tú	tú-P	Pp2-s
deas	deas	deas-R	Ri
tirim	tirim	tirim-A	Aqp
anois	anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Clíodhna	Clíodhna	Clíodhna-N	Np
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
Clíodhna	Clíodhna	Clíodhna-N	Np
an	an	an-T	Td-s
ghráinneog	ghráinneog	gráinneog-N	Ncfsc
isteach	isteach	isteach-R	Rd
.	.	.-F	Fe
Beidh	Beidh	bí-V	Vmif
leaba	leaba	leaba-N	Ncfsc
thirim	thirim	tirim-A	Aq-fsc
anois	anois	anois-R	Rt
agat	agat	ag-P	Pr2-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
leaba	leaba	leaba-N	Ncfsc
thirim	thirim	tirim-A	Aq-fsc
anois	anois	anois-R	Rt
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Clíodhna	Clíodhna	Clíodhna-N	Np
leis	leis	le-S	Sp
an	an	an-T	Td-s
ngráinneog	ngráinneog	gráinneog-N	Ncfsc
.	.	.-F	Fe
Lig	Lig	lig-V	Vmis|Vmm-2s
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
béic	béic	béic-N	Ncfsc
aisti	aisti	as-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Abha	Abha	abha-N	Ncfsc
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
rud	rud	rud-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
sa	sa	i-S	Spa-s
leaba	leaba	leaba-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
Abha	Abha	abha-N	Ncfsc
!	!	!-F	Fe
‘	‘	‘-X	Xx
Gráinneog	Gráinneog	gráinneog-N	Ncfsc
atá	atá	bí-V	Vmip---r
ann	ann	i-P	Pr3ms
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
A	A	a-U	Uv
Chlíodhna	Chlíodhna	clíodhna-N	Npmsc
!	!	!-F	Fe
