Ridire	Ridire	Ridire-N	Npmsc
bocht	bocht	bocht-A	Aq-msc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
mór	mór	mór-A	Aq-msc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Níl	Níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
mór	mór	mór-A	Aq-msc
liom	liom	le-P	Pr1-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
mór	mór	mór-A	Aq-msc
liom	liom	le-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Ridire	Ridire	Ridire-N	Npmsc
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
a	a	a-Q	Q-r
dhéanfaidh	dhéanfaidh	déan-V	Vmif
mé	mé	mé-P	Pp1-s
?	?	?-F	Fq
’	’	’-F	Fa
Agus	Agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmis
sé	sé	sé-P	Pp3msn
leis	leis	le-P	Pr3ms
go	go	go-U	Ua
dobrónach	dobrónach	dobrónach-A	Aqp
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmis
sé	sé	sé-P	Pp3msn
amach	amach	amach-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbóthar	mbóthar	bóthar-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmis
sé	sé	sé-P	Pp3msn
leis	leis	le-P	Pr3ms
nó	nó	nó-C	Cc
go	go	go-Q	Q
bhfaca	bhfaca	feic-V	Vmis---d
sé	sé	sé-P	Pp3msn
muc	muc	muc-N	Ncfsc
agus	agus	agus-C	Cc
bainbh	bainbh	banbh-N	Ncmsg|Ncmpc
i	i	i-S	Sp
mbuaile	mbuaile	buaile-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
!	!	!-F	Fe
Breathnaigh	Breathnaigh	breathnaigh-V	Vmm-2s
ar	ar	ar-S	Sp
an	an	an-T	Td-s
muc	muc	muc-N	Ncfsc
agus	agus	agus-C	Cc
ar	ar	ar-S	Sp
na	na	na-T	Td-p
bainbh	bainbh	banbh-N	Ncmpc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Ridire	Ridire	Ridire-N	Npmsc
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cén	Cén	cé-D	Dw--s
chaoi	chaoi	caoi-N	Ncfsc
a	a	a-Q	Q-i
bhfuil	bhfuil	bí-V	Vmip---d
sibh	sibh	sibh-P	Pp2-p
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Ridire	Ridire	Ridire-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhféadfaidh	bhféadfaidh	féad-V	Vmif
mé	mé	mé-P	Pp1-s
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
ag	ag	ag-S	Sp
spraoi	spraoi	spraoi-N	Nv-----n
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
libh	libh	le-P	Pr2-p
?	?	?-F	Fq
’	’	’-F	Fa
Cén	Cén	cé-D	Dw--s
chaoi	chaoi	caoi-N	Ncfsc
a	a	a-Q	Q-i
bhfuil	bhfuil	bí-V	Vmip---d
sibh	sibh	sibh-P	Pp2-p
?	?	?-F	Fq
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
fhéadfaidh	fhéadfaidh	féad-V	Vmif---n
tú	tú	tú-P	Pp2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
mhuc	mhuc	muc-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
rómhór	rómhór	mór-A	Aqp
dúinne	dúinne	do-P	Pr1-p-e
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
na	na	na-T	Td-p
bainbh	bainbh	banbh-N	Ncmpc
.	.	.-F	Fe
Ridire	Ridire	Ridire-N	Npmsc
bocht	bocht	bocht-A	Aq-msc
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
caoineadh	caoineadh	caoin-N	Nv
.	.	.-F	Fe
Níl	Níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
mór	mór	mór-A	Aq-msc
liom	liom	le-P	Pr1-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
mór	mór	mór-A	Aq-msc
liom	liom	le-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Ridire	Ridire	Ridire-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
a	a	a-Q	Q-r
dhéanfaidh	dhéanfaidh	déan-V	Vmif
mé	mé	mé-P	Pp1-s
?	?	?-F	Fq
’	’	’-F	Fa
Agus	Agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmis
sé	sé	sé-P	Pp3msn
leis	leis	le-P	Pr3ms
go	go	go-U	Ua
dobrónach	dobrónach	dobrónach-A	Aqp
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmis
sé	sé	sé-P	Pp3msn
leis	leis	le-P	Pr3ms
arís	arís	arís-R	Rg
nó	nó	nó-C	Cc
go	go	go-Q	Q
bhfaca	bhfaca	feic-V	Vmis---d
sé	sé	sé-P	Pp3msn
cearc	cearc	cearc-N	Ncfsc
agus	agus	agus-C	Cc
sicíní	sicíní	sicín-N	Ncmpg|Ncmpc|Ncmpg
i	i	i-S	Sp
mbuaile	mbuaile	buaile-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
!	!	!-F	Fe
Breathnaigh	Breathnaigh	breathnaigh-V	Vmm-2s
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcearc	gcearc	cearc-N	Ncfsc
agus	agus	agus-C	Cc
ar	ar	ar-S	Sp
na	na	na-T	Td-p
sicíní	sicíní	sicín-N	Ncmpc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Ridire	Ridire	Ridire-N	Npmsc
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cén	Cén	cé-D	Dw--s
chaoi	chaoi	caoi-N	Ncfsc
a	a	a-Q	Q-i
bhfuil	bhfuil	bí-V	Vmip---d
sibh	sibh	sibh-P	Pp2-p
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Ridire	Ridire	Ridire-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhféadfaidh	bhféadfaidh	féad-V	Vmif
mé	mé	mé-P	Pp1-s
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
ag	ag	ag-S	Sp
spraoi	spraoi	spraoi-N	Nv-----n
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
libh	libh	le-P	Pr2-p
?	?	?-F	Fq
’	’	’-F	Fa
Cén	Cén	cé-D	Dw--s
chaoi	chaoi	caoi-N	Ncfsc
a	a	a-Q	Q-i
bhfuil	bhfuil	bí-V	Vmip---d
sibh	sibh	sibh-P	Pp2-p
?	?	?-F	Fq
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
fhéadfaidh	fhéadfaidh	féad-V	Vmif---n
tú	tú	tú-P	Pp2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
chearc	chearc	cearc-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
rómhór	rómhór	mór-A	Aqp
dúinne	dúinne	do-P	Pr1-p-e
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
na	na	na-T	Td-p
sicíní	sicíní	sicín-N	Ncmpc
.	.	.-F	Fe
Ridire	Ridire	Ridire-N	Npmsc
bocht	bocht	bocht-A	Aq-msc
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
caoineadh	caoineadh	caoin-N	Nv
.	.	.-F	Fe
Níl	Níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
mór	mór	mór-A	Aq-msc
liom	liom	le-P	Pr1-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
mór	mór	mór-A	Aq-msc
liom	liom	le-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Ridire	Ridire	Ridire-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
a	a	a-Q	Q-r
dhéanfaidh	dhéanfaidh	déan-V	Vmif
mé	mé	mé-P	Pp1-s
?	?	?-F	Fq
’	’	’-F	Fa
Agus	Agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmis
sé	sé	sé-P	Pp3msn
leis	leis	le-P	Pr3ms
go	go	go-U	Ua
dobrónach	dobrónach	dobrónach-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
mór	mór	mór-A	Aq-msc
liom	liom	le-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Ridire	Ridire	Ridire-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
a	a	a-Q	Q-r
dhéanfaidh	dhéanfaidh	déan-V	Vmif
mé	mé	mé-P	Pp1-s
?	?	?-F	Fq
’	’	’-F	Fa
Agus	Agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmis
sé	sé	sé-P	Pp3msn
leis	leis	le-P	Pr3ms
go	go	go-U	Ua
dobrónach	dobrónach	dobrónach-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cén	Cén	cé-D	Dw--s
chaoi	chaoi	caoi-N	Ncfsc
a	a	a-Q	Q-i
bhfuil	bhfuil	bí-V	Vmip---d
sibh	sibh	sibh-P	Pp2-p
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Ridire	Ridire	Ridire-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhféadfaidh	bhféadfaidh	féad-V	Vmif
mé	mé	mé-P	Pp1-s
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
ag	ag	ag-S	Sp
spraoi	spraoi	spraoi-N	Nv-----n
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
libh	libh	le-P	Pr2-p
?	?	?-F	Fq
’	’	’-F	Fa
Cén	Cén	cé-D	Dw--s
chaoi	chaoi	caoi-N	Ncfsc
a	a	a-Q	Q-i
bhfuil	bhfuil	bí-V	Vmip---d
sibh	sibh	sibh-P	Pp2-p
?	?	?-F	Fq
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
fhéadfaidh	fhéadfaidh	féad-V	Vmif---n
tú	tú	tú-P	Pp2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
chaora	chaora	caora-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
rómhór	rómhór	mór-A	Aqp
dúinne	dúinne	do-P	Pr1-p-e
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
na	na	na-T	Td-p
huain	huain	uan-N	Ncmpc
.	.	.-F	Fe
Ridire	Ridire	Ridire-N	Npmsc
bocht	bocht	bocht-A	Aq-msc
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
caoineadh	caoineadh	caoin-N	Nv
.	.	.-F	Fe
Níl	Níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
mór	mór	mór-A	Aq-msc
liom	liom	le-P	Pr1-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
mór	mór	mór-A	Aq-msc
liom	liom	le-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Ridire	Ridire	Ridire-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
a	a	a-Q	Q-r
dhéanfaidh	dhéanfaidh	déan-V	Vmif
mé	mé	mé-P	Pp1-s
?	?	?-F	Fq
Agus	Agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmis
sé	sé	sé-P	Pp3msn
leis	leis	le-P	Pr3ms
go	go	go-U	Ua
dobrónach	dobrónach	dobrónach-A	Aqp
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmis
sé	sé	sé-P	Pp3msn
leis	leis	le-P	Pr3ms
nó	nó	nó-C	Cc
go	go	go-Q	Q
bhfaca	bhfaca	feic-V	Vmis---d
sé	sé	sé-P	Pp3msn
capall	capall	capall-N	Ncmsc
agus	agus	agus-C	Cc
searrach	searrach	searrach-N	Ncmpg|Ncmsc|Ncmpg
i	i	i-S	Sp
mbuaile	mbuaile	buaile-N	Ncfsc
.	.	.-F	Fe
Céard	Céard	cé-W	W--q
atá	atá	bí-V	Vmip---r
ort	ort	ar-P	Pr2-s
?	?	?-F	Fq
‘	‘	‘-X	Xx
Cén	Cén	cé-D	Dw--s
fáth	fáth	fáth-N	Ncmsc
a	a	a-Q	Q-i
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
caoineadh	caoineadh	caoin-N	Nv
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
searrach	searrach	searrach-N	Ncmsc
le	le	le-S	Sp
Ridire	Ridire	Ridire-N	Npmsc
.	.	.-F	Fe
Níl	Níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
mór	mór	mór-A	Aq-msc
liom	liom	le-P	Pr1-s
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmm-2s
an	an	an-T	Td-s
searrach	searrach	searrach-N	Ncmsc
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
mise	mise	mé-P	Pp1-s-e
mór	mór	mór-A	Aqp
leat	leat	le-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
searrach	searrach	searrach-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Féadfaidh	Féadfaidh	féad-V	Vmif
tú	tú	tú-P	Pp2-s
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
spraoi	spraoi	spraoi-N	Nv-----n
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
liomsa	liomsa	le-P	Pr1-s-e
!	!	!-F	Fe
’	’	’-F	Fa
Beidh	Beidh	bí-V	Vmif
mise	mise	mé-P	Pp1-s-e
mór	mór	mór-A	Aqp
leat	leat	le-P	Pr2-s
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
Ridire	Ridire	Ridire-N	Npmsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
searrach	searrach	searrach-N	Ncmsc
ag	ag	ag-S	Sp
spraoi	spraoi	spraoi-N	Nv-----n
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
seo	seo	seo-P	Pd
mór	mór	mór-N	Ncmsc|Aqp
liom	liom	le-P	Pr1-s
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an-spraoi	an-spraoi	spraoi-N	Ncmsc
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
muid	muid	muid-P	Pp1-p
mór	mór	mór-A	Aqp
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Ridire	Ridire	Ridire-N	Npmsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
searrach	searrach	searrach-N	Ncmsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
muid	muid	muid-P	Pp1-p
mór	mór	mór-A	Aqp
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
muc	muc	muc-N	Ncfsc
agus	agus	agus-C	Cc
banbh	banbh	banbh-N	Ncmpg|Ncmsc
cearc	cearc	cearc-N	Ncfpg|Ncfsc
agus	agus	agus-C	Cc
sicín	sicín	sicín-N	Ncmsg|Ncmsc
caora	caora	caor-N	Ncfpc
agus	agus	agus-C	Cc
uan	uan	uan-N	Ncmpg|Ncmsc
capall	capall	capall-N	Ncmpg
agus	agus	agus-C	Cc
searrach	searrach	searrach-N	Ncmpg|Ncmsc|Ncmpg
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
mór	mór	mór-A	Aq-msc
liom	liom	le-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Ridire	Ridire	Ridire-N	Npmsc
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
a	a	a-Q	Q-r
dhéanfaidh	dhéanfaidh	déan-V	Vmif
mé	mé	mé-P	Pp1-s
?	?	?-F	Fq
’	’	’-F	Fa
