Bhí	Bhí	bí-V	Vmis
Máire	Máire	Máire-N	Npfsc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
máthair	máthair	máthair-N	Ncfsc
beo	beo	beo-A	Aqp
bocht	bocht	bocht-A	Aqp
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ocras	ocras	ocras-N	Ncmsc
orthu	orthu	ar-P	Pr3-p
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
pota	pota	pota-N	Ncmsc
leitean	leitean	leite-N	Ncfsg
draíochta	draíochta	draíocht-N	Ncfsg|Ncfpc|Ncfpg
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
máthair	máthair	máthair-N	Ncfsc
Mháire	Mháire	Máire-N	Npfsc
an	an	an-T	Td-s
pota	pota	pota-N	Ncmsg
ar	ar	ar-S	Sp
an	an	an-T	Td-s
tine	tine	tine-N	Ncfsc
.	.	.-F	Fe
Fiuch	Fiuch	fiuch-V	Vmm-2s
,	,	,-F	Fi
a	a	a-U	Uv
phota	phota	pota-N	Ncmsv
.	.	.-F	Fe
Fiuch	Fiuch	fiuch-V	Vmm-2s
!	!	!-F	Fe
Agus	Agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
an	an	an-T	Td-s
pota	pota	pota-N	Ncmsc
ag	ag	ag-S	Sp
fiuchadh	fiuchadh	fiuch-N	Nv
.	.	.-F	Fe
Stop	Stop	stop-V	Vmis
,	,	,-F	Fi
a	a	a-U	Uv
phota	phota	pota-N	Ncmsv
.	.	.-F	Fe
Stop	Stop	stop-V	Vmm-2s
!	!	!-F	Fe
Agus	Agus	agus-C	Cc
stop	stop	stop-V	Vmis|Ncmsc|Vmm-2s
an	an	an-T	Td-s
pota	pota	pota-N	Ncmsg|Ncmsc
ag	ag	ag-S	Sp
fiuchadh	fiuchadh	fiuch-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
fear	fear	fear-N	Ncmsc
santach	santach	santach-A	Aq-msc
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
pota	pota	pota-N	Ncmsc
leitean	leitean	leite-N	Ncfsg
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
pota	pota	pota-N	Ncmsc
sin	sin	sin-D	Dd
uaim	uaim	ó-P	Pr1-s
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
Máire	Máire	Máire-N	Npfsc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
máthair	máthair	máthair-N	Ncfsc
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
amach	amach	amach-R	Rd
.	.	.-F	Fe
Ghoid	Ghoid	goid-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
pota	pota	pota-N	Ncmsc
.	.	.-F	Fe
Fiuch	Fiuch	fiuch-V	Vmm-2s
,	,	,-F	Fi
a	a	a-U	Uv
phota	phota	pota-N	Ncmsv
.	.	.-F	Fe
Fiuch	Fiuch	fiuch-V	Vmm-2s
!	!	!-F	Fe
Agus	Agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
an	an	an-T	Td-s
pota	pota	pota-N	Ncmsc
ag	ag	ag-S	Sp
fiuchadh	fiuchadh	fiuch-N	Nv
.	.	.-F	Fe
Stop	Stop	stop-V	Vmis
,	,	,-F	Fi
a	a	a-U	Uv
phota	phota	pota-N	Ncmsv
.	.	.-F	Fe
Stop	Stop	stop-V	Vmm-2s
!	!	!-F	Fe
ACH	ACH	ach-C	Cs
…	…	…-F	Fi
níor	níor	níor-W	Ws-in|Qn-s
stop	stop	stop-V	Vmis|Vmis---n|Ncmsc
an	an	an-T	Td-s
pota	pota	pota-N	Ncmsg|Ncmsc
ag	ag	ag-S	Sp
fiuchadh	fiuchadh	fiuch-N	Nv
.	.	.-F	Fe
Amach	Amach	amach-R	Rd
as	as	as-S	Sp
an	an	an-T	Td-s
bpota	bpota	pota-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
leite	leite	leite-N	Ncfsc
–	–	–-X	Xx
Stop	Stop	stop-V	Vmis
,	,	,-F	Fi
a	a	a-U	Uv
phota	phota	pota-N	Ncmsv
.	.	.-F	Fe
Stop	Stop	stop-V	Vmm-2s
!	!	!-F	Fe
Stop	Stop	stop-V	Vmis
,	,	,-F	Fi
a	a	a-U	Uv
phota	phota	pota-N	Ncmsv
.	.	.-F	Fe
Stop	Stop	stop-V	Vmm-2s
!	!	!-F	Fe
amach	amach	amach-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
urlár	urlár	urlár-N	Ncmsc
,	,	,-F	Fi
Stop	Stop	stop-V	Vmis
,	,	,-F	Fi
a	a	a-U	Uv
phota	phota	pota-N	Ncmsv
.	.	.-F	Fe
Stop	Stop	stop-V	Vmm-2s
!	!	!-F	Fe
amach	amach	amach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
,	,	,-F	Fi
agus	agus	agus-C	Cc
síos	síos	síos-R	Rd
an	an	an-T	Td-s
tsráid	tsráid	sráid-N	Ncfsc
.	.	.-F	Fe
Stop	Stop	stop-V	Vmm-2s
!	!	!-F	Fe
Stop	Stop	stop-V	Vmm-2s
!	!	!-F	Fe
Chonaic	Chonaic	feic-V	Vmis
Máire	Máire	Máire-N	Npfsc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
máthair	máthair	máthair-N	Ncfsc
an	an	an-T	Td-s
leite	leite	leite-N	Ncfsc
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
siad	siad	siad-P	Pp3-pn
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
santach	santach	santach-A	Aq-msc
.	.	.-F	Fe
Stop	Stop	stop-V	Vmis
,	,	,-F	Fi
a	a	a-U	Uv
phota	phota	pota-N	Ncmsv
.	.	.-F	Fe
STOP	STOP	stop-V	Vmm-2s
!	!	!-F	Fe
Agus	Agus	agus-C	Cc
stop	stop	stop-V	Vmis|Ncmsc|Vmm-2s
an	an	an-T	Td-s
pota	pota	pota-N	Ncmsg|Ncmsc
ag	ag	ag-S	Sp
fiuchadh	fiuchadh	fiuch-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ghoid	Ghoid	goid-V	Vmis
tú	tú	tú-P	Pp2-s
mo	mo	mo-D	Dp1-s
phota	phota	pota-N	Ncmsc
leitean	leitean	leite-N	Ncfsg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
máthair	máthair	máthair-N	Ncfsc
Mháire	Mháire	Máire-N	Npf-g
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
brón	brón	brón-N	Ncmsc
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
leite	leite	leite-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
urlár	urlár	urlár-N	Ncmsc
,	,	,-F	Fi
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
amach	amach	amach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
,	,	,-F	Fi
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
síos	síos	síos-R	Rd
an	an	an-T	Td-s
tsráid	tsráid	sráid-N	Ncfsc
.	.	.-F	Fe
Leite	Leite	leite-N	Ncfsc
!	!	!-F	Fe
ANSIN	ANSIN	ansin-R	Rt|Rl
…	…	…-F	Fi
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
leite	leite	leite-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
urlár	urlár	urlár-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
leite	leite	leite-N	Ncfsc
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
amach	amach	amach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
leite	leite	leite-N	Ncfsc
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
síos	síos	síos-R	Rd
an	an	an-T	Td-s
tsráid	tsráid	sráid-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
brón	brón	brón-N	Ncmsc
orm	orm	ar-P	Pr1-s
gur	gur	gur-W	Wsdi|Q--s
ghoid	ghoid	goid-N	Nv|Ncfsc|Vmis
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
pota	pota	pota-N	Ncmsg|Ncmsc
leitean	leitean	leite-N	Ncfsg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
santach	santach	santach-A	Aq-msc
arís	arís	arís-R	Rg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
cóisir	cóisir	cóisir-N	Ncfsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
bhfear	bhfear	fear-N	Ncmsc
santach	santach	santach-A	Aq-msc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Máire	Máire	Máire-N	Npfsc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
máthair	máthair	máthair-N	Ncfsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
gcóisir	gcóisir	cóisir-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
bia	bia	bia-N	Ncmsc
agus	agus	agus-C	Cc
deoch	deoch	deoch-V	Vmm-2s
ag	ag	ag-S	Sp
an	an	an-T	Td-s
gcóisir	gcóisir	cóisir-N	Ncfsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
…	…	…-F	Fi
an	an	an-Q	Qq
raibh	raibh	bí-V	Vmis---d
leite	leite	leite-N	Ncfsc
ann	ann	i-P	Pr3ms
?	?	?-F	Fq
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
!	!	!-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
oiread	oiread	oiread-N	Ns-s
is	is	agus-C	Cc
spúnóg	spúnóg	spúnóg-N	Ncfpg|Ncfsc|Ncfpg
amháin	amháin	amháin-A	Aqp
leitean	leitean	leite-N	Ncfsg
ann	ann	i-P	Pr3ms
!	!	!-F	Fe
