Tá	Tá	bí-V	Vmip
mise	mise	mé-P	Pp1-s-e
mór	mór	mór-A	Aqp
anois	anois	anois-R	Rt
.	.	.-F	Fe
Déanfaidh	Déanfaidh	déan-V	Vmif
mé	mé	mé-P	Pp1-s
lón	lón	lón-N	Ncmsc
dom	dom	do-P	Pr1-s
féin	féin	féin-P	Px
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
cheart	cheart	ceart-A	Aqp
duit	duit	do-P	Pr2-s
bia	bia	bia-N	Ncmsc
folláin	folláin	folláin-A	Aq-msc
a	a	a-U	U
ithe	ithe	ith-N	Nv
.	.	.-F	Fe
Maith	Maith	Maith-N	Npmsc
go leor	go leor	go_leor-A	Aq
,	,	,-F	Fi
a	a	a-U	Uv
Mhamaí	Mhamaí	mama-N	Ncfsv|Ncmpv
.	.	.-F	Fe
An	An	is-W	Wp-q
bia	bia	bia-N	Ncmsc
folláin	folláin	folláin-A	Aq-msc
é	é	é-P	Pp3ms
an	an	an-T	Td-s
t-arán	t-arán	arán-N	Ncmsc
donn	donn	donn-A	Aq-msc
,	,	,-F	Fi
a	a	a-U	Uv
Mhamaí	Mhamaí	mama-N	Ncfsv|Ncmpv
?	?	?-F	Fq
Is	Is	is-W	Wp-i
ea	ea	ea-P	Pp3-s
,	,	,-F	Fi
a	a	a-U	Uv
stór	stór	stór-N	Ncmsv
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
an	an	an-T	Td-s
sicín	sicín	sicín-N	Ncmsc
?	?	?-F	Fq
Is	Is	is-W	Wp-i
ea	ea	ea-P	Pp3-s
,	,	,-F	Fi
a	a	a-U	Uv
stór	stór	stór-N	Ncmsv
.	.	.-F	Fe
An	An	is-W	Wp-q
bia	bia	bia-N	Ncmsc
folláin	folláin	folláin-A	Aq-msc
iad	iad	iad-P	Pp3-p
na	na	na-T	Td-p
criospaí	criospaí	criospa-N	Ncmpc
sin	sin	sin-D	Dd
?	?	?-F	Fq
Ó	Ó	Ó-I	I
!	!	!-F	Fe
Ní	Ní	is-W	Wp-in
hea	hea	ea-P	Pp3-s
,	,	,-F	Fi
a	a	a-U	Uv
stór	stór	stór-N	Ncmsv
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
na	na	na-T	Td-p
horáistí	horáistí	oráiste-N	Ncmpc
?	?	?-F	Fq
Is	Is	is-W	Wp-i
ea	ea	ea-P	Pp3-s
,	,	,-F	Fi
a	a	a-U	Uv
stór	stór	stór-N	Ncmsv
.	.	.-F	Fe
An	An	is-W	Wp-q
bia	bia	bia-N	Ncmsc
folláin	folláin	folláin-A	Aq-msc
iad	iad	iad-P	Pp3-p
an	an	an-T	Td-s
cháis	cháis	cás-N	Ncmsg
agus	agus	agus-C	Cc
an	an	an-T	Td-s
t-iógart	t-iógart	iógart-N	Ncmsc
?	?	?-F	Fq
Is	Is	is-W	Wp-i
ea	ea	ea-P	Pp3-s
,	,	,-F	Fi
a	a	a-U	Uv
stór	stór	stór-N	Ncmsv
.	.	.-F	Fe
Anois	Anois	anois-R	Rt
,	,	,-F	Fi
cuirfidh	cuirfidh	cuir-V	Vmif
mé	mé	mé-P	Pp1-s
im	im	i-D	Dp1-s
ar	ar	ar-S	Sp
an	an	an-T	Td-s
arán	arán	arán-N	Ncmsc
.	.	.-F	Fe
Maith	Maith	Maith-N	Npmsc
an	an	an-T	Td-s
buachaill	buachaill	buachaill-N	Ncmsc
.	.	.-F	Fe
Cuirfidh	Cuirfidh	cuir-V	Vmif
mé	mé	mé-P	Pp1-s
píosa	píosa	píosa-N	Ncmsc
sicín	sicín	sicín-N	Ncmsg
isteach	isteach	isteach-R	Rd
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
lón	lón	lón-N	Ncmsc
folláin	folláin	folláin-A	Aq-msc
agam	agam	ag-P	Pr1-s
anois	anois	anois-R	Rt
.	.	.-F	Fe
Maith	Maith	Maith-N	Npmsc
an	an	an-T	Td-s
buachaill	buachaill	buachaill-N	Ncmsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
mise	mise	mé-P	Pp1-s-e
mór	mór	mór-A	Aqp
anois	anois	anois-R	Rt
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
lón	lón	lón-N	Ncmsc
déanta	déanta	déan-A	Av
agam	agam	ag-P	Pr1-s
dom	dom	do-P	Pr1-s
féin	féin	féin-P	Px
.	.	.-F	Fe
