D	D	D-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmm-2s
mé	mé	mé-P	Pp1-s
doras	doras	doras-N	Ncmsc
cófra	cófra	cófra-N	Ncmsg|Ncmsc
tarraiceán	tarraiceán	tarraiceán-N	Ncmpg|Ncmsc
féirín	féirín	féirín-N	Ncmsg|Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmm-2s
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
agus	agus	agus-C	Cc
chonaic	chonaic	feic-V	Vmis
mé	mé	mé-P	Pp1-s
solas	solas	solas-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmm-2s
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
cófra	cófra	cófra-N	Ncmsc
agus	agus	agus-C	Cc
chonaic	chonaic	feic-V	Vmis
mé	mé	mé-P	Pp1-s
bróga	bróga	bróg-N	Ncfpc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmm-2s
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
tarraiceán	tarraiceán	tarraiceán-N	Ncmsc
agus	agus	agus-C	Cc
chonaic	chonaic	feic-V	Vmis
mé	mé	mé-P	Pp1-s
milseán	milseán	milseán-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmm-2s
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
féirín	féirín	féirín-N	Ncmsc
agus	agus	agus-C	Cc
chonaic	chonaic	feic-V	Vmis
mé	mé	mé-P	Pp1-s
béirín	béirín	béirín-N	Ncmsc
!	!	!-F	Fe
Chonaic	Chonaic	feic-V	Vmis
mé	mé	mé-P	Pp1-s
solas	solas	solas-N	Ncmsc
bróga	bróga	bróg-N	Ncfpc
milseán	milseán	milseán-N	Ncmpg|Ncmsc
béirín	béirín	béirín-N	Ncmsg|Ncmsc
.	.	.-F	Fe
