Oráiste	Oráiste	oráiste-N	Ncmsc
breá	breá	breá-R	Ri
buí	buí	buí-A	Aqp
,	,	,-F	Fi
Chomh	Chomh	chomh-R	Ri
milis	milis	milis-A	Aqp
le	le	le-S	Sp
subh	subh	subh-N	Ncfsc
.	.	.-F	Fe
Seo	Seo	seo-W	W
dhá	dhá	dó-M	Mc
phiscín	phiscín	piscín-N	Ncmsc
bheaga	bheaga	beag-A	Aq--pc
,	,	,-F	Fi
Is	Is	is-W	Wpri
a	a	a-D	Dp3
máthair	máthair	máthair-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
dhubh	dhubh	dubh-A	Aq-fsc|Aq-fsv
.	.	.-F	Fe
Seo	Seo	seo-W	W
ubh	ubh	ubh-N	Ncfsc
bhruite	bhruite	bruith-A	Aqp|Av
bhlasta	bhlasta	blasta-A	Aqp
,	,	,-F	Fi
Thug	Thug	tabhair-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
dom	dom	do-P	Pr1-s
í	í	í-P	Pp3fs
.	.	.-F	Fe
Amuigh	Amuigh	amuigh-R	Rl
sa	sa	i-S	Spa-s
ghairdín	ghairdín	gairdín-N	Ncmsc
A	A	a-Q	Q-r
bhím	bhím	bí-V	Vmig1s
feadh	feadh	feadh-N	Ncmsc
an	an	an-T	Td-s
lae	lae	lá-N	Ncmsg
.	.	.-F	Fe
Culaith	Culaith	culaith-N	Ncfsc
ghorm	ghorm	gorm-A	Aq-fsc
agus	agus	agus-C	Cc
caipín	caipín	caipín-N	Ncmsg|Ncmsc
A	A	a-Q	Q-i|Q-r
fuair	fuair	faigh-V	Vmis
Tomás	Tomás	Tomás-N	Npmsc
sa	sa	i-S	Spa-s
bheart	bheart	beart-N	Ncmsc
.	.	.-F	Fe
Maith	Maith	Maith-N	Npmsc
an	an	an-T	Td-s
cailín	cailín	cailín-N	Ncmsg
,	,	,-F	Fi
a	a	a-U	Uv
Shíle	Shíle	Síle-N	Npf-v
,	,	,-F	Fi
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
gléasta	gléasta	gléas-A	Av
i	i	i-S	Sp
gceart	gceart	ceart-N	Ncmsc
.	.	.-F	Fe
Seo	Seo	seo-W	W
liathróid	liathróid	liathróid-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
dhaite	dhaite	daite-A	Aqp
Dearg	Dearg	dearg-A	Aqp
,	,	,-F	Fi
uaine	uaine	uaine-A	Aqp
agus	agus	agus-C	Cc
buí	buí	buí-N	Ncmsg|Ncmsc|Ns-s|Aqp
.	.	.-F	Fe
Cois	Cois	cois-S	Sp
farraige	farraige	farraige-N	Ncfsc
sa	sa	i-S	Spa-s
samhradh	samhradh	samhradh-N	Ncmsc
Bíonn	Bíonn	bí-V	Vmig
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
ag	ag	ag-S	Sp
spraoi	spraoi	spraoi-N	Nv-----n
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
bláthanna	bláthanna	bláth-N	Ncmpc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
muga	muga	muga-N	Ncmsc
,	,	,-F	Fi
Agus	Agus	agus-C	Cc
coiníní	coiníní	coinín-N	Ncmpc
áille	áille	álainn-A	Aq--pv|Aq--pc|Aq--pg|Aq--pc
.	.	.-F	Fe
Téim	Téim	téigh-V	Vmip1s
le	le	le-S	Sp
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbus	mbus	bus-N	Ncmsc
Agus	Agus	agus-C	Cc
íocaim	íocaim	íoc-V	Vmip1s
an	an	an-T	Td-s
táille	táille	táille-N	Ncfsc
.	.	.-F	Fe
Anonn	Anonn	anonn-R	Rd
is	is	is-W	Wp-i
anall	anall	anall-R	Rd
,	,	,-F	Fi
Ag	Ag	ag-S	Sp
luascadh	luascadh	luasc-N	Nv
faoin	faoin	faoi-S	Spa-s
ngrian	ngrian	grian-N	Ncmsc|Ncfsc
.	.	.-F	Fe
An	An	an-T	Td-s
páiste	páiste	páiste-N	Ncmsc
beag	beag	beag-A	Aq-msc
óg	óg	óg-A	Aq-msc
,	,	,-F	Fi
Ina	Ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
Coinníonn	Coinníonn	coinnigh-V	Vmip
scáth	scáth	scáth-N	Ncmsc
fearthainne	fearthainne	fearthainn-N	Ncfsg|Nv--g--n
Go	Go	go-U	Ua
deas	deas	deas-R	Ri
tirim	tirim	tirim-A	Aqp
mé	mé	mé-P	Pp1-s
.	.	.-F	Fe
Cuirim	Cuirim	cuir-V	Vmip1s
mo	mo	mo-D	Dp1-s
bhróga	bhróga	bróg-N	Ncfpc
orm	orm	ar-P	Pr1-s
,	,	,-F	Fi
Cé	Cé	cé-C	Cs
gur	gur	is-W	Wsdi|Wpdi
deacair	deacair	deacair-A	Aqp
dom	dom	do-P	Pr1-s
é	é	é-P	Pp3ms
.	.	.-F	Fe
Nach	Nach	is-W	Wpsin
deas	deas	deas-A	Aqp
iad	iad	iad-P	Pp3-p
na	na	na-T	Tdfsg
héiníní	héiníní	héiníní-N	Ncfsc
,	,	,-F	Fi
Thuas	Thuas	tuaigh-V	Vmip---r
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcrann	gcrann	crann-N	Ncmsc
.	.	.-F	Fe
Seo	Seo	seo-W	W
é	é	é-P	Pp3ms
mo	mo	mo-D	Dp1-s
dheartháirín	dheartháirín	deartháir-N	Ncmsc
,	,	,-F	Fi
Níl	Níl	bí-V	Vmip---n
méid	méid	méid-N	Ncmsc|Ncfsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
lá	lá	lá-N	Ncmsc
eile	eile	eile-D	Dd
caite	caite	caith-A	Av
,	,	,-F	Fi
Tá	Tá	bí-V	Vmip
clog	clog	clog-X	Xfev
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbuille	mbuille	buille-N	Ncmsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
tuirse	tuirse	tuirse-N	Ncfsc
is	is	agus-C	Cc
codladh	codladh	codail-N	Ncfsc|Nv
orm	orm	ar-P	Pr1-s
,	,	,-F	Fi
Fágaim	Fágaim	fág-V	Vmip1s
slán	slán	slán-N	Ncmsc
agaibh	agaibh	ag-P	Pr2-p
uile	uile	uile-N	Ns-s
.	.	.-F	Fe
Cá	Cá	cá-R	Rq
mbím	mbím	bí-V	Vmig1s
ar feadh	ar feadh	ar_feadh-S	Spc
an	an	an-T	Td-s
lae	lae	lá-N	Ncmsg
?	?	?-F	Fq
