Oíche	Oíche	oíche-N	Ncfsc
Nollag	Nollag	Nollaig-N	Ncfsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
i	i	i-S	Sp
dTír	dTír	tír-N	Ncfsc
na	na	na-T	Tdfsg
Sí	Sí	is-W	Wp-i-3
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
na	na	na-T	Tdfsg
Nollag	Nollag	Nollaig-N	Ncfsg
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
charr	charr	carr-N	Ncmsc|Ncfsc
sleamhnáin	sleamhnáin	sleamhnán-N	Ncmsg|Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
liosta	liosta	liosta-N	Ncmsc
fada	fada	fada-A	Aqp
go	go	go-U	Ua
maith	maith	maith-A	Aqp
ag	ag	ag-S	Sp
na	na	na-T	Td-p
sióga	sióga	sióg-N	Ncfpc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
na	na	na-T	Tdfsg
Nollag	Nollag	Nollaig-N	Ncfsg
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
léamh	léamh	léigh-N	Nv
an	an	an-T	Td-s
liosta	liosta	liosta-N	Ncmsg
.	.	.-F	Fe
Bhuail	Bhuail	buail-V	Vmis
tuirse	tuirse	tuirse-N	Ncfsc
Daidí	Daidí	daidí-N	Ncmsc
na	na	na-T	Tdfsg
Nollag	Nollag	Nollaig-N	Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
táim	táim	bí-V	Vmip1s
tuirseach	tuirseach	tuirseach-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
agus	agus	agus-C	Cc
leag	leag	leag-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
liosta	liosta	liosta-N	Ncmsc
uaidh	uaidh	ó-P	Pr3ms
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbord	mbord	bord-N	Ncmsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
shuigh	shuigh	suigh-V	Vmis
sé	sé	sé-P	Pp3msn
síos	síos	síos-R	Rd
agus	agus	agus-C	Cc
thit	thit	tit-V	Vmis
a	a	a-U	U
chodladh	chodladh	codail-N	Nv
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
na	na	na-T	Tdfsg
Nollag	Nollag	Nollaig-N	Ncfsg
ina	ina	i-S	Spp-s
chodladh	chodladh	codladh-N	Ncfsc
tháinig	tháinig	tar-V	Vmis
Gruama	Gruama	gruama-A	Aqc
,	,	,-F	Fi
an	an	an-T	Td-s
tsióg	tsióg	sióg-N	Ncfsc
ghránna	ghránna	gránna-A	Aqp
,	,	,-F	Fi
isteach	isteach	isteach-R	Rd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
an	an	an-T	Td-s
liosta	liosta	liosta-N	Ncmsc
sin	sin	sin-D	Dd
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Liosta	Liosta	liosta-N	Ncmsc
na	na	na-T	Td-p
mbréagán	mbréagán	bréagán-N	Ncmpg
!	!	!-F	Fe
’	’	’-F	Fa
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
chonaic	chonaic	feic-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
liosta	liosta	liosta-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbord	mbord	bord-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
agam	agam	ag-P	Pr1-s
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
liosta	liosta	liosta-N	Ncmsc
ina	ina	i-S	Spp-s
póca	póca	póca-N	Ncmsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
thóg	thóg	tóg-V	Vmis
sí	sí	sí-P	Pp3fsn
liosta	liosta	liosta-N	Ncmsc|Aqp
eile	eile	eile-D	Dd
amach	amach	amach-R	Rd
as	as	as-P	Pr3ms
a	a	a-D	Dp3
póca	póca	póca-N	Ncmsc
agus	agus	agus-C	Cc
leag	leag	leag-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbord	mbord	bord-N	Ncmsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Há	Há	Há-N	Npmsc
!	!	!-F	Fe
Há	Há	Há-N	Npmsc
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
agus	agus	agus-C	Cc
amach	amach	amach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
dhúisigh	dhúisigh	dúisigh-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
na	na	na-T	Tdfsg
Nollag	Nollag	Nollaig-N	Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	an-T	Td-s
Ríona	Ríona	ríon-N	Ncfsg
,	,	,-F	Fi
cá	cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
le	le	le-S	Sp
Ríona	Ríona	ríon-N	Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
in	in	i-S	Sp
am	am	am-N	Ncmsc
na	na	na-T	Td-p
bronntanais	bronntanais	bronntanas-N	Ncmpc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
do	do	do-S	Sp
na	na	na-T	Td-p
sióga	sióga	sióg-N	Ncfpc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
na	na	na-T	Tdfsg
Nollag	Nollag	Nollaig-N	Ncfsg
le	le	le-S	Sp
Ríona	Ríona	ríon-N	Ncfsg
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
liosta	liosta	liosta-N	Ncmsc
di	di	do-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cuir	Cuir	cur-N	Ncmsg
ainm	ainm	ainm-N	Ncmsg|Ncmsc|Ncmsg
ar	ar	ar-S	Sp
gach	gach	gach-D	Dq
bronntanas	bronntanas	bronntanas-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Chuir	Chuir	cur-N	Ncmsv
Ríona	Ríona	ríon-N	Ncfsg
ainm	ainm	ainm-N	Ncmsg|Ncmsc|Ncmsg
ar	ar	ar-S	Sp
gach	gach	gach-D	Dq
bronntanas	bronntanas	bronntanas-N	Ncmsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
thug	thug	tabhair-V	Vmis
sí	sí	sí-P	Pp3fsn
na	na	na-T	Td-p
bronntanais	bronntanais	bronntanas-N	Ncmpc
do	do	do-S	Sp
na	na	na-T	Td-p
sióga	sióga	sióg-N	Ncfpc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	is-W	Wp-in
mó	mó	mó-A	Aqc|Aqp
ná	ná	ná-C	Cs|Cc
sásta	sásta	sásta-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
na	na	na-T	Td-p
sióga	sióga	sióg-N	Ncfpc
nuair	nuair	nuair-C	Cs
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmis
siad	siad	siad-P	Pp3-pn
na	na	na-T	Td-p
bronntanais	bronntanais	bronntanas-N	Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
bhfuair	bhfuair	faigh-V	Vmis
mise	mise	mé-P	Pp1-s-e
an	an	an-T	Td-s
rud	rud	rud-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
uaim	uaim	ó-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
sióg	sióg	sióg-N	Ncfsc
amháin	amháin	amháin-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-C	Cs|Cc
mise	mise	mé-P	Pp1-s-e
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
oiread	oiread	oiread-N	Ns-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
sióg	sióg	sióg-N	Ncfsc
eile	eile	eile-D	Dd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
bhfuair	bhfuair	faigh-V	Vmis
mise	mise	mé-P	Pp1-s-e
an	an	an-T	Td-s
tarracóir	tarracóir	tarracóir-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
uaim	uaim	ó-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
sióg	sióg	sióg-N	Ncfsc
eile	eile	eile-D	Dd
fós	fós	fós-R	Rg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bábóg	Bábóg	bábóg-N	Ncfsc
a	a	a-Q	Q-i|Q-r
fuair	fuair	faigh-V	Vmis
mé	mé	mé-P	Pp1-s
!	!	!-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
thuigim	thuigim	tuig-V	Vmip1s-n
é	é	é-P	Pp3ms
seo	seo	seo-P	Pd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	ar-N	Ncmsc-e
Ríona	Ríona	ríon-N	Ncfsg
.	.	.-F	Fe
Amach	Amach	amach-R	Rd
le	le	le-S	Sp
Ríona	Ríona	ríon-N	Ncfsg
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
carr	carr	carr-N	Ncmsc|Ncfsc
sleamhnáin	sleamhnáin	sleamhnán-N	Ncmsg|Ncmpc
.	.	.-F	Fe
Cé	Cé	cé-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
istigh	istigh	istigh-R	Rl
sa	sa	i-S	Spa-s
charr	charr	carr-N	Ncmsc|Ncfsc
sleamhnáin	sleamhnáin	sleamhnán-N	Ncmsg|Ncmpc
ach	ach	ach-R	Ri
Gruama	Gruama	gruama-A	Aqp
,	,	,-F	Fi
an	an	an-T	Td-s
tsióg	tsióg	sióg-N	Ncfsc
ghránna	ghránna	gránna-A	Aqp
!	!	!-F	Fe
Rith	Rith	rith-N	Ncmsc
Gruama	Gruama	gruama-A	Aqp
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
sí	sí	sí-P	Pp3fsn
Ríona	Ríona	ríon-N	Ncfsg
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
.	.	.-F	Fe
Rith	Rith	rith-N	Ncmsc
Ríona	Ríona	ríon-N	Ncfsg
ina	ina	i-S	Spp-s
diaidh	diaidh	diaidh-N	Ns-s
.	.	.-F	Fe
Go	Go	go-U	Ua
tobann	tobann	tobann-A	Aqp
thit	thit	tit-V	Vmis
Gruama	Gruama	gruama-A	Aqc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
agam	agam	ag-P	Pr1-s
anois	anois	anois-R	Rt
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	ar-N	Ncmsc-e
Ríona	Ríona	ríon-N	Ncfsg
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Is	Is	is-W	Wp-i
ansin	ansin	ansin-R	Rt|Rl
a	a	a-Q	Q-r
thit	thit	tit-V	Vmis
píosa	píosa	píosa-N	Ncmsc
páipéir	páipéir	páipéar-N	Ncmsg
as	as	as-S	Sp
póca	póca	póca-N	Ncmsc
Ghruama	Ghruama	gruama-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Liosta	Liosta	liosta-N	Ncmsc
atá	atá	bí-V	Vmip---r
ann	ann	i-P	Pr3ms
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-S	Sp
Ríona	Ríona	ríon-N	Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Liosta	Liosta	liosta-N	Ncmsc
bronntanais	bronntanais	bronntanas-N	Ncmsg|Ncmpc
Nollag	Nollag	Nollaig-N	Ncfsg
.	.	.-F	Fe
Cá	Cá	cá-R	Rq
bhfuair	bhfuair	faigh-V	Vmis
tusa	tusa	tú-P	Pp2-s-e
é	é	é-P	Pp3ms
seo	seo	seo-P	Pd
?	?	?-F	Fq
’	’	’-F	Fa
Cá	Cá	cá-R	Rq
bhfuair	bhfuair	faigh-V	Vmis
tusa	tusa	tú-P	Pp2-s-e
é	é	é-P	Pp3ms
seo	seo	seo-P	Pd
?	?	?-F	Fq
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
brón	brón	brón-N	Ncmsc
orm	orm	ar-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gruama	Gruama	gruama-A	Aqc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
habair	habair	abair-V	Vmm-2s-n
aon	aon	aon-D	Dq
rud	rud	rud-N	Ncmsc
le	le	le-S	Sp
Daidí	Daidí	daidí-N	Ncmsc
na	na	na-T	Tdfsg
Nollag	Nollag	Nollaig-N	Ncfsg
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
dhéanfaidh	dhéanfaidh	déan-V	Vmif---n
mé	mé	mé-P	Pp1-s
aon	aon	aon-D	Dq
rud	rud	rud-N	Ncmsc
mar	mar	mar-C	Cs
sin	sin	sin-W	W
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
arís	arís	arís-R	Rg
!	!	!-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Tuigim	Tuigim	tuig-V	Vmip1s
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
anois	anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	ar-N	Ncmsc-e
Ríona	Ríona	ríon-N	Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tusa	Tusa	tú-P	Pp2-s-e
a	a	a-Q	Q-r
thóg	thóg	tóg-V	Vmis
an	an	an-T	Td-s
liosta	liosta	liosta-N	Ncmsc
ceart	ceart	ceart-A	Aq-msc
!	!	!-F	Fe
Tar	Tar	tar-V	Vmm-2s
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
liomsa	liomsa	le-P	Pr1-s-e
anois	anois	anois-R	Rt
agus	agus	agus-C	Cc
tabharfaimid	tabharfaimid	tabhair-V	Vmif1p
na	na	na-T	Td-p
bronntanais	bronntanais	bronntanas-N	Ncmpc
chearta	chearta	ceart-A	Aq--pc
do	do	do-S	Sp
na	na	na-T	Td-p
sióga	sióga	sióg-N	Ncfpc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Maith	Maith	Maith-N	Npmsc
go leor	go leor	go_leor-A	Aq
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gruama	Gruama	gruama-A	Aqc
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
Ríona	Ríona	ríon-N	Ncfsg
agus	agus	agus-C	Cc
Gruama	Gruama	gruama-A	Aqp
na	na	na-T	Td-p
bronntanais	bronntanais	bronntanas-N	Ncmpc
chearta	chearta	ceart-N	Ncmpc
do	do	do-S	Sp
na	na	na-T	Td-p
sióga	sióga	sióg-N	Ncfpc
.	.	.-F	Fe
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
míle	míle	míle-M	Mc
maith	maith	maith-N	Ncfsc
agaibh	agaibh	ag-P	Pr2-p
.	.	.-F	Fe
