‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
Daidí	Daidí	daidí-N	Ncmsc
ag	ag	ag-S	Sp
gabháil	gabháil	gabh-N	Nv
ag	ag	ag-S	Sp
siopadóireacht	siopadóireacht	siopadóir-N	Nv-----n
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
le	le	le-S	Sp
Gearóid	Gearóid	Gearóid-N	Npmsc
tráthnóna	tráthnóna	tráthnóna-N	Ncmsg
amháin	amháin	amháin-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
dtiocfaidh	dtiocfaidh	tar-V	Vmif
tú	tú	tú-P	Pp2-s
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
linn	linn	le-P	Pr1-p
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Tiocfaidh	Tiocfaidh	tar-V	Vmif
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
airgead	airgead	airgead-N	Ncmsc
a	a	a-U	U
tharraingt	tharraingt	tarraing-N	Nv
as	as	as-P	Pr3ms
mo	mo	mo-D	Dp1-s
chuntas	chuntas	cuntas-N	Nv|Ncmsc
in	in	i-S	Sp
Oifig	Oifig	oifig-N	Ncfsc
an	an	an-T	Td-s
Phoist	Phoist	post-N	Ncmsg
.	.	.-F	Fe
’	’	’-F	Fa
Bhreathnaigh	Bhreathnaigh	breathnaigh-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gclog	gclog	clog-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Gabh	Gabh	gabh-V	Vmm-2s
i	i	i-S	Sp
leith	leith	leith-N	Ncfsc
uait	uait	ó-P	Pr2-s
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Dúnann	Dúnann	dún-V	Vmip
Oifig	Oifig	oifig-N	Ncfsc
an	an	an-T	Td-s
Phoist	Phoist	post-N	Ncmsg
ag	ag	ag-S	Sp
a	a	a-U	Um
cúig	cúig	cúig-M	Mc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
dóigh	dóigh	dóigh-N	Ncfsc
go	go	go-Q	Q
mbeidh	mbeidh	bí-V	Vmif
tusa	tusa	tú-P	Pp2-s-e
scaitheamh	scaitheamh	scaitheamh-N	Ncmsc
in	in	i-S	Sp
Oifig	Oifig	oifig-N	Ncfsc
an	an	an-T	Td-s
Phoist	Phoist	post-N	Ncmsg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
le	le	le-S	Sp
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Feicfidh	Feicfidh	feic-V	Vmif
muid	muid	muid-P	Pp1-p
sa	sa	i-S	Spa-s
gcaife	gcaife	caife-N	Ncmsc
thú	thú	tú-P	Pp2-s
.	.	.-F	Fe
’	’	’-F	Fa
Bhí	Bhí	bí-V	Vmis
dúil	dúil	dúil-N	Ncfsc
ag	ag	ag-S	Sp
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
i	i	i-S	Sp
gcupán	gcupán	cupán-N	Ncmsc
caife	caife	caife-N	Ncmsg
.	.	.-F	Fe
Is	Is	is-W	Wp-i
fada	fada	fada-A	Aqp
liom	liom	le-P	Pr1-s
go	go	go-Q	Q
dtiocfaidh	dtiocfaidh	tar-V	Vmif
an	an	an-T	Td-s
Satharn	Satharn	Satharn-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an-lear	an-lear	lear-N	Ncmsc
daoine	daoine	duine-N	Ncmpg|Ncmpc
in	in	i-S	Sp
Oifig	Oifig	oifig-N	Ncfsc
an	an	an-T	Td-s
Phoist	Phoist	post-N	Ncmsg
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuaigh	chuaigh	téigh-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
isteach	isteach	isteach-R	Rd
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sé	sé	sé-P	Pp3msn
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
istigh	istigh	istigh-R	Rl
nó	nó	nó-C	Cc
gur	gur	gur-Q	Q--s
oscail	oscail	oscail-V	Vmis
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
le	le	le-S	Sp
beirt	beirt	beirt-N	Ncfsc
fhear	fhear	fear-N	Ncmpg
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
púicíní	púicíní	púicín-N	Ncmpc
orthu	orthu	ar-P	Pr3-p
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
gunna	gunna	gunna-N	Ncmsc
ag	ag	ag-S	Sp
fear	fear	fear-N	Ncmsc
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Síos	Síos	síos-R	Rd
libh	libh	le-P	Pr2-p
ar	ar	ar-S	Sp
an	an	an-T	Td-s
urlár	urlár	urlár-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
fear	fear	fear-N	Ncmsc
an	an	an-T	Td-s
ghunna	ghunna	gunna-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
ná	ná	ná-Q	Qnm
bíodh	bíodh	bí-V	Vmm-3s-n
cor	cor	cor-N	Ncmsc
asaibh	asaibh	as-P	Pr2-p
!	!	!-F	Fe
’	’	’-F	Fa
Suas	Suas	suas-R	Rd
leis	leis	le-S	Sp
an	an	an-T	Td-s
bhfear	bhfear	fear-N	Ncmsc
eile	eile	eile-D	Dd
chuig	chuig	chuig-S	Sp
an	an	an-T	Td-s
gcuntar	gcuntar	cuntar-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tabhair	Tabhair	tabhair-V	Vmm-2s
dom	dom	do-P	Pr1-s
an	an	an-T	Td-s
t-airgead	t-airgead	airgead-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
atá	atá	bí-V	Vmip---r
sa	sa	i-S	Spa-s
taisceadán	taisceadán	taisceadán-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
de	de	de-S	Sp
bhéic	bhéic	béic-N	Ncfsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
máistir	máistir	máistir-N	Ncmsc
poist	poist	post-N	Ncmsg|Ncmpc
,	,	,-F	Fi
‘	‘	‘-X	Xx
nó	nó	nó-C	Cc
is	is	agus-C	Cc
duitse	duitse	do-P	Pr2-s-e
is	is	is-U	U
measa	measa	olc-A	Aqc
!	!	!-F	Fe
’	’	’-F	Fa
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
chroí	chroí	croí-N	Ncmsc
ina	ina	i-S	Spp-s
bhéal	bhéal	béal-N	Ncmsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
máistir	máistir	máistir-N	Ncmsc
poist	poist	post-N	Ncmsg|Ncmpc
.	.	.-F	Fe
An	An	an-T	Td-s
fear	fear	fear-N	Ncmsc
bocht	bocht	bocht-A	Aq-msc
!	!	!-F	Fe
Thóg	Thóg	tóg-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
t-airgead	t-airgead	airgead-N	Ncmsc
amach	amach	amach-R	Rd
as	as	as-S	Sp
an	an	an-T	Td-s
taisceadán	taisceadán	taisceadán-N	Ncmsc
agus	agus	agus-C	Cc
shín	shín	sín-V	Vmis
sé	sé	sé-P	Pp3msn
chuig	chuig	chuig-S	Sp
an	an	an-T	Td-s
ngadaí	ngadaí	gadaí-N	Ncmsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Rug	Rug	beir-V	Vmis
an	an	an-T	Td-s
gadaí	gadaí	gadaí-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
airgead	airgead	airgead-N	Ncmsc
agus	agus	agus-C	Cc
shac	shac	sac-V	Vmis
sé	sé	sé-P	Pp3msn
isteach	isteach	isteach-R	Rd
ina	ina	i-S	Spp-s
mhála	mhála	mála-N	Ncmsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
amach	amach	amach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
lena	lena	le-S	Spp-s
chomrádaí	chomrádaí	comrádaí-N	Ncmsc
de	de	de-S	Sp
rite	rite	rite-X	Xfen
reaite	reaite	reaite-A	Av
.	.	.-F	Fe
Is	Is	is-W	Wp-i
fada	fada	fada-A	Aqp
liom	liom	le-P	Pr1-s
go	go	go-Q	Q
dtiocfaidh	dtiocfaidh	tar-V	Vmif
an	an	an-T	Td-s
Satharn	Satharn	Satharn-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
a	a	a-Q	Q-r
chuir	chuir	cuir-V	Vmis
moill	moill	moill-N	Ncfsc
ort	ort	ar-P	Pr2-s
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
de	de	de-S	Sp
Ghearóid	Ghearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cheap	Cheap	ceap-V	Vmis
muid	muid	muid-P	Pp1-p
gur	gur	is-W	Wsdi
ag	ag	ag-S	Sp
robáil	robáil	robáil-N	Nv
Oifig	Oifig	oifig-N	Ncfsc
an	an	an-T	Td-s
Phoist	Phoist	post-N	Ncmsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
tú	tú	tú-P	Pp2-s
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
tá	tá	bí-V	Vmip
dath	dath	dath-N	Ncmsc
an	an	an-T	Td-s
bháis	bháis	bás-N	Ncmsg
ort	ort	ar-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Suigh	Suigh	suigh-V	Vmm-2s
síos	síos	síos-R	Rd
ansin	ansin	ansin-R	Rt|Rl
agus	agus	agus-C	Cc
bíodh	bíodh	bí-V	Vmm-3s
cupán	cupán	cupán-N	Ncmsc
tae	tae	tae-N	Ncmsg|Ncmsc
agat	agat	ag-P	Pr2-s
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Fan	Fan	fan-V	Vmm-2s
go	go	go-Q	Q-s
gcloise	gcloise	clois-V	Vmsp
sibh	sibh	sibh-P	Pp2-p
céard	céard	cé-W	W--q
a	a	a-Q	Q-r
tharla	tharla	tarlaigh-V	Vmis
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
tar éis	tar éis	tar_éis-S	Spc
scaithimh	scaithimh	scaitheamh-N	Ncmsg
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
inis	inis	inis-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
dóibh	dóibh	do-P	Pr3-p
ó	ó	ó-S	Sp
thús	thús	tús-N	Ncmsc
deireadh	deireadh	abair-V	Vmih
.	.	.-F	Fe
‘	‘	‘-X	Xx
Chuile	Chuile	gach-D	Dq
sheans	sheans	seans-N	Ncmsg
gur	gur	is-W	Wsdi
gunna	gunna	gunna-N	Ncmsc
bréige	bréige	bréige-N	Ncfsg|Ncfsc|Ncfsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
acu	acu	ag-P	Pr3-p
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
cheapfainn	cheapfainn	ceap-V	Vmc-1s-n
é	é	é-P	Pp3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Go	Go	go-S	Sp
sábhála	sábhála	sábháil-N	Nv--g|Ncfsg
Dia	Dia	dia-N	Ncmsc
sinn	sinn	sinn-P	Pp1-p
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
D	D	D-X	Xl
’	’	’-F	Fa
fhéadfaidís	fhéadfaidís	féad-V	Vmc-3p
daoine	daoine	duine-N	Ncmpc
a	a	a-U	U
bheith	bheith	bí-N	Nv
maraithe	maraithe	maraigh-A	Av
acu	acu	ag-P	Pr3-p
!	!	!-F	Fe
’	’	’-F	Fa
Agus	Agus	agus-C	Cc
é	é	é-P	Pp3ms
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
bhealach	bhealach	bealach-N	Ncmsc
amach	amach	amach-R	Rd
as	as	as-S	Sp
an	an	an-T	Td-s
gcaife	gcaife	caife-N	Ncmsc
chonaic	chonaic	feic-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
fear	fear	fear-N	Ncmsc
ag	ag	ag-S	Sp
brú	brú	brúigh-N	Nv
an	an	an-T	Td-s
tseanchairr	tseanchairr	carr-N	Ncmsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
feicthe	feicthe	feic-A	Av
níos	níos	níos-U	Uc
túisce	túisce	túisce-R	Rt
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
siúráilte	siúráilte	siúráilte-A	Aqp
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
sin	sin	sin-D	Dd
feicthe	feicthe	feic-A	Av
agam	agam	ag-P	Pr1-s
in	in	i-S	Sp
áit	áit	áit-N	Ncfsc
éicint	éicint	éicint-A	Aq-fsc
cheana	cheana	cion-R	Rg|Ncmsg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	an-T	Td-s
Dhaidí	Dhaidí	daidí-N	Ncmsc
!	!	!-F	Fe
A	A	a-U	Uv
Mhamaí	Mhamaí	mamaí-N	Ncmpv|Ncfsv
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
ceapadh	ceapadh	ceap-N	Nv
gurb	gurb	is-W	Wpdi
in	in	sin-P	Pd
iad	iad	iad-P	Pp3-p
na	na	na-T	Td-p
gadaithe	gadaithe	gadaí-N	Ncmpc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
teannadh	teannadh	teann-N	Nv
leis	leis	le-S	Sp
an	an	an-T	Td-s
seancharr	seancharr	carr-N	Ncfsc|Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhí	Bhí	bí-V	Vmis
púicíní	púicíní	púicín-N	Ncmpc
orthu	orthu	ar-P	Pr3-p
ach	ach	ach-C	Cs
aithním	aithním	aithin-V	Vmip1s
iad	iad	iad-P	Pp3-p
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
féin	féin	féin-P	Px
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Más	Más	má-N	Ncmsc|Csw
in	in	sin-P	Pd
iad	iad	iad-P	Pp3-p
iad	iad	iad-P	Pp3-p
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
,	,	,-F	Fi
‘	‘	‘-X	Xx
b	b	b-X	Xl
’	’	’-F	Fa
fhearr	fhearr	maith-A	Aqc
dúinn	dúinn	do-P	Pr1-p
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
leis	leis	le-S	Sp
na	na	na-T	Td-p
Gardaí	Gardaí	garda-N	Ncmpc
.	.	.-F	Fe
’	’	’-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
inis	inis	inis-N	Npmsc
Gearóid	Gearóid	Gearóid-N	Npm-g|Npmsg|Npmsc
a	a	a-D	Dp3
scéal	scéal	scéal-N	Ncmsc
do	do	do-S	Sp
na	na	na-T	Td-p
Gardaí	Gardaí	garda-N	Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Sin	Sin	sin-W	W
iad	iad	iad-P	Pp3-p
na	na	na-T	Td-p
gadaithe	gadaithe	gadaí-N	Ncmpc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
leo	leo	le-P	Pr3-p
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
síneadh	síneadh	sín-N	Nv
a	a	a-D	Dp3
mhéire	mhéire	méar-N	Ncfsg
chuig	chuig	chuig-S	Sp
an	an	an-T	Td-s
seancharr	seancharr	carr-N	Ncfsc|Ncmsc
.	.	.-F	Fe
Díreach	Díreach	díreach-N	Ncmsc
ansin	ansin	ansin-R	Rt|Rl
lig	lig	lig-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
béic	béic	béic-N	Ncfsc
aisti	aisti	as-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
na	na	na-T	Td-p
gadaithe	gadaithe	gadaí-N	Ncmpc
ag	ag	ag-S	Sp
éalú	éalú	éalaigh-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Breathnaigh	Breathnaigh	breathnaigh-V	Vmm-2s
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
éalú	éalú	éalaigh-N	Nv
!	!	!-F	Fe
’	’	’-F	Fa
Bhí	Bhí	bí-V	Vmis
na	na	na-T	Td-p
gadaithe	gadaithe	gadaí-N	Ncmpc
ag	ag	ag-S	Sp
éalú	éalú	éalaigh-N	Nv
ceart	ceart	ceart-N	Ncmpg|Ncmsc
go leor	go leor	go_leor-A	Aq
.	.	.-F	Fe
Rith	Rith	rith-V	Vmm-2s|Vmis
na	na	na-T	Td-p
Gardaí	Gardaí	garda-N	Ncmpc
go dtí	go dtí	go_dtí-S	Spc
a	a	a-D	Dp3
gcarr	gcarr	carr-N	Ncmsc|Ncfsc
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
lig	lig	lig-V	Vmm-2s-n
dóibh	dóibh	do-P	Pr3-p
éalú	éalú	éalú-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
lig	lig	lig-V	Vmm-2s-n
dóibh	dóibh	do-P	Pr3-p
éalú	éalú	éalú-N	Ncmsc
!	!	!-F	Fe
’	’	’-F	Fa
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ródheireanach	ródheireanach	deireanach-A	Aqp
!	!	!-F	Fe
Faoin	Faoin	faoi-S	Spa-s
am	am	am-N	Ncmsc
seo	seo	seo-D	Dd
bhí	bhí	bí-V	Vmis
na	na	na-T	Td-p
gadaithe	gadaithe	gadaí-N	Ncmpc
ag	ag	ag-S	Sp
imeacht	imeacht	imigh-N	Nv
síos	síos	síos-R	Rd
an	an	an-T	Td-s
bóthar	bóthar	bóthar-N	Ncmsc
de	de	de-S	Sp
rite	rite	rite-X	Xfen
reaite	reaite	reaite-A	Av
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
éalú	éalú	éalaigh-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
go	go	go-U	Ua
dobrónach	dobrónach	dobrónach-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-S	Sp
aire	aire	aire-N	Ncmsc|Ncfsc
duit	duit	do-P	Pr2-s
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
sa	sa	i-S	Spa-s
diabhal	diabhal	diabhal-N	Ncmsc
atá	atá	bí-V	Vmip---r
ag	ag	ag-S	Sp
tarlú	tarlú	tarlaigh-N	Nv
?	?	?-F	Fq
’	’	’-F	Fa
Bhí	Bhí	bí-V	Vmis
leoraí	leoraí	leoraí-N	Ncmsc
mór	mór	mór-A	Aq-msc
tar éis	tar éis	tar_éis-S	Spc
stopadh	stopadh	stop-N	Nv
i lár	i lár	i_lár-S	Spc
an	an	an-T	Td-s
bhóthair	bhóthair	bóthar-N	Ncmsg
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
na	na	na-T	Td-p
gadaithe	gadaithe	gadaí-N	Ncmpc
in ann	in ann	in_ann-S	Spc
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
thar	thar	thar-S	Sp
an	an	an-T	Td-s
leoraí	leoraí	leoraí-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmm-2s
na	na	na-T	Td-p
gadaithe	gadaithe	gadaí-N	Ncmpc
amach	amach	amach-R	Rd
as	as	as-S	Sp
an	an	an-T	Td-s
gcarr	gcarr	carr-N	Ncmsc|Ncfsc
de	de	de-S	Sp
léim	léim	léim-N	Ncfsc
.	.	.-F	Fe
Síos	Síos	síos-R	Rd
an	an	an-T	Td-s
buaile	buaile	buaile-N	Ncfsc
leo	leo	le-P	Pr3-p
de	de	de-S	Sp
rite	rite	rite-X	Xfen
reaite	reaite	reaite-A	Av
agus	agus	agus-C	Cc
na	na	na-T	Td-p
Gardaí	Gardaí	garda-N	Ncmpc
ina	ina	i-S	Spp-p
ndiaidh	ndiaidh	diaidh-N	Ns-s
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sé	sé	sé-P	Pp3msn
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
nó	nó	nó-C	Cc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
ghadaithe	ghadaithe	gadaí-N	Ncmpc
tógtha	tógtha	tóg-A	Av
ag	ag	ag-S	Sp
na	na	na-T	Td-p
Gardaí	Gardaí	garda-N	Ncmpc
.	.	.-F	Fe
Cúpla	Cúpla	cúpla-N	Ncmsc|Dq
lá	lá	lá-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|Dd
bhí	bhí	bí-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
in	in	i-S	Sp
Oifig	Oifig	oifig-N	Ncfsc
an	an	an-T	Td-s
Phoist	Phoist	post-N	Ncmsg
arís	arís	arís-R	Rg
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	an-T	Td-s
Ghearóid	Ghearóid	Gearóid-N	Npmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
máistir	máistir	máistir-N	Ncmsc
poist	poist	post-N	Ncmsg|Ncmpc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
isteach	isteach	isteach-R	Rd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhí	Bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
faire	faire	fair-N	Nv
amach	amach	amach-R	Rd
duit	duit	do-P	Pr2-s
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
bronntanas	bronntanas	bronntanas-N	Ncmsc
anseo	anseo	anseo-R	Rl
agam	agam	ag-P	Pr1-s
duit	duit	do-P	Pr2-s
.	.	.-F	Fe
’	’	’-F	Fa
Agus	Agus	agus-C	Cc
shín	shín	sín-V	Vmis
sé	sé	sé-P	Pp3msn
bosca	bosca	bosca-N	Ncmsc
mór	mór	mór-A	Aq-msc
chuig	chuig	chuig-S	Sp
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
atá	atá	bí-V	Vmip---r
ann	ann	i-P	Pr3ms
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
de	de	de-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Feicfidh	Feicfidh	feic-V	Vmif
tú	tú	tú-P	Pp2-s
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
osclóidh	osclóidh	oscail-V	Vmif
tú	tú	tú-P	Pp2-s
é	é	é-P	Pp3ms
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
máistir	máistir	máistir-N	Ncmsc
poist	poist	post-N	Ncmsg|Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
tá	tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
siúráilte	siúráilte	siúráilte-A	Aqp
go	go	go-Q	Q
dtaitneoidh	dtaitneoidh	taitin-V	Vmif
sé	sé	sé-P	Pp3msn
thar	thar	thar-S	Sp
cionn	cionn	ceann-N	Ncfsd
leat	leat	le-P	Pr2-s
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
Daidí	Daidí	daidí-N	Ncmsc
ag	ag	ag-S	Sp
gabháil	gabháil	gabh-N	Nv
ag	ag	ag-S	Sp
siopadóireacht	siopadóireacht	siopadóir-N	Nv-----n
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
le	le	le-S	Sp
Gearóid	Gearóid	Gearóid-N	Npmsc
tráthnóna	tráthnóna	tráthnóna-N	Ncmsg
amháin	amháin	amháin-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
dtiocfaidh	dtiocfaidh	tar-V	Vmif
tú	tú	tú-P	Pp2-s
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
linn	linn	le-P	Pr1-p
?	?	?-F	Fq
’	’	’-F	Fa
