Ní	Ní	ní-Q	Qn
ritheann	ritheann	rith-V	Vmip---n
daoine	daoine	duine-N	Ncmpc
uait	uait	ó-P	Pr2-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
haon	haon	aon-M	Mc
dragún	dragún	dragún-N	Ncmsc
ceart	ceart	ceart-A	Aq-msc
tusa	tusa	tú-P	Pp2-s-e
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
na	na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpc
leis	leis	le-S	Sp
an	an	an-T	Td-s
dragún	dragún	dragún-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
ritheann	ritheann	rith-V	Vmip---n
daoine	daoine	duine-N	Ncmpc
uait	uait	ó-P	Pr2-s
nuair	nuair	nuair-C	Cs
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
féidir	féidir	féidir-N	Ns-s
leat	leat	le-P	Pr2-s
eitilt	eitilt	eitil-N	Nv
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
féidir	féidir	féidir-N	Ns-s
leat	leat	le-P	Pr2-s
a	a	a-Q	Q-r
fheiceann	fheiceann	feic-V	Vmip
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
tú	tú	tú-P	Pp2-s
,	,	,-F	Fi
’	’	’-F	Fa
lasracha	lasracha	lasair-N	Ncfpc
a	a	a-Q	Q-r
scaoileadh	scaoileadh	scaoil-V	Vmih
as	as	as-P	Pr3ms|Sp|Ncmsc
do	do	do-S	Sp
bhéal	bhéal	béal-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
na	na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpc
.	.	.-F	Fe
An	An	an-T	Td-s
dragún	dragún	dragún-N	Ncmsc
bocht	bocht	bocht-A	Aq-msc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
trína	trína	trí-S	Spp-s
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
féidir	féidir	féidir-N	Ns-s
liom	liom	le-P	Pr1-s
eitilt	eitilt	eitil-N	Nv
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
féidir	féidir	féidir-N	Ns-s
liom	liom	le-P	Pr1-s
lasracha	lasracha	lasair-N	Ncfpc
a	a	a-Q	Q-r
scaoileadh	scaoileadh	scaoil-V	Vmih
as	as	as-P	Pr3ms
mo	mo	mo-D	Dp1-s
bhéal	bhéal	béal-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
ritheann	ritheann	rith-V	Vmip---n
daoine	daoine	duine-N	Ncmpc
uaim	uaim	ó-P	Pr1-s
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
na	na	na-T	Td-p
sióga	sióga	sióg-N	Ncfpc
é	é	é-P	Pp3ms
seo	seo	seo-P	Pd
bhí	bhí	bí-V	Vmis
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
ritheann	ritheann	rith-V	Vmip---n
daoine	daoine	duine-N	Ncmpc
uaim	uaim	ó-P	Pr1-s
nuair	nuair	nuair-C	Cs
trua	trua	trua-N	Ncfsc
acu	acu	ag-P	Pr3-p
don	don	do-S	Spa-s
dragún	dragún	dragún-N	Ncmsc
.	.	.-F	Fe
a	a	a-Q	Q-r
fheiceann	fheiceann	feic-V	Vmip
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
mé	mé	mé-P	Pp1-s
,	,	,-F	Fi
’	’	’-F	Fa
‘	‘	‘-X	Xx
An	An	an-T	Td-s
dragún	dragún	dragún-N	Ncmsc
bocht	bocht	bocht-A	Aq-msc
!	!	!-F	Fe
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
siad	siad	siad-P	Pp3-pn
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
dragún	dragún	dragún-N	Ncmsc
.	.	.-F	Fe
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Labhair	Labhair	labhair-V	Vmis|Vmm-2s
na	na	na-T	Td-p
sióga	sióga	sióg-N	Ncfpc
leis	leis	le-S	Sp
an	an	an-T	Td-s
dragún	dragún	dragún-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tar	Tar	thar-S	Sp
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
linne	linne	linn-N	Ncfsg|Ncfpc|Ncfsg|Pr1-p-e|Ncfsg
go	go	go-S	Sp
Dún	Dún	dún-N	Ncmsc
na	na	na-T	Tdfsg
Sí	Sí	is-W	Wp-i-3
,	,	,-F	Fi
’	’	’-F	Fa
Siúd	Siúd	siúd-P	Pd
leis	leis	le-S	Sp
na	na	na-T	Td-p
sióga	sióga	sióg-N	Ncfpc
go	go	go-S	Sp
Dún	Dún	dún-N	Ncmsc
na	na	na-T	Tdfsg
Sí	Sí	is-W	Wp-i-3
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
siad	siad	siad-P	Pp3-pn
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
agus	agus	agus-C	Cc
an	an	an-T	Td-s
dragún	dragún	dragún-N	Ncmsc
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
Istigh	Istigh	istigh-R	Rl
sa	sa	i-S	Spa-s
dún	dún	dún-N	Ncmsc
chonaic	chonaic	feic-V	Vmis
an	an	an-T	Td-s
dragún	dragún	dragún-N	Ncmsc
doras	doras	doras-N	Ncmsc
mór	mór	mór-A	Aq-msc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
fógra	fógra	fógra-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
leis	leis	le-S	Sp
na	na	na-T	Td-p
sióga	sióga	sióg-N	Ncfpc
sa	sa	i-S	Spa-s
seomra	seomra	seomra-N	Ncmsc
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
leis	leis	le-S	Sp
an	an	an-T	Td-s
dragún	dragún	dragún-N	Ncmsc
ina	ina	i-S	Spp-p
ndiaidh	ndiaidh	diaidh-N	Ns-s
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
na	na	na-T	Td-p
sióga	sióga	sióg-N	Ncfpc
ag	ag	ag-S	Sp
oscailt	oscailt	oscail-N	Nv
na	na	na-T	Td-p
gcófraí	gcófraí	cófra-N	Ncmpg
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
sé	sé	sé-P	Pp3msn
faighte	faighte	faigh-A	Av
fós	fós	fós-R	Rg
agaibh	agaibh	ag-P	Pr2-p
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Síle	Síle	Síle-N	Ncfsc|Npfsc
Sióg	Sióg	sióg-N	Ncfsc|Ncfpg
tar éis	tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Sibéal	Sibéal	Sibéal-N	Npfsc
.	.	.-F	Fe
Go	Go	go-U	Ua
tobann	tobann	tobann-A	Aqp
lig	lig	lig-V	Vmis
Aoife	Aoife	Aoife-N	Npfsc
béic	béic	béic-N	Ncfsc
aisti	aisti	as-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
focal	focal	focal-N	Ncmsc
‘	‘	‘-X	Xx
Misneach	Misneach	misneach-N	Ncmsc
’	’	’-F	Fa
scríofa	scríofa	scríobh-A	Av
i	i	i-S	Sp
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
agam	agam	ag-P	Pr1-s
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
litreacha	litreacha	litir-N	Ncfpc
móra	móra	mór-A	Aq--pc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbuidéal	mbuidéal	buidéal-N	Ncmsc
.	.	.-F	Fe
tógáil	tógáil	tógáil-N	Ncfsc
buidéil	buidéil	buidéal-N	Ncmsg|Ncmpc
amach	amach	amach-R	Rd
as	as	as-S	Sp
cófra	cófra	cófra-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Scaoilfidh	Scaoilfidh	scaoil-V	Vmif
tú	tú	tú-P	Pp2-s
lasracha	lasracha	lasair-N	Ncfpc
as	as	as-N	Ncmpg|Ncmsc|Pr3ms|Sp
do	do	do-S	Sp
bhéal	bhéal	béal-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
Shín	Shín	Sín-N	Npfsc
Aoife	Aoife	Aoife-N	Npf-g|Npfsc
an	an	an-T	Td-s
buidéal	buidéal	buidéal-N	Ncmsc
chuig	chuig	chuig-S	Sp
an	an	an-T	Td-s
dragún	dragún	dragún-N	Ncmsc
.	.	.-F	Fe
arsa	arsa	arsa-V	Vmis
Sibéal	Sibéal	Sibéal-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
deoch	deoch	deoch-N	Ncfsc
dhraíochta	dhraíochta	draíocht-N	Ncfsg
atá	atá	bí-V	Vmip---r
sa	sa	i-S	Spa-s
bhuidéal	bhuidéal	buidéal-N	Ncmsc
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
rithfidh	rithfidh	rith-V	Vmif
daoine	daoine	duine-N	Ncmpc
uait	uait	ó-P	Pr2-s
nuair	nuair	nuair-C	Cs
seo	seo	seo-P	Pd
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Má	Má	má-C	Cs
ólann	ólann	ól-V	Vmip
tú	tú	tú-P	Pp2-s
a	a	a-Q	Q-r
fheicfidh	fheicfidh	feic-V	Vmif
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
tú	tú	tú-P	Pp2-s
,	,	,-F	Fi
’	’	’-F	Fa
deoch	deoch	deoch-V	Vmm-2s
seo	seo	seo-P	Pd
beidh	beidh	bí-V	Vmif
misneach	misneach	misneach-N	Ncmsc
agat	agat	ag-P	Pr2-s
.	.	.-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Síle	Síle	Síle-N	Ncfsc|Npfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
dragún	dragún	dragún-N	Ncmsc
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
dragún	dragún	dragún-N	Ncmsc
ceart	ceart	ceart-A	Aq-msc
anois	anois	anois-R	Rt
tú	tú	tú-P	Pp2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Síle	Síle	Síle-N	Ncfsc|Npfsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
Misneach	Misneach	misneach-N	Ncmsc
an	an	an-T	Td-s
t-ainm	t-ainm	ainm-N	Ncmsc
nua	nua	nua-A	Aqp
atá	atá	bí-V	Vmip---r
ort	ort	ar-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Aoife	Aoife	Aoife-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Go	Go	go-U	Ua
maith	maith	maith-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
dragún	dragún	dragún-N	Ncmsc
agus	agus	agus-C	Cc
‘	‘	‘-X	Xx
Misneach	Misneach	misneach-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
dragún	dragún	dragún-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Sin	Sin	sin-P	Pd
thosaigh	thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
ól	ól	ól-N	Nv
as	as	as-S	Sp
an	an	an-T	Td-s
mbuidéal	mbuidéal	buidéal-N	Ncmsc
.	.	.-F	Fe
ainm	ainm	ainm-N	Ncmsc
deas	deas	deas-A	Aq-msc
.	.	.-F	Fe
’	’	’-F	Fa
Amach	Amach	amach-R	Rd
leo	leo	le-P	Pr3-p
as	as	as-S	Sp
an	an	an-T	Td-s
dún	dún	dún-N	Ncmsc
ansin	ansin	ansin-R	Rt|Rl
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
féidir	féidir	féidir-N	Ns-s
leat	leat	le-P	Pr2-s
eitilt	eitilt	eitil-N	Nv
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
féidir	féidir	féidir-N	Ns-s
leat	leat	le-P	Pr2-s
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
haon	haon	aon-M	Mc
dragún	dragún	dragún-N	Ncmsc
ceart	ceart	ceart-A	Aq-msc
tusa	tusa	tú-P	Pp2-s-e
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
lasracha	lasracha	lasair-N	Ncfpc
a	a	a-Q	Q-r
scaoileadh	scaoileadh	scaoil-V	Vmih
as	as	as-P	Pr3ms|Sp|Ncmsc
do	do	do-S	Sp
bhéal	bhéal	béal-N	Ncmsc
.	.	.-F	Fe
na	na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpc
leis	leis	le-S	Sp
an	an	an-T	Td-s
dragún	dragún	dragún-N	Ncmsc
nuair	nuair	nuair-C	Cs
Ní	Ní	is-W	Wp-in
ritheann	ritheann	rith-V	Vmip
daoine	daoine	duine-N	Ncmpc
uait	uait	ó-P	Pr2-s
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
é	é	é-P	Pp3ms
.	.	.-F	Fe
a	a	a-Q	Q-r
fheiceann	fheiceann	feic-V	Vmip
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
tú	tú	tú-P	Pp2-s
.	.	.-F	Fe
’	’	’-F	Fa
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
d	d	d-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmm-2s
an	an	an-T	Td-s
dragún	dragún	dragún-N	Ncmsc
a	a	a-D	Dp3
bhéal	bhéal	béal-N	Ncmsc
.	.	.-F	Fe
Lig	Lig	lig-V	Vmis
sé	sé	sé-P	Pp3msn
béic	béic	béic-N	Ncfsc
as	as	as-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
dragún	dragún	dragún-N	Ncmsc
ceart	ceart	ceart-A	Aq-msc
anois	anois	anois-R	Rt
mé	mé	mé-P	Pp1-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
na	na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpc
ag	ag	ag-S	Sp
gáire	gáire	gáir-N	Nv
Ach	Ach	ach-C	Cs
ansin	ansin	ansin-R	Rt|Rl
scaoil	scaoil	scaoil-V	Vmis
an	an	an-T	Td-s
dragún	dragún	dragún-N	Ncmsc
lasracha	lasracha	lasair-N	Ncfpg|Ncfpc
faoi	faoi	faoi-P	Pr3ms
.	.	.-F	Fe
móra	móra	mór-A	Aq--pv|Aq--pg|Aq--pc
amach	amach	amach-R	Rd
as	as	as-P	Pr3ms
a	a	a-D	Dp3
bhéal	bhéal	béal-N	Ncmsc
.	.	.-F	Fe
Rithigí	Rithigí	rith-V	Vmm-2p
uaidh	uaidh	ó-P	Pr3ms
!	!	!-F	Fe
Baineadh	Baineadh	bain-V	Vmis0
geit	geit	geit-N	Ncfsc
as	as	as-S	Sp
na	na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
dragún	dragún	dragún-N	Ncmsc
ceart	ceart	ceart-A	Aq-msc
é	é	é-P	Pp3ms
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
siad	siad	siad-P	Pp3-pn
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
féidir	féidir	féidir-N	Ns-s
leis	leis	le-P	Pr3ms
lasracha	lasracha	lasair-N	Ncfpc
a	a	a-Q	Q-r
scaoileadh	scaoileadh	scaoil-V	Vmih
as	as	as-P	Pr3ms
a	a	a-D	Dp3
bhéal	bhéal	béal-N	Ncmsc
!	!	!-F	Fe
Rithigí	Rithigí	rith-V	Vmm-2p
uaidh	uaidh	ó-P	Pr3ms
!	!	!-F	Fe
’	’	’-F	Fa
Shín	Shín	Sín-N	Npfsc
Misneach	Misneach	misneach-N	Ncmsc
amach	amach	amach-R	Rd
a	a	a-D	Dp3
sciatháin	sciatháin	sciathán-N	Ncmpc
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
eitilt	eitilt	eitil-N	Nv
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
eitil	eitil	eitil-V	Vmis
sé	sé	sé-P	Pp3msn
suas	suas	suas-R	Rd
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
eitil	eitil	eitil-V	Vmis
sé	sé	sé-P	Pp3msn
síos	síos	síos-R	Rd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Táim	Táim	bí-V	Vmip1s
ag	ag	ag-S	Sp
eitilt	eitilt	eitil-N	Nv
.	.	.-F	Fe
Táim	Táim	bí-V	Vmip1s
ag	ag	ag-S	Sp
eitilt	eitilt	eitil-N	Nv
!	!	!-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
eitilt	eitilt	eitil-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
na	na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpc
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Rithigí	Rithigí	rith-V	Vmm-2p
uaidh	uaidh	ó-P	Pr3ms
!	!	!-F	Fe
Rithigí	Rithigí	rith-V	Vmm-2p
uaidh	uaidh	ó-P	Pr3ms
!	!	!-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
go	go	go-U	Ua
maith	maith	maith-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
Rith	Rith	rith-V	Vmm-2s|Vmis
na	na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpc
soir	soir	soir-A	Aqp
agus	agus	agus-C	Cc
siar	siar	siar-R	Rd
.	.	.-F	Fe
arsa	arsa	arsa-V	Vmis
na	na	na-T	Td-p
sióga	sióga	sióg-N	Ncfpc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
eitil	eitil	eitil-V	Vmm-2s
Misneach	Misneach	misneach-N	Ncmsc
ina	ina	i-S	Spp-p
ndiaidh	ndiaidh	diaidh-N	Ns-s
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
bhuail	bhuail	buail-V	Vmis
tuirse	tuirse	tuirse-N	Ncfsc
é	é	é-P	Pp3ms
agus	agus	agus-C	Cc
Misneach	Misneach	misneach-N	Ncmsc
leis	leis	le-S	Sp
na	na	na-T	Td-p
sióga	sióga	sióg-N	Ncfpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
dragún	dragún	dragún-N	Ncmsc
stop	stop	stop-V	Vmis
sé	sé	sé-P	Pp3msn
den	den	de-S	Spa-s
eitilt	eitilt	eitilt-N	Ncfsc
.	.	.-F	Fe
ceart	ceart	ceart-N	Ncmsc
anois	anois	anois-R	Rt
mé	mé	mé-P	Pp1-s
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
míle	míle	míle-M	Mc
maith	maith	maith-N	Ncfsc
agaibh	agaibh	ag-P	Pr2-p
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Is	Is	is-W	Wpri
dragún	dragún	dragún-N	Ncmsc
ceart	ceart	ceart-A	Aq-msc
anois	anois	anois-R	Rt
mé	mé	mé-P	Pp1-s
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
abhaile	abhaile	abhaile-R	Rd
leis	leis	le-P	Pr3ms
go	go	go-U	Ua
sásta	sásta	sásta-A	Aqp
.	.	.-F	Fe
