Lá	Lá	lá-N	Ncmsc
breá	breá	breá-A	Aq-msc
samhraidh	samhraidh	samhradh-N	Ncmsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
istigh	istigh	istigh-R	Rl
sa	sa	i-S	Spa-s
choinicéar	choinicéar	coinicéar-N	Ncmsc
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
fuar	fuar	fuar-A	Aqp
dorcha	dorcha	dorcha-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
fuar	fuar	fuar-A	Aqp
dorcha	dorcha	dorcha-A	Aqp
istigh	istigh	istigh-R	Rl
anseo	anseo	anseo-R	Rl
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cóilín	Cóilín	Cóilín-N	Npmsc
Coinín	Coinín	Coinín-N	Npmsg|Npmsc
lena	lena	le-S	Spp-s
mháthair	mháthair	máthair-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liom	liom	le-P	Pr1-s
dul	dul	téigh-N	Nv
amach	amach	amach-R	Rd
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Amach	Amach	amach-R	Rd
leat	leat	le-P	Pr2-s
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
a	a	a-D	Dp3
mháthair	mháthair	máthair-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
caithfidh	caithfidh	caith-V	Vmif
tú	tú	tú-P	Pp2-s
a	a	a-U	U
bheith	bheith	bí-N	Nv
cúramach	cúramach	cúramach-A	Aqp
.	.	.-F	Fe
Ná	Ná	ná-Q	Qnm
himigh	himigh	imigh-V	Vmm-2s-n
rófhada	rófhada	fada-A	Aqp
ó	ó	ó-S	Sp
bhaile	bhaile	baile-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
Caithfidh	Caithfidh	caith-V	Vmif
tú	tú	tú-P	Pp2-s
a	a	a-U	U
bheith	bheith	bí-N	Nv
cúramach	cúramach	cúramach-A	Aqp
.	.	.-F	Fe
Siúd	Siúd	siúd-P	Pd
le	le	le-S	Sp
Cóilín	Cóilín	Cóilín-N	Npmsc
amach	amach	amach-R	Rd
as	as	as-S	Sp
an	an	an-T	Td-s
gcoinicéar	gcoinicéar	coinicéar-N	Ncmsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
é	é	é-P	Pp3ms
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
féileacáin	féileacáin	féileacán-N	Ncmpc
agus	agus	agus-C	Cc
chonaic	chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
éin	éin	éan-N	Ncmpc
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
beacha	beacha	beach-N	Ncfpc
agus	agus	agus-C	Cc
chonaic	chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
bláthanna	bláthanna	bláth-N	Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
maith	maith	maith-A	Aqp
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
samhradh	samhradh	samhradh-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cóilín	Cóilín	Cóilín-N	Npmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
tar éis	tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
bhuail	bhuail	buail-V	Vmis
ocras	ocras	ocras-N	Ncmsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Chuimhnigh	Chuimhnigh	cuimhnigh-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
na	na	na-T	Td-p
cairéid	cairéid	cairéad-N	Ncmsg
bhreátha	bhreátha	breá-A	Aq-fsv
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sa	sa	i-S	Spa-s
gharraí	gharraí	garraí-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ansin	ansin	ansin-R	Rt|Rl
chuimhnigh	chuimhnigh	cuimhnigh-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
rud	rud	rud-N	Ncmsc
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
a	a	a-D	Dp3
mháthair	mháthair	máthair-N	Ncfsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Dúirt	Dúirt	abair-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
liom	liom	le-P	Pr1-s
gan	gan	gan-S	Sp
imeacht	imeacht	imigh-N	Nv
rófhada	rófhada	fada-A	Aqp
ó	ó	ó-S	Sp
bhaile	bhaile	baile-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cóilín	Cóilín	Cóilín-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
tá	tá	bí-V	Vmip
ocras	ocras	ocras-N	Ncmsc
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
’	’	’-F	Fa
Isteach	Isteach	isteach-R	Rd
leis	leis	le-S	Sp
sa	sa	i-S	Spa-s
gharraí	gharraí	garraí-N	Ncmsc
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
ithe	ithe	ith-N	Nv
na	na	na-T	Td-p
gcairéad	gcairéad	cairéad-N	Ncmpg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
na	na	na-T	Td-p
cairéid	cairéid	cairéad-N	Ncmpc
seo	seo	seo-D	Dd
breá	breá	breá-R	Ri
blasta	blasta	blasta-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ansin	ansin	ansin-R	Rt|Rl
chuala	chuala	clois-V	Vmis
Cóilín	Cóilín	Cóilín-N	Npmsc
glór	glór	glór-N	Ncmsc
.	.	.-F	Fe
Léim	Léim	léim-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
.	.	.-F	Fe
Cé	Cé	cé-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
ann	ann	i-P	Pr3ms
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
feirmeoir	feirmeoir	feirmeoir-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tusa	Tusa	tú-P	Pp2-s-e
atá	atá	bí-V	Vmip---r
ann	ann	i-P	Pr3ms
arís	arís	arís-R	Rg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
feirmeoir	feirmeoir	feirmeoir-N	Ncmsc
de	de	de-S	Sp
bhéic	bhéic	béic-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bailigh	Bailigh	bailigh-V	Vmm-2s
leat	leat	le-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
bhithiúnaigh	bhithiúnaigh	bithiúnach-N	Ncmsv
!	!	!-F	Fe
Bailigh	Bailigh	bailigh-V	Vmm-2s
leat	leat	le-P	Pr2-s
!	!	!-F	Fe
’	’	’-F	Fa
Bailigh	Bailigh	bailigh-V	Vmm-2s
leat	leat	le-P	Pr2-s
!	!	!-F	Fe
Rith	Rith	rith-V	Vmis
Cóilín	Cóilín	Cóilín-N	Npmsc
.	.	.-F	Fe
Rith	Rith	rith-V	Vmm-2s|Vmis
an	an	an-T	Td-s
feirmeoir	feirmeoir	feirmeoir-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
.	.	.-F	Fe
Cóilín	Cóilín	Cóilín-N	Npmsc
bocht	bocht	bocht-A	Aq-msc
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
chroí	chroí	croí-N	Ncmsc
ina	ina	i-S	Spp-s
bhéal	bhéal	béal-N	Ncmsc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Cá	Cá	cá-R	Rq
raibh	raibh	bí-V	Vmis---d
a	a	a-D	Dp3
mháthair	mháthair	máthair-N	Ncfsc
?	?	?-F	Fq
Cá	Cá	cá-R	Rq
raibh	raibh	bí-V	Vmis---d
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
?	?	?-F	Fq
Tamall	Tamall	tamall-N	Ncmsc
roimhe	roimhe	roimh-P	Pr3ms
sin	sin	sin-P	Pd|W
shábháil	shábháil	sábháil-V	Vmis|Nv|Ncfsc
Caoimhe	Caoimhe	Caoimhe-N	Npf-g|Npfsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
cá	cá	cá-R	Rq
raibh	raibh	bí-V	Vmis---d
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
anois	anois	anois-R	Rt
?	?	?-F	Fq
Rith	Rith	rith-V	Vmis
Cóilín	Cóilín	Cóilín-N	Npmsc
amach	amach	amach-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbóthar	mbóthar	bóthar-N	Ncmsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
feirmeoir	feirmeoir	feirmeoir-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
.	.	.-F	Fe
Síos	Síos	síos-R	Rd
an	an	an-T	Td-s
bóthar	bóthar	bóthar-N	Ncmsc
leis	leis	le-P	Pr3ms
,	,	,-F	Fi
síos	síos	síos-R	Rd
,	,	,-F	Fi
síos	síos	síos-R	Rd
,	,	,-F	Fi
síos	síos	síos-R	Rd
nó	nó	nó-C	Cc
gur	gur	gur-Q	Q--s
shroich	shroich	sroich-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
abhainn	abhainn	abhainn-N	Ncfsc
.	.	.-F	Fe
Cóilín	Cóilín	Cóilín-N	Npmsc
bocht	bocht	bocht-A	Aq-msc
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
chroí	chroí	croí-N	Ncmsc
ina	ina	i-S	Spp-s
bhéal	bhéal	béal-N	Ncmsc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
féidir	féidir	féidir-N	Ns-s
liom	liom	le-P	Pr1-s
snámh	snámh	snámh-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
,	,	,-F	Fi
‘	‘	‘-X	Xx
agus	agus	agus-C	Cc
tá	tá	bí-V	Vmip
an	an	an-T	Td-s
feirmeoir	feirmeoir	feirmeoir-N	Ncmsc
sa	sa	i-S	Spa-s
tóir	tóir	tóir-N	Ncfsc
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
’	’	’-F	Fa
Shuigh	Shuigh	suigh-V	Vmis
sé	sé	sé-P	Pp3msn
síos	síos	síos-R	Rd
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
caoineadh	caoineadh	caoin-N	Nv
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ansin	ansin	ansin-R	Rt|Rl
chuala	chuala	clois-V	Vmis
Cóilín	Cóilín	Cóilín-N	Npmsc
glór	glór	glór-N	Ncmsc
eile	eile	eile-D	Dd
.	.	.-F	Fe
Glór	Glór	glór-N	Ncmsc
deas	deas	deas-R	Ri
séimh	séimh	séimh-A	Aqp
.	.	.-F	Fe
Cé	Cé	cé-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
ann	ann	i-R	Rl|Pr3ms
ach	ach	ach-S	Sp
Darach	Darach	Darach-N	Npmsc
Dobharchú	Dobharchú	dobharchú-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
bí	bí	bí-V	Vmm-2s-n
ag	ag	ag-S	Sp
caoineadh	caoineadh	caoin-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Darach	Darach	Darach-N	Npmsc
le	le	le-S	Sp
Cóilín	Cóilín	Cóilín-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Suas	Suas	suas-R	Rd
leat	leat	le-P	Pr2-s
ar	ar	ar-N	Ncmsc
mo	mo	mo-D	Dp1-s
dhroim	dhroim	droim-N	Ncmsc
agus	agus	agus-C	Cc
tabharfaidh	tabharfaidh	tabhair-V	Vmif
mé	mé	mé-P	Pp1-s
trasna	trasna	trasna-S	Sp
na	na	na-T	Tdfsg
habhann	habhann	abhainn-N	Ncfsg
tú	tú	tú-P	Pp2-s
.	.	.-F	Fe
’	’	’-F	Fa
Suas	Suas	suas-R	Rd
leat	leat	le-P	Pr2-s
ar	ar	is-W	Wssi|Wpdi|Wpsi
mo	mo	mo-D	Dp1-s
dhroim	dhroim	droim-N	Ncmsc
.	.	.-F	Fe
Siúd	Siúd	siúd-P	Pd
trasna	trasna	trasna-S	Sp
na	na	na-T	Tdfsg
habhann	habhann	abhainn-N	Ncfsg
le	le	le-S	Sp
Darach	Darach	Darach-N	Npmsc
agus	agus	agus-C	Cc
Cóilín	Cóilín	Cóilín-N	Npmsc
ar	ar	is-W	Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
dhroim	dhroim	droim-N	Ncmsc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
shroich	shroich	sroich-V	Vmis
siad	siad	siad-P	Pp3-pn
an	an	an-T	Td-s
taobh	taobh	taobh-N	Ncmsc
eile	eile	eile-D	Dd
shuigh	shuigh	suigh-V	Vmis
Cóilín	Cóilín	Cóilín-N	Npmsc
síos	síos	síos-R	Rd
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
le	le	le-S	Sp
Darach	Darach	Darach-N	Npmsc
Dobharchú	Dobharchú	dobharchú-N	Ncmsg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhan	fhan	fan-V	Vmis
siad	siad	siad-P	Pp3-pn
ansin	ansin	ansin-R	Rt|Rl
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
nó	nó	nó-C	Cc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
dorcha	dorcha	dorcha-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nach	Nach	nach-Q	Qnr|Qnq
bhfuil	bhfuil	bí-V	Vmip---d|Vmip---n
sé	sé	sé-P	Pp3msn
in	in	i-S	Sp
am	am	am-N	Ncmsc
agatsa	agatsa	ag-P	Pr2-s-e
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
abhaile	abhaile	abhaile-R	Rd
anois	anois	anois-R	Rt
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Darach	Darach	Darach-N	Npmsc
le	le	le-S	Sp
Cóilín	Cóilín	Cóilín-N	Npmsc
ansin	ansin	ansin-R	Rt|Rl
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cóilín	Cóilín	Cóilín-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Suas	Suas	suas-R	Rd
leat	leat	le-P	Pr2-s
ar	ar	ar-N	Ncmsc
mo	mo	mo-D	Dp1-s
dhroim	dhroim	droim-N	Ncmsc
,	,	,-F	Fi
más	más	má-C	Csw
ea	ea	ea-P	Pp3-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
dobharchú	dobharchú	dobharchú-N	Ncmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
agus	agus	agus-C	Cc
tabharfaidh	tabharfaidh	tabhair-V	Vmif
mé	mé	mé-P	Pp1-s
trasna	trasna	trasna-S	Sp
na	na	na-T	Tdfsg
habhann	habhann	abhainn-N	Ncfsg
arís	arís	arís-R	Rg
tú	tú	tú-P	Pp2-s
.	.	.-F	Fe
’	’	’-F	Fa
Tabharfaidh	Tabharfaidh	tabhair-V	Vmif
mé	mé	mé-P	Pp1-s
trasna	trasna	trasna-S	Sp
na	na	na-T	Tdfsg
habhann	habhann	abhainn-N	Ncfsg
arís	arís	arís-R	Rg
tú	tú	tú-P	Pp2-s
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
shroich	shroich	sroich-V	Vmis
siad	siad	siad-P	Pp3-pn
an	an	an-T	Td-s
taobh	taobh	taobh-N	Ncmsc
eile	eile	eile-D	Dd
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
tásc	tásc	tásc-N	Ncmsc
ná	ná	ná-C	Cc
tuairisc	tuairisc	tuairisc-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhfeirmeoir	bhfeirmeoir	feirmeoir-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Táim	Táim	bí-V	Vmip1s
slán	slán	slán-N	Ncmsc
sábháilte	sábháilte	sábháil-A	Aqp|Av
anois	anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cóilín	Cóilín	Cóilín-N	Npmsc
le	le	le-S	Sp
Darach	Darach	Darach-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
míle	míle	míle-M	Mc
maith	maith	maith-N	Ncfsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Dharach	Dharach	Darach-N	Npfsg
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
fáilte	fáilte	fáilte-N	Ncfsc
romhat	romhat	roimh-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Chóilín	Chóilín	Chóilín-N	Npmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
dobharchú	dobharchú	dobharchú-N	Ncmsc
.	.	.-F	Fe
Táim	Táim	bí-V	Vmip1s
slán	slán	slán-N	Ncmsc
sábháilte	sábháilte	sábháil-A	Aqp|Av
anois	anois	anois-R	Rt
.	.	.-F	Fe
Suas	Suas	suas-R	Rd
an	an	an-T	Td-s
bóthar	bóthar	bóthar-N	Ncmsc
le	le	le-S	Sp
Cóilín	Cóilín	Cóilín-N	Npmsc
ansin	ansin	ansin-R	Rt|Rl
,	,	,-F	Fi
suas	suas	suas-R	Rd
,	,	,-F	Fi
suas	suas	suas-R	Rd
,	,	,-F	Fi
suas	suas	suas-R	Rd
nó	nó	nó-C	Cc
gur	gur	gur-Q	Q--s
shroich	shroich	sroich-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
baile	baile	baile-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
mháthair	mháthair	máthair-N	Ncfsc
ina	ina	i-S	Spp-p|Spp-s
suí	suí	suí-N	Ncmsc
cois	cois	cois-S	Sp
tine	tine	tine-N	Ncfsc
go	go	go-U	Ua
brónach	brónach	brónach-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
a	a	a-U	Uv
Chóilín	Chóilín	Chóilín-N	Npmsc
!	!	!-F	Fe
Cá	Cá	cá-R	Rq
raibh	raibh	bí-V	Vmis---d
tú	tú	tú-P	Pp2-s
,	,	,-F	Fi
a	a	a-U	Uv
stór	stór	stór-N	Ncmsv
?	?	?-F	Fq
Cá	Cá	cá-R	Rq
raibh	raibh	bí-V	Vmis---d
tú	tú	tú-P	Pp2-s
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
leis	leis	le-P	Pr3ms
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
sé	sé	sé-P	Pp3msn
isteach	isteach	isteach-R	Rd
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
inis	inis	inis-V	Vmis
Cóilín	Cóilín	Cóilín-N	Npmsc
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
ó	ó	ó-S	Sp
thús	thús	tús-N	Ncmsc
deireadh	deireadh	abair-V	Vmih
dá	dá	do-S	Spp-s
mháthair	mháthair	máthair-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Dúirt	Dúirt	abair-V	Vmis
tú	tú	tú-P	Pp2-s
liom	liom	le-P	Pr1-s
gan	gan	gan-S	Sp
dul	dul	téigh-N	Nv
rófhada	rófhada	fada-A	Aqp
ó	ó	ó-S	Sp
bhaile	bhaile	baile-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
bhuail	bhuail	buail-V	Vmis
ocras	ocras	ocras-N	Ncmsc
mé	mé	mé-P	Pp1-s
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Is	Is	agus-W	Wp-i|Cc
maith	maith	maith-V	Vmm-2s|Aqp|Ncfsc
an	an	an-T	Td-s
rud	rud	rud-N	Ncmsc
é	é	é-P	Pp3ms
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
dobharchú	dobharchú	dobharchú-N	Ncmsc
ann	ann	i-R	Rl|Pr3ms
le	le	le-S	Sp
haire	haire	aire-N	Ncfsc|Ncmsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
duit	duit	do-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
a	a	a-D	Dp3
mháthair	mháthair	máthair-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	agus-C	Cc
maith	maith	maith-V	Vmm-2s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cóilín	Cóilín	Cóilín-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
mé	mé	mé-P	Pp1-s
cúramach	cúramach	cúramach-A	Aqp
as	as	as-S	Sp
seo	seo	seo-P	Pd
amach	amach	amach-R	Rd
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
imeoidh	imeoidh	imigh-V	Vmif---n
mé	mé	mé-P	Pp1-s
rófhada	rófhada	fada-A	Aqp
ó	ó	ó-S	Sp
bhaile	bhaile	baile-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
Beidh	Beidh	bí-V	Vmif
mé	mé	mé-P	Pp1-s
cúramach	cúramach	cúramach-A	Aqp
as	as	as-S	Sp
seo	seo	seo-P	Pd
amach	amach	amach-R	Rd
.	.	.-F	Fe
