Lá	Lá	lá-N	Ncmsc
breá	breá	breá-A	Aq-msc
samhraidh	samhraidh	samhradh-N	Ncmsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níor	Níor	is-W	Ws-in
cheart	cheart	ceart-A	Aqp
a	a	a-U	U
bheith	bheith	bí-N	Nv
istigh	istigh	istigh-R	Rl
lá	lá	lá-N	Ncmsc
breá	breá	breá-A	Aq-msc
mar	mar	mar-S	Sp
seo	seo	seo-P	Pd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tabharfaidh	Tabharfaidh	tabhair-V	Vmif
mé	mé	mé-P	Pp1-s
Aoibheann	Aoibheann	Aoibheann-N	Npfsc
amach	amach	amach-R	Rd
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
caithfidh	caithfidh	caith-V	Vmif
tusa	tusa	tú-P	Pp2-s-e
fanacht	fanacht	fan-N	Ncmsc|Nv
anseo	anseo	anseo-R	Rl
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
le	le	le-S	Sp
Glic	Glic	glic-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Glic	Glic	glic-A	Aqp
bocht	bocht	bocht-A	Aqp
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Aoibheann	Aoibheann	Aoibheann-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
leis	leis	le-P	Pr3ms
dul	dul	téigh-N	Nv
amach	amach	amach-R	Rd
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
sé	sé	sé-P	Pp3msn
fanacht	fanacht	fan-N	Ncmsc|Nv
anseo	anseo	anseo-R	Rl
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bíonn	Bíonn	bí-V	Vmig
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
troid	troid	troid-N	Nv
le	le	le-S	Sp
madraí	madraí	madra-N	Ncmpc
eile	eile	eile-D	Dd
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Bhuf	Bhuf	Bhuf-N	Npmsc
!	!	!-F	Fe
Bhuf	Bhuf	Bhuf-N	Npmsc
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Glic	Glic	glic-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Isteach	Isteach	isteach-R	Rd
leat	leat	le-P	Pr2-s
sa	sa	i-S	Spa-s
bhugaí	bhugaí	bugaí-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
le	le	le-S	Sp
hAoibheann	hAoibheann	hAoibheann-N	Nc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	is-W	Wp-in
mó	mó	mó-A	Aqc|Aqp
ná	ná	ná-C	Cs|Cc
sásta	sásta	sásta-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Aoibheann	Aoibheann	Aoibheann-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
maith	maith	maith-A	Aqp
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
bugaí	bugaí	bugaí-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
béiceadh	béiceadh	béic-N	Nv
.	.	.-F	Fe
Rug	Rug	beir-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
ar	ar	ar-S	Sp
Aoibheann	Aoibheann	Aoibheann-N	Npfsc
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
bhugaí	bhugaí	bugaí-N	Ncmsc
í	í	í-P	Pp3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
bhfuilimid	bhfuilimid	bí-V	Vmip1p-d
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
Aoibheann	Aoibheann	Aoibheann-N	Npfsc
tar éis	tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Go	Go	go-S	Sp
dtí	dtí	tí-N	Ncmsc|Ncfsc
an	an	an-T	Td-s
siopa	siopa	siopa-N	Ncmsg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
páipéar	páipéar	páipéar-N	Ncmsc
a	a	a-U	U
cheannach	cheannach	ceannaigh-N	Nv
.	.	.-F	Fe
’	’	’-F	Fa
Bhí	Bhí	bí-V	Vmis
Aoibheann	Aoibheann	Aoibheann-N	Npfsc
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
sí	sí	sí-P	Pp3fsn
é	é	é-P	Pp3ms
sin	sin	sin-P	Pd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
maith	maith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
an	an	an-T	Td-s
siopa	siopa	siopa-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
Aoibheann	Aoibheann	Aoibheann-N	Npfsc
na	na	na-T	Td-p
milseáin	milseáin	milseán-N	Ncmsg
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
thosaigh	thosaigh	tosaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
béiceadh	béiceadh	béic-N	Nv
arís	arís	arís-R	Rg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
milseáin	milseáin	milseán-N	Ncmpc
uaim	uaim	ó-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
,	,	,-F	Fi
‘	‘	‘-X	Xx
ceann	ceann	ceann-N	Ncmsc
acu	acu	ag-P	Pr3-p
sin	sin	sin-P	Pd|W
agus	agus	agus-C	Cc
ceann	ceann	ceann-N	Ncmpg|Ncmsc
acu	acu	ag-P	Pr3-p
sin	sin	sin-P	Pd|W
agus	agus	agus-C	Cc
ceann	ceann	ceann-N	Ncmpg|Ncmsc
acu	acu	ag-P	Pr3-p
sin	sin	sin-P	Pd
!	!	!-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
bac	bac	bac-V	Vmm-2s-n
leo	leo	le-P	Pr3-p
sin	sin	sin-P	Pd
.	.	.-F	Fe
Níl	Níl	bí-V	Vmip---n
siad	siad	siad-P	Pp3-pn
go	go	go-U	Ua
maith	maith	maith-A	Aqp
duit	duit	do-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
agus	agus	agus-C	Cc
amach	amach	amach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
bhfuilimid	bhfuilimid	bí-V	Vmip1p-d
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
anois	anois	anois-R	Rt
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
Aoibheann	Aoibheann	Aoibheann-N	Npfsc
tar éis	tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ag	Ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
sa	sa	i-S	Spa-s
pháirc	pháirc	páirc-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Aoibheann	Aoibheann	Aoibheann-N	Npfsc
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
sí	sí	sí-P	Pp3fsn
é	é	é-P	Pp3ms
sin	sin	sin-P	Pd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
maith	maith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
an	an	an-T	Td-s
pháirc	pháirc	páirc-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
shroich	shroich	sroich-V	Vmis
siad	siad	siad-P	Pp3-pn
an	an	an-T	Td-s
pháirc	pháirc	páirc-N	Ncfsc
scaoil	scaoil	scaoil-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
Aoibheann	Aoibheann	Aoibheann-N	Npfsc
amach	amach	amach-R	Rd
as	as	as-S	Sp
an	an	an-T	Td-s
mbugaí	mbugaí	bugaí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
anois	anois	anois-R	Rt
.	.	.-F	Fe
Tabharfaimid	Tabharfaimid	tabhair-V	Vmif1p
bia	bia	bia-N	Ncmsc
do	do	do-S	Sp
na	na	na-T	Td-p
lachain	lachain	lacha-N	Ncfpc
ar	ar	ar-S	Sp
dtús	dtús	tús-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
Siúd	Siúd	siúd-P	Pd
leo	leo	le-P	Pr3-p
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
loch	loch	loch-N	Ncmsc
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
Aoibheann	Aoibheann	Aoibheann-N	Npfsc
arán	arán	arán-N	Ncmsc
do	do	do-S	Sp
na	na	na-T	Td-p
lachain	lachain	lacha-N	Ncfpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
maith	maith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
na	na	na-T	Td-p
lachain	lachain	lacha-N	Ncfpc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
Faoin	Faoin	faoi-S	Spa-s
am	am	am-N	Ncmsc
seo	seo	seo-D	Dd
bhí	bhí	bí-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
bocht	bocht	bocht-A	Aq-msc
tuirseach	tuirseach	tuirseach-A	Aq-msc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bí	Bí	bí-N	Ncfsc
ag	ag	ag-S	Sp
rith	rith	rith-N	Nv
leat	leat	le-P	Pr2-s
ansin	ansin	ansin-R	Rt|Rl
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
le	le	le-S	Sp
hAoibheann	hAoibheann	hAoibheann-N	Nc
,	,	,-F	Fi
‘	‘	‘-X	Xx
agus	agus	agus-C	Cc
léifidh	léifidh	léigh-V	Vmif
mise	mise	mé-P	Pp1-s-e
an	an	an-T	Td-s
páipéar	páipéar	páipéar-N	Ncmsc
.	.	.-F	Fe
Maith	Maith	Maith-N	Npmsc
an	an	an-T	Td-s
cailín	cailín	cailín-N	Ncmsg
.	.	.-F	Fe
’	’	’-F	Fa
Bhí	Bhí	bí-V	Vmis
Aoibheann	Aoibheann	Aoibheann-N	Npfsc
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
sí	sí	sí-P	Pp3fsn
féileacán	féileacán	féileacán-N	Ncmsc
agus	agus	agus-C	Cc
rith	rith	rith-V	Vmis
sí	sí	sí-P	Pp3fsn
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
sí	sí	sí-P	Pp3fsn
beach	beach	beach-X	Xfev
agus	agus	agus-C	Cc
rith	rith	rith-V	Vmis
sí	sí	sí-P	Pp3fsn
ina	ina	i-S	Spp-s
diaidh	diaidh	diaidh-N	Ns-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
maith	maith	maith-A	Aqp
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
pháirc	pháirc	páirc-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Aoibheann	Aoibheann	Aoibheann-N	Npfsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
ansin	ansin	ansin-R	Rt|Rl
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
Aoibheann	Aoibheann	Aoibheann-N	Npfsc
an	an	an-T	Td-s
madra	madra	madra-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	an-T	Td-s
Dhaidí	Dhaidí	daidí-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
Glic	Glic	glic-A	Aqp
anseo	anseo	anseo-R	Rl
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
Glic	Glic	glic-A	Aqp
anseo	anseo	anseo-R	Rl
!	!	!-F	Fe
’	’	’-F	Fa
Ach	Ach	ach-C	Cs
níor	níor	is-W	Ws-in
chuala	chuala	cual-N	Ncmpv
Daidí	Daidí	daidí-N	Ncmsc|Ncmsg
í	í	í-P	Pp3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
léamh	léamh	léigh-N	Nv
an	an	an-T	Td-s
pháipéir	pháipéir	páipéar-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tar	Tar	thar-S	Sp
anseo	anseo	anseo-R	Rl
,	,	,-F	Fi
a	a	a-D	Dp3
Ghlic	Ghlic	glic-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Aoibheann	Aoibheann	Aoibheann-N	Npfsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
madra	madra	madra-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tar	Tar	thar-S	Sp
anseo	anseo	anseo-R	Rl
.	.	.-F	Fe
’	’	’-F	Fa
Ach	Ach	ach-S	Sp
rith	rith	rith-N	Ncmsc
an	an	an-T	Td-s
madra	madra	madra-N	Ncmsg
uaithi	uaithi	ó-P	Pr3fs
.	.	.-F	Fe
Rith	Rith	rith-V	Vmis
Aoibheann	Aoibheann	Aoibheann-N	Npfsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
leag	leag	leag-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
uaidh	uaidh	ó-P	Pr3ms
an	an	an-T	Td-s
páipéar	páipéar	páipéar-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	an-T	Td-s
Aoibheann	Aoibheann	Aoibheann-N	Npfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
in	in	i-S	Sp
am	am	am-N	Ncmsc
againn	againn	ag-P	Pr1-p
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
abhaile	abhaile	abhaile-R	Rd
.	.	.-F	Fe
’	’	’-F	Fa
Ach	Ach	ach-S	Sp
tásc	tásc	tásc-N	Ncmsc
ná	ná	ná-C	Cs|Cc
tuairisc	tuairisc	tuairisc-N	Ncfsc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ar	ar	ar-S	Sp
Aoibheann	Aoibheann	Aoibheann-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	an-T	Td-s
Aoibheann	Aoibheann	Aoibheann-N	Npfsc
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
arís	arís	arís-R	Rg
.	.	.-F	Fe
Ach	Ach	ach-S	Sp
tásc	tásc	tásc-N	Ncmsc
ná	ná	ná-C	Cs|Cc
tuairisc	tuairisc	tuairisc-N	Ncfsc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ar	ar	ar-S	Sp
Aoibheann	Aoibheann	Aoibheann-N	Npfsc
.	.	.-F	Fe
Léim	Léim	léim-V	Vmip1s|Vmm-2s|Vmis
Daidí	Daidí	daidí-N	Ncmsc
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
chroí	chroí	croí-N	Ncmsc
ina	ina	i-S	Spp-s
bhéal	bhéal	béal-N	Ncmsc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
,	,	,-F	Fi
a	a	a-U	Uv
Aoibheann	Aoibheann	Aoibheann-N	Npf-v
?	?	?-F	Fq
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
Daidí	Daidí	daidí-N	Ncmsc
bocht	bocht	bocht-A	Aq-msc
!	!	!-F	Fe
Rith	Rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
loch	loch	loch-N	Ncmsc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
chroí	chroí	croí-N	Ncmsc
ina	ina	i-S	Spp-s
bhéal	bhéal	béal-N	Ncmsc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
,	,	,-F	Fi
a	a	a-U	Uv
Aoibheann	Aoibheann	Aoibheann-N	Npf-v
?	?	?-F	Fq
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
Ach	Ach	ach-S	Sp
tásc	tásc	tásc-N	Ncmsc
ná	ná	ná-C	Cs|Cc
tuairisc	tuairisc	tuairisc-N	Ncfsc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ar	ar	ar-S	Sp
Aoibheann	Aoibheann	Aoibheann-N	Npfsc
.	.	.-F	Fe
Rith	Rith	rith-V	Vmm-2s|Vmis
Daidí	Daidí	daidí-N	Ncmsc
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
fhaiche	fhaiche	faiche-N	Ncfsc
imeartha	imeartha	imir-A	Aqp|Av
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
chroí	chroí	croí-N	Ncmsc
ina	ina	i-S	Spp-s
bhéal	bhéal	béal-N	Ncmsc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
chuala	chuala	clois-V	Vmis
sé	sé	sé-P	Pp3msn
madra	madra	madra-N	Ncmsc
ag	ag	ag-S	Sp
tafann	tafann	tafainn-N	Nv
.	.	.-F	Fe
Chuala	Chuala	clois-V	Vmis
sé	sé	sé-P	Pp3msn
cailín	cailín	cailín-N	Ncmsc
beag	beag	beag-A	Aq-msc
ag	ag	ag-S	Sp
gáire	gáire	gáir-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	an-T	Td-s
Aoibheann	Aoibheann	Aoibheann-N	Npfsc
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	is-W	Wpdq|Wp-q
tusa	tusa	tú-P	Pp2-s-e
atá	atá	bí-V	Vmip---r
ansin	ansin	ansin-R	Rt|Rl
?	?	?-F	Fq
’	’	’-F	Fa
An	An	is-W	Wpdq|Wp-q
tusa	tusa	tú-P	Pp2-s-e
atá	atá	bí-V	Vmip---r
ansin	ansin	ansin-R	Rt|Rl
?	?	?-F	Fq
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
mé	mé	mé-P	Pp1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Aoibheann	Aoibheann	Aoibheann-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
,	,	,-F	Fi
a	a	a-U	Uv
Dhaidí	Dhaidí	daidí-N	Ncmsv
,	,	,-F	Fi
fuair	fuair	faigh-V	Vmis
mé	mé	mé-P	Pp1-s
deartháir	deartháir	deartháir-N	Ncmsc
nua	nua	nua-A	Aqp
do	do	do-D	Dp2-s
Ghlic	Ghlic	glic-A	Aqp
!	!	!-F	Fe
Ceolán	Ceolán	ceolán-N	Ncmsc
an	an	an-T	Td-s
t-ainm	t-ainm	ainm-N	Ncmsc
atá	atá	bí-V	Vmip---r
air	air	ar-P	Pr3ms
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
a	a	a-U	Uv
Aoibheann	Aoibheann	Aoibheann-N	Npf-v
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
slán	slán	slán-A	Aqp
sábháilte	sábháilte	sábháil-A	Av
.	.	.-F	Fe
Buíochas	Buíochas	buíochas-N	Ncmsc
le	le	le-S	Sp
Dia	Dia	dia-N	Ncmsc
!	!	!-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Bhuf	Bhuf	Bhuf-N	Npmsc
!	!	!-F	Fe
Bhuf	Bhuf	Bhuf-N	Npmsc
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Ceolán	Ceolán	ceolán-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níor	Níor	is-W	Ws-in
cheart	cheart	ceart-A	Aqp
a	a	a-U	U
bheith	bheith	bí-N	Nv
istigh	istigh	istigh-R	Rl
lá	lá	lá-N	Ncmsc
breá	breá	breá-A	Aq-msc
mar	mar	mar-S	Sp
seo	seo	seo-P	Pd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tabharfaidh	Tabharfaidh	tabhair-V	Vmif
mé	mé	mé-P	Pp1-s
Aoibheann	Aoibheann	Aoibheann-N	Npfsc
amach	amach	amach-R	Rd
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
.	.	.-F	Fe
’	’	’-F	Fa
