Áine	Áine	Áine-N	Npfsc
,	,	,-F	Fi
Cuireadh	Cuireadh	cuir-V	Vmm-3s
go	go	go-S	Sp
Páras	Páras	Páras-N	Npmsc
A	A	an-T	Td-s
Áine	Áine	Áine-N	Npfsc
dhil	dhil	dil-A	Aq-fsc
,	,	,-F	Fi
Tá	Tá	bí-V	Vmip
súil	súil	súil-N	Ncfsc
agam	agam	ag-P	Pr1-s
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
go	go	go-U	Ua
maith	maith	maith-A	Aqp
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
aimsir	aimsir	aimsir-N	Ncfsc
go	go	go-U	Ua
hálainn	hálainn	álainn-A	Aqp
anseo	anseo	anseo-R	Rl
i	i	i-S	Sp
bPáras	bPáras	Páras-N	Npmsc
.	.	.-F	Fe
Ar	Ar	is-W	Ws-q
mhaith	mhaith	maith-A	Aqp
leat	leat	le-P	Pr2-s
teacht	teacht	tar-N	Nv
anall	anall	anall-R	Rd
chugam	chugam	chuig-P	Pr1-s
?	?	?-F	Fq
Nach	Nach	is-W	Wp-qn
gearr	gearr	gearr-A	Aqp
go	go	go-Q	Q
mbeidh	mbeidh	bí-V	Vmif
laethanta	laethanta	lá-N	Ncmpc
saoire	saoire	saoire-N	Ncfsg|Ncfsc
agat	agat	ag-P	Pr2-s
?	?	?-F	Fq
Le	Le	le-S	Sp
grá	grá	gráigh-N	Nv
,	,	,-F	Fi
Aintín	Aintín	aintín-N	Ncfsc
Nóra	Nóra	Nóra-N	Npf-g|Npfsc
Bhí	Bhí	bí-V	Vmis
Áine	Áine	Áine-N	Npfsc
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
cuireadh	cuireadh	cuireadh-N	Ncmsc
go	go	go-S	Sp
Páras	Páras	Páras-N	Npmsc
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
le	le	le-S	Sp
Léiní	Léiní	Léiní-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Rachaidh	Rachaidh	téigh-V	Vmif
mé	mé	mé-P	Pp1-s
ann	ann	i-R	Rl|Pr3ms
le	le	le-S	Sp
haghaidh	haghaidh	aghaidh-N	Ncfsc
saoire	saoire	saor-A	Aq-fsg
na	na	na-T	Tdfsg
Cásca	Cásca	Cáisc-N	Ncfsg
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
dul	dul	téigh-N	Nv
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
leat	leat	le-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Léiní	Léiní	Léiní-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liom	liom	le-P	Pr1-s
Túr	Túr	túr-N	Ncmsc
Eiffel	Eiffel	Eiffel-N	Npm-g|Npmsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
Arc	Arc	arc-N	Ncmsc
de	de	de-S	Sp
Triomphe	Triomphe	Triomphe-N	Npmsc
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
tusa	tusa	tú-P	Pp2-s-e
fanacht	fanacht	fan-N	Ncmsc|Nv
ag	ag	ag-S	Sp
baile	baile	baile-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Áine	Áine	Áine-N	Npfsc
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
mó	mó	mó-A	Aqc|Aqp
ná	ná	ná-C	Cs|Cc
sásta	sásta	sásta-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Léiní	Léiní	Léiní-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
tusa	tusa	tú-P	Pp2-s-e
fanacht	fanacht	fan-N	Ncmsc|Nv
ag	ag	ag-S	Sp
baile	baile	baile-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Áine	Áine	Áine-N	Npfsc
le	le	le-S	Sp
Léiní	Léiní	Léiní-N	Npmsc
arís	arís	arís-R	Rg
.	.	.-F	Fe
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
Páras	Páras	Páras-N	Npmsc
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
Páras	Páras	Páras-N	Npmsc
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Léiní	Léiní	Léiní-N	Npmsc
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
Léim	Léim	léim-V	Vmis
sí	sí	sí-P	Pp3fsn
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
mhála	mhála	mála-N	Ncmsc
i	i	i-S	Sp
ngan fhios	ngan fhios	gan_fhios-N	Ncmsc
d	d	d-X	Xl
’	’	’-F	Fa
Áine	Áine	Áine-N	Npfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Áine	Áine	Áine-N	Npfsc
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
maith	maith	maith-A	Aqp
liom	liom	le-P	Pr1-s
Páras	Páras	Páras-N	Npmsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
le	le	le-S	Sp
hAintín	hAintín	aintín-N	Ncfsc
Nóra	Nóra	Nóra-N	Npf-g
.	.	.-F	Fe
Is	Is	is-W	Wp-i
maith	maith	maith-A	Aqp
liom	liom	le-P	Pr1-s
Páras	Páras	Páras-N	Npmsc
.	.	.-F	Fe
Bhuail	Bhuail	buail-V	Vmis
ocras	ocras	ocras-N	Ncmsc
Áine	Áine	Áine-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
arán	arán	arán-N	Ncmsc
a	a	a-U	U
cheannach	cheannach	ceannaigh-N	Nv
dom	dom	do-P	Pr1-s
féin	féin	féin-P	Px
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
agus	agus	agus-C	Cc
amach	amach	amach-R	Rd
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
le	le	le-S	Sp
hÁine	hÁine	Áine-N	Npf-g
san	san	i-S	Spa-s
ardaitheoir	ardaitheoir	ardaitheoir-N	Ncmsc
agus	agus	agus-C	Cc
bhrúigh	bhrúigh	brúigh-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
cnaipe	cnaipe	cnaipe-N	Ncmsc
.	.	.-F	Fe
Bhrúigh	Bhrúigh	brúigh-V	Vmis
sí	sí	sí-P	Pp3fsn
arís	arís	arís-R	Rg
agus	agus	agus-C	Cc
arís	arís	arís-R	Rg
eile	eile	eile-D	Dd
é	é	é-P	Pp3ms
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
níor	níor	is-W	Ws-in
bhog	bhog	bog-A	Aqp
an	an	an-T	Td-s
t-ardaitheoir	t-ardaitheoir	ardaitheoir-N	Ncmsc
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
Áine	Áine	Áine-N	Npfsc
ag	ag	ag-S	Sp
caoineadh	caoineadh	caoin-N	Nv
.	.	.-F	Fe
Ó	Ó	Ó-I	I
,	,	,-F	Fi
a	a	a-D	Dp3
thiarcais	thiarcais	tiarcais-N	Ns-s
!	!	!-F	Fe
Chuala	Chuala	clois-V	Vmis
Léiní	Léiní	Léiní-N	Npmsc
Áine	Áine	Áine-N	Npfsc
ag	ag	ag-S	Sp
caoineadh	caoineadh	caoin-N	Nv
.	.	.-F	Fe
Léim	Léim	léim-V	Vmis
sí	sí	sí-P	Pp3fsn
amach	amach	amach-R	Rd
as	as	as-S	Sp
an	an	an-T	Td-s
mála	mála	mála-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	an-T	Td-s
Léiní	Léiní	Léiní-N	Npmsc
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Áine	Áine	Áine-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cheap	Cheap	ceap-V	Vmis
mé	mé	mé-P	Pp1-s
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
tusa	tusa	tú-P	Pp2-s-e
ag	ag	ag-S	Sp
baile	baile	baile-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
chonaic	chonaic	feic-V	Vmis
Léiní	Léiní	Léiní-N	Npmsc
poll	poll	poll-X	Xfev
beag	beag	beag-N	Ncmsc
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
labhair	labhair	labhair-V	Vmis
sí	sí	sí-P	Pp3fsn
le	le	le-S	Sp
hÁine	hÁine	Áine-N	Npf-g
.	.	.-F	Fe
‘	‘	‘-X	Xx
Má	Má	má-C	Cs
bhrúnn	bhrúnn	brúigh-V	Vmip
tú	tú	tú-P	Pp2-s
an	an	an-T	Td-s
cnaipe	cnaipe	cnaipe-N	Ncmsc
anois	anois	anois-R	Rt
,	,	,-F	Fi
a	a	a-U	Uv
Áine	Áine	Áine-N	Npf-v
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
,	,	,-F	Fi
‘	‘	‘-X	Xx
beidh	beidh	bí-V	Vmif
leat	leat	le-P	Pr2-s
.	.	.-F	Fe
’	’	’-F	Fa
Bhrúigh	Bhrúigh	brúigh-V	Vmis
Áine	Áine	Áine-N	Npfsc
an	an	an-T	Td-s
cnaipe	cnaipe	cnaipe-N	Ncmsg
agus	agus	agus-C	Cc
síos	síos	síos-R	Rd
leis	leis	le-S	Sp
an	an	an-T	Td-s
ardaitheoir	ardaitheoir	ardaitheoir-N	Ncmsc
!	!	!-F	Fe
‘	‘	‘-X	Xx
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
maith	maith	maith-N	Ncfsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Áine	Áine	Áine-N	Npfsc
le	le	le-S	Sp
Léiní	Léiní	Léiní-N	Npmsc
.	.	.-F	Fe
Cheannaigh	Cheannaigh	ceannaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
bronntanas	bronntanas	bronntanas-N	Ncmsc
beag	beag	beag-A	Aq-msc
di	di	do-P	Pr3fs
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
mhála	mhála	mála-N	Ncmsc
leat	leat	le-P	Pr2-s
anois	anois	anois-R	Rt
.	.	.-F	Fe
‘	‘	‘-X	Xx
Isteach	Isteach	isteach-R	Rd
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
mhála	mhála	mála-N	Ncmsc
leat	leat	le-P	Pr2-s
anois	anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Áine	Áine	Áine-N	Npfsc
le	le	le-S	Sp
Léiní	Léiní	Léiní-N	Npmsc
ansin	ansin	ansin-R	Rt|Rl
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
ag	ag	ag-S	Sp
Aintín	Aintín	aintín-N	Ncfsc
Nóra	Nóra	Nóra-N	Npf-g
tú	tú	tú-P	Pp2-s
a	a	a-U	U
bheith	bheith	bí-N	Nv
anseo	anseo	anseo-R	Rl
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
mbeimid	mbeimid	bí-V	Vmif1p
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
anois	anois	anois-R	Rt
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Áine	Áine	Áine-N	Npfsc
le	le	le-S	Sp
hAintín	hAintín	aintín-N	Ncfsc
Nóra	Nóra	Nóra-N	Npf-g
tráthnóna	tráthnóna	tráthnóna-N	Ncmsg|Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Íosfaimid	Íosfaimid	ith-V	Vmif1p
rud	rud	rud-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
ar	ar	ar-S	Sp
dtús	dtús	tús-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Aintín	Aintín	aintín-N	Ncfsc
Nóra	Nóra	Nóra-N	Npf-g|Npfsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
agus	agus	agus-C	Cc
ansin	ansin	ansin-R	Rt|Rl
rachaimid	rachaimid	téigh-V	Vmif1p
ag	ag	ag-S	Sp
spaisteoireacht	spaisteoireacht	spaisteoireacht-N	Ncfsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
dul	dul	téigh-N	Nv
ag	ag	ag-S	Sp
spaisteoireacht	spaisteoireacht	spaisteoireacht-N	Ncfsc
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Léiní	Léiní	Léiní-N	Npmsc
agus	agus	agus-C	Cc
léim	léim	léim-V	Vmis
sí	sí	sí-P	Pp3fsn
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
mála	mála	mála-N	Ncmsc
Áine	Áine	Áine-N	Npf-g
.	.	.-F	Fe
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
dul	dul	téigh-N	Nv
ag	ag	ag-S	Sp
spaisteoireacht	spaisteoireacht	spaisteoireacht-N	Ncfsc
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
dóibh	dóibh	do-P	Pr3-p
béile	béile	béile-N	Ncmsc
breá	breá	breá-A	Aq-msc
a	a	a-U	U
bheith	bheith	bí-N	Nv
ite	ite	ith-A	Av
acu	acu	ag-P	Pr3-p
shiúil	shiúil	siúl-N	Ncmsg
Áine	Áine	Áine-N	Npf-g|Npfsc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
haintín	haintín	aintín-N	Ncfsg
síos	síos	síos-R	Rd
an	an	an-T	Td-s
Champs	Champs	Champs-N	Npmsc
Elysées	Elysées	Elysées-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Sin	Sin	sin-W	W
é	é	é-P	Pp3ms
an	an	an-T	Td-s
Arc	Arc	arc-N	Ncmsc
de	de	de-S	Sp
Triomphe	Triomphe	Triomphe-N	Npmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Aintín	Aintín	aintín-N	Ncfsc
Nóra	Nóra	Nóra-N	Npf-g|Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nach	Nach	is-C	Cs|Wpdin|Wpsin
mór	mór	mór-A	Aqp
atá	atá	bí-V	Vmip---r
sé	sé	sé-P	Pp3msn
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Áine	Áine	Áine-N	Npfsc
.	.	.-F	Fe
Thóg	Thóg	tóg-V	Vmis
Aintín	Aintín	aintín-N	Ncfsc
Nóra	Nóra	Nóra-N	Npf-g|Npfsc
grianghraf	grianghraf	grianghraf-N	Ncmpg|Ncmsc
d	d	d-X	Xl
’	’	’-F	Fa
Áine	Áine	Áine-N	Npfsc
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
os comhair	os comhair	os_comhair-S	Spc
an	an	an-T	Td-s
Arc	Arc	arc-N	Ncmsc
de	de	de-S	Sp
Triomphe	Triomphe	Triomphe-N	Npmsc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
cé	cé	cé-P	Pq
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
istigh	istigh	istigh-R	Rl
i	i	i-S	Sp
mála	mála	mála-N	Ncmsc
Áine	Áine	Áine-N	Npf-g
?	?	?-F	Fq
Sea	Sea	is-W	Wp-i-3
Léiní	Léiní	Léiní-N	Npmsc
!	!	!-F	Fe
Agus	Agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
éisteacht	éisteacht	éist-N	Nv
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
faire	faire	fair-N	Nv
!	!	!-F	Fe
Chuala	Chuala	clois-V	Vmis
sí	sí	sí-P	Pp3fsn
daoine	daoine	duine-N	Ncmpc
ag	ag	ag-S	Sp
rá	rá	abair-N	Nv
‘	‘	‘-X	Xx
bonjour	bonjour	bonjour-X	Xf
,	,	,-F	Fi
’	’	’-F	Fa
‘	‘	‘-X	Xx
au	au	au-N	Ncmsc
revoir	revoir	revoir-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
agus	agus	agus-C	Cc
‘	‘	‘-X	Xx
merci	merci	merci-N	Ncfsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Bonjour	Bonjour	Bonjour-N	Npmsc
,	,	,-F	Fi
au	au	au-N	Ncmsc
revoir	revoir	revoir-N	Ncfsc
,	,	,-F	Fi
merci	merci	merci-N	Ncfsc
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Léiní	Léiní	Léiní-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
Fraincis	Fraincis	Fraincis-N	Ncfsc
anois	anois	anois-R	Rt
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Bí	Bí	bí-N	Ncfsc
ciúin	ciúin	ciúin-A	Aqp
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Áine	Áine	Áine-N	Npfsc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
ag	ag	ag-S	Sp
Aintín	Aintín	aintín-N	Ncfsc
Nóra	Nóra	Nóra-N	Npf-g
tú	tú	tú-P	Pp2-s
a	a	a-U	U
bheith	bheith	bí-N	Nv
anseo	anseo	anseo-R	Rl
.	.	.-F	Fe
’	’	’-F	Fa
Níl	Níl	bí-V	Vmip---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
ag	ag	ag-S	Sp
Aintín	Aintín	aintín-N	Ncfsc
Nóra	Nóra	Nóra-N	Npf-g
tú	tú	tú-P	Pp2-s
a	a	a-U	U
bheith	bheith	bí-N	Nv
anseo	anseo	anseo-R	Rl
.	.	.-F	Fe
An	An	an-T	Td-s
oíche	oíche	oíche-N	Ncfsc
chéanna	chéanna	céanna-A	Aqp
chuir	chuir	cur-V	Vmis|Ncmsg
Áine	Áine	Áine-N	Npf-g|Npfsc
teachtaireacht	teachtaireacht	teachtaireacht-N	Ncfsc
ríomhphoist	ríomhphoist	ríomhphost-N	Ncmsg|Ncmpc|Ncmsg
chuig	chuig	chuig-S	Sp
a	a	a-D	Dp3
cara	cara	cara-N	Ncmsc
,	,	,-F	Fi
Eilís	Eilís	Eilís-N	Npfsc
.	.	.-F	Fe
Eilís	Eilís	Eilís-N	Npfsc
,	,	,-F	Fi
An	An	an-T	Td-s
Arc	Arc	arc-N	Ncmsc
de	de	de-S	Sp
Triomphe	Triomphe	Triomphe-N	Npmsc
A	A	a-T	Td-s|Dp3|U
Eilís	Eilís	Eilís-N	Npf-g|Npfsc
,	,	,-F	Fi
a	a	a-U	Uv
chara	chara	cara-N	Ncmsv
,	,	,-F	Fi
Bhí	Bhí	bí-V	Vmis
an-lá	an-lá	lá-N	Ncmsc
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
inniu	inniu	inniu-R	Rt
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
Arc	Arc	arc-N	Ncmsc
de	de	de-S	Sp
Triomphe	Triomphe	Triomphe-N	Npmsc
.	.	.-F	Fe
Seo	Seo	seo-W	W
pictiúr	pictiúr	pictiúr-N	Ncmsc
díom	díom	de-P	Pr1-s
a	a	a-Q	Q-r
thóg	thóg	tóg-V	Vmis
Aintín	Aintín	aintín-N	Ncfsc
Nóra	Nóra	Nóra-N	Npfsc
.	.	.-F	Fe
Le	Le	le-S	Sp
grá	grá	gráigh-N	Nv
,	,	,-F	Fi
Áine	Áine	Áine-N	Npfsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmm-2s
Áine	Áine	Áine-N	Npfsc
go	go	go-U	Ua
moch	moch	moch-A	Aqp
ar	ar	ar-S	Sp
maidin	maidin	maidin-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
mbeimid	mbeimid	bí-V	Vmif1p
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
inniu	inniu	inniu-R	Rt
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
le	le	le-S	Sp
hAintín	hAintín	aintín-N	Ncfsc
Nóra	Nóra	Nóra-N	Npf-g
.	.	.-F	Fe
‘	‘	‘-X	Xx
Go	Go	go-S	Sp
dtí	dtí	tí-N	Ncmsc|Ncfsc
Túr	Túr	túr-N	Ncmpg
Eiffel	Eiffel	Eiffel-N	Npm-g|Npmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Aintín	Aintín	aintín-N	Ncfsc
Nóra	Nóra	Nóra-N	Npf-g|Npfsc
.	.	.-F	Fe
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
Túr	Túr	túr-N	Ncmsc
Eiffel	Eiffel	Eiffel-N	Npm-g|Npmsc
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
Túr	Túr	túr-N	Ncmsc
Eiffel	Eiffel	Eiffel-N	Npm-g|Npmsc
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Léiní	Léiní	Léiní-N	Npmsc
agus	agus	agus-C	Cc
léim	léim	léim-V	Vmis
sí	sí	sí-P	Pp3fsn
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
mála	mála	mála-N	Ncmsc
Áine	Áine	Áine-N	Npf-g
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bí	Bí	bí-N	Ncfsc
ciúin	ciúin	ciúin-A	Aqp
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Áine	Áine	Áine-N	Npfsc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
ag	ag	ag-S	Sp
Aintín	Aintín	aintín-N	Ncfsc
Nóra	Nóra	Nóra-N	Npf-g
tú	tú	tú-P	Pp2-s
a	a	a-U	U
bheith	bheith	bí-N	Nv
anseo	anseo	anseo-R	Rl
.	.	.-F	Fe
’	’	’-F	Fa
Bhí	Bhí	bí-V	Vmis
an-lá	an-lá	lá-N	Ncmsc
ag	ag	ag-S	Sp
Áine	Áine	Áine-N	Npfsc
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
Aintín	Aintín	aintín-N	Ncfsc
Nóra	Nóra	Nóra-N	Npf-g
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
siad	siad	siad-P	Pp3-pn
an	an	an-T	Td-s
túr	túr	túr-N	Ncmsc
suas	suas	suas-R	Rd
agus	agus	agus-C	Cc
thóg	thóg	tóg-V	Vmis
siad	siad	siad-P	Pp3-pn
cúpla	cúpla	cúpla-D	Dq|Ncmsc
grianghraf	grianghraf	grianghraf-N	Ncmpg|Ncmsc
.	.	.-F	Fe
Ina	Ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|Dd
chuaigh	chuaigh	téigh-V	Vmis
siad	siad	siad-P	Pp3-pn
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
siopa	siopa	siopa-N	Ncmsc
agus	agus	agus-C	Cc
cheannaigh	cheannaigh	ceannach-V	Vmis|Ncmsg
Áine	Áine	Áine-N	Npf-g|Npfsc
bronntanais	bronntanais	bronntanas-N	Ncmsg|Ncmpc
dá	dá	de-S	Spp-s
cairde	cairde	cairde-N	Ncmpc|Ncmsc
.	.	.-F	Fe
Tamall	Tamall	tamall-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|Dd
thug	thug	tabhair-V	Vmis
Áine	Áine	Áine-N	Npfsc
faoi	faoi	faoi-S	Sp
deara	deara	deara-N	Ns-s
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
gíog	gíog	gíog-N	Ncfsc
ná	ná	nach-Q	Qnr
míog	míog	míog-V	Vmm-2s-n
as	as	as-S	Sp
Léiní	Léiní	Léiní-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
ansin	ansin	ansin-R	Rt|Rl
,	,	,-F	Fi
a	a	a-U	Uv
Léiní	Léiní	Léiní-N	Npmsc
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
Ach	Ach	ach-S	Sp
gíog	gíog	gíog-N	Ncfsc
ná	ná	ná-Q	Qnm
míog	míog	míog-V	Vmm-2s-n
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
as	as	as-S	Sp
Léiní	Léiní	Léiní-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
dul	dul	téigh-N	Ncmsc|Nv
suas	suas	suas-R	Rd
arís	arís	arís-R	Rg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Áine	Áine	Áine-N	Npfsc
lena	lena	le-S	Spp-s
haintín	haintín	aintín-N	Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
cá	cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
.	.	.-F	Fe
’	’	’-F	Fa
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
lig	lig	lig-V	Vmis
Aintín	Aintín	aintín-N	Ncfsc
Nóra	Nóra	Nóra-N	Npf-g|Npfsc
béic	béic	béic-N	Ncfsc
aisti	aisti	as-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Luch	Luch	luch-N	Ncfsc
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
Is	Is	is-W	Wp-i
ansin	ansin	ansin-R	Rt|Rl
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
Áine	Áine	Áine-N	Npfsc
Léiní	Léiní	Léiní-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
liomsa	liomsa	le-P	Pr1-s-e
í	í	í-P	Pp3fs
,	,	,-F	Fi
a	a	a-U	Uv
aintín	aintín	aintín-N	Ncfsv
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Léiní	Léiní	Léiní-N	Npmsc
an	an	an-T	Td-s
t-ainm	t-ainm	ainm-N	Ncmsc
atá	atá	bí-V	Vmip---r
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
leatsa	leatsa	le-P	Pr2-s-e
í	í	í-P	Pp3fs
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Aintín	Aintín	aintín-N	Ncfsc
Nóra	Nóra	Nóra-N	Npf-g|Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
tú	tú	tú-P	Pp2-s
leat	leat	le-P	Pr2-s
go	go	go-S	Sp
Páras	Páras	Páras-N	Npmsc
í	í	í-P	Pp3fs
!	!	!-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Sin	Sin	sin-W	W
scéal	scéal	scéal-N	Ncmsc
eile	eile	eile-D	Dd
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Áine	Áine	Áine-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Inseoidh	Inseoidh	inis-V	Vmif
mé	mé	mé-P	Pp1-s
anocht	anocht	anocht-N	Ns-s|Rt
duit	duit	do-P	Pr2-s
é	é	é-P	Pp3ms
.	.	.-F	Fe
’	’	’-F	Fa
Isteach	Isteach	isteach-R	Rd
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
mhála	mhála	mála-N	Ncmsc
leat	leat	le-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Léiní	Léiní	Léiní-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Isteach	Isteach	isteach-R	Rd
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
mhála	mhála	mála-N	Ncmsc
leat	leat	le-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Léiní	Léiní	Léiní-N	Npmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Áine	Áine	Áine-N	Npfsc
agus	agus	agus-C	Cc
siúd	siúd	siúd-P	Pd
leo	leo	le-P	Pr3-p
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
Métro	Métro	Métro-N	Npmsc
.	.	.-F	Fe
