 Cnaguirlisí	Cnaguirlisí	-X	Xx
atá	atá	bí-V	Vmip---r
ag	ag	ag-S	Sp
na	na	na-T	Td-p
ceoltóirí	ceoltóirí	ceoltóir-N	Ncmpc
seo	seo	seo-D	Dd
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
.	.	.-F	Fe
Buaileann	Buaileann	buail-V	Vmip
an	an	an-T	Td-s
ceoltóir	ceoltóir	ceoltóir-N	Ncmsc
an	an	an-T	Td-s
rithim	rithim	rithim-N	Ncfsc
fad	fad	fad-C	Cs
is	is	is-W	Wpri
a	a	a-Q	Q-r
mhaireann	mhaireann	mair-V	Vmip
an	an	an-T	Td-s
píosa	píosa	píosa-N	Ncmsc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
.	.	.-F	Fe
Is	Is	is-W	Wp-i
cnaguirlis	cnaguirlis	cnaguirlis-N	Ncfsc
é	é	é-P	Pp3ms
an	an	an-T	Td-s
bodhrán	bodhrán	bodhrán-N	Ncmsc
.	.	.-F	Fe
As	As	as-S	Sp
craiceann	craiceann	craiceann-N	Ncmsc
gabhair	gabhair	gabhar-N	Ncfsg|Ncmsg
a	a	a-Q	Q-r
dhéantar	dhéantar	déan-V	Vmip0
é	é	é-P	Pp3ms
.	.	.-F	Fe
Úsáidtear	Úsáidtear	úsáid-V	Vmip0
an	an	an-T	Td-s
bodhrán	bodhrán	bodhrán-N	Ncmsc
chun	chun	chun-S	Sp
an	an	an-T	Td-s
rithim	rithim	rithim-N	Ncfsc
a	a	a-U	U
bhualadh	bhualadh	buail-N	Nv
fad	fad	fad-C	Cs
is	is	is-W	Wpri
a	a	a-Q	Q-r
mhaireann	mhaireann	mair-V	Vmip
an	an	an-T	Td-s
píosa	píosa	píosa-N	Ncmsc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
.	.	.-F	Fe
Is	Is	is-W	Wp-i
cnaguirlisí	cnaguirlisí	cnaguirlis-N	Ncfpc
iad	iad	iad-P	Pp3-p
na	na	na-T	Td-p
cnámha	cnámha	cnámh-N	Ncfpc
.	.	.-F	Fe
As	As	as-S	Sp
eabhar	eabhar	eabhar-N	Ncmsc
a	a	a-Q	Q-r
dhéantar	dhéantar	déan-V	Vmip0
iad	iad	iad-P	Pp3-p
den	den	de-S	Spa-s
chuid	chuid	cuid-N	Ncfsc
is	is	is-U	U
mó	mó	mór-A	Aqc
.	.	.-F	Fe
Úsáidtear	Úsáidtear	úsáid-V	Vmip0
na	na	na-T	Td-p
cnámha	cnámha	cnámh-N	Ncfpc
chun	chun	chun-S	Sp
an	an	an-T	Td-s
rithim	rithim	rithim-N	Ncfsc
a	a	a-U	U
bhualadh	bhualadh	buail-N	Nv
fad	fad	fad-C	Cs
is	is	is-W	Wpri
a	a	a-Q	Q-r
mhaireann	mhaireann	mair-V	Vmip
an	an	an-T	Td-s
píosa	píosa	píosa-N	Ncmsc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
.	.	.-F	Fe
Is	Is	is-W	Wp-i
cnaguirlisí	cnaguirlisí	cnaguirlis-N	Ncfpc
iad	iad	iad-P	Pp3-p
na	na	na-T	Td-p
spúnóga	spúnóga	spúnóg-N	Ncfpc
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
.	.	.-F	Fe
Úsáidtear	Úsáidtear	úsáid-V	Vmip0
na	na	na-T	Td-p
spúnóga	spúnóga	spúnóg-N	Ncfpc
chun	chun	chun-S	Sp
an	an	an-T	Td-s
rithim	rithim	rithim-N	Ncfsc
a	a	a-U	U
bhualadh	bhualadh	buail-N	Nv
fad	fad	fad-C	Cs
is	is	is-W	Wpri
a	a	a-Q	Q-r
mhaireann	mhaireann	mair-V	Vmip
an	an	an-T	Td-s
píosa	píosa	píosa-N	Ncmsc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
.	.	.-F	Fe
Cé	Cé	cé-P	Pq
acu	acu	ag-P	Pr3-p
cnaguirlis	cnaguirlis	cnaguirlis-N	Ncfsc
is	is	is-W	Wpri
fearr	fearr	maith-A	Aqc
leatsa	leatsa	le-P	Pr2-s-e
?	?	?-F	Fq
Gaothuirlisí	Gaothuirlisí	Gaothuirlisí-N	Npmsc
atá	atá	bí-V	Vmip---r
ag	ag	ag-S	Sp
na	na	na-T	Td-p
ceoltóirí	ceoltóirí	ceoltóir-N	Ncmpc
seo	seo	seo-D	Dd
.	.	.-F	Fe
Séideann	Séideann	séid-V	Vmip
na	na	na-T	Td-p
ceoltóirí	ceoltóirí	ceoltóir-N	Ncmpc
isteach	isteach	isteach-R	Rd
sna	sna	i-S	Spa-p
gaothuirlisí	gaothuirlisí	uirlis-N	Ncfpc
chun	chun	chun-S	Sp
ceol	ceol	ceol-N	Nv-----n
a	a	a-U	U
bhaint	bhaint	bain-N	Nv
astu	astu	as-P	Pr3-p
.	.	.-F	Fe
Is	Is	is-W	Wp-i
gaothuirlis	gaothuirlis	uirlis-N	Ncfsc
í	í	í-P	Pp3fs
an	an	an-T	Td-s
fheadóg	fheadóg	feadóg-N	Ncfsc
stáin	stáin	stán-N	Ncmsg|Ncmpc|Ncmsg
.	.	.-F	Fe
Clúdaíonn	Clúdaíonn	clúdaigh-V	Vmip
an	an	an-T	Td-s
ceoltóir	ceoltóir	ceoltóir-N	Ncmsc
na	na	na-T	Td-p
poill	poill	poll-N	Ncmpc
agus	agus	agus-C	Cc
séideann	séideann	séid-V	Vmip
sí	sí	sí-P	Pp3fsn
isteach	isteach	isteach-R	Rd
san	san	i-S	Spa-s
fheadóg	fheadóg	feadóg-N	Ncfsc
chun	chun	chun-S	Sp
ceol	ceol	ceol-N	Nv-----n
a	a	a-U	U
bhaint	bhaint	bain-N	Nv
aisti	aisti	as-P	Pr3fs
.	.	.-F	Fe
Is	Is	is-W	Wp-i
gaothuirlis	gaothuirlis	uirlis-N	Ncfsc
í	í	í-P	Pp3fs
an	an	an-T	Td-s
fhliúit	fhliúit	fliúit-N	Ncfsc
.	.	.-F	Fe
Tugtar	Tugtar	tabhair-V	Vmip0
‘	‘	‘-X	Xx
fliúiteadóir	fliúiteadóir	fliúiteadóir-N	Ncmsc
’	’	’-F	Fa
ar	ar	ar-S	Sp
dhuine	dhuine	duine-N	Ncmsc
a	a	a-Q	Q-r
bhíonn	bhíonn	bí-V	Vmig
ag	ag	ag-S	Sp
seinm	seinm	seinn-N	Nv
na	na	na-T	Tdfsg
fliúite	fliúite	fliúit-N	Ncfsg
.	.	.-F	Fe
Cé	Cé	cé-P	Pq
acu	acu	ag-P	Pr3-p
gaothuirlis	gaothuirlis	uirlis-N	Ncfsc
is	is	is-W	Wpri
fearr	fearr	maith-A	Aqc
leatsa	leatsa	le-P	Pr2-s-e
?	?	?-F	Fq
Téaduirlisí	Téaduirlisí	Téaduirlisí-N	Npmsc
Téaduirlisí	Téaduirlisí	Téaduirlisí-N	Npmsc
atá	atá	bí-V	Vmip---r
ag	ag	ag-S	Sp
na	na	na-T	Td-p
ceoltóirí	ceoltóirí	ceoltóir-N	Ncmpc
seo	seo	seo-D	Dd
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
téaduirlis	téaduirlis	uirlis-N	Ncfsc
é	é	é-P	Pp3ms
an	an	an-T	Td-s
maindilín	maindilín	maindilín-N	Ncmsg|Ncmsc
.	.	.-F	Fe
Úsáidtear	Úsáidtear	úsáid-V	Vmip0
figín	figín	figín-N	Ncmsc
chun	chun	chun-S	Sp
ceol	ceol	ceol-N	Nv-----n
a	a	a-U	U
bhaint	bhaint	bain-N	Nv
as	as	as-S	Sp
téada	téada	téad-N	Ncfpc
an	an	an-T	Td-s
mhaindilín	mhaindilín	maindilín-N	Ncmsg
.	.	.-F	Fe
Scríobh	Scríobh	scríobh-N	Ncmsc|Vmis|Vmm-2s
na	na	na-T	Td-p
cumadóirí	cumadóirí	cumadóir-N	Ncmpc
Mozart	Mozart	Mozart-N	Npmsc
agus	agus	agus-C	Cc
Beethoven	Beethoven	Beethoven-N	Npmsc
ceol	ceol	ceol-N	Ncmsc|Nv-----n
don	don	do-S	Spa-s
mhaindilín	mhaindilín	maindilín-N	Ncmsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
téaduirlis	téaduirlis	uirlis-N	Ncfsc
é	é	é-P	Pp3ms
an	an	an-T	Td-s
giotár	giotár	giotár-N	Ncmsc
.	.	.-F	Fe
Seinntear	Seinntear	seinn-V	Vmip0
gach	gach	gach-D	Dq
sórt	sórt	sórt-N	Ncmsc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
ar	ar	ar-S	Sp
an	an	an-T	Td-s
ngiotár	ngiotár	giotár-N	Ncmsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
téaduirlis	téaduirlis	uirlis-N	Ncfsc
í	í	í-P	Pp3fs
an	an	an-T	Td-s
chláirseach	chláirseach	cláirseach-N	Ncfsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
cheann	cheann	ceann-N	Ncmsc
de	de	de-S	Sp
shiombail	shiombail	siombail-N	Ncfsc
náisiúnta	náisiúnta	náisiúnta-A	Aqp
na	na	na-T	Tdfsg
hÉireann	hÉireann	Éire-N	Npfsg
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
chláirseach	chláirseach	cláirseach-N	Ncfsc
is	is	is-U	U
sine	sine	sean-A	Aqc
in	in	i-S	Sp
Éirinn	Éirinn	Éire-N	Npfsd
le	le	le-S	Sp
feiceáil	feiceáil	feic-N	Nv
i	i	i-S	Sp
gColáiste	gColáiste	coláiste-N	Ncmsc
na	na	na-T	Tdfsg
Tríonóide	Tríonóide	Tríonóid-N	Ncfsg
.	.	.-F	Fe
Deirtear	Deirtear	abair-V	Vmip0
gur	gur	gur-Q	Q--s
le	le	le-S	Sp
Brian	Brian	Brian-N	Ncmsc|Npmsc
Bóramha	Bóramha	Bóramha-N	Npmsc
an	an	an-T	Td-s
chláirseach	chláirseach	cláirseach-N	Ncfsc
sin	sin	sin-D	Dd
.	.	.-F	Fe
Is	Is	is-W	Wp-i
téaduirlis	téaduirlis	uirlis-N	Ncfsc
í	í	í-P	Pp3fs
an	an	an-T	Td-s
fhidil	fhidil	fidil-N	Ncfsc
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
.	.	.-F	Fe
Úsáidtear	Úsáidtear	úsáid-V	Vmip0
bogha	bogha	bogha-N	Ncmsc
chun	chun	chun-S	Sp
ceol	ceol	ceol-N	Nv-----n
a	a	a-U	U
bhaint	bhaint	bain-N	Nv
as	as	as-S	Sp
téada	téada	téad-N	Ncfpc
na	na	na-T	Tdfsg
fidle	fidle	fidil-N	Ncfsg
.	.	.-F	Fe
Cé	Cé	cé-P	Pq
acu	acu	ag-P	Pr3-p
téaduirlis	téaduirlis	uirlis-N	Ncfsc
is	is	is-W	Wpri
fearr	fearr	maith-A	Aqc
leatsa	leatsa	le-P	Pr2-s-e
?	?	?-F	Fq
Feaguirlisí	Feaguirlisí	Feaguirlisí-N	Npmsc
Feaguirlisí	Feaguirlisí	Feaguirlisí-N	Npmsc
atá	atá	bí-V	Vmip---r
ag	ag	ag-S	Sp
na	na	na-T	Td-p
ceoltóirí	ceoltóirí	ceoltóir-N	Ncmpc
seo	seo	seo-D	Dd
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
feaguirlis	feaguirlis	uirlis-N	Ncfsc
í	í	í-P	Pp3fs
an	an	an-T	Td-s
phíb	phíb	píb-N	Ncfsc
uilleann	uilleann	uill-V	Vmip
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
cheann	cheann	ceann-N	Ncmsc
de	de	de-S	Sp
na	na	na-T	Td-p
huirlisí	huirlisí	uirlis-N	Ncfpc
is	is	is-U	U
sine	sine	sean-A	Aqc
dá	dá	do-S	Spp-p
bhfuil	bhfuil	fuil-N	Ncfsc
againn	againn	ag-P	Pr1-p
in	in	i-S	Sp
Éirinn	Éirinn	Éire-N	Npfsd
.	.	.-F	Fe
Is	Is	is-W	Wp-i
feaguirlis	feaguirlis	uirlis-N	Ncfsc
é	é	é-P	Pp3ms
an	an	an-T	Td-s
consairtín	consairtín	consairtín-N	Ncmsg|Ncmsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
ceol	ceol	ceol-N	Ncmsc
an	an	an-T	Td-s
chonsairtín	chonsairtín	consairtín-N	Ncmsg
go	go	go-U	Ua
láidir	láidir	láidir-A	Aqp
i	i	i-S	Sp
gContae	gContae	contae-N	Ncmsc
an	an	an-T	Td-s
Chláir	Chláir	Cláir-N	Npfsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
feaguirlis	feaguirlis	uirlis-N	Ncfsc
é	é	é-P	Pp3ms
an	an	an-T	Td-s
bosca	bosca	bosca-N	Ncmsg|Ncmsc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
.	.	.-F	Fe
Déanann	Déanann	déan-V	Vmip
an	an	an-T	Td-s
ceoltóir	ceoltóir	ceoltóir-N	Ncmsc
an	an	an-T	Td-s
bosca	bosca	bosca-N	Ncmsg|Ncmsc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
a	a	a-U	U
theannadh	theannadh	teann-N	Nv
agus	agus	agus-C	Cc
a	a	a-U	U
scaoileadh	scaoileadh	scaoil-N	Nv
agus	agus	agus-C	Cc
brúnn	brúnn	brúigh-V	Vmip
sé	sé	sé-P	Pp3msn
na	na	na-T	Td-p
cnaipí	cnaipí	cnaipe-N	Ncmpc
chun	chun	chun-S	Sp
ceol	ceol	ceol-N	Nv-----n
a	a	a-U	U
bhaint	bhaint	bain-N	Nv
as	as	as-P	Pr3ms
.	.	.-F	Fe
Cé	Cé	cé-P	Pq
acu	acu	ag-P	Pr3-p
feaguirlis	feaguirlis	uirlis-N	Ncfsc
is	is	is-W	Wpri
fearr	fearr	maith-A	Aqc
leatsa	leatsa	le-P	Pr2-s-e
?	?	?-F	Fq
Is	Is	is-W	Wp-i
uirlis	uirlis	uirlis-N	Ncfsc
é	é	é-P	Pp3ms
guth	guth	guth-N	Ncmsc
an	an	an-T	Td-s
duine	duine	duine-N	Ncmsg
.	.	.-F	Fe
Úsáidtear	Úsáidtear	úsáid-V	Vmip0
an	an	an-T	Td-s
guth	guth	guth-N	Ncmsc
chun	chun	chun-S	Sp
amhráin	amhráin	amhrán-N	Ncmsg
a	a	a-U	U
chanadh	chanadh	can-N	Nv
.	.	.-F	Fe
Cén	Cén	cé-W	W--q
sórt	sórt	sórt-N	Ncmsc
amhráin	amhráin	amhrán-N	Ncmsg
is	is	is-W	Wpri
fearr	fearr	maith-A	Aqc
leatsa	leatsa	le-P	Pr2-s-e
?	?	?-F	Fq
Is	Is	is-W	Wp-i
ócáid	ócáid	ócáid-N	Ncfsc
mór	mór	mór-A	Aqp
le	le	le-S	Sp
rá	rá	abair-N	Nv
í	í	í-P	Pp3fs
Fleadh	Fleadh	fleadh-N	Ncfsc
Cheoil	Cheoil	ceol-N	Nv--g--n|Ncmsg
na	na	na-T	Tdfsg
hÉireann	hÉireann	Éire-N	Npfsg
.	.	.-F	Fe
Uair	Uair	uair-N	Ncfsc
sa	sa	i-S	Spa-s
bhliain	bhliain	bliain-N	Ncfsc
a	a	a-Q	Q-r
bhíonn	bhíonn	bí-V	Vmig
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
siúl	siúl	siúil-N	Nv
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
comórtais	comórtais	comórtas-N	Ncmpc
cheoil	cheoil	ceol-N	Nv--g--n|Ncmsg
do	do	do-S	Sp
ghrúpaí	ghrúpaí	grúpa-N	Ncmpc
agus	agus	agus-C	Cc
do	do	do-S	Sp
dhaoine	dhaoine	duine-N	Ncmpc
aonair	aonair	aonar-N	Ncmsg
ar	ar	ar-S	Sp
siúl	siúl	siúil-N	Nv
le linn	le linn	le_linn-S	Spc
na	na	na-T	Tdfsg
fleá	fleá	fleá-N	Ncfsg
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
idir	idir	idir-S	Sp
óg	óg	óg-N	Ncmsc
agus	agus	agus-C	Cc
aosta	aosta	aosta-A	Aqp
ag	ag	ag-S	Sp
Fleadh	Fleadh	fleadh-N	Ncfsc
Cheoil	Cheoil	ceol-N	Nv--g--n|Ncmsg
na	na	na-T	Tdfsg
hÉireann	hÉireann	Éire-N	Npfsg
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
ceol	ceol	ceol-N	Ncmsc
agus	agus	agus-C	Cc
craic	craic	craic-N	Ncfsc
ar	ar	ar-S	Sp
na	na	na-T	Td-p
sráideanna	sráideanna	sráid-N	Ncfpc
le linn	le linn	le_linn-S	Spc
na	na	na-T	Tdfsg
fleá	fleá	fleá-N	Ncfsg
.	.	.-F	Fe
