Niamh	Niamh	Niamh-N	Npfsc
:	:	:-F	Fi
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
deirfiúr	deirfiúr	deirfiúr-N	Ncfsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
Nó	Nó	nó-C	Cc
deartháir	deartháir	deartháir-N	Ncmsc
,	,	,-F	Fi
b	b	b-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
.	.	.-F	Fe
Mamó	Mamó	mamó-N	Ncfsc
:	:	:-F	Fi
Ar	Ar	ar-S	Sp
mhaith	mhaith	maith-N	Ncfsc
anois	anois	anois-R	Rt
,	,	,-F	Fi
a	a	a-U	Uv
chroí	chroí	croí-N	Ncmsv
?	?	?-F	Fq
Niamh	Niamh	Niamh-N	Npfsc
:	:	:-F	Fi
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
.	.	.-F	Fe
An	An	an-Q	Qq
raibh	raibh	bí-V	Vmis---d
deirfiúracha	deirfiúracha	deirfiúr-N	Ncfpc
agus	agus	agus-C	Cc
deartháireacha	deartháireacha	deartháir-N	Ncmpg|Ncmpc
agatsa	agatsa	ag-P	Pr2-s-e
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
tú	tú	tú-P	Pp2-s
óg	óg	óg-A	Aqp
,	,	,-F	Fi
a	a	a-U	Uv
Mhamó	Mhamó	mamó-N	Ncfsv
?	?	?-F	Fq
Mamó	Mamó	mamó-N	Ncfsc
:	:	:-F	Fi
Bhí	Bhí	bí-V	Vmis
,	,	,-F	Fi
a	a	a-U	Uv
chroí	chroí	croí-N	Ncmsv
.	.	.-F	Fe
Mamó	Mamó	mamó-N	Ncfsc
:	:	:-F	Fi
Bhí	Bhí	bí-V	Vmis
ceathrar	ceathrar	ceathrar-N	Ncmsc
deartháir	deartháir	deartháir-N	Ncmsc
agus	agus	agus-C	Cc
triúr	triúr	triúr-N	Ncmpg|Ncmsc
deirfiúr	deirfiúr	deirfiúr-N	Ncfsc
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
Niamh	Niamh	Niamh-N	Npfsc
:	:	:-F	Fi
Bhí	Bhí	bí-V	Vmis
ochtar	ochtar	ochtar-N	Ncmsc
agaibh	agaibh	ag-P	Pr2-p
ann	ann	i-P	Pr3ms
!	!	!-F	Fe
Mamó	Mamó	mamó-N	Ncfsc
:	:	:-F	Fi
Bhí	Bhí	bí-V	Vmis
,	,	,-F	Fi
a	a	a-U	Uv
chroí	chroí	croí-N	Ncmsv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
ochtar	ochtar	ochtar-N	Ncmsc
againn	againn	ag-P	Pr1-p
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Niamh	Niamh	Niamh-N	Npfsc
:	:	:-F	Fi
Caithfidh	Caithfidh	caith-V	Vmif
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
teach	teach	teach-N	Ncmsc
an-mhór	an-mhór	mór-A	Aqp
agaibh	agaibh	ag-P	Pr2-p
,	,	,-F	Fi
más	más	má-C	Csw
ea	ea	ea-P	Pp3-s
.	.	.-F	Fe
Mamó	Mamó	mamó-N	Ncfsc
:	:	:-F	Fi
Muise	Muise	muise-X	Xsc
,	,	,-F	Fi
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
,	,	,-F	Fi
a	a	a-U	Uv
chroí	chroí	croí-N	Ncmsv
.	.	.-F	Fe
Mamó	Mamó	mamó-N	Ncfsc
:	:	:-F	Fi
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ach	ach	ach-S	Sp
dhá	dhá	dó-M	Mc
sheomra	sheomra	seomra-N	Ncmsc
codlata	codlata	codail-A	Av
sa	sa	i-S	Spa-s
teach	teach	teach-N	Ncmsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
fada	fada	fada-A	Aqp
liom	liom	le-P	Pr1-s
go	go	go-Q	Q
dtiocfaidh	dtiocfaidh	tar-V	Vmif
an	an	an-T	Td-s
Satharn	Satharn	Satharn-N	Ncmsc
.	.	.-F	Fe
Niamh	Niamh	Niamh-N	Npfsc
:	:	:-F	Fi
Dhá	Dhá	do-S	Spp
sheomra	sheomra	seomra-N	Ncmsc
codlata	codlata	codail-A	Av
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
ceithre	ceithre	ceathair-M	Mc
sheomra	sheomra	seomra-N	Ncmsc
codlata	codlata	codail-A	Av
sa	sa	i-S	Spa-s
teach	teach	teach-N	Ncmsc
seo	seo	seo-D	Dd
againne	againne	ag-P	Pr1-p-e
.	.	.-F	Fe
Niamh	Niamh	Niamh-N	Npfsc
:	:	:-F	Fi
Ó	Ó	Ó-I	I
,	,	,-F	Fi
tá	tá	bí-V	Vmip
mo	mo	mo-D	Dp1-s
gheansaí	gheansaí	geansaí-N	Ncmsc
salach	salach	salach-A	Aq-msc
,	,	,-F	Fi
a	a	a-U	Uv
Mhamó	Mhamó	mamó-N	Ncfsv
.	.	.-F	Fe
Mamó	Mamó	mamó-N	Ncfsc
:	:	:-F	Fi
Cuir	Cuir	cuir-V	Vmm-2s
san	san	i-S	Spa-s
inneall	inneall	inneall-N	Ncmsc
níocháin	níocháin	níochán-N	Ncmsg|Ncmpc
é	é	é-P	Pp3ms
,	,	,-F	Fi
a	a	a-U	Uv
chroí	chroí	croí-N	Ncmsv
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
ceann	ceann	ceann-N	Ncmsc
glan	glan	glan-A	Aq-msc
anseo	anseo	anseo-R	Rl
.	.	.-F	Fe
Niamh	Niamh	Niamh-N	Npfsc
:	:	:-F	Fi
An	An	an-Q	Qq
raibh	raibh	bí-V	Vmis---d
inneall	inneall	inneall-N	Ncmsc
níocháin	níocháin	níochán-N	Ncmsg|Ncmpc
agaibh	agaibh	ag-P	Pr2-p
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
tusa	tusa	tú-P	Pp2-s-e
óg	óg	óg-A	Aqp
,	,	,-F	Fi
a	a	a-U	Uv
Mhamó	Mhamó	mamó-N	Ncfsv
?	?	?-F	Fq
Mamó	Mamó	mamó-N	Ncfsc
:	:	:-F	Fi
Muise	Muise	muise-X	Xsc
,	,	,-F	Fi
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
,	,	,-F	Fi
a	a	a-U	Uv
chroí	chroí	croí-N	Ncmsv
.	.	.-F	Fe
Mamó	Mamó	mamó-N	Ncfsc
:	:	:-F	Fi
Ach	Ach	ach-C	Cs
is	is	is-W	Wpri
minic	minic	minic-A	Aqp
a	a	a-Q	Q-r
chabhraigh	chabhraigh	cabhraigh-V	Vmis
mé	mé	mé-P	Pp1-s
le	le	le-S	Sp
mo	mo	mo-D	Dp1-s
Mhamaí	Mhamaí	mama-N	Ncfsc|Ncmpc
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
ní	ní	nigh-N	Nv
na	na	na-T	Td-p
n-éadaí	n-éadaí	éadach-N	Ncmpg
.	.	.-F	Fe
Niamh	Niamh	Niamh-N	Npfsc
:	:	:-F	Fi
Agus	Agus	agus-C	Cc
an	an	an-Q	Qq
raibh	raibh	bí-V	Vmis---d
teilifís	teilifís	teilifís-N	Ncfsc
agaibh	agaibh	ag-P	Pr2-p
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
tú	tú	tú-P	Pp2-s
óg	óg	óg-A	Aqp
?	?	?-F	Fq
Mamó	Mamó	mamó-N	Ncfsc
:	:	:-F	Fi
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
,	,	,-F	Fi
a	a	a-U	Uv
chroí	chroí	croí-N	Ncmsv
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
pictiúrlann	pictiúrlann	pictiúrlann-N	Ncfsc
istigh	istigh	istigh-R	Rl
sa	sa	i-S	Spa-s
chathair	chathair	cathair-N	Ncfsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
minic	minic	minic-A	Aqp
a	a	a-Q	Q-r
chuaigh	chuaigh	téigh-V	Vmis
mé	mé	mé-P	Pp1-s
féin	féin	féin-P	Px
is	is	agus-C	Cc
mo	mo	mo-D	Dp1-s
chairde	chairde	cairde-N	Ncmpc|Ncmsc
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Is	Is	is-W	Wp-i
fada	fada	fada-A	Aqp
liom	liom	le-P	Pr1-s
go	go	go-Q	Q
dtiocfaidh	dtiocfaidh	tar-V	Vmif
an	an	an-T	Td-s
Satharn	Satharn	Satharn-N	Ncmsc
.	.	.-F	Fe
Niamh	Niamh	Niamh-N	Npfsc
:	:	:-F	Fi
An	An	an-Q	Qq
raibh	raibh	bí-V	Vmis---d
fón	fón	fón-N	Ncmsc
póca	póca	póca-N	Ncmsg|Ncmsc
agat	agat	ag-P	Pr2-s
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
tú	tú	tú-P	Pp2-s
óg	óg	óg-A	Aqp
?	?	?-F	Fq
Mamó	Mamó	mamó-N	Ncfsc
:	:	:-F	Fi
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
,	,	,-F	Fi
a	a	a-U	Uv
chroí	chroí	croí-N	Ncmsv
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
fón	fón	fón-N	Ncmsc
póca	póca	póca-N	Ncmsg|Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
ann	ann	i-P	Pr3ms
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
mise	mise	mé-P	Pp1-s-e
óg	óg	óg-A	Aqp
.	.	.-F	Fe
Mamó	Mamó	mamó-N	Ncfsc
:	:	:-F	Fi
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
fón	fón	fón-N	Ncmsc
tí	tí	teach-N	Ncmsg
againn	againn	ag-P	Pr1-p
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
oiread	oiread	oiread-N	Ns-s
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
ceann	ceann	ceann-N	Ncmsc
i	i	i-S	Sp
dteach	dteach	teach-N	Ncmsc
m	m	m-X	Xl
’	’	’-F	Fa
aintín	aintín	aintín-N	Ncfsc
Treasa	Treasa	Treasa-N	Npf-g|Npfsc
.	.	.-F	Fe
Niamh	Niamh	Niamh-N	Npfsc
:	:	:-F	Fi
An	An	an-Q	Qq
raibh	raibh	bí-V	Vmis---d
carr	carr	carr-N	Ncmsc|Ncfsc
agaibh	agaibh	ag-P	Pr2-p
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
tú	tú	tú-P	Pp2-s
óg	óg	óg-A	Aqp
,	,	,-F	Fi
a	a	a-U	Uv
Mhamó	Mhamó	mamó-N	Ncfsv
?	?	?-F	Fq
Mamó	Mamó	mamó-N	Ncfsc
:	:	:-F	Fi
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
,	,	,-F	Fi
a	a	a-U	Uv
chroí	chroí	croí-N	Ncmsv
.	.	.-F	Fe
Mamó	Mamó	mamó-N	Ncfsc
:	:	:-F	Fi
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
mórán	mórán	mórán-N	Ncmsc
carranna	carranna	carr-N	Ncmpg
ann	ann	i-P	Pr3ms
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
mise	mise	mé-P	Pp1-s-e
óg	óg	óg-A	Aqp
.	.	.-F	Fe
Niamh	Niamh	Niamh-N	Npfsc
:	:	:-F	Fi
A	A	an-T	Td-s
Mhamó	Mhamó	mamó-N	Ncfsc
,	,	,-F	Fi
an	an	an-Q	Qq
raibh	raibh	bí-V	Vmis---d
siopaí	siopaí	siopa-N	Ncmpc
ann	ann	i-P	Pr3ms
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
tusa	tusa	tú-P	Pp2-s-e
óg	óg	óg-A	Aqp
?	?	?-F	Fq
Mamó	Mamó	mamó-N	Ncfsc
:	:	:-F	Fi
Bhí	Bhí	bí-V	Vmis
,	,	,-F	Fi
a	a	a-U	Uv
chroí	chroí	croí-N	Ncmsv
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
siad	siad	siad-P	Pp3-pn
ar nós	ar nós	ar_nós-S	Spc
na	na	na-T	Td-p
siopaí	siopaí	siopa-N	Ncmpg
atá	atá	bí-V	Vmip---r
ann	ann	i-P	Pr3ms
anois	anois	anois-R	Rt
.	.	.-F	Fe
Niamh	Niamh	Niamh-N	Npfsc
:	:	:-F	Fi
An	An	an-Q	Qq
raibh	raibh	bí-V	Vmis---d
éadaí	éadaí	éadach-N	Ncmpc
deasa	deasa	deas-A	Aq--pc
agat	agat	ag-P	Pr2-s
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
tú	tú	tú-P	Pp2-s
óg	óg	óg-A	Aqp
,	,	,-F	Fi
a	a	a-U	Uv
Mhamó	Mhamó	mamó-N	Ncfsv
?	?	?-F	Fq
Mamó	Mamó	mamó-N	Ncfsc
:	:	:-F	Fi
Bhí	Bhí	bí-V	Vmis
,	,	,-F	Fi
a	a	a-U	Uv
chroí	chroí	croí-N	Ncmsv
.	.	.-F	Fe
Mamó	Mamó	mamó-N	Ncfsc
:	:	:-F	Fi
Is	Is	is-W	Wpri
minic	minic	minic-A	Aqp
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
beart	beart	beart-N	Ncmsc
chugainn	chugainn	chuig-P	Pr1-p
ó	ó	ó-C	Cs
m	m	m-X	Xl
’	’	’-F	Fa
aintín	aintín	aintín-N	Ncfsc
i	i	i-S	Sp
Meiriceá	Meiriceá	Meiriceá-N	Npfsc
agus	agus	agus-C	Cc
gúnaí	gúnaí	gúna-N	Ncmpc
deasa	deasa	deas-A	Aq--pc
ann	ann	i-R	Rl|Pr3ms
dom	dom	do-P	Pr1-s
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
do	do	do-D	Dp2-s|Sp
mo	mo	mo-D	Dp1-s
dheirfiúracha	dheirfiúracha	deirfiúr-N	Ncfpc
.	.	.-F	Fe
Niamh	Niamh	Niamh-N	Npfsc
:	:	:-F	Fi
Is	Is	is-W	Wpri
maith	maith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
an	an	an-T	Td-s
scoil	scoil	scoil-N	Ncfsc
,	,	,-F	Fi
a	a	a-U	Uv
Mhamó	Mhamó	mamó-N	Ncfsv
.	.	.-F	Fe
Ar	Ar	ar-Q	Qq-s
thaitin	thaitin	taitin-V	Vmis
an	an	an-T	Td-s
scoil	scoil	scoil-N	Ncfsc
leatsa	leatsa	le-P	Pr2-s-e
?	?	?-F	Fq
Mamó	Mamó	mamó-N	Ncfsc
:	:	:-F	Fi
Muise	Muise	muise-X	Xsc
,	,	,-F	Fi
níor	níor	níor-Q	Qn-s
thaitin	thaitin	taitin-V	Vmis---n
,	,	,-F	Fi
a	a	a-U	Uv
chroí	chroí	croí-N	Ncmsv
.	.	.-F	Fe
Mamó	Mamó	mamó-N	Ncfsc
:	:	:-F	Fi
Bhí	Bhí	bí-V	Vmis
na	na	na-T	Td-p
múinteoirí	múinteoirí	múinteoir-N	Ncmpc
an-chrosta	an-chrosta	crosta-A	Aqp
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
mise	mise	mé-P	Pp1-s-e
óg	óg	óg-A	Aqp
.	.	.-F	Fe
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
Páras	Páras	Páras-N	Npmsc
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
.	.	.-F	Fe
Niamh	Niamh	Niamh-N	Npfsc
:	:	:-F	Fi
Níl	Níl	bí-V	Vmip---n
mo	mo	mo-D	Dp1-s
mhúinteoirse	mhúinteoirse	múinteoir-N	Ncmsc-e
crosta	crosta	cros-A	Aqp|Av
,	,	,-F	Fi
a	a	a-U	Uv
Mhamó	Mhamó	mamó-N	Ncfsv
.	.	.-F	Fe
Mamó	Mamó	mamó-N	Ncfsc
:	:	:-F	Fi
Téigh	Téigh	téigh-V	Vmm-2s
isteach	isteach	isteach-R	Rd
chuici	chuici	chuig-P	Pr3fs
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
a	a	a-U	Uv
chroí	chroí	croí-N	Ncmsv
.	.	.-F	Fe
Slán	Slán	slán-N	Ncmsc
anois	anois	anois-R	Rt
agus	agus	agus-C	Cc
bí	bí	bí-V	Vmm-2s
go	go	go-U	Ua
maith	maith	maith-A	Aqp
.	.	.-F	Fe
Niamh	Niamh	Niamh-N	Npfsc
:	:	:-F	Fi
Ach	Ach	ach-C	Cs
fan	fan	fan-V	Vmm-2s
nóiméad	nóiméad	nóiméad-N	Ncmsc
,	,	,-F	Fi
a	a	a-U	Uv
Mhamó	Mhamó	mamó-N	Ncfsv
.	.	.-F	Fe
Ceist	Ceist	ceist-N	Ncfsc
amháin	amháin	amháin-A	Aqp
eile	eile	eile-D	Dd
agam	agam	ag-P	Pr1-s
ort	ort	ar-P	Pr2-s
.	.	.-F	Fe
An	An	an-Q	Qq
raibh	raibh	bí-V	Vmis---d
tú	tú	tú-P	Pp2-s
sona	sona	sona-A	Aqp
sásta	sásta	sásta-A	Aqp
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
tú	tú	tú-P	Pp2-s
óg	óg	óg-A	Aqp
?	?	?-F	Fq
Mamó	Mamó	mamó-N	Ncfsc
:	:	:-F	Fi
Bhí	Bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
tá	tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
níos	níos	níos-U	Uc
sásta	sásta	sásta-A	Aqc
fós	fós	fós-R	Rg
anois	anois	anois-R	Rt
mar	mar	mar-C	Cs
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
tusa	tusa	tú-P	Pp2-s-e
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
a	a	a-U	Uv
chroí	chroí	croí-N	Ncmsv
!	!	!-F	Fe
