Bhí	Bhí	bí-V	Vmis
Réalt	Réalt	alt-N	Ncmsc
na	na	na-T	Td-p
Mara	Mara	Mara-N	Npmsg
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
ar	ar	ar-S	Sp
Oileán	Oileán	oileán-N	Ncmsc
na	na	na-T	Td-p
Rón	Rón	rón-N	Ncmsc
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
thóir	thóir	tóir-N	Ncfsc
óir	óir	óir-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
criú	criú	criú-N	Ncmsc
an	an	an-T	Td-s
bháid	bháid	bád-N	Ncmsg
,	,	,-F	Fi
ór	ór	ór-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
i	i	i-S	Sp
bhfolach	bhfolach	folach-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
oileán	oileán	oileán-N	Ncmsc
,	,	,-F	Fi
má	má	má-N	Ncfsc|Cs
b	b	b-X	Xl
’	’	’-F	Fa
do	do	do-S	Sp
na	na	na-T	Td-p
scéalta	scéalta	scéal-N	Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
puth	puth	puth-N	Ncfsc
gaoithe	gaoithe	gaoth-A	Aq-fsg
ann	ann	i-P	Pr3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Leathchois	Leathchois	Leathchois-N	Npmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
gCaptaen	gCaptaen	captaen-N	Ncmsc
tar éis	tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
súil	súil	súil-N	Ncfsc
agam	agam	ag-P	Pr1-s
go	go	go-Q	Q
n-éireoidh	n-éireoidh	éirigh-V	Vmif
linn	linn	le-P	Pr1-p
dul	dul	téigh-N	Nv
i	i	i-S	Sp
dtír	dtír	tír-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
oileán	oileán	oileán-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
an	an	an-T	Td-s
Captaen	Captaen	captaen-N	Ncmsc
Ó	Ó	Ó-U	Up
Súilleabháin	Súilleabháin	Súilleabháin-N	Npmsc
é	é	é-P	Pp3ms
sin	sin	sin-P	Pd
léim	léim	léim-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
súil	súil	súil-N	Ncfsc
agat	agat	ag-P	Pr2-s
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
de	de	de-S	Sp
bhéic	bhéic	béic-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nach	Nach	is-W	Wpsin|Wpdin
tú	tú	tú-P	Pp2-s
an	an	an-T	Td-s
t-amadán	t-amadán	amadán-N	Ncmsc
!	!	!-F	Fe
Nár	Nár	nár-Q	Qnrs
éist	éist	éist-V	Vmis---n
tú	tú	tú-P	Pp2-s
leis	leis	le-S	Sp
an	an	an-T	Td-s
réamhaisnéis	réamhaisnéis	réamhaisnéis-N	Ncfsc
ar	ar	ar-S	Sp
maidin	maidin	maidin-N	Ncfsc
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Bhí	Bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
éisteacht	éisteacht	éist-N	Nv
leis	leis	le-P	Pr3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Leathchois	Leathchois	Leathchois-N	Npmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
tusa	tusa	tú-P	Pp2-s-e
isteach	isteach	isteach-R	Rd
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
iarr	iarr	iarr-V	Vmm-2s
tú	tú	tú-P	Pp2-s
orm	orm	ar-P	Pr1-s
…	…	…-F	Fi
’	’	’-F	Fa
‘	‘	‘-X	Xx
Leithscéalta	Leithscéalta	leithscéal-N	Ncmpc
!	!	!-F	Fe
Leithscéalta	Leithscéalta	leithscéal-N	Ncmpc
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Captaen	Captaen	captaen-N	Ncmsc
go	go	go-U	Ua
feargach	feargach	feargach-A	Aqp
agus	agus	agus-C	Cc
amach	amach	amach-R	Rd
as	as	as-S	Sp
an	an	an-T	Td-s
gcábán	gcábán	cábán-N	Ncmsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Leathchois	Leathchois	Leathchois-N	Npmsc
bocht	bocht	bocht-A	Aq-msc
trína	trína	trí-S	Spp-s
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
fearg	fearg	fearg-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gCaptaen	gCaptaen	captaen-N	Ncmsc
leis	leis	le-P	Pr3ms
arís	arís	arís-R	Rg
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
mar	mar	mar-C	Cs
bharr	bharr	barr-V	Vmis
ar	ar	ar-S	Sp
an	an	an-T	Td-s
donas	donas	donas-N	Ncmsc
bhí	bhí	bí-V	Vmis
tinneas	tinneas	tinneas-N	Ncmsc
farraige	farraige	farraige-N	Ncfsg|Ncfsc
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
anois	anois	anois-R	Rt
air	air	ar-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tinneas	tinneas	tinneas-N	Ncmsc
farraige	farraige	farraige-N	Ncfsg|Ncfsc
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
orm	orm	ar-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Leathchois	Leathchois	Leathchois-N	Npmsc
agus	agus	agus-C	Cc
an-trua	an-trua	trua-A	Aqp
aige	aige	ag-P	Pr3ms
dó	dó	do-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
maith	maith	maith-A	Aqp
liom	liom	le-P	Pr1-s
a	a	a-U	U
bheith	bheith	bí-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhfarraige	bhfarraige	farraige-N	Ncfsc
.	.	.-F	Fe
Ná	Ná	ná-C	Cs
ní	ní	is-W	Wp-in
maith	maith	maith-A	Aqp
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
Captaen	Captaen	captaen-N	Ncmsc
Ó	Ó	Ó-U	Up
Súilleabháin	Súilleabháin	Súilleabháin-N	Npmsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
féin	féin	féin-P	Px
,	,	,-F	Fi
más	más	má-N	Ncmsc|Csw
fíor	fíor	fíor-N	Ncfsc|Aq-msc|Aqp
na	na	na-T	Td-p
scéalta	scéalta	scéal-N	Ncmpg|Ncmpc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Leathchois	Leathchois	Leathchois-N	Npmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
tá	tá	bí-V	Vmip
ór	ór	ór-N	Ncmsc
Spáinneach	Spáinneach	Spáinneach-A	Aq-msc
i	i	i-S	Sp
bhfolach	bhfolach	folach-N	Ncmsc
ar	ar	ar-S	Sp
Oileán	Oileán	oileán-N	Ncmsc
na	na	na-T	Td-p
Rón	Rón	rón-N	Ncmsc
.	.	.-F	Fe
Sula	Sula	sula-C	Cs
n-éireoidh	n-éireoidh	éirigh-V	Vmif
ghrian	ghrian	grian-V	Vmis
ar	ar	ar-S	Sp
maidin	maidin	maidin-N	Ncfsc
beidh	beidh	bí-V	Vmif
mise	mise	mé-P	Pp1-s-e
i	i	i-S	Sp
m	m	m-X	Xl
’	’	’-F	Fa
saibhir	saibhir	saibhir-N	Ncmsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
fágfaidh	fágfaidh	fág-V	Vmif
mé	mé	mé-P	Pp1-s
slán	slán	slán-A	Aqp|Ncmsc
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
ag	ag	ag-S	Sp
an	an	an-T	Td-s
gCaptaen	gCaptaen	captaen-N	Ncmsc
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
bhfarraige	bhfarraige	farraige-N	Ncfsc
.	.	.-F	Fe
’	’	’-F	Fa
Níorbh	Níorbh	is-W	Ws-in
fhada	fhada	fada-A	Aqc|Aqp
go	go	go-Q	Q
bhfaca	bhfaca	feic-V	Vmis---d
Leathchois	Leathchois	Leathchois-N	Npmsc
Oileán	Oileán	oileán-N	Ncmsc
na	na	na-T	Td-p
Rón	Rón	rón-N	Ncmsc
faoi	faoi	faoi-S	Sp
sholas	sholas	solas-N	Ncmsc
na	na	na-T	Tdfsg
gealaí	gealaí	gealach-N	Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	a-D	Dp3
Chaptaein	Chaptaein	captaen-N	Ncmpc
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
de	de	de-S	Sp
bhéic	bhéic	béic-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
t-oileán	t-oileán	oileán-N	Ncmsc
le	le	le-S	Sp
feiceáil	feiceáil	feic-N	Nv
anois	anois	anois-R	Rt
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
níl	níl	bí-V	Vmip---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
cá	cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
an	an	an-T	Td-s
ché	ché	cé-N	Ncfsc
.	.	.-F	Fe
’	’	’-F	Fa
Amach	Amach	amach-R	Rd
leis	leis	le-S	Sp
an	an	an-T	Td-s
gCaptaen	gCaptaen	captaen-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Dúirt	Dúirt	abair-V	Vmis
mé	mé	mé-P	Pp1-s
leat	leat	le-P	Pr2-s
cheana	cheana	cheana-R	Rg
féin	féin	féin-P	Px
gur	gur	is-W	Wsdi|Wpdi
ar	ar	ar-S	Sp
an	an	an-T	Td-s
taobh	taobh	taobh-N	Ncmsc
ó	ó	ó-S	Sp
dheas	dheas	deas-N	Ns-s
atá	atá	bí-V	Vmip---r
an	an	an-T	Td-s
ché	ché	cé-N	Ncfsc
.	.	.-F	Fe
Nach	Nach	is-W	Wpsin
tú	tú	tú-P	Pp2-s
an	an	an-T	Td-s
t-amadán	t-amadán	amadán-N	Ncmsc
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
go	go	go-U	Ua
mífhoighneach	mífhoighneach	mífhoighneach-A	Aqp
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
siad	siad	siad-P	Pp3-pn
chomh	chomh	chomh-R	Ri
fada	fada	fada-A	Aqp
leis	leis	le-S	Sp
an	an	an-T	Td-s
gcé	gcé	cé-N	Ncfsc
bheag	bheag	beag-A	Aq-fsc
cheangail	cheangail	ceangail-V	Vmis
siad	siad	siad-P	Pp3-pn
suas	suas	suas-R	Rd
an	an	an-T	Td-s
bád	bád	bád-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
bád	bád	bád-N	Ncmsc
eile	eile	eile-D	Dd
ann	ann	i-R	Rl|Pr3ms
rompu	rompu	roimh-P	Pr3-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
duine	duine	duine-N	Ncmsc
ná	ná	ná-C	Cs|Cc
deoraí	deoraí	deora-N	Ncmsc|Ncmsg|Ncfpg|Ncfpc
anseo	anseo	anseo-R	Rl
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Leathchois	Leathchois	Leathchois-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
aon	aon	aon-D	Dq
deacracht	deacracht	deacracht-N	Ncfsc
againn	againn	ag-P	Pr1-p
teacht	teacht	teacht-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
ór	ór	ór-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Fuist	Fuist	fuist-N	Ncmsc
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Captaen	Captaen	captaen-N	Ncmsc
Ó	Ó	Ó-U	Up
Súilleabháin	Súilleabháin	Súilleabháin-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
D	D	D-X	Xl
’	’	’-F	Fa
fhéadfadh	fhéadfadh	féad-V	Vmc
daoine	daoine	duine-N	Ncmpc
a	a	a-U	U
bheith	bheith	bí-N	Nv
istigh	istigh	istigh-R	Rl
sa	sa	i-S	Spa-s
bhád	bhád	bád-N	Ncmsc
sin	sin	sin-D	Dd
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Anois	Anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Captaen	Captaen	captaen-N	Ncmsc
Ó	Ó	Ó-U	Up
Súilleabháin	Súilleabháin	Súilleabháin-N	Npmsc
le	le	le-S	Sp
Leathchois	Leathchois	Leathchois-N	Npmsc
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
leo	leo	le-P	Pr3-p
,	,	,-F	Fi
‘	‘	‘-X	Xx
tabhair	tabhair	tabhair-V	Vmm-2s
dom	dom	do-P	Pr1-s
an	an	an-T	Td-s
mapa	mapa	mapa-N	Ncmsc
sin	sin	sin-D	Dd
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
...	...	...-F	Fe
an	an	is-W	Wp-q
…	…	…-F	Fi
mapa	mapa	mapa-N	Ncmsc
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Leathchois	Leathchois	Leathchois-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cheap	Cheap	ceap-V	Vmis
mé	mé	mé-P	Pp1-s
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
agatsa	agatsa	ag-P	Pr2-s-e
.	.	.-F	Fe
’	’	’-F	Fa
Lig	Lig	lig-V	Vmis|Vmm-2s
an	an	an-T	Td-s
Captaen	Captaen	captaen-N	Ncmsc
Ó	Ó	Ó-U	Up
Súilleabháin	Súilleabháin	Súilleabháin-N	Npmsc
béic	béic	béic-N	Ncfsc
as	as	as-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cheap	Cheap	ceap-V	Vmis
tú	tú	tú-P	Pp2-s
!	!	!-F	Fe
Cheap	Cheap	ceap-V	Vmis
tú	tú	tú-P	Pp2-s
!	!	!-F	Fe
Nach	Nach	is-W	Wpsin
tú	tú	tú-P	Pp2-s
an	an	an-T	Td-s
t-amadán	t-amadán	amadán-N	Ncmsc
!	!	!-F	Fe
’	’	’-F	Fa
Bhí	Bhí	bí-V	Vmis
Leathchois	Leathchois	Leathchois-N	Npmsc
bocht	bocht	bocht-A	Aq-msc
trína	trína	trí-S	Spp-s
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
fearg	fearg	fearg-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gCaptaen	gCaptaen	captaen-N	Ncmsc
leis	leis	le-P	Pr3ms
arís	arís	arís-R	Rg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
agus	agus	agus-C	Cc
an-fhearg	an-fhearg	fearg-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Rachaidh	Rachaidh	téigh-V	Vmif
mé	mé	mé-P	Pp1-s
ar ais	ar ais	ar_ais-R	Rd
chun	chun	chun-S	Sp
an	an	an-T	Td-s
mapa	mapa	mapa-N	Ncmsc
a	a	a-U	U
fháil	fháil	faigh-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
mé	mé	mé-P	Pp1-s
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
Captaen	Captaen	captaen-N	Ncmsc
Ó	Ó	Ó-U	Up
Súilleabháin	Súilleabháin	Súilleabháin-N	Npmsc
ag	ag	ag-S	Sp
fanacht	fanacht	fan-N	Nv
go	go	go-U	Ua
mífhoighneach	mífhoighneach	mífhoighneach-A	Aqp
le	le	le-S	Sp
Leathchois	Leathchois	Leathchois-N	Npmsc
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
bhuail	bhuail	buail-V	Vmis
imní	imní	imní-N	Ncfsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
Leathchois	Leathchois	Leathchois-N	Npmsc
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
sé	sé	sé-P	Pp3msn
tite	tite	tit-A	Av
i	i	i-S	Sp
bhfarraige	bhfarraige	farraige-N	Ncfsc
?	?	?-F	Fq
B	B	B-X	Xl
’	’	’-F	Fa
fhearr	fhearr	maith-A	Aqc
dom	dom	do-P	Pr1-s
dul	dul	dul-N	Ncmsc
ar ais	ar ais	ar_ais-R	Rd
chuig	chuig	chuig-S	Sp
an	an	an-T	Td-s
mbád	mbád	bád-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
Isteach	Isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
bhád	bhád	bád-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
gCaptaen	gCaptaen	captaen-N	Ncmsc
Ó	Ó	Ó-U	Up
Súilleabháin	Súilleabháin	Súilleabháin-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	an-T	Td-s
Leathchois	Leathchois	Leathchois-N	Npmsc
!	!	!-F	Fe
A	A	a-U	Uv
Leathchois	Leathchois	Leathchois-N	Npmsc
!	!	!-F	Fe
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
an	an	an-T	Td-s
Captaen	Captaen	captaen-N	Ncmsc
Leathchois	Leathchois	Leathchois-N	Npmsc
bocht	bocht	bocht-A	Aq-msc
sínte	sínte	sín-A	Av
ar	ar	ar-S	Sp
an	an	an-T	Td-s
urlár	urlár	urlár-N	Ncmsc
gan	gan	gan-S	Sp
aithne	aithne	aithne-N	Ncfsc
gan	gan	gan-S	Sp
urlabhra	urlabhra	urlabhra-N	Ncfsc
ba	ba	is-W	Wsri
bheag	bheag	beag-A	Aqp
nár	nár	nár-Q	Qnrs
thit	thit	tit-V	Vmis---n
an	an	an-T	Td-s
t-anam	t-anam	anam-N	Ncmsc
as	as	as-P	Pr3ms
!	!	!-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmm-2s
Leathchois	Leathchois	Leathchois-N	Npmsc
a	a	a-U	U
shúile	shúile	súil-N	Nv--g--n
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	an-T	Td-s
Leathchois	Leathchois	Leathchois-N	Npmsc
!	!	!-F	Fe
A	A	a-U	Uv
Leathchois	Leathchois	Leathchois-N	Npmsc
!	!	!-F	Fe
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
ceart	ceart	ceart-A	Aqp
go leor	go leor	go_leor-A	Aq
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Captaen	Captaen	captaen-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
D	D	D-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmm-2s
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
ceann	ceann	ceann-N	Ncmsc
is	is	is-U	U
fearr	fearr	maith-A	Aqc
a	a	a-U	U
fháil	fháil	faigh-N	Nv
air	air	ar-P	Pr3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Leathchois	Leathchois	Leathchois-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cé	Cé	cé-P	Pq
air	air	ar-P	Pr3ms
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Captaen	Captaen	captaen-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
duine	duine	duine-N	Ncmsc
ná	ná	ná-C	Cc
deoraí	deoraí	deora-N	Ncmsc|Ncmsg|Ncfpg|Ncfpc
anseo	anseo	anseo-R	Rl
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
mapa	mapa	mapa-N	Ncmsc
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
lámh	lámh	lámh-N	Ncfsc
agam	agam	ag-P	Pr1-s
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
mé	mé	mé-P	Pp1-s
duine	duine	duine-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
taobh	taobh	taobh-N	Ncmsc
thiar	thiar	thiar-R	Rd
díom	díom	de-P	Pr1-s
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
iompaigh	iompaigh	iompaigh-V	Vmm-2s
mé	mé	mé-P	Pp1-s
timpeall	timpeall	timpeall-R	Rd|Ncmsc
rug	rug	beir-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mapa	mapa	mapa-N	Ncmsc
agus	agus	agus-C	Cc
…	…	…-F	Fi
’	’	’-F	Fa
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
imithe	imithe	imigh-A	Av
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Captaen	Captaen	captaen-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Imithe	Imithe	imigh-A	Av
leis	leis	le-S	Sp
an	an	an-T	Td-s
mapa	mapa	mapa-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
,	,	,-F	Fi
muise	muise	muise-X	Xsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Leathchois	Leathchois	Leathchois-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
istigh	istigh	istigh-R	Rl
sa	sa	i-S	Spa-s
chábán	chábán	cábán-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
Istigh	Istigh	istigh-R	Rl
sa	sa	i-S	Spa-s
chábán	chábán	cábán-N	Ncmsc
chonaic	chonaic	feic-V	Vmis
an	an	an-T	Td-s
Captaen	Captaen	captaen-N	Ncmsc
fear	fear	fear-N	Ncmsc|Ncmpg
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
a	a	a-D	Dp3
lámha	lámha	lámh-N	Ncfpc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
chosa	chosa	cos-N	Ncfpc
ceangailte	ceangailte	ceangail-A	Av
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
maraigh	maraigh	maraigh-V	Vmm-2s-n
mé	mé	mé-P	Pp1-s
!	!	!-F	Fe
Ná	Ná	ná-Q	Qnm
maraigh	maraigh	maraigh-V	Vmm-2s-n
mé	mé	mé-P	Pp1-s
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
uaim	uaim	ó-P	Pr1-s
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
mapa	mapa	mapa-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
cheap	cheap	ceap-V	Vmis
mé	mé	mé-P	Pp1-s
gur	gur	gur-Q	Q--s
éalaigh	éalaigh	éalaigh-V	Vmis
sé	sé	sé-P	Pp3msn
leis	leis	le-S	Sp
an	an	an-T	Td-s
mapa	mapa	mapa-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Captaen	Captaen	captaen-N	Ncmsc
Ó	Ó	Ó-U	Up
Súilleabháin	Súilleabháin	Súilleabháin-N	Npmsc
le	le	le-S	Sp
Leathchois	Leathchois	Leathchois-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Chuir	Chuir	cuir-V	Vmis
mé	mé	mé-P	Pp1-s
cor	cor	cor-N	Ncmsc
coise	coise	cos-N	Ncfsg
ann	ann	i-P	Pr3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Leathchois	Leathchois	Leathchois-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ansin	Ansin	ansin-R	Rt|Rl
cheangail	cheangail	ceangail-V	Vmis
mé	mé	mé-P	Pp1-s
é	é	é-P	Pp3ms
leis	leis	le-S	Sp
na	na	na-T	Td-p
rópaí	rópaí	rópa-N	Ncmpc
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
mé	mé	mé-P	Pp1-s
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
chábán	chábán	cábán-N	Ncmsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
amach	amach	amach-R	Rd
sciorr	sciorr	sciorr-V	Vmis
mé	mé	mé-P	Pp1-s
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
cuimhin	cuimhin	cuimhin-N	Ns-s
liom	liom	le-P	Pr1-s
aon	aon	aon-D	Dq
rud	rud	rud-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|W|Dd
go dtí	go dtí	go_dtí-S	Spc
gur	gur	gur-Q	Q--s
tháinig	tháinig	tar-V	Vmis
tusa	tusa	tú-P	Pp2-s-e
isteach	isteach	isteach-R	Rd
.	.	.-F	Fe
Caithfidh	Caithfidh	caith-V	Vmif
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
mé	mé	mé-P	Pp1-s
tamall	tamall	tamall-N	Ncmsc
gan	gan	gan-S	Sp
aithne	aithne	aithne-N	Ncfsc
gan	gan	gan-S	Sp
urlabhra	urlabhra	urlabhra-N	Ncfsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
an	an	an-T	Td-s
mapa	mapa	mapa-N	Ncmsc
?	?	?-F	Fq
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
an	an	an-T	Td-s
mapa	mapa	mapa-N	Ncmsc
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Captaen	Captaen	captaen-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Anseo	Anseo	anseo-R	Rl
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Leathchois	Leathchois	Leathchois-N	Npmsc
agus	agus	agus-C	Cc
shín	shín	sín-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
mapa	mapa	mapa-N	Ncmsc
chuig	chuig	chuig-S	Sp
an	an	an-T	Td-s
gCaptaen	gCaptaen	captaen-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Maith	Maith	Maith-N	Npmsc
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Captaen	Captaen	captaen-N	Ncmsc
Ó	Ó	Ó-U	Up
Súilleabháin	Súilleabháin	Súilleabháin-N	Npmsc
le	le	le-S	Sp
Leathchois	Leathchois	Leathchois-N	Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Leathchois	Leathchois	Leathchois-N	Npmsc
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
labhair	labhair	labhair-V	Vmis
an	an	an-T	Td-s
Captaen	Captaen	captaen-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
bhfear	bhfear	fear-N	Ncmsc
eile	eile	eile-D	Dd
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
leat	leat	le-P	Pr2-s
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
sé	sé	sé-P	Pp3msn
de	de	de-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Mo	Mo	mo-D	Dp1-s
dheartháir	dheartháir	deartháir-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
tá	tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
imithe	imithe	imigh-A	Av
i	i	i-S	Sp
dtír	dtír	tír-N	Ncfsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ar	Ar	ar-Q	Qq-s
tháinig	tháinig	tar-V	Vmis
sibh	sibh	sibh-P	Pp2-p
ar	ar	ar-S	Sp
thóir	thóir	tóir-N	Ncfsc
an	an	an-W	Wpdq|Wp-q|Td-s
óir	óir	ór-C	Cs|Ncmsg|Ncmpc
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Captaen	Captaen	captaen-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Thángamar	Thángamar	tar-V	Vmis1p
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
mhapa	mhapa	mapa-N	Ncmsc
againn	againn	ag-P	Pr1-p
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
tú	tú	tú-P	Pp2-s
teacht	teacht	tar-N	Ncmsc|Nv
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
linne	linne	le-P	Pr1-p-e
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Captaen	Captaen	captaen-N	Ncmsc
Ó	Ó	Ó-U	Up
Súilleabháin	Súilleabháin	Súilleabháin-N	Npmsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
shroich	shroich	sroich-V	Vmis
siad	siad	siad-P	Pp3-pn
barr	barr	barr-N	Ncmsc
na	na	na-T	Tdfsg
cé	cé	cé-N	Ncfsg
scrúdaigh	scrúdaigh	scrúdaigh-V	Vmis
an	an	an-T	Td-s
Captaen	Captaen	captaen-N	Ncmsc
an	an	an-T	Td-s
mapa	mapa	mapa-N	Ncmsg|Ncmsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
thug	thug	tabhair-V	Vmis
siad	siad	siad-P	Pp3-pn
aghaidh	aghaidh	aghaidh-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
áit	áit	áit-N	Ncfsc
ina	ina	i-S	Spr
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
t-ór	t-ór	ór-N	Ncmsc
Spáinneach	Spáinneach	Spáinneach-A	Aq-msc
i	i	i-S	Sp
bhfolach	bhfolach	folach-N	Ncmsc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
arbh	arbh	is-W	Wsdq
fhíor	fhíor	fíor-A	Aqp
do	do	do-S	Sp
na	na	na-T	Td-p
scéalta	scéalta	scéal-N	Ncmpc
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
ór	ór	ór-N	Ncmsc
Spáinneach	Spáinneach	Spáinneach-A	Aq-msc
i	i	i-S	Sp
bhfolach	bhfolach	folach-N	Ncmsc
ar	ar	ar-S	Sp
Oileán	Oileán	oileán-N	Ncmsc
na	na	na-T	Td-p
Rón	Rón	rón-N	Ncmsc
?	?	?-F	Fq
B	B	B-X	Xl
’	’	’-F	Fa
,	,	,-F	Fi
dar	dar	dar-S	Sp
ndóigh	ndóigh	dóigh-N	Ncfsc
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
thóg	thóg	tóg-V	Vmis---n
sé	sé	sé-P	Pp3msn
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gCaptaen	gCaptaen	captaen-N	Ncmsc
agus	agus	agus-C	Cc
ar	ar	ar-S	Sp
Leathchois	Leathchois	Leathchois-N	Npmsc
an	an	an-T	Td-s
t-ór	t-ór	ór-N	Ncmsc
Spáinneach	Spáinneach	Spáinneach-A	Aq-msc
a	a	a-U	U
fháil	fháil	faigh-N	Nv
agus	agus	agus-C	Cc
a	a	a-U	U
roinnt	roinnt	roinn-N	Nv
eatarthu	eatarthu	idir-P	Pr3-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
i	i	i-S	Sp
m	m	m-X	Xl
’	’	’-F	Fa
saibhir	saibhir	saibhir-N	Ncmsc
anois	anois	anois-R	Rt
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Leathchois	Leathchois	Leathchois-N	Npmsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
siad	siad	siad-P	Pp3-pn
ar ais	ar ais	ar_ais-R	Rd
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
ché	ché	cé-N	Ncfsc
d	d	d-X	Xl
’	’	’-F	Fa
ordaigh	ordaigh	ordaigh-V	Vmm-2s
an	an	an-T	Td-s
Captaen	Captaen	captaen-N	Ncmsc
don	don	do-S	Spa-s
fhear	fhear	fear-N	Ncmsc
dul	dul	téigh-N	Ncmsc|Nv
isteach	isteach	isteach-R	Rd
ina	ina	i-S	Spp-s
bhád	bhád	bád-N	Ncmsc
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
bailiú	bailiú	bailigh-N	Ncmsc|Nv
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bailigh	Bailigh	bailigh-V	Vmm-2s
leat	leat	le-P	Pr2-s
as	as	as-S	Sp
an	an	an-T	Td-s
áit	áit	áit-N	Ncfsc
seo	seo	seo-D	Dd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Captaen	Captaen	captaen-N	Ncmsc
Ó	Ó	Ó-U	Up
Súilleabháin	Súilleabháin	Súilleabháin-N	Npmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
nó	nó	nó-C	Cc
is	is	agus-C	Cc
duitse	duitse	do-P	Pr2-s-e
is	is	is-U	U
measa	measa	olc-A	Aqc
!	!	!-F	Fe
’	’	’-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
fhan	fhan	fan-V	Vmis
an	an	an-T	Td-s
Captaen	Captaen	captaen-N	Ncmsc
agus	agus	agus-C	Cc
Leathchois	Leathchois	Leathchois-N	Npmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcé	gcé	cé-N	Ncfsc
ag	ag	ag-S	Sp
faire	faire	fair-N	Nv
nó	nó	nó-C	Cc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
An	An	an-T	Td-s
Corcán	Corcán	corcán-N	Ncmsc
Óir	Óir	óir-C	Cs
imithe	imithe	imigh-A	Av
as	as	as-S	Sp
radharc	radharc	radharc-N	Ncmsc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
is	is	is-W	Wp-i
féidir	féidir	féidir-N	Ns-s
linn	linn	le-P	Pr1-p
a	a	a-U	U
bheith	bheith	bí-N	Nv
cinnte	cinnte	cinn-A	Av
gur	gur	gur-Q	Q--s
mhair	mhair	mair-V	Vmis
Leathchois	Leathchois	Leathchois-N	Npmsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
Captaen	Captaen	captaen-N	Ncmsc
Ó	Ó	Ó-U	Up
Súilleabháin	Súilleabháin	Súilleabháin-N	Npmsc
go	go	go-U	Ua
sona	sona	sona-A	Aqp
sásta	sásta	sásta-A	Aqp
as	as	as-S	Sp
sin	sin	sin-P	Pd
amach	amach	amach-R	Rd
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
Réalt	Réalt	alt-N	Ncmsc
na	na	na-T	Td-p
Mara	Mara	Mara-N	Npmsg
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
ar	ar	ar-S	Sp
Oileán	Oileán	oileán-N	Ncmsc
na	na	na-T	Td-p
Rón	Rón	rón-N	Ncmsc
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
thóir	thóir	tóir-N	Ncfsc
óir	óir	óir-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
criú	criú	criú-N	Ncmsc
an	an	an-T	Td-s
bháid	bháid	bád-N	Ncmsg
,	,	,-F	Fi
ór	ór	ór-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
i	i	i-S	Sp
bhfolach	bhfolach	folach-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
oileán	oileán	oileán-N	Ncmsc
,	,	,-F	Fi
má	má	má-N	Ncfsc|Cs
b	b	b-X	Xl
’	’	’-F	Fa
do	do	do-S	Sp
na	na	na-T	Td-p
scéalta	scéalta	scéal-N	Ncmpc
.	.	.-F	Fe
