Bhí	Bhí	bí-V	Vmis
baintreach	baintreach	baintreach-N	Ncfsc
ina	ina	i-S	Spp-s
cónaí	cónaí	cónaí-N	Ncmsc
in aice	in aice	in_aice-S	Spc
an	an	an-T	Td-s
Daingin	Daingin	daingean-N	Ncmsg
uair	uair	uair-N	Ncfsc
dá	dá	dá-C	Cs
raibh	raibh	bí-V	Vmis---d
.	.	.-F	Fe
mhac	mhac	mac-N	Ncmsc
amháin	amháin	amháin-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
Brian	Brian	Brian-N	Ncmsc|Npmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Théadh	Théadh	téigh-V	Vmih
sé	sé	sé-P	Pp3msn
don	don	do-S	Spa-s
Daingean	Daingean	Daingean-N	Npmsc
ag	ag	ag-S	Sp
imirt	imirt	imir-N	Nv
chártaí	chártaí	cárta-N	Ncmpg
istoíche	istoíche	istoíche-R	Rt
ar	ar	is-W	Wpsi|Ncmsc|Wssi|Wpdi
amanta	amanta	amanta-A	Av
.	.	.-F	Fe
Oíche	Oíche	oíche-N	Ncfsc
dá	dá	dá-C	Cs
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
gabháil	gabháil	gabh-N	Nv
an	an	an-T	Td-s
bóthar	bóthar	bóthar-N	Ncmsc
chonaic	chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
chuige	chuige	chuige-R	Rg
ceathrar	ceathrar	ceathrar-N	Ncmsc
fear	fear	fear-N	Ncmpg
agus	agus	agus-C	Cc
comhra	comhra	comhr-N	Ncmpc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
ngualainn	ngualainn	gualainn-N	Ncfsc
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Ag	Ag	ag-S	Sp
druidim	druidim	druid-N	Nv
dóibh	dóibh	do-P	Pr3-p
le	le	le-S	Sp
Brian	Brian	Brian-N	Ncmsc|Npmsc
bhuail	bhuail	buail-V	Vmis
an	an	an-T	Td-s
ceathrar	ceathrar	ceathrar-N	Ncmsc
an	an	an-Q	Qq
chomhra	chomhra	comhair-V	Vmsp---n
anuas	anuas	anuas-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbóthar	mbóthar	bóthar-N	Ncmsc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
leis	leis	le-S	Sp
sin	sin	sin-P	Pd
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmis
siad	siad	siad-P	Pp3-pn
as	as	as-S	Sp
radharc	radharc	radharc-N	Ncmsc
.	.	.-F	Fe
Bhuail	Bhuail	buail-V	Vmis
fiosracht	fiosracht	fiosracht-N	Ncfsc
Brian	Brian	Brian-N	Ncmsc|Npmsc
.	.	.-F	Fe
Sall	Sall	Sall-N	Npmsc
leis	leis	le-P	Pr3ms
go dtí	go dtí	go_dtí-S	Spc
an	an	an-Q	Qq
gcomhra	gcomhra	comhair-V	Vmsp
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
sé	sé	sé-P	Pp3msn
isteach	isteach	isteach-R	Rd
inti	inti	i-P	Pr3fs
.	.	.-F	Fe
Cad	Cad	cad-P	Pq
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sa	sa	i-S	Spa-s
chomhra	chomhra	comhair-V	Vmsp---n
ach	ach	ach-S	Sp
bean	bean	bean-N	Ncfsc
bhreá	bhreá	breá-A	Aq-fsc
óg	óg	óg-A	Aq-fsc
dhathúil	dhathúil	dathúil-A	Aq-fsc|Aq-fsv
!	!	!-F	Fe
Thit	Thit	tit-V	Vmis
Brian	Brian	Brian-N	Ncmsc|Npmsc
i	i	i-S	Sp
ngrá	ngrá	grá-N	Ncmsc
léi	léi	le-P	Pr3fs
ar	ar	ar-S	Sp
an	an	an-T	Td-s
dtoirt	dtoirt	toirt-N	Ncfsc
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
dhein	dhein	dein-V	Vmis
Brian	Brian	Brian-N	Ncmsc|Npmsc
faic	faic	faic-N	Ncfsc
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
chomhra	chomhra	comhair-V	Vmsp---n
a	a	a-U	U
bhualadh	bhualadh	buail-N	Nv
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
ghualainn	ghualainn	gualainn-N	Ncfsc
agus	agus	agus-C	Cc
tabhairt	tabhairt	tabhair-N	Ncfsc|Nv
faoin	faoin	faoi-S	Spa-s
mbaile	mbaile	baile-N	Ncmsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
a	a	a-D	Dp3
mháthair	mháthair	máthair-N	Ncfsc
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
é	é	é-P	Pp3ms
agus	agus	agus-C	Cc
an	an	an-Q	Qq
chomhra	chomhra	comhair-V	Vmsp---n
ar	ar	ar-S	Sp|Ncmsc
a	a	a-D	Dp3
ghualainn	ghualainn	gualainn-N	Ncfsc
aige	aige	ag-P	Pr3ms
bhí	bhí	bí-V	Vmis
iontas	iontas	iontas-N	Ncmsc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
máthair	máthair	máthair-N	Ncfsc
Bhriain	Bhriain	Brian-N	Npfsg|Ncmsg
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
chomhra	chomhra	comhair-V	Vmsp---n
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
bhfuairis	bhfuairis	faigh-V	Vmis2s
do	do	do-S	Sp
bhean	bhean	bean-N	Ncfsc
,	,	,-F	Fi
a	a	a-U	Uv
Bhriain	Bhriain	Brian-N	Ncmsv
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	ó-S	Sp
Dhia	Dhia	dia-N	Ncmsc
a	a	a-Q	Q-i|Q-r
fuaireas	fuaireas	faigh-V	Vmis1s
í	í	í-P	Pp3fs
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Brian	Brian	Brian-N	Ncmsc|Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
buairt	buairt	buairt-N	Ncfsc
ar	ar	ar-S	Sp
Bhrian	Bhrian	Brian-N	Ncmsc|Npmsc
mar	mar	mar-C	Cs
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
chaint	chaint	caint-N	Ncfsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
mbean	mbean	bean-N	Ncfsc
.	.	.-F	Fe
Siúd	Siúd	siúd-P	Pd
leis	leis	le-P	Pr3ms
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
lios	lios	lios-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
i	i	i-S	Sp
gcóngar	gcóngar	cóngar-N	Ncmsc
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
.	.	.-F	Fe
Shuigh	Shuigh	suigh-V	Vmis
sé	sé	sé-P	Pp3msn
síos	síos	síos-R	Rd
dó	dó	do-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
Faoi	Faoi	faoi-S	Sp
cheann	cheann	ceann-N	Ncmsc
tamaill	tamaill	tamall-N	Ncmsg
chuala	chuala	clois-V	Vmis
sé	sé	sé-P	Pp3msn
na	na	na-T	Td-p
sióga	sióga	sióg-N	Ncfpc
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
.	.	.-F	Fe
‘	‘	‘-X	Xx
Dá	Dá	dá-C	Cs
mbeadh	mbeadh	bí-V	Vmc
braon	braon	braon-N	Ncmsc
den	den	de-S	Spa-s
deoch	deoch	deoch-N	Ncfsc
sin	sin	sin-D	Dd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbord	mbord	bord-N	Ncmsc
ólta	ólta	ól-A	Av
aici	aici	ag-P	Pr3fs
bheadh	bheadh	bí-V	Vmc
caint	caint	caint-N	Ncfsc
aici	aici	ag-P	Pr3fs
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
sióg	sióg	sióg-N	Ncfsc
amháin	amháin	amháin-A	Aqp
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
ardaigh	ardaigh	ardaigh-V	Vmm-2s
croí	croí	croí-N	Ncmsc
Bhriain	Bhriain	Brian-N	Npfsg|Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ar	Ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
mo	mo	mo-D	Dp1-s
bheansa	bheansa	bean-N	Ncfsc-e
atá	atá	bí-V	Vmip---r
id	id	id-N	Ncfsc
ag	ag	ag-S	Sp
trácht	trácht	trácht-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sé	sé	sé-P	Pp3msn
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
leis	leis	le-S	Sp
sa	sa	i-S	Spa-s
lios	lios	lios-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhféadfainn	bhféadfainn	féad-V	Vmc-1s
an	an	an-T	Td-s
deoch	deoch	deoch-N	Ncfsc
sin	sin	sin-D	Dd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbord	mbord	bord-N	Ncmsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
agam	agam	ag-P	Pr1-s
le	le	le-S	Sp
tabhairt	tabhairt	tabhair-N	Nv
do	do	do-D	Dp2-s|Sp
mo	mo	mo-D	Dp1-s
bhean	bhean	bean-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
sé	sé	sé-P	Pp3msn
de	de	de-S	Sp
na	na	na-T	Td-p
sióga	sióga	sióg-N	Ncfpc
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
sióg	sióg	sióg-N	Ncfsc
an	an	an-T	Td-s
deoch	deoch	deoch-N	Ncfsc
dó	dó	do-P	Pr3ms
ach	ach	ach-C	Cs
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
,	,	,-F	Fi
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
doirt	doirt	doirt-V	Vmm-2s-n
oiread	oiread	oiread-N	Ns-s
is	is	agus-C	Cc
braon	braon	braon-N	Ncmsc
den	den	de-S	Spa-s
deoch	deoch	deoch-N	Ncfsc
nó	nó	nó-C	Cc
ní	ní	ní-Q	Qn
leigheasfar	leigheasfar	leigheas-V	Vmif0--n
do	do	do-S	Sp
bhean	bhean	bean-N	Ncfsc
.	.	.-F	Fe
’	’	’-F	Fa
Bhí	Bhí	bí-V	Vmis
ardáthas	ardáthas	áthas-N	Ncmsc
ar	ar	ar-S	Sp
Bhrian	Bhrian	Brian-N	Ncmsc|Npmsc
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
sé	sé	sé-P	Pp3msn
an-aire	an-aire	aire-N	Ncfsc|Ncmsc
don	don	do-S	Spa-s
bhuidéal	bhuidéal	buidéal-N	Ncmsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
shlí	shlí	slí-N	Ncfsc
abhaile	abhaile	abhaile-R	Rd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
caint	caint	caint-N	Ncfsc
ag	ag	ag-S	Sp
mo	mo	mo-D	Dp1-s
bhean	bhean	bean-N	Ncfsc
anois	anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
abhaile	abhaile	abhaile-R	Rd
leis	leis	le-P	Pr3ms
gur	gur	gur-Q	Q--s
thug	thug	tabhair-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
deoch	deoch	deoch-N	Ncfsc
dá	dá	do-S	Spp-s
bhean	bhean	bean-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ól	Ól	ól-N	Ncmsc|Nv
é	é	é-P	Pp3ms
seo	seo	seo-P	Pd
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
léi	léi	le-P	Pr3fs
,	,	,-F	Fi
‘	‘	‘-X	Xx
agus	agus	agus-C	Cc
beidh	beidh	bí-V	Vmif
caint	caint	caint-N	Ncfsc
agat	agat	ag-P	Pr2-s
.	.	.-F	Fe
’	’	’-F	Fa
Shín	Shín	Sín-N	Npfsc
sé	sé	is-W	Wp-i-3
an	an	an-T	Td-s
deoch	deoch	deoch-N	Ncfsc
chuici	chuici	chuig-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Brian	Brian	Brian-N	Ncmsc|Npmsc
bocht	bocht	bocht-A	Aq-msc
ar	ar	ar-S	Sp
tinneall	tinneall	tinneall-N	Ns-s
a	a	a-D	Dp3
fhad	fhad	fad-N	Ncmsc
is	is	agus-C	Cc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
ag	ag	ag-S	Sp
ól	ól	ól-N	Nv
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
deoch	deoch	deoch-N	Ncfsc
ólta	ólta	ól-A	Av
ag	ag	ag-S	Sp
an	an	an-T	Td-s
mbean	mbean	bean-N	Ncfsc
tháinig	tháinig	tar-V	Vmis
a	a	a-D	Dp3
caint	caint	caint-N	Ncfsc
chuici	chuici	chuig-P	Pr3fs
!	!	!-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
inis	inis	inis-V	Vmis
sí	sí	sí-P	Pp3fsn
do	do	do-S	Sp
Bhrian	Bhrian	Brian-N	Ncmsc|Npmsc
agus	agus	agus-C	Cc
dá	dá	do-S	Spp-s
mháthair	mháthair	máthair-N	Ncfsc
cad	cad	cad-P	Pq
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmm-2s
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bríde	Bríde	Bríde-N	Npmsc
an	an	an-T	Td-s
t-ainm	t-ainm	ainm-N	Ncmsc
atá	atá	bí-V	Vmip---r
orm	orm	ar-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
dúirt	dúirt	abair-V	Vmis
Bríde	Bríde	Bríde-N	Npmsc
leo	leo	le-P	Pr3-p
gur	gur	gur-Q	Q--s
thug	thug	tabhair-V	Vmis
na	na	na-T	Td-p
sióga	sióga	sióg-N	Ncfpc
leo	leo	le-P	Pr3-p
í	í	í-P	Pp3fs
ó	ó	ó-S	Sp
íochtar	íochtar	íochtar-N	Ncmsc
na	na	na-T	Tdfsg
hÉireann	hÉireann	Éire-N	Npfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
litir	litir	litir-N	Ncfsc
a	a	a-U	U
scríobh	scríobh	scríobh-N	Nv
go dtí	go dtí	go_dtí-S	Spc
mo	mo	mo-D	Dp1-s
mhuintir	mhuintir	muintir-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
ansin	ansin	ansin-R	Rt|Rl
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
buairt	buairt	buairt-N	Ncfsc
orthu	orthu	ar-P	Pr3-p
.	.	.-F	Fe
’	’	’-F	Fa
Scríobh	Scríobh	scríobh-N	Ncmsc|Nv|Vmis|Nv
Bríde	Bríde	Bríde-N	Npf-g|Npmsg|Npmsc
an	an	an-T	Td-s
litir	litir	litir-N	Ncfsc
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
do	do	do-S	Sp
Bhrian	Bhrian	Brian-N	Ncmsc|Npmsc
í	í	í-P	Pp3fs
.	.	.-F	Fe
Bhailigh	Bhailigh	bailigh-V	Vmis
Brian	Brian	Brian-N	Ncmsc|Npmsc
leis	leis	le-P	Pr3ms
thairis	thairis	tairis-V	Vmis
sléibhte	sléibhte	sliabh-N	Ncmpc
agus	agus	agus-C	Cc
gleannta	gleannta	gleann-N	Ncmpg|Ncmpc
.	.	.-F	Fe
Stad	Stad	stad-V	Vmis
ná	ná	ná-Q	Qnm
staonadh	staonadh	staon-V	Vmm-3s-n
níor	níor	níor-Q	Qn-s
dhein	dhein	dein-V	Vmis
sé	sé	sé-P	Pp3msn
gur	gur	gur-Q	Q--s
bhain	bhain	bain-V	Vmis
sé	sé	sé-P	Pp3msn
amach	amach	amach-R	Rd
íochtar	íochtar	íochtar-N	Ncmsc
na	na	na-T	Tdfsg
hÉireann	hÉireann	Éire-N	Npfsg
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
ghearr	ghearr	gearr-A	Aqp
go	go	go-Q	Q
bhfuair	bhfuair	faigh-V	Vmis
sé	sé	sé-P	Pp3msn
amach	amach	amach-R	Rd
tigh	tigh	teach-N	Ncmsd
na	na	na-T	Tdfsg
mná	mná	bean-N	Ncfsg
.	.	.-F	Fe
Tigh	Tigh	teach-N	Ncmsd
beag	beag	beag-A	Aq-msc
feirmeora	feirmeora	feirmeoir-N	Ncmsg
ab	ab	is-W	Wsri
ea	ea	ea-P	Pp3-s
é	é	é-P	Pp3ms
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
leis	leis	le-S	Sp
sa	sa	i-S	Spa-s
tigh	tigh	teach-N	Ncmsd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
fear	fear	fear-N	Ncmsc
,	,	,-F	Fi
bean	bean	bean-N	Ncfsc
agus	agus	agus-C	Cc
garsún	garsún	garsún-N	Ncmpg|Ncmsc
suite	suite	suigh-A	Aqp|Av
istigh	istigh	istigh-R	Rl
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
faoi	faoi	faoi-S	Sp
bhrón	bhrón	brón-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
buairt	buairt	buairt-N	Ncfsc
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
gcroí	gcroí	croí-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
ag	ag	ag-S	Sp
gol	gol	goil-N	Nv
go	go	go-U	Ua
ciúin	ciúin	ciúin-A	Aqp
cois	cois	cois-S	Sp
na	na	na-T	Tdfsg
tine	tine	tine-N	Ncfsc
.	.	.-F	Fe
Shín	Shín	Sín-N	Npfsc
Brian	Brian	Brian-N	Ncmsc|Npmsc
an	an	an-T	Td-s
litir	litir	litir-N	Ncfsc
go dtí	go dtí	go_dtí-S	Spc
bean	bean	bean-N	Ncfsc
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
léigh	léigh	léigh-V	Vmis
bean	bean	bean-N	Ncfsc
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
an	an	an-T	Td-s
litir	litir	litir-N	Ncfsc
bhí	bhí	bí-V	Vmis
iontas	iontas	iontas-N	Ncmsc
an	an	an-T	Td-s
domhain	domhain	domhan-N	Ncmsg
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
Bríde	Bríde	Bríde-N	Npmsc
ina	ina	i-S	Spp-s
beatha	beatha	beatha-N	Ncfsc
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
sí	sí	sí-P	Pp3fsn
ina	ina	i-S	Spp-s
beatha	beatha	beatha-N	Ncfsc
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
bean	bean	bean-N	Ncfsc
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
aoibh	aoibh	aoibh-N	Ncfsc
an	an	an-T	Td-s
gháire	gháire	gáire-N	Ncmsg
ar	ar	ar-S	Sp
fhear	fhear	fear-N	Ncmsc
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
Bríde	Bríde	Bríde-N	Npmsc
ina	ina	i-S	Spp-s
beatha	beatha	beatha-N	Ncfsc
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
agus	agus	agus-C	Cc
iontas	iontas	iontas-N	Ncmsc
an	an	an-T	Td-s
domhain	domhain	domhan-N	Ncmsg
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Léim	Léim	léim-V	Vmip1s|Vmm-2s|Vmis|Ncfsc
an	an	an-T	Td-s
garsún	garsún	garsún-N	Ncmsc
den	den	de-S	Spa-s
chathaoir	chathaoir	cathaoir-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
Bríde	Bríde	Bríde-N	Npmsc
ina	ina	i-S	Spp-s
beatha	beatha	beatha-N	Ncfsc
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Suigh	Suigh	suigh-V	Vmm-2s
síos	síos	síos-R	Rd
ansin	ansin	ansin-R	Rt|Rl
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
bean	bean	bean-N	Ncfsc
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
le	le	le-S	Sp
Brian	Brian	Brian-N	Ncmsc|Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	Ní-W	Wp-in|Up
foláir	foláir	foláir-N	Ns-s
nó	nó	nó-C	Cc
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
ocras	ocras	ocras-N	Ncmsc
ort	ort	ar-P	Pr2-s
.	.	.-F	Fe
’	’	’-F	Fa
Shuigh	Shuigh	suigh-V	Vmis
Brian	Brian	Brian-N	Ncmsc|Npmsc
chun	chun	chun-S	Sp
boird	boird	bord-N	Ncmsg
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
ith	ith	ith-V	Vmis
sé	sé	sé-P	Pp3msn
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
ól	ól	ól-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
sháith	sháith	sáith-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Táimid	Táimid	bí-V	Vmip1p
thar a bheith	thar a bheith	thar_a_bheith-R	Ri
buíoch	buíoch	buíoch-A	Aqp
díot	díot	de-P	Pr2-s
ach	ach	ach-C	Cs
caithfimid	caithfimid	caith-V	Vmif1p
Bríde	Bríde	Bríde-N	Npmsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
thar	thar	thar-S	Sp
n-ais	n-ais	ais-N	Ncfsc
abhaile	abhaile	abhaile-R	Rd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
fear	fear	fear-N	Ncmsc
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
le	le	le-S	Sp
Brian	Brian	Brian-N	Ncmsc|Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Baileoimid	Baileoimid	bailigh-V	Vmif1p
linn	linn	le-N	Ncfsc|Pr1-p
le	le	le-S	Sp
solas	solas	solas-N	Ncmsc
an	an	an-T	Td-s
lae	lae	lá-N	Ncmsg
agus	agus	agus-C	Cc
tabharfaimid	tabharfaimid	tabhair-V	Vmif1p
abhaile	abhaile	abhaile-R	Rd
í	í	í-P	Pp3fs
.	.	.-F	Fe
’	’	’-F	Fa
Bhí	Bhí	bí-V	Vmis
cumha	cumha	cumha-N	Ncmsc
ar	ar	ar-S	Sp
Bhrian	Bhrian	Brian-N	Ncmsc|Npmsc
.	.	.-F	Fe
Thabharfaidís	Thabharfaidís	tabhair-V	Vmc-3p
Bríde	Bríde	Bríde-N	Npmsc
abhaile	abhaile	abhaile-R	Rd
leo	leo	le-P	Pr3-p
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
chífeadh	chífeadh	chí-V	Vmc----n
sé	sé	sé-P	Pp3msn
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
arís	arís	arís-R	Rg
í	í	í-P	Pp3fs
.	.	.-F	Fe
chodladh	chodladh	codail-N	Nv
níor	níor	níor-Q	Qn-s
dhein	dhein	dein-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
oíche	oíche	oíche-N	Ncfsc
sin	sin	sin-D	Dd
!	!	!-F	Fe
Le	Le	le-S	Sp
solas	solas	solas-N	Ncmsc
an	an	an-T	Td-s
lae	lae	lá-N	Ncmsg
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmm-2s
fear	fear	fear-N	Ncmsc
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
agus	agus	agus-C	Cc
a	a	a-D	Dp3
mhac	mhac	mac-N	Ncmsc
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
le	le	le-S	Sp
Brian	Brian	Brian-N	Ncmsc|Npmsc
.	.	.-F	Fe
Bhailíodar	Bhailíodar	bailigh-V	Vmis3p
leo	leo	le-P	Pr3-p
thairis	thairis	tairis-V	Vmis
sléibhte	sléibhte	sliabh-N	Ncmpc
agus	agus	agus-C	Cc
gleannta	gleannta	gleann-N	Ncmpg|Ncmpc
gur	gur	gur-Q	Q--s
bhaineadar	bhaineadar	bain-V	Vmis3p
amach	amach	amach-R	Rd
tigh	tigh	teach-N	Ncmsd
Bhriain	Bhriain	Brian-N	Npfsg|Ncmsg
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
i	i	i-S	Sp
gcóngar	gcóngar	cóngar-N	Ncmsc
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
chonaiceadar	chonaiceadar	feic-V	Vmis3p
Bríde	Bríde	Bríde-N	Npmsc
sa	sa	i-S	Spa-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
Rith	Rith	rith-V	Vmis
sí	sí	sí-P	Pp3fsn
chucu	chucu	chuig-P	Pr3-p
agus	agus	agus-C	Cc
rug	rug	beir-V	Vmis
sí	sí	sí-P	Pp3fsn
barróg	barróg	barróg-N	Ncfsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
hathair	hathair	athair-N	Ncmsc
agus	agus	agus-C	Cc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
deartháir	deartháir	deartháir-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Suigh	Suigh	suigh-V	Vmm-2s
síos	síos	síos-R	Rd
ansin	ansin	ansin-R	Rt|Rl
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
máthair	máthair	máthair-N	Ncfsc
Bhriain	Bhriain	Brian-N	Npfsg|Ncmsg
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	Ní-W	Wp-in|Up
foláir	foláir	foláir-N	Ns-s
nó	nó	nó-C	Cc
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
ocras	ocras	ocras-N	Ncmsc
oraibh	oraibh	ar-P	Pr2-p
.	.	.-F	Fe
’	’	’-F	Fa
Shuigh	Shuigh	suigh-V	Vmis
siad	siad	siad-P	Pp3-pn
chun	chun	chun-S	Sp
boird	boird	bord-N	Ncmsg
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
ith	ith	ith-V	Vmis
siad	siad	siad-P	Pp3-pn
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
ól	ól	ól-V	Vmis
siad	siad	siad-P	Pp3-pn
a	a	a-D	Dp3
sáith	sáith	sáith-N	Ncfsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
a	a	a-D	Dp3
mbolg	mbolg	bolg-N	Ncmpg
lán	lán	lán-A	Aq--pg
acu	acu	ag-P	Pr3-p
shuíodar	shuíodar	suigh-V	Vmis3p
cois	cois	cois-S	Sp
na	na	na-T	Tdfsg
tine	tine	tine-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Raghaimid	Raghaimid	ragh-V	Vmip1p
abhaile	abhaile	abhaile-R	Rd
le	le	le-S	Sp
solas	solas	solas-N	Ncmsc
an	an	an-T	Td-s
lae	lae	lá-N	Ncmsg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
athair	athair	athair-N	Ncmsc
Bhríde	Bhríde	Bríde-N	Npf-g|Npfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
fada	fada	fada-A	Aqp
le	le	le-S	Sp
do	do	do-D	Dp2-s
mháthair	mháthair	máthair-N	Ncfsc
go	go	go-Q	Q-s
bhfeice	bhfeice	feic-V	Vmsp
sí	sí	sí-P	Pp3fsn
tú	tú	tú-P	Pp2-s
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
fada	fada	fada-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
go	go	go-Q	Q-s
bhfeice	bhfeice	feic-V	Vmsp
mé	mé	mé-P	Pp1-s
í	í	í-P	Pp3fs
sin	sin	sin-P	Pd|W
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Bríde	Bríde	Bríde-N	Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
cumha	cumha	cumha-N	Ncmsc
ar	ar	ar-S	Sp
Bhrian	Bhrian	Brian-N	Ncmsc|Npmsc
bocht	bocht	bocht-A	Aq-msc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
méid	méid	méid-N	Ncmsc
sin	sin	sin-D	Dd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-S	Sp
tiocfadsa	tiocfadsa	tiocfads-N	Ncmpc
thar	thar	thar-S	Sp
n-ais	n-ais	ais-N	Ncfsc
anseo	anseo	anseo-R	Rl
go dtí	go dtí	go_dtí-S	Spc
Brian	Brian	Brian-N	Ncmsc|Npmsc
arís	arís	arís-R	Rg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Bríde	Bríde	Bríde-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Mura	Mura	mura-C	Cs
mbeadh	mbeadh	bí-V	Vmc
Brian	Brian	Brian-N	Ncmsc|Npmsc
ní	ní	ní-Q	Qn
bheadh	bheadh	bí-V	Vmc----n
aon	aon	aon-D	Dq
chaint	chaint	caint-N	Ncfsc
agam	agam	ag-P	Pr1-s
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
chífinn	chífinn	chí-V	Vmc-1s-n
sibhse	sibhse	sibh-P	Pp2-p-e
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
arís	arís	arís-R	Rg
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
phósfadsa	phósfadsa	phósfads-N	Ncmpc
aon	aon	aon-D	Dq
fhear	fhear	fear-N	Ncmsc
eile	eile	eile-D	Dd
ach	ach	ach-S	Sp
Brian	Brian	Brian-N	Ncmsc|Npmsc
.	.	.-F	Fe
’	’	’-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
ardaigh	ardaigh	ardaigh-V	Vmm-2s
croí	croí	croí-N	Ncmsc
Bhriain	Bhriain	Brian-N	Npfsg|Ncmsg
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
méid	méid	méid-N	Ncmsc
seo	seo	seo-D	Dd
!	!	!-F	Fe
‘	‘	‘-X	Xx
Raghadsa	Raghadsa	Raghadsa-N	Npmsc
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
libh	libh	le-P	Pr2-p
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Pósfaidh	Pósfaidh	pós-V	Vmif
mé	mé	mé-P	Pp1-s
Bríde	Bríde	Bríde-N	Npmsc
agus	agus	agus-C	Cc
tabharfaidh	tabharfaidh	tabhair-V	Vmif
mé	mé	mé-P	Pp1-s
liom	liom	le-P	Pr1-s
abhaile	abhaile	abhaile-R	Rd
arís	arís	arís-R	Rg
í	í	í-P	Pp3fs
.	.	.-F	Fe
’	’	’-F	Fa
Agus	Agus	agus-C	Cc
sin	sin	sin-W	W
é	é	é-P	Pp3ms
díreach	díreach	díreach-A	Aqp|Ncmsc
a	a	a-Q	Q-r
dheineadar	dheineadar	dein-V	Vmis3p
!	!	!-F	Fe
Mhair	Mhair	mair-V	Vmis
Bríde	Bríde	Bríde-N	Npmsc
agus	agus	agus-C	Cc
Brian	Brian	Brian-N	Ncmsc|Npmsc
go	go	go-U	Ua
sona	sona	sona-A	Aqp
sásta	sásta	sásta-A	Aqp
as	as	as-S	Sp
sin	sin	sin-P	Pd
amach	amach	amach-R	Rd
.	.	.-F	Fe
Oíche	Oíche	oíche-N	Ncfsc
dá	dá	dá-C	Cs
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
gabháil	gabháil	gabh-N	Nv
an	an	an-T	Td-s
bóthar	bóthar	bóthar-N	Ncmsc
chonaic	chonaic	feic-V	Vmis
Brian	Brian	Brian-N	Ncmsc|Npmsc
chuige	chuige	chuige-R	Rg
ceathrar	ceathrar	ceathrar-N	Ncmsc
fear	fear	fear-N	Ncmpg
agus	agus	agus-C	Cc
comhra	comhra	comhr-N	Ncmpc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
ngualainn	ngualainn	gualainn-N	Ncfsc
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
