Dia	Dia	dia-N	Ncmsc
duit	duit	do-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
chaitín	chaitín	caitín-N	Ncmsv
,	,	,-F	Fi
Dia	Dia	dia-N	Ncmsc
duit	duit	do-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
stór	stór	stór-N	Ncmsv
.	.	.-F	Fe
An	An	is-W	Wp-q
fada	fada	fada-A	Aqp
ansin	ansin	ansin-R	Rt|Rl
tú	tú	tú-P	Pp2-s
?	?	?-F	Fq
Fada	Fada	fada-A	Aqp
go leor	go leor	go_leor-A	Aq
?	?	?-F	Fq
Scanraithe	Scanraithe	scanraigh-A	Av
romham	romham	roimh-P	Pr1-s
atá	atá	bí-V	Vmip---r
tú	tú	tú-P	Pp2-s
,	,	,-F	Fi
Nó	Nó	nó-C	Cc
scanraithe	scanraithe	scanraigh-A	Av
roimh	roimh	roimh-S	Sp
an	an	an-T	Td-s
rós	rós	rós-N	Ncmsc
?	?	?-F	Fq
Is	Is	is-W	Wp-i
cuma	cuma	cuma-A	Aqp
,	,	,-F	Fi
a	a	a-U	Uv
chaitín	chaitín	caitín-N	Ncmsv
,	,	,-F	Fi
Beimid	Beimid	bí-V	Vmif1p
cairdiúil	cairdiúil	cairdiúil-A	Aqp
fós	fós	fós-R	Rg
.	.	.-F	Fe
Seo	Seo	seo-W	W
babhla	babhla	babhla-N	Ncmsc
breá	breá	breá-A	Aq-msc
bainne	bainne	bainne-N	Ncmsg|Ncmsc
duit	duit	do-P	Pr2-s
,	,	,-F	Fi
Is	Is	agus-W	Wp-i|Wpri|Cc
iasc	iasc	iasc-N	Ncmsc|Vmm-2s|Ncmpg
mór	mór	mór-A	Aq-msc|Aqp|Ncmpg|Ncmsc|Ncmpg
groí	groí	groí-A	Aqp
.	.	.-F	Fe
Bain	Bain	bain-V	Vmm-2s|Npmsc
sásamh	sásamh	sásamh-N	Ncmpg|Ncmsc|Ncmpg
as	as	as-P	Pr3ms
,	,	,-F	Fi
a	a	a-U	Uv
chaitín	chaitín	caitín-N	Ncmsv
,	,	,-F	Fi
Bain	Bain	bain-V	Vmm-2s|Npmsc
sásamh	sásamh	sásamh-N	Ncmpg|Ncmsc|Ncmpg
as	as	as-P	Pr3ms
,	,	,-F	Fi
a	a	a-U	Uv
chroí	chroí	croí-N	Ncmsv
.	.	.-F	Fe
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
do	do	do-Q	Q
bholg	bholg	bolg-V	Vmis
lán	lán	lán-N	Ncmsc
,	,	,-F	Fi
Nó	Nó	nó-C	Cc
an	an	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
ocras	ocras	ocras-N	Ncmsc
ort	ort	ar-P	Pr2-s
go	go	go-U	Ua
fóill	fóill	fóill-A	Aqp
?	?	?-F	Fq
Ar	Ar	is-W	Ws-q
mhaith	mhaith	maith-A	Aqp
leat	leat	le-P	Pr2-s
dul	dul	téigh-N	Nv
a	a	a-U	U
chodladh	chodladh	codail-N	Nv
,	,	,-F	Fi
Ansin	Ansin	ansin-R	Rt|Rl
ar	ar	ar-S	Sp
an	an	an-T	Td-s
stól	stól	stól-N	Ncmsc
?	?	?-F	Fq
Fan	Fan	fan-V	Vmm-2s
anseo	anseo	anseo-R	Rl
liomsa	liomsa	le-P	Pr1-s-e
,	,	,-F	Fi
Is	Is	agus-C	Cc
ní	ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
ort	ort	ar-P	Pr2-s
aon	aon	aon-D	Dq
bhuairt	bhuairt	buairt-N	Ncfsc
.	.	.-F	Fe
Beimid	Beimid	bí-V	Vmif1p
ag	ag	ag-S	Sp
imirt	imirt	imir-N	Nv
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
,	,	,-F	Fi
Is	Is	agus-C	Cc
rachaimid	rachaimid	téigh-V	Vmif1p
ar	ar	ar-S	Sp
cuairt	cuairt	cuairt-N	Ncfsc
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
bhaile	bhaile	baile-N	Ncmsc
mór	mór	mór-A	Aq-msc
linn	linn	le-P	Pr1-p
,	,	,-F	Fi
Is	Is	is-W	Wpri
síos	síos	síos-R	Rd
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
trá	trá	trá-N	Ncfsc
,	,	,-F	Fi
Agus	Agus	agus-C	Cc
caithfimid	caithfimid	caith-V	Vmif1p
lá	lá	lá-N	Ncmsc
eile	eile	eile-D	Dd
,	,	,-F	Fi
Ag	Ag	ag-S	Sp
seoladh	seoladh	seol-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbá	mbá	bá-N	Ncfsc|Ncmsc
.	.	.-F	Fe
Déanfaidh	Déanfaidh	déan-V	Vmif
mé	mé	mé-P	Pp1-s
leaba	leaba	leaba-N	Ncfsc
duit	duit	do-P	Pr2-s
Sa	Sa	i-S	Spa-s
chiseán	chiseán	ciseán-N	Ncmsc
deas	deas	deas-A	Aq-msc
tuí	tuí	tuí-N	Ncfsg|Ncfsc
,	,	,-F	Fi
Is	Is	agus-C	Cc
beidh	beidh	bí-V	Vmif
tú	tú	tú-P	Pp2-s
te	te	te-A	Aqp
teolaí	teolaí	teolaí-A	Aqp
ann	ann	i-P	Pr3ms
,	,	,-F	Fi
Ansin	Ansin	ansin-R	Rt|Rl
i	i	i-S	Sp
do	do	do-D	Dp2-s
luí	luí	luí-N	Nv|Ncmsc
.	.	.-F	Fe
Mí-abha	Mí-abha	abha-N	Ncfsc
,	,	,-F	Fi
mhuis	mhuis	mhuis-N	Ncfsc
,	,	,-F	Fi
nach	nach	nach-Q	Qnr
mbeidh	mbeidh	bí-V	Vmif
mé	mé	mé-P	Pp1-s
,	,	,-F	Fi
Cé	Cé	cé-C	Cs
gur	gur	is-W	Wsdi|Wpdi
tú	tú	tú-P	Pp2-s
atá	atá	bí-V	Vmip---r
galánta	galánta	galánta-A	Aqc
,	,	,-F	Fi
Mar	Mar	mar-C	Cs
b	b	b-X	Xl
’	’	’-F	Fa
fhearr	fhearr	maith-A	Aqc
liom	liom	le-P	Pr1-s
m	m	m-X	Xl
’	’	’-F	Fa
áit	áit	áit-N	Ncfsc
féin	féin	féin-P	Px
,	,	,-F	Fi
Amuigh	Amuigh	amuigh-R	Rl
ar	ar	ar-S	Sp
na	na	na-T	Td-p
bánta	bánta	bán-N	Ncmpc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
beidh	beidh	bí-V	Vmif
uaigneas	uaigneas	uaigneas-N	Ncmsc
orm	orm	ar-P	Pr1-s
,	,	,-F	Fi
a	a	a-U	Uv
chaitín	chaitín	caitín-N	Ncmsv
,	,	,-F	Fi
Beidh	Beidh	bí-V	Vmif
buairt	buairt	buairt-N	Ncfsc
ar	ar	ar-N	Ncmsc|Sp
mo	mo	mo-D	Dp1-s
chroí	chroí	croí-N	Ncmsc
,	,	,-F	Fi
Ní	Ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
liomsa	liomsa	le-P	Pr1-s-e
,	,	,-F	Fi
Anseo	Anseo	anseo-R	Rl
feadh	feadh	feadh-N	Ncmsc
na	na	na-T	Tdfsg
hoích	hoích	hoích-N	Ncfsc
’	’	’-F	Fa
.	.	.-F	Fe
Tiocfad	Tiocfad	Tiocfad-N	Npmsc
ar	ar	ar-S	Sp
cuairt	cuairt	cuairt-N	Ncfsc
chugat	chugat	chuig-P	Pr2-s
,	,	,-F	Fi
Mar	Mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
gach	gach	gach-D	Dq
aon	aon	aon-D	Dq
lá	lá	lá-N	Ncmsc
.	.	.-F	Fe
Maith	Maith	Maith-N	Npmsc
go leor	go leor	go_leor-A	Aq
,	,	,-F	Fi
a	a	a-U	Uv
chaitín	chaitín	caitín-N	Ncmsv
,	,	,-F	Fi
Beidh	Beidh	bí-V	Vmif
sé	sé	sé-P	Pp3msn
sin	sin	sin-P	Pd
go	go	go-U	Ua
breá	breá	breá-A	Aqp
.	.	.-F	Fe
Dia	Dia	dia-N	Ncmsc
duit	duit	do-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
chaitín	chaitín	caitín-N	Ncmsv
,	,	,-F	Fi
Dia	Dia	dia-N	Ncmsc
duit	duit	do-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
stór	stór	stór-N	Ncmsv
…	…	…-F	Fi
