Rugadh	Rugadh	beir-V	Vmis0
Máire	Máire	Máire-N	Npfsc
Mhic	Mhic	Mac-U	Up
Ghiolla	Ghiolla	Giolla-N	Npfsg
Íosa	Íosa	Íosa-N	Ncmsg|Np|Npm-g|Ncmsc|Npmsg|Npmsc
I	I	i-S	Sp
mBéal Feirste	mBéal Feirste	Béal_Feirste-N	Npmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
27	27	27-M	Mn
Meitheamh	Meitheamh	Meitheamh-N	Ncmsc
1951	1951	1951-M	Mn
.	.	.-F	Fe
Máire	Máire	Máire-N	Npfsc
Nî	Nî	Nî-N	Nc
Leannacháin	Leannacháin	Leannacháin-N	Npmsg|Npmsc|Npfsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
uirthi	uirthi	ar-P	Pr3fs
sular	sular	sula-C	Cs-s
phós	phós	pós-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
gaolta	gaolta	gaol-N	Ncmpc
ag	ag	ag-S	Sp
Máire	Máire	Máire-N	Npfsc
i	i	i-S	Sp
gContae	gContae	contae-N	Ncmsc
Ros Comáin	Ros Comáin	Ros_Comáin-N	Npmsg
agus	agus	agus-C	Cc
bhain	bhain	bain-V	Vmis
sí	sí	sí-P	Pp3fsn
an-taitneamh	an-taitneamh	taitin-N	Ncmsc|Nv
as	as	as-S	Sp
na	na	na-T	Td-p
laethanta	laethanta	lá-N	Ncmpc
saoire	saoire	saoire-N	Ncfsg|Ncfsc
a	a	a-Q	Q-r
chaith	chaith	caith-V	Vmis
sí	sí	sí-P	Pp3fsn
ansin	ansin	ansin-R	Rt|Rl
.	.	.-F	Fe
Máire	Máire	Máire-N	Npfsc
i	i	i-S	Sp
Ros Comáin	Ros Comáin	Ros_Comáin-N	Npmsc
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
ar	ar	ar-S	Sp
Bhroncó	Bhroncó	broncó-N	Npmsc
,	,	,-F	Fi
an	an	an-T	Td-s
t-asal	t-asal	asal-N	Ncmsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
a	a	a-D	Dp3
hathair	hathair	athair-N	Ncmsc
sa	sa	i-S	Spa-s
phictiúr	phictiúr	pictiúr-N	Ncmsc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhreastal	fhreastal	freastail-N	Nv|Vmis
Máire	Máire	Máire-N	Npf-g|Npfsc
Ní	Ní	Ní-U	Up
Leannacháin	Leannacháin	Leannacháin-N	Npfsg
ar	ar	ar-S	Sp
bhunscoil	bhunscoil	bunscoil-N	Ncfsc
Chlochar	Chlochar	clochar-N	Ncmpg
na	na	na-T	Tdfsg
Trócaire	Trócaire	trócaire-N	Ncfsg
i	i	i-S	Sp
mBéal Feirste	mBéal Feirste	Béal_Feirste-N	Npmsc
.	.	.-F	Fe
Béarla	Béarla	béarla-N	Ncmsc
an	an	an-T	Td-s
t-ábhar	t-ábhar	ábhar-N	Ncmsc
scoile	scoile	scoil-N	Ncfsg
ba	ba	is-U	U
mhó	mhó	mór-A	Aqc
a	a	a-Q	Q-r
thaitin	thaitin	taitin-V	Vmis
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Máire	Máire	Máire-N	Npfsc
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
seacht	seacht	seacht-M	Mc
mbliana	mbliana	bliain-N	Ncfpc
d	d	d-X	Xl
’	’	’-F	Fa
aois	aois	aois-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an-suim	an-suim	suim-N	Ncfsc
ag	ag	ag-S	Sp
Máire	Máire	Máire-N	Npfsc
sa	sa	i-S	Spa-s
rince	rince	rince-N	Ncmsc
Gaelach	Gaelach	gaelach-A	Aq-msc
agus	agus	agus-C	Cc
bhuaigh	bhuaigh	buaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
go leor	go leor	go_leor-A	Aq|Ns-s|Rg
duaiseanna	duaiseanna	duais-N	Ncfpg
.	.	.-F	Fe
Máire	Máire	Máire-N	Npfsc
i	i	i-S	Sp
gcampa	gcampa	campa-N	Ncmsc
saoire	saoire	saoire-N	Ncfsg
Butlins	Butlins	Butlins-N	Npmsc
tar éis	tar éis	tar_éis-S	Spc
di	di	do-P	Pr3fs
comórtas	comórtas	comórtas-N	Ncmsc
rince	rince	rince-N	Ncmsc
Gaelach	Gaelach	gaelach-A	Aq-msc
a	a	a-U	U
bhuachan	bhuachan	buaigh-N	Nv
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
aon	aon	aon-M	Mc
bhliain	bhliain	bliain-N	Ncfsc
déag	déag	déag-N	Ns-s
d	d	d-X	Xl
’	’	’-F	Fa
fhág	fhág	fág-V	Vmis
Máire	Máire	Máire-N	Npfsc
an	an	an-T	Td-s
bhunscoil	bhunscoil	bunscoil-N	Ncfsc
agus	agus	agus-C	Cc
chuaigh	chuaigh	téigh-V	Vmis
sí	sí	sí-P	Pp3fsn
go	go	go-S	Sp
Clochar	Clochar	clochar-N	Ncmsc
Naomh	Naomh	Naomh-N	Npmsc
Doiminic	Doiminic	Doiminic-N	Npm-g|Npmsc
.	.	.-F	Fe
Béarla	Béarla	béarla-N	Ncmsc
,	,	,-F	Fi
Spáinnis	Spáinnis	Spáinnis-N	Ncfsc
agus	agus	agus-C	Cc
Stair	Stair	stair-N	Ncfsc
na	na	na-T	Td-p
hábhair	hábhair	ábhar-N	Ncmsg
scoile	scoile	scoil-N	Ncfsg
ba	ba	is-U	U
mhó	mhó	mór-A	Aqc
a	a	a-Q	Q-r
thaitin	thaitin	taitin-V	Vmis
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Thaitin	Thaitin	taitin-V	Vmis
cúrsaí	cúrsaí	cúrsa-N	Ncmpc
spóirt	spóirt	spórt-N	Ncmpc
léi	léi	le-P	Pr3fs
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
fhoireann	fhoireann	foireann-N	Ncfsc
badmantain	badmantain	badmantan-N	Ncmsg
na	na	na-T	Tdfsg
scoile	scoile	scoil-N	Ncfsg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
imir	imir	imir-V	Vmis
sí	sí	sí-P	Pp3fsn
camógaíocht	camógaíocht	camógaíocht-N	Ncfsc
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhreastal	fhreastal	freastail-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
chúrsaí	chúrsaí	cúrsa-N	Ncmpc
Gaeilge	Gaeilge	Gaeilge-N	Npfsg
i	i	i-S	Sp
mBaile	mBaile	Baile-N	Npmsc
na	na	na-T	Tdfsg
Finne	Finne	finne-N	Ncfsg
i	i	i-S	Sp
nGaeltacht	nGaeltacht	gaeltacht-N	Ncfsc
Dhún na nGall	Dhún na nGall	Dún_na_nGall-N	Npmsg
i	i	i-S	Sp
gcaitheamh	gcaitheamh	caitheamh-N	Ncmsc
an	an	an-T	Td-s
tsamhraidh	tsamhraidh	samhradh-N	Ncmsg
.	.	.-F	Fe
Máire	Máire	Máire-N	Npfsc
agus	agus	agus-C	Cc
foireann	foireann	foireann-N	Ncfsc
badmantain	badmantain	badmantan-N	Ncmpc
na	na	na-T	Tdfsg
scoile	scoile	scoil-N	Ncfsg
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhág	fhág	fág-V	Vmis
Máire	Máire	Máire-N	Npfsc
Clochar	Clochar	clochar-N	Ncmsc|Ncmpg
Naomh	Naomh	Naomh-N	Npmsc
Doiminic	Doiminic	Doiminic-N	Npm-g|Npmsc
chuaigh	chuaigh	téigh-V	Vmis
sí	sí	sí-P	Pp3fsn
chuig	chuig	chuig-S	Sp
Ollscoil	Ollscoil	ollscoil-N	Ncfsc
na	na	na-T	Tdfsg
Ríona	Ríona	ríon-N	Ncfsg
i	i	i-S	Sp
mBéal Feirste	mBéal Feirste	Béal_Feirste-N	Npmsc
agus	agus	agus-C	Cc
bhain	bhain	bain-V	Vmis
sí	sí	sí-P	Pp3fsn
céim	céim	céim-N	Ncfsc
sa	sa	i-S	Spa-s
dlí	dlí	dlí-N	Ncmsc
.	.	.-F	Fe
Ollscoil	Ollscoil	ollscoil-N	Ncfsc
na	na	na-T	Tdfsg
Ríona	Ríona	ríon-N	Ncfsg
,	,	,-F	Fi
Béal Feirste	Béal Feirste	Béal_Feirste-N	Npmsc
.	.	.-F	Fe
Ollscoil	Ollscoil	ollscoil-N	Ncfsc
na	na	na-T	Tdfsg
Ríona	Ríona	ríon-N	Ncfsg
,	,	,-F	Fi
Béal Feirste	Béal Feirste	Béal_Feirste-N	Npmsc
.	.	.-F	Fe
tábhachtach	tábhachtach	tábhachtach-A	Aqp
i	i	i-S	Sp
gColáiste	gColáiste	coláiste-N	Ncmsc
na	na	na-T	Tdfsg
Tríonóide	Tríonóide	Tríonóid-N	Ncfsg
i	i	i-S	Sp
mBaile	mBaile	Baile-N	Npmsc
Átha Cliath	Átha Cliath	Átha_Cliath-N	Npmsg
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
an	an	an-T	Td-s
post	post	post-N	Ncmsc
sin	sin	sin-D	Dd
ag	ag	ag-S	Sp
duine	duine	duine-N	Ncmsc
chomh	chomh	chomh-R	Ri
hóg	hóg	óg-A	Aqp
léi	léi	le-P	Pr3fs
riamh	riamh	riamh-R	Rg
roimhe	roimhe	roimh-P	Pr3ms
sin	sin	sin-P	Pd
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhág	fhág	fág-V	Vmis
sí	sí	sí-P	Pp3fsn
Béal Feirste	Béal Feirste	Béal_Feirste-N	Npmsc
agus	agus	agus-C	Cc
chuaigh	chuaigh	téigh-V	Vmis
sí	sí	sí-P	Pp3fsn
chun	chun	chun-S	Sp
cónaithe	cónaithe	cónaigh-N	Ncmpg|Nv--g
i	i	i-S	Sp
mBaile	mBaile	Baile-N	Npmsc
Átha Cliath	Átha Cliath	Átha_Cliath-N	Npmsg
.	.	.-F	Fe
Coláiste	Coláiste	coláiste-N	Ncmsc
na	na	na-T	Tdfsg
Tríonóide	Tríonóide	Tríonóid-N	Ncfsg
,	,	,-F	Fi
Baile	Baile	Baile-N	Npmsc
Átha Cliath	Átha Cliath	Átha_Cliath-N	Npmsc
.	.	.-F	Fe
Coláiste	Coláiste	coláiste-N	Ncmsc
na	na	na-T	Tdfsg
Tríonóide	Tríonóide	Tríonóid-N	Ncfsg
,	,	,-F	Fi
Baile	Baile	Baile-N	Npmsc
Átha Cliath	Átha Cliath	Átha_Cliath-N	Npmsc
.	.	.-F	Fe
Bliain	Bliain	bliain-N	Ncfsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|W|Dd
pósadh	pósadh	pósadh-V	Vmis0|Nv|Ncmsc
Máire	Máire	Máire-N	Npf-g|Npfsc
Ní	Ní	Ní-U	Up
Leannacháin	Leannacháin	Leannacháin-N	Npfsg
agus	agus	agus-C	Cc
Máirtín	Máirtín	Máirtín-N	Npm-g|Npmsg|Npmsc
Mac	Mac	Mac-U	Up
Ghiolla	Ghiolla	Giolla-N	Npfsg
Íosa	Íosa	Íosa-N	Ncmsg|Np|Npm-g|Ncmsc|Npmsg|Npmsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
beirt	beirt	beirt-N	Ncfsc
iníon	iníon	iníon-N	Ncfsc
agus	agus	agus-C	Cc
mac	mac	mac-N	Ncmsc|Ncmpg
amháin	amháin	amháin-A	Aqp
ag	ag	ag-S	Sp
Máire	Máire	Máire-N	Npfsc
agus	agus	agus-C	Cc
Máirtín	Máirtín	Máirtín-N	Npm-g|Npmsg|Npmsc
.	.	.-F	Fe
agus	agus	agus-C	Cc
rugadh	rugadh	beir-V	Vmis0
an	an	an-T	Td-s
cúpla	cúpla	cúpla-N	Ncmsc
,	,	,-F	Fi
Justin	Justin	Justin-N	Npmsc
agus	agus	agus-C	Cc
Justin	Justin	Justin-N	Npmsg|Npmsc
,	,	,-F	Fi
Saramai	Saramai	Saramai-N	Npmsc
,	,	,-F	Fi
Máirtín	Máirtín	Máirtín-N	Npmsc
,	,	,-F	Fi
Máire	Máire	Máire-N	Npfsc
,	,	,-F	Fi
Charlie	Charlie	Charlie-N	Npmsc
(	(	(-F	Fp
athair	athair	athair-N	Ncmsc
Mháirtín	Mháirtín	Máirtín-N	Npm-g|Npfsg
)	)	)-F	Fp
agus	agus	agus-C	Cc
Emma	Emma	Emma-N	Npfsg|Npfsc
.	.	.-F	Fe
Chaith	Chaith	caith-V	Vmis
Máire	Máire	Máire-N	Npfsc
Mhic	Mhic	Mac-U	Up
Ghiolla	Ghiolla	Giolla-N	Npfsg
Íosa	Íosa	Íosa-N	Ncmsg|Np|Npm-g|Ncmsc|Npmsg|Npmsc
roinnt	roinnt	roinn-N	Ncfsc|Nv
blianta	blianta	bliain-N	Ncfpg
ag	ag	ag-S	Sp
obair	obair	obair-N	Nv-----n
le	le	le-S	Sp
RTÉ	RTÉ	RTÉ-Y	Y
.	.	.-F	Fe
Bhíodh	Bhíodh	bí-V	Vmih
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
scríobh	scríobh	scríobh-N	Nv
do	do	do-S	Sp
nuachtáin	nuachtáin	nuachtán-N	Ncmpc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
irisí	irisí	iris-N	Ncfpc
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
.	.	.-F	Fe
Máire	Máire	Máire-N	Npfsc
Mhic	Mhic	Mac-U	Up
Ghiolla	Ghiolla	Giolla-N	Npfsg
Íosa	Íosa	Íosa-N	Ncmsg|Np|Npm-g|Ncmsc|Npmsg|Npmsc
ar	ar	is-W	Wssi|Wpdi|Wpsi
Frontline	Frontline	Frontline-N	Npmsc
ar	ar	ar-S	Sp
Máire	Máire	Máire-N	Npfsc
Mhic	Mhic	Mac-U	Up
Ghiolla	Ghiolla	Giolla-N	Npfsg
Íosa	Íosa	Íosa-N	Ncmsg|Np|Npm-g|Ncmsc|Npmsg|Npmsc
ar	ar	is-W	Wssi|Wpdi|Wpsi
Frontline	Frontline	Frontline-N	Npmsc
ar	ar	ar-S	Sp
Béal Feirste	Béal Feirste	Béal_Feirste-N	Npmsc
An	An	an-T	Td-s
tlúr	tlúr	tlúr-N	Ncmsc
Ros	Ros	Ros-N	Npmsc|Npfsc
Treabhair	Treabhair	Treabhair-N	Npmsg|Npmsc
Dún	Dún	dún-N	Ncmsc
Dealgan	Dealgan	Dealgan-N	Np
Droichead	Droichead	droichead-N	Ncmsc|Ncmpg
Átha	Átha	Átha-N	Npmsc
Ráth	Ráth	Ráth-N	Npmsc
Tó	Tó	Tó-N	Npmsc
Baile	Baile	Baile-N	Npmsc
Átha Cliath	Átha Cliath	Átha_Cliath-N	Npmsc
Ghiolla	Ghiolla	Giolla-N	Npfsg
Íosa	Íosa	Íosa-N	Ncmsg|Np|Npm-g|Ncmsc|Npmsg|Npmsc
post	post	post-N	Ncmsc
tábhachtach	tábhachtach	tábhachtach-A	Aq-msc
in	in	i-S	Sp
Ollscoil	Ollscoil	ollscoil-N	Ncfsc
na	na	na-T	Tdfsg
Ríona	Ríona	ríon-N	Ncfsg
i	i	i-S	Sp
mBéal Feirste	mBéal Feirste	Béal_Feirste-N	Npmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhág	fhág	fág-V	Vmis
muintir	muintir	muintir-N	Ncfsc
Mhic	Mhic	Mac-U	Up
Ghiolla	Ghiolla	Giolla-N	Npfsg
Íosa	Íosa	Íosa-N	Ncmsg|Np|Npm-g|Ncmsc|Npmsg|Npmsc
a	a	a-D	Dp3
dteach	dteach	teach-N	Ncmsc
i	i	i-S	Sp
gContae	gContae	contae-N	Ncmsc
na	na	na-T	Tdfsg
Mí	Mí	Mí-N	Npfsg
agus	agus	agus-C	Cc
chuaigh	chuaigh	téigh-V	Vmis
siad	siad	siad-P	Pp3-pn
chun	chun	chun-S	Sp
cónaithe	cónaithe	cónaigh-N	Ncmpg|Nv--g
i	i	i-S	Sp
Ros	Ros	Ros-N	Npfsc|Npmsc
Treabhair	Treabhair	Treabhair-N	Npmsg
,	,	,-F	Fi
i	i	i-S	Sp
gContae	gContae	contae-N	Ncmsc
an	an	an-T	Td-s
Dúin	Dúin	Dúin-N	Npmsc
.	.	.-F	Fe
Béal Feirste	Béal Feirste	Béal_Feirste-N	Npmsc
An	An	an-T	Td-s
tlúr	tlúr	tlúr-N	Ncmsc
Ros	Ros	Ros-N	Npmsc|Npfsc
Treabhair	Treabhair	Treabhair-N	Npmsg|Npmsc
Dún	Dún	dún-N	Ncmsc
Dealgan	Dealgan	Dealgan-N	Np
Droichead	Droichead	droichead-N	Ncmsc|Ncmpg
Átha	Átha	Átha-N	Npmsc
Ráth	Ráth	Ráth-N	Npmsc
Tó	Tó	Tó-N	Npmsc
Baile	Baile	Baile-N	Npmsc
Átha Cliath	Átha Cliath	Átha_Cliath-N	Npmsc
Bhog	Bhog	bog-A	Aq-msc
muintir	muintir	muintir-N	Ncfsc
Mhic	Mhic	Mac-U	Up
Ghiolla	Ghiolla	Giolla-N	Npfsg
Íosa	Íosa	Íosa-N	Ncmsg|Np|Npm-g|Ncmsc|Npmsg|Npmsc
ó	ó	ó-S	Sp
Ráth	Ráth	Ráth-N	Npmsc
Tó	Tó	Tó-N	Npmsc
i	i	i-S	Sp
gContae	gContae	contae-N	Ncmsc
na	na	na-T	Tdfsg
Mí	Mí	Mí-N	Npfsg
go dtí	go dtí	go_dtí-S	Spc
Ros	Ros	Ros-N	Npmsc|Npfsc
Treabhair	Treabhair	Treabhair-N	Npmsg|Npmsc
i	i	i-S	Sp
gContae	gContae	contae-N	Ncmsc
an	an	an-T	Td-s
Dúin	Dúin	Dúin-N	Npmsc
.	.	.-F	Fe
insealbhaíodh	insealbhaíodh	insealbhaigh-V	Vmih
Máire	Máire	Máire-N	Npfsc
Mhic	Mhic	Mac-U	Up
Ghiolla	Ghiolla	Giolla-N	Npfsg
Íosa	Íosa	Íosa-N	Ncmsg|Np|Npm-g|Ncmsc|Npmsg|Npmsc
mar	mar	mar-S	Sp
Uachtarán	Uachtarán	uachtarán-N	Ncmsc
ar	ar	ar-S	Sp
Éirinn	Éirinn	Éire-N	Npfsd
.	.	.-F	Fe
I	I	i-S	Sp
gCaisleán	gCaisleán	caisleán-N	Ncmsc
Bhaile	Bhaile	Baile-N	Npmsg
Átha Cliath	Átha Cliath	Átha_Cliath-N	Npmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
ócáid	ócáid	ócáid-N	Ncfsc
ar	ar	ar-S	Sp
siúl	siúl	siúil-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
daltaí	daltaí	dalta-N	Ncmpc
as	as	as-S	Sp
scoil	scoil	scoil-N	Ncfsc
amháin	amháin	amháin-A	Aqp
as	as	as-S	Sp
gach	gach	gach-D	Dq
cúige	cúige	cúige-N	Ncmsc
in	in	i-S	Sp
Éirinn	Éirinn	Éire-N	Npfsd
i láthair	i láthair	i_láthair-S	Spc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
ócáid	ócáid	ócáid-N	Ncfsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
seacht	seacht	seacht-M	Mc
mbliana	mbliana	bliain-N	Ncfpc
caite	caite	caith-A	Av
ag	ag	ag-S	Sp
Máire	Máire	Máire-N	Npfsc
Mhic	Mhic	Mac-U	Up
Ghiolla	Ghiolla	Giolla-N	Npfsg
Íosa	Íosa	Íosa-N	Ncmsg|Np|Npm-g|Ncmsc|Npmsg|Npmsc
ina	ina	i-S	Spp-s
hUachtarán	hUachtarán	uachtarán-N	Ncmsc
ceapadh	ceapadh	ceap-N	Nv
í	í	í-P	Pp3fs
ar feadh	ar feadh	ar_feadh-S	Spc
seacht	seacht	seacht-M	Mc
mbliana	mbliana	bliain-N	Ncfpc
eile	eile	eile-D	Dd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
slua	slua	slua-N	Ncmsc
mór	mór	mór-A	Aq-msc
i láthair	i láthair	i_láthair-S	Spc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
insealbhaíodh	insealbhaíodh	insealbhaigh-V	Vmih
Máire	Máire	Máire-N	Npfsc
Mhic	Mhic	Mac-U	Up
Ghiolla	Ghiolla	Giolla-N	Npfsg
Íosa	Íosa	Íosa-N	Ncmsg|Np|Npm-g|Ncmsc|Npmsg|Npmsc
ina	ina	i-S	Spp-s
hUachtarán	hUachtarán	uachtarán-N	Ncmsc
ar	ar	ar-S	Sp
Éirinn	Éirinn	Éire-N	Npfsd
den	den	de-S	Spa-s
dara	dara	dara-M	Mo
huair	huair	uair-N	Ncfsc
,	,	,-F	Fi
mí	mí	mí-N	Ncfsc|Ncmsc
na	na	na-T	Tdfsg
bhí	bhí	bí-N	Ncfsg
daoine	daoine	duine-N	Ncmpc
óga	óga	óg-A	Aq--pc
ó	ó	ó-S	Sp
cheann	cheann	ceann-N	Ncmsc
ceann	ceann	ceann-N	Ncmpg
na	na	na-T	Tdfsg
tíre	tíre	tír-N	Ncfsg
.	.	.-F	Fe
Is	Is	is-W	Wp-i
í	í	í-P	Pp3fs
an	an	an-T	Td-s
tUachtarán	tUachtarán	uachtarán-N	Ncmsc
féin	féin	féin-P	Px
a	a	a-Q	Q-r
thug	thug	tabhair-V	Vmis
cuireadh	cuireadh	cuireadh-N	Ncmsc
do	do	do-S	Sp
na	na	na-T	Td-p
daoine	daoine	duine-N	Ncmpc
óga	óga	óg-A	Aq--pc|Aq--pv|Aq--pc|Aq--pg
.	.	.-F	Fe
Is	Is	is-W	Wp-i
in	in	sin-P	Pd
Áras	Áras	áras-N	Ncmsc
an	an	an-T	Td-s
Uachtaráin	Uachtaráin	uachtarán-N	Ncmsg
a	a	a-Q	Q-r
chónaíonn	chónaíonn	cónaigh-V	Vmip
Uachtarán	Uachtarán	uachtarán-N	Ncmsc
na	na	na-T	Tdfsg
hÉireann	hÉireann	Éire-N	Npfsg
agus	agus	agus-C	Cc
is	is	is-W	Wpri
ann	ann	i-P	Pr3ms
atá	atá	bí-V	Vmip---r
muintir	muintir	muintir-N	Ncfsc
Mhic	Mhic	Mac-U	Up
Ghiolla	Ghiolla	Giolla-N	Npfsg
Íosa	Íosa	Íosa-N	Ncmsg|Np|Npm-g|Ncmsc|Npmsg|Npmsc
ina	ina	i-S	Spp-p
gcónaí	gcónaí	cónaí-N	Ncmsc
anois	anois	anois-R	Rt
.	.	.-F	Fe
Is	Is	is-W	Wp-i
maith	maith	maith-A	Aqp
leo	leo	le-P	Pr3-p
a	a	a-U	U
bheith	bheith	bí-N	Nv
ina	ina	i-S	Spp-p
gcónaí	gcónaí	cónaí-N	Ncmsc
in	in	i-S	Sp
Áras	Áras	áras-N	Ncmsc
an	an	an-T	Td-s
Uachtaráin	Uachtaráin	uachtarán-N	Ncmsg
,	,	,-F	Fi
teach	teach	teach-N	Ncmsc
álainn	álainn	álainn-A	Aq-msc
stairiúil	stairiúil	stairiúil-A	Aq-msc
atá	atá	bí-V	Vmip---r
suite	suite	suigh-A	Av
i	i	i-S	Sp
bPáirc	bPáirc	páirc-N	Ncfsc
an	an	an-T	Td-s
Fhionnuisce	Fhionnuisce	uisce-N	Ncmsg
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
Áras	Áras	áras-N	Ncmsc
an	an	an-T	Td-s
Uachtaráin	Uachtaráin	uachtarán-N	Ncmsg
oscailte	oscailte	oscail-A	Av
don	don	do-S	Spa-s
phobal	phobal	pobal-N	Ncmsc
agus	agus	agus-C	Cc
tugann	tugann	tabhair-V	Vmip
thart	thart	thart-R	Rd
ar	ar	ar-S	Sp
Áras	Áras	áras-N	Ncmsc
an	an	an-T	Td-s
Uachtaráin	Uachtaráin	uachtarán-N	Ncmsg
.	.	.-F	Fe
Tagann	Tagann	tar-V	Vmip
go leor	go leor	go_leor-R	Rg|Ns-s
daoine	daoine	duine-N	Ncmpg
ó	ó	ó-S	Sp
chian	chian	cian-N	Ncmsc|Ncfsc
is	is	agus-C	Cc
ó	ó	ó-S	Sp
chóngar	chóngar	cóngar-N	Ncmsc
ar	ar	ar-S	Sp
cuairt	cuairt	cuairt-N	Ncfsc
chuig	chuig	chuig-S	Sp
Máire	Máire	Máire-N	Npfsc
Mhic	Mhic	Mac-U	Up
Ghiolla	Ghiolla	Giolla-N	Npfsg
Íosa	Íosa	Íosa-N	Ncmsg|Np|Npm-g|Ncmsc|Npmsg|Npmsc
in	in	i-S	Sp
Áras	Áras	áras-N	Ncmsc
an	an	an-T	Td-s
Uachtaráin	Uachtaráin	uachtarán-N	Ncmsg
.	.	.-F	Fe
Tagann	Tagann	tar-V	Vmip
daoine	daoine	duine-N	Ncmpc
mór	mór	mór-A	Aq--pg
le	le	le-S	Sp
rá	rá	abair-N	Nv
ó	ó	ó-S	Sp
thíortha	thíortha	tír-N	Ncfpc
eile	eile	eile-D	Dd
ar	ar	ar-S	Sp
cuairt	cuairt	cuairt-N	Ncfsc
chuici	chuici	chuig-P	Pr3fs
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
le	le	le-S	Sp
daoine	daoine	duine-N	Ncmpc
as	as	as-N	Ncmpg
an	an	an-T	Td-s
tír	tír	tír-N	Ncfsc
seo	seo	seo-D	Dd
.	.	.-F	Fe
An	An	an-T	Td-s
tUachtarán	tUachtarán	uachtarán-N	Ncmsc
agus	agus	agus-C	Cc
Rí	Rí	rí-N	Nv|Ncmsc|Ncmsg
Harald	Harald	Harald-N	Npmsc
V	V	V-X	Xl
na	na	na-T	Tdfsg
hIorua	hIorua	Iorua-N	Npf-g
.	.	.-F	Fe
An	An	an-T	Td-s
tUachtarán	tUachtarán	uachtarán-N	Ncmsc
agus	agus	agus-C	Cc
Rí	Rí	rí-N	Nv|Ncmsc|Ncmsg
Harald	Harald	Harald-N	Npmsc
V	V	V-X	Xl
na	na	na-T	Tdfsg
hIorua	hIorua	Iorua-N	Npf-g
.	.	.-F	Fe
An	An	an-T	Td-s
tUachtarán	tUachtarán	uachtarán-N	Ncmsc
agus	agus	agus-C	Cc
Hector	Hector	Hector-N	Np
Ó	Ó	Ó-U	Up
hEochagáin	hEochagáin	Eochagáin-N	Npmsc
.	.	.-F	Fe
An	An	an-T	Td-s
tUachtarán	tUachtarán	uachtarán-N	Ncmsc
agus	agus	agus-C	Cc
lúthchleasaí	lúthchleasaí	lúthchleasaí-N	Ncmsg|Ncmsc|Ncmsg
a	a	a-Q	Q-r
bhuaigh	bhuaigh	buaigh-V	Vmis
duais	duais	duais-N	Ncfsc
sna	sna	i-S	Spa-p
Cluichí	Cluichí	cluiche-N	Ncmpc
Oilimpeacha	Oilimpeacha	Oilimpeach-A	Aq--pc
Speisialta	Speisialta	speisialta-A	Aqp
.	.	.-F	Fe
An	An	an-T	Td-s
tUachtarán	tUachtarán	uachtarán-N	Ncmsc
agus	agus	agus-C	Cc
Hector	Hector	Hector-N	Np
Ó	Ó	Ó-U	Up
hEochagáin	hEochagáin	Eochagáin-N	Npmsc
.	.	.-F	Fe
An	An	an-T	Td-s
tUachtarán	tUachtarán	uachtarán-N	Ncmsc
agus	agus	agus-C	Cc
lúthchleasaí	lúthchleasaí	lúthchleasaí-N	Ncmsg|Ncmsc|Ncmsg
a	a	a-Q	Q-r
bhuaigh	bhuaigh	buaigh-V	Vmis
duais	duais	duais-N	Ncfsc
sna	sna	i-S	Spa-p
Cluichí	Cluichí	cluiche-N	Ncmpc
Oilimpeacha	Oilimpeacha	Oilimpeach-A	Aq--pc
Speisialta	Speisialta	speisialta-A	Aqp
.	.	.-F	Fe
Tagann	Tagann	tar-V	Vmip
Daidí	Daidí	daidí-N	Ncmsc
na	na	na-T	Tdfsg
Nollag	Nollag	Nollaig-N	Ncfsg
ar	ar	ar-S	Sp
cuairt	cuairt	cuairt-N	Ncfsc
chuig	chuig	chuig-S	Sp
Áras	Áras	áras-N	Ncmsc
an	an	an-T	Td-s
Uachtaráin	Uachtaráin	uachtarán-N	Ncmsg
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
!	!	!-F	Fe
Déanann	Déanann	déan-V	Vmip
an	an	an-T	Td-s
tUachtarán	tUachtarán	uachtarán-N	Ncmsc
go leor	go leor	go_leor-A	Aq
taistil	taistil	taisteal-N	Ncmsg
in	in	i-S	Sp
Éirinn	Éirinn	Éire-N	Npfsd
agus	agus	agus-C	Cc
thar	thar	thar-S	Sp
lear	lear	lear-N	Ncmsc
.	.	.-F	Fe
Tugann	Tugann	tabhair-V	Vmip
sí	sí	sí-P	Pp3fsn
cuairt	cuairt	cuairt-N	Ncfsc
ar	ar	ar-S	Sp
ospidéil	ospidéil	ospidéal-N	Ncmpc
,	,	,-F	Fi
ar	ar	ar-S	Sp
scoileanna	scoileanna	scoil-N	Ncfpc
,	,	,-F	Fi
ar	ar	ar-S	Sp
chumainn	chumainn	cumann-N	Ncmpc
agus	agus	agus-C	Cc
ar	ar	ar-S	Sp
chlubanna	chlubanna	club-N	Ncmpc
ar fud	ar fud	ar_fud-S	Spc
na	na	na-T	Tdfsg
hÉireann	hÉireann	Éire-N	Npfsg
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
sí	sí	sí-P	Pp3fsn
i láthair	i láthair	i_láthair-S	Spc
ag	ag	ag-S	Sp
ócáidí	ócáidí	ócáidí-N	Ncmsc
mór	mór	mór-A	Aq-msc
le	le	le-S	Sp
rá	rá	abair-N	Nv
ar nós	ar nós	ar_nós-S	Spc
cluichí	cluichí	cluiche-N	Ncmpg
ceannais	ceannais	ceannais-A	Aq--pg
i	i	i-S	Sp
bPáirc	bPáirc	páirc-N	Ncfsc
an	an	an-Q	Qq
Chrócaigh	Chrócaigh	crócaigh-V	Vmis
agus	agus	agus-C	Cc
an	an	an-T	Td-s
Comórtas	Comórtas	comórtas-N	Ncmsc
Náisiúnta	Náisiúnta	náisiúnta-A	Aqp
Treabhdóireachta	Treabhdóireachta	treabhdóireacht-N	Nv--g|Ncfsg
.	.	.-F	Fe
An	An	an-T	Td-s
tUachtarán	tUachtarán	uachtarán-N	Ncmsc
i	i	i-S	Sp
bPáirc	bPáirc	páirc-N	Ncfsc
an	an	an-Q	Qq
Chrócaigh	Chrócaigh	crócaigh-V	Vmis
.	.	.-F	Fe
An	An	an-T	Td-s
tUachtarán	tUachtarán	uachtarán-N	Ncmsc
san	san	i-S	Spa-s
Araib	Araib	Araib-N	Npfsc
Shádach	Shádach	Shádach-A	Aq-fsc
.	.	.-F	Fe
An	An	an-T	Td-s
tUachtarán	tUachtarán	uachtarán-N	Ncmsc
sa	sa	i-S	Spa-s
Tansáin	Tansáin	Tansáin-N	Npfsc
.	.	.-F	Fe
An	An	an-T	Td-s
tUachtarán	tUachtarán	uachtarán-N	Ncmsc
san	san	i-S	Spa-s
Araib	Araib	Araib-N	Npfsc
Shádach	Shádach	Shádach-A	Aq-fsc
.	.	.-F	Fe
An	An	an-T	Td-s
tUachtarán	tUachtarán	uachtarán-N	Ncmsc
sa	sa	i-S	Spa-s
Tansáin	Tansáin	Tansáin-N	Npfsc
.	.	.-F	Fe
Bronnann	Bronnann	bronn-V	Vmip
an	an	an-T	Td-s
tUachtarán	tUachtarán	uachtarán-N	Ncmsc
gradam	gradam	gradam-N	Ncmpg|Ncmsc
speisialta	speisialta	speisialta-A	Aqp
ar	ar	ar-S	Sp
dhaoine	dhaoine	duine-N	Ncmpc
óga	óga	óg-A	Aq--pc
sa	sa	i-S	Spa-s
tír	tír	tír-N	Ncfsc
seo	seo	seo-D	Dd
gach	gach	gach-D	Dq
bliain	bliain	bliain-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Gaisce	Gaisce	gaisce-N	Ncmsc
’	’	’-F	Fa
a	a	a-Q	Q-r
thugtar	thugtar	tabhair-V	Vmip0
ar	ar	ar-S	Sp
an	an	an-T	Td-s
ngradam	ngradam	gradam-N	Ncmsc
sin	sin	sin-D	Dd
.	.	.-F	Fe
Cuireann	Cuireann	cuir-V	Vmip
daoine	daoine	duine-N	Ncmpc
óga	óga	óg-A	Aq--pc
i	i	i-S	Sp
scoileanna	scoileanna	scoil-N	Ncfpc
,	,	,-F	Fi
i	i	i-S	Sp
gclubanna	gclubanna	club-N	Ncmpc
agus	agus	agus-C	Cc
i	i	i-S	Sp
gcoláistí	gcoláistí	coláiste-N	Ncmpc
isteach	isteach	isteach-R	Rd
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Daoine	Daoine	duine-N	Ncmpc
óga	óga	óg-A	Aq--pc
i mbun	i mbun	i_mbun-S	Spc
gaisce	gaisce	gaisce-N	Ncmsg
!	!	!-F	Fe
An	An	an-T	Td-s
tUachtarán	tUachtarán	uachtarán-N	Ncmsc
ag	ag	ag-S	Sp
bronnadh	bronnadh	bronn-N	Nv
gradaim	gradaim	gradam-N	Ncmsg
‘	‘	‘-X	Xx
Gaisce	Gaisce	gaisce-N	Ncmsc
’	’	’-F	Fa
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhíonn	bhíonn	bí-V	Vmig
am	am	am-N	Ncmsc
saor	saor	saor-A	Aq-msc
ag	ag	ag-S	Sp
Máire	Máire	Máire-N	Npfsc
Mhic	Mhic	Mac-U	Up
Ghiolla	Ghiolla	Giolla-N	Npfsg
Íosa	Íosa	Íosa-N	Ncmsg|Np|Npm-g|Ncmsc|Npmsg|Npmsc
bíonn	bíonn	bí-V	Vmig
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
léamh	léamh	léigh-N	Nv
nó	nó	nó-C	Cc
ag	ag	ag-S	Sp
cniotáil	cniotáil	cniotáil-N	Nv
.	.	.-F	Fe
Is	Is	is-W	Wp-i
maith	maith	maith-A	Aqp
léi	léi	le-P	Pr3fs
freisin	freisin	freisin-R	Rg
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
na	na	na-T	Td-p
sléibhte	sléibhte	sliabh-N	Ncmpg
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
an-suim	an-suim	suim-N	Ncfsc
aici	aici	ag-P	Pr3fs
sa	sa	i-S	Spa-s
Ghaeilge	Ghaeilge	Gaeilge-N	Npfsc
agus	agus	agus-C	Cc
caitheann	caitheann	caith-V	Vmip
sí	sí	sí-P	Pp3fsn
seachtain	seachtain	seachtain-N	Ncfsc
i	i	i-S	Sp
nGleann	nGleann	gleann-N	Ncmsc
Cholm	Cholm	Colm-N	Npmsg|Npm-g
Cille	Cille	cill-N	Ncfsg
gach	gach	gach-D	Dq
bliain	bliain	bliain-N	Ncfsc
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
feabhais	feabhais	feabhas-N	Ncmsg
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
cuid	cuid	cuid-N	Ncfsc
Gaeilge	Gaeilge	Gaeilge-N	Npfsg
.	.	.-F	Fe
An	An	an-T	Td-s
tUachtarán	tUachtarán	uachtarán-N	Ncmsc
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
ar	ar	ar-S	Sp
chúrsa	chúrsa	cúrsa-N	Ncmsc
Gaeilge	Gaeilge	Gaeilge-N	Npfsg
i	i	i-S	Sp
nGleann	nGleann	gleann-N	Ncmsc
Cholm	Cholm	Colm-N	Npmsg|Npm-g
Cille	Cille	cill-N	Ncfsg
.	.	.-F	Fe
Is	Is	is-W	Wp-i
breá	breá	breá-A	Aqp
leis	leis	le-S	Sp
an	an	an-T	Td-s
Uachtarán	Uachtarán	uachtarán-N	Ncmsc
Máire	Máire	Máire-N	Npf-g|Npfsc
Mhic	Mhic	Mac-U	Up
Ghiolla	Ghiolla	Giolla-N	Npfsg
Íosa	Íosa	Íosa-N	Ncmsg|Np|Npm-g|Ncmsc|Npmsg|Npmsc
cuairt	cuairt	cuairt-N	Ncfsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
ar	ar	ar-S	Sp
scoileanna	scoileanna	scoil-N	Ncfpc
ar fud	ar fud	ar_fud-S	Spc
na	na	na-T	Tdfsg
hÉireann	hÉireann	Éire-N	Npfsg
.	.	.-F	Fe
Cuireann	Cuireann	cuir-V	Vmip
díograis	díograis	díograis-N	Ncfsc
agus	agus	agus-C	Cc
cineáltas	cineáltas	cineáltas-N	Ncmsc
na	na	na-T	Td-p
ndaltaí	ndaltaí	dalta-N	Ncmpg
áthas	áthas	áthas-N	Ncmpg|Ncmsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
croí	croí	croí-N	Ncmsc
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
.	.	.-F	Fe
