Bhí	Bhí	bí-V	Vmis
fear	fear	fear-N	Ncmsc
ann	ann	i-P	Pr3ms
fadó	fadó	fadó-R	Rg
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
Páidín	Páidín	Páidín-N	Npmsc
Mháire	Mháire	Máire-N	Npf-g
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Thaitníodh	Thaitníodh	taitin-V	Vmih
le	le	le-S	Sp
Páidín	Páidín	Páidín-N	Npmsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
éisteacht	éisteacht	éist-N	Nv
le	le	le-S	Sp
ceol	ceol	ceol-N	Nv-----n
agus	agus	agus-C	Cc
go	go	go-U	Ua
deimhin	deimhin	deimhin-A	Aqp
bhíodh	bhíodh	bí-V	Vmih
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
casadh	casadh	cas-N	Nv
na	na	na-T	Tdfsg
píbe	píbe	píb-N	Ncfsg
é	é	é-P	Pp3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
mo	mo	mo-D	Dp1-s
léan	léan	léan-N	Ncmsc
!	!	!-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ag	ag	ag-S	Sp
Páidín	Páidín	Páidín-N	Npmsc
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
t-aon	t-aon	aon-M	Mc
phort	phort	port-N	Ncmsc
amháin	amháin	amháin-A	Aqp
–	–	–-X	Xx
‘	‘	‘-X	Xx
An	An	an-T	Td-s
Rógaire	Rógaire	rógaire-N	Ncmsc
Dubh	Dubh	dubh-A	Aq-msc
’	’	’-F	Fa
.	.	.-F	Fe
Oíche	Oíche	oíche-N	Ncfsc
amháin	amháin	amháin-A	Aqp
agus	agus	agus-C	Cc
Páidín	Páidín	Páidín-N	Npm-g|Npmsg|Npmsc
Mháire	Mháire	Máire-N	Npf-g
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
abhaile	abhaile	abhaile-R	Rd
deireanach	deireanach	deireanach-A	Aqp
bhuail	bhuail	buail-V	Vmis
fonn	fonn	fonn-N	Ncmsc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
é	é	é-P	Pp3ms
.	.	.-F	Fe
Shuigh	Shuigh	suigh-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
chlaí	chlaí	claí-N	Ncmsc
beag	beag	beag-A	Aq-msc
íseal	íseal	íseal-A	Aq-msc
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
casadh	casadh	cas-N	Nv
‘	‘	‘-X	Xx
An	An	an-T	Td-s
Rógaire	Rógaire	rógaire-N	Ncmsc
Dubh	Dubh	dubh-A	Aq-msc
’	’	’-F	Fa
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
scaithimh	scaithimh	scaitheamh-N	Ncmsg
d	d	d-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmm-2s
Páidín	Páidín	Páidín-N	Npmsc
tuirseach	tuirseach	tuirseach-A	Aq-msc
den	den	de-S	Spa-s
cheol	cheol	ceol-N	Ncmsc
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
sé	sé	sé-P	Pp3msn
faoin	faoin	faoi-S	Spa-s
mbaile	mbaile	baile-N	Ncmsc
arís	arís	arís-R	Rg
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
sé	sé	sé-P	Pp3msn
chomh	chomh	chomh-R	Ri
fada	fada	fada-A	Aqp
leis	leis	le-S	Sp
an	an	an-T	Td-s
droichead	droichead	droichead-N	Ncmsc
beag	beag	beag-A	Aq-msc
bhraith	bhraith	braith-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
duine	duine	duine-N	Ncmsc
éicint	éicint	éicint-A	Aq-msc
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
taobh	taobh	taobh-N	Ncmsc
thiar	thiar	thiar-R	Rd
de	de	de-P	Pr3ms
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
iompaigh	iompaigh	iompaigh-V	Vmis
sé	sé	sé-P	Pp3msn
timpeall	timpeall	timpeall-R	Rd|Ncmsc
agus	agus	agus-C	Cc
cé	cé	cé-P	Pq
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fheicfeadh	fheicfeadh	feic-V	Vmc
sé	sé	sé-P	Pp3msn
ach	ach	ach-S	Sp
Púca	Púca	púca-N	Ncmsc
na	na	na-T	Tdfsg
Samhna	Samhna	Samhain-N	Ncfsg
.	.	.-F	Fe
Rug	Rug	beir-V	Vmis
an	an	an-T	Td-s
Púca	Púca	púca-N	Ncmsc
ar	ar	ar-S	Sp
Pháidín	Pháidín	Páidín-N	Npmsc
agus	agus	agus-C	Cc
chaith	chaith	caith-V	Vmis
sé	sé	sé-P	Pp3msn
suas	suas	suas-R	Rd
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
dhroim	dhroim	droim-N	Ncmsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
faitíos	faitíos	faitíos-N	Ncmsc
a	a	a-D	Dp3
chroí	chroí	croí-N	Ncmsc
ar	ar	ar-S	Sp
Pháidín	Pháidín	Páidín-N	Npmsc
go	go	go-Q	Q
dtitfeadh	dtitfeadh	tit-V	Vmc
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Rug	Rug	beir-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
adharc	adharc	adharc-N	Ncfsc
an	an	an-T	Td-s
Phúca	Phúca	púca-N	Ncmsg
agus	agus	agus-C	Cc
choinnigh	choinnigh	coinnigh-V	Vmis
sé	sé	sé-P	Pp3msn
greim	greim	greim-N	Ncmsc
daingean	daingean	daingean-A	Aq-msc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Lig	Lig	lig-V	Vmis
anuas	anuas	anuas-R	Rd
mé	mé	mé-P	Pp1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Páidín	Páidín	Páidín-N	Npmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
bPúca	bPúca	púca-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
abhaile	abhaile	abhaile-R	Rd
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
mo	mo	mo-D	Dp1-s
mháthair	mháthair	máthair-N	Ncfsc
ag	ag	ag-S	Sp
fanacht	fanacht	fan-N	Nv
leis	leis	le-S	Sp
an	an	an-T	Td-s
airgead	airgead	airgead-N	Ncmsc
seo	seo	seo-D	Dd
atá	atá	bí-V	Vmip---r
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
phóca	phóca	póca-N	Ncmsc
agam	agam	ag-P	Pr1-s
di	di	do-P	Pr3fs
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
bac	bac	bac-V	Vmm-2s-n
do	do	do-S	Sp
mháthair	mháthair	máthair-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Púca	Púca	púca-N	Ncmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
ach	ach	ach-C	Cs
coinnigh	coinnigh	coinnigh-V	Vmm-2s
do	do	do-S	Sp
ghreim	ghreim	greim-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Anois	Anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Púca	Púca	púca-N	Ncmsc
le	le	le-S	Sp
Páidín	Páidín	Páidín-N	Npmsc
tar éis	tar éis	tar_éis-S	Spc
scaithimh	scaithimh	scaitheamh-N	Ncmsg
,	,	,-F	Fi
‘	‘	‘-X	Xx
casfaidh	casfaidh	cas-V	Vmif
tú	tú	tú-P	Pp2-s
port	port	port-N	Ncmsc
dom	dom	do-P	Pr1-s
–	–	–-X	Xx
“	“	“-F	Fa
An	An	an-T	Td-s
tSeanbhean	tSeanbhean	bean-N	Ncfsc
Bhocht	Bhocht	bocht-A	Aq-fsc
”	”	”-F	Fa
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
an	an	an-T	Td-s
ceann	ceann	ceann-N	Ncmsc
sin	sin	sin-D	Dd
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Páidín	Páidín	Páidín-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
agam	agam	ag-P	Pr1-s
ach	ach	ach-S	Sp|Cs
“	“	“-F	Fa
An	An	an-T	Td-s
Rógaire	Rógaire	rógaire-N	Ncmsc
Dubh	Dubh	dubh-A	Aq-msc
”	”	”-F	Fa
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
cuma	cuma	cuma-A	Aqp
liom	liom	le-P	Pr1-s
an	an	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
sé	sé	sé-P	Pp3msn
agat	agat	ag-P	Pr2-s
nó	nó	nó-C	Cc
nach	nach	nach-Q	Qnr
bhfuil	bhfuil	bí-V	Vmip---n
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Púca	Púca	púca-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cas	Cas	Cas-N	Npmsc
é	é	é-P	Pp3ms
!	!	!-F	Fe
’	’	’-F	Fa
Thosaigh	Thosaigh	tosaigh-V	Vmis
Páidín	Páidín	Páidín-N	Npmsc
ag	ag	ag-S	Sp
casadh	casadh	cas-N	Nv
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
an	an	an-T	Td-s
ceol	ceol	ceol-N	Ncmsc
breá	breá	breá-A	Aq-msc
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
as	as	as-S	Sp
an	an	an-T	Td-s
bpíb	bpíb	píb-N	Ncfsc
iontas	iontas	iontas-N	Ncmpg|Ncmsc
ar	ar	ar-S	Sp
Pháidín	Pháidín	Páidín-N	Npmsc
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
tú	tú	tú-P	Pp2-s
an	an	an-T	Td-s
píobaire	píobaire	píobaire-N	Ncmsc
is	is	is-U	U
fearr	fearr	maith-A	Aqc
in	in	i-S	Sp
Éirinn	Éirinn	Éire-N	Npfsd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Púca	Púca	púca-N	Ncmsc
na	na	na-T	Tdfsg
Samhna	Samhna	Samhain-N	Ncfsg
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
scaithimh	scaithimh	scaitheamh-N	Ncmsg
stop	stop	stop-N	Ncmsg|Ncmsc|Ncmsg
Páidín	Páidín	Páidín-N	Npm-g|Npmsg|Npmsc
ag	ag	ag-S	Sp
casadh	casadh	cas-N	Nv
gur	gur	gur-Q	Q--s
cheistigh	cheistigh	ceistigh-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
Púca	Púca	púca-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Inis	Inis	inis-V	Vmis
seo	seo	seo-P	Pd
dom	dom	do-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
muid	muid	muid-P	Pp1-p
ag	ag	ag-S	Sp
gabháil	gabháil	gabh-N	Nv
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
féasta	féasta	féasta-N	Ncmsc
ag	ag	ag-S	Sp
na	na	na-T	Td-p
cailleacha	cailleacha	caille-N	Ncfpc
ar	ar	ar-S	Sp
bharr	bharr	barr-N	Ncmsc
Chruach	Chruach	cruach-N	Ncfsg|Ncfpg
Phádraig	Phádraig	Pádraig-N	Npm-g|Npfsg
anocht	anocht	anocht-N	Ns-s|Rt
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
do	do	do-D	Dp2-s|Sp
do	do	do-S	Sp
thabhairt	thabhairt	tabhairt-N	Ncfsc
ann	ann	i-R	Rl|Pr3ms
le	le	le-S	Sp
go	go	go-Q	Q
gcasfaidh	gcasfaidh	cas-V	Vmif
tú	tú	tú-P	Pp2-s
ceol	ceol	ceol-N	Ncmsc|Nv-----n
ag	ag	ag-S	Sp
an	an	an-T	Td-s
bhféasta	bhféasta	féasta-N	Ncmsc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
geallaimse	geallaimse	geall-V	Vmip1s--e
duit	duit	do-P	Pr2-s
gur	gur	is-W	Wsdi|Wpdi
breá	breá	breá-A	Aqp
an	an	an-T	Td-s
luach	luach	luach-N	Ncmsc
saothair	saothair	saothar-N	Ncmsg|Ncmpc
a	a	a-Q	Q-r
bheas	bheas	bí-V	Vmif---r
agat	agat	ag-P	Pr2-s
dá	dá	do-S	Spp-s
bharr	bharr	barr-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Más	Más	má-N	Ncmsc|Csw
in	in	sin-P	Pd
é	é	é-P	Pp3ms
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
é	é	é-P	Pp3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Páidín	Páidín	Páidín-N	Npmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
tá	tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
spáráil	spáráil	spáráil-N	Nv
turais	turais	turas-N	Ncmsg
dom	dom	do-P	Pr1-s
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
iarr	iarr	iarr-V	Vmm-2s
an	an	an-T	Td-s
sagart	sagart	sagart-N	Ncmsc
orm	orm	ar-P	Pr1-s
turas	turas	turas-N	Ncmsc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
go	go	go-S	Sp
Cruach	Cruach	cruach-N	Ncfsc
Phádraig	Phádraig	Pádraig-N	Npm-g|Npfsg
mar	mar	mar-S	Sp
gheall	gheall	geall-N	Ncmsc
ar	ar	ar-S	Sp
ghandal	ghandal	gandal-N	Ncmsc
bán	bán	bán-A	Aq-msc
a	a	a-Q	Q-r
ghoid	ghoid	goid-V	Vmis
mé	mé	mé-P	Pp1-s
uaidh	uaidh	ó-P	Pr3ms
an	an	an-T	Td-s
Nollaig	Nollaig	Nollaig-N	Ncfsc
seo	seo	seo-D	Dd
caite	caite	caith-A	Av
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Is	Is	agus-C	Cc
maith	maith	maith-V	Vmm-2s
sin	sin	sin-P	Pd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Púca	Púca	púca-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Féadfaidh	Féadfaidh	féad-V	Vmif
tú	tú	tú-P	Pp2-s
an	an	an-T	Td-s
dá	dá	dó-M	Mc
thrá	thrá	trá-N	Ncfsc
a	a	a-U	U
fhreastal	fhreastal	freastail-N	Nv
.	.	.-F	Fe
’	’	’-F	Fa
Ar	Ar	ar-S	Sp|Ncmsc|Wssi|Wpdi|Wpsi|Q-is
deireadh	deireadh	deireadh-V	Vmih|Ncmsc
thiar	thiar	thiar-R	Rd
thall	thall	thall-R	Rd
shroicheadar	shroicheadar	sroich-V	Vmis3p
barr	barr	barr-N	Ncmsc
Chruach	Chruach	cruach-N	Ncfsg|Ncfpg
Phádraig	Phádraig	Pádraig-N	Npm-g|Npfsg
.	.	.-F	Fe
Bhuail	Bhuail	buail-V	Vmis
an	an	an-T	Td-s
Púca	Púca	púca-N	Ncmsc
trí	trí	trí-M	Mc|Sp
chic	chic	cic-N	Ncfsc|Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
talamh	talamh	talamh-N	Ncfsc
lena	lena	le-S	Spp-s
chos	chos	cos-N	Ncfsc
.	.	.-F	Fe
Osclaíodh	Osclaíodh	oscail-V	Vmm-3s|Vmih
doras	doras	doras-N	Ncmsc
agus	agus	agus-C	Cc
isteach	isteach	isteach-R	Rd
leo	leo	le-P	Pr3-p
beirt	beirt	beirt-N	Ncfsc
i	i	i-S	Sp
seomra	seomra	seomra-N	Ncmsc
breá	breá	breá-A	Aq-msc
.	.	.-F	Fe
I	I	i-S	Sp
lár	lár	lár-N	Ncmsc
an	an	an-T	Td-s
urláir	urláir	urlár-N	Ncmsg
bhí	bhí	bí-V	Vmis
bord	bord	bord-N	Ncmsc
órga	órga	órga-A	Aqp
agus	agus	agus-C	Cc
na	na	na-T	Td-p
céadta	céadta	céad-N	Ncmpc
cailleach	cailleach	cailleach-N	Ncfpg|Ncfsc
ina	ina	i-S	Spp-p|Spp-s
suí	suí	suí-N	Ncmsc
thart	thart	thart-R	Rd
air	air	ar-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Céad	Céad	céad-M	Mc
míle	míle	míle-M	Mc
fáilte	fáilte	fáilte-N	Ncfsc
romhat	romhat	roimh-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Phúca	Phúca	púca-N	Ncmsv
na	na	na-T	Tdfsg
Samhna	Samhna	Samhain-N	Ncfsg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
cailleach	cailleach	cailleach-N	Ncfsc
amháin	amháin	amháin-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
cé	cé	cé-W	W--q
hé	hé	é-P	Pp3ms
seo	seo	seo-P	Pd
a	a	a-Q	Q-r
thug	thug	tabhair-V	Vmis
tú	tú	tú-P	Pp2-s
leat	leat	le-P	Pr2-s
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
é	é	é-P	Pp3ms
Páidín	Páidín	Páidín-N	Npmsc
Mháire	Mháire	Máire-N	Npf-g
,	,	,-F	Fi
an	an	an-T	Td-s
píobaire	píobaire	píobaire-N	Ncmsg|Ncmsc
is	is	is-U	U
fearr	fearr	maith-A	Aqc
in	in	i-S	Sp
Éirinn	Éirinn	Éire-N	Npfsd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Púca	Púca	púca-N	Ncmsc
.	.	.-F	Fe
Bhuail	Bhuail	buail-V	Vmis
an	an	an-T	Td-s
tseanchailleach	tseanchailleach	seanchailleach-N	Ncfsc
buille	buille	buille-N	Ncmsg|Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
urlár	urlár	urlár-N	Ncmsc
agus	agus	agus-C	Cc
leis	leis	le-S	Sp
sin	sin	sin-P	Pd
nár	nár	nár-Q	Qnrs
oscail	oscail	oscail-V	Vmis---n
doras	doras	doras-N	Ncmsc
beag	beag	beag-A	Aq-msc
ar	ar	ar-S	Sp
thaobh	thaobh	taobh-N	Ncmsc
an	an	an-T	Td-s
bhalla	bhalla	balla-N	Ncmsg
!	!	!-F	Fe
Cé	Cé	cé-C	Cs
a	a	a-Q	Q-r
thiocfadh	thiocfadh	tar-V	Vmc
amach	amach	amach-R	Rd
as	as	as-P	Pr3ms
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
gandal	gandal	gandal-N	Ncmsc
bán	bán	bán-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
goidte	goidte	goid-A	Av
ag	ag	ag-S	Sp
Páidín	Páidín	Páidín-N	Npmsc
ón	ón	ó-S	Spa-s
sagart	sagart	sagart-N	Ncmsc
an	an	an-T	Td-s
Nollaig	Nollaig	Nollaig-N	Ncfsc
roimhe	roimhe	roimh-P	Pr3ms
sin	sin	sin-P	Pd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
é	é	é-P	Pp3ms
seo	seo	seo-P	Pd
?	?	?-F	Fq
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
brionglóideach	brionglóideach	brionglóideach-N	Ncfsc
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Páidín	Páidín	Páidín-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nár	Nár	nár-Q	Qnrs
ith	ith	ith-V	Vmis---n
mé	mé	mé-P	Pp1-s
féin	féin	féin-P	Px
is	is	agus-C	Cc
mo	mo	mo-D	Dp1-s
mháthair	mháthair	máthair-N	Ncfsc
an	an	an-T	Td-s
gandal	gandal	gandal-N	Ncmsc
sin	sin	sin-D	Dd
Lá	Lá	lá-N	Ncmsc
Nollag	Nollag	Nollaig-N	Ncfsg
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Cas	Cas	Cas-N	Npmsc
cúpla	cúpla	cúpla-N	Ncmsg|Ncmsc|Dq
port	port	port-N	Ncmpg|Ncmsc
do	do	do-S	Sp
na	na	na-T	Td-p
mná	mná	bean-N	Ncfpc
seo	seo	seo-D	Dd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Púca	Púca	púca-N	Ncmsc
le	le	le-S	Sp
Páidín	Páidín	Páidín-N	Npmsc
ansin	ansin	ansin-R	Rt|Rl
.	.	.-F	Fe
Chas	Chas	Cas-N	Npfsg
Páidín	Páidín	Páidín-N	Npm-g|Npmsg|Npmsc
port	port	port-N	Ncmpg|Ncmsc
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosach-V	Vmis|Ncmsg
na	na	na-T	Td-p
cailleacha	cailleacha	cailleach-N	Ncfpc
ag	ag	ag-S	Sp
damhsa	damhsa	damhsaigh-N	Nv
.	.	.-F	Fe
Dhamhsaigh	Dhamhsaigh	damhsaigh-V	Vmis
siad	siad	siad-P	Pp3-pn
agus	agus	agus-C	Cc
dhamhsaigh	dhamhsaigh	damhsaigh-V	Vmis
siad	siad	siad-P	Pp3-pn
go	go	go-Q	Q
rabhadar	rabhadar	bí-V	Vmis3p-d
maraithe	maraithe	maraigh-A	Av
leis	leis	le-S	Sp
an	an	an-T	Td-s
tuirse	tuirse	tuirse-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Íocaigí	Íocaigí	íoc-V	Vmm-2p
an	an	an-T	Td-s
píobaire	píobaire	píobaire-N	Ncmsc
anois	anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Púca	Púca	púca-N	Ncmsc
agus	agus	agus-C	Cc
shín	shín	sín-V	Vmis
na	na	na-T	Td-p
cailleacha	cailleacha	cailleach-N	Ncfpc
píosa	píosa	píosa-N	Ncmsg|Ncmsc
óir	óir	óir-C	Cs
an	an	is-W	Wpdq|Wp-q
duine	duine	duine-N	Ncmsc
chuig	chuig	chuig-S	Sp
Páidín	Páidín	Páidín-N	Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
dhá	dhá	dó-M	Mc
chroí	chroí	croí-N	Ncmsc
ag	ag	ag-S	Sp
Páidín	Páidín	Páidín-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
saibhir	saibhir	saibhir-A	Aqp
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
agus	agus	agus-C	Cc
ríméad	ríméad	ríméad-N	Ncmsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Fág	Fág	fág-N	Ncmsc
seo	seo	seo-P	Pd|Dd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Púca	Púca	púca-N	Ncmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
chuile	chuile	gach-D	Dq
phíosa	phíosa	píosa-N	Ncmsc
óir	óir	ór-N	Ncmsg
ina	ina	i-S	Spp-s
phóca	phóca	póca-N	Ncmsc
ag	ag	ag-S	Sp
Páidín	Páidín	Páidín-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tabharfaidh	Tabharfaidh	tabhair-V	Vmif
mé	mé	mé-P	Pp1-s
abhaile	abhaile	abhaile-R	Rd
thú	thú	tú-P	Pp2-s
.	.	.-F	Fe
’	’	’-F	Fa
Agus	Agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
ag	ag	ag-S	Sp
réiteach	réiteach	réitigh-N	Nv
le	le	le-S	Sp
himeacht	himeacht	imigh-N	Nv
cé	cé	cé-C	Cs
a	a	a-Q	Q-r
thiocfadh	thiocfadh	tar-V	Vmc
anall	anall	anall-R	Rd
chucu	chucu	chuig-P	Pr3-p
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
gandal	gandal	gandal-N	Ncmsc
.	.	.-F	Fe
Shín	Shín	Sín-N	Npfsc
an	an	an-T	Td-s
gandal	gandal	gandal-N	Ncmsc
píb	píb	píb-N	Ncfsc
nua	nua	nua-A	Aqp
chuig	chuig	chuig-S	Sp
Páidín	Páidín	Páidín-N	Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
dhá	dhá	dó-M	Mc
chroí	chroí	croí-N	Ncmsc
ag	ag	ag-S	Sp
Páidín	Páidín	Páidín-N	Npmsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
chaith	chaith	caith-V	Vmis
an	an	an-T	Td-s
Púca	Púca	púca-N	Ncmsc
Páidín	Páidín	Páidín-N	Npm-g|Npmsg|Npmsc
Mháire	Mháire	Máire-N	Npf-g
suas	suas	suas-R	Rd
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
dhroim	dhroim	droim-N	Ncmsc
arís	arís	arís-R	Rg
agus	agus	agus-C	Cc
thugadar	thugadar	tabhair-V	Vmis3p
aghaidh	aghaidh	aghaidh-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbaile	mbaile	baile-N	Ncmsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
an	an	an-T	Td-s
droichead	droichead	droichead-N	Ncmsc
beag	beag	beag-A	Aq-msc
cóngarach	cóngarach	cóngarach-A	Aq-msc
do	do	do-S	Sp
bhaile	bhaile	baile-N	Ncmsc
Pháidín	Pháidín	Páidín-N	Npm-g|Npfsg
chaith	chaith	caith-V	Vmis
an	an	an-T	Td-s
Púca	Púca	púca-N	Ncmsc
an	an	an-T	Td-s
píobaire	píobaire	píobaire-N	Ncmsg|Ncmsc
anuas	anuas	anuas-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
talamh	talamh	talamh-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
dhá	dhá	dó-M	Mc
rud	rud	rud-N	Ncmsc
agat	agat	ag-P	Pr2-s
anois	anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Púca	Púca	púca-N	Ncmsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Dhá	Dhá	do-S	Spp
rud	rud	rud-N	Ncmsc
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
agat	agat	ag-P	Pr2-s
cheana	cheana	cheana-R	Rg
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
céard	céard	cé-W	W--q
iad	iad	iad-P	Pp3-p
sin	sin	sin-W	W
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Páidín	Páidín	Páidín-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ciall	Ciall	ciall-N	Ncfsc
agus	agus	agus-C	Cc
ceol	ceol	ceol-N	Ncmsc|Nv-----n
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Púca	Púca	púca-N	Ncmsc
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
le	le	le-S	Sp
Páidín	Páidín	Páidín-N	Npmsc
chuig	chuig	chuig-S	Sp
a	a	a-D	Dp3
mháthair	mháthair	máthair-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nach	Nach	is-C	Cs|Wpdin|Wpsin
deireanach	deireanach	deireanach-A	Aqp
atá	atá	bí-V	Vmip---r
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
abhaile	abhaile	abhaile-R	Rd
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
a	a	a-Q	Q-r
tharla	tharla	tarlaigh-V	Vmis
duit	duit	do-P	Pr2-s
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
saibhir	saibhir	saibhir-A	Aqp
agus	agus	agus-C	Cc
is	is	is-W	Wpri
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
píobaire	píobaire	píobaire-N	Ncmsc
is	is	is-U	U
fearr	fearr	maith-A	Aqc
in	in	i-S	Sp
Éirinn	Éirinn	Éire-N	Npfsd
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
chreid	chreid	creid-V	Vmis---n
a	a	a-D	Dp3
mháthair	mháthair	máthair-N	Ncfsc
focal	focal	focal-N	Ncmpg|Ncmsc
uaidh	uaidh	ó-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Fan	Fan	fan-V	Vmm-2s
go	go	go-Q	Q-s
gcloise	gcloise	clois-V	Vmsp
tú	tú	tú-P	Pp2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
píobaire	píobaire	píobaire-N	Ncmsc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
fháisc	fháisc	fáisc-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bpíb	bpíb	píb-N	Ncfsc
nua	nua	nua-A	Aqp
a	a	a-Q	Q-r
thug	thug	tabhair-V	Vmis
an	an	an-T	Td-s
gandal	gandal	gandal-N	Ncmsc
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
mo	mo	mo-D	Dp1-s
léan	léan	léan-N	Ncmsc
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
ceol	ceol	ceol-N	Ncmsc
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
as	as	as-S	Sp
an	an	an-T	Td-s
bpíb	bpíb	píb-N	Ncfsc
chomh	chomh	chomh-R	Ri
dona	dona	dona-A	Aqp
sin	sin	sin-P	Pd|W|Dd
is	is	agus-C	Cc
go	go	go-Q	Q
gceapfá	gceapfá	ceap-V	Vmc-2s
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
chuile	chuile	gach-D	Dq
ghé	ghé	gé-N	Ncfsc
agus	agus	agus-C	Cc
chuile	chuile	cuile-N	Ncfsg
ghandal	ghandal	gandal-N	Ncmpg
in	in	i-S	Sp
Éirinn	Éirinn	Éire-N	Npfsd
ag	ag	ag-S	Sp
scréachaíl	scréachaíl	scréachaíl-N	Ncfsc
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Dhúisigh	Dhúisigh	dúisigh-V	Vmis
sé	sé	sé-P	Pp3msn
na	na	na-T	Tdfsg
comharsain	comharsain	comharsain-N	Ncfsc
uileag	uileag	uileag-N	Ncmsc
agus	agus	agus-C	Cc
bhuaileadar	bhuaileadar	buail-V	Vmis3p
isteach	isteach	isteach-R	Rd
.	.	.-F	Fe
Bhíodar	Bhíodar	bí-V	Vmis3p
ag	ag	ag-S	Sp
magadh	magadh	magadh-N	Nv-----n
faoi	faoi	faoi-S	Sp
Pháidín	Pháidín	Páidín-N	Npmsc
agus	agus	agus-C	Cc
faoina	faoina	faoi-S	Spp-s
chuid	chuid	cuid-N	Ncfsc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ansin	ansin	ansin-R	Rt|Rl
leag	leag	leag-V	Vmis
Páidín	Páidín	Páidín-N	Npmsc
uaidh	uaidh	ó-P	Pr3ms
an	an	an-T	Td-s
phíb	phíb	píb-N	Ncfsc
nua	nua	nua-A	Aqp
agus	agus	agus-C	Cc
thóg	thóg	tóg-V	Vmis
sé	sé	sé-P	Pp3msn
amach	amach	amach-R	Rd
a	a	a-D	Dp3
sheanphíb	sheanphíb	píb-N	Ncfsc
.	.	.-F	Fe
Chas	Chas	Cas-N	Npfsg
sé	sé	sé-W	Wp-i-3|Pp3msn
ceol	ceol	ceol-N	Ncmsc
binn	binn	binn-A	Aq-msc
dóibh	dóibh	do-P	Pr3-p
leis	leis	le-S	Sp
an	an	an-T	Td-s
tseanphíb	tseanphíb	píb-N	Ncfsc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
inis	inis	inis-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
dóibh	dóibh	do-P	Pr3-p
ó	ó	ó-S	Sp
thús	thús	tús-N	Ncmsc
deireadh	deireadh	abair-V	Vmih
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuaigh	chuaigh	téigh-V	Vmis
máthair	máthair	máthair-N	Ncfsc
Pháidín	Pháidín	Páidín-N	Npmsc
ag	ag	ag-S	Sp
tóraíocht	tóraíocht	tóraigh-N	Nv
na	na	na-T	Td-p
bpíosaí	bpíosaí	píosa-N	Ncmpg
óir	óir	óir-C	Cs
ar	ar	is-W	Wpdi|Wpsi|Wssi
maidin	maidin	maidin-N	Ncfsc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
dé	dé	dé-N	Ncfsc
orthu	orthu	ar-P	Pr3-p
.	.	.-F	Fe
Duilleoga	Duilleoga	duilleog-N	Ncfpc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
fágtha	fágtha	fág-A	Av
san	san	i-S	Spa-s
áit	áit	áit-N	Ncfsc
a	a	a-Q	Q-i
rabhadar	rabhadar	bí-V	Vmis3p-d
ann	ann	i-P	Pr3ms
an	an	an-T	Td-s
oíche	oíche	oíche-N	Ncfsc
roimhe	roimhe	roimh-P	Pr3ms
sin	sin	sin-P	Pd
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
Páidín	Páidín	Páidín-N	Npmsc
chuig	chuig	chuig-S	Sp
an	an	an-T	Td-s
sagart	sagart	sagart-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
a	a	a-U	U
inseacht	inseacht	inis-N	Nv
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
chreid	chreid	creid-V	Vmis---n
an	an	an-T	Td-s
sagart	sagart	sagart-N	Ncmsc
focal	focal	focal-N	Ncmpg|Ncmsc
uaidh	uaidh	ó-P	Pr3ms
gur	gur	gur-Q	Q--s
chas	chas	cas-V	Vmis
an	an	an-T	Td-s
píobaire	píobaire	píobaire-N	Ncmsc
an	an	an-T	Td-s
phíb	phíb	píb-N	Ncfsc
nua	nua	nua-A	Aqp
leis	leis	le-S	Sp
an	an	an-T	Td-s
gceol	gceol	ceol-N	Ncmsc
uafásach	uafásach	uafásach-A	Aq-msc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bailigh	Bailigh	bailigh-V	Vmm-2s
leat	leat	le-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
ghadaí	ghadaí	gadaí-N	Ncmsv
chríochnaithe	chríochnaithe	críochnaithe-A	Av|Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
sagart	sagart	sagart-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
ceol	ceol	ceol-N	Ncmsc
sin	sin	sin-D	Dd
chomh	chomh	chomh-R	Ri
dona	dona	dona-A	Aqp
is	is	agus-C	Cc
go	go	go-Q	Q
gceapfá	gceapfá	ceap-V	Vmc-2s
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
chuile	chuile	gach-D	Dq
ghé	ghé	gé-N	Ncfsc
agus	agus	agus-C	Cc
chuile	chuile	cuile-N	Ncfsg
ghandal	ghandal	gandal-N	Ncmpg
in	in	i-S	Sp
Éirinn	Éirinn	Éire-N	Npfsd
ag	ag	ag-S	Sp
scréachaíl	scréachaíl	scréachaíl-N	Ncfsc
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
Ach	Ach	ach-C	Cs
níor	níor	is-W	Ws-in
imigh	imigh	imigh-V	Vmm-2s
Páidín	Páidín	Páidín-N	Npmsc
nó	nó	nó-C	Cc
gur	gur	gur-Q	Q--s
chas	chas	cas-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
tseanphíb	tseanphíb	píb-N	Ncfsc
le	le	le-S	Sp
taispeáint	taispeáint	taispeáin-N	Nv
don	don	do-S	Spa-s
sagart	sagart	sagart-N	Ncmsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
a	a	a-D	Dp3
scéal	scéal	scéal-N	Ncmsc
fíor	fíor	fíor-A	Aq-msc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
sagart	sagart	sagart-N	Ncmsc
sásta	sásta	sásta-A	Aqp
leis	leis	le-P	Pr3ms
mar	mar	mar-S	Sp
scéal	scéal	scéal-N	Ncmsc
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmm-2s
Páidín	Páidín	Páidín-N	Npmsc
leis	leis	le-P	Pr3ms
abhaile	abhaile	abhaile-R	Rd
.	.	.-F	Fe
Choinnigh	Choinnigh	Coinnigh-N	Npfsg
Páidín	Páidín	Páidín-N	Npm-g|Npmsg|Npmsc
Mháire	Mháire	Máire-N	Npf-g
air	air	ar-N	Ncmsg|Pr3ms
ag	ag	ag-S	Sp
casadh	casadh	cas-N	Nv
ceol	ceol	ceol-N	Ncmsc
binn	binn	binn-A	Aq-msc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bpíb	bpíb	píb-N	Ncfsc
agus	agus	agus-C	Cc
as	as	as-S	Sp
sin	sin	sin-P	Pd
go	go	go-S	Sp
lá	lá	lá-N	Ncmsc
a	a	a-D	Dp3
bháis	bháis	bás-N	Ncmsg
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
píobaire	píobaire	píobaire-N	Ncmsc
ní	ní	ní-N	Ncmsg|Nv|Ncmsc
b	b	b-X	Xl
’	’	’-F	Fa
fhearr	fhearr	maith-A	Aqc
ná	ná	ná-C	Cc
é	é	é-P	Pp3ms
le	le	le-S	Sp
fáil	fáil	faigh-N	Nv
thoir	thoir	thoir-R	Rd
ná	ná	ná-C	Cc
thiar	thiar	thiar-R	Rd
.	.	.-F	Fe
Oíche	Oíche	oíche-N	Ncfsc
amháin	amháin	amháin-A	Aqp
agus	agus	agus-C	Cc
Páidín	Páidín	Páidín-N	Npm-g|Npmsg|Npmsc
Mháire	Mháire	Máire-N	Npf-g
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
abhaile	abhaile	abhaile-R	Rd
deireanach	deireanach	deireanach-A	Aqp
bhuail	bhuail	buail-V	Vmis
fonn	fonn	fonn-N	Ncmsc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
é	é	é-P	Pp3ms
…	…	…-F	Fi
