Oíche	Oíche	oíche-N	Ncfsc
chiúin	chiúin	ciúin-A	Aq-fsc
ghealaí	ghealaí	gealach-N	Ncfsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Learaí	Learaí	Learaí-N	Npmsc
Leipreachán	Leipreachán	leipreachán-N	Ncmsc|Ncmpg
ag	ag	ag-S	Sp
obair	obair	obair-N	Nv-----n
leis	leis	le-P	Pr3ms
go	go	go-U	Ua
sásta	sásta	sásta-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tic	Tic	tic-N	Ncmsc|Xfen
teaic	teaic	teaic-N	Ncfsc
tiú	tiú	tiú-A	Aq
,	,	,-F	Fi
péire	péire	péire-N	Ncmsc
bróga	bróga	bróg-N	Ncfpc
nua	nua	nua-A	Aqp
.	.	.-F	Fe
Cuirfidh	Cuirfidh	cuir-V	Vmif
mise	mise	mé-P	Pp1-s-e
an	an	an-T	Td-s
tairne	tairne	tairne-N	Ncmsc
agus	agus	agus-C	Cc
cuirfidh	cuirfidh	cuir-V	Vmif
tusa	tusa	tú-P	Pp2-s-e
an	an	an-T	Td-s
crú	crú	crú-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
Tar éis	Tar éis	tar_éis-S	Spc
scaithimh	scaithimh	scaitheamh-N	Ncmsg
bhuail	bhuail	buail-V	Vmis
tuirse	tuirse	tuirse-N	Ncfsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
tuirseach	tuirseach	tuirseach-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
An-tuirseach	An-tuirseach	tuirseach-A	Aqp
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
thar	thar	thar-S	Sp
am	am	am-N	Ncmsc
baile	baile	baile-N	Ncmsg
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
’	’	’-F	Fa
Bhailigh	Bhailigh	bailigh-V	Vmis
Learaí	Learaí	Learaí-N	Npmsc
na	na	na-T	Td-p
bróga	bróga	bróg-N	Ncfpc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
déanta	déanta	déan-A	Av
aige	aige	ag-P	Pr3ms
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
mhála	mhála	mála-N	Ncmsc
iad	iad	iad-P	Pp3-p
.	.	.-F	Fe
Bhailigh	Bhailigh	bailigh-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
chuid	chuid	cuid-N	Ncfsc
giuirléidí	giuirléidí	giuirléid-N	Ncfpg
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
mhála	mhála	mála-N	Ncmsc
iad	iad	iad-P	Pp3-p
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
chuir	chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
mála	mála	mála-N	Ncmsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
dhroim	dhroim	droim-N	Ncmsc
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
sé	sé	sé-P	Pp3msn
aghaidh	aghaidh	aghaidh-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbaile	mbaile	baile-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tic	Tic	tic-N	Ncmsc|Xfen
teaic	teaic	teaic-N	Ncfsc
tiú	tiú	tiú-A	Aq
,	,	,-F	Fi
péire	péire	péire-N	Ncmsc
bróga	bróga	bróg-N	Ncfpc
nua	nua	nua-A	Aqp
.	.	.-F	Fe
Cuirfidh	Cuirfidh	cuir-V	Vmif
mise	mise	mé-P	Pp1-s-e
an	an	an-T	Td-s
tairne	tairne	tairne-N	Ncmsc
agus	agus	agus-C	Cc
cuirfidh	cuirfidh	cuir-V	Vmif
tusa	tusa	tú-P	Pp2-s-e
an	an	an-T	Td-s
crú	crú	crú-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
Bhí	Bhí	bí-V	Vmis
Learaí	Learaí	Learaí-N	Npmsc
ar	ar	ar-S	Sp
a	a	a-D	Dp3
bhealach	bhealach	bealach-N	Ncmsc
abhaile	abhaile	abhaile-R	Rd
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
sé	sé	sé-P	Pp3msn
torann	torann	torann-N	Ncmsc
aisteach	aisteach	aisteach-A	Aq-msc
:	:	:-F	Fi
Hic	Hic	hic-X	Xfl
!	!	!-F	Fe
Hic	Hic	hic-X	Xfl
!	!	!-F	Fe
Hic	Hic	hic-X	Xfl
!	!	!-F	Fe
Baineadh	Baineadh	bain-V	Vmis0
geit	geit	geit-N	Ncfsc
as	as	as-S	Sp
Learaí	Learaí	Learaí-N	Npmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
torann	torann	torann-N	Ncmsc
mar	mar	mar-C	Cs|Sp
é	é	é-P	Pp3ms
cloiste	cloiste	clois-A	Av
riamh	riamh	riamh-R	Rg
cheana	cheana	cheana-R	Rg
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
é	é	é-P	Pp3ms
sin	sin	sin-W	W
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
agus	agus	agus-C	Cc
sheas	sheas	seas-V	Vmis
sé	sé	sé-P	Pp3msn
gan	gan	gan-S	Sp
cor	cor	cor-N	Ncmsc
as	as	as-N	Ncmpg
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
Learaí	Learaí	Learaí-N	Npmsc
cluas	cluas	cluas-N	Ncfsc
air	air	ar-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
Bhreathnaigh	Bhreathnaigh	breathnaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
thimpeall	thimpeall	timpeall-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
duine	duine	duine-N	Ncmsc
ná	ná	ná-C	Cc
deoraí	deoraí	deora-N	Ncmsc|Ncmsg|Ncfpg|Ncfpc
le	le	le-S	Sp
feiceáil	feiceáil	feic-N	Nv
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
chuala	chuala	clois-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
torann	torann	torann-N	Ncmsc
arís	arís	arís-R	Rg
:	:	:-F	Fi
Hic	Hic	hic-X	Xfl
!	!	!-F	Fe
Hic	Hic	hic-X	Xfl
!	!	!-F	Fe
Hic	Hic	hic-X	Xfl
!	!	!-F	Fe
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
é	é	é-P	Pp3ms
sin	sin	sin-W	W
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Learaí	Learaí	Learaí-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
torainn	torainn	torann-N	Ncmsg
mar	mar	mar-C	Cs
sin	sin	sin-W	W
?	?	?-F	Fq
’	’	’-F	Fa
Ach	Ach	ach-C	Cs
níorbh	níorbh	is-W	Ws-in
fhada	fhada	fada-A	Aqc|Aqp
gur	gur	gur-Q	Q--s
thuig	thuig	tuig-V	Vmip|Vmis
Learaí	Learaí	Learaí-N	Npmsc
gurbh	gurbh	is-W	Wsdi
as	as	as-P	Pr3ms
a	a	a-D	Dp3
bhéal	bhéal	béal-N	Ncmsc
féin	féin	féin-P	Px
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
torann	torann	torann-N	Ncmsc
aisteach	aisteach	aisteach-A	Aq-msc
seo	seo	seo-D	Dd
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
mo	mo	mo-D	Dp1-s
bhéal	bhéal	béal-N	Ncmsc
a	a	a-U	U
dhúnadh	dhúnadh	dún-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
ansin	ansin	ansin-R	Rt|Rl
stopfaidh	stopfaidh	stop-V	Vmif
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
’	’	’-F	Fa
Dhún	Dhún	dún-V	Vmis
Learaí	Learaí	Learaí-N	Npmsc
a	a	a-D	Dp3
bhéal	bhéal	béal-N	Ncmsc
ach	ach	ach-C	Cs
…	…	…-F	Fi
níor	níor	níor-W	Ws-in|Qn-s
stop	stop	stop-V	Vmis|Vmis---n|Ncmsc
an	an	an-T	Td-s
torann	torann	torann-N	Ncmsc
.	.	.-F	Fe
Léim	Léim	léim-V	Vmip1s|Vmis
Learaí	Learaí	Learaí-N	Npmsc
suas	suas	suas-R	Rd
agus	agus	agus-C	Cc
anuas	anuas	anuas-R	Rd
.	.	.-F	Fe
Rith	Rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
soir	soir	sor-A	Aqp|Rd|Ncmpc
agus	agus	agus-C	Cc
rith	rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
siar	siar	siar-R	Rd
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
mar	mar	mar-C	Cs
sin	sin	sin-W	W
féin	féin	féin-P	Px
…	…	…-F	Fi
níor	níor	níor-Q	Qn-s
stop	stop	stop-V	Vmis---n
an	an	an-T	Td-s
torann	torann	torann-N	Ncmsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
nár	nár	is-W	Wsdin
stop	stop	stop-N	Ncmsc
an	an	an-T	Td-s
torann	torann	torann-N	Ncmsc
bhuail	bhuail	buail-V	Vmis
faitíos	faitíos	faitíos-N	Ncmsc
Learaí	Learaí	Learaí-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
ceapadh	ceapadh	ceap-N	Nv
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
galar	galar	galar-N	Ncmsc
éicint	éicint	éicint-A	Aq-msc
orm	orm	ar-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
chuig	chuig	chuig-S	Sp
an	an	an-T	Td-s
dochtúir	dochtúir	dochtúir-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
Bhreathnaigh	Bhreathnaigh	breathnaigh-V	Vmis
Fionnán	Fionnán	Fionnán-N	Npmsc
Frog	Frog	frog-N	Ncmsc|Xfen
amach	amach	amach-R	Rd
agus	agus	agus-C	Cc
chonaic	chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
chara	chara	cara-N	Ncmsc
Learaí	Learaí	Learaí-N	Npmsc
ag	ag	ag-S	Sp
gabháil	gabháil	gabh-N	Nv
síos	síos	síos-R	Rd
an	an	an-T	Td-s
bóthar	bóthar	bóthar-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Heileó	Heileó	Heileó-N	Npmsc
,	,	,-F	Fi
a	a	a-U	Uv
Learaí	Learaí	Learaí-N	Npmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Fionnán	Fionnán	Fionnán-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cén	Cén	cé-D	Dw--s
chaoi	chaoi	caoi-N	Ncfsc
a	a	a-Q	Q-i
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Hic	Hic	hic-X	Xfl
!	!	!-F	Fe
Hic	Hic	hic-X	Xfl
!	!	!-F	Fe
Hic	Hic	hic-X	Xfl
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Learaí	Learaí	Learaí-N	Npmsc
.	.	.-F	Fe
Scairt	Scairt	scairt-V	Vmis
Fionnán	Fionnán	Fionnán-N	Npmsc
amach	amach	amach-R	Rd
ag	ag	ag-S	Sp
gáire	gáire	gáir-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cén	Cén	cé-D	Dw--s
fáth	fáth	fáth-N	Ncmsc
a	a	a-Q	Q-i
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
gáire	gáire	gáir-N	Nv
fúm	fúm	faoi-P	Pr1-s
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
Learaí	Learaí	Learaí-N	Npmsc
de	de	de-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
ceapadh	ceapadh	ceap-N	Nv
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
galar	galar	galar-N	Ncmsc
éicint	éicint	éicint-A	Aq-msc
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
ná	ná	ná-C	Cs|Cc
galar	galar	galar-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Fionnán	Fionnán	Fionnán-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Fail	Fail	fail-N	Ncfsc
atá	atá	bí-V	Vmip---r
ort	ort	ar-P	Pr2-s
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Fail	Fail	fail-X	Xfev
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Learaí	Learaí	Learaí-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
é	é	é-P	Pp3ms
sin	sin	sin-W	W
?	?	?-F	Fq
Tá	Tá	bí-V	Vmip
súil	súil	súil-N	Ncfsc
agam	agam	ag-P	Pr1-s
nach	nach	nach-Q	Qnr
gcaithfidh	gcaithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
chuig	chuig	chuig-S	Sp
an	an	an-T	Td-s
dochtúir	dochtúir	dochtúir-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
chaithfidh	chaithfidh	caith-V	Vmif---n
tú	tú	tú-P	Pp2-s
,	,	,-F	Fi
muise	muise	muise-X	Xsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Fionnán	Fionnán	Fionnán-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
leigheas	leigheas	leigheas-N	Ncmsc
agamsa	agamsa	ag-P	Pr1-s-e
duit	duit	do-P	Pr2-s
.	.	.-F	Fe
Nach	Nach	is-W	Wpsin
minic	minic	minic-A	Aqp
a	a	a-Q	Q-r
bhíonn	bhíonn	bí-V	Vmig
fail	fail	fail-N	Ncfsc
orm	orm	ar-P	Pr1-s
féin	féin	féin-P	Px
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Tar	Tar	thar-S	Sp
anseo	anseo	anseo-R	Rl
chugam	chugam	chuig-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Fionnán	Fionnán	Fionnán-N	Npmsc
le	le	le-S	Sp
Learaí	Learaí	Learaí-N	Npmsc
ansin	ansin	ansin-R	Rt|Rl
,	,	,-F	Fi
‘	‘	‘-X	Xx
agus	agus	agus-C	Cc
seas	seas	seas-N	Ncmsc|Xfen
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
do	do	do-S	Sp
chloigeann	chloigeann	cloigeann-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ar	Ar	is-W	Wsdq|Ws-q
mo	mo	mo-D	Dp1-s
chloigeann	chloigeann	cloigeann-N	Ncmsc
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Learaí	Learaí	Learaí-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Sea	Sea	sea-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Fionnán	Fionnán	Fionnán-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ar	Ar	is-W	Wssi|Wpdi|Wpsi
do	do	do-S	Sp
chloigeann	chloigeann	cloigeann-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
Sheas	Sheas	seas-V	Vmis
Learaí	Learaí	Learaí-N	Npmsc
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
chloigeann	chloigeann	cloigeann-N	Ncmsc
mar	mar	mar-C	Cs|Sp
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
iarr	iarr	iarr-V	Vmm-2s
Fionnán	Fionnán	Fionnán-N	Npmsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Learaí	Learaí	Learaí-N	Npmsc
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
chloigeann	chloigeann	cloigeann-N	Ncmsc
shín	shín	sín-V	Vmis
Fionnán	Fionnán	Fionnán-N	Npmsc
deoch	deoch	deoch-N	Ncfsc
chuige	chuige	chuig-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ól	Ól	ól-N	Ncmsc|Nv
é	é	é-P	Pp3ms
sin	sin	sin-P	Pd|W
anois	anois	anois-R	Rt
agus	agus	agus-C	Cc
stopfaidh	stopfaidh	stop-V	Vmif
an	an	an-T	Td-s
fhail	fhail	fail-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
atá	atá	bí-V	Vmip---r
ann	ann	i-P	Pr3ms
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Learaí	Learaí	Learaí-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Braon	Braon	braon-N	Ncmsc
uisce	uisce	uisce-N	Ncmsg|Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Fionnán	Fionnán	Fionnán-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caith	Caith	caith-V	Vmm-2s
siar	siar	siar-R	Rd
é	é	é-P	Pp3ms
go	go	go-U	Ua
beo	beo	beo-A	Aqp
.	.	.-F	Fe
’	’	’-F	Fa
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
t-uisce	t-uisce	uisce-N	Ncmsc
ólta	ólta	ól-A	Av
ag	ag	ag-S	Sp
Learaí	Learaí	Learaí-N	Npmsc
dúirt	dúirt	abair-V	Vmis
Fionnán	Fionnán	Fionnán-N	Npmsc
leis	leis	le-P	Pr3ms
go	go	go-Q	Q
bhféadfadh	bhféadfadh	féad-V	Vmc
sé	sé	sé-P	Pp3msn
seasamh	seasamh	seas-N	Ncmsc|Nv
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
chosa	chosa	cos-N	Ncfpc
arís	arís	arís-R	Rg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
fhail	fhail	fail-N	Ncfsc
imithe	imithe	imigh-A	Av
díom	díom	de-P	Pr1-s
anois	anois	anois-R	Rt
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
thar a bheith	thar a bheith	thar_a_bheith-R	Ri
buíoch	buíoch	buíoch-A	Aqp
díot	díot	de-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Fhionnáin	Fhionnáin	Fionnán-N	Npm-v
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Learaí	Learaí	Learaí-N	Npmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
bhfrog	bhfrog	frog-N	Ncmsc
agus	agus	agus-C	Cc
síos	síos	síos-R	Rd
an	an	an-T	Td-s
bóthar	bóthar	bóthar-N	Ncmsc
leis	leis	le-P	Pr3ms
go	go	go-U	Ua
sásta	sásta	sásta-A	Aqp
.	.	.-F	Fe
Bhreathnaigh	Bhreathnaigh	breathnaigh-V	Vmis
Labhrás	Labhrás	Labhrás-N	Npmsc
Luch	Luch	luch-N	Ncfsc
amach	amach	amach-R	Rd
agus	agus	agus-C	Cc
chonaic	chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
chara	chara	cara-N	Ncmsc
Learaí	Learaí	Learaí-N	Npmsc
ag	ag	ag-S	Sp
gabháil	gabháil	gabh-N	Nv
síos	síos	síos-R	Rd
an	an	an-T	Td-s
bóthar	bóthar	bóthar-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Heileó	Heileó	Heileó-N	Npmsc
,	,	,-F	Fi
a	a	a-U	Uv
Learaí	Learaí	Learaí-N	Npmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Labhrás	Labhrás	Labhrás-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cén	Cén	cé-D	Dw--s
chaoi	chaoi	caoi-N	Ncfsc
a	a	a-Q	Q-i
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Hic	Hic	hic-X	Xfl
!	!	!-F	Fe
Hic	Hic	hic-X	Xfl
!	!	!-F	Fe
Hic	Hic	hic-X	Xfl
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Learaí	Learaí	Learaí-N	Npmsc
.	.	.-F	Fe
Scairt	Scairt	scairt-V	Vmis
Labhrás	Labhrás	Labhrás-N	Npmsc
amach	amach	amach-R	Rd
ag	ag	ag-S	Sp
gáire	gáire	gáir-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cén	Cén	cé-D	Dw--s
fáth	fáth	fáth-N	Ncmsc
a	a	a-Q	Q-i
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
gáire	gáire	gáir-N	Nv
fúm	fúm	faoi-P	Pr1-s
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
Learaí	Learaí	Learaí-N	Npmsc
de	de	de-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
ceapadh	ceapadh	ceap-N	Nv
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
galar	galar	galar-N	Ncmsc
éicint	éicint	éicint-A	Aq-msc
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
ná	ná	ná-C	Cs|Cc
galar	galar	galar-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Labhrás	Labhrás	Labhrás-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Fail	Fail	fail-N	Ncfsc
atá	atá	bí-V	Vmip---r
ort	ort	ar-P	Pr2-s
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Sin	Sin	sin-W	W
é	é	é-P	Pp3ms
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
Fionnán	Fionnán	Fionnán-N	Npmsc
Frog	Frog	frog-N	Ncmsc|Xfen
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Learaí	Learaí	Learaí-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
leigheas	leigheas	leigheas-N	Ncmsc
agamsa	agamsa	ag-P	Pr1-s-e
duit	duit	do-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Labhrás	Labhrás	Labhrás-N	Npmsc
le	le	le-S	Sp
Learaí	Learaí	Learaí-N	Npmsc
ansin	ansin	ansin-R	Rt|Rl
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nach	Nach	is-C	Cs|Wpdin|Wpsin
minic	minic	minic-A	Aqp|Rg
a	a	a-Q	Q-r
bhíonn	bhíonn	bí-V	Vmig
fail	fail	fail-N	Ncfsc
orm	orm	ar-P	Pr1-s
féin	féin	féin-P	Px
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
súil	súil	súil-N	Ncfsc
agam	agam	ag-P	Pr1-s
gur	gur	is-W	Wsdi
fearr	fearr	maith-A	Aqc
é	é	é-P	Pp3ms
ná	ná	ná-C	Cs
an	an	is-W	Wpdq|Wp-q
leigheas	leigheas	leigheas-N	Ncmsc|Nv
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
Fionnán	Fionnán	Fionnán-N	Npmsc
dom	dom	do-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Learaí	Learaí	Learaí-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
bac	bac	bac-V	Vmm-2s-n
Fionnán	Fionnán	Fionnán-N	Npmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Labhrás	Labhrás	Labhrás-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
leigheas	leigheas	leigheas-N	Ncmsc
atá	atá	bí-V	Vmip---r
agamsa	agamsa	ag-P	Pr1-s-e
thar	thar	thar-S	Sp
cionn	cionn	ceann-N	Ncfsd
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Tar	Tar	thar-S	Sp
anseo	anseo	anseo-R	Rl
chugam	chugam	chuig-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Labhrás	Labhrás	Labhrás-N	Npmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
leipreachán	leipreachán	leipreachán-N	Ncmsc
ansin	ansin	ansin-R	Rt|Rl
.	.	.-F	Fe
‘	‘	‘-X	Xx
Anois	Anois	anois-R	Rt
iompaigh	iompaigh	iompaigh-V	Vmm-2s
do	do	do-S	Sp
dhroim	dhroim	droim-N	Ncmsc
liom	liom	le-P	Pr1-s
agus	agus	agus-C	Cc
dún	dún	dún-V	Vmm-2s
do	do	do-S	Sp
shúile	shúile	súil-N	Ncfpc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
An	An	an-Q	Qq
gcaithfidh	gcaithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
seasamh	seasamh	seas-N	Ncmsc|Nv
ar	ar	ar-W	Wsdq|Ws-q|Wssi|Wpdi|Wpsi|Sp|Ncmsc
mo	mo	mo-D	Dp1-s
chloigeann	chloigeann	cloigeann-N	Ncmsc
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Learaí	Learaí	Learaí-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
chaithfidh	chaithfidh	caith-V	Vmif---n
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Labhrás	Labhrás	Labhrás-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
gcaithfidh	gcaithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
deoch	deoch	deoch-N	Ncfsc
uisce	uisce	uisce-N	Ncmsg|Ncmsc|Ncmsg
a	a	a-U	U
ól	ól	ól-N	Nv
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Learaí	Learaí	Learaí-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
chaithfidh	chaithfidh	caith-V	Vmif---n
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Labhrás	Labhrás	Labhrás-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
le	le	le-S	Sp
déanamh	déanamh	déan-N	Nv
agat	agat	ag-P	Pr2-s
ach	ach	ach-S	Sp|Cs
do	do	do-S	Sp
shúile	shúile	súil-N	Ncfpc
a	a	a-U	U
dhúnadh	dhúnadh	dún-N	Nv
agus	agus	agus-C	Cc
seasamh	seasamh	seas-N	Ncmsc|Nv
ansin	ansin	ansin-R	Rt|Rl
gan	gan	gan-S	Sp
cor	cor	cor-N	Ncmsc
asat	asat	as-P	Pr2-s
.	.	.-F	Fe
’	’	’-F	Fa
Dhún	Dhún	dún-V	Vmis
Learaí	Learaí	Learaí-N	Npmsc
a	a	a-U	U
shúile	shúile	súil-N	Nv--g--n
agus	agus	agus-C	Cc
sheas	sheas	seas-V	Vmis
sé	sé	sé-P	Pp3msn
gan	gan	gan-S	Sp
cor	cor	cor-N	Ncmsc
as	as	as-N	Ncmpg
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
níor	níor	is-W	Ws-in
stop	stop	stop-N	Ncmsc
an	an	an-T	Td-s
fhail	fhail	fail-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Hic	Hic	hic-X	Xfl
!	!	!-F	Fe
Hic	Hic	hic-X	Xfl
!	!	!-F	Fe
Hic	Hic	hic-X	Xfl
!	!	!-F	Fe
Níl	Níl	bí-V	Vmip---n
maith	maith	maith-N	Ncfsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
leigheas	leigheas	leigheas-N	Ncmsc
seo	seo	seo-D	Dd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Learaí	Learaí	Learaí-N	Npmsc
tar éis	tar éis	tar_éis-S	Spc
scaithimh	scaithimh	scaitheamh-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
fail	fail	fail-N	Ncfsc
fós	fós	fós-R	Rg
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Fan	Fan	fan-V	Vmm-2s
scaitheamh	scaitheamh	scaitheamh-N	Ncmsc
eile	eile	eile-D	Dd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Labhrás	Labhrás	Labhrás-N	Npmsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
Learaí	Learaí	Learaí-N	Npmsc
pléasc	pléasc	pléasc-N	Ncfsc
taobh	taobh	taobh-N	Ncmsc
thiar	thiar	thiar-R	Rd
de	de	de-P	Pr3ms
ba	ba	is-W	Wsri
bheag	bheag	beag-A	Aqp
nár	nár	nár-Q	Qnrs
thit	thit	tit-V	Vmis---n
an	an	an-T	Td-s
t-anam	t-anam	anam-N	Ncmsc
as	as	as-P	Pr3ms
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
shúile	shúile	súil-N	Ncfpc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
iompaigh	iompaigh	iompaigh-V	Vmis
sé	sé	sé-P	Pp3msn
timpeall	timpeall	timpeall-R	Rd|Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Éist	Éist	éist-V	Vmm-2s
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Labhrás	Labhrás	Labhrás-N	Npmsc
Luch	Luch	luch-N	Ncfsc|Ncfpg
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
Learaí	Learaí	Learaí-N	Npmsc
Leipreachán	Leipreachán	leipreachán-N	Ncmsc|Ncmpg
cluas	cluas	cluas-N	Ncfpg|Ncfsc
air	air	ar-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
chloisim	chloisim	clois-V	Vmip1s-n
tada	tada	tada-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nach	Nach	is-C	Cs|Wpdin|Wpsin
in	in	sin-P	Pd
é	é	é-P	Pp3ms
díreach	díreach	díreach-A	Aqp|Ncmsc
é	é	é-P	Pp3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
luch	luch	luch-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
chloiseann	chloiseann	clois-V	Vmip---n
tú	tú	tú-P	Pp2-s
tada	tada	tada-N	Ncmsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
fhail	fhail	fail-N	Ncfsc
imithe	imithe	imigh-A	Av
díot	díot	de-P	Pr2-s
anois	anois	anois-R	Rt
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Nach	Nach	is-C	Cs|Wpdin|Wpsin
iontach	iontach	iontach-A	Aqp
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
an	an	an-T	Td-s
leigheas	leigheas	leigheas-N	Ncmsc
é	é	é-P	Pp3ms
sin	sin	sin-P	Pd
atá	atá	bí-V	Vmip---r
agat	agat	ag-P	Pr2-s
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
leipreachán	leipreachán	leipreachán-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
thar a bheith	thar a bheith	thar_a_bheith-R	Ri
buíoch	buíoch	buíoch-A	Aqp
díot	díot	de-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Labhráis	Labhráis	Labhrás-N	Npm-v
.	.	.-F	Fe
Fan	Fan	fan-V	Vmm-2s
go	go	go-Q	Q-s
gcloise	gcloise	clois-V	Vmsp
Fionnán	Fionnán	Fionnán-N	Npmsc
Frog	Frog	frog-N	Ncmsc|Xfen
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
leigheas	leigheas	leigheas-N	Ncmsc
níos	níos	níos-U	Uc
fearr	fearr	maith-A	Aqc
agatsa	agatsa	ag-P	Pr2-s-e
ná	ná	ná-C	Cs|Cc
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
aige	aige	ag-P	Pr3ms
féin	féin	féin-P	Px
!	!	!-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Tic	Tic	tic-N	Ncmsc|Xfen
teaic	teaic	teaic-N	Ncfsc
tiú	tiú	tiú-A	Aq
,	,	,-F	Fi
péire	péire	péire-N	Ncmsc
bróga	bróga	bróg-N	Ncfpc
nua	nua	nua-A	Aqp
.	.	.-F	Fe
Cuirfidh	Cuirfidh	cuir-V	Vmif
mise	mise	mé-P	Pp1-s-e
an	an	an-T	Td-s
tairne	tairne	tairne-N	Ncmsc
agus	agus	agus-C	Cc
cuirfidh	cuirfidh	cuir-V	Vmif
tusa	tusa	tú-P	Pp2-s-e
an	an	an-T	Td-s
crú	crú	crú-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
Oíche	Oíche	oíche-N	Ncfsc
chiúin	chiúin	ciúin-A	Aq-fsc
ghealaí	ghealaí	gealach-N	Ncfsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Learaí	Learaí	Learaí-N	Npmsc
Leipreachán	Leipreachán	leipreachán-N	Ncmsc|Ncmpg
ag	ag	ag-S	Sp
obair	obair	obair-N	Nv-----n
leis	leis	le-P	Pr3ms
go	go	go-U	Ua
sásta	sásta	sásta-A	Aqp
…	…	…-F	Fi
