‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
cluiche	cluiche	cluiche-N	Ncmsc
peile	peile	peil-N	Ncfsg
le	le	le-S	Sp
himirt	himirt	imir-N	Nv
agamsa	agamsa	ag-P	Pr1-s-e
tar éis	tar éis	tar_éis-S	Spc
na	na	na-T	Tdfsg
scoile	scoile	scoil-N	Ncfsg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
lena	lena	le-S	Spp-s
Dhaidí	Dhaidí	daidí-N	Ncmsc
maidin	maidin	maidin-N	Ncfsc
amháin	amháin	amháin-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
súil	súil	súil-N	Ncfsc
agam	agam	ag-P	Pr1-s
go	go	go-Q	Q
mbeidh	mbeidh	bí-V	Vmif
an-chluiche	an-chluiche	cluiche-N	Ncmsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ar	Ar	ar-Q	Qq-s
imir	imir	imir-V	Vmis
tusa	tusa	tú-P	Pp2-s-e
peil	peil	peil-N	Ncfsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
tú	tú	tú-P	Pp2-s
óg	óg	óg-A	Aqp
,	,	,-F	Fi
a	a	a-U	Uv
Dhaidí	Dhaidí	daidí-N	Ncmsv
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
tar éis	tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
D	D	D-X	Xl
’	’	’-F	Fa
imir	imir	imir-V	Vmm-2s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhí	Bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
ar	ar	ar-S	Sp
fhoireann	fhoireann	foireann-N	Ncfsc
na	na	na-T	Tdfsg
scoile	scoile	scoil-N	Ncfsg
.	.	.-F	Fe
’	’	’-F	Fa
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
rug	rug	beir-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
chóta	chóta	cóta-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
bailiú	bailiú	bailigh-N	Nv
liom	liom	le-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Slán	Slán	slán-N	Ncmsc
go	go	go-U	Ua
fóill	fóill	fóill-A	Aqp
.	.	.-F	Fe
’	’	’-F	Fa
Agus	Agus	agus-C	Cc
amach	amach	amach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
cluiche	cluiche	cluiche-N	Ncmsc
peile	peile	peil-N	Ncfsg
le	le	le-S	Sp
himirt	himirt	imir-N	Nv
agamsa	agamsa	ag-P	Pr1-s-e
tar éis	tar éis	tar_éis-S	Spc
na	na	na-T	Tdfsg
scoile	scoile	scoil-N	Ncfsg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
lena	lena	le-S	Spp-s
Mhamaí	Mhamaí	mama-N	Ncfsc|Ncmpc
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
gabháil	gabháil	gabh-N	Nv
amach	amach	amach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
súil	súil	súil-N	Ncfsc
agam	agam	ag-P	Pr1-s
go	go	go-Q	Q
mbeidh	mbeidh	bí-V	Vmif
an-chluiche	an-chluiche	cluiche-N	Ncmsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cén	Cén	cé-D	Dw--s
chaoi	chaoi	caoi-N	Ncfsc
ar	ar	ar-Q	Q-is
éirigh	éirigh	éirigh-V	Vmis
libh	libh	le-P	Pr2-p
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
abhaile	abhaile	abhaile-R	Rd
tráthnóna	tráthnóna	tráthnóna-N	Ncmsc
.	.	.-F	Fe
Buaileadh	Buaileadh	buail-V	Vmis0
muid	muid	muid-P	Pp1-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Buaileadh	Buaileadh	buail-V	Vmis0
muid	muid	muid-P	Pp1-p
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhí	Bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
imirt	imirt	imir-N	Nv
sna	sna	i-S	Spa-p
tosaithe	tosaithe	tosaí-N	Ncmpc
ach	ach	ach-C	Cs
ní	ní	is-W	Wp-in
bhfuair	bhfuair	faigh-V	Vmis
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
oiread	oiread	oiread-N	Ns-s
is	is	agus-C	Cc
pointe	pointe	pointe-N	Ncmsg|Ncmsc
amháin	amháin	amháin-A	Aqp
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
An	An	an-Q	Qq
raibh	raibh	bí-V	Vmis---d
tusa	tusa	tú-P	Pp2-s-e
go	go	go-U	Ua
maith	maith	maith-A	Aqp
ag	ag	ag-S	Sp
an	an	an-T	Td-s
bpeil	bpeil	peil-N	Ncfsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
tú	tú	tú-P	Pp2-s
óg	óg	óg-A	Aqp
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
dá	dá	do-S	Spp-s
Dhaidí	Dhaidí	daidí-N	Ncmsc
an	an	an-T	Td-s
oíche	oíche	oíche-N	Ncfsg
sin	sin	sin-D	Dd
.	.	.-F	Fe
‘	‘	‘-X	Xx
M	M	M-X	Xl
’	’	’-F	Fa
anam	anam	anam-N	Ncmsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nach	Nach	nach-Q	Qnr|Qnq
bhfeiceann	bhfeiceann	feic-V	Vmip
tú	tú	tú-P	Pp2-s
na	na	na-T	Td-p
boinn	boinn	bonn-N	Ncmpc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
cupáin	cupáin	cupán-N	Ncmpc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
a	a	a-Q	Q-r
bhuaigh	bhuaigh	buaigh-V	Vmis
sé	sé	sé-P	Pp3msn
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
a	a	a-U	U
bheith	bheith	bí-N	Nv
go	go	go-U	Ua
maith	maith	maith-A	Aqp
ag	ag	ag-S	Sp
an	an	an-T	Td-s
bpeil	bpeil	peil-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
An	An	an-T	Td-s
Satharn	Satharn	Satharn-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-W	W
d	d	d-X	Xl
’	’	’-F	Fa
imir	imir	imir-N	Ncfsc
Gearóid	Gearóid	Gearóid-N	Npm-g|Npmsg|Npmsc
cluiche	cluiche	cluiche-N	Ncmsg|Ncmsc
eile	eile	eile-D	Dd
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
agus	agus	agus-C	Cc
Daidí	Daidí	daidí-N	Ncmsc|Ncmsg
ag	ag	ag-S	Sp
breathnú	breathnú	breathnaigh-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcluiche	gcluiche	cluiche-N	Ncmsc
.	.	.-F	Fe
Sna	Sna	i-S	Spa-p
tosaithe	tosaithe	tosaí-N	Ncmpc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
ag	ag	ag-S	Sp
imirt	imirt	imir-N	Nv
arís	arís	arís-R	Rg
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
foireann	foireann	foireann-N	Ncfsc
Ghearóid	Ghearóid	Gearóid-N	Npm-g|Npfsg
thar	thar	thar-S	Sp
moladh	moladh	moladh-N	Ncmsc
beirte	beirte	beirt-N	Ncfsg
agus	agus	agus-C	Cc
buaileadh	buaileadh	buail-V	Vmis0
iad	iad	iad-P	Pp3-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
dhéanann	dhéanann	déan-V	Vmip---n
siad	siad	siad-P	Pp3-pn
leath	leath	leath-V	Vmis
a	a	a-D	Dp3
ndóthain	ndóthain	dóthain-N	Ncfsc
traenála	traenála	traenáil-N	Ncfsg|Nv--g
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
le	le	le-S	Sp
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
Gearóid	Gearóid	Gearóid-N	Npmsc
sásta	sásta	sásta-A	Aqp
ar	ar	ar-S	Sp
chor	chor	cor-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
bhfuair	bhfuair	faigh-V	Vmis
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
oiread	oiread	oiread-N	Ns-s
is	is	agus-W	Wp-i|Wpri|Cc
pointe	pointe	pointe-N	Ncmsg|Ncmsc
amháin	amháin	amháin-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
le	le	le-S	Sp
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
B	B	B-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
nach	nach	nach-Q	Qnr
ndéanann	ndéanann	déan-V	Vmip
sibh	sibh	sibh-P	Pp2-p
bhur	bhur	bhur-D	Dp2-p
ndóthain	ndóthain	dóthain-N	Ncfsc
traenála	traenála	traenáil-N	Ncfsg|Nv--g
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
Níos	Níos	níos-U	Uc
deireanaí	deireanaí	deireanach-A	Aqc
tráthnóna	tráthnóna	tráthnóna-N	Ncmsc
bhí	bhí	bí-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
ag	ag	ag-S	Sp
breathnú	breathnú	breathnaigh-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
teilifís	teilifís	teilifís-N	Ncfsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
isteach	isteach	isteach-R	Rd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cuir	Cuir	cur-N	Ncmsg
ort	ort	ar-P	Pr2-s
do	do	do-S	Sp
chuid	chuid	cuid-N	Ncfsc
bróga	bróga	bróg-N	Ncfpc
peile	peile	peil-N	Ncfsg
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
le	le	le-S	Sp
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
taitníonn	taitníonn	taitin-V	Vmip
an	an	an-T	Td-s
clár	clár	clár-N	Ncmsc
seo	seo	seo-D	Dd
liom	liom	le-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cén	Cén	cé-D	Dw--s
chaoi	chaoi	caoi-N	Ncfsc
a	a	a-Q	Q-i
mbeidh	mbeidh	bí-V	Vmif
tú	tú	tú-P	Pp2-s
go	go	go-U	Ua
maith	maith	maith-A	Aqp
ag	ag	ag-S	Sp
an	an	an-T	Td-s
bpeil	bpeil	peil-N	Ncfsc
mura	mura	mura-C	Cs
mbíonn	mbíonn	bí-V	Vmig
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
traenáil	traenáil	traenáil-N	Nv
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
a	a	a-D	Dp3
chuid	chuid	cuid-N	Ncfsc
bróga	bróga	bróg-N	Ncfpc
peile	peile	peil-N	Ncfsg
ar	ar	ar-S	Sp
Ghearóid	Ghearóid	Gearóid-N	Npmsc
shín	shín	sín-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
mála	mála	mála-N	Ncmsc
chuige	chuige	chuig-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cheannaigh	Cheannaigh	ceannaigh-V	Vmis
mé	mé	mé-P	Pp1-s
bronntanas	bronntanas	bronntanas-N	Ncmsc
duit	duit	do-P	Pr2-s
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
atá	atá	bí-V	Vmip---r
ann	ann	i-P	Pr3ms
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Oscail	Oscail	oscail-V	Vmm-2s
é	é	é-P	Pp3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Liathróid	Liathróid	liathróid-N	Ncfsc
atá	atá	bí-V	Vmip---r
ann	ann	i-P	Pr3ms
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Liathróid	Liathróid	liathróid-N	Ncfsc
bhreá	bhreá	breá-A	Aq-fsc
.	.	.-F	Fe
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
míle	míle	míle-M	Mc
maith	maith	maith-N	Ncfsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Dhaidí	Dhaidí	daidí-N	Ncmsv
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
fáilte	fáilte	fáilte-N	Ncfsc
romhat	romhat	roimh-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
Amach	Amach	amach-R	Rd
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbeirt	mbeirt	beirt-N	Ncfsc
acu	acu	ag-P	Pr3-p
sa	sa	i-S	Spa-s
ngairdín	ngairdín	gairdín-N	Ncmsc
ansin	ansin	ansin-R	Rt|Rl
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
mise	mise	mé-P	Pp1-s-e
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
chúl	chúl	cúl-N	Ncmsc
báire	báire	báire-N	Ncmsg|Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
M	M	M-X	Xl
’	’	’-F	Fa
anam	anam	anam-N	Ncmsc
gur	gur	is-W	Wsdi
breá	breá	breá-A	Aqp
an	an	an-T	Td-s
liathróid	liathróid	liathróid-N	Ncfsc
í	í	í-P	Pp3fs
seo	seo	seo-P	Pd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
Tharraing	Tharraing	tarraing-V	Vmis
sé	sé	sé-P	Pp3msn
cic	cic	cic-N	Ncfsc|Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
liathróid	liathróid	liathróid-N	Ncfsc
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
…	…	…-F	Fi
…	…	…-F	Fi
amach	amach	amach-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbóthar	mbóthar	bóthar-N	Ncmsc
í	í	í-P	Pp3fs
!	!	!-F	Fe
‘	‘	‘-X	Xx
M	M	M-X	Xl
’	’	’-F	Fa
anam	anam	anam-N	Ncmsc
gur	gur	is-W	Wsdi
breá	breá	breá-A	Aqp
an	an	an-T	Td-s
liathróid	liathróid	liathróid-N	Ncfsc
í	í	í-P	Pp3fs
seo	seo	seo-P	Pd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
arís	arís	arís-R	Rg
.	.	.-F	Fe
Tharraing	Tharraing	tarraing-V	Vmis
sé	sé	sé-P	Pp3msn
cic	cic	cic-N	Ncfsc|Ncmsc
eile	eile	eile-D	Dd
uirthi	uirthi	ar-P	Pr3fs
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
…	…	…-F	Fi
…	…	…-F	Fi
isteach	isteach	isteach-R	Rd
sna	sna	i-S	Spa-p
sceacha	sceacha	sceach-N	Ncfpc
í	í	í-P	Pp3fs
!	!	!-F	Fe
‘	‘	‘-X	Xx
Gabh	Gabh	gabh-V	Vmm-2s
anall	anall	anall-R	Rd
anseo	anseo	anseo-R	Rl
chugam	chugam	chuig-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
tar éis	tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
mar	mar	mar-S	Sp
seo	seo	seo-P	Pd
ba	ba	is-W	Wsri
cheart	cheart	ceart-A	Aqp
í	í	í-P	Pp3fs
a	a	a-U	U
chiceáil	chiceáil	ciceáil-N	Nv
.	.	.-F	Fe
’	’	’-F	Fa
Tharraing	Tharraing	tarraing-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
cic	cic	cic-N	Ncfsc|Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
liathróid	liathróid	liathróid-N	Ncfsc
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
…	…	…-F	Fi
…	…	…-F	Fi
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
gcúl	gcúl	cúl-N	Ncmsc
í	í	í-P	Pp3fs
!	!	!-F	Fe
Chaith	Chaith	caith-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
tamall	tamall	tamall-N	Ncmsc
maith	maith	maith-A	Aq-msc
ag	ag	ag-S	Sp
cleachtadh	cleachtadh	cleacht-N	Nv
na	na	na-T	Td-p
scileanna	scileanna	scil-N	Ncfpg
peile	peile	peil-N	Ncfsg
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
lena	lena	le-S	Spp-s
Dhaidí	Dhaidí	daidí-N	Ncmsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
tharraing	tharraing	tarraing-V	Vmis
sé	sé	sé-P	Pp3msn
cic	cic	cic-N	Ncfsc|Ncmsc
eile	eile	eile-D	Dd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
liathróid	liathróid	liathróid-N	Ncfsc
.	.	.-F	Fe
Suas	Suas	suas-R	Rd
san	san	i-S	Spa-s
aer	aer	aer-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
liathróid	liathróid	liathróid-N	Ncfsc
–	–	–-X	Xx
suas	suas	suas-R	Rd
…	…	…-F	Fi
suas	suas	suas-R	Rd
…	…	…-F	Fi
suas	suas	suas-R	Rd
…	…	…-F	Fi
agus	agus	agus-C	Cc
…	…	…-F	Fi
…	…	…-F	Fi
thar	thar	thar-S	Sp
an	an	an-T	Td-s
trasnán	trasnán	trasnán-N	Ncmsc
!	!	!-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
go	go	go-U	Ua
maith	maith	maith-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Chuile	Chuile	gach-D	Dq
thráthnóna	thráthnóna	tráthnóna-N	Ncmsg
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|Dd
chaith	chaith	caith-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
tamall	tamall	tamall-N	Ncmsc
ag	ag	ag-S	Sp
traenáil	traenáil	traenáil-N	Nv
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
lena	lena	le-S	Spp-s
Dhaidí	Dhaidí	daidí-N	Ncmsc
.	.	.-F	Fe
Mí	Mí	Mí-N	Npfsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|Dd
bhí	bhí	bí-V	Vmis
cluiche	cluiche	cluiche-N	Ncmsc
eile	eile	eile-D	Dd
le	le	le-S	Sp
himirt	himirt	imir-N	Nv
ag	ag	ag-S	Sp
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
mise	mise	mé-P	Pp1-s-e
in ann	in ann	in_ann-S	Spc
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
chuig	chuig	chuig-S	Sp
an	an	an-T	Td-s
gcluiche	gcluiche	cluiche-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
leis	leis	le-P	Pr3ms
ar	ar	ar-S	Sp
maidin	maidin	maidin-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
go	go	go-S	Sp
Londain	Londain	Londain-N	Npfsc
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
mé	mé	mé-P	Pp1-s
ar ais	ar ais	ar_ais-R	Rd
in	in	i-S	Sp
am	am	am-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
imir	imir	imir-N	Ncfsc
Gearóid	Gearóid	Gearóid-N	Npm-g|Npmsg|Npmsc
an-chluiche	an-chluiche	cluiche-N	Ncmsc
.	.	.-F	Fe
Fuair	Fuair	faigh-V	Vmis
sé	sé	sé-P	Pp3msn
pointe	pointe	pointe-N	Ncmsc
amháin	amháin	amháin-A	Aqp
sa	sa	i-S	Spa-s
gcéad	gcéad	céad-M	Mo
leath	leath	leath-N	Ncfpg|Ncfsc|Ncfpg
agus	agus	agus-C	Cc
trí	trí	trí-M	Mc|Sp
phointe	phointe	pointe-N	Ncmsc
sa	sa	i-S	Spa-s
dara	dara	dara-M	Mo
leath	leath	leath-V	Vmis
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
cluiche	cluiche	cluiche-N	Ncmsc
thart	thart	thart-R	Rd
ghlaoigh	ghlaoigh	glaoigh-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
ar	ar	ar-S	Sp
Dhaidí	Dhaidí	daidí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhuaigh	Bhuaigh	Buaigh-N	Npfsg
muid	muid	muid-P	Pp1-p
,	,	,-F	Fi
a	a	a-U	Uv
Dhaidí	Dhaidí	daidí-N	Ncmsv
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
fuair	fuair	faigh-V	Vmis
mise	mise	mé-P	Pp1-s-e
ceithre	ceithre	ceathair-M	Mc
phointe	phointe	pointe-N	Ncmsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
é	é	é-P	Pp3ms
an	an	an-T	Td-s
trua	trua	trua-N	Ncfsc
nach	nach	nach-Q	Qnrs
bhfaca	bhfaca	feic-V	Vmis---d
tú	tú	tú-P	Pp2-s
mé	mé	mé-P	Pp1-s
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
chonaic	chonaic	feic-V	Vmis
mé	mé	mé-P	Pp1-s
thú	thú	tú-P	Pp2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
anseo	anseo	anseo-R	Rl
buailte	buailte	buail-A	Av
leat	leat	le-P	Pr2-s
.	.	.-F	Fe
’	’	’-F	Fa
Rith	Rith	rith-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
anonn	anonn	anonn-R	Rd
chuig	chuig	chuig-S	Sp
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
cheap	cheap	ceap-V	Vmis
mé	mé	mé-P	Pp1-s
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
tú	tú	tú-P	Pp2-s
i	i	i-S	Sp
Londain	Londain	Londain-N	Npfsc
,	,	,-F	Fi
a	a	a-U	Uv
Dhaidí	Dhaidí	daidí-N	Ncmsv
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhí	Bhí	bí-V	Vmis
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
ach	ach	ach-C	Cs
tháinig	tháinig	tar-V	Vmis
mé	mé	mé-P	Pp1-s
i	i	i-S	Sp
dtacsaí	dtacsaí	tacsaí-N	Ncmsc
ón	ón	ó-S	Spa-s
aerfort	aerfort	aerfort-N	Ncmsc
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
dara	dara	dara-M	Mo
leath	leath	leath-V	Vmis
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
a	a	a-Q	Q-r
cheap	cheap	ceap-V	Vmis
tú	tú	tú-P	Pp2-s
de	de	de-S	Sp
na	na	na-T	Td-p
pointí	pointí	pointe-N	Ncmpc
a	a	a-Q	Q-i|Q-r
fuair	fuair	faigh-V	Vmis
mé	mé	mé-P	Pp1-s
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
Murach	Murach	murach-C	Cs
an	an	is-W	Wpdq|Wp-q
traenáil	traenáil	traenáil-N	Ncfsc|Nv
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
…	…	…-F	Fi
‘	‘	‘-X	Xx
M	M	M-X	Xl
’	’	’-F	Fa
anam	anam	anam-N	Ncmsc
go	go	go-Q	Q
ndearna	ndearna	déan-V	Vmis---d
tú	tú	tú-P	Pp2-s
go	go	go-U	Ua
maith	maith	maith-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Murach	Murach	murach-C	Cs
an	an	is-W	Wpdq|Wp-q
traenáil	traenáil	traenáil-N	Ncfsc|Nv
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
…	…	…-F	Fi
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Sea	Sea	sea-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Murach	Murach	murach-C	Cs
an	an	is-W	Wpdq|Wp-q
traenáil	traenáil	traenáil-N	Ncfsc|Nv
…	…	…-F	Fi
’	’	’-F	Fa
Murach	Murach	murach-C	Cs
an	an	is-W	Wpdq|Wp-q
traenáil	traenáil	traenáil-N	Ncfsc|Nv
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
…	…	…-F	Fi
‘	‘	‘-X	Xx
Ar	Ar	ar-Q	Qq-s
imir	imir	imir-V	Vmis
tusa	tusa	tú-P	Pp2-s-e
peil	peil	peil-N	Ncfsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
tú	tú	tú-P	Pp2-s
óg	óg	óg-A	Aqp
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
dá	dá	do-S	Spp-s
Dhaidí	Dhaidí	daidí-N	Ncmsc
lá	lá	lá-N	Ncmsc
.	.	.-F	Fe
