Chuala	Chuala	clois-V	Vmis
Lug	Lug	lug-N	Ncmsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
carnabhal	carnabhal	carnabhal-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbaile	mbaile	baile-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ar	Ar	ar-Q	Qq-s
chuala	chuala	clois-V	Vmis
tú	tú	tú-P	Pp2-s
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
an	an	an-T	Td-s
carnabhal	carnabhal	carnabhal-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbaile	mbaile	baile-N	Ncmsc
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
le	le	le-S	Sp
Gug	Gug	Gug-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
dul	dul	téigh-N	Nv
ann	ann	ann-R	Rl
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
dul	dul	téigh-N	Nv
ann	ann	ann-R	Rl
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gug	Gug	Gug-N	Npmsc
.	.	.-F	Fe
An	An	an-T	Td-s
lá	lá	lá-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|W|Dd
d	d	d-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmm-2s
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
ar	ar	ar-N	Ncmsc
a	a	a-U	Um
hocht	hocht	ocht-M	Mc
a	a	an-T	Td-s
chlog	chlog	clog-N	Ncmsc
.	.	.-F	Fe
Síos	Síos	síos-R	Rd
leo	leo	le-P	Pr3-p
go	go	go-S	Sp
Bóthar	Bóthar	bóthar-N	Ncmsc
na	na	na-T	Tdfsg
Trá	Trá	trá-N	Ncfsg
.	.	.-F	Fe
Cheannaigh	Cheannaigh	ceannaigh-V	Vmis
siad	siad	siad-P	Pp3-pn
dhá	dhá	dó-M	Mc
thicéad	thicéad	ticéad-N	Ncmsc
agus	agus	agus-C	Cc
isteach	isteach	isteach-R	Rd
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
Siúd	Siúd	siúd-P	Pd
leo	leo	le-P	Pr3-p
ag	ag	ag-S	Sp
spaisteoireacht	spaisteoireacht	spaisteoireacht-N	Ncfsc
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
Lug	Lug	lug-N	Ncmsc
na	na	na-T	Td-p
báid	báid	bád-N	Ncmsg
luascáin	luascáin	luascán-N	Ncmsg|Ncmpc|Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
na	na	na-T	Td-p
báid	báid	bád-N	Ncmpc
luascáin	luascáin	luascán-N	Ncmsg|Ncmpc|Ncmsg
ansin	ansin	ansin-R	Rt|Rl
thall	thall	tall-V	Vmis
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
leat	leat	le-P	Pr2-s
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gug	Gug	Gug-N	Npmsc
.	.	.-F	Fe
Seo	Seo	seo-W	W
leat	leat	le-P	Pr2-s
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbeirt	mbeirt	beirt-N	Ncfsc
acu	acu	ag-P	Pr3-p
i	i	i-S	Sp
mbád	mbád	bád-N	Ncmsc
luascáin	luascáin	luascán-N	Ncmsg
.	.	.-F	Fe
Suas	Suas	suas-R	Rd
síos	síos	síos-R	Rd
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbeirt	mbeirt	beirt-N	Ncfsc
acu	acu	ag-P	Pr3-p
–	–	–-X	Xx
suas	suas	suas-R	Rd
síos	síos	síos-R	Rd
suas	suas	suas-R	Rd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Thaitin	Thaitin	taitin-V	Vmis
sé	sé	sé-P	Pp3msn
sin	sin	sin-P	Pd
liom	liom	le-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Lug	Lug	lug-N	Ncmsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
chonaic	chonaic	feic-V	Vmis
Gug	Gug	Gug-N	Npmsc
na	na	na-T	Td-p
tuairteáin	tuairteáin	tuairteán-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tuairteáin	tuairteáin	tuairteán-N	Ncmsg
ansin	ansin	ansin-R	Rt|Rl
thall	thall	tall-V	Vmis
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
leat	leat	le-P	Pr2-s
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Lug	Lug	lug-N	Ncmsc
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbeirt	mbeirt	beirt-N	Ncfsc
acu	acu	ag-P	Pr3-p
i	i	i-S	Sp
dtuairteán	dtuairteán	tuairteán-N	Ncmsc
.	.	.-F	Fe
Soir	Soir	soir-N	Ncmpc|Rd
siar	siar	siar-R	Rd
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbeirt	mbeirt	beirt-N	Ncfsc
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Timpeall	Timpeall	timpeall-N	Ncmsc|Rd
agus	agus	agus-C	Cc
timpeall	timpeall	timpeall-S	Sp|Rd
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Thaitin	Thaitin	taitin-V	Vmis
sé	sé	sé-P	Pp3msn
sin	sin	sin-P	Pd
liom	liom	le-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gug	Gug	Gug-N	Npmsc
.	.	.-F	Fe
Siúd	Siúd	siúd-P	Pd
leo	leo	le-P	Pr3-p
ag	ag	ag-S	Sp
spaisteoireacht	spaisteoireacht	spaisteoireacht-N	Ncfsc
arís	arís	arís-R	Rg
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
bhuail	bhuail	buail-V	Vmis
ocras	ocras	ocras-N	Ncmsc
Gug	Gug	Gug-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
ocras	ocras	ocras-N	Ncmsc
orm	orm	ar-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
siopa	siopa	siopa-N	Ncmsc
ansin	ansin	ansin-R	Rt|Rl
thall	thall	tall-V	Vmis
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Lug	Lug	lug-N	Ncmsc
.	.	.-F	Fe
Cheannaigh	Cheannaigh	ceannaigh-V	Vmis
Lug	Lug	lug-N	Ncmsc
úll	úll	úll-N	Ncmpg
agus	agus	agus-C	Cc
iógart	iógart	iógart-N	Ncmpg|Ncmsc
sa	sa	i-S	Spa-s
siopa	siopa	siopa-N	Ncmsc
.	.	.-F	Fe
Cheannaigh	Cheannaigh	ceannaigh-V	Vmis
Gug	Gug	Gug-N	Npmsc
milseáin	milseáin	milseán-N	Ncmpc
,	,	,-F	Fi
uachtar	uachtar	uachtar-N	Ncmsc
reoite	reoite	reoigh-A	Av
agus	agus	agus-C	Cc
criospaí	criospaí	criospa-N	Ncmsc|Ncmpc
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ba	Ba	is-W	Ws|Ws-i
cheart	cheart	ceart-A	Aqp
duit	duit	do-P	Pr2-s
bia	bia	bia-N	Ncmsc
folláin	folláin	folláin-A	Aq-msc
a	a	a-U	U
ithe	ithe	ith-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Lug	Lug	lug-N	Ncmsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
is	is	is-W	Wp-i
deise	deise	deas-A	Aqc
iad	iad	iad-P	Pp3-p
seo	seo	seo-P	Pd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gug	Gug	Gug-N	Npmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
is	is	is-W	Wp-i
deise	deise	deas-A	Aqc
iad	iad	iad-P	Pp3-p
seo	seo	seo-P	Pd
.	.	.-F	Fe
Siúd	Siúd	siúd-P	Pd
leo	leo	le-P	Pr3-p
ag	ag	ag-S	Sp
spaisteoireacht	spaisteoireacht	spaisteoireacht-N	Ncfsc
arís	arís	arís-R	Rg
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
chonaic	chonaic	feic-V	Vmis
Lug	Lug	lug-N	Ncmsc
an	an	an-T	Td-s
roithleagán	roithleagán	roithleagán-N	Ncmsc
ró	ró	ró-N	Ncmsg|Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
roithleagán	roithleagán	roithleagán-N	Ncmsc
ansin	ansin	ansin-R	Rt|Rl
thall	thall	tall-V	Vmis
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
leat	leat	le-P	Pr2-s
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gug	Gug	Gug-N	Npmsc
.	.	.-F	Fe
Suas	Suas	suas-R	Rd
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbeirt	mbeirt	beirt-N	Ncfsc
acu	acu	ag-P	Pr3-p
ar	ar	ar-S	Sp
an	an	an-T	Td-s
roithleagán	roithleagán	roithleagán-N	Ncmsc
ró	ró	ró-N	Ncmsg|Ncmsc
.	.	.-F	Fe
Timpeall	Timpeall	timpeall-N	Ncmsc|Rd
agus	agus	agus-C	Cc
timpeall	timpeall	timpeall-N	Ncmpg|Ncmsc|Sp|Rd
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbeirt	mbeirt	beirt-N	Ncfsc
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Thaitin	Thaitin	taitin-V	Vmis
sé	sé	sé-P	Pp3msn
sin	sin	sin-P	Pd
liom	liom	le-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Lug	Lug	lug-N	Ncmsc
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
chonaic	chonaic	feic-V	Vmis
Gug	Gug	Gug-N	Npmsc
siopa	siopa	siopa-N	Ncmsc
eile	eile	eile-D	Dd
.	.	.-F	Fe
Bhuail	Bhuail	buail-V	Vmis
ocras	ocras	ocras-N	Ncmsc
arís	arís	arís-R	Rg
é	é	é-P	Pp3ms
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
leis	leis	le-S	Sp
sa	sa	i-S	Spa-s
siopa	siopa	siopa-N	Ncmsc
agus	agus	agus-C	Cc
cheannaigh	cheannaigh	ceannaigh-V	Vmis
sé	sé	sé-P	Pp3msn
barra	barra	barra-N	Ncmsc
mór	mór	mór-A	Aq-msc
seacláide	seacláide	seacláid-N	Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
pian	pian	pian-N	Ncfsc
i	i	i-S	Sp
do	do	do-Q	Q
bholg	bholg	bolg-V	Vmis
má	má	má-C	Cs
itheann	itheann	ith-V	Vmip
tú	tú	tú-P	Pp2-s
é	é	é-P	Pp3ms
sin	sin	sin-P	Pd|W
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Lug	Lug	lug-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Dhera	Dhera	Dhera-N	Npmsc
,	,	,-F	Fi
ní	ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gug	Gug	Gug-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nach	Nach	nach-Q	Qnr|Qnq
bhfuil	bhfuil	bí-V	Vmip---d|Vmip---n
sé	sé	sé-P	Pp3msn
in	in	i-S	Sp
am	am	am-N	Ncmsc
againn	againn	ag-P	Pr1-p
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
abhaile	abhaile	abhaile-R	Rd
anois	anois	anois-R	Rt
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Lug	Lug	lug-N	Ncmsc
tar éis	tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
ní	ní	is-W	Wp-in
rabhamar	rabhamar	bí-V	Vmis1p-d
ar	ar	ar-S	Sp
an	an	an-T	Td-s
roth	roth	roth-N	Ncmsc
mór	mór	mór-A	Aq-msc
fós	fós	fós-R	Rg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gug	Gug	Gug-N	Npmsc
.	.	.-F	Fe
Suas	Suas	suas-R	Rd
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbeirt	mbeirt	beirt-N	Ncfsc
acu	acu	ag-P	Pr3-p
ar	ar	ar-S	Sp
an	an	an-T	Td-s
roth	roth	roth-N	Ncmsc
mór	mór	mór-A	Aq-msc
.	.	.-F	Fe
Suas	Suas	suas-R	Rd
suas	suas	suas-R	Rd
suas	suas	suas-R	Rd
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Lug	Lug	lug-N	Ncmsc
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
Go	Go	go-U	Ua
tobann	tobann	tobann-A	Aqp
lig	lig	lig-V	Vmis
Gug	Gug	Gug-N	Npmsc
béic	béic	béic-N	Ncfsc
as	as	as-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	a-T	Td-s|Dp3|Q-i|U|Q-r
Lug	Lug	lug-N	Ncmsc|Xfev|Ncmsc
!	!	!-F	Fe
A	A	a-U	Uv
Lug	Lug	lug-X	Xfev
,	,	,-F	Fi
tá	tá	bí-V	Vmip
pian	pian	pian-N	Ncfsc
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
bholg	bholg	bolg-V	Vmis
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
pian	pian	pian-N	Ncfsc
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
bholg	bholg	bolg-V	Vmis
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
an	an	an-T	Td-s
leithreas	leithreas	leithreas-N	Ncmsc
?	?	?-F	Fq
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
an	an	an-T	Td-s
leithreas	leithreas	leithreas-N	Ncmsc
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gug	Gug	Gug-N	Npmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
stop	stop	stop-V	Vmis
an	an	an-T	Td-s
roth	roth	roth-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ansin	Ansin	ansin-R	Rt|Rl
thall	thall	tall-V	Vmis
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Lug	Lug	lug-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
sé	sé	sé-P	Pp3msn
in	in	i-S	Sp
am	am	am-N	Ncmsc
againn	againn	ag-P	Pr1-p
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
abhaile	abhaile	abhaile-R	Rd
anois	anois	anois-R	Rt
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Lug	Lug	lug-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
tá	tá	bí-V	Vmip
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
,	,	,-F	Fi
cinnte	cinnte	cinn-A	Av
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gug	Gug	Gug-N	Npmsc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
abhaile	abhaile	abhaile-R	Rd
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
