Dath	Dath	dath-V	Vmm-2s
dubh	dubh	dubh-N	Ncmsc
nó	nó	nó-C	Cc
donn	donn	donn-N	Ncmpg|Ncmsc|Aqp
a	a	a-Q	Q-r
bhíonn	bhíonn	bí-V	Vmig
ar	ar	ar-S	Sp
na	na	na-T	Td-p
beacha	beacha	beach-N	Ncfpc
meala	meala	mil-N	Ncfsg
agus	agus	agus-C	Cc
bíonn	bíonn	bí-V	Vmig
bandaí	bandaí	bandach-A	Aqc
geala	geala	geal-A	Aq--pg|Aq--pc|Aq--pv
orthu	orthu	ar-P	Pr3-p
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
ar	ar	ar-S	Sp
fhad	fhad	fad-N	Ncmsc
.	.	.-F	Fe
Ceithre	Ceithre	ceathair-M	Mc
sciathán	sciathán	sciathán-N	Ncmsc
a	a	a-Q	Q-r
bhíonn	bhíonn	bí-V	Vmig
orthu	orthu	ar-P	Pr3-p
–	–	–-X	Xx
péire	péire	péire-N	Ncmsc
beag	beag	beag-A	Aq-msc
agus	agus	agus-C	Cc
péire	péire	péire-N	Ncmsg|Ncmsc
mór	mór	mór-N	Ncmpg
.	.	.-F	Fe
Sé	Sé	is-W	Wp-i-3
chos	chos	cos-N	Ncfsc
a	a	a-Q	Q-r
bhíonn	bhíonn	bí-V	Vmig
orthu	orthu	ar-P	Pr3-p
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
na	na	na-T	Td-p
cosa	cosa	cos-N	Ncfpc
deiridh	deiridh	deireadh-N	Ncmsg
níos	níos	níos-U	Uc
faide	faide	fada-A	Aqc
ná	ná	ná-C	Cc
na	na	na-T	Td-p
cosa	cosa	cos-N	Ncfpc
tosaigh	tosaigh	tosach-N	Ncmpc|Ncmsg
.	.	.-F	Fe
sciatháin	sciatháin	sciathán-N	Ncmpc
cosa	cosa	cos-N	Ncfpc
Buaileann	Buaileann	buail-V	Vmip
beacha	beacha	beach-N	Ncfpc
a	a	a-D	Dp3
sciatháin	sciatháin	sciathán-N	Ncmpc
‘	‘	‘-X	Xx
Dordán	Dordán	dordán-N	Ncmsc
’	’	’-F	Fa
a	a	a-Q	Q-r
thugtar	thugtar	tabhair-V	Vmip0
ar	ar	ar-S	Sp
an	an	an-T	Td-s
ngleo	ngleo	gleo-N	Ncmsc
a	a	a-Q	Q-r
dhéanann	dhéanann	déan-V	Vmip
bualadh	bualadh	buail-N	Ncmsc|Nv
sin	sin	sin-P	Pd|Dd
na	na	na-T	Td-p
sciathán	sciathán	sciathán-N	Ncmpg
.	.	.-F	Fe
Tugtar	Tugtar	tabhair-V	Vmip0
‘	‘	‘-X	Xx
coirceog	coirceog	coirceog-N	Ncfsc
’	’	’-F	Fa
ar	ar	ar-S	Sp
an	an	an-T	Td-s
áit	áit	áit-N	Ncfsc
ina	ina	i-S	Spr
maireann	maireann	mair-V	Vmip
na	na	na-T	Td-p
beacha	beacha	beach-N	Ncfpc
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
suas	suas	suas-R	Rd
i	i	i-S	Sp
gcoirceog	gcoirceog	coirceog-N	Ncfsc
mhór	mhór	mór-A	Aq-fsv|Aq-fsc
.	.	.-F	Fe
Seo	Seo	seo-W	W
coirceog	coirceog	coirceog-N	Ncfsc
a	a	a-Q	Q-r
thóg	thóg	tóg-V	Vmis
na	na	na-T	Td-p
beacha	beacha	beach-N	Ncfpc
iad	iad	iad-P	Pp3-p
féin	féin	féin-P	Px
.	.	.-F	Fe
Seo	Seo	seo-W	W
coirceog	coirceog	coirceog-N	Ncfsc
a	a	a-Q	Q-r
thóg	thóg	tóg-V	Vmis
duine	duine	duine-N	Ncmsc
.	.	.-F	Fe
Istigh	Istigh	istigh-R	Rl
sa	sa	i-S	Spa-s
choirceog	choirceog	coirceog-N	Ncfsc
bíonn	bíonn	bí-V	Vmig
an	an	an-T	Td-s
bhanríon	bhanríon	banríon-N	Ncfsc
na	na	na-T	Td-p
beacha	beacha	beach-N	Ncfpc
oibre	oibre	obair-N	Ncfsg|Nv--g--n
agus	agus	agus-C	Cc
na	na	na-T	Td-p
ladrainn	ladrainn	ladrann-N	Ncmpc
.	.	.-F	Fe
bhanríon	bhanríon	banríon-N	Ncfsc
amháin	amháin	amháin-A	Aqp
a	a	a-Q	Q-r
bhíonn	bhíonn	bí-V	Vmig
sa	sa	i-S	Spa-s
choirceog	choirceog	coirceog-N	Ncfsc
.	.	.-F	Fe
Ise	Ise	í-P	Pp3fs-e
a	a	a-Q	Q-r
bhíonn	bhíonn	bí-V	Vmig
i	i	i-S	Sp
gceannas	gceannas	ceannas-N	Ncmsc
ar	ar	ar-S	Sp
na	na	na-T	Td-p
beacha	beacha	beach-N	Ncfpc
sa	sa	i-S	Spa-s
choirceog	choirceog	coirceog-N	Ncfsc
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
cealg	cealg	cealg-N	Ncfsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
mbanríon	mbanríon	banríon-N	Ncfsc
.	.	.-F	Fe
Baineann	Baineann	bain-V	Vmip
sí	sí	sí-P	Pp3fsn
úsáid	úsáid	úsáid-N	Ncfsc|Nv
as	as	as-S	Sp
an	an	an-T	Td-s
gcealg	gcealg	cealg-N	Ncfsc
chun	chun	chun-S	Sp
banríona	banríona	banríon-N	Ncfsg
eile	eile	eile-D	Dd
sa	sa	i-S	Spa-s
choirceog	choirceog	coirceog-N	Ncfsc
a	a	a-U	U
mharú	mharú	maraigh-N	Nv
.	.	.-F	Fe
A	A	a-U	Um
trí	trí	trí-M	Mc
nó	nó	nó-C	Cc
a	a	a-U	Um
ceathair	ceathair	ceathair-M	Mc
de	de	de-S	Sp
bhlianta	bhlianta	bliain-N	Ncfpc
a	a	a-Q	Q-r
mhaireann	mhaireann	mair-V	Vmip
an	an	an-T	Td-s
bhanríon	bhanríon	banríon-N	Ncfsc
de	de	de-S	Sp
ghnáth	ghnáth	gnáth-N	Ncmsc
.	.	.-F	Fe
Tugtar	Tugtar	tabhair-V	Vmip0
‘	‘	‘-X	Xx
cráinbheach	cráinbheach	cráinbheach-N	Ncfsc
’	’	’-F	Fa
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbanríon	mbanríon	banríon-N	Ncfsc
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
.	.	.-F	Fe
an	an	an-T	Td-s
bhanríon	bhanríon	banríon-N	Ncfsc
cealla	cealla	cill-N	Ncfpc
céarach	céarach	céir-N	Ncfsg
Is	Is	is-W	Wpri
í	í	í-P	Pp3fs
an	an	an-T	Td-s
bhanríon	bhanríon	banríon-N	Ncfsc
a	a	a-Q	Q-r
bheireann	bheireann	beir-V	Vmip
na	na	na-T	Td-p
huibheacha	huibheacha	ubh-N	Ncfpc
as	as	as-P	Pr3ms
a	a	a-Q	Q-p
dtagann	dtagann	tar-V	Vmip
na	na	na-T	Td-p
beacha	beacha	beach-N	Ncfpc
óga	óga	óg-A	Aq--pc|Aq--pv|Aq--pc|Aq--pg
.	.	.-F	Fe
Sna	Sna	i-S	Spa-p
cealla	cealla	cill-N	Ncfpc
céarach	céarach	céir-N	Ncfsg
a	a	a-Q	Q-r
bheireann	bheireann	beir-V	Vmip
sí	sí	sí-P	Pp3fsn
na	na	na-T	Td-p
huibheacha	huibheacha	ubh-N	Ncfpc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéadfadh	fhéadfadh	féad-V	Vmc
a	a	a-U	U
bhreith	bhreith	beir-N	Nv
in aghaidh	in aghaidh	in_aghaidh-S	Spc
an	an	an-T	Td-s
lae	lae	lá-N	Ncmsg
i	i	i-S	Sp
Mí	Mí	Mí-N	Npfsc
Aibreáin	Aibreáin	Aibreán-N	Ncmsg
agus	agus	agus-C	Cc
i	i	i-S	Sp
Mí	Mí	Mí-N	Npfsc
na	na	na-T	Tdfsg
Bealtaine	Bealtaine	Bealtaine-N	Ncfsg
.	.	.-F	Fe
Tagann	Tagann	tar-V	Vmip
larbhaí	larbhaí	larbha-N	Ncmpc
as	as	as-S	Sp
na	na	na-T	Td-p
huibheacha	huibheacha	ubh-N	Ncfpc
tar éis	tar éis	tar_éis-S	Spc
trí	trí	trí-M	Mc
lá	lá	lá-N	Ncmsc
.	.	.-F	Fe
Fásann	Fásann	fás-V	Vmip
na	na	na-T	Td-p
larbhaí	larbhaí	larbha-N	Ncmpc
istigh	istigh	istigh-R	Rl
sna	sna	i-S	Spa-p
cealla	cealla	cill-N	Ncfpc
céarach	céarach	céir-N	Ncfsg
nó	nó	nó-C	Cc
go	go	go-Q	Q
mbíonn	mbíonn	bí-V	Vmig
siad	siad	siad-P	Pp3-pn
ina	ina	i-S	Spp-p
mbeacha	mbeacha	beach-N	Ncfpc
óga	óga	óg-A	Aq--pc|Aq--pv|Aq--pc|Aq--pg
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
tar éis	tar éis	tar_éis-S	Spc
cúpla	cúpla	cúpla-N	Ncmsg
seachtaine	seachtaine	seachtain-N	Ncfsg
tagann	tagann	tar-V	Vmip
na	na	na-T	Td-p
beacha	beacha	beach-N	Ncfpc
óga	óga	óg-A	Aq--pc
amach	amach	amach-R	Rd
as	as	as-S	Sp
na	na	na-T	Td-p
cealla	cealla	cill-N	Ncfpc
céarach	céarach	céir-N	Ncfsg
.	.	.-F	Fe
larbha	larbha	larbha-N	Ncmsc
beach	beach	beach-N	Ncfsc
óg	óg	óg-A	Aq-fsc
Is	Is	is-W	Wpri
beacha	beacha	beach-N	Ncfpc
baineanna	baineanna	bain-N	Ncmpc|Ncfpc
iad	iad	iad-P	Pp3-p
na	na	na-T	Td-p
beacha	beacha	beach-N	Ncfpc
oibre	oibre	obair-N	Ncfsg|Nv--g--n
ach	ach	ach-C	Cs
ní	ní	is-W	Wp-in
bheireann	bheireann	beir-V	Vmip
siad	siad	siad-P	Pp3-pn
aon	aon	aon-D	Dq
uibheacha	uibheacha	ubh-N	Ncfpc
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
tuairim	tuairim	tuairim-N	Ncfsc
is	is	agus-C	Cc
sa	sa	i-S	Spa-s
gheimhreadh	gheimhreadh	geimhreadh-N	Ncmsc
agus	agus	agus-C	Cc
tuairim	tuairim	tuairim-N	Ncfsc
is	is	agus-C	Cc
Bíonn	Bíonn	bí-V	Vmig
cealg	cealg	cealg-N	Ncfsc
ag	ag	ag-S	Sp
na	na	na-T	Td-p
beacha	beacha	beach-N	Ncfpc
oibre	oibre	obair-N	Ncfsg|Nv--g--n
.	.	.-F	Fe
Baineann	Baineann	bain-V	Vmip
siad	siad	siad-P	Pp3-pn
úsáid	úsáid	úsáid-N	Ncfsc|Nv
as	as	as-S	Sp
an	an	an-T	Td-s
gcealg	gcealg	cealg-N	Ncfsc
chun	chun	chun-S	Sp
iad	iad	iad-P	Pp3-p
féin	féin	féin-P	Px
a	a	a-U	U
chosaint	chosaint	cosain-N	Nv
.	.	.-F	Fe
beacha	beacha	beach-N	Ncfpc
oibre	oibre	obair-N	Ncfsg|Nv--g--n
an	an	an-T	Td-s
bhanríon	bhanríon	banríon-N	Ncfsc
Bíonn	Bíonn	bí-V	Vmig
na	na	na-T	Td-p
beacha	beacha	beach-N	Ncfpc
oibre	oibre	obair-N	Ncfsg|Nv--g--n
níos	níos	níos-U	Uc
lú	lú	beag-A	Aqc
ná	ná	ná-C	Cs
an	an	is-W	Wpdq|Wp-q
bhanríon	bhanríon	banríon-N	Ncfsc
.	.	.-F	Fe
Tuairim	Tuairim	tuairim-N	Ncfsc
is	is	agus-C	Cc
leathbhliain	leathbhliain	leathbhliain-N	Ncfsc
a	a	a-Q	Q-r
mhaireann	mhaireann	mair-V	Vmip
na	na	na-T	Td-p
beacha	beacha	beach-N	Ncfpc
oibre	oibre	obair-N	Ncfsg|Nv--g--n
de	de	de-S	Sp
ghnáth	ghnáth	gnáth-N	Ncmsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
iad	iad	iad-P	Pp3-p
na	na	na-T	Td-p
beacha	beacha	beach-N	Ncfpc
oibre	oibre	obair-N	Ncfsg|Nv--g--n
a	a	a-Q	Q-r
dhéanann	dhéanann	déan-V	Vmip
an	an	an-T	Td-s
obair	obair	obair-N	Ncfsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
iad	iad	iad-P	Pp3-p
a	a	a-Q	Q-r
bhailíonn	bhailíonn	bailigh-V	Vmip
neachtar	neachtar	neachtar-P	Pi|Ncmsc
,	,	,-F	Fi
pailin	pailin	pailin-N	Ncfsc
agus	agus	agus-C	Cc
uisce	uisce	uisce-N	Ncmsg|Ncmsc|Ncmsg
ó	ó	ó-S	Sp
na	na	na-T	Td-p
bláthanna	bláthanna	bláth-N	Ncmpc
le	le	le-S	Sp
tabhairt	tabhairt	tabhair-N	Nv
ar ais	ar ais	ar_ais-R	Rd
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
choirceog	choirceog	coirceog-N	Ncfsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
iad	iad	iad-P	Pp3-p
a	a	a-Q	Q-r
thugann	thugann	tabhair-V	Vmip
bia	bia	bia-N	Ncmsc
don	don	do-S	Spa-s
larbha	larbha	larbha-N	Ncmsc
agus	agus	agus-C	Cc
don	don	do-S	Spa-s
bhanríon	bhanríon	banríon-N	Ncfsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
iad	iad	iad-P	Pp3-p
na	na	na-T	Td-p
beacha	beacha	beach-N	Ncfpc
oibre	oibre	obair-N	Ncfsg|Nv--g--n
a	a	a-Q	Q-r
ghlanann	ghlanann	glan-V	Vmip
an	an	an-T	Td-s
choirceog	choirceog	coirceog-N	Ncfsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
iad	iad	iad-P	Pp3-p
a	a	a-Q	Q-r
dhéanann	dhéanann	déan-V	Vmip
na	na	na-T	Td-p
cíora	cíora	cíor-N	Ncfpc
meala	meala	mil-N	Ncfsg
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
na	na	na-T	Td-p
beacha	beacha	beach-N	Ncfpc
oibre	oibre	obair-N	Ncfsg|Nv--g--n
ina	ina	i-S	Spp-p
ngardaí	ngardaí	garda-N	Ncmpc
ag	ag	ag-S	Sp
‘	‘	‘-X	Xx
doras	doras	doras-N	Ncmsc
’	’	’-F	Fa
na	na	na-T	Tdfsg
coirceoige	coirceoige	coirceog-N	Ncfsg
agus	agus	agus-C	Cc
buaileann	buaileann	buail-V	Vmip
siad	siad	siad-P	Pp3-pn
a	a	a-D	Dp3
sciatháin	sciatháin	sciathán-N	Ncmpc
chun	chun	chun-S	Sp
aer	aer	aer-N	Ncmpg
úr	úr	úr-A	Aqp
a	a	a-U	U
scaoileadh	scaoileadh	scaoil-N	Nv
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
choirceog	choirceog	coirceog-N	Ncfsc
.	.	.-F	Fe
Déanann	Déanann	déan-V	Vmip
na	na	na-T	Td-p
beacha	beacha	beach-N	Ncfpc
oibre	oibre	obair-N	Ncfsg|Nv--g--n
rince	rince	rinc-N	Nv|Ncfsg|Nv--g|Ncfsg|Ncmsg|Nv--g|Ncmsg|Ncmsc|Nv--g|Nv
chun	chun	chun-S	Sp
a	a	a-U	U
chur	chur	cuir-N	Nv
in	in	i-S	Sp
iúl	iúl	iúl-N	Ncmsc
dá	dá	do-S	Spp-s
chéile	chéile	céile-N	Ncmsc
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
bia	bia	bia-N	Ncmsc
le	le	le-S	Sp
fáil	fáil	faigh-N	Nv
in	in	i-S	Sp
áit	áit	áit-N	Ncfsc
áirithe	áirithe	áirigh-A	Aqp|Av
.	.	.-F	Fe
choirceog	choirceog	coirceog-N	Ncfsc
i lár	i lár	i_lár-S	Spc
an	an	an-T	Td-s
tsamhraidh	tsamhraidh	samhradh-N	Ncmsg
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
bhíonn	bhíonn	bí-V	Vmig---n
aon	aon	aon-D	Dq
ladrainn	ladrainn	ladrann-N	Ncmpc
ann	ann	i-R	Rl|Pr3ms
sa	sa	i-S	Spa-s
gheimhreadh	gheimhreadh	geimhreadh-N	Ncmsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
beacha	beacha	beach-N	Ncfpc
fireanna	fireanna	fir-N	Ncmpc|Ncfpc
iad	iad	iad-P	Pp3-p
na	na	na-T	Td-p
ladrainn	ladrainn	ladrann-N	Ncmpc
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
bhíonn	bhíonn	bí-V	Vmig---n
aon	aon	aon-D	Dq
rud	rud	rud-N	Ncmsc
eile	eile	eile-D	Dd
le	le	le-S	Sp
déanamh	déanamh	déan-N	Nv
acu	acu	ag-P	Pr3-p
seachas	seachas	seachas-S	Sp
cúpláil	cúpláil	cúpláil-N	Ncfsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbanríon	mbanríon	banríon-N	Ncfsc
.	.	.-F	Fe
Faigheann	Faigheann	faigh-V	Vmip
na	na	na-T	Td-p
ladrainn	ladrainn	ladrann-N	Ncmpc
bás	bás	bás-N	Ncmsc
tar éis	tar éis	tar_éis-S	Spc
na	na	na-T	Tdfsg
cúplála	cúplála	cúpláil-N	Ncfsg
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
súile	súile	súil-N	Ncfpc
móra	móra	mór-A	Aq--pc
ag	ag	ag-S	Sp
na	na	na-T	Td-p
ladrainn	ladrainn	ladrann-N	Ncmpc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
bhíonn	bhíonn	bí-V	Vmig---n
aon	aon	aon-D	Dq
chealg	chealg	cealg-N	Ncfsc
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhíonn	bhíonn	bí-V	Vmig
an	an	an-T	Td-s
bia	bia	bia-N	Ncmsc
gann	gann	gann-A	Aq-msc
i	i	i-S	Sp
dtús	dtús	tús-N	Ncmsc
an	an	an-T	Td-s
gheimhridh	gheimhridh	geimhreadh-N	Ncmsg
cuireann	cuireann	cuir-V	Vmip
na	na	na-T	Td-p
beacha	beacha	beach-N	Ncfpc
oibre	oibre	obair-N	Ncfsg|Nv--g--n
ruaig	ruaig	ruaig-V	Vmis
ar	ar	ar-S	Sp
na	na	na-T	Td-p
ladrainn	ladrainn	ladrann-N	Ncmpc
as	as	as-S	Sp
an	an	an-T	Td-s
gcoirceog	gcoirceog	coirceog-N	Ncfsc
.	.	.-F	Fe
Faigheann	Faigheann	faigh-V	Vmip
na	na	na-T	Td-p
ladrainn	ladrainn	ladrann-N	Ncmpc
bás	bás	bás-N	Ncmsc
ansin	ansin	ansin-R	Rt|Rl
.	.	.-F	Fe
Déanann	Déanann	déan-V	Vmip
na	na	na-T	Td-p
beacha	beacha	beach-N	Ncfpc
oibre	oibre	obair-N	Ncfsg|Nv--g--n
neachtar	neachtar	neachtar-N	Ncmpg|Pi|Ncmpg|Ncmsc
a	a	a-U	U
shú	shú	súigh-N	Nv
as	as	as-S	Sp
bláthanna	bláthanna	bláth-N	Ncmpc
lena	lena	le-S	Spp-p
dteanga	dteanga	teanga-N	Ncfsc
fada	fada	fada-A	Aqp
.	.	.-F	Fe
Stórálann	Stórálann	stóráil-V	Vmip
siad	siad	siad-P	Pp3-pn
neachtar	neachtar	neachtar-P	Pi
ansin	ansin	ansin-R	Rt|Rl
i	i	i-S	Sp
sac	sac	sac-N	Ncmsc
atá	atá	bí-V	Vmip---r
acu	acu	ag-P	Pr3-p
ina	ina	i-S	Spp-p
mbolg	mbolg	bolg-N	Ncmsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhíonn	bhíonn	bí-V	Vmig
an	an	an-T	Td-s
sac	sac	sac-N	Ncmsc
lán	lán	lán-A	Aq-msc
de	de	de-S	Sp
neachtar	neachtar	neachtar-N	Ncmsc
acu	acu	ag-P	Pr3-p
filleann	filleann	fill-V	Vmip
siad	siad	siad-P	Pp3-pn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcoirceog	gcoirceog	coirceog-N	Ncfsc
.	.	.-F	Fe
Tógann	Tógann	tóg-V	Vmip
beacha	beacha	beach-N	Ncfpc
oibre	oibre	obair-N	Ncfsg|Nv--g--n
na	na	na-T	Tdfsg
coirceoige	coirceoige	coirceog-N	Ncfsg
neachtar	neachtar	neachtar-P	Pi
agus	agus	agus-C	Cc
déanann	déanann	déan-V	Vmip
siad	siad	siad-P	Pp3-pn
mil	mil	mil-N	Ncfsc
as	as	as-P	Pr3ms
.	.	.-F	Fe
Stóráiltear	Stóráiltear	stóráil-V	Vmip0
an	an	an-T	Td-s
mhil	mhil	mil-N	Ncfsc
sa	sa	i-S	Spa-s
chíor	chíor	cíor-N	Ncfsc
meala	meala	mil-N	Ncfsg
.	.	.-F	Fe
I	I	i-S	Sp
gcaitheamh	gcaitheamh	caitheamh-N	Ncmsc
an	an	an-T	Td-s
gheimhridh	gheimhridh	geimhreadh-N	Ncmsg
itheann	itheann	ith-V	Vmip
na	na	na-T	Td-p
beacha	beacha	beach-N	Ncfpc
mil	mil	mil-N	Ncfsc
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
níos	níos	níos-U	Uc
mó	mó	mór-A	Aqc
meala	meala	mil-N	Ncfsg
ag	ag	ag-S	Sp
na	na	na-T	Td-p
beacha	beacha	beach-N	Ncfpc
ná	ná	ná-C	Cs|Cc
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bhíonn	bhíonn	bí-V	Vmig
ag	ag	ag-S	Sp
teastáil	teastáil	teastaigh-N	Nv
uathu	uathu	ó-P	Pr3-p
.	.	.-F	Fe
Tugann	Tugann	tabhair-V	Vmip
an	an	an-T	Td-s
coimeádaí	coimeádaí	coimeádaí-N	Ncmsc
beach	beach	beach-X	Xfev
cuid	cuid	cuid-N	Ncfsc
den	den	de-S	Spa-s
mhil	mhil	mil-N	Ncfsc
leis	leis	le-P	Pr3ms
as	as	as-S	Sp
an	an	an-T	Td-s
gcoirceog	gcoirceog	coirceog-N	Ncfsc
.	.	.-F	Fe
Fágann	Fágann	fág-V	Vmip
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
oiread	oiread	oiread-N	Ns-s
ag	ag	ag-S	Sp
na	na	na-T	Td-p
beacha	beacha	beach-N	Ncfpc
is	is	agus-C	Cc
a	a	a-Q	Q-r
bheathóidh	bheathóidh	beathaigh-V	Vmif
iad	iad	iad-P	Pp3-p
i	i	i-S	Sp
gcaitheamh	gcaitheamh	caitheamh-N	Ncmsc
an	an	an-T	Td-s
gheimhridh	gheimhridh	geimhreadh-N	Ncmsg
.	.	.-F	Fe
Is	Is	is-W	Wp-i
gá	gá	gá-N	Ncmsc
don	don	do-S	Spa-s
choimeádaí	choimeádaí	coimeádaí-N	Ncmsc
beach	beach	beach-N	Ncfpg|Ncfsc|Xfen
a	a	a-U	U
bheith	bheith	bí-N	Nv
an-chúramach	an-chúramach	cúramach-A	Aqp
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
tógáil	tógáil	tóg-N	Nv
na	na	na-T	Tdfsg
meala	meala	mil-N	Ncfsg
as	as	as-S	Sp
an	an	an-T	Td-s
gcoirceog	gcoirceog	coirceog-N	Ncfsc
.	.	.-F	Fe
Caitheann	Caitheann	caith-V	Vmip
sé	sé	sé-P	Pp3msn
éide	éide	éide-N	Ncfsc
chosanta	chosanta	cosain-A	Av
ionas	ionas	ionas-N	Ns-s
nach	nach	nach-Q	Qnr
gcuirfidh	gcuirfidh	cuir-V	Vmif
na	na	na-T	Td-p
beacha	beacha	beach-N	Ncfpc
cealg	cealg	cealg-N	Ncfpg|Ncfsc
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Baineann	Baineann	bain-V	Vmip
sé	sé	sé-P	Pp3msn
úsáid	úsáid	úsáid-N	Ncfsc|Nv
as	as	as-S	Sp
deatach	deatach	deatach-N	Ncmsc
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
.	.	.-F	Fe
Is	Is	is-W	Wp-i
féidir	féidir	féidir-N	Ns-s
deoch	deoch	deoch-N	Ncfsc
dheas	dheas	deas-A	Aq-fsc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
le	le	le-S	Sp
mil	mil	mil-N	Ncfsc
.	.	.-F	Fe
