Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-U	Um
deich	deich	deich-M	Mc
a	a	an-T	Td-s
chlog	chlog	clog-N	Ncmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
abhaile	abhaile	abhaile-R	Rd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
Gearóid	Gearóid	Gearóid-N	Npmsc
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
le	le	le-S	Sp
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
mé	mé	mé-P	Pp1-s
le	le	le-S	Sp
tamall	tamall	tamall-N	Ncmsc
é	é	é-P	Pp3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seans	Seans	seans-N	Ncmsc
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
sé	sé	sé-P	Pp3msn
fós	fós	fós-R	Rg
os comhair	os comhair	os_comhair-S	Spc
na	na	na-T	Tdfsg
teilifíse	teilifíse	teilifís-N	Ncfsg
.	.	.-F	Fe
’	’	’-F	Fa
Chuaigh	Chuaigh	téigh-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
seomra	seomra	seomra-N	Ncmsc
suite	suite	suigh-A	Aqp|Av
agus	agus	agus-C	Cc
chonaic	chonaic	feic-V	Vmis
sí	sí	sí-P	Pp3fsn
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
ceart	ceart	ceart-N	Ncmsc
ag	ag	ag-S	Sp
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
fós	fós	fós-R	Rg
os comhair	os comhair	os_comhair-S	Spc
na	na	na-T	Tdfsg
teilifíse	teilifíse	teilifís-N	Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nach	Nach	nach-Q	Qnr|Qnq
bhfuil	bhfuil	bí-V	Vmip---d|Vmip---n
sé	sé	sé-P	Pp3msn
thar	thar	thar-S	Sp
am	am	am-N	Ncmsc
agatsa	agatsa	ag-P	Pr2-s-e
a	a	a-U	U
bheith	bheith	bí-N	Nv
sa	sa	i-S	Spa-s
leaba	leaba	leaba-N	Ncfsc
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
is	is	is-W	Wp-i
maith	maith	maith-A	Aqp
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
clár	clár	clár-N	Ncmsc
seo	seo	seo-D	Dd
,	,	,-F	Fi
a	a	a-U	Uv
Mhamaí	Mhamaí	mama-N	Ncfsv|Ncmpv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
sé	sé	sé-P	Pp3msn
thart	thart	thart-R	Rd
taobh istigh	taobh istigh	taobh_istigh-R	Rl
de	de	de-S	Sp
leathuair	leathuair	leathuair-N	Ncfsc
an	an	an-T	Td-s
chloig	chloig	clog-N	Ncmsg
.	.	.-F	Fe
’	’	’-F	Fa
Isteach	Isteach	isteach-R	Rd
le	le	le-S	Sp
Daidí	Daidí	daidí-N	Ncmsc
ansin	ansin	ansin-R	Rt|Rl
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nach	Nach	nach-Q	Qnr|Qnq
bhfuil	bhfuil	bí-V	Vmip---d|Vmip---n
cluiche	cluiche	cluiche-N	Ncmsc
iomána	iomána	iomáin-N	Ncfsg|Nv--g
agatsa	agatsa	ag-P	Pr2-s-e
amárach	amárach	amárach-N	Ns-s
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
le	le	le-S	Sp
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Díreach	Díreach	díreach-N	Ncmsc
tar éis	tar éis	tar_éis-S	Spc
na	na	na-T	Tdfsg
scoile	scoile	scoil-N	Ncfsg
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Bhuel	Bhuel	bhuel-X	Xsc
,	,	,-F	Fi
b	b	b-X	Xl
’	’	’-F	Fa
fhearr	fhearr	maith-A	Aqc
duit	duit	do-P	Pr2-s
dul	dul	dul-N	Ncmsc
a	a	a-U	U
chodladh	chodladh	codail-N	Nv
anois	anois	anois-R	Rt
nó	nó	nó-C	Cc
beidh	beidh	bí-V	Vmif
tú	tú	tú-P	Pp2-s
tuirseach	tuirseach	tuirseach-A	Aqp
amárach	amárach	amárach-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
mó	mó	mó-A	Aqc|Aqp
ná	ná	ná-C	Cs|Cc
sásta	sásta	sásta-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
a	a	a-U	Uv
Mhamaí	Mhamaí	mamaí-N	Ncmpv|Ncfsv
…	…	…-F	Fi
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
bac	bac	bac-V	Vmm-2s-n
le	le	le-S	Sp
do	do	do-D	Dp2-s
ach	ach	ach-C	Cs
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
sí	sí	sí-P	Pp3fsn
as	as	as-S	Sp
an	an	an-T	Td-s
teilifís	teilifís	teilifís-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Oíche	Oíche	oíche-N	Ncfsc
mhaith	mhaith	maith-A	Aq-fsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
agus	agus	agus-C	Cc
isteach	isteach	isteach-R	Rd
leis	leis	le-P	Pr3ms
ina	ina	i-S	Spp-s
sheomra	sheomra	seomra-N	Ncmsc
codlata	codlata	codail-A	Av
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
istigh	istigh	istigh-R	Rl
sa	sa	i-S	Spa-s
leaba	leaba	leaba-N	Ncfsc
thosaigh	thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
léamh	léamh	léigh-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an-spéis	an-spéis	spéis-N	Ncfsc
aige	aige	ag-P	Pr3ms
sa	sa	i-S	Spa-s
leabhar	leabhar	leabhar-N	Ncmsc
ach	ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
tuirseach	tuirseach	tuirseach-A	Aqp
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
léite	léite	léigh-A	Av
aige	aige	ag-P	Pr3ms
ach	ach	ach-S	Sp
cúpla	cúpla	cúpla-N	Ncmsc
leathanach	leathanach	leathanach-N	Ncmpg
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
thit	thit	tit-V	Vmis
an	an	an-T	Td-s
leabhar	leabhar	leabhar-N	Ncmsc
as	as	as-P	Pr3ms
a	a	a-D	Dp3
lámh	lámh	lámh-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
ina	ina	i-S	Spp-s
chodladh	chodladh	codladh-N	Ncfsc
go	go	go-U	Ua
sámh	sámh	sámh-A	Aqp
!	!	!-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
tháinig	tháinig	tar-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
isteach	isteach	isteach-R	Rd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Oíche	Oíche	oíche-N	Ncfsc
mhaith	mhaith	maith-A	Aq-fsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
níor	níor	is-W	Ws-in
fhreagair	fhreagair	freagair-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
í	í	í-P	Pp3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
chodladh	chodladh	codladh-N	Ncfsc
go	go	go-U	Ua
sámh	sámh	sámh-A	Aqp
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
dún	dún	dún-N	Ncmsc
mór	mór	mór-A	Aq-msc
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
uaidh	uaidh	ó-P	Pr3ms
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
pháirc	pháirc	páirc-N	Ncfsc
os comhair	os comhair	os_comhair-S	Spc
an	an	an-T	Td-s
dúin	dúin	dún-N	Ncmsg
chonaic	chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
buachaill	buachaill	buachaill-N	Ncmsc
ag	ag	ag-S	Sp
imirt	imirt	imir-N	Nv
iomána	iomána	iomáin-N	Ncfsg|Nv--g
.	.	.-F	Fe
‘	‘	‘-X	Xx
Sin	Sin	sin-W	W
é	é	é-P	Pp3ms
Cú	Cú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
tá	tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
imirt	imirt	imir-N	Nv
iomána	iomána	iomáin-N	Ncfsg|Nv--g
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liom	liom	le-P	Pr1-s
cluiche	cluiche	cluiche-N	Ncmsc
iomána	iomána	iomáin-N	Ncfsg|Nv--g
a	a	a-U	U
bheith	bheith	bí-N	Nv
agam	agam	ag-P	Pr1-s
le	le	le-S	Sp
Cú	Cú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Rachaidh	Rachaidh	téigh-V	Vmif
mé	mé	mé-P	Pp1-s
go	go	go-S	Sp
hEamhain	hEamhain	hEamhain-N	Nc
Mhacha	Mhacha	Macha-N	Npmsg|Npmsc|Npmsg
.	.	.-F	Fe
’	’	’-F	Fa
Suas	Suas	suas-R	Rd
san	san	i-S	Spa-s
aer	aer	aer-N	Ncmsc
le	le	le-S	Sp
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmis
sé	sé	sé-P	Pp3msn
leis	leis	le-P	Pr3ms
thar	thar	thar-S	Sp
choillte	choillte	coill-N	Ncfpc
agus	agus	agus-C	Cc
thar	thar	thar-S	Sp
ghleannta	ghleannta	gleann-N	Ncmpc
,	,	,-F	Fi
thar	thar	thar-S	Sp
locha	locha	loch-N	Ncmsg
agus	agus	agus-C	Cc
thar	thar	thar-S	Sp
aibhneacha	aibhneacha	abhainn-N	Ncfpc
nó	nó	nó-C	Cc
gur	gur	gur-Q	Q--s
shroich	shroich	sroich-V	Vmis
sé	sé	sé-P	Pp3msn
Eamhain	Eamhain	Eamhain-N	Npmsc
Mhacha	Mhacha	Mhacha-N	Npmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
shroich	shroich	sroich-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
Eamhain	Eamhain	Eamhain-N	Npmsc
Mhacha	Mhacha	Mhacha-N	Npmsc
tásc	tásc	tásc-N	Ncmpg|Ncmsc
ná	ná	ná-C	Cs|Cc
tuairisc	tuairisc	tuairisc-N	Ncfsc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ar	ar	ar-S	Sp
Chú	Chú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
fear	fear	fear-N	Ncmsc
ag	ag	ag-S	Sp
marcaíocht	marcaíocht	marcaigh-N	Nv
ar	ar	ar-S	Sp
chapall	chapall	capall-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfaca	bhfaca	feic-V	Vmis---d
tú	tú	tú-P	Pp2-s
Cú	Cú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
leis	leis	le-S	Sp
an	an	an-T	Td-s
bhfear	bhfear	fear-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
.	.	.-F	Fe
Tamall	Tamall	tamall-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|Dd
chonaic	chonaic	feic-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
buachaill	buachaill	buachaill-N	Ncmsc
óg	óg	óg-A	Aq-msc
ag	ag	ag-S	Sp
imirt	imirt	imir-N	Nv
iomána	iomána	iomáin-N	Ncfsg|Nv--g
lena	lena	le-S	Spp-s
athair	athair	athair-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfaca	bhfaca	feic-V	Vmis---d
sibh	sibh	sibh-P	Pp2-p
Cú	Cú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbeirt	mbeirt	beirt-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Chonaiceamar	Chonaiceamar	feic-V	Vmis1p
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
faire	faire	fair-N	Nv
an	an	an-T	Td-s
dúin	dúin	dún-N	Ncmsg
!	!	!-F	Fe
Ach	Ach	ach-C	Cs
cé	cé	cé-W	W--q
thusa	thusa	tú-P	Pp2-s-e
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Gearóid	Gearóid	Gearóid-N	Npmsc
atá	atá	bí-V	Vmip---r
ormsa	ormsa	ar-P	Pr1-s-e
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
agus	agus	agus-C	Cc
ba	ba	is-W	Wsri
mhaith	mhaith	maith-A	Aqp
liom	liom	le-P	Pr1-s
cluiche	cluiche	cluiche-N	Ncmsc
iomána	iomána	iomáin-N	Ncfsg|Nv--g
a	a	a-U	U
bheith	bheith	bí-N	Nv
agam	agam	ag-P	Pr1-s
le	le	le-S	Sp
Cú	Cú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
imreoir	imreoir	imreoir-N	Ncmsc
níos	níos	níos-U	Uc
fearr	fearr	maith-A	Aqc
ná	ná	ná-C	Cs|Cc
Cú	Cú	cú-N	Ncmsc|Ncmsg
Chulainn	Chulainn	Culann-N	Npm-g
sa	sa	i-S	Spa-s
chúige	chúige	cúige-N	Ncmsc
seo	seo	seo-D	Dd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
imreoir	imreoir	imreoir-N	Ncmsc
níos	níos	níos-U	Uc
fearr	fearr	maith-A	Aqc
ná	ná	ná-C	Cs|Cc
é	é	é-P	Pp3ms
in	in	i-S	Sp
Éirinn	Éirinn	Éire-N	Npfsd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
buachaill	buachaill	buachaill-N	Ncmsc
óg	óg	óg-A	Aq-msc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Go	Go	go-S	Sp
n-éirí	n-éirí	éirí-N	Ncmsc
an	an	an-T	Td-s
t-ádh	t-ádh	ádh-N	Ncmsc
leat	leat	le-P	Pr2-s
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
maith	maith	maith-N	Ncfsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
sé	sé	sé-P	Pp3msn
aghaidh	aghaidh	aghaidh-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
dún	dún	dún-N	Ncmsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
shroich	shroich	sroich-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
an	an	an-T	Td-s
dún	dún	dún-N	Ncmsc
bhuail	bhuail	buail-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
ngeata	ngeata	geata-N	Ncmsc
mór	mór	mór-A	Aq-msc
lena	lena	le-S	Spp-s
chamán	chamán	camán-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmm-2s
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
,	,	,-F	Fi
Conchúr	Conchúr	Conchúr-N	Npmsc
Mac	Mac	Mac-U	Up
Neasa	Neasa	Neasa-N	Np|Npfsc
,	,	,-F	Fi
an	an	an-T	Td-s
geata	geata	geata-N	Ncmsg|Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cé	Cé	cé-W	W--q
thusa	thusa	tú-P	Pp2-s-e
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
Gearóid	Gearóid	Gearóid-N	Npmsc
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
taobh amuigh	taobh amuigh	taobh_amuigh-R	Rl
.	.	.-F	Fe
‘	‘	‘-X	Xx
Gearóid	Gearóid	Gearóid-N	Npmsc
atá	atá	bí-V	Vmip---r
ormsa	ormsa	ar-P	Pr1-s-e
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
agus	agus	agus-C	Cc
ba	ba	is-W	Wsri
mhaith	mhaith	maith-A	Aqp
liom	liom	le-P	Pr1-s
cluiche	cluiche	cluiche-N	Ncmsc
iomána	iomána	iomáin-N	Ncfsg|Nv--g
a	a	a-U	U
bheith	bheith	bí-N	Nv
agam	agam	ag-P	Pr1-s
le	le	le-S	Sp
Cú	Cú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
.	.	.-F	Fe
’	’	’-F	Fa
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
Conchúr	Conchúr	Conchúr-N	Npmsc
Mac	Mac	Mac-U	Up
Neasa	Neasa	Neasa-N	Np|Npfsc
é	é	é-P	Pp3ms
seo	seo	seo-P	Pd
thosaigh	thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
gáire	gáire	gáir-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
imreoir	imreoir	imreoir-N	Ncmsc
níos	níos	níos-U	Uc
fearr	fearr	maith-A	Aqc
ná	ná	ná-C	Cs|Cc
Cú	Cú	cú-N	Ncmsc|Ncmsg
Chulainn	Chulainn	Culann-N	Npm-g
sa	sa	i-S	Spa-s
chúige	chúige	cúige-N	Ncmsc
seo	seo	seo-D	Dd
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
Chuala	Chuala	clois-V	Vmis
Cú	Cú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
imreoir	imreoir	imreoir-N	Ncmsc
níos	níos	níos-U	Uc
fearr	fearr	maith-A	Aqc
ná	ná	ná-C	Cs|Cc
mé	mé	mé-P	Pp1-s
in	in	i-S	Sp
Éirinn	Éirinn	Éire-N	Npfsd
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
beidh	beidh	bí-V	Vmif
cluiche	cluiche	cluiche-N	Ncmsc
agam	agam	ag-P	Pr1-s
leat	leat	le-P	Pr2-s
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
féin	féin	féin-P	Px
.	.	.-F	Fe
’	’	’-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
imir	imir	imir-N	Ncfsc
Gearóid	Gearóid	Gearóid-N	Npm-g|Npmsg|Npmsc
agus	agus	agus-C	Cc
Cú	Cú	cú-N	Ncmsc|Ncmsg
Chulainn	Chulainn	Culann-N	Npm-g
cluiche	cluiche	cluiche-N	Ncmsg|Ncmsc
iomána	iomána	iomáin-N	Ncfsg|Nv--g
sa	sa	i-S	Spa-s
pháirc	pháirc	páirc-N	Ncfsc
os comhair	os comhair	os_comhair-S	Spc
an	an	an-T	Td-s
dúin	dúin	dún-N	Ncmsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an-chluiche	an-chluiche	cluiche-N	Ncmsc
ag	ag	ag-S	Sp
Gearóid	Gearóid	Gearóid-N	Npmsc
ach	ach	ach-C	Cs
b	b	b-X	Xl
’	’	’-F	Fa
fhearr	fhearr	maith-A	Aqc
Cú	Cú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
ná	ná	ná-C	Cc
é	é	é-P	Pp3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
tú	tú	tú-P	Pp2-s
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
le	le	le-S	Sp
Cú	Cú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Conchúr	Conchúr	Conchúr-N	Npmsc
Mac	Mac	Mac-U	Up
Neasa	Neasa	Neasa-N	Np|Npfsc
le	le	le-S	Sp
Gearóid	Gearóid	Gearóid-N	Npmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
cluiche	cluiche	cluiche-N	Ncmsc
thart	thart	thart-R	Rd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
níl	níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
chailliúint	chailliúint	cailliúint-N	Ncfsc
ort	ort	ar-P	Pr2-s
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
féin	féin	féin-P	Px
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Is	Is	agus-W	Wp-i|Cc
maith	maith	maith-V	Vmm-2s|Aqp|Ncfsc
an	an	an-T	Td-s
t-iománaí	t-iománaí	iománaí-N	Ncmsc
tú	tú	tú-P	Pp2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cú	Cú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
agus	agus	agus-C	Cc
chroith	chroith	croith-V	Vmis
sé	sé	sé-P	Pp3msn
lámh	lámh	lámh-N	Ncfsc
le	le	le-S	Sp
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tar	Tar	thar-S	Sp
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
dún	dún	dún-N	Ncmsc
anois	anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
le	le	le-S	Sp
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
ocras	ocras	ocras-N	Ncmsc
ort	ort	ar-P	Pr2-s
.	.	.-F	Fe
’	’	’-F	Fa
Istigh	Istigh	istigh-R	Rl
sa	sa	i-S	Spa-s
dún	dún	dún-N	Ncmsc
shuigh	shuigh	suigh-V	Vmis
an	an	an-T	Td-s
triúr	triúr	triúr-N	Ncmsc
chun	chun	chun-S	Sp
boird	boird	bord-N	Ncmsg
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
béile	béile	béile-N	Ncmsc
breá	breá	breá-A	Aq-msc
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
sin	sin	sin-P	Pd
breá	breá	breá-R	Ri
blasta	blasta	blasta-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
béile	béile	béile-N	Ncmsc
ite	ite	ith-A	Av
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
míle	míle	míle-M	Mc
maith	maith	maith-N	Ncfsc
agaibh	agaibh	ag-P	Pr2-p
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
fáilte	fáilte	fáilte-N	Ncfsc
romhat	romhat	roimh-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cú	Cú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
mbeidh	mbeidh	bí-V	Vmif
cluiche	cluiche	cluiche-N	Ncmsc
eile	eile	eile-D	Dd
anois	anois	anois-R	Rt
againn	againn	ag-P	Pr1-p
?	?	?-F	Fq
’	’	’-F	Fa
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
bocht	bocht	bocht-A	Aq-msc
tuirseach	tuirseach	tuirseach-A	Aq-msc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
agus	agus	agus-C	Cc
an-tuirseach	an-tuirseach	tuirseach-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Lá	Lá	lá-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
eile	eile	eile-D	Dd
,	,	,-F	Fi
b	b	b-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
cluiche	cluiche	cluiche-N	Ncmsc
againn	againn	ag-P	Pr1-p
lá	lá	lá-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
eile	eile	eile-D	Dd
.	.	.-F	Fe
Táim	Táim	bí-V	Vmip1s
róthuirseach	róthuirseach	tuirseach-A	Aqp
anois	anois	anois-R	Rt
.	.	.-F	Fe
’	’	’-F	Fa
Go	Go	go-U	Ua
tobann	tobann	tobann-A	Aqp
d	d	d-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmm-2s
doras	doras	doras-N	Ncmsc
an	an	an-T	Td-s
dúin	dúin	dún-N	Ncmsg
agus	agus	agus-C	Cc
siúd	siúd	siúd-P	Pd
isteach	isteach	isteach-R	Rd
le	le	le-S	Sp
beirt	beirt	beirt-N	Ncfsc
shaighdiúirí	shaighdiúirí	saighdiúir-N	Ncmpg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
siad	siad	siad-P	Pp3-pn
tagtha	tagtha	tar-A	Av
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
duine	duine	duine-N	Ncmsc
de	de	de-S	Sp
na	na	na-T	Td-p
saighdiúirí	saighdiúirí	saighdiúir-N	Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
arm	arm	arm-X	Xfen|Ncmsc
Chonnacht	Chonnacht	Connacht-N	Npmsg
tagtha	tagtha	tar-A	Av
.	.	.-F	Fe
’	’	’-F	Fa
Léim	Léim	léim-V	Vmip1s|Vmis
Conchúr	Conchúr	Conchúr-N	Npmsc
Mac	Mac	Mac-U	Up
Neasa	Neasa	Neasa-N	Np|Npfsc
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
agus	agus	agus-C	Cc
rug	rug	beir-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
chlaíomh	chlaíomh	claíomh-N	Ncmsc
.	.	.-F	Fe
Léim	Léim	léim-V	Vmip1s|Vmm-2s|Vmis|Ncfsc
Cú	Cú	cú-N	Ncmsc|Ncmsg
Chulainn	Chulainn	Culann-N	Npm-g
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
agus	agus	agus-C	Cc
rug	rug	beir-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
shleá	shleá	sleá-N	Ncfsc
.	.	.-F	Fe
Siúd	Siúd	siúd-P	Pd
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbeirt	mbeirt	beirt-N	Ncfsc
acu	acu	ag-P	Pr3-p
amach	amach	amach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
Rith	Rith	rith-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
ina	ina	i-S	Spp-p
ndiaidh	ndiaidh	diaidh-N	Ns-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
sibh	sibh	sibh-P	Pp2-p
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
sé	sé	sé-P	Pp3msn
de	de	de-S	Sp
Chú	Chú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
sibh	sibh	sibh-P	Pp2-p
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
arm	arm	arm-X	Xfen|Ncmsc
Chonnacht	Chonnacht	Connacht-N	Npmsg
tagtha	tagtha	tar-A	Av
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cú	Cú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
,	,	,-F	Fi
‘	‘	‘-X	Xx
agus	agus	agus-C	Cc
tá	tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
in	in	i-S	Sp
am	am	am-N	Ncmsc
troda	troda	troid-N	Ncfsg|Nv--g
.	.	.-F	Fe
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
linn	linn	le-P	Pr1-p
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Mise	Mise	mé-P	Pp1-s-e
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
ní	ní	is-W	Wp-in
haon	haon	aon-D	Dq
saighdiúir	saighdiúir	saighdiúir-N	Ncmsc
mise	mise	mé-P	Pp1-s-e
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
iománaí	iománaí	iománaí-N	Ncmsc
maith	maith	maith-A	Aq-msc
tú	tú	tú-P	Pp2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Mar	Mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
déanfaidh	déanfaidh	déan-V	Vmif
tú	tú	tú-P	Pp2-s
saighdiúir	saighdiúir	saighdiúir-N	Ncmsc
maith	maith	maith-A	Aq-msc
.	.	.-F	Fe
’	’	’-F	Fa
Agus	Agus	agus-C	Cc
shín	shín	sín-V	Vmis
sé	sé	sé-P	Pp3msn
sleá	sleá	sleá-N	Ncfsc
agus	agus	agus-C	Cc
sciath	sciath	sciath-V	Vmm-2s
chuige	chuige	chuig-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
linn	linn	le-P	Pr1-p
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cú	Cú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
.	.	.-F	Fe
Gearóid	Gearóid	Gearóid-N	Npmsc
bocht	bocht	bocht-A	Aq-msc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
trína	trína	trí-S	Spp-s
chéile	chéile	céile-N	Ncmsc
!	!	!-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
maith	maith	maith-A	Aqp
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
áit	áit	áit-N	Ncfsc
seo	seo	seo-D	Dd
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
,	,	,-F	Fi
‘	‘	‘-X	Xx
ná	ná	ná-C	Cs
ní	ní	is-W	Wp-in
theastaíonn	theastaíonn	teastaigh-V	Vmip
uaim	uaim	ó-P	Pr1-s
a	a	a-U	U
bheith	bheith	bí-N	Nv
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
shaighdiúir	shaighdiúir	saighdiúir-N	Ncmsc
.	.	.-F	Fe
B	B	B-X	Xl
’	’	’-F	Fa
fhearr	fhearr	maith-A	Aqc
liom	liom	le-P	Pr1-s
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
baile	baile	baile-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
Ach	Ach	ach-C	Cs
rug	rug	beir-V	Vmis
Conchúr	Conchúr	Conchúr-N	Npmsc
Mac	Mac	Mac-U	Up
Neasa	Neasa	Neasa-N	Np|Npfsc
ar	ar	ar-S	Sp
Ghearóid	Ghearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Isteach	Isteach	isteach-R	Rd
leat	leat	le-P	Pr2-s
sa	sa	i-S	Spa-s
charbad	charbad	carbad-N	Ncmsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
Cú	Cú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
ag	ag	ag-S	Sp
fanacht	fanacht	fan-N	Nv
leat	leat	le-P	Pr2-s
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
dúirt	dúirt	abair-V	Vmis
mé	mé	mé-P	Pp1-s
leat	leat	le-P	Pr2-s
nach	nach	nach-W	Wprin|Wpdin|Wpsin|Cs
saighdiúir	saighdiúir	saighdiúir-N	Ncmsc
mé	mé	mé-P	Pp1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Teastaíonn	Teastaíonn	teastaigh-V	Vmip
uaim	uaim	uaim-N	Ncfsc
dul	dul	téigh-N	Ncmsc|Nv
abhaile	abhaile	abhaile-R	Rd
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Theastódh	Theastódh	teastaigh-V	Vmc
uait	uait	ó-P	Pr2-s
éirí	éirí	éirí-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
nó	nó	nó-C	Cc
beidh	beidh	bí-V	Vmif
tú	tú	tú-P	Pp2-s
déanach	déanach	déanach-A	Aqp|Rg
don	don	do-S	Spa-s
scoil	scoil	scoil-N	Ncfsc
.	.	.-F	Fe
’	’	’-F	Fa
Don	Don	do-S	Spa-s
scoil	scoil	scoil-N	Ncfsc
!	!	!-F	Fe
Conchúr	Conchúr	Conchúr-N	Npmsc
Mac	Mac	Mac-U	Up
Neasa	Neasa	Neasa-N	Np|Npfsc
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
faoin	faoin	faoi-S	Spa-s
scoil	scoil	scoil-N	Ncfsc
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
bocht	bocht	bocht-A	Aq-msc
trína	trína	trí-S	Spp-s
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
B	B	B-X	Xl
’	’	’-F	Fa
fhearr	fhearr	maith-A	Aqc
duit	duit	do-P	Pr2-s
éirí	éirí	éirí-N	Ncmsc
,	,	,-F	Fi
a	a	a-U	Uv
Ghearóid	Ghearóid	Gearóid-N	Npm-v
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
arís	arís	arís-R	Rg
,	,	,-F	Fi
‘	‘	‘-X	Xx
nó	nó	nó-C	Cc
beidh	beidh	bí-V	Vmif
tú	tú	tú-P	Pp2-s
déanach	déanach	déanach-A	Aqp|Rg
don	don	do-S	Spa-s
scoil	scoil	scoil-N	Ncfsc
.	.	.-F	Fe
’	’	’-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmm-2s
Gearóid	Gearóid	Gearóid-N	Npmsc
a	a	a-U	U
shúile	shúile	súil-N	Nv--g--n
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
cé	cé	cé-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
ag	ag	ag-S	Sp
bun	bun	bun-N	Ncmsc
na	na	na-T	Tdfsg
leapa	leapa	leaba-N	Ncfsg
ach	ach	ach-C	Cs
…	…	…-F	Fi
…	…	…-F	Fi
Daidí	Daidí	daidí-N	Ncmsc
!	!	!-F	Fe
‘	‘	‘-X	Xx
Tusa	Tusa	tú-P	Pp2-s-e
atá	atá	bí-V	Vmip---r
ann	ann	i-P	Pr3ms
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tusa	Tusa	tú-P	Pp2-s-e
atá	atá	bí-V	Vmip---r
ann	ann	i-P	Pr3ms
,	,	,-F	Fi
a	a	a-U	Uv
Dhaidí	Dhaidí	daidí-N	Ncmsv
!	!	!-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
cé	cé	cé-W	W--q|Pq
eile	eile	eile-D	Dd
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
ann	ann	i-P	Pr3ms
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Fionn	Fionn	Fionn-N	Npmsc
Mac	Mac	Mac-U	Up
Cumhaill	Cumhaill	Cumhaill-N	Npmsg
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
hea	hea	ea-P	Pp3-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
ach	ach	ach-S	Sp
Conchúr	Conchúr	Conchúr-N	Npmsc
Mac	Mac	Mac-U	Up
Neasa	Neasa	Neasa-N	Np|Npfsc
!	!	!-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
B	B	B-X	Xl
’	’	’-F	Fa
fhearr	fhearr	maith-A	Aqc
duit	duit	do-P	Pr2-s
éirí	éirí	éirí-N	Ncmsc
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
nó	nó	nó-C	Cc
ní	ní	ní-Q	Qn
thabharfaidh	thabharfaidh	tabhair-V	Vmif---n
Conchúr	Conchúr	Conchúr-N	Npmsc
Mac	Mac	Mac-U	Up
Neasa	Neasa	Neasa-N	Np|Npfsc
ar	ar	ar-S	Sp
scoil	scoil	scoil-N	Ncfsc
ina	ina	i-S	Spp-s
charbad	charbad	carbad-N	Ncmsc
tú	tú	tú-P	Pp2-s
!	!	!-F	Fe
’	’	’-F	Fa
sleá	sleá	sleá-N	Ncfsc
sciath	sciath	sciath-V	Vmis|Ncfpg|Ncmpg|Ncfpg|Ncfsc|Ncmsc|Ncmpg
carbad	carbad	carbad-N	Ncmpg|Ncmsc
claíomh	claíomh	claíomh-N	Ncmsc
saighdiúir	saighdiúir	saighdiúir-N	Ncmsc
‘	‘	‘-X	Xx
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liom	liom	le-P	Pr1-s
cluiche	cluiche	cluiche-N	Ncmsc
iomána	iomána	iomáin-N	Ncfsg|Nv--g
a	a	a-U	U
bheith	bheith	bí-N	Nv
agam	agam	ag-P	Pr1-s
le	le	le-S	Sp
Cú	Cú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Gearóid	Gearóid	Gearóid-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Rachaidh	Rachaidh	téigh-V	Vmif
mé	mé	mé-P	Pp1-s
go	go	go-S	Sp
hEamhain	hEamhain	hEamhain-N	Nc
Mhacha	Mhacha	Macha-N	Npmsg|Npmsc|Npmsg
.	.	.-F	Fe
’	’	’-F	Fa
