Clár	Clár	Clár-N	Npfsc
‘	‘	‘-X	Xx
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
dul	dul	téigh-N	Nv
ag	ag	ag-S	Sp
scátáil	scátáil	scátáil-N	Nv
ar	ar	ar-S	Sp
rinc	rinc	rinc-N	Ncfsc
scátála	scátála	scátáil-N	Nv--g
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
an	an	an-T	Td-s
rinc	rinc	rinc-N	Ncfsc
scátála	scátála	scátáil-N	Nv--g
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
i	i	i-S	Sp
mí	mí	mí-N	Ncfsc|Ncmsc
na	na	na-T	Tdfsg
Nollag	Nollag	Nollaig-N	Ncfsg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mama	Mama	mama-N	Ncmsc|Xfen
.	.	.-F	Fe
‘	‘	‘-X	Xx
Má	Má	má-C	Cs
bhíonn	bhíonn	bí-V	Vmig
tú	tú	tú-P	Pp2-s
go	go	go-U	Ua
maith	maith	maith-A	Aqp
ligfidh	ligfidh	lig-V	Vmif
mé	mé	mé-P	Pp1-s
ann	ann	i-R	Rl|Pr3ms
thú	thú	tú-P	Pp2-s
.	.	.-F	Fe
’	’	’-F	Fa
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
rinc	rinc	rinc-N	Ncfsc
scátála	scátála	scátáil-N	Nv--g
tagtha	tagtha	tar-A	Av
cheannaigh	cheannaigh	ceannaigh-V	Vmis
Mama	Mama	mama-N	Ncmsc|Xfen
dhá	dhá	dó-M	Mc
thicéad	thicéad	ticéad-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
rinc	rinc	rinc-N	Ncfsc
scátála	scátála	scátáil-N	Nv--g
tagtha	tagtha	tar-A	Av
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
le	le	le-S	Sp
Róisín	Róisín	Róisín-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tabharfaidh	Tabharfaidh	tabhair-V	Vmif
Deaide	Deaide	Deaide-N	Npmsc
ann	ann	i-R	Rl|Pr3ms
thú	thú	tú-P	Pp2-s
Dé	Dé	Dé-N	Ns-s
Sathairn	Sathairn	Satharn-N	Ncmsg
.	.	.-F	Fe
’	’	’-F	Fa
B	B	B-X	Xl
’	’	’-F	Fa
fhada	fhada	fada-A	Aqc
le	le	le-S	Sp
Róisín	Róisín	Róisín-N	Npfsc
go	go	go-Q	Q
dtiocfadh	dtiocfadh	tar-V	Vmc
an	an	an-T	Td-s
Satharn	Satharn	Satharn-N	Ncmsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
fada	fada	fada-A	Aqp
liom	liom	le-P	Pr1-s
go	go	go-Q	Q
dtiocfaidh	dtiocfaidh	tar-V	Vmif
an	an	an-T	Td-s
Satharn	Satharn	Satharn-N	Ncmsc
.	.	.-F	Fe
Ghlaoigh	Ghlaoigh	glaoigh-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
ar	ar	ar-S	Sp
Liam	Liam	Liam-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
rinc	rinc	rinc-N	Ncfsc
scátála	scátála	scátáil-N	Nv--g
tagtha	tagtha	tar-A	Av
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
ticéid	ticéid	ticéad-N	Ncmpc
faighte	faighte	faigh-A	Av
ag	ag	ag-S	Sp
Mama	Mama	mama-N	Ncmsc
dom	dom	do-P	Pr1-s
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
do	do	do-S	Sp
Dheaide	Dheaide	deaide-N	Npmsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Nach	Nach	is-W	Wpsin|Wpdin
aoibhinn	aoibhinn	aoibhinn-A	Aqp
duit	duit	do-P	Pr2-s
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Liam	Liam	Liam-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
mise	mise	mé-P	Pp1-s-e
ar	ar	ar-S	Sp
rinc	rinc	rinc-N	Ncfsc
scátála	scátála	scátáil-N	Nv--g
riamh	riamh	riamh-R	Rg
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
B	B	B-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
go	go	go-Q	Q
dtabharfadh	dtabharfadh	tabhair-V	Vmc
Daideo	Daideo	daideo-N	Ncmsc
ann	ann	i-R	Rl|Pr3ms
mé	mé	mé-P	Pp1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Liam	Liam	Liam-N	Npmsc
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
leag	leag	leag-V	Vmis
sé	sé	sé-P	Pp3msn
uaidh	uaidh	ó-P	Pr3ms
an	an	an-T	Td-s
fón	fón	fón-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Glaofaidh	Glaofaidh	glao-V	Vmif
mé	mé	mé-P	Pp1-s
air	air	ar-P	Pr3ms
.	.	.-F	Fe
’	’	’-F	Fa
Ghlaoigh	Ghlaoigh	glaoigh-V	Vmis
Liam	Liam	Liam-N	Npmsc
ar	ar	ar-S	Sp
Dhaideo	Dhaideo	daideo-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
rinc	rinc	rinc-N	Ncfsc
scátála	scátála	scátáil-N	Nv--g
tagtha	tagtha	tar-A	Av
,	,	,-F	Fi
a	a	a-U	Uv
Dhaideo	Dhaideo	daideo-N	Ncmsv
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
mise	mise	mé-P	Pp1-s-e
ar	ar	ar-S	Sp
rinc	rinc	rinc-N	Ncfsc
scátála	scátála	scátáil-N	Nv--g
riamh	riamh	riamh-R	Rg
.	.	.-F	Fe
An	An	an-Q	Qq
dtabharfaidh	dtabharfaidh	tabhair-V	Vmif
tú	tú	tú-P	Pp2-s
ann	ann	i-R	Rl|Pr3ms
mé	mé	mé-P	Pp1-s
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Rinc	Rinc	rinc-N	Ncfsc
scátála	scátála	scátáil-N	Nv--g
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daideo	Daideo	daideo-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
fada	fada	fada-A	Aqp
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
ó	ó	ó-C	Cs
bhí	bhí	bí-V	Vmis
mise	mise	mé-P	Pp1-s-e
ar	ar	ar-S	Sp
rinc	rinc	rinc-N	Ncfsc
scátála	scátála	scátáil-N	Nv--g
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
An	An	an-Q	Qq
dtabharfaidh	dtabharfaidh	tabhair-V	Vmif
tú	tú	tú-P	Pp2-s
ann	ann	i-R	Rl|Pr3ms
mé	mé	mé-P	Pp1-s
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Liam	Liam	Liam-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tabharfaidh	Tabharfaidh	tabhair-V	Vmif
mé	mé	mé-P	Pp1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daideo	Daideo	daideo-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
caithfidh	caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
labhairt	labhairt	labhair-N	Ncfsc|Nv
le	le	le-S	Sp
do	do	do-D	Dp2-s
Mham	Mham	mam-N	Ncfsc
nó	nó	nó-C	Cc
le	le	le-S	Sp
do	do	do-D	Dp2-s
Dhaid	Dhaid	Daid-N	Npmsc
ar	ar	ar-S	Sp
dtús	dtús	tús-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
Tar éis	Tar éis	tar_éis-S	Spc
do	do	do-D	Dp2-s
Dhaideo	Dhaideo	daideo-N	Ncmsc
labhairt	labhairt	labhair-N	Ncfsc|Nv
le	le	le-S	Sp
máthair	máthair	máthair-N	Ncfsc
Liam	Liam	Liam-N	Npm-g|Npfsg
cheannaigh	cheannaigh	ceannaigh-V	Vmis
sé	sé	sé-P	Pp3msn
dhá	dhá	dó-M	Mc
thicéad	thicéad	ticéad-N	Ncmsc
.	.	.-F	Fe
B	B	B-X	Xl
’	’	’-F	Fa
fhada	fhada	fada-A	Aqc
le	le	le-S	Sp
Liam	Liam	Liam-N	Npmsc
agus	agus	agus-C	Cc
le	le	le-S	Sp
Daideo	Daideo	daideo-N	Ncmsc
go	go	go-Q	Q
dtiocfadh	dtiocfadh	tar-V	Vmc
an	an	an-T	Td-s
Satharn	Satharn	Satharn-N	Ncmsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
fada	fada	fada-A	Aqp
liom	liom	le-P	Pr1-s
go	go	go-Q	Q
dtiocfaidh	dtiocfaidh	tar-V	Vmif
an	an	an-T	Td-s
Satharn	Satharn	Satharn-N	Ncmsc
.	.	.-F	Fe
Ar	Ar	is-N	Ncmsc|Sp|Wssi|Q-is|Wpsi
deireadh	deireadh	deireadh-V	Vmih|Ncmsc
thiar	thiar	thiar-R	Rd
thall	thall	thall-R	Rd
tháinig	tháinig	tar-V	Vmis
an	an	an-T	Td-s
Satharn	Satharn	Satharn-N	Ncmsc
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
Daideo	Daideo	daideo-N	Ncmsc
agus	agus	agus-C	Cc
Liam	Liam	Liam-N	Npm-g|Npmsc|Npfsg
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbus	mbus	bus-N	Ncmsc
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
rinc	rinc	rinc-N	Ncfsc
scátála	scátála	scátáil-N	Nv--g
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
.	.	.-F	Fe
Cuir	Cuir	cuir-V	Vmm-2s
ort	ort	ar-P	Pr2-s
iad	iad	iad-P	Pp3-p
seo	seo	seo-P	Pd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
le	le	le-S	Sp
Daideo	Daideo	daideo-N	Ncmsc
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
sí	sí	sí-P	Pp3fsn
péire	péire	péire-N	Ncmsc
scátaí	scátaí	scáta-N	Ncmpg
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
.	.	.-F	Fe
Cuir	Cuir	cuir-V	Vmm-2s
ort	ort	ar-P	Pr2-s
iad	iad	iad-P	Pp3-p
seo	seo	seo-P	Pd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
le	le	le-S	Sp
Liam	Liam	Liam-N	Npmsc
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
sí	sí	sí-P	Pp3fsn
péire	péire	péire-N	Ncmsc
scátaí	scátaí	scáta-N	Ncmpg
dósan	dósan	do-P	Pr3ms-e
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
féidir	féidir	féidir-N	Ns-s
liom	liom	le-P	Pr1-s
siúl	siúl	siúil-N	Nv
iontu	iontu	i-P	Pr3-p
seo	seo	seo-P	Pd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Liam	Liam	Liam-N	Npmsc
le	le	le-S	Sp
Daideo	Daideo	daideo-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Titfidh	Titfidh	tit-V	Vmif
mé	mé	mé-P	Pp1-s
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
thitfidh	thitfidh	tit-V	Vmif---n
tú	tú	tú-P	Pp2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daideo	Daideo	daideo-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tabharfaidh	Tabharfaidh	tabhair-V	Vmif
mise	mise	mé-P	Pp1-s-e
aire	aire	aire-N	Ncmsc|Ncfsc
duit	duit	do-P	Pr2-s
.	.	.-F	Fe
’	’	’-F	Fa
Agus	Agus	agus-C	Cc
rug	rug	beir-V	Vmis
sé	sé	sé-P	Pp3msn
greim	greim	greim-N	Ncmsc
láimhe	láimhe	lámh-N	Ncfsg
ar	ar	ar-S	Sp
Liam	Liam	Liam-N	Npmsc
.	.	.-F	Fe
Amach	Amach	amach-R	Rd
leo	leo	le-P	Pr3-p
ar	ar	ar-S	Sp
an	an	an-T	Td-s
rinc	rinc	rinc-N	Ncfsc
scátála	scátála	scátáil-N	Nv--g
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
linn	linn	le-P	Pr1-p
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daideo	Daideo	daideo-N	Ncmsc
.	.	.-F	Fe
Shín	Shín	Sín-N	Npfsc
Daideo	Daideo	daideo-N	Ncmsc|Ncmsg
a	a	a-D	Dp3
chos	chos	cos-N	Ncfsc
amach	amach	amach-R	Rd
agus	agus	agus-C	Cc
níorbh	níorbh	is-W	Ws-in
fhada	fhada	fada-A	Aqc|Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
…	…	…-F	Fi
…	…	…-F	Fi
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
thóin	thóin	tóin-N	Ncfsc
!	!	!-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmm-2s
Daideo	Daideo	daideo-N	Ncmsc
ach	ach	ach-C	Cs
níorbh	níorbh	is-W	Ws-in
fhada	fhada	fada-A	Aqc|Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
a	a	a-D	Dp3
thóin	thóin	tóin-N	Ncfsc
arís	arís	arís-R	Rg
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
Liam	Liam	Liam-N	Npmsc
ag	ag	ag-S	Sp
briseadh	briseadh	bris-N	Nv
a	a	a-D	Dp3
chroí	chroí	croí-N	Ncmsc
ag	ag	ag-S	Sp
gáire	gáire	gáir-N	Nv
faoi	faoi	faoi-P	Pr3ms
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
rug	rug	beir-V	Vmis
Liam	Liam	Liam-N	Npmsc
greim	greim	greim-N	Ncmsc
láimhe	láimhe	lámh-N	Ncfsg
ar	ar	ar-S	Sp
Dhaideo	Dhaideo	daideo-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
linn	linn	le-P	Pr1-p
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tabharfaidh	Tabharfaidh	tabhair-V	Vmif
mise	mise	mé-P	Pp1-s-e
aire	aire	aire-N	Ncmsc|Ncfsc
duit	duit	do-P	Pr2-s
.	.	.-F	Fe
’	’	’-F	Fa
Shín	Shín	Sín-N	Npfsc
siad	siad	siad-P	Pp3-pn
amach	amach	amach-R	Rd
a	a	a-D	Dp3
gcosa	gcosa	cos-N	Ncfpc
agus	agus	agus-C	Cc
níorbh	níorbh	is-W	Ws-in
fhada	fhada	fada-A	Aqc|Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
acu	acu	ag-P	Pr3-p
…	…	…-F	Fi
…	…	…-F	Fi
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
dtóin	dtóin	tóin-N	Ncfsc
!	!	!-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
Liam	Liam	Liam-N	Npmsc
ná	ná	ná-C	Cc
Daideo	Daideo	daideo-N	Ncmsc|Ncmsg
ag	ag	ag-S	Sp
déanamh	déanamh	déanamh-N	Ncmsc
rómhaith	rómhaith	maith-A	Aqp
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
athair	athair	athair-N	Ncmsc
Róisín	Róisín	Róisín-N	Npfsc
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
sibh	sibh	sibh-P	Pp2-p
dul	dul	téigh-N	Ncmsc|Nv
go	go	go-U	Ua
breá	breá	breá-R	Ri
réidh	réidh	réidh-A	Aqp
ar	ar	ar-S	Sp
dtús	dtús	tús-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Mar	Mar	mar-S	Sp
seo	seo	seo-P	Pd
.	.	.-F	Fe
’	’	’-F	Fa
Tar éis	Tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
bhí	bhí	bí-V	Vmis
Liam	Liam	Liam-N	Npmsc
á	á	do-S	Spo-s
thabhairt	thabhairt	tabhair-N	Nv
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
go	go	go-U	Ua
maith	maith	maith-A	Aqp
anois	anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
athair	athair	athair-N	Ncmsc
Róisín	Róisín	Róisín-N	Npf-g|Npfsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Daideo	Daideo	daideo-N	Ncmsc
á	á	do-S	Spo-s
thabhairt	thabhairt	tabhair-N	Nv
leis	leis	le-P	Pr3ms
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
go	go	go-U	Ua
maith	maith	maith-A	Aqp
anois	anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
athair	athair	athair-N	Ncmsc
Róisín	Róisín	Róisín-N	Npf-g|Npfsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Níorbh	Níorbh	is-W	Ws-in
fhada	fhada	fada-A	Aqc|Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
Liam	Liam	Liam-N	Npmsc
agus	agus	agus-C	Cc
Daideo	Daideo	daideo-N	Ncmsc|Ncmsg
ag	ag	ag-S	Sp
scátáil	scátáil	scátáil-N	Nv
timpeall	timpeall	timpeall-R	Rd
agus	agus	agus-C	Cc
timpeall	timpeall	timpeall-N	Ncmpg|Ncmsc|Rd
.	.	.-F	Fe
Nárbh	Nárbh	is-W	Wssin
iad	iad	iad-P	Pp3-p
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
leo	leo	le-P	Pr3-p
féin	féin	féin-P	Px
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
grianghrafadóir	grianghrafadóir	grianghrafadóir-N	Ncmsc
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
timpeall	timpeall	timpeall-R	Rd
agus	agus	agus-C	Cc
ceamara	ceamara	ceamara-N	Ncmsg|Ncmsc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Thóg	Thóg	tóg-V	Vmis
sé	sé	sé-P	Pp3msn
grianghraif	grianghraif	grianghraf-N	Ncmpc
de	de	de-S	Sp
Liam	Liam	Liam-N	Npmsc
agus	agus	agus-C	Cc
de	de	de-S	Sp
Dhaideo	Dhaideo	daideo-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cén	Cén	cé-W	W--q|Dw--s
t-ainm	t-ainm	ainm-N	Ncmsc
atá	atá	bí-V	Vmip---r
ort	ort	ar-P	Pr2-s
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
an	an	an-T	Td-s
grianghrafadóir	grianghrafadóir	grianghrafadóir-N	Ncmsc
de	de	de-S	Sp
Liam	Liam	Liam-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Liam	Liam	Liam-N	Npmsc
Mac	Mac	Mac-U	Up
Cárthaigh	Cárthaigh	Cárthaigh-N	Npmsg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Liam	Liam	Liam-N	Npmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
agus	agus	agus-C	Cc
is	is	is-W	Wpri
é	é	é-P	Pp3ms
seo	seo	seo-P	Pd
mo	mo	mo-D	Dp1-s
Dhaideo	Dhaideo	daideo-N	Ncmsc
,	,	,-F	Fi
Jeaic	Jeaic	Jeaic-N	Npmsc
Mac	Mac	Mac-U	Up
Cárthaigh	Cárthaigh	Cárthaigh-N	Npmsg
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
grianghraf	grianghraf	grianghraf-N	Ncmsc
sa	sa	i-S	Spa-s
pháipéar	pháipéar	páipéar-N	Ncmsc
an	an	an-T	Td-s
tseachtain	tseachtain	seachtain-N	Ncfsc
seo	seo	seo-D	Dd
chugainn	chugainn	chuig-P	Pr1-p
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
grianghrafadóir	grianghrafadóir	grianghrafadóir-N	Ncmsc
le	le	le-S	Sp
Liam	Liam	Liam-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beimid	Beimid	bí-V	Vmif1p
sa	sa	i-S	Spa-s
pháipéar	pháipéar	páipéar-N	Ncmsc
an	an	an-T	Td-s
tseachtain	tseachtain	seachtain-N	Ncfsc
seo	seo	seo-D	Dd
chugainn	chugainn	chuig-P	Pr1-p
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Liam	Liam	Liam-N	Npmsc
le	le	le-S	Sp
Daideo	Daideo	daideo-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
é	é	é-P	Pp3ms
a	a	a-U	U
cheannach	cheannach	ceannaigh-N	Nv
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daideo	Daideo	daideo-N	Ncmsc
.	.	.-F	Fe
An	An	an-T	Td-s
tseachtain	tseachtain	seachtain-N	Ncfsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|W|Dd
cheannaigh	cheannaigh	ceannach-V	Vmis|Ncmpc
Daideo	Daideo	daideo-N	Ncmsc|Ncmsg
an	an	an-T	Td-s
páipéar	páipéar	páipéar-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
grianghraf	grianghraf	grianghraf-N	Ncmsc
de	de	de-P	Pr3ms
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
de	de	de-S	Sp
Liam	Liam	Liam-N	Npmsc
ann	ann	ann-R	Rl
ceart	ceart	ceart-N	Ncmsc
go leor	go leor	go_leor-A	Aq
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
…	…	…-F	Fi
…	…	…-F	Fi
agus	agus	agus-C	Cc
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
acu	acu	ag-P	Pr3-p
ar	ar	ar-N	Ncmsc
a	a	a-D	Dp3
dtóin	dtóin	tóin-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
oighear	oighear	oighear-N	Ncmsc
!	!	!-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
an	an	an-T	Td-s
rinc	rinc	rinc-N	Ncfsc
scátála	scátála	scátáil-N	Nv--g
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
i	i	i-S	Sp
mí	mí	mí-N	Ncfsc|Ncmsc
na	na	na-T	Tdfsg
Nollag	Nollag	Nollaig-N	Ncfsg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mama	Mama	mama-N	Ncmsc|Xfen
.	.	.-F	Fe
‘	‘	‘-X	Xx
Má	Má	má-C	Cs
bhíonn	bhíonn	bí-V	Vmig
tú	tú	tú-P	Pp2-s
go	go	go-U	Ua
maith	maith	maith-A	Aqp
ligfidh	ligfidh	lig-V	Vmif
mé	mé	mé-P	Pp1-s
ann	ann	i-R	Rl|Pr3ms
thú	thú	tú-P	Pp2-s
.	.	.-F	Fe
’	’	’-F	Fa
