‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
fada	fada	fada-A	Aqp
liom	liom	le-P	Pr1-s
go	go	go-Q	Q
dtiocfaidh	dtiocfaidh	tar-V	Vmif
Oíche	Oíche	oíche-N	Ncfsc
Shamhna	Shamhna	Samhain-N	Ncfsg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cat	Cat	Cat-N	Npmsc
na	na	na-T	Tdfsg
Caillí	Caillí	cailleach-N	Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
Éirigh	Éirigh	éirigh-V	Vmm-2s
agus	agus	agus-C	Cc
scuab	scuab	scuab-N	Ncfsc|Vmis|Vmm-2s
an	an	an-T	Td-s
t-urlár	t-urlár	urlár-N	Ncmsc
dom	dom	do-P	Pr1-s
.	.	.-F	Fe
píosa	píosa	píosa-N	Ncmsc
den	den	de-S	Spa-s
bhairín	bhairín	bairín-N	Ncmsc
breac	breac	breac-A	Aq-msc
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
’	’	’-F	Fa
Chuala	Chuala	clois-V	Vmis
an	an	an-T	Td-s
Chailleach	Chailleach	cailleach-N	Ncfsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
,	,	,-F	Fi
muise	muise	muise-X	Xsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bíonn	Bíonn	bí-V	Vmig
tú	tú	tú-P	Pp2-s
i	i	i-S	Sp
do	do	do-D	Dp2-s
shuí	shuí	suí-N	Nv|Ncmsc
ansin	ansin	ansin-R	Rt|Rl
cois	cois	cois-S	Sp
na	na	na-T	Tdfsg
tine	tine	tine-N	Ncfsc
ó	ó	ó-S	Sp
mhaidin	mhaidin	maidin-N	Ncfsc
go	go	go-S	Sp
hoíche	hoíche	oíche-N	Ncfsc
.	.	.-F	Fe
Éirigh	Éirigh	éirigh-V	Vmm-2s
agus	agus	agus-C	Cc
scuab	scuab	scuab-N	Ncfsc|Vmis|Vmm-2s
an	an	an-T	Td-s
t-urlár	t-urlár	urlár-N	Ncmsc
dom	dom	do-P	Pr1-s
.	.	.-F	Fe
’	’	’-F	Fa
Éirigh	Éirigh	éirigh-V	Vmm-2s
agus	agus	agus-C	Cc
scuab	scuab	scuab-N	Ncfsc|Vmis|Vmm-2s
an	an	an-T	Td-s
t-urlár	t-urlár	urlár-N	Ncmsc
dom	dom	do-P	Pr1-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
fada	fada	fada-A	Aqp
liom	liom	le-P	Pr1-s
go	go	go-Q	Q
dtiocfaidh	dtiocfaidh	tar-V	Vmif
Oíche	Oíche	oíche-N	Ncfsc
Shamhna	Shamhna	Samhain-N	Ncfsg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cat	Cat	Cat-N	Npmsc
na	na	na-T	Tdfsg
Caillí	Caillí	cailleach-N	Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
bia	bia	bia-N	Ncmsc
breá	breá	breá-R	Ri
blasta	blasta	blasta-A	Aqp
as	as	as-S	Sp
an	an	an-T	Td-s
gcorcán	gcorcán	corcán-N	Ncmsc
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
’	’	’-F	Fa
Chuala	Chuala	clois-V	Vmis
an	an	an-T	Td-s
Chailleach	Chailleach	cailleach-N	Ncfsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
,	,	,-F	Fi
muise	muise	muise-X	Xsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bíonn	Bíonn	bí-V	Vmig
tú	tú	tú-P	Pp2-s
i	i	i-S	Sp
do	do	do-D	Dp2-s
shuí	shuí	suí-N	Nv|Ncmsc
ansin	ansin	ansin-R	Rt|Rl
cois	cois	cois-S	Sp
na	na	na-T	Tdfsg
tine	tine	tine-N	Ncfsc
ó	ó	ó-S	Sp
mhaidin	mhaidin	maidin-N	Ncfsc
go	go	go-S	Sp
hoíche	hoíche	oíche-N	Ncfsc
.	.	.-F	Fe
Éirigh	Éirigh	éirigh-V	Vmm-2s
agus	agus	agus-C	Cc
nigh	nigh	nigh-V	Vmis|Vmm-2s
an	an	an-T	Td-s
spúnóg	spúnóg	spúnóg-N	Ncfsc
dom	dom	do-P	Pr1-s
.	.	.-F	Fe
’	’	’-F	Fa
Éirigh	Éirigh	éirigh-V	Vmm-2s
agus	agus	agus-C	Cc
nigh	nigh	nigh-V	Vmis|Vmm-2s
an	an	an-T	Td-s
spúnóg	spúnóg	spúnóg-N	Ncfsc
dom	dom	do-P	Pr1-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
fada	fada	fada-A	Aqp
liom	liom	le-P	Pr1-s
go	go	go-Q	Q
dtiocfaidh	dtiocfaidh	tar-V	Vmif
Oíche	Oíche	oíche-N	Ncfsc
Shamhna	Shamhna	Samhain-N	Ncfsg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cat	Cat	Cat-N	Npmsc
na	na	na-T	Tdfsg
Caillí	Caillí	cailleach-N	Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
deis	deis	deis-N	Ncfsc
agam	agam	ag-P	Pr1-s
eitilt	eitilt	eitilt-N	Ncfsc
ar	ar	ar-S	Sp
scuab	scuab	scuab-N	Ncfsc
na	na	na-T	Tdfsg
caillí	caillí	cailleach-N	Ncfsg
.	.	.-F	Fe
’	’	’-F	Fa
Chuala	Chuala	clois-V	Vmis
an	an	an-T	Td-s
Chailleach	Chailleach	cailleach-N	Ncfsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
,	,	,-F	Fi
muise	muise	muise-X	Xsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bíonn	Bíonn	bí-V	Vmig
tú	tú	tú-P	Pp2-s
i	i	i-S	Sp
do	do	do-D	Dp2-s
shuí	shuí	suí-N	Nv|Ncmsc
ansin	ansin	ansin-R	Rt|Rl
cois	cois	cois-S	Sp
na	na	na-T	Tdfsg
tine	tine	tine-N	Ncfsc
ó	ó	ó-S	Sp
mhaidin	mhaidin	maidin-N	Ncfsc
go	go	go-S	Sp
hoíche	hoíche	oíche-N	Ncfsc
.	.	.-F	Fe
Éirigh	Éirigh	éirigh-V	Vmm-2s
agus	agus	agus-C	Cc
glan	glan	glan-V	Vmm-2s|Ncmsc|Vmm-2s|Aqp
an	an	an-T	Td-s
bord	bord	bord-N	Ncmsc
dom	dom	do-P	Pr1-s
.	.	.-F	Fe
’	’	’-F	Fa
Éirigh	Éirigh	éirigh-V	Vmm-2s
agus	agus	agus-C	Cc
glan	glan	glan-V	Vmm-2s|Ncmsc|Vmm-2s|Aqp
an	an	an-T	Td-s
bord	bord	bord-N	Ncmsc
dom	dom	do-P	Pr1-s
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
Oíche	Oíche	oíche-N	Ncfsc
Shamhna	Shamhna	Samhain-N	Ncfsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Cat	Cat	Cat-N	Npmsc
na	na	na-T	Tdfsg
Caillí	Caillí	cailleach-N	Ncfsg
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
píosa	píosa	píosa-N	Ncmsc
den	den	de-S	Spa-s
bhairín	bhairín	bairín-N	Ncmsc
breac	breac	breac-A	Aq-msc
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
bia	bia	bia-N	Ncmsc
breá	breá	breá-R	Ri
blasta	blasta	blasta-A	Aqp
as	as	as-S	Sp
an	an	an-T	Td-s
gcorcán	gcorcán	corcán-N	Ncmsc
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
ansin	ansin	ansin-R	Rt|Rl
beidh	beidh	bí-V	Vmif
deis	deis	deis-N	Ncfsc
agam	agam	ag-P	Pr1-s
eitilt	eitilt	eitilt-N	Ncfsc
ar	ar	ar-S	Sp
scuab	scuab	scuab-N	Ncfsc
na	na	na-T	Tdfsg
Caillí	Caillí	cailleach-N	Ncfsg
.	.	.-F	Fe
’	’	’-F	Fa
Chuala	Chuala	clois-V	Vmis
an	an	an-T	Td-s
Chailleach	Chailleach	cailleach-N	Ncfsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
,	,	,-F	Fi
muise	muise	muise-X	Xsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Féadfaidh	Féadfaidh	féad-V	Vmif
tú	tú	tú-P	Pp2-s
fanacht	fanacht	fan-N	Ncmsc|Nv
i	i	i-S	Sp
do	do	do-D	Dp2-s
shuí	shuí	suí-N	Nv|Ncmsc
ansin	ansin	ansin-R	Rt|Rl
cois	cois	cois-S	Sp
na	na	na-T	Tdfsg
tine	tine	tine-N	Ncfsc
.	.	.-F	Fe
’	’	’-F	Fa
Agus	Agus	agus-C	Cc
amach	amach	amach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
An	An	an-T	Td-s
cat	cat	cat-N	Ncmsc
bocht	bocht	bocht-A	Aq-msc
!	!	!-F	Fe
Ní	Ní	is-W	Wp-in
mó	mó	mó-A	Aqc|Aqp
ná	ná	ná-C	Cs|Cc
sásta	sásta	sásta-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Oíche	Oíche	oíche-N	Ncfsc
Shamhna	Shamhna	Samhain-N	Ncfsg
tagtha	tagtha	tar-A	Av
ach	ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
féin	féin	féin-P	Px
,	,	,-F	Fi
Cat	Cat	Cat-N	Npmsc
na	na	na-T	Tdfsg
Caillí	Caillí	cailleach-N	Ncfsg
,	,	,-F	Fi
fós	fós	fós-R	Rg
ina	ina	i-S	Spp-s
shuí	shuí	suí-N	Ncmsc
cois	cois	cois-S	Sp
na	na	na-T	Tdfsg
tine	tine	tine-N	Ncfsc
.	.	.-F	Fe
Bhuail	Bhuail	buail-V	Vmis
ocras	ocras	ocras-N	Ncmsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Anonn	Anonn	anonn-R	Rd
leis	leis	le-P	Pr3ms
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
corcán	corcán	corcán-N	Ncmsc
agus	agus	agus-C	Cc
sháigh	sháigh	sáigh-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
spúnóg	spúnóg	spúnóg-N	Ncfsc
isteach	isteach	isteach-R	Rd
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
seo	seo	seo-P	Pd
an-bhlasta	an-bhlasta	blasta-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
cat	cat	cat-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
spúnóg	spúnóg	spúnóg-N	Ncfsc
eile	eile	eile-D	Dd
de	de	de-P	Pr3ms|Sp
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
’	’	’-F	Fa
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
ithe	ithe	ith-N	Nv
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
ithe	ithe	ith-N	Nv
nó	nó	nó-C	Cc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
a	a	a-D	Dp3
bholg	bholg	bolg-N	Ncmsc
lán	lán	lán-A	Aq-msc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
shuigh	shuigh	suigh-V	Vmis
sé	sé	sé-P	Pp3msn
cois	cois	cois-S	Sp
na	na	na-T	Tdfsg
tine	tine	tine-N	Ncfsc
agus	agus	agus-C	Cc
thit	thit	tit-V	Vmis
a	a	a-U	U
chodladh	chodladh	codail-N	Nv
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Tamall	Tamall	tamall-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|Dd
dhúisigh	dhúisigh	dúisigh-V	Vmis
an	an	an-T	Td-s
cat	cat	cat-N	Ncmsc
.	.	.-F	Fe
Bhuail	Bhuail	buail-V	Vmis
ocras	ocras	ocras-N	Ncmsc
arís	arís	arís-R	Rg
é	é	é-P	Pp3ms
.	.	.-F	Fe
Anonn	Anonn	anonn-R	Rd
leis	leis	le-P	Pr3ms
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
corcán	corcán	corcán-N	Ncmsc
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
ithe	ithe	ith-N	Nv
arís	arís	arís-R	Rg
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
shuigh	shuigh	suigh-V	Vmis
sé	sé	sé-P	Pp3msn
cois	cois	cois-S	Sp
na	na	na-T	Tdfsg
tine	tine	tine-N	Ncfsc
agus	agus	agus-C	Cc
thit	thit	tit-V	Vmis
a	a	a-U	U
chodladh	chodladh	codail-N	Nv
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Chaith	Chaith	caith-V	Vmis
Cat	Cat	Cat-N	Npmsc
na	na	na-T	Tdfsg
Caillí	Caillí	cailleach-N	Ncfsg
an	an	an-T	Td-s
oíche	oíche	oíche-N	Ncfsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
ag	ag	ag-S	Sp
ithe	ithe	ith-N	Nv
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
codladh	codladh	codail-N	Nv
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
an	an	an-T	Td-s
Chailleach	Chailleach	cailleach-N	Ncfsc
ar ais	ar ais	ar_ais-R	Rd
bhí	bhí	bí-V	Vmis
ocras	ocras	ocras-N	Ncmsc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Anonn	Anonn	anonn-R	Rd
léi	léi	le-P	Pr3fs
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
corcán	corcán	corcán-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
mó	mó	mó-A	Aqc|Aqp
ná	ná	ná-C	Cs|Cc
sásta	sásta	sásta-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
Chailleach	Chailleach	cailleach-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
bhia	bhia	bia-N	Ncmsc
fágtha	fágtha	fág-A	Aqp|Av
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cé	Cé	cé-P	Pq
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
ith	ith	ith-V	Vmis
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
de	de	de-S	Sp
bhia	bhia	bia-N	Ncmsc
sa	sa	i-S	Spa-s
chorcán	chorcán	corcán-N	Ncmsc
?	?	?-F	Fq
’	’	’-F	Fa
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
dhúisigh	dhúisigh	dúisigh-V	Vmis
an	an	an-T	Td-s
cat	cat	cat-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Mise	Mise	mé-P	Pp1-s-e
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
ith	ith	ith-V	Vmis
é	é	é-P	Pp3ms
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
,	,	,-F	Fi
‘	‘	‘-X	Xx
agus	agus	agus-C	Cc
is	is	is-W	Wpri
é	é	é-P	Pp3ms
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
go	go	go-U	Ua
breá	breá	breá-R	Ri
blasta	blasta	blasta-A	Aqp
.	.	.-F	Fe
’	’	’-F	Fa
Mise	Mise	mé-P	Pp1-s-e
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
ith	ith	ith-V	Vmm-2s
é	é	é-P	Pp3ms
.	.	.-F	Fe
Is	Is	is-W	Wp-i
ansin	ansin	ansin-R	Rt|Rl
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
an	an	an-T	Td-s
Chailleach	Chailleach	cailleach-N	Ncfsc
an	an	an-T	Td-s
cat	cat	cat-N	Ncmsc
.	.	.-F	Fe
Baineadh	Baineadh	bain-V	Vmis0
geit	geit	geit-N	Ncfsc
aisti	aisti	as-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	is-W	Wpdq|Wp-q
tusa	tusa	tú-P	Pp2-s-e
atá	atá	bí-V	Vmip---r
ann	ann	i-P	Pr3ms
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
mé	mé	mé-P	Pp1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cat	Cat	Cat-N	Npmsc
na	na	na-T	Tdfsg
Caillí	Caillí	cailleach-N	Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
tá	tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
chomh	chomh	chomh-R	Ri
mór	mór	mór-A	Aqp
liom	liom	le-P	Pr1-s
féin	féin	féin-P	Px
anois	anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Chailleach	Chailleach	cailleach-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
M	M	M-X	Xl
’	’	’-F	Fa
anam	anam	anam-N	Ncmsc
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
mé	mé	mé-P	Pp1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
cat	cat	cat-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nár	Nár	nár-Q	Qnrs
ith	ith	ith-V	Vmis---n
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
bia	bia	bia-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sa	sa	i-S	Spa-s
chorcán	chorcán	corcán-N	Ncmsc
.	.	.-F	Fe
Caithfidh	Caithfidh	caith-V	Vmif
tú	tú	tú-P	Pp2-s
aire	aire	aire-N	Ncfsc
mhaith	mhaith	maith-A	Aq-fsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
domsa	domsa	do-P	Pr1-s-e
as	as	as-S	Sp
seo	seo	seo-P	Pd
amach	amach	amach-R	Rd
nó	nó	nó-C	Cc
is	is	agus-W	Wp-i|Wpri|Cc
tú	tú	tú-P	Pp2-s
féin	féin	féin-P	Px
a	a	a-Q	Q-r
bheidh	bheidh	bí-V	Vmif
sa	sa	i-S	Spa-s
chorcán	chorcán	corcán-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
