Bhí	Bhí	bí-V	Vmis
cró	cró	cró-N	Ncmsc
na	na	na-T	Td-p
gcearc	gcearc	cearc-N	Ncfpg
ciúin	ciúin	ciúin-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
áit	áit	áit-N	Ncfsc
seo	seo	seo-D	Dd
an-chiúin	an-chiúin	ciúin-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Chircín	Chircín	circín-N	Ncmsc
Rua	Rua	Rua-N	Npmsg|Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Chircín	Chircín	circín-N	Ncmsc
Dhubh	Dhubh	dubh-A	Aq-msc
.	.	.-F	Fe
‘	‘	‘-X	Xx
I	I	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
róchiúin	róchiúin	ciúin-A	Aqp
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Chircín	Chircín	circín-N	Ncmsc
Dhonn	Dhonn	Donn-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
cóisir	cóisir	cóisir-N	Ncfsc
againn	againn	ag-P	Pr1-p
.	.	.-F	Fe
Tabharfaimid	Tabharfaimid	tabhair-V	Vmif1p
cuireadh	cuireadh	cuireadh-N	Ncmsc
do	do	do-S	Sp
na	na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Tabharfaimid	Tabharfaimid	tabhair-V	Vmif1p
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Chircín	Chircín	circín-N	Ncmsc
Rua	Rua	Rua-N	Npmsg|Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
cóisir	cóisir	cóisir-N	Ncfsc
againn	againn	ag-P	Pr1-p
.	.	.-F	Fe
Beidh	Beidh	bí-V	Vmif
bia	bia	bia-N	Ncmsc
agus	agus	agus-C	Cc
deoch	deoch	deoch-N	Ncfsc
agus	agus	agus-C	Cc
ceol	ceol	ceol-N	Ncmsc|Nv-----n
againn	againn	ag-P	Pr1-p
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Caithfimid	Caithfimid	caith-V	Vmif1p
fógra	fógra	fógra-N	Ncmsc
a	a	a-U	U
scríobh	scríobh	scríobh-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
fógra	fógra	fógra-N	Ncmsc
scríofa	scríofa	scríobh-A	Av
ag	ag	ag-S	Sp
an	an	an-T	Td-s
Chircín	Chircín	circín-N	Ncmsg
Rua	Rua	Rua-N	Npmsg|Npmsc|Npfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cé	Cé	cé-P	Pq
acu	acu	ag-P	Pr3-p
againn	againn	ag-P	Pr1-p
is	is	is-U	U
fearr	fearr	maith-A	Aqc
gCircín	gCircín	circín-N	Ncmsc
Rua	Rua	Rua-N	Npmsg|Npmsc
chroch	chroch	croch-V	Vmis|Ncfpg
na	na	na-T	Td-p
cearca	cearca	cearc-N	Ncfpc
ag	ag	ag-S	Sp
scríobh	scríobh	scríobh-N	Nv
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-S	Sp
chrann	chrann	crann-N	Ncmsc
mór	mór	mór-A	Aq-msc
darach	darach	dair-N	Ncfsg
é	é	é-P	Pp3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tú	Tú	tú-P	Pp2-s
féin	féin	féin-P	Px
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Chircín	Chircín	circín-N	Ncmsc
Dhubh	Dhubh	dubh-A	Aq-msc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tú	Tú	tú-P	Pp2-s
féin	féin	féin-P	Px
is	is	is-U	U
fearr	fearr	maith-A	Aqc
ag	ag	ag-S	Sp
scríobh	scríobh	scríobh-N	Nv
.	.	.-F	Fe
’	’	’-F	Fa
Isteach	Isteach	isteach-R	Rd
leis	leis	le-S	Sp
na	na	na-T	Td-p
cearca	cearca	cearc-N	Ncfpc
sa	sa	i-S	Spa-s
chró	chró	cró-N	Ncmsc
.	.	.-F	Fe
Siúd	Siúd	siúd-P	Pd
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
cró	cró	cró-N	Ncmsc
glanta	glanta	glan-A	Av
ag	ag	ag-S	Sp
na	na	na-T	Tdfsg
leo	leo	leo-N	Ncmsc
ag	ag	ag-S	Sp
glanadh	glanadh	glan-N	Nv
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
sciúradh	sciúradh	sciúr-N	Nv
.	.	.-F	Fe
cearca	cearca	cearc-N	Ncfpc
thosaigh	thosaigh	tosaigh-V	Vmis
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
bácáil	bácáil	bácáil-N	Nv
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
an	an	an-T	Td-s
coileach	coileach	coileach-N	Ncmsc
an	an	an-T	Td-s
fógra	fógra	fógra-N	Ncmsg|Ncmsc
ar	ar	is-W	Wpsi|Ncmsc|Wssi|Wpdi
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
fógra	fógra	fógra-N	Ncmsc
scríofa	scríofa	scríobh-A	Av
aige	aige	ag-P	Pr3ms
gcrann	gcrann	crann-N	Ncmsc
darach	darach	dair-N	Ncfsg
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
mó	mó	mó-A	Aqc|Aqp
ná	ná	ná-C	Cs|Cc
sásta	sásta	sásta-A	Aqp
a	a	a-Q	Q-r
chroch	chroch	croch-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcrann	gcrann	crann-N	Ncmsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cóisir	Cóisir	cóisir-N	Ncfsc
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ainmhithe	Ainmhithe	ainmhí-N	Ncmpc
ag	ag	ag-S	Sp
ithe	ithe	ith-N	Nv
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
ól	ól	ól-N	Nv
istigh	istigh	istigh-R	Rl
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
chrósa	chrósa	cró-N	Ncmsc-e
!	!	!-F	Fe
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
fógra	fógra	fógra-N	Ncmsc
eile	eile	eile-D	Dd
a	a	a-U	U
scríobh	scríobh	scríobh-N	Nv
!	!	!-F	Fe
’	’	’-F	Fa
Chonaic	Chonaic	feic-V	Vmis
na	na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpc
an	an	an-T	Td-s
fógra	fógra	fógra-N	Ncmsg|Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
cuireadh	cuireadh	cuireadh-N	Ncmsc
agatsa	agatsa	ag-P	Pr2-s-e
chuig	chuig	chuig-S	Sp
Ní	Ní	is-W	Wp-in
mó	mó	mó-A	Aqc|Aqp
ná	ná	ná-C	Cs|Cc
sásta	sásta	sásta-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
.	.	.-F	Fe
cóisir	cóisir	cóisir-N	Ncfsc
na	na	na-T	Td-p
gcearc	gcearc	cearc-N	Ncfpg
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
capall	capall	capall-N	Ncmsc
leis	leis	le-P	Pr3ms
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
cuireadh	cuireadh	cuireadh-N	Ncmsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
an	an	an-T	Td-s
asal	asal	asal-N	Ncmsc
.	.	.-F	Fe
againn	againn	ag-P	Pr1-p
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
siad	siad	siad-P	Pp3-pn
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
t-asal	t-asal	asal-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
cuireadh	cuireadh	cuireadh-N	Ncmsc
agat	agat	ag-P	Pr2-s
féin	féin	féin-P	Px
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
capall	capall	capall-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
táim	táim	bí-V	Vmip1s
mór	mór	mór-N	Ncmsc
leis	leis	le-S	Sp
na	na	na-T	Td-p
cearca	cearca	cearc-N	Ncfpc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
cuireadh	cuireadh	cuireadh-N	Ncmsc
agatsa	agatsa	ag-P	Pr2-s-e
chuig	chuig	chuig-S	Sp
cóisir	cóisir	cóisir-N	Ncfsc
na	na	na-T	Td-p
gcearc	gcearc	cearc-N	Ncfpg
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
mhuc	mhuc	muc-N	Ncfsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
gcaora	gcaora	caora-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
chaora	chaora	caora-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
cuireadh	cuireadh	cuireadh-N	Ncmsc
agat	agat	ag-P	Pr2-s
féin	féin	féin-P	Px
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
mhuc	mhuc	muc-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
táim	táim	bí-V	Vmip1s
an-mhór	an-mhór	mór-A	Aqp
leis	leis	le-S	Sp
na	na	na-T	Td-p
cearca	cearca	cearc-N	Ncfpc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
aon	aon	aon-D	Dq
chóisir	chóisir	cóisir-N	Ncfsc
ann	ann	i-P	Pr3ms
,	,	,-F	Fi
más	más	má-C	Csw
ea	ea	ea-P	Pp3-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
searrach	searrach	searrach-N	Ncmsc
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
an	an	an-T	Td-s
coileach	coileach	coileach-N	Ncmsc
na	na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpc
.	.	.-F	Fe
Chuala	Chuala	clois-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
chaint	chaint	caint-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Há	Há	Há-N	Npmsc
!	!	!-F	Fe
Há	Há	Há-N	Npmsc
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
an	an	an-T	Td-s
bia	bia	bia-N	Ncmsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
deoch	deoch	deoch-N	Ncfsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
agam	agam	ag-P	Pr1-s
dom	dom	do-P	Pr1-s
féin	féin	féin-P	Px
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
in	in	i-S	Sp
am	am	am-N	Ncmsc
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
a	a	a-U	U
oscailt	oscailt	oscail-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
ocras	ocras	ocras-N	Ncmsc
ormsa	ormsa	ar-P	Pr1-s-e
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Chircín	Chircín	circín-N	Ncmsc
Rua	Rua	Rua-N	Npmsg|Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
tú	tú	tú-P	Pp2-s
fanacht	fanacht	fan-N	Ncmsc|Nv
ansin	ansin	ansin-R	Rt|Rl
nó	nó	nó-C	Cc
go	go	go-C	Cs
Nuair	Nuair	nuair-C	Cs
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmis
sí	sí	sí-P	Pp3fsn
é	é	é-P	Pp3ms
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ann	ann	i-P	Pr3ms
dtiocfaidh	dtiocfaidh	tar-V	Vmif
na	na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpc
eile	eile	eile-D	Dd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	ar-N	Ncmsc-e
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
coileach	coileach	coileach-N	Ncmsc
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
an	an	an-T	Td-s
Chircín	Chircín	circín-N	Ncmsc
Rua	Rua	Rua-N	Npmsg|Npmsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
coileach	coileach	coileach-N	Ncmsc
an	an	an-T	Td-s
bia	bia	bia-N	Ncmsg
agus	agus	agus-C	Cc
an	an	an-T	Td-s
deoch	deoch	deoch-N	Ncfsc
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
mó	mó	mó-A	Aqc|Aqp
ná	ná	ná-C	Cs|Cc
sásta	sásta	sásta-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
coileach	coileach	coileach-N	Ncmsc
.	.	.-F	Fe
Ar	Ar	is-W	Wssi|Wpsi
a	a	a-U	Um
naoi	naoi	naoi-M	Mc
a	a	an-T	Td-s
chlog	chlog	clog-N	Ncmsc
dhún	dhún	dún-N	Ncmsc
an	an	an-T	Td-s
Chircín	Chircín	circín-N	Ncmsg
‘	‘	‘-X	Xx
Bainfidh	Bainfidh	bain-V	Vmif
mé	mé	mé-P	Pp1-s
anuas	anuas	anuas-R	Rd
an	an	an-T	Td-s
fógra	fógra	fógra-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Rua	Rua	Rua-N	Npmsc
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
an	an	an-T	Td-s
Chircín	Chircín	circín-N	Ncmsc
Dhubh	Dhubh	dubh-A	Aq-msc
agus	agus	agus-C	Cc
amach	amach	amach-R	Rd
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níor	Níor	níor-Q	Qn-s
tháinig	tháinig	tar-V	Vmis---n
ár	ár	ár-N	Ncmsc|Dp1-p
gcairde	gcairde	cairde-N	Ncmpc|Ncmsc|Ncmpg|Ncmsg
chuig	chuig	chuig-S	Sp
an	an	an-T	Td-s
gcóisir	gcóisir	cóisir-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
go	go	go-U	Ua
brónach	brónach	brónach-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
coileach	coileach	coileach-N	Ncmsc
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
ag	ag	ag-S	Sp
Is	Is	is-W	Wpri
ansin	ansin	ansin-R	Rt|Rl
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
an	an	an-T	Td-s
Chircín	Chircín	circín-N	Ncmsc
Dhubh	Dhubh	dubh-A	Aq-msc
gcrann	gcrann	crann-N	Ncmpg
darach	darach	dair-N	Ncfsg
.	.	.-F	Fe
an	an	an-T	Td-s
fógra	fógra	fógra-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níor	Níor	níor-Q	Qn-s
tháinig	tháinig	tar-V	Vmis---n
ár	ár	ár-N	Ncmsc|Dp1-p
gcairde	gcairde	cairde-N	Ncmpc|Ncmsc|Ncmpg|Ncmsg
chuig	chuig	chuig-S	Sp
‘	‘	‘-X	Xx
A	A	an-T	Td-s
bhithiúnaigh	bhithiúnaigh	bithiúnach-N	Ncmsg
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
leis	leis	le-S	Sp
an	an	an-T	Td-s
gcóisir	gcóisir	cóisir-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Chircín	Chircín	circín-N	Ncmsc
Dhubh	Dhubh	dubh-A	Aq-msc
leis	leis	le-P	Pr3ms
gcoileach	gcoileach	coileach-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
tusa	tusa	tú-P	Pp2-s-e
a	a	a-Q	Q-r
scríobh	scríobh	scríobh-V	Vmis
go	go	go-U	Ua
brónach	brónach	brónach-A	Aqp
.	.	.-F	Fe
fógra	fógra	fógra-N	Ncmsc
seo	seo	seo-P	Pd|Dd
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Nár	Nár	nár-Q	Qnrs
tháinig	tháinig	tar-V	Vmis---n
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
coileach	coileach	coileach-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Há	Há	Há-N	Npmsc
!	!	!-F	Fe
Há	Há	Há-N	Npmsc
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
coileach	coileach	coileach-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Anois	Anois	anois-R	Rt
beidh	beidh	bí-V	Vmif
an	an	an-T	Td-s
bia	bia	bia-N	Ncmsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
deoch	deoch	deoch-N	Ncfsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
agam	agam	ag-P	Pr1-s
dom	dom	do-P	Pr1-s
féin	féin	féin-P	Px
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
,	,	,-F	Fi
muise	muise	muise-X	Xsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
chircín	chircín	circín-N	Ncmsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
na	na	na-T	Td-p
cearca	cearca	cearc-N	Ncfpc
eile	eile	eile-D	Dd
an	an	an-T	Td-s
Lá	Lá	lá-N	Ncmsc
arna	arna	arna-S	Spc
mhárach	mhárach	márach-N	Ns-s
chroch	chroch	croch-N	Ncfpg
na	na	na-T	Td-p
cearca	cearca	cearc-N	Ncfpc
scéal	scéal	scéal-N	Ncmsc
ní	ní	ní-N	Ns-s
mó	mó	mór-A	Aqc
ná	ná	ná-C	Cs|Cc
sásta	sásta	sásta-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
leis	leis	le-P	Pr3ms
a	a	a-D	Dp3
bhfógra	bhfógra	fógra-N	Ncmsc
féin	féin	féin-P	Px
arís	arís	arís-R	Rg
.	.	.-F	Fe
an	an	an-T	Td-s
gcoileach	gcoileach	coileach-N	Ncmpg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhan	fhan	fan-V	Vmis
an	an	an-T	Td-s
Chircín	Chircín	circín-N	Ncmsc
Dhonn	Dhonn	Donn-N	Npmsc
ar	ar	ar-S	Sp
garda	garda	garda-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
in	in	i-S	Sp
am	am	am-N	Ncmsc
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
a	a	a-U	U
oscailt	oscailt	oscail-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
‘	‘	‘-X	Xx
Bailigh	Bailigh	bailigh-V	Vmm-2s
leat	leat	le-P	Pr2-s
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Chircín	Chircín	circín-N	Ncmsc
Rua	Rua	Rua-N	Npmsg|Npmsc
.	.	.-F	Fe
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Chircín	Chircín	circín-N	Ncmsc
Rua	Rua	Rua-N	Npmsg|Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
chuireadh	chuireadh	cuireadh-N	Ncmsc
agatsa	agatsa	ag-P	Pr2-s-e
chuig	chuig	chuig-S	Sp
Nuair	Nuair	nuair-C	Cs
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmis
sí	sí	sí-P	Pp3fsn
é	é	é-P	Pp3ms
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ann	ann	ann-R	Rl
cóisir	cóisir	cóisir-N	Ncfsc
na	na	na-T	Td-p
gcearc	gcearc	cearc-N	Ncfpg
.	.	.-F	Fe
’	’	’-F	Fa
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
coileach	coileach	coileach-N	Ncmsc
.	.	.-F	Fe
Bailigh	Bailigh	bailigh-V	Vmm-2s
leat	leat	le-P	Pr2-s
!	!	!-F	Fe
Agus	Agus	agus-C	Cc
dhún	dhún	dún-V	Vmis
sí	sí	sí-P	Pp3fsn
amach	amach	amach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
lig	lig	lig-V	Vmis
an	an	an-T	Td-s
coileach	coileach	coileach-N	Ncmsc
béic	béic	béic-N	Ncfsc
as	as	as-P	Pr3ms
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
sí	sí	sí-P	Pp3fsn
bhéic	bhéic	béic-V	Vmis
d	d	d-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmm-2s
an	an	an-T	Td-s
Chircín	Chircín	circín-N	Ncmsc
Rua	Rua	Rua-N	Npmsg|Npmsc
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
arís	arís	arís-R	Rg
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
capall	capall	capall-N	Ncmsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
searrach	searrach	searrach-N	Ncmsc
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
mhuc	mhuc	muc-N	Ncfsc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
bainbh	bainbh	banbh-N	Ncmpc
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
chaora	chaora	caora-N	Ncfsc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
huain	huain	uan-N	Ncmpc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
chonaic	chonaic	feic-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
coileach	coileach	coileach-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
coileach	coileach	coileach-N	Ncmsc
fliuch	fliuch	fliuch-A	Aq-msc
báite	báite	báigh-A	Av
!	!	!-F	Fe
‘	‘	‘-X	Xx
Há	Há	Há-N	Npmsc
!	!	!-F	Fe
Há	Há	Há-N	Npmsc
!	!	!-F	Fe
Há	Há	Há-N	Npmsc
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Chircín	Chircín	circín-N	Ncmsc
Rua	Rua	Rua-N	Npmsg|Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Táim	Táim	bí-V	Vmip1s
fliuch	fliuch	fliuch-A	Aqp
báite	báite	báigh-A	Av
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bailigh	Bailigh	bailigh-V	Vmm-2s
leat	leat	le-P	Pr2-s
.	.	.-F	Fe
Níl	Níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
chuireadh	chuireadh	cuireadh-N	Ncmsc
agatsa	agatsa	ag-P	Pr2-s-e
chuig	chuig	chuig-S	Sp
cóisir	cóisir	cóisir-N	Ncfsc
na	na	na-T	Td-p
gcearc	gcearc	cearc-N	Ncfpg
.	.	.-F	Fe
’	’	’-F	Fa
Táim	Táim	bí-V	Vmip1s
fliuch	fliuch	fliuch-A	Aqp
báite	báite	báigh-A	Av
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an-oíche	an-oíche	oíche-N	Ncfsc
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
acu	acu	ag-P	Pr3-p
ag	ag	ag-S	Sp
cóisir	cóisir	cóisir-N	Ncfsc
na	na	na-T	Td-p
gcearc	gcearc	cearc-N	Ncfpg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Chircín	Chircín	circín-N	Ncmsc
Dhonn	Dhonn	Donn-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
cóisir	cóisir	cóisir-N	Ncfsc
againn	againn	ag-P	Pr1-p
.	.	.-F	Fe
’	’	’-F	Fa
