 ‘	‘	-X	Xx
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liom	liom	le-P	Pr1-s
dul	dul	téigh-N	Nv
amach	amach	amach-R	Rd
sa	sa	i-S	Spa-s
domhan	domhan	domhan-N	Ncmsc
mór	mór	mór-A	Aq-msc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cóilín	Cóilín	Cóilín-N	Npmsc
Coinín	Coinín	Coinín-N	Npmsg|Npmsc
lena	lena	le-S	Spp-s
mháthair	mháthair	máthair-N	Ncfsc
lá	lá	lá-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
ró-óg	ró-óg	óg-A	Aqp
fós	fós	fós-R	Rg
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
tú	tú	tú-P	Pp2-s
fanacht	fanacht	fan-N	Ncmsc|Nv
anseo	anseo	anseo-R	Rl
tamaillín	tamaillín	tamall-N	Ncmsc|Ncmpc
agus	agus	agus-C	Cc
aire	aire	aire-N	Ncmsc|Ncfsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
do	do	do-D	Dp2-s|Sp
do	do	do-S	Sp
dheirfiúirín	dheirfiúirín	deirfiúirín-N	Ncfsc
.	.	.-F	Fe
’	’	’-F	Fa
Agus	Agus	agus-C	Cc
amach	amach	amach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Cóilín	Cóilín	Cóilín-N	Npmsc
bocht	bocht	bocht-A	Aq-msc
!	!	!-F	Fe
Ní	Ní	is-W	Wp-in
mó	mó	mó-A	Aqc|Aqp
ná	ná	ná-C	Cs|Cc
sásta	sásta	sásta-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liom	liom	le-P	Pr1-s
dul	dul	téigh-N	Nv
amach	amach	amach-R	Rd
sa	sa	i-S	Spa-s
domhan	domhan	domhan-N	Ncmsc
mór	mór	mór-A	Aq-msc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
dúirt	dúirt	abair-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
liom	liom	le-P	Pr1-s
go	go	go-Q	Q
bhfuilim	bhfuilim	bí-V	Vmip1s-d
ró-óg	ró-óg	óg-A	Aqp
.	.	.-F	Fe
Is	Is	is-W	Wp-i
fada	fada	fada-A	Aqp
liom	liom	le-P	Pr1-s
go	go	go-Q	Q
mbeidh	mbeidh	bí-V	Vmif
mé	mé	mé-P	Pp1-s
mór	mór	mór-A	Aqp
.	.	.-F	Fe
’	’	’-F	Fa
Is	Is	is-W	Wp-i
fada	fada	fada-A	Aqp
liom	liom	le-P	Pr1-s
go	go	go-Q	Q
mbeidh	mbeidh	bí-V	Vmif
mé	mé	mé-P	Pp1-s
mór	mór	mór-A	Aqp
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
a	a	a-D	Dp3
dheirfiúirín	dheirfiúirín	deirfiúirín-N	Ncfsc
ina	ina	i-S	Spp-s
codladh	codladh	codladh-N	Ncfsc
siúd	siúd	siúd-P	Pd|Dd
le	le	le-S	Sp
Cóilín	Cóilín	Cóilín-N	Npmsc
amach	amach	amach-R	Rd
as	as	as-S	Sp
an	an	an-T	Td-s
gcoinicéar	gcoinicéar	coinicéar-N	Ncmsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
é	é	é-P	Pp3ms
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
amuigh	amuigh	amuigh-R	Rl
sa	sa	i-S	Spa-s
domhan	domhan	domhan-N	Ncmsc
mór	mór	mór-A	Aq-msc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
agus	agus	agus-C	Cc
síos	síos	síos-R	Rd
an	an	an-T	Td-s
bóthar	bóthar	bóthar-N	Ncmsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
Cóilín	Cóilín	Cóilín-N	Npmsc
féileacáin	féileacáin	féileacán-N	Ncmpc
agus	agus	agus-C	Cc
chonaic	chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
éin	éin	éan-N	Ncmpc
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
beacha	beacha	beach-N	Ncfpc
agus	agus	agus-C	Cc
chonaic	chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
bláthanna	bláthanna	bláth-N	Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
maith	maith	maith-A	Aqp
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
domhan	domhan	domhan-N	Ncmsc
mór	mór	mór-A	Aq-msc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
Is	Is	is-W	Wp-i
maith	maith	maith-A	Aqp
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
domhan	domhan	domhan-N	Ncmsc
mór	mór	mór-A	Aq-msc
!	!	!-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
chonaic	chonaic	feic-V	Vmis
Cóilín	Cóilín	Cóilín-N	Npmsc
garraí	garraí	garra-N	Ncmsc|Ncfpc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
cairéid	cairéid	cairéad-N	Ncmpc
agus	agus	agus-C	Cc
tornapaí	tornapaí	tornapa-N	Ncmpg|Ncmpc
agus	agus	agus-C	Cc
leitís	leitís	leitís-N	Ncfsc
ag	ag	ag-S	Sp
fás	fás	fás-N	Nv
sa	sa	i-S	Spa-s
gharraí	gharraí	garraí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cóilín	Cóilín	Cóilín-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
maith	maith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
cairéid	cairéid	cairéad-N	Ncmpc
.	.	.-F	Fe
’	’	’-F	Fa
Isteach	Isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
gharraí	gharraí	garraí-N	Ncmsc
leis	leis	le-P	Pr3ms
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
ithe	ithe	ith-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
na	na	na-T	Td-p
cairéid	cairéid	cairéad-N	Ncmpc
seo	seo	seo-D	Dd
breá	breá	breá-R	Ri
blasta	blasta	blasta-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cóilín	Cóilín	Cóilín-N	Npmsc
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
bhuail	bhuail	buail-V	Vmis
tuirse	tuirse	tuirse-N	Ncfsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Táim	Táim	bí-V	Vmip1s
tuirseach	tuirseach	tuirseach-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
Luigh	Luigh	luigh-V	Vmis
sé	sé	sé-P	Pp3msn
siar	siar	siar-R	Rd
agus	agus	agus-C	Cc
dhún	dhún	dún-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
shúile	shúile	súil-N	Ncfpc
.	.	.-F	Fe
Níorbh	Níorbh	is-W	Ws-in
fhada	fhada	fada-A	Aqc|Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
chodladh	chodladh	codladh-N	Ncfsc
go	go	go-U	Ua
sámh	sámh	sámh-A	Aqp
.	.	.-F	Fe
Tamall	Tamall	tamall-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|Dd
dhúisigh	dhúisigh	dúisigh-V	Vmis
Cóilín	Cóilín	Cóilín-N	Npmsc
de	de	de-U	Up
phreab	phreab	preab-V	Vmis
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
duine	duine	duine-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
!	!	!-F	Fe
Léim	Léim	léim-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
.	.	.-F	Fe
Cé	Cé	cé-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
ann	ann	i-P	Pr3ms
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
feirmeoir	feirmeoir	feirmeoir-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bailigh	Bailigh	bailigh-V	Vmm-2s
leat	leat	le-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
bhithiúnaigh	bhithiúnaigh	bithiúnach-N	Ncmsv
!	!	!-F	Fe
Bailigh	Bailigh	bailigh-V	Vmm-2s
leat	leat	le-P	Pr2-s
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
feirmeoir	feirmeoir	feirmeoir-N	Ncmsc
de	de	de-S	Sp
bhéic	bhéic	béic-N	Ncfsc
.	.	.-F	Fe
Bailigh	Bailigh	bailigh-V	Vmm-2s
leat	leat	le-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
bhithiúnaigh	bhithiúnaigh	bithiúnach-N	Ncmsv
!	!	!-F	Fe
Rith	Rith	rith-V	Vmis
Cóilín	Cóilín	Cóilín-N	Npmsc
.	.	.-F	Fe
Rith	Rith	rith-V	Vmm-2s|Vmis
an	an	an-T	Td-s
feirmeoir	feirmeoir	feirmeoir-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bailigh	Bailigh	bailigh-V	Vmm-2s
leat	leat	le-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
bhithiúnaigh	bhithiúnaigh	bithiúnach-N	Ncmsv
!	!	!-F	Fe
Bailigh	Bailigh	bailigh-V	Vmm-2s
leat	leat	le-P	Pr2-s
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
feirmeoir	feirmeoir	feirmeoir-N	Ncmsc
arís	arís	arís-R	Rg
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
chroí	chroí	croí-N	Ncmsc
ina	ina	i-S	Spp-s
bhéal	bhéal	béal-N	Ncmsc
ag	ag	ag-S	Sp
Cóilín	Cóilín	Cóilín-N	Npmsc
bocht	bocht	bocht-A	Aq-msc
.	.	.-F	Fe
Rith	Rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
agus	agus	agus-C	Cc
rith	rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
agus	agus	agus-C	Cc
an	an	an-T	Td-s
feirmeoir	feirmeoir	feirmeoir-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ansin	ansin	ansin-R	Rt|Rl
chuala	chuala	clois-V	Vmis
sé	sé	sé-P	Pp3msn
glór	glór	glór-N	Ncmsc
eile	eile	eile-D	Dd
.	.	.-F	Fe
Glór	Glór	glór-N	Ncmsc
deas	deas	deas-R	Ri
séimh	séimh	séimh-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tar	Tar	thar-S	Sp
anseo	anseo	anseo-R	Rl
,	,	,-F	Fi
a	a	a-U	Uv
Chóilín	Chóilín	Chóilín-N	Npmsc
.	.	.-F	Fe
Tabharfaidh	Tabharfaidh	tabhair-V	Vmif
mise	mise	mé-P	Pp1-s-e
aire	aire	aire-N	Ncmsc|Ncfsc
duit	duit	do-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
glór	glór	glór-N	Ncmsc
.	.	.-F	Fe
Cé	Cé	cé-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
ann	ann	i-R	Rl|Pr3ms
ach	ach	ach-S	Sp
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
Coinín	Coinín	Coinín-N	Npmsg
.	.	.-F	Fe
Rug	Rug	beir-V	Vmis
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
ar	ar	ar-S	Sp
Chóilín	Chóilín	cóilín-N	Npmsc
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
sí	sí	sí-P	Pp3fsn
isteach	isteach	isteach-R	Rd
ina	ina	i-S	Spp-s
coinicéar	coinicéar	coinicéar-N	Ncmsc
féin	féin	féin-P	Px
é	é	é-P	Pp3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
slán	slán	slán-A	Aqp
sábháilte	sábháilte	sábháil-A	Av
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
dorcha	dorcha	dorcha-A	Aqp
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
máthair	máthair	máthair-N	Ncfsc
Chóilín	Chóilín	Chóilín-N	Npmsc
abhaile	abhaile	abhaile-R	Rd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
,	,	,-F	Fi
a	a	a-U	Uv
Chóilín	Chóilín	Chóilín-N	Npmsc
?	?	?-F	Fq
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
tásc	tásc	tásc-N	Ncmsc
ná	ná	ná-C	Cc
tuairisc	tuairisc	tuairisc-N	Ncfsc
ar	ar	ar-S	Sp
Chóilín	Chóilín	cóilín-N	Npmsc
.	.	.-F	Fe
Rith	Rith	rith-V	Vmm-2s|Vmis
máthair	máthair	máthair-N	Ncfsc
Chóilín	Chóilín	Chóilín-N	Npmsc
amach	amach	amach-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbóthar	mbóthar	bóthar-N	Ncmsc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
croí	croí	croí-N	Ncmsc
ina	ina	i-S	Spp-s
béal	béal	béal-N	Ncmsc
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
,	,	,-F	Fi
a	a	a-U	Uv
Chóilín	Chóilín	Chóilín-N	Npmsc
?	?	?-F	Fq
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
Ach	Ach	ach-S	Sp
tásc	tásc	tásc-N	Ncmsc
ná	ná	ná-C	Cs|Cc
tuairisc	tuairisc	tuairisc-N	Ncfsc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ar	ar	ar-S	Sp
Chóilín	Chóilín	cóilín-N	Npmsc
.	.	.-F	Fe
Rith	Rith	rith-V	Vmm-2s|Vmis
máthair	máthair	máthair-N	Ncfsc
Chóilín	Chóilín	Chóilín-N	Npmsc
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
gharraí	gharraí	garraí-N	Ncmsc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
croí	croí	croí-N	Ncmsc
ina	ina	i-S	Spp-s
béal	béal	béal-N	Ncmsc
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
,	,	,-F	Fi
a	a	a-U	Uv
Chóilín	Chóilín	Chóilín-N	Npmsc
?	?	?-F	Fq
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
Is	Is	is-W	Wp-i
ansin	ansin	ansin-R	Rt|Rl
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
glór	glór	glór-N	Ncmsc
.	.	.-F	Fe
Glór	Glór	glór-N	Ncmsc
deas	deas	deas-R	Ri
séimh	séimh	séimh-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
anseo	anseo	anseo-R	Rl
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
liomsa	liomsa	le-P	Pr1-s-e
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
glór	glór	glór-N	Ncmsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
anseo	anseo	anseo-R	Rl
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
liomsa	liomsa	le-P	Pr1-s-e
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
Cóilín	Cóilín	Cóilín-N	Npmsc
a	a	a-D	Dp3
mháthair	mháthair	máthair-N	Ncfsc
thosaigh	thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
caoineadh	caoineadh	caoin-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
bí	bí	bí-V	Vmm-2s-n
ag	ag	ag-S	Sp
caoineadh	caoineadh	caoin-N	Nv
,	,	,-F	Fi
a	a	a-U	Uv
stór	stór	stór-N	Ncmsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
do	do	do-S	Sp
mhamaí	mhamaí	mamaí-N	Ncmpc|Ncfsc
anseo	anseo	anseo-R	Rl
anois	anois	anois-R	Rt
agus	agus	agus-C	Cc
tá	tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
slán	slán	slán-A	Aqp
sábháilte	sábháilte	sábháil-A	Aqp|Av
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
raibh	raibh	bí-V	Vmis---d
tú	tú	tú-P	Pp2-s
,	,	,-F	Fi
a	a	a-U	Uv
stór	stór	stór-N	Ncmsv
?	?	?-F	Fq
Cá	Cá	cá-R	Rq
raibh	raibh	bí-V	Vmis---d
tú	tú	tú-P	Pp2-s
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
a	a	a-D	Dp3
mháthair	mháthair	máthair-N	Ncfsc
de	de	de-S	Sp
Chóilín	Chóilín	cóilín-N	Npmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
inis	inis	inis-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
ó	ó	ó-S	Sp
thús	thús	tús-N	Ncmsc
deireadh	deireadh	abair-V	Vmih
di	di	do-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
maith	maith	maith-A	Aqp
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
domhan	domhan	domhan-N	Ncmsc
mór	mór	mór-A	Aq-msc
,	,	,-F	Fi
a	a	a-U	Uv
Mhamaí	Mhamaí	mama-N	Ncfsv|Ncmpv
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-C	Cs
ní	ní	is-W	Wp-in
maith	maith	maith-A	Aqp
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
feirmeoir	feirmeoir	feirmeoir-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
Ní	Ní	is-W	Wp-in
maith	maith	maith-A	Aqp
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
feirmeoir	feirmeoir	feirmeoir-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	agus-W	Wp-i|Cc
maith	maith	maith-V	Vmm-2s|Aqp|Ncfsc
an	an	an-T	Td-s
rud	rud	rud-N	Ncmsc
é	é	é-P	Pp3ms
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
tusa	tusa	tú-P	Pp2-s-e
anseo	anseo	anseo-R	Rl
le	le	le-S	Sp
haire	haire	aire-N	Ncfsc|Ncmsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
dó	dó	do-P	Pr3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
máthair	máthair	máthair-N	Ncfsc
Chóilín	Chóilín	Chóilín-N	Npmsc
le	le	le-S	Sp
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
ró-óg	ró-óg	óg-A	Aqp
le	le	le-S	Sp
bheith	bheith	bí-N	Nv
amuigh	amuigh	amuigh-R	Rl
sa	sa	i-S	Spa-s
domhan	domhan	domhan-N	Ncmsc
mór	mór	mór-A	Aq-msc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
I	I	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
ró-óg	ró-óg	óg-A	Aqp
.	.	.-F	Fe
’	’	’-F	Fa
Bhí	Bhí	bí-V	Vmis
Cóilín	Cóilín	Cóilín-N	Npmsc
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Táim	Táim	bí-V	Vmip1s
slán	slán	slán-N	Ncmsc
sábháilte	sábháilte	sábháil-A	Aqp|Av
anois	anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
‘	‘	‘-X	Xx
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
maith	maith	maith-N	Ncfsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Chaoimhe	Chaoimhe	Caoimhe-N	Npf-v
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Muise	Muise	muise-X	Xsc
,	,	,-F	Fi
tá	tá	bí-V	Vmip
fáilte	fáilte	fáilte-N	Ncfsc
romhat	romhat	roimh-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
stór	stór	stór-N	Ncmsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nach	Nach	nach-Q	Qnr|Qnq
bhfuil	bhfuil	bí-V	Vmip---d|Vmip---n
sé	sé	sé-P	Pp3msn
in	in	i-S	Sp
am	am	am-N	Ncmsc
againn	againn	ag-P	Pr1-p
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
abhaile	abhaile	abhaile-R	Rd
anois	anois	anois-R	Rt
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
a	a	a-D	Dp3
mháthair	mháthair	máthair-N	Ncfsc
le	le	le-S	Sp
Cóilín	Cóilín	Cóilín-N	Npmsc
tar éis	tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cóilín	Cóilín	Cóilín-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
maith	maith	maith-A	Aqp
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
domhan	domhan	domhan-N	Ncmsc
mór	mór	mór-A	Aq-msc
.	.	.-F	Fe
Ná	Ná	ná-C	Cs
ní	ní	is-W	Wp-in
maith	maith	maith-A	Aqp
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
feirmeoir	feirmeoir	feirmeoir-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmm-2s
Cóilín	Cóilín	Cóilín-N	Npmsc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
mháthair	mháthair	máthair-N	Ncfsc
abhaile	abhaile	abhaile-R	Rd
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
leo	leo	le-P	Pr3-p
féin	féin	féin-P	Px
.	.	.-F	Fe
