Fadó	Fadó	fadó-R	Rg
,	,	,-F	Fi
fadó	fadó	fadó-R	Rg
bhí	bhí	bí-V	Vmis
cónaí	cónaí	cónaí-N	Ncmsc
ar	ar	ar-S	Sp
fhear	fhear	fear-N	Ncmsc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
bhean	bhean	bean-N	Ncfsc
chéile	chéile	céile-N	Ncmsg
i	i	i-S	Sp
dteach	dteach	teach-N	Ncmsc
beag	beag	beag-A	Aq-msc
faoin	faoin	faoi-S	Spa-s
tuath	tuath	tuath-N	Ncfsc
.	.	.-F	Fe
Chan	Chan	can-V	Vmis
daoine	daoine	duine-N	Ncmpc
saibhre	saibhre	saibhir-A	Aq--pg|Aq--pc|Aq--pv
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
iontu	iontu	i-P	Pr3-p
ar	ar	ar-S	Sp
chor	chor	cor-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
ach	ach	ach-S	Sp|Cs
iad	iad	iad-P	Pp3-p
beo	beo	beo-A	Aqp
bocht	bocht	bocht-A	Aqp
.	.	.-F	Fe
Cha	Cha	cha-Q	Qn
dtiocfadh	dtiocfadh	tar-V	Vmc
leat	leat	le-P	Pr2-s
a	a	a-U	U
rá	rá	abair-N	Nv
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
na	na	na-T	Tdfsg
comharsain	comharsain	comharsain-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
acu	acu	ag-P	Pr3-p
bocht	bocht	bocht-N	Ncmsc
.	.	.-F	Fe
Cha	Cha	cha-Q	Qn
raibh	raibh	bí-V	Vmis---n
siad	siad	siad-P	Pp3-pn
bocht	bocht	bocht-A	Aqp
ar	ar	ar-S	Sp
chor	chor	cor-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
ach	ach	ach-S	Sp
neart	neart	neart-N	Ncmsc
de	de	de-S	Sp
shaibhreas	shaibhreas	saibhreas-N	Ncmsc
an	an	an-T	Td-s
tsaoil	tsaoil	saol-N	Ncmsg
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Tráthnóna	Tráthnóna	tráthnóna-N	Ncmsc
geimhridh	geimhridh	geimhreadh-N	Ncmsg
amháin	amháin	amháin-A	Aqp
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
ina	ina	i-S	Spp-p|Spp-s
suí	suí	suí-N	Ncmsc
ar	ar	ar-S	Sp
dhá	dhá	dó-M	Mc
thaobh	thaobh	taobh-N	Ncmsc
na	na	na-T	Tdfsg
tine	tine	tine-N	Ncfsg
thosaigh	thosaigh	tosaigh-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
faoi	faoi	faoi-S	Sp
na	na	na-T	Tdfsg
comharsain	comharsain	comharsain-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
faoi	faoi	faoi-S	Sp
cé	cé	cé-N	Ncfsc
chomh	chomh	chomh-R	Ri
sásta	sásta	sásta-A	Aqp
agus	agus	agus-C	Cc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
na	na	na-T	Tdfsg
comharsain	comharsain	comharsain-N	Ncfsc
agus	agus	agus-C	Cc
achan	achan	gach-D	Dq
chosúlacht	chosúlacht	cosúlacht-N	Ncfsc
orthu	orthu	ar-P	Pr3-p
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
siad	siad	siad-P	Pp3-pn
gan	gan	gan-S	Sp
buaireamh	buaireamh	buair-N	Nv
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nach	Nach	is-C	Cs|Wpdin|Wpsin
méanar	méanar	méanar-A	Aqp
dóibh	dóibh	do-P	Pr3-p
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ba	Ba	is-W	Ws|Ws-i
chóir	chóir	cóir-A	Aqp
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
muidne	muidne	muid-P	Pp1-p-e
níos	níos	níos-U	Uc
cosúla	cosúla	cosúil-A	Aqc
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
Dá	Dá	dá-C	Cs
mbeadh	mbeadh	bí-V	Vmc
cumhacht	cumhacht	cumhacht-N	Ncfsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
agamsa	agamsa	ag-P	Pr1-s-e
,	,	,-F	Fi
bheadh	bheadh	bí-V	Vmc
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
againne	againne	ag-P	Pr1-p-e
níos	níos	níos-U	Uc
sona	sona	sona-A	Aqc
sásta	sásta	sásta-A	Aqp
ná	ná	ná-C	Cc
iad	iad	iad-P	Pp3-p
uilig	uilig	uile-D	Dq
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
ceart	ceart	ceart-N	Ncmsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
a	a	a-D	Dp3
fear	fear	fear-N	Ncmsc
céile	céile	céile-N	Ncmsg|Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Dá	Dá	dá-C	Cs
mbeadh	mbeadh	bí-V	Vmc
a	a	a-D	Dp3
leithéid	leithéid	leithéid-N	Ncfsc
de	de	de-S	Sp
rud	rud	rud-N	Ncmsc
is	is	agus-W	Wp-i|Wpri|Cc
sióga	sióga	sióg-N	Ncfpc
ann	ann	i-P	Pr3ms
,	,	,-F	Fi
chuirfinn	chuirfinn	cuir-V	Vmc-1s
ceist	ceist	ceist-N	Ncfsc
orthu	orthu	ar-P	Pr3-p
an	an	an-Q	Qq
mbeadh	mbeadh	bí-V	Vmc
siad	siad	siad-P	Pp3-pn
sásta	sásta	sásta-A	Aqp
cúpla	cúpla	cúpla-D	Dq|Ncmsc
mian	mian	mian-N	Ncfsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
dom	dom	do-P	Pr1-s
.	.	.-F	Fe
’	’	’-F	Fa
Díreach	Díreach	díreach-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
phointe	phointe	pointe-N	Ncmsg
,	,	,-F	Fi
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ina	ina	i-S	Spp-p|Spp-s
seasamh	seasamh	seasamh-N	Ncmsc
os	os	os-N	Ncmpg|Sp|Ncmsc
a	a	a-D	Dp3
gcomhair	gcomhair	comhair-N	Ns-s
amach	amach	amach-R	Rd
ach	ach	ach-S	Sp
sióg	sióg	sióg-N	Ncfsc
!	!	!-F	Fe
Dhóbair	Dhóbair	Dhóbair-N	Npmsc
nár	nár	nár-Q	Qnrs
thit	thit	tit-V	Vmis---n
an	an	an-T	Td-s
t-anam	t-anam	anam-N	Ncmsc
as	as	as-S	Sp
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
siad	siad	siad-P	Pp3-pn
an	an	an-T	Td-s
tsióg	tsióg	sióg-N	Ncfsc
.	.	.-F	Fe
Labhair	Labhair	labhair-V	Vmis|Vmm-2s
an	an	an-T	Td-s
tsióg	tsióg	sióg-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Béarfaidh	Béarfaidh	beir-V	Vmif
mé	mé	mé-P	Pp1-s
daoibh	daoibh	do-P	Pr2-p
trí	trí	trí-M	Mc|Sp
mhian	mhian	mian-N	Ncfsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
bígí	bígí	bí-V	Vmm-2p
cúramach	cúramach	cúramach-A	Aqp
,	,	,-F	Fi
mar	mar	mar-C	Cs
,	,	,-F	Fi
i ndiaidh	i ndiaidh	i_ndiaidh-S	Spc
na	na	na-T	Tdfsg
trí	trí	trí-M	Mc
rud	rud	rud-N	Ncmsc
a	a	a-U	U
iarraidh	iarraidh	iarr-N	Nv
,	,	,-F	Fi
cha	cha	cha-Q	Qn
dtabharaim	dtabharaim	tabhar-V	Vmip1s
níos	níos	níos-U	Uc
mó	mó	mór-A	Aqc
.	.	.-F	Fe
’	’	’-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-V	Vmm-2s
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Trí	Trí	trí-S	Sp
mhian	mhian	mian-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Trí	Trí	trí-S	Sp
mhian	mhian	mian-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
.	.	.-F	Fe
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
bhain	bhain	bain-V	Vmis
an	an	an-T	Td-s
tsióg	tsióg	sióg-N	Ncfsc
na	na	na-T	Td-p
bonnaí	bonnaí	bonna-N	Ncmpc
as	as	as-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
achan	achan	gach-D	Dq
rud	rud	rud-N	Ncmsc
iontach	iontach	iontach-R	Ri
socair	socair	socair-A	Aqp
sa	sa	i-S	Spa-s
tseomra	tseomra	seomra-N	Ncmsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
mearbhall	mearbhall	mearbhall-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
fríd	fríd	trí-S	Sp
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
ar feadh	ar feadh	ar_feadh-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
thosaigh	thosaigh	tosaigh-V	Vmis
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
ag	ag	ag-S	Sp
cogarnach	cogarnach	cogarnach-N	Nv-----n
–	–	–-X	Xx
ar	ar	ar-S	Sp
eagla	eagla	eagla-N	Ncfsc
na	na	na-T	Tdfsg
heagla	heagla	eagla-N	Ncfsg
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
duine	duine	duine-N	Ncmsc
de	de	de-S	Sp
na	na	na-T	Tdfsg
comharsain	comharsain	comharsain-N	Ncfsc
taobh amuigh	taobh amuigh	taobh_amuigh-R	Rl
den	den	de-S	Spa-s
doras	doras	doras-N	Ncmsc
ag	ag	ag-S	Sp
éisteacht	éisteacht	éist-N	Nv
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Trí	Trí	trí-S	Sp
mhian	mhian	mian-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Trí	Trí	trí-S	Sp
mhian	mhian	mian-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
barúil	barúil	barúil-N	Ncfsc
agamsa	agamsa	ag-P	Pr1-s-e
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
ba	ba	is-W	Wsri
mhaith	mhaith	maith-A	Aqp
liom	liom	le-P	Pr1-s
.	.	.-F	Fe
Sílim	Sílim	síl-V	Vmip1s
gur	gur	is-W	Wsdi|Wpdi
mhaith	mhaith	maith-A	Aqp
liom	liom	le-P	Pr1-s
lear	lear	lear-N	Ncmsc
mór	mór	mór-A	Aq-msc
airgid	airgid	airgead-N	Ncmsg
,	,	,-F	Fi
...	...	...-F	Fe
…	…	…-F	Fi
teach	teach	teach-N	Ncmsc
mór	mór	mór-A	Aq-msc
…	…	…-F	Fi
…	…	…-F	Fi
agus	agus	agus-C	Cc
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
meas	meas	meas-N	Ncmsc
ag	ag	ag-S	Sp
daoine	daoine	duine-N	Ncmpc
orm	orm	ar-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
a	a	a-U	Uv
thaisce	thaisce	taisce-N	Ncfsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
a	a	a-D	Dp3
fear	fear	fear-N	Ncmsc
céile	céile	céile-N	Ncmsg|Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cad	Cad	cad-W	W--q
é	é	é-P	Pp3ms
a	a	a-Q	Q-r
tharlódh	tharlódh	tarlaigh-V	Vmc
dá	dá	dá-C	Cs
mbeadh	mbeadh	bí-V	Vmc
na	na	na-T	Td-p
mianta	mianta	mian-N	Ncfpc
sin	sin	sin-D	Dd
uilig	uilig	uile-D	Dq
tugtha	tugtha	tabhair-A	Av
duit	duit	do-P	Pr2-s
agus	agus	agus-C	Cc
tú	tú	tú-P	Pp2-s
i	i	i-S	Sp
do	do	do-D	Dp2-s
luí	luí	luí-N	Ncmsc
tinn	tinn	tinn-A	Aq-msc
gan	gan	gan-S	Sp
do	do	do-D	Dp2-s
shláinte	shláinte	sláinte-N	Ncfsc
agat	agat	ag-P	Pr2-s
agus	agus	agus-C	Cc
b	b	b-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
tú	tú	tú-P	Pp2-s
ar	ar	ar-S	Sp
leaba	leaba	leaba-N	Ncfsc
an	an	an-T	Td-s
bháis	bháis	bás-N	Ncmsg
?	?	?-F	Fq
Cha	Cha	cha-Q	Qn
bheadh	bheadh	bí-V	Vmc----n
mórán	mórán	mórán-N	Ncmsc
maith	maith	maith-A	Aq-msc
in	in	sin-S	Sp|Pd
do	do	do-S	Sp
chuid	chuid	cuid-N	Ncfsc
saibhris	saibhris	saibhreas-N	Ncmsg
ansin	ansin	ansin-R	Rt|Rl
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Cad	Cad	cad-W	W--q
é	é	é-P	Pp3ms
fá	fá	faoi-P	Pr3ms
dtaobh	dtaobh	taobh-N	Ncmsc
duitse	duitse	do-P	Pr2-s-e
?	?	?-F	Fq
Cad	Cad	cad-W	W--q
é	é	é-P	Pp3ms
ba	ba	is-W	Wsri
mhaith	mhaith	maith-A	Aqp
leatsa	leatsa	le-P	Pr2-s-e
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
thaisce	thaisce	taisce-N	Ncfsv
,	,	,-F	Fi
níl	níl	bí-V	Vmip---n
mé	mé	mé-P	Pp1-s
róchinnte	róchinnte	cinnte-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tógfaidh	Tógfaidh	tóg-V	Vmif
muid	muid	muid-P	Pp1-p
ár	ár	ár-D	Dp1-p
n-am	n-am	am-N	Ncmsc
agus	agus	agus-C	Cc
smaoineoidh	smaoineoidh	smaoinigh-V	Vmif
muid	muid	muid-P	Pp1-p
air	air	ar-P	Pr3ms
go	go	go-U	Ua
cúramach	cúramach	cúramach-A	Aqp
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
déanfaidh	déanfaidh	déan-V	Vmif
muid	muid	muid-P	Pp1-p
suas	suas	suas-R	Rd
ár	ár	ár-D	Dp1-p
n-intinn	n-intinn	intinn-N	Ncfsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
muid	muid	muid-P	Pp1-p
na	na	na-T	Tdfsg
trí	trí	trí-M	Mc
mhian	mhian	mian-N	Ncfsc
a	a	a-U	U
phiocadh	phiocadh	pioc-N	Nv
go	go	go-U	Ua
cúramach	cúramach	cúramach-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
trí	trí	trí-M	Mc|Sp
mhian	mhian	mian-N	Ncfsc
agus	agus	agus-C	Cc
beidh	beidh	bí-V	Vmif
muid	muid	muid-P	Pp1-p
saibhir	saibhir	saibhir-A	Aqp
.	.	.-F	Fe
’	’	’-F	Fa
Sheas	Sheas	seas-V	Vmis
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
ansin	ansin	ansin-R	Rt|Rl
agus	agus	agus-C	Cc
thóg	thóg	tóg-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
maide	maide	maide-N	Ncmsc
briste	briste	bris-A	Av
leis	leis	le-S	Sp
an	an	an-T	Td-s
tine	tine	tine-N	Ncfsc
a	a	a-U	U
stócáil	stócáil	stócáil-N	Nv
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
stócáil	stócáil	stócáil-N	Nv
na	na	na-T	Tdfsg
tine	tine	tine-N	Ncfsg
,	,	,-F	Fi
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
gan	gan	gan-S	Sp
smaoineamh	smaoineamh	smaoinigh-N	Nv
:	:	:-F	Fi
‘	‘	‘-X	Xx
Amharc	Amharc	amharc-N	Ncmsc|Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
tine	tine	tine-N	Ncfsc
dheas	dheas	deas-A	Aq-fsc
sin	sin	sin-D	Dd
.	.	.-F	Fe
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
dá	dá	dá-C	Cs
mbeadh	mbeadh	bí-V	Vmc
ispín	ispín	ispín-N	Ncmsc
againn	againn	ag-P	Pr1-p
don	don	do-S	Spa-s
tae	tae	tae-N	Ncmsc
.	.	.-F	Fe
Thiocfadh	Thiocfadh	tar-V	Vmc
linn	linn	le-N	Ncfsc|Pr1-p
é	é	é-P	Pp3ms
a	a	a-U	U
chur	chur	cuir-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
tine	tine	tine-N	Ncfsc
.	.	.-F	Fe
’	’	’-F	Fa
Cha	Cha	cha-Q	Qn
raibh	raibh	bí-V	Vmis---n
na	na	na-T	Td-p
focail	focail	focal-N	Ncmpc
as	as	as-P	Pr3ms
a	a	a-D	Dp3
béal	béal	béal-N	Ncmsc
i	i	i-S	Sp
gceart	gceart	ceart-N	Ncmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
ispín	ispín	ispín-N	Ncmsc
mór	mór	mór-A	Aq-msc
fada	fada	fada-A	Aqp
ramhar	ramhar	ramhar-A	Aqp
anuas	anuas	anuas-R	Rd
an	an	an-T	Td-s
simléar	simléar	simléar-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
has	has	has-X	Xfev
a	a	a-Q	Q-i
dtáinig	dtáinig	tar-V	Vmis
sin	sin	sin-P	Pd
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
agus	agus	agus-C	Cc
iontas	iontas	iontas-N	Ncmsc
an	an	an-T	Td-s
domhain	domhain	domhan-N	Ncmsg
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
fá	fá	faoi-P	Pr3ms
Dhia	Dhia	dia-N	Ncmsc
atá	atá	bí-V	Vmip---r
déanta	déanta	déan-A	Av
agat	agat	ag-P	Pr2-s
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
a	a	a-D	Dp3
fear	fear	fear-N	Ncmsc
céile	céile	céile-N	Ncmsg|Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
ceann	ceann	ceann-N	Ncmsc
amháin	amháin	amháin-A	Aqp
de	de	de-S	Sp
na	na	na-T	Td-p
mianta	mianta	mian-N	Ncfpc
úsáidte	úsáidte	úsáid-A	Av
agat	agat	ag-P	Pr2-s
anois	anois	anois-R	Rt
,	,	,-F	Fi
a	a	a-U	Uv|Dp3
bhean	bhean	bean-N	Ncfsv
gan	gan	gan-S	Sp
chiall	chiall	ciall-N	Ncfsc
.	.	.-F	Fe
Níl	Níl	bí-V	Vmip---n
fágtha	fágtha	fág-A	Av
againn	againn	ag-P	Pr1-p
ach	ach	ach-S	Sp
dhá	dhá	dó-M	Mc
mhian	mhian	mian-N	Ncfsc
anois	anois	anois-R	Rt
.	.	.-F	Fe
’	’	’-F	Fa
Bhí	Bhí	bí-V	Vmis
fearg	fearg	fearg-N	Ncfsc
mhillteanach	mhillteanach	millteanach-A	Aq-fsc
air	air	ar-N	Ncmsg|Pr3ms|Ncmsg
lena	lena	le-S	Spp-s
bhean	bhean	bean-N	Ncfsc
chéile	chéile	céile-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
dá	dá	dá-C	Cs
ngreamódh	ngreamódh	greamaigh-V	Vmc
an	an	an-T	Td-s
t-ispín	t-ispín	ispín-N	Ncmsc
sin	sin	sin-D	Dd
de	de	de-P	Pr3ms
do	do	do-S	Sp
shrón	shrón	srón-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Cha	Cha	cha-Q	Qn
raibh	raibh	bí-V	Vmis---n
na	na	na-T	Td-p
focail	focail	focal-N	Ncmpc
as	as	as-P	Pr3ms
a	a	a-D	Dp3
bhéal	bhéal	béal-N	Ncmsc
i	i	i-S	Sp
gceart	gceart	ceart-N	Ncmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
léim	léim	léim-V	Vmip1s|Vmis
an	an	an-T	Td-s
t-ispín	t-ispín	ispín-N	Ncmsc
ón	ón	ó-S	Spa-s
tine	tine	tine-N	Ncfsc
agus	agus	agus-C	Cc
ghreamaigh	ghreamaigh	greamaigh-V	Vmis
sé	sé	sé-P	Pp3msn
de	de	de-S	Sp
shrón	shrón	srón-N	Ncfsc
a	a	a-D	Dp3
bhean	bhean	bean-N	Ncfsc
chéile	chéile	céile-N	Ncmsg
.	.	.-F	Fe
Is	Is	is-W	Wp-i
ansin	ansin	ansin-R	Rt|Rl
a	a	a-Q	Q-r
thuig	thuig	tuig-V	Vmip|Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
déanta	déanta	déan-A	Av
aige	aige	ag-P	Pr3ms
féin	féin	féin-P	Px
fosta	fosta	fosta-A	Aqp|Rg
.	.	.-F	Fe
Thit	Thit	tit-V	Vmis
an	an	an-T	Td-s
croí	croí	croí-N	Ncmsc
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Anois	Anois	anois-R	Rt
bhí	bhí	bí-V	Vmis
dhá	dhá	dó-M	Mc
cheann	cheann	ceann-N	Ncmsc
de	de	de-S	Sp
na	na	na-T	Td-p
mianta	mianta	mian-N	Ncfpc
úsáidte	úsáidte	úsáid-A	Av
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
seisean	seisean	sé-P	Pp3msne
chomh	chomh	chomh-R	Ri
holc	holc	olc-A	Aqp
lena	lena	le-S	Spp-s
bhean	bhean	bean-N	Ncfsc
chéile	chéile	céile-N	Ncmsg
.	.	.-F	Fe
Rinne	Rinne	déan-V	Vmis
siad	siad	siad-P	Pp3-pn
iarracht	iarracht	iarracht-N	Ncfsc
an	an	an-T	Td-s
t-ispín	t-ispín	ispín-N	Ncmsc
a	a	a-U	U
tharraingt	tharraingt	tarraing-N	Nv
dá	dá	do-S	Spp-s|Spp-p
srón	srón	srón-N	Ncfsc
ach	ach	ach-C	Cs
ní	ní	is-W	Wp-in
bhogfadh	bhogfadh	bog-V	Vmc
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Tharraing	Tharraing	tarraing-V	Vmis
siad	siad	siad-P	Pp3-pn
agus	agus	agus-C	Cc
tharraing	tharraing	tarraing-V	Vmis
siad	siad	siad-P	Pp3-pn
agus	agus	agus-C	Cc
tharraing	tharraing	tarraing-V	Vmis
siad	siad	siad-P	Pp3-pn
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
mo	mo	mo-D	Dp1-s
shrón	shrón	srón-N	Ncfsc
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cha	Cha	cha-Q	Qn
dtig	dtig	tar-V	Vmip
liom	liom	le-P	Pr1-s
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
amach	amach	amach-R	Rd
anois	anois	anois-R	Rt
.	.	.-F	Fe
Beidh	Beidh	bí-V	Vmif
na	na	na-T	Tdfsg
comharsain	comharsain	comharsain-N	Ncfsc
uilig	uilig	uile-D	Dq
ag	ag	ag-S	Sp
magadh	magadh	magadh-N	Nv-----n
fúm	fúm	faoi-P	Pr1-s
.	.	.-F	Fe
’	’	’-F	Fa
Shuigh	Shuigh	suigh-V	Vmis
siad	siad	siad-P	Pp3-pn
ar	ar	ar-S	Sp
dhá	dhá	dó-M	Mc
thaobh	thaobh	taobh-N	Ncmsc
na	na	na-T	Tdfsg
tine	tine	tine-N	Ncfsg
agus	agus	agus-C	Cc
beaguchtach	beaguchtach	beaguchtach-N	Ncmpg|Ncmsc
orthu	orthu	ar-P	Pr3-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cad	Cad	cad-W	W--q
é	é	é-P	Pp3ms
a	a	a-Q	Q-r
dhéanfaidh	dhéanfaidh	déan-V	Vmif
muid	muid	muid-P	Pp1-p
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
lena	lena	le-S	Spp-s
fear	fear	fear-N	Ncmsc
céile	céile	céile-N	Ncmsg|Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
muid	muid	muid-P	Pp1-p
inár	inár	i-S	Spp-p
suí	suí	suí-N	Ncmsc
anseo	anseo	anseo-R	Rl
agus	agus	agus-C	Cc
muid	muid	muid-P	Pp1-p
ag	ag	ag-S	Sp
brionglóideach	brionglóideach	brionglóideach-N	Ncfsc
faoi	faoi	faoi-S	Sp
ór	ór	ór-N	Ncmsc
agus	agus	agus-C	Cc
airgead	airgead	airgead-N	Ncmsc
.	.	.-F	Fe
Nach	Nach	is-W	Wpsin
muid	muid	muid-P	Pp1-p
atá	atá	bí-V	Vmip---r
amaideach	amaideach	amaideach-A	Aqp
agus	agus	agus-C	Cc
santach	santach	santach-A	Aqp
.	.	.-F	Fe
Nach	Nach	nach-Q	Qnr
bhfuil	bhfuil	bí-V	Vmip---n
muid	muid	muid-P	Pp1-p
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
i	i	i-S	Sp
gceart	gceart	ceart-N	Ncmsc
mar	mar	mar-C	Cs
atá	atá	bí-V	Vmip---r
muid	muid	muid-P	Pp1-p
.	.	.-F	Fe
Níl	Níl	bí-V	Vmip---n
saibhreas	saibhreas	saibhreas-N	Ncmsc
a	a	a-U	U
dhíobháil	dhíobháil	díobháil-N	Nv
orainn	orainn	ar-P	Pr1-p
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
A	A	an-T	Td-s
thaisce	thaisce	taisce-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
tar éis	tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
,	,	,-F	Fi
‘	‘	‘-X	Xx
iarr	iarr	iarr-V	Vmm-2s
thusa	thusa	tú-P	Pp2-s-e
an	an	an-T	Td-s
mhian	mhian	mian-N	Ncfsc
dheireanach	dheireanach	deireanach-A	Aq-fsc
ach	ach	ach-S	Sp
glac	glac	glac-N	Ncfsc
d	d	d-X	Xl
’	’	’-F	Fa
am	am	am-N	Ncmsc
agus	agus	agus-C	Cc
smaoinigh	smaoinigh	smaoinigh-V	Vmm-2s
go	go	go-U	Ua
cúramach	cúramach	cúramach-A	Aqp
fá	fá	faoi-P	Pr3ms
dtaobh	dtaobh	taobh-N	Ncmsc
di	di	do-P	Pr3fs
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Bhuel	Bhuel	bhuel-X	Xsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
ní	ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
suaimhneas	suaimhneas	suaimhneas-N	Ncmsc
agamsa	agamsa	ag-P	Pr1-s-e
choíche	choíche	choíche-R	Rg
má	má	má-C	Cs
bhíonn	bhíonn	bí-V	Vmig
an	an	an-T	Td-s
rud	rud	rud-N	Ncmsc
seo	seo	seo-D	Dd
greamaithe	greamaithe	greamaigh-A	Av
de	de	de-P	Pr3ms
mo	mo	mo-D	Dp1-s
shrón	shrón	srón-N	Ncfsc
.	.	.-F	Fe
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
dá	dá	dá-C	Cs
mbeadh	mbeadh	bí-V	Vmc
sé	sé	sé-P	Pp3msn
imithe	imithe	imigh-A	Av
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
thit	thit	tit-V	Vmis
an	an	an-T	Td-s
t-ispín	t-ispín	ispín-N	Ncmsc
dá	dá	do-S	Spp-s|Spp-p
srón	srón	srón-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
sásta	sásta	sásta-A	Aqp
ansin	ansin	ansin-R	Rt|Rl
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nach	Nach	is-C	Cs|Wpdin|Wpsin
muid	muid	muid-P	Pp1-p
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
amaideach	amaideach	amaideach-A	Aqp
agus	agus	agus-C	Cc
santach	santach	santach-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-T	Td-s
té	té	té-N	Ncmsc
nach	nach	nach-Q	Qnr
bhfuil	bhfuil	bí-V	Vmip---n
caora	caora	caor-N	Ncfpc
ná	ná	ná-C	Cs|Cc
bó	bó	bó-N	Ncfsg|Ncfsc|Ncfpg
aige	aige	ag-P	Pr3ms
,	,	,-F	Fi
caora	caora	caor-N	Ncfpc
ná	ná	ná-C	Cs|Cc
bó	bó	bó-N	Ncfsg|Ncfsc|Ncfpg
ní	ní	ní-Q	Qn
chaillfidh	chaillfidh	caill-V	Vmif---n
sé	sé	sé-P	Pp3msn
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
tá	tá	bí-V	Vmip
Dia	Dia	dia-N	Ncmsc
maith	maith	maith-A	Aq-msc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
a	a	a-D	Dp3
fear	fear	fear-N	Ncmsc
céile	céile	céile-N	Ncmsg|Ncmsc
.	.	.-F	Fe
Ón	Ón	ó-S	Spa-s
lá	lá	lá-N	Ncmsc
sin	sin	sin-D	Dd
amach	amach	amach-R	Rd
mhair	mhair	mair-V	Vmis
siad	siad	siad-P	Pp3-pn
go	go	go-U	Ua
sona	sona	sona-A	Aqp
sásta	sásta	sásta-A	Aqp
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
níor	níor	níor-Q	Qn-s
chuir	chuir	cuir-V	Vmis---n
saibhreas	saibhreas	saibhreas-N	Ncmsc
na	na	na-T	Tdfsg
gcomharsan	gcomharsan	comharsa-N	Ncfsg
isteach	isteach	isteach-R	Rd
ná	ná	ná-C	Cc
amach	amach	amach-R	Rd
orthu	orthu	ar-P	Pr3-p
.	.	.-F	Fe
Fadó	Fadó	fadó-R	Rg
,	,	,-F	Fi
fadó	fadó	fadó-R	Rg
bhí	bhí	bí-V	Vmis
cónaí	cónaí	cónaí-N	Ncmsc
ar	ar	ar-S	Sp
fhear	fhear	fear-N	Ncmsc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
bhean	bhean	bean-N	Ncfsc
chéile	chéile	céile-N	Ncmsg
i	i	i-S	Sp
dteach	dteach	teach-N	Ncmsc
beag	beag	beag-A	Aq-msc
faoin	faoin	faoi-S	Spa-s
tuath	tuath	tuath-N	Ncfsc
.	.	.-F	Fe
Chan	Chan	can-V	Vmis
daoine	daoine	duine-N	Ncmpc
saibhre	saibhre	saibhir-A	Aq--pg|Aq--pc|Aq--pv
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
iontu	iontu	i-P	Pr3-p
ar	ar	ar-S	Sp
chor	chor	cor-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
ach	ach	ach-S	Sp|Cs
iad	iad	iad-P	Pp3-p
beo	beo	beo-A	Aqp
bocht	bocht	bocht-A	Aqp
.	.	.-F	Fe
