Suaircín	Suaircín	Suaircín-N	Npmsc
Bhí	Bhí	bí-V	Vmis
cailín	cailín	cailín-N	Ncmsc
beag	beag	beag-A	Aq-msc
ann	ann	i-P	Pr3ms
fadó	fadó	fadó-R	Rg
–	–	–-X	Xx
is	is	agus-W	Wp-i|Wpri|Cc
minic	minic	minic-A	Aqp|Rg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
agus	agus	agus-C	Cc
beidh	beidh	bí-V	Vmif
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
beagán	beagán	beagán-N	Ncmsc
cosúil	cosúil	cosúil-A	Aq-msc
leatsa	leatsa	le-P	Pr2-s-e
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
aici	aici	ag-P	Pr3fs
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
aici	aici	ag-P	Pr3fs
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
deartháir	deartháir	deartháir-N	Ncmsc
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
teach	teach	teach-N	Ncmsc
aici	aici	ag-P	Pr3fs
le	le	le-S	Sp
cónaí	cónaí	cónaigh-N	Nv
ann	ann	ann-R	Rl
,	,	,-F	Fi
chomh	chomh	chomh-R	Ri
deas	deas	deas-A	Aqp
is	is	agus-C	Cc
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
tú	tú	tú-P	Pp2-s
riamh	riamh	riamh-R	Rg
,	,	,-F	Fi
agus	agus	agus-C	Cc
bhíodh	bhíodh	bí-V	Vmih
rudaí	rudaí	rud-N	Ncmpc
deasa	deasa	deas-A	Aq--pc
le	le	le-S	Sp
n-ithe	n-ithe	ith-N	Nv
agus	agus	agus-C	Cc
le	le	le-S	Sp
n-ól	n-ól	ól-N	Nv
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
a	a	a-U	Ud|Dp3
Mamaí	Mamaí	mama-N	Ncfsc|Aqc|Ncmpc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
Daidí	Daidí	daidí-N	Ncmsc
cion	cion	cion-N	Ncmsc
ó	ó	ó-S	Sp
chroí	chroí	croí-N	Ncmsc
di	di	do-P	Pr3fs
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
dá	dá	do-S	Spp-s
deartháir	deartháir	deartháir-N	Ncmsc
.	.	.-F	Fe
Bhíodh	Bhíodh	bí-V	Vmih
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
ag	ag	ag-S	Sp
smaoineamh	smaoineamh	smaoinigh-N	Nv
conas	conas	conas-R	Rq
a	a	a-Q	Q-r
spárálfadh	spárálfadh	spáráil-V	Vmc
sí	sí	sí-P	Pp3fsn
airgead	airgead	airgead-N	Ncmsc
chun	chun	chun-S	Sp
éadaí	éadaí	éadach-N	Ncmpg
nua	nua	nua-A	Aqp
a	a	a-U	U
cheannach	cheannach	ceannaigh-N	Nv
dóibh	dóibh	do-P	Pr3-p
.	.	.-F	Fe
Thógadh	Thógadh	tóg-V	Vmih
Daidí	Daidí	daidí-N	Ncmsc
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
ghlúine	ghlúine	glúin-N	Ncfpc
iad	iad	iad-P	Pp3-p
gach	gach	gach-D	Dq
oíche	oíche	oíche-N	Ncfsc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
insíodh	insíodh	inis-V	Vmih
sé	sé	sé-P	Pp3msn
scéalta	scéalta	scéal-N	Ncmpc
iontacha	iontacha	iontach-A	Aq--pc
dóibh	dóibh	do-P	Pr3-p
faoin	faoin	faoi-S	Spa-s
slua	slua	slua-N	Ncmsc
sí	sí	sí-P	Pp3fsn
;	;	;-F	Fi
faoi	faoi	faoi-S	Sp
Dhonn	Dhonn	Donn-N	Npmsc
agus	agus	agus-C	Cc
Clíona	Clíona	Clíona-N	Npmsc
agus	agus	agus-C	Cc
Aoibheall	Aoibheall	aoibheall-N	Ncmsc|Ncmpg
agus	agus	agus-C	Cc
Áine	Áine	Áine-N	Npf-g|Npfsc
a	a	a-Q	Q-r
mhair	mhair	mair-V	Vmis
sna	sna	i-S	Spa-p
síbhruíonta	síbhruíonta	síbhruíon-N	Ncfpc
faoi	faoi	faoi-S	Sp
na	na	na-T	Td-p
cnoic	cnoic	cnoc-N	Ncmpc
san	san	i-S	Spa-s
anallód	anallód	anallód-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
an	an	an-T	Td-s
cailín	cailín	cailín-N	Ncmsc
beag	beag	beag-A	Aq-msc
sásta	sásta	sásta-A	Aqp
.	.	.-F	Fe
Ó	Ó	ó-S	Sp
mhaidin	mhaidin	maidin-N	Ncfsc
go	go	go-S	Sp
hoíche	hoíche	oíche-N	Ncfsc
bhíodh	bhíodh	bí-V	Vmih
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
clamhsán	clamhsán	clamhsán-N	Ncmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
rud	rud	rud-N	Ncmsc
le	le	le-S	Sp
déanamh	déanamh	déan-N	Nv
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
'	'	'-F	Fa
Agus	Agus	agus-C	Cc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
a	a	a-D	Dp3
máthair	máthair	máthair-N	Ncfsc
léi	léi	le-P	Pr3fs
,	,	,-F	Fi
lá	lá	lá-N	Ncmsc
amháin	amháin	amháin-A	Aqp
,	,	,-F	Fi
‘	‘	‘-X	Xx
Cad	Cad	cad-P	Pq|W--q
mar	mar	mar-S	Sp
gheall	gheall	geall-N	Ncmsc
ar	ar	ar-S	Sp
obair	obair	obair-N	Nv-----n
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
?	?	?-F	Fq
'	'	'-F	Fa
chuir	chuir	cuir-V	Vmis
sí	sí	sí-P	Pp3fsn
púic	púic	púic-N	Ncfsc
chomh	chomh	chomh-R	Ri
gránna	gránna	gránna-A	Aqp
sin	sin	sin-P	Pd|W|Dd
uirthi	uirthi	ar-P	Pr3fs
féin	féin	féin-P	Px
go	go	go-Q	Q
ndúirt	ndúirt	abair-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
,	,	,-F	Fi
‘	‘	‘-X	Xx
A	A	an-T	Td-s
leithéid	leithéid	leithéid-N	Ncfsc
de	de	de-S	Sp
phúic	phúic	púic-N	Ncfsc
.	.	.-F	Fe
Scanróidh	Scanróidh	scanraigh-V	Vmif
tú	tú	tú-P	Pp2-s
na	na	na-T	Td-p
daoine	daoine	duine-N	Ncmpc
maithe	maithe	maith-A	Aq--pg|Aq--pc|Aq--pv
.	.	.-F	Fe
'	'	'-F	Fa
Scanróidh	Scanróidh	scanraigh-V	Vmif
tú	tú	tú-P	Pp2-s
na	na	na-T	Td-p
daoine	daoine	duine-N	Ncmpc
maithe	maithe	maith-A	Aq--pg|Aq--pc|Aq--pv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Na	Na	na-T	Td-p
daoine	daoine	duine-N	Ncmpc
maithe	maithe	maith-A	Aq--pg|Aq--pc|Aq--pv
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
cailín	cailín	cailín-N	Ncmsc
beag	beag	beag-A	Aq-msc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cé	Cé	cé-W	W--q
hiad	hiad	iad-P	Pp3-p
na	na	na-T	Td-p
daoine	daoine	duine-N	Ncmpc
maithe	maithe	maith-A	Aq--pg|Aq--pc|Aq--pv
?	?	?-F	Fq
'	'	'-F	Fa
‘	‘	‘-X	Xx
An	An	an-T	Td-s
slua	slua	slua-N	Ncmsc
sí	sí	sí-P	Pp3fsn
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
,	,	,-F	Fi
‘	‘	‘-X	Xx
agus	agus	agus-C	Cc
má	má	má-C	Cs
théann	théann	téigh-V	Vmip
tú	tú	tú-P	Pp2-s
síos	síos	síos-R	Rd
go	go	go-S	Sp
bun	bun	bun-N	Ncmsc
an	an	an-T	Td-s
gharraí	gharraí	garraí-N	Ncmsg
,	,	,-F	Fi
amach	amach	amach-R	Rd
as	as	as-S	Sp
seo	seo	seo-P	Pd
faoi	faoi	faoi-P	Pr3ms
mo	mo	mo-D	Dp1-s
chosa	chosa	cos-N	Ncfpc
,	,	,-F	Fi
b	b	b-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
go	go	go-Q	Q
bhfeicfidh	bhfeicfidh	feic-V	Vmif
tú	tú	tú-P	Pp2-s
iad	iad	iad-P	Pp3-p
faoin	faoin	faoi-S	Spa-s
gcrann	gcrann	crann-N	Ncmsc
caorthainn	caorthainn	caorthann-N	Ncmsg|Ncmpc
.	.	.-F	Fe
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
a lán	a lán	a_lán-N	Ns-s
le	le	le-S	Sp
déanamh	déanamh	déan-N	Nv
ag	ag	ag-S	Sp
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
sin	sin	sin-D	Dd
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
ag	ag	ag-S	Sp
cabhrú	cabhrú	cabhraigh-N	Nv
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
an	an	an-T	Td-s
cailín	cailín	cailín-N	Ncmsc
beag	beag	beag-A	Aq-msc
síos	síos	síos-R	Rd
go	go	go-S	Sp
bun	bun	bun-N	Ncmsc
an	an	an-T	Td-s
gharraí	gharraí	garraí-N	Ncmsg
agus	agus	agus-C	Cc
shuigh	shuigh	suigh-V	Vmis
sí	sí	sí-P	Pp3fsn
síos	síos	síos-R	Rd
faoin	faoin	faoi-S	Spa-s
gcrann	gcrann	crann-N	Ncmsc
caorthainn	caorthainn	caorthann-N	Ncmsg|Ncmpc
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
sí	sí	sí-P	Pp3fsn
faoi	faoi	faoi-S	Sp
deara	deara	deara-N	Ns-s
na	na	na-T	Td-p
beacha	beacha	beach-N	Ncfpc
broidiúla	broidiúla	broidiúil-A	Aq--pc
ag	ag	ag-S	Sp
bailiú	bailiú	bailigh-N	Nv
meala	meala	mil-N	Ncfsg
,	,	,-F	Fi
na	na	na-T	Td-p
féileacáin	féileacáin	féileacán-N	Ncmpc
ag	ag	ag-S	Sp
eitilt	eitilt	eitil-N	Nv
ó	ó	ó-S	Sp
bhláth	bhláth	bláth-N	Ncmsc
go	go	go-S	Sp
bláth	bláth	bláth-N	Ncmsc
,	,	,-F	Fi
agus	agus	agus-C	Cc
iontais	iontais	iontas-N	Ncmsg|Ncmpc|Ncmsg
uile	uile	uile-N	Ns-s|Dq
an	an	an-T	Td-s
nádúir	nádúir	nádúr-N	Ncmsg
ina	ina	i-S	Spp-s
timpeall	timpeall	timpeall-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
smaoineamh	smaoineamh	smaoinigh-N	Nv
di	di	do-P	Pr3fs
féin	féin	féin-P	Px
gur	gur	is-W	Wsdi|Wpdi
dheas	dheas	deas-A	Aqp
dá	dá	dá-C	Cs
mbeadh	mbeadh	bí-V	Vmc
slua	slua	slua-N	Ncmsc
sí	sí	sí-P	Pp3fsn
,	,	,-F	Fi
nó	nó	nó-C	Cc
fiú	fiú	fiú-N	Ncmsg|Ncmsc|Rg|Ns-s
sióigín	sióigín	sióigín-N	Ncmsc
bheag	bheag	beag-A	Aq-msc
amháin	amháin	amháin-A	Aqp
,	,	,-F	Fi
a	a	a-Q	Q-r
thiocfadh	thiocfadh	tar-V	Vmc
i	i	i-S	Sp
gcabhair	gcabhair	cabhar-N	Ncfsc|Ncmpc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-U	Ud|Dp3
Mamaí	Mamaí	mama-N	Ncfsc|Aqc|Ncmpc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
méid	méid	méid-N	Ncmsc
sin	sin	sin-D	Dd
oibre	oibre	obair-N	Ncfsg|Nv--g--n
le	le	le-S	Sp
déanamh	déanamh	déan-N	Nv
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
,	,	,-F	Fi
chuala	chuala	clois-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
glór	glór	glór-N	Ncmsc
in aice	in aice	in_aice-S	Spc
léi	léi	le-P	Pr3fs
–	–	–-X	Xx
guth	guth	guth-N	Ncmsc
caoin	caoin	caoin-A	Aq-msc
séimh	séimh	séimh-A	Aq-msc
ceolmhar	ceolmhar	ceolmhar-A	Aq-msc
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
,	,	,-F	Fi
‘	‘	‘-X	Xx
Abair	Abair	abar-N	Ncmpc
liom	liom	le-P	Pr1-s
,	,	,-F	Fi
a	a	a-U	Uv
linbh	linbh	leanbh-N	Ncmsv
,	,	,-F	Fi
cad	cad	cad-P	Pq
a	a	a-Q	Q-r
thug	thug	tabhair-V	Vmis
anseo	anseo	anseo-R	Rl
thú	thú	tú-P	Pp2-s
?	?	?-F	Fq
'	'	'-F	Fa
Abair	Abair	abar-N	Ncmpc
liom	liom	le-P	Pr1-s
,	,	,-F	Fi
a	a	a-U	Uv
linbh	linbh	leanbh-N	Ncmsv
,	,	,-F	Fi
cad	cad	cad-P	Pq
a	a	a-Q	Q-r
thug	thug	tabhair-V	Vmis
anseo	anseo	anseo-R	Rl
thú	thú	tú-P	Pp2-s
?	?	?-F	Fq
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
an	an	an-T	Td-s
cailín	cailín	cailín-N	Ncmsc
beag	beag	beag-A	Aq-msc
suas	suas	suas-R	Rd
agus	agus	agus-C	Cc
ansiúd	ansiúd	ansiúd-R	Rl
le hais	le hais	le_hais-S	Spc
an	an	an-T	Td-s
chrainn	chrainn	crann-N	Ncmsg
bhí	bhí	bí-V	Vmis
bean	bean	bean-N	Ncfsc
uasal	uasal	uasal-A	Aq-fsc
ina	ina	i-S	Spp-p|Spp-s
seasamh	seasamh	seasamh-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sí	sí	sí-P	Pp3fsn
óg	óg	óg-A	Aqp
ná	ná	ná-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sí	sí	sí-P	Pp3fsn
críonna	críonna	críonna-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
cineáltas	cineáltas	cineáltas-N	Ncmsc
agus	agus	agus-C	Cc
tuiscint	tuiscint	tuig-N	Ncfsc|Nv
le	le	le-S	Sp
léamh	léamh	léigh-N	Nv
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
haghaidh	haghaidh	aghaidh-N	Ncfsc
álainn	álainn	álainn-A	Aq-fsv|Aq-fsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhreagair	fhreagair	freagair-V	Vmis
an	an	an-T	Td-s
cailín	cailín	cailín-N	Ncmsc
beag	beag	beag-A	Aq-msc
í	í	í-P	Pp3fs
,	,	,-F	Fi
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
lorg	lorg	lorg-N	Nv
na	na	na-T	Td-p
ndaoine	ndaoine	duine-N	Ncmpg
maithe	maithe	maith-A	Aq--pg
.	.	.-F	Fe
'	'	'-F	Fa
Rinne	Rinne	déan-V	Vmis
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
uasal	uasal	uasal-A	Aq-fsc
gáire	gáire	gáir-N	Ncmsc|Nv
ach	ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
brón	brón	brón-N	Ncmsc
ina	ina	i-S	Spp-p|Spp-s
súile	súile	súil-N	Ncfpc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
labhair	labhair	labhair-V	Vmis
sí	sí	sí-P	Pp3fsn
,	,	,-F	Fi
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
mo	mo	mo-D	Dp1-s
chroí	chroí	croí-N	Ncmsc
thú	thú	tú-P	Pp2-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
gach	gach	gach-D	Dq
lá	lá	lá-N	Ncmsc
a	a	a-Q	Q-r
chastar	chastar	cas-V	Vmip0
na	na	na-T	Td-p
daoine	daoine	duine-N	Ncmpc
maithe	maithe	maith-A	Aq--pc
ort	ort	ar-P	Pr2-s
–	–	–-X	Xx
agus	agus	agus-C	Cc
fiú	fiú	fiú-N	Ncmsg|Ncmsc|Rg|Ns-s
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chastar	chastar	cas-V	Vmip0
ort	ort	ar-P	Pr2-s
iad	iad	iad-P	Pp3-p
seans	seans	seans-N	Ncmsc
nach	nach	nach-Q	Qnr
n-aithneofá	n-aithneofá	aithin-V	Vmc-2s
iad	iad	iad-P	Pp3-p
mar	mar	mar-S	Sp
dhaoine	dhaoine	duine-N	Ncmpc
maithe	maithe	maith-A	Aq--pg|Aq--pc|Aq--pv
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
gabh	gabh	gabh-V	Vmm-2s
i	i	i-S	Sp
leith	leith	leith-N	Ncfsc
tusa	tusa	tú-P	Pp2-s-e
chun	chun	chun-S	Sp
an	an	an-T	Td-s
tobair	tobair	tobar-N	Ncmsg
.	.	.-F	Fe
Gabh	Gabh	gabh-V	Vmm-2s
síos	síos	síos-R	Rd
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
do	do	do-S	Sp
ghlúine	ghlúine	glúin-N	Ncfpc
agus	agus	agus-C	Cc
corraigh	corraigh	corrach-N	Ncmpc|Ncmsg
an	an	an-T	Td-s
t-uisce	t-uisce	uisce-N	Ncmsc
agus	agus	agus-C	Cc
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
aithris	aithris	aithris-N	Nv
an	an	an-T	Td-s
rainn	rainn	rann-N	Ncmsg
seo	seo	seo-D	Dd
:	:	:-F	Fi
CORRAÍM	CORRAÍM	corraigh-V	Vmip1s
AN	AN	an-T	Td-s
tUISCE	tUISCE	tuisce-N	Ncfsc
GO	GO	go-S	Sp
bhFEICE	bhFEICE	bhFEICE-N	Nc
MÉ	MÉ	mé-P	Pp1-s
AN	AN	an-T	Td-s
FHÍS	FHÍS	fís-N	Ncfsc
.	.	.-F	Fe
DHEINEAS	DHEINEAS	dein-V	Vmis1s
AGUS	AGUS	agus-C	Cc
CHONAC	CHONAC	feic-V	Vmis1s
…	…	…-F	Fi
Feicfidh	Feicfidh	feic-V	Vmif
tú	tú	tú-P	Pp2-s
críoch	críoch	críoch-N	Ncfsc
an	an	an-T	Td-s
rainn	rainn	rann-N	Ncmsg
sa	sa	i-S	Spa-s
tobar	tobar	tobar-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|Dd
.	.	.-F	Fe
'	'	'-F	Fa
Rinne	Rinne	déan-V	Vmis
an	an	an-T	Td-s
cailín	cailín	cailín-N	Ncmsc
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
chiúnaigh	chiúnaigh	ciúnaigh-V	Vmis
an	an	an-T	Td-s
t-uisce	t-uisce	uisce-N	Ncmsc
d	d	d-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
sí	sí	sí-P	Pp3fsn
síos	síos	síos-R	Rd
,	,	,-F	Fi
a	a	a-U	Uv
súile	súile	súil-N	Ncfpv
ar	ar	ar-S	Sp
dianleathadh	dianleathadh	dianleathadh-N	Ns-s
le	le	le-S	Sp
bís	bís	bís-N	Ncfsc
.	.	.-F	Fe
Céard	Céard	cé-W	W--q
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
sí	sí	sí-P	Pp3fsn
ach	ach	ach-S	Sp|Cs
a	a	a-D	Dp3
scáil	scáil	scál-N	Ncfsc|Ncmpc
féin	féin	féin-P	Px
ag	ag	ag-S	Sp
breathnú	breathnú	breathnaigh-N	Nv
aníos	aníos	aníos-R	Rd
uirthi	uirthi	ar-P	Pr3fs
ón	ón	ó-S	Spa-s
uisce	uisce	uisce-N	Ncmsc
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
críoch	críoch	críoch-N	Ncfsc
an	an	an-T	Td-s
rainn	rainn	rann-N	Ncmsg
chuici	chuici	chuig-P	Pr3fs
ar	ar	ar-S	Sp
an	an	an-T	Td-s
toirt	toirt	toirt-N	Ncfsc
.	.	.-F	Fe
CORRAÍM	CORRAÍM	corraigh-V	Vmip1s
AN	AN	an-T	Td-s
tUISCE	tUISCE	tuisce-N	Ncfsc
GO	GO	go-S	Sp
bhFEICE	bhFEICE	bhFEICE-N	Nc
MÉ	MÉ	mé-P	Pp1-s
AN	AN	an-T	Td-s
FHÍS	FHÍS	fís-N	Ncfsc
.	.	.-F	Fe
DHEINEAS	DHEINEAS	dein-V	Vmis1s
AGUS	AGUS	agus-C	Cc
CHONAC	CHONAC	feic-V	Vmis1s
…	…	…-F	Fi
…	…	…-F	Fi
MO	MO	mo-D	Dp1-s
SCÁILSE	SCÁILSE	scál-N	Ncfsc-e|Ncmpc-e|Ncfsc-e|Ncmpc-e
FÉIN	FÉIN	féin-P	Px
THÍOS	THÍOS	thíos-R	Rd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
álainn	álainn	álainn-A	Aq-fsc
fós	fós	fós-R	Rg
taobh	taobh	taobh-N	Ncmsc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
cé	cé	cé-W	W--q
tusa	tusa	tú-P	Pp2-s-e
?	?	?-F	Fq
'	'	'-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
cailín	cailín	cailín-N	Ncmsc
beag	beag	beag-A	Aq-msc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhreagair	fhreagair	freagair-V	Vmis
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
uasal	uasal	uasal-A	Aq-fsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
Is	Is	is-W	Wpri
mise	mise	mé-P	Pp1-s-e
an	an	an-T	Td-s
mháthair	mháthair	máthair-N	Ncfsc
áil	áil	áil-V	Vmis
.	.	.-F	Fe
Táim	Táim	bí-V	Vmip1s
chomh	chomh	chomh-R	Ri
sean	sean	sean-A	Aqp
leis	leis	le-S	Sp
an	an	an-T	Td-s
gceo	gceo	ceo-N	Ncmsc
,	,	,-F	Fi
agus	agus	agus-C	Cc
is	is	is-U	U
mó	mó	mór-A	Aqc
ainm	ainm	ainm-N	Ncmsg
a	a	a-Q	Q-r
thug	thug	tabhair-V	Vmis
agus	agus	agus-C	Cc
a	a	a-Q	Q-r
thugann	thugann	tabhair-V	Vmip
daoine	daoine	duine-N	Ncmpc
orm	orm	ar-P	Pr1-s
:	:	:-F	Fi
Éadaoin	Éadaoin	Éadaoin-N	Npfsc
agus	agus	agus-C	Cc
Aoife	Aoife	Aoife-N	Npf-g|Npfsc
agus	agus	agus-C	Cc
Donn	Donn	Donn-N	Npmsc
sa	sa	i-S	Spa-s
sean-am	sean-am	sean-am-N	Ncmsc
,	,	,-F	Fi
agus	agus	agus-C	Cc
arís	arís	arís-R	Rg
Bríd	Bríd	Bríd-N	Npfsc
agus	agus	agus-C	Cc
Íde	Íde	Íde-N	Npmsg|Npfsg
agus	agus	agus-C	Cc
Gobnait	Gobnait	Gobnait-N	Npf-g|Npfsc
ar	ar	ar-S	Sp
ball	ball	ball-N	Ncmsc
,	,	,-F	Fi
ach	ach	ach-C	Cs
níl	níl	bí-V	Vmip---n
rún	rún	rún-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
i	i	i-S	Sp
gcroí	gcroí	croí-N	Ncmsc
an	an	an-T	Td-s
duine	duine	duine-N	Ncmsg
nach	nach	nach-Q	Qnr
bhfuil	bhfuil	bí-V	Vmip---n
fuascailt	fuascailt	fuascail-N	Ncfsc|Nv
agam	agam	ag-P	Pr1-s
air	air	ar-P	Pr3ms
…	…	…-F	Fi
…	…	…-F	Fi
agus	agus	agus-C	Cc
tuigim	tuigim	tuig-V	Vmip1s
cailíní	cailíní	cailín-N	Ncmpc
beaga	beaga	beag-A	Aq--pc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
máithreacha	máithreacha	máthair-N	Ncfpc
freisin	freisin	freisin-R	Rg
.	.	.-F	Fe
Is	Is	is-W	Wp-i
mise	mise	mé-P	Pp1-s-e
an	an	an-T	Td-s
mháthair	mháthair	máthair-N	Ncfsc
áil	áil	áil-V	Vmis
…	…	…-F	Fi
Agus	Agus	agus-C	Cc
cé	cé	cé-W	W--q|Pq
tusa	tusa	tú-P	Pp2-s-e
?	?	?-F	Fq
Chuaigh	Chuaigh	téigh-V	Vmis
an	an	an-T	Td-s
cailín	cailín	cailín-N	Ncmsc
beag	beag	beag-A	Aq-msc
síos	síos	síos-R	Rd
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
glúine	glúine	glúin-N	Ncfpc
.	.	.-F	Fe
Líon	Líon	líon-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
dá	dá	do-S	Spp-s|Spp-p|Spp-s|Spp-p
lámh	lámh	lámh-N	Ncfsc
den	den	de-S	Spa-s
fhíoruisce	fhíoruisce	fíoruisce-N	Ncmsc
fuar	fuar	fuar-A	Aq-msc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
ól	ól	ól-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
Dúirt	Dúirt	abair-V	Vmis
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
uasal	uasal	uasal-A	Aq-fsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
Ón	Ón	ó-S	Spa-s
am	am	am-N	Ncmsc
seo	seo	seo-D	Dd
amach	amach	amach-R	Rd
,	,	,-F	Fi
bí	bí	bí-N	Ncfsc
cuiditheach	cuiditheach	cuiditheach-A	Aqp
,	,	,-F	Fi
geanúil	geanúil	geanúil-A	Aqp
,	,	,-F	Fi
misniúil	misniúil	misniúil-A	Aqp
,	,	,-F	Fi
suairc	suairc	suairc-A	Aqp
,	,	,-F	Fi
mar	mar	mar-C	Cs
tuigeann	tuigeann	tuig-V	Vmip
tú	tú	tú-P	Pp2-s
anois	anois	anois-R	Rt
an	an	an-T	Td-s
cairdeas	cairdeas	cairdeas-N	Ncmsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
grá	grá	grá-N	Ncmsg|Ncmsc
agus	agus	agus-C	Cc
ceangal	ceangal	ceangal-N	Ncmsc
an	an	an-T	Td-s
teaghlaigh	teaghlaigh	teaghlach-N	Ncmsg
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
tabharfar	tabharfar	tabhair-V	Vmif0
“	“	“-F	Fa
SUAIRCÍN	SUAIRCÍN	suaircín-N	Ncmsc
”	”	”-F	Fa
ort	ort	ar-P	Pr2-s
toisc	toisc	toisc-N	Ncfsc
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
bua	bua	bua-N	Ncmsc
an	an	an-T	Td-s
tsuaircis	tsuaircis	suairceas-N	Ncmsg
bainte	bainte	bain-A	Av
amach	amach	amach-R	Rd
agat	agat	ag-P	Pr2-s
.	.	.-F	Fe
'	'	'-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
eitil	eitil	eitil-V	Vmm-2s
rud	rud	rud-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
sciathánach	sciathánach	sciathánach-A	Aq-msc
thar	thar	thar-S	Sp
aghaidh	aghaidh	aghaidh-N	Ncfsc
an	an	an-T	Td-s
chailín	chailín	cailín-N	Ncmsg
agus	agus	agus-C	Cc
thuirling	thuirling	tuirling-V	Vmis
ar	ar	ar-S	Sp
bhrollach	bhrollach	brollach-N	Ncmsc
a	a	a-D	Dp3
gúna	gúna	gúna-N	Ncmsc
.	.	.-F	Fe
Cad	Cad	cad-P	Pq
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
?	?	?-F	Fq
…	…	…-F	Fi
Ú-ú-ú	Ú-ú-ú	Ú-ú-ú-N	Npmsc
,	,	,-F	Fi
bóín	bóín	bóín-N	Ncfsc
Dé	Dé	dia-N	Ncmsg
.	.	.-F	Fe
Tabharfar	Tabharfar	tabhair-V	Vmif0
“	“	“-F	Fa
SUAIRCÍN	SUAIRCÍN	suaircín-N	Ncmsc
”	”	”-F	Fa
ort	ort	ar-P	Pr2-s
.	.	.-F	Fe
Shiúil	Shiúil	siúil-V	Vmis
an	an	an-T	Td-s
cailín	cailín	cailín-N	Ncmsc
beag	beag	beag-A	Aq-msc
go	go	go-U	Ua
mall	mall	mall-A	Aqp
,	,	,-F	Fi
mall	mall	mall-A	Aqp
,	,	,-F	Fi
go dtí	go dtí	go_dtí-S	Spc
doras	doras	doras-N	Ncmsc
na	na	na-T	Tdfsg
cistine	cistine	cistin-N	Ncfsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-U	Ud|Dp3
Mamaí	Mamaí	mama-N	Ncfsc|Aqc|Ncmpc
ann	ann	i-R	Rl|Pr3ms
roimpi	roimpi	roimh-P	Pr3fs
agus	agus	agus-C	Cc
phógadar	phógadar	póg-V	Vmis3p
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Dúirt	Dúirt	abair-V	Vmis
an	an	an-T	Td-s
cailín	cailín	cailín-N	Ncmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
Daidí	Daidí	daidí-N	Ncmsc
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
abhaile	abhaile	abhaile-R	Rd
aon	aon	aon-D	Dq
nóiméad	nóiméad	nóiméad-N	Ncmsc
anois	anois	anois-R	Rt
–	–	–-X	Xx
leagfaidh	leagfaidh	leag-V	Vmif
mise	mise	mé-P	Pp1-s-e
an	an	an-T	Td-s
bord	bord	bord-N	Ncmsc
duit	duit	do-P	Pr2-s
le	le	le-S	Sp
haghaidh	haghaidh	aghaidh-N	Ncfsc
an	an	an-T	Td-s
tae	tae	tae-N	Ncmsg
.	.	.-F	Fe
'	'	'-F	Fa
Chuidigh	Chuidigh	cuidigh-V	Vmis
sí	sí	sí-P	Pp3fsn
lena	lena	le-S	Spp-p|Spp-s
máthair	máthair	máthair-N	Ncfsc
le	le	le-S	Sp
fonn	fonn	fonn-N	Ncmsc
,	,	,-F	Fi
a	a	a-D	Dp3
croí	croí	croí-N	Ncmsc
lán	lán	lán-A	Aq-msc
d	d	d-X	Xl
’	’	’-F	Fa
áthas	áthas	áthas-N	Ncmsc
agus	agus	agus-C	Cc
grá	grá	grá-N	Nv|Ncmsg|Ncmsc
–	–	–-X	Xx
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
fhan	fhan	fan-V	Vmis
an	an	an-T	Td-s
bóín	bóín	bóín-N	Ncfsc
Dé	Dé	dia-N	Ncmsg
go	go	go-U	Ua
ciúin	ciúin	ciúin-A	Aqp
socair	socair	socair-A	Aqp
ar	ar	ar-S	Sp
bhrollach	bhrollach	brollach-N	Ncmsc
a	a	a-D	Dp3
gúna	gúna	gúna-N	Ncmsc
.	.	.-F	Fe
