Maidin	Maidin	maidin-N	Ncfsc
Shathairn	Shathairn	Satharn-N	Ncmsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
agus	agus	agus-C	Cc
Daidí	Daidí	daidí-N	Ncmsc|Ncmsg
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
ag	ag	ag-S	Sp
siopadóireacht	siopadóireacht	siopadóir-N	Nv-----n
sa	sa	i-S	Spa-s
bhaile	bhaile	baile-N	Ncmsc
mór	mór	mór-A	Aq-msc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
agus	agus	agus-C	Cc
Daideo	Daideo	daideo-N	Ncmsc|Ncmsg
tagtha	tagtha	tar-A	Av
chun	chun	chun-S	Sp
aire	aire	aire-N	Ncfsg|Ncmsg
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
do	do	do-S	Sp
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Slán	Slán	slán-N	Ncmsc
libh	libh	le-P	Pr2-p
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Muireann	Muireann	Muireann-N	Npfsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
agus	agus	agus-C	Cc
Daidí	Daidí	daidí-N	Ncmsc|Ncmsg
ag	ag	ag-S	Sp
imeacht	imeacht	imigh-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
súil	súil	súil-N	Ncfsc
agam	agam	ag-P	Pr1-s
go	go	go-Q	Q
mbeidh	mbeidh	bí-V	Vmif
lá	lá	lá-N	Ncmsc
deas	deas	deas-A	Aq-msc
agaibh	agaibh	ag-P	Pr2-p
.	.	.-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
ná	ná	ná-Q	Qnm
déanaigí	déanaigí	déan-V	Vmm-2p-n
dearmad	dearmad	dearmad-N	Ncmsc
milseáin	milseáin	milseán-N	Ncmpc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
chugainn	chugainn	chuig-P	Pr1-p
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Conall	Conall	Conall-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
bhricfeasta	bhricfeasta	bricfeasta-N	Ncmsc
againn	againn	ag-P	Pr1-p
fós	fós	fós-R	Rg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Muireann	Muireann	Muireann-N	Npfsc
le	le	le-S	Sp
Mamó	Mamó	mamó-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
a	a	a-U	Uv
chréatúir	chréatúir	créatúr-N	Ncmsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
bhricfeasta	bhricfeasta	bricfeasta-N	Ncmsc
agaibh	agaibh	ag-P	Pr2-p
fós	fós	fós-R	Rg
.	.	.-F	Fe
'	'	'-F	Fa
Isteach	Isteach	isteach-R	Rd
léi	léi	le-P	Pr3fs
sa	sa	i-S	Spa-s
chistin	chistin	cistin-N	Ncfsc
.	.	.-F	Fe
Tamall	Tamall	tamall-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|Dd
sháigh	sháigh	sáigh-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
ceann	ceann	ceann-N	Ncmsc
amach	amach	amach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	an-T	Td-s
Mhuireann	Mhuireann	Muireann-N	Npfsc
!	!	!-F	Fe
A	A	a-U	Uv
Chonaill	Chonaill	Conall-N	Npm-v
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
bricfeasta	bricfeasta	bricfeasta-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbord	mbord	bord-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
Shuigh	Shuigh	suigh-V	Vmis
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
chun	chun	chun-S	Sp
boird	boird	bord-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
a	a	a-U	Uv
Mhamó	Mhamó	mamó-N	Ncfsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Muireann	Muireann	Muireann-N	Npfsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
ní	ní	ní-Q	Qn
fhéadfainn	fhéadfainn	féad-V	Vmc-1s-n
é	é	é-P	Pp3ms
seo	seo	seo-P	Pd
a	a	a-U	U
ithe	ithe	ith-N	Nv
.	.	.-F	Fe
Is	Is	is-W	Wp-i
é	é	é-P	Pp3ms
seo	seo	seo-P	Pd
an	an	an-T	Td-s
rud	rud	rud-N	Ncmsc
a	a	a-Q	Q-r
thugaimid	thugaimid	tabhair-V	Vmip1p
le	le	le-S	Sp
hithe	hithe	ith-N	Nv
do	do	do-S	Sp
Chócó	Chócó	cócó-N	Ncmsc
an	an	an-T	Td-s
madra	madra	madra-N	Ncmsg
!	!	!-F	Fe
’	’	’-F	Fa
.	.	.-F	Fe
‘	‘	‘-X	Xx
Go	Go	go-Q	Q-s
bhfóire	bhfóire	fóir-V	Vmsp
Dia	Dia	dia-N	Ncmsc
orainn	orainn	ar-P	Pr1-p
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seans	Seans	seans-N	Ncmsc
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
an	an	an-T	Td-s
ceart	ceart	ceart-N	Ncmsc
agat	agat	ag-P	Pr2-s
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
mo	mo	mo-D	Dp1-s
spéaclaí	spéaclaí	spéacla-N	Ncmpc
caillte	caillte	caill-A	Av
agam	agam	ag-P	Pr1-s
agus	agus	agus-C	Cc
ní	ní	is-W	Wp-in
féidir	féidir	féidir-N	Ns-s
liom	liom	le-P	Pr1-s
aon	aon	aon-D	Dq
rud	rud	rud-N	Ncmsc
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
gan	gan	gan-S	Sp
iad	iad	iad-P	Pp3-p
.	.	.-F	Fe
Táim	Táim	bí-V	Vmip1s
chomh	chomh	chomh-R	Ri
caoch	caoch	caoch-A	Aqp
le	le	le-S	Sp
gandal	gandal	gandal-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Phléasc	Phléasc	pléasc-V	Vmis
Conall	Conall	Conall-N	Npmsc
amach	amach	amach-R	Rd
ag	ag	ag-S	Sp
gáire	gáire	gáir-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhuf	Bhuf	Bhuf-N	Npmsc
!	!	!-F	Fe
Bhuf	Bhuf	Bhuf-N	Npmsc
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhuf	Bhuf	Bhuf-N	Npmsc
!	!	!-F	Fe
Bhuf	Bhuf	Bhuf-N	Npmsc
!	!	!-F	Fe
’	’	’-F	Fa
.	.	.-F	Fe
Mamó	Mamó	mamó-N	Ncfsc
bhocht	bhocht	bocht-A	Aq-fsc|Aq-fsv
.	.	.-F	Fe
Is	Is	is-W	Wp-i
beag	beag	beag-A	Aqp
lá	lá	lá-N	Ncmsc
nach	nach	nach-Q	Qnr
gcailleann	gcailleann	caill-V	Vmip
sí	sí	sí-P	Pp3fsn
rud	rud	rud-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
.	.	.-F	Fe
Chaill	Chaill	caill-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
fáinne	fáinne	fáinne-N	Ncmsc
pósta	pósta	pós-A	Aqp|Av
uair	uair	uair-N	Ncfsc
amháin	amháin	amháin-A	Aqp
agus	agus	agus-C	Cc
fuair	fuair	faigh-V	Vmis
Conall	Conall	Conall-N	Npmsc
istigh	istigh	istigh-R	Rl
ina	ina	i-S	Spp-s
bhabhla	bhabhla	babhla-N	Ncmsc
anraith	anraith	anraith-N	Ncmsg|Ncmsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Uair	Uair	uair-N	Ncfsc
eile	eile	eile-D	Dd
chaill	chaill	caill-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
huaireadóir	huaireadóir	uaireadóir-N	Ncmsc
agus	agus	agus-C	Cc
fuair	fuair	faigh-V	Vmis
Muireann	Muireann	Muireann-N	Npfsc
istigh	istigh	istigh-R	Rl
ina	ina	i-S	Spp-s
cáca	cáca	cáca-N	Ncmsc
lá	lá	lá-N	Ncmsc
breithe	breithe	beir-N	Ncfsg|Nv--g
é	é	é-P	Pp3ms
.	.	.-F	Fe
Uair	Uair	uair-N	Ncfsc
eile	eile	eile-D	Dd
fós	fós	fós-R	Rg
chaill	chaill	caill-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
hata	hata	hata-N	Ncmsc
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
do	do	do-D	Dp2-s
Chonall	Chonall	Conall-N	Npmsc
agus	agus	agus-C	Cc
do	do	do-S	Sp
Mhuireann	Mhuireann	Muireann-N	Npfsc
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
a	a	a-U	U
chaitheamh	chaitheamh	caith-N	Nv
á	á	do-S	Spo-s
chuardach	chuardach	cuardaigh-N	Nv
ba	ba	is-W	Wsri
é	é	é-P	Pp3ms
Cócó	Cócó	cócó-N	Ncmsc
a	a	a-Q	Q-i|Q-r
fuair	fuair	faigh-V	Vmis
é	é	é-P	Pp3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
ó	ó	ó-S	Sp
thalamh	thalamh	talamh-N	Ncfsc
an	an	an-T	Td-s
domhain	domhain	domhan-N	Ncmsg
cár	cár	cár-N	Ncmpg|Ncmsc
fhág	fhág	fág-V	Vmis
mé	mé	mé-P	Pp1-s
mo	mo	mo-D	Dp1-s
spéaclaí	spéaclaí	spéacla-N	Ncmpc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
B	B	B-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
gur	gur	is-W	Wsdi|Wpdi
sa	sa	i-S	Spa-s
chófra	chófra	cófra-N	Ncmsc
a	a	a-Q	Q-r
bheidís	bheidís	bí-V	Vmc-3p
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
cuisneoir	cuisneoir	cuisneoir-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
a	a	a-U	Uv
Mhamó	Mhamó	mamó-N	Ncfsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Muireann	Muireann	Muireann-N	Npfsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
ní	ní	nigh-W	Wp-in|Nv|Ncmsc|Nv
haon	haon	aon-D	Dq
chófra	chófra	cófra-N	Ncmsc
é	é	é-P	Pp3ms
sin	sin	sin-P	Pd
.	.	.-F	Fe
Sin	Sin	sin-W	W
é	é	é-P	Pp3ms
an	an	an-T	Td-s
cuisneoir	cuisneoir	cuisneoir-N	Ncmsc
!	!	!-F	Fe
’	’	’-F	Fa
.	.	.-F	Fe
Mamó	Mamó	mamó-N	Ncfsc
bhocht	bhocht	bocht-A	Aq-fsc|Aq-fsv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
an-trína	an-trína	an-trín-N	Ncfpc
chéile	chéile	céile-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
ó	ó	ó-S	Sp
thalamh	thalamh	talamh-N	Ncfsc
an	an	an-T	Td-s
domhain	domhain	domhan-N	Ncmsg
cár	cár	cár-N	Ncmpg|Ncmsc
fhág	fhág	fág-V	Vmis
mé	mé	mé-P	Pp1-s
na	na	na-T	Td-p
spéaclaí	spéaclaí	spéacla-N	Ncmpc
sin	sin	sin-D	Dd
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
arís	arís	arís-R	Rg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
bí	bí	bí-V	Vmm-2s-n
trína	trína	trí-S	Spp-s
chéile	chéile	céile-N	Ncmsc
,	,	,-F	Fi
a	a	a-U	Uv
Mhamó	Mhamó	mamó-N	Ncfsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Muireann	Muireann	Muireann-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Gheobhaidh	Gheobhaidh	faigh-V	Vmif
mise	mise	mé-P	Pp1-s-e
agus	agus	agus-C	Cc
.	.	.-F	Fe
Conall	Conall	Conall-N	Npmsc
duit	duit	do-P	Pr2-s
iad	iad	iad-P	Pp3-p
.	.	.-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Déarfainn	Déarfainn	abair-V	Vmc-1s
gur	gur	is-W	Wsdi|Wpdi
sa	sa	i-S	Spa-s
chistin	chistin	cistin-N	Ncfsc
atá	atá	bí-V	Vmip---r
siad	siad	siad-P	Pp3-pn
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Conall	Conall	Conall-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
B	B	B-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
go	go	go-Q	Q
mbeidís	mbeidís	bí-V	Vmc-3p
i	i	i-S	Sp
mála	mála	mála-N	Ncmsc
Mhamó	Mhamó	mamó-N	Ncfsg
ina	ina	i-S	Spp-s
cóta	cóta	cóta-N	Ncmsc
nó	nó	nó-C	Cc
sna	sna	i-S	Spa-p
cófraí	cófraí	cófra-N	Ncmpc
’	’	’-F	Fa
Chuardaigh	Chuardaigh	cuardaigh-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
chistin	chistin	cistin-N	Ncfsc
ó	ó	ó-S	Sp
bhun	bhun	bun-N	Ncmsc
go	go	go-S	Sp
barr	barr	barr-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
mo	mo	mo-D	Dp1-s
léan	léan	léan-N	Ncmsc
!	!	!-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
tásc	tásc	tásc-N	Ncmsc
ná	ná	ná-C	Cc
tuairisc	tuairisc	tuairisc-N	Ncfsc
ar	ar	ar-S	Sp
na	na	na-T	Td-p
spéaclaí	spéaclaí	spéacla-N	Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
siad	siad	siad-P	Pp3-pn
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
de	de	de-S	Sp
bhéic	bhéic	béic-N	Ncfsc
ón	ón	ó-S	Spa-s
seomra	seomra	seomra-N	Ncmsc
suite	suite	suigh-A	Aqp|Av
tamall	tamall	tamall-N	Ncmpg|Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|Dd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
mo	mo	mo-D	Dp1-s
spéaclaí	spéaclaí	spéacla-N	Ncmpc
agam	agam	ag-P	Pr1-s
!	!	!-F	Fe
’	’	’-F	Fa
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
le	le	le-S	Sp
Mamó	Mamó	mamó-N	Ncfsc
sa	sa	i-S	Spa-s
chistin	chistin	cistin-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
féidir	féidir	féidir-N	Ns-s
liom	liom	le-P	Pr1-s
aon	aon	aon-D	Dq
rud	rud	rud-N	Ncmsc
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
mo	mo	mo-D	Dp1-s
spéaclaí	spéaclaí	spéacla-N	Ncmpc
salach	salach	salach-A	Aq--pg|Aqp
.	.	.-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
a	a	a-U	Uv
Mhamó	Mhamó	mamó-N	Ncfsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Muireann	Muireann	Muireann-N	Npfsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
ní	ní	nigh-W	Wp-in|Nv|Ncmsc|Nv
shin	shin	sin-P	Pd
iad	iad	iad-P	Pp3-p
do	do	do-S	Sp
spéaclaíse	spéaclaíse	spéacla-N	Ncmpc-e
.	.	.-F	Fe
Sin	Sin	sin-W	W
iad	iad	iad-P	Pp3-p
spéaclaí	spéaclaí	spéacla-N	Ncmpc
gréine	gréine	grian-N	Ncfsg
Chonaill	Chonaill	Conaill-N	Npm-g|Npfsg
.	.	.-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
a	a	a-D	Dp3
Thiarcais	Thiarcais	tiarcais-N	Ns-s
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
mo	mo	mo-D	Dp1-s
spéaclaí	spéaclaí	spéacla-N	Ncmpc
a	a	a-U	U
fháil	fháil	faigh-N	Nv
.	.	.-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
bí	bí	bí-V	Vmm-2s-n
trína	trína	trí-S	Spp-s
chéile	chéile	céile-N	Ncmsc
,	,	,-F	Fi
a	a	a-U	Uv
Mhamó	Mhamó	mamó-N	Ncfsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Conall	Conall	Conall-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Gheobhaidh	Gheobhaidh	faigh-V	Vmif
mise	mise	mé-P	Pp1-s-e
agus	agus	agus-C	Cc
Muireann	Muireann	Muireann-N	Npfsc
duit	duit	do-P	Pr2-s
iad	iad	iad-P	Pp3-p
.	.	.-F	Fe
'	'	'-F	Fa
Chuala	Chuala	clois-V	Vmis
siad	siad	siad-P	Pp3-pn
cnag	cnag	cnag-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
Siúd	Siúd	siúd-P	Pd
amach	amach	amach-R	Rd
le	le	le-S	Sp
Muireann	Muireann	Muireann-N	Npfsc
.	.	.-F	Fe
Cé	Cé	cé-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
ach	ach	ach-S	Sp|Cs
a	a	a-D	Dp3
cara	cara	cara-N	Ncmsc
Treasa	Treasa	Treasa-N	Npf-g|Npfsc
agus	agus	agus-C	Cc
bosca	bosca	bosca-N	Ncmsc
dearg	dearg	dearg-A	Aq-msc
ina	ina	i-S	Spp-s
baclainn	baclainn	baclainn-N	Ncfsc
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
aon	aon	aon-D	Dq
seans	seans	seans-N	Ncmsc
go	go	go-Q	Q
dtabharfá	dtabharfá	tabhair-V	Vmc-2s
aire	aire	aire-N	Ncfsc
do	do	do-S	Sp
Neaindí	Neaindí	Neaindí-N	Npmsc
dom	dom	do-P	Pr1-s
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Treasa	Treasa	Treasa-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Táimid	Táimid	bí-V	Vmip1p
ag	ag	ag-S	Sp
imeacht	imeacht	imigh-N	Nv
ar feadh	ar feadh	ar_feadh-S	Spc
an	an	an-T	Td-s
deireadh	deireadh	deireadh-N	Ncmsc
seachtaine	seachtaine	seachtain-N	Ncfsg
agus	agus	agus-C	Cc
níl	níl	bí-V	Vmip---n
cead	cead	cead-N	Ncmsc
agam	agam	ag-P	Pr1-s
Neaindí	Neaindí	Neaindí-N	Npmsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
liom	liom	le-P	Pr1-s
.	.	.-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
ní	ní	ní-Q	Qn
fhéadfainn	fhéadfainn	féad-V	Vmc-1s-n
,	,	,-F	Fi
a	a	a-U	Uv
Threasa	Threasa	Treasa-N	Npf-v
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Muireann	Muireann	Muireann-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Mharódh	Mharódh	maraigh-V	Vmc
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
mé	mé	mé-P	Pp1-s
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
sí	sí	sí-P	Pp3fsn
scanraithe	scanraithe	scanraigh-A	Av
roimh	roimh	roimh-S	Sp
nathracha	nathracha	nathair-N	Ncfpc
.	.	.-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
tá	tá	bí-V	Vmip
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agat	agat	ag-P	Pr2-s
nach	nach	nach-Q	Qnr
bhfuil	bhfuil	bí-V	Vmip---n
aon	aon	aon-D	Dq
dochar	dochar	dochar-N	Ncmsc
inti	inti	i-P	Pr3fs
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Treasa	Treasa	Treasa-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
beidh	beidh	bí-V	Vmif
mé	mé	mé-P	Pp1-s
ar ais	ar ais	ar_ais-R	Rd
Dé	Dé	Dé-N	Ns-s
Luain	Luain	Luan-N	Ncmsg
.	.	.-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
fhéadfainn	fhéadfainn	féad-V	Vmc-1s-n
,	,	,-F	Fi
a	a	a-U	Uv
Threasa	Threasa	Treasa-N	Npf-v
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Muireann	Muireann	Muireann-N	Npfsc
arís	arís	arís-R	Rg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bheadh	Bheadh	bí-V	Vmc
eagla	eagla	eagla-N	Ncfsc
an	an	an-T	Td-s
domhain	domhain	domhan-N	Ncmsg
ar	ar	ar-S	Sp
Mhamaí	Mhamaí	mamaí-N	Ncmpc|Ncfsc
roimh	roimh	roimh-S	Sp
Neaindí	Neaindí	Neaindí-N	Npmsc
.	.	.-F	Fe
Fadó	Fadó	fadó-R	Rg
,	,	,-F	Fi
fadó	fadó	fadó-R	Rg
,	,	,-F	Fi
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Mamaí	Mamaí	mamaí-N	Ncfsc
óg	óg	óg-A	Aq-fsc
,	,	,-F	Fi
thug	thug	tabhair-V	Vmis
Daideo	Daideo	daideo-N	Ncmsc
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
zú	zú	zú-N	Ncmsc
í	í	í-P	Pp3fs
sa	sa	i-S	Spa-s
bhugaí	bhugaí	bugaí-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
istigh	istigh	istigh-R	Rl
i	i	i-S	Sp
dTeach	dTeach	teach-N	Ncmsc
na	na	na-T	Tdfsg
Nathrach	Nathrach	nathair-N	Ncfsg
nuair	nuair	nuair-C	Cs
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
éalaigh	éalaigh	éalaigh-V	Vmm-2s
nathair	nathair	nathair-N	Ncfsc
amach	amach	amach-R	Rd
as	as	as-P	Pr3ms
a	a	a-D	Dp3
cás	cás	cás-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
ar	ar	ar-Q	Qq-s
imigh	imigh	imigh-V	Vmis
an	an	an-T	Td-s
nathair	nathair	nathair-N	Ncfsc
léi	léi	le-P	Pr3fs
amach	amach	amach-R	Rd
as	as	as-S	Sp
an	an	an-T	Td-s
zú	zú	zú-N	Ncmsc
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
Treasa	Treasa	Treasa-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níor	Níor	níor-Q	Qn-s
imigh	imigh	imigh-V	Vmis---n
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
chuaigh	chuaigh	téigh-V	Vmis
sí	sí	sí-P	Pp3fsn
i	i	i-S	Sp
bhfolach	bhfolach	folach-N	Ncmsc
sa	sa	i-S	Spa-s
bhugaí	bhugaí	bugaí-N	Ncmsc
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
bheag	bheag	beag-A	Aqp
nár	nár	nár-Q	Qnrs
thit	thit	tit-V	Vmis---n
an	an	an-T	Td-s
t-anam	t-anam	anam-N	Ncmsc
as	as	as-S	Sp
Mamaí	Mamaí	mamaí-N	Ncmpc|Ncfsc
.	.	.-F	Fe
Ná	Ná	ná-Q	Qnm
labhair	labhair	labhair-V	Vmis---n
léi	léi	le-P	Pr3fs
ar	ar	ar-S	Sp
nathracha	nathracha	nathair-N	Ncfpc
ó	ó	ó-S	Sp
shin	shin	sin-P	Pd
!	!	!-F	Fe
’	’	’-F	Fa
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
a	a	a-U	Uv
Mhuireann	Mhuireann	Muireann-N	Npf-v
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Treasa	Treasa	Treasa-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
D	D	D-X	Xl
’	’	’-F	Fa
fhéadfá	fhéadfá	féad-V	Vmc-2s
an	an	an-T	Td-s
bosca	bosca	bosca-N	Ncmsc
a	a	a-U	U
chur	chur	cuir-N	Nv
i	i	i-S	Sp
bhfolach	bhfolach	folach-N	Ncmsc
faoi	faoi	faoi-P	Pr3ms|Sp
do	do	do-S	Sp
leaba	leaba	leaba-N	Ncfsc
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
bheadh	bheadh	bí-V	Vmc----n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
ag	ag	ag-S	Sp
éinne	éinne	duine-N	Ncmsc
é	é	é-P	Pp3ms
a	a	a-U	U
bheith	bheith	bí-N	Nv
ann	ann	ann-R	Rl
.	.	.-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
mharódh	mharódh	maraigh-V	Vmc
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
mé	mé	mé-P	Pp1-s
dá	dá	dá-C	Cs
n-éalódh	n-éalódh	éalaigh-V	Vmc
sí	sí	sí-P	Pp3fsn
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Muireann	Muireann	Muireann-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
éalóidh	éalóidh	éalaigh-V	Vmif---n
sí	sí	sí-P	Pp3fsn
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Treasa	Treasa	Treasa-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
chorróidh	chorróidh	corraigh-V	Vmif---n
sí	sí	sí-P	Pp3fsn
as	as	as-S	Sp
an	an	an-T	Td-s
mbosca	mbosca	bosca-N	Ncmsc
an	an	an-T	Td-s
deireadh	deireadh	deireadh-N	Ncmsc
seachtaine	seachtaine	seachtain-N	Ncfsg
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Maith	Maith	Maith-N	Npmsc
go leor	go leor	go_leor-A	Aq
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Muireann	Muireann	Muireann-N	Npfsc
.	.	.-F	Fe
Shín	Shín	Sín-N	Npfsc
Treasa	Treasa	Treasa-N	Npf-g|Npfsc
an	an	an-T	Td-s
bosca	bosca	bosca-N	Ncmsc
dearg	dearg	dearg-A	Aq-msc
go dtí	go dtí	go_dtí-S	Spc
Marina	Marina	marina-X	Xfen
.	.	.-F	Fe
‘	‘	‘-X	Xx
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
míle	míle	míle-M	Mc
maith	maith	maith-N	Ncfsc
agat	agat	ag-P	Pr2-s
.	.	.-F	Fe
Is	Is	agus-W	Wp-i|Cc
maith	maith	maith-V	Vmm-2s|Aqp|Ncfsc
an	an	an-T	Td-s
cara	cara	cara-N	Ncmsc
tú	tú	tú-P	Pp2-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Feicfidh	Feicfidh	feic-V	Vmif
mé	mé	mé-P	Pp1-s
Dé	Dé	Dé-N	Ns-s
Luain	Luain	Luan-N	Ncmsg
tú	tú	tú-P	Pp2-s
,	,	,-F	Fi
le	le	le-S	Sp
cúnamh	cúnamh	cúnamh-N	Ncmsc
Dé	Dé	dia-N	Ncmsg
.	.	.-F	Fe
'	'	'-F	Fa
Suas	Suas	suas-R	Rd
staighre	staighre	staighre-N	Ncmsc
go	go	go-U	Ua
ciúin	ciúin	ciúin-A	Aqp
le	le	le-S	Sp
Muireann	Muireann	Muireann-N	Npfsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
bosca	bosca	bosca-N	Ncmsc
dearg	dearg	dearg-A	Aq-msc
ina	ina	i-S	Spp-s
baclainn	baclainn	baclainn-N	Ncfsc
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
léi	léi	le-P	Pr3fs
ina	ina	i-S	Spp-p|Spp-s
seomra	seomra	seomra-N	Ncmsc
codlata	codlata	codail-A	Av
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
bosca	bosca	bosca-N	Ncmsc
i	i	i-S	Sp
bhfolach	bhfolach	folach-N	Ncmsc
faoin	faoin	faoi-S	Spa-s
leaba	leaba	leaba-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
tú	tú	tú-P	Pp2-s
ceart	ceart	ceart-A	Aqp
go leor	go leor	go_leor-A	Aq
ansin	ansin	ansin-R	Rt|Rl
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Muireann	Muireann	Muireann-N	Npfsc
le	le	le-S	Sp
Neaindí	Neaindí	Neaindí-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tabharfaidh	Tabharfaidh	tabhair-V	Vmif
mise	mise	mé-P	Pp1-s-e
aire	aire	aire-N	Ncfsc
mhaith	mhaith	maith-A	Aq-fsc
duit	duit	do-P	Pr2-s
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
an	an	an-T	Td-s
deireadh	deireadh	deireadh-N	Ncmsc
seachtaine	seachtaine	seachtain-N	Ncfsg
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
ag	ag	ag-S	Sp
imeacht	imeacht	imigh-N	Nv
.	.	.-F	Fe
'	'	'-F	Fa
Ansin	Ansin	ansin-R	Rt|Rl
dhún	dhún	dún-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
bosca	bosca	bosca-N	Ncmsc
go	go	go-U	Ua
cúramach	cúramach	cúramach-A	Aqp
agus	agus	agus-C	Cc
síos	síos	síos-R	Rd
an	an	an-T	Td-s
staighre	staighre	staighre-N	Ncmsg
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Tamall	Tamall	tamall-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|Dd
chuaigh	chuaigh	téigh-V	Vmis
Conall	Conall	Conall-N	Npmsc
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
seomra	seomra	seomra-N	Ncmsc
codlata	codlata	codail-A	Av
Mhuireann	Mhuireann	Muireann-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
spéaclaí	spéaclaí	spéacla-N	Ncmpc
Mhamó	Mhamó	mamó-N	Ncfsg
a	a	a-U	U
fháil	fháil	faigh-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
sí	sí	sí-P	Pp3fsn
an-trína	an-trína	an-trín-N	Ncfpc
chéile	chéile	céile-N	Ncmsg
.	.	.-F	Fe
'	'	'-F	Fa
Chonaic	Chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
bosca	bosca	bosca-N	Ncmsc
dearg	dearg	dearg-A	Aq-msc
faoin	faoin	faoi-S	Spa-s
leaba	leaba	leaba-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
B	B	B-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
gur	gur	is-W	Wsdi|Wpdi
istigh	istigh	istigh-R	Rl
anseo	anseo	anseo-R	Rl
a	a	a-Q	Q-r
bheidís	bheidís	bí-V	Vmc-3p
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
bosca	bosca	bosca-N	Ncmsc
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
bheag	bheag	beag-A	Aqp
nár	nár	nár-Q	Qnrs
thit	thit	tit-V	Vmis---n
an	an	an-T	Td-s
t-anam	t-anam	anam-N	Ncmsc
as	as	as-P	Pr3ms
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
nathair	nathair	nathair-N	Ncfsc
nimhe	nimhe	nimh-N	Ncfsg
!	!	!-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
a	a	a-D	Dp3
Thiarcais	Thiarcais	tiarcais-N	Ns-s
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
de	de	de-S	Sp
bhéic	bhéic	béic-N	Ncfsc
agus	agus	agus-C	Cc
amach	amach	amach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
leis	leis	le-P	Pr3ms
ar nós	ar nós	ar_nós-S	Spc
na	na	na-T	Tdfsg
gaoithe	gaoithe	gaoth-N	Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
nathair	nathair	nathair-N	Ncfsc
nimhe	nimhe	nimh-N	Ncfsg
i	i	i-S	Sp
seomra	seomra	seomra-N	Ncmsc
Mhuireann	Mhuireann	Muireann-N	Npfsc
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Conall	Conall	Conall-N	Npmsc
de	de	de-S	Sp
bhéic	bhéic	béic-N	Ncfsc
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
rith	rith	rith-N	Nv
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
chistin	chistin	cistin-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
nathair	nathair	nathair-N	Ncfsc
nimhe	nimhe	nimh-N	Ncfsg
i	i	i-S	Sp
seomra	seomra	seomra-N	Ncmsc
Mhuireann	Mhuireann	Muireann-N	Npfsc
!	!	!-F	Fe
’	’	’-F	Fa
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
chreid	chreid	creid-V	Vmis---n
Mamó	Mamó	mamó-N	Ncfsc
focal	focal	focal-N	Ncmsc
uaidh	uaidh	ó-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Éirigh	Éirigh	éirigh-V	Vmm-2s
as	as	as-P	Pr3ms
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
,	,	,-F	Fi
‘	‘	‘-X	Xx
agus	agus	agus-C	Cc
ná	ná	nach-Q	Qnr
bí	bí	bí-V	Vmm-2s-n
ag	ag	ag-S	Sp
cumadh	cumadh	cum-N	Nv
.	.	.-F	Fe
Táim	Táim	bí-V	Vmip1s
gan	gan	gan-S	Sp
aon	aon	aon-D	Dq
spéaclaí	spéaclaí	spéacla-N	Ncmpc
fós	fós	fós-R	Rg
agus	agus	agus-C	Cc
gheall	gheall	geall-V	Vmis
tusa	tusa	tú-P	Pp2-s-e
dom	dom	do-P	Pr1-s
go	go	go-Q	Q
bhfaighfeá	bhfaighfeá	faigh-V	Vmc-2s-d
dom	dom	do-P	Pr1-s
iad	iad	iad-P	Pp3-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Éirigh	Éirigh	éirigh-V	Vmm-2s
as	as	as-P	Pr3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
arís	arís	arís-R	Rg
,	,	,-F	Fi
‘	‘	‘-X	Xx
agus	agus	agus-C	Cc
cuardaigh	cuardaigh	cuardaigh-V	Vmm-2s
mo	mo	mo-D	Dp1-s
spéaclaí	spéaclaí	spéacla-N	Ncmpc
dom	dom	do-P	Pr1-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
ní	ní	is-W	Wp-in
ag	ag	ag-S	Sp
cumadh	cumadh	cum-N	Nv
atáim	atáim	bí-V	Vmip1s-r
,	,	,-F	Fi
a	a	a-U	Uv
Mhamó	Mhamó	mamó-N	Ncfsv
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Conall	Conall	Conall-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Táim	Táim	bí-V	Vmip1s
á	á	do-S	Spo-s
rá	rá	abair-N	Nv
leat	leat	le-P	Pr2-s
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
nathair	nathair	nathair-N	Ncfsc
nimhe	nimhe	nimh-N	Ncfsg
i	i	i-S	Sp
mbosca	mbosca	bosca-N	Ncmsc
dearg	dearg	dearg-A	Aq-msc
faoi	faoi	faoi-S	Sp
leaba	leaba	leaba-N	Ncfsc
Mhuireann	Mhuireann	Muireann-N	Npfsc
.	.	.-F	Fe
Ceann	Ceann	ceann-N	Ncmsc
mór	mór	mór-A	Aq-msc
millteanach	millteanach	millteanach-A	Aq-msc
agus	agus	agus-C	Cc
fiacla	fiacla	fiacail-N	Ncfpc
géara	géara	géar-A	Aq--pc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Dhera	Dhera	Dhera-N	Npmsc
,	,	,-F	Fi
ní	ní	ní-Q	Qn
stopann	stopann	stop-V	Vmip---n
tú	tú	tú-P	Pp2-s
ach	ach	ach-S	Sp|Cs
ag	ag	ag-S	Sp
cumadh	cumadh	cum-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
ní	ní	is-W	Wp-in
ag	ag	ag-S	Sp
cumadh	cumadh	cum-N	Nv
atá	atá	bí-V	Vmip---r
sé	sé	sé-P	Pp3msn
,	,	,-F	Fi
a	a	a-U	Uv
Mhamó	Mhamó	mamó-N	Ncfsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Muireann	Muireann	Muireann-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
D	D	D-X	Xl
’	’	’-F	Fa
iarr	iarr	iarr-V	Vmm-2s
Treasa	Treasa	Treasa-N	Npfsc
orm	orm	ar-P	Pr1-s
aire	aire	aire-N	Ncmsc|Ncfsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
dá	dá	do-S	Spp-s
peata	peata	peata-N	Ncmsc
,	,	,-F	Fi
Neaindí	Neaindí	Neaindí-N	Npmsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
sí	sí	sí-P	Pp3fsn
istigh	istigh	istigh-R	Rl
faoi	faoi	faoi-P	Pr3ms
mo	mo	mo-D	Dp1-s
leaba	leaba	leaba-N	Ncfsc
i	i	i-S	Sp
mbosca	mbosca	bosca-N	Ncmsc
dearg	dearg	dearg-A	Aq-msc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Anois	Anois	anois-R	Rt
,	,	,-F	Fi
a	a	a-U	Uv
Mhuireann	Mhuireann	Muireann-N	Npf-v
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
tá	tá	bí-V	Vmip
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agat	agat	ag-P	Pr2-s
go	go	go-U	Ua
maith	maith	maith-A	Aqp
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
do	do	do-S	Sp
Mhamaí	Mhamaí	mama-N	Ncfsc|Ncmpc
scanraithe	scanraithe	scanraigh-A	Av
roimh	roimh	roimh-S	Sp
nathracha	nathracha	nathair-N	Ncfpc
!	!	!-F	Fe
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
an	an	an-Q	Qq
bhfuair	bhfuair	faigh-V	Vmis
tú	tú	tú-P	Pp2-s
cead	cead	cead-N	Ncmsc
uaithi	uaithi	ó-P	Pr3fs
?	?	?-F	Fq
’	’	’-F	Fa
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
bhfuair	bhfuair	faigh-V	Vmis
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Muireann	Muireann	Muireann-N	Npfsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
ach	ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sí	sí	sí-P	Pp3fsn
anseo	anseo	anseo-R	Rl
san	san	i-S	Spa-s
am	am	am-N	Ncmsc
agus	agus	agus-C	Cc
dúirt	dúirt	abair-V	Vmis
Treasa	Treasa	Treasa-N	Npfsc
nach	nach	nach-Q	Qnr
gcorródh	gcorródh	corraigh-V	Vmc
Neaindí	Neaindí	Neaindí-N	Npmsc
as	as	as-S	Sp
an	an	an-T	Td-s
mbosca	mbosca	bosca-N	Ncmsc
an	an	an-T	Td-s
deireadh	deireadh	deireadh-N	Ncmsc
seachtaine	seachtaine	seachtain-N	Ncfsg
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Daideo	Daideo	daideo-N	Ncmsc
ag	ag	ag-S	Sp
obair	obair	obair-N	Nv-----n
sa	sa	i-S	Spa-s
ghairdín	ghairdín	gairdín-N	Ncmsc
.	.	.-F	Fe
Ghlaoigh	Ghlaoigh	glaoigh-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Gabh	Gabh	gabh-V	Vmm-2s
i	i	i-S	Sp
leith	leith	leith-N	Ncfsc
anseo	anseo	anseo-R	Rl
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Fan	Fan	fan-V	Vmm-2s
go	go	go-Q	Q
gcloisfidh	gcloisfidh	clois-V	Vmif
tú	tú	tú-P	Pp2-s
é	é	é-P	Pp3ms
seo	seo	seo-P	Pd
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
le	le	le-S	Sp
Daideo	Daideo	daideo-N	Ncmsc
sa	sa	i-S	Spa-s
chistin	chistin	cistin-N	Ncfsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
inis	inis	inis-V	Vmm-2s|Vmis
Mamó	Mamó	mamó-N	Ncfsc
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nathair	Nathair	nathair-N	Ncfsc
nimhe	nimhe	nimh-N	Ncfsg
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daideo	Daideo	daideo-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
nach	nach	is-W	Wpsin|Wpdin
bhfuil	bhfuil	fuil-N	Ncfsc
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agat	agat	ag-P	Pr2-s
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
do	do	do-S	Sp
Mhamaí	Mhamaí	mama-N	Ncfsc|Ncmpc
scanraithe	scanraithe	scanraigh-A	Av
roimh	roimh	roimh-S	Sp
nathracha	nathracha	nathair-N	Ncfpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Muireann	Muireann	Muireann-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
níl	níl	bí-V	Vmip---n
inti	inti	i-P	Pr3fs
ach	ach	ach-S	Sp
peata	peata	peata-N	Ncmsc
.	.	.-F	Fe
Níl	Níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
dochar	dochar	dochar-N	Ncmsc
inti	inti	i-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
tabhair	tabhair	tabhair-V	Vmm-2s-n
aon	aon	aon-D	Dq
aird	aird	aird-N	Ncfsc
ar	ar	ar-S	Sp
Mhuireann	Mhuireann	Muireann-N	Npfsc
,	,	,-F	Fi
a	a	a-U	Uv
Dhaideo	Dhaideo	daideo-N	Ncmsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Conall	Conall	Conall-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Chonaic	Chonaic	feic-V	Vmis
mise	mise	mé-P	Pp1-s-e
an	an	an-T	Td-s
nathair	nathair	nathair-N	Ncfsc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
ollphéist	ollphéist	ollphéist-N	Ncfsc
atá	atá	bí-V	Vmip---r
inti	inti	i-P	Pr3fs
!	!	!-F	Fe
.	.	.-F	Fe
Déarfainn	Déarfainn	abair-V	Vmc-1s
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
sí	sí	sí-P	Pp3fsn
cúpla	cúpla	cúpla-D	Dq
méadar	méadar	méadar-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
.	.	.-F	Fe
Dá	Dá	dá-C	Cs
bhfeicfeá	bhfeicfeá	feic-V	Vmc-2s
chomh	chomh	chomh-R	Ri
fíochmhar	fíochmhar	fíochmhar-A	Aqp
is	is	agus-C	Cc
atá	atá	bí-V	Vmip---r
sí	sí	sí-P	Pp3fsn
!	!	!-F	Fe
Agus	Agus	agus-C	Cc
na	na	na-T	Td-p
fiacla	fiacla	fiacail-N	Ncfpc
móra	móra	mór-A	Aq--pc
atá	atá	bí-V	Vmip---r
uirthi	uirthi	ar-P	Pr3fs
!	!	!-F	Fe
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
chreidfeá	chreidfeá	creid-V	Vmc-2s-n
é	é	é-P	Pp3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
nathair	nathair	nathair-N	Ncfsc
seo	seo	seo-D	Dd
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daideo	Daideo	daideo-N	Ncmsc
.	.	.-F	Fe
Suas	Suas	suas-R	Rd
staighre	staighre	staighre-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
gceathrar	gceathrar	ceathrar-N	Ncmsc
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agat	agat	ag-P	Pr2-s
go	go	go-Q	Q
gcaithfidh	gcaithfidh	caith-V	Vmif
tú	tú	tú-P	Pp2-s
an	an	an-T	Td-s
nathair	nathair	nathair-N	Ncfsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
ar ais	ar ais	ar_ais-R	Rd
do	do	do-S	Sp
Threasa	Threasa	Treasa-N	Npfsc
láithreach	láithreach	láithreach-A	Aq-fsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
sula	sula	sula-C	Cs
dtiocfaidh	dtiocfaidh	tar-V	Vmif
do	do	do-S	Sp
mháthair	mháthair	máthair-N	Ncfsc
abhaile	abhaile	abhaile-R	Rd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-S	Sp|Cs
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Muireann	Muireann	Muireann-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
bac	bac	bac-V	Vmm-2s-n
le	le	le-S	Sp
do	do	do-D	Dp2-s
ach	ach	ach-C	Cs
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
leo	leo	le-P	Pr3-p
i	i	i-S	Sp
seomra	seomra	seomra-N	Ncmsc
Mhuireann	Mhuireann	Muireann-N	Npfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
bosca	bosca	bosca-N	Ncmsc
dearg	dearg	dearg-A	Aq-msc
faoin	faoin	faoi-S	Spa-s
leaba	leaba	leaba-N	Ncfsc
ceart	ceart	ceart-A	Aqp
go leor	go leor	go_leor-A	Aq
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
!	!	!-F	Fe
Ach	Ach	ach-S	Sp
tásc	tásc	tásc-N	Ncmsc
ná	ná	ná-C	Cs|Cc
tuairisc	tuairisc	tuairisc-N	Ncfsc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ar	ar	ar-S	Sp
an	an	an-T	Td-s
nathair	nathair	nathair-N	Ncfsc
nimhe	nimhe	nimh-N	Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
sí	sí	sí-P	Pp3fsn
imithe	imithe	imigh-A	Av
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
ceathrú	ceathrú	ceathrú-A	Aqp
tar éis	tar éis	tar_éis-S	Spc
a	a	a-U	Um
dó	dó	dó-M	Mc
agus	agus	agus-C	Cc
beidh	beidh	bí-V	Vmif
do	do	do-S	Sp
Mhamaí	Mhamaí	mama-N	Ncfsc|Ncmpc
anseo	anseo	anseo-R	Rl
sula	sula	sula-C	Cs
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Maróidh	Maróidh	maraigh-V	Vmif
sí	sí	sí-P	Pp3fsn
mé	mé	mé-P	Pp1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Muireann	Muireann	Muireann-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Maróidh	Maróidh	maraigh-V	Vmif
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Conall	Conall	Conall-N	Npmsc
.	.	.-F	Fe
Phléasc	Phléasc	pléasc-V	Vmis
Muireann	Muireann	Muireann-N	Npfsc
amach	amach	amach-R	Rd
ag	ag	ag-S	Sp
caoineadh	caoineadh	caoin-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daideo	Daideo	daideo-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfimid	Caithfimid	caith-V	Vmif1p
tosú	tosú	tosú-N	Ncmsc
ag	ag	ag-S	Sp
cuardach	cuardach	cuardaigh-N	Nv
.	.	.-F	Fe
Múinteoir	Múinteoir	múinteoir-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
i	i	i-S	Sp
nDaideo	nDaideo	daideo-N	Ncmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
níos	níos	níos-U	Uc
óige	óige	óg-A	Aqc
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-U	Ua
maith	maith	maith-A	Aqp
ag	ag	ag-S	Sp
tabhairt	tabhairt	tabhair-N	Nv
orduithe	orduithe	ordú-N	Ncmpg
do	do	do-S	Sp
dhaoine	dhaoine	duine-N	Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Anois	Anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
le	le	le-S	Sp
Conall	Conall	Conall-N	Npmsc
agus	agus	agus-C	Cc
le	le	le-S	Sp
Mamó	Mamó	mamó-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Suas	Suas	suas-R	Rd
staighre	staighre	staighre-N	Ncmsc
libh	libh	le-P	Pr2-p
agus	agus	agus-C	Cc
cuardaígí	cuardaígí	cuardaigh-V	Vmm-2p
na	na	na-T	Td-p
seomraí	seomraí	seomra-N	Ncmpc
codlata	codlata	codail-A	Av
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Maith	Maith	Maith-N	Npmsc
go leor	go leor	go_leor-A	Aq
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
acu	acu	ag-P	Pr3-p
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmis
siad	siad	siad-P	Pp3-pn
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
,	,	,-F	Fi
a	a	a-U	Uv
Mhuireann	Mhuireann	Muireann-N	Npf-v
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
,	,	,-F	Fi
‘	‘	‘-X	Xx
stop	stop	stop-V	Vmis
ag	ag	ag-S	Sp
gol	gol	goil-N	Nv
agus	agus	agus-C	Cc
téigh	téigh	téigh-V	Vmm-2s
amach	amach	amach-R	Rd
sa	sa	i-S	Spa-s
ghairdín	ghairdín	gairdín-N	Ncmsc
.	.	.-F	Fe
B	B	B-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
gur	gur	is-W	Wsdi|Wpdi
amuigh	amuigh	amuigh-R	Rl
ansin	ansin	ansin-R	Rt|Rl
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
Rug	Rug	beir-V	Vmis
Daideo	Daideo	daideo-N	Ncmsc
ar	ar	ar-S	Sp
chamán	chamán	camán-N	Ncmsc
Mhuireann	Mhuireann	Muireann-N	Npfsc
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
clogad	clogad	clogad-N	Ncmsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
cheann	cheann	ceann-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
bhfaighidh	bhfaighidh	faigh-V	Vmif---d
aon	aon	aon-D	Dq
nathair	nathair	nathair-N	Ncfsc
nimhe	nimhe	nimh-N	Ncfsg
an	an	an-T	Td-s
ceann	ceann	ceann-N	Ncmsc
is	is	is-U	U
fearr	fearr	maith-A	Aqc
ormsa	ormsa	ar-P	Pr1-s-e
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
cuardach	cuardach	cuardaigh-N	Nv
.	.	.-F	Fe
Chuardaigh	Chuardaigh	cuardaigh-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
chistin	chistin	cistin-N	Ncfsc
ar	ar	ar-S	Sp
dtús	dtús	tús-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tar	Tar	thar-S	Sp
amach	amach	amach-R	Rd
,	,	,-F	Fi
a	a	a-D	Dp3
bhligeaird	bhligeaird	bhligeaird-N	Ncfsc
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
‘	‘	‘-X	Xx
nó	nó	nó-C	Cc
is	is	agus-C	Cc
duitse	duitse	do-P	Pr2-s-e
is	is	is-U	U
measa	measa	olc-A	Aqc
!	!	!-F	Fe
’	’	’-F	Fa
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
mhála	mhála	mála-N	Ncmsc
a	a	a-Q	Q-r
chaill	chaill	caill-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
dhá	dhá	dó-M	Mc
bhliain	bhliain	bliain-N	Ncfsc
roimhe	roimhe	roimh-P	Pr3ms
sin	sin	sin-P	Pd|W
ach	ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
tásc	tásc	tásc-N	Ncmsc
ná	ná	ná-C	Cc
tuairisc	tuairisc	tuairisc-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
nathair	nathair	nathair-N	Ncfsc
nimhe	nimhe	nimh-N	Ncfsg
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
Conall	Conall	Conall-N	Npmsc
an	an	an-T	Td-s
clogad	clogad	clogad-N	Ncmsc
ar	ar	ar-S	Sp
Dhaideo	Dhaideo	daideo-N	Ncmsc
bhuail	bhuail	buail-V	Vmis
smaoineamh	smaoineamh	smaoineamh-N	Ncmsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
air	air	ar-P	Pr3ms
a	a	a-D	Dp3
chulaith	chulaith	culaith-N	Ncfsc
ridire	ridire	ridire-N	Ncmsg|Ncmsc|Ncmsg
agus	agus	agus-C	Cc
rug	rug	beir-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
chlaíomh	chlaíomh	claíomh-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
bhfaighidh	bhfaighidh	faigh-V	Vmif---d
aon	aon	aon-D	Dq
nathair	nathair	nathair-N	Ncfsc
nimhe	nimhe	nimh-N	Ncfsg
an	an	an-T	Td-s
ceann	ceann	ceann-N	Ncmsc
is	is	is-U	U
fearr	fearr	maith-A	Aqc
ormsa	ormsa	ar-P	Pr1-s-e
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
aithrise	aithrise	aithris-N	Ncfsg
ar	ar	ar-S	Sp
Dhaideo	Dhaideo	daideo-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tar	Tar	thar-S	Sp
amach	amach	amach-R	Rd
,	,	,-F	Fi
a	a	a-D	Dp3
bhligeaird	bhligeaird	bhligeaird-N	Ncfsc
,	,	,-F	Fi
nó	nó	nó-C	Cc
is	is	is-W	Wpri
duitse	duitse	do-P	Pr2-s-e
is	is	is-U	U
measa	measa	olc-A	Aqc
!	!	!-F	Fe
’	’	’-F	Fa
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
cuardach	cuardach	cuardaigh-N	Nv
.	.	.-F	Fe
Chuardaigh	Chuardaigh	cuardaigh-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
nathair	nathair	nathair-N	Ncfsc
nimhe	nimhe	nimh-N	Ncfsg
…	…	…-F	Fi
thíos	thíos	thíos-R	Rd
faoi	faoi	faoi-S	Sp
na	na	na-T	Td-p
leapacha	leapacha	leaba-N	Ncfpc
…	…	…-F	Fi
…	…	…-F	Fi
istigh	istigh	istigh-R	Rl
sna	sna	i-S	Spa-p
tarraiceáin	tarraiceáin	tarraiceán-N	Ncmpc
…	…	…-F	Fi
…	…	…-F	Fi
os cionn	os cionn	os_cionn-S	Spc
na	na	na-T	Td-p
vardrús	vardrús	vardrús-N	Ncmpg
…	…	…-F	Fi
…	…	…-F	Fi
agus	agus	agus-C	Cc
istigh	istigh	istigh-R	Rl
sa	sa	i-S	Spa-s
leithreas	leithreas	leithreas-N	Ncmsc
fiú	fiú	fiú-N	Ncmsg|Ncmsc|Rg|Ns-s
!	!	!-F	Fe
.	.	.-F	Fe
Ach	Ach	ach-S	Sp
tásc	tásc	tásc-N	Ncmsc
ná	ná	ná-C	Cs|Cc
tuairisc	tuairisc	tuairisc-N	Ncfsc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ar	ar	ar-S	Sp
an	an	an-T	Td-s
nathair	nathair	nathair-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
ag	ag	ag-S	Sp
cuardach	cuardach	cuardaigh-N	Nv
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
léi	léi	le-P	Pr3fs
i	i	i-S	Sp
seomra	seomra	seomra-N	Ncmsc
Chonaill	Chonaill	Conaill-N	Npm-g|Npfsg
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
vardrús	vardrús	vardrús-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
sí	sí	sí-P	Pp3fsn
sa	sa	i-S	Spa-s
vardrús	vardrús	vardrús-N	Ncmsc
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
oiread	oiread	oiread-N	Ns-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmis
sí	sí	sí-P	Pp3fsn
léi	léi	le-P	Pr3fs
síos	síos	síos-R	Rd
staighre	staighre	staighre-N	Ncmsc
chun	chun	chun-S	Sp
cupán	cupán	cupán-N	Ncmpg
tae	tae	tae-N	Ncmsg|Ncmsc
a	a	a-U	U
fháil	fháil	faigh-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Muireann	Muireann	Muireann-N	Npfsc
ag	ag	ag-S	Sp
cuardach	cuardach	cuardaigh-N	Nv
amuigh	amuigh	amuigh-R	Rl
sa	sa	i-S	Spa-s
ghairdín	ghairdín	gairdín-N	Ncmsc
.	.	.-F	Fe
Chuardaigh	Chuardaigh	cuardaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
gairdín	gairdín	gairdín-N	Ncmsc
ó	ó	ó-S	Sp
bhun	bhun	bun-N	Ncmsc
go	go	go-S	Sp
barr	barr	barr-N	Ncmsc
ach	ach	ach-S	Sp
tásc	tásc	tásc-N	Ncmsc
ná	ná	ná-C	Cs|Cc
tuairisc	tuairisc	tuairisc-N	Ncfsc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ar	ar	ar-S	Sp
an	an	an-T	Td-s
nathair	nathair	nathair-N	Ncfsc
nimhe	nimhe	nimh-N	Ncfsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Muireann	Muireann	Muireann-N	Npfsc
bhocht	bhocht	bocht-A	Aq-fsc
an-trína	an-trína	an-trín-N	Ncfpc
chéile	chéile	céile-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
súil	súil	súil-N	Ncfsc
agam	agam	ag-P	Pr1-s
go	go	go-Q	Q
mbeidh	mbeidh	bí-V	Vmif
Neaindí	Neaindí	Neaindí-N	Npmsc
faighte	faighte	faigh-A	Av
againn	againn	ag-P	Pr1-p
sula	sula	sula-C	Cs
dtiocfaidh	dtiocfaidh	tar-V	Vmif
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
abhaile	abhaile	abhaile-R	Rd
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
,	,	,-F	Fi
‘	‘	‘-X	Xx
nó	nó	nó-C	Cc
maróidh	maróidh	maraigh-V	Vmif
sí	sí	sí-P	Pp3fsn
mé	mé	mé-P	Pp1-s
.	.	.-F	Fe
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
Cócó	Cócó	cócó-N	Ncmsc
an	an	an-T	Td-s
madra	madra	madra-N	Ncmsg
amuigh	amuigh	amuigh-R	Rl
sa	sa	i-S	Spa-s
halla	halla	halla-N	Ncmsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
nathair	nathair	nathair-N	Ncfsc
nimhe	nimhe	nimh-N	Ncfsg
ar	ar	ar-S	Sp
an	an	an-T	Td-s
staighre	staighre	staighre-N	Ncmsc
thosaigh	thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
tafann	tafann	tafainn-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Éirigh	Éirigh	éirigh-V	Vmm-2s
as	as	as-P	Pr3ms
,	,	,-F	Fi
a	a	a-U	Uv
Chócó	Chócó	cócó-N	Ncmsv
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daideo	Daideo	daideo-N	Ncmsc
de	de	de-S	Sp
bhéic	bhéic	béic-N	Ncfsc
ón	ón	ó-S	Spa-s
gcistin	gcistin	cistin-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tinneas	tinneas	tinneas-N	Ncmsc
cinn	cinn	ceann-N	Ncmsg|Ncmpc
orm	orm	ar-P	Pr1-s
ó	ó	ó-S	Sp
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
éisteacht	éisteacht	éist-N	Nv
leat	leat	le-P	Pr2-s
.	.	.-F	Fe
'	'	'-F	Fa
Ach	Ach	ach-C	Cs
ní	ní	is-W	Wp-in
stopfadh	stopfadh	stop-V	Vmc
Cócó	Cócó	cócó-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Éirigh	Éirigh	éirigh-V	Vmm-2s
as	as	as-P	Pr3ms
a	a	a-Q	Q-r
deirim	deirim	abair-V	Vmip1s
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daideo	Daideo	daideo-N	Ncmsc
arís	arís	arís-R	Rg
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	is-W	Wp-in
stopfadh	stopfadh	stop-V	Vmc
Cócó	Cócó	cócó-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
mó	mó	mó-A	Aqc|Aqp
ná	ná	ná-C	Cs|Cc
sásta	sásta	sásta-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Daideo	Daideo	daideo-N	Ncmsc
.	.	.-F	Fe
Amach	Amach	amach-R	Rd
sa	sa	i-S	Spa-s
halla	halla	halla-N	Ncmsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Rug	Rug	beir-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
Chócó	Chócó	cócó-N	Ncmsc
bocht	bocht	bocht-A	Aq-msc
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
amach	amach	amach-R	Rd
sa	sa	i-S	Spa-s
ghairdín	ghairdín	gairdín-N	Ncmsc
cúil	cúil	cúl-N	Ncfsc|Ncmsg|Ncmpc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
thug	thug	tabhair-V	Vmis---n
.	.	.-F	Fe
Daideo	Daideo	daideo-N	Ncmsc
an	an	an-T	Td-s
nathair	nathair	nathair-N	Ncfsc
faoi	faoi	faoi-S	Sp
deara	deara	deara-N	Ns-s
ar	ar	ar-S	Sp
an	an	an-T	Td-s
staighre	staighre	staighre-N	Ncmsc
!	!	!-F	Fe
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
an	an	an-T	Td-s
lóin	lóin	lón-N	Ncmsg
dóibh	dóibh	do-P	Pr3-p
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
sa	sa	i-S	Spa-s
chistin	chistin	cistin-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
tásc	tásc	tásc-N	Ncmsc
ná	ná	ná-C	Cs|Cc
tuairisc	tuairisc	tuairisc-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
diabhal	diabhal	diabhal-N	Ncmsc
de	de	de-S	Sp
nathair	nathair	nathair-N	Ncfsc
sin	sin	sin-P	Pd|Dd
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
le	le	le-S	Sp
Muireann	Muireann	Muireann-N	Npfsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
agus	agus	agus-C	Cc
is	is	is-W	Wpri
gearr	gearr	gearr-V	Vmm-2s
go	go	go-Q	Q
mbeidh	mbeidh	bí-V	Vmif
do	do	do-S	Sp
Mhamaí	Mhamaí	mama-N	Ncfsc|Ncmpc
ar ais	ar ais	ar_ais-R	Rd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
gur	gur	gur-Q	Q--s
éalaigh	éalaigh	éalaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
amach	amach	amach-R	Rd
i	i	i-S	Sp
ngan fhios	ngan fhios	gan_fhios-N	Ncmsc
dúinn	dúinn	do-P	Pr1-p
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daideo	Daideo	daideo-N	Ncmsc
.	.	.-F	Fe
Go	Go	go-U	Ua
tobann	tobann	tobann-A	Aqp
chuala	chuala	clois-V	Vmis
siad	siad	siad-P	Pp3-pn
torann	torann	torann-N	Ncmsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
cúil	cúil	cúl-N	Ncfsc|Ncmsg|Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
nathair	nathair	nathair-N	Ncfsc
taobh amuigh	taobh amuigh	taobh_amuigh-R	Rl
den	den	de-S	Spa-s
doras	doras	doras-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
de	de	de-S	Sp
chogar	chogar	cogar-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seasaigí	Seasaigí	seas-V	Vmm-2p
siar	siar	siar-R	Rd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daideo	Daideo	daideo-N	Ncmsc
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
sé	sé	sé-P	Pp3msn
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
tarraiceán	tarraiceán	tarraiceán-N	Ncmsc
agus	agus	agus-C	Cc
thóg	thóg	tóg-V	Vmis
sé	sé	sé-P	Pp3msn
amach	amach	amach-R	Rd
scian	scian	scian-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
mhillteanach	mhillteanach	millteanach-A	Aq-fsc|Aq-fsv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seachnaígí	Seachnaígí	seachain-V	Vmm-2p
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
Anonn	Anonn	anonn-R	Rd
le	le	le-S	Sp
Daideo	Daideo	daideo-N	Ncmsc
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
scian	scian	scian-N	Ncfsc
ina	ina	i-S	Spp-s|Spp-p
lámh	lámh	lámh-N	Ncfsc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
go	go	go-U	Ua
mall	mall	mall-A	Aqp
cúramach	cúramach	cúramach-A	Aqp
…	…	…-F	Fi
…	…	…-F	Fi
agus	agus	agus-C	Cc
cé	cé	cé-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
taobh amuigh	taobh amuigh	taobh_amuigh-R	Rl
ach	ach	ach-C	Cs
…	…	…-F	Fi
Cócó	Cócó	cócó-N	Ncmsc
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
créatúirín	créatúirín	créatúr-N	Ncmsc
bocht	bocht	bocht-A	Aq-msc
stiúgtha	stiúgtha	stiúg-A	Av
leis	leis	le-S	Sp
an	an	an-T	Td-s
ocras	ocras	ocras-N	Ncmsc
!	!	!-F	Fe
Thug	Thug	tabhair-V	Vmis
Conall	Conall	Conall-N	Npmsc
blúire	blúire	blúire-N	Ncmsg|Ncmsc
bia	bia	bia-N	Ncmsg|Ncmsc
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
lón	lón	lón-N	Ncmsc
ite	ite	ith-A	Av
acu	acu	ag-P	Pr3-p
thosaigh	thosaigh	tosaigh-V	Vmis
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
cuardach	cuardach	cuardaigh-N	Nv
arís	arís	arís-R	Rg
.	.	.-F	Fe
Sa	Sa	i-S	Spa-s
gharáiste	gharáiste	garáiste-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
ag	ag	ag-S	Sp
cuardach	cuardach	cuardaigh-N	Nv
an	an	an-T	Td-s
uair	uair	uair-N	Ncfsc
seo	seo	seo-D	Dd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
sí	sí	sí-P	Pp3fsn
agam	agam	ag-P	Pr1-s
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
de	de	de-S	Sp
bhéic	bhéic	béic-N	Ncfsc
tar éis	tar éis	tar_éis-S	Spc
cúpla	cúpla	cúpla-N	Ncmsg
nóiméad	nóiméad	nóiméad-N	Ncmpg|Ncmsc|Ncmpg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
nathair	nathair	nathair-N	Ncfsc
nimhe	nimhe	nimh-N	Ncfsg
faighte	faighte	faigh-A	Av
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
tá	tá	bí-V	Vmip
sí	sí	sí-P	Pp3fsn
do	do	do-D	Dp2-s|Sp
mo	mo	mo-D	Dp1-s
thachtadh	thachtadh	tacht-V	Vmih
!	!	!-F	Fe
Ááááá	Ááááá	Ááááá-N	Npmsc
!	!	!-F	Fe
’	’	’-F	Fa
.	.	.-F	Fe
Amach	Amach	amach-R	Rd
leis	leis	le-S	Sp
an	an	an-T	Td-s
triúr	triúr	triúr-N	Ncmsc
sa	sa	i-S	Spa-s
gharáiste	gharáiste	garáiste-N	Ncmsc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
gcroí	gcroí	croí-N	Ncmsc
ina	ina	i-S	Spp-p
mbéal	mbéal	béal-N	Ncmsc
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
Muireann	Muireann	Muireann-N	Npfsc
Mamó	Mamó	mamó-N	Ncfsc
phléasc	phléasc	pléasc-V	Vmis
sí	sí	sí-P	Pp3fsn
amach	amach	amach-R	Rd
ag	ag	ag-S	Sp
gáire	gáire	gáir-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
a	a	a-U	Uv
Mhamó	Mhamó	mamó-N	Ncfsv
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
haon	haon	aon-M	Mc
nathair	nathair	nathair-N	Ncfsc
é	é	é-P	Pp3ms
sin	sin	sin-W	W
.	.	.-F	Fe
Sin	Sin	sin-W	W
é	é	é-P	Pp3ms
an	an	an-T	Td-s
píobán	píobán	píobán-N	Ncmsc
uisce	uisce	uisce-N	Ncmsg|Ncmsc
!	!	!-F	Fe
’	’	’-F	Fa
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
caithfidh	caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
mo	mo	mo-D	Dp1-s
spéaclaí	spéaclaí	spéacla-N	Ncmpc
a	a	a-U	U
fháil	fháil	faigh-N	Nv
.	.	.-F	Fe
Níl	Níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
mhaith	mhaith	maith-N	Ncfsc
ionam	ionam	i-N	Ncmpg|Ncmsc|Pr1-s
gan	gan	gan-S	Sp
iad	iad	iad-P	Pp3-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
mo	mo	mo-D	Dp1-s
spéaclaí	spéaclaí	spéacla-N	Ncmpc
in	in	i-S	Sp
aon	aon	aon-D	Dq
áit	áit	áit-N	Ncfsc
sa	sa	i-S	Spa-s
teach	teach	teach-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuaigh	chuaigh	téigh-V	Vmis
siad	siad	siad-P	Pp3-pn
ar ais	ar ais	ar_ais-R	Rd
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
chistin	chistin	cistin-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
B	B	B-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
gur	gur	is-W	Wsdi
fhág	fhág	fág-N	Ncmsc
mé	mé	mé-P	Pp1-s
sa	sa	i-S	Spa-s
charr	charr	carr-N	Ncmsc|Ncfsc
iad	iad	iad-P	Pp3-p
ar	ar	ar-S	Sp
maidin	maidin	maidin-N	Ncfsc
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
a	a	a-D	Dp3
cóta	cóta	cóta-N	Ncmsc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfaca	bhfaca	feic-V	Vmis---d
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
mo	mo	mo-D	Dp1-s
scaif	scaif	scaif-N	Ncfsc
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Chonaic	Chonaic	feic-V	Vmis
mise	mise	mé-P	Pp1-s-e
sa	sa	i-S	Spa-s
halla	halla	halla-N	Ncmsc
í	í	í-P	Pp3fs
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Conall	Conall	Conall-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Go	Go	go-U	Ua
maith	maith	maith-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
agus	agus	agus-C	Cc
amach	amach	amach-R	Rd
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
do	do	do-D	Dp2-s
Mhamó	Mhamó	mamó-N	Ncfsc
imeacht	imeacht	imigh-N	Ncmsc|Nv
as	as	as-S	Sp
an	an	an-T	Td-s
gcistin	gcistin	cistin-N	Ncfsc
chuala	chuala	clois-V	Vmis
an	an	an-T	Td-s
triúr	triúr	triúr-N	Ncmsc
eile	eile	eile-D	Dd
cnag	cnag	cnag-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
tosaigh	tosaigh	tosach-N	Ncmpc|Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
gurb	gurb	is-W	Wpdi
í	í	í-P	Pp3fs
sin	sin	sin-P	Pd|W
Mamaí	Mamaí	mama-N	Ncfsc|Aqc|Ncmpc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Muireann	Muireann	Muireann-N	Npfsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ansin	ansin	ansin-R	Rt|Rl
chuala	chuala	clois-V	Vmis
siad	siad	siad-P	Pp3-pn
scread	scread	scread-N	Ncfsc
mhillteanach	mhillteanach	millteanach-A	Aq-fsc
…	…	…-F	Fi
‘	‘	‘-X	Xx
Ááááá	Ááááá	Ááááá-N	Npmsc
…	…	…-F	Fi
!	!	!-F	Fe
’	’	’-F	Fa
.	.	.-F	Fe
‘	‘	‘-X	Xx
Dia	Dia	dia-N	Ncmsc
idir	idir	idir-S	Sp
sinn	sinn	sinn-P	Pp1-p
agus	agus	agus-C	Cc
an	an	an-T	Td-s
anachain	anachain	anachain-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daideo	Daideo	daideo-N	Ncmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
rud	rud	rud-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
ar	ar	ar-S	Sp
Mhamó	Mhamó	mamó-N	Ncfsc
.	.	.-F	Fe
Amach	Amach	amach-R	Rd
leis	leis	le-S	Sp
an	an	an-T	Td-s
triúr	triúr	triúr-N	Ncmsc
ar nós	ar nós	ar_nós-S	Spc
na	na	na-T	Tdfsg
gaoithe	gaoithe	gaoth-N	Ncfsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Mamaí	Mamaí	mamaí-N	Ncfsc
bhocht	bhocht	bocht-A	Aq-fsc
sínte	sínte	sín-A	Av
ar	ar	ar-S	Sp
urlár	urlár	urlár-N	Ncmsc
an	an	an-T	Td-s
halla	halla	halla-N	Ncmsg
gan	gan	gan-S	Sp
cor	cor	cor-N	Ncmsc
aisti	aisti	as-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
cromtha	cromtha	crom-A	Av
lena	lena	le-S	Spp-s
taobh	taobh	taobh-N	Ncmsc
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
an-trína	an-trína	an-trín-N	Ncfpc
chéile	chéile	céile-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
thuigim	thuigim	tuig-V	Vmip1s-n
é	é	é-P	Pp3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Chomh	Chomh	chomh-R	Ri
luath	luath	luath-A	Aqp
in	in	i-S	Sp
Éirinn	Éirinn	Éire-N	Npfsd
agus	agus	agus-C	Cc
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
sí	sí	sí-P	Pp3fsn
mé	mé	mé-P	Pp1-s
lig	lig	lig-V	Vmis
sí	sí	sí-P	Pp3fsn
béic	béic	béic-N	Ncfsc
aisti	aisti	as-P	Pr3fs
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
an	an	an-T	Td-s
chéad	chéad	céad-M	Mo
rud	rud	rud-N	Ncmsc
eile	eile	eile-D	Dd
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
sínte	sínte	sín-A	Av
ar	ar	ar-S	Sp
an	an	an-T	Td-s
urlár	urlár	urlár-N	Ncmsc
!	!	!-F	Fe
’	’	’-F	Fa
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
a	a	a-U	Uv
Mhamó	Mhamó	mamó-N	Ncfsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Muireann	Muireann	Muireann-N	Npfsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
nach	nach	nach-Q	Qnr
bhfuil	bhfuil	bí-V	Vmip---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agat	agat	ag-P	Pr2-s
go	go	go-U	Ua
maith	maith	maith-A	Aqp
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
scanraithe	scanraithe	scanraigh-A	Av
roimh	roimh	roimh-S	Sp
nathracha	nathracha	nathair-N	Ncfpc
.	.	.-F	Fe
Nach	Nach	is-W	Wpsin
í	í	í-P	Pp3fs
sin	sin	sin-P	Pd|W
Neaindí	Neaindí	Neaindí-N	Npmsc
atá	atá	bí-V	Vmip---r
timpeall	timpeall	timpeall-R	Rd|Ncmsc|Sp
ar	ar	ar-S	Sp
do	do	do-S	Sp
mhuineál	mhuineál	muineál-N	Ncmsc
agat	agat	ag-P	Pr2-s
!	!	!-F	Fe
’	’	’-F	Fa
.	.	.-F	Fe
‘	‘	‘-X	Xx
Go	Go	go-S	Sp
sábhála	sábhála	sábháil-N	Nv--g|Ncfsg
Dia	Dia	dia-N	Ncmsc
sinn	sinn	sinn-P	Pp1-p
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
nathair	nathair	nathair-N	Ncfsc
nimhe	nimhe	nimh-N	Ncfsg
timpeall	timpeall	timpeall-N	Ncmpg|Ncmsc|Sp|Rd
ar	ar	is-W	Wpsi|Sp|Wssi|Wpdi
mo	mo	mo-D	Dp1-s
mhuineál	mhuineál	muineál-N	Ncmsc
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
á	á	do-S	Spo-s
croitheadh	croitheadh	croith-N	Nv
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
an	an	an-T	Td-s
nathair	nathair	nathair-N	Ncfsc
a	a	a-U	U
bhaint	bhaint	bain-N	Nv
dá	dá	de-S	Spp-p|Spp-s
muineál	muineál	muineál-N	Ncmsc
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
Daideo	Daideo	daideo-N	Ncmsc
suas	suas	suas-R	Rd
go dtí	go dtí	go_dtí-S	Spc
seomra	seomra	seomra-N	Ncmsc
Mhuireann	Mhuireann	Muireann-N	Npfsc
.	.	.-F	Fe
Níorbh	Níorbh	is-W	Ws-in
fhada	fhada	fada-A	Aqc|Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
ar ais	ar ais	ar_ais-R	Rd
agus	agus	agus-C	Cc
an	an	an-T	Td-s
bosca	bosca	bosca-N	Ncmsc
dearg	dearg	dearg-A	Aq-msc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
le	le	le-S	Sp
Mamó	Mamó	mamó-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Fan	Fan	fan-V	Vmm-2s
socair	socair	socair-A	Aqp
!	!	!-F	Fe
’	’	’-F	Fa
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
rug	rug	beir-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-U	Ua
cúramach	cúramach	cúramach-A	Aqp
ar	ar	ar-S	Sp
an	an	an-T	Td-s
nathair	nathair	nathair-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
a	a	a-D	Dp3
bhligeaird	bhligeaird	bhligeaird-N	Ncfsc
!	!	!-F	Fe
Níbhfaighidh	Níbhfaighidh	Níbhfaighidh-N	Npmsc
aon	aon	aon-D	Dq
nathair	nathair	nathair-N	Ncfsc
nimhe	nimhe	nimh-N	Ncfsg
an	an	an-T	Td-s
ceann	ceann	ceann-N	Ncmsc
is	is	is-U	U
fearr	fearr	maith-A	Aqc
ormsa	ormsa	ar-P	Pr1-s-e
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
agus	agus	agus-C	Cc
chaith	chaith	caith-V	Vmis
sé	sé	sé-P	Pp3msn
Neaindí	Neaindí	Neaindí-N	Npmsc
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
bhosca	bhosca	bosca-N	Ncmsc
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
d	d	d-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmm-2s
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
a	a	a-D	Dp3
súile	súile	súil-N	Ncfpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
an	an	an-T	Td-s
nathair	nathair	nathair-N	Ncfsc
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	is-W	Wpdq|Wp-q
nathair	nathair	nathair-N	Ncfsc
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Daideo	Daideo	daideo-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
ea	ea	ea-P	Pp3-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhí	Bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
cinnte	cinnte	cinnte-A	Av|Aqp
dearfa	dearfa	dearfa-A	Aqp
go	go	go-Q	Q
bhfaca	bhfaca	feic-V	Vmis---d
mé	mé	mé-P	Pp1-s
nathair	nathair	nathair-N	Ncfsc
nimhe	nimhe	nimh-N	Ncfsg
timpeall	timpeall	timpeall-N	Ncmpg|Ncmsc|Sp|Rd
ar	ar	ar-S	Sp
mhuineál	mhuineál	muineál-N	Ncmsc
Mhamó	Mhamó	mamó-N	Ncfsg
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
gach	gach	gach-D	Dq
éinne	éinne	duine-N	Ncmsc
ag	ag	ag-S	Sp
gáire	gáire	gáir-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nathair	Nathair	nathair-N	Ncfsc
nimhe	nimhe	nimh-N	Ncfsg
timpeall	timpeall	timpeall-N	Ncmpg|Ncmsc|Rd
ar	ar	is-W	Wpsi|Wssi|Wpdi
mo	mo	mo-D	Dp1-s
mhuineál	mhuineál	muineál-N	Ncmsc
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ar	Ar	ar-Q	Q-is
chuala	chuala	clois-V	Vmis
éinne	éinne	duine-N	Ncmsc
riamh	riamh	riamh-R	Rg
a	a	a-D	Dp3
leithéid	leithéid	leithéid-N	Ncfsc
!	!	!-F	Fe
’	’	’-F	Fa
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
iompaigh	iompaigh	iompaigh-V	Vmm-2s
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
timpeall	timpeall	timpeall-R	Rd|Ncmsc|Sp
chun	chun	chun-S	Sp
éirí	éirí	éirigh-N	Ncmsg|Nv--g
ina	ina	i-S	Spp-p|Spp-s
seasamh	seasamh	seasamh-N	Ncmsc
thug	thug	tabhair-V	Vmis
sí	sí	sí-P	Pp3fsn
faoi	faoi	faoi-S	Sp
deara	deara	deara-N	Ns-s
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
rud	rud	rud-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
istigh	istigh	istigh-R	Rl
faoin	faoin	faoi-S	Spa-s
mbord	mbord	bord-N	Ncmsc
teileafóin	teileafóin	teileafón-N	Ncmsg|Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
rud	rud	rud-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
anseo	anseo	anseo-R	Rl
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
agus	agus	agus-C	Cc
sháigh	sháigh	sáigh-V	Vmis
sí	sí	sí-P	Pp3fsn
isteach	isteach	isteach-R	Rd
a	a	a-D	Dp3
lámh	lámh	lámh-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Mo	Mo	mo-D	Dp1-s
spéaclaí	spéaclaí	spéacla-N	Ncmpc
!	!	!-F	Fe
Fuair	Fuair	faigh-V	Vmis
tú	tú	tú-P	Pp2-s
mo	mo	mo-D	Dp1-s
spéaclaí	spéaclaí	spéacla-N	Ncmpc
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
buíochas	buíochas	buíochas-N	Ncmsc
mór	mór	mór-A	Aq-msc
le	le	le-S	Sp
Dia	Dia	dia-N	Ncmsc
!	!	!-F	Fe
’	’	’-F	Fa
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
an	an	an-T	Td-s
tae	tae	tae-N	Ncmsg
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
in	in	i-S	Sp
am	am	am-N	Ncmsc
ag	ag	ag-S	Sp
Mamó	Mamó	mamó-N	Ncfsc
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
Daideo	Daideo	daideo-N	Ncmsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
abhaile	abhaile	abhaile-R	Rd
.	.	.-F	Fe
Shuigh	Shuigh	suigh-V	Vmis
Daideo	Daideo	daideo-N	Ncmsc
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
charr	charr	carr-N	Ncmsc|Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Fan	Fan	fan-V	Vmm-2s
ansin	ansin	ansin-R	Rt|Rl
,	,	,-F	Fi
a	a	a-D	Dp3
bhligeaird	bhligeaird	bhligeaird-N	Ncfsc
,	,	,-F	Fi
agus	agus	agus-C	Cc
ná	ná	nach-Q	Qnr
go dtí	go dtí	go_dtí-S	Spc
go	go	go-Q	Q
mbainfimid	mbainfimid	bain-V	Vmif1p
amach	amach	amach-R	Rd
an	an	an-T	Td-s
baile	baile	baile-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbosca	mbosca	bosca-N	Ncmsc
dearg	dearg	dearg-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
i	i	i-S	Sp
gcúl	gcúl	cúl-N	Ncmsc
an	an	an-T	Td-s
chairr	chairr	carr-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Slán	Slán	slán-N	Ncmsc
libh	libh	le-P	Pr2-p
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mamó	Mamó	mamó-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cuirfidh	Cuirfidh	cuir-V	Vmif
mé	mé	mé-P	Pp1-s
glaoch	glaoch	glaoigh-N	Ncmsc|Nv
oraibh	oraibh	ar-P	Pr2-p
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhainfimid	bhainfimid	bain-V	Vmif1p
amach	amach	amach-R	Rd
an	an	an-T	Td-s
baile	baile	baile-N	Ncmsc
.	.	.-F	Fe
Anois	Anois	anois-R	Rt
,	,	,-F	Fi
cá	cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
eochracha	eochracha	eochair-N	Ncfpc
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
?	?	?-F	Fq
Níl	Níl	bí-V	Vmip---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
ó	ó	ó-S	Sp
thalamh	thalamh	talamh-N	Ncfsc
an	an	an-T	Td-s
domhain	domhain	domhan-N	Ncmsg
cár	cár	cár-N	Ncmpg|Ncmsc
fhág	fhág	fág-V	Vmis
mé	mé	mé-P	Pp1-s
iad	iad	iad-P	Pp3-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
ná	ná	ná-Q	Qnm
habair	habair	abair-V	Vmm-2s-n
liom	liom	le-P	Pr1-s
…	…	…-F	Fi
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Muireann	Muireann	Muireann-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
nathair	nathair	nathair-N	Ncfsc
nimhe	nimhe	nimh-N	Ncfsg
i	i	i-S	Sp
seomra	seomra	seomra-N	Ncmsc
Mhuireann	Mhuireann	Muireann-N	Npfsc
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Conall	Conall	Conall-N	Npmsc
de	de	de-U	Up
bhéic	bhéic	béic-V	Vmis
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
chreid	chreid	creid-V	Vmis---n
Mamó	Mamó	mamó-N	Ncfsc
focal	focal	focal-N	Ncmsc
uaidh	uaidh	ó-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Éirigh	Éirigh	éirigh-V	Vmm-2s
as	as	as-P	Pr3ms
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
,	,	,-F	Fi
‘	‘	‘-X	Xx
agus	agus	agus-C	Cc
ná	ná	nach-Q	Qnr
bí	bí	bí-V	Vmm-2s-n
ag	ag	ag-S	Sp
cumadh	cumadh	cum-N	Nv
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
ag	ag	ag-S	Sp
cumadh	cumadh	cum-N	Nv
atá	atá	bí-V	Vmip---r
Conall	Conall	Conall-N	Npmsc
?	?	?-F	Fq
Léigh	Léigh	léigh-V	Vmm-2s
leat	leat	le-P	Pr2-s
go	go	go-Q	Q
bhfaighidh	bhfaighidh	faigh-V	Vmif---d
tú	tú	tú-P	Pp2-s
amach	amach	amach-R	Rd
!	!	!-F	Fe
.	.	.-F	Fe
