 Is	Is	-X	Xx
trom	trom	trom-N	Ncmsc
an	an	an-T	Td-s
t-ualach	t-ualach	ualach-N	Ncmsc
an	an	an-T	Td-s
leisce	leisce	leisce-N	Ncfsg|Ncfsc
!	!	!-F	Fe
Mí	Mí	Mí-N	Npfsc
na	na	na-T	Tdfsg
Nollag	Nollag	Nollaig-N	Ncfsg
i	i	i-S	Sp
mBaile	mBaile	Baile-N	Npmsc
Átha Cliath	Átha Cliath	Átha_Cliath-N	Npmsg
–	–	–-X	Xx
ghrian	ghrian	grian-V	Vmis
ag	ag	ag-S	Sp
taitneamh	taitneamh	taitin-N	Nv
,	,	,-F	Fi
spéaclaí	spéaclaí	spéacla-N	Ncmpc
gréine	gréine	grian-N	Ncfsg
agus	agus	agus-C	Cc
cultacha	cultacha	culaith-N	Ncfpg|Ncfpc
snámha	snámha	snámh-N	Nv--g|Ncmsg|Nv--g
ar	ar	ar-S	Sp
chách	chách	cách-N	Ncmsc
,	,	,-F	Fi
páistí	páistí	páiste-N	Ncmpc
ag	ag	ag-S	Sp
imirt	imirt	imir-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
trá	trá	trá-N	Ncfsc
!	!	!-F	Fe
Spleodar	Spleodar	spleodar-N	Ncmsc
ar	ar	ar-S	Sp
gach	gach	gach-D	Dq
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
!	!	!-F	Fe
Hé	Hé	é-P	Pp3ms
–	–	–-X	Xx
gabh	gabh	gabh-V	Vmm-2s
mo	mo	mo-D	Dp1-s
leithscéal	leithscéal	leithscéal-N	Ncmsc
?	?	?-F	Fq
Fan	Fan	fan-V	Vmm-2s
soicind	soicind	soicind-N	Ncmsc
!	!	!-F	Fe
Fan	Fan	fan-V	Vmm-2s
bomaite	bomaite	bomaite-N	Ncmsc
!	!	!-F	Fe
CÉN	CÉN	cé-W	W--q
SCÉAL	SCÉAL	scéal-N	Ncmsc
É	É	é-P	Pp3ms
SEO	SEO	seo-W	W
?	?	?-F	Fq
Mí	Mí	Mí-N	Npfsc
na	na	na-T	Tdfsg
Nollag	Nollag	Nollaig-N	Ncfsg
i	i	i-S	Sp
mBaile	mBaile	Baile-N	Npmsc
Átha Cliath	Átha Cliath	Átha_Cliath-N	Npmsg
–	–	–-X	Xx
sneachta	sneachta	sneachta-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
talamh	talamh	talamh-N	Ncfsc
,	,	,-F	Fi
hata	hata	hata-N	Ncmsc
agus	agus	agus-C	Cc
scaif	scaif	scaif-N	Ncfsc
ar	ar	ar-S	Sp
chách	chách	cách-N	Ncmsc
,	,	,-F	Fi
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
ag	ag	ag-S	Sp
sciáil	sciáil	sciáil-N	Nv
chun	chun	chun-S	Sp
na	na	na-T	Tdfsg
scoile	scoile	scoil-N	Ncfsg
.	.	.-F	Fe
Spleodar	Spleodar	spleodar-N	Ncmsc
ar	ar	ar-S	Sp
gach	gach	gach-D	Dq
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
!	!	!-F	Fe
Hé	Hé	é-P	Pp3ms
–	–	–-X	Xx
gabh	gabh	gabh-V	Vmm-2s
mo	mo	mo-D	Dp1-s
leithscéal	leithscéal	leithscéal-N	Ncmsc
?	?	?-F	Fq
Fan	Fan	fan-V	Vmm-2s
soicind	soicind	soicind-N	Ncmsc
!	!	!-F	Fe
Fan	Fan	fan-V	Vmm-2s
bomaite	bomaite	bomaite-N	Ncmsc
!	!	!-F	Fe
CÉN	CÉN	cé-W	W--q
SCÉAL	SCÉAL	scéal-N	Ncmsc
É	É	é-P	Pp3ms
SEO	SEO	seo-W	W
?	?	?-F	Fq
INIS	INIS	inis-N	Npmsc|Vmis|Ncfsc|Vmm-2s
AN	AN	an-T	Td-s
FHÍRINNE	FHÍRINNE	fírinne-N	Ncfsc
!	!	!-F	Fe
Ó	Ó	Ó-I	I
,	,	,-F	Fi
maith	maith	maith-A	Aqp
go leor	go leor	go_leor-A	Aq
.	.	.-F	Fe
Mí	Mí	Mí-N	Npfsc
na	na	na-T	Tdfsg
Nollag	Nollag	Nollaig-N	Ncfsg
i	i	i-S	Sp
mBaile	mBaile	Baile-N	Npmsc
Átha Cliath	Átha Cliath	Átha_Cliath-N	Npmsg
–	–	–-X	Xx
báisteach	báisteach	báistigh-N	Ncfsc|Nv
,	,	,-F	Fi
cótaí	cótaí	cóta-N	Ncmpc
báistí	báistí	báistigh-A	Av
agus	agus	agus-C	Cc
buataisí	buataisí	buatais-N	Ncfpg|Ncfpc
ar	ar	ar-S	Sp
chách	chách	cách-N	Ncmsc
,	,	,-F	Fi
na	na	na-T	Td-p
sráideanna	sráideanna	sráid-N	Ncfpg|Ncfpc
plódaithe	plódaithe	plódaigh-A	Av
.	.	.-F	Fe
Fuadar	Fuadar	fuadar-N	Ncmsc
faoi	faoi	faoi-S	Sp
gach	gach	gach-D	Dq
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
!	!	!-F	Fe
ACH	ACH	ach-C	Cs
;	;	;-F	Fi
BHÍ	BHÍ	bí-V	Vmis
AN	AN	an-T	Td-s
NOLLAIG	NOLLAIG	Nollaig-N	Ncfsc
AG	AG	ag-S	Sp
TEACHT	TEACHT	tar-N	Nv
–	–	–-X	Xx
HURÁ	HURÁ	hurá-I	I
!	!	!-F	Fe
!	!	!-F	Fe
!	!	!-F	Fe
Ag	Ag	ag-S	Sp
an	an	an-T	Td-s
Mol	Mol	mol-N	Ncmsc
Thuaidh	Thuaidh	tuaidh-N	Ns-s
bhí	bhí	bí-V	Vmis
San	San	i-S	Spa-s
Nioclás	Nioclás	Nioclás-N	Npmsc
agus	agus	agus-C	Cc
Ag	Ag	ag-S	Sp
an	an	an-T	Td-s
Mol	Mol	mol-N	Ncmsc
Thuaidh	Thuaidh	tuaidh-A	Aqp
bhí	bhí	bí-V	Vmis
San	San	i-S	Spa-s
Nioclás	Nioclás	Nioclás-N	Npmsc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
chúntóirí	chúntóirí	cúntóir-N	Ncmpc
cruinnithe	cruinnithe	cruinnigh-A	Av
i	i	i-S	Sp
gCeanncheathrú	gCeanncheathrú	ceanncheathrú-N	Ncfsc
a	a	a-D	Dp3
chúntóirí	chúntóirí	cúntóir-N	Ncmpc
cruinnithe	cruinnithe	cruinnigh-A	Av
i	i	i-S	Sp
gCeanncheathrú	gCeanncheathrú	ceanncheathrú-N	Ncfsc
na	na	na-T	Td-p
Sióg	Sióg	sióg-N	Ncfpg
.	.	.-F	Fe
na	na	na-T	Tdfsg
Sióg	Sióg	sióg-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
Fáilte	Fáilte	fáilte-N	Ncfsc
romhaibh	romhaibh	roimh-P	Pr2-p
!	!	!-F	Fe
Mí	Mí	Mí-N	Npfsc
na	na	na-T	Tdfsg
Nollag	Nollag	Nollaig-N	Ncfsg
arís	arís	arís-R	Rg
,	,	,-F	Fi
cé	cé	cé-P	Pq
a	a	a-D	Dp3
'	'	'-F	Fa
Fáilte	Fáilte	fáilte-N	Ncfsc
romhaibh	romhaibh	roimh-P	Pr2-p
!	!	!-F	Fe
Mí	Mí	Mí-N	Npfsc
na	na	na-T	Tdfsg
Nollag	Nollag	Nollaig-N	Ncfsg
arís	arís	arís-R	Rg
,	,	,-F	Fi
cé	cé	cé-P	Pq
a	a	a-Q	Q-r
chreidfeadh	chreidfeadh	creid-V	Vmc
é	é	é-P	Pp3ms
?	?	?-F	Fq
Hó	Hó	Hó-N	Npmsc
!	!	!-F	Fe
Hó	Hó	Hó-N	Npmsc
!	!	!-F	Fe
Hó	Hó	Hó-N	Npmsc
!	!	!-F	Fe
’	’	’-F	Fa
chreidfeadh	chreidfeadh	creid-V	Vmc
é	é	é-P	Pp3ms
?	?	?-F	Fq
Hó	Hó	Hó-N	Npmsc
!	!	!-F	Fe
Hó	Hó	Hó-N	Npmsc
!	!	!-F	Fe
Hó	Hó	Hó-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
go leor	go leor	go_leor-A	Aq|Ns-s|Rg
oibre	oibre	obair-N	Ncfsg|Nv--g--n
le	le	le-S	Sp
déanamh	déanamh	déan-N	Nv
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
go leor	go leor	go_leor-A	Aq|Ns-s|Rg
oibre	oibre	obair-N	Ncfsg|Nv--g--n
le	le	le-S	Sp
déanamh	déanamh	déan-N	Nv
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Ghlaoigh	Ghlaoigh	glaoigh-V	Vmis
San	San	i-S	Spa-s
Nioclás	Nioclás	Nioclás-N	Npmsc
an	an	an-T	Td-s
rolla	rolla	rolla-N	Ncmsg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhreagair	fhreagair	freagair-V	Vmis
Ghlaoigh	Ghlaoigh	glaoigh-V	Vmis
San	San	i-S	Spa-s
Nioclás	Nioclás	Nioclás-N	Npmsc
an	an	an-T	Td-s
rolla	rolla	rolla-N	Ncmsg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhreagair	fhreagair	freagair-V	Vmis
gach	gach	gach-D	Dq
duine	duine	duine-N	Ncmsc
,	,	,-F	Fi
'	'	'-F	Fa
Anseo	Anseo	anseo-R	Rl
’	’	’-F	Fa
.	.	.-F	Fe
gach	gach	gach-D	Dq
duine	duine	duine-N	Ncmsc
,	,	,-F	Fi
'	'	'-F	Fa
Anseo	Anseo	anseo-R	Rl
’	’	’-F	Fa
.	.	.-F	Fe
'	'	'-F	Fa
Rúdolf	Rúdolf	Rúdolf-N	Npmsc
Rua	Rua	Rua-N	Npmsg|Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Rúdolf	Rúdolf	Rúdolf-N	Npmsc
Rua	Rua	Rua-N	Npmsg|Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Dada	Dada	dada-N	Ncmsc
.	.	.-F	Fe
Dada	Dada	dada-N	Ncmsc
.	.	.-F	Fe
Níos	Níos	níos-U	Uc
airde	airde	ard-A	Aqc
arís	arís	arís-R	Rg
:	:	:-F	Fi
'	'	'-F	Fa
Rúdolf	Rúdolf	Rúdolf-N	Npmsc
Rua	Rua	Rua-N	Npmsg|Npmsc
?	?	?-F	Fq
'	'	'-F	Fa
Dada	Dada	dada-N	Ncmsc
.	.	.-F	Fe
Níos	Níos	níos-U	Uc
airde	airde	ard-A	Aqc
arís	arís	arís-R	Rg
:	:	:-F	Fi
'	'	'-F	Fa
Rúdolf	Rúdolf	Rúdolf-N	Npmsc
Rua	Rua	Rua-N	Npmsg|Npmsc
?	?	?-F	Fq
'	'	'-F	Fa
'	'	'-F	Fa
As	As	as-S	Sp
láthair	láthair	láthair-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Seán	Seán	Seán-N	Npmsc
,	,	,-F	Fi
Ceannaire	Ceannaire	ceannaire-N	Ncmsc
na	na	na-T	Td-p
Sióg	Sióg	sióg-N	Ncfpg
.	.	.-F	Fe
'	'	'-F	Fa
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
sé	sé	sé-P	Pp3msn
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
San	San	i-S	Spa-s
Nioclás	Nioclás	Nioclás-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
slaghdán	slaghdán	slaghdán-N	Ncmsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
fearg	fearg	fearg-N	Ncfsc
ar	ar	ar-S	Sp
Shan	Shan	Shan-N	Npmsc
Nioclás	Nioclás	Nioclás-N	Npmsc
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
chuma	chuma	cuma-A	Aqp
le	le	le-S	Sp
Rúdolf	Rúdolf	Rúdolf-N	Npmsc
faoi	faoi	faoi-S	Sp
aon	aon	aon-M	Mc
duine	duine	duine-N	Ncmsc
seachas	seachas	seachas-S	Sp
é	é	é-P	Pp3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ann	ann	i-R	Rl|Pr3ms
ach	ach	ach-S	Sp
leadaí	leadaí	leadaí-N	Ncmsc
leisciúil	leisciúil	leisciúil-A	Aq-msc
.	.	.-F	Fe
Thóg	Thóg	tóg-V	Vmis
San	San	i-S	Spa-s
Nioclás	Nioclás	Nioclás-N	Npmsc
amach	amach	amach-R	Rd
a	a	a-D	Dp3
fhón	fhón	fón-N	Ncmsc
póca	póca	póca-N	Ncmsg|Ncmsc
agus	agus	agus-C	Cc
ghlaoigh	ghlaoigh	glaoigh-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
Rúdolf	Rúdolf	Rúdolf-N	Npmsc
.	.	.-F	Fe
Bíííp	Bíííp	Bíííp-N	Npmsc
bíííp	bíííp	bíííp-N	Ncfsc
bíííp	bíííp	bíííp-N	Ncfsc
–	–	–-X	Xx
'	'	'-F	Fa
Rúdolf	Rúdolf	Rúdolf-N	Npmsc
anseo	anseo	anseo-R	Rl
.	.	.-F	Fe
Nílim	Nílim	bí-V	Vmip1s-n
anseo	anseo	anseo-R	Rl
faoi	faoi	faoi-S	Sp
láthair	láthair	láthair-N	Ncfsc
.	.	.-F	Fe
Má	Má	má-C	Cs
tá	tá	bí-V	Vmip
mo	mo	mo-D	Dp1-s
shíniú	shíniú	sínigh-N	Ncmsc|Nv
uait	uait	ó-P	Pr2-s
,	,	,-F	Fi
cuir	cuir	cuir-V	Vmm-2s
glaoch	glaoch	glaoch-N	Ncmsc
ar	ar	ar-N	Ncmsc|Sp
mo	mo	mo-D	Dp1-s
rúnaí	rúnaí	rúnaí-N	Ncmsc
.	.	.-F	Fe
ghnó	ghnó	gnó-N	Ncmsc
eile	eile	eile-D	Dd
,	,	,-F	Fi
fág	fág	fág-V	Vmm-2s
teachtaireacht	teachtaireacht	teachtaireacht-N	Ncfsc
.	.	.-F	Fe
Slán	Slán	slán-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Tar éis	Tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
chuaigh	chuaigh	téigh-V	Vmis
San	San	i-S	Spa-s
Nioclás	Nioclás	Nioclás-N	Npmsc
sa	sa	i-S	Spa-s
tóir	tóir	tóir-N	Ncfsc
ar	ar	ar-S	Sp
Rúdolf	Rúdolf	Rúdolf-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Bhuel	Bhuel	bhuel-X	Xsc
,	,	,-F	Fi
a	a	a-U	Uv
Rúdolf	Rúdolf	Rúdolf-N	Npmsc
,	,	,-F	Fi
cén	cén	cé-W	W--q|Dw--s
leithscéal	leithscéal	leithscéal-N	Ncmsc
atá	atá	bí-V	Vmip---r
agat	agat	ag-P	Pr2-s
an	an	an-T	Td-s
uair	uair	uair-N	Ncfsc
seo	seo	seo-D	Dd
?	?	?-F	Fq
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
San	San	i-S	Spa-s
Nioclás	Nioclás	Nioclás-N	Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Rúdolf	Rúdolf	Rúdolf-N	Npmsc
ina	ina	i-S	Spp-s|Spp-p
luí	luí	luí-N	Ncmsc
ina	ina	i-S	Spp-s|Spp-p
stábla	stábla	stábla-N	Ncmsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
Mol	Mol	mol-N	Ncmsc
Thuaidh	Thuaidh	tuaidh-A	Aqp
agus	agus	agus-C	Cc
sióga	sióga	sióg-N	Ncfpc
óga	óga	óg-A	Aq--pc
ag	ag	ag-S	Sp
cíoradh	cíoradh	cíor-N	Nv
a	a	a-D	Dp3
chuid	chuid	cuid-N	Ncfsc
gruaige	gruaige	gruaig-N	Ncfsg
.	.	.-F	Fe
'	'	'-F	Fa
Táim	Táim	bí-V	Vmip1s
tinn	tinn	tinn-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Rúdolf	Rúdolf	Rúdolf-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Tinn	Tinn	tinn-A	Aqp
?	?	?-F	Fq
'	'	'-F	Fa
'	'	'-F	Fa
Is	Is	is-W	Wp-i
ea	ea	ea-P	Pp3-s
.	.	.-F	Fe
Tinn	Tinn	tinn-A	Aqp
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
slaghdán	slaghdán	slaghdán-N	Ncmsc
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
Ceapaim	Ceapaim	ceap-V	Vmip1s
go	go	go-Q	Q
bhfanfaidh	bhfanfaidh	fan-V	Vmif
mé	mé	mé-P	Pp1-s
sa	sa	i-S	Spa-s
leaba	leaba	leaba-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
a	a	a-U	Uv
Rúdolf	Rúdolf	Rúdolf-N	Npmsc
,	,	,-F	Fi
cad	cad	cad-W	W--q
faoin	faoin	faoi-S	Spa-s
turas	turas	turas-N	Ncmsc
anocht	anocht	anocht-N	Ns-s|Rt
?	?	?-F	Fq
Cad	Cad	cad-W	W--q
faoi	faoi	faoi-P	Pr3ms
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
?	?	?-F	Fq
'	'	'-F	Fa
'	'	'-F	Fa
Ná	Ná	ná-Q	Qnm
bac	bac	bac-V	Vmm-2s-n
leis	leis	le-S	Sp
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
,	,	,-F	Fi
céard	céard	cé-W	W--q
fúmsa	fúmsa	faoi-P	Pr1-s-e
?	?	?-F	Fq
'	'	'-F	Fa
'	'	'-F	Fa
Leis	Leis	le-S	Sp
an	an	an-T	Td-s
bhfírinne	bhfírinne	fírinne-N	Ncfsc
a	a	a-U	U
rá	rá	abair-N	Nv
,	,	,-F	Fi
a	a	a-U	Uv
Shan	Shan	Shan-N	Npmsc
Nioclás	Nioclás	Nioclás-N	Npmsc
,	,	,-F	Fi
nílim	nílim	bí-V	Vmip1s-n
sásta	sásta	sásta-A	Aqc
a thuilleadh	a thuilleadh	a_thuilleadh-R	Rg
sa	sa	i-S	Spa-s
phost	phost	post-N	Ncmsc
seo	seo	seo-D	Dd
.	.	.-F	Fe
Táim	Táim	bí-V	Vmip1s
tinn	tinn	tinn-A	Aqp
tuirseach	tuirseach	tuirseach-A	Aqp
den	den	de-S	Spa-s
taisteal	taisteal	taisteal-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Tinn	Tinn	tinn-A	Aqp
tuirseach	tuirseach	tuirseach-A	Aqp
den	den	de-S	Spa-s
taisteal	taisteal	taisteal-N	Ncmsc
?	?	?-F	Fq
Nach	Nach	is-W	Wpsin
tú	tú	tú-P	Pp2-s
an	an	an-T	Td-s
leadaí	leadaí	leadaí-N	Ncmsc
leisciúil	leisciúil	leisciúil-A	Aq-msc
!	!	!-F	Fe
Níl	Níl	bí-V	Vmip---n
i	i	i-S	Sp
gceist	gceist	ceist-N	Ncfsc
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
t-aon	t-aon	aon-M	Mc
oíche	oíche	oíche-N	Ncfsc
amháin	amháin	amháin-A	Aqp
sa	sa	i-S	Spa-s
bhliain	bhliain	bliain-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
ach	ach	ach-C	Cs
tá	tá	bí-V	Vmip
an	an	an-T	Td-s
carr	carr	carr-N	Ncmsc|Ncfsc
sleamhnáin	sleamhnáin	sleamhnán-N	Ncmsg|Ncmpc
an-trom	an-trom	trom-A	Aqp
.	.	.-F	Fe
I	I	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
róthrom	róthrom	trom-A	Aqp
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
bhreá	bhreá	breá-A	Aqp
liom	liom	le-P	Pr1-s
a	a	a-U	U
bheith	bheith	bí-N	Nv
i	i	i-S	Sp
m	m	m-X	Xl
’	’	’-F	Fa
aisteoir	aisteoir	aisteoir-N	Ncmsc
.	.	.-F	Fe
Ceapaim	Ceapaim	ceap-V	Vmip1s
go	go	go-Q	Q
rachaidh	rachaidh	téigh-V	Vmif
mé	mé	mé-P	Pp1-s
go	go	go-S	Sp
Hollywood	Hollywood	Hollywood-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Cad	Cad	cad-P	Pq
a	a	a-Q	Q-r
dhéanfaidh	dhéanfaidh	déan-V	Vmif
mé	mé	mé-P	Pp1-s
anois	anois	anois-R	Rt
?	?	?-F	Fq
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
San	San	i-S	Spa-s
Nioclás	Nioclás	Nioclás-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Ná	Ná	ná-Q	Qnm
bíodh	bíodh	bí-V	Vmm-3s-n
buairt	buairt	buairt-N	Ncfsc
ort	ort	ar-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Seán	Seán	Seán-N	Npmsc
,	,	,-F	Fi
Ceannaire	Ceannaire	ceannaire-N	Ncmsc
na	na	na-T	Td-p
Sióg	Sióg	sióg-N	Ncfpg
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
réiteach	réiteach	réiteach-N	Ncmsc
na	na	na-T	Tdfsg
faidhbe	faidhbe	fadhb-N	Ncfsg
agamsa	agamsa	ag-P	Pr1-s-e
.	.	.-F	Fe
Cuirfimid	Cuirfimid	cuir-V	Vmif1p
fógra	fógra	fógra-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
teilifís	teilifís	teilifís-N	Ncfsc
.	.	.-F	Fe
Rachaidh	Rachaidh	téigh-V	Vmif
mé	mé	mé-P	Pp1-s
chuig	chuig	chuig-S	Sp
RTÉ	RTÉ	RTÉ-Y	Y
.	.	.-F	Fe
'	'	'-F	Fa
I	I	i-S	Sp
mBaile	mBaile	Baile-N	Npmsc
Átha Cliath	Átha Cliath	Átha_Cliath-N	Npmsg
bhí	bhí	bí-V	Vmis
cailín	cailín	cailín-N	Ncmsc
beag	beag	beag-A	Aq-msc
darbh	darbh	dar-W	Wpsi|Csws
ainm	ainm	ainm-N	Ncmsc
Máire	Máire	Máire-N	Npf-g|Npfsc
ag	ag	ag-S	Sp
smaoineamh	smaoineamh	smaoinigh-N	Nv
faoin	faoin	faoi-S	Spa-s
Nollaig	Nollaig	Nollaig-N	Ncfsc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
bronntanais	bronntanais	bronntanas-N	Ncmpc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
iarrtha	iarrtha	iarr-A	Av
aici	aici	ag-P	Pr3fs
ar	ar	ar-S	Sp
Dhaidí	Dhaidí	daidí-N	Ncmsc
na	na	na-T	Tdfsg
Nollag	Nollag	Nollaig-N	Ncfsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
bábóg	bábóg	bábóg-N	Ncfpg
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sí	sí	sí-P	Pp3fsn
sásta	sásta	sásta-A	Aqp
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbronntanas	mbronntanas	bronntanas-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
faighte	faighte	faigh-A	Av
aici	aici	ag-P	Pr3fs
an	an	an-T	Td-s
bhliain	bhliain	bliain-N	Ncfsc
roimhe	roimhe	roimh-P	Pr3ms
sin	sin	sin-P	Pd
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
iarr	iarr	iarr-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
Dhaidí	Dhaidí	daidí-N	Ncmsc
na	na	na-T	Tdfsg
Nollag	Nollag	Nollaig-N	Ncfsg
madra	madra	madra-N	Ncmsc
beag	beag	beag-A	Aq-msc
D	D	D-X	Xl
’	’	’-F	Fa
iarr	iarr	iarr-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
Dhaidí	Dhaidí	daidí-N	Ncmsc
na	na	na-T	Tdfsg
Nollag	Nollag	Nollaig-N	Ncfsg
madra	madra	madra-N	Ncmsc
beag	beag	beag-A	Aq-msc
agus	agus	agus-C	Cc
bosca	bosca	bosca-N	Ncmsc
mór	mór	mór-A	Aq-msc
milseán	milseán	milseán-N	Ncmpg|Ncmsc|Ncmpg
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
di	di	do-P	Pr3fs
agus	agus	agus-C	Cc
bosca	bosca	bosca-N	Ncmsc
mór	mór	mór-A	Aq-msc
milseán	milseán	milseán-N	Ncmpg|Ncmsc|Ncmpg
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
di	di	do-P	Pr3fs
an	an	an-T	Td-s
bhliain	bhliain	bliain-N	Ncfsc
roimhe	roimhe	roimh-P	Pr3ms
sin	sin	sin-P	Pd
.	.	.-F	Fe
an	an	an-T	Td-s
bhliain	bhliain	bliain-N	Ncfsc
roimhe	roimhe	roimh-P	Pr3ms
sin	sin	sin-W	W
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Máire	Máire	Máire-N	Npfsc
an-sásta	an-sásta	sásta-A	Aqp
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
fuair	fuair	faigh-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
madra	madra	madra-N	Ncmsc
ar	ar	ar-S	Sp
dtús	dtús	tús-N	Ncmsc
.	.	.-F	Fe
Mailí	Mailí	Mailí-N	Npfsc
a	a	a-Q	Q-r
thug	thug	tabhair-V	Vmis
sí	sí	sí-P	Pp3fsn
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
,	,	,-F	Fi
áfach	áfach	áfach-R	Rg
,	,	,-F	Fi
d	d	d-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmm-2s
Máire	Máire	Máire-N	Npfsc
tinn	tinn	tinn-A	Aqp
tuirseach	tuirseach	tuirseach-A	Aqp
den	den	de-S	Spa-s
mhadra	mhadra	madra-N	Ncmsc
beag	beag	beag-A	Aq-msc
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
sí	sí	sí-P	Pp3fsn
Mailí	Mailí	Mailí-N	Npfsc
isteach	isteach	isteach-R	Rd
léi	léi	le-P	Pr3fs
go	go	go-S	Sp
lár	lár	lár-N	Ncmsc
na	na	na-T	Tdfsg
cathrach	cathrach	cathair-N	Ncfsg
lá	lá	lá-N	Ncmsc
,	,	,-F	Fi
d	d	d-X	Xl
’	’	’-F	Fa
fhág	fhág	fág-V	Vmis
sí	sí	sí-P	Pp3fsn
in aice	in aice	in_aice-S	Spc
le	le	le-S	Sp
bosca	bosca	bosca-N	Ncmsc
bruscair	bruscair	bruscar-N	Ncmsg
í	í	í-P	Pp3fs
agus	agus	agus-C	Cc
léim	léim	léim-V	Vmip1s|Vmis
ar	ar	ar-S	Sp
bhus	bhus	bus-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
madra	madra	madra-N	Ncmsc
beag	beag	beag-A	Aq-msc
fágtha	fágtha	fág-A	Aqp|Av
ansin	ansin	ansin-R	Rt|Rl
agus	agus	agus-C	Cc
gan	gan	gan-S	Sp
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
aici	aici	ag-P	Pr3fs
cad	cad	cad-P	Pq
a	a	a-Q	Q-r
dhéanfadh	dhéanfadh	déan-V	Vmc
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Mailí	Mailí	Mailí-N	Npfsc
ag	ag	ag-S	Sp
maireachtáil	maireachtáil	mair-N	Nv
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
i lár	i lár	i_lár-S	Spc
na	na	na-T	Tdfsg
cathrach	cathrach	cathair-N	Ncfsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
uaigneach	uaigneach	uaigneach-A	Aqp
ocrach	ocrach	ocrach-A	Aqp
croíbhriste	croíbhriste	croíbhriste-A	Aqp
agus	agus	agus-C	Cc
ghoid	ghoid	goid-V	Vmis
sí	sí	sí-P	Pp3fsn
bia	bia	bia-N	Ncmsc
as	as	as-N	Ncmpg|Sp|Ncmsc
cibé	cibé	cibé-P	Pi|Dq
áit	áit	áit-N	Ncfsc
a	a	a-Q	Q-p
bhfaigheadh	bhfaigheadh	faigh-V	Vmc----d|Vmih
sí	sí	sí-P	Pp3fsn
é	é	é-P	Pp3ms
.	.	.-F	Fe
An	An	an-T	Td-s
lá	lá	lá-N	Ncmsc
áirithe	áirithe	áirigh-A	Aqp|Av
seo	seo	seo-D	Dd
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
Mailí	Mailí	Mailí-N	Npfsc
i ndiaidh	i ndiaidh	i_ndiaidh-S	Spc
ispíní	ispíní	ispín-N	Ncmpc
a	a	a-U	U
ghoid	ghoid	goid-N	Nv
ó	ó	ó-S	Sp
shiopa	shiopa	siopa-N	Ncmsc
búistéara	búistéara	búistéir-N	Ncmsg
.	.	.-F	Fe
Siúd	Siúd	siúd-P	Pd
léi	léi	le-P	Pr3fs
ar	ar	ar-S	Sp
cosa	cosa	cos-N	Ncfpc
in	in	i-S	Sp
airde	airde	airde-N	Ncfpc|Ncfsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
búistéir	búistéir	búistéir-N	Ncmsc
sa	sa	i-S	Spa-s
tóir	tóir	tóir-N	Ncfsc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Ar	Ar	is-N	Ncmsc|Sp|Wssi|Q-is|Wpsi
deireadh	deireadh	deireadh-V	Vmih|Ncmsc
thiar	thiar	thiar-R	Rd
thall	thall	tall-V	Vmis
,	,	,-F	Fi
stad	stad	stad-V	Vmis|Nv|Ncmsc|Nv
Mailí	Mailí	Mailí-N	Npf-g|Npfsc
taobh amuigh	taobh amuigh	taobh_amuigh-R	Rl
de	de	de-S	Sp
shiopa	shiopa	siopa-N	Ncmsc
teilifíseán	teilifíseán	teilifíseán-N	Ncmpg
chun	chun	chun-S	Sp
a	a	a-D	Dp3
hanáil	hanáil	anáil-N	Ncfsc
a	a	a-U	U
tharraingt	tharraingt	tarraing-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
nuacht	nuacht	nuacht-N	Ncfsc
ar	ar	ar-S	Sp
siúl	siúl	siúil-N	Nv
ar	ar	ar-S	Sp
na	na	na-T	Td-p
teilifíseáin	teilifíseáin	teilifíseán-N	Ncmpc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
i	i	i-S	Sp
bhfuinneog	bhfuinneog	fuinneog-N	Ncfsc
an	an	an-T	Td-s
tsiopa	tsiopa	siopa-N	Ncmsg
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
fadhb	fadhb	fadhb-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
Mol	Mol	mol-N	Ncmsc
Thuaidh	Thuaidh	tuaidh-A	Aqp
anocht	anocht	anocht-N	Ns-s|Rt
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
Rúdolf	Rúdolf	Rúdolf-N	Npmsc
Rua	Rua	Rua-N	Npmsc
tinn	tinn	tinn-A	Aq-msc
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
sé	sé	sé-P	Pp3msn
ábalta	ábalta	ábalta-A	Aqp
an	an	an-T	Td-s
carr	carr	carr-N	Ncmsc|Ncfsc
sleamhnáin	sleamhnáin	sleamhnán-N	Ncmsg|Ncmpc
a	a	a-U	U
thiomáint	thiomáint	tiomáin-N	Nv
.	.	.-F	Fe
Anseo	Anseo	anseo-R	Rl
liom	liom	le-P	Pr1-s
anois	anois	anois-R	Rt
tá	tá	bí-V	Vmip
Seán	Seán	Seán-N	Npmsc
,	,	,-F	Fi
Ceannaire	Ceannaire	ceannaire-N	Ncmsc
na	na	na-T	Td-p
Sióg	Sióg	sióg-N	Ncfpg
.	.	.-F	Fe
Cén	Cén	cé-W	W--q
scéal	scéal	scéal-N	Ncmsc
atá	atá	bí-V	Vmip---r
agatsa	agatsa	ag-P	Pr2-s-e
dúinn	dúinn	do-P	Pr1-p
,	,	,-F	Fi
a	a	a-U	Uv
Sheáin	Sheáin	Seán-N	Npm-v
?	?	?-F	Fq
'	'	'-F	Fa
'	'	'-F	Fa
Bhuel	Bhuel	bhuel-X	Xsc
,	,	,-F	Fi
tá	tá	bí-V	Vmip
na	na	na-T	Td-p
sióga	sióga	sióg-N	Ncfpc
réidh	réidh	réidh-A	Aq--pg|Aqp
ach	ach	ach-C	Cs
tá	tá	bí-V	Vmip
slaghdán	slaghdán	slaghdán-N	Ncmsc
ar	ar	ar-S	Sp
Rúdolf	Rúdolf	Rúdolf-N	Npmsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
créatúr	créatúr	créatúr-N	Ncmsc
chomh	chomh	chomh-R	Ri
lag	lag	lag-A	Aqp
le	le	le-S	Sp
sicín	sicín	sicín-N	Ncmsc
.	.	.-F	Fe
Caithfidh	Caithfidh	caith-V	Vmif
San	San	i-S	Spa-s
Nioclás	Nioclás	Nioclás-N	Npmsc
tiománaí	tiománaí	tiománaí-N	Ncmsg|Ncmsc
nua	nua	nua-A	Aqp
a	a	a-U	U
fháil	fháil	faigh-N	Nv
.	.	.-F	Fe
Is	Is	is-W	Wp-i
post	post	post-N	Ncmsc
deas	deas	deas-A	Aq-msc
é	é	é-P	Pp3ms
seo	seo	seo-P	Pd
.	.	.-F	Fe
Beidh	Beidh	bí-V	Vmif
rogha	rogha	rogha-N	Ncfsc
gach	gach	gach-D	Dq
bia	bia	bia-N	Ncmsc
agus	agus	agus-C	Cc
togha	togha	togha-N	Ncmsg|Ncmsc
gach	gach	gach-D	Dq
le	le	le-S	Sp
fáil	fáil	faigh-N	Nv
ag	ag	ag-S	Sp
an	an	an-T	Td-s
té	té	té-N	Ncmsc
a	a	a-Q	Q-i|Q-r
gheobhaidh	gheobhaidh	faigh-V	Vmif
é	é	é-P	Pp3ms
.	.	.-F	Fe
Cuir	Cuir	cuir-V	Vmm-2s
glaoch	glaoch	glaoch-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
uimhir	uimhir	uimhir-N	Ncfsc
seo	seo	seo-D	Dd
–	–	–-X	Xx
a	a	a-U	Um
naoi	naoi	naoi-M	Mc
,	,	,-F	Fi
a	a	a-U	Um
hocht	hocht	ocht-M	Mc
,	,	,-F	Fi
a	a	a-U	Um
seacht	seacht	seacht-M	Mc
,	,	,-F	Fi
a	a	a-U	Um
sé	sé	sé-P	Pp3msn
,	,	,-F	Fi
a	a	a-U	Um
cúig	cúig	cúig-M	Mc
,	,	,-F	Fi
a	a	a-U	Um
ceathair	ceathair	ceathair-M	Mc
,	,	,-F	Fi
a	a	a-U	Um
trí	trí	trí-M	Mc
,	,	,-F	Fi
a	a	a-U	Um
dó	dó	dó-M	Mc
,	,	,-F	Fi
a	a	a-U	Um
haon	haon	aon-M	Mc
–	–	–-X	Xx
láithreach	láithreach	láithreach-N	Ncmsc
!	!	!-F	Fe
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
Mailí	Mailí	Mailí-N	Npfsc
ag	ag	ag-S	Sp
éisteacht	éisteacht	éist-N	Nv
go	go	go-U	Ua
haireach	haireach	aireach-A	Aqp
.	.	.-F	Fe
Tiománaí	Tiománaí	Tiománaí-N	Npmsc
an	an	an-T	Td-s
chairr	chairr	carr-N	Ncmsg
shleamhnáin	shleamhnáin	sleamhnán-N	Ncmsg
!	!	!-F	Fe
Carr	Carr	Carr-N	Npmsc
sleamhnáin	sleamhnáin	sleamhnán-N	Ncmsg
Shan	Shan	San-A	Aq-msc
Nioclás	Nioclás	Nioclás-N	Npmsc
!	!	!-F	Fe
Ní	Ní	ní-Q	Qn
bheadh	bheadh	bí-V	Vmc----n
ocras	ocras	ocras-N	Ncmsc
ná	ná	ná-C	Cs|Cc
tart	tart	tart-N	Ncmsc|Xfea|Xfen
uirthi	uirthi	ar-P	Pr3fs
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
arís	arís	arís-R	Rg
dá	dá	dá-C	Cs
bhfaigheadh	bhfaigheadh	faigh-V	Vmc----d|Vmih
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
post	post	post-N	Ncmsc
seo	seo	seo-D	Dd
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
alp	alp	alp-V	Vmis
sí	sí	sí-P	Pp3fsn
siar	siar	siar-R	Rd
na	na	na-T	Td-p
hispíní	hispíní	ispín-N	Ncmpc
agus	agus	agus-C	Cc
siúd	siúd	siúd-P	Pd
léi	léi	le-P	Pr3fs
ar	ar	ar-S	Sp
cosa	cosa	cos-N	Ncfpc
in	in	i-S	Sp
airde	airde	airde-N	Ncfpc|Ncfsc
go dtí	go dtí	go_dtí-S	Spc
stiúideo	stiúideo	stiúideo-N	Ncmsc
RTÉ	RTÉ	RTÉ-Y	Y
.	.	.-F	Fe
'	'	'-F	Fa
A	A	a-U	Uv
Shan	Shan	Shan-N	Npmsc
Nioclás	Nioclás	Nioclás-N	Npmsc
,	,	,-F	Fi
seo	seo	seo-P	Pd
í	í	í-P	Pp3fs
Mailí	Mailí	Mailí-N	Npfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Seán	Seán	Seán-N	Npmsc
,	,	,-F	Fi
Ceannaire	Ceannaire	ceannaire-N	Ncmsc
na	na	na-T	Td-p
Sióg	Sióg	sióg-N	Ncfpg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
San	San	i-S	Spa-s
Nioclás	Nioclás	Nioclás-N	Npmsc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Cinnte	Cinnte	cinn-A	Av
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
láidir	láidir	láidir-A	Aqp
scafánta	scafánta	scafánta-A	Aqp
–	–	–-X	Xx
ach	ach	ach-S	Sp
cailín	cailín	cailín-N	Ncmsc
!	!	!-F	Fe
Buachaillí	Buachaillí	buachaill-N	Ncmpc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sna	sna	i-S	Spa-p
réinfhianna	réinfhianna	réinfhia-N	Ncmpc
!	!	!-F	Fe
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
féin	féin	féin-P	Px
,	,	,-F	Fi
b	b	b-X	Xl
’	’	’-F	Fa
fhiú	fhiú	fiú-N	Ns-s
triail	triail	triail-N	Ncfsc|Nv
a	a	a-U	U
bhaint	bhaint	bain-N	Nv
aisti	aisti	as-P	Pr3fs
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
fáilte	fáilte	fáilte-N	Ncfsc
romhat	romhat	roimh-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Mhailí	Mhailí	Mailí-N	Npf-v
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
San	San	i-S	Spa-s
Nioclás	Nioclás	Nioclás-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
súil	súil	súil-N	Ncfsc
agam	agam	ag-P	Pr1-s
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
turas	turas	turas-N	Ncmsc
deas	deas	deas-A	Aq-msc
agat	agat	ag-P	Pr2-s
.	.	.-F	Fe
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
mearbhall	mearbhall	mearbhall-N	Ncmsc
fós	fós	fós-R	Rg
ar	ar	ar-S	Sp
Mhailí	Mhailí	Mailí-N	Npfsc
tar éis	tar éis	tar_éis-S	Spc
di	di	do-P	Pr3fs
taisteal	taisteal	taisteal-N	Ncmsc
ar	ar	ar-S	Sp
luas	luas	luas-N	Ncmsc
lasrach	lasrach	lasrach-A	Aq-msc
i	i	i-S	Sp
gcarr	gcarr	carr-N	Ncmsc|Ncfsc
sleamhnáin	sleamhnáin	sleamhnán-N	Ncmsg
Sheáin	Sheáin	Seán-N	Npfsg|Ncmsg
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
Mol	Mol	mol-N	Ncmsc
Thuaidh	Thuaidh	tuaidh-N	Ns-s
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
Mailí	Mailí	Mailí-N	Npfsc
cinnte	cinnte	cinn-A	Aqp|Av
dearfa	dearfa	dearfa-A	Aqp
go	go	go-Q	Q
ndéanfadh	ndéanfadh	déan-V	Vmc
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
beart	beart	beart-N	Ncmsc
.	.	.-F	Fe
Nach	Nach	nach-Q	Qnq
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
in ann	in ann	in_ann-S	Spc
rith	rith	rith-N	Nv
ar nós	ar nós	ar_nós-S	Spc
na	na	na-T	Tdfsg
gaoithe	gaoithe	gaoth-N	Ncfsg
?	?	?-F	Fq
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
aon	aon	aon-M	Mc
fhadhb	fhadhb	fadhb-N	Ncfsc
amháin	amháin	amháin-A	Aqp
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
'	'	'-F	Fa
A	A	a-U	Uv
Shan	Shan	Shan-N	Npmsc
Nioclás	Nioclás	Nioclás-N	Npmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mailí	Mailí	Mailí-N	Npfsc
go	go	go-U	Ua
himníoch	himníoch	imníoch-A	Aqp
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
fadhb	fadhb	fadhb-N	Ncfsc
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
Nílim	Nílim	bí-V	Vmip1s-n
ábalta	ábalta	ábalta-A	Aqc
eitilt	eitilt	eitil-N	Ncfsc|Nv
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Ná	Ná	ná-Q	Qnm
cuireadh	cuireadh	cuir-V	Vmis0--n
sé	sé	sé-P	Pp3msn
sin	sin	sin-P	Pd
isteach	isteach	isteach-R	Rd
ná	ná	ná-C	Cc
amach	amach	amach-R	Rd
ort	ort	ar-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Mhailí	Mhailí	Mailí-N	Npf-v
.	.	.-F	Fe
Nach	Nach	nach-Q	Qnr
bhfuil	bhfuil	bí-V	Vmip---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agat	agat	ag-P	Pr2-s
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
draíocht	draíocht	draíocht-N	Ncfsc
agamsa	agamsa	ag-P	Pr1-s-e
.	.	.-F	Fe
'	'	'-F	Fa
Thóg	Thóg	tóg-V	Vmis
San	San	i-S	Spa-s
Nioclás	Nioclás	Nioclás-N	Npmsc
bosca	bosca	bosca-N	Ncmsc
beag	beag	beag-A	Aq-msc
amach	amach	amach-R	Rd
as	as	as-P	Pr3ms
a	a	a-D	Dp3
phóca	phóca	póca-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
bosca	bosca	bosca-N	Ncmsc
agus	agus	agus-C	Cc
líonadh	líonadh	líon-N	Ncmsc|Vmis0|Vmih|Vmm-3s|Nv
an	an	an-T	Td-s
seomra	seomra	seomra-N	Ncmsg|Ncmsc
le	le	le-S	Sp
solas	solas	solas-N	Ncmsc
geal	geal	geal-A	Aq-msc
.	.	.-F	Fe
'	'	'-F	Fa
Is	Is	is-W	Wp-i
púdar	púdar	púdar-N	Ncmsc
draíochta	draíochta	draíocht-N	Ncfsg|Ncfpc|Ncfpg
é	é	é-P	Pp3ms
seo	seo	seo-P	Pd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
San	San	i-S	Spa-s
Nioclás	Nioclás	Nioclás-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Scaipfidh	Scaipfidh	scaip-V	Vmif
mé	mé	mé-P	Pp1-s
é	é	é-P	Pp3ms
seo	seo	seo-P	Pd
timpeall	timpeall	timpeall-R	Rd|Sp
ort	ort	ar-P	Pr2-s
agus	agus	agus-C	Cc
déarfaidh	déarfaidh	abair-V	Vmif
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
rann	rann	rann-N	Ncmsc
draíochta	draíochta	draíocht-N	Ncfsg|Ncfpc|Ncfpg
.	.	.-F	Fe
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
ullamh	ullamh	ullamh-N	Ncmsc
?	?	?-F	Fq
Dún	Dún	dún-V	Vmm-2s
do	do	do-S	Sp
shúile	shúile	súil-N	Ncfpc
.	.	.-F	Fe
'	'	'-F	Fa
Dhún	Dhún	dún-V	Vmis
Mailí	Mailí	Mailí-N	Npfsc
a	a	a-D	Dp3
súile	súile	súil-N	Ncfpc
.	.	.-F	Fe
'	'	'-F	Fa
Cas	Cas	Cas-N	Npmsc
timpeall	timpeall	timpeall-S	Sp
trí	trí	trí-M	Mc
huaire	huaire	uair-N	Ncfsg
agus	agus	agus-C	Cc
ansin	ansin	ansin-R	Rt|Rl
oscail	oscail	oscail-V	Vmm-2s
do	do	do-S	Sp
shúile	shúile	súil-N	Ncfpc
.	.	.-F	Fe
'	'	'-F	Fa
Rinne	Rinne	déan-V	Vmis
Mailí	Mailí	Mailí-N	Npfsc
an	an	an-T	Td-s
rud	rud	rud-N	Ncmsc
a	a	a-Q	Q-r
dúradh	dúradh	abair-V	Vmis0
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Go	Go	go-U	Ua
tobann	tobann	tobann-A	Aqp
bhraith	bhraith	braith-V	Vmis
sí	sí	sí-P	Pp3fsn
chomh	chomh	chomh-R	Ri
héadrom	héadrom	éadrom-A	Aqp
le	le	le-S	Sp
cleite	cleite	cleite-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
súile	súile	súil-N	Ncfpc
.	.	.-F	Fe
'	'	'-F	Fa
Ó	Ó	Ó-I	I
,	,	,-F	Fi
a	a	a-U	Uv
Mhailí	Mhailí	Mailí-N	Npf-v
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Seán	Seán	Seán-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
eitilt	eitilt	eitil-N	Nv
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
eitilt	eitilt	eitil-N	Nv
!	!	!-F	Fe
’	’	’-F	Fa
Oíche	Oíche	oíche-N	Ncfsc
Nollag	Nollag	Nollaig-N	Ncfsg
!	!	!-F	Fe
Oíche	Oíche	oíche-N	Ncfsc
dhochreidte	dhochreidte	dochreidte-A	Aqp
!	!	!-F	Fe
Mailí	Mailí	Mailí-N	Npfsc
,	,	,-F	Fi
tiománaí	tiománaí	tiománaí-N	Ncmsc
nua	nua	nua-A	Aqp
Shan	Shan	San-A	Aqp
Nioclás	Nioclás	Nioclás-N	Npmsc
,	,	,-F	Fi
ag	ag	ag-S	Sp
taisteal	taisteal	taistil-N	Nv
timpeall	timpeall	timpeall-S	Sp
an	an	an-T	Td-s
domhain	domhain	domhan-N	Ncmsg
ar nós	ar nós	ar_nós-S	Spc
na	na	na-T	Tdfsg
gaoithe	gaoithe	gaoth-N	Ncfsg
.	.	.-F	Fe
Fuair	Fuair	faigh-V	Vmis
gach	gach	gach-D	Dq
uile	uile	uile-N	Ns-s|Dq
pháiste	pháiste	páiste-N	Ncmsc|Ncmsg
bronntanas	bronntanas	bronntanas-N	Ncmpg|Ncmsc
seachas	seachas	seachas-S	Sp
aon	aon	aon-M	Mc
chailín	chailín	cailín-N	Ncmsc
amháin	amháin	amháin-A	Aqp
.	.	.-F	Fe
Cérbh	Cérbh	cé-W	W--q
í	í	í-P	Pp3fs
féin	féin	féin-P	Px
?	?	?-F	Fq
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
ceart	ceart	ceart-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
agat	agat	ag-P	Pr2-s
–	–	–-X	Xx
Máire	Máire	Máire-N	Npfsc
,	,	,-F	Fi
an	an	an-T	Td-s
cailín	cailín	cailín-N	Ncmsg|Ncmsc
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhág	fhág	fág-V	Vmis
Mailí	Mailí	Mailí-N	Npfsc
go	go	go-U	Ua
huaigneach	huaigneach	uaigneach-A	Aqp
ocrach	ocrach	ocrach-A	Aqp
i lár	i lár	i_lár-S	Spc
na	na	na-T	Tdfsg
cathrach	cathrach	cathair-N	Ncfsg
an	an	an-T	Td-s
oíche	oíche	oíche-N	Ncfsc
úd	úd	úd-D	Dd
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
post	post	post-N	Ncmsc
ag	ag	ag-S	Sp
Máire	Máire	Máire-N	Npfsc
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
Rúdolf	Rúdolf	Rúdolf-N	Npmsc
anois	anois	anois-R	Rt
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
tabhairt	tabhairt	tabhair-N	Nv
aire	aire	aire-N	Ncfsg|Ncmsg|Ncfsg
do	do	do-S	Sp
Shan	Shan	Shan-N	Npmsc
Nioclás	Nioclás	Nioclás-N	Npmsc
,	,	,-F	Fi
do	do	do-S	Sp
Mhailí	Mhailí	Mailí-N	Npfsc
agus	agus	agus-C	Cc
do	do	do-S	Sp
na	na	na-T	Td-p
sióga	sióga	sióg-N	Ncfpc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
orthu	orthu	ar-P	Pr3-p
na	na	na-T	Td-p
héadaí	héadaí	éadach-N	Ncmpc
a	a	a-U	U
ní	ní	nigh-N	Nv
,	,	,-F	Fi
na	na	na-T	Td-p
béilí	béilí	béile-N	Ncmpc
a	a	a-U	U
ullmhú	ullmhú	ullmhaigh-N	Nv
agus	agus	agus-C	Cc
na	na	na-T	Td-p
leapacha	leapacha	leaba-N	Ncfpc
a	a	a-U	U
chóiriú	chóiriú	cóirigh-N	Nv
ó	ó	ó-S	Sp
éirí	éirí	éirí-N	Ncmsc
go	go	go-S	Sp
luí	luí	luí-N	Ncmsc
na	na	na-T	Tdfsg
gréine	gréine	grian-N	Ncfsg
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
mór	mór	mór-A	Aqp
liom	liom	le-P	Pr1-s
dóibh	dóibh	do-P	Pr3-p
é	é	é-P	Pp3ms
!	!	!-F	Fe
IS	IS	is-W	Wp-i
TROM	TROM	trom-A	Aqp
AN	AN	an-T	Td-s
tUALACH	tUALACH	tualach-N	Ncmsc
AN	AN	an-T	Td-s
LEISCE	LEISCE	leisce-N	Ncfsc|Ncfsg
!	!	!-F	Fe
