‘	‘	‘-X	Xx
Rang	Rang	rang-N	Ncmsc
a	a	a-U	Um
Ceathair	Ceathair	ceathair-M	Mc
?	?	?-F	Fq
Ná	Ná	ná-Q	Qnm
habair	habair	abair-V	Vmm-2s-n
liom	liom	le-P	Pr1-s
gurb	gurb	is-W	Wpdi
iad	iad	iad-P	Pp3-p
Rang	Rang	rang-N	Ncmsc
a	a	a-U	Um
Ceathair	Ceathair	ceathair-M	Mc
atá	atá	bí-V	Vmip---r
agam	agam	ag-P	Pr1-s
i	i	i-S	Sp
mbliana	mbliana	bliain-N	Ncfpc
!	!	!-F	Fe
’	’	’-F	Fa
Phléasc	Phléasc	pléasc-V	Vmis
an	an	an-T	Td-s
Máistir	Máistir	Máistir-N	Npmsc
Ó	Ó	Ó-U	Up
Riain	Riain	Riain-N	Npmsc
amach	amach	amach-R	Rd
ag	ag	ag-S	Sp
caoineadh	caoineadh	caoin-N	Nv
.	.	.-F	Fe
Síos	Síos	síos-R	Rd
leis	leis	le-P	Pr3ms
ar	ar	is-W	Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
dhá	dhá	dó-M	Mc
ghlúin	ghlúin	glúin-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
!	!	!-F	Fe
Más	Más	má-C	Csw
é	é	é-P	Pp3ms
do	do	do-S	Sp
thoil	thoil	toil-N	Ncfsc
é	é	é-P	Pp3ms
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tabhair	Tabhair	tabhair-V	Vmm-2s
rang	rang	rang-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
eile	eile	eile-D	Dd
dom	dom	do-P	Pr1-s
seachas	seachas	seachas-S	Sp
Rang	Rang	rang-N	Ncmsc
a	a	a-U	Um
Ceathair	Ceathair	ceathair-M	Mc
!	!	!-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Faraor	Faraor	faraor-X	Xsc
caithfidh	caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
iad	iad	iad-P	Pp3-p
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
duit	duit	do-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
an	an	an-T	Td-s
dara	dara	dara-M	Mo
rogha	rogha	rogha-N	Ncfsc
agam	agam	ag-P	Pr1-s
!	!	!-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
tá	tá	bí-V	Vmip
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
sa	sa	i-S	Spa-s
rang	rang	rang-N	Ncmsc
sin	sin	sin-D	Dd
fiáin	fiáin	fiáin-A	Aqp
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
siad	siad	siad-P	Pp3-pn
dána	dána	dána-A	Aqp
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
siad	siad	siad-P	Pp3-pn
imithe	imithe	imigh-A	Av
ó	ó	ó-S	Sp
smacht	smacht	smacht-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Máistir	Máistir	Máistir-N	Npmsc
Ó	Ó	Ó-U	Up
Riain	Riain	Riain-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
é	é	é-P	Pp3ms
sin	sin	sin-P	Pd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
siad	siad	siad-P	Pp3-pn
an-chrosta	an-chrosta	crosta-A	Aqp
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
!	!	!-F	Fe
Is	Is	is-W	Wp-i
iad	iad	iad-P	Pp3-p
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
is	is	is-U	U
fiáine	fiáine	fiáin-A	Aqc
iad	iad	iad-P	Pp3-p
dá	dá	dá-C	Cs
raibh	raibh	bí-V	Vmis---d
riamh	riamh	riamh-R	Rg
againn	againn	ag-P	Pr1-p
sa	sa	i-S	Spa-s
scoil	scoil	scoil-N	Ncfsc
seo	seo	seo-D	Dd
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Máistir	Máistir	Máistir-N	Npmsc
Ó	Ó	Ó-U	Up
Riain	Riain	Riain-N	Npmsc
arís	arís	arís-R	Rg
,	,	,-F	Fi
‘	‘	‘-X	Xx
ní	ní	ní-Q	Qn
theastaíonn	theastaíonn	teastaigh-V	Vmip---n
uaim	uaim	uaim-N	Ncfsc
Rang	Rang	rang-N	Ncmsc
a	a	a-U	Um
Ceathair	Ceathair	ceathair-M	Mc
a	a	a-U	U
mhúineadh	mhúineadh	múin-N	Nv
i	i	i-S	Sp
mbliana	mbliana	bliain-N	Ncfpc
.	.	.-F	Fe
Iarr	Iarr	iarr-V	Vmis
ar	ar	ar-S	Sp
mhúinteoir	mhúinteoir	múinteoir-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
eile	eile	eile-D	Dd
é	é	é-P	Pp3ms
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
tar éis	tar éis	tar_éis-S	Spc
labhairt	labhairt	labhair-N	Nv
le	le	le-S	Sp
gach	gach	gach-D	Dq
múinteoir	múinteoir	múinteoir-N	Ncmsc
eile	eile	eile-D	Dd
cheana	cheana	cheana-R	Rg
féin	féin	féin-P	Px
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
níl	níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
acu	acu	ag-P	Pr3-p
sásta	sásta	sásta-A	Aqp
an	an	an-T	Td-s
rang	rang	rang-N	Ncmsc
sin	sin	sin-D	Dd
a	a	a-U	U
mhúineadh	mhúineadh	múin-N	Nv
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
níl	níl	bí-V	Vmip---n
mise	mise	mé-P	Pp1-s-e
sásta	sásta	sásta-A	Aqp
iad	iad	iad-P	Pp3-p
a	a	a-U	U
mhúineadh	mhúineadh	múin-N	Nv
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
oiread	oiread	oiread-N	Ns-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Máistir	Máistir	Máistir-N	Npmsc
Ó	Ó	Ó-U	Up
Riain	Riain	Riain-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cén	Cén	cé-D	Dw--s
fáth	fáth	fáth-N	Ncmsc
nach	nach	nach-Q	Qnr
bhfuil	bhfuil	bí-V	Vmip---n
aon	aon	aon-D	Dq
rogha	rogha	rogha-N	Ncfsc
agamsa	agamsa	ag-P	Pr1-s-e
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Crannchur	Crannchur	crannchur-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Chuir	Chuir	cuir-V	Vmis
mé	mé	mé-P	Pp1-s
ainm	ainm	ainm-N	Ncmsc
gach	gach	gach-D	Dq
múinteora	múinteora	múinteoir-N	Ncmsg
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
hata	hata	hata-N	Ncmsc
.	.	.-F	Fe
Dhún	Dhún	dún-V	Vmis
mé	mé	mé-P	Pp1-s
mo	mo	mo-D	Dp1-s
shúile	shúile	súil-N	Ncfpc
agus	agus	agus-C	Cc
tharraing	tharraing	tarraing-V	Vmis
mé	mé	mé-P	Pp1-s
ainm	ainm	ainm-N	Ncmsc
amháin	amháin	amháin-A	Aqp
amach	amach	amach-R	Rd
as	as	as-P	Pr3ms
.	.	.-F	Fe
Is	Is	is-W	Wp-i
é	é	é-P	Pp3ms
d	d	d-X	Xl
’	’	’-F	Fa
ainmse	ainmse	ainm-N	Ncmsc-e
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
amach	amach	amach-R	Rd
.	.	.-F	Fe
’	’	’-F	Fa
Phléasc	Phléasc	pléasc-V	Vmis
an	an	an-T	Td-s
Máistir	Máistir	Máistir-N	Npmsc
Ó	Ó	Ó-U	Up
Riain	Riain	Riain-N	Npmsc
amach	amach	amach-R	Rd
ag	ag	ag-S	Sp
caoineadh	caoineadh	caoin-N	Nv
arís	arís	arís-R	Rg
.	.	.-F	Fe
Shín	Shín	Sín-N	Npfsc
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsg
ciarsúr	ciarsúr	ciarsúr-N	Ncmpg|Ncmsc
chuige	chuige	chuig-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Triomaigh	Triomaigh	triomach-N	Ncmpc
do	do	do-S	Sp
shúile	shúile	súil-N	Ncfpc
anois	anois	anois-R	Rt
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
dhéanfadh	dhéanfadh	déan-V	Vmc
fear	fear	fear-N	Ncmsc
maith	maith	maith-A	Aq-msc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
síos	síos	síos-R	Rd
leat	leat	le-P	Pr2-s
go dtí	go dtí	go_dtí-S	Spc
do	do	do-D	Dp2-s
rang	rang	rang-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
shiúil	shiúil	siúil-V	Vmis
an	an	an-T	Td-s
Máistir	Máistir	Máistir-N	Npmsc
Ó	Ó	Ó-U	Up
Riain	Riain	Riain-N	Npmsc
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
rang	rang	rang-N	Ncmsc
bhí	bhí	bí-V	Vmis
Siobhán	Siobhán	Siobhán-N	Npfsc
agus	agus	agus-C	Cc
Aifric	Aifric	Aifric-N	Npmsc
ag	ag	ag-S	Sp
rince	rince	rinc-N	Nv
ar	ar	ar-S	Sp
bhord	bhord	bord-N	Ncmsc
an	an	an-T	Td-s
mhúinteora	mhúinteora	múinteoir-N	Ncmsg
.	.	.-F	Fe
Rince	Rince	rince-N	Ncmsc
áiféiseach	áiféiseach	áiféiseach-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Iad	Iad	iad-P	Pp3-p
ag	ag	ag-S	Sp
béicíl	béicíl	béicíl-N	Nv-----n
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
bualadh	bualadh	buail-N	Nv
in aghaidh	in aghaidh	in_aghaidh-S	Spc
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Suígí	Suígí	suigh-V	Vmm-2p
síos	síos	síos-R	Rd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
máistir	máistir	máistir-N	Ncmsc
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
thug	thug	tabhair-V	Vmis---n
siad	siad	siad-P	Pp3-pn
aon	aon	aon-N	Ncmsc
toradh	toradh	toradh-N	Ncmsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Seán	Seán	Seán-N	Npmsc
,	,	,-F	Fi
Niamh	Niamh	Niamh-N	Npfsc
agus	agus	agus-C	Cc
Liam	Liam	Liam-N	Npm-g|Npmsc|Npfsg
ag	ag	ag-S	Sp
imirt	imirt	imir-N	Nv
peile	peile	peil-N	Ncfsg
thíos	thíos	thíos-R	Rd
i mbun	i mbun	i_mbun-S	Spc
an	an	an-T	Td-s
tseomra	tseomra	seomra-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Éirígí	Éirígí	éirigh-V	Vmm-2p
as	as	as-P	Pr3ms
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
máistir	máistir	máistir-N	Ncmsc
leo	leo	le-P	Pr3-p
siúd	siúd	siúd-P	Pd
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
níor	níor	is-W	Ws-in
éirigh	éirigh	éirigh-V	Vmis
siad	siad	siad-P	Pp3-pn
as	as	as-P	Pr3ms
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
thug	thug	tabhair-V	Vmis---n
siad	siad	siad-P	Pp3-pn
aon	aon	aon-N	Ncmsc
toradh	toradh	toradh-N	Ncmsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Choinnigh	Choinnigh	Coinnigh-N	Npfsg
siad	siad	siad-P	Pp3-pn
orthu	orthu	ar-P	Pr3-p
ag	ag	ag-S	Sp
léim	léim	léim-N	Nv
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
ciceáil	ciceáil	ciceáil-N	Nv
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
screadach	screadach	scread-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Nóra	Nóra	Nóra-N	Npfsc
,	,	,-F	Fi
Aoife	Aoife	Aoife-N	Npfsc
agus	agus	agus-C	Cc
Síle	Síle	Síle-N	Ncfsg|Npf-g|Ncfsg|Ncfsc|Npfsc
ag	ag	ag-S	Sp
luascadh	luascadh	luasc-N	Nv
as	as	as-S	Sp
na	na	na-T	Td-p
dallóga	dallóga	dallóg-N	Ncfpc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
cúpla	cúpla	cúpla-D	Dq|Ncmsc
duine	duine	duine-N	Ncmsc|Ncmsg
ag	ag	ag-S	Sp
canadh	canadh	can-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
daoine	daoine	duine-N	Ncmpc
eile	eile	eile-D	Dd
ag	ag	ag-S	Sp
béicíl	béicíl	béicíl-N	Nv-----n
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
beirt	beirt	beirt-N	Ncfsc
ag	ag	ag-S	Sp
troid	troid	troid-N	Nv
i lár	i lár	i_lár-S	Spc
an	an	an-T	Td-s
urláir	urláir	urlár-N	Ncmsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Dónall	Dónall	Dónall-N	Npmsc
agus	agus	agus-C	Cc
Eoghan	Eoghan	Eoghan-N	Npmsg|Npmsc
ag	ag	ag-S	Sp
ithe	ithe	ith-N	Nv
lóin	lóin	lón-N	Ncmsg
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
ag	ag	ag-S	Sp
caitheamh	caitheamh	caith-N	Nv
píosaí	píosaí	píosa-N	Ncmpg
aráin	aráin	arán-N	Ncmsg
le	le	le-S	Sp
páistí	páistí	páiste-N	Ncmpc
eile	eile	eile-D	Dd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
duine	duine	duine-N	Ncmsc
nó	nó	nó-C	Cc
dhó	dhó	dó-M	Mc
á	á	do-S	Spo-p
gcaitheamh	gcaitheamh	caith-N	Nv
ar ais	ar ais	ar_ais-R	Rd
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bígí	Bígí	bí-V	Vmm-2p
ciúin	ciúin	ciúin-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Máistir	Máistir	Máistir-N	Npmsc
Ó	Ó	Ó-U	Up
Riain	Riain	Riain-N	Npmsc
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
chuala	chuala	clois-V	Vmis
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
é	é	é-P	Pp3ms
nó	nó	nó-C	Cc
má	má	má-C	Cs
chuala	chuala	clois-V	Vmis
níor	níor	níor-Q	Qn-s
thug	thug	tabhair-V	Vmis---n
siad	siad	siad-P	Pp3-pn
aon	aon	aon-N	Ncmsc
toradh	toradh	toradh-N	Ncmsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bígí	Bígí	bí-V	Vmm-2p
ciúin	ciúin	ciúin-A	Aqp
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
máistir	máistir	máistir-N	Ncmsc
arís	arís	arís-R	Rg
de	de	de-S	Sp
bhéic	bhéic	béic-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bígí	Bígí	bí-V	Vmm-2p
ciúin	ciúin	ciúin-A	Aqp
,	,	,-F	Fi
más	más	má-C	Csw
é	é	é-P	Pp3ms
bhur	bhur	bhur-D	Dp2-p
dtoil	dtoil	toil-N	Ncfsc
é	é	é-P	Pp3ms
!	!	!-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
tú	tú	tú-P	Pp2-s
an	an	an-T	Td-s
fód	fód	fód-N	Ncmsc
a	a	a-U	U
sheasamh	sheasamh	seas-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
a	a	a-D	Dp3
bhean	bhean	bean-N	Ncfsc
chéile	chéile	céile-N	Ncmsg
leis	leis	le-S	Sp
an	an	an-T	Td-s
oíche	oíche	oíche-N	Ncfsc
sin	sin	sin-D	Dd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
tú	tú	tú-P	Pp2-s
a	a	a-U	U
thaispeáint	thaispeáint	taispeáin-N	Nv
dóibh	dóibh	do-P	Pr3-p
cé	cé	cé-N	Ncfsc
atá	atá	bí-V	Vmip---r
i	i	i-S	Sp
gceannas	gceannas	ceannas-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Sin	Sin	sin-W	W
í	í	í-P	Pp3fs
an	an	an-T	Td-s
deacracht	deacracht	deacracht-N	Ncfsc
atá	atá	bí-V	Vmip---r
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
máistir	máistir	máistir-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
go	go	go-U	Ua
maith	maith	maith-A	Aqp
cé	cé	cé-N	Ncfsg|Cs|Ncfsc
atá	atá	bí-V	Vmip---r
i	i	i-S	Sp
gceannas	gceannas	ceannas-N	Ncmsc
.	.	.-F	Fe
Na	Na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
!	!	!-F	Fe
Agus	Agus	agus-C	Cc
tá	tá	bí-V	Vmip
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
acusan	acusan	ag-P	Pr3-p-e
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
.	.	.-F	Fe
’	’	’-F	Fa
Maidin	Maidin	maidin-N	Ncfsc
lá	lá	lá-N	Ncmsc
arna	arna	arna-S	Spc
mhárach	mhárach	márach-N	Ns-s
chuir	chuir	cur-N	Ncmsg
an	an	an-T	Td-s
máistir	máistir	máistir-N	Ncmsg
air	air	ar-P	Pr3ms
a	a	a-D	Dp3
chlogad	chlogad	clogad-N	Ncmsc
.	.	.-F	Fe
Rug	Rug	beir-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
chamán	chamán	camán-N	Ncmsc
agus	agus	agus-C	Cc
amach	amach	amach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
shroich	shroich	sroich-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
scoil	scoil	scoil-N	Ncfsc
stop	stop	stop-V	Vmis
sé	sé	sé-P	Pp3msn
ar feadh	ar feadh	ar_feadh-S	Spc
nóiméid	nóiméid	nóiméad-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
fód	fód	fód-N	Ncmsc
a	a	a-U	U
sheasamh	sheasamh	seas-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
a	a	a-U	U
thaispeáint	thaispeáint	taispeáin-N	Nv
do	do	do-S	Sp
na	na	na-T	Td-p
bithiúnaigh	bithiúnaigh	bithiúnach-N	Ncmpc
bheaga	bheaga	beag-A	Aq--pc
seo	seo	seo-D	Dd
cé	cé	cé-C	Cs|Ncfsc
atá	atá	bí-V	Vmip---r
i	i	i-S	Sp
gceannas	gceannas	ceannas-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
Síos	Síos	síos-R	Rd
leis	leis	le-P	Pr3ms
go dtí	go dtí	go_dtí-S	Spc
seomra	seomra	seomra-N	Ncmsc
Rang	Rang	rang-N	Ncmsc
a	a	a-U	Um
Ceathair	Ceathair	ceathair-M	Mc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
chath	chath	cath-N	Ncmsc
idir	idir	idir-S	Sp
na	na	na-T	Td-p
buachaillí	buachaillí	buachaill-N	Ncmpc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
cailíní	cailíní	cailín-N	Ncmpc
.	.	.-F	Fe
Cístí	Cístí	císte-N	Ncmpc
beaga	beaga	beag-A	Aq--pc
agus	agus	agus-C	Cc
ceapairí	ceapairí	ceapaire-N	Ncmpg|Ncmpc
á	á	do-S	Spo-s
gcaitheamh	gcaitheamh	caith-N	Nv
acu	acu	ag-P	Pr3-p
lena	lena	le-S	Spp-s
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Bhuail	Bhuail	buail-V	Vmis
an	an	an-T	Td-s
Máistir	Máistir	Máistir-N	Npmsc
Ó	Ó	Ó-U	Up
Riain	Riain	Riain-N	Npmsc
a	a	a-D	Dp3
chamán	chamán	camán-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbord	mbord	bord-N	Ncmsc
.	.	.-F	Fe
Stop	Stop	stop-V	Vmis|Vmm-2s|Ncmsc
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
siad	siad	siad-P	Pp3-pn
an	an	an-T	Td-s
torann	torann	torann-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Éirígí	Éirígí	éirigh-V	Vmm-2p
as	as	as-P	Pr3ms
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
máistir	máistir	máistir-N	Ncmsc
de	de	de-S	Sp
bhéic	bhéic	béic-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Éirígí	Éirígí	éirigh-V	Vmm-2p
as	as	as-P	Pr3ms
a	a	a-Q	Q-r
deirim	deirim	abair-V	Vmip1s
!	!	!-F	Fe
’	’	’-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
máistir	máistir	máistir-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
rang	rang	rang-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
ciúin	ciúin	ciúin-A	Aq-msc
,	,	,-F	Fi
iad	iad	iad-P	Pp3-p
go	go	go-U	Ua
léir	léir	léir-A	Aqp
ag	ag	ag-S	Sp
féachaint	féachaint	féach-N	Nv
ar	ar	ar-S	Sp
chailín	chailín	cailín-N	Ncmsc
beag	beag	beag-A	Aq-msc
darbh	darbh	dar-W	Wpsi|Csws
ainm	ainm	ainm-N	Ncmsc
Niamh	Niamh	Niamh-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	a-U	Um
haon	haon	aon-M	Mc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Niamh	Niamh	Niamh-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	a-U	Um
haon	haon	aon-M	Mc
,	,	,-F	Fi
a	a	a-U	Um
dó	dó	dó-M	Mc
,	,	,-F	Fi
a	a	a-U	Um
trí	trí	trí-M	Mc
!	!	!-F	Fe
A	A	a-U	U|Dp3
…	…	…-F	Fi
nois	nois	nois-N	Ncfsc
!	!	!-F	Fe
’	’	’-F	Fa
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
caitheadh	caitheadh	caith-V	Vmis0
ceapairí	ceapairí	ceapaire-N	Ncmpc
,	,	,-F	Fi
boiscíní	boiscíní	boiscín-N	Ncmpc
bainne	bainne	bainne-N	Ncmsg|Ncmsc
agus	agus	agus-C	Cc
cístí	cístí	císte-N	Ncmpc
beaga	beaga	beag-A	Aq--pc
de	de	de-S	Sp
gach	gach	gach-D	Dq
sórt	sórt	sórt-N	Ncmsc
san	san	sin-S	Spa-s|Pd
aer	aer	aer-N	Ncmpg|Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmm-2s
leis	leis	le-S	Sp
an	an	an-T	Td-s
máistir	máistir	máistir-N	Ncmsc
cúpla	cúpla	cúpla-N	Ncmsg|Ncmsc|Dq
ceann	ceann	ceann-N	Ncmpg|Ncmsc
acu	acu	ag-P	Pr3-p
a	a	a-U	U
stopadh	stopadh	stop-N	Nv
lena	lena	le-S	Spp-s
chamán	chamán	camán-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhuail	bhuail	buail-V	Vmis
cúpla	cúpla	cúpla-D	Dq|Ncmsc
ceann	ceann	ceann-N	Ncmpg|Ncmsc
eile	eile	eile-D	Dd
sa	sa	i-S	Spa-s
chloigeann	chloigeann	cloigeann-N	Ncmsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Phléasc	Phléasc	pléasc-V	Vmis
boiscín	boiscín	boiscín-N	Ncmsc
amháin	amháin	amháin-A	Aqp
bainne	bainne	bainne-N	Ncmsg|Ncmsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
sheaicéad	sheaicéad	seaicéad-N	Ncmsc
.	.	.-F	Fe
Taobh	Taobh	taobh-N	Ncmsc
istigh	istigh	istigh-R	Rl
de	de	de-S	Sp
dhá	dhá	dó-M	Mc
nóiméad	nóiméad	nóiméad-N	Ncmsc
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
bocht	bocht	bocht-A	Aq-msc
clúdaithe	clúdaithe	clúdaigh-A	Av
le	le	le-S	Sp
huachtar	huachtar	uachtar-N	Ncmsc
,	,	,-F	Fi
le	le	le-S	Sp
bainne	bainne	bainne-N	Ncmsc
agus	agus	agus-C	Cc
le	le	le-S	Sp
seacláid	seacláid	seacláid-N	Ncfsc
.	.	.-F	Fe
Bhailigh	Bhailigh	bailigh-V	Vmis
an	an	an-T	Td-s
máistir	máistir	máistir-N	Ncmsc
suas	suas	suas-R	Rd
a	a	a-D	Dp3
chuid	chuid	cuid-N	Ncfsc
leabhar	leabhar	leabhar-N	Ncmsc
.	.	.-F	Fe
Chaith	Chaith	caith-V	Vmis
sé	sé	sé-P	Pp3msn
isteach	isteach	isteach-R	Rd
ina	ina	i-S	Spp-s
mhála	mhála	mála-N	Ncmsc
iad	iad	iad-P	Pp3-p
.	.	.-F	Fe
Rith	Rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
amach	amach	amach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
Suas	Suas	suas-R	Rd
leis	leis	le-P	Pr3ms
go dtí	go dtí	go_dtí-S	Spc
oifig	oifig	oifig-N	Ncfsc
an	an	an-T	Td-s
phríomhoide	phríomhoide	príomhoide-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Táimse	Táimse	bí-V	Vmip1s--e
ag	ag	ag-S	Sp
imeacht	imeacht	imigh-N	Nv
anois	anois	anois-R	Rt
díreach	díreach	díreach-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	Ní-W	Wp-in|Up
múinteoir	múinteoir	múinteoir-N	Ncmsc
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
uait	uait	ó-P	Pr2-s
don	don	do-S	Spa-s
rang	rang	rang-N	Ncmsc
sin	sin	sin-D	Dd
ach	ach	ach-S	Sp
saighdiúir	saighdiúir	saighdiúir-N	Ncmsc
!	!	!-F	Fe
’	’	’-F	Fa
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
chas	chas	cas-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
shála	shála	sáil-N	Ncfpc
agus	agus	agus-C	Cc
bhailigh	bhailigh	bailigh-V	Vmis
sé	sé	sé-P	Pp3msn
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
chas	chas	cas-V	Vmis
sé	sé	sé-P	Pp3msn
timpeall	timpeall	timpeall-R	Rd|Ncmsc
agus	agus	agus-C	Cc
labhair	labhair	labhair-V	Vmis
sé	sé	sé-P	Pp3msn
arís	arís	arís-R	Rg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
ea	ea	ea-P	Pp3-s
,	,	,-F	Fi
saighdiúir	saighdiúir	saighdiúir-N	Ncmsc
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
uait	uait	ó-P	Pr2-s
.	.	.-F	Fe
Saighdiúir	Saighdiúir	saighdiúir-N	Ncmsc
mór	mór	mór-A	Aq-msc
groí	groí	groí-A	Aqp
a	a	a-Q	Q-i
mbeadh	mbeadh	bí-V	Vmc
gunna	gunna	gunna-N	Ncmsc
aige	aige	ag-P	Pr3ms
!	!	!-F	Fe
’	’	’-F	Fa
Tharraing	Tharraing	tarraing-V	Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
píosa	píosa	píosa-N	Ncmsg|Ncmsc
páipéir	páipéir	páipéar-N	Ncmsg
chuige	chuige	chuig-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
fógra	fógra	fógra-N	Ncmsc
a	a	a-U	U
chur	chur	cuir-N	Nv
sa	sa	i-S	Spa-s
pháipéar	pháipéar	páipéar-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
scríobh	scríobh	scríobh-N	Nv
.	.	.-F	Fe
Múinteoir	Múinteoir	múinteoir-N	Ncmsc
de	de	de-S	Sp
dhíth	dhíth	díth-N	Ncfsc
ar	ar	ar-S	Sp
rang	rang	rang-N	Ncmsc
álainn	álainn	álainn-A	Aq-msc
ciúin	ciúin	ciúin-A	Aq-msc
séimh	séimh	séimh-A	Aq-msc
i	i	i-S	Sp
Scoil	Scoil	scoil-N	Ncfsc
Mhuire	Mhuire	Muire-N	Ncfsg|Npfsg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-N	Ncmsc|Sp
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
scríofa	scríofa	scríobh-A	Av
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
rinne	rinne	déan-V	Vmis
sé	sé	sé-P	Pp3msn
liathróidín	liathróidín	liathróidín-N	Ncmsc
bheag	bheag	beag-A	Aq-msc
den	den	de-S	Spa-s
pháipéar	pháipéar	páipéar-N	Ncmsc
agus	agus	agus-C	Cc
chaith	chaith	caith-V	Vmis
sé	sé	sé-P	Pp3msn
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
bhosca	bhosca	bosca-N	Ncmsc
bruscair	bruscair	bruscar-N	Ncmsg|Ncmpc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
tharraing	tharraing	tarraing-V	Vmis
sé	sé	sé-P	Pp3msn
píosa	píosa	píosa-N	Ncmsc
eile	eile	eile-D	Dd
páipéir	páipéir	páipéar-N	Ncmpc
chuige	chuige	chuig-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
Múinteoir	Múinteoir	múinteoir-N	Ncmsc
de	de	de-S	Sp
dhíth	dhíth	díth-N	Ncfsc
ar	ar	ar-S	Sp
rang	rang	rang-N	Ncmsc
dúshlánach	dúshlánach	dúshlánach-A	Aq-msc
Stop	Stop	stop-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
chuirfeadh	chuirfeadh	cuir-V	Vmc----n
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
isteach	isteach	isteach-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bpost	bpost	post-N	Ncmsc
sin	sin	sin-D	Dd
!	!	!-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
tharraing	tharraing	tarraing-V	Vmis
sé	sé	sé-P	Pp3msn
píosa	píosa	píosa-N	Ncmsc
eile	eile	eile-D	Dd
páipéir	páipéir	páipéar-N	Ncmpc
chuige	chuige	chuig-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
scríobh	scríobh	scríobh-N	Nv
arís	arís	arís-R	Rg
.	.	.-F	Fe
Múinteoir	Múinteoir	múinteoir-N	Ncmsc
de	de	de-S	Sp
dhíth	dhíth	díth-N	Ncfsc
ar	ar	ar-S	Sp
Rang	Rang	rang-N	Ncmsc
a	a	a-U	Um
Ceathair	Ceathair	ceathair-M	Mc
i	i	i-S	Sp
Scoil	Scoil	scoil-N	Ncfsc
Mhuire	Mhuire	Muire-N	Ncfsg|Npfsg
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
an	an	an-T	Td-s
fógra	fógra	fógra-N	Ncmsg|Ncmsc
sin	sin	sin-D	Dd
sa	sa	i-S	Spa-s
pháipéar	pháipéar	páipéar-N	Ncmsc
.	.	.-F	Fe
Triúr	Triúr	triúr-N	Ncmsc
a	a	a-Q	Q-r
chuir	chuir	cuir-V	Vmis
isteach	isteach	isteach-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bpost	bpost	post-N	Ncmsc
.	.	.-F	Fe
An	An	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
agus	agus	agus-C	Cc
beirt	beirt	beirt-N	Ncfsc
eile	eile	eile-D	Dd
a	a	a-Q	Q-r
chuir	chuir	cuir-V	Vmis
an	an	an-T	Td-s
triúr	triúr	triúr-N	Ncmsc
faoi	faoi	faoi-S	Sp
agallamh	agallamh	agallamh-N	Ncmsc
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
an	an	an-T	Td-s
chéad	chéad	céad-M	Mo
duine	duine	duine-N	Ncmsc
acu	acu	ag-P	Pr3-p
isteach	isteach	isteach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
Síle	Síle	Síle-N	Npfsc|Ncfsc
Ní	Ní	Ní-U	Up
Fhathaigh	Fhathaigh	Fathaigh-N	Npfsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Bean	Bean	bean-N	Ncfsc
óg	óg	óg-A	Aq-fsv|Aq-fsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
inti	inti	i-P	Pr3fs
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
beag	beag	beag-N	Ncmsc|Aqp
tanaí	tanaí	tanaí-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
chuma	chuma	cuma-N	Ncfsc
uirthi	uirthi	ar-P	Pr3fs
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
an-chiúin	an-chiúin	ciúin-A	Aqp
agus	agus	agus-C	Cc
cúthail	cúthail	cúthail-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
raibh	raibh	bí-V	Vmis---d
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
múineadh	múineadh	múin-N	Nv
roimhe	roimhe	roimh-P	Pr3ms
seo	seo	seo-P	Pd
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
é	é	é-P	Pp3ms
seo	seo	seo-P	Pd
mo	mo	mo-D	Dp1-s
chéad	chéad	céad-N	Ncmsc|Mc
phost	phost	post-N	Ncmpg|Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
mé	mé	mé-P	Pp1-s
ach	ach	ach-C	Cs
tar éis	tar éis	tar_éis-S	Spc
críochnú	críochnú	críochnaigh-N	Nv
sa	sa	i-S	Spa-s
choláiste	choláiste	coláiste-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
maith	maith	maith-N	Ncfsc
agat	agat	ag-P	Pr2-s
as	as	as-S	Sp
ucht	ucht	ucht-N	Ncmsc
teacht	teacht	tar-N	Ncmsc|Nv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cuirfidh	Cuirfidh	cuir-V	Vmif
mé	mé	mé-P	Pp1-s
glaoch	glaoch	glaoigh-N	Ncmsc|Nv
ort	ort	ar-P	Pr2-s
sula	sula	sula-C	Cs
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Slán	Slán	slán-N	Ncmsc
libh	libh	le-P	Pr2-p
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Síle	Síle	Síle-N	Ncfsc|Npfsc
Ní	Ní	Ní-U	Up
Fhathaigh	Fhathaigh	Fathaigh-N	Npfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
sheasfadh	sheasfadh	seas-V	Vmc----n
sí	sí	sí-P	Pp3fsn
siúd	siúd	siúd-P	Pd
fiú	fiú	fiú-N	Ns-s|Ncmsc|Rg
cúig	cúig	cúig-N	Ncmsg|Ncmsc|Mc
nóiméad	nóiméad	nóiméad-N	Ncmsc|Ncmpg
i	i	i-S	Sp
Rang	Rang	rang-N	Ncmsc
a	a	a-U	Um
Ceathair	Ceathair	ceathair-M	Mc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbeirt	mbeirt	beirt-N	Ncfsc
bhan	bhan	bean-N	Ncfpg
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Síle	Síle	Síle-N	Ncfsc|Npfsc
imithe	imithe	imigh-A	Av
amach	amach	amach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
ceart	ceart	ceart-N	Ncmsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
bean	bean	bean-N	Ncfsc
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Dhéanfaidís	Dhéanfaidís	déan-V	Vmc-3p
óinseach	óinseach	óinseach-N	Ncfsc
cheart	cheart	ceart-A	Aq-fsc
di	di	do-P	Pr3fs
.	.	.-F	Fe
’	’	’-F	Fa
Tháinig	Tháinig	tar-V	Vmis
an	an	an-T	Td-s
dara	dara	dara-M	Mo
duine	duine	duine-N	Ncmsc
isteach	isteach	isteach-R	Rd
.	.	.-F	Fe
Úna	Úna	Úna-N	Npfsc
Bean	Bean	bean-N	Ncfsc
Uí	Uí	Uí-U	Up
Chatháin	Chatháin	Catháin-N	Npfsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Bean	Bean	bean-N	Ncfsc
ard	ard	ard-A	Aq-fsv|Aq-fsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
inti	inti	i-P	Pr3fs
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
go leor	go leor	go_leor-A	Aq|Ns-s|Rg
taithí	taithí	taithigh-N	Ncfsg|Nv--g
múinteoireachta	múinteoireachta	múinteoireacht-N	Ncfsg
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
bhan	bhan	bean-N	Ncfpg
cuid	cuid	cuid-N	Ncfsc
mhaith	mhaith	maith-A	Aq-fsc
ceisteanna	ceisteanna	ceist-N	Ncfpg
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
B	B	B-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbeirt	mbeirt	beirt-N	Ncfsc
bhan	bhan	bean-N	Ncfpg
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Úna	Úna	Úna-N	Npfsc
imithe	imithe	imigh-A	Av
amach	amach	amach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
B	B	B-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
go	go	go-Q	Q
ndéanfadh	ndéanfadh	déan-V	Vmc
sí	sí	sí-P	Pp3fsn
siúd	siúd	siúd-P	Pd
an	an	an-T	Td-s
gnó	gnó	gnó-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
B	B	B-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
go	go	go-Q	Q
ndéanfadh	ndéanfadh	déan-V	Vmc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
bhan	bhan	bean-N	Ncfpg
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
an	an	an-T	Td-s
tríú	tríú	trí-M	Mo
duine	duine	duine-N	Ncmsc
isteach	isteach	isteach-R	Rd
.	.	.-F	Fe
Eoghan	Eoghan	Eoghan-N	Npmsc
Mac	Mac	Mac-U	Up
Donnchadha	Donnchadha	Donnchadha-N	Np
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Fear	Fear	fear-N	Ncmsc
mór	mór	mór-A	Aq-msc
láidir	láidir	láidir-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
agus	agus	agus-C	Cc
é	é	éigh-V	Vmsp---n
sé	sé	sé-P	Pp3msn
troithe	troithe	troigh-N	Ncfpc
ar	ar	ar-S	Sp
airde	airde	airde-N	Ncfpc|Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
guaillí	guaillí	gualainn-N	Ncfpc
móra	móra	mór-A	Aq--pc
leathana	leathana	leathan-A	Aq--pc
air	air	ar-P	Pr3ms
agus	agus	agus-C	Cc
lámha	lámha	lámh-N	Ncfpc
móra	móra	mór-A	Aq--pc
millteanacha	millteanacha	millteanach-A	Aq--pg|Aq--pc|Aq--pv
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
chuir	chuir	cuir-V	Vmis---n
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
t-aon	t-aon	aon-M	Mc
cheist	cheist	ceist-N	Ncfsc
amháin	amháin	amháin-A	Aqp
air	air	ar-P	Pr3ms
:	:	:-F	Fi
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhféadfá	bhféadfá	féad-V	Vmc-2s
tosú	tosú	tosú-N	Ncmsc
amárach	amárach	amárach-A	Aqp
?	?	?-F	Fq
’	’	’-F	Fa
Maidin	Maidin	maidin-N	Ncfsc
lá	lá	lá-N	Ncmsc
arna	arna	arna-S	Spc
mhárach	mhárach	márach-N	Ns-s
shiúil	shiúil	siúl-N	Ncmsg
an	an	an-T	Td-s
Máistir	Máistir	Máistir-N	Npmsg
Mac	Mac	Mac-U	Up
Donnchadha	Donnchadha	Donnchadha-N	Np
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
seomra	seomra	seomra-N	Ncmsc
Rang	Rang	rang-N	Ncmsc
a	a	a-U	Um
Ceathair	Ceathair	ceathair-M	Mc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
chíréib	chíréib	círéib-N	Ncfsc
sa	sa	i-S	Spa-s
seomra	seomra	seomra-N	Ncmsc
céanna	céanna	céanna-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Suígí	Suígí	suigh-V	Vmm-2p
síos	síos	síos-R	Rd
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
de	de	de-S	Sp
bhéic	bhéic	béic-N	Ncfsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Chaoch	Chaoch	caoch-V	Vmis
cúpla	cúpla	cúpla-D	Dq|Ncmsc
duine	duine	duine-N	Ncmsc|Ncmsg
acu	acu	ag-P	Pr3-p
súil	súil	súil-N	Ncfsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
shuigh	shuigh	suigh-V	Vmis
siad	siad	siad-P	Pp3-pn
síos	síos	síos-R	Rd
go	go	go-U	Ua
ciúin	ciúin	ciúin-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
ag	ag	ag-S	Sp
éisteacht	éisteacht	éist-N	Nv
taobh amuigh	taobh amuigh	taobh_amuigh-R	Rl
den	den	de-S	Spa-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
go	go	go-U	Ua
maith	maith	maith-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
go	go	go-U	Ua
sásta	sásta	sásta-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Déanfaidh	Déanfaidh	déan-V	Vmif
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
seo	seo	seo-D	Dd
an	an	an-T	Td-s
gnó	gnó	gnó-N	Ncmsg|Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
Ar ais	Ar ais	ar_ais-R	Rd
leis	leis	le-P	Pr3ms
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
oifig	oifig	oifig-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Matamaitic	Matamaitic	matamaitic-N	Ncfsc
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Máistir	Máistir	Máistir-N	Npmsc
Mac	Mac	Mac-U	Up
Donnchadha	Donnchadha	Donnchadha-N	Np
leis	leis	le-S	Sp
an	an	an-T	Td-s
rang	rang	rang-N	Ncmsc
de	de	de-S	Sp
bhéic	bhéic	béic-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tógaigí	Tógaigí	tóg-V	Vmm-2p
amach	amach	amach-R	Rd
na	na	na-T	Td-p
leabhair	leabhair	leabhar-N	Ncmpc
mhatamaitice	mhatamaitice	matamaitic-N	Ncfsg
.	.	.-F	Fe
’	’	’-F	Fa
Thóg	Thóg	tóg-V	Vmis
gach	gach	gach-D	Dq
duine	duine	duine-N	Ncmsc
amach	amach	amach-R	Rd
a	a	a-D	Dp3
leabhar	leabhar	leabhar-N	Ncmsc
matamaitice	matamaitice	matamaitic-N	Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cóipleabhair	Cóipleabhair	cóipleabhar-N	Ncmpc
anois	anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
máistir	máistir	máistir-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tógaigí	Tógaigí	tóg-V	Vmm-2p
amach	amach	amach-R	Rd
na	na	na-T	Td-p
cóipleabhair	cóipleabhair	cóipleabhar-N	Ncmpc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
na	na	na-T	Td-p
pinn	pinn	peann-N	Ncmpc
luaidhe	luaidhe	luaidhe-N	Ncfsg|Ncfsc|Ncfsg
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
.	.	.-F	Fe
’	’	’-F	Fa
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
rang	rang	rang-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
ciúin	ciúin	ciúin-A	Aq-msc
,	,	,-F	Fi
iad	iad	iad-P	Pp3-p
go	go	go-U	Ua
léir	léir	léir-A	Aqp
ag	ag	ag-S	Sp
féachaint	féachaint	féach-N	Nv
ar	ar	ar-S	Sp
bhuachaill	bhuachaill	buachaill-N	Ncmsc
beag	beag	beag-A	Aq-msc
darbh	darbh	dar-W	Wpsi|Csws
ainm	ainm	ainm-N	Ncmsc
Rónán	Rónán	Rónán-N	Npmsc
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
Rónán	Rónán	Rónán-N	Npmsc
ag	ag	ag-S	Sp
comhaireamh	comhaireamh	comhair-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	a-U	Um
haon	haon	aon-M	Mc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Rónan	Rónan	Rónan-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	a-U	Um
haon	haon	aon-M	Mc
,	,	,-F	Fi
a	a	a-U	Um
dó	dó	dó-M	Mc
,	,	,-F	Fi
a	a	a-U	Um
trí	trí	trí-M	Mc
!	!	!-F	Fe
A	A	a-U	U|Dp3
…	…	…-F	Fi
nois	nois	nois-N	Ncfsc
!	!	!-F	Fe
’	’	’-F	Fa
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
caitheadh	caitheadh	caith-V	Vmis0
leabhair	leabhair	leabhar-N	Ncmpc
san	san	sin-S	Spa-s|Pd
aer	aer	aer-N	Ncmpg|Ncmsc
.	.	.-F	Fe
Caitheadh	Caitheadh	caith-V	Vmis0
cóipleabhair	cóipleabhair	cóipleabhar-N	Ncmpc
san	san	sin-S	Spa-s|Pd
aer	aer	aer-N	Ncmpg|Ncmsc
.	.	.-F	Fe
Caitheadh	Caitheadh	caith-V	Vmis0
pinn	pinn	peann-N	Ncmpc
de	de	de-S	Sp
gach	gach	gach-D	Dq
sórt	sórt	sórt-N	Ncmsc
san	san	sin-S	Spa-s|Pd
aer	aer	aer-N	Ncmpg|Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
chlogad	chlogad	clogad-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
Máistir	Máistir	Máistir-N	Npmsc
Mac	Mac	Mac-U	Up
Donnchadha	Donnchadha	Donnchadha-N	Np
bocht	bocht	bocht-N	Ncmpg|Ncmsc
.	.	.-F	Fe
Buaileadh	Buaileadh	buail-V	Vmis0
sa	sa	i-S	Spa-s
chloigeann	chloigeann	cloigeann-N	Ncmsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Buaileadh	Buaileadh	buail-V	Vmis0
san	san	i-S	Spa-s
éadan	éadan	éadan-N	Ncmsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Buaileadh	Buaileadh	buail-V	Vmis0
ar	ar	ar-S	Sp
na	na	na-T	Td-p
guaillí	guaillí	gualainn-N	Ncfpc
,	,	,-F	Fi
sa	sa	i-S	Spa-s
mhuineál	mhuineál	muineál-N	Ncmsc
agus	agus	agus-C	Cc
ar	ar	ar-S	Sp
na	na	na-T	Td-p
cosa	cosa	cos-N	Ncfpc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
áit	áit	áit-N	Ncfsc
nár	nár	nár-Q	Qnrs
buaileadh	buaileadh	buail-V	Vmis0--n
é	é	é-P	Pp3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
beirt	beirt	beirt-N	Ncfsc
pháistí	pháistí	páiste-N	Ncmpc
sa	sa	i-S	Spa-s
rang	rang	rang-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
freagrach	freagrach	freagrach-A	Aqp
as	as	as-S	Sp
na	na	na-T	Td-p
cóipleabhair	cóipleabhair	cóipleabhar-N	Ncmpc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
leabhair	leabhair	leabhar-N	Ncmpc
a	a	a-U	U
bhailiú	bhailiú	bailigh-N	Nv
ionas	ionas	ionas-N	Ns-s
nach	nach	nach-Q	Qnr
mbeadh	mbeadh	bí-V	Vmc
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
eile	eile	eile-D	Dd
gann	gann	gann-A	Aqp
ar	ar	ar-S	Sp
armlón	armlón	armlón-N	Ncmsc
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
acu	acu	ag-P	Pr3-p
seo	seo	seo-P	Pd
ag	ag	ag-S	Sp
cosa	cosa	cos-N	Ncfpc
an	an	an-T	Td-s
mháistir	mháistir	máistir-N	Ncmsg
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
dhá	dhá	dó-M	Mc
mhadra	mhadra	madra-N	Ncmsc
bheaga	bheaga	beag-A	Aq--pc
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Leabhair	Leabhair	leabhar-N	Ncmpc
agus	agus	agus-C	Cc
pinn	pinn	peann-N	Ncmpc
agus	agus	agus-C	Cc
cóipleabhair	cóipleabhair	cóipleabhar-N	Ncmsg|Ncmpc
á	á	do-S	Spo-s
mbailiú	mbailiú	bailigh-N	Nv
acu	acu	ag-P	Pr3-p
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
ag	ag	ag-S	Sp
rith	rith	rith-N	Nv
síos	síos	síos-R	Rd
suas	suas	suas-R	Rd
ag	ag	ag-S	Sp
tabhairt	tabhairt	tabhair-N	Nv
an	an	an-T	Td-s
armlóin	armlóin	armlón-N	Ncmsg
ar ais	ar ais	ar_ais-R	Rd
do	do	do-S	Sp
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
eile	eile	eile-D	Dd
.	.	.-F	Fe
Lean	Lean	Lean-N	Npmsc
an	an	an-T	Td-s
t-ionsaí	t-ionsaí	ionsaí-N	Ncmsc
fíochmhar	fíochmhar	fíochmhar-A	Aq-msc
ar	ar	ar-S	Sp
aghaidh	aghaidh	aghaidh-N	Ncfsc
.	.	.-F	Fe
Ar	Ar	is-N	Ncmsc|Sp|Wssi|Q-is|Wpsi
deireadh	deireadh	deireadh-V	Vmih|Ncmsc
thiar	thiar	thiar-R	Rd
thall	thall	tall-V	Vmis
d	d	d-X	Xl
’	’	’-F	Fa
éalaigh	éalaigh	éalaigh-V	Vmm-2s
an	an	an-T	Td-s
Máistir	Máistir	Máistir-N	Npmsc
Mac	Mac	Mac-U	Up
Donnchadha	Donnchadha	Donnchadha-N	Np
leis	leis	le-P	Pr3ms
isteach	isteach	isteach-R	Rd
faoin	faoin	faoi-S	Spa-s
mbord	mbord	bord-N	Ncmsc
.	.	.-F	Fe
Thíos	Thíos	thíos-R	Rd
san	san	i-S	Spa-s
oifig	oifig	oifig-N	Ncfsc
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
ag	ag	ag-S	Sp
éisteacht	éisteacht	éist-N	Nv
leis	leis	le-S	Sp
an	an	an-T	Td-s
ngleo	ngleo	gleo-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
an	an	an-T	Td-s
Máistir	Máistir	Máistir-N	Npmsc
Mac	Mac	Mac-U	Up
Donnchadha	Donnchadha	Donnchadha-N	Np
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
agus	agus	agus-C	Cc
a	a	a-Q	Q-r
cheap	cheap	ceap-V	Vmis
mé	mé	mé-P	Pp1-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
Síos	Síos	síos-R	Rd
leis	leis	le-P	Pr3ms
go dtí	go dtí	go_dtí-S	Spc
seomra	seomra	seomra-N	Ncmsc
Rang	Rang	rang-N	Ncmsc
a	a	a-U	Um
Ceathair	Ceathair	ceathair-M	Mc
.	.	.-F	Fe
Sheas	Sheas	seas-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
Chuala	Chuala	clois-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
chíréib	chíréib	círéib-N	Ncfsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
clampar	clampar	clampar-N	Ncmsc
.	.	.-F	Fe
Chuala	Chuala	clois-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
bhéicíl	bhéicíl	béicíl-N	Ncfsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
scréachach	scréachach	scréachach-N	Ncfsc
.	.	.-F	Fe
Chuala	Chuala	clois-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
raic	raic	raic-N	Ncfsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
ruaille	ruaille	ruaill-N	Ncfsg
buaille	buaille	buaill-N	Ncfsg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
na	na	na-T	Td-p
leabhair	leabhair	leabhar-N	Ncmpc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
cóipleabhair	cóipleabhair	cóipleabhar-N	Ncmpc
ag	ag	ag-S	Sp
gabháil	gabháil	gabh-N	Nv
tríd	tríd	trí-S	Sp
an	an	an-T	Td-s
aer	aer	aer-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
an	an	an-T	Td-s
máistir	máistir	máistir-N	Ncmsc
nua	nua	nua-A	Aqp
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
chuala	chuala	clois-V	Vmis
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
é	é	é-P	Pp3ms
nó	nó	nó-C	Cc
má	má	má-C	Cs
chuala	chuala	clois-V	Vmis
níor	níor	níor-Q	Qn-s
thug	thug	tabhair-V	Vmis---n
siad	siad	siad-P	Pp3-pn
aon	aon	aon-N	Ncmsc
toradh	toradh	toradh-N	Ncmsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Dhún	Dhún	dún-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
arís	arís	arís-R	Rg
go	go	go-U	Ua
ciúin	ciúin	ciúin-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tar	Tar	thar-S	Sp
i	i	i-S	Sp
gcabhair	gcabhair	cabhar-N	Ncfsc|Ncmpc
orm	orm	ar-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Máistir	Máistir	Máistir-N	Npmsc
Mac	Mac	Mac-U	Up
Donnchadha	Donnchadha	Donnchadha-N	Np
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tar	Tar	thar-S	Sp
i	i	i-S	Sp
gcabhair	gcabhair	cabhar-N	Ncfsc|Ncmpc
orm	orm	ar-P	Pr1-s
!	!	!-F	Fe
’	’	’-F	Fa
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
bailithe	bailithe	bailigh-A	Av
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
am	am	am-N	Ncmsc
lóin	lóin	lón-N	Ncmsg
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmm-2s
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
amach	amach	amach-R	Rd
sa	sa	i-S	Spa-s
chlós	chlós	clós-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
seomra	seomra	seomra-N	Ncmsc
deas	deas	deas-R	Ri
ciúin	ciúin	ciúin-A	Aqp
.	.	.-F	Fe
Amach	Amach	amach-R	Rd
leis	leis	le-S	Sp
an	an	an-T	Td-s
Máistir	Máistir	Máistir-N	Npmsc
Mac	Mac	Mac-U	Up
Donnchadha	Donnchadha	Donnchadha-N	Np
ón	ón	ó-S	Spa-s
áit	áit	áit-N	Ncfsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
i	i	i-S	Sp
bhfolach	bhfolach	folach-N	Ncmsc
.	.	.-F	Fe
Rug	Rug	beir-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
chóta	chóta	cóta-N	Ncmsc
.	.	.-F	Fe
Rug	Rug	beir-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
mhála	mhála	mála-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
éalaigh	éalaigh	éalaigh-V	Vmis
sé	sé	sé-P	Pp3msn
leis	leis	le-P	Pr3ms
amach	amach	amach-R	Rd
as	as	as-S	Sp
an	an	an-T	Td-s
seomra	seomra	seomra-N	Ncmsc
ranga	ranga	rang-N	Ncmsg
…	…	…-F	Fi
agus	agus	agus-C	Cc
amach	amach	amach-R	Rd
doras	doras	doras-N	Ncmsc
na	na	na-T	Tdfsg
scoile	scoile	scoil-N	Ncfsg
…	…	…-F	Fi
Maidin	Maidin	maidin-N	Ncfsc
lá	lá	lá-N	Ncmsc
arna	arna	arna-S	Spc
mhárach	mhárach	márach-N	Ns-s
chuir	chuir	cur-N	Ncmsg
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsg
glaoch	glaoch	glaoigh-N	Ncmsc|Nv
ar	ar	ar-S	Sp
Bhean	Bhean	bean-N	Ncfsc
Uí	Uí	Uí-U	Up
Chatháin	Chatháin	Catháin-N	Npfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-T	Td-s
post	post	post-N	Ncmsc
sa	sa	i-S	Spa-s
scoil	scoil	scoil-N	Ncfsc
seo	seo	seo-D	Dd
againne	againne	ag-P	Pr1-p-e
.	.	.-F	Fe
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
spéis	spéis	spéis-N	Ncfsc
agat	agat	ag-P	Pr2-s
ann	ann	i-R	Rl|Pr3ms
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Dhá	Dhá	do-S	Spp
lá	lá	lá-N	Ncmsc
a	a	a-Q	Q-r
chaith	chaith	caith-V	Vmis
sí	sí	sí-P	Pp3fsn
siúd	siúd	siúd-P	Pd
le	le	le-S	Sp
Rang	Rang	rang-N	Ncmsc
a	a	a-U	Um
Ceathair	Ceathair	ceathair-M	Mc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
na	na	na-T	Td-p
leanaí	leanaí	leanbh-N	Ncmpc
sin	sin	sin-D	Dd
chomh	chomh	chomh-R	Ri
fiáin	fiáin	fiáin-A	Aqp
le	le	le-S	Sp
pocáin	pocáin	pocán-N	Ncmpc
ghabhair	ghabhair	gabhar-N	Ncfsg|Ncmsg
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
mé	mé	mé-P	Pp1-s
a	a	a-D	Dp3
leithéid	leithéid	leithéid-N	Ncfsc
riamh	riamh	riamh-R	Rg
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
shaol	shaol	saol-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
rith	rith	rith-N	Nv
amach	amach	amach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
is	is	is-U	U
iomaí	iomaí	iomaí-A	Aqc
scoil	scoil	scoil-N	Ncfsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
mé	mé	mé-P	Pp1-s
inti	inti	i-P	Pr3fs
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
himigh	himigh	imigh-V	Vmm-2s-n
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beannacht	Beannacht	beannacht-N	Ncfsc
Dé	Dé	dia-N	Ncmsg
leat	leat	le-P	Pr2-s
is	is	agus-C	Cc
ná	ná	ná-Q	Qnm
himigh	himigh	imigh-V	Vmm-2s-n
!	!	!-F	Fe
’	’	’-F	Fa
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
de	de	de-S	Sp
rogha	rogha	rogha-N	Ncfsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
bpríomhoide	bpríomhoide	príomhoide-N	Ncmsc
anois	anois	anois-R	Rt
ach	ach	ach-S	Sp
glaoch	glaoch	glaoch-N	Ncmsc
ar	ar	ar-S	Sp
Shíle	Shíle	Síle-N	Npfsc|Ncfsc
Ní	Ní	Ní-U	Up
Fhathaigh	Fhathaigh	Fathaigh-N	Npfsg
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
dhéanfadh	dhéanfadh	déan-V	Vmc
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
i	i	i-S	Sp
Rang	Rang	rang-N	Ncmsc
a	a	a-U	Um
Ceathair	Ceathair	ceathair-M	Mc
óinseach	óinseach	óinseach-N	Ncfsc
cheart	cheart	ceart-A	Aq-fsc
de	de	de-S	Sp
Shíle	Shíle	Síle-N	Npfsc|Ncfsc
.	.	.-F	Fe
Bheadh	Bheadh	bí-V	Vmc
sí	sí	sí-P	Pp3fsn
róbheag	róbheag	beag-A	Aqp
.	.	.-F	Fe
Bheadh	Bheadh	bí-V	Vmc
sí	sí	sí-P	Pp3fsn
róthanaí	róthanaí	tanaí-A	Aqp
.	.	.-F	Fe
Bheadh	Bheadh	bí-V	Vmc
sí	sí	sí-P	Pp3fsn
róchiúin	róchiúin	ciúin-A	Aqp
.	.	.-F	Fe
Bheadh	Bheadh	bí-V	Vmc
sí	sí	sí-P	Pp3fsn
róchúthail	róchúthail	cúthail-A	Aqp
.	.	.-F	Fe
Ró-óg	Ró-óg	óg-A	Aqp
.	.	.-F	Fe
Ró-	Ró-	Ró--X	Xsp
...	...	...-F	Fe
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
féin	féin	féin-P	Px
,	,	,-F	Fi
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
an	an	an-T	Td-s
dara	dara	dara-M	Mo
rogha	rogha	rogha-N	Ncfsc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Chaithfeadh	Chaithfeadh	caith-V	Vmc
sé	sé	sé-P	Pp3msn
múinteoir	múinteoir	múinteoir-N	Ncmsc
a	a	a-U	U
fháil	fháil	faigh-N	Nv
do	do	do-S	Sp
Rang	Rang	rang-N	Ncmsc
a	a	a-U	Um
Ceathair	Ceathair	ceathair-M	Mc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
an	an	an-T	Td-s
dara	dara	dara-M	Mo
rogha	rogha	rogha-N	Ncfsc
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
babhta	babhta	babhta-N	Ncmsc
seo	seo	seo-P	Pd|Dd
beidh	beidh	bí-V	Vmif
mé	mé	mé-P	Pp1-s
fírinneach	fírinneach	fírinneach-A	Aqp
macánta	macánta	macánta-A	Aqp
léi	léi	le-P	Pr3fs
ó	ó	ó-S	Sp
thús	thús	tús-N	Ncmsc
.	.	.-F	Fe
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
a	a	a-U	U
mhíniú	mhíniú	mínigh-N	Nv
di	di	do-P	Pr3fs
roimh	roimh	roimh-S	Sp
ré	ré	ré-N	Ncfsc|Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Maith	Maith	Maith-N	Npmsc
go leor	go leor	go_leor-A	Aq
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Síle	Síle	Síle-N	Ncfsc|Npfsc
Ní	Ní	Ní-U	Up
Fhathaigh	Fhathaigh	Fathaigh-N	Npfsg
nuair	nuair	nuair-C	Cs
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
inis	inis	inis-V	Vmis|Npmsc|Ncfsc|Vmm-2s
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsg|Ncmsc
di	di	do-P	Pr3fs
faoi	faoi	faoi-S	Sp
Rang	Rang	rang-N	Ncmsc
a	a	a-U	Um
Ceathair	Ceathair	ceathair-M	Mc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Déanfaidh	Déanfaidh	déan-V	Vmif
mé	mé	mé-P	Pp1-s
mo	mo	mo-D	Dp1-s
sheacht	sheacht	seacht-M	Mc
míle	míle	míle-M	Mc
dícheall	dícheall	dícheall-N	Ncmsc
.	.	.-F	Fe
Feicfidh	Feicfidh	feic-V	Vmif
mé	mé	mé-P	Pp1-s
ar	ar	ar-S	Sp
maidin	maidin	maidin-N	Ncfsc
thú	thú	tú-P	Pp2-s
,	,	,-F	Fi
le	le	le-S	Sp
cúnamh	cúnamh	cúnamh-N	Ncmsc
Dé	Dé	dia-N	Ncmsg
.	.	.-F	Fe
’	’	’-F	Fa
Shuigh	Shuigh	suigh-V	Vmis
Síle	Síle	Síle-N	Ncfsc|Npfsc
Ní	Ní	Ní-U	Up
Fhathaigh	Fhathaigh	Fathaigh-N	Npfsg
síos	síos	síos-R	Rd
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
cuimhneamh	cuimhneamh	cuimhnigh-N	Nv
uirthi	uirthi	ar-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Conas	Conas	conas-R	Rq
is	is	is-W	Wp-i
féidir	féidir	féidir-N	Ns-s
liom	liom	le-P	Pr1-s
smacht	smacht	smacht-N	Ncmsc
a	a	a-U	U
chur	chur	cuir-N	Nv
orthu	orthu	ar-P	Pr3-p
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
cuimhneamh	cuimhneamh	cuimhneamh-N	Nv|Ncmsc
ar	ar	ar-S	Sp
phlean	phlean	plean-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
post	post	post-N	Ncmsc
seo	seo	seo-D	Dd
ag	ag	ag-S	Sp
teastáil	teastáil	teastaigh-N	Nv
go	go	go-U	Ua
dóite	dóite	dóigh-A	Av
uaim	uaim	ó-P	Pr1-s
.	.	.-F	Fe
’	’	’-F	Fa
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
fós	fós	fós-R	Rg
ina	ina	i-S	Spp-p|Spp-s
suí	suí	suí-N	Ncmsc
ansin	ansin	ansin-R	Rt|Rl
ag	ag	ag-S	Sp
cuimhneamh	cuimhneamh	cuimhnigh-N	Nv
uirthi	uirthi	ar-P	Pr3fs
féin	féin	féin-P	Px
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
a	a	a-D	Dp3
deartháir	deartháir	deartháir-N	Ncmsc
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
seomra	seomra	seomra-N	Ncmsc
suite	suite	suigh-A	Aqp|Av
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
inis	inis	inis-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
post	post	post-N	Ncmsc
seo	seo	seo-D	Dd
ag	ag	ag-S	Sp
teastáil	teastáil	teastaigh-N	Nv
go	go	go-U	Ua
dóite	dóite	dóigh-A	Av
uaim	uaim	ó-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
leis	leis	le-P	Pr3ms
,	,	,-F	Fi
‘	‘	‘-X	Xx
ach	ach	ach-C	Cs
ón	ón	ó-S	Spa-s
méid	méid	méid-N	Ncmsc|Ncfsc
atá	atá	bí-V	Vmip---r
ráite	ráite	abair-A	Av
ag	ag	ag-S	Sp
an	an	an-T	Td-s
bpríomhoide	bpríomhoide	príomhoide-N	Ncmsc
liom	liom	le-P	Pr1-s
is	is	agus-W	Wp-i|Wpri|Cc
léir	léir	léir-A	Aqp
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
seo	seo	seo-D	Dd
chomh	chomh	chomh-R	Ri
fiáin	fiáin	fiáin-A	Aqp
le	le	le-S	Sp
pocáin	pocáin	pocán-N	Ncmpc
ghabhair	ghabhair	gabhar-N	Ncfsg|Ncmsg
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
chuma	chuma	cuma-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
nach	nach	nach-Q	Qnr
bhfuil	bhfuil	bí-V	Vmip---n
smacht	smacht	smacht-N	Ncmsc
dá	dá	do-S	Spp-s|Spp-p|Spp-s|Spp-p
laghad	laghad	laghad-N	Ncmsc
orthu	orthu	ar-P	Pr3-p
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
cuireadh	cuireadh	cuir-V	Vmis0--n
sé	sé	sé-P	Pp3msn
sin	sin	sin-P	Pd
isteach	isteach	isteach-R	Rd
ná	ná	ná-C	Cs|Cc
amach	amach	amach-R	Rd
ort	ort	ar-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
a	a	a-D	Dp3
deartháir	deartháir	deartháir-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
plean	plean	plean-N	Ncmsc
agamsa	agamsa	ag-P	Pr1-s-e
duit	duit	do-P	Pr2-s
…	…	…-F	Fi
’	’	’-F	Fa
Maidin	Maidin	maidin-N	Ncfsc
lá	lá	lá-N	Ncmsc
arna	arna	arna-S	Spc
mhárach	mhárach	márach-N	Ns-s
shiúil	shiúil	siúl-N	Ncmsg
Iníon	Iníon	iníon-N	Ncfsc
Uí	Uí	Uí-U	Up
Fhathaigh	Fhathaigh	Fathaigh-N	Npfsg
isteach	isteach	isteach-R	Rd
in	in	i-S	Sp
oifig	oifig	oifig-N	Ncfsc
an	an	an-T	Td-s
phríomhoide	phríomhoide	príomhoide-N	Ncmsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
culaith	culaith	culaith-N	Ncfsc
bhán	bhán	bán-A	Aq-fsc
agus	agus	agus-C	Cc
crios	crios	crios-N	Ncmsc
dubh	dubh	dubh-A	Aq-msc
uirthi	uirthi	ar-P	Pr3fs
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
gan	gan	gan-S	Sp
bróg	bróg	bróg-N	Ncfsc
gan	gan	gan-S	Sp
stoca	stoca	stoca-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-N	Ncmsc|Nv|Vmm-2s
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsg|Ncmsc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-V	Vmis
sé	sé	sé-P	Pp3msn
uirthi	uirthi	ar-P	Pr3fs
den	den	de-S	Spa-s
dara	dara	dara-M	Mo
babhta	babhta	babhta-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níor	Níor	níor-W	Ws-in|Qn-s
inis	inis	inis-V	Vmis|Vmis---n|Npmsc|Ncfsc|Npmsc|Vmis|Vmis---n
tú	tú	tú-P	Pp2-s
dúinn	dúinn	do-P	Pr1-p
ag	ag	ag-S	Sp
an	an	an-T	Td-s
agallamh	agallamh	agallamh-N	Ncmsc
gur	gur	is-W	Wsdi|Wpdi
saineolaí	saineolaí	saineolach-A	Aqc
karate	karate	karate-A	Av
thú	thú	tú-P	Pp2-s
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
bac	bac	bac-V	Vmm-2s-n
leis	leis	le-S	Sp
sin	sin	sin-P	Pd
anois	anois	anois-R	Rt
ach	ach	ach-S	Sp|Cs
tar	tar	thar-S	Sp
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
liomsa	liomsa	le-P	Pr1-s-e
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Iníon	Iníon	iníon-N	Ncfsc
Uí	Uí	Uí-U	Up
Fhathaigh	Fhathaigh	Fathaigh-N	Npfsg
leis	leis	le-S	Sp
an	an	an-T	Td-s
bpríomhoide	bpríomhoide	príomhoide-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Rachaidh	Rachaidh	téigh-V	Vmif
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
againn	againn	ag-P	Pr1-p
síos	síos	síos-R	Rd
go dtí	go dtí	go_dtí-S	Spc
seomra	seomra	seomra-N	Ncmsc
Rang	Rang	rang-N	Ncmsc
a	a	a-U	Um
Ceathair	Ceathair	ceathair-M	Mc
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Mise	Mise	mé-P	Pp1-s-e
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
théimse	théimse	téigh-V	Vmip1s-ne
níos	níos	níos-U	Uc
faide	faide	fada-A	Aqc
ná	ná	ná-C	Cc
doras	doras	doras-N	Ncmsc
an	an	an-T	Td-s
tseomra	tseomra	seomra-N	Ncmsg
sin	sin	sin-D	Dd
.	.	.-F	Fe
Níl	Níl	bí-V	Vmip---n
sé	sé	sé-P	Pp3msn
sábháilte	sábháilte	sábháil-A	Av
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
na	na	na-T	Td-p
leanaí	leanaí	leanbh-N	Ncmpc
sin	sin	sin-D	Dd
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
rófhiáin	rófhiáin	fiáin-A	Aqp
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
cuireadh	cuireadh	cuir-V	Vmis0--n
sé	sé	sé-P	Pp3msn
sin	sin	sin-P	Pd
isteach	isteach	isteach-R	Rd
ná	ná	ná-C	Cs|Cc
amach	amach	amach-R	Rd
ort	ort	ar-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Iníon	Iníon	iníon-N	Ncfsc
Uí	Uí	Uí-U	Up
Fhathaigh	Fhathaigh	Fathaigh-N	Npfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
plean	plean	plean-N	Ncmsc
breá	breá	breá-A	Aq-msc
agamsa	agamsa	ag-P	Pr1-s-e
.	.	.-F	Fe
Cogar	Cogar	cogar-N	Ncmsc
i	i	i-S	Sp
leith	leith	leith-N	Ncfsc
chugam	chugam	chuig-P	Pr1-s
...	...	...-F	Fe
’	’	’-F	Fa
Cúig	Cúig	cúig-N	Ncmsc|Mc
nóiméad	nóiméad	nóiméad-N	Ncmsc|Ncmpg
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|W|Dd
d	d	d-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmm-2s
Iníon	Iníon	iníon-N	Ncfsc
Uí	Uí	Uí-U	Up
Fhathaigh	Fhathaigh	Fathaigh-N	Npfsg
doras	doras	doras-N	Ncmsc
sheomra	sheomra	seomra-N	Ncmsg
Rang	Rang	rang-N	Ncmsc
a	a	a-U	Um
Ceathair	Ceathair	ceathair-M	Mc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhan	fhan	fan-V	Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
taobh amuigh	taobh amuigh	taobh_amuigh-R	Rl
den	den	de-S	Spa-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
cluiche	cluiche	cluiche-N	Ncmsc
camógaíochta	camógaíochta	camógaíocht-N	Ncfsg
ar	ar	ar-S	Sp
siúl	siúl	siúil-N	Nv
ag	ag	ag-S	Sp
cuid	cuid	cuid-N	Ncfsc
de	de	de-S	Sp
na	na	na-T	Td-p
cailíní	cailíní	cailín-N	Ncmpc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
cuid	cuid	cuid-N	Ncfsc
eile	eile	eile-D	Dd
acu	acu	ag-P	Pr3-p
ag	ag	ag-S	Sp
rince	rince	rinc-N	Nv
ar	ar	ar-S	Sp
na	na	na-T	Td-p
boird	boird	bord-N	Ncmpc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
beirt	beirt	beirt-N	Ncfsc
bhuachaillí	bhuachaillí	buachaill-N	Ncmpc
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
péint	péint	péint-N	Ncfsc
dhearg	dhearg	dearg-A	Aq-fsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gclár	gclár	clár-N	Ncmsc
bán	bán	bán-N	Ncmpg
agus	agus	agus-C	Cc
triúr	triúr	triúr-N	Ncmpg|Ncmsc
eile	eile	eile-D	Dd
ag	ag	ag-S	Sp
imirt	imirt	imir-N	Nv
peile	peile	peil-N	Ncfsg
taobh	taobh	taobh-N	Ncmsc
thiar	thiar	thiar-R	Rd
den	den	de-S	Spa-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
Rug	Rug	beir-V	Vmis
Iníon	Iníon	iníon-N	Ncfsc
Uí	Uí	Uí-U	Up
Fhathaigh	Fhathaigh	Fathaigh-N	Npfsg
greim	greim	greim-N	Ncmsc
cluaise	cluaise	cluas-N	Ncfsg
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bpríomhoide	bpríomhoide	príomhoide-N	Ncmsc
agus	agus	agus-C	Cc
tharraing	tharraing	tarraing-V	Vmis
sí	sí	sí-P	Pp3fsn
isteach	isteach	isteach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Haigh	Haigh	haigh-V	Vmis
Áá	Áá	Áá-N	Npmsc
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
agus	agus	agus-C	Cc
chaith	chaith	caith-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
urlár	urlár	urlár-N	Ncmsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Stop	Stop	stop-V	Vmis|Vmm-2s|Ncmsc
an	an	an-T	Td-s
cluiche	cluiche	cluiche-N	Ncmsg|Ncmsc
peile	peile	peil-N	Ncfsg
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bpointe	bpointe	pointe-N	Ncmsc
boise	boise	bos-N	Ncfsg
.	.	.-F	Fe
Stop	Stop	stop-V	Vmm-2s
phéinteáil	phéinteáil	péinteáil-V	Vmis
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfaca	bhfaca	feic-V	Vmis---d
sibh	sibh	sibh-P	Pp2-p
é	é	é-P	Pp3ms
sin	sin	sin-P	Pd
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
cailín	cailín	cailín-N	Ncmsc
amháin	amháin	amháin-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Haigh	Haigh	haigh-V	Vmis
Áá	Áá	Áá-N	Npmsc
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Iníon	Iníon	iníon-N	Ncfsc
Uí	Uí	Uí-U	Up
Fhathaigh	Fhathaigh	Fathaigh-N	Npfsg
arís	arís	arís-R	Rg
.	.	.-F	Fe
Stop	Stop	stop-V	Vmis|Vmm-2s
an	an	an-T	Td-s
rince	rince	rince-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bpointe	bpointe	pointe-N	Ncmsc
boise	boise	bos-N	Ncfsg
.	.	.-F	Fe
Stop	Stop	stop-V	Vmis|Vmm-2s|Ncmsc
an	an	an-T	Td-s
cluiche	cluiche	cluiche-N	Ncmsg|Ncmsc
camógaíochta	camógaíochta	camógaíocht-N	Ncfsg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
ardaigh	ardaigh	ardaigh-V	Vmm-2s
Iníon	Iníon	iníon-N	Ncfsc
Uí	Uí	Uí-U	Up
Fhathaigh	Fhathaigh	Fathaigh-N	Npfsg
a	a	a-D	Dp3
cos	cos	cos-N	Ncfsc
agus	agus	agus-C	Cc
tharraing	tharraing	tarraing-V	Vmis
sí	sí	sí-P	Pp3fsn
cic	cic	cic-N	Ncfsc|Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bpríomhoide	bpríomhoide	príomhoide-N	Ncmsc
.	.	.-F	Fe
Lig	Lig	lig-V	Vmis
seisean	seisean	sé-P	Pp3msne
béic	béic	béic-N	Ncfsc
as	as	as-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Lig	Lig	lig-V	Vmis
dom	dom	do-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Lig	Lig	lig-V	Vmis
dom	dom	do-P	Pr1-s
,	,	,-F	Fi
más	más	má-C	Csw
é	é	é-P	Pp3ms
do	do	do-S	Sp
thoil	thoil	toil-N	Ncfsc
é	é	é-P	Pp3ms
!	!	!-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Éirigh	Éirigh	éirigh-V	Vmm-2s
i	i	i-S	Sp
do	do	do-D	Dp2-s
sheasamh	sheasamh	seas-N	Ncmsc|Nv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Iníon	Iníon	iníon-N	Ncfsc
Uí	Uí	Uí-U	Up
Fhathaigh	Fhathaigh	Fathaigh-N	Npfsg
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Éirigh	Éirigh	éirigh-V	Vmm-2s
i	i	i-S	Sp
do	do	do-D	Dp2-s
sheasamh	sheasamh	seas-N	Ncmsc|Nv
anois	anois	anois-R	Rt
díreach	díreach	díreach-N	Ncmsc
!	!	!-F	Fe
’	’	’-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmm-2s
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
bocht	bocht	bocht-A	Aq-msc
ag	ag	ag-S	Sp
crith	crith	crith-N	Nv
.	.	.-F	Fe
Faoin	Faoin	faoi-S	Spa-s
am	am	am-N	Ncmsc
seo	seo	seo-D	Dd
bhí	bhí	bí-V	Vmis
lán	lán	lán-N	Ncmsc
na	na	na-T	Td-p
súl	súl	súil-N	Ncfpg
á	á	do-S	Spo-s
bhaint	bhaint	bain-N	Nv
ag	ag	ag-S	Sp
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
as	as	as-S	Sp
an	an	an-T	Td-s
múinteoir	múinteoir	múinteoir-N	Ncmsc
nua	nua	nua-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
baint	baint	bain-N	Nv
an-sásamh	an-sásamh	sásaigh-N	Ncmsc|Nv
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
as	as	as-S	Sp
an	an	an-T	Td-s
seó	seó	seó-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
As	As	as-S	Sp
ucht	ucht	ucht-N	Ncmsc
Dé	Dé	dia-N	Ncmsg
ort	ort	ar-P	Pr2-s
!	!	!-F	Fe
Ná	Ná	ná-Q	Qnm
buail	buail	buail-V	Vmm-2s-n
arís	arís	arís-R	Rg
mé	mé	mé-P	Pp1-s
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
buail	buail	buail-V	Vmm-2s-n
arís	arís	arís-R	Rg
mé	mé	mé-P	Pp1-s
!	!	!-F	Fe
’	’	’-F	Fa
Thosaigh	Thosaigh	tosaigh-V	Vmis
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
ag	ag	ag-S	Sp
gáire	gáire	gáir-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
buail	buail	buail-V	Vmm-2s-n
arís	arís	arís-R	Rg
mé	mé	mé-P	Pp1-s
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Rónán	Rónán	Rónán-N	Npmsc
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
aithrise	aithrise	aithris-N	Ncfsg
ar	ar	ar-S	Sp
ghuth	ghuth	guth-N	Ncmsc
an	an	an-T	Td-s
phríomhoide	phríomhoide	príomhoide-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Taispeánfaidh	Taispeánfaidh	taispeáin-V	Vmif
mise	mise	mé-P	Pp1-s-e
duitse	duitse	do-P	Pr2-s-e
cé	cé	cé-N	Ncfsc
atá	atá	bí-V	Vmip---r
i	i	i-S	Sp
gceannas	gceannas	ceannas-N	Ncmsc
anseo	anseo	anseo-R	Rl
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Iníon	Iníon	iníon-N	Ncfsc
Uí	Uí	Uí-U	Up
Fhathaigh	Fhathaigh	Fathaigh-N	Npfsg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
ardaigh	ardaigh	ardaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
lámh	lámh	lámh-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Haigh	Haigh	haigh-V	Vmis
Áá	Áá	Áá-N	Npmsc
!	!	!-F	Fe
’	’	’-F	Fa
Tharraing	Tharraing	tarraing-V	Vmis
sí	sí	sí-P	Pp3fsn
buille	buille	buille-N	Ncmsc
sa	sa	i-S	Spa-s
mhuineál	mhuineál	muineál-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bpríomhoide	bpríomhoide	príomhoide-N	Ncmsc
.	.	.-F	Fe
Thit	Thit	tit-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
chnap	chnap	cnap-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
urlár	urlár	urlár-N	Ncmsc
arís	arís	arís-R	Rg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Éirigh	Éirigh	éirigh-V	Vmm-2s
i	i	i-S	Sp
do	do	do-D	Dp2-s
sheasamh	sheasamh	seas-N	Ncmsc|Nv
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
leis	leis	le-P	Pr3ms
arís	arís	arís-R	Rg
.	.	.-F	Fe
An	An	an-T	Td-s
uair	uair	uair-N	Ncfsc
seo	seo	seo-D	Dd
bhuail	bhuail	buail-V	Vmis
sí	sí	sí-P	Pp3fsn
sa	sa	i-S	Spa-s
tsrón	tsrón	srón-N	Ncfsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Haigh	Haigh	haigh-V	Vmis
Áá	Áá	Áá-N	Npmsc
!	!	!-F	Fe
’	’	’-F	Fa
Ansin	Ansin	ansin-R	Rt|Rl
bhuail	bhuail	buail-V	Vmis
sí	sí	sí-P	Pp3fsn
sa	sa	i-S	Spa-s
droim	droim	droim-N	Ncmsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Haigh	Haigh	haigh-V	Vmis
Áá	Áá	Áá-N	Npmsc
!	!	!-F	Fe
’	’	’-F	Fa
Ansin	Ansin	ansin-R	Rt|Rl
tharraing	tharraing	tarraing-V	Vmis
sí	sí	sí-P	Pp3fsn
cic	cic	cic-N	Ncfsc|Ncmsc
eile	eile	eile-D	Dd
air	air	ar-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Anois	Anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Éirigh	Éirigh	éirigh-V	Vmm-2s
i	i	i-S	Sp
do	do	do-D	Dp2-s
sheasamh	sheasamh	seas-N	Ncmsc|Nv
.	.	.-F	Fe
’	’	’-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmm-2s
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bailigh	Bailigh	bailigh-V	Vmm-2s
leat	leat	le-P	Pr2-s
amach	amach	amach-R	Rd
as	as	as-P	Pr3ms
mo	mo	mo-D	Dp1-s
sheomra	sheomra	seomra-N	Ncmsc
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Iníon	Iníon	iníon-N	Ncfsc
Uí	Uí	Uí-U	Up
Fhathaigh	Fhathaigh	Fathaigh-N	Npfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bailigh	Bailigh	bailigh-V	Vmm-2s
leat	leat	le-P	Pr2-s
amach	amach	amach-R	Rd
as	as	as-P	Pr3ms
mo	mo	mo-D	Dp1-s
radharc	radharc	radharc-N	Ncmsc
!	!	!-F	Fe
’	’	’-F	Fa
Rith	Rith	rith-V	Vmm-2s|Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
amach	amach	amach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
Bhreathnaigh	Bhreathnaigh	breathnaigh-V	Vmis
Iníon	Iníon	iníon-N	Ncfsc
Uí	Uí	Uí-U	Up
Fhathaigh	Fhathaigh	Fathaigh-N	Npfsg
thart	thart	thart-R	Rd
.	.	.-F	Fe
Shiúil	Shiúil	siúil-V	Vmis
sí	sí	sí-P	Pp3fsn
síos	síos	síos-R	Rd
suas	suas	suas-R	Rd
.	.	.-F	Fe
Bhreathnaigh	Bhreathnaigh	breathnaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
go	go	go-U	Ua
fiáin	fiáin	fiáin-A	Aqp
fíochmhar	fíochmhar	fíochmhar-A	Aqp
idir	idir	idir-S	Sp
an	an	an-T	Td-s
dá	dá	dó-M	Mc
shúil	shúil	súil-N	Ncfsc
ar	ar	ar-S	Sp
gach	gach	gach-D	Dq
páiste	páiste	páiste-N	Ncmsc
sa	sa	i-S	Spa-s
rang	rang	rang-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
gíog	gíog	gíog-N	Ncfsc
ná	ná	nach-Q	Qnr
míog	míog	míog-V	Vmm-2s-n
as	as	as-P	Pr3ms
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
labhair	labhair	labhair-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
‘	‘	‘-X	Xx
Anois	Anois	anois-R	Rt
,	,	,-F	Fi
a	a	a-U	Uv
pháistí	pháistí	páiste-N	Ncmpv
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
go	go	go-U	Ua
ciúin	ciúin	ciúin-A	Aqp
,	,	,-F	Fi
‘	‘	‘-X	Xx
éistigí	éistigí	éist-V	Vmm-2p
leis	leis	le-S	Sp
an	an	an-T	Td-s
dlúthdhiosca	dlúthdhiosca	diosca-N	Ncmsc
…	…	…-F	Fi
’	’	’-F	Fa
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
bhfoghlaimeodh	bhfoghlaimeodh	foghlaim-V	Vmc
duine	duine	duine-N	Ncmsc
karate	karate	karate-A	Av
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
Bean	Bean	bean-N	Ncfsc
Uí	Uí	Uí-U	Up
Chuinn	Chuinn	Cuinn-N	Np
d	d	d-X	Xl
’	’	’-F	Fa
Iníon	Iníon	iníon-N	Ncfsc
Uí	Uí	Uí-U	Up
Fhathaigh	Fhathaigh	Fathaigh-N	Npfsg
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
amach	amach	amach-R	Rd
an	an	an-T	Td-s
geata	geata	geata-N	Ncmsg|Ncmsc
tar éis	tar éis	tar_éis-S	Spc
scoile	scoile	scoil-N	Ncfsg
an	an	an-T	Td-s
tráthnóna	tráthnóna	tráthnóna-N	Ncmsg
sin	sin	sin-D	Dd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
tuairim	tuairim	tuairim-N	Ncfsc
faoin	faoin	faoi-S	Spa-s
spéir	spéir	spéir-N	Ncfsc
agamsa	agamsa	ag-P	Pr1-s-e
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Iníon	Iníon	iníon-N	Ncfsc
Uí	Uí	Uí-U	Up
Fhathaigh	Fhathaigh	Fathaigh-N	Npfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
aon	aon	aon-D	Dq
ní	ní	ní-N	Ns-s
beo	beo	beo-A	Aqc
faoi	faoi	faoi-P	Pr3ms
karate	karate	karate-A	Av
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
chulaith	chulaith	culaith-N	Ncfsc
ná	ná	ná-C	Cs
an	an	is-W	Wpdq|Wp-q
crios	crios	crios-N	Ncmsc
fiú	fiú	fiú-N	Ncmsg|Ncmsc|Rg|Ns-s
!	!	!-F	Fe
Is	Is	is-W	Wp-i
amhlaidh	amhlaidh	amhlaidh-R	Rg
a	a	a-Q	Q-i|Q-r
fuair	fuair	faigh-V	Vmis
mé	mé	mé-P	Pp1-s
ar	ar	ar-S	Sp
iasacht	iasacht	iasacht-N	Ncfsc
ó	ó	ó-C	Cs|Sp
mo	mo	mo-D	Dp1-s
dheartháir	dheartháir	deartháir-N	Ncmsc
iad	iad	iad-P	Pp3-p
!	!	!-F	Fe
Cén	Cén	cé-D	Dw--s
tslí	tslí	slí-N	Ncfsc
eile	eile	eile-D	Dd
a	a	a-Q	Q-r
sheasfainn	sheasfainn	seas-V	Vmc-1s
an	an	an-T	Td-s
fód	fód	fód-N	Ncmsc
in aghaidh	in aghaidh	in_aghaidh-S	Spc
Rang	Rang	rang-N	Ncmsc
a	a	a-U	Um
Ceathair	Ceathair	ceathair-M	Mc
!	!	!-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Rang	Rang	rang-N	Ncmsc
a	a	a-U	Um
Ceathair	Ceathair	ceathair-M	Mc
?	?	?-F	Fq
Ná	Ná	ná-Q	Qnm
habair	habair	abair-V	Vmm-2s-n
liom	liom	le-P	Pr1-s
gurb	gurb	is-W	Wpdi
iad	iad	iad-P	Pp3-p
Rang	Rang	rang-N	Ncmsc
a	a	a-U	Um
Ceathair	Ceathair	ceathair-M	Mc
atá	atá	bí-V	Vmip---r
agam	agam	ag-P	Pr1-s
i	i	i-S	Sp
mbliana	mbliana	bliain-N	Ncfpc
!	!	!-F	Fe
’	’	’-F	Fa
Phléasc	Phléasc	pléasc-V	Vmis
an	an	an-T	Td-s
Máistir	Máistir	Máistir-N	Npmsc
Ó	Ó	Ó-U	Up
Riain	Riain	Riain-N	Npmsc
amach	amach	amach-R	Rd
ag	ag	ag-S	Sp
caoineadh	caoineadh	caoin-N	Nv
.	.	.-F	Fe
