 Sióga	Sióga	-X	Xx
Cheann	Cheann	ceann-N	Ncmsc
Tíre	Tíre	tír-N	Ncfsg
Bhí	Bhí	bí-V	Vmis
sióg	sióg	sióg-N	Ncfsc
i	i	i-S	Sp
gCeann	gCeann	ceann-N	Ncmsc
Tíre	Tíre	tír-N	Ncfsg
tráth	tráth	tráth-N	Ncmsc
.	.	.-F	Fe
Rírá	Rírá	rírá-N	Ncmsc
an	an	an-T	Td-s
t-ainm	t-ainm	ainm-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sé	sé	sé-P	Pp3msn
ach	ach	ach-R	Ri
díreach	díreach	díreach-A	Aqp
tagtha	tagtha	tar-A	Av
ar	ar	ar-S	Sp
an	an	an-T	Td-s
saol	saol	saol-N	Ncmsc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
imeacht	imeacht	imigh-N	Nv
leis	leis	le-P	Pr3ms
amach	amach	amach-R	Rd
ag	ag	ag-S	Sp
spaisteoireacht	spaisteoireacht	spaisteoireacht-N	Ncfsc
bhuail	bhuail	buail-V	Vmis
Rírá	Rírá	rírá-N	Ncmsc
le	le	le-S	Sp
sióg	sióg	sióg-N	Ncfsc
eile	eile	eile-D	Dd
ar	ar	ar-S	Sp
thairseach	thairseach	tairseach-N	Ncfsc
a	a	a-D	Dp3
thí	thí	tí-N	Ncfsc|Ncmsc
.	.	.-F	Fe
Ruaille	Ruaille	ruaille-N	Ns-s
Buaille	Buaille	Buaille-N	Npmsc
an	an	an-T	Td-s
t-ainm	t-ainm	ainm-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ar	ar	ar-S	Sp
an	an	an-T	Td-s
tsióg	tsióg	sióg-N	Ncfsc
seo	seo	seo-D	Dd
.	.	.-F	Fe
Chaith	Chaith	caith-V	Vmis
Rírá	Rírá	rírá-N	Ncmsc
agus	agus	agus-C	Cc
Ruaille	Ruaille	ruaille-N	Ncfsg|Ns-s|Ncfsg|Ns-s
Buaille	Buaille	Buaille-N	Npmsc
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
i	i	i-S	Sp
gcomhluadar	gcomhluadar	comhluadar-N	Ncmsc
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
áit	áit	áit-N	Ncfsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
Rírá	Rírá	rírá-N	Ncmsc
bhí	bhí	bí-V	Vmis
Ruaille	Ruaille	ruaille-N	Ns-s
Buaille	Buaille	Buaille-N	Npmsc
ann	ann	i-P	Pr3ms
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
scarfadh	scarfadh	scar-V	Vmc----n
aon	aon	aon-D	Dq
ní	ní	ní-N	Ncmsc
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
óna	óna	ó-S	Spp-s
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Amuigh	Amuigh	amuigh-R	Rl
ag	ag	ag-S	Sp
súgradh	súgradh	súgradh-N	Nv-----n
a	a	a-Q	Q-r
chaitheadar	chaitheadar	caith-V	Vmis3p
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
,	,	,-F	Fi
ag	ag	ag-S	Sp
rith	rith	rith-N	Nv
siar	siar	siar-R	Rd
is	is	agus-C	Cc
aniar	aniar	aniar-A	Aqp|Rd
,	,	,-F	Fi
suas	suas	suas-R	Rd
is	is	agus-C	Cc
anuas	anuas	anuas-R	Rd
,	,	,-F	Fi
ag	ag	ag-S	Sp
iascach	iascach	iasc-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
loch	loch	loch-N	Ncmsc
is	is	agus-C	Cc
ag	ag	ag-S	Sp
scipeáil	scipeáil	scipeáil-N	Nv
tríd	tríd	trí-S	Sp
an	an	an-T	Td-s
aer	aer	aer-N	Ncmsc
.	.	.-F	Fe
Nach	Nach	is-W	Wpsin
acu	acu	ag-P	Pr3-p
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
spórt	spórt	spórt-N	Ncmsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
spraoi	spraoi	spraoi-N	Ncmsg
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
aoibhinn	aoibhinn	aoibhinn-A	Aq-msc
gréine	gréine	grian-N	Ncfsg
úd	úd	úd-D	Dd
!	!	!-F	Fe
Ach	Ach	ach-C	Cs
ansin	ansin	ansin-R	Rt|Rl
tháinig	tháinig	tar-V	Vmis
an	an	an-T	Td-s
oíche	oíche	oíche-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
ó	ó	ó-S	Sp
sholas	sholas	solas-N	Ncmsc
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
na	na	na-T	Td-p
réaltaí	réaltaí	réalta-N	Ncfpc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
ghealach	ghealach	gealach-N	Ncfsc
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
iarracht	iarracht	iarracht-N	Ncfsc
teacht	teacht	tar-N	Ncmsc|Nv
amach	amach	amach-R	Rd
agus	agus	agus-C	Cc
a	a	a-D	Dp3
gcluichí	gcluichí	cluiche-N	Ncmpg
féin	féin	féin-P	Px
a	a	a-U	U
imirt	imirt	imir-N	Nv
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
thuig	thuig	tuig-V	Vmip---n|Vmis---n
Rírá	Rírá	rírá-N	Ncmsc
céard	céard	cé-W	W--q
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
titim	titim	tit-N	Nv
amach	amach	amach-R	Rd
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
ansin	ansin	ansin-R	Rt|Rl
,	,	,-F	Fi
go	go	go-U	Ua
tobann	tobann	tobann-A	Aqp
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
Ruaille	Ruaille	ruaille-N	Ns-s
Buaille	Buaille	Buaille-N	Npmsc
imithe	imithe	imigh-A	Av
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
mearbhall	mearbhall	mearbhall-N	Ncmsc
ar	ar	ar-S	Sp
Rírá	Rírá	rírá-N	Ncmsc
.	.	.-F	Fe
Cá	Cá	cá-R	Rq
raibh	raibh	bí-V	Vmis---d
Ruaille	Ruaille	ruaille-N	Ns-s
Buaille	Buaille	Buaille-N	Npmsc
imithe	imithe	imigh-A	Av
?	?	?-F	Fq
Agus	Agus	agus-C	Cc
cén	cén	cé-D	Dw--s
fáth	fáth	fáth-N	Ncmsc
ar	ar	ar-Q	Q-is
imigh	imigh	imigh-V	Vmis
sé	sé	sé-P	Pp3msn
?	?	?-F	Fq
Bhí	Bhí	bí-V	Vmis
Rírá	Rírá	rírá-N	Ncmsc
bocht	bocht	bocht-A	Aq-msc
trína	trína	trí-S	Spp-s
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
aige	aige	ag-P	Pr3ms
an	an	an-Q	Qq
bhfeicfeadh	bhfeicfeadh	feic-V	Vmc
sé	sé	sé-P	Pp3msn
Ruaille	Ruaille	ruaille-N	Ns-s
Buaille	Buaille	Buaille-N	Npmsc
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
arís	arís	arís-R	Rg
.	.	.-F	Fe
Shocraigh	Shocraigh	socraigh-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-Q	Q
dtabharfadh	dtabharfadh	tabhair-V	Vmc
sé	sé	sé-P	Pp3msn
cuairt	cuairt	cuairt-N	Ncfsc
ar	ar	is-W	Wpsi|Ncmsc|Wssi|Wpdi
,	,	,-F	Fi
rí	rí	rí-N	Ncmsc
na	na	na-T	Td-p
sióg	sióg	sióg-N	Ncfpg
i	i	i-S	Sp
gCeann	gCeann	ceann-N	Ncmsc
Tíre	Tíre	tír-N	Ncfsg
,	,	,-F	Fi
le	le	le-S	Sp
comhairle	comhairle	comhairle-N	Ncfsc
agus	agus	agus-C	Cc
cabhair	cabhair	cabhair-N	Ncmpc|Ncfsc
a	a	a-U	U
fháil	fháil	faigh-N	Nv
uaidh	uaidh	ó-P	Pr3ms
.	.	.-F	Fe
Shiúil	Shiúil	siúil-V	Vmis
sé	sé	sé-P	Pp3msn
isteach	isteach	isteach-R	Rd
go	go	go-S	Sp
pálás	pálás	pálás-N	Ncmsc
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsg
,	,	,-F	Fi
áit	áit	áit-N	Ncfsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
ina	ina	i-S	Spp-s
shuí	shuí	suí-N	Ncmsc
ina	ina	i-S	Spp-s|Spp-p
ríchathaoir	ríchathaoir	ríchathaoir-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	a-U	U
rí	rí	rígh-N	Nv
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
do	do	do-Q	Q
chabhair	chabhair	cabhair-V	Vmis
uaim	uaim	ó-P	Pr1-s
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Rírá	Rírá	rírá-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Abair	Abair	abar-N	Ncmpc
leat	leat	le-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
.	.	.-F	Fe
Ag	Ag	ag-S	Sp
súgradh	súgradh	súgradh-N	Nv-----n
a	a	a-Q	Q-r
bhíomar	bhíomar	bí-V	Vmis1p
,	,	,-F	Fi
Ag	Ag	ag-S	Sp
súgradh	súgradh	súgradh-N	Nv-----n
is	is	agus-C	Cc
ag	ag	ag-S	Sp
spraoi	spraoi	spraoi-N	Nv-----n
.	.	.-F	Fe
Anois	Anois	anois-R	Rt
tá	tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
imithe	imithe	imigh-A	Av
,	,	,-F	Fi
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
sé	sé	sé-P	Pp3msn
,	,	,-F	Fi
a	a	a-U	U
rí	rí	rígh-N	Nv
?	?	?-F	Fq
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
liom	liom	le-P	Pr1-s
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcnoc	gcnoc	cnoc-N	Ncmsc
,	,	,-F	Fi
An	An	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
againn	againn	ag-P	Pr1-p
ag	ag	ag-S	Sp
rith	rith	rith-N	Nv
,	,	,-F	Fi
Ach	Ach	ach-C	Cs
anois	anois	anois-R	Rt
níl	níl	bí-V	Vmip---n
tuairisc	tuairisc	tuairisc-N	Ncfsc
air	air	ar-N	Ncmsg
Áit	Áit	áit-N	Ncfsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
éist	éist	éist-V	Vmm-2s
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
le	le	le-S	Sp
scéal	scéal	scéal-N	Ncmsc
Rírá	Rírá	rírá-N	Ncmsg
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
shuigh	shuigh	suigh-V	Vmis
sé	sé	sé-P	Pp3msn
siar	siar	siar-R	Rd
ina	ina	i-S	Spp-s|Spp-p
ríchathaoir	ríchathaoir	ríchathaoir-N	Ncfsc
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
smaoineamh	smaoineamh	smaoinigh-N	Nv
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
nár	nár	is-W	Wsdin
tháinig	tháinig	tar-V	Vmis
aon	aon	aon-D	Dq
smaoineamh	smaoineamh	smaoineamh-N	Ncmsc
chuige	chuige	chuig-P	Pr3ms
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
:	:	:-F	Fi
Níl	Níl	bí-V	Vmip---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
a	a	a-D	Dp3
shióigín	shióigín	sióigín-N	Ncmsc
,	,	,-F	Fi
níl	níl	bí-V	Vmip---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
faraor	faraor	faraor-X	Xsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
ag	ag	ag-S	Sp
sióga	sióga	sióg-N	Ncfpc
na	na	na-T	Td-p
gcnoc	gcnoc	cnoc-N	Ncmpg
,	,	,-F	Fi
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
réiteach	réiteach	réitigh-N	Ncmsc|Nv
do	do	do-S	Sp
scéil	scéil	scéal-N	Ncmsg
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
siadsan	siadsan	siad-P	Pp3-pne
níos	níos	níos-U	Uc
airde	airde	ard-A	Aqc
,	,	,-F	Fi
níos	níos	níos-U	Uc
airde	airde	ard-A	Aqc
sa	sa	i-S	Spa-s
spéir	spéir	spéir-N	Ncfsc
,	,	,-F	Fi
Os	Os	os-S	Sp
cionn	cionn	ceann-N	Ncfsd
páirce	páirce	páirc-N	Ncfsg
is	is	agus-C	Cc
talún	talún	talamh-N	Ncfsg
,	,	,-F	Fi
os	os	os-N	Ncmsc|Sp
ár	ár	ár-N	Ncmsc|Dp1-p
gcionn	gcionn	ceann-N	Ncfsd
go	go	go-U	Ua
léir	léir	léir-A	Aqp
!	!	!-F	Fe
‘	‘	‘-X	Xx
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
maith	maith	maith-N	Ncfsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Rírá	Rírá	rírá-N	Ncmsc
agus	agus	agus-C	Cc
bhuail	bhuail	buail-V	Vmis
sé	sé	sé-P	Pp3msn
bóthar	bóthar	bóthar-N	Ncmsc
ag	ag	ag-S	Sp
lorg	lorg	lorg-N	Nv
áit	áit	áit-N	Ncfsc
chónaithe	chónaithe	cónaigh-A	Av
shióga	shióga	sióg-N	Ncfpc
na	na	na-T	Td-p
gcnoc	gcnoc	cnoc-N	Ncmpg
.	.	.-F	Fe
Thóg	Thóg	tóg-V	Vmis
sé	sé	sé-P	Pp3msn
tamall	tamall	tamall-N	Ncmsc
air	air	ar-N	Ncmsg
teacht	teacht	tar-N	Ncmsc|Nv
ar	ar	ar-S	Sp
áit	áit	áit-N	Ncfsc
chónaithe	chónaithe	cónaigh-A	Av
shióga	shióga	sióg-N	Ncfpc
na	na	na-T	Td-p
gcnoc	gcnoc	cnoc-N	Ncmpg
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhain	bhain	bain-V	Vmis
sé	sé	sé-P	Pp3msn
amach	amach	amach-R	Rd
an	an	an-T	Td-s
áit	áit	áit-N	Ncfsc
ar	ar	ar-S	Sp
deireadh	deireadh	deireadh-N	Ncmsc
shiúil	shiúil	siúil-V	Vmis
sé	sé	sé-P	Pp3msn
tríd	tríd	trí-S	Sp
an	an	an-T	Td-s
bhfraoch	bhfraoch	fraoch-N	Ncmsc
agus	agus	agus-C	Cc
tríd	tríd	trí-S	Sp
an	an	an-T	Td-s
aiteann	aiteann	aiteann-N	Ncmsc
nó	nó	nó-C	Cc
gur	gur	gur-Q	Q--s
tháinig	tháinig	tar-V	Vmis
sé	sé	sé-P	Pp3msn
chomh	chomh	chomh-R	Ri
fada	fada	fada-A	Aqp
leis	leis	le-S	Sp
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
sé	sé	sé-P	Pp3msn
den	den	de-S	Spa-s
rí	rí	rí-N	Ncmsc
an	an	an-Q	Qq
raibh	raibh	bí-V	Vmis---d
aon	aon	aon-D	Dq
tuairim	tuairim	tuairim-N	Ncfsc
aige	aige	ag-P	Pr3ms
cá	cá	cá-R	Rq
raibh	raibh	bí-V	Vmis---d
Ruaille	Ruaille	ruaille-N	Ns-s
Buaille	Buaille	Buaille-N	Npmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
éist	éist	éist-V	Vmm-2s
rí	rí	rí-N	Ncmsc
shióga	shióga	sióg-N	Ncfpc
na	na	na-T	Td-p
gcnoc	gcnoc	cnoc-N	Ncmpg
le	le	le-S	Sp
scéal	scéal	scéal-N	Ncmsc
Rírá	Rírá	rírá-N	Ncmsg
agus	agus	agus-C	Cc
ansin	ansin	ansin-R	Rt|Rl
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
:	:	:-F	Fi
Níl	Níl	bí-V	Vmip---n
aithne	aithne	aithne-N	Ncfsc
agam	agam	ag-P	Pr1-s
ar	ar	ar-S	Sp
Ruaille	Ruaille	ruaille-N	Ns-s
Buaille	Buaille	Buaille-N	Npmsc
,	,	,-F	Fi
a	a	a-U	Uv
stór	stór	stór-N	Ncmsv
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
thírse	thírse	tír-N	Ncfsc-e
atá	atá	bí-V	Vmip---r
sé	sé	sé-P	Pp3msn
,	,	,-F	Fi
ach	ach	ach-C	Cs
guím	guím	guigh-V	Vmip1s
ort	ort	ar-P	Pr2-s
ádh	ádh	ádh-N	Ncmsc
mór	mór	mór-A	Aq-msc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an-díomá	an-díomá	díomá-N	Ncfsc
ar	ar	ar-S	Sp
Rírá	Rírá	rírá-N	Ncmsc
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
taisteal	taisteal	taistil-N	Nv
ar ais	ar ais	ar_ais-R	Rd
go	go	go-S	Sp
Ceann	Ceann	ceann-N	Ncmsc
Tíre	Tíre	tír-N	Ncfsg
.	.	.-F	Fe
Shiúil	Shiúil	siúil-V	Vmis
sé	sé	sé-P	Pp3msn
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
bpálás	bpálás	pálás-N	Ncmsc
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsg
arís	arís	arís-R	Rg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
trua	trua	trua-N	Ncfsc
ag	ag	ag-S	Sp
rí	rí	rígh-N	Nv
na	na	na-T	Td-p
sióg	sióg	sióg-N	Ncfpg
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Inis	Inis	inis-V	Vmis
do	do	do-S	Sp
scéal	scéal	scéal-N	Ncmsc
dom	dom	do-P	Pr1-s
,	,	,-F	Fi
inis	inis	inis-V	Vmm-2s|Vmis
é	é	é-P	Pp3ms
arís	arís	arís-R	Rg
,	,	,-F	Fi
agus	agus	agus-C	Cc
b	b	b-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
go	go	go-Q	Q
bhfeicfinn	bhfeicfinn	feic-V	Vmc-1s
do	do	do-S	Sp
chara	chara	cara-N	Ncmsc
i	i	i-S	Sp
bhfís	bhfís	fís-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
Ag	Ag	ag-S	Sp
súgradh	súgradh	súgradh-N	Nv-----n
a	a	a-Q	Q-r
bhíomar	bhíomar	bí-V	Vmis1p
,	,	,-F	Fi
Ag	Ag	ag-S	Sp
súgradh	súgradh	súgradh-N	Nv-----n
is	is	agus-C	Cc
ag	ag	ag-S	Sp
spraoi	spraoi	spraoi-N	Nv-----n
.	.	.-F	Fe
Anois	Anois	anois-R	Rt
tá	tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
imithe	imithe	imigh-A	Av
,	,	,-F	Fi
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
sé	sé	sé-P	Pp3msn
,	,	,-F	Fi
a	a	a-U	U
rí	rí	rígh-N	Nv
?	?	?-F	Fq
Bhíomar	Bhíomar	bí-V	Vmis1p
ag	ag	ag-S	Sp
iascach	iascach	iasc-N	Nv
,	,	,-F	Fi
Ansiúd	Ansiúd	ansiúd-R	Rl
inár	inár	i-S	Spp-p
suí	suí	suí-N	Ncmsc
,	,	,-F	Fi
Anois	Anois	anois-R	Rt
táim	táim	bí-V	Vmip1s
ag	ag	ag-S	Sp
éirí	éirí	éirigh-N	Nv
‑	‑	‑-F	Fb
bhuartha	bhuartha	buair-A	Av
faoi	faoi	faoi-P	Pr3ms
.	.	.-F	Fe
Shuigh	Shuigh	suigh-V	Vmis
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
siar	siar	siar-R	Rd
sa	sa	i-S	Spa-s
ríchathaoir	ríchathaoir	ríchathaoir-N	Ncfsc
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
smaoineamh	smaoineamh	smaoinigh-N	Nv
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
cúpla	cúpla	cúpla-N	Ncmsg
nóiméad	nóiméad	nóiméad-N	Ncmpg|Ncmsc|Ncmpg
labhair	labhair	labhair-V	Vmis
sé	sé	sé-P	Pp3msn
:	:	:-F	Fi
Níl	Níl	bí-V	Vmip---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
a	a	a-D	Dp3
shióigín	shióigín	sióigín-N	Ncmsc
,	,	,-F	Fi
níl	níl	bí-V	Vmip---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
faraor	faraor	faraor-X	Xsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
ag	ag	ag-S	Sp
sióga	sióga	sióg-N	Ncfpc
na	na	na-T	Tdfsg
farraige	farraige	farraige-N	Ncfsg
,	,	,-F	Fi
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
réiteach	réiteach	réitigh-N	Ncmsc|Nv
do	do	do-S	Sp
scéil	scéil	scéal-N	Ncmsg
!	!	!-F	Fe
Más	Más	má-C	Csw
ag	ag	ag-S	Sp
iascach	iascach	iasc-N	Nv
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
,	,	,-F	Fi
a	a	a-D	Dp3
shióigín	shióigín	sióigín-N	Ncmsc
bhinn	bhinn	binn-A	Aq-msc
,	,	,-F	Fi
Faoin	Faoin	faoi-S	Spa-s
bhfarraige	bhfarraige	farraige-N	Ncfsc
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
sé	sé	sé-P	Pp3msn
,	,	,-F	Fi
ní	ní	ní-W	Wp-in|Nv|Ncmsc
thuas	thuas	tuaigh-R	Rd|Vmip---r
anseo	anseo	anseo-R	Rl
linn	linn	le-P	Pr1-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
maith	maith	maith-N	Ncfsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Rírá	Rírá	rírá-N	Ncmsc
agus	agus	agus-C	Cc
bhuail	bhuail	buail-V	Vmis
sé	sé	sé-P	Pp3msn
bóthar	bóthar	bóthar-N	Ncmsc
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
cuardach	cuardach	cuardaigh-N	Nv
shióga	shióga	sióg-N	Ncfpc
na	na	na-T	Tdfsg
farraige	farraige	farraige-N	Ncfsg
.	.	.-F	Fe
Síos	Síos	síos-R	Rd
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
trá	trá	trá-N	Ncfsc
leis	leis	le-P	Pr3ms
agus	agus	agus-C	Cc
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
bpluais	bpluais	pluais-N	Ncfsc
san	san	i-S	Spa-s
aill	aill	aill-N	Ncfsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
éist	éist	éist-V	Vmm-2s
rí	rí	rí-N	Ncmsc
shióga	shióga	sióg-N	Ncfpc
na	na	na-T	Tdfsg
farraige	farraige	farraige-N	Ncfsg
le	le	le-S	Sp
scéal	scéal	scéal-N	Ncmsc
Rírá	Rírá	rírá-N	Ncmsg
ach	ach	ach-C	Cs
ansin	ansin	ansin-R	Rt|Rl
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
:	:	:-F	Fi
Níl	Níl	bí-V	Vmip---n
aithne	aithne	aithne-N	Ncfsc
agam	agam	ag-P	Pr1-s
ar	ar	ar-S	Sp
Ruaille	Ruaille	ruaille-N	Ns-s
Buaille	Buaille	Buaille-N	Npmsc
,	,	,-F	Fi
a	a	a-U	Uv
stór	stór	stór-N	Ncmsv
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
thírse	thírse	tír-N	Ncfsc-e
atá	atá	bí-V	Vmip---r
sé	sé	sé-P	Pp3msn
,	,	,-F	Fi
ach	ach	ach-C	Cs
guím	guím	guigh-V	Vmip1s
ort	ort	ar-P	Pr2-s
ádh	ádh	ádh-N	Ncmsc
mór	mór	mór-A	Aq-msc
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
an-díomá	an-díomá	díomá-N	Ncfsc
ar	ar	ar-S	Sp
Rírá	Rírá	rírá-N	Ncmsc
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
taisteal	taisteal	taistil-N	Nv
ar ais	ar ais	ar_ais-R	Rd
go	go	go-S	Sp
Ceann	Ceann	ceann-N	Ncmsc
Tíre	Tíre	tír-N	Ncfsg
.	.	.-F	Fe
Shiúil	Shiúil	siúil-V	Vmis
sé	sé	sé-P	Pp3msn
ar ais	ar ais	ar_ais-R	Rd
go dtí	go dtí	go_dtí-S	Spc
pálás	pálás	pálás-N	Ncmsc
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsg
arís	arís	arís-R	Rg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
trua	trua	trua-N	Ncfsc
ag	ag	ag-S	Sp
rí	rí	rígh-N	Nv
na	na	na-T	Td-p
sióg	sióg	sióg-N	Ncfpg
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Inis	Inis	inis-V	Vmis
do	do	do-S	Sp
scéal	scéal	scéal-N	Ncmsc
dom	dom	do-P	Pr1-s
,	,	,-F	Fi
inis	inis	inis-V	Vmm-2s|Vmis
é	é	é-P	Pp3ms
arís	arís	arís-R	Rg
,	,	,-F	Fi
agus	agus	agus-C	Cc
b	b	b-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
go	go	go-Q	Q
bhfeicfinn	bhfeicfinn	feic-V	Vmc-1s
do	do	do-S	Sp
chara	chara	cara-N	Ncmsc
i	i	i-S	Sp
bhfís	bhfís	fís-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
Ag	Ag	ag-S	Sp
súgradh	súgradh	súgradh-N	Nv-----n
a	a	a-Q	Q-r
bhíomar	bhíomar	bí-V	Vmis1p
,	,	,-F	Fi
Ag	Ag	ag-S	Sp
súgradh	súgradh	súgradh-N	Nv-----n
is	is	agus-C	Cc
ag	ag	ag-S	Sp
spraoi	spraoi	spraoi-N	Nv-----n
.	.	.-F	Fe
Anois	Anois	anois-R	Rt
tá	tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
imithe	imithe	imigh-A	Av
,	,	,-F	Fi
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
sé	sé	sé-P	Pp3msn
,	,	,-F	Fi
a	a	a-U	U
rí	rí	rígh-N	Nv
?	?	?-F	Fq
Bhíomar	Bhíomar	bí-V	Vmis1p
ag	ag	ag-S	Sp
scipeáil	scipeáil	scipeáil-N	Nv
Is	Is	is-W	Wpri
ag	ag	ag-S	Sp
damhsa	damhsa	damhsaigh-N	Nv
san	san	sin-S	Spa-s|Pd
aer	aer	aer-N	Ncmpg|Ncmsc
,	,	,-F	Fi
Anois	Anois	anois-R	Rt
tá	tá	bí-V	Vmip
mise	mise	mé-P	Pp1-s-e
Liom	Liom	le-P	Pr1-s
féin	féin	féin-P	Px
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhféar	bhféar	féar-N	Ncmsc
.	.	.-F	Fe
Shuigh	Shuigh	suigh-V	Vmis
rí	rí	rí-N	Ncmsc
na	na	na-T	Td-p
sióg	sióg	sióg-N	Ncfpg
siar	siar	siar-R	Rd
sa	sa	i-S	Spa-s
ríchathaoir	ríchathaoir	ríchathaoir-N	Ncfsc
arís	arís	arís-R	Rg
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
smaoineamh	smaoineamh	smaoinigh-N	Nv
.	.	.-F	Fe
Níl	Níl	bí-V	Vmip---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
a	a	a-D	Dp3
shióigín	shióigín	sióigín-N	Ncmsc
,	,	,-F	Fi
atá	atá	bí-V	Vmip---r
tagtha	tagtha	tar-A	Av
ar	ar	ar-S	Sp
an	an	an-T	Td-s
saol	saol	saol-N	Ncmsc
.	.	.-F	Fe
B	B	B-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
gur	gur	is-W	Wsdi|Wpdi
ag	ag	ag-S	Sp
sióga	sióga	sióg-N	Ncfpc
na	na	na-T	Tdfsg
gealaí	gealaí	gealach-N	Ncfsg
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
réiteach	réiteach	réitigh-N	Ncmsc|Nv
do	do	do-S	Sp
scéil	scéil	scéal-N	Ncmsg
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
Rírá	Rírá	rírá-N	Ncmsc
bocht	bocht	bocht-A	Aq-msc
ag	ag	ag-S	Sp
éirí	éirí	éirigh-N	Nv
tuirseach	tuirseach	tuirseach-A	Aqp
faoin	faoin	faoi-S	Spa-s
am	am	am-N	Ncmsc
seo	seo	seo-D	Dd
ach	ach	ach-C	Cs
bhuail	bhuail	buail-V	Vmis
sé	sé	sé-P	Pp3msn
bóthar	bóthar	bóthar-N	Ncmsc
ag	ag	ag-S	Sp
cuardach	cuardach	cuardaigh-N	Nv
áit	áit	áit-N	Ncfsc
chónaithe	chónaithe	cónaigh-A	Av
shióga	shióga	sióg-N	Ncfpc
na	na	na-T	Tdfsg
gealaí	gealaí	gealach-N	Ncfsg
.	.	.-F	Fe
Shiúil	Shiúil	siúil-V	Vmis
sé	sé	sé-P	Pp3msn
suas	suas	suas-R	Rd
go	go	go-S	Sp
barr	barr	barr-N	Ncmsc
an	an	an-T	Td-s
chnoic	chnoic	cnoc-N	Ncmsg
ab	ab	is-U	U
airde	airde	ard-A	Aqc
i	i	i-S	Sp
gCeann	gCeann	ceann-N	Ncmsc
Tíre	Tíre	tír-N	Ncfsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
chomh	chomh	chomh-R	Ri
gar	gar	gar-A	Aqp
don	don	do-S	Spa-s
ghealach	ghealach	gealach-N	Ncfsc
is	is	agus-C	Cc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
in ann	in ann	in_ann-S	Spc
labhairt	labhairt	labhair-N	Nv
le	le	le-S	Sp
rí	rí	rígh-N	Nv
shióga	shióga	sióg-N	Ncfpc
na	na	na-T	Tdfsg
gealaí	gealaí	gealach-N	Ncfsg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
sé	sé	sé-P	Pp3msn
den	den	de-S	Spa-s
rí	rí	rí-N	Ncmsc
an	an	an-Q	Qq
raibh	raibh	bí-V	Vmis---d
aon	aon	aon-D	Dq
tuairim	tuairim	tuairim-N	Ncfsc
aige	aige	ag-P	Pr3ms
cá	cá	cá-R	Rq
raibh	raibh	bí-V	Vmis---d
Ruaille	Ruaille	ruaille-N	Ns-s
Buaille	Buaille	Buaille-N	Npmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
éist	éist	éist-V	Vmm-2s
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
agus	agus	agus-C	Cc
ansin	ansin	ansin-R	Rt|Rl
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
:	:	:-F	Fi
Níl	Níl	bí-V	Vmip---n
aithne	aithne	aithne-N	Ncfsc
agam	agam	ag-P	Pr1-s
ar	ar	ar-S	Sp
Ruaille	Ruaille	ruaille-N	Ns-s
Buaille	Buaille	Buaille-N	Npmsc
,	,	,-F	Fi
a	a	a-U	Uv
stór	stór	stór-N	Ncmsv
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
thírse	thírse	tír-N	Ncfsc-e
atá	atá	bí-V	Vmip---r
sé	sé	sé-P	Pp3msn
,	,	,-F	Fi
ach	ach	ach-C	Cs
guím	guím	guigh-V	Vmip1s
ort	ort	ar-P	Pr2-s
ádh	ádh	ádh-N	Ncmsc
mór	mór	mór-A	Aq-msc
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
tuirse	tuirse	tuirse-N	Ncfsc
agus	agus	agus-C	Cc
díomá	díomá	díomá-N	Ncfsg|Ncfsc
ar	ar	ar-S	Sp
Rírá	Rírá	rírá-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
oíche	oíche	oíche-N	Ncfsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
caite	caite	caith-A	Av
aige	aige	ag-P	Pr3ms
ag	ag	ag-S	Sp
cuardach	cuardach	cuardaigh-N	Nv
Ruaille	Ruaille	ruaill-N	Ncfsg
Buaille	Buaille	Buaille-N	Npmsc
ach	ach	ach-S	Sp
tásc	tásc	tásc-N	Ncmsc
ná	ná	ná-C	Cs|Cc
tuairisc	tuairisc	tuairisc-N	Ncfsc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
air	air	ar-P	Pr3ms
in	in	i-S	Sp
aon	aon	aon-D	Dq
áit	áit	áit-N	Ncfsc
.	.	.-F	Fe
Shuigh	Shuigh	suigh-V	Vmis
sé	sé	sé-P	Pp3msn
síos	síos	síos-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhféar	bhféar	féar-N	Ncmsc
,	,	,-F	Fi
gan	gan	gan-S	Sp
tuairim	tuairim	tuairim-N	Ncfsc
na	na	na-T	Td-p
ngrást	ngrást	grásta-N	Ncmpg
aige	aige	ag-P	Pr3ms
cad	cad	cad-P	Pq
a	a	a-Q	Q-r
dhéanfadh	dhéanfadh	déan-V	Vmc
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Chrom	Chrom	crom-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
cheann	cheann	ceann-N	Ncmsc
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
caoineadh	caoineadh	caoin-N	Nv
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
ghrian	ghrian	grian-V	Vmis
ag	ag	ag-S	Sp
éirí	éirí	éirigh-N	Nv
san	san	sin-S	Spa-s|Pd
oirthear	oirthear	oirthear-N	Ncmpg|Ncmsc
.	.	.-F	Fe
Diaidh	Diaidh	diaidh-N	Ns-s
ar	ar	ar-S	Sp
ndiaidh	ndiaidh	diaidh-N	Ns-s
chuaigh	chuaigh	téigh-V	Vmis
na	na	na-T	Td-p
réaltaí	réaltaí	réalta-N	Ncfpc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
ghealach	ghealach	gealach-N	Ncfsc
i	i	i-S	Sp
bhfolach	bhfolach	folach-N	Ncmsc
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
ghrian	ghrian	grian-V	Vmis
a	a	a-D	Dp3
ceann	ceann	ceann-N	Ncmsc
aníos	aníos	aníos-R	Rd
de	de	de-S	Sp
dhroim	dhroim	droim-N	Ncmsc
na	na	na-T	Td-p
gcnoc	gcnoc	cnoc-N	Ncmpg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmm-2s
Rírá	Rírá	rírá-N	Ncmsc
as	as	as-S	Sp
an	an	an-T	Td-s
ngol	ngol	gol-N	Ncmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhraith	bhraith	braith-V	Vmis
sé	sé	sé-P	Pp3msn
teas	teas	teas-N	Ncmsc
na	na	na-T	Tdfsg
gréine	gréine	grian-N	Ncfsg
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
shúile	shúile	súil-N	Ncfpc
cé	cé	cé-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
in aice	in aice	in_aice-S	Spc
leis	leis	le-P	Pr3ms
ach	ach	ach-C	Cs
…	…	…-F	Fi
Ruaille	Ruaille	ruaille-N	Ns-s
Buaille	Buaille	Buaille-N	Npmsc
!	!	!-F	Fe
Amuigh	Amuigh	amuigh-R	Rl
ag	ag	ag-S	Sp
súgradh	súgradh	súgradh-N	Nv-----n
a	a	a-Q	Q-r
chaitheadar	chaitheadar	caith-V	Vmis3p
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
,	,	,-F	Fi
ag	ag	ag-S	Sp
rith	rith	rith-N	Nv
siar	siar	siar-R	Rd
is	is	agus-C	Cc
aniar	aniar	aniar-A	Aqp|Rd
,	,	,-F	Fi
agus	agus	agus-C	Cc
suas	suas	suas-R	Rd
is	is	agus-C	Cc
anuas	anuas	anuas-R	Rd
,	,	,-F	Fi
.	.	.-F	Fe
ag	ag	ag-S	Sp
iascach	iascach	iasc-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
loch	loch	loch-N	Ncmsc
is	is	is-W	Wpri
ag	ag	ag-S	Sp
scipeáil	scipeáil	scipeáil-N	Nv
tríd	tríd	trí-S	Sp
an	an	an-T	Td-s
aer	aer	aer-N	Ncmsc
.	.	.-F	Fe
Nach	Nach	is-W	Wpsin
acu	acu	ag-P	Pr3-p
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
spórt	spórt	spórt-N	Ncmsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
spraoi	spraoi	spraoi-N	Ncmsg
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
aoibhinn	aoibhinn	aoibhinn-A	Aq-msc
gréine	gréine	grian-N	Ncfsg
úd	úd	úd-D	Dd
!	!	!-F	Fe
Agus	Agus	agus-C	Cc
Rírá	Rírá	rírá-N	Ncmsc
agus	agus	agus-C	Cc
Ruaille	Ruaille	ruaille-N	Ncfsg|Ns-s|Ncfsg|Ns-s
Buaille	Buaille	Buaille-N	Npmsc
ag	ag	ag-S	Sp
rith	rith	rith-N	Nv
ar nós	ar nós	ar_nós-S	Spc
na	na	na-T	Tdfsg
gaoithe	gaoithe	gaoth-N	Ncfsg
síos	síos	síos-R	Rd
an	an	an-T	Td-s
cnoc	cnoc	cnoc-N	Ncmsc
bhuail	bhuail	buail-V	Vmis
siad	siad	siad-P	Pp3-pn
le	le	le-S	Sp
,	,	,-F	Fi
rí	rí	rí-N	Ncmsc
na	na	na-T	Td-p
sióg	sióg	sióg-N	Ncfpg
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
aon	aon	aon-D	Dq
tásc	tásc	tásc-N	Ncmsc
nó	nó	nó-C	Cc
tuairisc	tuairisc	tuairisc-N	Ncfsc
ar	ar	ar-W	Wsdq|Ws-q|Wssi|Wpdi|Wpsi|Sp|Ncmsc
do	do	do-S	Sp
chara	chara	cara-N	Ncmsc
Ruaille	Ruaille	ruaill-N	Ncfsg
Buaille	Buaille	Buaille-N	Npmsc
?	?	?-F	Fq
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
rí	rí	rí-N	Ncmsc
na	na	na-T	Td-p
sióg	sióg	sióg-N	Ncfpg
de	de	de-S	Sp
Rírá	Rírá	rírá-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
anseo	anseo	anseo-R	Rl
in aice	in aice	in_aice-S	Spc
liom	liom	le-P	Pr1-s
.	.	.-F	Fe
Nach	Nach	nach-Q	Qnr
bhfeiceann	bhfeiceann	feic-V	Vmip
tú	tú	tú-P	Pp2-s
é	é	é-P	Pp3ms
!	!	!-F	Fe
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
Rírá	Rírá	rírá-N	Ncmsc
leis	leis	le-P	Pr3ms
,	,	,-F	Fi
ag	ag	ag-S	Sp
sméideadh	sméideadh	sméid-N	Nv
a	a	a-Q	Q-r
chinn	chinn	cinn-V	Vmis
i	i	i-S	Sp
dtreo	dtreo	treo-N	Ncmsc
Ruaille	Ruaille	ruaill-N	Ncfsg
Buaille	Buaille	Buaille-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
fheicimse	fheicimse	feic-V	Vmip1s-ne
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
feicim	feicim	feic-V	Vmip1s
do	do	do-S	Sp
scáil	scáil	scáil-N	Ncmpc|Ncfsc
ina	ina	i-S	Spp-s|Spp-p
luí	luí	luí-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhféar	bhféar	féar-N	Ncmsc
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
A	A	an-T	Td-s
shióigín	shióigín	sióigín-N	Ncmsc
,	,	,-F	Fi
atá	atá	bí-V	Vmip---r
tagtha	tagtha	tar-A	Av
ar	ar	ar-S	Sp
an	an	an-T	Td-s
saol	saol	saol-N	Ncmsc
,	,	,-F	Fi
Tá	Tá	bí-V	Vmip
scáil	scáil	scál-N	Ncfsc|Ncmpc
ag	ag	ag-S	Sp
gach	gach	gach-D	Dq
sióigín	sióigín	sióigín-N	Ncmsc
amuigh	amuigh	amuigh-R	Rl
faoin	faoin	faoi-S	Spa-s
ngrian	ngrian	grian-N	Ncmsc|Ncfsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	is-W	Wp-in
fheictear	fheictear	feic-V	Vmip0
an	an	an-T	Td-s
scáil	scáil	scáil-N	Ncfsc
riamh	riamh	riamh-R	Rg
san	san	i-S	Spa-s
oíche	oíche	oíche-N	Ncfsc
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhíonn	bhíonn	bí-V	Vmig
an	an	an-T	Td-s
ghrian	ghrian	grian-N	Ncfsc
bhuí	bhuí	buí-A	Aqp
dulta	dulta	téigh-A	Av
ag	ag	ag-S	Sp
luí	luí	luigh-N	Nv
.	.	.-F	Fe
A	A	an-T	Td-s
fhad	fhad	fad-N	Ncmsc
is	is	agus-C	Cc
a	a	a-Q	Q-r
bheidh	bheidh	bí-V	Vmif
grian	grian	grian-N	Ncmsc|Ncfsc
ag	ag	ag-S	Sp
taitneamh	taitneamh	taitin-N	Nv
,	,	,-F	Fi
is	is	is-W	Wpri
ag	ag	ag-S	Sp
scairteadh	scairteadh	scairt-N	Nv
go	go	go-U	Ua
beo	beo	beo-A	Aqp
,	,	,-F	Fi
Beidh	Beidh	bí-V	Vmif
dlúthchara	dlúthchara	cara-N	Ncmsc
buan	buan	buan-A	Aq-msc
agat	agat	ag-P	Pr2-s
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
is	is	agus-C	Cc
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
.	.	.-F	Fe
Seo	Seo	seo-W	W
libh	libh	le-P	Pr2-p
anois	anois	anois-R	Rt
,	,	,-F	Fi
a	a	a-U	Uv
chairde	chairde	cara-N	Ncmsv|Ncmpv
,	,	,-F	Fi
mo	mo	mo-D	Dp1-s
chroí	chroí	croí-N	Ncmsc
,	,	,-F	Fi
Bainigí	Bainigí	bain-V	Vmm-2p
sult	sult	sult-N	Ncmsc
agus	agus	agus-C	Cc
spraoi	spraoi	spraoi-N	Ncmsc|Nv-----n|Nv--g--n|Ncmsg|Nv-----n|Ncmsg|Nv--g--n|Nv-----n
as	as	as-S	Sp
an	an	an-T	Td-s
ngrian	ngrian	grian-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
bhuí	bhuí	buí-A	Aqp
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
siúd	siúd	siúd-P	Pd
le	le	le-S	Sp
Rírá	Rírá	rírá-N	Ncmsc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
scáil	scáil	scál-N	Ncfsc|Ncmpc
,	,	,-F	Fi
Ruaille	Ruaille	ruaille-N	Ns-s
Buaille	Buaille	Buaille-N	Npmsc
,	,	,-F	Fi
ag	ag	ag-S	Sp
rith	rith	rith-N	Nv
siar	siar	siar-R	Rd
is	is	is-W	Wpri
aniar	aniar	aniar-A	Aqp
agus	agus	agus-C	Cc
suas	suas	suas-R	Rd
is	is	is-W	Wpri
anuas	anuas	anuas-R	Rd
,	,	,-F	Fi
ag	ag	ag-S	Sp
baint	baint	bain-N	Nv
taitnimh	taitnimh	taitin-N	Ncmsg|Nv--g
,	,	,-F	Fi
suilt	suilt	sult-N	Ncmpc
agus	agus	agus-C	Cc
spraoi	spraoi	spraoi-N	Ncmsc|Nv-----n|Nv--g--n|Ncmsg|Nv-----n|Ncmsg|Nv--g--n|Nv-----n
as	as	as-S	Sp
lá	lá	lá-N	Ncmsc
aoibhinn	aoibhinn	aoibhinn-A	Aq-msc
gréine	gréine	grian-N	Ncfsg
a	a	a-U	U
chaitheamh	chaitheamh	caith-N	Nv
i gcuideachta	i gcuideachta	i_gcuideachta-S	Spc
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
!	!	!-F	Fe
