 3	3	-X	Xx
Cian	Cian	Cian-N	Npmsc
iníon	iníon	iníon-N	Ncfsc
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
rí	rí	rí-N	Ncmsc
ina	ina	i-S	Spp-s
chónaí	chónaí	cónaí-N	Ncmsc
i	i	i-S	Sp
dTeamhair	dTeamhair	teamhair-N	Ncfsc
lena	lena	le-S	Spp-s
bhean	bhean	bean-N	Ncfsc
agus	agus	agus-C	Cc
lena	lena	le-S	Spp-s
iníon	iníon	iníon-N	Ncfsc
,	,	,-F	Fi
Róisín	Róisín	Róisín-N	Npfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
saibhreas	saibhreas	saibhreas-N	Ncmsc
an	an	an-T	Td-s
tsaoil	tsaoil	saol-N	Ncmsg
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Níor	Níor	is-W	Ws-in
ghá	ghá	gá-N	Ncmsc
dóibh	dóibh	do-P	Pr3-p
aon	aon	aon-D	Dq
obair	obair	obair-N	Ncfsc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
.	.	.-F	Fe
Bhíodh	Bhíodh	bí-V	Vmih
siad	siad	siad-P	Pp3-pn
‑	‑	‑-F	Fb
ghléasta	ghléasta	gléas-A	Av
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
togha	togha	togha-N	Ncmsc
gach	gach	gach-D	Dq
bia	bia	bia-N	Ncmsc
agus	agus	agus-C	Cc
rogha	rogha	rogha-N	Ncfsg|Ncfsc|Ncfsg
gach	gach	gach-D	Dq
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
baile	baile	baile-N	Ncmsc
beag	beag	beag-A	Aq-msc
bocht	bocht	bocht-A	Aq-msc
taobh amuigh	taobh amuigh	taobh_amuigh-R	Rl
den	den	de-S	Spa-s
dún	dún	dún-N	Ncmsc
.	.	.-F	Fe
Na	Na	na-T	Td-p
daoine	daoine	duine-N	Ncmpc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ina	ina	i-S	Spp-p
gcónaí	gcónaí	cónaí-N	Ncmsc
ansin	ansin	ansin-R	Rt
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ach	ach	ach-C	Cs
ón	ón	ó-S	Spa-s
lámh	lámh	lámh-N	Ncfsc
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
béal	béal	béal-N	Ncmsc
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
bhanríon	bhanríon	banríon-N	Ncfsc
chuige	chuige	chuig-P	Pr3ms
nach	nach	nach-Q	Qnr
bhfeicfeadh	bhfeicfeadh	feic-V	Vmc
Róisín	Róisín	Róisín-N	Npfsc
páistí	páistí	páiste-N	Ncmpc
bochta	bochta	bocht-A	Aq--pc
an	an	an-T	Td-s
bhaile	bhaile	baile-N	Ncmsg
in	in	i-S	Sp
am	am	am-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
.	.	.-F	Fe
Bhíodh	Bhíodh	bí-V	Vmih
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
lena	lena	le-S	Spp-s
chuid	chuid	cuid-N	Ncfsc
laochra	laochra	laochra-N	Ncmpg|Ncmsg|Ncmpg|Ncmsg
gach	gach	gach-D	Dq
uile	uile	uile-N	Ns-s|Dq
lá	lá	lá-N	Ncmsc
,	,	,-F	Fi
ag	ag	ag-S	Sp
seilg	seilg	seilg-N	Nv
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
fiach	fiach	fiach-N	Nv
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
imirt	imirt	imir-N	Nv
.	.	.-F	Fe
Bhíodh	Bhíodh	bí-V	Vmih
an	an	an-T	Td-s
bhanríon	bhanríon	banríon-N	Ncfsc
leis	leis	le-S	Sp
na	na	na-T	Td-p
banfhlatha	banfhlatha	banfhlaith-N	Ncmpc
gach	gach	gach-D	Dq
uile	uile	uile-N	Ns-s|Dq
lá	lá	lá-N	Ncmsc
,	,	,-F	Fi
ag	ag	ag-S	Sp
sníomh	sníomh	sníomh-N	Nv
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
airneán	airneán	airneán-N	Ncmsc
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
ceol	ceol	ceol-N	Nv-----n
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
uaigneas	uaigneas	uaigneas-N	Ncmsc
ar	ar	ar-S	Sp
Róisín	Róisín	Róisín-N	Npfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
ina	ina	i-S	Spp-s
girseach	girseach	girseach-N	Ncfsc
ghleoite	ghleoite	gleoite-A	Aqp
ghnaíúil	ghnaíúil	gnaíúil-A	Aqp
.	.	.-F	Fe
De	De	de-S	Sp
bhrí	bhrí	brí-N	Ncfsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
saibhreas	saibhreas	saibhreas-N	Ncmsc
an	an	an-T	Td-s
tsaoil	tsaoil	saol-N	Ncmsg
ag	ag	ag-S	Sp
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
bhanríon	bhanríon	banríon-N	Ncfsc
níor	níor	níor-Q	Qn-s
fhág	fhág	fág-V	Vmis---n
siad	siad	siad-P	Pp3-pn
easpa	easpa	easpa-N	Ncfsc
ná	ná	ná-C	Cc
díth	díth	díth-N	Ncfsc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Fuair	Fuair	faigh-V	Vmis
siad	siad	siad-P	Pp3-pn
bréagáin	bréagáin	bréagán-N	Ncmpc
ón	ón	ó-S	Spa-s
Bhreatain	Bhreatain	Breatain-N	Npfsc
di	di	do-P	Pr3fs
.	.	.-F	Fe
Fuair	Fuair	faigh-V	Vmis
siad	siad	siad-P	Pp3-pn
capaill	capaill	capall-N	Ncmpc
ó	ó	ó-S	Sp
Chonamara	Chonamara	Conamara-N	Npmsc
di	di	do-P	Pr3fs
.	.	.-F	Fe
Fuair	Fuair	faigh-V	Vmis
siad	siad	siad-P	Pp3-pn
spíosraí	spíosraí	spíosra-N	Ncmpc
ón	ón	ó-S	Spa-s
Spáinn	Spáinn	Spáinn-N	Npfsc
di	di	do-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
bean	bean	bean-N	Ncfsc
choimhdeachta	choimhdeachta	coimhdeacht-N	Ncfsg
ag	ag	ag-S	Sp
tabhairt	tabhairt	tabhair-N	Nv
aire	aire	aire-N	Ncfsg|Ncmsg|Ncfsg
di	di	do-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
ollamh	ollamh	ollamh-N	Ncmsc
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
oideachais	oideachais	oideachas-N	Ncmsg
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
lia	lia	lia-A	Aqc
ab	ab	is-U	U
oilte	oilte	oilte-A	Aqc
sa	sa	i-S	Spa-s
tír	tír	tír-N	Ncfsc
ar	ar	ar-S	Sp
fáil	fáil	faigh-N	Nv
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
sa	sa	i-S	Spa-s
dún	dún	dún-N	Ncmsc
ar	ar	ar-S	Sp
eagla	eagla	eagla-N	Ncfsc
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
sí	sí	sí-P	Pp3fsn
tinn	tinn	tinn-A	Aqp
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
mhór	mhór	mór-A	Aqp
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
imní	imní	imní-N	Ncfsc
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsg
agus	agus	agus-C	Cc
na	na	na-T	Tdfsg
banríona	banríona	banríon-N	Ncfsg
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhraith	bhraith	braith-V	Vmis
siad	siad	siad-P	Pp3-pn
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
Róisín	Róisín	Róisín-N	Npfsc
sona	sona	sona-A	Aqp
.	.	.-F	Fe
Leoga	Leoga	leoga-X	Xsc
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
cian	cian	cian-N	Ncfsc|Ncmsc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
tuairim	tuairim	tuairim-N	Ncfsc
na	na	na-T	Td-p
ngrást	ngrást	grásta-N	Ncmpg
ag	ag	ag-S	Sp
an	an	an-T	Td-s
bhanríon	bhanríon	banríon-N	Ncfsc
ná	ná	ná-C	Cs|Cc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
as	as	as-N	Ncmpg|Ncmsc|Pr3ms|Sp
di	di	do-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
bhanríon	bhanríon	banríon-N	Ncfsc
ag	ag	ag-S	Sp
cailleadh	cailleadh	caill-N	Nv
foighne	foighne	foighne-N	Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nach	Nach	nach-Q	Qnr|Qnq
bhfuil	bhfuil	bí-V	Vmip---d|Vmip---n
tú	tú	tú-P	Pp2-s
in ann	in ann	in_ann-S	Spc
aon	aon	aon-D	Dq
rud	rud	rud-N	Ncmsc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
?	?	?-F	Fq
'	'	'-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
go	go	go-U	Ua
borb	borb	borb-A	Aqp
lena	lena	le-S	Spp-s
fear	fear	fear-N	Ncmsc
céile	céile	céile-N	Ncmsg|Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
réiteach	réiteach	réiteach-N	Ncmsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
.	.	.-F	Fe
Ghlaoigh	Ghlaoigh	glaoigh-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-N	Ncmsc
lia	lia	lia-A	Aqc
.	.	.-F	Fe
Ghlaoigh	Ghlaoigh	glaoigh-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
ollamh	ollamh	ollamh-N	Ncmsc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
ghlaoigh	ghlaoigh	glaoigh-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
choimhdeachta	choimhdeachta	coimhdeacht-N	Ncfsg
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
acusan	acusan	ag-P	Pr3-p-e
in ann	in ann	in_ann-S	Spc
aon	aon	aon-D	Dq
rud	rud	rud-N	Ncmsc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
di	di	do-P	Pr3fs
ach	ach	ach-S	Sp
oiread	oiread	oiread-N	Ns-s
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
i	i	i-S	Sp
ndeireadh	ndeireadh	deireadh-N	Ncmsc
na	na	na-T	Tdfsg
preibe	preibe	preab-N	Ncfsg
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
éigean	éigean	éigean-N	Ncmsc
má	má	má-C	Cs
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
bhanríon	bhanríon	banríon-N	Ncfsc
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
leis	leis	le-P	Pr3ms
a thuilleadh	a thuilleadh	a_thuilleadh-R	Rg
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
biseach	biseach	biseach-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
ar	ar	ar-S	Sp
Róisín	Róisín	Róisín-N	Npfsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
an	an	an-T	Td-s
dara	dara	dara-M	Mo
rogha	rogha	rogha-N	Ncfsc
aige	aige	ag-P	Pr3ms
ach	ach	ach-S	Sp
fógra	fógra	fógra-N	Ncmsc
a	a	a-U	U
chur	chur	cuir-N	Nv
amach	amach	amach-R	Rd
:	:	:-F	Fi
‘	‘	‘-X	Xx
Tabharfaidh	Tabharfaidh	tabhair-V	Vmif
mé	mé	mé-P	Pp1-s
ór	ór	ór-N	Ncmsc
agus	agus	agus-C	Cc
airgead	airgead	airgead-N	Ncmsc
d	d	d-X	Xl
’	’	’-F	Fa
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
atá	atá	bí-V	Vmip---r
in ann	in ann	in_ann-S	Spc
m	m	m-X	Xl
’	’	’-F	Fa
iníon	iníon	iníon-N	Ncfsc
a	a	a-U	U
leigheas	leigheas	leigheas-N	Nv
.	.	.-F	Fe
'	'	'-F	Fa
Tháinig	Tháinig	tar-V	Vmis
daoine	daoine	duine-N	Ncmpc
go	go	go-S	Sp
Teamhair	Teamhair	teamhair-N	Ncfsc
ó	ó	ó-S	Sp
gach	gach	gach-D	Dq
cearn	cearn	cearn-N	Ncfsc
den	den	de-S	Spa-s
tír	tír	tír-N	Ncfsc
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
siad	siad	siad-P	Pp3-pn
bronntanais	bronntanais	bronntanas-N	Ncmpc
chuici	chuici	chuig-P	Pr3fs
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
inis	inis	inis-V	Vmis
siad	siad	siad-P	Pp3-pn
scéalta	scéalta	scéal-N	Ncmpc
di	di	do-P	Pr3fs
.	.	.-F	Fe
Chan	Chan	can-V	Vmis
siad	siad	siad-P	Pp3-pn
amhráin	amhráin	amhrán-N	Ncmpc
di	di	do-P	Pr3fs
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
thriail	thriail	triail-V	Vmis
siad	siad	siad-P	Pp3-pn
mórán	mórán	mórán-N	Ncmsc
rudaí	rudaí	rud-N	Ncmpg
eile	eile	eile-D	Dd
.	.	.-F	Fe
Ach	Ach	ach-S	Sp
saothar	saothar	saothar-N	Ncmsc
in	in	i-S	Sp
aisce	aisce	aisce-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmm-2s
na	na	na-T	Td-p
míonna	míonna	mí-N	Ncfpc
isteach	isteach	isteach-R	Rd
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
Oíche	Oíche	oíche-N	Ncfsc
Shamhna	Shamhna	Samhain-N	Ncfsg
–	–	–-X	Xx
oíche	oíche	oíche-N	Ncfsc
na	na	na-T	Td-p
draíochta	draíochta	draíocht-N	Ncfpg
,	,	,-F	Fi
oíche	oíche	oíche-N	Ncfsc
na	na	na-T	Tdfsg
sí	sí	sí-N	Ncmsg
.	.	.-F	Fe
Oíche	Oíche	oíche-N	Ncfsc
gharbh	gharbh	garbh-A	Aq-fsc
ghaofar	ghaofar	gaofar-A	Aq-fsc|Aq-fsv
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
De	De	de-S	Sp
ghnáth	ghnáth	gnáth-N	Ncmsc
bhíodh	bhíodh	bí-V	Vmih
fleá	fleá	fleá-N	Ncfsc|Ncmsc
agus	agus	agus-C	Cc
féasta	féasta	féasta-N	Ncmsg|Ncmsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
bhanríon	bhanríon	banríon-N	Ncfsc
le	le	le-S	Sp
huaisle	huaisle	uaisle-N	Ncmpc|Ncfsc
na	na	na-T	Tdfsg
tíre	tíre	tír-N	Ncfsg
leis	leis	le-S	Sp
an	an	an-T	Td-s
tSamhain	tSamhain	Samhain-N	Ncfsc
a	a	a-U	U
cheiliúradh	cheiliúradh	ceiliúir-N	Nv
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
cheiliúradh	cheiliúradh	ceiliúradh-N	Ncmsc
i	i	i-S	Sp
dTeamhair	dTeamhair	teamhair-N	Ncfsc
an	an	an-T	Td-s
tSamhain	tSamhain	Samhain-N	Ncfsc
sin	sin	sin-D	Dd
.	.	.-F	Fe
Go	Go	go-U	Ua
domhain	domhain	domhain-A	Aqp
san	san	i-S	Spa-s
oíche	oíche	oíche-N	Ncfsc
chuala	chuala	clois-V	Vmis
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
scread	scread	scread-V	Vmis
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmis
sé	sé	sé-P	Pp3msn
de	de	de-S	Sp
phreab	phreab	preab-N	Ncfsc
agus	agus	agus-C	Cc
rith	rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
go dtí	go dtí	go_dtí-S	Spc
leaba	leaba	leaba-N	Ncfsc
Róisín	Róisín	Róisín-N	Npf-g|Npfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
ina	ina	i-S	Spp-p|Spp-s
suí	suí	suí-N	Ncmsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
leaba	leaba	leaba-N	Ncfsc
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
bogchaoineadh	bogchaoineadh	caoin-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
a	a	a-U	Uv
athair	athair	athair-N	Ncmsv
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
,	,	,-F	Fi
‘	‘	‘-X	Xx
bhí	bhí	bí-V	Vmis
drochbhrionglóid	drochbhrionglóid	brionglóid-N	Ncfsc
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
'	'	'-F	Fa
Thosaigh	Thosaigh	tosaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
gur	gur	gur-Q	Q--s
inis	inis	inis-V	Vmis
sí	sí	sí-P	Pp3fsn
dó	dó	do-P	Pr3ms
mar	mar	mar-C	Cs|Sp
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhuadaigh	fhuadaigh	fuadaigh-V	Vmis
an	an	an-T	Td-s
slua	slua	slua-N	Ncmsc
sí	sí	sí-P	Pp3fsn
í	í	í-P	Pp3fs
ina	ina	i-S	Spp-s
brionglóid	brionglóid	brionglóid-N	Ncfsc
cionn	cionn	ceann-N	Ncfsd
is	is	agus-C	Cc
nach	nach	nach-Q	Qnrs
ndearnadh	ndearnadh	déan-V	Vmis0--d
ceiliúradh	ceiliúradh	ceiliúir-N	Ncmsc|Nv
mar	mar	mar-C	Cs
ba	ba	is-W	Wsri
cheart	cheart	ceart-A	Aqp
Oíche	Oíche	oíche-N	Ncfsc|Ncfsg
Shamhna	Shamhna	Samhain-N	Ncfsg
.	.	.-F	Fe
Shocraigh	Shocraigh	socraigh-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
chun	chun	chun-S	Sp
suain	suain	suan-N	Ncmsg
arís	arís	arís-R	Rg
faoi	faoi	faoi-S	Sp
dheireadh	dheireadh	deireadh-N	Ncmsc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
fhill	fhill	fill-V	Vmis
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
leaba	leaba	leaba-N	Ncfsc
féin	féin	féin-P	Px
.	.	.-F	Fe
Ach	Ach	ach-S	Sp
codladh	codladh	codladh-N	Ncfsc
ní	ní	ní-Q	Qn
dhearna	dhearna	déan-V	Vmis---n
sé	sé	sé-P	Pp3msn
,	,	,-F	Fi
ach	ach	ach-S	Sp|Cs
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
smaoineamh	smaoineamh	smaoinigh-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
méid	méid	méid-N	Ncmsc
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
Róisín	Róisín	Róisín-N	Npfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
tí	tí	tí-N	Ncfsc
titim	titim	tit-V	Vmip1s
ina	ina	i-S	Spp-s
chodladh	chodladh	codladh-N	Ncfsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
thug	thug	tabhair-V	Vmis
an	an	an-T	Td-s
bhanríon	bhanríon	banríon-N	Ncfsc
sonc	sonc	sonc-N	Ncmsg|Ncmsc
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Éirigh	Éirigh	éirigh-V	Vmis
go	go	go-U	Ua
pras	pras	pras-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
duine	duine	duine-N	Ncmsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
!	!	!-F	Fe
Téanam	Téanam	Téanam-N	Npmsc
ort	ort	ar-P	Pr2-s
!	!	!-F	Fe
'	'	'-F	Fa
Chuaigh	Chuaigh	téigh-V	Vmis
siad	siad	siad-P	Pp3-pn
beirt	beirt	beirt-N	Ncfsc
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
Cé	Cé	cé-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
ina	ina	i-S	Spp-p|Spp-s
seasamh	seasamh	seasamh-N	Ncmsc
rompu	rompu	roimh-P	Pr3-p
ansin	ansin	ansin-R	Rt|Rl
ach	ach	ach-S	Sp
muintir	muintir	muintir-N	Ncfsc
an	an	an-T	Td-s
bhaile	bhaile	baile-N	Ncmsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
cosnochta	cosnochta	cosnochta-A	Aqp
,	,	,-F	Fi
iad	iad	iad-P	Pp3-p
ar	ar	ar-S	Sp
crith	crith	crith-N	Nv
leis	leis	le-S	Sp
an	an	an-T	Td-s
fhuacht	fhuacht	fuacht-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
alltacht	alltacht	alltacht-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhanríon	bhanríon	banríon-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cén	Cén	cé-W	W--q|Dw--s
driopás	driopás	driopás-N	Ncmsc
seo	seo	seo-D	Dd
atá	atá	bí-V	Vmip---r
ort	ort	ar-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
fhir	fhir	fear-N	Ncmsv
?	?	?-F	Fq
'	'	'-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
leis	leis	le-S	Sp
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cuir	Cuir	cur-N	Ncmsg
ruaig	ruaig	ruaig-V	Vmis
ar	ar	ar-S	Sp
an	an	an-T	Td-s
scroblach	scroblach	scroblach-N	Ncmsc
seo	seo	seo-D	Dd
!	!	!-F	Fe
'	'	'-F	Fa
Sula	Sula	sula-C	Cs
raibh	raibh	bí-V	Vmis---d
deis	deis	deis-N	Ncfsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
í	í	í-P	Pp3fs
a	a	a-U	U
fhreagairt	fhreagairt	freagair-N	Nv
,	,	,-F	Fi
labhair	labhair	labhair-V	Vmis|Vmm-2s
buachaill	buachaill	buachaill-N	Ncmsc
óg	óg	óg-A	Aq-msc
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	a-U	U
rí	rí	rígh-N	Nv
!	!	!-F	Fe
'	'	'-F	Fa
Rinneadh	Rinneadh	déan-V	Vmis0
staic	staic	staic-N	Ncfsc
den	den	de-S	Spa-s
bhanríon	bhanríon	banríon-N	Ncfsc
.	.	.-F	Fe
Buachaill	Buachaill	buachaill-N	Ncmsc
bocht	bocht	bocht-A	Aq-msc
mar	mar	mar-C	Cs
sin	sin	sin-W	W
ag	ag	ag-S	Sp
labhairt	labhairt	labhair-N	Nv
leis	leis	le-S	Sp
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
!	!	!-F	Fe
Ach	Ach	ach-C	Cs
baineadh	baineadh	bain-V	Vmis0
an	an	an-T	Td-s
anáil	anáil	anáil-N	Ncfsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
di	di	de-P	Pr3fs
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
thug	thug	tabhair-V	Vmis
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
cead	cead	cead-N	Ncmsc
don	don	do-S	Spa-s
bhuachaill	bhuachaill	buachaill-N	Ncmsc
leanúint	leanúint	lean-N	Ncfsc|Nv
ar	ar	ar-S	Sp
aghaidh	aghaidh	aghaidh-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	a-U	U
rí	rí	rígh-N	Nv
,	,	,-F	Fi
mura	mura	mura-C	Cs
mbíonn	mbíonn	bí-V	Vmig
fleá	fleá	fleá-N	Ncfsc|Ncmsc
sa	sa	i-S	Spa-s
dún	dún	dún-N	Ncmsc
Oíche	Oíche	oíche-N	Ncfsc|Ncfsg
Shamhna	Shamhna	Samhain-N	Ncfsg
beidh	beidh	bí-V	Vmif
fearg	fearg	fearg-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
slua	slua	slua-N	Ncmsc
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
Caithfear	Caithfear	caith-V	Vmif0
an	an	an-T	Td-s
tSamhain	tSamhain	Samhain-N	Ncfsc
a	a	a-U	U
cheiliúradh	cheiliúradh	ceiliúir-N	Nv
.	.	.-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
a	a	a-D	Dp3
smugachán	smugachán	smugachán-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
bhanríon	bhanríon	banríon-N	Ncfsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
níl	níl	bí-V	Vmip---n
laoch	laoch	laoch-N	Ncmsc
,	,	,-F	Fi
banfhlaith	banfhlaith	banfhlaith-N	Ncmsc
ná	ná	nach-Q	Qnr
file	file	file-X	Xfev
faoi	faoi	faoi-S	Sp
fhad	fhad	fad-N	Ncmsc
scairte	scairte	scairt-A	Av
den	den	de-S	Spa-s
dún	dún	dún-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
féidir	féidir	féidir-N	Ns-s
linn	linn	le-P	Pr1-p
fleá	fleá	fleá-N	Ncfsc|Ncmsc
a	a	a-U	U
thionól	thionól	tionóil-N	Nv
!	!	!-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
A	A	an-T	Td-s
chéile	chéile	céile-N	Ncmsc
,	,	,-F	Fi
a	a	a-U	Uv
chroí	chroí	croí-N	Ncmsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
tá	tá	bí-V	Vmip
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
a	a	a-Q	Q-r
dhéanfaidh	dhéanfaidh	déan-V	Vmif
muid	muid	muid-P	Pp1-p
.	.	.-F	Fe
Rud	Rud	rud-N	Ncmsc
nach	nach	nach-Q	Qnrs
ndearna	ndearna	déan-V	Vmis---d
muid	muid	muid-P	Pp1-p
riamh	riamh	riamh-R	Rg
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
bhacfaidh	bhacfaidh	bac-V	Vmif---n
muid	muid	muid-P	Pp1-p
le	le	le-S	Sp
laoch	laoch	laoch-N	Ncmsc
,	,	,-F	Fi
banfhlaith	banfhlaith	banfhlaith-N	Ncmsc
ná	ná	nach-Q	Qnr
file	file	file-X	Xfev
.	.	.-F	Fe
Déanfaidh	Déanfaidh	déan-V	Vmif
muid	muid	muid-P	Pp1-p
an	an	an-T	Td-s
tSamhain	tSamhain	Samhain-N	Ncfsc
a	a	a-U	U
cheiliúradh	cheiliúradh	ceiliúir-N	Nv
le	le	le-S	Sp
muintir	muintir	muintir-N	Ncfsc
an	an	an-T	Td-s
bhaile	bhaile	baile-N	Ncmsg
!	!	!-F	Fe
'	'	'-F	Fa
Ba	Ba	is-W	Ws|Ws-i
léir	léir	léir-A	Aqp
don	don	do-S	Spa-s
bhanríon	bhanríon	banríon-N	Ncfsc
nárbh	nárbh	is-W	Wsrin
fhiú	fhiú	fiú-N	Ns-s|Ncmsc
di	di	do-P	Pr3fs
dul	dul	dul-N	Ncmsc
in éadan	in éadan	in_éadan-S	Spc
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsg
an	an	an-T	Td-s
iarraidh	iarraidh	iarraidh-N	Ncfsc
seo	seo	seo-D	Dd
.	.	.-F	Fe
Lig	Lig	lig-V	Vmis|Vmm-2s
an	an	an-T	Td-s
scata	scata	scata-N	Ncmsc
liú	liú	liúigh-N	Ncmsg|Ncmsc|Nv|Nv--g
áthais	áthais	áthas-N	Ncmsg|Ncmpc
astu	astu	as-P	Pr3-p
.	.	.-F	Fe
Níorbh	Níorbh	is-W	Ws-in
fhada	fhada	fada-A	Aqc|Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
togha	togha	togha-N	Ncmsc
gach	gach	gach-D	Dq
bia	bia	bia-N	Ncmsc
agus	agus	agus-C	Cc
rogha	rogha	rogha-N	Ncfsg|Ncfsc|Ncfsg
gach	gach	gach-D	Dq
ar	ar	ar-S	Sp
bord	bord	bord-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
scléip	scléip	scléip-N	Ncfsc
agus	agus	agus-C	Cc
ceol	ceol	ceol-N	Ncmsc|Nv-----n
ag	ag	ag-S	Sp
cách	cách	cách-N	Ncmsc
i bhfochair	i bhfochair	i_bhfochair-S	Spc
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
go	go	go-S	Sp
maidin	maidin	maidin-N	Ncfsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
mhúscail	mhúscail	múscail-V	Vmis
an	an	an-T	Td-s
bhanríon	bhanríon	banríon-N	Ncfsc
ar	ar	ar-S	Sp
maidin	maidin	maidin-N	Ncfsc
chuala	chuala	clois-V	Vmis
sí	sí	sí-P	Pp3fsn
rud	rud	rud-N	Ncmsc
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
cloiste	cloiste	clois-A	Av
aici	aici	ag-P	Pr3fs
le	le	le-S	Sp
fada	fada	fada-A	Aqp
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
–	–	–-X	Xx
gáire	gáire	gáire-N	Ncmsc
gliondrach	gliondrach	gliondrach-A	Aq-msc
Róisín	Róisín	Róisín-N	Npf-g|Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Éirigh	Éirigh	éirigh-V	Vmm-2s
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
leis	leis	le-S	Sp
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Éirigh	Éirigh	éirigh-V	Vmm-2s
go	go	go-U	Ua
beo	beo	beo-A	Aqp
!	!	!-F	Fe
'	'	'-F	Fa
Chonaic	Chonaic	feic-V	Vmis
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
bhanríon	bhanríon	banríon-N	Ncfsc
Róisín	Róisín	Róisín-N	Npf-g|Npfsc
ag	ag	ag-S	Sp
spraoi	spraoi	spraoi-N	Nv-----n
ar	ar	ar-S	Sp
fhaiche	fhaiche	faiche-N	Ncfsc
an	an	an-T	Td-s
dúin	dúin	dún-N	Ncmsg
le	le	le-S	Sp
páistí	páistí	páiste-N	Ncmpc
an	an	an-T	Td-s
bhaile	bhaile	baile-N	Ncmsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
gealgháireach	gealgháireach	gealgháireach-A	Aqp
éadromchroíoch	éadromchroíoch	éadromchroíoch-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
lúcháir	lúcháir	lúcháir-N	Ncfsc
an	an	an-T	Td-s
domhain	domhain	domhan-N	Ncmsg
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhanríon	bhanríon	banríon-N	Ncfsc
agus	agus	agus-C	Cc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
.	.	.-F	Fe
