Míorúilt	Míorúilt	míorúilt-N	Ncfsc
na	na	na-T	Tdfsg
Nollag	Nollag	Nollaig-N	Ncfsg
.	.	.-F	Fe
Ar	Ar	is-W	Wssi|Wpsi
a	a	a-D	Dp3
mbealach	mbealach	bealach-N	Ncmsc
abhaile	abhaile	abhaile-R	Rd
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
siad	siad	siad-P	Pp3-pn
den	den	de-S	Spa-s
chéad	chéad	céad-M	Mo
uair	uair	uair-N	Ncfsc
é	é	é-P	Pp3ms
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
go	go	go-U	Ua
truamhéalach	truamhéalach	truamhéalach-A	Aqp
i	i	i-S	Sp
bhfuacht	bhfuacht	fuacht-N	Ncmsc
an	an	an-T	Td-s
tráthnóna	tráthnóna	tráthnóna-N	Ncmsg
–	–	–-X	Xx
asal	asal	asal-N	Ncmsc
beag	beag	beag-A	Aq-msc
donn	donn	donn-A	Aq-msc
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	a-T	Td-s|Dp3|U
Chathail	Chathail	Cathal-N	Npm-v
!	!	!-F	Fe
Gabh	Gabh	gabh-V	Vmm-2s
i	i	i-S	Sp
leith	leith	leith-N	Ncfsc
anseo	anseo	anseo-R	Rl
go	go	go-Q	Q
bhfeicfidh	bhfeicfidh	feic-V	Vmif
tú	tú	tú-P	Pp2-s
!	!	!-F	Fe
'	'	'-F	Fa
Róise	Róise	Róise-N	Npfsc
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
ar	ar	ar-S	Sp
dtús	dtús	tús-N	Ncmsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
é	é	é-P	Pp3ms
anois	anois	anois-R	Rt
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Cathal	Cathal	Cathal-N	Npmsc
agus	agus	agus-C	Cc
cantal	cantal	cantal-N	Ncmpg|Ncmsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
deifir	deifir	deifir-N	Ncfsc
abhaile	abhaile	abhaile-R	Rd
ormsa	ormsa	ar-P	Pr1-s-e
!	!	!-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Breathnaigh	Breathnaigh	breathnaigh-V	Vmm-2s
air	air	ar-P	Pr3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Róise	Róise	Róise-N	Npfsc
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
siad	siad	siad-P	Pp3-pn
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
cróilí	cróilí	cróilí-A	Aqp
tanaí	tanaí	tanaí-A	Aqp
agus	agus	agus-C	Cc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
chuma	chuma	cuma-N	Ncfsc
air	air	ar-P	Pr3ms
nár	nár	nár-Q	Qnrs
tugadh	tugadh	tabhair-V	Vmis0
aon	aon	aon-D	Dq
aire	aire	aire-N	Ncmsc|Ncfsc
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
an	an	an-T	Td-s
créatúirín	créatúirín	créatúr-N	Ncmsc
bocht	bocht	bocht-A	Aq-msc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Cathal	Cathal	Cathal-N	Npmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
dúirt	dúirt	abair-V	Vmis
Róise	Róise	Róise-N	Npfsc
rud	rud	rud-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
lámh	lámh	lámh-N	Ncfsc
amach	amach	amach-R	Rd
.	.	.-F	Fe
Tharraing	Tharraing	tarraing-V	Vmis
t	t	t-X	Xl
‑	‑	‑-F	Fb
asal	asal	asal-N	Ncmsc
siar	siar	siar-R	Rd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
thrustann	thrustann	trust-V	Vmip---n
sé	sé	sé-P	Pp3msn
muid	muid	muid-P	Pp1-p
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Róise	Róise	Róise-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
iontas	iontas	iontas-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
orm	orm	ar-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
a	a	a-D	Dp3
cara	cara	cara-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
é	é	é-P	Pp3ms
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
abhaile	abhaile	abhaile-R	Rd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Róise	Róise	Róise-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
as	as	as-P	Pr3ms
do	do	do-S	Sp
mheabhair	mheabhair	meabhair-N	Ncfsc
atá	atá	bí-V	Vmip---r
tú	tú	tú-P	Pp2-s
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Cathal	Cathal	Cathal-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
ligfeadh	ligfeadh	lig-V	Vmc----n
do	do	do-S	Sp
mháthair	mháthair	máthair-N	Ncfsc
duit	duit	do-P	Pr2-s
é	é	é-P	Pp3ms
a	a	a-U	U
choinneáil	choinneáil	coinnigh-N	Nv
!	!	!-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
ní	ní	is-W	Wp-in
fhéadfaidh	fhéadfaidh	féad-V	Vmif
muid	muid	muid-P	Pp1-p
é	é	é-P	Pp3ms
a	a	a-U	U
fhágáil	fhágáil	fág-N	Nv
anseo	anseo	anseo-R	Rl
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Róise	Róise	Róise-N	Npfsc
agus	agus	agus-C	Cc
ghlaoigh	ghlaoigh	glaoigh-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
máthair	máthair	máthair-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
a	a	a-D	Dp3
thiarcais	thiarcais	tiarcais-N	Ns-s
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
máthair	máthair	máthair-N	Ncfsc
Róise	Róise	Róise-N	Npf-g|Npfsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
fhad	fhad	fad-N	Ncmsc
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-T	Td-s
créatúirín	créatúirín	créatúr-N	Ncmsc
bocht	bocht	bocht-A	Aq-msc
.	.	.-F	Fe
Caithfidh	Caithfidh	caith-V	Vmif
muid	muid	muid-P	Pp1-p
fios	fios	fios-N	Ncmsc
a	a	a-U	U
chur	chur	cuir-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
tréidlia	tréidlia	tréidlia-N	Ncmsc
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
Tabhair	Tabhair	tabhair-V	Vmm-2s
cúnamh	cúnamh	cúnamh-N	Ncmsc
dom	dom	do-P	Pr1-s
,	,	,-F	Fi
a	a	a-U	Uv
pháistí	pháistí	páiste-N	Ncmpv
,	,	,-F	Fi
agus	agus	agus-C	Cc
tabharfaidh	tabharfaidh	tabhair-V	Vmif
muid	muid	muid-P	Pp1-p
abhaile	abhaile	abhaile-R	Rd
é	é	é-P	Pp3ms
.	.	.-F	Fe
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
mearbhall	mearbhall	mearbhall-N	Ncmsc
ar	ar	ar-S	Sp
Chathal	Chathal	Cathal-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
gcuirfidh	gcuirfidh	cuir-V	Vmif
sibh	sibh	sibh-P	Pp2-p
é	é	é-P	Pp3ms
?	?	?-F	Fq
'	'	'-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
a	a	a-D	Dp3
dhóthain	dhóthain	dóthain-N	Ncfsc
fairsinge	fairsinge	fairsing-A	Aq-fsg
sa	sa	i-S	Spa-s
gharáiste	gharáiste	garáiste-N	Ncmsc
aige	aige	ag-P	Pr3ms
má	má	má-C	Cs
thugaim	thugaim	tabhair-V	Vmip1s
an	an	an-T	Td-s
carr	carr	carr-N	Ncmsc|Ncfsc
amach	amach	amach-R	Rd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
máthair	máthair	máthair-N	Ncfsc
Róisín	Róisín	Róisín-N	Npf-g|Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhuel	Bhuel	bhuel-X	Xsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cathal	Cathal	Cathal-N	Npmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
b	b	b-X	Xl
’	’	’-F	Fa
fhearr	fhearr	maith-A	Aqc
domsa	domsa	do-P	Pr1-s-e
slám	slám	slám-N	Ncmsc
tuí	tuí	tuí-N	Ncfsg|Ncfsc
a	a	a-U	U
fháil	fháil	faigh-N	Nv
daoibh	daoibh	do-P	Pr2-p
i	i	i-S	Sp
scioból	scioból	scioból-N	Ncmsc
Mhicil	Mhicil	Mhicil-N	Npmsc
Sheáinín	Sheáinín	Seán-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
siad	siad	siad-P	Pp3-pn
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
ag	ag	ag-S	Sp
fanacht	fanacht	fan-N	Nv
leis	leis	le-S	Sp
an	an	an-T	Td-s
tréidlia	tréidlia	tréidlia-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
‑	‑	‑-F	Fb
iontas	iontas	iontas-N	Ncmsc
air	air	ar-N	Ncmsg
siúd	siúd	siúd-P	Pd|Dd
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
t	t	t-X	Xl
‑	‑	‑-F	Fb
asailín	asailín	asailín-N	Ncmsc
ina	ina	i-S	Spp-s|Spp-p
luí	luí	luí-N	Ncmsc
faoi	faoi	faoi-S	Sp
bhlaincéad	bhlaincéad	blaincéad-N	Ncmsc
ar	ar	ar-S	Sp
urlár	urlár	urlár-N	Ncmsc
an	an	an-T	Td-s
gharáiste	gharáiste	garáiste-N	Ncmsg
.	.	.-F	Fe
Scrúdaigh	Scrúdaigh	scrúdaigh-V	Vmis
sé	sé	sé-P	Pp3msn
t	t	t-X	Xl
‑	‑	‑-F	Fb
asal	asal	asal-N	Ncmsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
réidh	réidh	réidh-A	Aqp
chroith	chroith	croith-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
cheann	cheann	ceann-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
muid	muid	muid-P	Pp1-p
ródheireanach	ródheireanach	deireanach-A	Aqp
.	.	.-F	Fe
Is	Is	is-W	Wp-i
dóigh	dóigh	dóigh-N	Ncfsc
nach	nach	nach-Q	Qnr
sracfaidh	sracfaidh	srac-V	Vmif
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
oíche	oíche	oíche-N	Ncfsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
chuma	chuma	cuma-N	Ncfsc
air	air	ar-P	Pr3ms
go	go	go-Q	Q
bhfuair	bhfuair	faigh-V	Vmis
sé	sé	sé-P	Pp3msn
drochíde	drochíde	drochíde-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
rud	rud	rud-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhéadfadh	fhéadfadh	féad-V	Vmc
muid	muid	muid-P	Pp1-p
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
dó	dó	do-P	Pr3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Róise	Róise	Róise-N	Npfsc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
deora	deora	deoir-N	Ncfpc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Lig	Lig	lig-V	Vmis|Vmm-2s
an	an	an-T	Td-s
tréidlia	tréidlia	tréidlia-N	Ncmsc
osna	osna	osna-N	Ncmsg|Ncmsc
as	as	as-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Coinnigh	Coinnigh	Coinnigh-N	Npmsc
uisce	uisce	uisce-N	Ncmsg|Ncmsc
leis	leis	le-P	Pr3ms
agus	agus	agus-C	Cc
féar	féar	féar-N	Ncmpg|Ncmsc
.	.	.-F	Fe
Sin	Sin	sin-W	W
an	an	an-T	Td-s
méid	méid	méid-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
fhan	fhan	fan-V	Vmis
Róise	Róise	Róise-N	Npfsc
sa	sa	i-S	Spa-s
gharáiste	gharáiste	garáiste-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
asal	asal	asal-N	Ncmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
tréidlia	tréidlia	tréidlia-N	Ncmsc
imithe	imithe	imigh-A	Av
.	.	.-F	Fe
Chuimil	Chuimil	cuimil-V	Vmis
sí	sí	sí-P	Pp3fsn
go	go	go-U	Ua
cineálta	cineálta	cineálta-A	Aqp
é	é	é-P	Pp3ms
agus	agus	agus-C	Cc
labhair	labhair	labhair-V	Vmis
sí	sí	sí-P	Pp3fsn
leis	leis	le-P	Pr3ms
de	de	de-S	Sp
ghlór	ghlór	glór-N	Ncmsc
deas	deas	deas-R	Ri
séimh	séimh	séimh-A	Aqp
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
sí	sí	sí-P	Pp3fsn
uisce	uisce	uisce-N	Ncmsc
dó	dó	do-P	Pr3ms
le	le	le-S	Sp
hól	hól	ól-N	Nv
agus	agus	agus-C	Cc
féar	féar	féar-N	Ncmsc
tirim	tirim	tirim-A	Aq-msc
le	le	le-S	Sp
hithe	hithe	ith-N	Nv
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
deireadh	deireadh	deireadh-N	Ncmsc
thit	thit	tit-V	Vmis
t	t	t-X	Xl
‑	‑	‑-F	Fb
asal	asal	asal-N	Ncmsc
ina	ina	i-S	Spp-s
chodladh	chodladh	codladh-N	Ncfsc
.	.	.-F	Fe
Sheas	Sheas	seas-V	Vmis
Róise	Róise	Róise-N	Npfsc
ag	ag	ag-S	Sp
giall	giall	giall-N	Ncmsc
an	an	an-T	Td-s
dorais	dorais	doras-N	Ncmsg
.	.	.-F	Fe
Oíche	Oíche	oíche-N	Ncfsc
spéirghealaí	spéirghealaí	spéirghealach-N	Ncfsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sioc	sioc	sioc-N	Ncmsc
crua	crua	crua-A	Aqp
ar	ar	ar-S	Sp
an	an	an-T	Td-s
talamh	talamh	talamh-N	Ncfsc
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
soilse	soilse	solas-N	Ncfsc|Ncmpc
na	na	na-T	Tdfsg
Nollag	Nollag	Nollaig-N	Ncfsg
le	le	le-S	Sp
feiceáil	feiceáil	feic-N	Nv
sna	sna	i-S	Spa-p
tithe	tithe	teach-N	Ncmpc
máguaird	máguaird	máguaird-N	Ncfsc
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
theastaigh	theastaigh	teastaigh-V	Vmis---n
ó	ó	ó-S	Sp
Róise	Róise	Róise-N	Npfsc
dul	dul	téigh-N	Ncmsc|Nv
isteach	isteach	isteach-R	Rd
abhaile	abhaile	abhaile-R	Rd
fós	fós	fós-R	Rg
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
tháinig	tháinig	tar-V	Vmis
máthair	máthair	máthair-N	Ncfsc
Róise	Róise	Róise-N	Npf-g|Npfsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhógair	fhógair	fógair-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
Róise	Róise	Róise-N	Npfsc
deifir	deifir	deifir-N	Ncfsc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
nó	nó	nó-C	Cc
bheidís	bheidís	bí-V	Vmc-3p
deireanach	deireanach	deireanach-A	Aqp
d	d	d-X	Xl
’	’	’-F	Fa
Aifreann	Aifreann	aifreann-N	Ncmsc
Oíche	Oíche	oíche-N	Ncfsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhág	fhág	fág-V	Vmis
Róise	Róise	Róise-N	Npfsc
slán	slán	slán-A	Aqp
ag	ag	ag-S	Sp
an	an	an-T	Td-s
asal	asal	asal-N	Ncmsc
ach	ach	ach-C	Cs
níor	níor	is-W	Ws-in
chorraigh	chorraigh	corraigh-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
ceol	ceol	ceol-N	Ncmsc
binn	binn	binn-A	Aq-msc
na	na	na-T	Tdfsg
Nollag	Nollag	Nollaig-N	Ncfsg
sa	sa	i-S	Spa-s
séipéal	séipéal	séipéal-N	Ncmsc
:	:	:-F	Fi
Oíche	Oíche	oíche-N	Ncfsc
chiúin	chiúin	ciúin-A	Aq-fsc
,	,	,-F	Fi
Oíche	Oíche	oíche-N	Ncfsc
mhic	mhic	mac-N	Ncmsg
Dé	Dé	dia-N	Ncmsg
…	…	…-F	Fi
Bhí	Bhí	bí-V	Vmis
coinnle	coinnle	coinneal-N	Ncfpc
ar	ar	ar-S	Sp
lasadh	lasadh	las-N	Nv
agus	agus	agus-C	Cc
boladh	boladh	boladh-N	Ncmsc
túise	túise	túis-N	Ncfsg
san	san	sin-S	Spa-s|Pd
aer	aer	aer-N	Ncmpg|Ncmsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
tAifreann	tAifreann	aifreann-N	Ncmsc
thart	thart	thart-R	Rd
chuaigh	chuaigh	téigh-V	Vmis
Róise	Róise	Róise-N	Npfsc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
máthair	máthair	máthair-N	Ncfsc
suas	suas	suas-R	Rd
chun	chun	chun-S	Sp
an	an	an-T	Td-s
mainséar	mainséar	mainséar-N	Ncmsc
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Cathal	Cathal	Cathal-N	Npmsc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
mhuintir	mhuintir	muintir-N	Ncfsc
ansin	ansin	ansin-R	Rt|Rl
rompu	rompu	roimh-P	Pr3-p
.	.	.-F	Fe
É	É	é-P	Pp3ms
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
a	a	a-D	Dp3
athair	athair	athair-N	Ncmsc
a	a	a-Q	Q-r
chuir	chuir	cuir-V	Vmis
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Rinne	Rinne	déan-V	Vmis
tú	tú	tú-P	Pp2-s
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
athair	athair	athair-N	Ncmsc
‑	‑	‑-F	Fb
jab	jab	jab-N	Ncmsc
den	den	de-S	Spa-s
mhainséar	mhainséar	mainséar-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
máthair	máthair	máthair-N	Ncfsc
Róise	Róise	Róise-N	Npf-g|Npfsc
leis	leis	le-P	Pr3ms
de	de	de-S	Sp
chogar	chogar	cogar-N	Ncmsc
.	.	.-F	Fe
Bhreathnaigh	Bhreathnaigh	breathnaigh-V	Vmis
Róise	Róise	Róise-N	Npfsc
na	na	na-T	Td-p
dealbha	dealbha	dealbh-N	Ncfpc
,	,	,-F	Fi
go	go	go-U	Ua
háirithe	háirithe	áirithe-A	Aqp
t	t	t-X	Xl
‑	‑	‑-F	Fb
asal	asal	asal-N	Ncmsc
beag	beag	beag-A	Aq-msc
donn	donn	donn-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
faire	faire	fair-N	Nv
go	go	go-U	Ua
gnaíúil	gnaíúil	gnaíúil-A	Aqp
ar	ar	ar-S	Sp
Íosagán	Íosagán	Íosagán-N	Npmsc
.	.	.-F	Fe
Chuimhnigh	Chuimhnigh	cuimhnigh-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
asailín	asailín	asailín-N	Ncmsc
bocht	bocht	bocht-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ar	ar	ar-S	Sp
an	an	an-T	Td-s
dé	dé	dé-N	Ncfsc
deiridh	deiridh	deireadh-N	Ncmsg
sa	sa	i-S	Spa-s
gharáiste	gharáiste	garáiste-N	Ncmsc
ag	ag	ag-S	Sp
baile	baile	baile-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ar	Ar	ar-Q	Qq-s
chuimhnigh	chuimhnigh	cuimhnigh-V	Vmis
tú	tú	tú-P	Pp2-s
ar	ar	ar-S	Sp
phaidir	phaidir	paidir-N	Ncfsc
a	a	a-U	U
rá	rá	abair-N	Nv
don	don	do-S	Spa-s
asailín	asailín	asailín-N	Ncmsc
seo	seo	seo-D	Dd
againne	againne	ag-P	Pr1-p-e
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Róise	Róise	Róise-N	Npfsc
le	le	le-S	Sp
Cathal	Cathal	Cathal-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cén	Cén	cé-D	Dw--s
chaoi	chaoi	caoi-N	Ncfsc
a	a	a-Q	Q-i
bhfuil	bhfuil	bí-V	Vmip---d
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
aon	aon	aon-D	Dq
chaoi	chaoi	caoi-N	Ncfsc
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Cathal	Cathal	Cathal-N	Npmsc
.	.	.-F	Fe
Ach	Ach	ach-S	Sp
freagra	freagra	freagra-N	Ncmsc
ní	ní	ní-Q	Qn
bhfuair	bhfuair	faigh-V	Vmis
sé	sé	sé-P	Pp3msn
mar	mar	mar-C	Cs
gur	gur	is-W	Wsdi
tháinig	tháinig	tar-V	Vmis
sprocht	sprocht	sprocht-N	Ncmsc
ar	ar	ar-S	Sp
Róise	Róise	Róise-N	Npfsc
.	.	.-F	Fe
Thuig	Thuig	tuig-V	Vmis
Cathal	Cathal	Cathal-N	Npmsc
as	as	as-S	Sp
sin	sin	sin-P	Pd
nárbh	nárbh	is-W	Wsrin
aon	aon	aon-D	Dq
dea	dea	dea-N	Ns-s
‑	‑	‑-F	Fb
scéala	scéala	scéala-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
Shiúil	Shiúil	siúil-V	Vmis
muintir	muintir	muintir-N	Ncfsc
Róise	Róise	Róise-N	Npfsc
agus	agus	agus-C	Cc
muintir	muintir	muintir-N	Ncfsc
Chathail	Chathail	Cathal-N	Npfsg|Npm-g
abhaile	abhaile	abhaile-R	Rd
i	i	i-S	Sp
gcomhluadar	gcomhluadar	comhluadar-N	Ncmsc
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
focal	focal	focal-N	Ncmsc
as	as	as-S	Sp
Róise	Róise	Róise-N	Npfsc
i	i	i-S	Sp
gcaitheamh	gcaitheamh	caitheamh-N	Ncmsc
an	an	an-T	Td-s
achair	achair	achar-N	Ncmsg
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
súil	súil	súil-N	Ncfsc
aici	aici	ag-P	Pr3fs
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
t	t	t-X	Xl
‑	‑	‑-F	Fb
asailín	asailín	asailín-N	Ncmsc
beo	beo	beo-A	Aqp
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
shroichfeadh	shroichfeadh	sroich-V	Vmc
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
baile	baile	baile-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
athair	athair	athair-N	Ncmsc
Róise	Róise	Róise-N	Npf-g|Npfsc|Npf-g
le	le	le-S	Sp
muintir	muintir	muintir-N	Ncfsc
Chathail	Chathail	Cathal-N	Npfsg|Npm-g
,	,	,-F	Fi
‘	‘	‘-X	Xx
beidh	beidh	bí-V	Vmif
deoch	deoch	deoch-N	Ncfsc
na	na	na-T	Tdfsg
Nollag	Nollag	Nollaig-N	Ncfsg
agaibh	agaibh	ag-P	Pr2-p
linn	linn	le-P	Pr1-p
.	.	.-F	Fe
'	'	'-F	Fa
Thug	Thug	tabhair-V	Vmis
na	na	na-T	Td-p
daoine	daoine	duine-N	Ncmpc
fásta	fásta	fás-A	Aqp|Av
aghaidh	aghaidh	aghaidh-N	Ncfsc
ar	ar	ar-S	Sp
chistin	chistin	cistin-N	Ncfsc
theolaí	theolaí	teolaí-A	Aqp
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
agus	agus	agus-C	Cc
chuaigh	chuaigh	téigh-V	Vmis
Róise	Róise	Róise-N	Npfsc
agus	agus	agus-C	Cc
Cathal	Cathal	Cathal-N	Npmsc
díreach	díreach	díreach-A	Aq-msc
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
garáiste	garáiste	garáiste-N	Ncmsc
.	.	.-F	Fe
Sheas	Sheas	seas-V	Vmis
siad	siad	siad-P	Pp3-pn
taobh amuigh	taobh amuigh	taobh_amuigh-R	Rl
den	den	de-S	Spa-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
Bhreathnaigh	Bhreathnaigh	breathnaigh-V	Vmis
siad	siad	siad-P	Pp3-pn
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
ar feadh	ar feadh	ar_feadh-S	Spc
meandair	meandair	meandar-N	Ncmsg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmm-2s
Róise	Róise	Róise-N	Npfsc
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
go	go	go-U	Ua
drogallach	drogallach	drogallach-A	Aqp
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
léi	léi	le-P	Pr3fs
agus	agus	agus-C	Cc
Cathal	Cathal	Cathal-N	Npmsc
sna	sna	i-S	Spa-p
sála	sála	sáil-N	Ncfpc
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
siad	siad	siad-P	Pp3-pn
in ann	in ann	in_ann-S	Spc
aon	aon	aon-D	Dq
cheo	cheo	ceo-N	Ncmsc
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
ar	ar	ar-S	Sp
dtús	dtús	tús-N	Ncmsc
.	.	.-F	Fe
Shín	Shín	Sín-N	Npfsc
Róise	Róise	Róise-N	Npf-g|Npfsc|Npf-g
a	a	a-D	Dp3
lámh	lámh	lámh-N	Ncfsc
amach	amach	amach-R	Rd
sa	sa	i-S	Spa-s
dorchadas	dorchadas	dorchadas-N	Ncmsc
agus	agus	agus-C	Cc
tháinig	tháinig	tar-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-N	Ncmsc
lasc	lasc	lasc-V	Vmis
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
scairt	scairt	scairt-V	Vmis
an	an	an-T	Td-s
solas	solas	solas-N	Ncmsc
baineadh	baineadh	bain-V	Vmis0
an	an	an-T	Td-s
anáil	anáil	anáil-N	Ncfsc
de	de	de-S	Sp
Róise	Róise	Róise-N	Npfsc
agus	agus	agus-C	Cc
de	de	de-S	Sp
Chathal	Chathal	Cathal-N	Npmsc
.	.	.-F	Fe
Os	Os	os-N	Ncmsc|Sp
a	a	a-D	Dp3
gcomhair	gcomhair	comhair-N	Ns-s
amach	amach	amach-R	Rd
céard	céard	cé-W	W--q
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
siad	siad	siad-P	Pp3-pn
…	…	…-F	Fi
…	…	…-F	Fi
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
t	t	t-X	Xl
‑	‑	‑-F	Fb
asailín	asailín	asailín-N	Ncmsc
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
rompu	rompu	roimh-P	Pr3-p
beo	beo	beo-A	Aqp
beathach	beathach	beathach-A	Aqp
i lár	i lár	i_lár-S	Spc
an	an	an-T	Td-s
urláir	urláir	urlár-N	Ncmsg
!	!	!-F	Fe
