 Turas	Turas	-X	Xx
Scoile	Scoile	scoil-N	Ncfsg
Lá	Lá	lá-N	Ncmsc
breá	breá	breá-A	Aq-msc
samhraidh	samhraidh	samhradh-N	Ncmsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
ghrian	ghrian	grian-V	Vmis
ag	ag	ag-S	Sp
taitneamh	taitneamh	taitin-N	Nv
go	go	go-U	Ua
hard	hard	ard-X	Xfea|Aqp
sa	sa	i-S	Spa-s
spéir	spéir	spéir-N	Ncfsc
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
na	na	na-T	Td-p
héin	héin	éan-N	Ncmpc
ag	ag	ag-S	Sp
canadh	canadh	can-N	Nv
ar	ar	ar-S	Sp
na	na	na-T	Td-p
sceacha	sceacha	sceach-N	Ncfpc
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
na	na	na-T	Td-p
beacha	beacha	beach-N	Ncfpc
ag	ag	ag-S	Sp
crónán	crónán	crónán-N	Nv-----n
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
ag	ag	ag-S	Sp
bailiú	bailiú	bailigh-N	Nv
meala	meala	mil-N	Ncfsg
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
na	na	na-T	Td-p
coiníní	coiníní	coinín-N	Ncmpc
beaga	beaga	beag-A	Aq--pc
ag	ag	ag-S	Sp
damhsa	damhsa	damhsaigh-N	Nv
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
spraoi	spraoi	spraoi-N	Nv-----n
sna	sna	i-S	Spa-p
páirceanna	páirceanna	páirc-N	Ncfpc
.	.	.-F	Fe
BHÍ	BHÍ	bí-V	Vmis
,	,	,-F	Fi
MUISE	MUISE	muise-X	Xsc
!	!	!-F	Fe
!	!	!-F	Fe
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
stealladh	stealladh	steall-N	Nv
báistí	báistí	báistigh-A	Av
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
gála	gála	gála-N	Ncmsc
gaoithe	gaoithe	gaoth-N	Ncfsg
ag	ag	ag-S	Sp
séideadh	séideadh	séid-N	Nv
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
fhágfadh	fhágfadh	fág-V	Vmc----n
ach	ach	ach-S	Sp
amadán	amadán	amadán-N	Ncmsc
an	an	an-T	Td-s
baile	baile	baile-N	Ncmsg
a	a	a-D	Dp3
leithéid	leithéid	leithéid-N	Ncfsc
de	de	de-S	Sp
lá	lá	lá-N	Ncmsc
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
geansaithe	geansaithe	geansaí-N	Ncmpc
,	,	,-F	Fi
hataí	hataí	hata-N	Ncmpc
agus	agus	agus-C	Cc
cótaí	cótaí	cóta-N	Ncmpc
móra	móra	mór-A	Aq--pc
ar	ar	ar-S	Sp
gach	gach	gach-D	Dq
duine	duine	duine-N	Ncmsc
.	.	.-F	Fe
Geansaí	Geansaí	Geansaí-N	Npfsc
‘	‘	‘-X	Xx
álainn	álainn	álainn-A	Aqp
’	’	’-F	Fa
flannbhuí	flannbhuí	flannbhuí-A	Aqc
agus	agus	agus-C	Cc
pictiúr	pictiúr	pictiúr-N	Ncmpg|Ncmsc
d	d	d-X	Xl
’	’	’-F	Fa
sneachta	sneachta	sneachta-N	Ncmsc
air	air	ar-P	Pr3ms
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
Máistir	Máistir	Máistir-N	Npmsc
a	a	a-U	U
chaitheamh	chaitheamh	caith-N	Nv
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
hata	hata	hata-N	Ncmsc
glas	glas	glas-A	Aq-msc
cluthar	cluthar	cluthar-A	Aq-msc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
cheann	cheann	ceann-N	Ncmsc
.	.	.-F	Fe
Is	Is	agus-W	Wp-i|Cc
maith	maith	maith-V	Vmm-2s|Aqp|Ncfsc
an	an	an-T	Td-s
rud	rud	rud-N	Ncmsc
é	é	é-P	Pp3ms
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
cead	cead	cead-N	Ncmsc
ag	ag	ag-S	Sp
na	na	na-T	Td-p
naíonáin	naíonáin	naíonán-N	Ncmpc
teacht	teacht	tar-N	Ncmsc|Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
turas	turas	turas-N	Ncmsc
,	,	,-F	Fi
nó	nó	nó-C	Cc
bheadh	bheadh	bí-V	Vmc
eagla	eagla	eagla-N	Ncfsc
an	an	an-T	Td-s
domhain	domhain	domhan-N	Ncmsg
ar	ar	ar-S	Sp
na	na	na-T	Td-p
créatúir	créatúir	créatúr-N	Ncmpc
roimhe	roimhe	roimh-P	Pr3ms
!	!	!-F	Fe
Ar	Ar	ar-S	Sp
chúl	chúl	cúl-N	Ncmsc
an	an	an-T	Td-s
bhus	bhus	bus-N	Ncmsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Colm	Colm	Colm-N	Npmsc
ina	ina	i-S	Spp-s
shuí	shuí	suí-N	Ncmsc
,	,	,-F	Fi
an	an	an-T	Td-s
áit	áit	áit-N	Ncfsc
a	a	a-Q	Q-r
shuíodh	shuíodh	suigh-V	Vmih
sé	sé	sé-P	Pp3msn
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
théadh	théadh	téigh-V	Vmih
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
thuras	thuras	turas-N	Ncmsc
leis	leis	le-S	Sp
na	na	na-T	Td-p
gasóga	gasóga	gasóg-N	Ncfpc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	is-W	Wp-in
ar	ar	ar-S	Sp
thuras	thuras	turas-N	Ncmsc
leis	leis	le-S	Sp
na	na	na-T	Td-p
gasóga	gasóga	gasóg-N	Ncfpc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
inniu	inniu	inniu-R	Rt
,	,	,-F	Fi
áfach	áfach	áfach-R	Rg
,	,	,-F	Fi
ach	ach	ach-C	Cs
ar	ar	is-W	Wpdi|Wpsi|Wssi
thuras	thuras	turas-N	Ncmsc
scoile	scoile	scoil-N	Ncfsg
.	.	.-F	Fe
Ruaigeadh	Ruaigeadh	ruaig-V	Vmm-3s
as	as	as-S	Sp
na	na	na-T	Td-p
gasóga	gasóga	gasóg-N	Ncfpc
é	é	é-P	Pp3ms
toisc	toisc	toisc-C	Cs
gur	gur	is-W	Wsdi
cheangail	cheangail	ceangail-V	Vmis
sé	sé	sé-P	Pp3msn
Pól	Pól	Pól-N	Npmsc
Ó	Ó	ó-C	Cs
Sé	Sé	is-W	Wp-i-3
de	de	de-P	Pr3ms
chrann	chrann	crann-N	Ncmsc
darach	darach	dair-N	Ncfsg
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
in	in	i-S	Sp
ainm	ainm	ainm-N	Ncmsc
is	is	agus-C	Cc
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
suas	suas	suas-R	Rd
pubaill	pubaill	puball-N	Ncmpc
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
tugadh	tugadh	tabhair-V	Vmis0
aon	aon	aon-D	Dq
éisteacht	éisteacht	éisteacht-N	Ncfsc
do	do	do-S	Sp
Cholm	Cholm	Colm-N	Npmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
mhínigh	mhínigh	mínigh-V	Vmis
sé	sé	sé-P	Pp3msn
gur	gur	is-W	Wsdi
ag	ag	ag-S	Sp
cleachtadh	cleachtadh	cleacht-N	Nv
a	a	a-D	Dp3
chuid	chuid	cuid-N	Ncfsc
snaidhmeanna	snaidhmeanna	snaidhm-N	Ncfpg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhág	fhág	fág-V	Vmis
sé	sé	sé-P	Pp3msn
Pól	Pól	Pól-N	Npmsc
bocht	bocht	bocht-A	Aq-msc
ceangailte	ceangailte	ceangail-A	Av
ar feadh	ar feadh	ar_feadh-S	Spc
trí	trí	trí-M	Mc
huaire	huaire	uair-N	Ncfsg
an	an	an-T	Td-s
chloig	chloig	clog-N	Ncmsg
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
nach	nach	is-W	Wpdin|Wpsin
ionadh	ionadh	ionadh-N	Ncmsc
,	,	,-F	Fi
níorbh	níorbh	is-W	Ws-in
fhada	fhada	fada-A	Aqc|Aqp
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-W	W
gur	gur	is-W	Wsdi
bhog	bhog	bog-N	Ncmsc
muintir	muintir	muintir-N	Ncfsc
Shé	Shé	Sé-N	Npfsg
go dtí	go dtí	go_dtí-S	Spc
baile	baile	baile-N	Ncmsc
nua	nua	nua-A	Aqp
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
rud	rud	rud-N	Ncmsc
amháin	amháin	amháin-A	Aqp
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhoghlaim	fhoghlaim	foghlaim-V	Vmis|Nv
Colm	Colm	Colm-N	Npm-g|Npmsc
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
sna	sna	i-S	Spa-p
gasóga	gasóga	gasóg-N	Ncfpc
:	:	:-F	Fi
‘	‘	‘-X	Xx
bí	bí	bí-N	Ncfsc
ullamh	ullamh	ullamh-N	Ncmsc
!	!	!-F	Fe
'	'	'-F	Fa
Agus	Agus	agus-C	Cc
nach	nach	is-W	Wpsin|Wpdin
eisean	eisean	é-P	Pp3ms-e
a	a	a-Q	Q-r
bhíodh	bhíodh	bí-V	Vmih
ullamh	ullamh	ullamh-N	Ncmsc
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
!	!	!-F	Fe
Ullamh	Ullamh	Ullamh-N	Npmsc
don	don	do-S	Spa-s
éirí	éirí	éirí-N	Ncmsc
in	in	i-S	Sp
airde	airde	airde-N	Ncfpc|Ncfsc
agus	agus	agus-C	Cc
don	don	do-S	Spa-s
phleidhcíocht	phleidhcíocht	pleidhcíocht-N	Ncfsc
:	:	:-F	Fi
tacóidí	tacóidí	tacóid-N	Ncfpc
ordóige	ordóige	ordóg-N	Ncfsg
ar	ar	ar-S	Sp
shuíocháin	shuíocháin	suíochán-N	Ncmpc
,	,	,-F	Fi
bandaí	bandaí	bandach-A	Aqc
leaisteacha	leaisteacha	leaisteach-A	Aq--pg|Aq--pc|Aq--pv
a	a	a-U	U
scaoileadh	scaoileadh	scaoil-N	Nv
tríd	tríd	trí-S	Sp
an	an	an-T	Td-s
aer	aer	aer-N	Ncmsc
,	,	,-F	Fi
damháin	damháin	damhán-N	Ncmpc
alla	alla	alla-N	Ncmsg|Ncmsc|Ncmsg
i	i	i-S	Sp
mboscaí	mboscaí	bosca-N	Ncmpc
lóin	lóin	lón-N	Ncmsg
,	,	,-F	Fi
lucha	lucha	luch-N	Ncfpc
rubair	rubair	rubar-N	Ncmsg|Ncmpc|Ncmsg
i	i	i-S	Sp
dtarraiceán	dtarraiceán	tarraiceán-N	Ncmsc
an	an	an-T	Td-s
mhúinteora	mhúinteora	múinteoir-N	Ncmsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
‑	‑	‑-F	Fb
spórt	spórt	spórt-N	Ncmsc
ag	ag	ag-S	Sp
Colm	Colm	Colm-N	Npmsc
i	i	i-S	Sp
gcúl	gcúl	cúl-N	Ncmsc
an	an	an-T	Td-s
bhus	bhus	bus-N	Ncmsg
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
tháinig	tháinig	tar-V	Vmis---n
buachaill	buachaill	buachaill-N	Ncmsc
ná	ná	ná-C	Cc
cailín	cailín	cailín-N	Ncmsc
slán	slán	slán-A	Aq-msc
óna	óna	ó-S	Spp-s
chuid	chuid	cuid-N	Ncfsc
maistíneachta	maistíneachta	maistíneacht-N	Ncfsg
.	.	.-F	Fe
Go	Go	go-U	Ua
deimhin	deimhin	deimhin-A	Aqp
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
cúl	cúl	cúl-N	Ncmsc
an	an	an-T	Td-s
bhus	bhus	bus-N	Ncmsg
ina	ina	i-S	Spp-s
chíréib	chíréib	círéib-N	Ncfsc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Faoi	Faoi	faoi-S	Sp
dheireadh	dheireadh	deireadh-N	Ncmsc
cuireadh	cuireadh	cuireadh-N	Ncmsc
ina	ina	i-S	Spp-s
shuí	shuí	suí-N	Ncmsc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
barr	barr	barr-N	Ncmsc
an	an	an-T	Td-s
bhus	bhus	bus-N	Ncmsg
taobh	taobh	taobh-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
Máistir	Máistir	Máistir-N	Npmsc
.	.	.-F	Fe
Shuigh	Shuigh	suigh-V	Vmis
sé	sé	sé-P	Pp3msn
agus	agus	agus-C	Cc
strainc	strainc	strainc-N	Ncfsc
air	air	ar-P	Pr3ms
,	,	,-F	Fi
t	t	t-X	Xl
‑	‑	‑-F	Fb
amadán	amadán	amadán-N	Ncmsc
d	d	d-X	Xl
’	’	’-F	Fa
sneachta	sneachta	sneachta-N	Ncmsc
ar	ar	ar-S	Sp
gheansaí	gheansaí	geansaí-N	Ncmsc
an	an	an-T	Td-s
Mháistir	Mháistir	Máistir-N	Npfsg
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
cancair	cancair	cancar-N	Ncmsg
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Shroich	Shroich	sroich-V	Vmis
siad	siad	siad-P	Pp3-pn
ceann	ceann	ceann-N	Ncmsc
scríbe	scríbe	scríob-N	Ncfsg
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-U	Um
deich	deich	deich-M	Mc
a	a	an-T	Td-s
chlog	chlog	clog-N	Ncmsc
,	,	,-F	Fi
díreach	díreach	díreach-A	Aqp
.	.	.-F	Fe
Lig	Lig	lig-V	Vmis|Vmm-2s
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
liú	liú	liúigh-N	Ncmsg|Ncmsc|Nv|Nv--g|Ncmsg|Nv
áthais	áthais	áthas-N	Ncmsg|Ncmpc
astu	astu	as-P	Pr3-p
mar	mar	mar-C	Cs
bhí	bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
bréan	bréan	bréan-A	Aqp
bailithe	bailithe	bailigh-A	Av
d	d	d-X	Xl
’	’	’-F	Fa
amhráin	amhráin	amhrán-N	Ncmpc
an	an	an-T	Td-s
mhúinteoir	mhúinteoir	múinteoir-N	Ncmsc
Mháire	Mháire	Máire-N	Npf-g
faoi	faoi	faoi-S	Sp
seo	seo	seo-P	Pd
.	.	.-F	Fe
Ionad	Ionad	ionad-N	Ncmsc
spraoi	spraoi	spraoi-N	Ncmsc|Ncmsg|Nv--g--n|Nv-----n
agus	agus	agus-C	Cc
spóirt	spóirt	spórt-N	Ncmsg|Ncmpc|Ncmsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
–	–	–-X	Xx
peil	peil	peil-N	Ncfsc
,	,	,-F	Fi
bádóireacht	bádóireacht	bádóir-N	Ncfsc|Nv-----n
,	,	,-F	Fi
cispheil	cispheil	cispheil-N	Ncfsc
,	,	,-F	Fi
dreapadóireacht	dreapadóireacht	dreapadóireacht-N	Ncfsc
,	,	,-F	Fi
sleamhnán	sleamhnán	sleamhnán-N	Ncmsc
láibe	láibe	láib-N	Ncfsg
,	,	,-F	Fi
tóraíocht	tóraíocht	tóraigh-N	Ncfsc|Nv
taisce	taisce	taisce-N	Ncfsg|Ncfsc
agus	agus	agus-C	Cc
go leor	go leor	go_leor-A	Aq|Ns-s|Rg
eile	eile	eile-D	Dd
.	.	.-F	Fe
Roinneadh	Roinneadh	roinn-V	Vmm-3s
ina	ina	i-S	Spp-p
ngrúpaí	ngrúpaí	grúpa-N	Ncmpc
iad	iad	iad-P	Pp3-p
,	,	,-F	Fi
Colm	Colm	Colm-N	Npmsc
i	i	i-S	Sp
ngrúpa	ngrúpa	grúpa-N	Ncmsc
an	an	an-T	Td-s
Mháistir	Mháistir	Máistir-N	Npfsg
,	,	,-F	Fi
ar	ar	ar-S	Sp
chúis	chúis	cúis-N	Ncfsc
éigin	éigin	éigin-A	Aq-fsc
,	,	,-F	Fi
agus	agus	agus-C	Cc
isteach	isteach	isteach-R	Rd
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
‑	‑	‑-F	Fb
lá	lá	lá-N	Ncmsc
acu	acu	ag-P	Pr3-p
,	,	,-F	Fi
ag	ag	ag-S	Sp
imirt	imirt	imir-N	Nv
is	is	agus-C	Cc
ag	ag	ag-S	Sp
spraoi	spraoi	spraoi-N	Nv-----n
i	i	i-S	Sp
gcomhluadar	gcomhluadar	comhluadar-N	Ncmsc
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
í	í	í-P	Pp3fs
an	an	an-T	Td-s
tóraíocht	tóraíocht	tóraíocht-N	Ncfsc
taisce	taisce	taisce-N	Ncfsg|Ncfsc
buaicphointe	buaicphointe	pointe-N	Ncmsc
an	an	an-T	Td-s
lae	lae	lá-N	Ncmsg
.	.	.-F	Fe
B	B	B-X	Xl
’	’	’-F	Fa
éigean	éigean	éigean-N	Ncmsc
do	do	do-S	Sp
gach	gach	gach-D	Dq
duine	duine	duine-N	Ncmsc
páirtí	páirtí	páirtí-N	Ncmsg|Ncmsc
a	a	a-U	U
roghnú	roghnú	roghnaigh-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	a-D	Dp3
Choilm	Choilm	colm-N	Ncmpc
!	!	!-F	Fe
Beidh	Beidh	bí-V	Vmif
tusa	tusa	tú-P	Pp2-s-e
agus	agus	agus-C	Cc
Bouli	Bouli	Bouli-N	Npmsc
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
arís	arís	arís-R	Rg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Máistir	Máistir	Máistir-N	Npmsc
.	.	.-F	Fe
Lig	Lig	lig-V	Vmis
Colm	Colm	Colm-N	Npmsc
air	air	ar-P	Pr3ms
féin	féin	féin-P	Px
nár	nár	nár-Q	Qnrs
thuig	thuig	tuig-V	Vmip---n|Vmis---n
sé	sé	sé-P	Pp3msn
gurb	gurb	is-W	Wpdi
é	é	é-P	Pp3ms
Bouli	Bouli	Bouli-N	Npmsc
,	,	,-F	Fi
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
sneachta	sneachta	sneachta-N	Ncmsg|Ncmsc
,	,	,-F	Fi
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
i	i	i-S	Sp
gceist	gceist	ceist-N	Ncfsc
aige	aige	ag-P	Pr3ms
,	,	,-F	Fi
ach	ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
dul	dul	dul-N	Ncmsc
as	as	as-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nach	Nach	nach-Q	Qnr
bhfuil	bhfuil	bí-V	Vmip---n
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
éisteacht	éisteacht	éist-N	Nv
,	,	,-F	Fi
a	a	a-U	Uv
Choilm	Choilm	colm-N	Ncmsv
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Máistir	Máistir	Máistir-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
tú	tú	tú-P	Pp2-s
fanacht	fanacht	fan-N	Ncmsc|Nv
i	i	i-S	Sp
m	m	m-X	Xl
’	’	’-F	Fa
fhochairse	fhochairse	fochair-N	Ns-s--e
.	.	.-F	Fe
’	’	’-F	Fa
Lean	Lean	Lean-N	Npmsc
Colm	Colm	Colm-N	Npmsc
an	an	an-T	Td-s
Máistir	Máistir	Máistir-N	Npmsg
go	go	go-U	Ua
tromchroíoch	tromchroíoch	tromchroíoch-A	Aqp
,	,	,-F	Fi
tromchosach	tromchosach	tromchosach-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
Máistir	Máistir	Máistir-N	Npmsc
féin	féin	féin-P	Px
ar	ar	ar-S	Sp
bís	bís	bís-N	Ncfsc
,	,	,-F	Fi
dar	dar	dar-S	Sp
ndóigh	ndóigh	dóigh-N	Ncfsc
,	,	,-F	Fi
ag	ag	ag-S	Sp
brostú	brostú	brostaigh-N	Nv
ar	ar	ar-S	Sp
aghaidh	aghaidh	aghaidh-N	Ncfsc
,	,	,-F	Fi
an	an	an-T	Td-s
léarscáil	léarscáil	léarscáil-N	Ncfsc
ina	ina	i-S	Spp-s|Spp-p
lámh	lámh	lámh-N	Ncfsc
,	,	,-F	Fi
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
féachaint	féachaint	féach-N	Nv
i	i	i-S	Sp
ngach	ngach	gach-D	Dq
treo	treo	treo-N	Ncmsc
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
sealgaire	sealgaire	sealgaire-N	Ncmsc
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
tríú	tríú	trí-M	Mo
leid	leid	leid-N	Ncfsc
faighte	faighte	faigh-A	Av
acu	acu	ag-P	Pr3-p
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
thosaigh	thosaigh	tosaigh-V	Vmis
an	an	an-T	Td-s
screadach	screadach	screadach-N	Ncfsc
.	.	.-F	Fe
Amadán	Amadán	amadán-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
ó	ó	ó-S	Sp
Rang	Rang	rang-N	Ncmsc
a	a	a-U	Um
Trí	Trí	trí-M	Mc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Nóinín	Nóinín	nóinín-N	Ncmsc
a	a	a-Q	Q-r
bhain	bhain	bain-V	Vmis
tuisle	tuisle	tuisle-N	Ncmsc
as	as	as-P	Pr3ms
,	,	,-F	Fi
ba	ba	is-W	Wsri
chosúil	chosúil	cosúil-A	Aqp
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ach	ach	ach-S	Sp
scríob	scríob	scríob-N	Ncfsc
bheag	bheag	beag-A	Aq-fsc
bhídeach	bhídeach	bídeach-A	Aq-fsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
ghlúin	ghlúin	glúin-N	Ncfsc
,	,	,-F	Fi
ach	ach	ach-C	Cs
rinne	rinne	déan-V	Vmis
sé	sé	sé-P	Pp3msn
olagón	olagón	olagón-N	Ncmsc
cráite	cráite	cráigh-A	Aqp|Av
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
bean	bean	bean-N	Ncfsc
sí	sí	sí-P	Pp3fsn
ann	ann	i-P	Pr3ms
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
deoir	deoir	deoir-N	Ncfsc
fola	fola	fuil-N	Ncfsg|Ncfpc|Ncfpg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
Máistir	Máistir	Máistir-N	Npmsc
chomh	chomh	chomh-R	Ri
gnóthach	gnóthach	gnóthach-A	Aqp
sin	sin	sin-P	Pd|W|Dd
leis	leis	le-S	Sp
an	an	an-T	Td-s
naíonán	naíonán	naíonán-N	Ncmsc
seo	seo	seo-D	Dd
nach	nach	nach-Q	Qnrs
bhfaca	bhfaca	feic-V	Vmis---d
sé	sé	sé-P	Pp3msn
Colm	Colm	Colm-N	Npmsc
ag	ag	ag-S	Sp
cúlú	cúlú	cúlaigh-N	Nv
,	,	,-F	Fi
ag	ag	ag-S	Sp
cúlú	cúlú	cúlaigh-N	Nv
uaidh	uaidh	ó-P	Pr3ms
go	go	go-U	Ua
deas	deas	deas-R	Ri
réidh	réidh	réidh-A	Aqp
,	,	,-F	Fi
céim	céim	céim-N	Ncfsc
ar	ar	ar-S	Sp
chéim	chéim	céim-N	Ncfsc
,	,	,-F	Fi
nó	nó	nó-C	Cc
gur	gur	gur-Q	Q--s
shroich	shroich	sroich-V	Vmis
sé	sé	sé-P	Pp3msn
crann	crann	crann-N	Ncmsc
mór	mór	mór-A	Aq-msc
ard	ard	ard-A	Aq-msc
géagach	géagach	géagach-A	Aq-msc
.	.	.-F	Fe
Suas	Suas	suas-R	Rd
leis	leis	le-P	Pr3ms
go	go	go-U	Ua
haclaí	haclaí	aclaí-A	Aqp
,	,	,-F	Fi
ag	ag	ag-S	Sp
dreapadh	dreapadh	dreap-N	Nv
leis	leis	le-P	Pr3ms
gan	gan	gan-S	Sp
stró	stró	stró-N	Ncmsc
–	–	–-X	Xx
scil	scil	scil-N	Ncfsc
eile	eile	eile-D	Dd
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhoghlaim	fhoghlaim	foghlaim-V	Vmis
sé	sé	sé-P	Pp3msn
sna	sna	i-S	Spa-p
gasóga	gasóga	gasóg-N	Ncfpc
,	,	,-F	Fi
dar	dar	dar-S	Sp
ndóigh	ndóigh	dóigh-N	Ncfsc
.	.	.-F	Fe
Lean	Lean	Lean-N	Npmsc
sé	sé	sé-W	Wp-i-3|Pp3msn
air	air	ar-P	Pr3ms
go dtí	go dtí	go_dtí-S	Spc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
i	i	i-S	Sp
bhfolach	bhfolach	folach-N	Ncmsc
i	i	i-S	Sp
measc	measc	measc-N	Ncmsc
na	na	na-T	Td-p
nduilleog	nduilleog	duilleog-N	Ncfpg
.	.	.-F	Fe
Shocraigh	Shocraigh	socraigh-V	Vmis
sé	sé	sé-P	Pp3msn
é	é	é-P	Pp3ms
féin	féin	féin-P	Px
go	go	go-U	Ua
compordach	compordach	compordach-A	Aqp
ar	ar	ar-S	Sp
chraobh	chraobh	craobh-N	Ncfsc
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
súil	súil	súil-N	Nv-----n
le	le	le-S	Sp
spórt	spórt	spórt-N	Ncmsc
is	is	agus-C	Cc
spraoi	spraoi	spraoi-N	Ncmsc|Nv-----n|Nv--g--n|Ncmsg|Nv-----n|Ncmsg|Nv--g--n|Nv-----n
.	.	.-F	Fe
Díreach	Díreach	díreach-N	Ncmsc
ansin	ansin	ansin-R	Rt|Rl
a	a	a-Q	Q-r
thug	thug	tabhair-V	Vmis
an	an	an-T	Td-s
Máistir	Máistir	Máistir-N	Npmsc
faoi	faoi	faoi-S	Sp
deara	deara	deara-N	Ns-s
den	den	de-S	Spa-s
chéad	chéad	céad-M	Mo
uair	uair	uair-N	Ncfsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
Colm	Colm	Colm-N	Npmsc
ar	ar	ar-S	Sp
iarraidh	iarraidh	iarr-N	Nv
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
sé	sé	sé-P	Pp3msn
soir	soir	soir-R	Rd
,	,	,-F	Fi
d	d	d-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
sé	sé	sé-P	Pp3msn
siar	siar	siar-R	Rd
,	,	,-F	Fi
d	d	d-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
sé	sé	sé-P	Pp3msn
soir	soir	soir-R	Rd
arís	arís	arís-R	Rg
.	.	.-F	Fe
Ghlaoigh	Ghlaoigh	glaoigh-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
Cholm	Cholm	Colm-N	Npmsc
.	.	.-F	Fe
Ghlaoigh	Ghlaoigh	glaoigh-V	Vmis
sé	sé	sé-P	Pp3msn
arís	arís	arís-R	Rg
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Ghlaoigh	Ghlaoigh	glaoigh-V	Vmis
sé	sé	sé-P	Pp3msn
in	in	sin-S	Sp|Pd
ard	ard	ard-N	Ncmsc|Aqp
a	a	a-Q	Q-r
chinn	chinn	cinn-V	Vmis
is	is	agus-C	Cc
a	a	a-D	Dp3
ghutha	ghutha	guth-N	Ncmsg
.	.	.-F	Fe
B	B	B-X	Xl
’	’	’-F	Fa
fhada	fhada	fada-A	Aqc
ó	ó	ó-C	Cs
bhí	bhí	bí-V	Vmis
a	a	a-D	Dp3
leithéid	leithéid	leithéid-N	Ncfsc
de	de	de-S	Sp
spraoi	spraoi	spraoi-N	Ncmsc
ag	ag	ag-S	Sp
Colm	Colm	Colm-N	Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
oiread	oiread	oiread-N	Ns-s
sin	sin	sin-D	Dd
fonn	fonn	fonn-N	Ncmsc
gáire	gáire	gáir-N	Ncfsg|Nv|Ncmsg|Ncmsc|Nv--g
air	air	ar-P	Pr3ms
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
i	i	i-S	Sp
riocht	riocht	riocht-N	Ncmsc
pléascadh	pléascadh	pléascadh-N	Nv|Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
baint	baint	bain-N	Nv
an	an	an-T	Td-s
méid	méid	méid-N	Ncmsg
sin	sin	sin-D	Dd
taitnimh	taitnimh	taitin-N	Ncmsg|Nv--g
as	as	as-S	Sp
cruachás	cruachás	cruachás-N	Ncmsc
an	an	an-T	Td-s
Mháistir	Mháistir	Máistir-N	Npfsg
go	go	go-Q	Q
ndearna	ndearna	déan-V	Vmis---d
sé	sé	sé-P	Pp3msn
dearmad	dearmad	dearmad-N	Ncmsc
glan	glan	glan-A	Aq-msc
gur	gur	is-W	Wsdi
thuas	thuas	thuas-R	Rd
i	i	i-S	Sp
gcrann	gcrann	crann-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
bhraith	bhraith	braith-V	Vmis---n
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
ghéag	ghéag	géag-N	Ncfsc
ag	ag	ag-S	Sp
lúbadh	lúbadh	lúb-N	Nv
faoina	faoina	faoi-S	Spp-s
mheáchan	mheáchan	meáchan-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
ansin	ansin	ansin-R	Rt|Rl
,	,	,-F	Fi
chuala	chuala	clois-V	Vmis
sé	sé	sé-P	Pp3msn
gíoscán	gíoscán	gíoscán-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
titim	titim	tit-N	Nv
,	,	,-F	Fi
a	a	a-U	Uv
lámha	lámha	lámh-N	Ncfpv
sínte	sínte	sín-A	Av
amach	amach	amach-R	Rd
uaidh	uaidh	ó-P	Pr3ms
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
breith	breith	beir-N	Ncfsc|Nv
ar	ar	ar-N	Ncmsc
…	…	…-F	Fi
aer	aer	aer-N	Ncmsc
.	.	.-F	Fe
Spéir	Spéir	spéir-N	Ncfsc
,	,	,-F	Fi
talamh	talamh	talamh-N	Ncfsc
,	,	,-F	Fi
spéir	spéir	spéir-N	Ncfsc
,	,	,-F	Fi
talamh	talamh	talamh-N	Ncfsc
,	,	,-F	Fi
gorm	gorm	gorm-A	Aqp
,	,	,-F	Fi
glas	glas	glas-A	Aqp
,	,	,-F	Fi
gorm	gorm	gorm-A	Aqp
,	,	,-F	Fi
glas	glas	glas-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
bholg	bholg	bolg-N	Ncmsc
trína	trína	trí-S	Spp-s
chéile	chéile	céile-N	Ncmsc
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
mearbhall	mearbhall	mearbhall-N	Ncmsc
ina	ina	i-S	Spp-s
cheann	cheann	ceann-N	Ncmsc
.	.	.-F	Fe
Mhothaigh	Mhothaigh	mothaigh-V	Vmis
sé	sé	sé-P	Pp3msn
t	t	t-X	Xl
‑	‑	‑-F	Fb
aer	aer	aer-N	Ncmsc
ag	ag	ag-S	Sp
séideadh	séideadh	séid-N	Nv
a	a	a-D	Dp3
chuid	chuid	cuid-N	Ncfsc
gruaige	gruaige	gruaig-N	Ncfsg
agus	agus	agus-C	Cc
a	a	a-D	Dp3
chuid	chuid	cuid-N	Ncfsc
éadaí	éadaí	éadach-N	Ncmpg
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
scread	scread	scread-V	Vmis---n
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Níorbh	Níorbh	is-W	Ws-in
fhiú	fhiú	fiú-N	Ns-s|Ncmsc
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
aige	aige	ag-P	Pr3ms
go	go	go-U	Ua
rímhaith	rímhaith	maith-A	Aqp
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
i	i	i-S	Sp
ndán	ndán	dán-N	Ncmsc
dó	dó	do-P	Pr3ms
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
bás	bás	bás-N	Ncmsc
agus	agus	agus-C	Cc
gur	gur	is-W	Wsdi|Wpdi
bás	bás	bás-N	Ncmsc
fuilteach	fuilteach	fuilteach-A	Aq-msc
tapa	tapa	tapa-A	Aqp
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Le	Le	le-S	Sp
cúnamh	cúnamh	cúnamh-N	Ncmsc
Dé	Dé	dia-N	Ncmsg
bheadh	bheadh	bí-V	Vmc
sé	sé	sé-P	Pp3msn
tapa	tapa	tapa-A	Aqp
.	.	.-F	Fe
Chuala	Chuala	clois-V	Vmis
sé	sé	sé-P	Pp3msn
feadaíl	feadaíl	feadaíl-N	Ncfsc|Nv-----n
ina	ina	i-S	Spp-s
chluasa	chluasa	cluas-N	Ncfpc
.	.	.-F	Fe
Na	Na	na-T	Td-p
héin	héin	éan-N	Ncmpc
?	?	?-F	Fq
An	An	is-W	Wp-q
t	t	t-X	Xl
‑	‑	‑-F	Fb
aer	aer	aer-N	Ncmsc
?	?	?-F	Fq
A	A	a-U	Uv
chuid	chuid	cuid-N	Ncfsv
fola	fola	fuil-N	Ncfsg
féin	féin	féin-P	Px
?	?	?-F	Fq
Ach	Ach	ach-C	Cs
ba	ba	is-W	Ws|Ws-i
dheacair	dheacair	deacair-A	Aqp
dó	dó	do-P	Pr3ms
greim	greim	greim-N	Ncmsc
a	a	a-U	U
fháil	fháil	faigh-N	Nv
ar	ar	is-W	Wssi|Wpdi|Wpsi
aon	aon	aon-D	Dq
smaoineamh	smaoineamh	smaoineamh-N	Ncmsc
fónta	fónta	fóin-A	Aqp|Av
.	.	.-F	Fe
Há	Há	Há-N	Npmsc
!	!	!-F	Fe
Níorbh	Níorbh	is-W	Ws-in
fhiú	fhiú	fiú-N	Ns-s|Ncmsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
smaoineamh	smaoineamh	smaoinigh-N	Nv
anois	anois	anois-R	Rt
,	,	,-F	Fi
dar	dar	dar-S	Sp
ndóigh	ndóigh	dóigh-N	Ncfsc
.	.	.-F	Fe
Níorbh	Níorbh	is-W	Ws-in
fhiú	fhiú	fiú-N	Ns-s|Ncmsc
faic	faic	faic-N	Ncfsc
na	na	na-T	Td-p
smaointe	smaointe	smaoineamh-N	Ncmpg
céanna	céanna	céanna-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
t	t	t-X	Xl
‑	‑	‑-F	Fb
aer	aer	aer-N	Ncmsc
ag	ag	ag-S	Sp
tarraingt	tarraingt	tarraing-N	Nv
ar	ar	ar-S	Sp
mhuinchillí	mhuinchillí	muinchille-N	Ncfpc
a	a	a-D	Dp3
gheansaí	gheansaí	geansaí-N	Ncmsc
.	.	.-F	Fe
Dá	Dá	dá-C	Cs
mbeadh	mbeadh	bí-V	Vmc
cóta	cóta	cóta-N	Ncmsc
féin	féin	féin-P	Px
air	air	ar-P	Pr3ms
bheadh	bheadh	bí-V	Vmc
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
pharaisiút	pharaisiút	paraisiút-N	Ncmsc
agus	agus	agus-C	Cc
chuirfeadh	chuirfeadh	cuir-V	Vmc
sé	sé	sé-P	Pp3msn
moill	moill	moill-N	Ncfsc
éigin	éigin	éigin-A	Aq-fsc
ar	ar	is-W	Wpsi|Ncmsc|Wssi|Wpdi
titim	titim	tit-V	Vmip1s
.	.	.-F	Fe
Bheadh	Bheadh	bí-V	Vmc
seans	seans	seans-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
aige	aige	ag-P	Pr3ms
dá	dá	dá-C	Cs
mbeadh	mbeadh	bí-V	Vmc
paiste	paiste	paiste-N	Ncmsc
móintigh	móintigh	móinteach-N	Ncmpc
nó	nó	nó-C	Cc
lochán	lochán	lochán-N	Ncmpg|Ncmsc|Ncmpg
uisce	uisce	uisce-N	Ncmsg|Ncmsc
nó	nó	nó-C	Cc
sceach	sceach	sceach-N	Ncfpg|Ncfsc|Ncfpg
faoi	faoi	faoi-P	Pr3ms
,	,	,-F	Fi
go	go	go-C	Cs|Sp
fiú	fiú	fiú-N	Ns-s|Ncmsc|Rg
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
faoin	faoin	faoi-S	Spa-s
gcrann	gcrann	crann-N	Ncmsc
ach	ach	ach-S	Sp
talamh	talamh	talamh-N	Ncfsc
chrua	chrua	crua-A	Aqp
chlochach	chlochach	clochach-A	Aqp
…	…	…-F	Fi
Dhúisigh	Dhúisigh	dúisigh-V	Vmis
sé	sé	sé-P	Pp3msn
san	san	i-S	Spa-s
otharcharr	otharcharr	otharcharr-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
cheann	cheann	ceann-N	Ncmsc
á	á	do-S	Spo-s
scoilteadh	scoilteadh	scoilt-N	Nv
ag	ag	ag-S	Sp
scréachach	scréachach	scréach-N	Nv
an	an	an-T	Td-s
bhonnáin	bhonnáin	bonnán-N	Ncmsg
.	.	.-F	Fe
Chuala	Chuala	clois-V	Vmis
sé	sé	sé-P	Pp3msn
glór	glór	glór-N	Ncmsc
an	an	an-T	Td-s
Mháistir	Mháistir	Máistir-N	Npfsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ina	ina	i-S	Spp-s
shuí	shuí	suí-N	Ncmsc
taobh	taobh	taobh-N	Ncmsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
,	,	,-F	Fi
a	a	a-U	Uv
Choilm	Choilm	colm-N	Ncmsv
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
caol	caol	caol-N	Ncmsc
do	do	do-S	Sp
láimhe	láimhe	lámh-N	Ncfsg
briste	briste	bris-A	Aqp|Av
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
tú	tú	tú-P	Pp2-s
in ann	in ann	in_ann-S	Spc
faic	faic	faic-N	Ncfsc
a	a	a-U	U
scríobh	scríobh	scríobh-N	Nv
go ceann	go ceann	go_ceann-S	Spc
sé	sé	sé-W	Wp-i-3|Pp3msn
seachtaine	seachtaine	seachtain-N	Ncfsg
.	.	.-F	Fe
'	'	'-F	Fa
Leath	Leath	leath-D	Dq
meangadh	meangadh	meang-V	Vmis0
mór	mór	mór-N	Ncmsc
ar	ar	ar-S	Sp
aghaidh	aghaidh	aghaidh-N	Ncfsc
Choilm	Choilm	colm-N	Ncmsg
in	in	sin-P	Pd
ainneoin	ainneoin	ainneoin-C	Cs
na	na	na-T	Tdfsg
péine	péine	pian-N	Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
mé	mé	mé-P	Pp1-s
in ann	in ann	in_ann-S	Spc
scríobh	scríobh	scríobh-N	Nv
!	!	!-F	Fe
Ní	Ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
mé	mé	mé-P	Pp1-s
in ann	in ann	in_ann-S	Spc
aon	aon	aon-D	Dq
obair	obair	obair-N	Ncfsc
scoile	scoile	scoil-N	Ncfsg
ná	ná	ná-C	Cc
obair	obair	obair-N	Ncfsc|Nv-----n
bhaile	bhaile	baile-N	Ncmsg
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
go ceann	go ceann	go_ceann-S	Spc
sé	sé	sé-W	Wp-i-3|Pp3msn
seachtaine	seachtaine	seachtain-N	Ncfsg
!	!	!-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
By	By	by-X	Xfer|Xfes
dad	dad	dad-X	Xfen
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Máistir	Máistir	Máistir-N	Npmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
nach	nach	nach-W	Wprin|Wpdin|Wpsin|Cs
maith	maith	maith-N	Ncfsc|Aqp
an	an	an-T	Td-s
rud	rud	rud-N	Ncmsc
é	é	é-P	Pp3ms
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
saoire	saoire	saoire-N	Ncfsc
an	an	an-T	Td-s
tsamhraidh	tsamhraidh	samhradh-N	Ncmsg
ag	ag	ag-S	Sp
tosú	tosú	tosaigh-N	Nv
amárach	amárach	amárach-R	Rt
.	.	.-F	Fe
’	’	’-F	Fa
