Gort	Gort	gort-N	Ncmsc
an	an	an-T	Td-s
Leasa	Leasa	leas-N	Ncmsg
.	.	.-F	Fe
Fadó	Fadó	fadó-R	Rg
,	,	,-F	Fi
fadó	fadó	fadó-R	Rg
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
cónaí	cónaí	cónaí-N	Ncmsc
ar	ar	ar-S	Sp
bhaintreach	bhaintreach	baintreach-N	Ncfsc
bhocht	bhocht	bocht-A	Aq-fsc
i	i	i-S	Sp
mBaile	mBaile	Baile-N	Npmsc
na	na	na-T	Td-p
Rún	Rún	rún-N	Ncmpg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
beirt	beirt	beirt-N	Ncfsc
mhac	mhac	mac-N	Ncmsc
aici	aici	ag-P	Pr3fs
,	,	,-F	Fi
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Oisín	Oisín	Oisín-N	Npmsc
agus	agus	agus-C	Cc
Diarmaid	Diarmaid	Diarmaid-N	Npmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
de	de	de-S	Sp
mhaoin	mhaoin	maoin-N	Ncfsc
an	an	an-T	Td-s
tsaoil	tsaoil	saol-N	Ncmsg
acu	acu	ag-P	Pr3-p
ach	ach	ach-S	Sp
cúpla	cúpla	cúpla-N	Ncmsc
garraí	garraí	garraí-N	Ncmsc
beag	beag	beag-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
míle	míle	míle-M	Mc
nó	nó	nó-C	Cc
dhó	dhó	dó-M	Mc
ón	ón	ó-S	Spa-s
teach	teach	teach-N	Ncmsc
.	.	.-F	Fe
Mholadh	Mholadh	mol-V	Vmih
na	na	na-T	Td-p
daoine	daoine	duine-N	Ncmpc
Oisín	Oisín	Oisín-N	Npm-g|Npmsg|Npm-g|Npmsc|Npfsg
go	go	go-U	Ua
hard	hard	ard-X	Xfea|Aqp
na	na	na-T	Tdfsg
spéire	spéire	spéir-N	Ncfsg
.	.	.-F	Fe
Bhíodh	Bhíodh	bí-V	Vmih
Diarmaid	Diarmaid	Diarmaid-N	Npmsc
bodhraithe	bodhraithe	bodhraigh-A	Av
ag	ag	ag-S	Sp
éisteacht	éisteacht	éist-N	Nv
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
De réir	De réir	de_réir-C	Cs|Spc
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
d	d	d-X	Xl
’	’	’-F	Fa
fhás	fhás	fás-V	Vmis
éad	éad	éad-N	Ncmsc
i	i	i-S	Sp
gcroí	gcroí	croí-N	Ncmsc
Dhiarmada	Dhiarmada	Diarmada-N	Npm-g|Npfsg
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmis
sé	sé	sé-P	Pp3msn
míshona	míshona	míshona-A	Aqp
stuacach	stuacach	stuacach-A	Aqp
ann	ann	i-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
thugadh	thugadh	tabhair-V	Vmih---n
sé	sé	sé-P	Pp3msn
lámh	lámh	lámh-N	Ncfsc
chúnta	chúnta	cúnaigh-N	Nv--g
d	d	d-X	Xl
’	’	’-F	Fa
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
riamh	riamh	riamh-R	Rg
agus	agus	agus-C	Cc
sheachnaíodh	sheachnaíodh	seachain-V	Vmih
sé	sé	sé-P	Pp3msn
comhluadar	comhluadar	comhluadar-N	Ncmsc
na	na	na-T	Td-p
ndaoine	ndaoine	duine-N	Ncmpg
a	a	a-D	Dp3
oiread	oiread	oiread-N	Ns-s
is	is	agus-W	Wp-i|Wpri|Cc
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhéadfadh	fhéadfadh	féad-V	Vmc
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Dhéanadh	Dhéanadh	déan-V	Vmih
a	a	a-D	Dp3
mháthair	mháthair	máthair-N	Ncfsc
iarracht	iarracht	iarracht-N	Ncfsc
comhairle	comhairle	comhairle-N	Ncfsg|Ncfsc
a	a	a-U	U
chur	chur	cuir-N	Nv
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	is-W	Wp-in
éisteadh	éisteadh	éist-V	Vmih
sé	sé	sé-P	Pp3msn
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
éisteadh	éisteadh	éist-V	Vmih---n
sé	sé	sé-P	Pp3msn
le	le	le-S	Sp
haon	haon	aon-D	Dq
duine	duine	duine-N	Ncmsc
.	.	.-F	Fe
Faoi	Faoi	faoi-S	Sp
dheireadh	dheireadh	deireadh-N	Ncmsc
thug	thug	tabhair-V	Vmis
a	a	a-D	Dp3
mháthair	mháthair	máthair-N	Ncfsc
Diarmaid	Diarmaid	Diarmaid-N	Npmsc
go dtí	go dtí	go_dtí-S	Spc
Máire	Máire	Máire-N	Npfsc
Dhubh	Dhubh	dubh-A	Aq-fsc
an	an	an-T	Td-s
tSléibhe	tSléibhe	sliabh-N	Ncmsg
.	.	.-F	Fe
Bean	Bean	bean-N	Ncfsc
feasa	feasa	fios-N	Ncmsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
i	i	i-S	Sp
Máire	Máire	Máire-N	Npfsc
Dhubh	Dhubh	dubh-A	Aq-fsc|Aq-fsv
a	a	a-Q	Q-r
chónaigh	chónaigh	cónaigh-V	Vmis
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
i	i	i-S	Sp
gcúl	gcúl	cúl-N	Ncmsc
an	an	an-T	Td-s
chnoic	chnoic	cnoc-N	Ncmsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
de	de	de-S	Sp
cháil	cháil	cáil-N	Ncmpc|Ncfsc
ar	ar	ar-S	Sp
Mháire	Mháire	Máire-N	Npfsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
leigheas	leigheas	leigheas-N	Ncmsc
aici	aici	ag-P	Pr3fs
ar	ar	ar-S	Sp
gach	gach	gach-D	Dq
aon	aon	aon-D	Dq
aicíd	aicíd	aicíd-N	Ncfsc
a	a	a-Q	Q-r
thiocfadh	thiocfadh	tar-V	Vmc
ar	ar	ar-S	Sp
cholainn	cholainn	colainn-N	Ncfsc
nó	nó	nó-C	Cc
ar	ar	ar-S	Sp
mheabhair	mheabhair	meabhair-N	Ncfsc
an	an	an-T	Td-s
duine	duine	duine-N	Ncmsg
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbean	mbean	bean-N	Ncfsc
feasa	feasa	fios-N	Ncmsg
seo	seo	seo-D	Dd
a	a	a-Q	Q-r
thrialladh	thrialladh	triall-V	Vmih
muintir	muintir	muintir-N	Ncfsc
Bhaile	Bhaile	Baile-N	Npmsc
na	na	na-T	Td-p
Rún	Rún	rún-N	Ncmpg
in	in	i-S	Sp
am	am	am-N	Ncmsc
an	an	an-T	Td-s
ghá	ghá	gá-N	Ncmsg
agus	agus	agus-C	Cc
an	an	an-T	Td-s
ghátair	ghátair	gátar-N	Ncmsg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-N	Ncmsc|Nv
Máire	Máire	Máire-N	Npfsc
Dhubh	Dhubh	dubh-A	Aq-fsc
sa	sa	i-S	Spa-s
tine	tine	tine-N	Ncfsc
agus	agus	agus-C	Cc
tháinig	tháinig	tar-V	Vmis
scáil	scáil	scál-N	Ncfsc|Ncmpc
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
súile	súile	súil-N	Ncfpc
.	.	.-F	Fe
Lig	Lig	lig-V	Vmis
sí	sí	sí-P	Pp3fsn
osna	osna	osna-N	Ncmsc
fhada	fhada	fada-A	Aqp
aisti	aisti	as-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	an-T	Td-s
Dhiarmaid	Dhiarmaid	Diarmaid-N	Npmsc
bhig	bhig	beag-A	Aq-msv|Aq-msg
na	na	na-T	Td-p
gcleas	gcleas	cleas-N	Ncmpg
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
leis	leis	le-P	Pr3ms
faoi	faoi	faoi-S	Sp
dheireadh	dheireadh	deireadh-N	Ncmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
mura	mura	mura-C	Cs
n	n	n-X	Xl
‑	‑	‑-F	Fb
athraíonn	athraíonn	athraigh-V	Vmip
tú	tú	tú-P	Pp2-s
béasa	béasa	béas-N	Ncmpc
beidh	beidh	bí-V	Vmif
aiféala	aiféala	aiféala-N	Ncmsc
fós	fós	fós-R	Rg
ort	ort	ar-P	Pr2-s
.	.	.-F	Fe
'	'	'-F	Fa
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
faraor	faraor	faraor-X	Xsc
géar	géar	géar-N	Ncmsc
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
Diarmaid	Diarmaid	Diarmaid-N	Npmsc
chomh	chomh	chomh-R	Ri
ceanndána	ceanndána	ceanndána-A	Aqp
agus	agus	agus-C	Cc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
riamh	riamh	riamh-R	Rg
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
éistfeadh	éistfeadh	éist-V	Vmc----n
sé	sé	sé-P	Pp3msn
fiú	fiú	fiú-N	Ns-s|Ncmsc|Rg
le	le	le-S	Sp
Máire	Máire	Máire-N	Npfsc
Dhubh	Dhubh	dubh-A	Aq-fsc
an	an	an-T	Td-s
tSléibhe	tSléibhe	sliabh-N	Ncmsg
.	.	.-F	Fe
Tráthnóna	Tráthnóna	tráthnóna-N	Ncmsc
amháin	amháin	amháin-A	Aqp
,	,	,-F	Fi
tamall	tamall	tamall-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|Dd
,	,	,-F	Fi
agus	agus	agus-C	Cc
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
ó	ó	ó-S	Sp
sholas	sholas	solas-N	Ncmsc
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
Oisín	Oisín	Oisín-N	Npmsc
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
abhaile	abhaile	abhaile-R	Rd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
caite	caite	caith-A	Av
aige	aige	ag-P	Pr3ms
ag	ag	ag-S	Sp
obair	obair	obair-N	Nv-----n
.	.	.-F	Fe
Cé	Cé	cé-P	Pq
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fheicfeadh	fheicfeadh	feic-V	Vmc
sé	sé	sé-P	Pp3msn
amach	amach	amach-R	Rd
roimhe	roimhe	roimh-P	Pr3ms
ach	ach	ach-S	Sp|Cs
a	a	a-D	Dp3
dheartháir	dheartháir	deartháir-N	Ncmsc
Diarmaid	Diarmaid	Diarmaid-N	Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Diarmaid	Diarmaid	Diarmaid-N	Npmsc
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
ar	ar	ar-S	Sp
Ghort	Ghort	gort-N	Ncmsc
an	an	an-T	Td-s
Leasa	Leasa	leas-N	Ncmsg
.	.	.-F	Fe
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
gort	gort	gort-N	Ncmsc
sin	sin	sin-D	Dd
faoi	faoi	faoi-P	Pr3ms
gheasa	gheasa	geis-N	Ncfpc
ag	ag	ag-S	Sp
na	na	na-T	Td-p
sióga	sióga	sióg-N	Ncfpc
,	,	,-F	Fi
agus	agus	agus-C	Cc
dá	dá	dá-C	Cs
rachadh	rachadh	téigh-V	Vmc
ghrian	ghrian	grian-V	Vmis
faoi	faoi	faoi-P	Pr3ms
agus	agus	agus-C	Cc
tú	tú	tú-P	Pp2-s
istigh	istigh	istigh-R	Rl
ann	ann	i-P	Pr3ms
,	,	,-F	Fi
nach	nach	nach-Q	Qnr
bhfeicfeá	bhfeicfeá	feic-V	Vmc-2s
solas	solas	solas-N	Ncmsc
an	an	an-T	Td-s
lae	lae	lá-N	Ncmsg
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
arís	arís	arís-R	Rg
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
spéis	spéis	spéis-N	Ncfsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
ag	ag	ag-S	Sp
Diarmaid	Diarmaid	Diarmaid-N	Npmsc
i	i	i-S	Sp
seanscéalta	seanscéalta	seanscéal-N	Ncmpc
ná	ná	ná-C	Cc
i	i	i-S	Sp
seanchas	seanchas	seanchas-N	Ncmsc
d	d	d-X	Xl
’	’	’-F	Fa
aon	aon	aon-D	Dq
sórt	sórt	sórt-N	Ncmsc
.	.	.-F	Fe
Chinn	Chinn	cinn-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
shiúl	shiúl	siúl-N	Ncmsc
trasna	trasna	trasna-S	Sp
an	an	an-T	Td-s
ghoirt	ghoirt	gort-N	Ncmsg
chun go	chun go	chun_go-C	Cs
mbainfeadh	mbainfeadh	bain-V	Vmc
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
teach	teach	teach-N	Ncmsc
amach	amach	amach-R	Rd
roimh	roimh	roimh-S	Sp
Oisín	Oisín	Oisín-N	Npmsc
agus	agus	agus-C	Cc
go	go	go-Q	Q
bhfaigheadh	bhfaigheadh	faigh-V	Vmc----d|Vmih
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
chéad	chéad	céad-M	Mo
bhlaiseadh	bhlaiseadh	blaiseadh-N	Ncmsc
de	de	de-S	Sp
bhia	bhia	bia-N	Ncmsc
an	an	an-T	Td-s
tráthnóna	tráthnóna	tráthnóna-N	Ncmsg
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
Oisín	Oisín	Oisín-N	Npmsc
rabhadh	rabhadh	rabhadh-N	Ncmsc
dó	dó	do-P	Pr3ms
agus	agus	agus-C	Cc
dúirt	dúirt	abair-V	Vmis
leis	leis	le-P	Pr3ms
gan	gan	gan-S	Sp
dul	dul	téigh-N	Nv
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
ghort	ghort	gort-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Má	Má	má-C	Cs
théann	théann	téigh-V	Vmip
ghrian	ghrian	grian-V	Vmis
faoi	faoi	faoi-P	Pr3ms
agus	agus	agus-C	Cc
tú	tú	tú-P	Pp2-s
i	i	i-S	Sp
nGort	nGort	gort-N	Ncmsc
an	an	an-T	Td-s
Leasa	Leasa	leas-N	Ncmsg
ní	ní	ní-Q	Qn
éalóidh	éalóidh	éalaigh-V	Vmif---n
tú	tú	tú-P	Pp2-s
as	as	as-P	Pr3ms|Sp|Ncmsc
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nach	Nach	is-C	Cs|Wpdin|Wpsin
sásta	sásta	sásta-A	Aqp|Aqc
a	a	a-Q	Q-r
bheidh	bheidh	bí-V	Vmif
gach	gach	gach-D	Dq
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
mura	mura	mura-C	Cs
n	n	n-X	Xl
‑	‑	‑-F	Fb
éalaím	éalaím	éalaigh-V	Vmip1s
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Diarmaid	Diarmaid	Diarmaid-N	Npmsc
go	go	go-U	Ua
grod	grod	grod-A	Aqp
.	.	.-F	Fe
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
léim	léim	léim-V	Vmis
sé	sé	sé-P	Pp3msn
thar	thar	thar-S	Sp
an	an	an-T	Td-s
gclaí	gclaí	claí-N	Ncmsc
agus	agus	agus-C	Cc
isteach	isteach	isteach-R	Rd
leis	leis	le-S	Sp
sa	sa	i-S	Spa-s
ghort	ghort	gort-N	Ncmsc
.	.	.-F	Fe
Sheas	Sheas	seas-V	Vmis
Oisín	Oisín	Oisín-N	Npmsc
tamall	tamall	tamall-N	Ncmsc
ag	ag	ag-S	Sp
stánadh	stánadh	stán-N	Nv
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
ghort	ghort	gort-N	Ncmsc
.	.	.-F	Fe
Cé	Cé	cé-C	Cs
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
ghrian	ghrian	grian-N	Ncfsc
imithe	imithe	imigh-A	Av
faoi	faoi	faoi-P	Pr3ms
bhí	bhí	bí-V	Vmis
Gort	Gort	gort-N	Ncmsc
an	an	an-T	Td-s
Leasa	Leasa	leas-N	Ncmsg
le	le	le-S	Sp
feiceáil	feiceáil	feic-N	Nv
go	go	go-U	Ua
soiléir	soiléir	soiléir-A	Aqp
sa	sa	i-S	Spa-s
chlapsholas	chlapsholas	clapsholas-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
Diarmaid	Diarmaid	Diarmaid-N	Npmsc
le	le	le-S	Sp
feiceáil	feiceáil	feic-N	Nv
in	in	i-S	Sp
aon	aon	aon-D	Dq
chor	chor	cor-N	Ncmsc
.	.	.-F	Fe
An	An	an-Q	Qq
bhféadfadh	bhféadfadh	féad-V	Vmc
sé	sé	sé-P	Pp3msn
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
sciobtha	sciobtha	sciob-A	Aqp|Av
cheana	cheana	cheana-R	Rg
féin	féin	féin-P	Px
ag	ag	ag-S	Sp
sióga	sióga	sióg-N	Ncfpc
Ghort	Ghort	gort-N	Ncmpg
an	an	an-T	Td-s
Leasa	Leasa	leas-N	Ncmsg
?	?	?-F	Fq
Thiontaigh	Thiontaigh	tiontaigh-V	Vmis
Oisín	Oisín	Oisín-N	Npmsc
de	de	de-U	Up
gheit	gheit	geit-V	Vmis
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
sé	sé	sé-P	Pp3msn
aghaidh	aghaidh	aghaidh-N	Ncfsc
ar	ar	ar-S	Sp
theach	theach	teach-N	Ncmsc
Mháire	Mháire	Máire-N	Npfsc
Dhubh	Dhubh	dubh-A	Aq-fsc
chomh	chomh	chomh-R	Ri
tiubh	tiubh	tiubh-A	Aqp
géar	géar	géar-A	Aqp
agus	agus	agus-C	Cc
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhéadfadh	fhéadfadh	féad-V	Vmc
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Chonacthas	Chonacthas	feic-V	Vmis0
do	do	do-S	Sp
Dhiarmaid	Dhiarmaid	Diarmaid-N	Npmsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
gach	gach	gach-D	Dq
rud	rud	rud-N	Ncmsc
ina	ina	i-S	Spp-s
thimpeall	thimpeall	timpeall-N	Ncmsc
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
na	na	na-T	Td-p
ballaí	ballaí	balla-N	Ncmpc
cloiche	cloiche	cloch-N	Ncfsg
,	,	,-F	Fi
na	na	na-T	Td-p
tithe	tithe	teach-N	Ncmpc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
cnoic	cnoic	cnoc-N	Ncmpc
le	le	le-S	Sp
feiceáil	feiceáil	feic-N	Nv
fós	fós	fós-R	Rg
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
scáil	scáil	scáil-N	Ncfsc
thaibhsiúil	thaibhsiúil	taibhsiúil-A	Aq-fsc
éigin	éigin	éigin-A	Aq-fsc
idir	idir	idir-S	Sp
é	é	é-P	Pp3ms
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
an	an	an-T	Td-s
claí	claí	claí-N	Ncmsg|Ncmsc
.	.	.-F	Fe
Nó	Nó	nó-C	Cc
an	an	is-W	Wpdq|Wp-q
é	é	é-P	Pp3ms
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
mearbhall	mearbhall	mearbhall-N	Ncmsc
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
air	air	ar-P	Pr3ms
?	?	?-F	Fq
Rinne	Rinne	déan-V	Vmis
sé	sé	sé-P	Pp3msn
iarracht	iarracht	iarracht-N	Ncfsc
dul	dul	téigh-N	Ncmsc|Nv
suas	suas	suas-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gclaí	gclaí	claí-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sé	sé	sé-P	Pp3msn
ábalta	ábalta	ábalta-A	Aqp
.	.	.-F	Fe
Rith	Rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
timpeall	timpeall	timpeall-S	Sp
an	an	an-T	Td-s
ghoirt	ghoirt	gort-N	Ncmsg
ag	ag	ag-S	Sp
cuardach	cuardach	cuardaigh-N	Nv
bealach	bealach	bealach-N	Ncmsc
éalaithe	éalaithe	éalaigh-A	Av
.	.	.-F	Fe
Ach	Ach	ach-S	Sp
bealach	bealach	bealach-N	Ncmsc
éalaithe	éalaithe	éalaigh-A	Av
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
le	le	le-S	Sp
fáil	fáil	faigh-N	Nv
.	.	.-F	Fe
Lig	Lig	lig-V	Vmis
sé	sé	sé-P	Pp3msn
scread	scread	scread-N	Ncfsc
as	as	as-P	Pr3ms
.	.	.-F	Fe
Ach	Ach	ach-S	Sp
freagra	freagra	freagra-N	Ncmsc
dá	dá	do-S	Spp-s|Spp-p|Spp-s|Spp-p
laghad	laghad	laghad-N	Ncmsc
ní	ní	ní-Q	Qn
bhfuair	bhfuair	faigh-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Bhuail	Bhuail	buail-V	Vmis
scanradh	scanradh	scanradh-N	Ncmsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Chaithfeadh	Chaithfeadh	caith-V	Vmc
sé	sé	sé-P	Pp3msn
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
faoi	faoi	faoi-S	Sp
gheasa	gheasa	geis-N	Ncfpc
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
é	é	é-P	Pp3ms
fágtha	fágtha	fág-A	Av
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
dorchadas	dorchadas	dorchadas-N	Ncmsc
na	na	na-T	Tdfsg
hoíche	hoíche	oíche-N	Ncfsg
ag	ag	ag-S	Sp
titim	titim	tit-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
cinnte	cinnte	cinnte-A	Av|Aqp
dearfa	dearfa	dearfa-A	Aqp
de	de	de-P	Pr3ms
nach	nach	nach-Q	Qnr
dtiocfadh	dtiocfadh	tar-V	Vmc
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
i	i	i-S	Sp
gcabhair	gcabhair	cabhar-N	Ncfsc|Ncmpc
air	air	ar-N	Ncmsg
go	go	go-U	Ua
brách	brách	brách-A	Aqp
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
thuigfeadh	thuigfeadh	tuig-V	Vmc
sé	sé	sé-P	Pp3msn
dóibh	dóibh	do-P	Pr3-p
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
cailleadh	cailleadh	caill-N	Nv
a	a	a-Q	Q-r
mhisnigh	mhisnigh	misnigh-V	Vmis
.	.	.-F	Fe
Chaith	Chaith	caith-V	Vmis
sé	sé	sé-P	Pp3msn
faoi	faoi	faoi-P	Pr3ms|Sp
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhféar	bhféar	féar-N	Ncmsc
fuar	fuar	fuar-A	Aq-msc
fliuch	fliuch	fliuch-A	Aq-msc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
ceo	ceo	ceo-N	Ncmsc
ag	ag	ag-S	Sp
dúnadh	dúnadh	dún-N	Nv
isteach	isteach	isteach-R	Rd
ar	ar	ar-S	Sp
Dhiarmaid	Dhiarmaid	Diarmaid-N	Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
aige	aige	ag-P	Pr3ms
gur	gur	is-W	Wsdi
cheo	cheo	ceo-N	Ncmsc
draíochta	draíochta	draíocht-N	Ncfsg|Ncfpc|Ncfpg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
agus	agus	agus-C	Cc
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
sé	sé	sé-P	Pp3msn
sciobtha	sciobtha	sciob-A	Av
ag	ag	ag-S	Sp
an	an	an-T	Td-s
slua	slua	slua-N	Ncmsc
sí	sí	sí-P	Pp3fsn
faoi	faoi	faoi-S	Sp
mhaidin	mhaidin	maidin-N	Ncfsc
,	,	,-F	Fi
gan	gan	gan-S	Sp
éalú	éalú	éalaigh-N	Nv
i	i	i-S	Sp
ndán	ndán	dán-N	Ncmsc
dó	dó	do-P	Pr3ms
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
na	na	na-T	Td-p
ndeor	ndeor	deoir-N	Ncfpg
.	.	.-F	Fe
Shuigh	Shuigh	suigh-V	Vmis
sé	sé	sé-P	Pp3msn
ansin	ansin	ansin-R	Rt|Rl
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
a	a	a-U	U
mhachnaimh	mhachnaimh	machnaigh-N	Nv--g
.	.	.-F	Fe
Smaoinigh	Smaoinigh	smaoinigh-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
tsáinn	tsáinn	sáinn-N	Ncfsc
ina	ina	i-S	Spr
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Smaoinigh	Smaoinigh	smaoinigh-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
shaol	shaol	saol-N	Ncmsc
go dtí	go dtí	go_dtí-S	Spc
sin	sin	sin-P	Pd
.	.	.-F	Fe
Smaoinigh	Smaoinigh	smaoinigh-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
mháthair	mháthair	máthair-N	Ncfsc
agus	agus	agus-C	Cc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
dheartháir	dheartháir	deartháir-N	Ncmsc
.	.	.-F	Fe
Den	Den	de-S	Spa-s
chéad	chéad	céad-M	Mo
uair	uair	uair-N	Ncfsc
riamh	riamh	riamh-R	Rg
mhothaigh	mhothaigh	mothaigh-V	Vmis
sé	sé	sé-P	Pp3msn
aithreachas	aithreachas	aithreachas-N	Ncmsc
ina	ina	i-S	Spp-s
chroí	chroí	croí-N	Ncmsc
istigh	istigh	istigh-R	Rl
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhan	fhan	fan-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-U	Ua
foighneach	foighneach	foighneach-A	Aqp
ansin	ansin	ansin-R	Rt|Rl
sa	sa	i-S	Spa-s
dorchadas	dorchadas	dorchadas-N	Ncmsc
go	go	go-Q	Q
sciobfadh	sciobfadh	sciob-V	Vmc
ceo	ceo	ceo-N	Ncmsc
draíochta	draíochta	draíocht-N	Ncfpc
an	an	an-T	Td-s
tslua	tslua	slua-N	Ncmsg
sí	sí	sí-P	Pp3fsn
é	é	é-P	Pp3ms
.	.	.-F	Fe
Tríd	Tríd	trí-S	Sp
an	an	an-T	Td-s
gceo	gceo	ceo-N	Ncmsc
,	,	,-F	Fi
chonaic	chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
solas	solas	solas-N	Ncmsc
beag	beag	beag-A	Aq-msc
buí	buí	buí-A	Aqp
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
bhí	bhí	bí-V	Vmis
dhá	dhá	dó-M	Mc
sholas	sholas	solas-N	Ncmsc
ann	ann	i-P	Pr3ms
,	,	,-F	Fi
trí	trí	trí-M	Mc
cinn	cinn	ceann-N	Ncmpc
,	,	,-F	Fi
ceithre	ceithre	ceathair-M	Mc
cinn	cinn	ceann-N	Ncmpc
…	…	…-F	Fi
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
crith	crith	crith-N	Nv
le	le	le-S	Sp
heagla	heagla	eagla-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
cinnte	cinnte	cinnte-A	Av|Aqp
dearfa	dearfa	dearfa-A	Aqp
de	de	de-P	Pr3ms
nárbh	nárbh	is-W	Wsrin
fhada	fhada	fada-A	Aqc|Aqp
uaidh	uaidh	ó-P	Pr3ms
an	an	an-T	Td-s
slua	slua	slua-N	Ncmsc
sí	sí	sí-P	Pp3fsn
anois	anois	anois-R	Rt
.	.	.-F	Fe
Níorbh	Níorbh	is-W	Ws-in
iad	iad	iad-P	Pp3-p
an	an	an-T	Td-s
slua	slua	slua-N	Ncmsc
sí	sí	sí-P	Pp3fsn
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
faoina	faoina	faoi-S	Spp-s
dhéin	dhéin	déan-N	Ncmpc
,	,	,-F	Fi
áfach	áfach	áfach-R	Rg
,	,	,-F	Fi
ach	ach	ach-S	Sp
muintir	muintir	muintir-N	Ncfsc
an	an	an-T	Td-s
bhaile	bhaile	baile-N	Ncmsg
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
i	i	i-S	Sp
dtreo	dtreo	treo-N	Ncmsc
an	an	an-T	Td-s
ghoirt	ghoirt	gort-N	Ncmsg
,	,	,-F	Fi
ina	ina	i-S	Spp-p
nduine	nduine	duine-N	Ncmsc
agus	agus	agus-C	Cc
ina	ina	i-S	Spp-p
nduine	nduine	duine-N	Ncmsc
,	,	,-F	Fi
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
Máire	Máire	Máire-N	Npfsc
Dhubh	Dhubh	dubh-A	Aq-fsc
agus	agus	agus-C	Cc
Oisín	Oisín	Oisín-N	Npm-g|Npmsg|Npm-g|Npmsc|Npfsg
ar	ar	ar-S	Sp
cheann	cheann	ceann-N	Ncmsc
an	an	an-T	Td-s
tslua	tslua	slua-N	Ncmsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
píce	píce	píce-N	Ncmsc
ag	ag	ag-S	Sp
gach	gach	gach-D	Dq
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
acu	acu	ag-P	Pr3-p
agus	agus	agus-C	Cc
fód	fód	fód-N	Ncmpg|Ncmsc
móna	móna	móin-N	Ncfsg
lasta	lasta	las-A	Av
ar	ar	ar-S	Sp
iompar	iompar	iompair-N	Nv
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Léim	Léim	léim-V	Vmip1s|Vmm-2s|Vmis|Ncfsc
croí	croí	croí-N	Ncmsg|Ncmsc
Dhiarmada	Dhiarmada	Diarmada-N	Npm-g|Npfsg
.	.	.-F	Fe
Lean	Lean	Lean-N	Npmsc
siad	siad	siad-P	Pp3-pn
orthu	orthu	ar-P	Pr3-p
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
go dtí	go dtí	go_dtí-S	Spc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
gort	gort	gort-N	Ncmsc
timpeallaithe	timpeallaithe	timpeallaigh-A	Av
acu	acu	ag-P	Pr3-p
,	,	,-F	Fi
iad	iad	iad-P	Pp3-p
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
balla	balla	balla-N	Ncmsc
cosanta	cosanta	cosain-A	Av
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Leis	Leis	le-S	Sp
na	na	na-T	Td-p
tóirsí	tóirsí	tóirse-N	Ncmpc
go	go	go-U	Ua
léir	léir	léir-A	Aqp
ag	ag	ag-S	Sp
lonradh	lonradh	lonradh-N	Ncmsc
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
chomh	chomh	chomh-R	Ri
geal	geal	geal-A	Aqp
le	le	le-S	Sp
lár	lár	lár-N	Ncmsc
an	an	an-T	Td-s
lae	lae	lá-N	Ncmsg
ghil	ghil	geal-A	Aq-msg
istigh	istigh	istigh-R	Rl
sa	sa	i-S	Spa-s
ghort	ghort	gort-N	Ncmsc
.	.	.-F	Fe
Diaidh	Diaidh	diaidh-N	Ns-s
ar	ar	ar-S	Sp
ndiaidh	ndiaidh	diaidh-N	Ns-s
scaip	scaip	scaip-V	Vmis
an	an	an-T	Td-s
ceo	ceo	ceo-N	Ncmsc
draíochta	draíochta	draíocht-N	Ncfsg|Ncfpc|Ncfpg
.	.	.-F	Fe
Thuig	Thuig	tuig-V	Vmis
Diarmaid	Diarmaid	Diarmaid-N	Npmsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
slán	slán	slán-A	Aqp
,	,	,-F	Fi
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
gheis	gheis	geis-N	Ncfsc
briste	briste	bris-A	Aqp|Av
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
leag	leag	leag-V	Vmis
sé	sé	sé-P	Pp3msn
cos	cos	cos-N	Ncfsc
taobh amuigh	taobh amuigh	taobh_amuigh-R	Rl
de	de	de-S	Sp
Ghort	Ghort	gort-N	Ncmsc
an	an	an-T	Td-s
Leasa	Leasa	leas-N	Ncmsg
bhí	bhí	bí-V	Vmis
na	na	na-T	Td-p
daoine	daoine	duine-N	Ncmpc
ábalta	ábalta	ábalta-A	Aqp
é	é	é-P	Pp3ms
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
.	.	.-F	Fe
Lig	Lig	lig-V	Vmis
siad	siad	siad-P	Pp3-pn
liú	liú	liúigh-N	Ncmsc|Nv
áthais	áthais	áthas-N	Ncmsg|Ncmpc
astu	astu	as-P	Pr3-p
.	.	.-F	Fe
Duine	Duine	duine-N	Ncmsc
macánta	macánta	macánta-A	Aqp
croíúil	croíúil	croíúil-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
i	i	i-S	Sp
nDiarmaid	nDiarmaid	Diarmaid-N	Npmsc
ón	ón	ó-S	Spa-s
lá	lá	lá-N	Ncmsc
sin	sin	sin-D	Dd
amach	amach	amach-R	Rd
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
,	,	,-F	Fi
maidir le	maidir le	maidir_le-S	Sp
Gort	Gort	gort-N	Ncmsc
an	an	an-T	Td-s
Leasa	Leasa	leas-N	Ncmsg
,	,	,-F	Fi
níor	níor	níor-Q	Qn-s
chualathas	chualathas	clois-V	Vmis0
gur	gur	gur-Q	Q--s
leag	leag	leag-V	Vmis
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
cos	cos	cos-N	Ncfpg|Ncfsc
sa	sa	i-S	Spa-s
ghort	ghort	gort-N	Ncmsc
céanna	céanna	céanna-A	Aqp
ón	ón	ó-S	Spa-s
lá	lá	lá-N	Ncmsc
sin	sin	sin-D	Dd
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
atá	atá	bí-V	Vmip---r
inniu	inniu	inniu-R	Rt
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
