Breith	Breith	breith-N	Ncfsc
agus	agus	agus-C	Cc
Ceantar	Ceantar	ceantar-N	Ncmsc|Ncmpg
Dúchais	Dúchais	dúchas-N	Ncmpc|Ncmsg
Is	Is	is-W	Wpri
duine	duine	duine-N	Ncmsc
de	de	de-S	Sp
cheoltóirí	cheoltóirí	ceoltóir-N	Ncmpc
móra	móra	mór-A	Aq--pc
na	na	na-T	Tdfsg
hÉireann	hÉireann	Éire-N	Npfsg
í	í	í-P	Pp3fs
Mairéad	Mairéad	Mairéad-N	Npmsc
Ní	Ní	Ní-U	Up
Mhaonaigh	Mhaonaigh	Maonaigh-N	Npfsg
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
clú	clú	clú-N	Ncmsc
agus	agus	agus-C	Cc
cáil	cáil	cál-N	Ncfsc|Ncmsg|Ncmpc
bainte	bainte	bain-A	Av
amach	amach	amach-R	Rd
aici	aici	ag-P	Pr3fs
,	,	,-F	Fi
ní	ní	nigh-W	Wp-in|Nv|Ncmsc|Nv
hamháin	hamháin	amháin-A	Aqp
sa	sa	i-S	Spa-s
tír	tír	tír-N	Ncfsc
seo	seo	seo-D	Dd
,	,	,-F	Fi
ach	ach	ach-C	Cs
ar fud	ar fud	ar_fud-S	Spc
an	an	an-T	Td-s
domhain	domhain	domhan-N	Ncmsg
mhóir	mhóir	mór-A	Aq-msv|Aq-msg
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
Mairéad	Mairéad	Mairéad-N	Npmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
saol	saol	saol-N	Ncmsc
ar	ar	is-W	Wpsi|Ncmsc|Wssi|Wpdi
Luinnigh	Luinnigh	luinnigh-V	Vmis
i	i	i-S	Sp
nGaoth	nGaoth	gaoth-N	Ncmsc|Ncfsc
Dobhair	Dobhair	dobhar-N	Ncmsg
i	i	i-S	Sp
nGaeltacht	nGaeltacht	gaeltacht-N	Ncfsc
an	an	an-T	Td-s
dara	dara	dara-M	Mo
duine	duine	duine-N	Ncmsc|Ncmsg
clainne	clainne	clann-N	Ncfsg
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
Proinsias	Proinsias	Proinsias-N	Npmsc
Ó	Ó	Ó-U	Up
Maonaigh	Maonaigh	Maonaigh-N	Npmsc
(	(	(-F	Fp
Francie	Francie	Francie-N	Npmsc
)	)	)-F	Fp
agus	agus	agus-C	Cc
Caitlín	Caitlín	Caitlín-N	Npf-g|Npfsc
Ní	Ní	Ní-U	Up
Ghallchóir	Ghallchóir	Gallchóir-N	Npfsg
(	(	(-F	Fp
Kitty	Kitty	kitty-X	Xfen
Rua	Rua	Rua-N	Npmsg|Npmsc|Npfsg
)	)	)-F	Fp
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
deartháir	deartháir	deartháir-N	Ncmsc
níos	níos	níos-U	Uc
sine	sine	sean-A	Aqc
aici	aici	ag-P	Pr3fs
,	,	,-F	Fi
Gearóid	Gearóid	Gearóid-N	Npmsc
,	,	,-F	Fi
agus	agus	agus-C	Cc
deirfiúr	deirfiúr	deirfiúr-N	Ncfsc
níos	níos	níos-U	Uc
óige	óige	óg-A	Aqc
,	,	,-F	Fi
Anna	Anna	Anna-N	Npfsc
.	.	.-F	Fe
Mairéad	Mairéad	Mairéad-N	Npmsc
ina	ina	i-S	Spp-s
tachrán	tachrán	tachrán-N	Ncmsc
.	.	.-F	Fe
An	An	an-T	Td-s
teach	teach	teach-N	Ncmsc
inar	inar	i-S	Spr
chaith	chaith	caith-V	Vmis
Mairéad	Mairéad	Mairéad-N	Npmsc
t	t	t-X	Xl
ús	ús	ús-N	Ncmsc
a	a	a-D	Dp3
saoil	saoil	saol-N	Ncmsg
.	.	.-F	Fe
Mairéad	Mairéad	Mairéad-N	Npmsc
,	,	,-F	Fi
a	a	a-D	Dp3
deirfiúr	deirfiúr	deirfiúr-N	Ncfsc
Anna	Anna	Anna-N	Npf-g|Npfsg|Npfsc
,	,	,-F	Fi
a	a	a-D	Dp3
deartháir	deartháir	deartháir-N	Ncmsc
Gearóid	Gearóid	Gearóid-N	Npm-g|Npmsg|Npmsc
,	,	,-F	Fi
agus	agus	agus-C	Cc
a	a	a-D	Dp3
tuismitheoirí	tuismitheoirí	tuismitheoir-N	Ncmpc
Francie	Francie	Francie-N	Npmsc
agus	agus	agus-C	Cc
Kitty	Kitty	kitty-X	Xfen
Rua	Rua	Rua-N	Npmsg|Npmsc|Npfsg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhás	fhás	fás-V	Vmis
Mairéad	Mairéad	Mairéad-N	Npmsc
aníos	aníos	aníos-R	Rd
i	i	i-S	Sp
nGaoth	nGaoth	gaoth-N	Ncmsc|Ncfsc
Dobhair	Dobhair	dobhar-N	Ncmsg
,	,	,-F	Fi
dúiche	dúiche	dúiche-N	Ncfsc
álainn	álainn	álainn-A	Aq-fsc
idir	idir	idir-S	Sp
sliabh	sliabh	sliabh-N	Ncmsc
agus	agus	agus-C	Cc
muir	muir	muir-N	Ncfsc
in	in	i-S	Sp
iarthuaisceart	iarthuaisceart	iarthuaisceart-N	Ncmsc
Thír	Thír	tír-N	Ncfsc
Chonaill	Chonaill	Conaill-N	Npm-g|Npfsg
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
í	í	í-P	Pp3fs
an	an	an-T	Td-s
Ghaeilge	Ghaeilge	Gaeilge-N	Npfsc
gnáth	gnáth	gnáth-N	Ncmpg|Ncmsc
‑	‑	‑-F	Fb
theanga	theanga	teanga-N	Ncfsc
labhartha	labhartha	labhair-A	Av
an	an	an-T	Td-s
teaghlaigh	teaghlaigh	teaghlach-N	Ncmsg
agus	agus	agus-C	Cc
an	an	an-T	Td-s
phobail	phobail	pobal-N	Ncmsg
.	.	.-F	Fe
Bunscoil	Bunscoil	bunscoil-N	Ncfsc
agus	agus	agus-C	Cc
Óige	Óige	óige-N	Ncfsc|Ncfsg
Chuaigh	Chuaigh	téigh-V	Vmis
Mairéad	Mairéad	Mairéad-N	Npmsc
ar	ar	ar-S	Sp
Scoil	Scoil	scoil-N	Ncfsc
na	na	na-T	Td-p
Luinní	Luinní	Luinní-N	Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
hathair	hathair	athair-N	Ncmsc
,	,	,-F	Fi
Francie	Francie	Francie-N	Npmsc
,	,	,-F	Fi
agus	agus	agus-C	Cc
triúr	triúr	triúr-N	Ncmpg|Ncmsc
eile	eile	eile-D	Dd
,	,	,-F	Fi
ag	ag	ag-S	Sp
teagasc	teagasc	teagasc-N	Nv
sa	sa	i-S	Spa-s
scoil	scoil	scoil-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Francie	Francie	Francie-N	Npmsc
ar	ar	ar-S	Sp
dhuine	dhuine	duine-N	Ncmsc
d	d	d-X	Xl
’	’	’-F	Fa
aisteoirí	aisteoirí	aisteoir-N	Ncmpc
móra	móra	mór-A	Aq--pc
na	na	na-T	Tdfsg
háite	háite	áit-N	Ncfsg
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
a	a	a-D	Dp3
shliocht	shliocht	sliocht-N	Ncmsc
sin	sin	sin-P	Pd|W|Dd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
scoil	scoil	scoil-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
béim	béim	béim-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
drámaíocht	drámaíocht	drámaíocht-N	Ncfsc
.	.	.-F	Fe
Bhíodh	Bhíodh	bí-V	Vmih
páirt	páirt	páirt-N	Ncfsc
ag	ag	ag-S	Sp
Mairéad	Mairéad	Mairéad-N	Npmsc
i	i	i-S	Sp
gcuid	gcuid	cuid-N	Ncfsc
mhór	mhór	mór-N	Ncmpg
drámaí	drámaí	dráma-N	Ncmpg|Ncmpc
scoile	scoile	scoil-N	Ncfsg
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
is	is	is-W	Wp-i
iad	iad	iad-P	Pp3-p
na	na	na-T	Td-p
cuimhní	cuimhní	cuimhne-N	Ncfpc
is	is	is-U	U
deise	deise	deas-A	Aqc
atá	atá	bí-V	Vmip---r
aici	aici	ag-P	Pr3fs
ná	ná	ná-C	Cc
a	a	a-U	U
bheith	bheith	bí-N	Nv
páirteach	páirteach	páirteach-A	Aqp
Amharclann	Amharclann	amharclann-N	Ncfsc
Ghaoth	Ghaoth	gaoth-A	Aq-fsc
Dobhair	Dobhair	dobhar-N	Ncmpc|Ncmsg
.	.	.-F	Fe
sna	sna	i-S	Spa-p
geamaireachtaí	geamaireachtaí	geamaireachta-N	Ncmpc
a	a	a-Q	Q-r
bhíodh	bhíodh	bí-V	Vmih
ar	ar	ar-S	Sp
siúl	siúl	siúil-N	Nv
in	in	i-S	Sp
Amharclann	Amharclann	amharclann-N	Ncfsc
Ghaoth	Ghaoth	gaoth-A	Aq-fsc
Dobhair	Dobhair	dobhar-N	Ncmpc|Ncmsg
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
mhinic	mhinic	minic-A	Aqp
í	í	í-P	Pp3fs
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
na	na	na-T	Td-p
girseacha	girseacha	girseach-N	Ncfpc
óga	óga	óg-A	Aq--pc
eile	eile	eile-D	Dd
ina	ina	i-S	Spp-p|Spp-s
sióga	sióga	sióg-N	Ncfpc
sna	sna	i-S	Spa-p
geamaireachtaí	geamaireachtaí	geamaireachta-N	Ncmpc
céanna	céanna	céanna-A	Aqp
.	.	.-F	Fe
Is	Is	is-W	Wp-i
dóigh	dóigh	dóigh-N	Ncfsc
le	le	le-S	Sp
Mairéad	Mairéad	Mairéad-N	Npmsc
gur	gur	gur-Q	Q--s
thug	thug	tabhair-V	Vmis
an	an	an-T	Td-s
taithí	taithí	taithí-N	Ncfsc
seo	seo	seo-D	Dd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
stáitse	stáitse	stáitse-N	Ncmsc
muinín	muinín	muinín-N	Ncfsc
di	di	do-P	Pr3fs
a	a	a-Q	Q-r
chuidigh	chuidigh	cuidigh-V	Vmis
léi	léi	le-P	Pr3fs
níos	níos	níos-U	Uc
faide	faide	fada-A	Aqc
anonn	anonn	anonn-R	Rd
ina	ina	i-S	Spp-p|Spp-s
saol	saol	saol-N	Ncmsc
.	.	.-F	Fe
Mairéad	Mairéad	Mairéad-N	Npmsc
i	i	i-S	Sp
ngeamaireacht	ngeamaireacht	geamaireacht-N	Ncfsc
.	.	.-F	Fe
Chaitheadh	Chaitheadh	caith-V	Vmih
Mairéad	Mairéad	Mairéad-N	Npmsc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
eile	eile	eile-D	Dd
an	an	an-T	Td-s
chuid	chuid	cuid-N	Ncfsc
is	is	is-U	U
mó	mó	mór-A	Aqc
dá	dá	do-S	Spp-p
gcuid	gcuid	cuid-N	Ncfsc
ama	ama	ama-N	Ncmsg
amuigh	amuigh	amuigh-R	Rl
faoin	faoin	faoi-S	Spa-s
aer	aer	aer-N	Ncmsc
.	.	.-F	Fe
Bhíodh	Bhíodh	bí-V	Vmih
siad	siad	siad-P	Pp3-pn
thíos	thíos	thíos-R	Rd
fán	fán	faoi-S	Spa-s
abhainn	abhainn	abhainn-N	Ncfsc
ag	ag	ag-S	Sp
piocadh	piocadh	pioc-N	Nv
péarlaí	péarlaí	péarla-N	Ncmpg
amach	amach	amach-R	Rd
as	as	as-S	Sp
sliogáin	sliogáin	sliogán-N	Ncmpc
,	,	,-F	Fi
ag	ag	ag-S	Sp
obair	obair	obair-N	Nv-----n
ar	ar	ar-S	Sp
an	an	an-T	Td-s
chaorán	chaorán	caorán-N	Ncmsc
agus	agus	agus-C	Cc
ina	ina	i-S	Spp-s|Spp-p
rith	rith	rith-N	Ncmsc
thart	thart	thart-R	Rd
cosnochta	cosnochta	cosnochta-A	Aqp
sa	sa	i-S	Spa-s
samhradh	samhradh	samhradh-N	Ncmsc
.	.	.-F	Fe
Bhíodh	Bhíodh	bí-V	Vmih
deartháir	deartháir	deartháir-N	Ncmsc
Mhairéad	Mhairéad	Mhairéad-N	Npmsc
,	,	,-F	Fi
Gearóid	Gearóid	Gearóid-N	Npmsc
,	,	,-F	Fi
in	in	i-S	Sp
ainm	ainm	ainm-N	Ncmsc
is	is	agus-W	Wp-i|Wpri|Cc
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
coinneáil	coinneáil	coinnigh-N	Nv
súile	súile	súil-N	Ncfsg|Nv--g--n|Ncfsg|Nv--g--n
uirthi	uirthi	ar-P	Pr3fs
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
,	,	,-F	Fi
ach	ach	ach-C	Cs
is	is	is-W	Wpri
iomaí	iomaí	iomaí-A	Aqp|Aqc
uair	uair	uair-N	Ncfsc
a	a	a-Q	Q-r
thugadh	thugadh	tabhair-V	Vmih
sé	sé	sé-P	Pp3msn
cead	cead	cead-N	Ncmsc
a	a	a-D	Dp3
coise	coise	cos-N	Ncfsg
di	di	do-P	Pr3fs
.	.	.-F	Fe
Is	Is	is-W	Wp-i
minic	minic	minic-A	Aqp
a	a	a-Q	Q-r
théadh	théadh	téigh-V	Vmih
Mairéad	Mairéad	Mairéad-N	Npmsc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
deartháir	deartháir	deartháir-N	Ncmsc
suas	suas	suas-R	Rd
an	an	an-T	Td-s
baile	baile	baile-N	Ncmsg|Ncmsc
chuig	chuig	chuig-S	Sp
a	a	a-D	Dp3
n	n	n-X	Xl
‑	‑	‑-F	Fb
aintín	aintín	aintín-N	Ncfsc
,	,	,-F	Fi
Máire	Máire	Máire-N	Npfsc
,	,	,-F	Fi
go	go	go-Q	Q
bhfeicfeadh	bhfeicfeadh	feic-V	Vmc
siad	siad	siad-P	Pp3-pn
cláracha	cláracha	clár-N	Ncmpc
teilifíse	teilifíse	teilifís-N	Ncfsg
mar	mar	mar-S	Sp
Rin	Rin	Rin-N	Npmsc
Tin	Tin	tin-X	Xfev
Tin	Tin	tin-X	Xfen
agus	agus	agus-C	Cc
Mr.	Mr.	Mister-Y	Y
Ed	Ed	Ed-N	Npmsc|Y
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
ndóigh	ndóigh	dóigh-N	Ncfsc
,	,	,-F	Fi
ní	ní	nigh-W	Wp-in|Nv|Ncmsc|Nv
mórán	mórán	mórán-N	Ncmsc
tithe	tithe	teach-N	Ncmpg
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
teilifís	teilifís	teilifís-N	Ncfsc
iontu	iontu	i-P	Pr3-p
t	t	t-X	Xl
‑	‑	‑-F	Fb
am	am	am-N	Ncmsc
sin	sin	sin-P	Pd|Dd
.	.	.-F	Fe
Gearóid	Gearóid	Gearóid-N	Npmsc
ag	ag	ag-S	Sp
us	us	us-X	Xfep
Mairéad	Mairéad	Mairéad-N	Npmsc
.	.	.-F	Fe
An	An	an-T	Td-s
Ardscoil	Ardscoil	ardscoil-N	Ncfsc
agus	agus	agus-C	Cc
Baba	Baba	Baba-N	Npmsc
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Mairéad	Mairéad	Mairéad-N	Npmsc
réidh	réidh	réidh-A	Aq-msc
leis	leis	le-S	Sp
an	an	an-T	Td-s
bhunscoil	bhunscoil	bunscoil-N	Ncfsc
chuaigh	chuaigh	téigh-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
aghaidh	aghaidh	aghaidh-N	Ncfsc
go dtí	go dtí	go_dtí-S	Spc
Ardscoil	Ardscoil	ardscoil-N	Ncfsc
Mhuire	Mhuire	Muire-N	Ncfsg|Npfsg
i	i	i-S	Sp
nGaoth	nGaoth	gaoth-N	Ncmsc|Ncfsc
Dobhair	Dobhair	dobhar-N	Ncmsg
.	.	.-F	Fe
Bhain	Bhain	bain-V	Vmis
sí	sí	sí-P	Pp3fsn
sult	sult	sult-N	Ncmsc
mór	mór	mór-A	Aq-msc
as	as	as-P	Pr3ms
a	a	a-D	Dp3
cuid	cuid	cuid-N	Ncfsc
ama	ama	ama-N	Ncmsg
ansin	ansin	ansin-R	Rt|Rl
.	.	.-F	Fe
Dalta	Dalta	dalta-N	Ncmsc
díograiseach	díograiseach	díograiseach-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
inti	inti	i-P	Pr3fs
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmm-2s
go	go	go-U	Ua
fíormhaith	fíormhaith	fíormhaith-A	Aqp
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
béim	béim	béim-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
drámaíocht	drámaíocht	drámaíocht-N	Ncfsc
agus	agus	agus-C	Cc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
cheol	cheol	ceol-N	Nv-----n
sa	sa	i-S	Spa-s
scoil	scoil	scoil-N	Ncfsc
,	,	,-F	Fi
rud	rud	rud-N	Ncmsc
a	a	a-Q	Q-r
thaitin	thaitin	taitin-V	Vmis
le	le	le-S	Sp
Mairéad	Mairéad	Mairéad-N	Npmsc
.	.	.-F	Fe
Ghlac	Ghlac	glac-V	Vmis
sí	sí	sí-P	Pp3fsn
páirt	páirt	páirt-N	Ncfsc
i	i	i-S	Sp
ndíospóireachtaí	ndíospóireachtaí	díospóireacht-N	Ncfpc
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
agus	agus	agus-C	Cc
Ardscoil	Ardscoil	ardscoil-N	Ncfsc
Mhuire	Mhuire	Muire-N	Ncfsg|Npfsg
.	.	.-F	Fe
bhuaigh	bhuaigh	buaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
duais	duais	duais-N	Ncfsc
náisiúnta	náisiúnta	náisiúnta-A	Aqp
i	i	i-S	Sp
gcomórtas	gcomórtas	comórtas-N	Ncmsc
díospóireachta	díospóireachta	díospóireacht-N	Ncfsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Máire	Máire	Máire-N	Npfsc
Bean	Bean	bean-N	Ncfsc
Uí	Uí	Uí-U	Up
Bhraonáin	Bhraonáin	Braonáin-N	Npfsg
,	,	,-F	Fi
nó	nó	nó-C	Cc
Baba	Baba	Baba-N	Npmsc
mar	mar	mar-C	Cs
is	is	is-W	Wpri
fearr	fearr	maith-A	Aqc
aithne	aithne	aithne-N	Ncfsc
uirthi	uirthi	ar-P	Pr3fs
,	,	,-F	Fi
ar	ar	ar-S	Sp
dhuine	dhuine	duine-N	Ncmsc
de	de	de-S	Sp
na	na	na-T	Td-p
múinteoirí	múinteoirí	múinteoir-N	Ncmpc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
teagasc	teagasc	teagasc-N	Nv
in	in	i-S	Sp
Ardscoil	Ardscoil	ardscoil-N	Ncfsc
Mhuire	Mhuire	Muire-N	Ncfsg|Npfsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
aithne	aithne	aithne-N	Ncfsc
ag	ag	ag-S	Sp
Mairéad	Mairéad	Mairéad-N	Npmsc
ar	ar	ar-S	Sp
Bhaba	Bhaba	baba-N	Npmsc
ó	ó	ó-C	Cs
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
ina	ina	i-S	Spp-s
girseach	girseach	girseach-N	Ncfsc
óg	óg	óg-A	Aq-fsv|Aq-fsc
mar	mar	mar-C	Cs
bhíodh	bhíodh	bí-V	Vmih
Baba	Baba	Baba-N	Npmsc
ag	ag	ag-S	Sp
seinm	seinm	seinn-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
phianó	phianó	pianó-N	Ncmsg
ag	ag	ag-S	Sp
na	na	na-T	Td-p
geamaireachtaí	geamaireachtaí	geamaireachta-N	Ncmpc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
cáil	cáil	cál-N	Ncfsc|Ncmpc
ar	ar	ar-S	Sp
chlann	chlann	clann-N	Ncfsc
Bhaba	Bhaba	Bhaba-N	Npmsc
Uí	Uí	Uí-U	Up
Bhraonáin	Bhraonáin	Braonáin-N	Npfsg
anois	anois	anois-R	Rt
ar fud	ar fud	ar_fud-S	Spc
na	na	na-T	Tdfsg
hÉireann	hÉireann	Éire-N	Npfsg
agus	agus	agus-C	Cc
ar fud	ar fud	ar_fud-S	Spc
an	an	an-T	Td-s
domhain	domhain	domhan-N	Ncmsg
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
siad	siad	siad-P	Pp3-pn
sa	sa	i-S	Spa-s
bhuíon	bhuíon	buíon-N	Ncfsc
cheoil	cheoil	ceol-N	Ncmsg
chlúiteach	chlúiteach	clúiteach-A	Aq-msc
,	,	,-F	Fi
Clannad	Clannad	Clannad-N	Npmsc
,	,	,-F	Fi
agus	agus	agus-C	Cc
tá	tá	bí-V	Vmip
iomrá	iomrá	iomrá-N	Ncmsc
mór	mór	mór-A	Aq-msc
leitheadach	leitheadach	leitheadach-A	Aq-msc
ar	ar	ar-S	Sp
Eithne	Eithne	Eithne-N	Npfsc
agus	agus	agus-C	Cc
ar	ar	ar-S	Sp
Mháire	Mháire	Máire-N	Npfsc
,	,	,-F	Fi
nó	nó	nó-C	Cc
Enya	Enya	Enya-N	Npmsc
agus	agus	agus-C	Cc
Moya	Moya	Moya-N	Npmsc
mar	mar	mar-C	Cs
is	is	is-W	Wpri
fearr	fearr	maith-A	Aqc
aithne	aithne	aithne-N	Ncfsc
orthu	orthu	ar-P	Pr3-p
.	.	.-F	Fe
Is	Is	agus-C	Cc
maith	maith	maith-V	Vmm-2s
is	is	agus-C	Cc
cuimhin	cuimhin	cuimhin-N	Ns-s
le	le	le-S	Sp
Baba	Baba	Baba-N	Npmsc
Mairéad	Mairéad	Mairéad-N	Npmsc
sna	sna	i-S	Spa-p
geamaireachtaí	geamaireachtaí	geamaireachta-N	Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
ina	ina	i-S	Spp-s
banríon	banríon	banríon-N	Ncfsc
bliain	bliain	bliain-N	Ncfsc
amháin	amháin	amháin-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
deir	deir	abair-V	Vmip
sí	sí	sí-P	Pp3fsn
,	,	,-F	Fi
‘	‘	‘-X	Xx
agus	agus	agus-C	Cc
tugadh	tugadh	tabhair-V	Vmis0
amhrán	amhrán	amhrán-N	Ncmsc
di	di	do-P	Pr3fs
le	le	le-S	Sp
ceol	ceol	ceol-N	Nv-----n
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
aithneofá	aithneofá	aithin-V	Vmc-2s
ansin	ansin	ansin-R	Rt|Rl
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
bua	bua	bua-N	Ncmsc
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
inti	inti	i-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
’	’	’-F	Fa
Pictiúr	Pictiúr	pictiúr-N	Ncmsc
d	d	d-X	Xl
’	’	’-F	Fa
fhidleacha	fhidleacha	fidil-N	Ncfpc
a	a	a-Q	Q-r
phéinteáil	phéinteáil	péinteáil-V	Vmis
Mairéad	Mairéad	Mairéad-N	Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Baba	Baba	Baba-N	Npmsc
ina	ina	i-S	Spp-s
múinteoir	múinteoir	múinteoir-N	Ncmsc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
in	in	i-S	Sp
Ardscoil	Ardscoil	ardscoil-N	Ncfsc
Mhuire	Mhuire	Muire-N	Ncfsg|Npfsg
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
.	.	.-F	Fe
Bhain	Bhain	bain-V	Vmis
cór	cór	cór-N	Ncmsc
na	na	na-T	Tdfsg
scoile	scoile	scoil-N	Ncfsg
,	,	,-F	Fi
faoi	faoi	faoi-S	Sp
stiúir	stiúir	stiúir-N	Ncfsc
Bhaba	Bhaba	Bhaba-N	Npmsc
,	,	,-F	Fi
duaiseanna	duaiseanna	duais-N	Ncfpc
móra	móra	mór-A	Aq--pc
ag	ag	ag-S	Sp
comórtais	comórtais	comórtas-N	Ncmpc
cheoil	cheoil	ceol-N	Nv--g--n|Ncmsg
,	,	,-F	Fi
ina	ina	i-S	Spp-p|Spp-s
measc	measc	measc-N	Ncmsc
Slógadh	Slógadh	slóg-N	Ncmsc|Nv
,	,	,-F	Fi
Fleánna	Fleánna	fleá-N	Ncmpc|Ncfpc
Ceoil	Ceoil	ceol-N	Ncmsg|Nv--g--n
agus	agus	agus-C	Cc
Oireachtas	Oireachtas	oireachtas-N	Ncmsc
na	na	na-T	Tdfsg
Gaeilge	Gaeilge	Gaeilge-N	Npfsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Baba	Baba	Baba-N	Npmsc
fosta	fosta	fosta-A	Aqp
i mbun	i mbun	i_mbun-S	Spc
cabaret	cabaret	cabaret-X	Xfen
Ghael	Ghael	gael-N	Ncmpg
Linn	Linn	Linn-N	Npmsg|Npmsc
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
Mairéad	Mairéad	Mairéad-N	Npmsc
mar	mar	mar-S	Sp
bhall	bhall	ball-N	Ncmsc
den	den	de-S	Spa-s
chabaret	chabaret	chabaret-N	Ncfsc
.	.	.-F	Fe
Arsa	Arsa	arsa-V	Vmis
Baba	Baba	Baba-N	Npmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
bhíodh	bhíodh	bí-V	Vmih
sí	sí	sí-P	Pp3fsn
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
sna	sna	i-S	Spa-p
cabarets	cabarets	cabarets-X	Xfen
ag	ag	ag-S	Sp
bualadh	bualadh	buail-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
fhidil	fhidil	fidil-N	Ncfsc
,	,	,-F	Fi
ag	ag	ag-S	Sp
ceol	ceol	ceol-N	Nv-----n
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
comhcheoil	comhcheoil	comhcheol-N	Ncmsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
iontach	iontach	iontach-R	Ri
cliste	cliste	cliste-A	Aqp
mar	mar	mar-C	Cs
sin	sin	sin-W	W
.	.	.-F	Fe
’	’	’-F	Fa
Ó	Ó	ó-S	Sp
Thaobh	Thaobh	taobh-N	Ncmsc
na	na	na-T	Td-p
dTaobhanna	dTaobhanna	taobh-N	Ncmpg
Is	Is	is-W	Wpri
tríd	tríd	trí-P	Pr3ms
an	an	an-T	Td-s
cheol	cheol	ceol-N	Nv-----n
a	a	a-Q	Q-r
casadh	casadh	cas-V	Vmis0
tuismitheoirí	tuismitheoirí	tuismitheoir-N	Ncmpc
Mhairéad	Mhairéad	Mhairéad-N	Npmsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
an	an	an-T	Td-s
chéad	chéad	céad-M	Mo
lá	lá	lá-N	Ncmsc
riamh	riamh	riamh-R	Rg
.	.	.-F	Fe
Teach	Teach	teach-N	Ncmsc
mór	mór	mór-A	Aq-msc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
i	i	i-S	Sp
dteach	dteach	teach-N	Ncmsc
Dan	Dan	Dan-N	Npmsc
Eoghain	Eoghain	Eoghan-N	Npmsg|Npm-g
Charlie	Charlie	Charlie-N	Npmsc
Uí	Uí	Uí-U	Up
Ghallchóir	Ghallchóir	Gallchóir-N	Npfsg
,	,	,-F	Fi
an	an	an-T	Td-s
teach	teach	teach-N	Ncmsc
inar	inar	i-S	Spr
tógadh	tógadh	tóg-V	Vmis0
Kitty	Kitty	kitty-X	Xfen
Rua	Rua	Rua-N	Npmsg|Npmsc|Npfsg
,	,	,-F	Fi
máthair	máthair	máthair-N	Ncfsc
Mhairéad	Mhairéad	Mhairéad-N	Npmsc
.	.	.-F	Fe
Bhualadh	Bhualadh	bualadh-N	Ncmsc
Kitty	Kitty	kitty-X	Xfen
féin	féin	féin-P	Px
an	an	an-T	Td-s
bosca	bosca	bosca-N	Ncmsg|Ncmsc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
agus	agus	agus-C	Cc
an	an	an-T	Td-s
orgán	orgán	orgán-N	Ncmsc
béil	béil	béal-N	Ncmsg|Ncmpc
.	.	.-F	Fe
Bhíodh	Bhíodh	bí-V	Vmih
ceoltóirí	ceoltóirí	ceoltóir-N	Ncmpc
go leor	go leor	go_leor-A	Aq
ag	ag	ag-S	Sp
triall	triall	triall-N	Nv
ar	ar	ar-S	Sp
theach	theach	teach-N	Ncmsc
Dan	Dan	Dan-N	Npmsc
Eoghain	Eoghain	Eoghan-N	Npmsg|Npm-g
Charlie	Charlie	Charlie-N	Npmsc
fá choinne	fá choinne	fá_choinne-S	Spc
oícheanta	oícheanta	oíche-N	Ncfpg
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
.	.	.-F	Fe
Fidléir	Fidléir	fidléir-N	Ncmsc
iomráiteach	iomráiteach	iomráiteach-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
in	in	i-S	Sp
Francie	Francie	Francie-N	Npmsc
Ó	Ó	Ó-U	Up
Maonaigh	Maonaigh	Maonaigh-N	Npmsc
agus	agus	agus-C	Cc
ba	ba	is-W	Wsri
mhinic	mhinic	minic-A	Aqp
é	é	é-P	Pp3ms
féin	féin	féin-P	Px
ag	ag	ag-S	Sp
na	na	na-T	Td-p
hoícheanta	hoícheanta	oíche-N	Ncfpc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
seo	seo	seo-D	Dd
lena	lena	le-S	Spp-s
chairde	chairde	cairde-N	Ncmpc|Ncmsc
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
óna	óna	ó-S	Spp-s
mháthair	mháthair	máthair-N	Ncfsc
féin	féin	féin-P	Px
,	,	,-F	Fi
Róise	Róise	Róise-N	Npfsc
Ní	Ní	Ní-U	Up
Dhomhnaill	Dhomhnaill	Domhnaill-N	Np
,	,	,-F	Fi
a	a	a-Q	Q-i|Q-r
fuair	fuair	faigh-V	Vmis
Francie	Francie	Francie-N	Npmsc
féith	féith	féith-A	Aq-msc
an	an	an-T	Td-s
cheoil	cheoil	ceol-N	Ncmsg
.	.	.-F	Fe
Chan	Chan	chan-W	Wp-in
iontas	iontas	iontas-N	Ncmsc
ar	ar	is-W	Wssi|Wpdi|Wpsi
bith	bith	bith-N	Ncmsc|Ns-s
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
an	an	an-T	Td-s
ceol	ceol	ceol-N	Ncmsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
go	go	go-S	Sp
smior	smior	smior-N	Ncmsc
i	i	i-S	Sp
Mairéad	Mairéad	Mairéad-N	Npmsc
Ní	Ní	Ní-U	Up
Mhaonaigh	Mhaonaigh	Maonaigh-N	Npfsg
.	.	.-F	Fe
Chan	Chan	can-V	Vmis
a	a	a-U	U
ghoid	ghoid	goid-N	Nv
nó	nó	nó-C	Cc
a	a	a-U	U
fhuadach	fhuadach	fuadaigh-N	Nv
a	a	a-Q	Q-r
rinne	rinne	déan-V	Vmis
sí	sí	sí-P	Pp3fsn
,	,	,-F	Fi
mar	mar	mar-C	Cs
tá	tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
aici	aici	ag-P	Pr3fs
ó	ó	ó-S	Sp
thaobh	thaobh	taobh-N	Ncmsc
na	na	na-T	Td-p
dtaobhanna	dtaobhanna	taobh-N	Ncmpg
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
phós	phós	pós-V	Vmis
Francie	Francie	Francie-N	Npmsc
agus	agus	agus-C	Cc
Kitty	Kitty	kitty-X	Xfen
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
teach	teach	teach-N	Ncmsc
seo	seo	seo-P	Pd|Dd
acusan	acusan	ag-P	Pr3-p-e
ina	ina	i-S	Spp-s
theach	theach	teach-N	Ncmsc
aitheantais	aitheantais	aitheantas-N	Ncmsg
ag	ag	ag-S	Sp
ceoltóirí	ceoltóirí	ceoltóir-N	Ncmpc
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
an	an	an-T	Td-s
ceol	ceol	ceol-N	Ncmsc
,	,	,-F	Fi
Francie	Francie	Francie-N	Npmsc
agus	agus	agus-C	Cc
Kitty	Kitty	kitty-X	Xfen
ag	ag	ag-S	Sp
seisiún	seisiún	seisiún-N	Ncmsc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
.	.	.-F	Fe
Mairéad	Mairéad	Mairéad-N	Npmsc
lena	lena	le-S	Spp-s
tuismitheoirí	tuismitheoirí	tuismitheoir-N	Ncmpc
.	.	.-F	Fe
agus	agus	agus-C	Cc
an	an	an-T	Td-s
chuideachta	chuideachta	cuideachta-N	Ncfsc
a	a	a-Q	Q-r
théann	théann	téigh-V	Vmip
leis	leis	le-P	Pr3ms
,	,	,-F	Fi
i	i	i-S	Sp
bhfeidhm	bhfeidhm	feidhm-N	Ncfsc
go	go	go-U	Ua
mór	mór	mór-A	Aqp
ar	ar	ar-S	Sp
Mhairéad	Mhairéad	mairéad-N	Npmsc
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
fás	fás	fás-N	Nv
aníos	aníos	aníos-R	Rd
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
dhual	dhual	dual-N	Ns-s
di	di	do-P	Pr3fs
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
an	an	an-T	Td-s
ceol	ceol	ceol-N	Ncmsc
a	a	a-U	U
thógáil	thógáil	tóg-N	Nv
.	.	.-F	Fe
Níorbh	Níorbh	is-W	Ws-in
iontas	iontas	iontas-N	Ncmsc
gurbh	gurbh	is-W	Wsdi
í	í	í-P	Pp3fs
an	an	an-T	Td-s
fhidil	fhidil	fidil-N	Ncfsc
an	an	an-T	Td-s
gléas	gléas	gléas-N	Ncmsc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
a	a	a-Q	Q-r
ghlac	ghlac	glac-V	Vmis
Mairéad	Mairéad	Mairéad-N	Npmsc
chuici	chuici	chuig-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
iomrá	iomrá	iomrá-N	Ncmsc
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
hathair	hathair	athair-N	Ncmsc
,	,	,-F	Fi
Francie	Francie	Francie-N	Npmsc
,	,	,-F	Fi
cheana	cheana	cheana-R	Rg
féin	féin	féin-P	Px
mar	mar	mar-S	Sp
mhúinteoir	mhúinteoir	múinteoir-N	Ncmsc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
,	,	,-F	Fi
agus	agus	agus-C	Cc
ranganna	ranganna	rang-N	Ncmpg|Ncmpc|Ncmpg
fidléireachta	fidléireachta	fidléireacht-N	Ncfsg
aige	aige	ag-P	Pr3ms
d	d	d-X	Xl
’	’	’-F	Fa
aos	aos	aos-N	Ncmsc
óg	óg	óg-A	Aq-msc
na	na	na-T	Tdfsg
háite	háite	áit-N	Ncfsg
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
Mairéad	Mairéad	Mairéad-N	Npmsc
suim	suim	suim-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
sna	sna	i-S	Spa-p
hamhráin	hamhráin	amhrán-N	Ncmpc
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
sí	sí	sí-P	Pp3fsn
thart	thart	thart-R	Rd
uirthi	uirthi	ar-P	Pr3fs
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
agus	agus	agus-C	Cc
,	,	,-F	Fi
ó	ó	ó-C	Cs
tharla	tharla	tarlaigh-V	Vmis
guth	guth	guth-N	Ncmsc
deas	deas	deas-R	Ri
binn	binn	binn-A	Aqp
aici	aici	ag-P	Pr3fs
,	,	,-F	Fi
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
á	á	do-S	Spo-s
gceol	gceol	ceol-N	Nv-----n
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
daoine	daoine	duine-N	Ncmpc
thart	thart	thart-R	Rd
uirthi	uirthi	ar-P	Pr3fs
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
na	na	na-T	Td-p
céadta	céadta	céad-N	Ncmpc
amhrán	amhrán	amhrán-N	Ncmpg|Ncmsc
acu	acu	ag-P	Pr3-p
agus	agus	agus-C	Cc
thóg	thóg	tóg-V	Vmis
sí	sí	sí-P	Pp3fsn
stór	stór	stór-N	Ncmsc
mór	mór	mór-A	Aq-msc
amhrán	amhrán	amhrán-N	Ncmpg|Ncmsc
uathu	uathu	ó-P	Pr3-p
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
Mairéad	Mairéad	Mairéad-N	Npmsc
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
chuig	chuig	chuig-S	Sp
seisiúin	seisiúin	seisiún-N	Ncmpc
cheoil	cheoil	ceol-N	Nv--g--n|Ncmsg
ar fud	ar fud	ar_fud-S	Spc
Thír	Thír	tír-N	Ncfsc
Chonaill	Chonaill	Conaill-N	Npm-g|Npfsg
lena	lena	le-S	Spp-s
hathair	hathair	athair-N	Ncmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
Francie	Francie	Francie-N	Npmsc
agus	agus	agus-C	Cc
Mairéad	Mairéad	Mairéad-N	Npmsc
.	.	.-F	Fe
deich	deich	deich-M	Mc
mbliana	mbliana	bliain-N	Ncfpc
d	d	d-X	Xl
’	’	’-F	Fa
aois	aois	aois-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
féin	féin	féin-P	Px
ag	ag	ag-S	Sp
bualadh	bualadh	buail-N	Nv
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
tógáil	tógáil	tóg-N	Nv
amhrán	amhrán	amhrán-N	Ncmpg
i gcuideachta	i gcuideachta	i_gcuideachta-S	Spc
na	na	na-T	Tdfsg
cuideachta	cuideachta	cuideachta-N	Ncfsg
.	.	.-F	Fe
Chastaí	Chastaí	casadh-N	Ncmpc
ceoltóirí	ceoltóirí	ceoltóir-N	Ncmpc
móra	móra	mór-A	Aq--pc
Thír	Thír	tír-N	Ncfsc
Chonaill	Chonaill	Conaill-N	Npm-g|Npfsg
uirthi	uirthi	ar-P	Pr3fs
ag	ag	ag-S	Sp
na	na	na-T	Td-p
seisiúin	seisiúin	seisiún-N	Ncmpc
seo	seo	seo-D	Dd
.	.	.-F	Fe
Chomh	Chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
leis	leis	le-S	Sp
sin	sin	sin-P	Pd
chluineadh	chluineadh	cluin-V	Vmih
sí	sí	sí-P	Pp3fsn
taifeadadh	taifeadadh	taifeadadh-N	Nv|Ncmsc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
de	de	de-S	Sp
na	na	na-T	Td-p
seanfhidléirí	seanfhidléirí	fidléir-N	Ncmpc
iomráiteacha	iomráiteacha	iomráiteach-A	Aq--pg|Aq--pc|Aq--pv
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ar	ar	ar-S	Sp
shlua	shlua	slua-N	Ncmsc
na	na	na-T	Td-p
marbh	marbh	marbh-N	Ncmpg
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
í	í	í-P	Pp3fs
stíl	stíl	stíl-N	Ncfsc
cheoil	cheoil	ceol-N	Nv--g--n|Ncmsg
Thír	Thír	tír-N	Ncfsc
Chonaill	Chonaill	Conaill-N	Npm-g|Npfsg
a	a	a-Q	Q-r
thóg	thóg	tóg-V	Vmis
Mairéad	Mairéad	Mairéad-N	Npmsc
ó	ó	ó-S	Sp
na	na	na-T	Td-p
fidléirí	fidléirí	fidléir-N	Ncmpc
seo	seo	seo-D	Dd
go	go	go-U	Ua
léir	léir	léir-A	Aqp
–	–	–-X	Xx
stíl	stíl	stíl-N	Ncfsc
ar	ar	ar-S	Sp
leith	leith	leith-N	Ncfsc
,	,	,-F	Fi
stíl	stíl	stíl-N	Ncfsc
inti	inti	i-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
Frankie	Frankie	Frankie-N	Npmsc
Ba	Ba	is-W	Wsri
ag	ag	ag-S	Sp
seisiún	seisiún	seisiún-N	Ncmsc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
i	i	i-S	Sp
dTábhairne	dTábhairne	tábhairne-N	Ncmsc
Hiúdaí	Hiúdaí	Hiúdaí-N	Npmsc
Bhig	Bhig	Big-N	Npfsg
i	i	i-S	Sp
nGaoth	nGaoth	gaoth-N	Ncmsc|Ncfsc
Dobhair	Dobhair	dobhar-N	Ncmsg
a	a	a-Q	Q-r
casadh	casadh	cas-V	Vmis0
Frankie	Frankie	Frankie-N	Npmsc
Kennedy	Kennedy	Kennedy-N	Npmsc
ar	ar	ar-S	Sp
Mhairéad	Mhairéad	mairéad-N	Npmsc
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
as	as	as-P	Pr3ms
Béal Feirste	Béal Feirste	Béal_Feirste-N	Npmsc
Frankie	Frankie	Frankie-N	Npmsc
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
saoire	saoire	saoire-N	Ncfsc
ag	ag	ag-S	Sp
foghlaim	foghlaim	foghlaim-N	Nv
Gaeilge	Gaeilge	Gaeilge-N	Npfsg
sa	sa	i-S	Spa-s
Ghaeltacht	Ghaeltacht	gaeltacht-N	Ncfsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
Mairéad	Mairéad	Mairéad-N	Npmsc
ach	ach	ach-S	Sp
cúig	cúig	cúig-M	Mc
bliana	bliana	bliain-N	Ncfpc
déag	déag	déag-N	Ns-s
ag	ag	ag-S	Sp
an	an	an-T	Td-s
am	am	am-N	Ncmsc
sin	sin	sin-D	Dd
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
Frankie	Frankie	Frankie-N	Npmsc
ocht	ocht	ocht-M	Mc
mbliana	mbliana	bliain-N	Ncfpc
déag	déag	déag-N	Ns-s
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmm-2s
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
geanúil	geanúil	geanúil-A	Aqp
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhill	fhill	fill-V	Vmis
Frankie	Frankie	Frankie-N	Npmsc
chun	chun	chun-S	Sp
an	an	an-T	Td-s
bhaile	bhaile	baile-N	Ncmsg
thosaigh	thosaigh	tosaigh-V	Vmis
siad	siad	siad-P	Pp3-pn
a	a	a-U	U
scríobh	scríobh	scríobh-N	Nv
chuig	chuig	chuig-S	Sp
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
agus	agus	agus-C	Cc
thagadh	thagadh	tar-V	Vmih
Frankie	Frankie	Frankie-N	Npmsc
go	go	go-S	Sp
Tír	Tír	tír-N	Ncfsc
Chonaill	Chonaill	Conaill-N	Npm-g|Npfsg
chomh	chomh	chomh-R	Ri
minic	minic	minic-A	Aqp
is	is	agus-W	Wp-i|Wpri|Cc
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhéadfadh	fhéadfadh	féad-V	Vmc
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhás	fhás	fás-V	Vmis
an	an	an-T	Td-s
grá	grá	grá-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Frankie	Frankie	Frankie-N	Npmsc
anois	anois	anois-R	Rt
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
níos	níos	níos-U	Uc
mó	mó	mór-A	Aqc
suime	suime	suim-N	Ncfsg
sa	sa	i-S	Spa-s
cheol	cheol	ceol-N	Ncmsc
.	.	.-F	Fe
Níorbh	Níorbh	is-W	Ws-in
fhada	fhada	fada-A	Aqc|Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
in ann	in ann	in_ann-S	Spc
an	an	an-T	Td-s
fheadóg	fheadóg	feadóg-N	Ncfsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
Mairéad	Mairéad	Mairéad-N	Npmsc
agus	agus	agus-C	Cc
Frankie	Frankie	Frankie-N	Npmsc
.	.	.-F	Fe
fhliúit	fhliúit	fliúit-N	Ncfsc
a	a	a-U	U
bhualadh	bhualadh	buail-N	Nv
go	go	go-U	Ua
sármhaith	sármhaith	sármhaith-A	Aqp
agus	agus	agus-C	Cc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
Gaeilge	Gaeilge	Gaeilge-N	Npfsc
bhinn	bhinn	binn-A	Aq-fsc
bhlasta	bhlasta	blasta-A	Aqp
Thír	Thír	tír-N	Ncfsc
Chonaill	Chonaill	Conaill-N	Npm-g|Npfsg
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
thoil	thoil	toil-N	Ncfsc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Níorbh	Níorbh	is-W	Ws-in
fhada	fhada	fada-A	Aqc|Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
Mairéad	Mairéad	Mairéad-N	Npmsc
agus	agus	agus-C	Cc
Frankie	Frankie	Frankie-N	Npmsc
ag	ag	ag-S	Sp
seinm	seinm	seinn-N	Nv
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
i gcuideachta	i gcuideachta	i_gcuideachta-S	Spc
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Shíl	Shíl	síl-V	Vmis
tuismitheoirí	tuismitheoirí	tuismitheoir-N	Ncmpc
Mhairéad	Mhairéad	Mhairéad-N	Npmsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
tús	tús	tús-N	Ncmsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
‑	‑	‑-F	Fb
óg	óg	óg-N	Ncmsc
le	le	le-S	Sp
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
amach	amach	amach-R	Rd
le	le	le-S	Sp
gasúr	gasúr	gasúr-N	Ncmsc
,	,	,-F	Fi
ach	ach	ach-C	Cs
de réir	de réir	de_réir-C	Cs|Spc
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
chuir	chuir	cuir-V	Vmis
siad	siad	siad-P	Pp3-pn
aithne	aithne	aithne-N	Ncfsc
ar	ar	ar-S	Sp
Frankie	Frankie	Frankie-N	Npmsc
thuig	thuig	tuig-V	Vmis
siad	siad	siad-P	Pp3-pn
gur	gur	is-W	Wsdi
duine	duine	duine-N	Ncmsc
fiúntach	fiúntach	fiúntach-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
I	I	i-S	Sp
mBaile	mBaile	Baile-N	Npmsc
Átha Cliath	Átha Cliath	Átha_Cliath-N	Npmsg
Nuair	Nuair	nuair-C	Cs
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhág	fhág	fág-V	Vmis
Mairéad	Mairéad	Mairéad-N	Npmsc
Ardscoil	Ardscoil	ardscoil-N	Ncfsc
Mhuire	Mhuire	Muire-N	Ncfsg|Npfsg
chuaigh	chuaigh	téigh-V	Vmis
sí	sí	sí-P	Pp3fsn
go	go	go-S	Sp
Coláiste	Coláiste	coláiste-N	Ncmsc
Bhantiarna	Bhantiarna	bantiarna-N	Ncfsg
na	na	na-T	Tdfsg
Trócaire	Trócaire	trócaire-N	Ncfsg
i	i	i-S	Sp
mBaile	mBaile	Baile-N	Npmsc
Átha Cliath	Átha Cliath	Átha_Cliath-N	Npmsg
le	le	le-S	Sp
traenáil	traenáil	traenáil-N	Nv
mar	mar	mar-S	Sp
mhúinteoir	mhúinteoir	múinteoir-N	Ncmsc
bunscoile	bunscoile	bunscoil-N	Ncfsg
.	.	.-F	Fe
Chaith	Chaith	caith-V	Vmis
sí	sí	sí-P	Pp3fsn
trí	trí	trí-M	Mc
bliana	bliana	bliain-N	Ncfpc
ansin	ansin	ansin-R	Rt|Rl
agus	agus	agus-C	Cc
deir	deir	abair-V	Vmip
sí	sí	sí-P	Pp3fsn
féin	féin	féin-P	Px
go	go	go-Q	Q
mbíodh	mbíodh	bí-V	Vmih
cumha	cumha	cumha-N	Ncmsc
uirthi	uirthi	ar-P	Pr3fs
i ndiaidh	i ndiaidh	i_ndiaidh-S	Spc
an	an	an-T	Td-s
bhaile	bhaile	baile-N	Ncmsg
.	.	.-F	Fe
Mhothaigh	Mhothaigh	mothaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
Baile	Baile	Baile-N	Npmsc
Átha Cliath	Átha Cliath	Átha_Cliath-N	Npmsc
iontach	iontach	iontach-R	Ri
strainséartha	strainséartha	strainséartha-A	Aqp
agus	agus	agus-C	Cc
ar	ar	ar-S	Sp
dtús	dtús	tús-N	Ncmsc
ní	ní	ní-Q	Qn
théadh	théadh	téigh-V	Vmih---n
sí	sí	sí-P	Pp3fsn
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
chathair	chathair	cathair-N	Ncfsc
mórán	mórán	mórán-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sé	sé	sé-P	Pp3msn
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
gur	gur	gur-Q	Q--s
chuir	chuir	cuir-V	Vmis
sí	sí	sí-P	Pp3fsn
aithne	aithne	aithne-N	Ncfsc
ar	ar	ar-S	Sp
dhaoine	dhaoine	duine-N	Ncmpc
eile	eile	eile-D	Dd
fán	fán	faoi-S	Spa-s
choláiste	choláiste	coláiste-N	Ncmsc
agus	agus	agus-C	Cc
sa	sa	i-S	Spa-s
chathair	chathair	cathair-N	Ncfsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
suim	suim	suim-N	Ncfsc
acu	acu	ag-P	Pr3-p
sa	sa	i-S	Spa-s
cheol	cheol	ceol-N	Ncmsc
Ghaelach	Ghaelach	gaelach-A	Aq-msc
cosúil	cosúil	cosúil-A	Aq-msc
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
mhinic	mhinic	minic-A	Aqp
í	í	í-P	Pp3fs
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
cara	cara	cara-N	Ncmsc
léi	léi	le-P	Pr3fs
,	,	,-F	Fi
Nollaig	Nollaig	Nollaig-N	Ncfsc
Ní	Ní	Ní-U	Up
Chathasaigh	Chathasaigh	Cathasaigh-N	Npfsg
,	,	,-F	Fi
páirteach	páirteach	páirteach-A	Aqp
i	i	i-S	Sp
seisiúin	seisiúin	seisiún-N	Ncmpc
cheoil	cheoil	ceol-N	Nv--g--n|Ncmsg
agus	agus	agus-C	Cc
,	,	,-F	Fi
ar	ar	ar-S	Sp|Ncmsc|Wssi|Wpdi|Wpsi|Q-is
deireadh	deireadh	deireadh-V	Vmih|Ncmsc
,	,	,-F	Fi
thosaigh	thosaigh	tosaigh-V	Vmis
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
buscáil	buscáil	buscáil-N	Nv
fán	fán	faoi-S	Spa-s
chathair	chathair	cathair-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
fáil	fáil	faigh-N	Nv
gig	gig	gig-N	Ncfsc
anois	anois	anois-R	Rt
agus	agus	agus-C	Cc
arís	arís	arís-R	Rg
de	de	de-S	Sp
thoradh	thoradh	toradh-N	Ncmsc
an	an	an-T	Td-s
bhuscála	bhuscála	buscáil-N	Nv--g
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
anois	anois	anois-R	Rt
ag	ag	ag-S	Sp
saothrú	saothrú	saothraigh-N	Nv
airgid	airgid	airgead-N	Ncmsg
phóca	phóca	póca-N	Ncmsg
ar	ar	ar-S	Sp
an	an	an-T	Td-s
cheol	cheol	ceol-N	Nv-----n
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
baint	baint	bain-N	Nv
suilt	suilt	sult-N	Ncmsg
as	as	as-S	Sp
an	an	an-T	Td-s
saol	saol	saol-N	Ncmsc
.	.	.-F	Fe
Mairéad	Mairéad	Mairéad-N	Npmsc
lá	lá	lá-N	Ncmsc
bronnta	bronnta	bronn-A	Av
na	na	na-T	Td-p
gcéimeanna	gcéimeanna	céim-N	Ncfpg
.	.	.-F	Fe
Ag	Ag	ag-S	Sp
Múineadh	Múineadh	múin-N	Nv
Cháiligh	Cháiligh	cáiligh-V	Vmis
Mairéad	Mairéad	Mairéad-N	Npmsc
mar	mar	mar-S	Sp
mhúinteoir	mhúinteoir	múinteoir-N	Ncmsc
an	an	an-T	Td-s
domhain	domhain	domhan-N	Ncmsg
uirthi	uirthi	ar-P	Pr3fs
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
fuair	fuair	faigh-V	Vmis
sí	sí	sí-P	Pp3fsn
post	post	post-N	Ncmsc
i	i	i-S	Sp
Scoil	Scoil	scoil-N	Ncfsc
Oilibhéir	Oilibhéir	Oilibhéar-N	Npm-g|Npmsg|Npm-g
Pluincéid	Pluincéid	Pluincéid-N	Npmsg|Npmsc
i	i	i-S	Sp
Mullach	Mullach	mullach-N	Ncmsc
Íde	Íde	Íde-N	Npmsg
i	i	i-S	Sp
gContae	gContae	contae-N	Ncmsc
Bhaile	Bhaile	Baile-N	Npmsg
Átha Cliath	Átha Cliath	Átha_Cliath-N	Npmsc
an	an	an-T	Td-s
bhliain	bhliain	bliain-N	Ncfsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|Dd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Frankie	Frankie	Frankie-N	Npmsc
Kennedy	Kennedy	Kennedy-N	Npmsc
ag	ag	ag-S	Sp
múineadh	múineadh	múin-N	Nv
sa	sa	i-S	Spa-s
scoil	scoil	scoil-N	Ncfsc
chéanna	chéanna	céanna-A	Aqp
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
mar	mar	mar-S	Sp
gheall	gheall	geall-N	Ncmsc
ar	ar	ar-S	Sp
Mhairéad	Mhairéad	mairéad-N	Npmsc
a	a	a-Q	Q-r
chuaigh	chuaigh	téigh-V	Vmis
Frankie	Frankie	Frankie-N	Npmsc
a	a	a-U	U
theagasc	theagasc	teagasc-N	Nv
i	i	i-S	Sp
mBaile	mBaile	Baile-N	Npmsc
Átha Cliath	Átha Cliath	Átha_Cliath-N	Npmsg
an	an	an-T	Td-s
chéad	chéad	céad-M	Mo
lá	lá	lá-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
obair	obair	obair-N	Ncfsc|Nv-----n
Frankie	Frankie	Frankie-N	Npmsc
agus	agus	agus-C	Cc
Mairéad	Mairéad	Mairéad-N	Npmsc
go	go	go-U	Ua
crua	crua	crua-A	Aqp
chun	chun	chun-S	Sp
an	an	an-T	Td-s
ceol	ceol	ceol-N	Ncmsc
a	a	a-U	U
chur	chur	cuir-N	Nv
chun	chun	chun-S	Sp
cinn	cinn	ceann-N	Ncmsg
i	i	i-S	Sp
Scoil	Scoil	scoil-N	Ncfsc
Oilibhéir	Oilibhéir	Oilibhéar-N	Npm-g|Npmsg|Npm-g
Pluincéid	Pluincéid	Pluincéid-N	Npmsg|Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Mairéad	Mairéad	Mairéad-N	Npmsc
iontach	iontach	iontach-R	Ri
tugtha	tugtha	tugtha-A	Aqp
don	don	do-S	Spa-s
mhúinteoireacht	mhúinteoireacht	múinteoireacht-N	Ncfsc
.	.	.-F	Fe
Mura	Mura	mura-C	Cs
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
ina	ina	i-S	Spp-s
ceoltóir	ceoltóir	ceoltóir-N	Ncmsc
,	,	,-F	Fi
a	a	a-Q	Q-r
deir	deir	abair-V	Vmip
sí	sí	sí-P	Pp3fsn
,	,	,-F	Fi
bheadh	bheadh	bí-V	Vmc
sí	sí	sí-P	Pp3fsn
ina	ina	i-S	Spp-s
múinteoir	múinteoir	múinteoir-N	Ncmsc
bunscoile	bunscoile	bunscoil-N	Ncfsg
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
atá	atá	bí-V	Vmip---r
inniu	inniu	inniu-R	Rt
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
dáimh	dáimh	dáimh-N	Ncfsc
ar	ar	ar-S	Sp
leith	leith	leith-N	Ncfsc
ag	ag	ag-S	Sp
iardhaltaí	iardhaltaí	iardhalta-N	Ncmpc
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
foireann	foireann	foireann-N	Ncfsc
Scoil	Scoil	scoil-N	Ncfsc
Oilibhéir	Oilibhéir	Oilibhéar-N	Npm-g|Npmsg|Npm-g
Pluincéid	Pluincéid	Pluincéid-N	Npmsg|Npmsc
le	le	le-S	Sp
Mairéad	Mairéad	Mairéad-N	Npmsc
go	go	go-U	Ua
fóill	fóill	fóill-A	Aqp
agus	agus	agus-C	Cc
molann	molann	mol-V	Vmip
siad	siad	siad-P	Pp3-pn
go	go	go-U	Ua
hard	hard	ard-X	Xfea|Aqp
í	í	í-P	Pp3fs
.	.	.-F	Fe
Deir	Deir	abair-V	Vmip
siad	siad	siad-P	Pp3-pn
gur	gur	is-W	Wsdi
múinteoir	múinteoir	múinteoir-N	Ncmsc
ar	ar	ar-S	Sp
dóigh	dóigh	dóigh-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
inti	inti	i-P	Pr3fs
agus	agus	agus-C	Cc
gur	gur	is-W	Wsdi
duine	duine	duine-N	Ncmsc
lách	lách	lách-A	Aq-msc
cineálta	cineálta	cineálta-A	Aqp
cneasta	cneasta	cneasta-A	Aqp
í	í	í-P	Pp3fs
nach	nach	nach-Q	Qnrs
dtugadh	dtugadh	tabhair-V	Vmis0
súil	súil	súil-N	Ncfsc|Nv-----n
ghruama	ghruama	gruama-A	Aqp
ar	ar	ar-S	Sp
pháistí	pháistí	páiste-N	Ncmpc
riamh	riamh	riamh-R	Rg
.	.	.-F	Fe
Chomh	Chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
le	le	le-S	Sp
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
obair	obair	obair-N	Nv-----n
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
ar	ar	ar-S	Sp
scoil	scoil	scoil-N	Ncfsc
bhí	bhí	bí-V	Vmis
Mairéad	Mairéad	Mairéad-N	Npmsc
agus	agus	agus-C	Cc
Frankie	Frankie	Frankie-N	Npmsc
ag	ag	ag-S	Sp
bualadh	bualadh	buail-N	Nv
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
i gcuideachta	i gcuideachta	i_gcuideachta-S	Spc
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
i rith	i rith	i_rith-S	Spc
an	an	an-T	Td-s
ama	ama	ama-N	Ncmsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
clú	clú	clú-N	Ncmsc
agus	agus	agus-C	Cc
cáil	cáil	cál-N	Ncfsc|Ncmsg|Ncmpc
orthu	orthu	ar-P	Pr3-p
mar	mar	mar-S	Sp
cheoltóirí	cheoltóirí	ceoltóir-N	Ncmpc
d	d	d-X	Xl
’	’	’-F	Fa
ardchaighdeán	ardchaighdeán	caighdeán-N	Ncmsc
cheana	cheana	cheana-R	Rg
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
iarradh	iarradh	iarr-V	Vmm-3s
orthu	orthu	ar-P	Pr3-p
ceol	ceol	ceol-N	Ncmsc
tionlacain	tionlacain	tionlacan-N	Ncmsg|Ncmpc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
d	d	d-X	Xl
’	’	’-F	Fa
Albert	Albert	Albert-N	Npmsc
Fry	Fry	fry-X	Xfen
Bhí	Bhí	bí-V	Vmis
Mairéad	Mairéad	Mairéad-N	Npmsc
agus	agus	agus-C	Cc
Frankie	Frankie	Frankie-N	Npmsc
dúnta	dúnta	dún-A	Av
i	i	i-S	Sp
ngrá	ngrá	grá-N	Ncmsc
go	go	go-U	Ua
fóill	fóill	fóill-A	Aqp
agus	agus	agus-C	Cc
níorbh	níorbh	is-W	Ws-in
fhada	fhada	fada-A	Aqc|Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
siad	siad	siad-P	Pp3-pn
idir	idir	idir-S	Sp
dáil	dáil	dáil-N	Ncfsc
is	is	agus-C	Cc
pósadh	pósadh	pós-V	Vmm-3s
.	.	.-F	Fe
Ar	Ar	is-W	Wssi|Wpsi
an	an	an-T	Td-s
Pobail	Pobail	pobal-N	Ncmpc
Mhuire	Mhuire	Muire-N	Ncfsg|Npfsg
i	i	i-S	Sp
nDoirí	nDoirí	doire-N	Ncmpc
Beaga	Beaga	beag-A	Aq--pc
i	i	i-S	Sp
bparóiste	bparóiste	paróiste-N	Ncmsc
Ghaoth	Ghaoth	gaoth-A	Aq-msc
Dobhair	Dobhair	dobhar-N	Ncmpc|Ncmsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
ceoltóirí	ceoltóirí	ceoltóir-N	Ncmpc
ó	ó	ó-S	Sp
cheann	cheann	ceann-N	Ncmsc
ceann	ceann	ceann-N	Ncmpg
na	na	na-T	Tdfsg
tíre	tíre	tír-N	Ncfsg
ag	ag	ag-S	Sp
an	an	an-T	Td-s
bhainis	bhainis	bainis-N	Ncfsc
in	in	i-S	Sp
Óstán	Óstán	óstán-N	Ncmsc
Dhoirí	Dhoirí	Doirí-N	Npfsg
Beaga	Beaga	beag-A	Aq--pg
,	,	,-F	Fi
Teach	Teach	teach-N	Ncmsc
Mhicí	Mhicí	Mhicí-N	Npmsc
,	,	,-F	Fi
i	i	i-S	Sp
nGaoth	nGaoth	gaoth-N	Ncmsc|Ncfsc
Dobhair	Dobhair	dobhar-N	Ncmsg
.	.	.-F	Fe
An	An	an-T	Td-s
Ceol	Ceol	ceol-N	Ncmsc
go	go	go-U	Ua
Lánaimseartha	Lánaimseartha	lánaimseartha-A	Aqp
Bhí	Bhí	bí-V	Vmis
lúcháir	lúcháir	lúcháir-N	Ncfsc
ar	ar	ar-S	Sp
Mhairéad	Mhairéad	mairéad-N	Npmsc
agus	agus	agus-C	Cc
ar	ar	ar-S	Sp
Frankie	Frankie	Frankie-N	Npmsc
nuair	nuair	nuair-C	Cs
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
iarr	iarr	iarr-V	Vmm-2s
Gael	Gael	gael-N	Ncmsc
Linn	Linn	Linn-N	Npmsc
orthu	orthu	ar-P	Pr3-p
ceirnín	ceirnín	ceirnín-N	Ncmsc
dá	dá	do-S	Spp-p
gcuid	gcuid	cuid-N	Ncfsc
féin	féin	féin-P	Px
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
siad	siad	siad-P	Pp3-pn
Ceol	Ceol	ceol-N	Ncmsc|Nv-----n
Aduaidh	Aduaidh	aduaidh-A	Aqp|Rd
amach	amach	amach-R	Rd
maith	maith	maith-N	Ncfsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
an	an	an-T	Td-s
ceirnín	ceirnín	ceirnín-N	Ncmsc
seo	seo	seo-D	Dd
ceol	ceol	ceol-N	Ncmsc|Nv-----n
traidisiúnta	traidisiúnta	traidisiúnta-A	Aqp
Chúige	Chúige	cúige-N	Ncmsg
Uladh	Uladh	Uladh-N	Npmsc|Npfsg
chun	chun	chun-S	Sp
cinn	cinn	ceann-N	Ncmsg
ar fud	ar fud	ar_fud-S	Spc
na	na	na-T	Tdfsg
hÉireann	hÉireann	Éire-N	Npfsg
,	,	,-F	Fi
agus	agus	agus-C	Cc
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
tá	tá	bí-V	Vmip
tábhacht	tábhacht	tábhacht-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
ag	ag	ag-S	Sp
baint	baint	bain-N	Nv
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
ráchairt	ráchairt	ráchairt-N	Ncfsc
níos	níos	níos-U	Uc
mó	mó	mór-A	Aqc
ná	ná	ná-C	Cc
riamh	riamh	riamh-R	Rg
ar	ar	ar-S	Sp
Mhairéad	Mhairéad	mairéad-N	Npmsc
agus	agus	agus-C	Cc
ar	ar	ar-S	Sp
Frankie	Frankie	Frankie-N	Npmsc
anois	anois	anois-R	Rt
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
caitheamh	caitheamh	caith-N	Nv
cuid	cuid	cuid-N	Ncfsc
mhór	mhór	mór-N	Ncmpg
ama	ama	ama-N	Ncmsg|Ncmsc
ag	ag	ag-S	Sp
taisteal	taisteal	taistil-N	Nv
,	,	,-F	Fi
chan	chan	chan-W	Wp-in
amháin	amháin	amháin-A	Aqp
in	in	i-S	Sp
Éirinn	Éirinn	Éire-N	Npfsd
ach	ach	ach-S	Sp|Cs
i	i	i-S	Sp
Meiriceá	Meiriceá	Meiriceá-N	Npfsc
fosta	fosta	fosta-A	Aqp
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
fhéadfadh	fhéadfadh	féad-V	Vmc----n
siad	siad	siad-P	Pp3-pn
an	an	an-T	Td-s
dá	dá	dó-M	Mc
thrá	thrá	trá-N	Ncfsc
a	a	a-U	U
fhreastal	fhreastal	freastail-N	Nv
.	.	.-F	Fe
Shocraigh	Shocraigh	socraigh-V	Vmis
siad	siad	siad-P	Pp3-pn
sa	sa	i-S	Spa-s
deireadh	deireadh	deireadh-N	Ncmsc
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
orthu	orthu	ar-P	Pr3-p
cúl	cúl	cúl-N	Ncmsc
a	a	a-D	Dp3
gcinn	gcinn	ceann-N	Ncmpc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
don	don	do-S	Spa-s
mhúinteoireacht	mhúinteoireacht	múinteoireacht-N	Ncfsc
agus	agus	agus-C	Cc
dul	dul	téigh-N	Ncmsc|Nv
leis	leis	le-S	Sp
an	an	an-T	Td-s
cheol	cheol	ceol-N	Nv-----n
go	go	go-U	Ua
lánaimseartha	lánaimseartha	lánaimseartha-A	Aqp
.	.	.-F	Fe
Altan	Altan	Altan-N	Npmsc
An	An	an-T	Td-s
Earagail	Earagail	Earagail-N	Npmsc
.	.	.-F	Fe
agus	agus	agus-C	Cc
ceoltóirí	ceoltóirí	ceoltóir-N	Ncmpc
eile	eile	eile-D	Dd
an	an	an-T	Td-s
banna	banna	banna-N	Ncmsg|Ncmsc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
,	,	,-F	Fi
Altan	Altan	Altan-N	Npmsc
.	.	.-F	Fe
Thóg	Thóg	tóg-V	Vmis
siad	siad	siad-P	Pp3-pn
t	t	t-X	Xl
‑	‑	‑-F	Fb
ainm	ainm	ainm-N	Ncmsc
ó	ó	ó-S	Sp
Loch	Loch	loch-N	Ncmsc
Alltáin	Alltáin	alltán-N	Ncmsg
atá	atá	bí-V	Vmip---r
ag	ag	ag-S	Sp
bun	bun	bun-N	Ncmsc
na	na	na-T	Tdfsg
hEaragaile	hEaragaile	hEaragaile-N	Nc
i	i	i-S	Sp
dTír	dTír	tír-N	Ncfsc
Chonaill	Chonaill	Conaill-N	Npm-g|Npfsg
.	.	.-F	Fe
Ainm	Ainm	ainm-N	Ncmsc
maith	maith	maith-A	Aq-msc
atá	atá	bí-V	Vmip---r
ann	ann	i-R	Rl|Pr3ms
do	do	do-S	Sp
bhanna	bhanna	banna-N	Ncmsc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
:	:	:-F	Fi
tá	tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
furasta	furasta	furasta-A	Aqp
a	a	a-U	U
rá	rá	abair-N	Nv
,	,	,-F	Fi
baineann	baineann	bain-V	Vmip
sé	sé	sé-P	Pp3msn
le	le	le-S	Sp
ceantar	ceantar	ceantar-N	Ncmsc
dúchais	dúchais	dúchas-N	Ncmsg
Mhairéad	Mhairéad	Mhairéad-N	Npmsc
agus	agus	agus-C	Cc
tosaíonn	tosaíonn	tosaigh-V	Vmip
sé	sé	sé-P	Pp3msn
leis	leis	le-S	Sp
an	an	an-T	Td-s
litir	litir	litir-N	Ncfsc
‘	‘	‘-X	Xx
A	A	a-U	U|Dp3
’	’	’-F	Fa
,	,	,-F	Fi
rud	rud	rud-N	Ncmsc
a	a	a-Q	Q-r
fhágann	fhágann	fág-V	Vmip
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
ar	ar	ar-S	Sp
bharr	bharr	barr-N	Ncmsc
liostaí	liostaí	liosta-N	Ncmpg
é	é	é-P	Pp3ms
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
domhan	domhan	domhan-N	Ncmsc
siúlta	siúlta	siúil-A	Av
ag	ag	ag-S	Sp
Mairéad	Mairéad	Mairéad-N	Npmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
ghrúpa	ghrúpa	grúpa-N	Ncmsg
,	,	,-F	Fi
Altan	Altan	Altan-N	Npmsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
camchuairteanna	camchuairteanna	camchuairt-N	Ncfpc
tugtha	tugtha	tabhair-A	Av
ag	ag	ag-S	Sp
an	an	an-T	Td-s
ghrúpa	ghrúpa	grúpa-N	Ncmsg
ar fud	ar fud	ar_fud-S	Spc
na	na	na-T	Tdfsg
hEorpa	hEorpa	Eoraip-N	Npfsg
agus	agus	agus-C	Cc
níos	níos	níos-U	Uc
faide	faide	fada-A	Aqc
i	i	i-S	Sp
gcéin	gcéin	cian-N	Ncfsd
,	,	,-F	Fi
áiteanna	áiteanna	áit-N	Ncfpc
cosúil	cosúil	cosúil-A	Aq--pg
le	le	le-S	Sp
Meiriceá	Meiriceá	Meiriceá-N	Npfsc
,	,	,-F	Fi
an	an	an-T	Td-s
Astráil	Astráil	Astráil-N	Npfsc
,	,	,-F	Fi
an	an	an-T	Td-s
tSeapáin	tSeapáin	Seapáin-N	Npfsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
Chóiré	Chóiré	Cóiré-N	Npfsc
.	.	.-F	Fe
Chomh	Chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
leis	leis	le-S	Sp
na	na	na-T	Td-p
camchuairteanna	camchuairteanna	camchuairt-N	Ncfpc
tá	tá	bí-V	Vmip
cuid	cuid	cuid-N	Ncfsc
mhór	mhór	mór-N	Ncmpg
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
taifeadta	taifeadta	taifead-A	Av
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
lear	lear	lear-N	Ncmsc
dlúthdhioscaí	dlúthdhioscaí	diosca-N	Ncmpc|Ncmpg
eisithe	eisithe	eisigh-A	Av
acu	acu	ag-P	Pr3-p
ó	ó	ó-C	Cs
thosaigh	thosaigh	tosaigh-V	Vmis
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
seinm	seinm	seinn-N	Nv
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Bronnadh	Bronnadh	bronn-V	Vmis0
cuid	cuid	cuid-N	Ncfsc
mhór	mhór	mór-N	Ncmpg
gradam	gradam	gradam-N	Ncmpg|Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
ghrúpa	ghrúpa	grúpa-N	Ncmsg
de bharr	de bharr	de_bharr-S	Spc
díolacháin	díolacháin	díolachán-N	Ncmsg
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
eisigh	eisigh	eisigh-N	Ncmpc|Vmm-2s
An	An	an-T	Td-s
Post	Post	post-N	Ncmsc
stampa	stampa	stampa-N	Ncmsg|Ncmsc
le	le	le-S	Sp
pictiúr	pictiúr	pictiúr-N	Ncmsc
d	d	d-X	Xl
’	’	’-F	Fa
Altan	Altan	Altan-N	Npmsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Sheinn	Sheinn	seinn-V	Vmis
Altan	Altan	Altan-N	Npmsc
do	do	do-S	Sp
mhaithe	mhaithe	maithe-N	Ncfpc|Ncfsc
agus	agus	agus-C	Cc
do	do	do-S	Sp
mhóruaisle	mhóruaisle	móruasal-N	Ncmpc
,	,	,-F	Fi
ina	ina	i-S	Spp-p|Spp-s
measc	measc	measc-N	Ncmsc
Uachtarán	Uachtarán	uachtarán-N	Ncmsc|Ncmpg
agus	agus	agus-C	Cc
Taoiseach	Taoiseach	taoiseach-N	Ncmsc
na	na	na-T	Tdfsg
hÉireann	hÉireann	Éire-N	Npfsg
agus	agus	agus-C	Cc
ceannairí	ceannairí	ceannaire-N	Ncmpg|Ncmpc
rialtais	rialtais	rialtas-N	Ncmsg|Ncmpc|Ncmsg
ó	ó	ó-S	Sp
thíortha	thíortha	tír-N	Ncfpc
eile	eile	eile-D	Dd
.	.	.-F	Fe
Cor	Cor	cor-V	Vmm-2s|Ncmsc
sa	sa	i-S	Spa-s
Chinniúint	Chinniúint	cinniúint-N	Ncfsc
Bhí	Bhí	bí-V	Vmis
Mairéad	Mairéad	Mairéad-N	Npmsc
agus	agus	agus-C	Cc
Frankie	Frankie	Frankie-N	Npmsc
ar	ar	ar-S	Sp
rothaí	rothaí	rothaí-N	Ncmpc|Ncmsc
an	an	an-T	Td-s
tsaoil	tsaoil	saol-N	Ncmsg
agus	agus	agus-C	Cc
rudaí	rudaí	rud-N	Ncmpg|Ncmpc|Ncmpg
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
go	go	go-U	Ua
hiontach	hiontach	iontach-A	Aqp
maith	maith	maith-A	Aqp
dóibh	dóibh	do-P	Pr3-p
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ansin	ansin	ansin-R	Rt|Rl
,	,	,-F	Fi
sa	sa	i-S	Spa-s
bhliain	bhliain	bliain-N	Ncfsc
Mhothaigh	Mhothaigh	mothaigh-V	Vmis
Frankie	Frankie	Frankie-N	Npmsc
a	a	a-D	Dp3
dhroim	dhroim	droim-N	Ncmsc
ag	ag	ag-S	Sp
éirí	éirí	éirigh-N	Nv
nimhneach	nimhneach	nimhneach-A	Aqp
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
shíl	shíl	síl-V	Vmis---n
sé	sé	sé-P	Pp3msn
mórán	mórán	mórán-N	Ncmsc
de	de	de-P	Pr3ms|Sp
ar	ar	ar-S	Sp
dtús	dtús	tús-N	Ncmsc
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
mhinic	mhinic	minic-A	Aqp
a	a	a-Q	Q-r
bhíodh	bhíodh	bí-V	Vmih
air	air	ar-P	Pr3ms
rudaí	rudaí	rud-N	Ncmpc
troma	troma	trom-A	Aq--pc
a	a	a-U	U
iompar	iompar	iompair-N	Nv
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
ar	ar	ar-S	Sp
chamchuairteanna	chamchuairteanna	camchuairt-N	Ncfpc
agus	agus	agus-C	Cc
shíl	shíl	síl-V	Vmis
sé	sé	sé-P	Pp3msn
gurb	gurb	is-W	Wpdi
é	é	é-P	Pp3ms
sin	sin	sin-P	Pd|W
ba	ba	is-U	U
chiontaí	chiontaí	ciontach-A	Aqc
leis	leis	le-S	Sp
an	an	an-T	Td-s
phian	phian	pian-N	Ncfsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
éirí	éirí	éirigh-N	Nv
níos	níos	níos-U	Uc
measa	measa	olc-A	Aqc
de réir	de réir	de_réir-C	Cs|Spc
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Sa	Sa	i-S	Spa-s
deireadh	deireadh	deireadh-N	Ncmsc
b	b	b-X	Xl
’	’	’-F	Fa
éigean	éigean	éigean-N	Ncmsc
é	é	é-P	Pp3ms
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
dochtúir	dochtúir	dochtúir-N	Ncmsc
.	.	.-F	Fe
Fuarthas	Fuarthas	faigh-V	Vmis0
amach	amach	amach-R	Rd
gur	gur	is-W	Wsdi
ailse	ailse	ailse-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Cuireadh	Cuireadh	cuir-V	Vmis0
gach	gach	gach-D	Dq
cóir	cóir	cór-N	Ncfsc|Ns-s|Ncmpc
leighis	leighis	leigheas-N	Ncmsg|Nv--g|Ncmsg|Nv--g
air	air	ar-P	Pr3ms
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
aghaidh	aghaidh	aghaidh-N	Ncfsc
bisigh	bisigh	biseach-N	Ncmsg
ar feadh	ar feadh	ar_feadh-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
de	de	de-S	Sp
mhíonna	mhíonna	mí-N	Ncfpc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
faraor	faraor	faraor-X	Xsc
géar	géar	géar-N	Ncmsc
,	,	,-F	Fi
tháinig	tháinig	tar-V	Vmis
an	an	an-T	Td-s
aicíd	aicíd	aicíd-N	Ncfsc
ar ais	ar ais	ar_ais-R	Rd
ní ba	ní ba	ní_ba-N	Ns-s
mheasa	mheasa	olc-A	Aqc
.	.	.-F	Fe
Fuair	Fuair	faigh-V	Vmis
Frankie	Frankie	Frankie-N	Npmsc
bás	bás	bás-N	Ncmsc
ar	ar	ar-S	Sp
Mhachaire	Mhachaire	Machaire-N	Npfsg
Gathlán	Gathlán	Gathlán-N	Npmsc
i	i	i-S	Sp
nGaoth	nGaoth	gaoth-N	Ncmsc|Ncfsc
Dobhair	Dobhair	dobhar-N	Ncmsg
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
mhillteanach	mhillteanach	millteanach-A	Aqp
an	an	an-T	Td-s
buille	buille	buille-N	Ncmsc
bás	bás	bás-N	Ncmsc
Frankie	Frankie	Frankie-N	Npmsc
do	do	do-S	Sp
Mhairéad	Mhairéad	mairéad-N	Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
cumann	cumann	cumann-N	Ncmsc
eatarthu	eatarthu	idir-P	Pr3-p
ó	ó	ó-C	Cs
bhí	bhí	bí-V	Vmis
sise	sise	sí-P	Pp3fsne
cúig	cúig	cúig-M	Mc
bliana	bliana	bliain-N	Ncfpc
déag	déag	déag-N	Ns-s
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
shíl	shíl	síl-V	Vmis---n
sí	sí	sí-P	Pp3fsn
riamh	riamh	riamh-R	Rg
go	go	go-Q	Q
dtógfaí	dtógfaí	tóg-V	Vmc-0
uaithi	uaithi	ó-P	Pr3fs
chomh	chomh	chomh-R	Ri
tubaisteach	tubaisteach	tubaisteach-A	Aqp
seo	seo	seo-P	Pd|Dd
é	é	é-P	Pp3ms
agus	agus	agus-C	Cc
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
sí	sí	sí-P	Pp3fsn
fágtha	fágtha	fág-A	Av
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
ina	ina	i-S	Spp-s
baintreach	baintreach	baintreach-N	Ncfsc
gan	gan	gan-S	Sp
í	í	í-P	Pp3fs
ach	ach	ach-S	Sp|Cs
in	in	i-S	Sp
aois	aois	aois-N	Ncfsc
a	a	a-U	Um
cúig	cúig	cúig-M	Mc
bliana	bliana	bliain-N	Ncfpc
déag	déag	déag-N	Ns-s
is	is	agus-C	Cc
fiche	fiche	fiche-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
sula	sula	sula-C	Cs
bhfuair	bhfuair	faigh-V	Vmis
sé	sé	sé-P	Pp3msn
bás	bás	bás-N	Ncmsc
,	,	,-F	Fi
d	d	d-X	Xl
’	’	’-F	Fa
iarr	iarr	iarr-V	Vmm-2s
Frankie	Frankie	Frankie-N	Npmsc
ar	ar	ar-S	Sp
Mhairéad	Mhairéad	mairéad-N	Npmsc
gan	gan	gan-S	Sp
éirí	éirí	éirigh-N	Nv
as	as	as-S	Sp
an	an	an-T	Td-s
cheol	cheol	ceol-N	Nv-----n
.	.	.-F	Fe
Mar	Mar	mar-C	Cs
sin	sin	sin-W	W
de	de	de-P	Pr3ms
,	,	,-F	Fi
i	i	i-S	Sp
bhfách	bhfách	bhfách-N	Ncmsc
le	le	le-S	Sp
Frankie	Frankie	Frankie-N	Npmsc
,	,	,-F	Fi
shocraigh	shocraigh	socraigh-V	Vmis
Mairéad	Mairéad	Mairéad-N	Npmsc
agus	agus	agus-C	Cc
Altan	Altan	Altan-N	Npmsc
leanúint	leanúint	lean-N	Ncfsc|Nv
ar	ar	ar-S	Sp
aghaidh	aghaidh	aghaidh-N	Ncfsc
.	.	.-F	Fe
Go	Go	go-U	Ua
luath	luath	luath-A	Aqp
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|W|Dd
d	d	d-X	Xl
’	’	’-F	Fa
eagraigh	eagraigh	eagraigh-V	Vmm-2s
Mairéad	Mairéad	Mairéad-N	Npmsc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
deartháir	deartháir	deartháir-N	Ncmsc
scoil	scoil	scoil-N	Ncfsc
cheoil	cheoil	ceol-N	Nv--g--n|Ncmsg
i	i	i-S	Sp
nDún	nDún	dún-N	Ncmsc
Lúiche	Lúiche	Lúiche-N	Npmsc
i	i	i-S	Sp
nGaoth	nGaoth	gaoth-N	Ncmsc|Ncfsc
Dobhair	Dobhair	dobhar-N	Ncmsg
.	.	.-F	Fe
Anois	Anois	anois-R	Rt
triallann	triallann	triall-V	Vmip
na	na	na-T	Td-p
céadta	céadta	céad-N	Ncmpc
ceoltóir	ceoltóir	ceoltóir-N	Ncmsc
ar	ar	ar-S	Sp
Scoil	Scoil	scoil-N	Ncfsc
Gheimhridh	Gheimhridh	Geimhridh-N	Npfsg
Frankie	Frankie	Frankie-N	Npmsc
Kennedy	Kennedy	Kennedy-N	Npmsc
gach	gach	gach-D	Dq
bliain	bliain	bliain-N	Ncfsc
idir	idir	idir-S	Sp
dhá	dhá	dó-M	Mc
Nollaig	Nollaig	Nollaig-N	Ncfsc
chun	chun	chun-S	Sp
ceird	ceird	ceird-N	Ncfsc
an	an	an-T	Td-s
cheoil	cheoil	ceol-N	Ncmsg
a	a	a-U	U
fhoghlaim	fhoghlaim	foghlaim-N	Nv
agus	agus	agus-C	Cc
a	a	a-U	U
fheabhsú	fheabhsú	feabhsaigh-N	Nv
.	.	.-F	Fe
Is	Is	is-W	Wp-i
mór	mór	mór-A	Aqp
t	t	t-X	Xl
‑	‑	‑-F	Fb
ómós	ómós	ómós-N	Ncmsc
sin	sin	sin-P	Pd|W|Dd
dó	dó	do-P	Pr3ms
mar	mar	mar-C	Cs
ba	ba	is-W	Wsri
mhúinteoir	mhúinteoir	múinteoir-N	Ncmsc
agus	agus	agus-C	Cc
ceoltóir	ceoltóir	ceoltóir-N	Ncmsc
ar	ar	ar-S	Sp
dóigh	dóigh	dóigh-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
in	in	i-S	Sp
Frankie	Frankie	Frankie-N	Npmsc
féin	féin	féin-P	Px
.	.	.-F	Fe
Tamall	Tamall	tamall-N	Ncmsc
i ndiaidh	i ndiaidh	i_ndiaidh-S	Spc
bhás	bhás	bás-N	Ncmsc
Frankie	Frankie	Frankie-N	Npmsc
fuair	fuair	faigh-V	Vmis
Mairéad	Mairéad	Mairéad-N	Npmsc
cuireadh	cuireadh	cuir-V	Vmis0
chuig	chuig	chuig-S	Sp
searmanas	searmanas	searmanas-N	Ncmsc
cuimhneacháin	cuimhneacháin	cuimhneachán-N	Ncmsg
i	i	i-S	Sp
Scoil	Scoil	scoil-N	Ncfsc
Oilibhéir	Oilibhéir	Oilibhéar-N	Npm-g|Npmsg|Npm-g
Pluincéid	Pluincéid	Pluincéid-N	Npmsg|Npmsc
i	i	i-S	Sp
Mullach	Mullach	mullach-N	Ncmsc
Íde	Íde	Íde-N	Npmsg
,	,	,-F	Fi
an	an	an-T	Td-s
scoil	scoil	scoil-N	Ncfsc
ina	ina	i-S	Spr
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
Frankie	Frankie	Frankie-N	Npmsc
ag	ag	ag-S	Sp
múineadh	múineadh	múin-N	Nv
.	.	.-F	Fe
Cé	Cé	cé-C	Cs
gur	gur	is-W	Wsdi
ócáid	ócáid	ócáid-N	Ncfsc
bhrónach	bhrónach	brónach-A	Aq-fsc|Aq-fsv
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
speisialta	speisialta	speisialta-A	Aqp
agus	agus	agus-C	Cc
ceolmhar	ceolmhar	ceolmhar-A	Aqp
fosta	fosta	fosta-A	Aqp
.	.	.-F	Fe
Sheinn	Sheinn	seinn-V	Vmis
Mairéad	Mairéad	Mairéad-N	Npmsc
agus	agus	agus-C	Cc
Altan	Altan	Altan-N	Npmsc
i	i	i-S	Sp
gcomhluadar	gcomhluadar	comhluadar-N	Ncmsc
na	na	na-T	Td-p
ndaltaí	ndaltaí	dalta-N	Ncmpg
agus	agus	agus-C	Cc
na	na	na-T	Td-p
múinteoirí	múinteoirí	múinteoir-N	Ncmpg|Ncmpc
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
siad	siad	siad-P	Pp3-pn
crann	crann	crann-N	Ncmsc
i	i	i-S	Sp
gcuimhne	gcuimhne	cuimhne-N	Ncfsc
do	do	do-S	Sp
Frankie	Frankie	Frankie-N	Npmsc
i	i	i-S	Sp
ngairdín	ngairdín	gairdín-N	Ncmsc
na	na	na-T	Tdfsg
scoile	scoile	scoil-N	Ncfsg
.	.	.-F	Fe
Saol	Saol	saol-N	Ncmsc
Úr	Úr	úr-A	Aq-msc
Phós	Phós	pós-V	Vmis
sí	sí	sí-P	Pp3fsn
Dermot	Dermot	Dermot-N	Npmsc
Byrne	Byrne	Byrne-N	Npmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
chéad	chéad	céad-M	Mo
lá	lá	lá-N	Ncmsc
de	de	de-S	Sp
Dheireadh Fómhair	Dheireadh Fómhair	Deireadh_Fómhair-N	Ncmsc
i	i	i-S	Sp
dTeach	dTeach	teach-N	Ncmsc
Pobail	Pobail	pobal-N	Ncmsg
Dhún	Dhún	dún-V	Vmis
Lúiche	Lúiche	Lúiche-N	Npmsc
ag	ag	ag-S	Sp
bun	bun	bun-N	Ncmsc
na	na	na-T	Tdfsg
hEaragaile	hEaragaile	hEaragaile-N	Nc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
ceoltóir	ceoltóir	ceoltóir-N	Ncmsc
é	é	é-P	Pp3ms
Dermot	Dermot	Dermot-N	Npmsc
fosta	fosta	fosta-A	Aqp
agus	agus	agus-C	Cc
tá	tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
bhall	bhall	ball-N	Ncmsc
d	d	d-X	Xl
’	’	’-F	Fa
Altan	Altan	Altan-N	Npmsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
iomrá	iomrá	iomrá-N	Ncmsc
leitheadach	leitheadach	leitheadach-A	Aq-msc
air	air	ar-N	Ncmsg|Pr3ms
mar	mar	mar-S	Sp
bhoscadóir	bhoscadóir	boscadóir-N	Ncmsc
fíormhaith	fíormhaith	fíormhaith-A	Aq-msc
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
Mairéad	Mairéad	Mairéad-N	Npmsc
,	,	,-F	Fi
Nia	Nia	Nia-N	Npmsc
agus	agus	agus-C	Cc
Dermot	Dermot	Dermot-N	Npmsc
Mairéad	Mairéad	Mairéad-N	Npmsc
agus	agus	agus-C	Cc
Dermot	Dermot	Dermot-N	Npmsc
fúthu	fúthu	faoi-P	Pr3-p
i	i	i-S	Sp
mBaile	mBaile	Baile-N	Npmsc
Átha Cliath	Átha Cliath	Átha_Cliath-N	Npmsg
ar	ar	ar-S	Sp
dtús	dtús	tús-N	Ncmsc
agus	agus	agus-C	Cc
rugadh	rugadh	beir-V	Vmis0
iníon	iníon	iníon-N	Ncfsc
a	a	a-Q	Q-r
bhaist	bhaist	baist-V	Vmis
siad	siad	siad-P	Pp3-pn
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Faoin	Faoin	faoi-S	Spa-s
am	am	am-N	Ncmsc
seo	seo	seo-D	Dd
bhí	bhí	bí-V	Vmis
a	a	a-D	Dp3
saol	saol	saol-N	Ncmsc
caite	caite	caith-A	Av
ag	ag	ag-S	Sp
Mairéad	Mairéad	Mairéad-N	Npmsc
i	i	i-S	Sp
mBaile	mBaile	Baile-N	Npmsc
Átha Cliath	Átha Cliath	Átha_Cliath-N	Npmsg
ó	ó	ó-C	Cs
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
le	le	le-S	Sp
saol	saol	saol-N	Ncmsc
na	na	na-T	Tdfsg
cathrach	cathrach	cathair-N	Ncfsg
,	,	,-F	Fi
ach	ach	ach-C	Cs
sa	sa	i-S	Spa-s
deireadh	deireadh	deireadh-N	Ncmsc
shocraigh	shocraigh	socraigh-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-Q	Q-p
bhogadh	bhogadh	bog-V	Vmih
sí	sí	sí-P	Pp3fsn
Baile	Baile	Baile-N	Npmsc
Átha Cliath	Átha Cliath	Átha_Cliath-N	Npmsc
cionn	cionn	ceann-N	Ncfsd
is	is	agus-C	Cc
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
a	a	a-D	Dp3
cuid	cuid	cuid-N	Ncfsc
oibre	oibre	obair-N	Ncfsg|Nv--g--n
ag	ag	ag-S	Sp
brath	brath	braith-N	Nv
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
beith	beith	beith-N	Ncfsc
sa	sa	i-S	Spa-s
chathair	chathair	cathair-N	Ncfsc
níos	níos	níos-U	Uc
mó	mó	mór-A	Aqc
.	.	.-F	Fe
Chomh	Chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
leis	leis	le-S	Sp
sin	sin	sin-P	Pd
,	,	,-F	Fi
dar	dar	dar-V	Vmip
léi	léi	le-P	Pr3fs
,	,	,-F	Fi
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
saol	saol	saol-N	Ncmsc
na	na	na-T	Tdfsg
tuaithe	tuaithe	tuath-N	Ncfsg
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
níos	níos	níos-U	Uc
folláine	folláine	folláin-A	Aqc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
Nia	Nia	Nia-N	Npmsg|Npfsg
a	a	a-U	U
thógáil	thógáil	tóg-N	Nv
sa	sa	i-S	Spa-s
Ghaeltacht	Ghaeltacht	gaeltacht-N	Ncfsc
cóngarach	cóngarach	cóngarach-A	Aqp
dá	dá	do-S	Spp-s|Spp-p
muintir	muintir	muintir-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
hathair	hathair	athair-N	Ncmsc
,	,	,-F	Fi
Francie	Francie	Francie-N	Npmsc
,	,	,-F	Fi
ag	ag	ag-S	Sp
éileamh	éileamh	éiligh-N	Nv
san	san	i-S	Spa-s
am	am	am-N	Ncmsc
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
níos	níos	níos-U	Uc
mó	mó	mór-A	Aqc
ama	ama	ama-N	Ncmsg
a	a	a-U	U
chaitheamh	chaitheamh	caith-N	Nv
ina	ina	i-S	Spp-s
chuideachta	chuideachta	cuideachta-N	Ncfsc
.	.	.-F	Fe
Sceitse	Sceitse	sceitse-N	Ncmsc
a	a	a-Q	Q-r
tharraing	tharraing	tarraing-V	Vmis
Mairéad	Mairéad	Mairéad-N	Npmsc
dá	dá	de-S	Spp-s
hathair	hathair	athair-N	Ncmsc
.	.	.-F	Fe
Anois	Anois	anois-R	Rt
ós	ós	ó-N	Ncmsc|Csw
rud	rud	rud-N	Ncmsc
é	é	é-P	Pp3ms
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
Mairéad	Mairéad	Mairéad-N	Npmsc
ina	ina	i-S	Spp-s
cónaí	cónaí	cónaí-N	Ncmsc
fá	fá	faoi-P	Pr3ms
bhaile	bhaile	baile-N	Ncmsc
agus	agus	agus-C	Cc
iníon	iníon	iníon-N	Ncfsc
aici	aici	ag-P	Pr3fs
,	,	,-F	Fi
tá	tá	bí-V	Vmip
níos	níos	níos-U	Uc
mó	mó	mór-A	Aqc
ama	ama	ama-N	Ncmsg
aici	aici	ag-P	Pr3fs
don	don	do-S	Spa-s
chumadóireacht	chumadóireacht	cumadóireacht-N	Ncfsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
bunús	bunús	bunús-N	Ncmsc
a	a	a-D	Dp3
cuid	cuid	cuid-N	Ncfsc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
bunaithe	bunaithe	bunaigh-A	Av
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
ceantar	ceantar	ceantar-N	Ncmsc
dúchais	dúchais	dúchas-N	Ncmsg|Ncmpc
.	.	.-F	Fe
Chomh	Chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
le	le	le-S	Sp
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
cumadóireacht	cumadóireacht	cumadóireacht-N	Ncfsc
bíonn	bíonn	bí-V	Vmig
Mairéad	Mairéad	Mairéad-N	Npmsc
ag	ag	ag-S	Sp
líníocht	líníocht	líníocht-N	Ncfsc
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
tarraingt	tarraingt	tarraing-N	Nv
pictiúr	pictiúr	pictiúr-N	Ncmpg
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
spéis	spéis	spéis-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
aici	aici	ag-P	Pr3fs
sa	sa	i-S	Spa-s
líníocht	líníocht	líníocht-N	Ncfsc
ó	ó	ó-C	Cs
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
scoil	scoil	scoil-N	Ncfsc
agus	agus	agus-C	Cc
tá	tá	bí-V	Vmip
seans	seans	seans-N	Ncmsc
anois	anois	anois-R	Rt
aici	aici	ag-P	Pr3fs
níos	níos	níos-U	Uc
mó	mó	mór-A	Aqc
ama	ama	ama-N	Ncmsg
a	a	a-U	U
chaitheamh	chaitheamh	caith-N	Nv
leis	leis	le-S	Sp
an	an	an-T	Td-s
ealaín	ealaín	ealaín-N	Ncfsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
Mairéad	Mairéad	Mairéad-N	Npmsc
ag	ag	ag-S	Sp
seinm	seinm	seinn-N	Nv
le	le	le-S	Sp
grúpa	grúpa	grúpa-N	Ncmsc
eile	eile	eile-D	Dd
anois	anois	anois-R	Rt
,	,	,-F	Fi
‘	‘	‘-X	Xx
The	The	the-X	Xfe
String	String	string-X	Xfen
Sisters	Sisters	sisters-X	Xfen
’	’	’-F	Fa
.	.	.-F	Fe
Grúpa	Grúpa	grúpa-N	Ncmsc
de	de	de-S	Sp
cheoltóirí	cheoltóirí	ceoltóir-N	Ncmpc
mná	mná	bean-N	Ncfsg
atá	atá	bí-V	Vmip---r
iontu	iontu	i-P	Pr3-p
ó	ó	ó-S	Sp
Mheiriceá	Mheiriceá	Meiriceá-N	Npfsc
,	,	,-F	Fi
na	na	na-T	Td-p
tíortha	tíortha	tír-N	Ncfpc
Lochlannacha	Lochlannacha	Lochlannach-A	Aq--pc
,	,	,-F	Fi
Albain	Albain	Albain-N	Npfsc
agus	agus	agus-C	Cc
,	,	,-F	Fi
ar	ar	ar-S	Sp
ndóigh	ndóigh	dóigh-N	Ncfsc
,	,	,-F	Fi
ó	ó	ó-S	Sp
Éirinn	Éirinn	Éire-N	Npfsd
,	,	,-F	Fi
agus	agus	agus-C	Cc
a	a	a-D	Dp3
stíl	stíl	stíl-N	Ncfsc
dhúchasach	dhúchasach	dúchasach-A	Aq-fsc
féin	féin	féin-P	Px
ag	ag	ag-S	Sp
gach	gach	gach-D	Dq
duine	duine	duine-N	Ncmsc
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
ag	ag	ag-S	Sp
éirí	éirí	éirigh-N	Nv
go	go	go-S	Sp
han	han	han-N	Ncfsc
‑	‑	‑-F	Fb
mhaith	mhaith	maith-V	Vmis
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
Mairéad	Mairéad	Mairéad-N	Npmsc
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
lena	lena	le-S	Spp-p|Spp-s
saol	saol	saol-N	Ncmsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
teach	teach	teach-N	Ncmsc
úr	úr	úr-A	Aq-msc
deismir	deismir	deismir-A	Aq-msc
aici	aici	ag-P	Pr3fs
ar	ar	ar-S	Sp
an	an	an-T	Td-s
Charraig	Charraig	carraig-N	Ncfsc
Fhinn	Fhinn	Finn-N	Npmsc
cóngarach	cóngarach	cóngarach-A	Aq-msc
do	do	do-S	Sp
Ghaoth	Ghaoth	gaoth-N	Ncmsc|Ncfsc
Dobhair	Dobhair	dobhar-N	Ncmsg
,	,	,-F	Fi
áit	áit	áit-N	Ncfsc
a	a	a-Q	Q-i
bhfuil	bhfuil	bí-V	Vmip---d
cuid	cuid	cuid-N	Ncfsc
mhór	mhór	mór-N	Ncmpg
gaolta	gaolta	gaol-N	Ncmpg|Ncmpc
aici	aici	ag-P	Pr3fs
,	,	,-F	Fi
agus	agus	agus-C	Cc
Níl	Níl	bí-V	Vmip---n
de	de	de-S	Sp
dhíth	dhíth	díth-N	Ncfsc
uirthi	uirthi	ar-P	Pr3fs
anois	anois	anois-R	Rt
ach	ach	ach-S	Sp
leanúint	leanúint	leanúint-N	Ncfsc
ar	ar	ar-S	Sp
aghaidh	aghaidh	aghaidh-N	Ncfsc
mar	mar	mar-C	Cs
atá	atá	bí-V	Vmip---r
,	,	,-F	Fi
ag	ag	ag-S	Sp
cumadh	cumadh	cum-N	Nv
amhrán	amhrán	amhrán-N	Ncmpg
agus	agus	agus-C	Cc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
,	,	,-F	Fi
ag	ag	ag-S	Sp
seinm	seinm	seinn-N	Nv
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
tarraingt	tarraingt	tarraing-N	Nv
pictiúr	pictiúr	pictiúr-N	Ncmpg
.	.	.-F	Fe
Ach	Ach	ach-S	Sp|Cs
thar	thar	thar-S	Sp
rud	rud	rud-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
eile	eile	eile-D	Dd
tá	tá	bí-V	Vmip
sí	sí	sí-P	Pp3fsn
sásta	sásta	sásta-A	Aqp
go	go	go-S	Sp
dtig	dtig	teach-N	Ncmsd
léi	léi	le-P	Pr3fs
tréan	tréan	tréan-N	Ncmsc
ama	ama	ama-N	Ncmsg|Ncmsc
a	a	a-U	U
chaitheamh	chaitheamh	caith-N	Nv
le	le	le-S	Sp
Nia	Nia	Nia-N	Npmsc
,	,	,-F	Fi
a	a	a-D	Dp3
‘	‘	‘-X	Xx
Níon	Níon	Níon-N	Npmsc
Ó.	Ó.	Ó.-Y	Y
’	’	’-F	Fa
Nia	Nia	Nia-N	Npmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
trá	trá	trá-N	Ncfsc
.	.	.-F	Fe
Mo	Mo	mo-D	Dp1-s
Níon	Níon	Níon-N	Npmsc
Ó	Ó	Ó-U	Up
Tar	Tar	thar-S	Sp
liom	liom	le-P	Pr1-s
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
Mo	Mo	mo-D	Dp1-s
níon	níon	níon-N	Ncmsc
ó	ó	ó-C	Cs|Sp
Thar	Thar	thar-S	Sp
mhaola	mhaola	maol-A	Aq--pc
fionna	fionna	fionn-A	Aq--pc
na	na	na-T	Tdfsg
Trá	Trá	trá-N	Ncfsg
Báine	Báine	bán-A	Aq-fsg
Is	Is	agus-W	Wp-i|Wpri|Cc
déan	déan	déan-V	Vmm-2s|Ncmsc|Ncmpg
caisleáin	caisleáin	caisleán-N	Ncmsg|Ncmpc
óir	óir	ór-C	Cs|Ncmsg|Ncmpc|Ncmsg
Mo	Mo	mo-D	Dp1-s
níon	níon	níon-N	Ncmsc
ó	ó	ó-C	Cs
Den	Den	de-S	Spa-s
ghainimh	ghainimh	gaineamh-N	Ncmpc
mhín	mhín	mín-A	Aqp
’	’	’-F	Fa
s	s	s-X	Xl
sliogáin	sliogáin	sliogán-N	Ncmpc
ghlé	ghlé	glé-A	Aqp
.	.	.-F	Fe
Go	Go	go-Q	Q
mbeidh	mbeidh	bí-V	Vmif
d	d	d-X	Xl
’	’	’-F	Fa
aistear	aistear	aistear-N	Ncmsc
réidh	réidh	réidh-A	Aq-msc
Mo	Mo	mo-D	Dp1-s
níon	níon	níon-N	Ncmsc
ó	ó	ó-C	Cs
Ar	Ar	is-W	Wpdi|Wpsi|Wssi
fud	fud	fud-N	Ns-s
an	an	an-T	Td-s
tsaoil	tsaoil	saol-N	Ncmsg
seo	seo	seo-D	Dd
’	’	’-F	Fa
tá	tá	bí-V	Vmip
romhat	romhat	roimh-P	Pr2-s
Is	Is	agus-C	Cc
lean	lean	lean-V	Vmm-2s
do	do	do-S	Sp
mhian	mhian	mian-N	Ncfsc
Mo	Mo	mo-D	Dp1-s
níon	níon	níon-N	Ncmsc
ó	ó	ó-C	Cs
Is	Is	is-W	Wpri
beidh	beidh	bí-V	Vmif
cumhdach	cumhdach	cumhdach-N	Nv|Ncmsc
le	le	le-S	Sp
fáil	fáil	faigh-N	Nv
.	.	.-F	Fe
Curfá	Curfá	curfá-N	Ncmsc
:	:	:-F	Fi
Mo	Mo	mo-D	Dp1-s
níon	níon	níon-N	Ncmsc
ó	ó	ó-C	Cs
,	,	,-F	Fi
óró	óró	óró-N	Ncmsc
Mo	Mo	mo-D	Dp1-s
níon	níon	níon-N	Ncmsc
ó	ó	ó-C	Cs
,	,	,-F	Fi
óró	óró	óró-N	Ncmsc
Mo	Mo	mo-D	Dp1-s
níon	níon	níon-N	Ncmsc
ó	ó	ó-C	Cs
,	,	,-F	Fi
óró	óró	óró-N	Ncmsc
Go	Go	go-Q	Q
dtéigh	dtéigh	téigh-V	Vmis
tú	tú	tú-P	Pp2-s
slán	slán	slán-N	Ncmsc|Aqp
gach	gach	gach-D	Dq
oíche	oíche	oíche-N	Ncfsc
’	’	’-F	Fa
s	s	s-X	Xl
ló	ló	lá-N	Ncmsc
.	.	.-F	Fe
Ó	Ó	ó-C	Cs
tóg	tóg	tóg-V	Vmm-2s
do	do	do-Q	Q
sheol	sheol	seol-V	Vmis
Mo	Mo	mo-D	Dp1-s
níon	níon	níon-N	Ncmsc
ó	ó	ó-C	Cs
Amach	Amach	amach-R	Rd
go	go	go-S	Sp
Gabhla	Gabhla	Gabhla-N	Npmsc
ar	ar	ar-S	Sp
bhád	bhád	bád-N	Ncmsc
sí	sí	sí-P	Pp3fsn
Thar	Thar	thar-S	Sp
bharr	bharr	barr-N	Ncmsc
na	na	na-T	Td-p
dtonn	dtonn	tonn-N	Ncfpg
Mo	Mo	mo-D	Dp1-s
níon	níon	níon-N	Ncmsc
ó	ó	ó-C	Cs|Sp
Go	Go	go-S	Sp
ngealaí	ngealaí	gealach-N	Ncfsg
an	an	an-T	Td-s
ghealach	ghealach	gealach-N	Ncfsc
os	os	os-N	Ncmpg|Ncmsc|Sp
do	do	do-S	Sp
chionn	chionn	ceann-N	Ncfsd
.	.	.-F	Fe
Ó	Ó	ó-U	Up|Sp|Cs
codlaigh	codlaigh	codlach-V	Vmis|Ncmpc
suan	suan	suan-N	Ncmpg|Ncmsc|Ncmpg
Mo	Mo	mo-D	Dp1-s
níon	níon	níon-N	Ncmsc
ó	ó	ó-C	Cs
Ar	Ar	is-W	Wpdi|Wpsi|Wssi
leaba	leaba	leaba-N	Ncfsc
theolaí	theolaí	teolaí-A	Aqp
den	den	de-S	Spa-s
tsíoda	tsíoda	síoda-N	Npmsg
bhán	bhán	bán-A	Aq-msc
Sín	Sín	Sín-N	Npfsc
síos	síos	síos-R	Rd
go	go	go-U	Ua
ciúin	ciúin	ciúin-A	Aqp
Mo	Mo	mo-D	Dp1-s
níon	níon	níon-N	Ncmsc
ó	ó	ó-C	Cs
Is	Is	is-W	Wpri
éist	éist	éist-V	Vmm-2s
le	le	le-S	Sp
ceolta	ceolta	ceol-N	Ncmpc
binn	binn	binn-A	Aq--pg
na	na	na-T	Tdfsg
n	n	n-X	Xl
‑	‑	‑-F	Fb
éan	éan	éan-N	Ncmsc
.	.	.-F	Fe
Go	Go	go-Q	Q-s
dté	dté	téigh-V	Vmsp
tú	tú	tú-P	Pp2-s
slán	slán	slán-A	Aqp|Ncmsc
Mo	Mo	mo-D	Dp1-s
níon	níon	níon-N	Ncmsc
ó	ó	ó-C	Cs|Sp
Gan	Gan	gan-S	Sp
bhuairt	bhuairt	buairt-N	Ncfsc
gan	gan	gan-S	Sp
ghruaim	ghruaim	gruaim-N	Ncfsc
Gach	Gach	gach-D	Dq
oíche	oíche	oíche-N	Ncfsc
is	is	agus-W	Wp-i|Wpri|Cc
ló	ló	lá-N	Ncmsc
Ach	Ach	ach-C	Cs
cuimhnigh	cuimhnigh	cuimhnigh-V	Vmm-2s
do	do	do-Q	Q
lorg	lorg	lorg-V	Vmis
Mo	Mo	mo-D	Dp1-s
níon	níon	níon-N	Ncmsc
ó	ó	ó-C	Cs
Ar	Ar	is-W	Wpdi|Wpsi|Wssi
ghaineamh	ghaineamh	gaineamh-N	Ncmsc
mhín	mhín	mín-A	Aq-msc
na	na	na-T	Tdfsg
Trá	Trá	trá-N	Ncfsg
Báine	Báine	bán-A	Aq-fsg
.	.	.-F	Fe
