 Paráid	Paráid	-X	Xx
Lá	Lá	lá-N	Ncmsc
Fhéile	Fhéile	féile-N	Ncfsg
Pádraig	Pádraig	Pádraig-N	Npm-g|Npmsg|Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
dhá	dhá	dó-M	Mc
lámh	lámh	lámh-N	Ncfsc
sa	sa	i-S	Spa-s
doirteal	doirteal	doirteal-N	Ncmsc
ag	ag	ag-S	Sp
Deaide	Deaide	Deaide-N	Npmsc
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
sciúradh	sciúradh	sciúr-N	Nv
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
dinnéar	dinnéar	dinnéar-N	Ncmsc
ite	ite	ith-A	Av
ag	ag	ag-S	Sp
gach	gach	gach-D	Dq
uile	uile	uile-N	Ns-s|Dq
dhuine	dhuine	duine-N	Ncmsc|Ncmsg
agus	agus	agus-C	Cc
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
bailithe	bailithe	bailigh-A	Av
leo	leo	le-P	Pr3-p
amach	amach	amach-R	Rd
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
spraoi	spraoi	spraoi-N	Ncmsg|Nv--g--n
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
fós	fós	fós-R	Rg
ag	ag	ag-S	Sp
an	an	an-T	Td-s
mbord	mbord	bord-N	Ncmsc
,	,	,-F	Fi
ag	ag	ag-S	Sp
léamh	léamh	léigh-N	Nv
an	an	an-T	Td-s
pháipéir	pháipéir	páipéar-N	Ncmsg
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
suaimhneas	suaimhneas	suaimhneas-N	Ncmsc
.	.	.-F	Fe
Thóg	Thóg	tóg-V	Vmis
Deaide	Deaide	Deaide-N	Npmsc
a	a	a-U	U
shúile	shúile	súil-N	Nv--g--n
de	de	de-S	Sp
na	na	na-T	Td-p
soithí	soithí	soitheach-N	Ncmpc
agus	agus	agus-C	Cc
bhreathnaigh	bhreathnaigh	breathnaigh-V	Vmis
sé	sé	sé-P	Pp3msn
amach	amach	amach-R	Rd
an	an	an-T	Td-s
fhuinneog	fhuinneog	fuinneog-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-S	Sp
meas	meas	meas-N	Ncmsc
tú	tú	tú-P	Pp2-s
cén	cén	cé-W	W--q|Dw--s
sórt	sórt	sórt-N	Ncmsc
pramsáil	pramsáil	pramsáil-N	Nv
thart	thart	thart-R	Rd
atá	atá	bí-V	Vmip---r
ag	ag	ag-S	Sp
Pól	Pól	Pól-N	Npmsc
?	?	?-F	Fq
'	'	'-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
le	le	le-S	Sp
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmm-2s
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
ón	ón	ó-S	Spa-s
mbord	mbord	bord-N	Ncmsc
go	go	go-Q	Q
bhfeicfeadh	bhfeicfeadh	feic-V	Vmc
sí	sí	sí-P	Pp3fsn
di	di	do-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Pól	Pól	Pól-N	Npmsc
ag	ag	ag-S	Sp
máirseáil	máirseáil	máirseáil-N	Nv
,	,	,-F	Fi
cheapfá	cheapfá	ceap-V	Vmc-2s
,	,	,-F	Fi
ach	ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
gach	gach	gach-D	Dq
aon	aon	aon-D	Dq
léim	léim	léim-N	Ncfsc
aige	aige	ag-P	Pr3ms
freisin	freisin	freisin-R	Rg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
dhá	dhá	dó-M	Mc
lámh	lámh	lámh-N	Ncfsc
sínte	sínte	sín-A	Av
amach	amach	amach-R	Rd
chun	chun	chun-S	Sp
tosaigh	tosaigh	tosach-N	Ncmsg
aige	aige	ag-P	Pr3ms
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
geáitsí	geáitsí	geáitse-N	Ncmpc
aisteacha	aisteacha	aisteach-A	Aq--pc
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
ag	ag	ag-S	Sp
Mamaí	Mamaí	mamaí-N	Ncfsc
láithreach	láithreach	láithreach-A	Aq-fsc
céard	céard	cé-W	W--q
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ar	ar	ar-S	Sp
bun	bun	bun-N	Ncmsc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
deir	deir	abair-V	Vmip
sí	sí	sí-P	Pp3fsn
le	le	le-S	Sp
Deaide	Deaide	Deaide-N	Npmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
tá	tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
cleachtadh	cleachtadh	cleacht-N	Nv
don	don	do-S	Spa-s
pharáid	pharáid	paráid-N	Ncfsc
.	.	.-F	Fe
Beidh	Beidh	bí-V	Vmif
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
casadh	casadh	cas-N	Nv
an	an	an-T	Td-s
druma	druma	druma-N	Ncmsg
mhóir	mhóir	mór-A	Aq-msg
le	le	le-S	Sp
banna	banna	banna-N	Ncmsc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
na	na	na-T	Tdfsg
scoile	scoile	scoil-N	Ncfsg
.	.	.-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Á	Á	Á-I	I
,	,	,-F	Fi
b	b	b-X	Xl
’	’	’-F	Fa
in	in	sin-S	Sp|Pd
é	é	é-P	Pp3ms
é	é	é-P	Pp3ms
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Deaide	Deaide	Deaide-N	Npmsc
.	.	.-F	Fe
Thuig	Thuig	tuig-V	Vmis
sé	sé	sé-P	Pp3msn
cuid	cuid	cuid-N	Ncfsc
de	de	de-S	Sp
na	na	na-T	Td-p
geáitsí	geáitsí	geáitse-N	Ncmpc
anois	anois	anois-R	Rt
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhan	fhan	fan-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
breathnú	breathnú	breathnaigh-N	Nv
ar	ar	ar-S	Sp
Phól	Phól	Pól-N	Npmsc
ag	ag	ag-S	Sp
máirseáil	máirseáil	máirseáil-N	Nv
suas	suas	suas-R	Rd
síos	síos	síos-R	Rd
an	an	an-T	Td-s
garraí	garraí	garraí-N	Ncmsg|Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sé	sé	sé-P	Pp3msn
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
gur	gur	gur-Q	Q--s
iompaigh	iompaigh	iompaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
Mhamaí	Mhamaí	mama-N	Ncfsc|Ncmpc
arís	arís	arís-R	Rg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
amhras	amhras	amhras-N	Ncmsc
beag	beag	beag-A	Aq-msc
fós	fós	fós-R	Rg
orm	orm	ar-P	Pr1-s
faoin	faoin	faoi-S	Spa-s
máirseáil	máirseáil	máirseáil-N	Ncfsc
sin	sin	sin-D	Dd
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Thriomaigh	Thriomaigh	triomaigh-V	Vmis
Deaide	Deaide	Deaide-N	Npmsc
a	a	a-D	Dp3
lámha	lámha	lámh-N	Ncfpc
agus	agus	agus-C	Cc
amach	amach	amach-R	Rd
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Inis	Inis	inis-V	Vmis
dom	dom	do-P	Pr1-s
faoin	faoin	faoi-S	Spa-s
bparáid	bparáid	paráid-N	Ncfsc
seo	seo	seo-D	Dd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Deaide	Deaide	Deaide-N	Npmsc
le	le	le-S	Sp
Pól	Pól	Pól-N	Npmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
acu	acu	ag-P	Pr3-p
ar ais	ar ais	ar_ais-R	Rd
sa	sa	i-S	Spa-s
chistin	chistin	cistin-N	Ncfsc
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
fhreagair	fhreagair	freagair-V	Vmis---n
Pól	Pól	Pól-N	Npmsc
Deaide	Deaide	Deaide-N	Npmsc
beag	beag	beag-A	Aq-msc
ná	ná	nach-Q	Qnr
mór	mór	mór-V	Vmm-2s-n
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
giúmar	giúmar	giúmar-N	Ncmsc
maith	maith	maith-A	Aq-msc
air	air	ar-N	Ncmsg|Pr3ms
ar	ar	ar-S	Sp
chor	chor	cor-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
choinnigh	choinnigh	coinnigh-V	Vmis
Deaide	Deaide	Deaide-N	Npmsc
air	air	ar-P	Pr3ms
á	á	do-S	Spo-s
cheistiú	cheistiú	ceistigh-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cén	Cén	cé-D	Dw--s
fáth	fáth	fáth-N	Ncmsc
a	a	a-Q	Q-i
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
léim	léim	léim-V	Vmip1s|Vmis
tar éis	tar éis	tar_éis-S	Spc
gach	gach	gach-D	Dq
uile	uile	uile-N	Ns-s|Dq
thrí	thrí	trí-M	Mc
nó	nó	nó-C	Cc
cheithre	cheithre	ceathair-M	Mc
choiscéim	choiscéim	coiscéim-N	Ncfsc
?	?	?-F	Fq
'	'	'-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
Phléasc	Phléasc	pléasc-V	Vmis
Pól	Pól	Pól-N	Npmsc
amach	amach	amach-R	Rd
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Mar	Mar	mar-C	Cs
níl	níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
rogha	rogha	rogha-N	Ncfsc
agam	agam	ag-P	Pr1-s
!	!	!-F	Fe
'	'	'-F	Fa
Chrom	Chrom	crom-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
cheann	cheann	ceann-N	Ncmsc
ansin	ansin	ansin-R	Rt|Rl
,	,	,-F	Fi
bhrúigh	bhrúigh	brúigh-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
smig	smig	smig-N	Ncfsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
ucht	ucht	ucht-N	Ncmsc
agus	agus	agus-C	Cc
bhreathnaigh	bhreathnaigh	breathnaigh-V	Vmis
sé	sé	sé-P	Pp3msn
síos	síos	síos-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
urlár	urlár	urlár-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhill	fhill	fill-V	Vmis
Mamaí	Mamaí	mamaí-N	Ncmpc|Ncfsc
an	an	an-T	Td-s
páipéar	páipéar	páipéar-N	Ncmsc
go	go	go-U	Ua
deas	deas	deas-R	Ri
réidh	réidh	réidh-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Coinnigh	Coinnigh	Coinnigh-N	Npmsc
ort	ort	ar-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
mhic	mhic	mac-N	Ncmsv
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
Deaide	Deaide	Deaide-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Mínigh	Mínigh	mínigh-V	Vmm-2s
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
dúinn	dúinn	do-P	Pr1-p
,	,	,-F	Fi
maith	maith	maith-A	Aqp
an	an	an-T	Td-s
buachaill	buachaill	buachaill-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Ba	Ba	is-W	Ws|Ws-i
ansin	ansin	ansin-R	Rt|Rl
a	a	a-Q	Q-r
chuir	chuir	cuir-V	Vmis
Pól	Pól	Pól-N	Npmsc
an	an	an-T	Td-s
racht	racht	racht-N	Ncmsc
uaidh	uaidh	ó-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
neart	neart	neart-N	Ncmsc
agamsa	agamsa	ag-P	Pr1-s-e
air	air	ar-P	Pr3ms
más	más	más-N	Ncmsc
agamsa	agamsa	ag-P	Pr1-s-e
atá	atá	bí-V	Vmip---r
na	na	na-T	Td-p
cosa	cosa	cos-N	Ncfpc
is	is	is-U	U
giorra	giorra	gearr-A	Aqc
sa	sa	i-S	Spa-s
rang	rang	rang-N	Ncmsc
.	.	.-F	Fe
Níl	Níl	bí-V	Vmip---n
neart	neart	neart-N	Ncmsc
agamsa	agamsa	ag-P	Pr1-s-e
air	air	ar-P	Pr3ms
má	má	má-N	Ncfsc
d	d	d-X	Xl
’	’	’-F	Fa
iarr	iarr	iarr-V	Vmm-2s
an	an	an-T	Td-s
múinteoir	múinteoir	múinteoir-N	Ncmsc
orm	orm	ar-P	Pr1-s
an	an	an-T	Td-s
druma	druma	druma-N	Ncmsc
millteach	millteach	millteach-A	Aq-msc
mór	mór	mór-A	Aq-msc
sin	sin	sin-P	Pd|W|Dd
a	a	a-U	U
bhualadh	bhualadh	buail-N	Nv
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
…	…	…-F	Fi
agus	agus	agus-C	Cc
…	…	…-F	Fi
níl	níl	bí-V	Vmip---n
neart	neart	neart-N	Ncmsc
agamsa	agamsa	ag-P	Pr1-s-e
air	air	ar-P	Pr3ms
má	má	má-C	Cs
bhím	bhím	bí-V	Vmig1s
ag	ag	ag-S	Sp
rith	rith	rith-N	Nv
is	is	agus-C	Cc
ag	ag	ag-S	Sp
léim	léim	léim-N	Nv
ar nós	ar nós	ar_nós-S	Spc
frog	frog	frog-X	Xfen
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
coinneáil	coinneáil	coinnigh-N	Ncfsc|Nv
suas	suas	suas-R	Rd
le	le	le-S	Sp
gach	gach	gach-D	Dq
uile	uile	uile-N	Ns-s|Dq
dhuine	dhuine	duine-N	Ncmsc|Ncmsg
eile	eile	eile-D	Dd
sa	sa	i-S	Spa-s
pharáid	pharáid	paráid-N	Ncfsc
!	!	!-F	Fe
'	'	'-F	Fa
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
méid	méid	méid-N	Ncmsc
sin	sin	sin-D	Dd
curtha	curtha	cuir-A	Av
de	de	de-P	Pr3ms|Sp
aige	aige	ag-P	Pr3ms
rith	rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
amach	amach	amach-R	Rd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Muise	Muise	muise-X	Xsc
,	,	,-F	Fi
an	an	an-T	Td-s
créatúr	créatúr	créatúr-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Deaide	Deaide	Deaide-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
a	a	a-Q	Q-r
dhéanfas	dhéanfas	déan-V	Vmif---r
muid	muid	muid-P	Pp1-p
?	?	?-F	Fq
'	'	'-F	Fa
Chuimhnigh	Chuimhnigh	cuimhnigh-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
uirthi	uirthi	ar-P	Pr3fs
féin	féin	féin-P	Px
tamaillín	tamaillín	tamall-N	Ncmsc|Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Gabhfaimid	Gabhfaimid	gabh-V	Vmif1p
chun	chun	chun-S	Sp
cainte	cainte	caint-N	Ncfsg|Nv--g--n
leis	leis	le-S	Sp
an	an	an-T	Td-s
Máistreás	Máistreás	máistreás-N	Ncfsc
Méabh	Méabh	Méabh-N	Npfsc
amárach	amárach	amárach-A	Aqp
agus	agus	agus-C	Cc
gheobhaimid	gheobhaimid	faigh-V	Vmif1p
réiteach	réiteach	réiteach-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
idir	idir	idir-S	Sp
an	an	an-T	Td-s
dá	dá	dó-M	Mc
linn	linn	linn-N	Ncfsc
,	,	,-F	Fi
céard	céard	cé-W	W--q
faoi	faoi	faoi-P	Pr3ms
dá	dá	dá-C	Cs
dtiocfadh	dtiocfadh	tar-V	Vmc
Mamó	Mamó	mamó-N	Ncfsc
ar	ar	ar-S	Sp
cuairt	cuairt	cuairt-N	Ncfsc
?	?	?-F	Fq
Thabharfadh	Thabharfadh	tabhair-V	Vmc
sé	sé	sé-P	Pp3msn
sin	sin	sin-P	Pd
ardú	ardú	ardaigh-N	Ncmsc|Nv
croí	croí	croí-N	Ncmsg|Ncmsc
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
'	'	'-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
aontaigh	aontaigh	aontaigh-V	Vmm-2s
Deaide	Deaide	Deaide-N	Npmsc
gur	gur	is-W	Wsdi
phlean	phlean	plean-N	Ncmsc
maith	maith	maith-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ansin	ansin	ansin-R	Rt
.	.	.-F	Fe
Amach	Amach	amach-R	Rd
leis	leis	le-P	Pr3ms
chuig	chuig	chuig-S	Sp
an	an	an-T	Td-s
bhfón	bhfón	fón-N	Ncmsc
chun	chun	chun-S	Sp
cuireadh	cuireadh	cuireadh-N	Ncmsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
do	do	do-S	Sp
Mhamó	Mhamó	mamó-N	Ncfsc
a	a	a-U	U
theacht	theacht	tar-N	Nv
le	le	le-S	Sp
haghaidh	haghaidh	aghaidh-N	Ncfsc
tae	tae	tae-N	Ncmsg
.	.	.-F	Fe
Chaith	Chaith	caith-V	Vmis
siad	siad	siad-P	Pp3-pn
an	an	an-T	Td-s
tráthnóna	tráthnóna	tráthnóna-N	Ncmsc
ag	ag	ag-S	Sp
éisteacht	éisteacht	éist-N	Nv
le	le	le-S	Sp
scéalta	scéalta	scéal-N	Ncmpc
barrúla	barrúla	barrúil-A	Aq--pc
Mhamó	Mhamó	mamó-N	Ncfsg
.	.	.-F	Fe
Dá bharr sin	Dá bharr sin	dá_bharr_sin-R	Rg
uile	uile	uile-N	Ns-s|Dq
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
an	an	an-T	Td-s
oiread	oiread	oiread-N	Ns-s
céanna	céanna	céanna-A	Aqp
imní	imní	imní-N	Ncfsg|Ncfsc
ar	ar	ar-S	Sp
Phól	Phól	Pól-N	Npmsc
faoin	faoin	faoi-S	Spa-s
bparáid	bparáid	paráid-N	Ncfsc
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
a	a	a-U	U
chodladh	chodladh	codail-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
aige	aige	ag-P	Pr3ms
go	go	go-Q	Q
rachadh	rachadh	téigh-V	Vmc
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
agus	agus	agus-C	Cc
Deaide	Deaide	Deaide-N	Npmsc
chun	chun	chun-S	Sp
cainte	cainte	caint-N	Ncfsg|Nv--g--n
leis	leis	le-S	Sp
an	an	an-T	Td-s
Máistreás	Máistreás	máistreás-N	Ncfsc
Méabh	Méabh	Méabh-N	Npfsc
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
dár	dár	do-S	Spp-p
gcionn	gcionn	ceann-N	Ncfsd
.	.	.-F	Fe
Chuimhneoidís	Chuimhneoidís	cuimhnigh-V	Vmc-3p
siúd	siúd	siúd-P	Pd
ar	ar	ar-S	Sp
rud	rud	rud-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
,	,	,-F	Fi
Deaide	Deaide	Deaide-N	Npmsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
Mháistreás	Mháistreás	máistreás-N	Ncfsc
Méabh	Méabh	Méabh-N	Npfsc
go	go	go-U	Ua
maith	maith	maith-A	Aqp
ag	ag	ag-S	Sp
cuimhneamh	cuimhneamh	cuimhnigh-N	Nv
ar	ar	ar-S	Sp
phleananna	phleananna	plean-N	Ncmpc
.	.	.-F	Fe
