 An	An	-X	Xx
Gáirdín	Gáirdín	Gáirdín-N	Npmsc
Álainn	Álainn	álainn-A	Aq-msc
Bhí	Bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
te	te	te-A	Aqp
teolaí	teolaí	teolaí-A	Aqp
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
luí	luí	luí-N	Nv|Ncmsc
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
leaba	leaba	leaba-N	Ncfsc
bheag	bheag	beag-A	Aq-fsc
chluthar	chluthar	cluthar-A	Aq-fsc|Aq-fsv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
teach	teach	teach-N	Ncmsc
ciúin	ciúin	ciúin-A	Aq-msc
anois	anois	anois-R	Rt
ó	ó	ó-C	Cs
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
tórramh	tórramh	tórramh-N	Ncmsc
thart	thart	thart-R	Rd
.	.	.-F	Fe
Bhreathnaigh	Bhreathnaigh	breathnaigh-V	Vmis
mé	mé	mé-P	Pp1-s
uair	uair	uair-N	Ncfsc
amháin	amháin	amháin-A	Aqp
eile	eile	eile-D	Dd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
uaireadóir	uaireadóir	uaireadóir-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ar	ar	ar-S	Sp
an	an	an-T	Td-s
tábla	tábla	tábla-N	Ncfsc|Ncmsc
in aice	in aice	in_aice-S	Spc
na	na	na-T	Tdfsg
fuinneoige	fuinneoige	fuinneog-N	Ncfsg
,	,	,-F	Fi
uaireadóir	uaireadóir	uaireadóir-N	Ncmsc
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhág	fhág	fág-V	Vmis
mo	mo	mo-D	Dp1-s
mháthair	mháthair	máthair-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
Uaireadóir	Uaireadóir	uaireadóir-N	Ncmsc
a	a	a-Q	Q-r
thug	thug	tabhair-V	Vmis
a	a	a-D	Dp3
máthair	máthair	máthair-N	Ncfsc
féin	féin	féin-P	Px
di	di	do-P	Pr3fs
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sise	sise	sí-P	Pp3fsne
ina	ina	i-S	Spp-s
girseach	girseach	girseach-N	Ncfsc
óg	óg	óg-A	Aq-fsc
cosúil	cosúil	cosúil-A	Aq-msc
liomsa	liomsa	le-P	Pr1-s-e
.	.	.-F	Fe
Tharraing	Tharraing	tarraing-V	Vmis
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
phluid	phluid	pluid-N	Ncfsc
timpeall	timpeall	timpeall-S	Sp|Rd
orm	orm	ar-P	Pr1-s
agus	agus	agus-C	Cc
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
éisteacht	éisteacht	éist-N	Nv
leis	leis	le-S	Sp
na	na	na-T	Td-p
roiseanna	roiseanna	rois-N	Ncfpc
móra	móra	mór-A	Aq--pc
gaoithe	gaoithe	gaoth-A	Aq-fsg
taobh amuigh	taobh amuigh	taobh_amuigh-R	Rl
.	.	.-F	Fe
Oíche	Oíche	oíche-N	Ncfsc
fhuar	fhuar	fuar-A	Aq-fsc
gheimhridh	gheimhridh	geimhreadh-N	Ncmsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
de	de	de-S	Sp
dhíon	dhíon	díon-N	Ncmsc
is	is	agus-C	Cc
de	de	de-P	Pr3ms
dheora	dheora	deora-N	Ncfpc|Ncfsc
.	.	.-F	Fe
Lá	Lá	lá-N	Ncmsc
fuar	fuar	fuar-A	Aq-msc
feannta	feannta	feann-A	Aqp|Av
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
níos	níos	níos-U	Uc
luaithe	luaithe	luath-A	Aqc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
cuireadh	cuireadh	cuir-V	Vmis0
mo	mo	mo-D	Dp1-s
mháthair	mháthair	máthair-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
i	i	i-S	Sp
Reilig	Reilig	reilig-N	Ncfsc
na	na	na-T	Tdfsg
Cathrach	Cathrach	cathair-N	Ncfsg
.	.	.-F	Fe
Dhruid	Dhruid	druid-V	Vmis
mé	mé	mé-P	Pp1-s
mo	mo	mo-D	Dp1-s
shúile	shúile	súil-N	Ncfpc
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
mé	mé	mé-P	Pp1-s
paidir	paidir	paidir-N	Ncfsc
lena	lena	le-S	Spp-s
hanam	hanam	anam-N	Ncmsc
.	.	.-F	Fe
Go	Go	go-U	Ua
tobann	tobann	tobann-A	Aqp
chuala	chuala	clois-V	Vmis
mé	mé	mé-P	Pp1-s
cloigín	cloigín	cloigín-N	Ncmsc
ag	ag	ag-S	Sp
bualadh	bualadh	buail-N	Nv
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmm-2s
mé	mé	mé-P	Pp1-s
mo	mo	mo-D	Dp1-s
shúile	shúile	súil-N	Ncfpc
de	de	de-S	Sp
gheit	gheit	geit-N	Ncfsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
a	a	a-Q	Q-r
thuig	thuig	tuig-V	Vmip|Vmis
mé	mé	mé-P	Pp1-s
,	,	,-F	Fi
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
eile	eile	eile-D	Dd
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
ann	ann	i-R	Rl|Pr3ms
ach	ach	ach-S	Sp
aláram	aláram	aláram-N	Ncmsc
an	an	an-T	Td-s
uaireadóra	uaireadóra	uaireadóir-N	Ncmsg
!	!	!-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmm-2s
mé	mé	mé-P	Pp1-s
as	as	as-S	Sp
an	an	an-T	Td-s
leaba	leaba	leaba-N	Ncfsc
.	.	.-F	Fe
Shiúil	Shiúil	siúil-V	Vmis
mé	mé	mé-P	Pp1-s
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
tábla	tábla	tábla-N	Ncmsc|Ncfsc
agus	agus	agus-C	Cc
thóg	thóg	tóg-V	Vmis
mé	mé	mé-P	Pp1-s
uaireadóir	uaireadóir	uaireadóir-N	Ncmsc
mo	mo	mo-D	Dp1-s
Mhóraí	Mhóraí	móraí-N	Ncfsc
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
mé	mé	mé-P	Pp1-s
as	as	as-P	Pr3ms
t	t	t-X	Xl
‑	‑	‑-F	Fb
aláram	aláram	aláram-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
cuirtín	cuirtín	cuirtín-N	Ncmsc
leathoscailte	leathoscailte	leathoscailt-N	Ncfsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
ar	ar	ar-S	Sp
tí	tí	tí-N	Ncfsc
é	é	é-P	Pp3ms
a	a	a-U	U
dhruidim	dhruidim	druid-N	Nv
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
baineadh	baineadh	bain-V	Vmis0
an	an	an-T	Td-s
anáil	anáil	anáil-N	Ncfsc
díom	díom	de-P	Pr1-s
.	.	.-F	Fe
A	A	an-T	Td-s
leithéid	leithéid	leithéid-N	Ncfsc
de	de	de-S	Sp
radharc	radharc	radharc-N	Ncmsc
!	!	!-F	Fe
Oíche	Oíche	oíche-N	Ncfsc
chiúin	chiúin	ciúin-A	Aq-fsc
shocair	shocair	socair-A	Aq-fsc|Aq-fsv
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
anois	anois	anois-R	Rt
ann	ann	i-P	Pr3ms
,	,	,-F	Fi
gairdín	gairdín	gairdín-N	Ncmsc
álainn	álainn	álainn-A	Aq-msc
taibhsiúil	taibhsiúil	taibhsiúil-A	Aq-msc
le	le	le-S	Sp
feiceáil	feiceáil	feic-N	Nv
thíos	thíos	thíos-R	Rd
fúm	fúm	faoi-P	Pr1-s
faoi	faoi	faoi-S	Sp
sholas	sholas	solas-N	Ncmsc
na	na	na-T	Tdfsg
gealaí	gealaí	gealach-N	Ncfsg
,	,	,-F	Fi
gairdín	gairdín	gairdín-N	Ncmsc
ina	ina	i-S	Spr
raibh	raibh	bí-V	Vmis---d
plandaí	plandaí	planda-N	Ncmpc
agus	agus	agus-C	Cc
bláthanna	bláthanna	bláth-N	Ncmpg|Ncmpc
nach	nach	nach-Q	Qnrs
bhfaca	bhfaca	feic-V	Vmis---d
mé	mé	mé-P	Pp1-s
riamh	riamh	riamh-R	Rg
roimhe	roimhe	roimh-P	Pr3ms
seo	seo	seo-P	Pd
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
ina	ina	i-S	Spp-s
shuí	shuí	suí-N	Ncmsc
go	go	go-U	Ua
státúil	státúil	státúil-A	Aqp
ar	ar	ar-S	Sp
ghéag	ghéag	géag-N	Ncfsc
chrainn	chrainn	crann-N	Ncmsg
bhí	bhí	bí-V	Vmis
t	t	t-X	Xl
‑	‑	‑-F	Fb
éan	éan	éan-N	Ncmsc
ba	ba	is-U	U
mhaorga	mhaorga	maorga-A	Aqc
dá	dá	dá-C	Cs
bhfaca	bhfaca	feic-V	Vmis---d
tú	tú	tú-P	Pp2-s
riamh	riamh	riamh-R	Rg
,	,	,-F	Fi
solas	solas	solas-N	Ncmsc
na	na	na-T	Tdfsg
gealaí	gealaí	gealach-N	Ncfsg
ag	ag	ag-S	Sp
lonrú	lonrú	lonraigh-N	Nv
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-U	Ud|Dp3
chleití	chleití	cleiteach-A	Aqc
slíoctha	slíoctha	slíoc-A	Aqp|Av
.	.	.-F	Fe
Arbh	Arbh	is-W	Ws-q
é	é	é-P	Pp3ms
seo	seo	seo-P	Pd
an	an	an-T	Td-s
gairdín	gairdín	gairdín-N	Ncmsc
a	a	a-Q	Q-i
mbíodh	mbíodh	bí-V	Vmih
mo	mo	mo-D	Dp1-s
Mhóraí	Mhóraí	móraí-N	Ncfsc
ag	ag	ag-S	Sp
trácht	trácht	trácht-N	Nv
air	air	ar-N	Ncmsg
,	,	,-F	Fi
an	an	an-T	Td-s
gairdín	gairdín	gairdín-N	Ncmsg|Ncmsc
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
a	a	a-D	Dp3
máthair	máthair	máthair-N	Ncfsc
siúd	siúd	siúd-P	Pd|Dd
tá	tá	bí-V	Vmip
céad	céad	céad-N	Ncmsc|Mc
bliain	bliain	bliain-N	Ncfsc
ó	ó	ó-S	Sp
shin	shin	sin-P	Pd
,	,	,-F	Fi
nuair	nuair	nuair-C	Cs
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
sí	sí	sí-P	Pp3fsn
ach	ach	ach-S	Sp
dhá	dhá	dó-M	Mc
bhliain	bhliain	bliain-N	Ncfsc
déag	déag	déag-N	Ns-s
d	d	d-X	Xl
’	’	’-F	Fa
aois	aois	aois-N	Ncfsc
?	?	?-F	Fq
Rug	Rug	beir-V	Vmis
mé	mé	mé-P	Pp1-s
ar	ar	ar-S	Sp
an	an	an-T	Td-s
uaireadóir	uaireadóir	uaireadóir-N	Ncmsc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmm-2s
mé	mé	mé-P	Pp1-s
liom	liom	le-P	Pr1-s
,	,	,-F	Fi
síos	síos	síos-R	Rd
an	an	an-T	Td-s
staighre	staighre	staighre-N	Ncmsc
chomh	chomh	chomh-R	Ri
ciúin	ciúin	ciúin-A	Aqp
réidh	réidh	réidh-A	Aqp
is	is	agus-C	Cc
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
liom	liom	le-P	Pr1-s
agus	agus	agus-C	Cc
amach	amach	amach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
lá	lá	lá-N	Ncmsc
geal	geal	geal-A	Aq-msc
ann	ann	i-P	Pr3ms
taobh amuigh	taobh amuigh	taobh_amuigh-R	Rl
,	,	,-F	Fi
gairdín	gairdín	gairdín-N	Ncmsc
álainn	álainn	álainn-A	Aq-msc
amach	amach	amach-R	Rd
romham	romham	roimh-P	Pr1-s
agus	agus	agus-C	Cc
boladh	boladh	boladh-N	Ncmsc
cumhra	cumhra	cumhra-A	Aqp
na	na	na-T	Td-p
mbláthanna	mbláthanna	bláth-N	Ncmpg
ar	ar	ar-S	Sp
an	an	an-T	Td-s
aer	aer	aer-N	Ncmsc
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
síos	síos	síos-R	Rd
an	an	an-T	Td-s
cosán	cosán	cosán-N	Ncmsc
agus	agus	agus-C	Cc
aoibhneas	aoibhneas	aoibhneas-N	Ncmpg|Ncmsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
mo	mo	mo-D	Dp1-s
chroí	chroí	croí-N	Ncmsc
.	.	.-F	Fe
Sheas	Sheas	seas-V	Vmis
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
ceapóg	ceapóg	ceapóg-N	Ncfsc
de	de	de-S	Sp
bhláthanna	bhláthanna	bláth-N	Ncmpc
deasa	deasa	deas-A	Aq--pc
corcra	corcra	corcra-A	Aqp
,	,	,-F	Fi
bláthanna	bláthanna	bláth-N	Ncmpc
nach	nach	nach-Q	Qnrs
bhfaca	bhfaca	feic-V	Vmis---d
mé	mé	mé-P	Pp1-s
riamh	riamh	riamh-R	Rg
roimhe	roimhe	roimh-P	Pr3ms
sin	sin	sin-P	Pd
.	.	.-F	Fe
Bhreathnaigh	Bhreathnaigh	breathnaigh-V	Vmis
mé	mé	mé-P	Pp1-s
timpeall	timpeall	timpeall-R	Rd|Ncmsc
.	.	.-F	Fe
Beagnach	Beagnach	beagnach-R	Rg
i	i	i-S	Sp
ngan fhios	ngan fhios	gan_fhios-N	Ncmsc
shín	shín	sín-N	Ncfsc
mé	mé	mé-P	Pp1-s
mo	mo	mo-D	Dp1-s
lámh	lámh	lámh-N	Ncfsc
amach	amach	amach-R	Rd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
baint	baint	bain-N	Nv
lán	lán	lán-N	Ncmpg
mo	mo	mo-D	Dp1-s
shúl	shúl	súil-N	Ncfpg
as	as	as-S	Sp
an	an	an-T	Td-s
bhláth	bhláth	bláth-N	Ncmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
mé	mé	mé-P	Pp1-s
t	t	t-X	Xl
‑	‑	‑-F	Fb
aláram	aláram	aláram-N	Ncmsc
arís	arís	arís-R	Rg
.	.	.-F	Fe
Sheas	Sheas	seas-V	Vmis
mé	mé	mé-P	Pp1-s
ar feadh	ar feadh	ar_feadh-S	Spc
soicind	soicind	soicind-N	Ncmsg
agus	agus	agus-C	Cc
mé	mé	mé-P	Pp1-s
idir	idir	idir-S	Sp
dhá	dhá	dó-M	Mc
chomhairle	chomhairle	comhairle-N	Ncfsc
.	.	.-F	Fe
Bhreathnaigh	Bhreathnaigh	breathnaigh-V	Vmis
mé	mé	mé-P	Pp1-s
ar	ar	ar-S	Sp
an	an	an-T	Td-s
ghairdín	ghairdín	gairdín-N	Ncmsg
aoibhinn	aoibhinn	aoibhinn-A	Aq-msg
timpeall	timpeall	timpeall-S	Sp|Rd
orm	orm	ar-P	Pr1-s
uair	uair	uair-N	Ncfsc
amháin	amháin	amháin-A	Aqp
eile	eile	eile-D	Dd
.	.	.-F	Fe
Thiontaigh	Thiontaigh	tiontaigh-V	Vmis
mé	mé	mé-P	Pp1-s
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
mo	mo	mo-D	Dp1-s
sháil	sháil	sáil-N	Ncfsc
agus	agus	agus-C	Cc
rith	rith	rith-V	Vmis
mé	mé	mé-P	Pp1-s
suas	suas	suas-R	Rd
an	an	an-T	Td-s
cosán	cosán	cosán-N	Ncmsc
ar ais	ar ais	ar_ais-R	Rd
i	i	i-S	Sp
dtreo	dtreo	treo-N	Ncmsc
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
mhúscail	mhúscail	múscail-V	Vmis
mé	mé	mé-P	Pp1-s
ar	ar	ar-S	Sp
maidin	maidin	maidin-N	Ncfsc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
tásc	tásc	tásc-N	Ncmsc
ná	ná	ná-C	Cs|Cc
tuairisc	tuairisc	tuairisc-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
ghairdín	ghairdín	gairdín-N	Ncmsg
álainn	álainn	álainn-A	Aq-msg|Aq-msc|Aq-msv
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
mé	mé	mé-P	Pp1-s
faoi	faoi	faoi-S	Sp
sholas	sholas	solas-N	Ncmsc
na	na	na-T	Tdfsg
gealaí	gealaí	gealach-N	Ncfsg
.	.	.-F	Fe
Go	Go	go-S	Sp
dtí	dtí	tí-N	Ncmsc|Ncfsc
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
atá	atá	bí-V	Vmip---r
inniu	inniu	inniu-R	Rt
ann	ann	i-P	Pr3ms
níor	níor	níor-W	Ws-in|Qn-s
inis	inis	inis-V	Vmis|Vmis---n|Npmsc|Ncfsc|Npmsc|Vmis|Vmis---n
mé	mé	mé-P	Pp1-s
do	do	do-S	Sp
dhuine	dhuine	duine-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
beo	beo	beo-A	Aqp
faoi	faoi	faoi-P	Pr3ms
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
tá	tá	bí-V	Vmip
bláth	bláth	bláth-N	Ncmsc
álainn	álainn	álainn-A	Aq-msc
corcra	corcra	corcra-A	Aqp
agam	agam	ag-P	Pr1-s
go	go	go-U	Ua
fóill	fóill	fóill-A	Aqp
,	,	,-F	Fi
bláth	bláth	bláth-N	Ncmsc
nach	nach	nach-Q	Qnrs
bhfaca	bhfaca	feic-V	Vmis---d
mé	mé	mé-P	Pp1-s
a	a	a-D	Dp3
leithéid	leithéid	leithéid-N	Ncfsc
riamh	riamh	riamh-R	Rg
ó	ó	ó-S	Sp
shin	shin	sin-P	Pd
.	.	.-F	Fe
