Dhúisigh	Dhúisigh	dúisigh-V	Vmis
mé	mé	mé-P	Pp1-s
de	de	de-S	Sp
gheit	gheit	geit-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
mothú	mothú	mothú-N	Ncmsc
aisteach	aisteach	aisteach-A	Aq-msc
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
bholg	bholg	bolg-V	Vmis
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
feadh	feadh	feadh-N	Ncmsc
trí	trí	trí-M	Mc
shoicind	shoicind	soicind-N	Ncmsc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
cén	cén	cé-D	Dw--s
fáth	fáth	fáth-N	Ncmsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
chuimhnigh	chuimhnigh	cuimhnigh-V	Vmis
mé	mé	mé-P	Pp1-s
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Inniu	Inniu	inniu-R	Rt
an	an	an-T	Td-s
Aoine	Aoine	Aoine-N	Ncfsc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
gach	gach	gach-D	Dq
Aoine	Aoine	Aoine-N	Ncfsc
bíonn	bíonn	bí-V	Vmig
teist	teist	teist-N	Ncfsc
litrithe	litrithe	litrigh-A	Av
againn	againn	ag-P	Pr1-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	ó-S	Sp
bhó	bhó	bó-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
mé	mé	mé-P	Pp1-s
liom	liom	le-P	Pr1-s
féin	féin	féin-P	Px
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
cúis	cúis	cúis-N	Ncfsc
agam	agam	ag-P	Pr1-s
lena	lena	le-S	Spp-s
rá	rá	abair-N	Nv
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
go	go	go-U	Ua
maith	maith	maith-A	Aqp
chuig	chuig	chuig-S	Sp
go leor	go leor	go_leor-N	Ns-s
rudaí	rudaí	rud-N	Ncmpg
ar	ar	ar-S	Sp
scoil	scoil	scoil-N	Ncfsc
ach	ach	ach-C	Cs
níl	níl	bí-V	Vmip---n
mé	mé	mé-P	Pp1-s
in ann	in ann	in_ann-S	Spc
litriú	litriú	litrigh-N	Nv
.	.	.-F	Fe
Ceapaim	Ceapaim	ceap-V	Vmip1s
gur	gur	is-W	Wsdi
i	i	i-S	Sp
Rang	Rang	rang-N	Ncmsc
a	a	a-U	Um
Dó	Dó	dó-M	Mc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
fuair	fuair	faigh-V	Vmis
mé	mé	mé-P	Pp1-s
amach	amach	amach-R	Rd
ar	ar	ar-S	Sp
dtús	dtús	tús-N	Ncmsc
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
mé	mé	mé-P	Pp1-s
in ann	in ann	in_ann-S	Spc
litriú	litriú	litrigh-N	Nv
.	.	.-F	Fe
Níl	Níl	bí-V	Vmip---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
cén	cén	cé-D	Dw--s
fáth	fáth	fáth-N	Ncmsc
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
é	é	é-P	Pp3ms
roimhe	roimhe	roimh-P	Pr3ms
sin	sin	sin-P	Pd
.	.	.-F	Fe
B	B	B-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
mé	mé	mé-P	Pp1-s
go	go	go-U	Ua
maith	maith	maith-A	Aqp
chuige	chuige	chuige-R	Rg
uair	uair	uair-N	Ncfsc
amháin	amháin	amháin-A	Aqp
ach	ach	ach-C	Cs
ansin	ansin	ansin-R	Rt|Rl
,	,	,-F	Fi
go	go	go-U	Ua
tobann	tobann	tobann-A	Aqp
,	,	,-F	Fi
go	go	go-Q	Q
ndeachaigh	ndeachaigh	téigh-V	Vmis---d
mé	mé	mé-P	Pp1-s
in	in	i-S	Sp
olcas	olcas	olcas-N	Ncmsc
.	.	.-F	Fe
Nó	Nó	nó-C	Cc
b	b	b-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
mé	mé	mé-P	Pp1-s
in ann	in ann	in_ann-S	Spc
litriú	litriú	litrigh-N	Nv
riamh	riamh	riamh-R	Rg
ach	ach	ach-C	Cs
nár	nár	is-W	Wsrin
tugadh	tugadh	tabhair-V	Vmis0
faoi	faoi	faoi-S	Sp
deara	deara	deara-N	Ns-s
é	é	é-P	Pp3ms
.	.	.-F	Fe
Mar	Mar	mar-C	Cs
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
mé	mé	mé-P	Pp1-s
,	,	,-F	Fi
níl	níl	bí-V	Vmip---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
faoin	faoin	faoi-S	Spa-s
am	am	am-N	Ncmsc
seo	seo	seo-D	Dd
tá	tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
cinnte	cinnte	cinn-A	Av
de	de	de-S	Sp
rud	rud	rud-N	Ncmsc
amháin	amháin	amháin-A	Aqp
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
deich	deich	deich-M	Mc
mbliana	mbliana	bliain-N	Ncfpc
d	d	d-X	Xl
’	’	’-F	Fa
aois	aois	aois-N	Ncfsc
,	,	,-F	Fi
mé	mé	mé-P	Pp1-s
i	i	i-S	Sp
Rang	Rang	rang-N	Ncmsc
a	a	a-U	Um
Ceathair	Ceathair	ceathair-M	Mc
agus	agus	agus-C	Cc
níl	níl	bí-V	Vmip---n
tuairim	tuairim	tuairim-N	Ncfsc
na	na	na-T	Td-p
ngrást	ngrást	grásta-N	Ncmpg
agam	agam	ag-P	Pr1-s
cén	cén	cé-W	W--q
chaoi	chaoi	caoi-N	Ncfsg|Ncfsc
le	le	le-S	Sp
litriú	litriú	litrigh-N	Nv
.	.	.-F	Fe
Fiche	Fiche	fiche-N	Ncmsc|Mc
focal	focal	focal-N	Ncmpg|Ncmsc
a	a	a-Q	Q-r
bhíonn	bhíonn	bí-V	Vmig
le	le	le-S	Sp
foghlaim	foghlaim	foghlaim-N	Nv
againn	againn	ag-P	Pr1-p
gach	gach	gach-D	Dq
seachtain	seachtain	seachtain-N	Ncfsc
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
an	an	an-T	Td-s
Luan	Luan	Luan-N	Ncmsc
a	a	a-Q	Q-r
thugann	thugann	tabhair-V	Vmip
an	an	an-T	Td-s
Mháistreás	Mháistreás	máistreás-N	Ncfsc
na	na	na-T	Td-p
focail	focail	focal-N	Ncmpc
dúinn	dúinn	do-P	Pr1-p
.	.	.-F	Fe
An	An	an-T	Td-s
tseachtain	tseachtain	seachtain-N	Ncfsc
seo	seo	seo-D	Dd
,	,	,-F	Fi
ar nós	ar nós	ar_nós-S	Spc
gach	gach	gach-D	Dq
uile	uile	uile-N	Ns-s|Dq
sheachtain	sheachtain	seachtain-N	Ncfsc
,	,	,-F	Fi
rinne	rinne	déan-V	Vmis
mé	mé	mé-P	Pp1-s
an-iarracht	an-iarracht	iarracht-N	Ncfsc
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
iad	iad	iad-P	Pp3-p
a	a	a-U	U
fhoghlaim	fhoghlaim	foghlaim-N	Nv
.	.	.-F	Fe
Oíche	Oíche	oíche-N	Ncfsc
Dé	Dé	Dé-N	Ns-s
Luain	Luain	Luan-N	Ncmsg
,	,	,-F	Fi
d	d	d-X	Xl
’	’	’-F	Fa
fhoghlaim	fhoghlaim	foghlaim-V	Vmis
mé	mé	mé-P	Pp1-s
trí	trí	trí-M	Mc
cinn	cinn	ceann-N	Ncmpc
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Oíche	Oíche	oíche-N	Ncfsc
Dé	Dé	Dé-N	Ns-s
Máirt	Máirt	Máirt-N	Ncmsg|Ncfsg
,	,	,-F	Fi
d	d	d-X	Xl
’	’	’-F	Fa
fhoghlaim	fhoghlaim	foghlaim-V	Vmis
mé	mé	mé-P	Pp1-s
trí	trí	trí-M	Mc
cinn	cinn	ceann-N	Ncmpc
eile	eile	eile-D	Dd
.	.	.-F	Fe
Oíche	Oíche	oíche-N	Ncfsc
Dé	Dé	Dé-N	Ns-s
Céadaoin	Céadaoin	Céadaoin-N	Ncfsg
,	,	,-F	Fi
thuig	thuig	tuig-V	Vmis
mé	mé	mé-P	Pp1-s
go	go	go-U	Ua
maith	maith	maith-A	Aqp
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
seans	seans	seans-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
ann	ann	i-P	Pr3ms
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
fiche	fiche	fiche-N	Ncmsc|Mc
focal	focal	focal-N	Ncmpg|Ncmsc
foghlamtha	foghlamtha	foghlaim-A	Av
agam	agam	ag-P	Pr1-s
roimh	roimh	roimh-S	Sp
theist	theist	teist-N	Ncfsc
litrithe	litrithe	litrigh-A	Av
na	na	na-T	Tdfsg
hAoine	hAoine	Aoine-N	Ncfsg
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
anuas	anuas	anuas-R	Rd
air	air	ar-P	Pr3ms
sin	sin	sin-P	Pd
,	,	,-F	Fi
de bharr	de bharr	de_bharr-S	Spc
na	na	na-T	Tdfsg
dtrí	dtrí	trí-M	Mc
fhocal	fhocal	focal-N	Ncmsc
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhoghlaim	fhoghlaim	foghlaim-V	Vmis
mé	mé	mé-P	Pp1-s
oíche	oíche	oíche-N	Ncfsc
Dé	Dé	Dé-N	Ns-s
Luain	Luain	Luan-N	Ncmsg
a	a	a-U	U
bheith	bheith	bí-N	Nv
dearmadta	dearmadta	dearmad-A	Av
agam	agam	ag-P	Pr1-s
cheana	cheana	cheana-R	Rg
féin	féin	féin-P	Px
,	,	,-F	Fi
b	b	b-X	Xl
’	’	’-F	Fa
éigean	éigean	éigean-N	Ncmsc
dom	dom	do-P	Pr1-s
iad	iad	iad-P	Pp3-p
a	a	a-U	U
fhoghlaim	fhoghlaim	foghlaim-N	Nv
arís	arís	arís-R	Rg
.	.	.-F	Fe
Obair	Obair	obair-N	Ncfsc
in	in	i-S	Sp
aisce	aisce	aisce-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
fhocal	fhocal	focal-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
foghlamtha	foghlamtha	foghlaim-A	Av
agam	agam	ag-P	Pr1-s
oíche	oíche	oíche-N	Ncfsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
imithe	imithe	imigh-A	Av
glan	glan	glan-A	Aqp
amach	amach	amach-R	Rd
as	as	as-P	Pr3ms
mo	mo	mo-D	Dp1-s
cheann	cheann	ceann-N	Ncmsc
an	an	an-T	Td-s
oíche	oíche	oíche-N	Ncfsg
dár	dár	do-S	Spp-p
gcionn	gcionn	ceann-N	Ncfsd
.	.	.-F	Fe
Rinne	Rinne	déan-V	Vmis
mé	mé	mé-P	Pp1-s
mo	mo	mo-D	Dp1-s
sheacht	sheacht	seacht-M	Mc
míle	míle	míle-M	Mc
dícheall	dícheall	dícheall-N	Ncmsc
.	.	.-F	Fe
Bhreathnaigh	Bhreathnaigh	breathnaigh-V	Vmis
mé	mé	mé-P	Pp1-s
go	go	go-U	Ua
grinn	grinn	grinn-A	Aqp
ar	ar	ar-S	Sp
gach	gach	gach-D	Dq
focal	focal	focal-N	Ncmsc
,	,	,-F	Fi
litrigh	litrigh	litrigh-V	Vmis
mé	mé	mé-P	Pp1-s
amach	amach	amach-R	Rd
os	os	os-S	Sp
ard	ard	ard-N	Ncmsc
iad	iad	iad-P	Pp3-p
,	,	,-F	Fi
scríobh	scríobh	scríobh-V	Vmis
mé	mé	mé-P	Pp1-s
síos	síos	síos-R	Rd
deich	deich	deich-M	Mc
n-uaire	n-uaire	uair-N	Ncfsg
iad	iad	iad-P	Pp3-p
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
mé	mé	mé-P	Pp1-s
,	,	,-F	Fi
obair	obair	obair-N	Ncfsc|Nv-----n
in	in	i-S	Sp
aisce	aisce	aisce-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
ag	ag	ag-S	Sp
teip	teip	teip-N	Nv
orm	orm	ar-P	Pr1-s
iad	iad	iad-P	Pp3-p
a	a	a-U	U
fhoghlaim	fhoghlaim	foghlaim-N	Nv
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
gá	gá	gá-N	Ncmsc
a	a	a-U	U
rá	rá	abair-N	Nv
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
mé	mé	mé-P	Pp1-s
an-trína	an-trína	an-trín-N	Ncfpc
chéile	chéile	céile-N	Ncmsg
.	.	.-F	Fe
Chonacthas	Chonacthas	feic-V	Vmis0
domsa	domsa	do-P	Pr1-s-e
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
ann	ann	i-P	Pr3ms
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
t-aon	t-aon	aon-M	Mc
bhealach	bhealach	bealach-N	Ncmsc
amháin	amháin	amháin-A	Aqp
le	le	le-S	Sp
focal	focal	focal-N	Ncmsc
a	a	a-U	U
litriú	litriú	litrigh-N	Nv
.	.	.-F	Fe
An	An	an-T	Td-s
focal	focal	focal-N	Ncmsc
‘	‘	‘-X	Xx
ainmhí	ainmhí	ainmhí-N	Ncmsc
’	’	’-F	Fa
mar	mar	mar-S	Sp
shampla	shampla	sampla-N	Ncmsc
.	.	.-F	Fe
Ann	Ann	ann-R	Rl
,	,	,-F	Fi
ainm	ainm	ainm-N	Ncmsc
cailín	cailín	cailín-N	Ncmsg|Ncmsc
,	,	,-F	Fi
a	a	a-D	Dp3
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
ansin	ansin	ansin-R	Rt|Rl
bhí	bhí	bí-V	Vmis
;	;	;-F	Fi
Annabhí	Annabhí	bí-N	Ncfsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
de réir	de réir	de_réir-C	Cs|Spc
cosúlachta	cosúlachta	cosúlacht-N	Ncfsg
,	,	,-F	Fi
tá	tá	bí-V	Vmip
dul	dul	dul-N	Ncmsc
amú	amú	amaigh-R	Rg|Nv
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
de réir	de réir	de_réir-C	Cs|Spc
cosúlachta	cosúlachta	cosúlacht-N	Ncfsg
,	,	,-F	Fi
tá	tá	bí-V	Vmip
dul	dul	dul-N	Ncmsc
amú	amú	amaigh-R	Rg|Nv
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
Dar	Dar	dar-V	Vmip
le	le	le-S	Sp
gach	gach	gach-D	Dq
duine	duine	duine-N	Ncmsc
eile	eile	eile-D	Dd
,	,	,-F	Fi
ní	ní	nigh-W	Wp-in|Nv|Ncmsc|Nv
bealach	bealach	bealach-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
é	é	é-P	Pp3ms
sin	sin	sin-P	Pd|W
le	le	le-S	Sp
focal	focal	focal-N	Ncmsc
a	a	a-U	U
litriú	litriú	litrigh-N	Nv
.	.	.-F	Fe
Maidin	Maidin	maidin-N	Ncfsc
Dé	Dé	Dé-N	Ns-s
hAoine	hAoine	Aoine-N	Ncfsg
!	!	!-F	Fe
A	A	an-T	Td-s
thiarcais	thiarcais	tiarcais-N	Ns-s
!	!	!-F	Fe
Agus	Agus	agus-C	Cc
gan	gan	gan-S	Sp
ach	ach	ach-C	Cs
sé	sé	is-W	Wp-i-3
fhocal	fhocal	focal-N	Ncmsc
foghlamtha	foghlamtha	foghlaim-A	Av
agam	agam	ag-P	Pr1-s
as	as	as-S	Sp
an	an	an-T	Td-s
scór	scór	scór-N	Ncmsc
focal	focal	focal-N	Ncmpg
a	a	a-Q	Q-r
tugadh	tugadh	tabhair-V	Vmis0
dúinn	dúinn	do-P	Pr1-p
.	.	.-F	Fe
Maróidh	Maróidh	maraigh-V	Vmif
an	an	an-T	Td-s
Mháistreás	Mháistreás	máistreás-N	Ncfsc
mé	mé	mé-P	Pp1-s
!	!	!-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
shiúil	shiúil	siúil-V	Vmis
mé	mé	mé-P	Pp1-s
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
gclós	gclós	clós-N	Ncmsc
na	na	na-T	Tdfsg
scoile	scoile	scoil-N	Ncfsg
,	,	,-F	Fi
cé	cé	cé-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
ann	ann	i-R	Rl|Pr3ms
romham	romham	roimh-P	Pr1-s
ach	ach	ach-S	Sp|Cs
mo	mo	mo-D	Dp1-s
chara	chara	cara-N	Ncmsc
Sadhbh	Sadhbh	Sadhbh-N	Npf-g|Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	an-T	Td-s
Nuala	Nuala	Nuala-N	Npfsc
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
‘	‘	‘-X	Xx
Fan	Fan	fan-V	Vmm-2s
go	go	go-Q	Q-s
bhfeice	bhfeice	feic-V	Vmsp
tú	tú	tú-P	Pp2-s
an	an	an-T	Td-s
iris	iris	iris-N	Ncfsc
nua	nua	nua-A	Aqp
atá	atá	bí-V	Vmip---r
agam	agam	ag-P	Pr1-s
faoi	faoi	faoi-S	Sp
chapaill	chapaill	capall-N	Ncmpc
.	.	.-F	Fe
Taispeánfaidh	Taispeánfaidh	taispeáin-V	Vmif
mé	mé	mé-P	Pp1-s
duit	duit	do-P	Pr2-s
í	í	í-P	Pp3fs
sula	sula	sula-C	Cs
mbuailfear	mbuailfear	buail-V	Vmif0
clog	clog	clog-X	Xfev
.	.	.-F	Fe
’	’	’-F	Fa
Stop	Stop	stop-V	Vmis
sí	sí	sí-P	Pp3fsn
ansin	ansin	ansin-R	Rt|Rl
agus	agus	agus-C	Cc
bhreathnaigh	bhreathnaigh	breathnaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
atá	atá	bí-V	Vmip---r
ort	ort	ar-P	Pr2-s
?	?	?-F	Fq
!	!	!-F	Fe
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	ó-C	Cs
ná	ná	ná-Q	Qnm
habair	habair	abair-V	Vmm-2s-n
liom	liom	le-P	Pr1-s
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
imní	imní	imní-N	Ncfsc
ort	ort	ar-P	Pr2-s
mar	mar	mar-S	Sp
gheall	gheall	geall-N	Ncmsc
ar	ar	ar-S	Sp
theist	theist	teist-N	Ncfsc
bheag	bheag	beag-A	Aq-fsc
litrithe	litrithe	litrigh-A	Av
!	!	!-F	Fe
’	’	’-F	Fa
Sin	Sin	sin-W	W
í	í	í-P	Pp3fs
Sadhbh	Sadhbh	Sadhbh-N	Npfsc
agat	agat	ag-P	Pr2-s
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
aici	aici	ag-P	Pr3fs
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bpointe	bpointe	pointe-N	Ncmsc
boise	boise	bos-N	Ncfsg
má	má	má-C	Cs
bhíonn	bhíonn	bí-V	Vmig
rud	rud	rud-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
as	as	as-N	Ncmpg|Ncmsc|Pr3ms|Sp
dom	dom	do-P	Pr1-s
.	.	.-F	Fe
Uaireanta	Uaireanta	uaireanta-N	Ncfpc|Rg
ceapaim	ceapaim	ceap-V	Vmip1s
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
sí	sí	sí-P	Pp3fsn
níos	níos	níos-U	Uc
fearr	fearr	maith-A	Aqc
ná	ná	ná-C	Cc
mo	mo	mo-D	Dp1-s
thuismitheoirí	thuismitheoirí	tuismitheoir-N	Ncmpc
fiú	fiú	fiú-N	Ncmsg|Ncmsc|Rg|Ns-s
.	.	.-F	Fe
Le	Le	le-S	Sp
tamall	tamall	tamall-N	Ncmsc
anuas	anuas	anuas-R	Rd
is	is	is-U	U
fearr	fearr	maith-A	Aqc
a	a	a-Q	Q-r
thuigeann	thuigeann	tuig-V	Vmip
Sadhbh	Sadhbh	Sadhbh-N	Npfsc
mé	mé	mé-P	Pp1-s
ná	ná	ná-C	Cc
iadsan	iadsan	iad-P	Pp3-p-e
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
mise	mise	mé-P	Pp1-s-e
agus	agus	agus-C	Cc
Sadhbh	Sadhbh	Sadhbh-N	Npfsc
mór	mór	mór-A	Aqp
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
ó	ó	ó-C	Cs
bhíomar	bhíomar	bí-V	Vmis1p
sna	sna	i-S	Spa-p
Naíonáin	Naíonáin	Naíonáin-N	Npmsc
Mhóra	Mhóra	mór-A	Aq--pc
.	.	.-F	Fe
Is	Is	agus-C	Cc
maith	maith	maith-V	Vmm-2s
is	is	agus-C	Cc
cuimhin	cuimhin	cuimhin-N	Ns-s
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
chéad	chéad	céad-M	Mo
uair	uair	uair-N	Ncfsc
a	a	a-Q	Q-r
chuireamar	chuireamar	cuir-V	Vmis1p
aithne	aithne	aithne-N	Ncfsc
cheart	cheart	ceart-A	Aq-fsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Sciob	Sciob	sciob-V	Vmis|Vmm-2s
Brian	Brian	Brian-N	Ncmsc|Npmsc
Ó	Ó	Ó-U	Up
Tuathail	Tuathail	Tuathail-N	Npmsc
an	an	an-T	Td-s
crián	crián	crián-N	Ncmsc
gorm	gorm	gorm-A	Aq-msc
uaim	uaim	ó-P	Pr1-s
agus	agus	agus-C	Cc
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
dathú	dathú	dathaigh-N	Nv
pictiúir	pictiúir	pictiúr-N	Ncmsg
de	de	de-S	Sp
mhaighdean	mhaighdean	maighdean-N	Ncfsc
mhara	mhara	muir-N	Ncfsg|Ncfpg
.	.	.-F	Fe
Bhain	Bhain	bain-N	Npmsc
Sadhbh	Sadhbh	Sadhbh-N	Npf-g|Npfsc
scealpóg	scealpóg	scealpóg-N	Ncfsc
aisteach	aisteach	aisteach-A	Aq-fsc
as	as	as-P	Pr3ms
a	a	a-Q	Q-r
chuir	chuir	cuir-V	Vmis
ag	ag	ag-S	Sp
caoineadh	caoineadh	caoin-N	Nv
é	é	é-P	Pp3ms
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
mó	mó	mó-A	Aqc|Aqp
ná	ná	ná-C	Cs|Cc
sásta	sásta	sásta-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
Mháistreás	Mháistreás	máistreás-N	Ncfsc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
tá	tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
Sadhbh	Sadhbh	Sadhbh-N	Npfsc
an-mhór	an-mhór	mór-A	Aqp
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
riamh	riamh	riamh-R	Rg
ó	ó	ó-S	Sp
shin	shin	sin-P	Pd
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
Sadhbh	Sadhbh	Sadhbh-N	Npfsc
an-chliste	an-chliste	cliste-A	Aqp
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
.	.	.-F	Fe
Níl	Níl	bí-V	Vmip---n
caill	caill	caill-N	Ncfsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
orm	orm	ar-P	Pr1-s
féin	féin	féin-P	Px
ag	ag	ag-S	Sp
an	an	an-T	Td-s
matamaitic	matamaitic	matamaitic-N	Ncfsc
ach	ach	ach-C	Cs
tá	tá	bí-V	Vmip
Sadhbh	Sadhbh	Sadhbh-N	Npfsc
thar	thar	thar-S	Sp
barr	barr	barr-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
sí	sí	sí-P	Pp3fsn
an-mhaith	an-mhaith	maith-A	Aqp
ag	ag	ag-S	Sp
léamh	léamh	léigh-N	Nv
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
scríobh	scríobh	scríobh-N	Nv
freisin	freisin	freisin-R	Rg
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
thar	thar	thar-S	Sp
aon	aon	aon-D	Dq
ní	ní	ní-N	Ncmsc
eile	eile	eile-D	Dd
,	,	,-F	Fi
tá	tá	bí-V	Vmip
sí	sí	sí-P	Pp3fsn
go	go	go-U	Ua
hiontach	hiontach	iontach-A	Aqp
ag	ag	ag-S	Sp
an	an	an-T	Td-s
litriú	litriú	litriú-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
hainm	hainm	ainm-N	Ncmsc
i	i	i-S	Sp
Leabhar	Leabhar	leabhar-N	Ncmsc
na	na	na-T	Td-p
Réaltaí	Réaltaí	réalta-N	Ncfpg
cúpla	cúpla	cúpla-N	Ncmsg|Ncmsc|Dq
uair	uair	uair-N	Ncfsc
cheana	cheana	cion-R	Rg|Ncmsg
féin	féin	féin-P	Px
mar	mar	mar-S	Sp
gheall	gheall	geall-N	Ncmsc
ar	ar	ar-S	Sp
na	na	na-T	Td-p
marcanna	marcanna	marc-N	Ncmpc
arda	arda	ard-A	Aq--pc|Aq--pv|Aq--pc|Aq--pg
a	a	a-Q	Q-r
bhain	bhain	bain-V	Vmis
sí	sí	sí-P	Pp3fsn
amach	amach	amach-R	Rd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
imní	imní	imní-N	Ncfsc
orm	orm	ar-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
mé	mé	mé-P	Pp1-s
léi	léi	le-P	Pr3fs
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
seo	seo	seo-D	Dd
.	.	.-F	Fe
‘	‘	‘-X	Xx
An-imní	An-imní	imní-N	Ncfsc
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
.	.	.-F	Fe
Níl	Níl	bí-V	Vmip---n
ach	ach	ach-C	Cs
sé	sé	is-W	Wp-i-3
fhocal	fhocal	focal-N	Ncmsc
as	as	as-S	Sp
fiche	fiche	fiche-N	Ncmsc
foghlamtha	foghlamtha	foghlaim-N	Nv--g
agam	agam	ag-P	Pr1-s
agus	agus	agus-C	Cc
is	is	is-W	Wpri
ar	ar	ar-S	Sp
éigean	éigean	éigean-N	Ncmsc
atá	atá	bí-V	Vmip---r
an	an	an-T	Td-s
méid	méid	méid-N	Ncmsc
sin	sin	sin-P	Pd
féin	féin	féin-P	Px
foghlamtha	foghlamtha	foghlaim-A	Aqp|Av
mar	mar	mar-C	Cs
ba	ba	is-W	Wsri
cheart	cheart	ceart-A	Aqp
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
gá	gá	gá-N	Ncmsc
duit	duit	do-P	Pr2-s
aon	aon	aon-D	Dq
imní	imní	imní-N	Ncfsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
ort	ort	ar-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Nuala	Nuala	Nuala-N	Npf-v
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
‘	‘	‘-X	Xx
Coinnigh	Coinnigh	Coinnigh-N	Npmsc
do	do	do-S	Sp
shúil	shúil	súil-N	Ncfsc
ormsa	ormsa	ar-P	Pr1-s-e
agus	agus	agus-C	Cc
beidh	beidh	bí-V	Vmif
tú	tú	tú-P	Pp2-s
ceart	ceart	ceart-A	Aqp
go leor	go leor	go_leor-A	Aq
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Maith	Maith	Maith-N	Npmsc
go leor	go leor	go_leor-A	Aq
,	,	,-F	Fi
a	a	a-U	Uv
pháistí	pháistí	páiste-N	Ncmpv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Mháistreás	Mháistreás	máistreás-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
in	in	i-S	Sp
am	am	am-N	Ncmsc
don	don	do-S	Spa-s
teist	teist	teist-N	Ncfsc
litrithe	litrithe	litrigh-A	Av
.	.	.-F	Fe
Tógaigí	Tógaigí	tóg-V	Vmm-2p
amach	amach	amach-R	Rd
bhur	bhur	bhur-D	Dp2-p
gcóipleabhair	gcóipleabhair	cóipleabhar-N	Ncmpc
agus	agus	agus-C	Cc
tosóimid	tosóimid	tosaigh-V	Vmif1p
.	.	.-F	Fe
’	’	’-F	Fa
Bhí	Bhí	bí-V	Vmis
uafás	uafás	uafás-N	Ncmsc
orm	orm	ar-P	Pr1-s
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
seo	seo	seo-P	Pd
níos	níos	níos-U	Uc
measa	measa	olc-A	Aqc
ná	ná	ná-C	Cs|Cc
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
súil	súil	súil-N	Nv-----n
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
De	De	de-S	Sp
ghnáth	ghnáth	gnáth-N	Ncmsc
,	,	,-F	Fi
thugadh	thugadh	tabhair-V	Vmih
sí	sí	sí-P	Pp3fsn
seans	seans	seans-N	Ncmsc
dúinn	dúinn	do-P	Pr1-p
breathnú	breathnú	breathnú-N	Ncmsc
ar	ar	ar-S	Sp
na	na	na-T	Td-p
focail	focail	focal-N	Ncmpc
roimh	roimh	roimh-S	Sp
ré	ré	ré-N	Ncfsc|Ncmsc
ar feadh	ar feadh	ar_feadh-S	Spc
dhá	dhá	dó-M	Mc
nóiméad	nóiméad	nóiméad-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
ardaigh	ardaigh	ardaigh-V	Vmm-2s
mé	mé	mé-P	Pp1-s
mo	mo	mo-D	Dp1-s
lámh	lámh	lámh-N	Ncfsc
go	go	go-U	Ua
faiteach	faiteach	faiteach-A	Aqp
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
mé	mé	mé-P	Pp1-s
di	di	do-P	Pr3fs
an	an	an-Q	Qq
bhféadfaimis	bhféadfaimis	féad-V	Vmc-1p
dhá	dhá	dó-M	Mc
nóiméad	nóiméad	nóiméad-N	Ncmsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
againn	againn	ag-P	Pr1-p
le	le	le-S	Sp
breathnú	breathnú	breathnaigh-N	Nv
ar	ar	ar-S	Sp
na	na	na-T	Td-p
focail	focail	focal-N	Ncmpc
arís	arís	arís-R	Rg
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
mó	mó	mó-A	Aqc|Aqp
ná	ná	ná-C	Cs|Cc
sásta	sásta	sásta-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
Mháistreás	Mháistreás	máistreás-N	Ncfsc
liom	liom	le-P	Pr1-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhí	Bhí	bí-V	Vmis
ceithre	ceithre	ceathair-M	Mc
lá	lá	lá-N	Ncmsc
agaibh	agaibh	ag-P	Pr2-p
,	,	,-F	Fi
a	a	a-U	Uv
Nuala	Nuala	Nuala-N	Npf-v
de	de	de-U	Up
Búrca	Búrca	Búrca-N	Npmsc
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
liom	liom	le-P	Pr1-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
ár	ár	ár-N	Ncmsc|Dp1-p
ndóthain	ndóthain	dóthain-N	Ncfsg|Ncfsc
ama	ama	ama-N	Ncmsg|Ncmsc
againn	againn	ag-P	Pr1-p
le	le	le-S	Sp
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
siar	siar	siar-R	Rd
ar	ar	ar-S	Sp
obair	obair	obair-N	Nv-----n
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ceaptha	ceaptha	ceap-A	Av
a	a	a-U	U
bheith	bheith	bí-N	Nv
déanta	déanta	déan-A	Av
sa	sa	i-S	Spa-s
bhaile	bhaile	baile-N	Ncmsc
.	.	.-F	Fe
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
sibh	sibh	sibh-P	Pp2-p
réidh	réidh	réidh-A	Aqp
?	?	?-F	Fq
!	!	!-F	Fe
Seo	Seo	seo-W	W
é	é	é-P	Pp3ms
an	an	an-T	Td-s
chéad	chéad	céad-M	Mo
fhocal	fhocal	focal-N	Ncmsc
.	.	.-F	Fe
Litrígí	Litrígí	litrigh-V	Vmm-2p
‘	‘	‘-X	Xx
ainmhí	ainmhí	ainmhí-N	Ncmsc
’	’	’-F	Fa
.	.	.-F	Fe
Faoin	Faoin	faoi-S	Spa-s
am	am	am-N	Ncmsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
tríú	tríú	trí-M	Mo
focal	focal	focal-N	Ncmsc
glaoite	glaoite	glaoigh-A	Av
ag	ag	ag-S	Sp
an	an	an-T	Td-s
Máistreás	Máistreás	máistreás-N	Ncfsc
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
fonn	fonn	fonn-N	Ncmsc
caointe	caointe	caoin-A	Av
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
oiread	oiread	oiread-N	Ns-s
agus	agus	agus-C	Cc
focal	focal	focal-N	Ncmpg|Ncmsc
amháin	amháin	amháin-A	Aqp
scríofa	scríofa	scríobh-A	Av
agamsa	agamsa	ag-P	Pr1-s-e
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
chóipleabhar	chóipleabhar	cóipleabhar-N	Ncmsc
ach	ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
dream	dream	dream-N	Ncmsc
eile	eile	eile-D	Dd
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
ag	ag	ag-S	Sp
scríobh	scríobh	scríobh-N	Nv
le	le	le-S	Sp
buille	buille	buille-N	Ncmsc
.	.	.-F	Fe
Faoin	Faoin	faoi-S	Spa-s
am	am	am-N	Ncmsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
seacht	seacht	seacht-M	Mc|Ncmsc
bhfocal	bhfocal	focal-N	Ncmsc|Ncmpg
léite	léite	léigh-A	Av
amach	amach	amach-R	Rd
ag	ag	ag-S	Sp
an	an	an-T	Td-s
Máistreás	Máistreás	máistreás-N	Ncfsc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ach	ach	ach-S	Sp
trí	trí	trí-M	Mc
cinn	cinn	ceann-N	Ncmpc
scríofa	scríofa	scríobh-A	Av
agamsa	agamsa	ag-P	Pr1-s-e
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
,	,	,-F	Fi
go	go	go-U	Ua
tobann	tobann	tobann-A	Aqp
,	,	,-F	Fi
thug	thug	tabhair-V	Vmis
duine	duine	duine-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
sonc	sonc	sonc-N	Ncmsg|Ncmsc
sa	sa	i-S	Spa-s
chos	chos	cos-N	Ncfsc
dom	dom	do-P	Pr1-s
.	.	.-F	Fe
Soicind	Soicind	soicind-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|Dd
tugadh	tugadh	tabhair-V	Vmis0
sonc	sonc	sonc-N	Ncmsc
eile	eile	eile-D	Dd
sa	sa	i-S	Spa-s
chos	chos	cos-N	Ncfsc
dom	dom	do-P	Pr1-s
,	,	,-F	Fi
agus	agus	agus-C	Cc
ceann	ceann	ceann-N	Ncmpg|Ncmsc
eile	eile	eile-D	Dd
ach	ach	ach-C	Cs
níos	níos	níos-U	Uc
láidre	láidre	láidir-A	Aqc
an	an	an-T	Td-s
uair	uair	uair-N	Ncfsc
seo	seo	seo-D	Dd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
mo	mo	mo-D	Dp1-s
rúitín	rúitín	rúitín-N	Ncmsc
ag	ag	ag-S	Sp
éirí	éirí	éirigh-N	Nv
tinn	tinn	tinn-A	Aqp
.	.	.-F	Fe
Chuimil	Chuimil	cuimil-V	Vmis
mé	mé	mé-P	Pp1-s
mo	mo	mo-D	Dp1-s
rúitín	rúitín	rúitín-N	Ncmsc
agus	agus	agus-C	Cc
bhreathnaigh	bhreathnaigh	breathnaigh-V	Vmis
mé	mé	mé-P	Pp1-s
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
thimpeall	thimpeall	timpeall-N	Ncmsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
ansin	ansin	ansin-R	Rt|Rl
a	a	a-Q	Q-r
thug	thug	tabhair-V	Vmis
mé	mé	mé-P	Pp1-s
faoi	faoi	faoi-S	Sp
deara	deara	deara-N	Ns-s
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
Sadhbh	Sadhbh	Sadhbh-N	Npfsc
ag	ag	ag-S	Sp
breathnú	breathnú	breathnaigh-N	Nv
orm	orm	ar-P	Pr1-s
agus	agus	agus-C	Cc
meangadh	meangadh	meang-V	Vmis0
mór	mór	mór-N	Ncmsc
millteach	millteach	millteach-A	Aq-msc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
faire	faire	fair-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
Máistreás	Máistreás	máistreás-N	Ncfsc
,	,	,-F	Fi
sháigh	sháigh	sáigh-V	Vmis
Sadhbh	Sadhbh	Sadhbh-N	Npfsc
píosa	píosa	píosa-N	Ncmsc
beag	beag	beag-A	Aq-msc
páipéir	páipéir	páipéar-N	Ncmsg
anall	anall	anall-R	Rd
chugam	chugam	chuig-P	Pr1-s
,	,	,-F	Fi
go	go	go-U	Ua
mall	mall	mall-A	Aqp
cúramach	cúramach	cúramach-A	Aqp
.	.	.-F	Fe
Céard	Céard	cé-W	W--q
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bpáipéar	bpáipéar	páipéar-N	Ncmsc
ach	ach	ach-C	Cs
…	…	…-F	Fi
na	na	na-T	Td-p
focail	focail	focal-N	Ncmpc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
glaoite	glaoite	glaoigh-A	Av
amach	amach	amach-R	Rd
ag	ag	ag-S	Sp
an	an	an-T	Td-s
Máistreás	Máistreás	máistreás-N	Ncfsc
go dtí	go dtí	go_dtí-S	Spc
seo	seo	seo-P	Pd
!	!	!-F	Fe
Agus	Agus	agus-C	Cc
ar	ar	ar-S	Sp
ndóigh	ndóigh	dóigh-N	Ncfsc
,	,	,-F	Fi
d	d	d-X	Xl
’	’	’-F	Fa
fhéadfá	fhéadfá	féad-V	Vmc-2s
a	a	a-U	U
bheith	bheith	bí-N	Nv
cinnte	cinnte	cinn-A	Av
de	de	de-P	Pr3ms
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
gach	gach	gach-D	Dq
aon	aon	aon-D	Dq
cheann	cheann	ceann-N	Ncmsc
acu	acu	ag-P	Pr3-p
litrithe	litrithe	litrí-N	Ncmpc
i	i	i-S	Sp
gceart	gceart	ceart-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
cad	cad	cad-W	W--q
chuige	chuige	chuig-P	Pr3ms
nach	nach	nach-Q	Qnr
mbeadh	mbeadh	bí-V	Vmc
nuair	nuair	nuair-C	Cs
ab	ab	is-W	Wsri
í	í	í-P	Pp3fs
Sadhbh	Sadhbh	Sadhbh-N	Npfsc
féin	féin	féin-P	Px
a	a	a-Q	Q-r
scríobh	scríobh	scríobh-V	Vmis
iad	iad	iad-P	Pp3-p
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
rud	rud	rud-N	Ncmsc
a	a	a-Q	Q-r
rinne	rinne	déan-V	Vmis
mé	mé	mé-P	Pp1-s
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|W|Dd
mícheart	mícheart	ceart-A	Aqp
.	.	.-F	Fe
Go	Go	go-U	Ua
deimhin	deimhin	deimhin-A	Aqp
féin	féin	féin-P	Px
,	,	,-F	Fi
nílim	nílim	bí-V	Vmip1s-n
bródúil	bródúil	bródúil-A	Aqp
as	as	as-P	Pr3ms
a	a	a-Q	Q-p
ndearna	ndearna	déan-V	Vmis---d
mé	mé	mé-P	Pp1-s
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
faoin	faoin	faoi-S	Spa-s
am	am	am-N	Ncmsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
teist	teist	teist-N	Ncfsc
thart	thart	thart-R	Rd
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
dhá	dhá	dó-M	Mc
cheann	cheann	ceann-N	Ncmsc
déag	déag	déag-N	Ns-s
de	de	de-S	Sp
na	na	na-T	Td-p
focail	focail	focal-N	Ncmpc
scríofa	scríofa	scríobh-A	Av
amach	amach	amach-R	Rd
agam	agam	ag-P	Pr1-s
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
chóipleabhar	chóipleabhar	cóipleabhar-N	Ncmsc
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
mé	mé	mé-P	Pp1-s
beagnach	beagnach	beagnach-R	Rg
cinnte	cinnte	cinn-A	Av
de	de	de-P	Pr3ms
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
siad	siad	siad-P	Pp3-pn
litrithe	litrithe	litrigh-A	Av
i	i	i-S	Sp
gceart	gceart	ceart-N	Ncmsc
.	.	.-F	Fe
Ag	Ag	ag-S	Sp
am	am	am-N	Ncmsc
spraoi	spraoi	spraoi-N	Nv--g--n|Ncmsg
,	,	,-F	Fi
b	b	b-X	Xl
’	’	’-F	Fa
fhada	fhada	fada-A	Aqc
liom	liom	le-P	Pr1-s
go	go	go-Q	Q
bhfaighinn	bhfaighinn	faigh-V	Vmc-1s-d|Vmih1s
deis	deis	deis-N	Ncfsc
labhairt	labhairt	labhair-N	Ncfsc|Nv
le	le	le-S	Sp
Sadhbh	Sadhbh	Sadhbh-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cén	Cén	cé-D	Dw--s
fáth	fáth	fáth-N	Ncmsc
a	a	a-Q	Q-i
ndearna	ndearna	déan-V	Vmis---d
tú	tú	tú-P	Pp2-s
é	é	é-P	Pp3ms
sin	sin	sin-P	Pd
?	?	?-F	Fq
!	!	!-F	Fe
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
mé	mé	mé-P	Pp1-s
léi	léi	le-P	Pr3fs
chomh	chomh	chomh-R	Ri
luath	luath	luath-A	Aqp
is	is	agus-C	Cc
a	a	a-Q	Q-i|Q-r
fuair	fuair	faigh-V	Vmis
mé	mé	mé-P	Pp1-s
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
í	í	í-P	Pp3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cén	Cén	cé-D	Dw--s
fáth	fáth	fáth-N	Ncmsc
ar	ar	ar-Q	Q-is
thug	thug	tabhair-V	Vmis
tú	tú	tú-P	Pp2-s
na	na	na-T	Td-p
focail	focail	focal-N	Ncmpc
úd	úd	úd-D	Dd
dom	dom	do-P	Pr1-s
?	?	?-F	Fq
!	!	!-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Muise	Muise	muise-X	Xsc
,	,	,-F	Fi
cén	cén	cé-W	W--q|Dw--s
sórt	sórt	sórt-N	Ncmsc
cantail	cantail	cantal-N	Ncmsg
atá	atá	bí-V	Vmip---r
ort	ort	ar-P	Pr2-s
?	?	?-F	Fq
!	!	!-F	Fe
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
Sadhbh	Sadhbh	Sadhbh-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cheapfá	Cheapfá	ceap-V	Vmc-2s
go	go	go-Q	Q
mbeifeá	mbeifeá	bí-V	Vmc-2s
buíoch	buíoch	buíoch-A	Aqp
díom	díom	de-P	Pr1-s
.	.	.-F	Fe
Nár	Nár	is-W	Ws-qn
gheall	gheall	geall-N	Ncmsc
mé	mé	mé-P	Pp1-s
ar	ar	ar-S	Sp
maidin	maidin	maidin-N	Ncfsc
duit	duit	do-P	Pr2-s
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
ghá	ghá	gá-N	Ncmsc
le	le	le-S	Sp
himní	himní	imní-N	Ncfsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
ort	ort	ar-P	Pr2-s
?	?	?-F	Fq
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
díomá	díomá	díomá-N	Ncfsc
orm	orm	ar-P	Pr1-s
nach	nach	nach-Q	Qnr
bhfuil	bhfuil	bí-V	Vmip---n
tú	tú	tú-P	Pp2-s
buíoch	buíoch	buíoch-A	Aqp
díom	díom	de-P	Pr1-s
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
hé	hé	é-P	Pp3ms
nach	nach	nach-Q	Qnr
bhfuil	bhfuil	bí-V	Vmip---n
mé	mé	mé-P	Pp1-s
buíoch	buíoch	buíoch-A	Aqp
díot	díot	de-P	Pr2-s
,	,	,-F	Fi
ach	ach	ach-C	Cs
is	is	is-W	Wpri
ag	ag	ag-S	Sp
cóipeáil	cóipeáil	cóipeáil-N	Nv
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
!	!	!-F	Fe
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
mise	mise	mé-P	Pp1-s-e
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
sin	sin	sin-P	Pd
mímhacánta	mímhacánta	mímhacánta-A	Aqp
,	,	,-F	Fi
a	a	a-U	Uv
Shadhbh	Shadhbh	Sadhbh-N	Npf-v
!	!	!-F	Fe
Is	Is	is-W	Wp-i
maith	maith	maith-A	Aqp
atá	atá	bí-V	Vmip---r
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agat	agat	ag-P	Pr2-s
é	é	é-P	Pp3ms
!	!	!-F	Fe
’	’	’-F	Fa
Rinneadh	Rinneadh	déan-V	Vmis0
staic	staic	staic-N	Ncfsc
de	de	de-S	Sp
Shadhbh	Shadhbh	Sadhbh-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
ach	ach	ach-C	Cs
.	.	.-F	Fe
.	.	.-F	Fe
.	.	.-F	Fe
is	is	is-W	Wp-i
tusa	tusa	tú-P	Pp2-s-e
mo	mo	mo-D	Dp1-s
chara	chara	cara-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
agus	agus	agus-C	Cc
crith	crith	crith-V	Vmm-2s
ina	ina	i-S	Spp-s
glór	glór	glór-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhí	Bhí	bí-V	Vmis
tú	tú	tú-P	Pp2-s
i	i	i-S	Sp
bponc	bponc	ponc-N	Ncmsc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
tagann	tagann	tar-V	Vmip
cairde	cairde	cairde-N	Ncmpc|Ncmsc
i	i	i-S	Sp
gcabhair	gcabhair	cabhar-N	Ncfsc|Ncmpc
ar	ar	ar-W	Wsdq|Ws-q|Wssi|Wpdi|Wpsi|Sp|Ncmsc
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
má	má	má-C	Cs
bhíonn	bhíonn	bí-V	Vmig
duine	duine	duine-N	Ncmsc
acu	acu	ag-P	Pr3-p
i	i	i-S	Sp
bponc	bponc	ponc-N	Ncmsc
,	,	,-F	Fi
nach	nach	nach-Q	Qnr
dtagann	dtagann	tar-V	Vmip
?	?	?-F	Fq
!	!	!-F	Fe
’	’	’-F	Fa
Go	Go	go-U	Ua
tobann	tobann	tobann-A	Aqp
bhraith	bhraith	braith-V	Vmis
mé	mé	mé-P	Pp1-s
go	go	go-Q	Q
rabhamar	rabhamar	bí-V	Vmis1p-d
sna	sna	i-S	Spa-p
Naíonáin	Naíonáin	Naíonáin-N	Npmsc
Mhóra	Mhóra	mór-A	Aq--pc
arís	arís	arís-R	Rg
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
Sadhbh	Sadhbh	Sadhbh-N	Npfsc
na	na	na-T	Td-p
focail	focail	focal-N	Ncmsg
sin	sin	sin-D	Dd
den	den	de-S	Spa-s
chéad	chéad	céad-M	Mo
uair	uair	uair-N	Ncfsc
.	.	.-F	Fe
Chuimhnigh	Chuimhnigh	cuimhnigh-V	Vmis
mé	mé	mé-P	Pp1-s
ar	ar	ar-S	Sp
Bhriain	Bhriain	Brian-N	Npfsg|Ncmsg
Ó	Ó	Ó-U	Up
Tuathail	Tuathail	Tuathail-N	Npmsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
crián	crián	crián-N	Ncmsc
gorm	gorm	gorm-A	Aq-msc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
chomh	chomh	chomh-R	Ri
dílis	dílis	dílis-A	Aqp
is	is	agus-C	Cc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Sadhbh	Sadhbh	Sadhbh-N	Npfsc
dom	dom	do-P	Pr1-s
an	an	an-T	Td-s
t-am	t-am	am-N	Ncmsc
sin	sin	sin-D	Dd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
sásta	sásta	sásta-A	Aqp
cuidiú	cuidiú	cuidigh-N	Ncmsc|Nv
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
,	,	,-F	Fi
beag	beag	beag-A	Aqp
beann	beann	beann-N	Ncfpg|Ncfsc
ar	ar	ar-S	Sp
aon	aon	aon-D	Dq
trioblóid	trioblóid	trioblóid-N	Ncfsc
a	a	a-Q	Q-r
tharraingeodh	tharraingeodh	tarraing-V	Vmc
sí	sí	sí-P	Pp3fsn
uirthi	uirthi	ar-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
,	,	,-F	Fi
rinne	rinne	déan-V	Vmis
mé	mé	mé-P	Pp1-s
suas	suas	suas-R	Rd
m	m	m-X	Xl
’	’	’-F	Fa
intinn	intinn	intinn-N	Ncfsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
í	í	í-P	Pp3fs
Sadhbh	Sadhbh	Sadhbh-N	Npfsc
an	an	an-T	Td-s
cara	cara	cara-N	Ncmsc
is	is	is-U	U
fearr	fearr	maith-A	Aqc
atá	atá	bí-V	Vmip---r
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
mé	mé	mé-P	Pp1-s
mo	mo	mo-D	Dp1-s
lámh	lámh	lámh-N	Ncfsc
timpeall	timpeall	timpeall-S	Sp|Rd
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
ceart	ceart	ceart-N	Ncmsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Shadhbh	Shadhbh	Sadhbh-N	Npf-v
.	.	.-F	Fe
Tagann	Tagann	tar-V	Vmip
cairde	cairde	cairde-N	Ncmpc|Ncmsc
i	i	i-S	Sp
gcabhair	gcabhair	cabhar-N	Ncfsc|Ncmpc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
mé	mé	mé-P	Pp1-s
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
dhá	dhá	dó-M	Mc
chroí	chroí	croí-N	Ncmsc
ag	ag	ag-S	Sp
Sadhbh	Sadhbh	Sadhbh-N	Npfsc
.	.	.-F	Fe
Faoin	Faoin	faoi-S	Spa-s
am	am	am-N	Ncmsc
ar	ar	ar-Q	Q-is
shroich	shroich	sroich-V	Vmis
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
baile	baile	baile-N	Ncmsc
tráthnóna	tráthnóna	tráthnóna-N	Ncmsg|Ncmsc
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
eachtraí	eachtraí	eachtraí-N	Ncfpc|Ncmsc
an	an	an-T	Td-s
lae	lae	lá-N	Ncmsg
dearmadta	dearmadta	dearmad-A	Av
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cén	Cén	cé-D	Dw--s
chaoi	chaoi	caoi-N	Ncfsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
teist	teist	teist-N	Ncfsc
litrithe	litrithe	litrigh-A	Av
inniu	inniu	inniu-R	Rt
?	?	?-F	Fq
!	!	!-F	Fe
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
Mam	Mam	mam-N	Ncfsc
,	,	,-F	Fi
tar éis	tar éis	tar_éis-S	Spc
an	an	an-T	Td-s
tae	tae	tae-N	Ncmsg
.	.	.-F	Fe
Bhain	Bhain	bain-V	Vmis
a	a	a-D	Dp3
ceist	ceist	ceist-N	Ncfsc
geit	geit	geit-N	Ncfsc
asam	asam	as-P	Pr1-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	ó-C	Cs
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
,	,	,-F	Fi
um	um	um-S	Sp
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
maith	maith	maith-A	Aqp
go leor	go leor	go_leor-A	Aq
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
mé	mé	mé-P	Pp1-s
féin	féin	féin-P	Px
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
tháinig	tháinig	tar-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
ar ais	ar ais	ar_ais-R	Rd
chugam	chugam	chuig-P	Pr1-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Maith	Maith	Maith-N	Npmsc
go leor	go leor	go_leor-A	Aq
a	a	a-Q	Q-r
deir	deir	abair-V	Vmip
tú	tú	tú-P	Pp2-s
?	?	?-F	Fq
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Deaide	Deaide	Deaide-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
De	De	de-S	Sp
ghnáth	ghnáth	gnáth-N	Ncmsc
deir	deir	abair-V	Vmip
tú	tú	tú-P	Pp2-s
go	go	go-Q	Q
mbíonn	mbíonn	bí-V	Vmig
sí	sí	sí-P	Pp3fsn
uafásach	uafásach	uafásach-A	Aqp
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Bhuel	Bhuel	bhuel-X	Xsc
.	.	.-F	Fe
.	.	.-F	Fe
.	.	.-F	Fe
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
mé	mé	mé-P	Pp1-s
,	,	,-F	Fi
agus	agus	agus-C	Cc
mo	mo	mo-D	Dp1-s
cheann	cheann	ceann-N	Ncmsc
fúm	fúm	faoi-P	Pr1-s
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
céard	céard	cé-W	W--q
a	a	a-Q	Q-r
déarfainn	déarfainn	abair-V	Vmc-1s
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhuel	Bhuel	bhuel-X	Xsc
,	,	,-F	Fi
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sí	sí	sí-P	Pp3fsn
chomh	chomh	chomh-R	Ri
dona	dona	dona-A	Aqp
sin	sin	sin-P	Pd|W|Dd
inniu	inniu	inniu-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
mé	mé	mé-P	Pp1-s
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an-fhonn	an-fhonn	fonn-N	Ncmsc
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
orm	orm	ar-P	Pr1-s
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
a	a	a-U	U
insint	insint	inis-N	Nv
do	do	do-D	Dp2-s|Sp
mo	mo	mo-D	Dp1-s
thuismitheoirí	thuismitheoirí	tuismitheoir-N	Ncmpc
.	.	.-F	Fe
An	An	an-T	Td-s
fhírinne	fhírinne	fírinne-N	Ncfsc
a	a	a-U	U
rá	rá	abair-N	Nv
amach	amach	amach-R	Rd
go	go	go-U	Ua
lom	lom	lom-A	Aqp
díreach	díreach	díreach-A	Aqp
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
róchasta	róchasta	casta-A	Aqp
mar	mar	mar-S	Sp
scéal	scéal	scéal-N	Ncmsc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
gach	gach	gach-D	Dq
seans	seans	seans-N	Ncmsc
ann	ann	i-P	Pr3ms
nach	nach	nach-Q	Qnr
dtuigfidís	dtuigfidís	tuig-V	Vmc-3p
mo	mo	mo-D	Dp1-s
chás	chás	cás-N	Ncmsc
ar	ar	ar-S	Sp
chor	chor	cor-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
.	.	.-F	Fe
Shocraigh	Shocraigh	socraigh-V	Vmis
mé	mé	mé-P	Pp1-s
go	go	go-Q	Q
bhfanfainn	bhfanfainn	fan-V	Vmc-1s
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
thost	thost	tost-V	Vmis
.	.	.-F	Fe
Le	Le	le-S	Sp
linn	linn	linn-N	Ncfsc
an	an	an-T	Td-s
deireadh	deireadh	deireadh-N	Ncmsc
seachtaine	seachtaine	seachtain-N	Ncfsg
rinne	rinne	déan-V	Vmis
mé	mé	mé-P	Pp1-s
gach	gach	gach-D	Dq
iarracht	iarracht	iarracht-N	Ncfsc
an	an	an-T	Td-s
scoil	scoil	scoil-N	Ncfsc
agus	agus	agus-C	Cc
gach	gach	gach-N	Ns-s
ar	ar	is-W	Wssi
bhain	bhain	bain-N	Npmsc
léi	léi	le-P	Pr3fs
a	a	a-U	U
chur	chur	cuir-N	Nv
as	as	as-P	Pr3ms
mo	mo	mo-D	Dp1-s
cheann	cheann	ceann-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
go	go	go-U	Ua
tobann	tobann	tobann-A	Aqp
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
maidin	maidin	maidin-N	Ncfsc
Dé	Dé	Dé-N	Ns-s
Luain	Luain	Luan-N	Ncmsg
buailte	buailte	buail-A	Av
linn	linn	le-P	Pr1-p
arís	arís	arís-R	Rg
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
fhonn	fhonn	fonn-N	Ncmsc
beo	beo	beo-A	Aqp
orm	orm	ar-P	Pr1-s
dul	dul	dul-N	Ncmsc
ar ais	ar ais	ar_ais-R	Rd
ar	ar	ar-S	Sp
scoil	scoil	scoil-N	Ncfsc
.	.	.-F	Fe
Inniu	Inniu	inniu-R	Rt
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
an	an	an-T	Td-s
Mháistreás	Mháistreás	máistreás-N	Ncfsc
ag	ag	ag-S	Sp
tabhairt	tabhairt	tabhair-N	Nv
amach	amach	amach-R	Rd
torthaí	torthaí	toradh-N	Ncmpc
na	na	na-T	Tdfsg
teiste	teiste	teist-N	Ncfsg
…	…	…-F	Fi
Bhí	Bhí	bí-V	Vmis
Sadhbh	Sadhbh	Sadhbh-N	Npfsc
romham	romham	roimh-P	Pr1-s
ag	ag	ag-S	Sp
geata	geata	geata-N	Ncmsc
na	na	na-T	Tdfsg
scoile	scoile	scoil-N	Ncfsg
agus	agus	agus-C	Cc
chonaic	chonaic	feic-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
mé	mé	mé-P	Pp1-s
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
chuma	chuma	cuma-N	Ncfsc
uirthi	uirthi	ar-P	Pr3fs
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
sona	sona	sona-A	Aqp
sásta	sásta	sásta-A	Aqp
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
cén	cén	cé-D	Dw--s
fáth	fáth	fáth-N	Ncmsc
nach	nach	nach-Q	Qnr
mbeadh	mbeadh	bí-V	Vmc
?	?	?-F	Fq
!	!	!-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
rud	rud	rud-N	Ncmsc
ar nós	ar nós	ar_nós-S	Spc
torthaí	torthaí	toradh-N	Ncmpg
teiste	teiste	teist-N	Ncfsg
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
as	as	as-N	Ncmpg|Ncmsc|Pr3ms|Sp
dise	dise	do-P	Pr3fs-e
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuaigh	chuaigh	téigh-V	Vmis
mé	mé	mé-P	Pp1-s
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
seomra	seomra	seomra-N	Ncmsc
ranga	ranga	rang-N	Ncmsg
chonaic	chonaic	feic-V	Vmis
mé	mé	mé-P	Pp1-s
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
mo	mo	mo-D	Dp1-s
chóipleabhar	chóipleabhar	cóipleabhar-N	Ncmsc
leagtha	leagtha	leag-A	Av
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
mo	mo	mo-D	Dp1-s
dheasc	dheasc	deasc-V	Vmis
.	.	.-F	Fe
Rug	Rug	beir-V	Vmis
mé	mé	mé-P	Pp1-s
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Bhreathnaigh	Bhreathnaigh	breathnaigh-V	Vmis
mé	mé	mé-P	Pp1-s
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gclúdach	gclúdach	clúdach-N	Ncmsc
ar feadh	ar feadh	ar_feadh-S	Spc
soicind	soicind	soicind-N	Ncmsg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmm-2s
mé	mé	mé-P	Pp1-s
go	go	go-U	Ua
faiteach	faiteach	faiteach-A	Aqp
é	é	é-P	Pp3ms
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
marc	marc	marc-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
scríofa	scríofa	scríobh-A	Av
ag	ag	ag-S	Sp
an	an	an-T	Td-s
Máistreás	Máistreás	máistreás-N	Ncfsc
ba	ba	is-W	Wsri
bheag	bheag	beag-A	Aqp
nár	nár	nár-Q	Qnrs
thit	thit	tit-V	Vmis---n
mé	mé	mé-P	Pp1-s
as	as	as-P	Pr3ms
mo	mo	mo-D	Dp1-s
sheasamh	sheasamh	seas-N	Ncmsc|Nv
!	!	!-F	Fe
Cúig	Cúig	cúig-M	Mc
déag	déag	déag-N	Ns-s
as	as	as-S	Sp
fiche	fiche	fiche-N	Ncmsc
!	!	!-F	Fe
An	An	an-T	Td-s
marc	marc	marc-N	Ncmsc
ab	ab	is-U	U
fhearr	fhearr	maith-A	Aqc
dá	dá	dá-C	Cs
bhfuair	bhfuair	faigh-V	Vmis
mé	mé	mé-P	Pp1-s
riamh	riamh	riamh-R	Rg
!	!	!-F	Fe
Ar	Ar	ar-S	Sp
dtús	dtús	tús-N	Ncmsc
bhí	bhí	bí-V	Vmis
iontas	iontas	iontas-N	Ncmsc
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
bhí	bhí	bí-V	Vmis
ríméad	ríméad	ríméad-N	Ncmsc
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
mé	mé	mé-P	Pp1-s
Sadhbh	Sadhbh	Sadhbh-N	Npfsc
ag	ag	ag-S	Sp
breathnú	breathnú	breathnaigh-N	Nv
orm	orm	ar-P	Pr1-s
agus	agus	agus-C	Cc
meangadh	meangadh	meang-V	Vmis0
mór	mór	mór-N	Ncmsc
uirthi	uirthi	ar-P	Pr3fs
féin	féin	féin-P	Px
freisin	freisin	freisin-R	Rg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Anois	Anois	anois-R	Rt
,	,	,-F	Fi
a	a	a-U	Uv
Nuala	Nuala	Nuala-N	Npf-v
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
‘	‘	‘-X	Xx
Dúirt	Dúirt	abair-V	Vmis
mé	mé	mé-P	Pp1-s
leat	leat	le-P	Pr2-s
Dé	Dé	Dé-N	Ns-s
hAoine	hAoine	Aoine-N	Ncfsg
nár	nár	is-W	Wsrin
ghá	ghá	gá-N	Ncmsc
duit	duit	do-P	Pr2-s
aon	aon	aon-D	Dq
imní	imní	imní-N	Ncfsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
ort	ort	ar-P	Pr2-s
!	!	!-F	Fe
’	’	’-F	Fa
An	An	an-T	Td-s
chuid	chuid	cuid-N	Ncfsc
eile	eile	eile-D	Dd
den	den	de-S	Spa-s
lá	lá	lá-N	Ncmsc
sin	sin	sin-D	Dd
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
rudaí	rudaí	rud-N	Ncmpc
aisteacha	aisteacha	aisteach-A	Aq--pc
ag	ag	ag-S	Sp
tarlú	tarlú	tarlaigh-N	Nv
istigh	istigh	istigh-R	Rl
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
cheann	cheann	ceann-N	Ncmsc
.	.	.-F	Fe
Ag	Ag	ag-S	Sp
10	10	10-M	Mn
a	a	an-T	Td-s
chlog	chlog	clog-N	Ncmsc
-	-	--F	Fb
bhí	bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
sásta	sásta	sásta-A	Aqp
liom	liom	le-P	Pr1-s
féin	féin	féin-P	Px
mar	mar	mar-C	Cs
go	go	go-Q	Q
bhfuair	bhfuair	faigh-V	Vmis
mé	mé	mé-P	Pp1-s
marc	marc	marc-N	Ncmsc
iontach	iontach	iontach-A	Aq-msc
sa	sa	i-S	Spa-s
teist	teist	teist-N	Ncfsc
.	.	.-F	Fe
Ag	Ag	ag-S	Sp
10	10	10-M	Mn
.	.	.-F	Fe
30	30	30-M	Mn
-	-	--M	Ms|Fb
bhraith	bhraith	braith-V	Vmis
mé	mé	mé-P	Pp1-s
ciontach	ciontach	ciontach-A	Aqp|Ncmsc
.	.	.-F	Fe
Fuair	Fuair	faigh-V	Vmis
mé	mé	mé-P	Pp1-s
marc	marc	marc-N	Ncmsc
iontach	iontach	iontach-A	Aq-msc
mar	mar	mar-C	Cs
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
cóipeáil	cóipeáil	cóipeáil-N	Nv
.	.	.-F	Fe
Ag	Ag	ag-S	Sp
10	10	10-M	Mn
.	.	.-F	Fe
45	45	45-M	Mn
-	-	--M	Ms|Fb
bhí	bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
sásta	sásta	sásta-A	Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
cara	cara	cara-N	Ncmsc
ar nós	ar nós	ar_nós-S	Spc
Sadhbh	Sadhbh	Sadhbh-N	Npf-g
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
Cara	Cara	cara-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sásta	sásta	sásta-A	Aqc
rud	rud	rud-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
mo	mo	mo-D	Dp1-s
shon	shon	son-N	Ns-s|Ncmsc
.	.	.-F	Fe
Ag	Ag	ag-S	Sp
11	11	11-M	Mn
a	a	a-D	Dp3
Chloe	Chloe	Chloe-N	Npfsc
-	-	--F	Fb
bhraith	bhraith	braith-V	Vmis
mé	mé	mé-P	Pp1-s
an-chiontach	an-chiontach	ciontach-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
rud	rud	rud-N	Ncmsc
mímhacánta	mímhacánta	mímhacánta-A	Aqp
déanta	déanta	déan-A	Av
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
Shocraigh	Shocraigh	socraigh-V	Vmis
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
an	an	an-T	Td-s
bpointe	bpointe	pointe-N	Ncmsc
sin	sin	sin-D	Dd
go	go	go-Q	Q
n-inseoinn	n-inseoinn	inis-V	Vmc-1s
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
don	don	do-S	Spa-s
Mháistreás	Mháistreás	máistreás-N	Ncfsc
.	.	.-F	Fe
Ach	Ach	ach-S	Sp|Cs
ag	ag	ag-S	Sp
11	11	11-M	Mn
.	.	.-F	Fe
30	30	30-M	Mn
-	-	--M	Ms|Fb
rita	rita	rita-A	Av
sé	sé	sé-W	Wp-i-3|Pp3msn
liom	liom	le-P	Pr1-s
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
Sadhbh	Sadhbh	Sadhbh-N	Npfsc
i	i	i-S	Sp
dtrioblóid	dtrioblóid	trioblóid-N	Ncfsc
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
dá	dá	dá-C	Cs
n-inseoinn	n-inseoinn	inis-V	Vmc-1s
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
don	don	do-S	Spa-s
Mháistreás	Mháistreás	máistreás-N	Ncfsc
.	.	.-F	Fe
Shocraigh	Shocraigh	socraigh-V	Vmis
mé	mé	mé-P	Pp1-s
nach	nach	nach-Q	Qnr
ndéarfainn	ndéarfainn	abair-V	Vmc-1s
dada	dada	dada-N	Ncmsc
.	.	.-F	Fe
cheart	cheart	ceart-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
céard	céard	cé-W	W--q
ba	ba	is-W	Wsri
cheart	cheart	ceart-A	Aqp
dom	dom	do-P	Pr1-s
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
an	an	an-T	Td-s
Mháistreás	Mháistreás	máistreás-N	Ncfsc
ag	ag	ag-S	Sp
súil	súil	súil-N	Nv-----n
le	le	le-S	Sp
marc	marc	marc-N	Ncmsc
ard	ard	ard-A	Aq-msc
uaim	uaim	ó-N	Ncfsc|Pr1-s
sa	sa	i-S	Spa-s
teist	teist	teist-N	Ncfsc
litrithe	litrithe	litrigh-A	Av
uaidh	uaidh	ó-P	Pr3ms
seo	seo	seo-P	Pd
amach	amach	amach-R	Rd
.	.	.-F	Fe
Shocraigh	Shocraigh	socraigh-V	Vmis
mé	mé	mé-P	Pp1-s
go	go	go-Q	Q
n-inseoinn	n-inseoinn	inis-V	Vmc-1s
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
di	di	do-P	Pr3fs
.	.	.-F	Fe
dá	dá	dá-C	Cs
ndéanfainn	ndéanfainn	déan-V	Vmc-1s
an-iarracht	an-iarracht	iarracht-N	Ncfsc
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
,	,	,-F	Fi
go	go	go-Q	Q
bhféadfainn	bhféadfainn	féad-V	Vmc-1s
feabhas	feabhas	feabhas-N	Ncmsc
a	a	a-U	U
chur	chur	cuir-N	Nv
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
mo	mo	mo-D	Dp1-s
chuid	chuid	cuid-N	Ncfsc
litrithe	litrithe	litrigh-N	Ncmsg|Ncmpg|Nv--g
.	.	.-F	Fe
B	B	B-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
go	go	go-Q	Q
mbeinn	mbeinn	bí-V	Vmc-1s
in ann	in ann	in_ann-S	Spc
marc	marc	marc-N	Ncmsc
sách	sách	sách-R	Ri
maith	maith	maith-A	Aqp
a	a	a-U	U
bhaint	bhaint	bain-N	Nv
amach	amach	amach-R	Rd
an	an	an-T	Td-s
tseachtain	tseachtain	seachtain-N	Ncfsc
dár	dár	de-S	Spp-p
gcionn	gcionn	ceann-N	Ncfsd
.	.	.-F	Fe
Shocraigh	Shocraigh	socraigh-V	Vmis
mé	mé	mé-P	Pp1-s
nach	nach	nach-Q	Qnr
ndéarfainn	ndéarfainn	abair-V	Vmc-1s
dada	dada	dada-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
an-trína	an-trína	an-trín-N	Ncfpc
chéile	chéile	céile-N	Ncmsg
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
tuairim	tuairim	tuairim-N	Ncfsc
na	na	na-T	Td-p
ngrást	ngrást	grásta-N	Ncmpg
agam	agam	ag-P	Pr1-s
céard	céard	cé-W	W--q
ba	ba	is-W	Wsri
cheart	cheart	ceart-A	Aqp
dom	dom	do-P	Pr1-s
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
?	?	?-F	Fq
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
fós	fós	fós-R	Rg
idir	idir	idir-S	Sp
dhá	dhá	dó-M	Mc
chomhairle	chomhairle	comhairle-N	Ncfsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
Mháistreás	Mháistreás	máistreás-N	Ncfsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
labhairt	labhairt	labhair-N	Ncfsc|Nv
liom	liom	le-P	Pr1-s
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmm-2s
gach	gach	gach-D	Dq
duine	duine	duine-N	Ncmsc
eile	eile	eile-D	Dd
amach	amach	amach-R	Rd
as	as	as-S	Sp
an	an	an-T	Td-s
seomra	seomra	seomra-N	Ncmsc
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
fanta	fanta	fan-A	Av
ach	ach	ach-S	Sp|Cs
mé	mé	mé-P	Pp1-s
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
obair	obair	obair-N	Nv-----n
go	go	go-U	Ua
dícheallach	dícheallach	dícheallach-A	Aqp
na	na	na-T	Td-p
laethanta	laethanta	lá-N	Ncmpg|Ncmpc
seo	seo	seo-D	Dd
,	,	,-F	Fi
a	a	a-U	Uv
Nuala	Nuala	Nuala-N	Npf-v
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
Mháistreás	Mháistreás	máistreás-N	Ncfsc
liom	liom	le-P	Pr1-s
.	.	.-F	Fe
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
feicim	feicim	feic-V	Vmip1s
gur	gur	gur-Q	Q--s
éirigh	éirigh	éirigh-V	Vmis
go	go	go-U	Ua
maith	maith	maith-A	Aqp
leat	leat	le-P	Pr2-s
sa	sa	i-S	Spa-s
teist	teist	teist-N	Ncfsc
litrithe	litrithe	litrigh-A	Av
an	an	an-T	Td-s
tseachtain	tseachtain	seachtain-N	Ncfsc
seo	seo	seo-D	Dd
.	.	.-F	Fe
Táim	Táim	bí-V	Vmip1s
an-sásta	an-sásta	sásta-A	Aqp
leat	leat	le-P	Pr2-s
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
le	le	le-S	Sp
d	d	d-X	Xl
’	’	’-F	Fa
ainm	ainm	ainm-N	Ncmsc
a	a	a-U	U
chur	chur	cuir-N	Nv
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
Leabhar	Leabhar	leabhar-N	Ncmsc
na	na	na-T	Td-p
Réaltaí	Réaltaí	réalta-N	Ncfpg
anois	anois	anois-R	Rt
láithreach	láithreach	láithreach-N	Ncmsc
!	!	!-F	Fe
’	’	’-F	Fa
Sa	Sa	i-S	Spa-s
rang	rang	rang-N	Ncmsc
seo	seo	seo-D	Dd
againne	againne	ag-P	Pr1-p-e
,	,	,-F	Fi
tá	tá	bí-V	Vmip
an	an	an-T	Td-s
leabhar	leabhar	leabhar-N	Ncmsc
mór	mór	mór-A	Aq-msc
seo	seo	seo-D	Dd
ann	ann	i-P	Pr3ms
,	,	,-F	Fi
‘	‘	‘-X	Xx
Leabhar	Leabhar	leabhar-N	Ncmsc
na	na	na-T	Td-p
Réaltaí	Réaltaí	réalta-N	Ncfpg
.	.	.-F	Fe
’	’	’-F	Fa
Bíonn	Bíonn	bí-V	Vmig
sé	sé	sé-P	Pp3msn
leagtha	leagtha	leag-A	Av
ar	ar	ar-S	Sp
an	an	an-T	Td-s
deasc	deasc	deasc-N	Ncfsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
Máistreás	Máistreás	máistreás-N	Ncfsc
.	.	.-F	Fe
Má	Má	má-C	Cs
bhíonn	bhíonn	bí-V	Vmig
páiste	páiste	páiste-N	Ncmsc
thar	thar	thar-S	Sp
barr	barr	barr-N	Ncmsc
sa	sa	i-S	Spa-s
rang	rang	rang-N	Ncmsc
–	–	–-X	Xx
agus	agus	agus-C	Cc
thar	thar	thar-S	Sp
barr	barr	barr-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
atá	atá	bí-V	Vmip---r
i	i	i-S	Sp
gceist	gceist	ceist-N	Ncfsc
agam	agam	ag-P	Pr1-s
–	–	–-X	Xx
scríobhtar	scríobhtar	scríobh-V	Vmip0
a	a	a-D	Dp3
ainm	ainm	ainm-N	Ncmsc
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
Leabhar	Leabhar	leabhar-N	Ncmsc
na	na	na-T	Td-p
Réaltaí	Réaltaí	réalta-N	Ncfpg
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
ag	ag	ag-S	Sp
deireadh	deireadh	deireadh-N	Ncmsc
an	an	an-T	Td-s
téarma	téarma	téarma-N	Ncmsg
faigheann	faigheann	faigh-V	Vmip
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
a	a	a-Q	Q-i
bhfuil	bhfuil	bí-V	Vmip---d
a	a	a-D	Dp3
ainm	ainm	ainm-N	Ncmsc
sa	sa	i-S	Spa-s
Leabhar	Leabhar	leabhar-N	Ncmsc
duais	duais	duais-N	Ncfsc
ón	ón	ó-S	Spa-s
Máistreás	Máistreás	máistreás-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
cuir	cuir	cur-N	Ncmsg
,	,	,-F	Fi
a	a	a-U	Uv
Mháistreás	Mháistreás	máistreás-N	Ncfsv
!	!	!-F	Fe
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
mé	mé	mé-P	Pp1-s
go	go	go-U	Ua
tobann	tobann	tobann-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
cuir	cuir	cuir-V	Vmm-2s-n
m	m	m-X	Xl
’	’	’-F	Fa
ainm	ainm	ainm-N	Ncmsc
i	i	i-S	Sp
Leabhar	Leabhar	leabhar-N	Ncmsc
na	na	na-T	Td-p
Réaltaí	Réaltaí	réalta-N	Ncfpg
!	!	!-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
atá	atá	bí-V	Vmip---r
tú	tú	tú-P	Pp2-s
a	a	a-U	U
rá	rá	abair-N	Nv
,	,	,-F	Fi
a	a	a-U	Uv
Nuala	Nuala	Nuala-N	Npf-v
?	?	?-F	Fq
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Mháistreás	Mháistreás	máistreás-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
rá	rá	abair-N	Nv
liom	liom	le-P	Pr1-s
gan	gan	gan-S	Sp
d	d	d-X	Xl
’	’	’-F	Fa
ainm	ainm	ainm-N	Ncmsc
a	a	a-U	U
chur	chur	cuir-N	Nv
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
Leabhar	Leabhar	leabhar-N	Ncmsc
?	?	?-F	Fq
!	!	!-F	Fe
Ach	Ach	ach-C	Cs
cén	cén	cé-W	W--q
fáth	fáth	fáth-N	Ncmsc
nach	nach	nach-Q	Qnr
gcuirfinn	gcuirfinn	cuir-V	Vmc-1s
agus	agus	agus-C	Cc
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
obair	obair	obair-N	Nv-----n
go	go	go-U	Ua
dícheallach	dícheallach	dícheallach-A	Aqp
?	?	?-F	Fq
!	!	!-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
nílim	nílim	bí-V	Vmip1s-n
ag	ag	ag-S	Sp
obair	obair	obair-N	Nv-----n
go	go	go-U	Ua
dícheallach	dícheallach	dícheallach-A	Aqp
!	!	!-F	Fe
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
mise	mise	mé-P	Pp1-s-e
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
réalta	réalta	réalta-N	Ncfsc
tuillte	tuillte	tuill-A	Av
agam	agam	ag-P	Pr1-s
!	!	!-F	Fe
’	’	’-F	Fa
Bhreathnaigh	Bhreathnaigh	breathnaigh-V	Vmis
an	an	an-T	Td-s
Mháistreás	Mháistreás	máistreás-N	Ncfsc
orm	orm	ar-P	Pr1-s
ar nós	ar nós	ar_nós-S	Spc
dá	dá	dá-C	Cs
mbeinn	mbeinn	bí-V	Vmc-1s
as	as	as-P	Pr3ms
mo	mo	mo-D	Dp1-s
mheabhair	mheabhair	meabhair-N	Ncfsc
.	.	.-F	Fe
Go	Go	go-U	Ua
tobann	tobann	tobann-A	Aqp
agus	agus	agus-C	Cc
gan	gan	gan-S	Sp
aon	aon	aon-D	Dq
spreagadh	spreagadh	spreagadh-N	Ncmsc
ón	ón	ó-S	Spa-s
Máistreás	Máistreás	máistreás-N	Ncfsc
,	,	,-F	Fi
thosaigh	thosaigh	tosaigh-V	Vmis
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
inis	inis	inis-V	Vmis
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
di	di	do-P	Pr3fs
ó	ó	ó-S	Sp
thús	thús	tús-N	Ncmsc
deireadh	deireadh	abair-V	Vmih
.	.	.-F	Fe
An	An	an-T	Td-s
chaoi	chaoi	caoi-N	Ncfsc
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
mhaith	mhaith	maith-N	Ncfsc
liom	liom	le-P	Pr1-s
ag	ag	ag-S	Sp
litriú	litriú	litrigh-N	Nv
.	.	.-F	Fe
An	An	an-T	Td-s
chaoi	chaoi	caoi-N	Ncfsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
Sadhbh	Sadhbh	Sadhbh-N	Npfsc
agus	agus	agus-C	Cc
mé	mé	mé-P	Pp1-s
féin	féin	féin-P	Px
chomh	chomh	chomh-R	Ri
mór	mór	mór-A	Aqp
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
fiú	fiú	fiú-N	Ns-s|Ncmsc|Rg
amháin	amháin	amháin-A	Aqp
,	,	,-F	Fi
d	d	d-X	Xl
’	’	’-F	Fa
inis	inis	inis-V	Vmis
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
faoi	faoi	faoi-S	Sp
Bhriain	Bhriain	Brian-N	Npfsg|Ncmsg
Ó	Ó	Ó-U	Up
Tuathail	Tuathail	Tuathail-N	Npmsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
crián	crián	crián-N	Ncmsc
gorm	gorm	gorm-A	Aq-msc
sna	sna	i-S	Spa-p
Naíonáin	Naíonáin	Naíonáin-N	Npmsc
Mhóra	Mhóra	mór-A	Aq--pc
.	.	.-F	Fe
Mhínigh	Mhínigh	mínigh-V	Vmis
mé	mé	mé-P	Pp1-s
don	don	do-S	Spa-s
Mháistreás	Mháistreás	máistreás-N	Ncfsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
faitíos	faitíos	faitíos-N	Ncmsc
orm	orm	ar-P	Pr1-s
go	go	go-Q	Q
dtarraingeoinn	dtarraingeoinn	tarraing-V	Vmc-1s
trioblóid	trioblóid	trioblóid-N	Ncfsc
ar	ar	ar-S	Sp
Shadhbh	Shadhbh	Sadhbh-N	Npfsc
dá	dá	dá-C	Cs
n-inseoinn	n-inseoinn	inis-V	Vmc-1s
an	an	an-T	Td-s
fhírinne	fhírinne	fírinne-N	Ncfsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
deireadh	deireadh	deireadh-N	Ncmsc
ráite	ráite	abair-A	Av
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
tharraing	tharraing	tarraing-V	Vmis
mé	mé	mé-P	Pp1-s
m	m	m-X	Xl
’	’	’-F	Fa
anáil	anáil	anáil-N	Ncfsc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
fhan	fhan	fan-V	Vmis
mé	mé	mé-P	Pp1-s
le	le	le-S	Sp
freagra	freagra	freagra-N	Ncmsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
an	an	an-T	Td-s
freagra	freagra	freagra-N	Ncmsc
,	,	,-F	Fi
rinneadh	rinneadh	déan-V	Vmis0
staic	staic	staic-N	Ncfsc
díom	díom	de-P	Pr1-s
.	.	.-F	Fe
Dúirt	Dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
liom	liom	le-P	Pr1-s
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
díomá	díomá	díomá-N	Ncfsc
uirthi	uirthi	ar-P	Pr3fs
liom	liom	le-P	Pr1-s
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
mar	mar	mar-C	Cs
sin	sin	sin-W	W
féin	féin	féin-P	Px
gur	gur	gur-Q	Q--s
thuig	thuig	tuig-V	Vmip|Vmis
sí	sí	sí-P	Pp3fsn
mo	mo	mo-D	Dp1-s
chás	chás	cás-N	Ncmsc
.	.	.-F	Fe
Mhínigh	Mhínigh	mínigh-V	Vmis
sí	sí	sí-P	Pp3fsn
dom	dom	do-P	Pr1-s
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
athrú	athrú	athrú-N	Ncmsc
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
go	go	go-U	Ua
gearr	gearr	gearr-A	Aqp
ar	ar	ar-S	Sp
churaclam	churaclam	curaclam-N	Ncmsc
na	na	na-T	Tdfsg
scoile	scoile	scoil-N	Ncfsg
agus	agus	agus-C	Cc
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
bealaí	bealaí	bealach-N	Ncmpc
níos	níos	níos-U	Uc
fearr	fearr	maith-A	Aqc
ann	ann	i-R	Rl|Pr3ms
le	le	le-S	Sp
litriú	litriú	litrigh-N	Nv
a	a	a-U	U
mhúineadh	mhúineadh	múin-N	Nv
agus	agus	agus-C	Cc
a	a	a-U	U
fhoghlaim	fhoghlaim	foghlaim-N	Nv
.	.	.-F	Fe
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
gach	gach	gach-D	Dq
seans	seans	seans-N	Ncmsc
ann	ann	i-P	Pr3ms
go	go	go-Q	Q
gcuirfí	gcuirfí	cuir-V	Vmc-0
deireadh	deireadh	deireadh-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
le	le	le-S	Sp
teisteanna	teisteanna	teist-N	Ncfpc
litrithe	litrithe	litrigh-A	Av
.	.	.-F	Fe
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
ní	ní	ní-Q	Qn
chuirfidh	chuirfidh	cuir-V	Vmif---n
mé	mé	mé-P	Pp1-s
aon	aon	aon-D	Dq
phionós	phionós	pionós-N	Ncmsc
ort	ort	ar-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
Mháistreás	Mháistreás	máistreás-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
tú	tú	tú-P	Pp2-s
a	a	a-U	U
ghealladh	ghealladh	geall-N	Nv
dom	dom	do-P	Pr1-s
go	go	go-Q	Q
n-inseoidh	n-inseoidh	inis-V	Vmif
tú	tú	tú-P	Pp2-s
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
do	do	do-D	Dp2-s|Sp
do	do	do-S	Sp
thuismitheoirí	thuismitheoirí	tuismitheoir-N	Ncmpc
.	.	.-F	Fe
’	’	’-F	Fa
Ó	Ó	Ó-I	I
,	,	,-F	Fi
muise	muise	muise-X	Xsc
.	.	.-F	Fe
Díreach	Díreach	díreach-N	Ncmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
cheap	cheap	ceap-V	Vmis
mé	mé	mé-P	Pp1-s
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
báire	báire	báire-N	Ncmsc
liom	liom	le-P	Pr1-s
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
sin	sin	sin-P	Pd
níos	níos	níos-U	Uc
measa	measa	olc-A	Aqc
ná	ná	ná-C	Cs|Cc
aon	aon	aon-D	Dq
phionós	phionós	pionós-N	Ncmsc
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhéadfadh	fhéadfadh	féad-V	Vmc
an	an	an-T	Td-s
Mháistreás	Mháistreás	máistreás-N	Ncfsc
a	a	a-U	U
chur	chur	cuir-N	Nv
orm	orm	ar-P	Pr1-s
!	!	!-F	Fe
Bheadh	Bheadh	bí-V	Vmc
an-díomá	an-díomá	díomá-N	Ncfsc
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
mo	mo	mo-D	Dp1-s
thuismitheoirí	thuismitheoirí	tuismitheoir-N	Ncmpc
!	!	!-F	Fe
Ach	Ach	ach-C	Cs
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
Mháistreás	Mháistreás	máistreás-N	Ncfsc
rud	rud	rud-N	Ncmsc
amháin	amháin	amháin-A	Aqp
eile	eile	eile-D	Dd
liom	liom	le-P	Pr1-s
.	.	.-F	Fe
Dúirt	Dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
gur	gur	is-W	Wsdi
rud	rud	rud-N	Ncmsc
mímhacánta	mímhacánta	mímhacánta-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
déanta	déanta	déan-A	Av
ag	ag	ag-S	Sp
Sadhbh	Sadhbh	Sadhbh-N	Npfsc
,	,	,-F	Fi
ach	ach	ach-C	Cs
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
t-ádh	t-ádh	ádh-N	Ncmsc
dearg	dearg	dearg-A	Aq-msc
liomsa	liomsa	le-P	Pr1-s-e
a	a	a-D	Dp3
leithéid	leithéid	leithéid-N	Ncfsc
de	de	de-S	Sp
chara	chara	cara-N	Ncmsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
sí	sí	sí-P	Pp3fsn
m	m	m-X	Xl
’	’	’-F	Fa
ainm	ainm	ainm-N	Ncmsc
i	i	i-S	Sp
‘	‘	‘-X	Xx
Leabhar	Leabhar	leabhar-N	Ncmsc
na	na	na-T	Td-p
Réaltaí	Réaltaí	réalta-N	Ncfpg
’	’	’-F	Fa
freisin	freisin	freisin-R	Rg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Rinne	Rinne	déan-V	Vmis
mé	mé	mé-P	Pp1-s
é	é	é-P	Pp3ms
sin	sin	sin-P	Pd
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
liom	liom	le-P	Pr1-s
,	,	,-F	Fi
‘	‘	‘-X	Xx
mar	mar	mar-C	Cs
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
de	de	de-S	Sp
mhisneach	mhisneach	misneach-N	Ncmsc
agat	agat	ag-P	Pr2-s
an	an	an-T	Td-s
fhírinne	fhírinne	fírinne-N	Ncfsc
a	a	a-U	U
insint	insint	inis-N	Nv
dom	dom	do-P	Pr1-s
agus	agus	agus-C	Cc
gan	gan	gan-S	Sp
an	an	an-T	Td-s
milleán	milleán	milleán-N	Ncmsc
a	a	a-U	U
chur	chur	cuir-N	Nv
ar	ar	ar-S	Sp
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
eile	eile	eile-D	Dd
.	.	.-F	Fe
’	’	’-F	Fa
Agus	Agus	agus-C	Cc
sin	sin	sin-W	W
é	é	é-P	Pp3ms
é	é	é-P	Pp3ms
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
gach	gach	gach-D	Dq
rud	rud	rud-N	Ncmsc
thar	thar	thar-S	Sp
barr	barr	barr-N	Ncmsc
ar	ar	ar-S	Sp
scoil	scoil	scoil-N	Ncfsc
anois	anois	anois-R	Rt
!	!	!-F	Fe
Thar	Thar	thar-S	Sp
barr	barr	barr-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
!	!	!-F	Fe
