Scanraithe	Scanraithe	scanraigh-A	Av
!	!	!-F	Fe
Oíche	Oíche	oíche-N	Ncfsc
Dé	Dé	Dé-N	Ns-s
Sathairn	Sathairn	Satharn-N	Ncmsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Méabh	Méabh	Méabh-N	Npfsc
agus	agus	agus-C	Cc
beirt	beirt	beirt-N	Ncfsc
chairde	chairde	cairde-N	Ncmpc|Ncmsc
dá	dá	de-S	Spp-s
cuid	cuid	cuid-N	Ncfsc
–	–	–-X	Xx
Denise	Denise	Denise-N	Npmsc
agus	agus	agus-C	Cc
Sinéad	Sinéad	Sinéad-N	Npf-g|Npfsc
–	–	–-X	Xx
suite	suite	suigh-A	Av
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gclaí	gclaí	claí-N	Ncmsc
sa	sa	i-S	Spa-s
gcarrchlós	gcarrchlós	carrchlós-N	Ncmsc
taobh amuigh	taobh amuigh	taobh_amuigh-R	Rl
den	den	de-S	Spa-s
phictiúrlann	phictiúrlann	pictiúrlann-N	Ncfsc
áitiúil	áitiúil	áitiúil-A	Aq-fsc|Aq-fsv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
triúr	triúr	triúr-N	Ncmsc
acu	acu	ag-P	Pr3-p
tar éis	tar éis	tar_éis-S	Spc
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
a	a	a-U	U
chaitheamh	chaitheamh	caith-N	Nv
i gcuideachta	i gcuideachta	i_gcuideachta-S	Spc
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
mhaidin	mhaidin	maidin-N	Ncfsc
caite	caite	caith-A	Av
acu	acu	ag-P	Pr3-p
ag	ag	ag-S	Sp
gabháil	gabháil	gabh-N	Nv
thart	thart	thart-R	Rd
sna	sna	i-S	Spa-p
hionaid	hionaid	ionad-N	Ncmpc
siopadóireachta	siopadóireachta	siopadóir-N	Ncfsg|Nv--g--n
sa	sa	i-S	Spa-s
mbaile	mbaile	baile-N	Ncmsc
mór	mór	mór-A	Aq-msc
ag	ag	ag-S	Sp
breathnú	breathnú	breathnaigh-N	Nv
ar	ar	ar-S	Sp
na	na	na-T	Td-p
héadaí	héadaí	éadach-N	Ncmpc
agus	agus	agus-C	Cc
ar	ar	ar-S	Sp
na	na	na-T	Td-p
bróga	bróga	bróg-N	Ncfpc
deasa	deasa	deas-A	Aq--pc
galánta	galánta	galánta-A	Aqp
a	a	a-Q	Q-r
cheannóidís	cheannóidís	ceannaigh-V	Vmc-3p
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
t	t	t-X	Xl
‑	‑	‑-F	Fb
airgead	airgead	airgead-N	Ncmsc
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
'	'	'-F	Fa
Is	Is	is-W	Wp-i
ea	ea	ea-P	Pp3-s
–	–	–-X	Xx
lá	lá	lá-N	Ncmsc
eicínt	eicínt	eicínt-A	Aq-msc
amach	amach	amach-R	Rd
anseo	anseo	anseo-R	Rl
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhuafaidh	bhuafaidh	buaigh-V	Vmif
muid	muid	muid-P	Pp1-p
an	an	an-T	Td-s
lató	lató	lató-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Denise	Denise	Denise-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
phósfaidh	phósfaidh	pós-V	Vmif
muid	muid	muid-P	Pp1-p
milliúnaithe	milliúnaithe	milliúnaí-N	Ncmpc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Sinéad	Sinéad	Sinéad-N	Npfsc
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
fios	fios	fios-N	Ncmsc
cén	cén	cé-W	W--q|Dw--s
spraoi	spraoi	spraoi-N	Ncmsc|Ncmsg|Ncmsc|Ncmsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
an	an	an-T	Td-s
triúr	triúr	triúr-N	Ncmsc
cé	cé	cé-C	Cs
nár	nár	is-W	Wsrin
chaith	chaith	caith-V	Vmis
siad	siad	siad-P	Pp3-pn
leathphingin	leathphingin	leathphingin-N	Ncfsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
tar éis	tar éis	tar_éis-S	Spc
an	an	an-T	Td-s
lóin	lóin	lón-N	Ncmsg
chas	chas	cas-V	Vmis
siad	siad	siad-P	Pp3-pn
le	le	le-S	Sp
cuid	cuid	cuid-N	Ncfsc
de	de	de-S	Sp
na	na	na-T	Td-p
buachaillí	buachaillí	buachaill-N	Ncmpc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
cailíní	cailíní	cailín-N	Ncmpc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sa	sa	i-S	Spa-s
rang	rang	rang-N	Ncmsc
céanna	céanna	céanna-A	Aqp
leo	leo	le-P	Pr3-p
i	i	i-S	Sp
Scoil	Scoil	scoil-N	Ncfsc
Chuimsitheach	Chuimsitheach	cuimsitheach-A	Aq-fsc
Naomh	Naomh	Naomh-N	Npmsc
Pádraig	Pádraig	Pádraig-N	Npm-g|Npmsg|Npmsc
agus	agus	agus-C	Cc
chuaigh	chuaigh	téigh-V	Vmis
an	an	an-T	Td-s
grúpa	grúpa	grúpa-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
ag	ag	ag-S	Sp
babhláil	babhláil	babhláil-N	Nv
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Seo	Seo	seo-W	W
socrú	socrú	socrú-N	Nv|Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
déanta	déanta	déan-A	Av
acu	acu	ag-P	Pr3-p
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
a	a	a-Q	Q-i|Q-r
fuair	fuair	faigh-V	Vmis
siad	siad	siad-P	Pp3-pn
laethanta	laethanta	lá-N	Ncmpc
saoire	saoire	saoire-N	Ncfsc
an	an	an-T	Td-s
tsamhraidh	tsamhraidh	samhradh-N	Ncmsg
mí	mí	mí-N	Ncfsc|Ncmsc|Ncmsg
roimhe	roimhe	roimh-P	Pr3ms
sin	sin	sin-P	Pd
.	.	.-F	Fe
Cé	Cé	cé-C	Cs
nár	nár	is-W	Wssin|Wsdin
éirigh	éirigh	éirigh-V	Vmm-2s
leo	leo	le-P	Pr3-p
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
i láthair	i láthair	i_láthair-S	Spc
bhain	bhain	bain-N	Npmsg
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
acu	acu	ag-P	Pr3-p
ann	ann	i-P	Pr3ms
‑	‑	‑-F	Fb
sásamh	sásamh	sásamh-N	Nv|Ncmsc
as	as	as-S	Sp
an	an	an-T	Td-s
ócáid	ócáid	ócáid-N	Ncfsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhág	fhág	fág-V	Vmis
an	an	an-T	Td-s
grúpa	grúpa	grúpa-N	Ncmsc
slán	slán	slán-A	Aq-msc
ag	ag	ag-S	Sp
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
ionad	ionad	ionad-N	Ncmsc
babhlála	babhlála	babhláil-N	Nv--g
ag	ag	ag-S	Sp
leathuair	leathuair	leathuair-N	Ncfsc
tar éis	tar éis	tar_éis-S	Spc
a	a	a-U	Um
cúig	cúig	cúig-M	Mc
cheap	cheap	ceap-N	Ncmsc
Méabh	Méabh	Méabh-N	Npfsc
,	,	,-F	Fi
Denise	Denise	Denise-N	Npmsc
agus	agus	agus-C	Cc
Sinéad	Sinéad	Sinéad-N	Npf-g|Npfsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
róluath	róluath	luath-A	Aqp
dóibh	dóibh	do-P	Pr3-p
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
tabhairt	tabhairt	tabhair-N	Nv
aghaidh	aghaidh	aghaidh-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbaile	mbaile	baile-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
‑	‑	‑-F	Fb
chraic	chraic	craic-N	Ncfsc
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
acu	acu	ag-P	Pr3-p
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
fonn	fonn	fonn-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
triúr	triúr	triúr-N	Ncmsc
scaradh	scaradh	scar-V	Vmis0
lena	lena	le-S	Spp-s
chéile	chéile	céile-N	Ncmsc
fós	fós	fós-R	Rg
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
cá	cá	cá-R	Rq
gcaithfidís	gcaithfidís	caith-V	Vmc-3p
an	an	an-T	Td-s
chuid	chuid	cuid-N	Ncfsc
eile	eile	eile-D	Dd
den	den	de-S	Spa-s
lá	lá	lá-N	Ncmsc
?	?	?-F	Fq
B	B	B-X	Xl
’	’	’-F	Fa
in	in	sin-S	Sp|Pd
í	í	í-P	Pp3fs
an	an	an-T	Td-s
cheist	cheist	ceist-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
Céard	Céard	cé-W	W--q
faoi	faoi	faoi-P	Pr3ms
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
chuig	chuig	chuig-S	Sp
an	an	an-T	Td-s
scannán	scannán	scannán-N	Ncmsc
nua	nua	nua-A	Aqp
sin	sin	sin-D	Dd
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
na	na	na-T	Td-p
buachaillí	buachaillí	buachaill-N	Ncmpc
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
faoi	faoi	faoi-P	Pr3ms|Sp
ar	ar	ar-S	Sp
ball	ball	ball-N	Ncmsc
?	?	?-F	Fq
'	'	'-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
Méabh	Méabh	Méabh-N	Npfsc
.	.	.-F	Fe
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
á	á	do-S	Spo-p
mholadh	mholadh	mol-N	Nv
go	go	go-U	Ua
hard	hard	ard-X	Xfea|Aqp
na	na	na-T	Tdfsg
spéire	spéire	spéir-N	Ncfsg
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Sin	Sin	sin-P	Pd|W
‑	‑	‑-F	Fb
phlean	phlean	plean-N	Ncmsc
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Denise	Denise	Denise-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
in	in	i-S	Sp
ainm	ainm	ainm-N	Ncmsc
is	is	agus-C	Cc
a	a	a-U	U
bheith	bheith	bí-N	Nv
‑	‑	‑-F	Fb
bharrúil	bharrúil	barrúil-A	Aqp
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Shocraigh	Shocraigh	socraigh-V	Vmis
siad	siad	siad-P	Pp3-pn
gurb	gurb	is-W	Wpdi
in	in	sin-P	Pd
é	é	é-P	Pp3ms
a	a	a-Q	Q-r
dhéanfaidís	dhéanfaidís	déan-V	Vmc-3p
–	–	–-X	Xx
rachaidís	rachaidís	téigh-V	Vmc-3p
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
phictiúrlann	phictiúrlann	pictiúrlann-N	Ncfsc
áitiúil	áitiúil	áitiúil-A	Aq-fsc|Aq-fsv
go	go	go-Q	Q
bhfeicfidís	bhfeicfidís	feic-V	Vmc-3p
an	an	an-T	Td-s
scannán	scannán	scannán-N	Ncmsc
grinn	grinn	grinn-A	Aq-msc
nua	nua	nua-A	Aqp
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
oiread	oiread	oiread-N	Ns-s
sin	sin	sin-D	Dd
cloiste	cloiste	clois-A	Av
acu	acu	ag-P	Pr3-p
mar	mar	mar-S	Sp
gheall	gheall	geall-N	Ncmsc
air	air	ar-N	Ncmsg
.	.	.-F	Fe
Dá	Dá	de-S	Spp-s
n	n	n-X	Xl
‑	‑	‑-F	Fb
imeoidís	imeoidís	imigh-V	Vmc-3p
as	as	as-S	Sp
an	an	an-T	Td-s
mbaile	mbaile	baile-N	Ncmsc
mór	mór	mór-A	Aq-msc
láithreach	láithreach	láithreach-A	Aq-msc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbus	mbus	bus-N	Ncmsc
bheidís	bheidís	bí-V	Vmc-3p
ag	ag	ag-S	Sp
an	an	an-T	Td-s
bpictiúrlann	bpictiúrlann	pictiúrlann-N	Ncfsc
sula	sula	sula-C	Cs
dtosódh	dtosódh	tosaigh-V	Vmc
an	an	an-T	Td-s
scannán	scannán	scannán-N	Ncmsc
ag	ag	ag-S	Sp
leathuair	leathuair	leathuair-N	Ncfsc
tar éis	tar éis	tar_éis-S	Spc
a	a	a-U	Um
sé	sé	sé-P	Pp3msn
,	,	,-F	Fi
rud	rud	rud-N	Ncmsc
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhágfadh	fhágfadh	fág-V	Vmc
go	go	go-Q	Q
bhféadfaidís	bhféadfaidís	féad-V	Vmc-3p
a	a	a-U	U
bheith	bheith	bí-N	Nv
sa	sa	i-S	Spa-s
mbaile	mbaile	baile-N	Ncmsc
roimh	roimh	roimh-S	Sp
a	a	a-U	Um
haon	haon	aon-M	Mc
déag	déag	déag-N	Ns-s
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
geallta	geallta	geall-A	Av
acu	acu	ag-P	Pr3-p
an	an	an-T	Td-s
mhaidin	mhaidin	maidin-N	Ncfsc
sin	sin	sin-D	Dd
dá	dá	do-S	Spp-p
dtuismitheoirí	dtuismitheoirí	tuismitheoir-N	Ncmpc
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
don	don	do-S	Spa-s
triúr	triúr	triúr-N	Ncmsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
acu	acu	ag-P	Pr3-p
dá	dá	do-S	Spp-p
gcuid	gcuid	cuid-N	Ncfsc
airgid	airgid	airgead-N	Ncmsg
a	a	a-U	U
chomhaireamh	chomhaireamh	comhair-N	Nv
–	–	–-X	Xx
agus	agus	agus-C	Cc
,	,	,-F	Fi
go	go	go-U	Ua
deimhin	deimhin	deimhin-A	Aqp
féin	féin	féin-P	Px
,	,	,-F	Fi
ní	ní	nigh-W	Wp-in|Nv|Ncmsc|Nv
mórán	mórán	mórán-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
–	–	–-X	Xx
fuaireadar	fuaireadar	faigh-V	Vmis3p
amach	amach	amach-R	Rd
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
a	a	a-D	Dp3
ndóthain	ndóthain	dóthain-N	Ncfsc
acu	acu	ag-P	Pr3-p
leis	leis	le-S	Sp
na	na	na-T	Td-p
ticéid	ticéid	ticéad-N	Ncmpc
don	don	do-S	Spa-s
phictiúrlann	phictiúrlann	pictiúrlann-N	Ncfsc
a	a	a-U	U
cheannach	cheannach	ceannaigh-N	Nv
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
éigean	éigean	éigean-N	Ncmsc
!	!	!-F	Fe
Faraor	Faraor	faraor-X	Xsc
,	,	,-F	Fi
ní	ní	ní-Q	Qn
bheadh	bheadh	bí-V	Vmc----n
tada	tada	tada-N	Ncmsc
fágtha	fágtha	fág-A	Av
don	don	do-S	Spa-s
ghrán	ghrán	grán-N	Ncmsc
rósta	rósta	róst-A	Av
ná	ná	ná-C	Cc
don	don	do-S	Spa-s
uachtar	uachtar	uachtar-N	Ncmsc
reoite	reoite	reoigh-A	Av
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
cén	cén	cé-W	W--q
dochar	dochar	dochar-N	Ncmsc
.	.	.-F	Fe
Nach	Nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
cuid	cuid	cuid-N	Ncfsc
mhaith	mhaith	maith-A	Aq-fsc
rudaí	rudaí	rud-N	Ncmpg
milse	milse	milis-A	Aq--pg
ite	ite	ith-A	Av
acu	acu	ag-P	Pr3-p
ó	ó	ó-S	Sp
mhaidin	mhaidin	maidin-N	Ncfsc
.	.	.-F	Fe
I	I	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
an	an	an-T	Td-s
iomarca	iomarca	iomarca-N	Ncfsg
,	,	,-F	Fi
dar	dar	dar-V	Vmip
le	le	le-S	Sp
Sinéad	Sinéad	Sinéad-N	Npfsc
!	!	!-F	Fe
Anois	Anois	anois-R	Rt
agus	agus	agus-C	Cc
an	an	an-T	Td-s
scannán	scannán	scannán-N	Ncmsc
feicthe	feicthe	feic-A	Av
acu	acu	ag-P	Pr3-p
ní	ní	ní-N	Ncmsc
fios	fios	fios-N	Ncmsc
cén	cén	cé-W	W--q|Dw--s
díomá	díomá	díomá-N	Ncfsg|Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ar	ar	ar-S	Sp
na	na	na-T	Td-p
cailíní	cailíní	cailín-N	Ncmpc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sé	sé	sé-P	Pp3msn
leath	leath	leath-D	Dq
chomh	chomh	chomh-R	Ri
barrúil	barrúil	barrúil-A	Aqp
agus	agus	agus-C	Cc
a	a	a-Q	Q-r
bhíodar	bhíodar	bí-V	Vmis3p
ag	ag	ag-S	Sp
súil	súil	súil-N	Nv-----n
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
sé	sé	sé-P	Pp3msn
,	,	,-F	Fi
bunaithe	bunaithe	bunaigh-A	Av
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
cloiste	cloiste	clois-A	Av
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Déanta	Déanta	déan-A	Av
na	na	na-T	Tdfsg
fírinne	fírinne	fírinne-N	Ncfsc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sa	sa	i-S	Spa-s
scannán	scannán	scannán-N	Ncmsc
seo	seo	seo-D	Dd
ó	ó	ó-S	Sp
thús	thús	tús-N	Ncmsc
go	go	go-Q	Q
deireadh	deireadh	abair-V	Vmih
ach	ach	ach-S	Sp
cúpla	cúpla	cúpla-N	Ncmsc
radharc	radharc	radharc-N	Ncmsc
greannmhar	greannmhar	greannmhar-A	Aq-msc
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
sin	sin	sin-P	Pd
feicthe	feicthe	feic-A	Av
acu	acu	ag-P	Pr3-p
cheana	cheana	cheana-R	Rg
féin	féin	féin-P	Px
sna	sna	i-S	Spa-p
fógraí	fógraí	fógra-N	Ncmpc
don	don	do-S	Spa-s
scannán	scannán	scannán-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ar	ar	ar-S	Sp
an	an	an-T	Td-s
teilifís	teilifís	teilifís-N	Ncfsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
aontaigh	aontaigh	aontaigh-V	Vmm-2s
an	an	an-T	Td-s
triúr	triúr	triúr-N	Ncmsc
anois	anois	anois-R	Rt
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
a	a	a-D	Dp3
gcuid	gcuid	cuid-N	Ncfsc
airgid	airgid	airgead-N	Ncmsg
caite	caite	caith-A	Aqp|Av
go	go	go-U	Ua
fánach	fánach	fánach-A	Aqp
acu	acu	ag-P	Pr3-p
agus	agus	agus-C	Cc
gur	gur	is-W	Wsdi|Wpdi
beag	beag	beag-A	Aqp
aird	aird	ard-N	Ncfsc|Ncmsg
a	a	a-Q	Q-r
thabharfaidís	thabharfaidís	tabhair-V	Vmc-3p
feasta	feasta	feasta-R	Rg
ar	ar	ar-S	Sp
thuairimí	thuairimí	tuairim-N	Ncfpc
na	na	na-T	Td-p
mbuachaillí	mbuachaillí	buachaill-N	Ncmpg
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
mise	mise	mé-P	Pp1-s-e
ag	ag	ag-S	Sp
ceapadh	ceapadh	ceap-N	Nv
nach	nach	is-W	Wprin
iad	iad	iad-P	Pp3-p
na	na	na-T	Td-p
scannáin	scannáin	scannán-N	Ncmpc
le	le	le-S	Sp
le	le	le-S	Sp
cailíní	cailíní	cailín-N	Ncmpc
agus	agus	agus-C	Cc
chéanna	chéanna	céanna-A	Aqp
a	a	a-Q	Q-r
thaitníonn	thaitníonn	taitin-V	Vmip
buachaillí	buachaillí	buachaill-N	Ncmpc
,	,	,-F	Fi
ar	ar	ar-S	Sp
aon	aon	aon-D	Dq
chaoi	chaoi	caoi-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Sinéad	Sinéad	Sinéad-N	Npfsc
.	.	.-F	Fe
'	'	'-F	Fa
Sin	Sin	sin-W	W
é	é	é-P	Pp3ms
a	a	a-Q	Q-r
deir	deir	abair-V	Vmip
mo	mo	mo-D	Dp1-s
Mham	Mham	mam-N	Ncfsc
faoin	faoin	faoi-S	Spa-s
teilifís	teilifís	teilifís-N	Ncfsc
freisin	freisin	freisin-R	Rg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Méabh	Méabh	Méabh-N	Npfsc
.	.	.-F	Fe
'	'	'-F	Fa
Bíonn	Bíonn	bí-V	Vmig
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
di	di	do-P	Pr3fs
mar	mar	mar-S	Sp
gheall	gheall	geall-N	Ncmsc
go	go	go-Q	Q
mbíonn	mbíonn	bí-V	Vmig
mo	mo	mo-D	Dp1-s
Dhaid	Dhaid	Daid-N	Npmsc
agus	agus	agus-C	Cc
mo	mo	mo-D	Dp1-s
chuid	chuid	cuid-N	Ncfsc
deartháireacha	deartháireacha	deartháir-N	Ncmpg
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
ag	ag	ag-S	Sp
breathnú	breathnú	breathnaigh-N	Nv
ar	ar	ar-S	Sp
chláracha	chláracha	clár-N	Ncmpc
nach	nach	nach-Q	Qnr
mbíonn	mbíonn	bí-V	Vmig
suim	suim	suim-N	Ncfsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
beo	beo	beo-A	Aqp
aici	aici	ag-P	Pr3fs
féin	féin	féin-P	Px
iontu	iontu	i-P	Pr3-p
.	.	.-F	Fe
'	'	'-F	Fa
Shocraigh	Shocraigh	socraigh-V	Vmis
na	na	na-T	Td-p
cailíní	cailíní	cailín-N	Ncmpc
ansin	ansin	ansin-R	Rt|Rl
gurb	gurb	is-W	Wpdi
amhlaidh	amhlaidh	amhlaidh-R	Rg
a	a	a-Q	Q-r
thógfaidís	thógfaidís	tóg-V	Vmc-3p
DVD	DVD	DVD-Y	Y
amach	amach	amach-R	Rd
ar	ar	ar-S	Sp
cíos	cíos	cíos-N	Ncmsc
an	an	an-T	Td-s
tseachtain	tseachtain	seachtain-N	Ncfsc
dár	dár	do-S	Spp-p
gcionn	gcionn	ceann-N	Ncfsd
.	.	.-F	Fe
Ag	Ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
a	a	a-Q	Q-r
theacht	theacht	teacht-V	Vmis
ar	ar	ar-S	Sp
réiteach	réiteach	réitigh-N	Nv
faoi	faoi	faoi-S	Sp
cé	cé	cé-N	Ncfsc
acu	acu	ag-P	Pr3-p
a	a	a-Q	Q-r
phiocfadh	phiocfadh	pioc-V	Vmc
an	an	an-T	Td-s
DVD	DVD	DVD-Y	Y
agus	agus	agus-C	Cc
cén	cén	cé-W	W--q|Dw--s
méid	méid	méid-N	Ncfsc
airgead	airgead	airgead-N	Ncmsc
póca	póca	póca-N	Ncmsg|Ncmsc
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhéadfaidís	fhéadfaidís	féad-V	Vmc-3p
a	a	a-U	U
choinneáil	choinneáil	coinnigh-N	Nv
le	le	le-S	Sp
caitheamh	caitheamh	caith-N	Nv
ar	ar	ar-S	Sp
rudaí	rudaí	rud-N	Ncmpc
milse	milse	milis-A	Aq--pc|Aq--pv|Aq--pg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
dhíle	dhíle	díle-N	Ncfsc
bháistí	bháistí	báistigh-A	Av
gan	gan	gan-S	Sp
choinne	choinne	coinne-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
An	An	an-T	Td-s
diabhal	diabhal	diabhal-N	Ncmsc
de	de	de-S	Sp
bháisteach	bháisteach	báisteach-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Sinéad	Sinéad	Sinéad-N	Npfsc
go	go	go-U	Ua
cantalach	cantalach	cantalach-A	Aqp
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
léim	léim	léim-N	Nv
anuas	anuas	anuas-R	Rd
den	den	de-S	Spa-s
chlaí	chlaí	claí-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
lá	lá	lá-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
nach	nach	nach-Q	Qnr
mbíonn	mbíonn	bí-V	Vmig
báisteach	báisteach	báistigh-N	Ncfsc|Nv
againn	againn	ag-P	Pr1-p
sa	sa	i-S	Spa-s
tír	tír	tír-N	Ncfsc
seo	seo	seo-D	Dd
?	?	?-F	Fq
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
tinn	tinn	tinn-A	Aqp
tuirseach	tuirseach	tuirseach-A	Aqp
di	di	do-P	Pr3fs
.	.	.-F	Fe
'	'	'-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
aontaigh	aontaigh	aontaigh-V	Vmm-2s
Méabh	Méabh	Méabh-N	Npfsc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
'	'	'-F	Fa
Samhradh	Samhradh	samhradh-N	Ncmsc
,	,	,-F	Fi
mar	mar	mar-S	Sp
dhea	dhea	dea-N	Ns-s
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
'	'	'-F	Fa
Beidh	Beidh	bí-V	Vmif
mo	mo	mo-D	Dp1-s
chuid	chuid	cuid-N	Ncfsc
bróg	bróg	bróg-N	Ncfpg
nua	nua	nua-A	Aqp
millte	millte	mill-A	Av
ormsa	ormsa	ar-P	Pr1-s-e
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Denise	Denise	Denise-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Agus	Agus	agus-C	Cc
mé	mé	mé-P	Pp1-s
tar éis	tar éis	tar_éis-S	Spc
lán	lán	lán-N	Ncmpg
laidhre	laidhre	ladhar-N	Ncfsg
a	a	a-U	U
chaitheamh	chaitheamh	caith-N	Nv
orthu	orthu	ar-P	Pr3-p
do	do	do-Q	Q
bhainis	bhainis	bain-V	Vmis1s
m	m	m-X	Xl
’	’	’-F	Fa
uncail	uncail	uncail-N	Ncmsc
an	an	an-T	Td-s
tseachtain	tseachtain	seachtain-N	Ncfsc
seo	seo	seo-D	Dd
caite	caite	caith-A	Av
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Gabh	Gabh	gabh-V	Vmm-2s
i	i	i-S	Sp
leith	leith	leith-N	Ncfsc
uaibh	uaibh	ó-P	Pr2-p
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
!	!	!-F	Fe
Is	Is	is-W	Wp-i
fearr	fearr	maith-A	Aqc
dúinn	dúinn	do-P	Pr1-p
rith	rith	rith-N	Ncmsc
abhaile	abhaile	abhaile-R	Rd
nó	nó	nó-C	Cc
beidh	beidh	bí-V	Vmif
muid	muid	muid-P	Pp1-p
báite	báite	báigh-A	Av
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Sinéad	Sinéad	Sinéad-N	Npfsc
.	.	.-F	Fe
'	'	'-F	Fa
Ar	Ar	ar-S	Sp
aon	aon	aon-D	Dq
chaoi	chaoi	caoi-N	Ncfsc
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
mise	mise	mé-P	Pp1-s-e
‑	‑	‑-F	Fb
deireanach	deireanach	deireanach-A	Aqp
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
isteach	isteach	isteach-R	Rd
aréir	aréir	aréir-N	Ns-s|Rt|Ns-s
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
mo	mo	mo-D	Dp1-s
mháthair	mháthair	máthair-N	Ncfsc
ag	ag	ag-S	Sp
gabháil	gabháil	gabh-N	Nv
in	in	i-S	Sp
aer	aer	aer-N	Ncmsc
.	.	.-F	Fe
Má	Má	má-C	Cs
bhím	bhím	bí-V	Vmig1s
deireanach	deireanach	deireanach-A	Aqp
arís	arís	arís-R	Rg
anocht	anocht	anocht-N	Ns-s|Rt
tabharfaidh	tabharfaidh	tabhair-V	Vmif
sí	sí	sí-P	Pp3fsn
leathmharú	leathmharú	maraigh-N	Ncmsc|Nv
orm	orm	ar-P	Pr1-s
agus	agus	agus-C	Cc
gach	gach	gach-D	Dq
seans	seans	seans-N	Ncmsc
gur	gur	is-W	Wsdi|Wpdi
coinnithe	coinnithe	coinnigh-A	Av
istigh	istigh	istigh-R	Rl
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
a	a	a-Q	Q-r
bheidh	bheidh	bí-V	Vmif
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
deireadh	deireadh	deireadh-N	Ncmsc
seachtaine	seachtaine	seachtain-N	Ncfsg
seo	seo	seo-D	Dd
chugainn	chugainn	chuig-P	Pr1-p
.	.	.-F	Fe
'	'	'-F	Fa
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
ar	ar	ar-S	Sp
chor	chor	cor-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
le	le	le-S	Sp
gabháil	gabháil	gabh-N	Nv
ag	ag	ag-S	Sp
Sinéad	Sinéad	Sinéad-N	Npfsc
agus	agus	agus-C	Cc
Denise	Denise	Denise-N	Npmsc
,	,	,-F	Fi
ó	ó	ó-C	Cs
tharla	tharla	tarlaigh-V	Vmis
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
siad	siad	siad-P	Pp3-pn
ina	ina	i-S	Spp-p
gcónaí	gcónaí	cónaí-N	Ncmsc
ar	ar	ar-S	Sp
Shráid	Shráid	sráid-N	Ncfsc
an	an	an-T	Td-s
Aonaigh	Aonaigh	aonach-N	Ncmsg
,	,	,-F	Fi
an	an	an-T	Td-s
tsráid	tsráid	sráid-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
díreach	díreach	díreach-N	Ncmsc
taobh	taobh	taobh-N	Ncmsc
thiar	thiar	thiar-R	Rd
den	den	de-S	Spa-s
phictiúrlann	phictiúrlann	pictiúrlann-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
teach	teach	teach-N	Ncmsc
Mhéibhe	Mhéibhe	Méabh-N	Npf-g
,	,	,-F	Fi
áfach	áfach	áfach-R	Rg
,	,	,-F	Fi
píosa	píosa	píosa-N	Ncmsc
maith	maith	maith-A	Aq-msc
as	as	as-N	Ncmpg
láthair	láthair	láthar-N	Ncfsc|Ncmsg
ar	ar	ar-S	Sp
an	an	an-T	Td-s
taobh	taobh	taobh-N	Ncmsc
eile	eile	eile-D	Dd
den	den	de-S	Spa-s
bhaile	bhaile	baile-N	Ncmsc
.	.	.-F	Fe
Bheadh	Bheadh	bí-V	Vmc
siúlóid	siúlóid	siúlóid-N	Ncfsc
fiche	fiche	fiche-N	Ncmsc|Mc
nóiméad	nóiméad	nóiméad-N	Ncmpg|Ncmsc|Ncmpg
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
laghad	laghad	laghad-N	Ncmsc
le	le	le-S	Sp
cur	cur	cuir-N	Nv
di	di	do-P	Pr3fs
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
t	t	t-X	Xl
‑	‑	‑-F	Fb
ádh	ádh	ádh-N	Ncmsc
dearg	dearg	dearg-A	Aq-msc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbeirt	mbeirt	beirt-N	Ncfsc
agaibhse	agaibhse	ag-P	Pr2-p-e
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Méabh	Méabh	Méabh-N	Npfsc
lena	lena	le-S	Spp-s
cairde	cairde	cairde-N	Ncmpc|Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
éad	éad	éad-N	Ncmsc
orm	orm	ar-P	Pr1-s
libh	libh	le-P	Pr2-p
.	.	.-F	Fe
Beidh	Beidh	bí-V	Vmif
sibhse	sibhse	sibh-P	Pp2-p-e
ag	ag	ag-S	Sp
baile	baile	baile-N	Ncmsc
taobh istigh	taobh istigh	taobh_istigh-R	Rl
de	de	de-S	Sp
chúpla	chúpla	cúpla-N	Ncmsc
nóiméad	nóiméad	nóiméad-N	Ncmpg
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
beidh	beidh	bí-V	Vmif
mise	mise	mé-P	Pp1-s-e
báite	báite	báigh-A	Av
go	go	go-S	Sp
craiceann	craiceann	craiceann-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Ach	Ach	ach-C	Cs
nach	nach	is-W	Wpsin|Wpdin|Wpdqn|Wp-qn
bhféadfá	bhféadfá	féad-V	Vmc-2s
fanacht	fanacht	fanacht-N	Ncmsc
ar	ar	ar-S	Sp
foscadh	foscadh	foscadh-N	Ncmsc
go	go	go-Q	Q
dtiocfaidh	dtiocfaidh	tar-V	Vmif
an	an	an-T	Td-s
bus	bus	bus-N	Ncmsc
?	?	?-F	Fq
Nach	Nach	is-W	Wp-qn
in	in	sin-P	Pd
a	a	a-Q	Q-r
dhéanann	dhéanann	déan-V	Vmip
tú	tú	tú-P	Pp2-s
de	de	de-S	Sp
ghnáth	ghnáth	gnáth-N	Ncmsc
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Denise	Denise	Denise-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Dhera	Dhera	Dhera-N	Npmsc
,	,	,-F	Fi
ní	ní	is-W	Wp-in
féidir	féidir	féidir-N	Ns-s
brath	brath	braith-N	Ncmsc|Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbus	mbus	bus-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Méabh	Méabh	Méabh-N	Npfsc
.	.	.-F	Fe
'	'	'-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
fhéadfainn	fhéadfainn	féad-V	Vmc-1s
a	a	a-U	U
bheith	bheith	bí-N	Nv
ansin	ansin	ansin-R	Rt|Rl
leathuair	leathuair	leathuair-N	Ncfsc
.	.	.-F	Fe
Feicfidh	Feicfidh	feic-V	Vmif
mé	mé	mé-P	Pp1-s
sibh	sibh	sibh-P	Pp2-p
ar	ar	ar-S	Sp
maidin	maidin	maidin-N	Ncfsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
súil	súil	súil-N	Ncfsc
agam	agam	ag-P	Pr1-s
go	go	go-Q	Q
mbeidh	mbeidh	bí-V	Vmif
feabhas	feabhas	feabhas-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
tagtha	tagtha	tar-A	Av
ar	ar	ar-S	Sp
an	an	an-T	Td-s
aimsir	aimsir	aimsir-N	Ncfsc
faoin	faoin	faoi-S	Spa-s
am	am	am-N	Ncmsc
sin	sin	sin-D	Dd
.	.	.-F	Fe
'	'	'-F	Fa
Agus	Agus	agus-C	Cc
leis	leis	le-S	Sp
sin	sin	sin-P	Pd
d	d	d-X	Xl
’	’	’-F	Fa
fhág	fhág	fág-V	Vmis
an	an	an-T	Td-s
triúr	triúr	triúr-N	Ncmsc
slán	slán	slán-A	Aq-msc
ag	ag	ag-S	Sp
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fháisc	fháisc	fáisc-V	Vmis
Méabh	Méabh	Méabh-N	Npfsc
an	an	an-T	Td-s
seaicéad	seaicéad	seaicéad-N	Ncmsc
éadrom	éadrom	éadrom-A	Aq-msc
denime	denime	denime-N	Ncfsc
timpeall	timpeall	timpeall-S	Sp|Rd
uirthi	uirthi	ar-P	Pr3fs
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
í	í	í-P	Pp3fs
féin	féin	féin-P	Px
a	a	a-U	U
choinneáil	choinneáil	coinnigh-N	Nv
tirim	tirim	tirim-A	Aqp
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ba	ba	is-W	Ws|Ws-i
bheag	bheag	beag-A	Aqp
an	an	an-T	Td-s
mhaith	mhaith	maith-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Níorbh	Níorbh	is-W	Ws-in
fhada	fhada	fada-A	Aqc|Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
ina	ina	i-S	Spp-s|Spp-p
líbín	líbín	líbín-N	Ncmsc
báite	báite	báigh-A	Av
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
le	le	le-S	Sp
bheith	bheith	bí-N	Nv
préachta	préachta	préach-A	Av
leis	leis	le-S	Sp
an	an	an-T	Td-s
bhfuacht	bhfuacht	fuacht-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
dar	dar	dar-S	Sp
ndóigh	ndóigh	dóigh-N	Ncfsc
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
cuid	cuid	cuid-N	Ncfsc
den	den	de-S	Spa-s
mhilleán	mhilleán	milleán-N	Ncmsc
uirthi	uirthi	ar-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sí	sí	sí-P	Pp3fsn
gléasta	gléasta	gléas-A	Av
don	don	do-S	Spa-s
sórt	sórt	sórt-N	Ncmsc
sin	sin	sin-D	Dd
aimsire	aimsire	aimsir-N	Ncfsg
.	.	.-F	Fe
Dá	Dá	dá-C	Cs
dtabharfadh	dtabharfadh	tabhair-V	Vmc
sí	sí	sí-P	Pp3fsn
toradh	toradh	toradh-N	Ncmsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
máthair	máthair	máthair-N	Ncfsc
an	an	an-T	Td-s
mhaidin	mhaidin	maidin-N	Ncfsc
sin	sin	sin-D	Dd
bheadh	bheadh	bí-V	Vmc
a	a	a-D	Dp3
cóta	cóta	cóta-N	Ncmsc
báistí	báistí	báistigh-A	Av
tugtha	tugtha	tabhair-A	Av
léi	léi	le-P	Pr3fs
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
ghráin	ghráin	gráin-N	Ncfsc
dhearg	dhearg	dearg-A	Aq-fsc
aici	aici	ag-P	Pr3fs
ar	ar	ar-S	Sp
an	an	an-T	Td-s
seanliobar	seanliobar	liobar-N	Ncmsc
de	de	de-S	Sp
chóta	chóta	cóta-N	Ncmsc
céanna	céanna	céanna-A	Aqp
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
ligfeadh	ligfeadh	lig-V	Vmc----n
an	an	an-T	Td-s
náire	náire	náire-N	Ncfsc
di	di	do-P	Pr3fs
a	a	a-D	Dp3
leithéid	leithéid	leithéid-N	Ncfsc
de	de	de-S	Sp
rud	rud	rud-N	Ncmsc
gránna	gránna	gránna-A	Aqp
a	a	a-U	U
chaitheamh	chaitheamh	caith-N	Nv
go	go	go-U	Ua
poiblí	poiblí	poiblí-A	Aqp
.	.	.-F	Fe
Bronntanas	Bronntanas	bronntanas-N	Ncmsc
'	'	'-F	Fa
praiticiúil	praiticiúil	praiticiúil-A	Aqp
’	’	’-F	Fa
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sa	sa	i-S	Spa-s
gcóta	gcóta	cóta-N	Ncmsc
sin	sin	sin-D	Dd
a	a	a-Q	Q-r
thug	thug	tabhair-V	Vmis
a	a	a-D	Dp3
haintín	haintín	aintín-N	Ncfsg
Úna	Úna	Úna-N	Npf-g|Npfsc
di	di	do-P	Pr3fs
an	an	an-T	Td-s
Nollaig	Nollaig	Nollaig-N	Ncfsc
roimhe	roimhe	roimh-P	Pr3ms
sin	sin	sin-P	Pd
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
amhras	amhras	amhras-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
ar	ar	ar-S	Sp
Mhéabh	Mhéabh	Méabh-N	Npfsc
ach	ach	ach-C	Cs
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
chuile	chuile	gach-D	Dq
dhuine	dhuine	duine-N	Ncmsc
ag	ag	ag-S	Sp
spochadh	spochadh	spoch-N	Nv
aisti	aisti	as-P	Pr3fs
dá	dá	dá-C	Cs
gcaithfeadh	gcaithfeadh	caith-V	Vmc
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
cóta	cóta	cóta-N	Ncmsc
sin	sin	sin-D	Dd
–	–	–-X	Xx
fiú	fiú	fiú-N	Ns-s|Ncmsc|Rg
amháin	amháin	amháin-A	Aqp
na	na	na-T	Td-p
buachaillí	buachaillí	buachaill-N	Ncmpc
deasa	deasa	deas-A	Aq--pv|Aq--pg|Aq--pc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
babhláil	babhláil	babhláil-N	Nv
leo	leo	le-P	Pr3-p
níos	níos	níos-U	Uc
túisce	túisce	túisce-R	Rt
sa	sa	i-S	Spa-s
lá	lá	lá-N	Ncmsc
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
dona	dona	dona-A	Aqp
go leor	go leor	go_leor-A	Aq
go	go	go-Q	Q
mbíodh	mbíodh	bí-V	Vmih
an	an	an-T	Td-s
chulaith	chulaith	culaith-N	Ncfsc
scoile	scoile	scoil-N	Ncfsg
b	b	b-X	Xl
’	’	’-F	Fa
uafásaí	uafásaí	uafásach-A	Aqc
dá	dá	dá-C	Cs
bhfaca	bhfaca	feic-V	Vmis---d
tú	tú	tú-P	Pp2-s
riamh	riamh	riamh-R	Rg
uirthi	uirthi	ar-P	Pr3fs
cúig	cúig	cúig-N	Ncmsc
lá	lá	lá-N	Ncmsc
na	na	na-T	Tdfsg
seachtaine	seachtaine	seachtain-N	Ncfsg
gan	gan	gan-S	Sp
í	í	í-P	Pp3fs
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
óinseach	óinseach	óinseach-N	Ncfpg
di	di	do-P	Pr3fs
féin	féin	féin-P	Px
os comhair	os comhair	os_comhair-S	Spc
an	an	an-T	Td-s
tsaoil	tsaoil	saol-N	Ncmsg
le linn	le linn	le_linn-S	Spc
an	an	an-T	Td-s
deireadh	deireadh	deireadh-N	Ncmsc
seachtaine	seachtaine	seachtain-N	Ncfsg
!	!	!-F	Fe
Ag	Ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
cuimhneamh	cuimhneamh	cuimhnigh-N	Ncmpg|Ncmsc|Nv
ar	ar	ar-S	Sp
bhealach	bhealach	bealach-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
a	a	a-Q	Q-i
bhféadfadh	bhféadfadh	féad-V	Vmc
an	an	an-T	Td-s
cóta	cóta	cóta-N	Ncmsc
céanna	céanna	céanna-A	Aqp
'	'	'-F	Fa
imeacht	imeacht	imigh-N	Ncmsc|Nv
amú	amú	amaigh-R	Rg|Nv
’	’	’-F	Fa
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Méabh	Méabh	Méabh-N	Npfsc
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
timpeall	timpeall	timpeall-S	Sp
an	an	an-T	Td-s
choirnéil	choirnéil	coirnéal-N	Ncmsg
ag	ag	ag-S	Sp
Sráid	Sráid	sráid-N	Ncfsc
Thomáis	Thomáis	Tomás-N	Npfsg|Npm-g
.	.	.-F	Fe
Is	Is	is-W	Wp-i
ansin	ansin	ansin-R	Rt|Rl
a	a	a-Q	Q-r
bhuail	bhuail	buail-V	Vmis
an	an	an-T	Td-s
stolladh	stolladh	stolladh-N	Ncmsc
gaoithe	gaoithe	gaoth-N	Ncfsg
í	í	í-P	Pp3fs
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
bheag	bheag	beag-A	Aqp
nár	nár	nár-Q	Qnrs
baineadh	baineadh	bain-V	Vmis0--n
an	an	an-T	Td-s
anáil	anáil	anáil-N	Ncfsc
di	di	de-P	Pr3fs
.	.	.-F	Fe
'	'	'-F	Fa
Samhradh	Samhradh	samhradh-N	Ncmsc
,	,	,-F	Fi
mar	mar	mar-S	Sp
dhea	dhea	dea-N	Ns-s
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
ina	ina	i-S	Spp-s
hintinn	hintinn	intinn-N	Ncfsc
féin	féin	féin-P	Px
arís	arís	arís-R	Rg
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
crith	crith	crith-N	Nv
leis	leis	le-S	Sp
an	an	an-T	Td-s
bhfuacht	bhfuacht	fuacht-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Samhradh	Samhradh	samhradh-N	Ncmsc
in	in	sin-P	Pd
éirinn	éirinn	éir-V	Vmih1s
!	!	!-F	Fe
'	'	'-F	Fa
Tháinig	Tháinig	tar-V	Vmis
carr	carr	carr-N	Ncmsc|Ncfsc
anuas	anuas	anuas-R	Rd
Sráid	Sráid	sráid-N	Ncfsc
Thomáis	Thomáis	Tomás-N	Npfsg|Npm-g
go	go	go-U	Ua
mall	mall	mall-A	Aqp
réidh	réidh	réidh-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
bháisteach	bháisteach	báisteach-N	Ncfsc
chomh	chomh	chomh-R	Ri
trom	trom	trom-A	Aqp
faoin	faoin	faoi-S	Spa-s
am	am	am-N	Ncmsc
sin	sin	sin-D	Dd
gur	gur	is-W	Wsdi
ar	ar	ar-S	Sp
éigean	éigean	éigean-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Méabh	Méabh	Méabh-N	Npfsc
in ann	in ann	in_ann-S	Spc
soilse	soilse	solas-N	Ncfsg|Ncmpg|Ncfsg|Ncmpg
an	an	an-T	Td-s
chairr	chairr	carr-N	Ncmsg
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
amach	amach	amach-R	Rd
ar	ar	ar-S	Sp
chor	chor	cor-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
chlapsholas	chlapsholas	clapsholas-N	Ncmsc
agus	agus	agus-C	Cc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
carr	carr	carr-N	Ncmsc|Ncfsc
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
thairsti	thairsti	thar-P	Pr3fs
scairt	scairt	scairt-N	Ncfsc
léas	léas	léas-N	Ncmsc|Ncfpg|Ncfsc
solais	solais	solas-N	Ncmsg
uaidh	uaidh	ó-P	Pr3ms
.	.	.-F	Fe
Is	Is	is-W	Wp-i
ansin	ansin	ansin-R	Rt|Rl
a	a	a-Q	Q-r
thug	thug	tabhair-V	Vmis
Méabh	Méabh	Méabh-N	Npfsc
faoi	faoi	faoi-S	Sp
deara	deara	deara-N	Ns-s
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
duine	duine	duine-N	Ncmsc
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcosán	gcosán	cosán-N	Ncmsc
díreach	díreach	díreach-A	Aq-msc
trasna	trasna	trasna-S	Sp
na	na	na-T	Tdfsg
sráide	sráide	sráid-N	Ncfsg
uaithi	uaithi	ó-P	Pr3fs
‑	‑	‑-F	Fb
duine	duine	duine-N	Ncmsc
ard	ard	ard-A	Aq-msc
tanaí	tanaí	tanaí-A	Aqp
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
cochall	cochall	cochall-N	Ncmsc
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
cheann	cheann	ceann-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
fhéadfadh	fhéadfadh	féad-V	Vmc----n
sí	sí	sí-P	Pp3fsn
a	a	a-U	U
mhionnú	mhionnú	mionnaigh-N	Nv
ar	ar	ar-S	Sp
dtús	dtús	tús-N	Ncmsc
go	go	go-Q	Q
bhfaca	bhfaca	feic-V	Vmis---d
sí	sí	sí-P	Pp3fsn
duine	duine	duine-N	Ncmsc
.	.	.-F	Fe
An	An	an-Q	Qq
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
á	á	do-S	Spo-s
shamhlú	shamhlú	samhlaigh-N	Nv
?	?	?-F	Fq
Ach	Ach	ach-C	Cs
ansin	ansin	ansin-R	Rt|Rl
sheas	sheas	seas-V	Vmis
sí	sí	sí-P	Pp3fsn
nóiméad	nóiméad	nóiméad-N	Ncmsc
agus	agus	agus-C	Cc
chuimil	chuimil	cuimil-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
cuid	cuid	cuid-N	Ncfsc
súl	súl	súil-N	Ncfpg
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
…	…	…-F	Fi
is	is	is-W	Wp-i
ea	ea	ea-P	Pp3-s
…	…	…-F	Fi
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
duine	duine	duine-N	Ncmsc
ann	ann	ann-R	Rl
ceart	ceart	ceart-N	Ncmsc
go leor	go leor	go_leor-A	Aq
.	.	.-F	Fe
é	é	é-P	Pp3ms
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
ansin	ansin	ansin-R	Rt|Rl
ina	ina	i-S	Spp-s|Spp-p
staic	staic	staic-N	Ncfsc
ag	ag	ag-S	Sp
breathnú	breathnú	breathnaigh-N	Nv
trasna	trasna	trasna-S	Sp
na	na	na-T	Tdfsg
sráide	sráide	sráid-N	Ncfsg
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
arís	arís	arís-R	Rg
ar ais	ar ais	ar_ais-R	Rd
cén	cén	cé-D	Dw--s
fáth	fáth	fáth-N	Ncmsc
nach	nach	nach-Q	Qnr
mbeadh	mbeadh	bí-V	Vmc
?	?	?-F	Fq
Bhí	Bhí	bí-V	Vmis
neart	neart	neart-N	Ncmsc
daoine	daoine	duine-N	Ncmpg|Ncmpc
amuigh	amuigh	amuigh-R	Rl
an	an	an-T	Td-s
oíche	oíche	oíche-N	Ncfsc
Shathairn	Shathairn	Satharn-N	Ncmsg
seo	seo	seo-D	Dd
.	.	.-F	Fe
Mar	Mar	mar-C	Cs
a	a	a-Q	Q-r
bhíodh	bhíodh	bí-V	Vmih
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
ag	ag	ag-S	Sp
deireadh	deireadh	deireadh-N	Ncmsc
na	na	na-T	Tdfsg
seachtaine	seachtaine	seachtain-N	Ncfsg
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
is	is	is-W	Wp-i
é	é	é-P	Pp3ms
an	an	an-T	Td-s
rud	rud	rud-N	Ncmsc
a	a	a-Q	Q-r
chuir	chuir	cuir-V	Vmis
t	t	t-X	Xl
‑	‑	‑-F	Fb
iontas	iontas	iontas-N	Ncmsc
–	–	–-X	Xx
agus	agus	agus-C	Cc
sórt	sórt	sórt-N	Ncmpg|Ncmsc|Ncmpg
imní	imní	imní-N	Ncfsg
–	–	–-X	Xx
ar	ar	ar-S	Sp
Mhéabh	Mhéabh	Méabh-N	Npfsc
ná	ná	ná-C	Cc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
duine	duine	duine-N	Ncmsc
seo	seo	seo-D	Dd
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
gan	gan	gan-S	Sp
cor	cor	cor-N	Ncmsc
as	as	as-N	Ncmpg
agus	agus	agus-C	Cc
an	an	an-T	Td-s
chuma	chuma	cuma-N	Ncfsc
air	air	ar-N	Ncmsg
gur	gur	is-W	Wsdi
ag	ag	ag-S	Sp
stánadh	stánadh	stán-N	Nv
ina	ina	i-S	Spp-s
treo	treo	treo-N	Ncmsc
féin	féin	féin-P	Px
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sé	sé	sé-P	Pp3msn
ar nós	ar nós	ar_nós-S	Spc
daoine	daoine	duine-N	Ncmpg
eile	eile	eile-D	Dd
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
amuigh	amuigh	amuigh-R	Rl
an	an	an-T	Td-s
tráthnóna	tráthnóna	tráthnóna-N	Ncmsc
gránna	gránna	gránna-A	Aqp
seo	seo	seo-D	Dd
,	,	,-F	Fi
a	a	a-D	Dp3
gcloigne	gcloigne	cloigeann-N	Ncmpg
fúthu	fúthu	faoi-P	Pr3-p
acu	acu	ag-P	Pr3-p
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
éalú	éalú	éalú-N	Ncmsg
chomh	chomh	chomh-R	Ri
tapa	tapa	tapa-A	Aqp
agus	agus	agus-C	Cc
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhéadfaidís	fhéadfaidís	féad-V	Vmc-3p
ón	ón	ó-S	Spa-s
mbáisteach	mbáisteach	báisteach-N	Ncfsc
agus	agus	agus-C	Cc
ón	ón	ó-S	Spa-s
bhfuacht	bhfuacht	fuacht-N	Ncmsc
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
níos	níos	níos-U	Uc
sciobtha	sciobtha	sciobtha-A	Aqc
.	.	.-F	Fe
Níorbh	Níorbh	is-W	Ws-in
fhada	fhada	fada-A	Aqc|Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
sodar	sodar	sodar-N	Ncmsc
.	.	.-F	Fe
Dar	Dar	dar-S	Sp
ndóigh	ndóigh	dóigh-N	Ncfsc
,	,	,-F	Fi
thuig	thuig	tuig-V	Vmis
sí	sí	sí-P	Pp3fsn
go	go	go-U	Ua
rímhaith	rímhaith	maith-A	Aqp
nach	nach	nach-Q	Qnr
bhféadfadh	bhféadfadh	féad-V	Vmc
sí	sí	sí-P	Pp3fsn
rith	rith	rith-N	Ncmsc|Nv
an	an	an-T	Td-s
bealach	bealach	bealach-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
abhaile	abhaile	abhaile-R	Rd
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sí	sí	sí-P	Pp3fsn
chomh	chomh	chomh-R	Ri
haclaí	haclaí	aclaí-A	Aqp
sin	sin	sin-P	Pd|Dd
!	!	!-F	Fe
Go	Go	go-U	Ua
deimhin	deimhin	deimhin-A	Aqp
féin	féin	féin-P	Px
,	,	,-F	Fi
déarfadh	déarfadh	abair-V	Vmc
a	a	a-D	Dp3
múinteoir	múinteoir	múinteoir-N	Ncmsc
corpoideachais	corpoideachais	corpoideachas-N	Ncmsg
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
sí	sí	sí-P	Pp3fsn
aclaí	aclaí	aclaí-A	Aqp
ar	ar	ar-S	Sp
chor	chor	cor-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
.	.	.-F	Fe
Chomh	Chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
leis	leis	le-S	Sp
sin	sin	sin-P	Pd
chaithfeadh	chaithfeadh	caith-V	Vmc
sí	sí	sí-P	Pp3fsn
siúl	siúl	siúil-N	Ncmsc|Nv
in aghaidh	in aghaidh	in_aghaidh-S	Spc
an	an	an-T	Td-s
chnoic	chnoic	cnoc-N	Ncmsg
agus	agus	agus-C	Cc
na	na	na-T	Tdfsg
gaoithe	gaoithe	gaoth-N	Ncfsg
an	an	an-T	Td-s
chuid	chuid	cuid-N	Ncfsc
is	is	is-U	U
mó	mó	mór-A	Aqc
den	den	de-S	Spa-s
bhealach	bhealach	bealach-N	Ncmsc
abhaile	abhaile	abhaile-R	Rd
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
anuas	anuas	anuas-R	Rd
air	air	ar-P	Pr3ms
sin	sin	sin-P	Pd
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
ghaoth	ghaoth	gaoth-N	Ncfsc
ag	ag	ag-S	Sp
séideadh	séideadh	séid-N	Nv
ina	ina	i-S	Spp-s
gála	gála	gála-N	Ncmsc
faoin	faoin	faoi-S	Spa-s
am	am	am-N	Ncmsc
sin	sin	sin-D	Dd
.	.	.-F	Fe
ó	ó	ó-C	Cs
tharla	tharla	tarlaigh-V	Vmis
a	a	a-D	Dp3
cuid	cuid	cuid-N	Ncfsc
éadaigh	éadaigh	éadach-N	Ncmsg
agus	agus	agus-C	Cc
a	a	a-D	Dp3
cuid	cuid	cuid-N	Ncfsc
buataisí	buataisí	buatais-N	Ncfpg
a	a	a-U	U
bheith	bheith	bí-N	Nv
báite	báite	báigh-A	Av
fliuch	fliuch	fliuch-A	Aqp
bhraith	bhraith	braith-V	Vmis
Méabh	Méabh	Méabh-N	Npfsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
níos	níos	níos-U	Uc
mó	mó	mór-A	Aqc
stró	stró	stró-N	Ncmsg
ná	ná	ná-C	Cs|Cc
mar	mar	mar-C	Cs
ba	ba	is-W	Wsri
cheart	cheart	ceart-A	Aqp
ag	ag	ag-S	Sp
baint	baint	bain-N	Nv
le	le	le-S	Sp
chuile	chuile	cuile-N	Ncfsc
choiscéim	choiscéim	coiscéim-N	Ncfsc
a	a	a-Q	Q-r
thóg	thóg	tóg-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
Ar	Ar	is-W	Ws-q
cheart	cheart	ceart-A	Aqp
di	di	do-P	Pr3fs
a	a	a-D	Dp3
cuid	cuid	cuid-N	Ncfsc
buataisí	buataisí	buatais-N	Ncfpg
a	a	a-U	U
bhaint	bhaint	bain-N	Nv
di	di	de-P	Pr3fs
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
agus	agus	agus-C	Cc
rith	rith	rith-N	Ncmsc|Nv
cosnochta	cosnochta	cosnochta-A	Aqp
?	?	?-F	Fq
'	'	'-F	Fa
Ach	Ach	ach-C	Cs
má	má	má-C	Cs
stopaim	stopaim	stop-V	Vmip1s
cuirfidh	cuirfidh	cuir-V	Vmif
sé	sé	sé-P	Pp3msn
sin	sin	sin-P	Pd
moill	moill	moill-N	Ncfsc
orm	orm	ar-P	Pr1-s
agus	agus	agus-C	Cc
tá	tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
níos	níos	níos-U	Uc
mó	mó	mór-A	Aqc
ná	ná	ná-C	Cs|Cc
leath	leath	leath-N	Ncfpg|Ncfsc|Dq|Ncfpg
bealaigh	bealaigh	bealach-N	Ncmsg
anois	anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
an	an	an-T	Td-s
gcrosbhóthar	gcrosbhóthar	crosbhóthar-N	Ncmsc
faoin	faoin	faoi-S	Spa-s
am	am	am-N	Ncmsc
sin	sin	sin-D	Dd
agus	agus	agus-C	Cc
gan	gan	gan-S	Sp
le	le	le-S	Sp
cur	cur	cuir-N	Nv
di	di	do-P	Pr3fs
aici	aici	ag-P	Pr3fs
ach	ach	ach-S	Sp
dhá	dhá	dó-M	Mc
shráid	shráid	sráid-N	Ncfsc
eile	eile	eile-D	Dd
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
ansin	ansin	ansin-R	Rt|Rl
bheadh	bheadh	bí-V	Vmc
sí	sí	sí-P	Pp3fsn
slán	slán	slán-A	Aqp
tirim	tirim	tirim-A	Aqp
teolaí	teolaí	teolaí-A	Aqp
ina	ina	i-S	Spp-s
teach	teach	teach-N	Ncmsc
féin	féin	féin-P	Px
!	!	!-F	Fe
Sheas	Sheas	seas-V	Vmis
Méabh	Méabh	Méabh-N	Npfsc
ar	ar	ar-S	Sp
imeall	imeall	imeall-N	Ncmsc
an	an	an-T	Td-s
chosáin	chosáin	cosán-N	Ncmsg
lena	lena	le-S	Spp-s
chinntiú	chinntiú	cinntigh-N	Nv
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
sábháilte	sábháilte	sábháil-A	Aqp|Av
an	an	an-T	Td-s
bóthar	bóthar	bóthar-N	Ncmsc
a	a	a-U	U
thrasnú	thrasnú	trasnaigh-N	Nv
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
choisithe	choisithe	coisí-N	Ncmpc
eile	eile	eile-D	Dd
le	le	le-S	Sp
feiceáil	feiceáil	feic-N	Nv
ach	ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
trácht	trácht	trácht-N	Ncmsc
trom	trom	trom-A	Aq-msc
.	.	.-F	Fe
Bóthar	Bóthar	bóthar-N	Ncmsc
contúirteach	contúirteach	contúirteach-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
agus	agus	agus-C	Cc
níor	níor	is-W	Ws-in
mhór	mhór	mór-A	Aqp
do	do	do-S	Sp
dhuine	dhuine	duine-N	Ncmsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
cúramach	cúramach	cúramach-A	Aqp
á	á	do-S	Spo-s
thrasnú	thrasnú	trasnaigh-N	Nv
go	go	go-U	Ua
háirithe	háirithe	áirithe-A	Aqp
ag	ag	ag-S	Sp
an	an	an-T	Td-s
am	am	am-N	Ncmsc
seo	seo	seo-D	Dd
den	den	de-S	Spa-s
oíche	oíche	oíche-N	Ncfsc
.	.	.-F	Fe
Díreach	Díreach	díreach-N	Ncmsc
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
ar	ar	ar-S	Sp
tí	tí	tí-N	Ncfsc
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
trasna	trasna	trasna-R	Rd
chonaic	chonaic	feic-V	Vmis
sí	sí	sí-P	Pp3fsn
arís	arís	arís-R	Rg
é	é	é-P	Pp3ms
–	–	–-X	Xx
an	an	an-T	Td-s
duine	duine	duine-N	Ncmsc
céanna	céanna	céanna-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
stánadh	stánadh	stán-N	Nv
uirthi	uirthi	ar-P	Pr3fs
tamall	tamall	tamall-N	Ncmsc
roimhe	roimhe	roimh-P	Pr3ms
sin	sin	sin-P	Pd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
anois	anois	anois-R	Rt
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcosán	gcosán	cosán-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
taobh	taobh	taobh-N	Ncmsc
eile	eile	eile-D	Dd
den	den	de-S	Spa-s
bhóthar	bhóthar	bóthar-N	Ncmsc
uaithi	uaithi	ó-P	Pr3fs
,	,	,-F	Fi
an	an	an-T	Td-s
cochall	cochall	cochall-N	Ncmsc
fós	fós	fós-R	Rg
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
cheann	cheann	ceann-N	Ncmsc
.	.	.-F	Fe
B	B	B-X	Xl
’	’	’-F	Fa
fhacthas	fhacthas	feic-V	Vmis0--n
do	do	do-S	Sp
Mhéabh	Mhéabh	Méabh-N	Npfsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
fanacht	fanacht	fan-N	Nv
le	le	le-S	Sp
rud	rud	rud-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
…	…	…-F	Fi
nó	nó	nó-C	Cc
le	le	le-S	Sp
duine	duine	duine-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
!	!	!-F	Fe
An	An	is-W	Wp-q
léise	léise	le-P	Pr3fs-e
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
fanacht	fanacht	fan-N	Nv
?	?	?-F	Fq
Murab	Murab	mura-C	Csws
ea	ea	ea-P	Pp3-s
céard	céard	cé-W	W--q
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ar	ar	ar-S	Sp
siúl	siúl	siúil-N	Nv
aige	aige	ag-P	Pr3ms
?	?	?-F	Fq
Cé	Cé	cé-P	Pq
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
chomh	chomh	chomh-R	Ri
díchéillí	díchéillí	díchéillí-A	Aqp
agus	agus	agus-C	Cc
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
ar	ar	ar-S	Sp
thaobh	thaobh	taobh-N	Ncmsc
na	na	na-T	Tdfsg
sráide	sráide	sráid-N	Ncfsg
oíche	oíche	oíche-N	Ncfsg|Ncfsc
mar	mar	mar-S	Sp
seo	seo	seo-P	Pd
agus	agus	agus-C	Cc
an	an	an-T	Td-s
bháisteach	bháisteach	báisteach-N	Ncfsc
ag	ag	ag-S	Sp
stealladh	stealladh	steall-N	Nv
anuas	anuas	anuas-R	Rd
air	air	ar-P	Pr3ms
?	?	?-F	Fq
Tháinig	Tháinig	tar-V	Vmis
fuarallas	fuarallas	fuarallas-N	Ncmsc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Cén	Cén	cé-D	Dw--s
fáth	fáth	fáth-N	Ncmsc
nár	nár	nár-Q	Qnrs
fhan	fhan	fan-V	Vmis---n
sí	sí	sí-P	Pp3fsn
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbus	mbus	bus-N	Ncmsc
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
mhol	mhol	mol-V	Vmis
Denise	Denise	Denise-N	Npmsc
di	di	do-P	Pr3fs
?	?	?-F	Fq
Thosaigh	Thosaigh	tosaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
cuimhneamh	cuimhneamh	cuimhnigh-N	Nv
ar	ar	ar-S	Sp
na	na	na-T	Td-p
scannáin	scannáin	scannán-N	Ncmpc
uafáis	uafáis	uafás-N	Ncmsg|Ncmpc|Ncmsg
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
feicthe	feicthe	feic-A	Av
aici	aici	ag-P	Pr3fs
le	le	le-S	Sp
cúpla	cúpla	cúpla-N	Ncmsc
bliain	bliain	bliain-N	Ncfsc
anuas	anuas	anuas-R	Rd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
radharcanna	radharcanna	radharc-N	Ncmpc
scanrúla	scanrúla	scanrúil-A	Aq--pc
as	as	as-S	Sp
na	na	na-T	Td-p
scannáin	scannáin	scannán-N	Ncmpc
ag	ag	ag-S	Sp
rith	rith	rith-N	Nv
trína	trína	trí-S	Spp-s
ceann	ceann	ceann-N	Ncmsc
.	.	.-F	Fe
Bean	Bean	bean-N	Ncfsc
nó	nó	nó-C	Cc
cailín	cailín	cailín-N	Ncmsg|Ncmsc
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
ina	ina	i-S	Spp-s
haonar	haonar	aonar-N	Ncmsc
ar	ar	ar-S	Sp
shráid	shráid	sráid-N	Ncfsc
dhorcha	dhorcha	dorcha-A	Aqp
nó	nó	nó-C	Cc
ar	ar	ar-S	Sp
bhóthar	bhóthar	bóthar-N	Ncmsc
ciúin	ciúin	ciúin-A	Aq-msc
iargúlta	iargúlta	iargúlta-A	Aqp
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
ansin	ansin	ansin-R	Rt|Rl
,	,	,-F	Fi
gan	gan	gan-S	Sp
aon	aon	aon-D	Dq
choinne	choinne	coinne-N	Ncfsc
leis	leis	le-P	Pr3ms
…	…	…-F	Fi
t	t	t-X	Xl
‑	‑	‑-F	Fb
ionsaí	ionsaí	ionsaí-N	Ncmsc
marfach	marfach	marfach-A	Aq-msc
!	!	!-F	Fe
Bhuel	Bhuel	bhuel-X	Xsc
,	,	,-F	Fi
ní	ní	ní-Q	Qn
tharlódh	tharlódh	tarlaigh-V	Vmc----n
sé	sé	sé-P	Pp3msn
sin	sin	sin-P	Pd
dise	dise	do-P	Pr3fs-e
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
ligfeadh	ligfeadh	lig-V	Vmc----n
sí	sí	sí-P	Pp3fsn
dá	dá	do-S	Spp-s|Spp-p|Spp-s|Spp-p
leithéid	leithéid	leithéid-N	Ncfsc
tarlú	tarlú	tarlaigh-N	Ncmsc|Nv
di	di	do-P	Pr3fs
,	,	,-F	Fi
go	go	go-U	Ua
háirithe	háirithe	áirithe-A	Aqp
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
faoi	faoi	faoi-S	Sp
urchar	urchar	urchar-N	Ncmsc
méaróige	méaróige	méaróg-N	Ncfsg
den	den	de-S	Spa-s
bhaile	bhaile	baile-N	Ncmsc
.	.	.-F	Fe
Shocraigh	Shocraigh	socraigh-V	Vmis
sí	sí	sí-P	Pp3fsn
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
sé	sé	sé-P	Pp3msn
níos	níos	níos-U	Uc
sábháilte	sábháilte	sábháilte-A	Aqc
fanacht	fanacht	fan-N	Ncmsc|Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
taobh	taobh	taobh-N	Ncmsc
den	den	de-S	Spa-s
bhóthar	bhóthar	bóthar-N	Ncmsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
seachas	seachas	seachas-S	Sp
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
trasna	trasna	trasna-R	Rd
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ar	ar	ar-S	Sp
intinn	intinn	intinn-N	Ncfsc
aici	aici	ag-P	Pr3fs
ar	ar	ar-S	Sp
dtús	dtús	tús-N	Ncmsc
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
Méabh	Méabh	Méabh-N	Npfsc
a	a	a-D	Dp3
ceann	ceann	ceann-N	Ncmsc
fúithi	fúithi	faoi-P	Pr3fs
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
chomh	chomh	chomh-R	Ri
sciobtha	sciobtha	sciobtha-A	Aqp
in	in	sin-P	Pd
éirinn	éirinn	éir-V	Vmih1s
agus	agus	agus-C	Cc
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhéad	fhéad	féad-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
aiféala	aiféala	aiféala-N	Ncmsc
uirthi	uirthi	ar-P	Pr3fs
anois	anois	anois-R	Rt
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
oiread	oiread	oiread-N	Ns-s
sin	sin	sin-D	Dd
ranganna	ranganna	rang-N	Ncmpc
corpoideachais	corpoideachais	corpoideachas-N	Ncmsg
caillte	caillte	caill-A	Av
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
Ag	Ag	ag-S	Sp
ligean	ligean	lig-N	Nv
uirthi	uirthi	ar-P	Pr3fs
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
tinn	tinn	tinn-A	Aqp
le	le	le-S	Sp
héalú	héalú	éalaigh-N	Nv
uathu	uathu	ó-P	Pr3-p
.	.	.-F	Fe
Bheadh	Bheadh	bí-V	Vmc
sí	sí	sí-P	Pp3fsn
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
níos	níos	níos-U	Uc
lúfaire	lúfaire	lúfar-A	Aqc
dá	dá	de-S	Spp-s
…	…	…-F	Fi
ach	ach	ach-C	Cs
cén	cén	cé-W	W--q
mhaith	mhaith	maith-N	Ncfsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
cuimhneamh	cuimhneamh	cuimhnigh-N	Nv
air	air	ar-N	Ncmsg
sin	sin	sin-P	Pd|W|Dd
anois	anois	anois-R	Rt
?	?	?-F	Fq
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
scanraithe	scanraithe	scanraigh-A	Av
as	as	as-P	Pr3ms
a	a	a-D	Dp3
craiceann	craiceann	craiceann-N	Ncmsc
agus	agus	agus-C	Cc
chuile	chuile	cuile-N	Ncfsg
thorann	thorann	torann-N	Ncmpg
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
sí	sí	sí-P	Pp3fsn
ina	ina	i-S	Spp-s
timpeall	timpeall	timpeall-N	Ncmsc
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
tuilleadh	tuilleadh	tuilleadh-N	Nv-----n|Ncmsc
scéine	scéine	scian-N	Ncfsg
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Fiú	Fiú	fiú-N	Ncmsc|Rg|Ns-s
trup	trup	trup-N	Ncmsg|Ncmsc
a	a	a-D	Dp3
cuid	cuid	cuid-N	Ncfsc
buataisí	buataisí	buatais-N	Ncfpg
féin	féin	féin-P	Px
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcosán	gcosán	cosán-N	Ncmsc
!	!	!-F	Fe
Thug	Thug	tabhair-V	Vmis
sí	sí	sí-P	Pp3fsn
sracfhéachaint	sracfhéachaint	sracfhéachaint-N	Ncfsc
fhaiteach	fhaiteach	faiteach-A	Aq-fsc
amháin	amháin	amháin-A	Aqp
i ndiaidh	i ndiaidh	i_ndiaidh-S	Spc
a	a	a-D	Dp3
cúil	cúil	cúl-N	Ncfsc|Ncmpc
ach	ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
duine	duine	duine-N	Ncmsc
ná	ná	ná-C	Cc
deoraí	deoraí	deora-N	Ncmsc|Ncmsg|Ncfpg|Ncfpc
le	le	le-S	Sp
feiceáil	feiceáil	feic-N	Nv
.	.	.-F	Fe
Cá	Cá	cá-R	Rq
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
?	?	?-F	Fq
An	An	an-Q	Qq
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
bailithe	bailithe	bailigh-A	Av
leis	leis	le-P	Pr3ms
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
?	?	?-F	Fq
B	B	B-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
…	…	…-F	Fi
Bhí	Bhí	bí-V	Vmis
súil	súil	súil-N	Ncfsc
le	le	le-S	Sp
Dia	Dia	dia-N	Ncmsc
aici	aici	ag-P	Pr3fs
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ina	ina	i-S	Spp-s
croí	croí	croí-N	Ncmsc
istigh	istigh	istigh-R	Rl
chreid	chreid	creid-V	Vmis
Méabh	Méabh	Méabh-N	Npfsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
fós	fós	fós-R	Rg
i	i	i-S	Sp
ngar	ngar	gar-N	Ncmsc
di	di	do-P	Pr3fs
,	,	,-F	Fi
i	i	i-S	Sp
bhfolach	bhfolach	folach-N	Ncmsc
in	in	i-S	Sp
áit	áit	áit-N	Ncfsc
chúlráideach	chúlráideach	cúlráideach-A	Aq-fsc
dhorcha	dhorcha	dorcha-A	Aqp
nach	nach	nach-Q	Qnr
bhféadfaí	bhféadfaí	féad-V	Vmc-0
é	é	é-P	Pp3ms
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
…	…	…-F	Fi
nó	nó	nó-C	Cc
b	b	b-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
gur	gur	is-W	Wsdi
ag	ag	ag-S	Sp
fanacht	fanacht	fan-N	Nv
léi	léi	le-P	Pr3fs
ag	ag	ag-S	Sp
an	an	an-T	Td-s
gcéad	gcéad	céad-M	Mo
choirnéal	choirnéal	coirnéal-N	Ncmpg
eile	eile	eile-D	Dd
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
!	!	!-F	Fe
léi	léi	le-P	Pr3fs
de	de	de-P	Pr3ms|Sp
Timpeall	Timpeall	timpeall-S	Sp
an	an	an-T	Td-s
choirnéil	choirnéil	coirnéal-N	Ncmsg
ropadh	ropadh	rop-V	Vmis0
.	.	.-F	Fe
Bhreathnaigh	Bhreathnaigh	breathnaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
ina	ina	i-S	Spp-s
timpeall	timpeall	timpeall-N	Ncmsc
go	go	go-U	Ua
faiteach	faiteach	faiteach-A	Aqp
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
tásc	tásc	tásc-N	Ncmsc
ná	ná	ná-C	Cc
tuairisc	tuairisc	tuairisc-N	Ncfsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Is	Is	is-W	Wp-i
ag	ag	ag-S	Sp
bun	bun	bun-N	Ncmsc
na	na	na-T	Tdfsg
sráide	sráide	sráid-N	Ncfsg
seo	seo	seo-D	Dd
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
a	a	a-D	Dp3
teach	teach	teach-N	Ncmsc
féin	féin	féin-P	Px
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
má	má	má-C	Cs
ba	ba	is-W	Ws|Ws-i
ea	ea	ea-P	Pp3-s
féin	féin	féin-P	Px
,	,	,-F	Fi
ar	ar	is-W	Wsdq|Ws-q
cheart	cheart	ceart-A	Aqp
di	di	do-P	Pr3fs
glaoch	glaoch	glaoch-N	Ncmsc
ar	ar	is-W	Wsdq|Ws-q|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
tuismitheoirí	tuismitheoirí	tuismitheoir-N	Ncmpc
?	?	?-F	Fq
A	A	an-T	Td-s
fhad	fhad	fad-N	Ncmsc
is	is	agus-C	Cc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
seans	seans	seans-N	Ncmsc
aici	aici	ag-P	Pr3fs
?	?	?-F	Fq
Cé	Cé	cé-W	W--q
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
faoi	faoi	faoi-S	Sp
urchar	urchar	urchar-N	Ncmsc
méaróige	méaróige	méaróg-N	Ncfsg
den	den	de-S	Spa-s
bhaile	bhaile	baile-N	Ncmsc
?	?	?-F	Fq
Agus	Agus	agus-C	Cc
gan	gan	gan-S	Sp
aon	aon	aon-D	Dq
tuairisc	tuairisc	tuairisc-N	Ncfsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
bpointe	bpointe	pointe-N	Ncmsc
sin	sin	sin-D	Dd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
duine	duine	duine-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sa	sa	i-S	Spa-s
tóir	tóir	tóir-N	Ncfsc
uirthi	uirthi	ar-P	Pr3fs
?	?	?-F	Fq
Bhí	Bhí	bí-V	Vmis
Méabh	Méabh	Méabh-N	Npfsc
idir	idir	idir-S	Sp
dhá	dhá	dó-M	Mc
chomhairle	chomhairle	comhairle-N	Ncfsc
.	.	.-F	Fe
An	An	an-Q	Qq
mbeidís	mbeidís	bí-V	Vmc-3p
ag	ag	ag-S	Sp
magadh	magadh	magadh-N	Nv-----n
fúithi	fúithi	faoi-P	Pr3fs
ag	ag	ag-S	Sp
baile	baile	baile-N	Ncmsc
?	?	?-F	Fq
Ag	Ag	ag-S	Sp
spochadh	spochadh	spoch-N	Nv
aisti	aisti	as-P	Pr3fs
–	–	–-X	Xx
iad	iad	iad-P	Pp3-p
á	á	do-S	Spo-p
rá	rá	abair-N	Nv
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
iomarca	iomarca	iomarca-N	Ncfsc
tóir	tóir	tóir-N	Ncfsc
aici	aici	ag-P	Pr3fs
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
ar	ar	ar-S	Sp
na	na	na-T	Td-p
scannáin	scannáin	scannán-N	Ncmpc
uafáis	uafáis	uafás-N	Ncmsg|Ncmpc|Ncmsg
?	?	?-F	Fq
Ach	Ach	ach-C	Cs
shocraigh	shocraigh	socraigh-V	Vmis
sí	sí	sí-P	Pp3fsn
go	go	go-Q	Q
gcuirfeadh	gcuirfeadh	cuir-V	Vmc
sí	sí	sí-P	Pp3fsn
suas	suas	suas-R	Rd
leis	leis	le-S	Sp
an	an	an-T	Td-s
spochadh	spochadh	spochadh-N	Ncmsc
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
mharaigh	mharaigh	maraigh-V	Vmis---n
spochadh	spochadh	spochadh-N	Ncmsc
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
riamh	riamh	riamh-R	Rg
.	.	.-F	Fe
Gan	Gan	gan-S	Sp
stopadh	stopadh	stopadh-N	Ncmsc
ar	ar	ar-S	Sp
chor	chor	cor-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
sháigh	sháigh	sáigh-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
lámh	lámh	lámh-N	Ncfsc
isteach	isteach	isteach-R	Rd
ina	ina	i-S	Spp-p|Spp-s
mála	mála	mála-N	Ncmsc
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
útamáil	útamáil	útamáil-N	Ncfsc
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
a	a	a-Q	Q-r
theacht	theacht	teacht-V	Vmis
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
fón	fón	fón-N	Ncmsc
póca	póca	póca-N	Ncmsg|Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
aimsigh	aimsigh	aimsigh-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
fón	fón	fón-N	Ncmsc
i	i	i-S	Sp
dtóin	dtóin	tóin-N	Ncfsc
an	an	an-T	Td-s
mhála	mhála	mála-N	Ncmsg
ar	ar	ar-S	Sp|Ncmsc|Wssi|Wpdi|Wpsi|Q-is
deireadh	deireadh	deireadh-V	Vmih|Ncmsc
.	.	.-F	Fe
Tharraing	Tharraing	tarraing-V	Vmis
sí	sí	sí-P	Pp3fsn
amach	amach	amach-R	Rd
é	é	é-P	Pp3ms
agus	agus	agus-C	Cc
bhrúigh	bhrúigh	brúigh-V	Vmis
sí	sí	sí-P	Pp3fsn
na	na	na-T	Td-p
cnaipí	cnaipí	cnaipe-N	Ncmpc
le	le	le-S	Sp
glaoch	glaoch	glaoigh-N	Nv
abhaile	abhaile	abhaile-R	Rd
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
má	má	má-C	Cs
bhrúigh	bhrúigh	brúigh-V	Vmis
,	,	,-F	Fi
níor	níor	níor-Q	Qn-s
tharla	tharla	tarlaigh-V	Vmis---n
faic	faic	faic-N	Ncfsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
ansin	ansin	ansin-R	Rt|Rl
a	a	a-Q	Q-r
chuimhnigh	chuimhnigh	cuimhnigh-V	Vmis
sí	sí	sí-P	Pp3fsn
gurbh	gurbh	is-W	Wsdi
éigean	éigean	éigean-N	Ncmsc
dóibh	dóibh	do-P	Pr3-p
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
a	a	a-D	Dp3
bhfón	bhfón	fón-N	Ncmpg
póca	póca	póca-N	Ncmsg|Ncmsc
a	a	a-U	U
chur	chur	cuir-N	Nv
as	as	as-P	Pr3ms
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
sa	sa	i-S	Spa-s
bpictiúrlann	bpictiúrlann	pictiúrlann-N	Ncfsc
níos	níos	níos-U	Uc
túisce	túisce	túisce-R	Rt
tráthnóna	tráthnóna	tráthnóna-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
brú	brú	brúigh-N	Nv
an	an	an-T	Td-s
chnaipe	chnaipe	cnaipe-N	Ncmsg
leis	leis	le-S	Sp
an	an	an-T	Td-s
bhfón	bhfón	fón-N	Ncmsc
a	a	a-U	U
chur	chur	cuir-N	Nv
ar	ar	ar-S	Sp
siúl	siúl	siúil-N	Nv
arís	arís	arís-R	Rg
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
shleamhnaigh	shleamhnaigh	sleamhnaigh-V	Vmis
an	an	an-T	Td-s
fón	fón	fón-N	Ncmsc
as	as	as-P	Pr3ms
a	a	a-D	Dp3
méara	méara	méar-N	Ncfpc
fliucha	fliucha	fliuch-A	Aq--pg|Aq--pc|Aq--pv
.	.	.-F	Fe
Síos	Síos	síos-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
talamh	talamh	talamh-N	Ncfsc
…	…	…-F	Fi
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
lochán	lochán	lochán-N	Ncmsc
uisce	uisce	uisce-N	Ncmsg
ag	ag	ag-S	Sp
a	a	a-D	Dp3
cosa	cosa	cos-N	Ncfpc
.	.	.-F	Fe
Sular	Sular	sula-C	Cs-s
chrom	chrom	crom-V	Vmis
sí	sí	sí-P	Pp3fsn
síos	síos	síos-R	Rd
leis	leis	le-S	Sp
an	an	an-T	Td-s
bhfón	bhfón	fón-N	Ncmsc
a	a	a-U	U
fháil	fháil	faigh-N	Nv
bhraith	bhraith	braith-V	Vmis
Méabh	Méabh	Méabh-N	Npfsc
gur	gur	is-W	Wsdi|Wpdi
cheart	cheart	ceart-A	Aqp
di	di	do-P	Pr3fs
breathnú	breathnú	breathnú-N	Ncmsc
taobh	taobh	taobh-N	Ncmsc
thiar	thiar	thiar-R	Rd
di	di	do-P	Pr3fs
babhta	babhta	babhta-N	Ncmsc
amháin	amháin	amháin-A	Aqp
eile	eile	eile-D	Dd
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
fhaitíos	fhaitíos	faitíos-N	Ncmsc
na	na	na-T	Td-p
bhfaitíos	bhfaitíos	faitíos-N	Ncmpg
…	…	…-F	Fi
ó	ó	ó-C	Cs
,	,	,-F	Fi
a	a	a-D	Dp3
thiarcais	thiarcais	tiarcais-N	Ns-s
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ann	ann	i-P	Pr3ms
!	!	!-F	Fe
É	É	é-P	Pp3ms
ag	ag	ag-S	Sp
rith	rith	rith-N	Nv
ina	ina	i-S	Spp-s
treo	treo	treo-N	Ncmsc
ar nós	ar nós	ar_nós-S	Spc
na	na	na-T	Tdfsg
lasrach	lasrach	lasair-N	Ncfsg
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
dabht	dabht	dabht-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
uirthi	uirthi	ar-P	Pr3fs
anois	anois	anois-R	Rt
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
hé	hé	é-P	Pp3ms
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
á	á	do-S	Spo-s
shamhlú	shamhlú	samhlaigh-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
duine	duine	duine-N	Ncmsc
seo	seo	seo-D	Dd
sa	sa	i-S	Spa-s
tóir	tóir	tóir-N	Ncfsc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
i	i	i-S	Sp
gcontúirt	gcontúirt	contúirt-N	Ncfsc
mhór	mhór	mór-A	Aq-fsv|Aq-fsc
.	.	.-F	Fe
Chaithfeadh	Chaithfeadh	caith-V	Vmc
sí	sí	sí-P	Pp3fsn
éalú	éalú	éalaigh-N	Ncmsc|Nv
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
Méabh	Méabh	Méabh-N	Npfsc
ag	ag	ag-S	Sp
rith	rith	rith-N	Nv
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
in	in	sin-P	Pd
éirinn	éirinn	éir-V	Vmih1s
is	is	agus-C	Cc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
in ann	in ann	in_ann-S	Spc
.	.	.-F	Fe
Cúpla	Cúpla	cúpla-N	Ncmsc|Dq
céad	céad	céad-N	Ncmsc|Mc
slat	slat	slat-N	Ncfsc|Ncfpg
agus	agus	agus-C	Cc
bheadh	bheadh	bí-V	Vmc
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
baile	baile	baile-N	Ncmsc
slán	slán	slán-A	Aq-msc
sábháilte	sábháilte	sábháil-A	Aqp|Av
.	.	.-F	Fe
Chuala	Chuala	clois-V	Vmis
sí	sí	sí-P	Pp3fsn
trup	trup	trup-N	Ncmsc
trom	trom	trom-A	Aq-msc
na	na	na-T	Td-p
gcos	gcos	cos-N	Ncfpg
taobh	taobh	taobh-N	Ncmsc
thiar	thiar	thiar-R	Rd
di	di	do-P	Pr3fs
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
aici	aici	ag-P	Pr3fs
go	go	go-Q	Q
rabhadar	rabhadar	bí-V	Vmis3p-d
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
níos	níos	níos-U	Uc
gaire	gaire	gar-A	Aqc
di	di	do-P	Pr3fs
le	le	le-S	Sp
gach	gach	gach-D	Dq
coiscéim	coiscéim	coiscéim-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
duine	duine	duine-N	Ncmsc
seo	seo	seo-D	Dd
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
níos	níos	níos-U	Uc
tapúla	tapúla	tapa-A	Aqc
ná	ná	ná-C	Cc
í	í	í-P	Pp3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
Nóiméad	Nóiméad	nóiméad-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
anois	anois	anois-R	Rt
agus	agus	agus-C	Cc
bheadh	bheadh	bí-V	Vmc
lámh	lámh	lámh-N	Ncfsc
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
gualainn	gualainn	gualainn-N	Ncfsc
–	–	–-X	Xx
lámh	lámh	lámh-N	Ncfsc
timpeall	timpeall	timpeall-N	Ncmpg|Ncmsc|Sp|Rd
ar	ar	is-W	Wpsi|Sp|Wssi|Wpdi
a	a	a-D	Dp3
muineál	muineál	muineál-N	Ncmsc
.	.	.-F	Fe
Rinne	Rinne	déan-V	Vmis
sí	sí	sí-P	Pp3fsn
tréaniarracht	tréaniarracht	tréaniarracht-N	Ncfsc
rith	rith	rith-V	Vmis
níos	níos	níos-U	Uc
tapúla	tapúla	tapa-A	Aqc
ach	ach	ach-C	Cs
ní	ní	is-W	Wp-in
fhéadfadh	fhéadfadh	féad-V	Vmc
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
Faoin	Faoin	faoi-S	Spa-s
am	am	am-N	Ncmsc
sin	sin	sin-D	Dd
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
caite	caite	caith-A	Aqp|Av
spíonta	spíonta	spíon-A	Av
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
ar	ar	ar-S	Sp
éigean	éigean	éigean-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
aon	aon	aon-D	Dq
spreacadh	spreacadh	spreacadh-N	Ncmsc
fanta	fanta	fan-A	Av
inti	inti	i-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
cailleadh	cailleadh	caill-N	Nv
a	a	a-D	Dp3
cuid	cuid	cuid-N	Ncfsc
misnigh	misnigh	misneach-N	Ncmsg
.	.	.-F	Fe
Thuig	Thuig	tuig-V	Vmis
sí	sí	sí-P	Pp3fsn
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
mórán	mórán	mórán-N	Ncmsc
seans	seans	seans-N	Ncmsg
ann	ann	i-P	Pr3ms
anois	anois	anois-R	Rt
go	go	go-Q	Q
mbainfeadh	mbainfeadh	bain-V	Vmc
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
teach	teach	teach-N	Ncmsc
amach	amach	amach-R	Rd
slán	slán	slán-N	Ncmsc
sábháilte	sábháilte	sábháil-A	Aqp|Av
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
béal	béal	béal-N	Ncmsc
le	le	le-S	Sp
scréach	scréach	scréach-N	Ncfsc
a	a	a-U	U
ligean	ligean	lig-N	Nv
aisti	aisti	as-P	Pr3fs
.	.	.-F	Fe
Ach	Ach	ach-R	Ri
díreach	díreach	díreach-A	Aqp
ansin	ansin	ansin-R	Rt|Rl
chuala	chuala	clois-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
ghlór	ghlór	glór-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Stop	Stop	stop-V	Vmm-2s
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
'	'	'-F	Fa
Céard	Céard	cé-W	W--q
sa	sa	i-S	Spa-s
diabhal	diabhal	diabhal-N	Ncmsc
atá	atá	bí-V	Vmip---r
ort	ort	ar-P	Pr2-s
?	?	?-F	Fq
Chaill	Chaill	caill-V	Vmis
tú	tú	tú-P	Pp2-s
d	d	d-X	Xl
’	’	’-F	Fa
fhón	fhón	fón-N	Ncmsc
póca	póca	póca-N	Ncmsg|Ncmsc
.	.	.-F	Fe
Fan	Fan	fan-V	Vmm-2s
liom	liom	le-P	Pr1-s
!	!	!-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Fanacht	Fanacht	fan-N	Ncmsc|Nv
le	le	le-S	Sp
dúmharfóir	dúmharfóir	marfóir-N	Ncmsc
?	?	?-F	Fq
'	'	'-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
Méabh	Méabh	Méabh-N	Npfsc
ina	ina	i-S	Spp-s
hintinn	hintinn	intinn-N	Ncfsc
féin	féin	féin-P	Px
.	.	.-F	Fe
'	'	'-F	Fa
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
ceapadh	ceapadh	ceap-N	Nv
go	go	go-Q	Q
mbeinn	mbeinn	bí-V	Vmc-1s
chomh	chomh	chomh-R	Ri
díchéillí	díchéillí	díchéillí-A	Aqp
–	–	–-X	Xx
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
mé	mé	mé-P	Pp1-s
craiceáilte	craiceáilte	craiceáil-A	Av
uileag	uileag	uileag-N	Ncmsc
?	?	?-F	Fq
'	'	'-F	Fa
Ach	Ach	ach-C	Cs
lean	lean	lean-V	Vmis
an	an	an-T	Td-s
glór	glór	glór-N	Ncmsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Ag	Ag	ag-S	Sp
impí	impí	impigh-N	Nv
uirthi	uirthi	ar-P	Pr3fs
stopadh	stopadh	stopadh-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Fan	Fan	fan-V	Vmm-2s
,	,	,-F	Fi
a	a	a-U	Uv
Mhéabh	Mhéabh	Méabh-N	Npf-v
.	.	.-F	Fe
Céard	Céard	cé-W	W--q
atá	atá	bí-V	Vmip---r
ort	ort	ar-P	Pr2-s
?	?	?-F	Fq
Mise	Mise	mé-P	Pp1-s-e
atá	atá	bí-V	Vmip---r
ann	ann	ann-R	Rl
…	…	…-F	Fi
Breandán	Breandán	Breandán-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
Méabh	Méabh	Méabh-N	Npfsc
trína	trína	trí-S	Spp-s
chéile	chéile	céile-N	Ncmsc
sin	sin	sin-P	Pd|W|Dd
faoin	faoin	faoi-S	Spa-s
am	am	am-N	Ncmsc
sin	sin	sin-D	Dd
is	is	agus-C	Cc
gur	gur	gur-Q	Q--s
thóg	thóg	tóg-V	Vmis
sé	sé	sé-P	Pp3msn
tamall	tamall	tamall-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
méid	méid	méid-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ráite	ráite	abair-A	Av
aige	aige	ag-P	Pr3ms
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
i	i	i-S	Sp
bhfeidhm	bhfeidhm	feidhm-N	Ncfsc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ansin	ansin	ansin-R	Rt|Rl
go	go	go-U	Ua
tobann	tobann	tobann-A	Aqp
thuig	thuig	tuig-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
Sheas	Sheas	seas-V	Vmis
sí	sí	sí-P	Pp3fsn
ina	ina	i-S	Spp-s|Spp-p
staic	staic	staic-N	Ncfsc
i lár	i lár	i_lár-S	Spc
an	an	an-T	Td-s
chosáin	chosáin	cosán-N	Ncmsg
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
dúnmharfóir	dúnmharfóir	dúnmharfóir-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
rith	rith	rith-N	Nv
ina	ina	i-S	Spp-s
diaidh	diaidh	diaidh-N	Ns-s
ar	ar	ar-S	Sp
chor	chor	cor-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
!	!	!-F	Fe
Duine	Duine	duine-N	Ncmsc
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
aithin	aithin	aithin-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
!	!	!-F	Fe
Duine	Duine	duine-N	Ncmsc
dá	dá	de-S	Spp-s
comhscoláirí	comhscoláirí	comhscoláir-N	Ncfpc
!	!	!-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
iompaigh	iompaigh	iompaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
timpeall	timpeall	timpeall-R	Rd|Ncmsc
go	go	go-U	Ua
mall	mall	mall-A	Aqp
,	,	,-F	Fi
a	a	a-D	Dp3
croí	croí	croí-N	Ncmsc
fós	fós	fós-R	Rg
ag	ag	ag-S	Sp
preabadh	preabadh	preab-N	Nv
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
cé	cé	cé-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
os	os	os-N	Ncmpg|Sp|Ncmsc
a	a	a-D	Dp3
comhair	comhair	comhair-N	Ns-s
amach	amach	amach-R	Rd
ach	ach	ach-C	Cs
…	…	…-F	Fi
Breandán	Breandán	Breandán-N	Npmsc
ó	ó	ó-S	Sp
Móráin	Móráin	Móráin-N	Npmsc
.	.	.-F	Fe
É	É	é-P	Pp3ms
báite	báite	báigh-A	Av
go	go	go-S	Sp
craiceann	craiceann	craiceann-N	Ncmsc
cosúil	cosúil	cosúil-A	Aq-msc
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
a	a	a-D	Dp3
chochall	chochall	cochall-N	Ncmsc
fliuch	fliuch	fliuch-A	Aq-msc
thar	thar	thar-S	Sp
a	a	a-D	Dp3
chloigeann	chloigeann	cloigeann-N	Ncmsc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Breandán	Breandán	Breandán-N	Npmsc
in	in	i-S	Sp
aon	aon	aon-D	Dq
rang	rang	rang-N	Ncmsc
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
sa	sa	i-S	Spa-s
scoil	scoil	scoil-N	Ncfsc
agus	agus	agus-C	Cc
súil	súil	súil-N	Ncfsc|Nv-----n
ag	ag	ag-S	Sp
na	na	na-T	Td-p
cailíní	cailíní	cailín-N	Ncmpc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
–	–	–-X	Xx
í	í	í-P	Pp3fs
féin	féin	féin-P	Px
san	san	i-S	Spa-s
áireamh	áireamh	áireamh-N	Ncmsc
–	–	–-X	Xx
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
hé	hé	é-P	Pp3ms
amháin	amháin	amháin-A	Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
leaid	leaid	leaid-N	Ncmsc
seo	seo	seo-D	Dd
dathúil	dathúil	dathúil-A	Aqp
agus	agus	agus-C	Cc
barrúil	barrúil	barrúil-A	Aqp
ach	ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
lách	lách	lách-A	Aqp
cineálta	cineálta	cineálta-A	Aqp
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
anois	anois	anois-R	Rt
is	is	is-U	U
mó	mó	mór-A	Aqc
an	an	an-T	Td-s
fonn	fonn	fonn-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
uirthi	uirthi	ar-P	Pr3fs
leathmharú	leathmharú	marú-N	Ncmsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Sul	Sul	sula-C	Cs
má	má	má-C	Cs
bhí	bhí	bí-V	Vmis
am	am	am-N	Ncmsc
aici	aici	ag-P	Pr3fs
cuimhneamh	cuimhneamh	cuimhneamh-N	Ncmsc
i	i	i-S	Sp
gceart	gceart	ceart-N	Ncmsc
uirthi	uirthi	ar-P	Pr3fs
féin	féin	féin-P	Px
thosaigh	thosaigh	tosaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
á	á	do-S	Spo-s
bhualadh	bhualadh	buail-N	Nv
lena	lena	le-S	Spp-s
cuid	cuid	cuid-N	Ncfsc
dorn	dorn	dorn-N	Ncmpg
.	.	.-F	Fe
'	'	'-F	Fa
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agat	agat	ag-P	Pr2-s
gur	gur	gur-Q	Q--s
scanraigh	scanraigh	scanraigh-V	Vmis
tú	tú	tú-P	Pp2-s
an	an	is-W	Wpdq|Wp-q
t	t	t-X	Xl
‑	‑	‑-F	Fb
anam	anam	anam-N	Ncmsc
asam	asam	as-P	Pr1-s
,	,	,-F	Fi
a	a	a-U	Uv|Dp3
liúdrámáin	liúdrámáin	liúdrámán-N	Ncmsg
?	?	?-F	Fq
Is	Is	is-W	Wp-i
beag	beag	beag-A	Aqp
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
taom	taom	taom-N	Ncmsc
croí	croí	croí-N	Ncmsg|Ncmsc
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
de	de	de-S	Sp
bhéic	bhéic	béic-N	Ncfsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
tharraing	tharraing	tarraing-V	Vmis
sí	sí	sí-P	Pp3fsn
buille	buille	buille-N	Ncmsc
eile	eile	eile-D	Dd
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Sa	Sa	i-S	Spa-s
mbolg	mbolg	bolg-N	Ncmsc
an	an	an-T	Td-s
babhta	babhta	babhta-N	Ncmsg
seo	seo	seo-D	Dd
.	.	.-F	Fe
Chomh	Chomh	chomh-R	Ri
tréan	tréan	tréan-A	Aqp
agus	agus	agus-C	Cc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
in ann	in ann	in_ann-S	Spc
.	.	.-F	Fe
'	'	'-F	Fa
Cén	Cén	cé-D	Dw--s
fáth	fáth	fáth-N	Ncmsc
nár	nár	nár-Q	Qnrs
labhair	labhair	labhair-V	Vmis---n
tú	tú	tú-P	Pp2-s
roimhe	roimhe	roimh-P	Pr3ms
seo	seo	seo-P	Pd
,	,	,-F	Fi
a	a	a-U	Uv
phleota	phleota	pleota-N	Ncmsv
?	?	?-F	Fq
In	In	i-S	Sp
áit	áit	áit-N	Ncfsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
cúinneáil	cúinneáil	cúinneáil-N	Nv
thart	thart	thart-R	Rd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
scanraithe	scanraithe	scanraigh-A	Av
as	as	as-P	Pr3ms
mo	mo	mo-D	Dp1-s
chraiceann	chraiceann	craiceann-N	Ncmsc
.	.	.-F	Fe
Cheap	Cheap	ceap-V	Vmis
mé	mé	mé-P	Pp1-s
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
duine	duine	duine-N	Ncmsc
craiceáilte	craiceáilte	craiceáil-A	Av
eicínt	eicínt	eicínt-A	Aqp
sa	sa	i-S	Spa-s
tóir	tóir	tóir-N	Ncfsc
orm	orm	ar-P	Pr1-s
–	–	–-X	Xx
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
mé	mé	mé-P	Pp1-s
a	a	a-U	U
ionsaí	ionsaí	ionsaigh-N	Nv
!	!	!-F	Fe
'	'	'-F	Fa
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
an	an	an-T	Td-s
anáil	anáil	anáil-N	Ncfsc
ag	ag	ag-S	Sp
Breandán	Breandán	Breandán-N	Npmsc
bocht	bocht	bocht-A	Aq-msc
le	le	le-S	Sp
hí	hí	í-N	Ncfsc
a	a	a-U	U
fhreagairt	fhreagairt	freagair-N	Nv
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbualadh	mbualadh	bualadh-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
á	á	do-S	Spo-s
fháil	fháil	faigh-N	Nv
uaithi	uaithi	ó-P	Pr3fs
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ar	ar	is-W	Wpdi|Wpsi|Wssi
deireadh	deireadh	deireadh-N	Ncmsc
d	d	d-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmm-2s
leis	leis	le-P	Pr3ms
breith	breith	beir-N	Nv
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
dhá	dhá	dó-M	Mc
lámh	lámh	lámh-N	Ncfsc
le	le	le-S	Sp
hí	hí	í-N	Ncfsc
a	a	a-U	U
stopadh	stopadh	stop-N	Nv
.	.	.-F	Fe
'	'	'-F	Fa
Éirigh	Éirigh	éirigh-V	Vmm-2s
as	as	as-P	Pr3ms
,	,	,-F	Fi
a	a	a-U	Uv
Mhéabh	Mhéabh	Méabh-N	Npf-v
,	,	,-F	Fi
as	as	as-S	Sp
ucht	ucht	ucht-N	Ncmsc
Dé	Dé	dia-N	Ncmsg
ort	ort	ar-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
'	'	'-F	Fa
Stop	Stop	stop-V	Vmm-2s
do	do	do-D	Dp2-s|Sp
mo	mo	mo-D	Dp1-s
bhualadh	bhualadh	buail-N	Ncmsc|Nv
.	.	.-F	Fe
Tabhair	Tabhair	tabhair-V	Vmm-2s
seans	seans	seans-N	Ncmsc
dom	dom	do-P	Pr1-s
labhairt	labhairt	labhairt-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Bhuel	Bhuel	bhuel-X	Xsc
,	,	,-F	Fi
abair	abair	abair-V	Vmm-2s
leat	leat	le-P	Pr2-s
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Méabh	Méabh	Méabh-N	Npfsc
agus	agus	agus-C	Cc
cantal	cantal	cantal-N	Ncmpg|Ncmsc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
'	'	'-F	Fa
Inis	Inis	inis-V	Vmm-2s
dom	dom	do-P	Pr1-s
faoin	faoin	faoi-S	Spa-s
sásamh	sásamh	sásamh-N	Ncmsc
a	a	a-Q	Q-r
bhain	bhain	bain-V	Vmis
tú	tú	tú-P	Pp2-s
as	as	as-P	Pr3ms
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
faire	faire	fair-N	Nv
orm	orm	ar-P	Pr1-s
agus	agus	agus-C	Cc
t	t	t-X	Xl
‑	‑	‑-F	Fb
anam	anam	anam-N	Ncmsc
ag	ag	ag-S	Sp
titim	titim	tit-N	Nv
asam	asam	as-P	Pr1-s
.	.	.-F	Fe
'	'	'-F	Fa
Bhreathnaigh	Bhreathnaigh	breathnaigh-V	Vmis
Breandán	Breandán	Breandán-N	Npmsc
uirthi	uirthi	ar-P	Pr3fs
agus	agus	agus-C	Cc
níor	níor	níor-Q	Qn-s
dhúirt	dhúirt	abair-V	Vmis---n
sé	sé	sé-P	Pp3msn
tada	tada	tada-N	Ncmsc
ar feadh	ar feadh	ar_feadh-S	Spc
soicind	soicind	soicind-N	Ncmsg
.	.	.-F	Fe
'	'	'-F	Fa
Ní	Ní	Ní-W	Wp-in|Up
hin	hin	hin-N	Ncfsc
é	é	é-P	Pp3ms
an	an	an-T	Td-s
chaoi	chaoi	caoi-N	Ncfsc
a	a	a-Q	Q-i
bhfuil	bhfuil	bí-V	Vmip---d
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
chor	chor	cor-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
,	,	,-F	Fi
a	a	a-U	Uv
Mhéabh	Mhéabh	Méabh-N	Npf-v
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
mé	mé	mé-P	Pp1-s
taobh amuigh	taobh amuigh	taobh_amuigh-R	Rl
den	den	de-S	Spa-s
phictiúrlann	phictiúrlann	pictiúrlann-N	Ncfsc
thú	thú	tú-P	Pp2-s
le	le	le-S	Sp
do	do	do-D	Dp2-s
chuid	chuid	cuid-N	Ncfsc
cairde	cairde	cairde-N	Ncmpg|Ncmsg
–	–	–-X	Xx
Sinéad	Sinéad	Sinéad-N	Npfsc
agus	agus	agus-C	Cc
Denise	Denise	Denise-N	Npmsc
–	–	–-X	Xx
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
ar	ar	is-W	Wpsi|Sp|Wssi|Wpdi
mo	mo	mo-D	Dp1-s
bhealach	bhealach	bealach-N	Ncmsc
abhaile	abhaile	abhaile-R	Rd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
anonn	anonn	anonn-R	Rd
chugat	chugat	chuig-P	Pr2-s
ansin	ansin	ansin-R	Rt|Rl
ach	ach	ach-C	Cs
shocraigh	shocraigh	socraigh-V	Vmis
mé	mé	mé-P	Pp1-s
go	go	go-C	Cs
mb	mb	mb-Y	Y
’	’	’-F	Fa
fhearr	fhearr	maith-A	Aqc
dom	dom	do-P	Pr1-s
fanacht	fanacht	fanacht-N	Ncmsc
nó	nó	nó-C	Cc
go	go	go-Q	Q
mbeifeá	mbeifeá	bí-V	Vmc-2s
leat	leat	le-P	Pr2-s
féin	féin	féin-P	Px
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Ach	Ach	ach-C	Cs
nach	nach	is-W	Wpsin|Wpdin|Wpdqn|Wp-qn
in	in	sin-P	Pd
ceathrú	ceathrú	ceathrú-A	Aqp|Ncfsc
uaire	uaire	uair-N	Ncfsg
ó	ó	ó-S	Sp
shin	shin	sin-P	Pd
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Méabh	Méabh	Méabh-N	Npfsc
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Breandán	Breandán	Breandán-N	Npmsc
,	,	,-F	Fi
'	'	'-F	Fa
ach	ach	ach-C	Cs
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
thar	thar	thar-S	Sp
an	an	an-T	Td-s
óstán	óstán	óstán-N	Ncmsc
bhí	bhí	bí-V	Vmis
duine	duine	duine-N	Ncmsc
de	de	de-S	Sp
na	na	na-T	Td-p
comharsana	comharsana	comharsa-N	Ncfpc
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
amach	amach	amach-R	Rd
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
sé	sé	sé-M	Mc
míle	míle	míle-M	Mc
ceist	ceist	ceist-N	Ncfsc
orm	orm	ar-P	Pr1-s
faoin	faoin	faoi-S	Spa-s
gcluiche	gcluiche	cluiche-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
againn	againn	ag-P	Pr1-p
inné	inné	inné-R	Rt
agus	agus	agus-C	Cc
níorbh	níorbh	is-W	Ws-in
féidir	féidir	féidir-N	Ns-s
liom	liom	le-P	Pr1-s
éalú	éalú	éalaigh-N	Nv
uaidh	uaidh	ó-P	Pr3ms
.	.	.-F	Fe
Ar	Ar	is-W	Wssi|Wpsi
aon	aon	aon-D	Dq
chaoi	chaoi	caoi-N	Ncfsc
,	,	,-F	Fi
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
rá	rá	abair-N	Nv
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
fonn	fonn	fonn-N	Ncmsc
orm	orm	ar-P	Pr1-s
labhairt	labhairt	labhairt-N	Ncfsc
leat	leat	le-P	Pr2-s
inniu	inniu	inniu-R	Rt
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
muid	muid	muid-P	Pp1-p
san	san	i-S	Spa-s
ionad	ionad	ionad-N	Ncmsc
babhlála	babhlála	babhláil-N	Nv--g
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
tú	tú	tú-P	Pp2-s
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
na	na	na-T	Td-p
cailíní	cailíní	cailín-N	Ncmpc
eile	eile	eile-D	Dd
ag	ag	ag-S	Sp
crochadh	crochadh	croch-N	Nv
as	as	as-P	Pr3ms
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
ar nós	ar nós	ar_nós-S	Spc
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bhíonn	bhíonn	bí-V	Vmig
sibh	sibh	sibh-P	Pp2-p
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
bhfuair	bhfuair	faigh-V	Vmis
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
seans	seans	seans-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Bhuel	Bhuel	bhuel-X	Xsc
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Méabh	Méabh	Méabh-N	Npfsc
go	go	go-U	Ua
mífhoighdeach	mífhoighdeach	mífhoighdeach-A	Aqp
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
liom	liom	le-P	Pr1-s
féin	féin	féin-P	Px
anois	anois	anois-R	Rt
.	.	.-F	Fe
Abair	Abair	abar-N	Ncmpc
cibé	cibé	cibé-P	Pi|Dq
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
céard	céard	cé-W	W--q
atá	atá	bí-V	Vmip---r
le	le	le-S	Sp
rá	rá	abair-N	Nv
agat	agat	ag-P	Pr2-s
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Taitníonn	Taitníonn	taitin-V	Vmip
tú	tú	tú-P	Pp2-s
liom	liom	le-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Breandán	Breandán	Breandán-N	Npmsc
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
breathnú	breathnú	breathnaigh-N	Nv
isteach	isteach	isteach-R	Rd
idir	idir	idir-S	Sp
an	an	an-T	Td-s
dá	dá	dó-M	Mc
shúil	shúil	súil-N	Ncfsc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
'	'	'-F	Fa
Taitníonn	Taitníonn	taitin-V	Vmip
tú	tú	tú-P	Pp2-s
thar	thar	thar-S	Sp
cionn	cionn	ceann-N	Ncfsd
liom	liom	le-P	Pr1-s
.	.	.-F	Fe
An	An	an-Q	Qq
bhféadfadh	bhféadfadh	féad-V	Vmc
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
againn	againn	ag-P	Pr1-p
castáil	castáil	castáil-N	Nv
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
uair	uair	uair-N	Ncfsc
eicínt	eicínt	eicínt-A	Aq-fsc|Aq-fsv
.	.	.-F	Fe
Linn	Linn	Linn-N	Npmsc
féin	féin	féin-P	Px
?	?	?-F	Fq
Le	Le	le-S	Sp
gabháil	gabháil	gabh-N	Nv
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
phictiúrlann	phictiúrlann	pictiúrlann-N	Ncfsc
.	.	.-F	Fe
Nó	Nó	nó-C	Cc
…	…	…-F	Fi
rud	rud	rud-N	Ncmsc
eicínt	eicínt	eicínt-A	Aq-msc
eile	eile	eile-D	Dd
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
.	.	.-F	Fe
Níl	Níl	bí-V	Vmip---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
…	…	…-F	Fi
cibé	cibé	cibé-P	Pi|Dq
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
céard	céard	cé-W	W--q
ba	ba	is-W	Wsri
mhaith	mhaith	maith-A	Aqp
leat	leat	le-P	Pr2-s
féin	féin	féin-P	Px
…	…	…-F	Fi
’	’	’-F	Fa
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
méid	méid	méid-N	Ncmsc
sin	sin	sin-D	Dd
ráite	ráite	abair-A	Av
aige	aige	ag-P	Pr3ms
chuir	chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
cheann	cheann	ceann-N	Ncmsc
faoi	faoi	faoi-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
oiread	oiread	oiread-N	Ns-s
sin	sin	sin-D	Dd
iontais	iontais	iontas-N	Ncmpc
ar	ar	ar-S	Sp
Mhéabh	Mhéabh	Méabh-N	Npfsc
is	is	agus-C	Cc
nár	nár	nár-Q	Qnrs
fhan	fhan	fan-V	Vmis---n
focal	focal	focal-N	Ncmsc
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
Ó	Ó	ó-S	Sp
thús	thús	tús-N	Ncmsc
na	na	na-T	Tdfsg
bliana	bliana	bliain-N	Ncfsg
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
suite	suite	suigh-A	Aqp|Av
taobh	taobh	taobh-N	Ncmsc
thiar	thiar	thiar-R	Rd
den	den	de-S	Spa-s
leaid	leaid	leaid-N	Ncmsc
seo	seo	seo-D	Dd
sa	sa	i-S	Spa-s
rang	rang	rang-N	Ncmsc
eolaíochta	eolaíochta	eolaíocht-N	Ncfsg
.	.	.-F	Fe
Ceithre	Ceithre	ceathair-M	Mc
huaire	huaire	uair-N	Ncfsg
sa	sa	i-S	Spa-s
tseachtain	tseachtain	seachtain-N	Ncfsc
.	.	.-F	Fe
Suite	Suite	suigh-A	Av
ansin	ansin	ansin-R	Rt|Rl
ag	ag	ag-S	Sp
stánadh	stánadh	stán-N	Nv
ar	ar	ar-S	Sp
chúl	chúl	cúl-N	Ncmsc
a	a	a-Q	Q-r
chinn	chinn	cinn-V	Vmis
,	,	,-F	Fi
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
brionglóidigh	brionglóidigh	brionglóideach-N	Ncfpc
faoin	faoin	faoi-S	Spa-s
lá	lá	lá-N	Ncmsc
a	a	a-Q	Q-i
dtabharfadh	dtabharfadh	tabhair-V	Vmc
sé	sé	sé-P	Pp3msn
faoi	faoi	faoi-S	Sp
deara	deara	deara-N	Ns-s
í	í	í-P	Pp3fs
agus	agus	agus-C	Cc
go	go	go-Q	Q
ndéarfadh	ndéarfadh	abair-V	Vmc
sé	sé	sé-P	Pp3msn
rud	rud	rud-N	Ncmsc
eicínt	eicínt	eicínt-A	Aq-msc
deas	deas	deas-A	Aq-msc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Rud	Rud	rud-N	Ncmsc
eicínt	eicínt	eicínt-A	Aq-msc
mar	mar	mar-S	Sp
seo	seo	seo-P	Pd
!	!	!-F	Fe
Ach	Ach	ach-C	Cs
níor	níor	is-W	Ws-in
tharla	tharla	tarlaigh-V	Vmis
sé	sé	sé-P	Pp3msn
riamh	riamh	riamh-R	Rg
ina	ina	i-S	Spp-s
cuid	cuid	cuid-N	Ncfsc
brionglóidí	brionglóidí	brionglóid-N	Ncfsg|Ncfpg
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
fliuch	fliuch	fliuch-A	Aqp
báite	báite	báigh-A	Av
agus	agus	agus-C	Cc
cuma	cuma	cuma-N	Ncfsc
na	na	na-T	Tdfsg
hainnise	hainnise	ainnise-N	Ncfsg
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
thuig	thuig	tuig-V	Vmis
Méabh	Méabh	Méabh-N	Npfsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
Breandán	Breandán	Breandán-N	Npmsc
ag	ag	ag-S	Sp
fanacht	fanacht	fan-N	Nv
go	go	go-U	Ua
foighdeach	foighdeach	foighdeach-A	Aqp
le	le	le-S	Sp
freagra	freagra	freagra-N	Ncmsc
uaithi	uaithi	ó-P	Pr3fs
–	–	–-X	Xx
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
thar	thar	thar-S	Sp
am	am	am-N	Ncmsc
aici	aici	ag-P	Pr3fs
rud	rud	rud-N	Ncmsc
eicínt	eicínt	eicínt-A	Aq-msc
a	a	a-U	U
rá	rá	abair-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
breathnú	breathnú	breathnaigh-N	Nv
síos	síos	síos-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
talamh	talamh	talamh-N	Ncfsc
anois	anois	anois-R	Rt
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
ciceáil	ciceáil	ciceáil-N	Nv
barraicíní	barraicíní	barraicín-N	Ncmpg
a	a	a-D	Dp3
dhá	dhá	dó-M	Mc
bhróg	bhróg	bróg-N	Ncfsc
in aghaidh	in aghaidh	in_aghaidh-S	Spc
dhromchla	dhromchla	dromchla-N	Ncmsg
an	an	an-T	Td-s
chosáin	chosáin	cosán-N	Ncmsg
.	.	.-F	Fe
'	'	'-F	Fa
Is	Is	is-W	Wp-i
ea	ea	ea-P	Pp3-s
,	,	,-F	Fi
togha	togha	togha-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
go	go	go-U	Ua
cúthalach	cúthalach	cúthalach-A	Aqp
.	.	.-F	Fe
'	'	'-F	Fa
Thaitneodh	Thaitneodh	taitin-V	Vmc
sé	sé	sé-P	Pp3msn
sin	sin	sin-P	Pd
liom	liom	le-P	Pr1-s
.	.	.-F	Fe
'	'	'-F	Fa
Agus	Agus	agus-C	Cc
ar	ar	ar-S	Sp
chúis	chúis	cúis-N	Ncfsc
eicínt	eicínt	eicínt-A	Aq-fsc|Aq-fsv
nár	nár	nár-Q	Qnrs
thuig	thuig	tuig-V	Vmip---n|Vmis---n
sí	sí	sí-P	Pp3fsn
féin	féin	féin-P	Px
ní	ní	ní-Q	Qn
fhéadfadh	fhéadfadh	féad-V	Vmc----n
sí	sí	sí-P	Pp3fsn
níos	níos	níos-U	Uc
mó	mó	mór-A	Aqc
ná	ná	ná-C	Cc
sin	sin	sin-W	W
a	a	a-U	U
rá	rá	abair-N	Nv
.	.	.-F	Fe
Ise	Ise	í-P	Pp3fs-e
!	!	!-F	Fe
Cailín	Cailín	Cailín-N	Npmsc
nach	nach	nach-Q	Qnr
stopfadh	stopfadh	stop-V	Vmc----n
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
ó	ó	ó-C	Cs
d	d	d-X	Xl
’	’	’-F	Fa
éiríodh	éiríodh	éirigh-V	Vmih
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
maidin	maidin	maidin-N	Ncfsc
go	go	go-Q	Q
dtéadh	dtéadh	téigh-V	Vmih
sí	sí	sí-P	Pp3fsn
a	a	a-U	U
chodladh	chodladh	codail-N	Nv
san	san	i-S	Spa-s
oíche	oíche	oíche-N	Ncfsc
!	!	!-F	Fe
A	A	a-Q	Q-i
mbíodh	mbíodh	bí-V	Vmih
a	a	a-D	Dp3
mamó	mamó	mamó-N	Ncfsc
ag	ag	ag-S	Sp
glaoch	glaoch	glaoigh-N	Nv
'	'	'-F	Fa
roilleach	roilleach	roilleach-N	Ncmsc
’	’	’-F	Fa
uirthi	uirthi	ar-P	Pr3fs
!	!	!-F	Fe
Ach	Ach	ach-C	Cs
ba	ba	is-W	Ws|Ws-i
chosúil	chosúil	cosúil-A	Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
Breandán	Breandán	Breandán-N	Npmsc
sásta	sásta	sásta-A	Aqp
go leor	go leor	go_leor-A	Aq
leis	leis	le-S	Sp
an	an	an-T	Td-s
bhfreagra	bhfreagra	freagra-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
faighte	faighte	faigh-A	Av
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
breathnú	breathnú	breathnaigh-N	Nv
uirthi	uirthi	ar-P	Pr3fs
anois	anois	anois-R	Rt
agus	agus	agus-C	Cc
meangadh	meangadh	meang-V	Vmis0
mór	mór	mór-N	Ncmsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
'	'	'-F	Fa
Cuirfidh	Cuirfidh	cuir-V	Vmif
mé	mé	mé-P	Pp1-s
téacs	téacs	téacs-N	Ncmsc
chugat	chugat	chuig-P	Pr2-s
amárach	amárach	amárach-N	Ns-s
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
agus	agus	agus-C	Cc
déanfaidh	déanfaidh	déan-V	Vmif
muid	muid	muid-P	Pp1-p
socrú	socrú	socrú-N	Nv|Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
'	'	'-F	Fa
Oíche	Oíche	oíche-N	Ncfsc
mhaith	mhaith	maith-A	Aq-fsc
,	,	,-F	Fi
a	a	a-U	Uv
Mhéabh	Mhéabh	Méabh-N	Npf-v
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
tá	tá	bí-V	Vmip
‑	‑	‑-F	Fb
bhrón	bhrón	brón-V	Vmis
orm	orm	ar-P	Pr1-s
gur	gur	gur-Q	Q--s
scanraigh	scanraigh	scanraigh-V	Vmis
mé	mé	mé-P	Pp1-s
thú	thú	tú-P	Pp2-s
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
a	a	a-D	Dp3
leithéid	leithéid	leithéid-N	Ncfsc
i	i	i-S	Sp
gceist	gceist	ceist-N	Ncfsc
agam	agam	ag-P	Pr1-s
in	in	i-S	Sp
aon	aon	aon-D	Dq
chor	chor	cor-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Oíche	Oíche	oíche-N	Ncfsc
mhaith	mhaith	maith-A	Aq-fsc
,	,	,-F	Fi
a	a	a-U	Uv
Bhreandáin	Bhreandáin	Breandán-N	Npm-v
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
go	go	go-U	Ua
ciúin	ciúin	ciúin-A	Aqp
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
abhaile	abhaile	abhaile-R	Rd
go	go	go-U	Ua
ríméadach	ríméadach	ríméadach-A	Aqp
.	.	.-F	Fe
Aisteach	Aisteach	aisteach-A	Aqp
go leor	go leor	go_leor-A	Aq
níor	níor	níor-Q	Qn-s
bhraith	bhraith	braith-V	Vmis---n
sí	sí	sí-P	Pp3fsn
fuar	fuar	faigh-V	Vmis
ná	ná	ná-Q	Qnm
fliuch	fliuch	fliuch-V	Vmm-2s-n
níos	níos	níos-U	Uc
mó	mó	mór-A	Aqc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
gliondar	gliondar	gliondar-N	Ncmsc
ina	ina	i-S	Spp-s
croí	croí	croí-N	Ncmsc
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
meangadh	meangadh	meangadh-N	Ncmsc
gáire	gáire	gáir-N	Ncfsg|Nv|Ncmsg|Ncmsc|Nv--g
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
béal	béal	béal-N	Ncmsc
.	.	.-F	Fe
Chuirfeadh	Chuirfeadh	cuir-V	Vmc
sé	sé	sé-P	Pp3msn
téacs	téacs	téacs-N	Ncmsc
chuici	chuici	chuig-P	Pr3fs
amárach	amárach	amárach-N	Ns-s
!	!	!-F	Fe
Agus	Agus	agus-C	Cc
bheidís	bheidís	bí-V	Vmc-3p
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
amach	amach	amach-R	Rd
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ansin	ansin	ansin-R	Rt|Rl
gan	gan	gan-S	Sp
aon	aon	aon-D	Dq
choinne	choinne	coinne-N	Ncfsc
bhí	bhí	bí-V	Vmis
Breandán	Breandán	Breandán-N	Npmsc
lena	lena	le-S	Spp-s
taobh	taobh	taobh-N	Ncmsc
arís	arís	arís-R	Rg
.	.	.-F	Fe
'	'	'-F	Fa
Seo	Seo	seo-W	W
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
'	'	'-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
fhón	fhón	fón-N	Ncmsc
póca	póca	póca-N	Ncmsg|Ncmsc
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
chuimhnigh	chuimhnigh	cuimhnigh-V	Vmis---n
mé	mé	mé-P	Pp1-s
ar	ar	is-W	Wpdi|Wpsi|Wssi
é	é	é-P	Pp3ms
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
duit	duit	do-P	Pr2-s
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
súil	súil	súil-N	Ncfsc
agam	agam	ag-P	Pr1-s
nach	nach	nach-Q	Qnr
bhfuil	bhfuil	bí-V	Vmip---n
sé	sé	sé-P	Pp3msn
briste	briste	briste-A	Av|Aqp
.	.	.-F	Fe
'	'	'-F	Fa
Agus	Agus	agus-C	Cc
sháigh	sháigh	sáigh-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
fón	fón	fón-N	Ncmsc
póca	póca	póca-N	Ncmsg|Ncmsc
isteach	isteach	isteach-R	Rd
ina	ina	i-S	Spp-s|Spp-p
lámh	lámh	lámh-N	Ncfsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhreathnaigh	bhreathnaigh	breathnaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
suas	suas	suas-R	Rd
air	air	ar-P	Pr3ms
le	le	le-S	Sp
'	'	'-F	Fa
go	go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
maith	maith	maith-N	Ncfsc
agat	agat	ag-P	Pr2-s
’	’	’-F	Fa
a	a	a-U	U
rá	rá	abair-N	Nv
chrom	chrom	crom-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
cheann	cheann	ceann-N	Ncmsc
agus	agus	agus-C	Cc
phóg	phóg	póg-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-U	Ua
sciobtha	sciobtha	sciob-A	Av
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-Q	Q-p
leiceann	leiceann	leic-V	Vmip
í	í	í-P	Pp3fs
.	.	.-F	Fe
'	'	'-F	Fa
Beidh	Beidh	bí-V	Vmif
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
leat	leat	le-P	Pr2-s
amárach	amárach	amárach-N	Ns-s
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
agus	agus	agus-C	Cc
ansin	ansin	ansin-R	Rt
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
imithe	imithe	imigh-A	Av
uaithi	uaithi	ó-P	Pr3fs
de	de	de-S	Sp
ropadh	ropadh	ropadh-N	Ncmsc
síos	síos	síos-R	Rd
an	an	an-T	Td-s
tsráid	tsráid	sráid-N	Ncfsc
.	.	.-F	Fe
