Saoirse	Saoirse	Saoirse-N	Npfsc
an	an	is-W	Wpdq|Wp-q
Mhic	Mhic	Mac-U	Up
Tíre	Tíre	tír-N	Ncfsg
'	'	'-F	Fa
Céard	Céard	cé-W	W--q
é	é	é-P	Pp3ms
seo	seo	seo-P	Pd
,	,	,-F	Fi
a	a	a-U	Uv
Mham	Mham	mam-N	Ncfsv
?	?	?-F	Fq
'	'	'-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
dá	dá	do-S	Spp-s|Spp-p
máthair	máthair	máthair-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
Cá	Cá	cá-R	Rq
bhfuair	bhfuair	faigh-V	Vmis
tú	tú	tú-P	Pp2-s
é	é	é-P	Pp3ms
?	?	?-F	Fq
'	'	'-F	Fa
'	'	'-F	Fa
ó	ó	ó-C	Cs
,	,	,-F	Fi
an	an	an-T	Td-s
deilbhín	deilbhín	deilbhín-N	Ncmsc
!	!	!-F	Fe
An	An	an-Q	Qq
dtaitníonn	dtaitníonn	taitin-V	Vmip
sé	sé	sé-P	Pp3msn
leat	leat	le-P	Pr2-s
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Anna	Anna	Anna-N	Npfsc
.	.	.-F	Fe
'	'	'-F	Fa
Sa	Sa	i-S	Spa-s
siopa	siopa	siopa-N	Ncmsc
carthanais	carthanais	carthanas-N	Ncmsg|Ncmpc
in	in	sin-S	Sp|Pd
Inis	Inis	inis-V	Vmis|Npmsc|Ncfsc
a	a	a-Q	Q-r
cheannaigh	cheannaigh	ceannaigh-V	Vmis
mé	mé	mé-P	Pp1-s
inné	inné	inné-R	Rt
é	é	é-P	Pp3ms
.	.	.-F	Fe
Nach	Nach	nach-Q	Qnr
bhfuil	bhfuil	bí-V	Vmip---n
sé	sé	sé-P	Pp3msn
gleoite	gleoite	gleoite-A	Aqp
!	!	!-F	Fe
'	'	'-F	Fa
Deilbhín	Deilbhín	deilbhín-N	Ncmsc
beag	beag	beag-A	Aq-msc
adhmaid	adhmaid	adhmad-N	Ncmsg|Ncmpc
i	i	i-S	Sp
gcruth	gcruth	cruth-N	Ncmsc
mac	mac	mac-N	Ncmpg
tíre	tíre	tír-N	Ncfsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ina	ina	i-S	Spp-s|Spp-p
lámh	lámh	lámh-N	Ncfsc
ag	ag	ag-S	Sp
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
á	á	do-S	Spo-s
chuimilt	chuimilt	cuimil-N	Nv
láithreach	láithreach	láithreach-N	Ncmsc
nach	nach	nach-W	Wprin|Wpdin|Wpsin|Cs
go	go	go-U	Ua
cúramach	cúramach	cúramach-A	Aqp
.	.	.-F	Fe
Bhraith	Bhraith	braith-V	Vmis
sí	sí	sí-P	Pp3fsn
gnáthornáid	gnáthornáid	ornáid-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
ach	ach	ach-C	Cs
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
rud	rud	rud-N	Ncmsc
eicínt	eicínt	eicínt-A	Aq-msc
‑	‑	‑-F	Fb
speisialta	speisialta	speisialta-A	Aqc
ag	ag	ag-S	Sp
baint	baint	bain-N	Nv
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Bhraith	Bhraith	braith-V	Vmis
Anna	Anna	Anna-N	Npfsc
an	an	an-T	Td-s
rud	rud	rud-N	Ncmsc
céanna	céanna	céanna-A	Aqp
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
leag	leag	leag-V	Vmis
sí	sí	sí-P	Pp3fsn
súil	súil	súil-N	Ncfsc|Nv-----n
air	air	ar-N	Ncmsg|Pr3ms|Ncmsg
den	den	de-S	Spa-s
chéad	chéad	céad-M	Mo
uair	uair	uair-N	Ncfsc
sa	sa	i-S	Spa-s
siopa	siopa	siopa-N	Ncmsc
in	in	sin-P	Pd
Inis	Inis	inis-V	Vmis
.	.	.-F	Fe
Bhraith	Bhraith	braith-V	Vmis
sí	sí	sí-P	Pp3fsn
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
deilbhín	deilbhín	deilbhín-N	Ncmsc
á	á	do-S	Spo-s
mealladh	mealladh	meall-N	Nv
.	.	.-F	Fe
Nach	Nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
rogha	rogha	rogha-N	Ncfsc
aici	aici	ag-P	Pr3fs
ach	ach	ach-S	Sp|Cs
é	é	é-P	Pp3ms
a	a	a-U	U
cheannach	cheannach	ceannaigh-N	Nv
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
‑	‑	‑-F	Fb
fhiosrach	fhiosrach	fiosrach-A	Aqp
faoi	faoi	faoi-P	Pr3ms
.	.	.-F	Fe
Céard	Céard	cé-W	W--q
as	as	as-P	Pr3ms
ar	ar	ar-Q	Q-is|Qq-s
tháinig	tháinig	tar-V	Vmis
sé	sé	sé-P	Pp3msn
?	?	?-F	Fq
Cé	Cé	cé-W	W--q
chomh	chomh	chomh-R	Ri
sean	sean	sean-A	Aqp
agus	agus	agus-C	Cc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
?	?	?-F	Fq
Cé	Cé	cé-P	Pq
a	a	a-Q	Q-r
rinne	rinne	déan-V	Vmis
é	é	é-P	Pp3ms
?	?	?-F	Fq
Ach	Ach	ach-C	Cs
tar éis	tar éis	tar_éis-S	Spc
di	di	do-P	Pr3fs
sracfhéachaint	sracfhéachaint	sracfhéachaint-N	Ncfsc
amháin	amháin	amháin-A	Aqp
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcailín	gcailín	cailín-N	Ncmsc
óg	óg	óg-A	Aq-msc
taobh	taobh	taobh-N	Ncmsc
thiar	thiar	thiar-R	Rd
den	den	de-S	Spa-s
chuntar	chuntar	cuntar-N	Ncmsc
bhí	bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
ag	ag	ag-S	Sp
Anna	Anna	Anna-N	Npfsc
nach	nach	nach-Q	Qnr|Qnrs
bhfaigheadh	bhfaigheadh	faigh-V	Vmc----d|Vmih
sí	sí	sí-P	Pp3fsn
freagra	freagra	freagra-N	Ncmsc
ar	ar	ar-S	Sp
na	na	na-T	Td-p
ceisteanna	ceisteanna	ceist-N	Ncfpc
sin	sin	sin-D	Dd
inniu	inniu	inniu-R	Rt
.	.	.-F	Fe
Ag	Ag	ag-S	Sp
faire	faire	fair-N	Nv
an	an	an-T	Td-s
chloig	chloig	clog-N	Ncmsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
cailín	cailín	cailín-N	Ncmsc
óg	óg	óg-A	Aq-msc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
chuma	chuma	cuma-N	Ncfsc
uirthi	uirthi	ar-P	Pr3fs
gurbh	gurbh	is-W	Wsdi
fhearr	fhearr	maith-A	Aqc
léi	léi	le-P	Pr3fs
a	a	a-U	U
bheith	bheith	bí-N	Nv
in	in	i-S	Sp
áit	áit	áit-N	Ncfsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
eile	eile	eile-D	Dd
seachas	seachas	seachas-S	Sp
sa	sa	i-S	Spa-s
siopa	siopa	siopa-N	Ncmsc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
cuimhneamh	cuimhneamh	cuimhnigh-N	Nv
siar	siar	siar-R	Rd
air	air	ar-P	Pr3ms
seo	seo	seo-P	Pd
anois	anois	anois-R	Rt
shocraigh	shocraigh	socraigh-V	Vmis
Anna	Anna	Anna-N	Npfsc
go	go	go-Q	Q
mbuailfeadh	mbuailfeadh	buail-V	Vmc
sí	sí	sí-P	Pp3fsn
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
siopa	siopa	siopa-N	Ncmsc
arís	arís	arís-R	Rg
ag	ag	ag-S	Sp
deireadh	deireadh	deireadh-N	Ncmsc
na	na	na-T	Tdfsg
seachtaine	seachtaine	seachtain-N	Ncfsg
.	.	.-F	Fe
Bheadh	Bheadh	bí-V	Vmc
duine	duine	duine-N	Ncmsc
den	den	de-S	Spa-s
bheirt	bheirt	beirt-N	Ncfsc
a	a	a-Q	Q-r
bhíodh	bhíodh	bí-V	Vmih
ag	ag	ag-S	Sp
freastal	freastal	freastail-N	Nv
ann	ann	ann-R	Rl
go	go	go-U	Ua
hiondúil	hiondúil	iondúil-A	Aqp
taobh	taobh	taobh-N	Ncmsc
thiar	thiar	thiar-R	Rd
den	den	de-S	Spa-s
chuntar	chuntar	cuntar-N	Ncmsc
agus	agus	agus-C	Cc
cheisteodh	cheisteodh	ceistigh-V	Vmc
sí	sí	sí-P	Pp3fsn
í	í	í-P	Pp3fs
faoin	faoin	faoi-S	Spa-s
deilbhín	deilbhín	deilbhín-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
fós	fós	fós-R	Rg
ag	ag	ag-S	Sp
cuimilt	cuimilt	cuimil-N	Nv
an	an	an-T	Td-s
deilbhín	deilbhín	deilbhín-N	Ncmsg
agus	agus	agus-C	Cc
an	an	an-T	Td-s
chuma	chuma	cuma-N	Ncfsc
uirthi	uirthi	ar-P	Pr3fs
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
faoi	faoi	faoi-S	Sp
dhraíocht	dhraíocht	draíocht-N	Ncfsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
mac	mac	mac-N	Ncmsc
tíre	tíre	tír-N	Ncfsg
beag	beag	beag-A	Aqp
adhmaid	adhmaid	adhmad-N	Ncmsg|Ncmpc|Ncmsg
.	.	.-F	Fe
'	'	'-F	Fa
Féadfaidh	Féadfaidh	féad-V	Vmif
tú	tú	tú-P	Pp2-s
é	é	é-P	Pp3ms
a	a	a-U	U
bheith	bheith	bí-N	Nv
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
más	más	má-C	Csw
maith	maith	maith-A	Aqp
leat	leat	le-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Anna	Anna	Anna-N	Npfsc
lena	lena	le-S	Spp-s
hiníon	hiníon	iníon-N	Ncfsc
tar éis	tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
agus	agus	agus-C	Cc
meangadh	meangadh	meang-V	Vmm-3s
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
'	'	'-F	Fa
Ach	Ach	ach-C	Cs
b	b	b-X	Xl
’	’	’-F	Fa
fhearr	fhearr	maith-A	Aqc
duit	duit	do-P	Pr2-s
dul	dul	dul-N	Ncmsc
ar ais	ar ais	ar_ais-R	Rd
go dtí	go dtí	go_dtí-S	Spc
do	do	do-D	Dp2-s
leaba	leaba	leaba-N	Ncfsc
anois	anois	anois-R	Rt
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agat	agat	ag-P	Pr2-s
céard	céard	cé-W	W--q
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
dochtúir	dochtúir	dochtúir-N	Ncmsc
leat	leat	le-P	Pr2-s
!	!	!-F	Fe
'	'	'-F	Fa
Bhreathnaigh	Bhreathnaigh	breathnaigh-V	Vmis
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
máthair	máthair	máthair-N	Ncfsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
bhreathnaigh	bhreathnaigh	breathnaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
síos	síos	síos-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
deilbhín	deilbhín	deilbhín-N	Ncmsc
álainn	álainn	álainn-A	Aq-msg|Aq-msc|Aq-msv
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ina	ina	i-S	Spp-s|Spp-p
lámh	lámh	lámh-N	Ncfsc
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
'	'	'-F	Fa
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
míle	míle	míle-M	Mc
maith	maith	maith-N	Ncfsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Mham	Mham	mam-N	Ncfsv
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
go	go	go-U	Ua
ciúin	ciúin	ciúin-A	Aqp
.	.	.-F	Fe
'	'	'-F	Fa
Is	Is	is-W	Wp-i
aoibhinn	aoibhinn	aoibhinn-A	Aqp
liom	liom	le-P	Pr1-s
é	é	é-P	Pp3ms
.	.	.-F	Fe
'	'	'-F	Fa
Ansin	Ansin	ansin-R	Rt|Rl
d	d	d-X	Xl
’	’	’-F	Fa
iompaigh	iompaigh	iompaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
timpeall	timpeall	timpeall-R	Rd|Ncmsc
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
go	go	go-U	Ua
mall	mall	mall-A	Aqp
suas	suas	suas-R	Rd
an	an	an-T	Td-s
staighre	staighre	staighre-N	Ncmsg
.	.	.-F	Fe
Sheas	Sheas	seas-V	Vmis
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
bhfuinneog	bhfuinneog	fuinneog-N	Ncfsc
ina	ina	i-S	Spp-p|Spp-s
seomra	seomra	seomra-N	Ncmsc
codlata	codlata	codail-A	Av
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
faire	faire	fair-N	Nv
amach	amach	amach-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
sneachta	sneachta	sneachta-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
titim	titim	tit-N	Nv
go	go	go-U	Ua
tiubh	tiubh	tiubh-A	Aqp
ar	ar	ar-S	Sp
na	na	na-T	Td-p
crainn	crainn	crann-N	Ncmpc
taobh amuigh	taobh amuigh	taobh_amuigh-R	Rl
den	den	de-S	Spa-s
fhuinneog	fhuinneog	fuinneog-N	Ncfsc
.	.	.-F	Fe
Chuala	Chuala	clois-V	Vmis
sí	sí	sí-P	Pp3fsn
páistí	páistí	páiste-N	Ncmpc
na	na	na-T	Tdfsg
gcomharsan	gcomharsan	comharsa-N	Ncfsg
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
ag	ag	ag-S	Sp
baint	baint	bain-N	Nv
suilt	suilt	sult-N	Ncmsg
agus	agus	agus-C	Cc
spraoi	spraoi	spraoi-N	Ncmsc|Nv-----n|Nv--g--n|Ncmsg|Nv-----n|Ncmsg|Nv--g--n|Nv-----n
as	as	as-S	Sp
an	an	an-T	Td-s
sneachta	sneachta	sneachta-N	Ncmsc
.	.	.-F	Fe
Nárbh	Nárbh	is-W	Wssin
aoibhinn	aoibhinn	aoibhinn-A	Aqp
dóibh	dóibh	do-P	Pr3-p
!	!	!-F	Fe
Thabharfadh	Thabharfadh	tabhair-V	Vmc
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
dhá	dhá	dó-M	Mc
súil	súil	súil-N	Ncfsc
ar	ar	is-W	Wpsi|Ncmsc|Wssi|Wpdi
a	a	a-U	U
bheith	bheith	bí-N	Nv
in ann	in ann	in_ann-S	Spc
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
amach	amach	amach-R	Rd
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéadfadh	fhéadfadh	féad-V	Vmc
sí	sí	sí-P	Pp3fsn
fear	fear	fear-N	Ncmsc
sneachta	sneachta	sneachta-N	Ncmsg|Ncmsc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
dá	dá	dá-C	Cs
gcoinneodh	gcoinneodh	coinnigh-V	Vmc
an	an	an-T	Td-s
sneachta	sneachta	sneachta-N	Ncmsc
air	air	ar-N	Ncmsg|Pr3ms
ag	ag	ag-S	Sp
titim	titim	tit-N	Nv
!	!	!-F	Fe
Ach	Ach	ach-C	Cs
thuig	thuig	tuig-V	Vmis
sí	sí	sí-P	Pp3fsn
faoin	faoin	faoi-S	Spa-s
am	am	am-N	Ncmsc
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
biseach	biseach	biseach-N	Ncmsc
tagtha	tagtha	tar-A	Av
uirthi	uirthi	ar-P	Pr3fs
gur	gur	is-W	Wsdi
beag	beag	beag-A	Aqp
seans	seans	seans-N	Ncmsg|Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
an	an	an-T	Td-s
sneachta	sneachta	sneachta-N	Ncmsc
fós	fós	fós-R	Rg
ar	ar	ar-S	Sp
an	an	an-T	Td-s
talamh	talamh	talamh-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
plúchadh	plúchadh	plúch-V	Vmis0
go	go	go-U	Ua
dona	dona	dona-A	Aqp
uirthi	uirthi	ar-P	Pr3fs
le	le	le-S	Sp
cúpla	cúpla	cúpla-N	Ncmsc
seachtain	seachtain	seachtain-N	Ncfsc
anois	anois	anois-R	Rt
.	.	.-F	Fe
Fuair	Fuair	faigh-V	Vmis
sí	sí	sí-P	Pp3fsn
drochshlaghdán	drochshlaghdán	slaghdán-N	Ncmsc
agus	agus	agus-C	Cc
galrú	galrú	galraigh-N	Ncmsc|Nv
ina	ina	i-S	Spp-s
cliabhrach	cliabhrach	cliabhrach-N	Ncmsc
,	,	,-F	Fi
rud	rud	rud-N	Ncmsc
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhág	fhág	fág-V	Vmis
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
drochghearranáil	drochghearranáil	gearranáil-N	Ncfsc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
ordú	ordú	ordú-N	Ncmsc
aici	aici	ag-P	Pr3fs
ón	ón	ó-S	Spa-s
dochtúir	dochtúir	dochtúir-N	Ncmsc
a	a	a-D	Dp3
cuid	cuid	cuid-N	Ncfsc
antaibheathach	antaibheathach	antaibheathach-N	Ncmpg
a	a	a-U	U
thógáil	thógáil	tóg-N	Nv
,	,	,-F	Fi
gan	gan	gan-S	Sp
as	as	as-S	Sp
an	an	an-T	Td-s
leaba	leaba	leaba-N	Ncfsc
nó	nó	nó-C	Cc
go	go	go-Q	Q
bhfeicfeadh	bhfeicfeadh	feic-V	Vmc
sé	sé	sé-P	Pp3msn
arís	arís	arís-R	Rg
í	í	í-P	Pp3fs
,	,	,-F	Fi
agus	agus	agus-C	Cc
neart	neart	neart-N	Ncmsc
scíthe	scíthe	scíth-N	Ncfsg
a	a	a-U	U
fháil	fháil	faigh-N	Nv
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
a	a	a-D	Dp3
máthair	máthair	máthair-N	Ncfsc
chuige	chuige	chuig-P	Pr3ms
gur	gur	gur-Q	Q--s
lean	lean	lean-V	Vmis
sí	sí	sí-P	Pp3fsn
comhairle	comhairle	comhairle-N	Ncfsc
an	an	an-T	Td-s
dochtúra	dochtúra	dochtúir-N	Ncmsg
.	.	.-F	Fe
Níor	Níor	níor-W	Ws-in|Qn-s
stop	stop	stop-V	Vmis|Vmis---n|Ncmsc
Caoimhe	Caoimhe	Caoimhe-N	Npf-g|Npfsc
ach	ach	ach-S	Sp|Cs
ag	ag	ag-S	Sp
clamhsán	clamhsán	clamhsán-N	Ncmsc
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
di	di	do-P	Pr3fs
an	an	an-T	Td-s
chéad	chéad	céad-M	Mo
chúpla	chúpla	cúpla-N	Ncmsc|Ncmsg
lá	lá	lá-N	Ncmsc
.	.	.-F	Fe
Nach	Nach	nach-Q	Qnr
bhféadfadh	bhféadfadh	féad-V	Vmc
sí	sí	sí-P	Pp3fsn
a	a	a-U	U
bheith	bheith	bí-N	Nv
luite	luite	luigh-A	Av
ar	ar	ar-S	Sp
an	an	an-T	Td-s
tolg	tolg	tolg-N	Ncmsc
faoi	faoi	faoi-S	Sp
phluid	phluid	pluid-N	Ncfsc
sa	sa	i-S	Spa-s
seomra	seomra	seomra-N	Ncmsc
suí	suí	suigh-N	Ncmsc|Ncmsg|Nv
ag	ag	ag-S	Sp
breathnú	breathnú	breathnaigh-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
teilifís	teilifís	teilifís-N	Ncfsc
,	,	,-F	Fi
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
,	,	,-F	Fi
in	in	i-S	Sp
áit	áit	áit-N	Ncfsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
sáinnithe	sáinnithe	sáinnigh-A	Av
ina	ina	i-S	Spp-p|Spp-s
seomra	seomra	seomra-N	Ncmsc
codlata	codlata	codail-A	Av
.	.	.-F	Fe
Cén	Cén	cé-W	W--q
difríocht	difríocht	difríocht-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
?	?	?-F	Fq
Nach	Nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
sé	sé	sé-P	Pp3msn
chomh	chomh	chomh-R	Ri
teolaí	teolaí	teolaí-A	Aqp
céanna	céanna	céanna-A	Aqp
sa	sa	i-S	Spa-s
seomra	seomra	seomra-N	Ncmsc
suí	suí	suigh-N	Ncmsc|Ncmsg|Nv
!	!	!-F	Fe
Ach	Ach	ach-C	Cs
tar éis	tar éis	tar_éis-S	Spc
cúpla	cúpla	cúpla-N	Ncmsg
lá	lá	lá-N	Ncmsc
thuig	thuig	tuig-V	Vmis
sí	sí	sí-P	Pp3fsn
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
mhaith	mhaith	maith-N	Ncfsc
di	di	do-P	Pr3fs
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
thug	thug	tabhair-V	Vmis---n
a	a	a-D	Dp3
máthair	máthair	máthair-N	Ncfsc
di	di	do-P	Pr3fs
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
chluas	chluas	cluas-N	Ncfsc
bhodhar	bhodhar	bodhar-A	Aq-fsc|Aq-fsv
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ar	ar	is-W	Wpdi|Wpsi|Wssi
a	a	a-D	Dp3
laghad	laghad	laghad-N	Ncmsc
bhí	bhí	bí-V	Vmis
neart	neart	neart-N	Ncmsc
leabhar	leabhar	leabhar-N	Ncmsc
le	le	le-S	Sp
léamh	léamh	léigh-N	Nv
aici	aici	ag-P	Pr3fs
fad	fad	fad-C	Cs
is	is	is-W	Wpri
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
coinnithe	coinnithe	coinnigh-A	Av
sa	sa	i-S	Spa-s
leaba	leaba	leaba-N	Ncfsc
.	.	.-F	Fe
Thuig	Thuig	tuig-V	Vmis
a	a	a-D	Dp3
cuid	cuid	cuid-N	Ncfsc
gaolta	gaolta	gaol-N	Ncmpg
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
cé	cé	cé-N	Ncfsg
chomh	chomh	chomh-R	Ri
mór	mór	mór-A	Aqp
agus	agus	agus-C	Cc
a	a	a-Q	Q-r
thaitin	thaitin	taitin-V	Vmis
leabhair	leabhair	leabhar-N	Ncmpc
le	le	le-S	Sp
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
agus	agus	agus-C	Cc
ní	ní	ní-W	Wp-in|Nv|Ncmsg|Nv|Ncmsg|Ncmsc
fios	fios	fios-N	Ncmsc
cén	cén	cé-W	W--q|Dw--s
sásamh	sásamh	sásamh-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
aici	aici	ag-P	Pr3fs
sa	sa	i-S	Spa-s
siopa	siopa	siopa-N	Ncmsc
leabhar	leabhar	leabhar-N	Ncmsc
tar éis	tar éis	tar_éis-S	Spc
na	na	na-T	Tdfsg
Nollag	Nollag	Nollaig-N	Ncfsg
.	.	.-F	Fe
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
a	a	a-D	Dp3
hintinn	hintinn	intinn-N	Ncfsc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
suas	suas	suas-R	Rd
faoi	faoi	faoi-S	Sp
na	na	na-T	Td-p
leabhair	leabhair	leabhar-N	Ncmpc
ab	ab	is-U	U
fhearr	fhearr	maith-A	Aqc
a	a	a-U	U
cheannach	cheannach	ceannaigh-N	Nv
leis	leis	le-S	Sp
na	na	na-T	Td-p
dearbháin	dearbháin	dearbhán-N	Ncmpc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
faighte	faighte	faigh-A	Av
aici	aici	ag-P	Pr3fs
mar	mar	mar-S	Sp
bhronntanais	bhronntanais	bronntanas-N	Ncmpc
Nollag	Nollag	Nollaig-N	Ncfsg
.	.	.-F	Fe
Watership	Watership	Watership-N	Npmsc
Down	Down	Down-N	Npmsc
an	an	an-T	Td-s
leabhar	leabhar	leabhar-N	Ncmsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
sáite	sáite	sáigh-A	Av
ann	ann	i-P	Pr3ms
faoi	faoi	faoi-S	Sp
láthair	láthair	láthair-N	Ncfsc
agus	agus	agus-C	Cc
cheap	cheap	ceap-V	Vmis|Ncmpg
Caoimhe	Caoimhe	Caoimhe-N	Npf-g|Npfsc
gurbh	gurbh	is-W	Wsdi
é	é	é-P	Pp3ms
seo	seo	seo-P	Pd
an	an	an-T	Td-s
leabhar	leabhar	leabhar-N	Ncmsc
ab	ab	is-U	U
fhearr	fhearr	maith-A	Aqc
dá	dá	dá-C	Cs
raibh	raibh	bí-V	Vmis---d
léite	léite	léigh-A	Av
riamh	riamh	riamh-R	Rg
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
Nóiméad	Nóiméad	nóiméad-N	Ncmsc
amháin	amháin	amháin-A	Aqp
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
scanraithe	scanraithe	scanraigh-A	Aqp|Av
croíbhriste	croíbhriste	croíbhriste-A	Aqp
ag	ag	ag-S	Sp
eachtraí	eachtraí	eachtraigh-N	Nv
an	an	an-T	Td-s
scéil	scéil	scéal-N	Ncmsg
agus	agus	agus-C	Cc
an	an	an-T	Td-s
chéad	chéad	céad-M	Mo
nóiméad	nóiméad	nóiméad-N	Ncmsc|Ncmpg
eile	eile	eile-D	Dd
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
briseadh	briseadh	bris-N	Nv
a	a	a-D	Dp3
croí	croí	croí-N	Ncmsc
ag	ag	ag-S	Sp
gáire	gáire	gáir-N	Nv
.	.	.-F	Fe
Leag	Leag	leag-V	Vmis
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
an	an	an-T	Td-s
deilbhín	deilbhín	deilbhín-N	Ncmsg
go	go	go-U	Ua
cúramach	cúramach	cúramach-A	Aqp
ar	ar	ar-S	Sp
leac	leac	leac-N	Ncfsc
na	na	na-T	Tdfsg
fuinneoige	fuinneoige	fuinneog-N	Ncfsg
agus	agus	agus-C	Cc
rug	rug	beir-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
leabhar	leabhar	leabhar-N	Ncmsc
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
leaba	leaba	leaba-N	Ncfsc
léi	léi	le-P	Pr3fs
ansin	ansin	ansin-R	Rt|Rl
go	go	go-U	Ua
sciobtha	sciobtha	sciob-A	Aqp|Av
agus	agus	agus-C	Cc
síos	síos	síos-R	Rd
faoi	faoi	faoi-S	Sp
na	na	na-T	Td-p
héadaí	héadaí	éadach-N	Ncmpc
leapa	leapa	leaba-N	Ncfsg
.	.	.-F	Fe
Níorbh	Níorbh	is-W	Ws-in
fhada	fhada	fada-A	Aqc|Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
te	te	te-A	Aqp
teolaí	teolaí	teolaí-A	Aqp
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
éalaithe	éalaithe	éalaigh-A	Av
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
ndomhan	ndomhan	domhan-N	Ncmsc
rúnda	rúnda	rúnda-A	Aqp
na	na	na-T	Td-p
gcoiníní	gcoiníní	coinín-N	Ncmpg
arís	arís	arís-R	Rg
.	.	.-F	Fe
Meán	Meán	meán-N	Ncmsc
oíche	oíche	oíche-N	Ncfsg|Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
ach	ach	ach-C	Cs
má	má	má-C	Cs
ba	ba	is-W	Wsri
ea	ea	ea-P	Pp3-s
féin	féin	féin-P	Px
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
chomh	chomh	chomh-R	Ri
geal	geal	geal-A	Aqp
leis	leis	le-S	Sp
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
na	na	na-T	Td-p
carnáin	carnáin	carnán-N	Ncmpc
mhóra	mhóra	mór-A	Aq--pc
sneachta	sneachta	sneachta-N	Ncmsg|Ncmsc
ag	ag	ag-S	Sp
soilsiú	soilsiú	soilsigh-N	Nv
faoi	faoi	faoi-S	Sp
sholas	sholas	solas-N	Ncmsc
na	na	na-T	Tdfsg
gealaí	gealaí	gealach-N	Ncfsg
.	.	.-F	Fe
I	I	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
as	as	as-N	Ncmpg
láthair	láthair	láthar-N	Ncfsc|Ncmsg
d	d	d-X	Xl
’	’	’-F	Fa
fhéadfá	fhéadfá	féad-V	Vmc-2s
sléibhte	sléibhte	sliabh-N	Ncmpc
arda	arda	ard-A	Aq--pc
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
,	,	,-F	Fi
sléibhte	sléibhte	sliabh-N	Ncmpc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
clúdaithe	clúdaithe	clúdaigh-A	Av
faoi	faoi	faoi-S	Sp
bhrat	bhrat	brat-N	Ncmsc
de	de	de-S	Sp
chrainn	chrainn	crann-N	Ncmpc
shíorghlasa	shíorghlasa	síorghlas-A	Aq--pc
.	.	.-F	Fe
Caithfidh	Caithfidh	caith-V	Vmif
sé	sé	sé-P	Pp3msn
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
teocht	teocht	teocht-N	Ncfsc
go	go	go-U	Ua
maith	maith	maith-A	Aqp
faoin	faoin	faoi-S	Spa-s
reophointe	reophointe	reophointe-N	Ncmsc
faoin	faoin	faoi-S	Spa-s
am	am	am-N	Ncmsc
seo	seo	seo-D	Dd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
goimh	goimh	goimh-N	Ncfsc
sa	sa	i-S	Spa-s
ngaoth	ngaoth	gaoth-N	Ncmsc|Ncfsc
agus	agus	agus-C	Cc
níorbh	níorbh	is-W	Ws-in
fhada	fhada	fada-A	Aqc|Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
ag	ag	ag-S	Sp
crith	crith	crith-N	Nv
leis	leis	le-S	Sp
an	an	an-T	Td-s
bhfuacht	bhfuacht	fuacht-N	Ncmsc
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
sí	sí	sí-P	Pp3fsn
faoi	faoi	faoi-S	Sp
deara	deara	deara-N	Ns-s
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
a	a	a-D	Dp3
hanáil	hanáil	anáil-N	Ncfsc
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
scamaill	scamaill	scamall-N	Ncmpc
mhóra	mhóra	mór-A	Aq--pc
gal	gal	gal-N	Ncmpg|Ncmsc|Ncfsc|Ncfpg
uisce	uisce	uisce-N	Ncmsg|Ncmsc
in	in	i-S	Sp
aer	aer	aer-N	Ncmsc
nimhneach	nimhneach	nimhneach-A	Aq-msc
na	na	na-T	Tdfsg
hoíche	hoíche	oíche-N	Ncfsg
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
shéid	shéid	séid-V	Vmis
an	an	an-T	Td-s
ghaoth	ghaoth	gaoth-N	Ncfsc
calóga	calóga	calóg-N	Ncfpc
fuara	fuara	fuar-A	Aq--pc
sneachta	sneachta	sneachta-N	Ncmsg|Ncmsc
isteach	isteach	isteach-R	Rd
ina	ina	i-S	Spp-s
cuid	cuid	cuid-N	Ncfsc
súl	súl	súil-N	Ncfpg
baineadh	baineadh	bain-V	Vmis0
an	an	an-T	Td-s
anáil	anáil	anáil-N	Ncfsc
di	di	de-P	Pr3fs
agus	agus	agus-C	Cc
níorbh	níorbh	is-W	Ws-in
fhéidir	fhéidir	féidir-N	Ns-s
léi	léi	le-P	Pr3fs
tada	tada	tada-N	Ncmsc
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
.	.	.-F	Fe
Rinne	Rinne	déan-V	Vmis
sí	sí	sí-P	Pp3fsn
iarracht	iarracht	iarracht-N	Ncfsc
a	a	a-D	Dp3
lámh	lámh	lámh-N	Ncfsc
a	a	a-U	U
ardú	ardú	ardaigh-N	Nv
leis	leis	le-S	Sp
na	na	na-T	Td-p
calóga	calóga	calóg-N	Ncfpc
a	a	a-U	U
bhaint	bhaint	bain-N	Nv
dá	dá	de-S	Spp-s
héadan	héadan	éadan-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
rud	rud	rud-N	Ncmsc
eicínt	eicínt	eicínt-A	Aq-msc
aisteach	aisteach	aisteach-A	Aq-msc
tarlaithe	tarlaithe	tarlaigh-A	Av
dá	dá	do-S	Spp-s|Spp-p|Spp-s|Spp-p
lámh	lámh	lámh-N	Ncfsc
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sí	sí	sí-P	Pp3fsn
in ann	in ann	in_ann-S	Spc
í	í	í-P	Pp3fs
a	a	a-U	U
ardú	ardú	ardaigh-N	Nv
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
caithfidh	caithfidh	caith-V	Vmif
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
rud	rud	rud-N	Ncmsc
eicínt	eicínt	eicínt-A	Aq-msc
aisteach	aisteach	aisteach-A	Aq-msc
tarlaithe	tarlaithe	tarlaigh-A	Av
dá	dá	de-S	Spp-s
cuid	cuid	cuid-N	Ncfsc
súl	súl	súil-N	Ncfpg
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
mar	mar	mar-C	Cs
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
leáigh	leáigh	leáigh-V	Vmis
na	na	na-T	Td-p
calóga	calóga	calóg-N	Ncfpc
bhreathnaigh	bhreathnaigh	breathnaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
síos	síos	síos-R	Rd
san	san	i-S	Spa-s
áit	áit	áit-N	Ncfsc
ar	ar	ar-S	Sp
cheart	cheart	ceart-N	Ncmsc
dá	dá	de-S	Spp-s
cuid	cuid	cuid-N	Ncfsc
cosa	cosa	cos-N	Ncfpc
a	a	a-U	U
bheith	bheith	bí-N	Nv
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	is-W	Wp-in
cosa	cosa	cos-N	Ncfpc
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
chor	chor	cor-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
ach	ach	ach-C	Cs
…	…	…-F	Fi
crúba	crúba	crúb-N	Ncfpc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
bhraith	bhraith	braith-V	Vmis
sí	sí	sí-P	Pp3fsn
rud	rud	rud-N	Ncmsc
eicínt	eicínt	eicínt-A	Aq-msc
ag	ag	ag-S	Sp
bogadh	bogadh	bog-N	Nv
taobh	taobh	taobh-N	Ncmsc
thiar	thiar	thiar-R	Rd
di	di	do-P	Pr3fs
.	.	.-F	Fe
Lig	Lig	lig-V	Vmis
sí	sí	sí-P	Pp3fsn
béic	béic	béic-N	Ncfsc
uafáis	uafáis	uafás-N	Ncmsg|Ncmpc|Ncmsg
aisti	aisti	as-P	Pr3fs
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhreathnaigh	bhreathnaigh	breathnaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
siar	siar	siar-R	Rd
.	.	.-F	Fe
Eireaball	Eireaball	eireaball-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
agus	agus	agus-C	Cc
is	is	is-W	Wpri
uirthi	uirthi	ar-P	Pr3fs
féin	féin	féin-P	Px
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
t	t	t-X	Xl
‑	‑	‑-F	Fb
eireaball	eireaball	eireaball-N	Ncmsc
!	!	!-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
á	á	do-S	Spo-s
croitheadh	croitheadh	croith-N	Nv
agus	agus	agus-C	Cc
á	á	do-S	Spo-s
lúbadh	lúbadh	lúb-N	Nv
féin	féin	féin-P	Px
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
a	a	a-U	U
oibriú	oibriú	oibrigh-N	Nv
amach	amach	amach-R	Rd
céard	céard	cé-W	W--q
sa	sa	i-S	Spa-s
domhan	domhan	domhan-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
tarlaithe	tarlaithe	tarlaigh-A	Av
di	di	do-P	Pr3fs
.	.	.-F	Fe
An	An	an-Q	Qq
bhféadfadh	bhféadfadh	féad-V	Vmc
sé	sé	sé-P	Pp3msn
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
…	…	…-F	Fi
ina	ina	i-S	Spp-s
gadhar	gadhar	gadhar-N	Ncmsc
?	?	?-F	Fq
Má	Má	má-C	Cs
bhí	bhí	bí-V	Vmis
nár	nár	nár-Q	Qnq
cheart	cheart	ceart-N	Ncmsc
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
sí	sí	sí-P	Pp3fsn
in ann	in ann	in_ann-S	Spc
tafann	tafann	tafann-N	Ncmpg
?	?	?-F	Fq
Bhain	Bhain	bain-V	Vmis
sí	sí	sí-P	Pp3fsn
triail	triail	triail-N	Ncfsc|Nv
as	as	as-P	Pr3ms
.	.	.-F	Fe
'	'	'-F	Fa
Bhuf	Bhuf	Bhuf-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
ansin	ansin	ansin-R	Rt|Rl
níos	níos	níos-U	Uc
airde	airde	ard-A	Aqc
fós	fós	fós-R	Rg
,	,	,-F	Fi
'	'	'-F	Fa
Bhuf	Bhuf	Bhuf-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
Iarracht	Iarracht	iarracht-N	Ncfsc
sách	sách	sách-R	Ri
maith	maith	maith-A	Aqp
a	a	a-Q	Q-r
cheap	cheap	ceap-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
seo	seo	seo-P	Pd
craiceáilte	craiceáilte	craiceáil-A	Av
!	!	!-F	Fe
An	An	an-Q	Qq
bhféadfadh	bhféadfadh	féad-V	Vmc
sé	sé	sé-P	Pp3msn
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
ina	ina	i-S	Spp-s
gadhar	gadhar	gadhar-N	Ncmsc
?	?	?-F	Fq
'	'	'-F	Fa
Bhuel	Bhuel	bhuel-X	Xsc
,	,	,-F	Fi
i	i	i-S	Sp
ndáiríre	ndáiríre	dáiríre-N	Ncmsc
,	,	,-F	Fi
d	d	d-X	Xl
’	’	’-F	Fa
fhéadfadh	fhéadfadh	féad-V	Vmc
rud	rud	rud-N	Ncmsc
níos	níos	níos-U	Uc
measa	measa	olc-A	Aqc
a	a	a-U	U
bheith	bheith	bí-N	Nv
tarlaithe	tarlaithe	tarlaigh-A	Av
dom	dom	do-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
tar éis	tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
.	.	.-F	Fe
Thaitin	Thaitin	taitin-V	Vmis
gadhair	gadhair	gadhar-N	Ncmpc
thar	thar	thar-S	Sp
cionn	cionn	ceann-N	Ncfsd
le	le	le-S	Sp
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
dhá	dhá	dó-M	Mc
chroí	chroí	croí-N	Ncmsc
aici	aici	ag-P	Pr3fs
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
gheall	gheall	geall-V	Vmis
a	a	a-D	Dp3
máthair	máthair	máthair-N	Ncfsc
go	go	go-Q	Q
bhfaigheadh	bhfaigheadh	faigh-V	Vmc----d|Vmih
sí	sí	sí-P	Pp3fsn
gadhar	gadhar	gadhar-N	Ncmsc
di	di	do-P	Pr3fs
.	.	.-F	Fe
Brocaire	Brocaire	brocaire-N	Ncmsc
Tibéadach	Tibéadach	Tibéadach-A	Aq-msc
a	a	a-Q	Q-r
cheannódh	cheannódh	ceannaigh-V	Vmc
sí	sí	sí-P	Pp3fsn
di	di	do-P	Pr3fs
dá	dá	de-S	Spp-s
céad	céad	céad-N	Ncmsc
lá	lá	lá-N	Ncmsc
breithe	breithe	beir-N	Ncfsg|Nv--g
eile	eile	eile-D	Dd
.	.	.-F	Fe
De réir	De réir	de_réir-C	Cs
an	an	is-W	Wpdq|Wp-q
taighde	taighde	taighde-N	Nv|Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
déanta	déanta	déan-A	Av
ag	ag	ag-S	Sp
Anna	Anna	Anna-N	Npfsc
le	le	le-S	Sp
deireanas	deireanas	deireanas-N	Ncmsc
ní	ní	ní-Q	Qn
chuireann	chuireann	cuir-V	Vmip---n
cluimhreach	cluimhreach	cluimhreach-N	Ncfsc
an	an	an-T	Td-s
ghadhair	ghadhair	gadhar-N	Ncmsg
áirithe	áirithe	áirigh-A	Aqp|Av
seo	seo	seo-D	Dd
isteach	isteach	isteach-R	Rd
ar	ar	ar-S	Sp
dhaoine	dhaoine	duine-N	Ncmpc
a	a	a-Q	Q-i
mbíonn	mbíonn	bí-V	Vmig
plúchadh	plúchadh	plúch-V	Vmis0
orthu	orthu	ar-P	Pr3-p
.	.	.-F	Fe
Is	Is	is-W	Wp-i
mar	mar	mar-S	Sp
gheall	gheall	geall-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bplúchadh	bplúchadh	plúchadh-N	Ncmsc
céanna	céanna	céanna-A	Aqp
,	,	,-F	Fi
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
as	as	as-N	Ncmpg|Ncmsc|Pr3ms|Sp
di	di	do-P	Pr3fs
ó	ó	ó-C	Cs
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
ina	ina	i-S	Spp-s|Spp-p
naíonán	naíonán	naíonán-N	Ncmsc
,	,	,-F	Fi
nach	nach	nach-Q	Qnr
ligfeadh	ligfeadh	lig-V	Vmc----n
a	a	a-D	Dp3
máthair	máthair	máthair-N	Ncfsc
do	do	do-S	Sp
Chaoimhe	Chaoimhe	Caoimhe-N	Npfsc
cat	cat	cat-N	Ncmpg
,	,	,-F	Fi
gadhar	gadhar	gadhar-N	Ncmsc
,	,	,-F	Fi
ná	ná	ná-C	Cc
fiú	fiú	fiú-N	Ncmsg|Ncmsc|Rg|Ns-s
coinín	coinín	coinín-N	Ncmsg|Ncmsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
aici	aici	ag-P	Pr3fs
mar	mar	mar-S	Sp
pheata	pheata	peata-N	Ncmsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
iomaí	iomaí	iomaí-A	Aqc|Aqp
deoir	deoir	deoir-N	Ncfsc
a	a	a-Q	Q-r
shil	shil	sil-V	Vmis
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
bhocht	bhocht	bocht-A	Aq-fsc
thar	thar	thar-S	Sp
na	na	na-T	Td-p
blianta	blianta	bliain-N	Ncfpc
mar	mar	mar-S	Sp
gheall	gheall	geall-N	Ncmsc
air	air	ar-N	Ncmsg
seo	seo	seo-P	Pd|Dd
ach	ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
mhaith	mhaith	maith-N	Ncfsc
di	di	do-P	Pr3fs
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
ghéillfeadh	ghéillfeadh	géill-V	Vmc----n
Anna	Anna	Anna-N	Npfsc
.	.	.-F	Fe
Go	Go	go-S	Sp
dtí	dtí	tí-N	Ncmsc|Ncfsc
anois	anois	anois-R	Rt
.	.	.-F	Fe
Faoi	Faoi	faoi-S	Sp
cheann	cheann	ceann-N	Ncmsc
dhá	dhá	dó-M	Mc
mhí	mhí	mí-N	Ncfsc|Ncmsc
eile	eile	eile-D	Dd
bheadh	bheadh	bí-V	Vmc
gadhar	gadhar	gadhar-N	Ncmsc
dá	dá	de-S	Spp-s
cuid	cuid	cuid-N	Ncfsc
féin	féin	féin-P	Px
ag	ag	ag-S	Sp
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
–	–	–-X	Xx
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
sí	sí	sí-P	Pp3fsn
trí	trí	trí-M	Mc
bliana	bliana	bliain-N	Ncfpc
déag	déag	déag-N	Ns-s
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
nach	nach	is-W	Wpsin|Wpdin
í	í	í-P	Pp3fs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
buíoch	buíoch	buíoch-A	Aqp
as	as	as-S	Sp
an	an	an-T	Td-s
gcomhluadar	gcomhluadar	comhluadar-N	Ncmsc
.	.	.-F	Fe
Ó	Ó	ó-C	Cs
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmis
a	a	a-D	Dp3
deirfiúr	deirfiúr	deirfiúr-N	Ncfsc
,	,	,-F	Fi
Sinéad	Sinéad	Sinéad-N	Npfsc
,	,	,-F	Fi
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
ollscoil	ollscoil	ollscoil-N	Ncfsc
i	i	i-S	Sp
mí	mí	mí-N	Ncfsc|Ncmsc
Mheán Fómhair	Mheán Fómhair	Meán_Fómhair-N	Ncmsg
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
teach	teach	teach-N	Ncmsc
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
éireann	éireann	éir-V	Vmip
róchiúin	róchiúin	ciúin-A	Aqp
di	di	do-P	Pr3fs
.	.	.-F	Fe
Gan	Gan	gan-S	Sp
sa	sa	i-S	Spa-s
teach	teach	teach-N	Ncmsc
ach	ach	ach-S	Sp|Cs
í	í	í-P	Pp3fs
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
a	a	a-D	Dp3
máthair	máthair	máthair-N	Ncfsc
.	.	.-F	Fe
Gan	Gan	gan-S	Sp
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
ann	ann	i-R	Rl|Pr3ms
le	le	le-S	Sp
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
argóint	argóint	argóin-N	Nv
léi	léi	le-P	Pr3fs
faoin	faoin	faoi-S	Spa-s
seomra	seomra	seomra-N	Ncmsc
folctha	folctha	folc-A	Av
nó	nó	nó-C	Cc
faoi	faoi	faoi-P	Pr3ms
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
goid	goid	goid-N	Nv
a	a	a-D	Dp3
cuid	cuid	cuid-N	Ncfsc
éadaigh	éadaigh	éadach-N	Ncmsg
.	.	.-F	Fe
Dar	Dar	dar-S	Sp
ndóigh	ndóigh	dóigh-N	Ncfsc
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
níos	níos	níos-U	Uc
mó	mó	mór-A	Aqc
spáis	spáis	spás-N	Ncmsg
ag	ag	ag-S	Sp
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
di	di	do-P	Pr3fs
féin	féin	féin-P	Px
anois	anois	anois-R	Rt
–	–	–-X	Xx
rud	rud	rud-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
á	á	do-S	Spo-s
iarraidh	iarraidh	iarr-N	Nv
aici	aici	ag-P	Pr3fs
leis	leis	le-S	Sp
na	na	na-T	Td-p
blianta	blianta	bliain-N	Ncfpc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
éadaí	éadaí	éadach-N	Ncmpc
deasa	deasa	deas-A	Aq--pc
agus	agus	agus-C	Cc
smidiú	smidiú	smidiú-N	Nv
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhág	fhág	fág-V	Vmis
Sinéad	Sinéad	Sinéad-N	Npfsc
ina	ina	i-S	Spp-s
diaidh	diaidh	diaidh-N	Ns-s
aici	aici	ag-P	Pr3fs
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
chaithfeadh	chaithfeadh	caith-V	Vmc
sí	sí	sí-P	Pp3fsn
a	a	a-U	U
admháil	admháil	admhaigh-N	Nv
ina	ina	i-S	Spp-s
croí	croí	croí-N	Ncmsc
istigh	istigh	istigh-R	Rl
gur	gur	gur-Q	Q--s
airigh	airigh	airigh-V	Vmis
sí	sí	sí-P	Pp3fsn
uaithi	uaithi	ó-P	Pr3fs
a	a	a-D	Dp3
deirfiúr	deirfiúr	deirfiúr-N	Ncfsc
.	.	.-F	Fe
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
uaigneas	uaigneas	uaigneas-N	Ncmsc
uirthi	uirthi	ar-P	Pr3fs
ina	ina	i-S	Spp-s
diaidh	diaidh	diaidh-N	Ns-s
.	.	.-F	Fe
Cé	Cé	cé-C	Cs
a	a	a-Q	Q-r
chreidfeadh	chreidfeadh	creid-V	Vmc
é	é	é-P	Pp3ms
!	!	!-F	Fe
An	An	an-T	Td-s
deirfiúr	deirfiúr	deirfiúr-N	Ncfsc
ar	ar	ar-Q	Q-is
chaith	chaith	caith-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
saol	saol	saol-N	Ncmsc
ag	ag	ag-S	Sp
troid	troid	troid-N	Nv
léi	léi	le-P	Pr3fs
!	!	!-F	Fe
Ach	Ach	ach-R	Ri
díreach	díreach	díreach-A	Aqp
ansin	ansin	ansin-R	Rt|Rl
chuir	chuir	cuir-V	Vmis
an	an	an-T	Td-s
gleo	gleo	gleo-N	Ncmsc
uafásach	uafásach	uafásach-A	Aq-msc
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
chuici	chuici	chuig-P	Pr3fs
ar	ar	ar-S	Sp
an	an	an-T	Td-s
ngaoth	ngaoth	gaoth-N	Ncmsc|Ncfsc
deireadh	deireadh	abair-V	Vmih
leis	leis	le-S	Sp
na	na	na-T	Td-p
smaointe	smaointe	smaoineamh-N	Ncmpc
seo	seo	seo-D	Dd
.	.	.-F	Fe
In	In	i-S	Sp
áit	áit	áit-N	Ncfsc
éigin	éigin	éigin-A	Aq-fsc
taobh	taobh	taobh-N	Ncmsc
thiar	thiar	thiar-R	Rd
di	di	do-P	Pr3fs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
gleo	gleo	gleo-N	Ncmsc
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
níos	níos	níos-U	Uc
gaire	gaire	gar-A	Aqc
di	di	do-P	Pr3fs
de réir	de réir	de_réir-C	Cs|Spc
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
croí	croí	croí-N	Ncmsc
ina	ina	i-S	Spp-s
béal	béal	béal-N	Ncmsc
ag	ag	ag-S	Sp
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
.	.	.-F	Fe
Thuig	Thuig	tuig-V	Vmis
sí	sí	sí-P	Pp3fsn
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
i	i	i-S	Sp
gcontúirt	gcontúirt	contúirt-N	Ncfsc
.	.	.-F	Fe
Chaithfeadh	Chaithfeadh	caith-V	Vmc
sí	sí	sí-P	Pp3fsn
imeacht	imeacht	imigh-N	Ncmsc|Nv
as	as	as-S	Sp
an	an	an-T	Td-s
áit	áit	áit-N	Ncfsc
seo	seo	seo-D	Dd
.	.	.-F	Fe
Chaithfeadh	Chaithfeadh	caith-V	Vmc
sí	sí	sí-P	Pp3fsn
éalú	éalú	éalaigh-N	Ncmsc|Nv
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
rith	rith	rith-N	Nv
ar	ar	ar-S	Sp
cosa	cosa	cos-N	Ncfpc
–	–	–-X	Xx
ar	ar	ar-S	Sp
lapa	lapa	lapa-N	Ncmsc
–	–	–-X	Xx
in	in	i-S	Sp
airde	airde	airde-N	Ncfpc|Ncfsc
,	,	,-F	Fi
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
éalú	éalú	éalaigh-N	Nv
chomh	chomh	chomh-R	Ri
scioptha	scioptha	scioptha-A	Av
in	in	sin-P	Pd
éirinn	éirinn	éir-V	Vmih1s
agus	agus	agus-C	Cc
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhéad	fhéad	féad-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chaith	chaith	caith-V	Vmis
sí	sí	sí-P	Pp3fsn
leathshúil	leathshúil	leathshúil-N	Ncfsc
taobh	taobh	taobh-N	Ncmsc
thiar	thiar	thiar-R	Rd
di	di	do-P	Pr3fs
ba	ba	is-W	Wsri
bheag	bheag	beag-A	Aqp
nár	nár	nár-Q	Qnrs
thit	thit	tit-V	Vmis---n
t	t	t-X	Xl
‑	‑	‑-F	Fb
anam	anam	anam-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
aisti	aisti	as-P	Pr3fs
.	.	.-F	Fe
Céard	Céard	cé-W	W--q
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
ag	ag	ag-S	Sp
drannadh	drannadh	drann-N	Nv
léi	léi	le-P	Pr3fs
ach	ach	ach-S	Sp
mac	mac	mac-N	Ncmsc
–	–	–-X	Xx
fan	fan	fan-V	Vmm-2s
,	,	,-F	Fi
ní	ní	is-W	Wp-in
hea	hea	ea-P	Pp3-s
–	–	–-X	Xx
ach	ach	ach-S	Sp
mic	mic	mac-N	Ncmpc
tíre	tíre	tír-N	Ncfsg
.	.	.-F	Fe
Leathscór	Leathscór	leathscór-N	Ncmsc
acu	acu	ag-P	Pr3-p
ar	ar	is-W	Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
laghad	laghad	laghad-N	Ncmsc
.	.	.-F	Fe
Céard	Céard	cé-W	W--q
as	as	as-P	Pr3ms
ar	ar	ar-Q	Q-is|Qq-s
tháinig	tháinig	tar-V	Vmis
siad	siad	siad-P	Pp3-pn
chomh	chomh	chomh-R	Ri
ciúin	ciúin	ciúin-A	Aqp
agus	agus	agus-C	Cc
chomh	chomh	chomh-R	Ri
gasta	gasta	gasta-A	Aqp
sin	sin	sin-P	Pd|Dd
?	?	?-F	Fq
I	I	i-S	Sp
ngan fhios	ngan fhios	gan_fhios-N	Ncmsc
di	di	do-P	Pr3fs
!	!	!-F	Fe
Níorbh	Níorbh	is-W	Ws-in
fhada	fhada	fada-A	Aqc|Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
siad	siad	siad-P	Pp3-pn
tagtha	tagtha	tar-A	Av
chomh	chomh	chomh-R	Ri
fada	fada	fada-A	Aqp
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Iad	Iad	iad-P	Pp3-p
ina	ina	i-S	Spp-s|Spp-p
leathchiorcal	leathchiorcal	leathchiorcal-N	Ncmsc
ina	ina	i-S	Spp-s
timpeall	timpeall	timpeall-N	Ncmsc
.	.	.-F	Fe
Stop	Stop	stop-V	Vmis|Ncmsc
Caoimhe	Caoimhe	Caoimhe-N	Npf-g|Npfsc
ag	ag	ag-S	Sp
rith	rith	rith-N	Nv
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
d	d	d-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
béal	béal	béal-N	Ncmsc
agus	agus	agus-C	Cc
lig	lig	lig-V	Vmis
sí	sí	sí-P	Pp3fsn
scread	scread	scread-N	Ncfsc
uafáis	uafáis	uafás-N	Ncmsg|Ncmpc|Ncmsg
aisti	aisti	as-P	Pr3fs
.	.	.-F	Fe
Ach	Ach	ach-S	Sp|Cs
in	in	i-S	Sp
áit	áit	áit-N	Ncfsc
scread	scread	scread-N	Ncfsc
daonna	daonna	daonna-A	Aqp
céard	céard	cé-W	W--q
a	a	a-Q	Q-r
thiocfadh	thiocfadh	tar-V	Vmc
amach	amach	amach-R	Rd
as	as	as-P	Pr3ms
a	a	a-D	Dp3
béal	béal	béal-N	Ncmsc
ach	ach	ach-S	Sp
tafann	tafann	tafann-N	Ncmsc
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
ag	ag	ag-S	Sp
madra	madra	madra-N	Ncmsc
nó	nó	nó-C	Cc
ag	ag	ag-S	Sp
,	,	,-F	Fi
b	b	b-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
,	,	,-F	Fi
mac	mac	mac-N	Ncmsc
tíre	tíre	tír-N	Ncfsg
!	!	!-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
mac	mac	mac-N	Ncmsc
tíre	tíre	tír-N	Ncfsg
mór	mór	mór-A	Aqp
liath	liath	liath-A	Aqp
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
caol	caol	caol-N	Ncmsc
díreach	díreach	díreach-A	Aq-msc
uirthi	uirthi	ar-P	Pr3fs
bhí	bhí	bí-V	Vmis
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
cinnte	cinnte	cinn-A	Aqp|Av
dearfa	dearfa	dearfa-A	Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
deireadh	deireadh	deireadh-N	Ncmsc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
chomh	chomh	chomh-R	Ri
scanraithe	scanraithe	scanraithe-A	Aqp
is	is	agus-C	Cc
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
sí	sí	sí-P	Pp3fsn
in ann	in ann	in_ann-S	Spc
as	as	as-S	Sp
an	an	an-T	Td-s
áit	áit	áit-N	Ncfsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
an	an	an-T	Td-s
mac	mac	mac-N	Ncmsc
tíre	tíre	tír-N	Ncfsg
chomh	chomh	chomh-R	Ri
fada	fada	fada-A	Aqp
léi	léi	le-P	Pr3fs
in	in	i-S	Sp
áit	áit	áit-N	Ncfsc
í	í	í-P	Pp3fs
a	a	a-U	U
alpadh	alpadh	alp-N	Nv
is	is	is-W	Wp-i
amhlaidh	amhlaidh	amhlaidh-R	Rg
a	a	a-Q	Q-r
thosaigh	thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
á	á	do-S	Spo-s
bolú	bolú	bolaigh-N	Nv
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
thosaigh	thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
cuimilt	cuimilt	cuimil-N	Nv
a	a	a-D	Dp3
chloiginn	chloiginn	cloigeann-N	Ncmsg
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
gualainn	gualainn	gualainn-N	Ncfsc
go	go	go-U	Ua
deas	deas	deas-R	Ri
séimh	séimh	séimh-A	Aqp
.	.	.-F	Fe
Chaithfeadh	Chaithfeadh	caith-V	Vmc
gur	gur	gur-Q	Q--s
chomhartha	chomhartha	comhair-A	Av
de	de	de-S	Sp
chineál	chineál	cineál-N	Ncmsc
eicínt	eicínt	eicínt-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
anseo	anseo	anseo-R	Rl
mar	mar	mar-S	Sp
thosaigh	thosaigh	tosach-N	Ncmpc
na	na	na-T	Td-p
mic	mic	mac-N	Ncmpc
tíre	tíre	tír-N	Ncfsg
eile	eile	eile-D	Dd
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
níos	níos	níos-U	Uc
gaire	gaire	gar-A	Aqc
di	di	do-P	Pr3fs
ansin	ansin	ansin-R	Rt
.	.	.-F	Fe
Rinne	Rinne	déan-V	Vmis
chuile	chuile	gach-D	Dq
mhac	mhac	mac-N	Ncmsc
tíre	tíre	tír-N	Ncfsg
acu	acu	ag-P	Pr3-p
an	an	an-T	Td-s
rud	rud	rud-N	Ncmsc
céanna	céanna	céanna-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
déanta	déanta	déan-A	Av
ag	ag	ag-S	Sp
an	an	an-T	Td-s
gcéad	gcéad	céad-M	Mo
mhac	mhac	mac-N	Ncmsc
tíre	tíre	tír-N	Ncfsg
léi	léi	le-P	Pr3fs
ar nós	ar nós	ar_nós-S	Spc
dá	dá	dá-C	Cs
mbeidís	mbeidís	bí-V	Vmc-3p
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
fáilte	fáilte	fáilte-N	Ncfsg
roimpi	roimpi	roimh-P	Pr3fs
.	.	.-F	Fe
'	'	'-F	Fa
Is	Is	is-W	Wp-i
cosúil	cosúil	cosúil-A	Aqp
gurb	gurb	is-W	Wpdi
é	é	é-P	Pp3ms
an	an	an-T	Td-s
mac	mac	mac-N	Ncmsc
tíre	tíre	tír-N	Ncfsg
mór	mór	mór-A	Aqp
liath	liath	liath-A	Aqp
an	an	an-T	Td-s
ceannaire	ceannaire	ceannaire-N	Ncmsg|Ncmsc
atá	atá	bí-V	Vmip---r
orthu	orthu	ar-P	Pr3-p
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
glacadh	glacadh	glac-N	Nv
leis	leis	le-P	Pr3ms
gur	gur	is-W	Wsdi
cuid	cuid	cuid-N	Ncfsc
den	den	de-S	Spa-s
chonairt	chonairt	conairt-N	Ncfsc
mé	mé	mé-P	Pp1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
ina	ina	i-S	Spp-s
hintinn	hintinn	intinn-N	Ncfsc
féin	féin	féin-P	Px
.	.	.-F	Fe
Díreach	Díreach	díreach-N	Ncmsc
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
tuairim	tuairim	tuairim-N	Ncfsc
seo	seo	seo-D	Dd
shuigh	shuigh	suigh-V	Vmis
an	an	an-T	Td-s
ceannaire	ceannaire	ceannaire-N	Ncmsc
faoi	faoi	faoi-P	Pr3ms|Sp
ar	ar	ar-S	Sp
an	an	an-T	Td-s
sneachta	sneachta	sneachta-N	Ncmsc
,	,	,-F	Fi
d	d	d-X	Xl
’	’	’-F	Fa
iompaigh	iompaigh	iompaigh-V	Vmis
sé	sé	sé-P	Pp3msn
i	i	i-S	Sp
dtreo	dtreo	treo-N	Ncmsc
na	na	na-T	Tdfsg
gealaí	gealaí	gealach-N	Ncfsg
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
tafann	tafann	tafainn-N	Nv
go	go	go-U	Ua
cráite	cráite	cráigh-A	Aqp|Av
.	.	.-F	Fe
Rinne	Rinne	déan-V	Vmis
na	na	na-T	Td-p
mic	mic	mac-N	Ncmpc
tíre	tíre	tír-N	Ncfsg
eile	eile	eile-D	Dd
an	an	an-T	Td-s
rud	rud	rud-N	Ncmsc
céanna	céanna	céanna-A	Aqp
.	.	.-F	Fe
Bhrisfeadh	Bhrisfeadh	bris-V	Vmc
sé	sé	sé-P	Pp3msn
do	do	do-S	Sp
chroí	chroí	croí-N	Ncmsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
éisteacht	éisteacht	éist-N	Nv
leis	leis	le-S	Sp
an	an	an-T	Td-s
olagón	olagón	olagón-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
'	'	'-F	Fa
Ar	Ar	ar-S	Sp
nós	nós	nós-N	Ncmsc
amhránaíocht	amhránaíocht	amhránaíocht-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
sean	sean	sean-N	Ncmsc
‑	‑	‑-F	Fb
nós	nós	nós-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
stop	stop	stop-N	Ncmsc
na	na	na-T	Td-p
mic	mic	mac-N	Ncmsg
tíre	tíre	tír-N	Ncfsg
agus	agus	agus-C	Cc
bhreathnaigh	bhreathnaigh	breathnaigh-V	Vmis
siad	siad	siad-P	Pp3-pn
ar	ar	ar-S	Sp
Chaoimhe	Chaoimhe	Caoimhe-N	Npfsc
.	.	.-F	Fe
'	'	'-F	Fa
Ó	Ó	Ó-I	I
,	,	,-F	Fi
maith	maith	maith-A	Aqp
go leor	go leor	go_leor-A	Aq
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
'	'	'-F	Fa
Bainfidh	Bainfidh	bain-V	Vmif
mé	mé	mé-P	Pp1-s
triail	triail	triail-N	Ncfsc|Nv
as	as	as-P	Pr3ms
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
fhéadfadh	fhéadfadh	féad-V	Vmc----n
sé	sé	sé-P	Pp3msn
a	a	a-U	U
bheith	bheith	bí-N	Nv
ródheacair	ródheacair	deacair-A	Aqp
.	.	.-F	Fe
'	'	'-F	Fa
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
,	,	,-F	Fi
d	d	d-X	Xl
’	’	’-F	Fa
iompaigh	iompaigh	iompaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
i	i	i-S	Sp
dtreo	dtreo	treo-N	Ncmsc
na	na	na-T	Tdfsg
gealaí	gealaí	gealach-N	Ncfsg
agus	agus	agus-C	Cc
lig	lig	lig-V	Vmis
sí	sí	sí-P	Pp3fsn
uaill	uaill	uaill-N	Ncfsc
aisti	aisti	as-P	Pr3fs
–	–	–-X	Xx
an	an	an-T	Td-s
uaill	uaill	uaill-N	Ncfsc
ab	ab	is-U	U
fhaide	fhaide	fada-A	Aqc
agus	agus	agus-C	Cc
ab	ab	is-U	U
airde	airde	ard-A	Aqc
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhéadfá	fhéadfá	féad-V	Vmc-2s
a	a	a-U	U
shamhlú	shamhlú	samhlaigh-N	Nv
.	.	.-F	Fe
Bhreathnaigh	Bhreathnaigh	breathnaigh-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
na	na	na-T	Td-p
mic	mic	mac-N	Ncmpc
tíre	tíre	tír-N	Ncfsg
sásta	sásta	sásta-A	Aqp
go leor	go leor	go_leor-A	Aq
lena	lena	le-S	Spp-s
cuid	cuid	cuid-N	Ncfsc
iarrachtaí	iarrachtaí	iarracht-N	Ncfpg
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
siad	siad	siad-P	Pp3-pn
féin	féin	féin-P	Px
ar	ar	ar-S	Sp
an	an	an-T	Td-s
olagón	olagón	olagón-N	Ncmsc
arís	arís	arís-R	Rg
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ansin	ansin	ansin-R	Rt|Rl
go	go	go-U	Ua
tobann	tobann	tobann-A	Aqp
stop	stop	stop-V	Vmis
siad	siad	siad-P	Pp3-pn
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
ag	ag	ag-S	Sp
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
ar feadh	ar feadh	ar_feadh-S	Spc
scaithimh	scaithimh	scaitheamh-N	Ncmsg
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
siad	siad	siad-P	Pp3-pn
stoptha	stoptha	stop-A	Av
de bharr	de bharr	de_bharr-S	Spc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
gus	gus	gus-N	Ncmsc
a	a	a-D	Dp3
hanama	hanama	anam-N	Ncmsg
isteach	isteach	isteach-R	Rd
ina	ina	i-S	Spp-s
cuid	cuid	cuid-N	Ncfsc
tafainn	tafainn	tafann-N	Ncmsg
.	.	.-F	Fe
Cén	Cén	cé-D	Dw--s
fáth	fáth	fáth-N	Ncmsc
ar	ar	ar-Q	Q-is
stop	stop	stop-V	Vmis
na	na	na-T	Td-p
mic	mic	mac-N	Ncmpc
tíre	tíre	tír-N	Ncfsg
den	den	de-S	Spa-s
olagón	olagón	olagón-N	Ncmsc
?	?	?-F	Fq
Céard	Céard	cé-W	W--q
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
tarlú	tarlú	tarlaigh-N	Nv
?	?	?-F	Fq
Is	Is	is-W	Wp-i
ansin	ansin	ansin-R	Rt|Rl
a	a	a-Q	Q-r
thug	thug	tabhair-V	Vmis
sí	sí	sí-P	Pp3fsn
faoi	faoi	faoi-S	Sp
deara	deara	deara-N	Ns-s
an	an	an-T	Td-s
boladh	boladh	boladh-N	Ncmsc
breá	breá	breá-A	Aq-msc
bia	bia	bia-N	Ncmsg|Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
chucu	chucu	chuig-P	Pr3-p
ar	ar	ar-S	Sp
an	an	an-T	Td-s
ngaoth	ngaoth	gaoth-N	Ncmsc|Ncfsc
.	.	.-F	Fe
Caithfidh	Caithfidh	caith-V	Vmif
sé	sé	sé-P	Pp3msn
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
láthair	láthair	láthair-N	Ncfsc
champála	champála	campáil-N	Nv--g
in	in	i-S	Sp
áit	áit	áit-N	Ncfsc
eicínt	eicínt	eicínt-A	Aq-fsc
cóngarach	cóngarach	cóngarach-A	Aq-msc
dóibh	dóibh	do-P	Pr3-p
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmm-2s
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
agus	agus	agus-C	Cc
lean	lean	lean-V	Vmis
sí	sí	sí-P	Pp3fsn
na	na	na-T	Td-p
mic	mic	mac-N	Ncmpc
tíre	tíre	tír-N	Ncfsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
anois	anois	anois-R	Rt
ag	ag	ag-S	Sp
rith	rith	rith-N	Nv
ar	ar	ar-S	Sp
luas	luas	luas-N	Ncmsc
lasrach	lasrach	lasrach-A	Aq-msc
i	i	i-S	Sp
dtreo	dtreo	treo-N	Ncmsc
an	an	an-T	Td-s
bholaidh	bholaidh	boladh-N	Ncmsg
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
theastaigh	theastaigh	teastaigh-V	Vmis---n
uaithi	uaithi	ó-P	Pr3fs
go	go	go-Q	Q
dtiocfadh	dtiocfadh	tar-V	Vmc
deireadh	deireadh	deireadh-N	Ncmsc
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
leis	leis	le-S	Sp
an	an	an-T	Td-s
eachtra	eachtra	eachtra-N	Ncfsc
iontach	iontach	iontach-A	Aq-fsc
seo	seo	seo-D	Dd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
mhuin	mhuin	muin-N	Ncfsc
na	na	na-T	Tdfsg
muice	muice	muc-N	Ncfsg
anois	anois	anois-R	Rt
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
rith	rith	rith-N	Nv
ar nós	ar nós	ar_nós-S	Spc
na	na	na-T	Tdfsg
gaoithe	gaoithe	gaoth-N	Ncfsg
leis	leis	le-S	Sp
na	na	na-T	Td-p
mic	mic	mac-N	Ncmpc
tíre	tíre	tír-N	Ncfsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
folláin	folláin	folláin-A	Aqp
,	,	,-F	Fi
láidir	láidir	láidir-A	Aqp
,	,	,-F	Fi
scafánta	scafánta	scafánta-A	Aqp
,	,	,-F	Fi
saor	saor	saor-A	Aqp
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
aithin	aithin	aithin-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
boladh	boladh	boladh-N	Ncmsc
–	–	–-X	Xx
stéig	stéig	stéig-N	Ncfsc
,	,	,-F	Fi
thuig	thuig	tuig-V	Vmis
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
go	go	go-U	Ua
tobann	tobann	tobann-A	Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
stiúgtha	stiúgtha	stiúg-A	Av
leis	leis	le-S	Sp
an	an	an-T	Td-s
ocras	ocras	ocras-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
an	an	an-T	Td-s
bia	bia	bia-N	Ncmsc
rófhada	rófhada	fada-A	Aqp
uathu	uathu	ó-P	Pr3-p
anois	anois	anois-R	Rt
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
sí	sí	sí-P	Pp3fsn
faoi	faoi	faoi-S	Sp
deara	deara	deara-N	Ns-s
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
na	na	na-T	Td-p
prislíní	prislíní	prislín-N	Ncmpc
móra	móra	mór-A	Aq--pv|Aq--pg|Aq--pc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
as	as	as-P	Pr3ms
a	a	a-D	Dp3
béal	béal	béal-N	Ncmsc
ag	ag	ag-S	Sp
leá	leá	leáigh-N	Nv
an	an	an-T	Td-s
tsneachta	tsneachta	sneachta-N	Ncmsg
thíos	thíos	thíos-R	Rd
ag	ag	ag-S	Sp
a	a	a-D	Dp3
cosa	cosa	cos-N	Ncfpc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
,	,	,-F	Fi
go	go	go-U	Ua
tobann	tobann	tobann-A	Aqp
,	,	,-F	Fi
tháinig	tháinig	tar-V	Vmis
smaoineamh	smaoineamh	smaoineamh-N	Ncmsc
uafásach	uafásach	uafásach-A	Aq-msc
isteach	isteach	isteach-R	Rd
ina	ina	i-S	Spp-s
ceann	ceann	ceann-N	Ncmsc
.	.	.-F	Fe
An	An	an-Q	Qq
raibh	raibh	bí-V	Vmis---d
na	na	na-T	Td-p
mic	mic	mac-N	Ncmpc
tíre	tíre	tír-N	Ncfsg
le	le	le-S	Sp
daoine	daoine	duine-N	Ncmpc
a	a	a-U	U
ionsaí	ionsaí	ionsaigh-N	Nv
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
a	a	a-U	U
ithe	ithe	ith-N	Nv
?	?	?-F	Fq
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
aici	aici	ag-P	Pr3fs
ó	ó	ó-S	Sp
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
breathnú	breathnú	breathnaigh-N	Nv
ar	ar	ar-S	Sp
chláracha	chláracha	clár-N	Ncmpc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
Discovery	Discovery	discovery-X	Xfen
Channel	Channel	Channel-X	Xfenp
go	go	go-C	Cs
n	n	n-X	Xl
‑	‑	‑-F	Fb
itheann	itheann	ith-V	Vmip
mic	mic	mac-N	Ncmpc
tíre	tíre	tír-N	Ncfsg
daoine	daoine	duine-N	Ncmpg|Ncmpc
amanta	amanta	amanta-A	Av
.	.	.-F	Fe
Lig	Lig	lig-V	Vmis
sí	sí	sí-P	Pp3fsn
béic	béic	béic-N	Ncfsc
aisti	aisti	as-P	Pr3fs
ag	ag	ag-S	Sp
súil	súil	súil-N	Nv-----n
go	go	go-Q	Q
gcloisfeadh	gcloisfeadh	clois-V	Vmc
na	na	na-T	Td-p
daoine	daoine	duine-N	Ncmpc
sa	sa	i-S	Spa-s
láthair	láthair	láthair-N	Ncfsc
champála	champála	campáil-N	Nv--g
í	í	í-P	Pp3fs
.	.	.-F	Fe
'	'	'-F	Fa
Bígí	Bígí	bí-V	Vmm-2p
cúramach	cúramach	cúramach-A	Aqp
!	!	!-F	Fe
Bígí	Bígí	bí-V	Vmm-2p
cúramach	cúramach	cúramach-A	Aqp
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
mic	mic	mac-N	Ncmpc
tíre	tíre	tír-N	Ncfsg
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
!	!	!-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Céard	Céard	cé-W	W--q
atá	atá	bí-V	Vmip---r
ort	ort	ar-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
stór	stór	stór-N	Ncmsv
?	?	?-F	Fq
Cén	Cén	cé-D	Dw--s
fáth	fáth	fáth-N	Ncmsc
a	a	a-Q	Q-i
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
béiceadh	béiceadh	béic-N	Nv
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Anna	Anna	Anna-N	Npfsc
go	go	go-U	Ua
himníoch	himníoch	imníoch-A	Aqp
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
súil	súil	súil-N	Ncfsc
agam	agam	ag-P	Pr1-s
nach	nach	nach-Q	Qnr
bhfuil	bhfuil	bí-V	Vmip---n
teas	teas	teas-N	Ncmsc|Xfen
fola	fola	fuil-N	Ncfsg|Ncfpc|Ncfpg
ort	ort	ar-P	Pr2-s
arís	arís	arís-R	Rg
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
t	t	t-X	Xl
‑	‑	‑-F	Fb
allas	allas	allas-N	Ncmsc
ag	ag	ag-S	Sp
sileadh	sileadh	sil-N	Nv
asat	asat	as-P	Pr2-s
.	.	.-F	Fe
Suigh	Suigh	suigh-V	Vmm-2s
suas	suas	suas-R	Rd
sa	sa	i-S	Spa-s
leaba	leaba	leaba-N	Ncfsc
agus	agus	agus-C	Cc
ith	ith	ith-V	Vmm-2s
do	do	do-S	Sp
dhinnéar	dhinnéar	dinnéar-N	Ncmsc
sula	sula	sula-C	Cs
mbeidh	mbeidh	bí-V	Vmif
sé	sé	sé-P	Pp3msn
fuar	fuar	fuar-A	Aqp
.	.	.-F	Fe
'	'	'-F	Fa
Shuigh	Shuigh	suigh-V	Vmis
Caoimhe	Caoimhe	Caoimhe-N	Npfsc
aniar	aniar	aniar-A	Aqp
sa	sa	i-S	Spa-s
leaba	leaba	leaba-N	Ncfsc
go	go	go-U	Ua
mall	mall	mall-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
mearbhall	mearbhall	mearbhall-N	Ncmsc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
sí	sí	sí-P	Pp3fsn
Anna	Anna	Anna-N	Npfsc
cromtha	cromtha	crom-A	Av
os	os	os-N	Ncmpg|Ncmsc|Sp
a	a	a-D	Dp3
cionn	cionn	ceann-N	Ncfsd
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
dinnéar	dinnéar	dinnéar-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mboirdín	mboirdín	bord-N	Ncmsc
le hais	le hais	le_hais-S	Spc
na	na	na-T	Tdfsg
leapa	leapa	leaba-N	Ncfsg
agus	agus	agus-C	Cc
an	an	an-T	Td-s
ghal	ghal	gal-N	Ncfsc
ag	ag	ag-S	Sp
éirí	éirí	éirigh-N	Nv
as	as	as-P	Pr3ms
.	.	.-F	Fe
Sceallóga	Sceallóga	sceallóg-N	Ncfpc
,	,	,-F	Fi
muisiriúin	muisiriúin	muisiriún-N	Ncmpc
agus	agus	agus-C	Cc
stéig	stéig	stéig-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
na	na	na-T	Td-p
héadaí	héadaí	éadach-N	Ncmpc
leapa	leapa	leaba-N	Ncfsg
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
in	in	sin-P	Pd
achrann	achrann	achair-V	Vmip
thíos	thíos	thíos-R	Rd
ag	ag	ag-S	Sp
a	a	a-D	Dp3
cosa	cosa	cos-N	Ncfpc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
deilbhín	deilbhín	deilbhín-N	Ncmsc
adhmaid	adhmaid	adhmad-N	Ncmsg|Ncmpc
fós	fós	fós-R	Rg
san	san	i-S	Spa-s
áit	áit	áit-N	Ncfsc
ar	ar	ar-Q	Q-p
fhág	fhág	fág-V	Vmis
sí	sí	sí-P	Pp3fsn
é	é	é-P	Pp3ms
ar	ar	ar-S	Sp
leac	leac	leac-N	Ncfsc
na	na	na-T	Tdfsg
fuinneoige	fuinneoige	fuinneog-N	Ncfsg
.	.	.-F	Fe
B	B	B-X	Xl
’	’	’-F	Fa
fhacthas	fhacthas	feic-V	Vmis0--n
do	do	do-S	Sp
Chaoimhe	Chaoimhe	Caoimhe-N	Npfsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
mac	mac	mac-N	Ncmsc
tíre	tíre	tír-N	Ncfsg
beag	beag	beag-A	Aqp
ag	ag	ag-S	Sp
stánadh	stánadh	stán-N	Nv
uirthi	uirthi	ar-P	Pr3fs
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
na	na	na-T	Tdfsg
súile	súile	súil-N	Ncfsg
tríthi	tríthi	tríthi-N	Ncfsc
.	.	.-F	Fe
Bhreathnaigh	Bhreathnaigh	breathnaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
air	air	ar-P	Pr3ms
ar feadh	ar feadh	ar_feadh-S	Spc
nóiméid	nóiméid	nóiméad-N	Ncmsg
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
cuimhneamh	cuimhneamh	cuimhnigh-N	Nv
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
seal	seal	seal-N	Ncmsc
beag	beag	beag-A	Aq-msc
aoibhinn	aoibhinn	aoibhinn-A	Aq-msc
ina	ina	i-S	Spp-p|Spp-s
mac	mac	mac-N	Ncmsc
tíre	tíre	tír-N	Ncfsg
…	…	…-F	Fi
í	í	í-P	Pp3fs
folláin	folláin	folláin-A	Aqp
,	,	,-F	Fi
scafánta	scafánta	scafánta-A	Aqp
,	,	,-F	Fi
saor	saor	saor-A	Aqp
.	.	.-F	Fe
