Amestrus	Amestrus	Amestrus-N	Npmsc
sa	sa	i-S	Spa-s
Mhúsaem	Mhúsaem	músaem-N	Ncmsc
Tráthnóna	Tráthnóna	tráthnóna-N	Ncmsc|Ncmsg
báistí	báistí	báistigh-A	Av
,	,	,-F	Fi
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
turasóir	turasóir	turasóir-N	Ncmsc
deireanach	deireanach	deireanach-A	Aq-msc
imithe	imithe	imigh-A	Av
agus	agus	agus-C	Cc
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
mór	mór	mór-A	Aq-msc
dúnta	dúnta	dún-A	Av
ag	ag	ag-S	Sp
an	an	an-T	Td-s
bhfear	bhfear	fear-N	Ncmsc
slándála	slándála	slándáil-N	Ncfsg
,	,	,-F	Fi
thit	thit	tit-V	Vmis
ciúnas	ciúnas	ciúnas-N	Ncmsc
seal	seal	seal-N	Ncmsc
ar	ar	ar-S	Sp
Mhúsaem	Mhúsaem	músaem-N	Ncmsc
Stair	Stair	stair-N	Ncfsc
an	an	an-T	Td-s
Dúlra	Dúlra	dúlra-N	Ncmsg
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
ainmhithe	ainmhithe	ainmhí-N	Ncmpc
an	an	an-T	Td-s
mhúsaeim	mhúsaeim	músaem-N	Ncmsg
ag	ag	ag-S	Sp
ullmhú	ullmhú	ullmhaigh-N	Nv
i	i	i-S	Sp
gcomhair	gcomhair	comhair-N	Ns-s
oíche	oíche	oíche-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
scéalaíochta	scéalaíochta	scéalaíocht-N	Ncfsg
.	.	.-F	Fe
'	'	'-F	Fa
Nach	Nach	nach-Q	Qnr
mbíonn	mbíonn	bí-V	Vmig
an	an	an-T	Td-s
aimsir	aimsir	aimsir-N	Ncfsc
in	in	sin-P	Pd
éirinn	éirinn	éir-V	Vmih1s
go	go	go-U	Ua
hainnis	hainnis	ainnis-A	Aqp
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Míol	Míol	míol-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
Gorm	Gorm	gorm-A	Aq-msc
ón	ón	ó-S	Spa-s
áit	áit	áit-N	Ncfsc
ina	ina	i-S	Spr
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
foluain	foluain	foluain-N	Ncfsc
go	go	go-U	Ua
hard	hard	ard-X	Xfea|Aqp
san	san	sin-S	Spa-s|Pd
aer	aer	aer-N	Ncmpg|Ncmsc
faoi	faoi	faoi-S	Sp
dhíon	dhíon	díon-N	Ncmsc
mór	mór	mór-A	Aq-msc
gloine	gloine	gloine-N	Ncfsc
an	an	an-T	Td-s
mhúsaeim	mhúsaeim	músaem-N	Ncmsg
.	.	.-F	Fe
Lig	Lig	lig-V	Vmis
sé	sé	sé-P	Pp3msn
osna	osna	osna-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Cuireann	Cuireann	cuir-V	Vmip
an	an	an-T	Td-s
bháisteach	bháisteach	báisteach-N	Ncfsc
seo	seo	seo-D	Dd
uaigneas	uaigneas	uaigneas-N	Ncmsc
orm	orm	ar-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
,	,	,-F	Fi
'	'	'-F	Fa
mar	mar	mar-C	Cs
cuireann	cuireann	cuir-V	Vmip
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
fharraige	fharraige	farraige-N	Ncfsc
i	i	i-S	Sp
gcuimhne	gcuimhne	cuimhne-N	Ncfsc
dom	dom	do-P	Pr1-s
.	.	.-F	Fe
'	'	'-F	Fa
Tharraing	Tharraing	tarraing-V	Vmis
sé	sé	sé-P	Pp3msn
anáil	anáil	anáil-N	Ncfsc
agus	agus	agus-C	Cc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
lig	lig	lig-V	Vmis
sé	sé	sé-P	Pp3msn
amach	amach	amach-R	Rd
í	í	í-P	Pp3fs
steall	steall	steall-N	Ncfsc
uisce	uisce	uisce-N	Ncmsg|Ncmsc|Ncmsg
amach	amach	amach-R	Rd
as	as	as-P	Pr3ms|Sp|Ncmsc
in	in	i-S	Sp
airde	airde	airde-N	Ncfpc|Ncfsc
agus	agus	agus-C	Cc
thit	thit	tit-V	Vmis
anuas	anuas	anuas-R	Rd
ar	ar	ar-S	Sp
cheann	cheann	ceann-N	Ncmsc
an	an	an-T	Td-s
Tíogair	Tíogair	tíogar-N	Ncmsg
.	.	.-F	Fe
Baineadh	Baineadh	bain-V	Vmis0
geit	geit	geit-N	Ncfsc
as	as	as-S	Sp
an	an	an-T	Td-s
Tíogar	Tíogar	tíogar-N	Ncmsc
agus	agus	agus-C	Cc
lig	lig	lig-V	Vmis
sé	sé	sé-P	Pp3msn
béic	béic	béic-N	Ncfsc
as	as	as-P	Pr3ms
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
na	na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpc
eile	eile	eile-D	Dd
suas	suas	suas-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
Míol	Míol	míol-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
Gorm	Gorm	gorm-A	Aq-msc
le	le	le-S	Sp
barr	barr	barr-N	Ncmsc
iontais	iontais	iontas-N	Ncmsg
.	.	.-F	Fe
'	'	'-F	Fa
Nach	Nach	nach-Q	Qnrs
ndúirt	ndúirt	abair-V	Vmis
mé	mé	mé-P	Pp1-s
leatsa	leatsa	le-P	Pr2-s-e
cheana	cheana	cheana-R	Rg
gan	gan	gan-S	Sp
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
gearán	gearán	gearán-N	Nv
faoin	faoin	faoi-S	Spa-s
drochaimsir	drochaimsir	drochaimsir-N	Ncfsc
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
Tíogar	Tíogar	tíogar-N	Ncmsc
,	,	,-F	Fi
na	na	na-T	Td-p
fiacla	fiacla	fiacail-N	Ncfpc
ag	ag	ag-S	Sp
imeacht	imeacht	imigh-N	Nv
sa	sa	i-S	Spa-s
cheann	cheann	ceann-N	Ncmsc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
'	'	'-F	Fa
Má	Má	má-C	Cs
bhíonn	bhíonn	bí-V	Vmig
drochaimsir	drochaimsir	drochaimsir-N	Ncfsc
ann	ann	i-P	Pr3ms
b	b	b-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
go	go	go-Q	Q
dtiocfadh	dtiocfadh	tar-V	Vmc
sneachta	sneachta	sneachta-N	Ncmsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
deas	deas	deas-A	Aqp
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
ghlanann	ghlanann	glan-V	Vmip
an	an	an-T	Td-s
sneachta	sneachta	sneachta-N	Ncmsc
mo	mo	mo-D	Dp1-s
chóta	chóta	cóta-N	Ncmsc
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
gach	gach	gach-D	Dq
duine	duine	duine-N	Ncmsc
ag	ag	ag-S	Sp
baint	baint	bain-N	Nv
lán	lán	lán-N	Ncmsc
na	na	na-T	Td-p
súl	súl	súil-N	Ncfpg
asam	asam	as-P	Pr1-s
ansin	ansin	ansin-R	Rt|Rl
.	.	.-F	Fe
Go	Go	go-U	Ua
deimhin	deimhin	deimhin-A	Aqp
,	,	,-F	Fi
deir	deir	abair-V	Vmip
siad	siad	siad-P	Pp3-pn
go	go	go-Q	Q
bhfuilim	bhfuilim	bí-V	Vmip1s-d
go	go	go-U	Ua
hálainn	hálainn	álainn-A	Aqp
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
rud	rud	rud-N	Ncmsc
beag	beag	beag-A	Aq-msc
eile	eile	eile-D	Dd
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
leis	leis	le-S	Sp
an	an	an-T	Td-s
Míol	Míol	míol-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
Gorm	Gorm	gorm-A	Aq-msc
,	,	,-F	Fi
'	'	'-F	Fa
nach	nach	nach-W	Wprin|Wpdin|Wpsin|Cs
méanar	méanar	méanar-A	Aqp
duit	duit	do-P	Pr2-s
a	a	a-U	U
bheith	bheith	bí-N	Nv
thuas	thuas	thuas-R	Rd
san	san	i-S	Spa-s
aer	aer	aer-N	Ncmsc
úr	úr	úr-A	Aq-msc
ansin	ansin	ansin-R	Rt|Rl
!	!	!-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Níl	Níl	bí-V	Vmip---n
meas	meas	meas-N	Ncmsc
madra	madra	madra-N	Ncmsg|Ncmsc
agamsa	agamsa	ag-P	Pr1-s-e
ar	ar	ar-S	Sp
an	an	an-T	Td-s
aer	aer	aer-N	Ncmsc
úr	úr	úr-A	Aq-msc
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
Míol	Míol	míol-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
Gorm	Gorm	gorm-A	Aq-msc
agus	agus	agus-C	Cc
uisce	uisce	uisce-N	Ncmsg|Ncmsc|Ncmsg
ag	ag	ag-S	Sp
spalpadh	spalpadh	spalp-N	Nv
óna	óna	ó-S	Spp-s
bhéal	bhéal	béal-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Is	Is	is-W	Wp-i
fuath	fuath	fuath-N	Ncmsc
liom	liom	le-P	Pr1-s
é	é	é-P	Pp3ms
!	!	!-F	Fe
Is	Is	is-W	Wp-i
fearr	fearr	maith-A	Aqc
liom	liom	le-P	Pr1-s
t	t	t-X	Xl
‑	‑	‑-F	Fb
uisce	uisce	uisce-N	Ncmsc
!	!	!-F	Fe
'	'	'-F	Fa
Dhúisigh	Dhúisigh	dúisigh-V	Vmis
an	an	an-T	Td-s
Madra	Madra	madra-N	Ncmsc
Rua	Rua	Rua-N	Npmsg|Npmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
cheap	cheap	ceap-V	Vmis
sé	sé	sé-P	Pp3msn
gur	gur	gur-Q	Q--s
chuala	chuala	clois-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
ainm	ainm	ainm-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
duine	duine	duine-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
ag	ag	ag-S	Sp
magadh	magadh	magadh-N	Nv-----n
fúm	fúm	faoi-P	Pr1-s
?	?	?-F	Fq
'	'	'-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
ón	ón	ó-S	Spa-s
áit	áit	áit-N	Ncfsc
ina	ina	i-S	Spr
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
luachair	luachair	luachair-N	Ncfsc
i	i	i-S	Sp
Seomra	Seomra	seomra-N	Ncmsc
na	na	na-T	Tdfsg
héireann	héireann	héir-V	Vmip
,	,	,-F	Fi
éan	éan	éan-N	Ncmsc
marbh	marbh	marbh-A	Aq-msc
in aice	in aice	in_aice-S	Spc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
'	'	'-F	Fa
Gabh	Gabh	gabh-V	Vmm-2s
mo	mo	mo-D	Dp1-s
leithscéal	leithscéal	leithscéal-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Míol	Míol	míol-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
Gorm	Gorm	gorm-A	Aq-msc
go	go	go-U	Ua
maorga	maorga	maorga-A	Aqp
,	,	,-F	Fi
'	'	'-F	Fa
ach	ach	ach-C	Cs
ní	ní	is-W	Wp-in
leatsa	leatsa	le-P	Pr2-s-e
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
.	.	.-F	Fe
'	'	'-F	Fa
Chas	Chas	Cas-N	Npfsg
sé	sé	is-W	Wp-i-3
a	a	a-D	Dp3
dhroim	dhroim	droim-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
Madra	Madra	madra-N	Ncmsc
Rua	Rua	Rua-N	Npmsg|Npmsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
lean	lean	lean-V	Vmis
sé	sé	sé-P	Pp3msn
air	air	ar-P	Pr3ms
ag	ag	ag-S	Sp
féachaint	féachaint	féach-N	Nv
amach	amach	amach-R	Rd
an	an	an-T	Td-s
díon	díon	díon-N	Ncmsc
mór	mór	mór-A	Aq-msc
gloine	gloine	gloine-N	Ncfsg|Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbáisteach	mbáisteach	báisteach-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
titim	titim	tit-N	Nv
gan	gan	gan-S	Sp
stad	stad	stad-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcathair	gcathair	cathair-N	Ncfsc
thíos	thíos	thíos-R	Rd
faoi	faoi	faoi-P	Pr3ms
agus	agus	agus-C	Cc
ar	ar	ar-S	Sp
na	na	na-T	Td-p
daoine	daoine	duine-N	Ncmpc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
thar	thar	thar-S	Sp
bráid	bráid	bráid-N	Ncfsc
faoi	faoi	faoi-S	Sp
dheifir	dheifir	deifir-N	Ncfsc
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
labhair	labhair	labhair-V	Vmis
sé	sé	sé-P	Pp3msn
arís	arís	arís-R	Rg
:	:	:-F	Fi
'	'	'-F	Fa
Nach	Nach	nach-W	Wprin|Wpdin|Wpsin|Cs
deas	deas	deas-N	Ns-s|Aqp
é	é	é-P	Pp3ms
seo	seo	seo-P	Pd
.	.	.-F	Fe
Caithimse	Caithimse	caith-V	Vmip1s--e
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
agus	agus	agus-C	Cc
daoine	daoine	duine-N	Ncmpg|Ncmpc
ag	ag	ag-S	Sp
faire	faire	fair-N	Nv
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
anois	anois	anois-R	Rt
tá	tá	bí-V	Vmip
deis	deis	deis-N	Ncfsc
agamsa	agamsa	ag-P	Pr1-s-e
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
faire	faire	fair-N	Nv
i	i	i-S	Sp
ngan fhios	ngan fhios	gan_fhios-N	Ncmsc
orthusan	orthusan	ar-P	Pr3-p-e
!	!	!-F	Fe
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
Damhán	Damhán	damhán-N	Ncmsc
Alla	Alla	alla-N	Ncmsc|Ncmsg
tar éis	tar éis	tar_éis-S	Spc
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
éisteacht	éisteacht	éist-N	Nv
leis	leis	le-S	Sp
an	an	an-T	Td-s
gcomhrá	gcomhrá	comhrá-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
dealbh	dealbh	dealbh-N	Ncfsc
nua	nua	nua-A	Aqp
a	a	a-Q	Q-r
tugadh	tugadh	tabhair-V	Vmis0
isteach	isteach	isteach-R	Rd
an	an	an-T	Td-s
mhaidin	mhaidin	maidin-N	Ncfsc
sin	sin	sin-D	Dd
.	.	.-F	Fe
Thuirling	Thuirling	tuirling-V	Vmis
sé	sé	sé-P	Pp3msn
di	di	do-P	Pr3fs
go	go	go-U	Ua
tapa	tapa	tapa-A	Aqp
.	.	.-F	Fe
'	'	'-F	Fa
Is	Is	is-W	Wp-i
fada	fada	fada-A	Aqp
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
ó	ó	ó-C	Cs
bhí	bhí	bí-V	Vmis
duine	duine	duine-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
ag	ag	ag-S	Sp
baint	baint	bain-N	Nv
lán	lán	lán-N	Ncmsc
na	na	na-T	Td-p
súl	súl	súil-N	Ncfpg
asatsa	asatsa	as-P	Pr2-s-e
,	,	,-F	Fi
a	a	a-U	Uv
Thíogair	Thíogair	tíogar-N	Ncmsv
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
i	i	i-S	Sp
nglór	nglór	glór-N	Ncmsc
beag	beag	beag-A	Aq-msc
íseal	íseal	íseal-A	Aq-msc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
an	an	an-T	Td-s
Tíogar	Tíogar	tíogar-N	Ncmsc
timpeall	timpeall	timpeall-R	Rd
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sé	sé	sé-P	Pp3msn
ábalta	ábalta	ábalta-A	Aqp
rud	rud	rud-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
sa	sa	i-S	Spa-s
dorchadas	dorchadas	dorchadas-N	Ncmsc
seachas	seachas	seachas-S	Sp
na	na	na-T	Td-p
céadta	céadta	céad-N	Ncmpc
boscaí	boscaí	bosca-N	Ncmpg|Ncmpc
gloine	gloine	gloine-N	Ncfsg|Ncfsc
ina	ina	i-S	Spr
raibh	raibh	bí-V	Vmis---d
cuid	cuid	cuid-N	Ncfsc
de	de	de-S	Sp
na	na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpc
beaga	beaga	beag-A	Aq--pc
ina	ina	i-S	Spp-p
gcónaí	gcónaí	cónaí-N	Ncmsc
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
fearg	fearg	fearg-N	Ncfsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
'	'	'-F	Fa
Cé	Cé	cé-P	Pq
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
é	é	é-P	Pp3ms
sin	sin	sin-P	Pd
?	?	?-F	Fq
'	'	'-F	Fa
a	a	a-Q	Q-r
bhéic	bhéic	béic-V	Vmis
an	an	an-T	Td-s
Tíogar	Tíogar	tíogar-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Nach	Nach	nach-Q	Qnr|Qnq
mbíonn	mbíonn	bí-V	Vmig
daoine	daoine	duine-N	Ncmpc
ag	ag	ag-S	Sp
baint	baint	bain-N	Nv
lán	lán	lán-N	Ncmsc
na	na	na-T	Td-p
súl	súl	súil-N	Ncfpg
asamsa	asamsa	as-P	Pr1-s-e
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bhíonn	bhíonn	bí-V	Vmig
siad	siad	siad-P	Pp3-pn
as	as	as-S	Sp
an	an	an-T	Td-s
Míol	Míol	míol-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
Gorm	Gorm	gorm-A	Aq-msc
?	?	?-F	Fq
Nach	Nach	nach-Q	Qnr
mbíonn	mbíonn	bí-V	Vmig
cláracha	cláracha	clár-N	Ncmpc
fúmsa	fúmsa	faoi-P	Pr1-s-e
ar	ar	ar-S	Sp
an	an	an-T	Td-s
teilifís	teilifís	teilifís-N	Ncfsc
ó	ó	ó-S	Sp
mhaidin	mhaidin	maidin-N	Ncfsc
go	go	go-S	Sp
hoíche	hoíche	oíche-N	Ncfsc
!	!	!-F	Fe
Taispeáin	Taispeáin	taispeáin-V	Vmm-2s
tú	tú	tú-P	Pp2-s
féin	féin	féin-P	Px
!	!	!-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Táim	Táim	bí-V	Vmip1s
anseo	anseo	anseo-R	Rl
…	…	…-F	Fi
anseo	anseo	anseo-R	Rl
…	…	…-F	Fi
anseo	anseo	anseo-R	Rl
.	.	.-F	Fe
Nach	Nach	nach-Q	Qnq
bhfeiceann	bhfeiceann	feic-V	Vmip
tú	tú	tú-P	Pp2-s
mé	mé	mé-P	Pp1-s
?	?	?-F	Fq
'	'	'-F	Fa
Agus	Agus	agus-C	Cc
,	,	,-F	Fi
leis	leis	le-S	Sp
sin	sin	sin-P	Pd
,	,	,-F	Fi
léim	léim	léim-V	Vmip1s|Vmm-2s|Ncfsc|Nv|Vmis|Nv
an	an	an-T	Td-s
Damhán	Damhán	damhán-N	Ncmsc
Alla	Alla	alla-N	Ncmsc|Ncmsg
anuas	anuas	anuas-R	Rd
thosaigh	thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
rince	rince	rinc-N	Nv
ar	ar	ar-S	Sp
shrón	shrón	srón-N	Ncfsc
an	an	an-T	Td-s
Tíogair	Tíogair	tíogar-N	Ncmsg
.	.	.-F	Fe
'	'	'-F	Fa
Go	Go	go-U	Ua
bog	bog	bog-A	Aqp
,	,	,-F	Fi
a	a	a-U	Uv
chairde	chairde	cairde-N	Ncmpv|Ncmsv
.	.	.-F	Fe
Tógaigí	Tógaigí	tóg-V	Vmm-2p
go	go	go-U	Ua
bog	bog	bog-A	Aqp
é	é	é-P	Pp3ms
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
Fia	Fia	fia-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
ardaigh	ardaigh	ardaigh-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
bheanna	bheanna	beann-N	Ncfpc
san	san	sin-S	Spa-s|Pd
aer	aer	aer-N	Ncmpg|Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Féachaigí	Féachaigí	féach-V	Vmm-2p
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
féachaint	féachaint	féach-N	Nv
timpeall	timpeall	timpeall-R	Rd
ar	ar	ar-S	Sp
na	na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpc
eile	eile	eile-D	Dd
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
cuid	cuid	cuid-N	Ncfsc
againn	againn	ag-P	Pr1-p
i	i	i-S	Sp
mbaol	mbaol	baol-N	Ncmsc
agus	agus	agus-C	Cc
tá	tá	bí-V	Vmip
deireadh	deireadh	deireadh-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
gcuid	gcuid	cuid-N	Ncfsc
eile	eile	eile-D	Dd
againn	againn	ag-P	Pr1-p
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
is	is	is-W	Wp-i
ag	ag	ag-S	Sp
ceiliúradh	ceiliúradh	ceiliúir-N	Nv
atáimid	atáimid	bí-V	Vmip1p-r
anocht	anocht	anocht-N	Ns-s|Rt
!	!	!-F	Fe
Ár	Ár	ár-N	Ncmsc|Dp1-p
n	n	n-X	Xl
‑	‑	‑-F	Fb
oíche	oíche	oíche-N	Ncfsc
scéalaíochta	scéalaíochta	scéalaíocht-N	Ncfsg
!	!	!-F	Fe
Mar	Mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
ba	ba	is-W	Ws|Ws-i
mhaith	mhaith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
,	,	,-F	Fi
mar	mar	mar-S	Sp
Fhia	Fhia	fia-N	Ncmsc
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
,	,	,-F	Fi
seans	seans	seans-N	Ncmsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
do	do	do-S	Sp
gach	gach	gach-D	Dq
ainmhí	ainmhí	ainmhí-N	Ncmsc
a	a	a-D	Dp3
scéal	scéal	scéal-N	Ncmsc
a	a	a-U	U
insint	insint	inis-N	Nv
.	.	.-F	Fe
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
na	na	na-T	Td-p
cluasa	cluasa	cluas-N	Ncfpc
ar	ar	ar-S	Sp
bior	bior	bior-N	Ncmsc
acu	acu	ag-P	Pr3-p
go	go	go-U	Ua
léir	léir	léir-A	Aqp
.	.	.-F	Fe
Go	Go	go-U	Ua
tobann	tobann	tobann-A	Aqp
briseadh	briseadh	bris-V	Vmis0
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gciúnas	gciúnas	ciúnas-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
Míol	Míol	míol-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
maol	maol	maol-A	Aq-msc
i	i	i-S	Sp
mbaol	mbaol	baol-N	Ncmsc
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
Míol	Míol	míol-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
maol	maol	maol-A	Aq-msc
i	i	i-S	Sp
mbaol	mbaol	baol-N	Ncmsc
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-Q	Q-r
scread	scread	scread-V	Vmis
an	an	an-T	Td-s
Phearóid	Phearóid	Pearóid-N	Npfsg
ón	ón	ó-S	Spa-s
Taispeántas	Taispeántas	taispeántas-N	Ncmsc
Idirnáisiúnta	Idirnáisiúnta	idirnáisiúnta-A	Aqp
thuas	thuas	tuaigh-V	Vmip---r
staighre	staighre	staighre-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcéad	gcéad	céad-M	Mo
urlár	urlár	urlár-N	Ncmpg|Ncmsc
.	.	.-F	Fe
Áit	Áit	áit-N	Ncfsc
éigin	éigin	éigin-A	Aq-fsc
sa	sa	i-S	Spa-s
Ghailearaí	Ghailearaí	gailearaí-N	Ncmsc
íochtarach	íochtarach	íochtarach-A	Aq-msc
i mbun	i mbun	i_mbun-S	Spc
an	an	an-T	Td-s
mhúsaeim	mhúsaeim	músaem-N	Ncmsg
rinne	rinne	déan-V	Vmis
ainmhí	ainmhí	ainmhí-N	Ncmsc
beag	beag	beag-A	Aq-msc
gáire	gáire	gáir-N	Ncfsg|Nv|Ncmsg|Ncmsc|Nv--g
.	.	.-F	Fe
Réitigh	Réitigh	réitigh-V	Vmis|Vmm-2s
an	an	an-T	Td-s
Fia	Fia	fia-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
a	a	a-D	Dp3
scornach	scornach	scornach-N	Ncfsc
ach	ach	ach-C	Cs
,	,	,-F	Fi
sula	sula	sula-C	Cs
raibh	raibh	bí-V	Vmis---d
seans	seans	seans-N	Ncmsc
aige	aige	ag-P	Pr3ms
aon	aon	aon-D	Dq
rud	rud	rud-N	Ncmsc
a	a	a-U	U
rá	rá	abair-N	Nv
,	,	,-F	Fi
chuala	chuala	clois-V	Vmis
sé	sé	sé-P	Pp3msn
torann	torann	torann-N	Ncmsc
taobh	taobh	taobh-N	Ncmsc
thiar	thiar	thiar-R	Rd
de	de	de-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
rud	rud	rud-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
tar éis	tar éis	tar_éis-S	Spc
titim	titim	tit-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
urlár	urlár	urlár-N	Ncmsc
.	.	.-F	Fe
Chas	Chas	Cas-N	Npfsg
sé	sé	is-W	Wp-i-3
timpeall	timpeall	timpeall-R	Rd|Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
le	le	le-S	Sp
feiceáil	feiceáil	feic-N	Nv
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
dealbh	dealbh	dealbh-A	Aqp
mharmair	mharmair	marmar-N	Ncmsg
nua	nua	nua-A	Aqp
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
faoi	faoi	faoi-S	Sp
scáileanna	scáileanna	scáil-N	Ncfpc
na	na	na-T	Tdfsg
hoíche	hoíche	oíche-N	Ncfsg
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
sé	sé	sé-P	Pp3msn
aghaidh	aghaidh	aghaidh-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcomhluadar	gcomhluadar	comhluadar-N	Ncmsc
arís	arís	arís-R	Rg
.	.	.-F	Fe
'	'	'-F	Fa
Bhuel	Bhuel	bhuel-X	Xsc
,	,	,-F	Fi
a	a	a-U	Uv
chairde	chairde	cara-N	Ncmsv|Ncmpv
,	,	,-F	Fi
tá	tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
in	in	i-S	Sp
am	am	am-N	Ncmsc
tús	tús	tús-N	Ncmsc
a	a	a-U	U
chur	chur	cuir-N	Nv
leis	leis	le-S	Sp
an	an	an-T	Td-s
oíche	oíche	oíche-N	Ncfsc
scéalaíochta	scéalaíochta	scéalaíocht-N	Ncfsg
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
'	'	'-F	Fa
Glaoim	Glaoim	Glaoim-N	Npmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mBeach	mBeach	beach-N	Ncfsc
Fhiáin	Fhiáin	fiáin-A	Aq-fsc|Aq-fsv
.	.	.-F	Fe
A	A	a-U	Uv
Bheach	Bheach	beach-N	Ncfsv
,	,	,-F	Fi
an	an	an-Q	Qq
inseoidh	inseoidh	inis-V	Vmif
tú	tú	tú-P	Pp2-s
do	do	do-S	Sp
scéal	scéal	scéal-N	Ncmsc
dúinn	dúinn	do-P	Pr1-p
?	?	?-F	Fq
'	'	'-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
eitil	eitil	eitil-N	Ncfsc|Vmm-2s
an	an	an-T	Td-s
Bheach	Bheach	beach-N	Ncfsc
Fhiáin	Fhiáin	fiáin-A	Aq-fsc
os	os	os-N	Ncmpg|Ncmsc|Sp
a	a	a-D	Dp3
gcionn	gcionn	ceann-N	Ncfsd
in	in	i-S	Sp
airde	airde	airde-N	Ncfpc|Ncfsc
gur	gur	gur-Q	Q--s
thuirling	thuirling	tuirling-V	Vmis
ar	ar	ar-S	Sp
dhroim	dhroim	droim-N	Ncmsc
a	a	a-D	Dp3
seancharad	seancharad	cara-N	Ncmsg
,	,	,-F	Fi
an	an	an-T	Td-s
Míol	Míol	míol-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
Gorm	Gorm	gorm-A	Aq-msc
,	,	,-F	Fi
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
fós	fós	fós-R	Rg
ag	ag	ag-S	Sp
féachaint	féachaint	féach-N	Nv
amach	amach	amach-R	Rd
an	an	an-T	Td-s
díon	díon	díon-N	Ncmsc
mór	mór	mór-A	Aq-msc
gloine	gloine	gloine-N	Ncfsg|Ncfsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
na	na	na-T	Td-p
haghaidheanna	haghaidheanna	aghaidh-N	Ncfpc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
thíos	thíos	thíos-R	Rd
fúithi	fúithi	faoi-P	Pr3fs
.	.	.-F	Fe
'	'	'-F	Fa
Inseoidh	Inseoidh	inis-V	Vmif
,	,	,-F	Fi
cinnte	cinnte	cinnte-A	Av|Aqp
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
Ach	Ach	ach-S	Sp|Cs
in	in	i-S	Sp
ionad	ionad	ionad-N	Ncmsc
a	a	a-D	Dp3
scéal	scéal	scéal-N	Ncmsc
a	a	a-U	U
insint	insint	inis-N	Nv
nuair	nuair	nuair-C	Cs
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
béal	béal	béal-N	Ncmsc
beag	beag	beag-A	Aq-msc
,	,	,-F	Fi
lig	lig	lig-V	Vmis
sí	sí	sí-P	Pp3fsn
liú	liú	liú-N	Ncmsc
mór	mór	mór-A	Aq-msc
aisti	aisti	as-P	Pr3fs
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
léim	léim	léim-N	Nv
suas	suas	suas-R	Rd
síos	síos	síos-R	Rd
ar	ar	ar-S	Sp
dhroim	dhroim	droim-N	Ncmsc
an	an	an-T	Td-s
Mhíl	Mhíl	míol-N	Ncmsg
Mhóir	Mhóir	mór-A	Aq-msg
Ghoirm	Ghoirm	Goirm-N	Npfsg
.	.	.-F	Fe
'	'	'-F	Fa
ó	ó	ó-C	Cs
!	!	!-F	Fe
ó	ó	ó-C	Cs
!	!	!-F	Fe
!	!	!-F	Fe
Ghortaigh	Ghortaigh	gortaigh-V	Vmis
tú	tú	tú-P	Pp2-s
mé	mé	mé-P	Pp1-s
!	!	!-F	Fe
Tóg	Tóg	tóg-V	Vmm-2s
go	go	go-U	Ua
bog	bog	bog-A	Aqp
é	é	é-P	Pp3ms
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Míol	Míol	míol-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
Gorm	Gorm	gorm-A	Aq-msc
.	.	.-F	Fe
'	'	'-F	Fa
Is	Is	is-W	Wp-i
í	í	í-P	Pp3fs
atá	atá	bí-V	Vmip---r
ann	ann	i-P	Pr3ms
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
Bheach	Bheach	beach-N	Ncfsc
Fhiáin	Fhiáin	fiáin-A	Aq-fsc
agus	agus	agus-C	Cc
bús	bús	bús-N	Ncmsc
ceart	ceart	ceart-A	Aq-msc
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
'	'	'-F	Fa
Is	Is	is-W	Wp-i
í	í	í-P	Pp3fs
atá	atá	bí-V	Vmip---r
ann	ann	i-P	Pr3ms
!	!	!-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Sancam	Sancam	Sancam-N	Npmsc
soncam	soncam	am-N	Ncmsc
,	,	,-F	Fi
ach	ach	ach-C	Cs
cad	cad	cad-W	W--q
atá	atá	bí-V	Vmip---r
ort	ort	ar-P	Pr2-s
anois	anois	anois-R	Rt
,	,	,-F	Fi
a	a	a-U	Uv
Bheach	Bheach	beach-N	Ncfsv
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Dineasár	Dineasár	dineasár-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Sin	Sin	sin-W	W
í	í	í-P	Pp3fs
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
a	a	a-Q	Q-r
chuir	chuir	cuir-V	Vmis
chun	chun	chun-S	Sp
báis	báis	bás-N	Ncmsg
mé	mé	mé-P	Pp1-s
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Bheach	Bheach	beach-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
Aithním	Aithním	aithin-V	Vmip1s
an	an	an-T	Td-s
scáth	scáth	scáth-N	Ncmsc
fearthainne	fearthainne	fearthainn-N	Ncfsg|Nv--g--n
sin	sin	sin-D	Dd
!	!	!-F	Fe
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
Míol	Míol	míol-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
Gorm	Gorm	gorm-A	Aq-msc
fós	fós	fós-R	Rg
ag	ag	ag-S	Sp
féachaint	féachaint	féach-N	Nv
amach	amach	amach-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcathair	gcathair	cathair-N	Ncfsc
thíos	thíos	thíos-R	Rd
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
rith	rith	rith-N	Nv
thar	thar	thar-S	Sp
an	an	an-T	Td-s
músaem	músaem	músaem-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ar	ar	ar-S	Sp
bís	bís	bís-N	Ncfsc
,	,	,-F	Fi
'	'	'-F	Fa
agus	agus	agus-C	Cc
tá	tá	bí-V	Vmip
sí	sí	sí-P	Pp3fsn
fliuch	fliuch	fliuch-A	Aqp
go	go	go-S	Sp
craiceann	craiceann	craiceann-N	Ncmsc
!	!	!-F	Fe
'	'	'-F	Fa
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
na	na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
a	a	a-Q	Q-r
mharaigh	mharaigh	maraigh-V	Vmis
an	an	an-T	Td-s
Bheach	Bheach	beach-N	Ncfsc
Fhiáin	Fhiáin	fiáin-A	Aq-fsc
ag	ag	ag-S	Sp
rith	rith	rith-N	Nv
thar	thar	thar-S	Sp
an	an	an-T	Td-s
músaem	músaem	músaem-N	Ncmsc
tháinig	tháinig	tar-V	Vmis
fearg	fearg	fearg-N	Ncfsc
orthu	orthu	ar-P	Pr3-p
.	.	.-F	Fe
'	'	'-F	Fa
Nach	Nach	is-C	Cs|Wpdin|Wpsin
dána	dána	dána-A	Aqp|Aqc
an	an	an-T	Td-s
aghaidh	aghaidh	aghaidh-N	Ncfsc
atá	atá	bí-V	Vmip---r
uirthi	uirthi	ar-P	Pr3fs
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Phearóid	Phearóid	Pearóid-N	Npfsg
.	.	.-F	Fe
'	'	'-F	Fa
Is	Is	is-W	Wp-i
ea	ea	ea-P	Pp3-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Bheach	Bheach	beach-N	Ncfsc
Fhiáin	Fhiáin	fiáin-A	Aq-fsc
,	,	,-F	Fi
'	'	'-F	Fa
ach	ach	ach-C	Cs
cheap	cheap	ceap-V	Vmis
sí	sí	sí-P	Pp3fsn
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
m	m	m-X	Xl
’	’	’-F	Fa
aghaidhse	aghaidhse	aghaidh-N	Ncfsc-e
níos	níos	níos-U	Uc
dána	dána	dána-A	Aqc
fós	fós	fós-R	Rg
!	!	!-F	Fe
Cheap	Cheap	ceap-V	Vmis
sí	sí	sí-P	Pp3fsn
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
a	a	a-D	Dp3
leanbh	leanbh	leanbh-N	Ncmsc
sa	sa	i-S	Spa-s
chliabhán	chliabhán	cliabhán-N	Ncmsc
a	a	a-U	U
ghortú	ghortú	gortaigh-N	Nv
.	.	.-F	Fe
Rinne	Rinne	déan-V	Vmis
mise	mise	mé-P	Pp1-s-e
crónán	crónán	crónán-N	Nv-----n|Ncmsc
speisialta	speisialta	speisialta-A	Aqp
don	don	do-S	Spa-s
leanbh	leanbh	leanbh-N	Ncmsc
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
seisean	seisean	sé-P	Pp3msne
ag	ag	ag-S	Sp
féachaint	féachaint	féach-N	Nv
aníos	aníos	aníos-R	Rd
orm	orm	ar-P	Pr1-s
,	,	,-F	Fi
é	é	é-P	Pp3ms
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
,	,	,-F	Fi
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
gáire	gáire	gáir-N	Nv
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
mharaigh	mharaigh	maraigh-V	Vmis
sí	sí	sí-P	Pp3fsn
mé	mé	mé-P	Pp1-s
lena	lena	le-S	Spp-s|Spp-p
scáth	scáth	scáth-N	Ncmsc
fearthainne	fearthainne	fearthainn-N	Ncfsg|Nv--g--n
!	!	!-F	Fe
Ar	Ar	ar-S	Sp
an	an	an-T	Td-s
spota	spota	spota-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Dá	Dá	dá-C	Cs
bhfaighinn	bhfaighinn	faigh-V	Vmc-1s-d|Vmih1s
greim	greim	greim-N	Ncmsc
uirthi	uirthi	ar-P	Pr3fs
siúd	siúd	siúd-P	Pd
chuirfinn	chuirfinn	cuir-V	Vmc-1s
mé	mé	mé-P	Pp1-s
féin	féin	féin-P	Px
timpeall	timpeall	timpeall-R	Rd|Ncmsc|Sp
a	a	a-D	Dp3
muiníl	muiníl	muineál-N	Ncmpc
agus	agus	agus-C	Cc
thachtfainn	thachtfainn	tacht-V	Vmc-1s
í	í	í-P	Pp3fs
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Nathair	Nathair	nathair-N	Ncfsc
Nimhe	Nimhe	nimh-N	Ncfsg
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
Bheach	Bheach	beach-N	Ncfsc
Fhiáin	Fhiáin	fiáin-A	Aq-fsc
faic	faic	faic-N	Ncfsg|Ncfsc
ach	ach	ach-S	Sp
crónán	crónán	crónán-N	Ncmsc
a	a	a-U	U
ligean	ligean	lig-N	Nv
.	.	.-F	Fe
'	'	'-F	Fa
Agus	Agus	agus-C	Cc
tusa	tusa	tú-P	Pp2-s-e
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
Fia	Fia	fia-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
'	'	'-F	Fa
Cad	Cad	cad-P	Pq
a	a	a-Q	Q-r
dhéanfása	dhéanfása	déan-V	Vmc-2s--e
,	,	,-F	Fi
a	a	a-U	Uv
Bheach	Bheach	beach-N	Ncfsv
,	,	,-F	Fi
ós	ós	ó-N	Ncmsc|Csw
rud	rud	rud-N	Ncmsc
é	é	é-P	Pp3ms
gur	gur	is-W	Wsdi
tusa	tusa	tú-P	Pp2-s-e
an	an	an-T	Td-s
neach	neach	neach-N	Ncmsg
a	a	a-Q	Q-r
mharaigh	mharaigh	maraigh-V	Vmis
sí	sí	sí-P	Pp3fsn
?	?	?-F	Fq
'	'	'-F	Fa
'	'	'-F	Fa
Ní	Ní	ní-Q	Qn
dhéanfainn	dhéanfainn	déan-V	Vmc-1s-n
aon	aon	aon-D	Dq
díobháil	díobháil	díobháil-N	Ncfsc
di	di	do-P	Pr3fs
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
Bheach	Bheach	beach-N	Ncfsc
Fhiáin	Fhiáin	fiáin-A	Aq-fsc|Aq-fsv
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
clann	clann	clann-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
uirthi	uirthi	ar-P	Pr3fs
agus	agus	agus-C	Cc
níor	níor	níor-Q	Qn-s
thuig	thuig	tuig-V	Vmip---n|Vmis---n
sí	sí	sí-P	Pp3fsn
cad	cad	cad-P	Pq
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
á	á	do-S	Spo-s
dhéanamh	dhéanamh	déan-N	Nv
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
'	'	'-F	Fa
Thit	Thit	tit-V	Vmis
ciúnas	ciúnas	ciúnas-N	Ncmsc
ar	ar	ar-S	Sp
na	na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpc
eile	eile	eile-D	Dd
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
a	a	a-D	Dp3
máthair	máthair	máthair-N	Ncfsc
ag	ag	ag-S	Sp
teastáil	teastáil	teastaigh-N	Nv
ó	ó	ó-S	Sp
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
sin	sin	sin-D	Dd
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
Bheach	Bheach	beach-N	Ncfsc
Fhiáin	Fhiáin	fiáin-A	Aq-fsc|Aq-fsv
.	.	.-F	Fe
'	'	'-F	Fa
Bíonn	Bíonn	bí-V	Vmig
máthair	máthair	máthair-N	Ncfsc
ag	ag	ag-S	Sp
teastáil	teastáil	teastaigh-N	Nv
uainn	uainn	ó-P	Pr1-p
go	go	go-U	Ua
léir	léir	léir-A	Aqp
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhógair	fhógair	fógair-V	Vmis
guth	guth	guth-N	Ncmsc
ó	ó	ó-S	Sp
lár	lár	lár-N	Ncmsc
an	an	an-T	Td-s
mhúsaeim	mhúsaeim	músaem-N	Ncmsg
–	–	–-X	Xx
guth	guth	guth-N	Ncmsc
nua	nua	nua-A	Aqp
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
cloiste	cloiste	clois-A	Av
cheana	cheana	cheana-R	Rg
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Chas	Chas	Cas-N	Npfsg
na	na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpg
timpeall	timpeall	timpeall-N	Ncmpg|Ncmsc|Rd
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
siad	siad	siad-P	Pp3-pn
rud	rud	rud-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
ar	ar	ar-S	Sp
dtús	dtús	tús-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ansin	ansin	ansin-R	Rt|Rl
bhog	bhog	bog-V	Vmis
na	na	na-T	Td-p
scamaill	scamaill	scamall-N	Ncmpc
sa	sa	i-S	Spa-s
spéir	spéir	spéir-N	Ncfsc
beagán	beagán	beagán-N	Ncmpg|Ncmsc
agus	agus	agus-C	Cc
tháinig	tháinig	tar-V	Vmis
solas	solas	solas-N	Ncmsc
na	na	na-T	Tdfsg
gealaí	gealaí	gealach-N	Ncfsg
isteach	isteach	isteach-R	Rd
tríd	tríd	trí-S	Sp
an	an	an-T	Td-s
díon	díon	díon-N	Ncmsc
.	.	.-F	Fe
Thit	Thit	tit-V	Vmis
sé	sé	sé-P	Pp3msn
anuas	anuas	anuas-R	Rd
ar	ar	ar-S	Sp
dhealbh	dhealbh	dealbh-N	Ncfsc
álainn	álainn	álainn-A	Aq-fsc
de	de	de-S	Sp
chailín	chailín	cailín-N	Ncmsc
óg	óg	óg-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
seasamh	seasamh	seas-N	Nv
ina	ina	i-S	Spp-s|Spp-p
staic	staic	staic-N	Ncfsc
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
i lár	i lár	i_lár-S	Spc
an	an	an-T	Td-s
tseomra	tseomra	seomra-N	Ncmsg
,	,	,-F	Fi
dath	dath	dath-V	Vmm-2s
dubh	dubh	dubh-N	Ncmsc
uirthi	uirthi	ar-P	Pr3fs
nach	nach	nach-W	Wprin|Wpdin|Wpsin|Cs
den	den	de-S	Spa-s
oíche	oíche	oíche-N	Ncfsc
é	é	é-P	Pp3ms
ach	ach	ach-S	Sp|Cs
de	de	de-S	Sp
mharmar	mharmar	marmar-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
A	A	an-T	Td-s
Thiarcais	Thiarcais	tiarcais-N	Ns-s
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Madra	Madra	madra-N	Ncmsc
Rua	Rua	Rua-N	Npmsg|Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Cé	Cé	cé-W	W--q
hí	hí	í-N	Ncfsg
sin	sin	sin-W	W
?	?	?-F	Fq
'	'	'-F	Fa
'	'	'-F	Fa
Sin	Sin	sin-W	W
í	í	í-P	Pp3fs
an	an	an-T	Td-s
dealbh	dealbh	dealbh-N	Ncfsc
nua	nua	nua-A	Aqp
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
Nathair	Nathair	nathair-N	Ncfsc
Nimhe	Nimhe	nimh-N	Ncfsg
.	.	.-F	Fe
'	'	'-F	Fa
An	An	an-T	Td-s
dealbh	dealbh	dealbh-N	Ncfsc
a	a	a-Q	Q-r
tugadh	tugadh	tabhair-V	Vmis0
isteach	isteach	isteach-R	Rd
ar	ar	ar-S	Sp
maidin	maidin	maidin-N	Ncfsc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
tá	tá	bí-V	Vmip
sí	sí	sí-P	Pp3fsn
ina	ina	i-S	Spp-s
dúiseacht	dúiseacht	dúiseacht-N	Ncfsc
!	!	!-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
ó	ó	ó-C	Cs
,	,	,-F	Fi
nílim	nílim	bí-V	Vmip1s-n
nua	nua	nua-N	Ncmsc
in	in	i-S	Sp
aon	aon	aon-D	Dq
chor	chor	cor-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
dealbh	dealbh	dealbh-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
Agus	Agus	agus-C	Cc
,	,	,-F	Fi
go	go	go-U	Ua
deimhin	deimhin	deimhin-A	Aqp
,	,	,-F	Fi
táim	táim	bí-V	Vmip1s
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
shuí	shuí	suí-N	Nv|Ncmsc
le	le	le-S	Sp
fada	fada	fada-A	Aqp
.	.	.-F	Fe
'	'	'-F	Fa
Rinne	Rinne	déan-V	Vmis
sí	sí	sí-P	Pp3fsn
gáire	gáire	gáire-N	Ncmsc
beag	beag	beag-A	Aq-msc
.	.	.-F	Fe
Sheas	Sheas	seas-V	Vmis
an	an	an-T	Td-s
Fia	Fia	fia-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
amach	amach	amach-R	Rd
ó	ó	ó-S	Sp
na	na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpc
eile	eile	eile-D	Dd
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
na	na	na-T	Td-p
beanna	beanna	beann-N	Ncfpc
síos	síos	síos-R	Rd
go dtí	go dtí	go_dtí-S	Spc
gur	gur	gur-Q	Q--s
theagmhaigh	theagmhaigh	teagmhaigh-V	Vmis
siad	siad	siad-P	Pp3-pn
leis	leis	le-S	Sp
an	an	an-T	Td-s
urlár	urlár	urlár-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Gabhaim	Gabhaim	gabh-V	Vmip1s
pardún	pardún	pardún-N	Ncmsc
thar ceann	thar ceann	thar_ceann-S	Spc
ainmhithe	ainmhithe	ainmhí-N	Ncmpg
an	an	an-T	Td-s
mhúsaeim	mhúsaeim	músaem-N	Ncmsg
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
,	,	,-F	Fi
'	'	'-F	Fa
ach	ach	ach-C	Cs
níor	níor	is-W	Ws-in
thuigeamar	thuigeamar	tuig-V	Vmis1p
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
chaint	chaint	caint-N	Ncfsc
agat	agat	ag-P	Pr2-s
!	!	!-F	Fe
Fáilte	Fáilte	fáilte-N	Ncfsc
romhat	romhat	roimh-P	Pr2-s
inár	inár	i-S	Spp-p
measc	measc	measc-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
maith	maith	maith-N	Ncfsc
agaibh	agaibh	ag-P	Pr2-p
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
dealbh	dealbh	dealbh-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
Mise	Mise	mé-P	Pp1-s-e
Amestrus	Amestrus	Amestrus-N	Npmsc
.	.	.-F	Fe
Deas	Deas	deas-N	Ns-s
bualadh	bualadh	buail-N	Ncmsc|Nv
libh	libh	le-P	Pr2-p
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
aontaím	aontaím	aontaigh-V	Vmip1s
leis	leis	le-S	Sp
an	an	an-T	Td-s
mBeach	mBeach	beach-N	Ncfsc
Fhiáin	Fhiáin	fiáin-A	Aq-fsc|Aq-fsv
.	.	.-F	Fe
A	A	a-U	Uv
chairde	chairde	cara-N	Ncmsv|Ncmpv
,	,	,-F	Fi
lig	lig	lig-V	Vmis|Vmm-2s
don	don	do-S	Spa-s
mháthair	mháthair	máthair-N	Ncfsc
sin	sin	sin-D	Dd
!	!	!-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sí	sí	sí-P	Pp3fsn
ach	ach	ach-S	Sp|Cs
ag	ag	ag-S	Sp
cosaint	cosaint	cosain-N	Nv
a	a	a-D	Dp3
linbh	linbh	leanbh-N	Ncmsg
.	.	.-F	Fe
'	'	'-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
na	na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
agus	agus	agus-C	Cc
chroith	chroith	croith-V	Vmis
an	an	an-T	Td-s
Madra	Madra	madra-N	Ncmsc
Rua	Rua	Rua-N	Npmsg|Npmsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
Phearóid	Phearóid	Pearóid-N	Npfsg
a	a	a-D	Dp3
gceann	gceann	ceann-N	Ncmpg
ó	ó	ó-S	Sp
thaobh	thaobh	taobh-N	Ncmsc
taobh	taobh	taobh-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Agus	Agus	agus-C	Cc
tusa	tusa	tú-P	Pp2-s-e
,	,	,-F	Fi
a	a	a-U	Uv
dhealbh	dhealbh	dealbh-N	Ncfsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Tíogar	Tíogar	tíogar-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Cén	Cén	cé-D	Dw--s
fáth	fáth	fáth-N	Ncmsc
a	a	a-Q	Q-i
bhfuil	bhfuil	bí-V	Vmip---d
tusa	tusa	tú-P	Pp2-s-e
sa	sa	i-S	Spa-s
mhúsaem	mhúsaem	músaem-N	Ncmsc
seo	seo	seo-D	Dd
anocht	anocht	anocht-N	Ns-s|Rt
?	?	?-F	Fq
'	'	'-F	Fa
Chuimil	Chuimil	cuimil-V	Vmis
Amestrus	Amestrus	Amestrus-N	Npmsc
a	a	a-D	Dp3
lámh	lámh	lámh-N	Ncfsc
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
faic	faic	faic-N	Ncfsc
ar feadh	ar feadh	ar_feadh-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
.	.	.-F	Fe
Ar	Ar	is-N	Ncmsc|Sp|Wssi|Q-is|Wpsi
deireadh	deireadh	deireadh-V	Vmih|Ncmsc
d	d	d-X	Xl
’	’	’-F	Fa
ardaigh	ardaigh	ardaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
ceann	ceann	ceann-N	Ncmsc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
sí	sí	sí-P	Pp3fsn
orthu	orthu	ar-P	Pr3-p
.	.	.-F	Fe
'	'	'-F	Fa
Ní	Ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
mé	mé	mé-P	Pp1-s
anseo	anseo	anseo-R	Rl
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
,	,	,-F	Fi
'	'	'-F	Fa
b	b	b-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
nach	nach	nach-W	Wprin|Wpdin|Wpsin|Cs
fiú	fiú	fiú-N	Ns-s|Ncmsc|Rg
mo	mo	mo-D	Dp1-s
scéal	scéal	scéal-N	Ncmsc
a	a	a-U	U
insint	insint	inis-N	Nv
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
ó	ó	ó-C	Cs
,	,	,-F	Fi
sin	sin	sin-P	Pd|W
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
siad	siad	siad-P	Pp3-pn
linn	linn	le-P	Pr1-p
go	go	go-U	Ua
léir	léir	léir-A	Aqp
na	na	na-T	Td-p
céadta	céadta	céad-N	Ncmpc
bliain	bliain	bliain-N	Ncfsc
ó	ó	ó-S	Sp
shin	shin	sin-P	Pd
,	,	,-F	Fi
a	a	a-U	Uv
Amestrus	Amestrus	Amestrus-N	Npmsc
,	,	,-F	Fi
agus	agus	agus-C	Cc
táimid	táimid	bí-V	Vmip1p
fós	fós	fós-R	Rg
anseo	anseo	anseo-R	Rl
!	!	!-F	Fe
Ba	Ba	is-W	Ws|Ws-i
bhreá	bhreá	breá-A	Aqp
linn	linn	le-P	Pr1-p
do	do	do-S	Sp
scéal	scéal	scéal-N	Ncmsc
a	a	a-U	U
chlos	chlos	clois-N	Nv
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Fia	Fia	fia-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
.	.	.-F	Fe
'	'	'-F	Fa
Nár	Nár	is-W	Ws-qn|Wsdin|Wsdqn|Wssin
bhreá	bhreá	breá-A	Aqp
,	,	,-F	Fi
a	a	a-U	Uv
chairde	chairde	cara-N	Ncmsv|Ncmpv
?	?	?-F	Fq
'	'	'-F	Fa
Chas	Chas	Cas-N	Npfsg
sé	sé	is-W	Wp-i-3
i	i	i-S	Sp
dtreo	dtreo	treo-N	Ncmsc
na	na	na-T	Tdfsg
n	n	n-X	Xl
‑	‑	‑-F	Fb
ainmhithe	ainmhithe	ainmhí-N	Ncmpc
eile	eile	eile-D	Dd
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
aontaigh	aontaigh	aontaigh-V	Vmis
siad	siad	siad-P	Pp3-pn
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
go	go	go-U	Ua
maith	maith	maith-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
Amestrus	Amestrus	Amestrus-N	Npmsc
agus	agus	agus-C	Cc
tharraing	tharraing	tarraing-V	Vmis
sí	sí	sí-P	Pp3fsn
anáil	anáil	anáil-N	Ncfsc
fhada	fhada	fada-A	Aqp
.	.	.-F	Fe
'	'	'-F	Fa
Eachtróidh	Eachtróidh	eachtraigh-V	Vmif
mise	mise	mé-P	Pp1-s-e
mo	mo	mo-D	Dp1-s
scéal	scéal	scéal-N	Ncmsc
daoibh	daoibh	do-P	Pr2-p
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
é	é	é-P	Pp3ms
an	an	an-T	Td-s
teas	teas	teas-N	Ncmsc
faoi	faoi	faoi-S	Sp
deara	deara	deara-N	Ns-s
é	é	é-P	Pp3ms
.	.	.-F	Fe
Is	Is	is-W	Wp-i
é	é	é-P	Pp3ms
an	an	an-T	Td-s
rud	rud	rud-N	Ncmsc
a	a	a-Q	Q-r
tharla	tharla	tarlaigh-V	Vmis
ná	ná	ná-C	Cs|Cc
–	–	–-X	Xx
’	’	’-F	Fa
Go	Go	go-U	Ua
tobann	tobann	tobann-A	Aqp
chuala	chuala	clois-V	Vmis
siad	siad	siad-P	Pp3-pn
glórtha	glórtha	glór-N	Ncmpc
daonna	daonna	daonna-A	Aqp
lasmuigh	lasmuigh	lasmuigh-A	Aqp
agus	agus	agus-C	Cc
eochair	eochair	eochair-N	Ncfsc
sa	sa	i-S	Spa-s
doras	doras	doras-N	Ncmsc
mór	mór	mór-A	Aq-msc
.	.	.-F	Fe
'	'	'-F	Fa
Tranglam	Tranglam	tranglam-N	Ncmsc
manglam	manglam	manglam-N	Ncmpg|Ncmsc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Míol	Míol	míol-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
Gorm	Gorm	gorm-A	Aq-msc
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
duine	duine	duine-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
mhúsaem	mhúsaem	músaem-N	Ncmsc
!	!	!-F	Fe
Brostaígí	Brostaígí	brostaigh-V	Vmm-2p
!	!	!-F	Fe
Ar ais	Ar ais	ar_ais-R	Rd
ar	ar	ar-S	Sp
na	na	na-T	Td-p
seastáin	seastáin	seastán-N	Ncmpc
agus	agus	agus-C	Cc
isteach	isteach	isteach-R	Rd
sna	sna	i-S	Spa-p
boscaí	boscaí	bosca-N	Ncmpc
gloine	gloine	gloine-N	Ncfsg|Ncfsc
!	!	!-F	Fe
'	'	'-F	Fa
Suas	Suas	suas-R	Rd
ar	ar	ar-S	Sp
na	na	na-T	Td-p
seastáin	seastáin	seastán-N	Ncmpc
agus	agus	agus-C	Cc
isteach	isteach	isteach-R	Rd
sna	sna	i-S	Spa-p
boscaí	boscaí	bosca-N	Ncmpc
gloine	gloine	gloine-N	Ncfsg|Ncfsc
leo	leo	le-P	Pr3-p
ar nós	ar nós	ar_nós-S	Spc
na	na	na-T	Tdfsg
gaoithe	gaoithe	gaoth-N	Ncfsg
.	.	.-F	Fe
Na	Na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpc
ar	ar	ar-S	Sp
cheart	cheart	ceart-N	Ncmsc
dóibh	dóibh	do-P	Pr3-p
bheith	bheith	bí-N	Nv
i	i	i-S	Sp
dtaisce	dtaisce	taisce-N	Ncfsc
,	,	,-F	Fi
chuaigh	chuaigh	téigh-V	Vmis
siad	siad	siad-P	Pp3-pn
i	i	i-S	Sp
dtaisce	dtaisce	taisce-N	Ncfsc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpc
ar	ar	ar-S	Sp
cheart	cheart	ceart-N	Ncmsc
dóibh	dóibh	do-P	Pr3-p
a	a	a-U	U
bheith	bheith	bí-N	Nv
á	á	do-S	Spo-p
dtaispeáint	dtaispeáint	taispeáin-N	Nv
féin	féin	féin-P	Px
,	,	,-F	Fi
chuir	chuir	cuir-V	Vmis
siad	siad	siad-P	Pp3-pn
iad	iad	iad-P	Pp3-p
féin	féin	féin-P	Px
ar	ar	ar-S	Sp
taispeáint	taispeáint	taispeáin-N	Nv
.	.	.-F	Fe
Chuala	Chuala	clois-V	Vmis
siad	siad	siad-P	Pp3-pn
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
mór	mór	mór-A	Aq-msc
ag	ag	ag-S	Sp
díoscán	díoscán	díoscán-N	Ncmsc
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
dheacair	dheacair	deacair-A	Aqp
é	é	é-P	Pp3ms
a	a	a-U	U
oscailt	oscailt	oscail-N	Nv
.	.	.-F	Fe
Faoi	Faoi	faoi-S	Sp
dheireadh	dheireadh	deireadh-N	Ncmsc
osclaíodh	osclaíodh	oscail-V	Vmih
in	in	i-S	Sp
aon	aon	aon-M	Mc
iarracht	iarracht	iarracht-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
amháin	amháin	amháin-A	Aqp
é	é	é-P	Pp3ms
.	.	.-F	Fe
Chuala	Chuala	clois-V	Vmis
na	na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpc
coiscéimeanna	coiscéimeanna	coiscéim-N	Ncfpg|Ncfpc
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
trasna	trasna	trasna-S	Sp
an	an	an-T	Td-s
urláir	urláir	urlár-N	Ncmsg
.	.	.-F	Fe
Lasadh	Lasadh	lasadh-V	Vmis0|Vmm-3s|Vmih|Ncmsc
na	na	na-T	Td-p
soilse	soilse	solas-N	Ncmpg|Ncmpc
.	.	.-F	Fe
Stiúrthóir	Stiúrthóir	stiúrthóir-N	Ncmsc
an	an	an-T	Td-s
mhúsaeim	mhúsaeim	músaem-N	Ncmsg
agus	agus	agus-C	Cc
beirt	beirt	beirt-N	Ncfsc
bhan	bhan	bean-N	Ncfpg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
'	'	'-F	Fa
Seo	Seo	seo-W	W
linn	linn	le-P	Pr1-p
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Stiúrthóir	Stiúrthóir	stiúrthóir-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
tí	tí	tí-N	Ncfsc
siúl	siúl	siúil-N	Ncmsc|Nv
ar	ar	ar-S	Sp
aghaidh	aghaidh	aghaidh-N	Ncfsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
rith	rith	rith-V	Vmis
rud	rud	rud-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Chrom	Chrom	crom-V	Vmis
sé	sé	sé-P	Pp3msn
síos	síos	síos-R	Rd
chun	chun	chun-S	Sp
féachaint	féachaint	féach-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
mór	mór	mór-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
tar éis	tar éis	tar_éis-S	Spc
an	an	an-T	Td-s
díoscán	díoscán	díoscán-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
.	.	.-F	Fe
Chnag	Chnag	cnag-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-U	Ua
héadrom	héadrom	éadrom-A	Aqp
air	air	ar-P	Pr3ms
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
braon	braon	braon-N	Ncmsc
ola	ola	ola-N	Ncfsg|Ncfsc
ag	ag	ag-S	Sp
teastáil	teastáil	teastaigh-N	Nv
uaidh	uaidh	ó-P	Pr3ms
seo	seo	seo-P	Pd
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Dhún	Dhún	dún-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
.	.	.-F	Fe
Baineadh	Baineadh	bain-V	Vmis0
creathadh	creathadh	creathadh-N	Ncmsc
as	as	as-S	Sp
fuinneoga	fuinneoga	fuinneog-N	Ncfpc
an	an	an-T	Td-s
mhúsaeim	mhúsaeim	músaem-N	Ncmsg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
bhan	bhan	bean-N	Ncfpg
timpeall	timpeall	timpeall-R	Rd
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
‑	‑	‑-F	Fb
bhrón	bhrón	brón-V	Vmis
orm	orm	ar-P	Pr1-s
faoi	faoi	faoi-S	Sp
seo	seo	seo-P	Pd
,	,	,-F	Fi
a	a	a-U	Uv
Jack	Jack	Jack-N	Npmsc
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
duine	duine	duine-N	Ncmsc
acu	acu	ag-P	Pr3-p
leis	leis	le-S	Sp
an	an	an-T	Td-s
Stiúrthóir	Stiúrthóir	stiúrthóir-N	Ncmsc
,	,	,-F	Fi
'	'	'-F	Fa
ach	ach	ach-C	Cs
rinne	rinne	déan-V	Vmis
mé	mé	mé-P	Pp1-s
dearmad	dearmad	dearmad-N	Ncmsc
glan	glan	glan-A	Aq-msc
féachaint	féachaint	féach-N	Ncfsc|Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
dealbh	dealbh	dealbh-N	Ncfsc
sin	sin	sin-P	Pd|W
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
anseo	anseo	anseo-R	Rl
tráthnóna	tráthnóna	tráthnóna-N	Ncmsc
.	.	.-F	Fe
Bhíomar	Bhíomar	bí-V	Vmis1p
déanach	déanach	déanach-N	Ncmsc|Rg
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
agus	agus	agus-C	Cc
,	,	,-F	Fi
ar	ar	ar-W	Wsdq|Ws-q|Wssi|Wpdi|Wpsi|Q-is|Ncmsc|Qq-s|Sp
deireadh	deireadh	deireadh-V	Vmih|Ncmsc
,	,	,-F	Fi
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ach	ach	ach-S	Sp|Cs
mé	mé	mé-P	Pp1-s
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
Betty	Betty	Betty-N	Npmsc
fágtha	fágtha	fág-A	Av
sa	sa	i-S	Spa-s
mhúsaem	mhúsaem	músaem-N	Ncmsc
–	–	–-X	Xx
’	’	’-F	Fa
'	'	'-F	Fa
Na	Na	na-T	Td-p
tuilte	tuilte	tuile-N	Ncfpc
ar	ar	ar-S	Sp
na	na	na-T	Td-p
bóithre	bóithre	bóthar-N	Ncmpc
,	,	,-F	Fi
b	b	b-X	Xl
’	’	’-F	Fa
in	in	sin-S	Sp|Pd
a	a	a-Q	Q-r
chuir	chuir	cuir-V	Vmis
moill	moill	moill-N	Ncfsc
orainn	orainn	ar-P	Pr1-p
,	,	,-F	Fi
nárbh	nárbh	is-W	Wsrin
ea	ea	ea-P	Pp3-s
,	,	,-F	Fi
a	a	a-U	Uv
Martha	Martha	Martha-N	Npfsc
?	?	?-F	Fq
'	'	'-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
eile	eile	eile-D	Dd
.	.	.-F	Fe
'	'	'-F	Fa
Agus	Agus	agus-C	Cc
ansin	ansin	ansin-R	Rt|Rl
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
slándála	slándála	slándáil-N	Ncfsg
ag	ag	ag-S	Sp
tabhairt	tabhairt	tabhair-N	Nv
orainn	orainn	ar-P	Pr1-p
imeacht	imeacht	imeacht-N	Ncmsc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
chéad	chéad	céad-M	Mo
bhean	bhean	bean-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
Ach	Ach	ach-C	Cs
tá	tá	bí-V	Vmip
an	an	an-T	Td-s
méid	méid	méid-N	Ncmsc
sin	sin	sin-D	Dd
cloiste	cloiste	clois-A	Av
againn	againn	ag-P	Pr1-p
faoin	faoin	faoi-S	Spa-s
dealbh	dealbh	dealbh-N	Ncfsc
gur	gur	is-W	Wsdi|Wpdi
mhaith	mhaith	maith-A	Aqp
linn	linn	le-P	Pr1-p
í	í	í-P	Pp3fs
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
anois	anois	anois-R	Rt
.	.	.-F	Fe
Is	Is	is-W	Wp-i
é	é	é-P	Pp3ms
seo	seo	seo-P	Pd
an	an	an-T	Td-s
seans	seans	seans-N	Ncmsc
deireanach	deireanach	deireanach-A	Aq-msc
againn	againn	ag-P	Pr1-p
.	.	.-F	Fe
'	'	'-F	Fa
Chuimil	Chuimil	cuimil-V	Vmis
an	an	an-T	Td-s
Stiúrthóir	Stiúrthóir	stiúrthóir-N	Ncmsc
a	a	a-U	U
shúile	shúile	súil-N	Nv--g--n
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
‑	‑	‑-F	Fb
tuirseach	tuirseach	tuirseach-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
saghas	saghas	saghas-N	Ncmsc
eagla	eagla	eagla-N	Ncfsg
air	air	ar-N	Ncmsg|Pr3ms|Ncmsg
roimh	roimh	roimh-S	Sp
a	a	a-D	Dp3
aintín	aintín	aintín-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
Cinnte	Cinnte	cinn-A	Av
,	,	,-F	Fi
a	a	a-U	Uv
Aintín	Aintín	aintín-N	Ncfsv
Martha	Martha	Martha-N	Npfsg|Npfsc
…	…	…-F	Fi
ach	ach	ach-C	Cs
…	…	…-F	Fi
ach	ach	ach-C	Cs
cén	cén	cé-W	W--q
dealbh	dealbh	dealbh-N	Ncfsc
go	go	go-U	Ua
díreach	díreach	díreach-A	Aqp
atá	atá	bí-V	Vmip---r
i	i	i-S	Sp
gceist	gceist	ceist-N	Ncfsc
agat	agat	ag-P	Pr2-s
?	?	?-F	Fq
'	'	'-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
'	'	'-F	Fa
Mo	Mo	mo-D	Dp1-s
náire	náire	náire-N	Ncfsc
thú	thú	tú-P	Pp2-s
,	,	,-F	Fi
a	a	a-U	Uv
Jack	Jack	Jack-N	Npmsc
.	.	.-F	Fe
Cén	Cén	cé-W	W--q
dealbh	dealbh	dealbh-N	Ncfsc
!	!	!-F	Fe
Níl	Níl	bí-V	Vmip---n
ach	ach	ach-R	Ri
dealbh	dealbh	dealbh-A	Aqp
amháin	amháin	amháin-A	Aqp
sa	sa	i-S	Spa-s
mhúsaem	mhúsaem	músaem-N	Ncmsc
seo	seo	seo-D	Dd
faoi	faoi	faoi-S	Sp
láthair	láthair	láthair-N	Ncfsc
a	a	a-Q	Q-i
bhfuil	bhfuil	bí-V	Vmip---d
clú	clú	clú-N	Ncmsc
agus	agus	agus-C	Cc
cáil	cáil	cál-N	Ncfsc|Ncmsg|Ncmpc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
An	An	an-T	Td-s
dealbh	dealbh	dealbh-N	Ncfsc
mharmair	mharmair	marmar-N	Ncmsg
sin	sin	sin-D	Dd
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sna	sna	i-S	Spa-p
nuachtáin	nuachtáin	nuachtán-N	Ncmpc
go	go	go-U	Ua
léir	léir	léir-A	Aqp
ar	ar	ar-S	Sp
maidin	maidin	maidin-N	Ncfsc
!	!	!-F	Fe
Amestrus	Amestrus	Amestrus-N	Npmsc
a	a	a-Q	Q-r
thugtar	thugtar	tabhair-V	Vmip0
uirthi	uirthi	ar-P	Pr3fs
,	,	,-F	Fi
…	…	…-F	Fi
nach	nach	is-W	Wprin
ea	ea	ea-P	Pp3-s
?	?	?-F	Fq
Fan	Fan	fan-V	Vmm-2s
go	go	go-S	Sp
bhfeicfi	bhfeicfi	bhfeicfi-N	Ncfsc
dh	dh	dh-Y	Y
mé	mé	mé-P	Pp1-s
cá	cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
sí	sí	sí-P	Pp3fsn
anois	anois	anois-R	Rt
…	…	…-F	Fi
’	’	’-F	Fa
'	'	'-F	Fa
A	A	a-U	Uv
Martha	Martha	Martha-N	Npfsc
!	!	!-F	Fe
Tar	Tar	tar-V	Vmm-2s
anseo	anseo	anseo-R	Rl
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
sí	sí	sí-P	Pp3fsn
agam	agam	ag-P	Pr1-s
!	!	!-F	Fe
Seo	Seo	seo-W	W
í	í	í-P	Pp3fs
!	!	!-F	Fe
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
Betty	Betty	Betty-N	Npmsc
ag	ag	ag-S	Sp
glaoch	glaoch	glaoigh-N	Nv
ó	ó	ó-S	Sp
lár	lár	lár-N	Ncmsc
an	an	an-T	Td-s
mhúsaeim	mhúsaeim	músaem-N	Ncmsg
,	,	,-F	Fi
áit	áit	áit-N	Ncfsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
ina	ina	i-S	Spp-p|Spp-s
seasamh	seasamh	seasamh-N	Ncmsc
in aice	in aice	in_aice-S	Spc
le	le	le-S	Sp
dealbh	dealbh	dealbh-N	Ncfsc
dhubh	dhubh	dubh-A	Aq-fsc
mharmair	mharmair	marmar-N	Ncmsg
,	,	,-F	Fi
a	a	a-U	Uv
lámha	lámha	lámh-N	Ncfpv
sínte	sínte	sín-A	Av
amach	amach	amach-R	Rd
faoi	faoi	faoi-P	Pr3ms
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
Amestrus	Amestrus	Amestrus-N	Npmsc
in	in	i-S	Sp
aithne	aithne	aithne-N	Ncfsc
dóibh	dóibh	do-P	Pr3-p
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Amestrus	Amestrus	Amestrus-N	Npmsc
ina	ina	i-S	Spp-p|Spp-s
seasamh	seasamh	seasamh-N	Ncmsc
os	os	os-N	Ncmpg|Sp|Ncmsc
a	a	a-D	Dp3
gcomhair	gcomhair	comhair-N	Ns-s
,	,	,-F	Fi
bogha	bogha	bogha-N	Ncmsc
agus	agus	agus-C	Cc
saighead	saighead	saighead-N	Ncfpg|Ncfsc|Ncfpg
thar	thar	thar-S	Sp
a	a	a-D	Dp3
gualainn	gualainn	gualainn-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
chuma	chuma	cuma-N	Ncfsc
uirthi	uirthi	ar-P	Pr3fs
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
díreach	díreach	díreach-A	Aqp
tar éis	tar éis	tar_éis-S	Spc
teacht	teacht	tar-N	Nv
ón	ón	ó-S	Spa-s
tseilg	tseilg	seilg-N	Ncfsc
agus	agus	agus-C	Cc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
lá	lá	lá-N	Ncmsc
fada	fada	fada-A	Aqp
curtha	curtha	cuir-A	Av
isteach	isteach	isteach-R	Rd
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
ainmhí	ainmhí	ainmhí-N	Ncmsc
beag	beag	beag-A	Aq-msc
ina	ina	i-S	Spp-s|Spp-p
luí	luí	luí-N	Ncmsc
in aice	in aice	in_aice-S	Spc
lena	lena	le-S	Spp-s
cos	cos	cos-N	Ncfsc
chlé	chlé	clé-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
gáire	gáire	gáire-N	Ncmsc
beag	beag	beag-A	Aq-msc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
béal	béal	béal-N	Ncmsc
,	,	,-F	Fi
ach	ach	ach-S	Sp
na	na	na-T	Td-p
súile	súile	súil-N	Ncfpc
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
féachaint	féachaint	féach-N	Nv
ar	ar	ar-S	Sp
rud	rud	rud-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
i	i	i-S	Sp
gcéin	gcéin	cian-N	Ncfsd
.	.	.-F	Fe
Bhain	Bhain	bain-V	Vmis
áilleacht	áilleacht	áilleacht-N	Ncfsc
an	an	an-T	Td-s
mharmair	mharmair	marmar-N	Ncmsg
an	an	an-T	Td-s
anáil	anáil	anáil-N	Ncfsc
de	de	de-S	Sp
na	na	na-T	Td-p
mná	mná	bean-N	Ncfpc
.	.	.-F	Fe
Leag	Leag	leag-V	Vmis
Martha	Martha	Martha-N	Npfsc
a	a	a-D	Dp3
méara	méara	méara-N	Ncfpc|Ncmsc
ar	ar	ar-S	Sp
ainm	ainm	ainm-N	Ncmsc
Amestrus	Amestrus	Amestrus-N	Npmsc
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
greanta	greanta	grean-A	Av
sa	sa	i-S	Spa-s
mharmar	mharmar	marmar-N	Ncmsc
ag	ag	ag-S	Sp
bun	bun	bun-N	Ncmsc
na	na	na-T	Tdfsg
deilbhe	deilbhe	deilbh-N	Ncfsg
:	:	:-F	Fi
sa	sa	i-S	Spa-s
mharmar	mharmar	marmar-N	Ncmsc
ag	ag	ag-S	Sp
bun	bun	bun-N	Ncmsc
na	na	na-T	Tdfsg
deilbhe	deilbhe	deilbh-N	Ncfsg
:	:	:-F	Fi
'	'	'-F	Fa
Ach	Ach	ach-C	Cs
níl	níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
eolas	eolas	eolas-N	Ncmsc
scríofa	scríofa	scríobh-A	Av
anseo	anseo	anseo-R	Rl
mar	mar	mar-S	Sp
gheall	gheall	geall-N	Ncmsc
ar	ar	ar-S	Sp
Amestrus	Amestrus	Amestrus-N	Npmsc
agus	agus	agus-C	Cc
mar	mar	mar-S	Sp
gheall	gheall	geall-N	Ncmsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
saol	saol	saol-N	Ncmsc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Betty	Betty	Betty-N	Npmsc
agus	agus	agus-C	Cc
díomá	díomá	díomá-N	Ncfsg|Ncfsc
ina	ina	i-S	Spp-s
glór	glór	glór-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
eolas	eolas	eolas-N	Ncmsc
agamsa	agamsa	ag-P	Pr1-s-e
fúithi	fúithi	faoi-P	Pr3fs
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Martha	Martha	Martha-N	Npfsc
,	,	,-F	Fi
'	'	'-F	Fa
mar	mar	mar-C	Cs
léigh	léigh	léigh-V	Vmis
mé	mé	mé-P	Pp1-s
mar	mar	mar-S	Sp
gheall	gheall	geall-N	Ncmsc
uirthi	uirthi	ar-P	Pr3fs
sa	sa	i-S	Spa-s
nuachtán	nuachtán	nuachtán-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Shiúil	Shiúil	siúil-V	Vmis
sí	sí	sí-P	Pp3fsn
i	i	i-S	Sp
dtreo	dtreo	treo-N	Ncmsc
na	na	na-T	Tdfsg
deilbhe	deilbhe	deilbh-N	Ncfsg
go dtí	go dtí	go_dtí-S	Spc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
díreach	díreach	díreach-A	Aqp
in aice	in aice	in_aice-S	Spc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Bhain	Bhain	bain-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-U	Ud|Dp3
spéaclaí	spéaclaí	spéaclach-N	Ncmpc|Aqc
di	di	de-P	Pr3fs
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
sí	sí	sí-P	Pp3fsn
aníos	aníos	aníos-R	Rd
ar	ar	ar-S	Sp
Amestrus	Amestrus	Amestrus-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Rinneadh	Rinneadh	déan-V	Vmis0
an	an	an-T	Td-s
dealbh	dealbh	dealbh-N	Ncfsc
seo	seo	seo-D	Dd
de	de	de-S	Sp
chailín	chailín	cailín-N	Ncmsc
Gréagach	Gréagach	Gréagach-A	Aq-msc
na	na	na-T	Td-p
mílte	mílte	míle-N	Ncmpg|Ncmpc
bliain	bliain	bliain-N	Ncfsc
ó	ó	ó-S	Sp
shin	shin	sin-P	Pd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
go	go	go-U	Ua
hálainn	hálainn	álainn-A	Aqp
tráth	tráth	tráth-N	Ncmsc
ach	ach	ach-C	Cs
tá	tá	bí-V	Vmip
a	a	a-D	Dp3
ré	ré	ré-N	Ncmsc|Ncfsc
mar	mar	mar-S	Sp
dhealbh	dhealbh	dealbh-N	Ncfsc
beagnach	beagnach	beagnach-R	Rg
thart	thart	thart-R	Rd
agus	agus	agus-C	Cc
níl	níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
luach	luach	luach-N	Ncmsc
ag	ag	ag-S	Sp
baint	baint	bain-N	Nv
léi	léi	le-P	Pr3fs
anois	anois	anois-R	Rt
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
i	i	i-S	Sp
gceist	gceist	ceist-N	Ncfsc
í	í	í-P	Pp3fs
a	a	a-U	U
chaitheamh	chaitheamh	caith-N	Nv
amach	amach	amach-R	Rd
.	.	.-F	Fe
Féachaigí	Féachaigí	féach-V	Vmm-2p
!	!	!-F	Fe
Nach	Nach	nach-Q	Qnr
bhfeiceann	bhfeiceann	feic-V	Vmip
sibh	sibh	sibh-P	Pp2-p
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
titim	titim	tit-N	Nv
as	as	as-P	Pr3ms
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
fiú	fiú	fiú-N	Ns-s|Ncmsc|Rg
dealbh	dealbh	dealbh-N	Ncfpg|Ncfsc|Aqp|Aq-msc
mar	mar	mar-C	Cs
sin	sin	sin-W	W
a	a	a-U	U
chur	chur	cuir-N	Nv
isteach	isteach	isteach-R	Rd
in	in	i-S	Sp
aon	aon	aon-D	Dq
mhúsaem	mhúsaem	músaem-N	Ncmsc
!	!	!-F	Fe
'	'	'-F	Fa
Chuir	Chuir	cuir-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
lámh	lámh	lámh-N	Ncfsc
ar	ar	ar-S	Sp
ghruaig	ghruaig	gruaig-N	Ncfsc
Amestrus	Amestrus	Amestrus-N	Npmsc
agus	agus	agus-C	Cc
thit	thit	tit-V	Vmis
píosa	píosa	píosa-N	Ncmsc
di	di	do-P	Pr3fs
go	go	go-S	Sp
talamh	talamh	talamh-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
oíche	oíche	oíche-N	Ncfsc
amháin	amháin	amháin-A	Aqp
a	a	a-Q	Q-r
bheidh	bheidh	bí-V	Vmif
sí	sí	sí-P	Pp3fsn
anseo	anseo	anseo-R	Rl
.	.	.-F	Fe
Cuimhnígí	Cuimhnígí	cuimhnigh-V	Vmm-2p
!	!	!-F	Fe
Í	Í	í-P	Pp3fs
ina	ina	i-S	Spp-s
dealbh	dealbh	dealbh-N	Ncfsc
cháiliúil	cháiliúil	cáiliúil-A	Aq-fsc
tamall	tamall	tamall-N	Ncmpg|Ncmsc
,	,	,-F	Fi
ach	ach	ach-C	Cs
níl	níl	bí-V	Vmip---n
inti	inti	i-P	Pr3fs
anois	anois	anois-R	Rt
ach	ach	ach-R	Ri
seandealbh	seandealbh	dealbh-A	Aqp
bhriste	bhriste	briste-A	Av|Aqp
nach	nach	nach-Q	Qnr
bhfuil	bhfuil	bí-V	Vmip---n
ag	ag	ag-S	Sp
teastáil	teastáil	teastaigh-N	Nv
ó	ó	ó-S	Sp
aon	aon	aon-D	Dq
mhúsaem	mhúsaem	músaem-N	Ncmsc
ar	ar	ar-S	Sp
domhan	domhan	domhan-N	Ncmsc
.	.	.-F	Fe
Nach	Nach	nach-Q	Qnq
bhfuil	bhfuil	bí-V	Vmip---d
an	an	an-T	Td-s
ceart	ceart	ceart-N	Ncmsc
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
a	a	a-U	Uv
Jack	Jack	Jack-N	Npmsc
?	?	?-F	Fq
'	'	'-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
Stiúrthóir	Stiúrthóir	stiúrthóir-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
an	an	an-T	Td-s
Stiúrthóir	Stiúrthóir	stiúrthóir-N	Ncmsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
uaireadóir	uaireadóir	uaireadóir-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
B	B	B-X	Xl
’	’	’-F	Fa
fhearr	fhearr	maith-A	Aqc
dúinn	dúinn	do-P	Pr1-p
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
imeacht	imeacht	imigh-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
'	'	'-F	Fa
Nach	Nach	is-W	Wpsin|Wpdin
mór	mór	mór-A	Aqp
an	an	an-T	Td-s
trua	trua	trua-N	Ncfsc
sin	sin	sin-W	W
!	!	!-F	Fe
Bhuel	Bhuel	bhuel-X	Xsc
,	,	,-F	Fi
bhuail	bhuail	buail-V	Vmis
muid	muid	muid-P	Pp1-p
léi	léi	le-P	Pr3fs
,	,	,-F	Fi
ar	ar	ar-S	Sp
aon	aon	aon-D	Dq
nós	nós	nós-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Betty	Betty	Betty-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Is	Is	is-W	Wp-i
ea	ea	ea-P	Pp3-s
,	,	,-F	Fi
sin	sin	sin-P	Pd|W
an	an	an-T	Td-s
rud	rud	rud-N	Ncmsc
is	is	is-U	U
tábhachtaí	tábhachtaí	tábhachtach-A	Aqc
,	,	,-F	Fi
go	go	go-Q	Q
bhfaca	bhfaca	feic-V	Vmis---d
muid	muid	muid-P	Pp1-p
í	í	í-P	Pp3fs
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Martha	Martha	Martha-N	Npfsc
.	.	.-F	Fe
'	'	'-F	Fa
Agus	Agus	agus-C	Cc
anois	anois	anois-R	Rt
beimid	beimid	bí-V	Vmif1p
ábalta	ábalta	ábalta-A	Aqc
a	a	a-U	U
rá	rá	abair-N	Nv
le	le	le-S	Sp
gach	gach	gach-D	Dq
duine	duine	duine-N	Ncmsc
ag	ag	ag-S	Sp
baile	baile	baile-N	Ncmsc
go	go	go-Q	Q
bhfaca	bhfaca	feic-V	Vmis---d
muid	muid	muid-P	Pp1-p
an	an	an-T	Td-s
dealbh	dealbh	dealbh-N	Ncfsc
is	is	is-U	U
cáiliúla	cáiliúla	cáiliúil-A	Aqc
in	in	sin-P	Pd
éirinn	éirinn	éir-V	Vmih1s
!	!	!-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Is	Is	is-W	Wp-i
dócha	dócha	dócha-A	Aqp|Aqc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Betty	Betty	Betty-N	Npmsc
agus	agus	agus-C	Cc
chas	chas	cas-V	Vmis
sí	sí	sí-P	Pp3fsn
timpeall	timpeall	timpeall-R	Rd|Ncmsc
go dtí	go dtí	go_dtí-S	Spc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
féachaint	féachaint	féach-N	Nv
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
súile	súile	súil-N	Ncfpc
Amestrus	Amestrus	Amestrus-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Slán	Slán	slán-N	Ncmsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Amestrus	Amestrus	Amestrus-N	Npmsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
'	'	'-F	Fa
Caithfimid	Caithfimid	caith-V	Vmif1p
imeacht	imeacht	imeacht-N	Ncmsc
anois	anois	anois-R	Rt
,	,	,-F	Fi
ach	ach	ach-C	Cs
ní	ní	is-W	Wp-in
dhéanfaidh	dhéanfaidh	déan-V	Vmif
mé	mé	mé-P	Pp1-s
dearmad	dearmad	dearmad-N	Ncmsc|Nv
ort	ort	ar-P	Pr2-s
.	.	.-F	Fe
'	'	'-F	Fa
Leag	Leag	leag-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
lámh	lámh	lámh-N	Ncfsc
ar	ar	ar-S	Sp
lámh	lámh	lámh-N	Ncfsc
Amestrus	Amestrus	Amestrus-N	Npmsc
faoi	faoi	faoi-P	Pr3ms
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
croitheadh	croitheadh	croith-N	Nv
láimhe	láimhe	lámh-N	Ncfsg
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
'	'	'-F	Fa
Nach	Nach	is-C	Cs|Wpdin|Wpsin
tú	tú	tú-P	Pp2-s
atá	atá	bí-V	Vmip---r
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
ó	ó	ó-S	Sp
bhaile	bhaile	baile-N	Ncmsc
anseo	anseo	anseo-R	Rl
!	!	!-F	Fe
Ba	Ba	is-W	Ws|Ws-i
bhreá	bhreá	breá-A	Aqp
liom	liom	le-P	Pr1-s
ceist	ceist	ceist-N	Ncfsc
a	a	a-U	U
chur	chur	cuir-N	Nv
ort	ort	ar-P	Pr2-s
fút	fút	faoi-P	Pr2-s
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
faoinar	faoinar	faoi-S	Spr
tharla	tharla	tarlaigh-V	Vmis
duit	duit	do-P	Pr2-s
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
gan	gan	gan-S	Sp
amhras	amhras	amhras-N	Ncmsc
,	,	,-F	Fi
ní	ní	is-W	Wp-in
féidir	féidir	féidir-N	Ns-s
leat	leat	le-P	Pr2-s
na	na	na-T	Td-p
freagraí	freagraí	freagra-N	Ncmpc
sin	sin	sin-D	Dd
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
dúinn	dúinn	do-P	Pr1-p
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
.	.	.-F	Fe
'	'	'-F	Fa
Ansin	Ansin	ansin-R	Rt|Rl
chas	chas	cas-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
sála	sála	sáil-N	Ncfpc
agus	agus	agus-C	Cc
shiúil	shiúil	siúil-V	Vmis
siad	siad	siad-P	Pp3-pn
triúr	triúr	triúr-N	Ncmsc
síos	síos	síos-R	Rd
na	na	na-T	Td-p
pasáistí	pasáistí	pasáiste-N	Ncmpc
fada	fada	fada-A	Aqp
.	.	.-F	Fe
Mhúch	Mhúch	múch-V	Vmis
siad	siad	siad-P	Pp3-pn
na	na	na-T	Td-p
soilse	soilse	solas-N	Ncmpc
,	,	,-F	Fi
dhún	dhún	dún-V	Vmis
siad	siad	siad-P	Pp3-pn
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
mór	mór	mór-A	Aq-msc
ina	ina	i-S	Spp-p
ndiaidh	ndiaidh	diaidh-N	Ns-s
de	de	de-S	Sp
phlab	phlab	plab-N	Ncmsc
,	,	,-F	Fi
casadh	casadh	cas-N	Ncmsc|Vmm-3s|Vmis0|Nv
an	an	an-T	Td-s
eochair	eochair	eochair-N	Ncfsc
sa	sa	i-S	Spa-s
doras	doras	doras-N	Ncmsc
agus	agus	agus-C	Cc
thit	thit	tit-V	Vmis
ciúnas	ciúnas	ciúnas-N	Ncmsc
arís	arís	arís-R	Rg
ar	ar	ar-S	Sp
an	an	an-T	Td-s
músaem	músaem	músaem-N	Ncmsc
.	.	.-F	Fe
Labhair	Labhair	labhair-V	Vmis
Amestrus	Amestrus	Amestrus-N	Npmsc
ansin	ansin	ansin-R	Rt|Rl
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agaibh	agaibh	ag-P	Pr2-p
anois	anois	anois-R	Rt
cad	cad	cad-P	Pq
atá	atá	bí-V	Vmip---r
romham	romham	roimh-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
go	go	go-U	Ua
ciúin	ciúin	ciúin-A	Aqp
,	,	,-F	Fi
'	'	'-F	Fa
agus	agus	agus-C	Cc
is	is	is-U	U
dócha	dócha	dócha-A	Aqc
gur	gur	is-W	Wsdi|Wpdi
mhaith	mhaith	maith-A	Aqp
libh	libh	le-P	Pr2-p
mo	mo	mo-D	Dp1-s
scéal	scéal	scéal-N	Ncmsc
a	a	a-U	U
chlos	chlos	clois-N	Nv
freisin	freisin	freisin-R	Rg
.	.	.-F	Fe
Rugadh	Rugadh	beir-V	Vmis0
agus	agus	agus-C	Cc
tógadh	tógadh	tóg-V	Vmis0
mé	mé	mé-P	Pp1-s
sa	sa	i-S	Spa-s
Chréit	Chréit	Créit-N	Npfsc
,	,	,-F	Fi
níos	níos	níos-U	Uc
mó	mó	mór-A	Aqc
ná	ná	ná-C	Cc
trí	trí	trí-M	Mc
mhíle	mhíle	míle-M	Mc
bliain	bliain	bliain-N	Ncfsc
ó	ó	ó-S	Sp
shin	shin	sin-P	Pd
.	.	.-F	Fe
Konstantinos	Konstantinos	Konstantinos-N	Npmsc
ab	ab	is-W	Wsri
ainm	ainm	ainm-N	Ncmsc
do	do	do-D	Dp2-s
m	m	m-X	Xl
’	’	’-F	Fa
athair	athair	athair-N	Ncmsc
agus	agus	agus-C	Cc
Leaina	Leaina	Leaina-N	Npmsc
ab	ab	is-W	Wsri
ainm	ainm	ainm-N	Ncmsc
do	do	do-D	Dp2-s|Sp
mo	mo	mo-D	Dp1-s
mháthair	mháthair	máthair-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
m	m	m-X	Xl
’	’	’-F	Fa
athair	athair	athair-N	Ncmsc
ag	ag	ag-S	Sp
obair	obair	obair-N	Nv-----n
don	don	do-S	Spa-s
Rí	Rí	rí-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
cónaí	cónaí	cónaí-N	Ncmsc
orm	orm	ar-P	Pr1-s
in	in	i-S	Sp
áras	áras	áras-N	Ncmsc
álainn	álainn	álainn-A	Aq-msc
ar	ar	ar-S	Sp
mhachaire	mhachaire	machaire-N	Ncmsc
mór	mór	mór-A	Aq-msc
le	le	le-S	Sp
mo	mo	mo-D	Dp1-s
mhuintir	mhuintir	muintir-N	Ncfsc
agus	agus	agus-C	Cc
le	le	le-S	Sp
mo	mo	mo-D	Dp1-s
pheataí	pheataí	peata-N	Ncmpc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
gach	gach	gach-D	Dq
rud	rud	rud-N	Ncmsc
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
'	'	'-F	Fa
Lig	Lig	lig-V	Vmis
sí	sí	sí-P	Pp3fsn
osna	osna	osna-N	Ncmsc
aisti	aisti	as-P	Pr3fs
,	,	,-F	Fi
a	a	a-Q	Q-r
shéid	shéid	séid-V	Vmis
mar	mar	mar-S	Sp
leoithne	leoithne	leoithne-N	Ncfsc
ghaoithe	ghaoithe	gaoth-N	Ncfsg
trí	trí	trí-M	Mc|Sp
sheomraí	sheomraí	seomra-N	Ncmpc
móra	móra	mór-A	Aq--pc
an	an	an-T	Td-s
mhúsaeim	mhúsaeim	músaem-N	Ncmsg
.	.	.-F	Fe
'	'	'-F	Fa
Lá	Lá	lá-N	Ncmsc
amháin	amháin	amháin-A	Aqp
–	–	–-X	Xx
mo	mo	mo-D	Dp1-s
lá	lá	lá-N	Ncmsc
breithe	breithe	beir-N	Ncfsg|Nv--g
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
–	–	–-X	Xx
bhí	bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
súgradh	súgradh	súgradh-N	Nv-----n
lasmuigh	lasmuigh	lasmuigh-A	Aqp
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
ghlaoigh	ghlaoigh	glaoigh-V	Vmis
mo	mo	mo-D	Dp1-s
mháthair	mháthair	máthair-N	Ncfsc
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
teach	teach	teach-N	Ncmsc
mé	mé	mé-P	Pp1-s
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
bronntanas	bronntanas	bronntanas-N	Ncmsc
aici	aici	ag-P	Pr3fs
dom	dom	do-P	Pr1-s
–	–	–-X	Xx
cóta	cóta	cóta-N	Ncmsc
álainn	álainn	álainn-A	Aq-msc
de	de	de-S	Sp
gach	gach	gach-D	Dq
dath	dath	dath-N	Ncmsc
agus	agus	agus-C	Cc
de	de	de-S	Sp
gach	gach	gach-D	Dq
mianach	mianach	mianach-N	Ncmsc
faoin	faoin	faoi-S	Spa-s
spéir	spéir	spéir-N	Ncfsc
.	.	.-F	Fe
Dúirt	Dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
liom	liom	le-P	Pr1-s
go	go	go-Q	Q
gcoimeádfadh	gcoimeádfadh	coimeád-V	Vmc
an	an	an-T	Td-s
cóta	cóta	cóta-N	Ncmsc
sin	sin	sin-D	Dd
slán	slán	slán-N	Ncmsc
mé	mé	mé-P	Pp1-s
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
mé	mé	mé-P	Pp1-s
orm	orm	ar-P	Pr1-s
é	é	é-P	Pp3ms
agus	agus	agus-C	Cc
thaitin	thaitin	taitin-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-U	Ua
mór	mór	mór-A	Aqp
liom	liom	le-P	Pr1-s
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
oíche	oíche	oíche-N	Ncfsc
sin	sin	sin-P	Pd|W|Dd
bhrúcht	bhrúcht	brúcht-V	Vmis|Ncmsc
bolcán	bolcán	bolcán-N	Ncmpg|Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
oileán	oileán	oileán-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
cuimhin	cuimhin	cuimhin-N	Ns-s
liom	liom	le-P	Pr1-s
mórán	mórán	mórán-N	Ncmsc
faoi	faoi	faoi-P	Pr3ms
ach	ach	ach-C	Cs
is	is	is-W	Wpri
cuimhin	cuimhin	cuimhin-N	Ns-s
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
teas	teas	teas-N	Ncmsc
marfach	marfach	marfach-A	Aq-msc
,	,	,-F	Fi
na	na	na-T	Td-p
tinte	tinte	tine-N	Ncfpc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
tuilte	tuilte	tuile-N	Ncfpc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
is	is	is-W	Wp-i
cuimhin	cuimhin	cuimhin-N	Ns-s
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
fuacht	fuacht	fuacht-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
.	.	.-F	Fe
Cailleadh	Cailleadh	caill-V	Vmm-3s
mo	mo	mo-D	Dp1-s
mháthair	mháthair	máthair-N	Ncfsc
agus	agus	agus-C	Cc
m	m	m-X	Xl
’	’	’-F	Fa
athair	athair	athair-N	Ncmsc
,	,	,-F	Fi
mo	mo	mo-D	Dp1-s
chairde	chairde	cairde-N	Ncmpc|Ncmsc
,	,	,-F	Fi
agus	agus	agus-C	Cc
mo	mo	mo-D	Dp1-s
pheataí	pheataí	peata-N	Ncmpc
go	go	go-U	Ua
léir	léir	léir-A	Aqp
.	.	.-F	Fe
Sa	Sa	i-S	Spa-s
deireadh	deireadh	deireadh-N	Ncmsc
fuair	fuair	faigh-V	Vmis
mise	mise	mé-P	Pp1-s-e
bás	bás	bás-N	Ncmsc
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
fuarthas	fuarthas	faigh-V	Vmis0
mo	mo	mo-D	Dp1-s
chorp	chorp	corp-N	Ncmsc
rinneadh	rinneadh	déan-V	Vmis0
dealbh	dealbh	dealbh-N	Ncfsc
díom	díom	de-P	Pr1-s
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
táim	táim	bí-V	Vmip1s
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
dhealbh	dhealbh	dealbh-N	Ncfsc
ó	ó	ó-S	Sp
shin	shin	sin-P	Pd
i	i	i-S	Sp
leith	leith	leith-N	Ncfsc
.	.	.-F	Fe
Sin	Sin	sin-W	W
é	é	é-P	Pp3ms
mo	mo	mo-D	Dp1-s
scéalsa	scéalsa	scéal-N	Ncmsc-e
.	.	.-F	Fe
Sin	Sin	sin-W	W
a	a	a-Q	Q-r
tharla	tharla	tarlaigh-V	Vmis
dom	dom	do-P	Pr1-s
.	.	.-F	Fe
'	'	'-F	Fa
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
a	a	a-D	Dp3
scéal	scéal	scéal-N	Ncmsc
críochnaithe	críochnaithe	críochnaigh-A	Av
aici	aici	ag-P	Pr3fs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
rud	rud	rud-N	Ncmsc
le	le	le-S	Sp
clos	clos	clois-N	Nv
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
macalla	macalla	macalla-N	Ncmsc
a	a	a-Q	Q-r
bhain	bhain	bain-V	Vmis
an	an	an-T	Td-s
marmar	marmar	marmar-N	Ncmsc
as	as	as-S	Sp
an	an	an-T	Td-s
urlár	urlár	urlár-N	Ncmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
thit	thit	tit-V	Vmis
píosa	píosa	píosa-N	Ncmsc
di	di	de-P	Pr3fs
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Leag	Leag	leag-V	Vmis
Amestrus	Amestrus	Amestrus-N	Npmsc
lámh	lámh	lámh-N	Ncfsc
fhuar	fhuar	fuar-A	Aq-fsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
héadan	héadan	éadan-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Táim	Táim	bí-V	Vmip1s
ag	ag	ag-S	Sp
éirí	éirí	éirigh-N	Nv
fuar	fuar	faigh-V	Vmis
arís	arís	arís-R	Rg
anois	anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
agus	agus	agus-C	Cc
rinne	rinne	déan-V	Vmis
sí	sí	sí-P	Pp3fsn
casacht	casacht	casacht-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
Déanfaimid	Déanfaimid	déan-V	Vmif1p
cóta	cóta	cóta-N	Ncmsc
nua	nua	nua-A	Aqp
duit	duit	do-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Amestrus	Amestrus	Amestrus-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Fia	Fia	fia-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
.	.	.-F	Fe
'	'	'-F	Fa
Chun	Chun	chun-S	Sp
tú	tú	tú-P	Pp2-s
a	a	a-Q	Q-r
choimeád	choimeád	coimeád-V	Vmis
slán	slán	slán-N	Ncmsc
feasta	feasta	feasta-R	Rg
!	!	!-F	Fe
'	'	'-F	Fa
Mhúscail	Mhúscail	múscail-V	Vmis
na	na	na-T	Td-p
focail	focail	focal-N	Ncmpc
sin	sin	sin-D	Dd
na	na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpc
eile	eile	eile-D	Dd
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Is	Is	is-W	Wp-i
ea	ea	ea-P	Pp3-s
,	,	,-F	Fi
déanfaimid	déanfaimid	déan-V	Vmif1p
cóta	cóta	cóta-N	Ncmsc
duit	duit	do-P	Pr2-s
ionas	ionas	ionas-N	Ns-s
nach	nach	nach-Q	Qnr
mbeidh	mbeidh	bí-V	Vmif
tú	tú	tú-P	Pp2-s
fuar	fuar	faigh-V	Vmis
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
arís	arís	arís-R	Rg
!	!	!-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Cóta	Cóta	cóta-N	Ncmsc
de	de	de-S	Sp
gach	gach	gach-D	Dq
dath	dath	dath-N	Ncmsc
faoin	faoin	faoi-S	Spa-s
spéir	spéir	spéir-N	Ncfsc
!	!	!-F	Fe
'	'	'-F	Fa
Chuaigh	Chuaigh	téigh-V	Vmis
siad	siad	siad-P	Pp3-pn
i mbun	i mbun	i_mbun-S	Spc
oibre	oibre	obair-N	Ncfsg|Nv--g--n
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
de	de	de-P	Pr3ms
chlúmh	chlúmh	clúmh-N	Ncmsc
buí	buí	buí-A	Aqp
agus	agus	agus-C	Cc
dubh	dubh	dubh-N	Ncmsc
an	an	an-T	Td-s
Tíogair	Tíogair	tíogar-N	Ncmsg
a	a	a-Q	Q-r
rinne	rinne	déan-V	Vmis
siad	siad	siad-P	Pp3-pn
an	an	an-T	Td-s
cóta	cóta	cóta-N	Ncmsc
.	.	.-F	Fe
Anuas	Anuas	anuas-R	Rd
air	air	ar-P	Pr3ms
sin	sin	sin-P	Pd
leag	leag	leag-V	Vmis
an	an	an-T	Td-s
Dineasár	Dineasár	dineasár-N	Ncmsc
a	a	a-U	Ud|Dp3
scálaí	scálaí	scálach-N	Ncmpc|Aqc
liatha	liatha	liath-A	Aq--pc|Aq--pv|Aq--pg|Aq--pc
.	.	.-F	Fe
Anuas	Anuas	anuas-R	Rd
ar	ar	ar-S	Sp
scálaí	scálaí	scála-N	Ncmpc
an	an	an-T	Td-s
Dineasáir	Dineasáir	dineasár-N	Ncmsg
chuir	chuir	cur-V	Vmis|Ncmsg
an	an	an-T	Td-s
Phearóid	Phearóid	Pearóid-N	Npfsg
slám	slám	slám-N	Ncmsc|Ncmsg
dá	dá	de-S	Spp-s
cuid	cuid	cuid-N	Ncfsc
cleití	cleití	cleite-N	Ncfsg|Ncmpg
agus	agus	agus-C	Cc
chaith	chaith	caith-V	Vmis
an	an	an-T	Td-s
Damhán	Damhán	damhán-N	Ncmsc
Alla	Alla	alla-N	Ncmsc|Ncmsg
leaba	leaba	leaba-N	Ncfsc
airgid	airgid	airgead-N	Ncmsg
aníos	aníos	aníos-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcóta	gcóta	cóta-N	Ncmsc
mar	mar	mar-S	Sp
sheál	sheál	seál-N	Ncmsc
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
an	an	an-T	Td-s
Madra	Madra	madra-N	Ncmsc
Rua	Rua	Rua-N	Npmsg|Npmsc
cuid	cuid	cuid-N	Ncfsc
dá	dá	do-S	Spp-s
fhionnadh	fhionnadh	fionnadh-N	Ncmsc
chun go	chun go	chun_go-C	Cs
mbeadh	mbeadh	bí-V	Vmc
bóna	bóna	bóna-N	Ncmsc
deas	deas	deas-R	Ri
cluthar	cluthar	cluthar-A	Aqp
ag	ag	ag-S	Sp
an	an	an-T	Td-s
gcóta	gcóta	cóta-N	Ncmsc
.	.	.-F	Fe
Sa	Sa	i-S	Spa-s
deireadh	deireadh	deireadh-N	Ncmsc
cheangail	cheangail	ceangal-N	Ncmpc
na	na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpg
t	t	t-X	Xl
‑	‑	‑-F	Fb
ábhar	ábhar	ábhar-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
le	le	le-S	Sp
hola	hola	ola-N	Ncfsc
an	an	an-T	Td-s
Mhíl	Mhíl	míol-N	Ncmsg
Mhóir	Mhóir	mór-A	Aq-msg
Ghoirm	Ghoirm	Goirm-N	Npfsg
,	,	,-F	Fi
rud	rud	rud-N	Ncmsc
a	a	a-Q	Q-r
chuir	chuir	cuir-V	Vmis
snas	snas	snas-N	Ncmsc
álainn	álainn	álainn-A	Aq-msc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcóta	gcóta	cóta-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
giotaí	giotaí	giota-N	Ncmpc
de	de	de-S	Sp
bheanna	bheanna	beann-N	Ncfpc
dubha	dubha	dubh-A	Aq--pc
an	an	an-T	Td-s
Fhia	Fhia	fia-N	Ncmsg
Mhóir	Mhóir	mór-A	Aq-msg
mar	mar	mar-S	Sp
chnaipí	chnaipí	cnaipe-N	Ncmpc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuir	chuir	cuir-V	Vmis
Amestrus	Amestrus	Amestrus-N	Npmsc
an	an	an-T	Td-s
cóta	cóta	cóta-N	Ncmsg
nua	nua	nua-A	Aqp
uirthi	uirthi	ar-P	Pr3fs
tháinig	tháinig	tar-V	Vmis
áthas	áthas	áthas-N	Ncmsc
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
croí	croí	croí-N	Ncmsc
marmair	marmair	marmar-N	Ncmsg|Ncmpc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
sí	sí	sí-P	Pp3fsn
timpeall	timpeall	timpeall-R	Rd
ar	ar	is-W	Wpsi|Sp|Wssi|Wpdi
a	a	a-D	Dp3
cairde	cairde	cairde-N	Ncmpc|Ncmsc
nua	nua	nua-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
cuma	cuma	cuma-N	Ncfsc
thraochta	thraochta	traoch-A	Av
orthu	orthu	ar-P	Pr3-p
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
cuma	cuma	cuma-N	Ncfsc
lom	lom	lom-A	Aq-fsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
Dineasár	Dineasár	dineasár-N	Ncmsc
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
Tíogar	Tíogar	tíogar-N	Ncmsc
ag	ag	ag-S	Sp
féachaint	féachaint	féach-N	Nv
tanaí	tanaí	tanaí-N	Ncfsg
.	.	.-F	Fe
'	'	'-F	Fa
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
maith	maith	maith-N	Ncfsc
agaibh	agaibh	ag-P	Pr2-p
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
'	'	'-F	Fa
Ach	Ach	ach-C	Cs
anois	anois	anois-R	Rt
,	,	,-F	Fi
cad	cad	cad-P	Pq
is	is	is-W	Wpri
féidir	féidir	féidir-N	Ns-s
liomsa	liomsa	le-P	Pr1-s-e
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
daoibhse	daoibhse	do-P	Pr2-p-e
?	?	?-F	Fq
'	'	'-F	Fa
'	'	'-F	Fa
Tar	Tar	thar-S	Sp
ar ais	ar ais	ar_ais-R	Rd
chugainn	chugainn	chuig-P	Pr1-p
,	,	,-F	Fi
a	a	a-U	Uv
Amestrus	Amestrus	Amestrus-N	Npmsc
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
Míol	Míol	míol-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
Gorm	Gorm	gorm-A	Aq-msc
de	de	de-S	Sp
ghuth	ghuth	guth-N	Ncmsc
mall	mall	mall-A	Aq-msc
réidh	réidh	réidh-A	Aq-msc
.	.	.-F	Fe
'	'	'-F	Fa
Sin	Sin	sin-P	Pd
atá	atá	bí-V	Vmip---r
uainn	uainn	ó-P	Pr1-p
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Is	Is	is-W	Wp-i
ea	ea	ea-P	Pp3-s
,	,	,-F	Fi
tabhair	tabhair	tabhair-V	Vmm-2s
cuairt	cuairt	cuairt-N	Ncfsc
orainn	orainn	ar-P	Pr1-p
arís	arís	arís-R	Rg
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
Phearóid	Phearóid	Pearóid-N	Npfsg
.	.	.-F	Fe
'	'	'-F	Fa
Ná	Ná	ná-Q	Qnm
déan	déan	déan-V	Vmm-2s-n
dearmad	dearmad	dearmad-N	Ncmsc
orainn	orainn	ar-P	Pr1-p
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
!	!	!-F	Fe
'	'	'-F	Fa
Thosaigh	Thosaigh	tosaigh-V	Vmis
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
bualadh	bualadh	buail-N	Nv
bos	bos	bos-N	Ncfpg
agus	agus	agus-C	Cc
líon	líon	líon-V	Vmis|Vmm-2s|Ncmsc
súile	súile	súil-N	Ncfsg|Ncfpc|Ncfsg
Amestrus	Amestrus	Amestrus-N	Npmsc
le	le	le-S	Sp
deora	deora	deora-N	Ncfpc|Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
Codladh	Codladh	codladh-N	Ncfsc
sámh	sámh	sámh-A	Aqp
,	,	,-F	Fi
a	a	a-U	Uv
chairde	chairde	cairde-N	Ncmpv|Ncmsv
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Amestrus	Amestrus	Amestrus-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Oíche	Oíche	oíche-N	Ncfsc
mhaith	mhaith	maith-A	Aq-fsc
,	,	,-F	Fi
a	a	a-U	Uv
Amestrus	Amestrus	Amestrus-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
Nathair	Nathair	nathair-N	Ncfsc
Nimhe	Nimhe	nimh-N	Ncfsg
agus	agus	agus-C	Cc
ba	ba	is-W	Wsri
ar	ar	ar-S	Sp
éigean	éigean	éigean-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Amestrus	Amestrus	Amestrus-N	Npmsc
ábalta	ábalta	ábalta-A	Aqp
a	a	a-D	Dp3
guth	guth	guth-N	Ncmsc
a	a	a-U	U
chlos	chlos	clois-N	Nv
.	.	.-F	Fe
'	'	'-F	Fa
Slán	Slán	slán-N	Ncmsc
codlata	codlata	codail-A	Av
na	na	na-T	Td-p
Ríthe	Ríthe	rí-N	Ncmpg|Ncmpc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
chailín	chailín	cailín-N	Ncmsv
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Madra	Madra	madra-N	Ncmsc
Rua	Rua	Rua-N	Npmsg|Npmsc
go	go	go-U	Ua
ciúin	ciúin	ciúin-A	Aqp
.	.	.-F	Fe
'	'	'-F	Fa
Go	Go	go-C	Cs
n	n	n-X	Xl
‑	‑	‑-F	Fb
éirí	éirí	éirí-N	Nv|Ncmsc
do	do	do-S	Sp
bhealach	bhealach	bealach-N	Ncmsc
leat	leat	le-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
dhealbh	dhealbh	dealbh-N	Ncfsv
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Fia	Fia	fia-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
os	os	os-N	Ncmpg|Sp|Ncmsc
íseal	íseal	íseal-N	Ncmpg|Aq-msc|Ncmsc|Aqp
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
,	,	,-F	Fi
go	go	go-U	Ua
tobann	tobann	tobann-A	Aqp
,	,	,-F	Fi
thit	thit	tit-V	Vmis
codladh	codladh	codladh-N	Ncfsc
orthu	orthu	ar-P	Pr3-p
go	go	go-U	Ua
léir	léir	léir-A	Aqp
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
t	t	t-X	Xl
‑	‑	‑-F	Fb
ainmhí	ainmhí	ainmhí-N	Ncmsc
deireanach	deireanach	deireanach-A	Aq-msc
tite	tite	tit-A	Av
a	a	a-U	U
chodladh	chodladh	codail-N	Nv
d	d	d-X	Xl
’	’	’-F	Fa
ullmhaigh	ullmhaigh	ullmhaigh-V	Vmm-2s
Amestrus	Amestrus	Amestrus-N	Npmsc
í	í	í-P	Pp3fs
féin	féin	féin-P	Px
don	don	do-S	Spa-s
imeacht	imeacht	imeacht-N	Ncmsc
i	i	i-S	Sp
leathsholas	leathsholas	solas-N	Ncmsc
an	an	an-T	Td-s
mhúsaeim	mhúsaeim	músaem-N	Ncmsg
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
an	an	an-T	Td-s
Stiúrthóir	Stiúrthóir	stiúrthóir-N	Ncmsc
isteach	isteach	isteach-R	Rd
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
dár	dár	do-S	Spp-p
gcionn	gcionn	ceann-N	Ncfsd
chun	chun	chun-S	Sp
an	an	an-T	Td-s
dealbh	dealbh	dealbh-N	Ncfsc
bhriste	bhriste	briste-A	Av|Aqp
a	a	a-U	U
bhailiú	bhailiú	bailigh-N	Nv
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sí	sí	sí-P	Pp3fsn
le	le	le-S	Sp
feiceáil	feiceáil	feic-N	Nv
i lár	i lár	i_lár-S	Spc
an	an	an-T	Td-s
mhúsaeim	mhúsaeim	músaem-N	Ncmsg
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
solas	solas	solas-N	Ncmsc
na	na	na-T	Tdfsg
gréine	gréine	grian-N	Ncfsg
ag	ag	ag-S	Sp
titim	titim	tit-N	Nv
anuas	anuas	anuas-R	Rd
tríd	tríd	trí-S	Sp
an	an	an-T	Td-s
díon	díon	díon-N	Ncmsc
ar	ar	ar-S	Sp
chleití	chleití	cleite-N	Ncmpc
éin	éin	éan-N	Ncmsg
,	,	,-F	Fi
ar	ar	ar-S	Sp
phíosaí	phíosaí	píosa-N	Ncmpc
de	de	de-S	Sp
ghruaig	ghruaig	gruaig-N	Ncfsc
dhubh	dhubh	dubh-A	Aq-fsc
agus	agus	agus-C	Cc
de	de	de-S	Sp
lámha	lámha	lámh-N	Ncfpc
marmair	marmair	marmar-N	Ncmsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ina	ina	i-S	Spp-s|Spp-p
luí	luí	luí-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
talamh	talamh	talamh-N	Ncfsc
.	.	.-F	Fe
Lig	Lig	lig-V	Vmis|Vmm-2s
an	an	an-T	Td-s
Stiúrthóir	Stiúrthóir	stiúrthóir-N	Ncmsc
scread	scread	scread-V	Vmis
as	as	as-P	Pr3ms
a	a	a-Q	Q-r
dhúiseodh	dhúiseodh	dúisigh-V	Vmc
Farónna	Farónna	faró-N	Ncmpc
na	na	na-T	Tdfsg
hÉigipte	hÉigipte	Éigipt-N	Npf-g
.	.	.-F	Fe
'	'	'-F	Fa
Cad	Cad	cad-P	Pq
a	a	a-Q	Q-r
rinne	rinne	déan-V	Vmis
sibh	sibh	sibh-P	Pp2-p
léi	léi	le-P	Pr3fs
?	?	?-F	Fq
'	'	'-F	Fa
a	a	a-Q	Q-r
bhéic	bhéic	béic-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
'	'	'-F	Fa
Ó	Ó	Ó-I	I
,	,	,-F	Fi
ba	ba	is-W	Ws|Ws-i
cheart	cheart	ceart-A	Aqp
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
nach	nach	nach-Q	Qnr
mbeadh	mbeadh	bí-V	Vmc
sí	sí	sí-P	Pp3fsn
sábháilte	sábháilte	sábháil-A	Aqp|Av
anseo	anseo	anseo-R	Rl
!	!	!-F	Fe
Ní	Ní	is-W	Wp-in
nach	nach	is-C	Cs|Wpdin|Wpsin
ionadh	ionadh	ionadh-N	Ncmsc
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
cuid	cuid	cuid-N	Ncfsc
agaibh	agaibh	ag-P	Pr2-p
i	i	i-S	Sp
mbaol	mbaol	baol-N	Ncmsc
agus	agus	agus-C	Cc
gur	gur	gur-Q	Q--s
tháinig	tháinig	tar-V	Vmis
deireadh	deireadh	deireadh-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
gcuid	gcuid	cuid-N	Ncfsc
eile	eile	eile-D	Dd
agaibh	agaibh	ag-P	Pr2-p
!	!	!-F	Fe
'	'	'-F	Fa
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
gíog	gíog	gíog-N	Ncfsc
ná	ná	nach-Q	Qnr
míog	míog	míog-V	Vmm-2s-n
as	as	as-S	Sp
na	na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpc
.	.	.-F	Fe
Pé	Pé	pé-P	Pi
áit	áit	áit-N	Ncfsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
acu	acu	ag-P	Pr3-p
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
cóta	cóta	cóta-N	Ncmsc
nua	nua	nua-A	Aqp
Amestrus	Amestrus	Amestrus-N	Npmsc
tar éis	tar éis	tar_éis-S	Spc
í	í	í-P	Pp3fs
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
slán	slán	slán-N	Ncmpg|Ncmsc|Ncmpg
.	.	.-F	Fe
Diaidh	Diaidh	diaidh-N	Ns-s
ar	ar	ar-S	Sp
ndiaidh	ndiaidh	diaidh-N	Ns-s
,	,	,-F	Fi
áfach	áfach	áfach-R	Rg
,	,	,-F	Fi
rinne	rinne	déan-V	Vmis
an	an	an-T	Td-s
Stiúrthóir	Stiúrthóir	stiúrthóir-N	Ncmsc
dearmad	dearmad	dearmad-N	Ncmsc|Nv|Ncmpg
ar	ar	ar-S	Sp
Amestrus	Amestrus	Amestrus-N	Npmsc
agus	agus	agus-C	Cc
ar	ar	ar-S	Sp
ar	ar	ar-Q	Q-p
tharla	tharla	tarlaigh-V	Vmis
di	di	do-P	Pr3fs
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
dhearna	dhearna	déan-V	Vmis---n
na	na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpc
dearmad	dearmad	dearmad-N	Ncmsc|Nv|Ncmpg
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
mhinic	mhinic	minic-A	Aqp
a	a	a-Q	Q-r
labhair	labhair	labhair-V	Vmis
siad	siad	siad-P	Pp3-pn
fúithi	fúithi	faoi-P	Pr3fs
le linn	le linn	le_linn-S	Spc
oícheanta	oícheanta	oíche-N	Ncfpg
scéalaíochta	scéalaíochta	scéalaíocht-N	Ncfsg
an	an	an-T	Td-s
mhúsaeim	mhúsaeim	músaem-N	Ncmsg
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
inis	inis	inis-V	Vmis
siad	siad	siad-P	Pp3-pn
scéal	scéal	scéal-N	Ncmsc
agus	agus	agus-C	Cc
stair	stair	stair-N	Ncfsc
Amestrus	Amestrus	Amestrus-N	Npmsc
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
lena	lena	le-S	Spp-p
gcuid	gcuid	cuid-N	Ncfsc
scéalta	scéalta	scéal-N	Ncmpg
agus	agus	agus-C	Cc
lena	lena	le-S	Spp-p
gcuid	gcuid	cuid-N	Ncfsc
staire	staire	stair-N	Ncfsg
féin	féin	féin-P	Px
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
má	má	má-C	Cs
bhuaileann	bhuaileann	buail-V	Vmip
tusa	tusa	tú-P	Pp2-s-e
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
Músaem	Músaem	músaem-N	Ncmsc
Stair	Stair	stair-N	Ncfsc
an	an	an-T	Td-s
Dúlra	Dúlra	dúlra-N	Ncmsg
lá	lá	lá-N	Ncmsc
,	,	,-F	Fi
feicfidh	feicfidh	feic-V	Vmif
tú	tú	tú-P	Pp2-s
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
na	na	na-T	Td-p
hainmhithe	hainmhithe	ainmhí-N	Ncmpc
fós	fós	fós-R	Rg
ina	ina	i-S	Spp-p
gcodladh	gcodladh	codladh-N	Ncfsc
–	–	–-X	Xx
go dtí	go dtí	go_dtí-S	Spc
go	go	go-C	Cs
n	n	n-X	Xl
‑	‑	‑-F	Fb
imíonn	imíonn	imigh-V	Vmip
tú	tú	tú-P	Pp2-s
agus	agus	agus-C	Cc
go	go	go-Q	Q
ndúnann	ndúnann	dún-V	Vmip
tú	tú	tú-P	Pp2-s
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
mór	mór	mór-A	Aq-msc
i	i	i-S	Sp
do	do	do-D	Dp2-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
.	.	.-F	Fe
Is	Is	is-W	Wp-i
ann	ann	i-P	Pr3ms
a	a	a-Q	Q-r
fhanfaidh	fhanfaidh	fan-V	Vmif
siad	siad	siad-P	Pp3-pn
go dtí	go dtí	go_dtí-S	Spc
go	go	go-Q	Q
bhfillfidh	bhfillfidh	fill-V	Vmif
a	a	a-D	Dp3
gcara	gcara	cara-N	Ncmsc
Amestrus	Amestrus	Amestrus-N	Npmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
músaem	músaem	músaem-N	Ncmsc
.	.	.-F	Fe
Tiocfaidh	Tiocfaidh	tar-V	Vmif
sí	sí	sí-P	Pp3fsn
,	,	,-F	Fi
cinnte	cinnte	cinnte-A	Av|Aqp
,	,	,-F	Fi
ach	ach	ach-C	Cs
níl	níl	bí-V	Vmip---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
cathain	cathain	cathain-R	Rq
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
tá	tá	bí-V	Vmip
fuílleach	fuílleach	fuílleach-N	Ncmsc
ama	ama	ama-N	Ncmsg|Ncmsc
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
bhíonn	bhíonn	bí-V	Vmig---n
aon	aon	aon-D	Dq
deifir	deifir	deifir-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
stair	stair	stair-N	Ncfsc
.	.	.-F	Fe
