 Nuair	Nuair	-X	Xx
a	a	a-Q	Q-r
Lonraigh	Lonraigh	lonraigh-V	Vmis
an	an	an-T	Td-s
Lampa	Lampa	lampa-N	Ncmsc
D	D	D-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmm-2s
mé	mé	mé-P	Pp1-s
mo	mo	mo-D	Dp1-s
shúile	shúile	súil-N	Ncfpc
go	go	go-U	Ua
fadálach	fadálach	fadálach-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
mo	mo	mo-D	Dp1-s
chroí	chroí	croí-N	Ncmsc
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
bhéal	bhéal	béal-N	Ncmsc
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
thuig	thuig	tuig-V	Vmip---n|Vmis---n
mé	mé	mé-P	Pp1-s
go	go	go-U	Ua
díreach	díreach	díreach-A	Aqp
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
i ndiaidh	i ndiaidh	i_ndiaidh-S	Spc
tarlú	tarlú	tarlaigh-N	Nv
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
dhearna	dhearna	déan-V	Vmis---n
mé	mé	mé-P	Pp1-s
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
lampa	lampa	lampa-N	Ncmsc
aisteach	aisteach	aisteach-A	Aq-msc
sin	sin	sin-P	Pd|W|Dd
a	a	a-U	U
chuimilt	chuimilt	cuimil-N	Nv
agus	agus	agus-C	Cc
an	an	an-T	Td-s
chéad	chéad	céad-M	Mo
rud	rud	rud-N	Ncmsc
eile	eile	eile-D	Dd
–	–	–-X	Xx
bhúis	bhúis	búis-N	Ncmpc|Ncfsc
!	!	!-F	Fe
–	–	–-X	Xx
bhí	bhí	bí-V	Vmis
mo	mo	mo-D	Dp1-s
chorp	chorp	corp-N	Ncmsc
ag	ag	ag-S	Sp
eitilt	eitilt	eitil-N	Nv
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
réaltaí	réaltaí	réalta-N	Ncfpc
ag	ag	ag-S	Sp
spréacharnach	spréacharnach	spréacharnach-N	Ncfsc
thart	thart	thart-R	Rd
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
Sa	Sa	i-S	Spa-s
deireadh	deireadh	deireadh-N	Ncmsc
bhí	bhí	bí-V	Vmis
faill	faill	faill-N	Ncfsc
agam	agam	ag-P	Pr1-s
amharc	amharc	amharc-N	Ncmsc
thart	thart	thart-R	Rd
orm	orm	ar-P	Pr1-s
féin	féin	féin-P	Px
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
cá	cá	cá-R	Rq
raibh	raibh	bí-V	Vmis---d
mé	mé	mé-P	Pp1-s
?	?	?-F	Fq
A	A	an-T	Td-s
leithéid	leithéid	leithéid-N	Ncfsc
d	d	d-X	Xl
’	’	’-F	Fa
áit	áit	áit-N	Ncfsc
ní	ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
mé	mé	mé-P	Pp1-s
riamh	riamh	riamh-R	Rg
agus	agus	agus-C	Cc
,	,	,-F	Fi
leis	leis	le-S	Sp
an	an	an-T	Td-s
fhírinne	fhírinne	fírinne-N	Ncfsc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
cineál	cineál	cineál-R	Ri
buartha	buartha	buartha-A	Aqp
.	.	.-F	Fe
Áit	Áit	áit-N	Ncfsc
ghruama	ghruama	gruama-A	Aqp
dhorcha	dhorcha	dorcha-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
sheasamh	sheasamh	seas-N	Ncmsc|Nv
ag	ag	ag-S	Sp
taobh	taobh	taobh-N	Ncmsc
doras	doras	doras-N	Ncmsc
millteanach	millteanach	millteanach-A	Aq-msc
mór	mór	mór-A	Aq-msc
.	.	.-F	Fe
'	'	'-F	Fa
Cé	Cé	cé-P	Pq
atá	atá	bí-V	Vmip---r
ag	ag	ag-S	Sp
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
?	?	?-F	Fq
'	'	'-F	Fa
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
mé	mé	mé-P	Pp1-s
go	go	go-U	Ua
tobann	tobann	tobann-A	Aqp
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmm-2s
mé	mé	mé-P	Pp1-s
mo	mo	mo-D	Dp1-s
bhéal	bhéal	béal-N	Ncmsc
le	le	le-S	Sp
freagra	freagra	freagra-N	Ncmsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
cheist	cheist	ceist-N	Ncfsc
ach	ach	ach-S	Sp
focal	focal	focal-N	Ncmsc
ná	ná	ná-C	Cs|Cc
focal	focal	focal-N	Ncmpg|Ncmsc
ní	ní	ní-Q	Qn
thiocfadh	thiocfadh	tar-V	Vmc----n
amach	amach	amach-R	Rd
as	as	as-P	Pr3ms
.	.	.-F	Fe
'	'	'-F	Fa
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
tusa	tusa	tú-P	Pp2-s-e
anseo	anseo	anseo-R	Rl
le	le	le-S	Sp
cuidiú	cuidiú	cuidigh-N	Nv
liom	liom	le-P	Pr1-s
?	?	?-F	Fq
Ar	Ar	ar-Q	Qq-s
thug	thug	tabhair-V	Vmis
tú	tú	tú-P	Pp2-s
leat	leat	le-P	Pr2-s
é	é	é-P	Pp3ms
?	?	?-F	Fq
'	'	'-F	Fa
Faoin	Faoin	faoi-S	Spa-s
am	am	am-N	Ncmsc
seo	seo	seo-D	Dd
bhí	bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
go	go	go-U	Ua
hiomlán	hiomlán	iomlán-A	Aqp
fríd	fríd	trí-N	Ncfsc|Sp
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
mo	mo	mo-D	Dp1-s
sháith	sháith	sáith-N	Ncfsc
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
duine	duine	duine-N	Ncmsc
millteanach	millteanach	millteanach-A	Aq-msc
cróga	cróga	cróga-A	Aqp
mé	mé	mé-P	Pp1-s
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
fanacht	fanacht	fan-N	Ncmsc|Nv
thart	thart	thart-R	Rd
le	le	le-S	Sp
fáil	fáil	faigh-N	Nv
amach	amach	amach-R	Rd
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
t	t	t-X	Xl
‑	‑	‑-F	Fb
uafás	uafás	uafás-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ar	ar	ar-S	Sp
an	an	an-T	Td-s
taobh	taobh	taobh-N	Ncmsc
eile	eile	eile-D	Dd
den	den	de-S	Spa-s
doras	doras	doras-N	Ncmsc
seo	seo	seo-D	Dd
.	.	.-F	Fe
Shocraigh	Shocraigh	socraigh-V	Vmis
mé	mé	mé-P	Pp1-s
ar	ar	ar-S	Sp
imeacht	imeacht	imigh-N	Nv
as	as	as-S	Sp
an	an	an-T	Td-s
áit	áit	áit-N	Ncfsc
seo	seo	seo-D	Dd
chomh	chomh	chomh-R	Ri
tiubh	tiubh	tiubh-A	Aqp
géar	géar	géar-A	Aqp
agus	agus	agus-C	Cc
a	a	a-Q	Q-r
thiocfadh	thiocfadh	tar-V	Vmc
liom	liom	le-P	Pr1-s
.	.	.-F	Fe
Líon	Líon	líon-V	Vmis
mé	mé	mé-P	Pp1-s
mo	mo	mo-D	Dp1-s
chuid	chuid	cuid-N	Ncfsc
scamhóg	scamhóg	scamhóg-N	Ncfpg
le	le	le-S	Sp
haer	haer	aer-N	Ncmsc
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
rith	rith	rith-N	Nv
.	.	.-F	Fe
Bhuel	Bhuel	bhuel-X	Xsc
,	,	,-F	Fi
sin	sin	sin-P	Pd|W
an	an	an-T	Td-s
rud	rud	rud-N	Ncmsc
a	a	a-Q	Q-r
shíl	shíl	síl-V	Vmis
mé	mé	mé-P	Pp1-s
ach	ach	ach-C	Cs
i ndiaidh	i ndiaidh	i_ndiaidh-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
thuig	thuig	tuig-V	Vmis
mé	mé	mé-P	Pp1-s
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
mé	mé	mé-P	Pp1-s
cosúil	cosúil	cosúil-A	Aqp
le	le	le-S	Sp
duine	duine	duine-N	Ncmsc
ar	ar	ar-S	Sp
inneall	inneall	inneall-N	Ncmsc
reathaíochta	reathaíochta	reathaíocht-N	Ncfsg
–	–	–-X	Xx
bhí	bhí	bí-V	Vmis
mo	mo	mo-D	Dp1-s
chosa	chosa	cos-N	Ncfpc
ag	ag	ag-S	Sp
bogadh	bogadh	bog-N	Nv
ach	ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
gabháil	gabháil	gabh-N	Nv
áit	áit	áit-N	Ncfsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
greim	greim	greim-N	Ncmsc
daingean	daingean	daingean-A	Aq-msc
ag	ag	ag-S	Sp
'	'	'-F	Fa
rud	rud	rud-N	Ncmsc
inteacht	inteacht	tar-N	Ncmsc|Nv
’	’	’-F	Fa
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
mo	mo	mo-D	Dp1-s
ghualainn	ghualainn	gualainn-N	Ncfsc
.	.	.-F	Fe
Thiontaigh	Thiontaigh	tiontaigh-V	Vmis
mé	mé	mé-P	Pp1-s
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
mo	mo	mo-D	Dp1-s
sháil	sháil	sáil-N	Ncfsc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-V	Vmm-2s
mé	mé	mé-P	Pp1-s
idir	idir	idir-S	Sp
an	an	an-T	Td-s
dá	dá	dó-M	Mc
shúil	shúil	súil-N	Ncfsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
rud	rud	rud-N	Ncmsc
uafásach	uafásach	uafásach-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
ar	ar	ar-S	Sp
chor	chor	cor-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
.	.	.-F	Fe
Fathach	Fathach	fathach-N	Ncmsc
de	de	de-S	Sp
dhuine	dhuine	duine-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
cuma	cuma	cuma-N	Ncfsc
gharbh	gharbh	garbh-A	Aq-fsc
air	air	ar-P	Pr3ms
ach	ach	ach-C	Cs
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
féin	féin	féin-P	Px
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
brón	brón	brón-N	Ncmsc
sna	sna	i-S	Spa-p
súile	súile	súil-N	Ncfpc
a	a	a-Q	Q-r
chuaigh	chuaigh	téigh-V	Vmis
go	go	go-S	Sp
smior	smior	smior-N	Ncmsc
ionam	ionam	ionam-N	Ncmpg
.	.	.-F	Fe
'	'	'-F	Fa
Ar	Ar	ar-Q	Qq-s
thug	thug	tabhair-V	Vmis
tú	tú	tú-P	Pp2-s
leat	leat	le-P	Pr2-s
é	é	é-P	Pp3ms
?	?	?-F	Fq
'	'	'-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
impigh	impigh	impigh-V	Vmis
sé	sé	sé-P	Pp3msn
arís	arís	arís-R	Rg
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
stánadh	stánadh	stán-N	Nv
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
'	'	'-F	Fa
Cad	Cad	cad-W	W--q
é	é	é-P	Pp3ms
?	?	?-F	Fq
'	'	'-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
mé	mé	mé-P	Pp1-s
sa	sa	i-S	Spa-s
deireadh	deireadh	deireadh-N	Ncmsc
agus	agus	agus-C	Cc
crith	crith	crith-V	Vmm-2s
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
bhéal	bhéal	béal-N	Ncmsc
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
thuig	thuig	tuig-V	Vmip---n|Vmis---n
mé	mé	mé-P	Pp1-s
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-U	U
mhaíomh	mhaíomh	maígh-N	Nv
.	.	.-F	Fe
'	'	'-F	Fa
An	An	an-T	Td-s
taistealaí	taistealaí	taistealaí-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
'	'	'-F	Fa
An	An	an-T	Td-s
gléas	gléas	gléas-N	Ncmsc
a	a	a-Q	Q-r
chuidigh	chuidigh	cuidigh-V	Vmis
leat	leat	le-P	Pr2-s
teacht	teacht	tar-N	Nv
anseo	anseo	anseo-R	Rl
.	.	.-F	Fe
Ar	Ar	ar-Q	Qq-s
thug	thug	tabhair-V	Vmis
tú	tú	tú-P	Pp2-s
leat	leat	le-P	Pr2-s
é	é	é-P	Pp3ms
?	?	?-F	Fq
'	'	'-F	Fa
Thuig	Thuig	tuig-V	Vmis
mé	mé	mé-P	Pp1-s
ansin	ansin	ansin-R	Rt|Rl
gur	gur	is-W	Wsdi
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
ar	ar	ar-S	Sp
an	an	an-T	Td-s
lampa	lampa	lampa-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-V	Vmm-2s
mé	mé	mé-P	Pp1-s
thart	thart	thart-R	Rd
lena	lena	le-S	Spp-s
chuartú	chuartú	cuartú-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
rud	rud	rud-N	Ncmsc
féin	féin	féin-P	Px
ina	ina	i-S	Spp-s|Spp-p
luí	luí	luí-N	Ncmsc
fá	fá	faoi-P	Pr3ms
ghiota	ghiota	giota-N	Ncmsc
dúinn	dúinn	do-P	Pr1-p
.	.	.-F	Fe
I	I	i-S	Sp
bhfaiteadh	bhfaiteadh	faiteadh-N	Ncmsc
na	na	na-T	Td-p
súl	súl	súil-N	Ncfpg
shín	shín	sín-V	Vmis
an	an	an-T	Td-s
fathach	fathach	fathach-N	Ncmsc
amach	amach	amach-R	Rd
a	a	a-D	Dp3
lámh	lámh	lámh-N	Ncfsc
agus	agus	agus-C	Cc
rug	rug	beir-V	Vmis
greim	greim	greim-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
lampa	lampa	lampa-N	Ncmsc
luachmhar	luachmhar	luachmhar-A	Aq-msc
seo	seo	seo-D	Dd
.	.	.-F	Fe
Shílfeá	Shílfeá	síl-V	Vmc-2s
gur	gur	is-W	Wsdi
páiste	páiste	páiste-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
Lá	Lá	lá-N	Ncmsc
Nollag	Nollag	Nollaig-N	Ncfsg
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
pocléim	pocléim	pocléim-N	Nv
le	le	le-S	Sp
háthas	háthas	áthas-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
lúcháir	lúcháir	lúcháir-N	Ncfsc
an	an	an-T	Td-s
domhain	domhain	domhan-N	Ncmsg
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
greim	greim	greim-N	Ncmsc
aige	aige	ag-P	Pr3ms
go	go	go-U	Ua
fóill	fóill	fóill-A	Aqp
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
mo	mo	mo-D	Dp1-s
ghualainn	ghualainn	gualainn-N	Ncfsc
agus	agus	agus-C	Cc
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
de	de	de-P	Pr3ms
,	,	,-F	Fi
tharraing	tharraing	tarraing-V	Vmis
sé	sé	sé-P	Pp3msn
mé	mé	mé-P	Pp1-s
suas	suas	suas-R	Rd
agus	agus	agus-C	Cc
anuas	anuas	anuas-R	Rd
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
sásta	sásta	sásta-A	Aqp
sa	sa	i-S	Spa-s
deireadh	deireadh	deireadh-N	Ncmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
stad	stad	stad-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
'	'	'-F	Fa
Sa	Sa	i-S	Spa-s
deireadh	deireadh	deireadh-N	Ncmsc
,	,	,-F	Fi
tá	tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
bhéic	bhéic	béic-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
'	'	'-F	Fa
Thig	Thig	tar-V	Vmip
liom	liom	le-P	Pr1-s
imeacht	imeacht	imigh-N	Nv
!	!	!-F	Fe
Thig	Thig	tar-V	Vmip
liom	liom	le-P	Pr1-s
imeacht	imeacht	imigh-N	Nv
!	!	!-F	Fe
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
pacáil	pacáil	pacáil-N	Ncfsc|Nv
anois	anois	anois-R	Rt
–	–	–-X	Xx
níl	níl	bí-V	Vmip---n
mé	mé	mé-P	Pp1-s
réidh	réidh	réidh-A	Aqp
.	.	.-F	Fe
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
deifir	deifir	deifir-N	Ncfsc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
!	!	!-F	Fe
'	'	'-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmis
sé	sé	sé-P	Pp3msn
leis	leis	le-P	Pr3ms
agus	agus	agus-C	Cc
ar	ar	ar-S	Sp
ball	ball	ball-N	Ncmsc
beag	beag	beag-A	Aq-msc
tháinig	tháinig	tar-V	Vmis
sé	sé	sé-P	Pp3msn
ar ais	ar ais	ar_ais-R	Rd
agus	agus	agus-C	Cc
cás	cás	cás-N	Ncmsc
beag	beag	beag-A	Aq-msc
ina	ina	i-S	Spp-s|Spp-p
lámh	lámh	lámh-N	Ncfsc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
'	'	'-F	Fa
Ar	Ar	ar-S	Sp
aghaidh	aghaidh	aghaidh-N	Ncfsc
linn	linn	linn-N	Ncfpg
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
'	'	'-F	Fa
Gabh	Gabh	gabh-V	Vmm-2s
ar	ar	ar-S	Sp
aghaidh	aghaidh	aghaidh-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
Ba	Ba	is-W	Ws|Ws-i
léir	léir	léir-A	Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
dúil	dúil	dúil-N	Ncfsc
liom	liom	le-P	Pr1-s
rud	rud	rud-N	Ncmsc
inteacht	inteacht	tar-N	Ncmsc|Nv
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
ach	ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-V	Vmm-2s
mé	mé	mé-P	Pp1-s
air	air	ar-P	Pr3ms
go	go	go-U	Ua
hamhrasach	hamhrasach	amhrasach-A	Aqp
agus	agus	agus-C	Cc
mhothaigh	mhothaigh	mothaigh-V	Vmis
mé	mé	mé-P	Pp1-s
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
éirí	éirí	éirigh-N	Nv
mífhoighdeach	mífhoighdeach	mífhoighdeach-A	Aqp
.	.	.-F	Fe
Cad	Cad	cad-W	W--q
é	é	é-P	Pp3ms
an	an	an-T	Td-s
dochar	dochar	dochar-N	Ncmsc
sin	sin	sin-D	Dd
a	a	a-U	U
thriail	thriail	triail-N	Nv
arís	arís	arís-R	Rg
?	?	?-F	Fq
Chuimil	Chuimil	cuimil-V	Vmis
mé	mé	mé-P	Pp1-s
é	é	é-P	Pp3ms
go	go	go-U	Ua
díreach	díreach	díreach-A	Aqp
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
rinne	rinne	déan-V	Vmis
mé	mé	mé-P	Pp1-s
roimhe	roimhe	roimh-P	Pr3ms
agus	agus	agus-C	Cc
–	–	–-X	Xx
bhúis	bhúis	búis-N	Ncmpc|Ncfsc
!	!	!-F	Fe
–	–	–-X	Xx
don	don	do-S	Spa-s
dara	dara	dara-M	Mo
huair	huair	uair-N	Ncfsc
bhí	bhí	bí-V	Vmis
mo	mo	mo-D	Dp1-s
chorp	chorp	corp-N	Ncmsc
ag	ag	ag-S	Sp
eitilt	eitilt	eitil-N	Nv
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
réaltaí	réaltaí	réalta-N	Ncfpc
ag	ag	ag-S	Sp
spréacharnach	spréacharnach	spréacharnach-N	Ncfsc
thart	thart	thart-R	Rd
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmm-2s
mé	mé	mé-P	Pp1-s
mo	mo	mo-D	Dp1-s
shúile	shúile	súil-N	Ncfpc
go	go	go-U	Ua
fadálach	fadálach	fadálach-A	Aqp
arís	arís	arís-R	Rg
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
lúcháir	lúcháir	lúcháir-N	Ncfsc
orm	orm	ar-P	Pr1-s
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
mé	mé	mé-P	Pp1-s
sa	sa	i-S	Spa-s
bhaile	bhaile	baile-N	Ncmsc
arís	arís	arís-R	Rg
.	.	.-F	Fe
'	'	'-F	Fa
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
muid	muid	muid-P	Pp1-p
?	?	?-F	Fq
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
fathach	fathach	fathach-N	Ncmsc
liom	liom	le-P	Pr1-s
go	go	go-U	Ua
fóill	fóill	fóill-A	Aqp
agus	agus	agus-C	Cc
an	an	an-T	Td-s
chuma	chuma	cuma-N	Ncfsc
air	air	ar-P	Pr3ms
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
sásta	sásta	sásta-A	Aqp
fanacht	fanacht	fan-N	Ncmsc|Nv
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
chónaí	chónaí	cónaí-N	Ncmsc
linn	linn	le-P	Pr1-p
go	go	go-U	Ua
fóill	fóill	fóill-A	Aqp
.	.	.-F	Fe
Síleann	Síleann	síl-V	Vmip
achan	achan	gach-D	Dq
duine	duine	duine-N	Ncmsc
gur	gur	is-W	Wsdi
seanuncail	seanuncail	seanuncail-N	Ncmsc
de	de	de-P	Pr3ms
mo	mo	mo-D	Dp1-s
chuid	chuid	cuid-N	Ncfsc
é	é	é-P	Pp3ms
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
chugainn	chugainn	chuig-P	Pr1-p
as	as	as-S	Sp
an	an	an-T	Td-s
Afraic	Afraic	Afraic-N	Npfsc
,	,	,-F	Fi
ach	ach	ach-C	Cs
tá	tá	bí-V	Vmip
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agaibh	agaibh	ag-P	Pr2-p
an	an	an-T	Td-s
fhírinne	fhírinne	fírinne-N	Ncfsc
anois	anois	anois-R	Rt
.	.	.-F	Fe
I	I	i-S	Sp
dtaca	dtaca	taca-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
lampa	lampa	lampa-N	Ncmsc
,	,	,-F	Fi
ní	ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
mé	mé	mé-P	Pp1-s
arís	arís	arís-R	Rg
é	é	é-P	Pp3ms
.	.	.-F	Fe
Sílim	Sílim	síl-V	Vmip1s
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
m	m	m-X	Xl
’	’	’-F	Fa
uncail	uncail	uncail-N	Ncmsc
úr	úr	úr-A	Aq-msc
i	i	i-S	Sp
bhfolach	bhfolach	folach-N	Ncmsc
áit	áit	áit-N	Ncfsc
inteacht	inteacht	tar-N	Ncmsc|Nv
ar	ar	ar-S	Sp
eagla	eagla	eagla-N	Ncfsc
go	go	go-Q	Q
gcuirfeadh	gcuirfeadh	cuir-V	Vmc
duine	duine	duine-N	Ncmsc
inteacht	inteacht	tar-N	Ncmsc|Nv
ar ais	ar ais	ar_ais-R	Rd
é	é	é-P	Pp3ms
.	.	.-F	Fe
Is	Is	is-W	Wp-i
cuma	cuma	cuma-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
nó	nó	nó-C	Cc
ní	ní	ní-Q	Qn
dhéanfainn	dhéanfainn	déan-V	Vmc-1s-n
an	an	an-T	Td-s
turas	turas	turas-N	Ncmsc
sin	sin	sin-D	Dd
arís	arís	arís-R	Rg
ar	ar	ar-S	Sp
ór	ór	ór-N	Ncmsc
na	na	na-T	Tdfsg
cruinne	cruinne	cruinne-N	Ncfsg
agus	agus	agus-C	Cc
tá	tá	bí-V	Vmip
sé	sé	sé-P	Pp3msn
‑	‑	‑-F	Fb
úsáideach	úsáideach	úsáideach-A	Aqp
fathach	fathach	fathach-N	Ncmsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
agat	agat	ag-P	Pr2-s
mar	mar	mar-S	Sp
uncail	uncail	uncail-N	Ncmsc
.	.	.-F	Fe
