 Fuil	Fuil	-X	Xx
Dhearg	Dhearg	dearg-V	Vmis
an	an	an-T	Td-s
Cheoil	Cheoil	ceol-N	Ncmsg
An	An	an-T	Td-s
chéad	chéad	céad-M	Mo
uair	uair	uair-N	Ncfsc
riamh	riamh	riamh-R	Rg
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
Ciarán	Ciarán	Ciarán-N	Npmsc
Jimi	Jimi	Jimi-N	Npmsc
Hendrix	Hendrix	Hendrix-N	Npmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
teilifís	teilifís	teilifís-N	Ncfsc
shocraigh	shocraigh	socraigh-V	Vmis
sé	sé	sé-P	Pp3msn
giotár	giotár	giotár-N	Ncmsc
a	a	a-U	U
cheannach	cheannach	ceannaigh-N	Nv
.	.	.-F	Fe
Hendrix	Hendrix	Hendrix-N	Npmsc
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
ardán	ardán	ardán-N	Ncmsc
ina	ina	i-S	Spp-s
chulaith	chulaith	culaith-N	Ncfsc
bhán	bhán	bán-A	Aq-fsc
,	,	,-F	Fi
bandána	bandána	bandán-N	Ncmpv
timpeall	timpeall	timpeall-N	Ncmpg|Ncmsc|Sp|Rd
a	a	a-D	Dp3
chuid	chuid	cuid-N	Ncfsc
gruaige	gruaige	gruaig-N	Ncfsg
,	,	,-F	Fi
a	a	a-U	U
shúile	shúile	súil-N	Nv--g--n
dúnta	dúnta	dún-A	Av
agus	agus	agus-C	Cc
a	a	a-D	Dp3
bhéal	bhéal	béal-N	Ncmsc
ar	ar	ar-S	Sp
leathoscailt	leathoscailt	leathoscailt-N	Ncfsc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
É	É	é-P	Pp3ms
beag	beag	beag-N	Ncmsc|Aqp
beann	beann	beann-N	Ncfpg|Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
slua	slua	slua-N	Ncmsc
os	os	os-N	Ncmpg|Sp|Ncmsc
a	a	a-Q	Q-r
chomhair	chomhair	comhair-V	Vmis
amach	amach	amach-R	Rd
,	,	,-F	Fi
slua	slua	slua-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
stánadh	stánadh	stán-N	Nv
air	air	ar-N	Ncmsg|Pr3ms|Ncmsg
ar nós	ar nós	ar_nós-S	Spc
páistí	páistí	páiste-N	Ncmpg
ocracha	ocracha	ocrach-A	Aq--pg
ag	ag	ag-S	Sp
faire	faire	fair-N	Nv
ar	ar	ar-S	Sp
fhuinneog	fhuinneog	fuinneog-N	Ncfsc
siopa	siopa	siopa-N	Ncmsg
milseán	milseán	milseán-N	Ncmpg|Ncmsc|Ncmpg
.	.	.-F	Fe
A	A	a-T	Td-s|Dp3|U|Uv
mhéara	mhéara	méar-N	Ncmsv|Ncfpv
ag	ag	ag-S	Sp
rince	rince	rinc-N	Nv
ar	ar	ar-S	Sp
mhuineál	mhuineál	muineál-N	Ncmsc
an	an	an-T	Td-s
ghiotáir	ghiotáir	giotár-N	Ncmsg
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
ag	ag	ag-S	Sp
tarraingt	tarraingt	tarraing-N	Nv
ceol	ceol	ceol-N	Ncmsc
fíochmhar	fíochmhar	fíochmhar-A	Aq-msc
as	as	as-P	Pr3ms
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
mála	mála	mála-N	Ncmsc
de	de	de-S	Sp
chait	chait	cat-N	Ncmpc
fhiáine	fhiáine	fiáin-A	Aq--pc
ann	ann	ann-R	Rl
oíche	oíche	oíche-N	Ncfsc
ghealaí	ghealaí	gealach-N	Ncfsg
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
dul	dul	dul-N	Ncmsc
as	as	as-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
giotár	giotár	giotár-N	Ncmsc
ó	ó	ó-S	Sp
Chiarán	Chiarán	Ciarán-N	Npmsc
.	.	.-F	Fe
Láithreach	Láithreach	láithreach-N	Ncmsc
!	!	!-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
t	t	t-X	Xl
‑	‑	‑-F	Fb
aon	aon	aon-M	Mc
fhadhb	fhadhb	fadhb-N	Ncfsc
amháin	amháin	amháin-A	Aqp
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
A	A	a-U	Uv
Mhamaí	Mhamaí	mamaí-N	Ncmpv|Ncfsv
,	,	,-F	Fi
ar	ar	ar-S	Sp
ndóigh	ndóigh	dóigh-N	Ncfsc
.	.	.-F	Fe
Cé	Cé	cé-W	W--q
eile	eile	eile-D	Dd
?	?	?-F	Fq
'	'	'-F	Fa
Giotár	Giotár	giotár-N	Ncmsc
?	?	?-F	Fq
Níl	Níl	bí-V	Vmip---n
giotár	giotár	giotár-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
teach	teach	teach-N	Ncmsc
seo	seo	seo-D	Dd
!	!	!-F	Fe
Bheimis	Bheimis	bí-V	Vmc-1p
bodhar	bodhar	bodhar-N	Ncmsc
agat	agat	ag-P	Pr2-s
!	!	!-F	Fe
Cé	Cé	cé-P	Pq
mhéad	mhéad	méad-N	Ncmsc
a	a	a-Q	Q-r
chosnódh	chosnódh	cosain-V	Vmc
sé	sé	sé-P	Pp3msn
?	?	?-F	Fq
Cé	Cé	cé-P	Pq
a	a	a-Q	Q-r
mhúinfeadh	mhúinfeadh	múin-V	Vmc
duit	duit	do-P	Pr2-s
conas	conas	conas-R	Rq
é	é	é-P	Pp3ms
a	a	a-U	U
sheinm	sheinm	seinn-N	Nv
?	?	?-F	Fq
'	'	'-F	Fa
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
freagra	freagra	freagra-N	Ncmsc
ag	ag	ag-S	Sp
Ciarán	Ciarán	Ciarán-N	Npmsc
ar	ar	ar-S	Sp
gach	gach	gach-D	Dq
ceist	ceist	ceist-N	Ncfsc
agus	agus	agus-C	Cc
ghéill	ghéill	géill-V	Vmis
sí	sí	sí-P	Pp3fsn
sa	sa	i-S	Spa-s
deireadh	deireadh	deireadh-N	Ncmsc
,	,	,-F	Fi
mar	mar	mar-C	Cs
ba	ba	is-W	Wsri
ghnách	ghnách	gnách-A	Aqp
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
fadhb	fadhb	fadhb-N	Ncfsc
amháin	amháin	amháin-A	Aqp
eile	eile	eile-D	Dd
fós	fós	fós-R	Rg
aige	aige	ag-P	Pr3ms
–	–	–-X	Xx
ní	ní	ní-Q	Qn
íocfadh	íocfadh	íoc-V	Vmc----n
sí	sí	sí-P	Pp3fsn
as	as	as-P	Pr3ms
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
t	t	t-X	Xl
‑	‑	‑-F	Fb
ádh	ádh	ádh-N	Ncmsc
dearg	dearg	dearg-A	Aq-msc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
chóineartú	chóineartú	cóineartú-N	Ncmsc
díreach	díreach	díreach-A	Aq-msc
thart	thart	thart-R	Rd
agus	agus	agus-C	Cc
bheadh	bheadh	bí-V	Vmc
a	a	a-D	Dp3
bhreithlá	bhreithlá	lá-N	Ncmsc
ann	ann	i-R	Rl|Pr3ms
gan	gan	gan-S	Sp
mhoill	mhoill	moill-N	Ncfsc
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
ndóigh	ndóigh	dóigh-N	Ncfsc
,	,	,-F	Fi
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
a	a	a-D	Dp3
uncailí	uncailí	uncail-N	Ncmpc
ná	ná	ná-C	Cs|Cc
a	a	a-D	Dp3
aintíní	aintíní	aintín-N	Ncfpc
róshásta	róshásta	sásta-A	Aqp
é	é	é-P	Pp3ms
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
chucu	chucu	chuig-P	Pr3-p
arís	arís	arís-R	Rg
chomh	chomh	chomh-R	Ri
luath	luath	luath-A	Aqp
seo	seo	seo-P	Pd|Dd
ach	ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
an	an	an-T	Td-s
dara	dara	dara-M	Mo
rogha	rogha	rogha-N	Ncfsc
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
ar	ar	ar-S	Sp|Ncmsc
a	a	a-D	Dp3
leithéidí	leithéidí	leithéid-N	Ncfpc
bronntanas	bronntanas	bronntanas-N	Ncmpg|Ncmsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
dá	dá	do-S	Spp-s|Spp-p
nia	nia	nia-N	Ncmsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
bhreithlá	bhreithlá	lá-N	Ncmsc
–	–	–-X	Xx
is	is	agus-C	Cc
riail	riail	riail-N	Ncfsc
dhaingean	dhaingean	daingean-A	Aq-fsc
dhocht	dhocht	docht-A	Aq-fsc
í	í	í-P	Pp3fs
!	!	!-F	Fe
Fuair	Fuair	faigh-V	Vmis
sé	sé	sé-P	Pp3msn
airgead	airgead	airgead-N	Ncmsc
óna	óna	ó-S	Spp-s
Dhaideo	Dhaideo	daideo-N	Ncmsc
faoi	faoi	faoi-S	Sp
dhó	dhó	dó-M	Mc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
bocht	bocht	bocht-A	Aq-msc
‑	‑	‑-F	Fb
dearmadach	dearmadach	dearmadach-A	Aqp
ach	ach	ach-C	Cs
,	,	,-F	Fi
chun	chun	chun-S	Sp
a	a	a-D	Dp3
cheart	cheart	ceart-N	Ncmsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
do	do	do-S	Sp
Chiarán	Chiarán	Ciarán-N	Npmsc
,	,	,-F	Fi
níor	níor	is-W	Ws-in
ghnách	ghnách	gnách-A	Aqp
leis	leis	le-P	Pr3ms
teacht	teacht	tar-N	Nv
i	i	i-S	Sp
dtír	dtír	tír-N	Ncfsc
air	air	ar-N	Ncmsg
sin	sin	sin-P	Pd|Dd
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
gach	gach	gach-D	Dq
cent	cent	cent-X	Xfen
rua	rua	rua-N	Npfsg|Ncmsg|Npmsg|Ncfsc|Ncfsg|Ncmsc|Npmsc|Ncfsg
bailithe	bailithe	bailigh-A	Av
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
aige	aige	ag-P	Pr3ms
thug	thug	tabhair-V	Vmis
Ciarán	Ciarán	Ciarán-N	Npmsc
aghaidh	aghaidh	aghaidh-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
siopa	siopa	siopa-N	Ncmsc
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
.	.	.-F	Fe
Déagóir	Déagóir	déagóir-N	Ncmsc
le	le	le-S	Sp
gruaig	gruaig	gruaig-N	Ncfsc
fhada	fhada	fada-A	Aqp
shleamhain	shleamhain	sleamhain-A	Aqp
,	,	,-F	Fi
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
a	a	a-D	Dp3
chuid	chuid	cuid-N	Ncfsc
cainte	cainte	caint-N	Ncfsg|Nv--g--n
chomh	chomh	chomh-R	Ri
mall	mall	mall-A	Aqp
lena	lena	le-S	Spp-s
chuid	chuid	cuid-N	Ncfsc
siúil	siúil	siúl-N	Ncmsg
,	,	,-F	Fi
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
i bhfeighil	i bhfeighil	i_bhfeighil-S	Spc
na	na	na-T	Td-p
ngiotár	ngiotár	giotár-N	Ncmpg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
shuí	shuí	suí-N	Ncmsc
ar	ar	ar-S	Sp
stól	stól	stól-N	Ncmsc
ard	ard	ard-A	Aq-msc
ag	ag	ag-S	Sp
léamh	léamh	léigh-N	Nv
Rock	Rock	Rock-N	Npmsg
Guitar	Guitar	guitar-X	Xfen
Monthly	Monthly	monthly-X	Xfea
agus	agus	agus-C	Cc
lean	lean	lean-V	Vmis
sé	sé	sé-P	Pp3msn
air	air	ar-P	Pr3ms
ag	ag	ag-S	Sp
léamh	léamh	léigh-N	Nv
a	a	a-D	Dp3
fhad	fhad	fad-N	Ncmsc
is	is	agus-C	Cc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Ciarán	Ciarán	Ciarán-N	Npmsc
ag	ag	ag-S	Sp
breathnú	breathnú	breathnaigh-N	Nv
timpeall	timpeall	timpeall-S	Sp
an	an	an-T	Td-s
tsiopa	tsiopa	siopa-N	Ncmsg
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
Ciarán	Ciarán	Ciarán-N	Npmsc
leis	leis	le-P	Pr3ms
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
giotár	giotár	giotár-N	Ncmsc
cosúil	cosúil	cosúil-A	Aq-msc
le	le	le-S	Sp
giotár	giotár	giotár-N	Ncmsc
Hendrix	Hendrix	Hendrix-N	Npmsc
de	de	de-S	Sp
dhíth	dhíth	díth-N	Ncfsc
air	air	ar-N	Ncmsg
tháinig	tháinig	tar-V	Vmis
miongháire	miongháire	miongháire-N	Ncmsc
beag	beag	beag-A	Aq-msc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
bhéal	bhéal	béal-N	Ncmsc
.	.	.-F	Fe
Shín	Shín	Sín-N	Npfsc
sé	sé	is-W	Wp-i-3
méar	méar	méar-N	Ncfsc
fhada	fhada	fada-A	Aqp
thanaí	thanaí	tanaí-A	Aqp
i	i	i-S	Sp
dtreo	dtreo	treo-N	Ncmsc
cás	cás	cás-N	Ncmsc
gloine	gloine	gloine-N	Ncfsg|Ncfsc
taobh	taobh	taobh-N	Ncmsc
thiar	thiar	thiar-R	Rd
de	de	de-P	Pr3ms
.	.	.-F	Fe
Stán	Stán	stán-V	Vmis
Ciarán	Ciarán	Ciarán-N	Npmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
ngiotár	ngiotár	giotár-N	Ncmsc
sa	sa	i-S	Spa-s
chás	chás	cás-N	Ncmsc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
bhéal	bhéal	béal-N	Ncmsc
ar	ar	ar-S	Sp
oscailt	oscailt	oscail-N	Nv
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
B	B	B-X	Xl
’	’	’-F	Fa
in	in	sin-S	Sp|Pd
é	é	é-P	Pp3ms
an	an	an-T	Td-s
giotár	giotár	giotár-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
uaidh	uaidh	ó-P	Pr3ms
,	,	,-F	Fi
gan	gan	gan-S	Sp
dabht	dabht	dabht-N	Ncmsc
ar	ar	ar-S	Sp
domhan	domhan	domhan-N	Ncmsc
–	–	–-X	Xx
an	an	an-T	Td-s
cruth	cruth	cruth-N	Ncmsc
,	,	,-F	Fi
an	an	an-T	Td-s
dath	dath	dath-N	Ncmsc
,	,	,-F	Fi
an	an	an-T	Td-s
loinnir	loinnir	loinnir-N	Ncfsc
–	–	–-X	Xx
gach	gach	gach-D	Dq
rud	rud	rud-N	Ncmsc
díreach	díreach	díreach-A	Aq-msc
i	i	i-S	Sp
gceart	gceart	ceart-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ansin	ansin	ansin-R	Rt|Rl
thug	thug	tabhair-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
praghas	praghas	praghas-N	Ncmsc
faoi	faoi	faoi-S	Sp
deara	deara	deara-N	Ns-s
agus	agus	agus-C	Cc
thuig	thuig	tuig-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
miongháire	miongháire	miongháire-N	Ncmsc
.	.	.-F	Fe
Bheadh	Bheadh	bí-V	Vmc
fiche	fiche	fiche-N	Ncmsc|Mc
uncail	uncail	uncail-N	Ncmsg|Ncmsc
agus	agus	agus-C	Cc
daichead	daichead	daichead-N	Ncmsc|Mc
aintín	aintín	aintín-N	Ncfsg|Ncfsc
de	de	de-S	Sp
dhíth	dhíth	díth-N	Ncfsc
air	air	ar-N	Ncmsg
chun	chun	chun-S	Sp
giotár	giotár	giotár-N	Ncmpg
den	den	de-S	Spa-s
chineál	chineál	cineál-N	Ncmsc
sin	sin	sin-D	Dd
a	a	a-U	U
cheannach	cheannach	ceannaigh-N	Nv
!	!	!-F	Fe
Chonaic	Chonaic	feic-V	Vmis
an	an	an-T	Td-s
déagóir	déagóir	déagóir-N	Ncmsc
an	an	an-T	Td-s
díomá	díomá	díomá-N	Ncfsg
ar	ar	ar-S	Sp
aghaidh	aghaidh	aghaidh-N	Ncfsc
Chiaráin	Chiaráin	Ciarán-N	Npfsg|Npm-g
agus	agus	agus-C	Cc
lig	lig	lig-V	Vmis
sé	sé	sé-P	Pp3msn
osna	osna	osna-N	Ncmsc
as	as	as-P	Pr3ms
.	.	.-F	Fe
Bheadh	Bheadh	bí-V	Vmc
air	air	ar-P	Pr3ms
éirí	éirí	éirí-N	Ncmsc
den	den	de-S	Spa-s
stól	stól	stól-N	Ncmsc
!	!	!-F	Fe
Thug	Thug	tabhair-V	Vmis
sé	sé	sé-P	Pp3msn
Ciarán	Ciarán	Ciarán-N	Npmsc
siar	siar	siar-R	Rd
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
gcúl	gcúl	cúl-N	Ncmsc
an	an	an-T	Td-s
tsiopa	tsiopa	siopa-N	Ncmsg
,	,	,-F	Fi
áit	áit	áit-N	Ncfsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
na	na	na-T	Td-p
giotáir	giotáir	giotár-N	Ncmpc
shaora	shaora	saor-A	Aq--pc
d	d	d-X	Xl
’	’	’-F	Fa
fhoghlaimeoirí	fhoghlaimeoirí	foghlaimeoir-N	Ncmpc
.	.	.-F	Fe
Thaispeáin	Thaispeáin	taispeáin-V	Vmis
sé	sé	sé-P	Pp3msn
ceann	ceann	ceann-N	Ncmsc
do	do	do-S	Sp
Chiarán	Chiarán	Ciarán-N	Npmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
cosúil	cosúil	cosúil-A	Aqp
le	le	le-S	Sp
giotár	giotár	giotár-N	Ncmsc
Hendrix	Hendrix	Hendrix-N	Npmsc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
inis	inis	inis-V	Vmis
sé	sé	sé-P	Pp3msn
dó	dó	do-P	Pr3ms
gur	gur	is-W	Wsdi
ghiotár	ghiotár	giotár-N	Ncmsc
mar	mar	mar-C	Cs
sin	sin	sin-W	W
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
aige	aige	ag-P	Pr3ms
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
foghlaim	foghlaim	foghlaim-N	Nv
.	.	.-F	Fe
Thaispeáin	Thaispeáin	taispeáin-V	Vmis
sé	sé	sé-P	Pp3msn
dó	dó	do-P	Pr3ms
conas	conas	conas-R	Rq
an	an	an-T	Td-s
giotár	giotár	giotár-N	Ncmsc
a	a	a-U	U
chur	chur	cuir-N	Nv
i	i	i-S	Sp
bhfearas	bhfearas	fearas-N	Ncmsc
agus	agus	agus-C	Cc
mhúin	mhúin	múin-V	Vmis
sé	sé	sé-P	Pp3msn
corda	corda	corda-N	Ncmsc
'	'	'-F	Fa
C	C	C-X	Xl
’	’	’-F	Fa
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
Sheol	Sheol	seol-V	Vmis
sé	sé	sé-P	Pp3msn
abhaile	abhaile	abhaile-R	Rd
ansin	ansin	ansin-R	Rt|Rl
é	é	é-P	Pp3ms
chun	chun	chun-S	Sp
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
cleachtadh	cleachtadh	cleacht-N	Nv
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
sular	sular	sula-C	Csws
fhág	fhág	fág-N	Ncmsc
Ciarán	Ciarán	Ciarán-N	Npmsc
an	an	an-T	Td-s
siopa	siopa	siopa-N	Ncmsg
d	d	d-X	Xl
’	’	’-F	Fa
inis	inis	inis-V	Vmis
sé	sé	sé-P	Pp3msn
dó	dó	do-P	Pr3ms
go	go	go-Q	Q
mbíodh	mbíodh	bí-V	Vmih
Hendrix	Hendrix	Hendrix-N	Npmsc
ag	ag	ag-S	Sp
cleachtadh	cleachtadh	cleacht-N	Nv
ar feadh	ar feadh	ar_feadh-S	Spc
cúig	cúig	cúig-N	Ncmsg
uaire	uaire	uair-N	Ncfsg
an	an	an-T	Td-s
chloig	chloig	clog-N	Ncmsg
gach	gach	gach-D	Dq
lá	lá	lá-N	Ncmsc
nó	nó	nó-C	Cc
go dtí	go dtí	go_dtí-S	Spc
go	go	go-Q	Q
dtosaíodh	dtosaíodh	tosaigh-V	Vmih
a	a	a-D	Dp3
mhéara	mhéara	méara-N	Ncfpc|Ncmsc
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
fola	fola	fuil-N	Ncfsg|Ncfpg
!	!	!-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
shroich	shroich	sroich-V	Vmis
Ciarán	Ciarán	Ciarán-N	Npmsc
an	an	an-T	Td-s
baile	baile	baile-N	Ncmsg
thóg	thóg	tóg-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
giotár	giotár	giotár-N	Ncmsc
as	as	as-S	Sp
an	an	an-T	Td-s
mbosca	mbosca	bosca-N	Ncmsc
go	go	go-U	Ua
réidh	réidh	réidh-A	Aqp
cúramach	cúramach	cúramach-A	Aqp
agus	agus	agus-C	Cc
phlugáil	phlugáil	plugáil-V	Vmis
sé	sé	sé-P	Pp3msn
isteach	isteach	isteach-R	Rd
é	é	é-P	Pp3ms
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
cleachtadh	cleachtadh	cleacht-N	Nv
go	go	go-U	Ua
díograiseach	díograiseach	díograiseach-A	Aqp
agus	agus	agus-C	Cc
meangadh	meangadh	meangadh-V	Vmis0|Vmm-3s|Ncmsc
mór	mór	mór-A	Aq-msc|Aqp|Ncmpg|Ncmsc|Ncmpg
gáire	gáire	gáir-N	Ncfsg|Nv|Ncmsg|Ncmsc|Nv--g
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
bhéal	bhéal	béal-N	Ncmsc
.	.	.-F	Fe
Taobh	Taobh	taobh-N	Ncmsc
istigh	istigh	istigh-R	Rl
de	de	de-S	Sp
chúig	chúig	cúig-N	Ncmsc
nóiméad	nóiméad	nóiméad-N	Ncmpg
,	,	,-F	Fi
áfach	áfach	áfach-R	Rg
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
meangadh	meangadh	meangadh-N	Ncmsc
gáire	gáire	gáire-N	Ncfsg|Ncmsc|Ncmsg
imithe	imithe	imigh-A	Av
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
pianta	pianta	pian-A	Av
ina	ina	i-S	Spp-s
chuid	chuid	cuid-N	Ncfsc
méar	méar	méar-N	Ncfpg
,	,	,-F	Fi
ina	ina	i-S	Spp-s
ghuaillí	ghuaillí	gualainn-N	Ncmsc|Ncfpc
,	,	,-F	Fi
i	i	i-S	Sp
gcaol	gcaol	caol-N	Ncmsc
na	na	na-T	Tdfsg
láimhe	láimhe	lámh-N	Ncfsg
agus	agus	agus-C	Cc
fiú	fiú	fiú-N	Ncmsg|Ncmsc|Rg|Ns-s
ina	ina	i-S	Spp-s
mhuineál	mhuineál	muineál-N	Ncmsc
.	.	.-F	Fe
Chomh	Chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
leis	leis	le-S	Sp
sin	sin	sin-P	Pd
bhí	bhí	bí-V	Vmis
a	a	a-U	Ud|Dp3
Mhamaí	Mhamaí	mamach-A	Aqc
ag	ag	ag-S	Sp
screadaíl	screadaíl	screadaíl-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
taobh	taobh	taobh-N	Ncmsc
eile	eile	eile-D	Dd
den	den	de-S	Spa-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
a	a	a-U	Uv
Mham	Mham	mam-N	Ncfsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Ciarán	Ciarán	Ciarán-N	Npmsc
de	de	de-U	Up
bhéic	bhéic	béic-V	Vmis
,	,	,-F	Fi
'	'	'-F	Fa
caithfi	caithfi	caithfi-N	Ncfsc
dh	dh	dh-Y	Y
mé	mé	mé-P	Pp1-s
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
cleachtadh	cleachtadh	cleacht-N	Nv
go dtí	go dtí	go_dtí-S	Spc
go	go	go-Q	Q
dtosaíonn	dtosaíonn	tosaigh-V	Vmip
mo	mo	mo-D	Dp1-s
mhéara	mhéara	méara-N	Ncfpc|Ncmsc
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
fola	fola	fuil-N	Ncfsg|Ncfpg
!	!	!-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Beidh	Beidh	bí-V	Vmif
rud	rud	rud-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
eile	eile	eile-D	Dd
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
fola	fola	fuil-N	Ncfsg|Ncfpg
mura	mura	mura-C	Cs
n	n	n-X	Xl
‑	‑	‑-F	Fb
éiríonn	éiríonn	éirigh-V	Vmip
tú	tú	tú-P	Pp2-s
as	as	as-N	Ncmsc|Sp
láithreach	láithreach	láithreach-N	Ncmsc|Aqp
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
scread	scread	scread-V	Vmis
a	a	a-U	Ud|Dp3
Mhamaí	Mhamaí	mamach-A	Aqc
ar ais	ar ais	ar_ais-R	Rd
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
an	an	an-T	Td-s
dara	dara	dara-M	Mo
rogha	rogha	rogha-N	Ncfsc
aige	aige	ag-P	Pr3ms
ach	ach	ach-S	Sp
éirí	éirí	éirí-N	Ncmsc
as	as	as-N	Ncmpg
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
cleachtadh	cleachtadh	cleacht-N	Nv
ina	ina	i-S	Spp-s
sheomra	sheomra	seomra-N	Ncmsc
codlata	codlata	codail-A	Av
!	!	!-F	Fe
Ach	Ach	ach-S	Sp
gach	gach	gach-D	Dq
lá	lá	lá-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|Dd
chaitheadh	chaitheadh	caith-V	Vmih
sé	sé	sé-P	Pp3msn
tamall	tamall	tamall-N	Ncmsc
ag	ag	ag-S	Sp
cleachtadh	cleachtadh	cleacht-N	Nv
sa	sa	i-S	Spa-s
tseid	tseid	seid-N	Ncfsc
ag	ag	ag-S	Sp
bun	bun	bun-N	Ncmsc
an	an	an-T	Td-s
ghairdín	ghairdín	gairdín-N	Ncmsg
agus	agus	agus-C	Cc
a	a	a-D	Dp3
fhad	fhad	fad-N	Ncmsc
is	is	agus-C	Cc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
a	a	a-D	Dp3
chuid	chuid	cuid-N	Ncfsc
gruaige	gruaige	gruaig-N	Ncfsg
ag	ag	ag-S	Sp
éirí	éirí	éirigh-N	Nv
níos	níos	níos-U	Uc
faide	faide	fada-A	Aqc
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
tréimhse	tréimhse	tréimhse-N	Ncfsc
chleachtaidh	chleachtaidh	cleachtadh-N	Ncmsg
ag	ag	ag-S	Sp
éirí	éirí	éirigh-N	Nv
níos	níos	níos-U	Uc
faide	faide	fada-A	Aqc
freisin	freisin	freisin-R	Rg
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
lá	lá	lá-N	Ncmsc
aoibhinn	aoibhinn	aoibhinn-A	Aq-msc
amháin	amháin	amháin-A	Aqp
,	,	,-F	Fi
sa	sa	i-S	Spa-s
tseid	tseid	seid-N	Ncfsc
sin	sin	sin-D	Dd
ag	ag	ag-S	Sp
bun	bun	bun-N	Ncmsc
an	an	an-T	Td-s
ghairdín	ghairdín	gairdín-N	Ncmsg
–	–	–-X	Xx
a	a	a-U	U
shúile	shúile	súil-N	Nv--g--n
dúnta	dúnta	dún-A	Av
,	,	,-F	Fi
a	a	a-D	Dp3
bhéal	bhéal	béal-N	Ncmsc
ar	ar	ar-S	Sp
leathoscailt	leathoscailt	leathoscailt-N	Ncfsc
aige	aige	ag-P	Pr3ms
agus	agus	agus-C	Cc
an	an	an-T	Td-s
giotár	giotár	giotár-N	Ncmsc
ag	ag	ag-S	Sp
screadaíl	screadaíl	screadaíl-N	Ncfsc
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
mála	mála	mála-N	Ncmsc
de	de	de-S	Sp
chait	chait	cat-N	Ncmpc
fhiáine	fhiáine	fiáin-A	Aq--pc
ann	ann	ann-R	Rl
oíche	oíche	oíche-N	Ncfsc
ghealaí	ghealaí	gealach-N	Ncfsg
–	–	–-X	Xx
mhothaigh	mhothaigh	mothaigh-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
mhéara	mhéara	méara-N	Ncfpc|Ncmsc
ag	ag	ag-S	Sp
sleamhnú	sleamhnú	sleamhnaigh-N	Nv
ar	ar	ar-S	Sp
na	na	na-T	Td-p
sreanga	sreanga	sreang-N	Ncfpc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
nuair	nuair	nuair-C	Cs
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
sé	sé	sé-P	Pp3msn
síos	síos	síos-R	Rd
cad	cad	cad-P	Pq
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
le	le	le-S	Sp
feiceáil	feiceáil	feic-N	Nv
ag	ag	ag-S	Sp
sileadh	sileadh	sil-N	Nv
óna	óna	ó-S	Spp-s
mhéara	mhéara	méara-N	Ncfpc|Ncmsc
ach	ach	ach-S	Sp
fuil	fuil	fuil-N	Ncfsc
dhearg	dhearg	dearg-A	Aq-fsc
an	an	an-T	Td-s
cheoil	cheoil	ceol-N	Ncmsg
.	.	.-F	Fe
