Bhí	Bhí	bí-V	Vmis
Dónall	Dónall	Dónall-N	Npmsc
Óg	Óg	óg-N	Ncmsc|Ncmpg
Ó	Ó	Ó-U	Up
Scolláin	Scolláin	Scolláin-N	Npmsc
ag	ag	ag-S	Sp
ceangal	ceangal	ceangail-N	Nv
a	a	a-D	Dp3
chuid	chuid	cuid-N	Ncfsc
bróg	bróg	bróg-N	Ncfpg
ag	ag	ag-S	Sp
an	an	an-T	Td-s
tinteán	tinteán	tinteán-N	Ncmsc
i ndiaidh	i ndiaidh	i_ndiaidh-S	Spc
an	an	an-T	Td-s
bhricfeasta	bhricfeasta	bricfeasta-N	Ncmsg
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
chosúil	chosúil	cosúil-A	Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
rud	rud	rud-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
ag	ag	ag-S	Sp
dó	dó	dóigh-N	Nv
na	na	na-T	Tdfsg
geirbe	geirbe	geirbe-N	Ncfsc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
'	'	'-F	Fa
A	A	a-U	Uv
Mháthair	Mháthair	máthair-N	Ncfsv
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
ar	ar	ar-S	Sp|Ncmsc|Q-is
deireadh	deireadh	deireadh-V	Vmih|Ncmsc
,	,	,-F	Fi
'	'	'-F	Fa
beidh	beidh	bí-V	Vmif
trialacha	trialacha	triail-N	Ncfpc
capall	capall	capall-N	Ncmpg|Ncmsc
i	i	i-S	Sp
gCoill	gCoill	coll-N	Ncfsc|Ncmpc
na	na	na-T	Td-p
Baice	Baice	Baice-N	Npmsc
inniu	inniu	inniu-R	Rt
.	.	.-F	Fe
'	'	'-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-V	Vmis
sé	sé	sé-P	Pp3msn
suas	suas	suas-R	Rd
uirthi	uirthi	ar-P	Pr3fs
agus	agus	agus-C	Cc
a	a	a-D	Dp3
shúile	shúile	súil-N	Ncfpc
lán	lán	lán-A	Aq--pg
de	de	de-S	Sp
dhóchas	dhóchas	dóchas-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liom	liom	le-P	Pr1-s
dul	dul	téigh-N	Nv
ann	ann	ann-R	Rl
le	le	le-S	Sp
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
Máire	Máire	Máire-N	Npfsc
Rua	Rua	Rua-N	Npmsg|Npmsc
ag	ag	ag-S	Sp
ní	ní	nigh-N	Nv
soithí	soithí	soitheach-N	Ncmpg
an	an	an-T	Td-s
bhricfeasta	bhricfeasta	bricfeasta-N	Ncmsg
,	,	,-F	Fi
í	í	í-P	Pp3fs
gnóthach	gnóthach	gnóthach-A	Aqp
,	,	,-F	Fi
mar	mar	mar-C	Cs
ba	ba	is-W	Wsri
ghnách	ghnách	gnách-A	Aqp
.	.	.-F	Fe
'	'	'-F	Fa
Ní	Ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
tusa	tusa	tú-P	Pp2-s-e
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
go	go	go-S	Sp
Coill	Coill	Coill-N	Npmsc
na	na	na-T	Td-p
Baice	Baice	Baice-N	Npmsc
inniu	inniu	inniu-R	Rt
,	,	,-F	Fi
a	a	a-U	Uv
mhic	mhic	mac-N	Ncmsv
ó	ó	ó-C	Cs
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
,	,	,-F	Fi
gan	gan	gan-S	Sp
tiontú	tiontú	tiontaigh-N	Nv
ón	ón	ó-S	Spa-s
doirteal	doirteal	doirteal-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Bain	Bain	bain-V	Vmm-2s|Npmsc
an	an	an-T	Td-s
scoil	scoil	scoil-N	Ncfsc
amach	amach	amach-R	Rd
anois	anois	anois-R	Rt
chomh	chomh	chomh-R	Ri
tiubh	tiubh	tiubh-A	Aqp
géar	géar	géar-A	Aqp
agus	agus	agus-C	Cc
a	a	a-Q	Q-r
thig	thig	tar-V	Vmip
leat	leat	le-P	Pr2-s
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
a	a	a-U	Uv
Mháthair	Mháthair	máthair-N	Ncfsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Dónall	Dónall	Dónall-N	Npmsc
,	,	,-F	Fi
agus	agus	agus-C	Cc
na	na	na-T	Td-p
deora	deora	deoir-N	Ncfpc
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
leis	leis	le-P	Pr3ms
dá	dá	de-S	Spp-s
ainneoin	ainneoin	ainneoin-C	Cs
féin	féin	féin-P	Px
,	,	,-F	Fi
'	'	'-F	Fa
beidh	beidh	bí-V	Vmif
an	an	an-T	Td-s
Traenálaí	Traenálaí	traenálaí-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Dá	Dá	dá-C	Cs
bhfeicfeadh	bhfeicfeadh	feic-V	Vmc
sé	sé	sé-P	Pp3msn
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
marcaíocht	marcaíocht	marcaigh-N	Nv
!	!	!-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Gasúr	Gasúr	gasúr-N	Ncmsc
dhá	dhá	dó-M	Mc
bhliain	bhliain	bliain-N	Ncfsc
déag	déag	déag-N	Ns-s
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
mar	mar	mar-C	Cs
sin	sin	sin-W	W
!	!	!-F	Fe
Caithfidh	Caithfidh	caith-V	Vmif
tú	tú	tú-P	Pp2-s
suim	suim	suim-N	Ncfsc
a	a	a-U	U
chur	chur	cuir-N	Nv
sna	sna	i-S	Spa-p
leabhair	leabhair	leabhar-N	Ncmpc
scoile	scoile	scoil-N	Ncfsg
ar	ar	ar-S	Sp
dtús	dtús	tús-N	Ncmsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
is	is	is-W	Wp-i
féidir	féidir	féidir-N	Ns-s
leat	leat	le-P	Pr2-s
smaoineamh	smaoineamh	smaoinigh-N	Nv
ar	ar	ar-S	Sp
na	na	na-T	Td-p
capaill	capaill	capall-N	Ncmpc
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
aghaidh	aghaidh	aghaidh-N	Ncfsc
leat	leat	le-P	Pr2-s
chun	chun	chun-S	Sp
na	na	na-T	Tdfsg
scoile	scoile	scoil-N	Ncfsg
!	!	!-F	Fe
'	'	'-F	Fa
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
shocraíodh	shocraíodh	socraigh-V	Vmih
Máire	Máire	Máire-N	Npfsc
Rua	Rua	Rua-N	Npmsc
a	a	a-D	Dp3
hintinn	hintinn	intinn-N	Ncfsc
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
deacair	deacair	deacair-A	Aqp
a	a	a-D	Dp3
hathrú	hathrú	athrú-N	Ncmsc
.	.	.-F	Fe
Thriomaigh	Thriomaigh	triomaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
lámha	lámha	lámh-N	Ncfpc
agus	agus	agus-C	Cc
amach	amach	amach-R	Rd
léi	léi	le-P	Pr3fs
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
líne	líne	líne-N	Ncfsc
éadaí	éadaí	éadach-N	Ncmpc|Ncmpg
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
Dónall	Dónall	Dónall-N	Npmsc
liobar	liobar	liobar-N	Ncmsc
air	air	ar-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
Tharraing	Tharraing	tarraing-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
mála	mála	mála-N	Ncmsc
leabhar	leabhar	leabhar-N	Ncmsc
go	go	go-U	Ua
tromchroíoch	tromchroíoch	tromchroíoch-A	Aqp
aniar	aniar	aniar-A	Aqp
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
ghualainn	ghualainn	gualainn-N	Ncfsc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
amach	amach	amach-R	Rd
.	.	.-F	Fe
Shiúil	Shiúil	siúil-V	Vmis
sé	sé	sé-P	Pp3msn
leis	leis	le-P	Pr3ms
go	go	go-U	Ua
malltriallach	malltriallach	malltriallach-A	Aqp
bóthar	bóthar	bóthar-N	Ncmsc
theach	theach	teach-N	Ncmsc
na	na	na-T	Tdfsg
scoile	scoile	scoil-N	Ncfsg
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
ndóigh	ndóigh	dóigh-N	Ncfsc
,	,	,-F	Fi
ní	ní	ní-W	Wp-in|Nv|Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
scoil	scoil	scoil-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Dónall	Dónall	Dónall-N	Npmsc
ag	ag	ag-S	Sp
smaoineamh	smaoineamh	smaoinigh-N	Nv
ach	ach	ach-C	Cs
ar	ar	is-W	Wpdi|Wpsi|Wssi
thrialacha	thrialacha	triail-N	Ncfpc
capall	capall	capall-N	Ncmpg|Ncmsc
Choill	Choill	Coill-N	Npfsg
na	na	na-T	Td-p
Baice	Baice	Baice-N	Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
croí	croí	croí-N	Ncmsc
Dhónaill	Dhónaill	Dónall-N	Npm-g
Óig	Óig	óg-A	Aq-msg
sna	sna	i-S	Spa-p
capaill	capaill	capall-N	Ncmpc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
sa	sa	i-S	Spa-s
ghlóir	ghlóir	glóir-N	Ncfsc
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
a	a	a-Q	Q-r
thug	thug	tabhair-V	Vmis
a	a	a-D	Dp3
athair	athair	athair-N	Ncmsc
,	,	,-F	Fi
Sean	Sean	Sean-N	Npmsc
‑	‑	‑-F	Fb
Dónall	Dónall	Dónall-N	Npmsc
,	,	,-F	Fi
agus	agus	agus-C	Cc
a	a	a-D	Dp3
uncail	uncail	uncail-N	Ncmsc
,	,	,-F	Fi
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
,	,	,-F	Fi
chuig	chuig	chuig-S	Sp
na	na	na-T	Td-p
rásaí	rásaí	rás-N	Ncmpc
é	é	é-P	Pp3ms
den	den	de-S	Spa-s
chéad	chéad	céad-M	Mo
uair	uair	uair-N	Ncfsc
.	.	.-F	Fe
Ba	Ba	is-U	U
mhó	mhó	mór-A	Aqc
arís	arís	arís-R	Rg
a	a	a-D	Dp3
lúcháir	lúcháir	lúcháir-N	Ncfsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
fuair	fuair	faigh-V	Vmis
sé	sé	sé-P	Pp3msn
Beití	Beití	beití-N	Ncmsc
,	,	,-F	Fi
a	a	a-U	Uv
phónaí	phónaí	pónaí-N	Ncmpv|Ncmsv
féin	féin	féin-P	Px
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
claí	claí	claí-N	Ncmsc
ná	ná	ná-C	Cs|Cc
sceach	sceach	sceach-N	Ncfpg|Ncfsc|Ncfpg
ó	ó	ó-S	Sp
Dhroichead	Dhroichead	droichead-N	Ncmsc
Thuama	Thuama	Tuama-N	Npfsg
go	go	go-S	Sp
Port	Port	port-N	Ncmsc
Chluain	Chluain	cluain-N	Ncfsc
Eoghain	Eoghain	Eoghan-N	Npmsg|Npfsg|Npm-g
nár	nár	nár-W	Wsrin|Wsdin|Wssin|Qn-s|Qnrs
léim	léim	léim-V	Vmip1s|Ncfsc|Vmip1s-n|Nv|Ncfsc|Nv|Vmis|Vmis---n
Dónall	Dónall	Dónall-N	Npmsc
lena	lena	le-S	Spp-s
phónaí	phónaí	pónaí-N	Ncmsc
liath	liath	liath-A	Aq-msc|Aq-msv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
ina	ina	i-S	Spp-s
mharcach	mharcach	marcach-N	Ncmsc
mór	mór	mór-A	Aq-msc
tráth	tráth	tráth-N	Ncmsc
den	den	de-S	Spa-s
saol	saol	saol-N	Ncmsc
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s|Spp-p
laoch	laoch	laoch-N	Ncmsc
ag	ag	ag-S	Sp
Dónall	Dónall	Dónall-N	Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
ag	ag	ag-S	Sp
Dónall	Dónall	Dónall-N	Npmsc
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
chuig	chuig	chuig-S	Sp
na	na	na-T	Td-p
trialacha	trialacha	triail-N	Ncfpc
capall	capall	capall-N	Ncmpg|Ncmsc
i	i	i-S	Sp
gCoill	gCoill	coll-N	Ncfsc|Ncmpc
na	na	na-T	Td-p
Baice	Baice	Baice-N	Npmsc
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
sin	sin	sin-D	Dd
agus	agus	agus-C	Cc
thabharfadh	thabharfadh	tabhair-V	Vmc
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
dhá	dhá	dó-M	Mc
shúil	shúil	súil-N	Ncfsc
ach	ach	ach-C	Cs
a	a	a-U	U
bheith	bheith	bí-N	Nv
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Mheas	Mheas	meas-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-Q	Q
dtiocfadh	dtiocfadh	tar-V	Vmc
leis	leis	le-P	Pr3ms
a	a	a-U	U
thaispeáint	thaispeáint	taispeáin-N	Nv
don	don	do-S	Spa-s
Traenálaí	Traenálaí	traenálaí-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
i	i	i-S	Sp
gCoill	gCoill	coll-N	Ncfsc|Ncmpc
na	na	na-T	Td-p
Baice	Baice	Baice-N	Npmsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
ábalta	ábalta	ábalta-A	Aqp
capall	capall	capall-N	Ncmsc
a	a	a-U	U
láimhseáil	láimhseáil	láimhseáil-N	Nv
agus	agus	agus-C	Cc
go	go	go-Q	Q
ndéanfadh	ndéanfadh	déan-V	Vmc
sé	sé	sé-P	Pp3msn
marcach	marcach	marcach-N	Ncmsc
ar	ar	ar-S	Sp
dóigh	dóigh	dóigh-N	Ncfsc
.	.	.-F	Fe
Maidin	Maidin	maidin-N	Ncfsc
álainn	álainn	álainn-A	Aq-fsc
ghrianmhar	ghrianmhar	grianmhar-A	Aq-fsc|Aq-fsv
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
agus	agus	agus-C	Cc
Dónall	Dónall	Dónall-N	Npmsc
Óg	Óg	óg-A	Aq-msc
ag	ag	ag-S	Sp
triall	triall	triall-N	Nv
go	go	go-U	Ua
drogallach	drogallach	drogallach-A	Aqp
ar	ar	ar-S	Sp
an	an	an-T	Td-s
scoil	scoil	scoil-N	Ncfsc
.	.	.-F	Fe
Nár	Nár	is-W	Wssin
bhreá	bhreá	breá-A	Aqp
leis	leis	le-P	Pr3ms
dul	dul	téigh-N	Nv
chuig	chuig	chuig-S	Sp
trialacha	trialacha	triail-N	Ncfpc
capall	capall	capall-N	Ncmpg
lá	lá	lá-N	Ncmsc
mar	mar	mar-C	Cs|Sp
é	é	é-P	Pp3ms
!	!	!-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
uaidh	uaidh	ó-P	Pr3ms
teach	teach	teach-N	Ncmsc
Shéarlaí	Shéarlaí	Shéarlaí-N	Npmsc
ba	ba	is-U	U
mhó	mhó	mór-A	Aqc
fós	fós	fós-R	Rg
an	an	an-T	Td-s
fonn	fonn	fonn-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
air	air	ar-P	Pr3ms
casadh	casadh	casadh-N	Ncmsc
ar	ar	ar-S	Sp
dheis	dheis	deis-N	Ncfsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
gcrosbhealach	gcrosbhealach	crosbhealach-N	Ncmsc
in	in	i-S	Sp
áit	áit	áit-N	Ncfsc
dul	dul	dul-N	Ncmsc
díreach	díreach	díreach-A	Aq-msc
ar	ar	ar-S	Sp
aghaidh	aghaidh	aghaidh-N	Ncfsc
i	i	i-S	Sp
dtreo	dtreo	treo-N	Ncmsc
na	na	na-T	Tdfsg
scoile	scoile	scoil-N	Ncfsg
.	.	.-F	Fe
Rinne	Rinne	déan-V	Vmis
sé	sé	sé-P	Pp3msn
gach	gach	gach-D	Dq
iarracht	iarracht	iarracht-N	Ncfsc
an	an	an-T	Td-s
smaoineamh	smaoineamh	smaoineamh-N	Ncmsc
a	a	a-Q	Q-r
ruaigeadh	ruaigeadh	ruaig-V	Vmih
as	as	as-P	Pr3ms
a	a	a-D	Dp3
cheann	cheann	ceann-N	Ncmsc
mar	mar	mar-C	Cs
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
aige	aige	ag-P	Pr3ms
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
a	a	a-D	Dp3
mháthair	mháthair	máthair-N	Ncfsc
ar	ar	is-W	Wssi|Wpdi|Wpsi
mire	mire	mear-A	Aqc
leis	leis	le-P	Pr3ms
mura	mura	mura-C	Cs
rachadh	rachadh	téigh-V	Vmc
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
scoil	scoil	scoil-N	Ncfsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
faoin	faoin	faoi-S	Spa-s
am	am	am-N	Ncmsc
ar	ar	ar-Q	Q-is
tháinig	tháinig	tar-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
fhad	fhad	fad-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
chrosbhealach	chrosbhealach	crosbhealach-N	Ncmsc
bhí	bhí	bí-V	Vmis
cinneadh	cinneadh	cinn-V	Vmis0
déanta	déanta	déan-A	Av
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Thiontaigh	Thiontaigh	tiontaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
dheis	dheis	deis-N	Ncfsc
,	,	,-F	Fi
chuir	chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
mhála	mhála	mála-N	Ncmsc
scoile	scoile	scoil-N	Ncfsg
i	i	i-S	Sp
bhfolach	bhfolach	folach-N	Ncmsc
i	i	i-S	Sp
gcúl	gcúl	cúl-N	Ncmsc
claí	claí	claí-N	Ncmsg
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmis
sé	sé	sé-P	Pp3msn
de	de	de-S	Sp
rith	rith	rith-N	Ncmsc
,	,	,-F	Fi
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
giorria	giorria	giorria-N	Ncmsc
ann	ann	i-P	Pr3ms
,	,	,-F	Fi
ag	ag	ag-S	Sp
tarraingt	tarraingt	tarraing-N	Nv
ar	ar	ar-S	Sp
stábla	stábla	stábla-N	Ncmsc
a	a	a-D	Dp3
uncail	uncail	uncail-N	Ncmsc
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Níl	Níl	bí-V	Vmip---n
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
ar	ar	ar-S	Sp
scoil	scoil	scoil-N	Ncfsc
inniu	inniu	inniu-R	Rt
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
leis	leis	le-P	Pr3ms
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
Dónall	Dónall	Dónall-N	Npmsc
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
air	air	ar-P	Pr3ms
.	.	.-F	Fe
'	'	'-F	Fa
Níl	Níl	bí-V	Vmip---n
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Dónall	Dónall	Dónall-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Deir	Deir	abair-V	Vmip
Mamaí	Mamaí	mama-N	Ncfsc|Ncmpc
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
cead	cead	cead-N	Ncmsc
agam	agam	ag-P	Pr1-s
dul	dul	dul-N	Ncmsc
chuig	chuig	chuig-S	Sp
na	na	na-T	Td-p
trialacha	trialacha	triail-N	Ncfpc
capall	capall	capall-N	Ncmpg|Ncmsc
leatsa	leatsa	le-P	Pr2-s-e
.	.	.-F	Fe
'	'	'-F	Fa
Níor	Níor	is-W	Ws-in
mhaith	mhaith	maith-A	Aqp
le	le	le-S	Sp
Dónall	Dónall	Dónall-N	Npmsc
bréag	bréag	bréag-N	Ncfpg
a	a	a-U	U
insint	insint	inis-N	Nv
ach	ach	ach-C	Cs
cad	cad	cad-W	W--q
eile	eile	eile-D	Dd
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhéadfadh	fhéadfadh	féad-V	Vmc
sé	sé	sé-P	Pp3msn
a	a	a-U	U
rá	rá	abair-N	Nv
le	le	le-S	Sp
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
?	?	?-F	Fq
Dá	Dá	de-S	Spp-s
n	n	n-X	Xl
‑	‑	‑-F	Fb
inseodh	inseodh	inis-V	Vmc
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
fhírinne	fhírinne	fírinne-N	Ncfsc
dó	dó	do-P	Pr3ms
chuirfeadh	chuirfeadh	cuir-V	Vmc
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
láithreach	láithreach	láithreach-A	Aq-msc
bonn	bonn	bonn-N	Ncmpg|Ncmsc
chun	chun	chun-S	Sp
na	na	na-T	Tdfsg
scoile	scoile	scoil-N	Ncfsg
é	é	é-P	Pp3ms
.	.	.-F	Fe
'	'	'-F	Fa
Maith	Maith	Maith-N	Npmsc
go leor	go leor	go_leor-A	Aq
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Tú	Tú	tú-P	Pp2-s
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
mé	mé	mé-P	Pp1-s
féin	féin	féin-P	Px
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
.	.	.-F	Fe
Seo	Seo	seo-W	W
linn	linn	le-P	Pr1-p
go	go	go-S	Sp
Coill	Coill	Coill-N	Npmsc
na	na	na-T	Td-p
Baice	Baice	Baice-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
Léim	Léim	léim-V	Vmip1s|Vmis
Dónall	Dónall	Dónall-N	Npmsc
ar	ar	ar-S	Sp
dhroim	dhroim	droim-N	Ncmsc
an	an	an-T	Td-s
chapaill	chapaill	capall-N	Ncmsg
dhuibh	dhuibh	dubh-A	Aq-msg
a	a	a-D	Dp3
fhad	fhad	fad-N	Ncmsc
is	is	agus-W	Wp-i|Wpri|Cc
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fheistigh	fheistigh	feistigh-V	Vmis
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
an	an	an-T	Td-s
capall	capall	capall-N	Ncmsc
bán	bán	bán-A	Aq-msc
dó	dó	do-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
nach	nach	is-W	Wpsin|Wpdin
é	é	é-P	Pp3ms
Dónall	Dónall	Dónall-N	Npmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
bródúil	bródúil	bródúil-A	Aqp
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
marcaíocht	marcaíocht	marcaigh-N	Nv
feadh	feadh	feadh-N	Ncmsc
bhruach	bhruach	bruach-N	Ncmsc
na	na	na-T	Td-p
Banna	Banna	banna-N	Ncmsg
lena	lena	le-S	Spp-s
uncail	uncail	uncail-N	Ncmsc
agus	agus	agus-C	Cc
aer	aer	aer-N	Ncmsc
fionnuar	fionnuar	fionnuar-A	Aq-msc
na	na	na-T	Tdfsg
maidine	maidine	maidin-N	Ncfsg
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
spriolladh	spriolladh	spriolladh-N	Ncmpg
iontu	iontu	i-P	Pr3-p
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
na	na	na-T	Td-p
trialacha	trialacha	triail-N	Ncfpc
capall	capall	capall-N	Ncmpg|Ncmsc
ar	ar	ar-S	Sp
bhomaite	bhomaite	bomaite-N	Ncmsc
a	a	a-U	Um
deich	deich	deich-M	Mc
.	.	.-F	Fe
Cliathrás	Cliathrás	cliathrás-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
ar	ar	ar-S	Sp
dtús	dtús	tús-N	Ncmsc
.	.	.-F	Fe
Sa	Sa	i-S	Spa-s
rás	rás	rás-N	Ncmsc
seo	seo	seo-D	Dd
bheadh	bheadh	bí-V	Vmc
ar	ar	ar-S	Sp
na	na	na-T	Td-p
capaill	capaill	capall-N	Ncmpc
rith	rith	rith-V	Vmis
agus	agus	agus-C	Cc
léim	léim	léim-V	Vmm-2s
thar	thar	thar-S	Sp
chlaíocha	chlaíocha	claí-N	Ncmpc
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
é	é	é-P	Pp3ms
seo	seo	seo-P	Pd
an	an	an-T	Td-s
seans	seans	seans-N	Ncmsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
Dónall	Dónall	Dónall-N	Npmsc
ag	ag	ag-S	Sp
súil	súil	súil-N	Nv-----n
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
na	na	na-T	Td-p
stócaigh	stócaigh	stócach-N	Ncmpc
eile	eile	eile-D	Dd
níos	níos	níos-U	Uc
sine	sine	sean-A	Aqc
ná	ná	ná-C	Cs|Cc
é	é	é-P	Pp3ms
,	,	,-F	Fi
ach	ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
Dónall	Dónall	Dónall-N	Npmsc
Óg	Óg	óg-A	Aq-msc
iontach	iontach	iontach-R	Ri
maith	maith	maith-A	Aqp
i mbun	i mbun	i_mbun-S	Spc
capaill	capaill	capall-N	Ncmsg
.	.	.-F	Fe
Bhuaigh	Bhuaigh	Buaigh-N	Npfsg
sé	sé	is-W	Wp-i-3
an	an	an-T	Td-s
cliathrás	cliathrás	cliathrás-N	Ncmsc
gan	gan	gan-S	Sp
mórán	mórán	mórán-N	Ncmsc
dua	dua	dua-N	Ncmsg
.	.	.-F	Fe
Tamall	Tamall	tamall-N	Ncmsc
i ndiaidh	i ndiaidh	i_ndiaidh-S	Spc
an	an	an-T	Td-s
rása	rása	rás-N	Ncmsg
bhí	bhí	bí-V	Vmis
Dónall	Dónall	Dónall-N	Npmsc
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
a	a	a-U	Ud|Dp3
scíthe	scíthe	scíth-A	Aqc
ar	ar	ar-S	Sp
chlaí	chlaí	claí-N	Ncmsc
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
baint	baint	bain-N	Nv
lán	lán	lán-N	Ncmsc
na	na	na-T	Td-p
súl	súl	súil-N	Ncfpg
as	as	as-S	Sp
an	an	an-T	Td-s
radharc	radharc	radharc-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
os	os	os-N	Ncmsc|Sp
a	a	a-Q	Q-r
chomhair	chomhair	comhair-V	Vmis
amach	amach	amach-R	Rd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
capaill	capaill	capall-N	Ncmpc
de	de	de-S	Sp
gach	gach	gach-D	Dq
sórt	sórt	sórt-N	Ncmsc
ann	ann	i-R	Rl|Pr3ms
as	as	as-S	Sp
áiteanna	áiteanna	áit-N	Ncfpc
ar fud	ar fud	ar_fud-S	Spc
na	na	na-T	Tdfsg
tíre	tíre	tír-N	Ncfsg
.	.	.-F	Fe
Cad	Cad	cad-W	W--q
é	é	é-P	Pp3ms
a	a	a-Q	Q-r
chí	chí	chí-V	Vmip
sé	sé	sé-P	Pp3msn
ansin	ansin	ansin-R	Rt|Rl
ach	ach	ach-S	Sp
Traenálaí	Traenálaí	traenálaí-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
Choill	Choill	Coill-N	Npfsg
na	na	na-T	Td-p
Baice	Baice	Baice-N	Npmsc
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
le	le	le-S	Sp
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-V	Vmis
siad	siad	siad-P	Pp3-pn
beirt	beirt	beirt-N	Ncfsc
ar	ar	ar-S	Sp
Dhónall	Dhónall	Dónall-N	Npmsc
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
siad	siad	siad-P	Pp3-pn
a	a	a-U	U
shiúl	shiúl	siúil-N	Nv
ina	ina	i-S	Spp-s
threo	threo	treo-N	Ncmsc
.	.	.-F	Fe
Léim	Léim	léim-V	Vmip1s|Vmis
Dónall	Dónall	Dónall-N	Npmsc
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
agus	agus	agus-C	Cc
bhain	bhain	bain-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
chaipín	chaipín	caipín-N	Ncmsc
de	de	de-P	Pr3ms
.	.	.-F	Fe
'	'	'-F	Fa
Bulaí	Bulaí	bulaí-N	Ncmsc
gasúir	gasúir	gasúr-N	Ncmsg|Ncmpc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Traenálaí	Traenálaí	traenálaí-N	Ncmsc
mór	mór	mór-A	Aq-msc
,	,	,-F	Fi
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
bualadh	bualadh	buail-N	Nv
boise	boise	bos-N	Ncfsg
sa	sa	i-S	Spa-s
ghualainn	ghualainn	gualainn-N	Ncfsc
ar	ar	ar-S	Sp
Dhónall	Dhónall	Dónall-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Is	Is	is-W	Wp-i
ábhar	ábhar	ábhar-N	Ncmsc
maith	maith	maith-A	Aq-msc
marcaigh	marcaigh	marcach-N	Ncmpc|Ncmsg
tú	tú	tú-P	Pp2-s
.	.	.-F	Fe
Níl	Níl	bí-V	Vmip---n
dabht	dabht	dabht-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
faoi	faoi	faoi-S	Sp
sin	sin	sin-P	Pd
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
post	post	post-N	Ncmsc
anseo	anseo	anseo-R	Rl
duit	duit	do-P	Pr2-s
sna	sna	i-S	Spa-p
stáblaí	stáblaí	stábla-N	Ncmpc
más	más	má-C	Csw
maith	maith	maith-A	Aqp
leat	leat	le-P	Pr2-s
é	é	é-P	Pp3ms
.	.	.-F	Fe
Beidh	Beidh	bí-V	Vmif
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
obair	obair	obair-N	Nv-----n
trí	trí	trí-M	Mc|Sp
thráthnóna	thráthnóna	tráthnóna-N	Ncmsc
sa	sa	i-S	Spa-s
tseachtain	tseachtain	seachtain-N	Ncfsc
ar	ar	ar-S	Sp
sheacht	sheacht	seacht-N	Ncmsc
scillinge	scillinge	scilling-N	Ncfsg
.	.	.-F	Fe
'	'	'-F	Fa
Las	Las	las-V	Vmis|Vmm-2s
aghaidh	aghaidh	aghaidh-N	Ncfsc
Dhónaill	Dhónaill	Dónall-N	Npfsg|Npm-g
go	go	go-S	Sp
barr	barr	barr-N	Ncmsc
na	na	na-T	Td-p
gcluas	gcluas	cluas-N	Ncfpg
.	.	.-F	Fe
'	'	'-F	Fa
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
maith	maith	maith-N	Ncfsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
dhuine	dhuine	duine-N	Ncmsv
uasail	uasail	uasal-A	Aq-msv|Aq-msg
!	!	!-F	Fe
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
céad	céad	céad-N	Ncmsc|Mc
maith	maith	maith-N	Ncfsc
agat	agat	ag-P	Pr2-s
!	!	!-F	Fe
'	'	'-F	Fa
Nuair	Nuair	nuair-C	Cs
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmm-2s
an	an	an-T	Td-s
Traenálaí	Traenálaí	traenálaí-N	Ncmsc
leis	leis	le-P	Pr3ms
rug	rug	beir-V	Vmis
Dónall	Dónall	Dónall-N	Npmsc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
uncail	uncail	uncail-N	Ncmsc
greim	greim	greim-N	Ncmsc
láimhe	láimhe	lámh-N	Ncfsg
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
agus	agus	agus-C	Cc
chroith	chroith	croith-V	Vmis
go	go	go-U	Ua
croíúil	croíúil	croíúil-A	Aqp
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
tháinig	tháinig	tar-V	Vmis
smúit	smúit	smúit-N	Ncfsc
ar	ar	ar-S	Sp
ghnúis	ghnúis	gnúis-N	Ncfsc
Dhónaill	Dhónaill	Dónall-N	Npfsg|Npm-g
.	.	.-F	Fe
'	'	'-F	Fa
Ach	Ach	ach-C	Cs
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
a	a	a-Q	Q-r
déarfaidh	déarfaidh	abair-V	Vmif
mo	mo	mo-D	Dp1-s
mháthair	mháthair	máthair-N	Ncfsc
?	?	?-F	Fq
'	'	'-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
agus	agus	agus-C	Cc
imní	imní	imní-N	Ncfsc
ina	ina	i-S	Spp-s
ghlór	ghlór	glór-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Ná	Ná	ná-Q	Qnm
bí	bí	bí-V	Vmm-2s-n
buartha	buartha	buair-A	Av
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
gáire	gáire	gáir-N	Ncfsg|Ncmsg|Nv--g
.	.	.-F	Fe
'	'	'-F	Fa
Pléifidh	Pléifidh	pléigh-V	Vmif
mise	mise	mé-P	Pp1-s-e
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
le	le	le-S	Sp
do	do	do-D	Dp2-s
mháthair	mháthair	máthair-N	Ncfsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
í	í	í-P	Pp3fs
a	a	a-Q	Q-r
bheas	bheas	bí-V	Vmif---r
sásta	sásta	sásta-A	Aqc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bheas	bheas	bí-V	Vmif---r
tú	tú	tú-P	Pp2-s
i	i	i-S	Sp
do	do	do-D	Dp2-s
mharcach	mharcach	marcach-N	Ncmsc
déanta	déanta	déan-A	Aqp|Av
agus	agus	agus-C	Cc
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
saothrú	saothrú	saothraigh-N	Nv
airgid	airgid	airgead-N	Ncmsg
di	di	do-P	Pr3fs
as	as	as-S	Sp
seo	seo	seo-P	Pd
amach	amach	amach-R	Rd
.	.	.-F	Fe
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
Dónall	Dónall	Dónall-N	Npmsc
Óg	Óg	óg-A	Aq-msc
amuigh	amuigh	amuigh-R	Rl
ag	ag	ag-S	Sp
an	an	an-T	Td-s
fhuinneog	fhuinneog	fuinneog-N	Ncfsc
,	,	,-F	Fi
ag	ag	ag-S	Sp
cúléisteacht	cúléisteacht	cúléist-N	Nv
lena	lena	le-S	Spp-s
mháthair	mháthair	máthair-N	Ncfsc
ag	ag	ag-S	Sp
sceamhlaigh	sceamhlaigh	sceamhlach-N	Ncmpc
istigh	istigh	istigh-R	Rl
sa	sa	i-S	Spa-s
chistin	chistin	cistin-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
rásaí	rásaí	rásaí-N	Ncmpc|Ncmsc
capall	capall	capall-N	Ncmpg|Ncmsc
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
róchontúirteach	róchontúirteach	contúirteach-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Máire	Máire	Máire-N	Npfsc
Rua	Rua	Rua-N	Npmsg|Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Dia	Dia	dia-N	Ncmsc
ár	ár	ár-N	Ncmsc|Dp1-p
sábháil	sábháil	sábháil-N	Nv|Ncfsc
!	!	!-F	Fe
Léimeann	Léimeann	léim-V	Vmip
mo	mo	mo-D	Dp1-s
chroí	chroí	croí-N	Ncmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
thiteann	thiteann	tit-V	Vmip
na	na	na-T	Td-p
marcaigh	marcaigh	marcach-N	Ncmpc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
capaill	capaill	capall-N	Ncmpc
ina	ina	i-S	Spp-p|Spp-s
mullach	mullach	mullach-N	Ncmsc
.	.	.-F	Fe
Nach	Nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
seo	seo	seo-P	Pd|Dd
againne	againne	ag-P	Pr1-p-e
sa	sa	i-S	Spa-s
bhaile	bhaile	baile-N	Ncmsc
sé	sé	sé-M	Mc
mhí	mhí	mí-N	Ncfsc|Ncmsc
le	le	le-S	Sp
cnámha	cnámha	cnámh-N	Ncfpc
briste	briste	bris-A	Aqp|Av
tá	tá	bí-V	Vmip
fiche	fiche	fiche-N	Ncmsc|Mc
bliain	bliain	bliain-N	Ncfsc
ó	ó	ó-S	Sp
shin	shin	sin-P	Pd
!	!	!-F	Fe
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
Sean	Sean	Sean-N	Npmsc
‑	‑	‑-F	Fb
Dónall	Dónall	Dónall-N	Npmsc
ina	ina	i-S	Spp-s
shuí	shuí	suí-N	Ncmsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
tine	tine	tine-N	Ncfsc
,	,	,-F	Fi
páipéar	páipéar	páipéar-N	Ncmsc
nuachta	nuachta	nuacht-N	Ncfsg
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
ghlúin	ghlúin	glúin-N	Ncfsc
aige	aige	ag-P	Pr3ms
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
scrúdú	scrúdú	scrúdaigh-N	Nv
leathanach	leathanach	leathanach-N	Ncmpg
na	na	na-T	Td-p
gcapall	gcapall	capall-N	Ncmpg
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
minic	minic	minic-A	Aqp
a	a	a-Q	Q-r
chuireadh	chuireadh	cuir-V	Vmih
sé	sé	sé-P	Pp3msn
in éadan	in éadan	in_éadan-S	Spc
bhean	bhean	bean-N	Ncfsc
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
chonacthas	chonacthas	feic-V	Vmis0
dó	dó	do-P	Pr3ms
gur	gur	is-W	Wsdi|Wpdi
cheart	cheart	ceart-A	Aqp
dó	dó	do-P	Pr3ms
labhairt	labhairt	labhairt-N	Ncfsc
an	an	an-T	Td-s
iarraidh	iarraidh	iarraidh-N	Ncfsc
seo	seo	seo-D	Dd
.	.	.-F	Fe
Bhain	Bhain	bain-V	Vmis
sé	sé	sé-P	Pp3msn
na	na	na-T	Td-p
gloiní	gloiní	gloine-N	Ncfpc
dá	dá	de-S	Spp-s
shrón	shrón	srón-N	Ncfsc
agus	agus	agus-C	Cc
labhair	labhair	labhair-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-U	Ua
ciúin	ciúin	ciúin-A	Aqp
séimh	séimh	séimh-A	Aqp
.	.	.-F	Fe
'	'	'-F	Fa
A	A	a-U	Uv
thaisce	thaisce	taisce-N	Ncfsv
,	,	,-F	Fi
is	is	is-U	U
iomaí	iomaí	iomaí-A	Aqc
sin	sin	sin-P	Pd|W|Dd
duine	duine	duine-N	Ncmsc
a	a	a-Q	Q-r
bhíonn	bhíonn	bí-V	Vmig
páirteach	páirteach	páirteach-A	Aqp
i	i	i-S	Sp
rásaí	rásaí	rás-N	Ncmsc|Ncmpc
capall	capall	capall-N	Ncmpg
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
níor	níor	níor-Q	Qn-s
gortaíodh	gortaíodh	gortaigh-V	Vmis0--n
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
chomh	chomh	chomh-R	Ri
holc	holc	olc-A	Aqp
sin	sin	sin-P	Pd|W|Dd
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
sna	sna	i-S	Spa-p
céadta	céadta	céad-N	Ncmpc
rás	rás	rás-N	Ncmsc
i rith	i rith	i_rith-S	Spc
a	a	a-D	Dp3
shaoil	shaoil	saol-N	Ncmsg
.	.	.-F	Fe
Amharc	Amharc	amharc-V	Vmm-2s
t	t	t-X	Xl
‑	‑	‑-F	Fb
airgead	airgead	airgead-N	Ncmsc
atá	atá	bí-V	Vmip---r
déanta	déanta	déan-A	Av
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
saol	saol	saol-N	Ncmsc
an	an	an-T	Td-s
mhadaidh	mhadaidh	mhadaidh-N	Ncfsc
bháin	bháin	bán-N	Ncmsg
anois	anois	anois-R	Rt
aige	aige	ag-P	Pr3ms
,	,	,-F	Fi
feirm	feirm	feirm-N	Ncfsc
bheag	bheag	beag-A	Aq-fsc
sheascair	sheascair	seascair-A	Aq-fsc
agus	agus	agus-C	Cc
stáblaí	stáblaí	stábla-N	Ncmpg|Ncmpc|Ncmpg
aige	aige	ag-P	Pr3ms
i	i	i-S	Sp
mBaile	mBaile	Baile-N	Npmsc
an	an	an-T	Td-s
Easa	Easa	eas-N	Ncmsg
.	.	.-F	Fe
'	'	'-F	Fa
Chroith	Chroith	croith-V	Vmis
Máire	Máire	Máire-N	Npfsc
a	a	a-D	Dp3
ceann	ceann	ceann-N	Ncmsc
agus	agus	agus-C	Cc
chaith	chaith	caith-V	Vmis
an	an	an-T	Td-s
cheirt	cheirt	ceirt-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ina	ina	i-S	Spp-s|Spp-p
lámh	lámh	lámh-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
tábla	tábla	tábla-N	Ncfsc|Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
malrach	malrach	malrach-N	Ncmsc
sin	sin	sin-D	Dd
againne	againne	ag-P	Pr1-p-e
ró	ró	ró-N	Ncmsc
‑	‑	‑-F	Fb
óg	óg	óg-N	Ncmsc
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
scor	scor	scor-N	Ncmsc
ar	ar	is-W	Wsdq|Ws-q|Wssi|Wpdi|Wpsi
bith	bith	bith-N	Ncmsc|Ns-s
,	,	,-F	Fi
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
fán	fán	faoi-S	Spa-s
scoil	scoil	scoil-N	Ncfsc
?	?	?-F	Fq
Nach	Nach	nach-Q	Qnq
bhfuil	bhfuil	bí-V	Vmip---d
an	an	an-T	Td-s
máistir	máistir	máistir-N	Ncmsc
á	á	do-S	Spo-s
rá	rá	abair-N	Nv
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
seans	seans	seans-N	Ncmsc
aige	aige	ag-P	Pr3ms
scoláireacht	scoláireacht	scoláireacht-N	Ncfsc
a	a	a-U	U
fháil	fháil	faigh-N	Nv
go dtí	go dtí	go_dtí-S	Spc
Coláiste	Coláiste	coláiste-N	Ncmsc
Choilm	Choilm	colm-N	Ncmsg
i	i	i-S	Sp
nDoire	nDoire	Doire-N	Npfsc|Npmsc
ach	ach	ach-S	Sp
staidéar	staidéar	staidéar-N	Ncmsc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
?	?	?-F	Fq
'	'	'-F	Fa
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
Dónall	Dónall	Dónall-N	Npmsc
Óg	Óg	óg-A	Aq-msc
caint	caint	caint-N	Ncfsc
na	na	na-T	Tdfsg
máthar	máthar	máthair-N	Ncfsg
tháinig	tháinig	tar-V	Vmis
cnap	cnap	cnap-N	Ncmsc
crua	crua	crua-A	Aqp
ina	ina	i-S	Spp-s|Spp-p
scornach	scornach	scornach-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
imní	imní	imní-N	Ncfsc
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
go	go	go-S	Sp
croí	croí	croí-N	Ncmsc
ann	ann	i-P	Pr3ms
nach	nach	nach-Q	Qnr
ligfeadh	ligfeadh	lig-V	Vmc----n
a	a	a-D	Dp3
mháthair	mháthair	máthair-N	Ncfsc
dó	dó	do-P	Pr3ms
dul	dul	dul-N	Ncmsc
go	go	go-S	Sp
Coill	Coill	Coill-N	Npmsc
na	na	na-T	Td-p
Baice	Baice	Baice-N	Npmsc
ag	ag	ag-S	Sp
obair	obair	obair-N	Nv-----n
.	.	.-F	Fe
Thóg	Thóg	tóg-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
chamán	chamán	camán-N	Ncmsc
ó	ó	ó-S	Sp
chúl	chúl	cúl-N	Ncmsc
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmm-2s
síos	síos	síos-R	Rd
an	an	an-T	Td-s
pháirc	pháirc	páirc-N	Ncfsc
ag	ag	ag-S	Sp
greadadh	greadadh	gread-N	Nv
an	an	an-T	Td-s
chnaig	chnaig	cnag-N	Ncmsg
roimhe	roimhe	roimh-P	Pr3ms
.	.	.-F	Fe
Rinne	Rinne	déan-V	Vmis
sé	sé	sé-P	Pp3msn
tamall	tamall	tamall-N	Ncmsc
iomána	iomána	iomáin-N	Ncfsg|Nv--g
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
,	,	,-F	Fi
chuaigh	chuaigh	téigh-V	Vmis
sé	sé	sé-P	Pp3msn
anonn	anonn	anonn-R	Rd
chuig	chuig	chuig-S	Sp
páirc	páirc	páirc-N	Ncfsc
eile	eile	eile-D	Dd
,	,	,-F	Fi
áit	áit	áit-N	Ncfsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
a	a	a-D	Dp3
phónaí	phónaí	pónaí-N	Ncmsc
liath	liath	liath-A	Aq-msc
féin	féin	féin-P	Px
.	.	.-F	Fe
Shlíoc	Shlíoc	slíoc-V	Vmis
sé	sé	sé-P	Pp3msn
moing	moing	moing-N	Ncfsc
an	an	an-T	Td-s
phónaí	phónaí	pónaí-N	Ncmsg
go	go	go-U	Ua
séimh	séimh	séimh-A	Aqp
.	.	.-F	Fe
Smaoinigh	Smaoinigh	smaoinigh-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
na	na	na-T	Td-p
laethanta	laethanta	lá-N	Ncmpc
fada	fada	fada-A	Aqp
a	a	a-Q	Q-r
chaith	chaith	caith-V	Vmis
sé	sé	sé-P	Pp3msn
sa	sa	i-S	Spa-s
diallait	diallait	diallait-N	Ncfsc
,	,	,-F	Fi
ag	ag	ag-S	Sp
léim	léim	léim-N	Nv
thar	thar	thar-S	Sp
chlaí	chlaí	claí-N	Ncmsc
agus	agus	agus-C	Cc
sceach	sceach	sceach-N	Ncfpg|Ncfsc|Ncfpg
trasna	trasna	trasna-S	Sp
na	na	na-T	Td-p
bpáirceanna	bpáirceanna	páirc-N	Ncfpg
,	,	,-F	Fi
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
an	an	an-T	Td-s
ghaoth	ghaoth	gaoth-N	Ncfsc
Mhárta	Mhárta	Márta-N	Ncmsg
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
amharc	amharc	amharc-N	Ncmsc
suas	suas	suas-R	Rd
dó	dó	do-P	Pr3ms
,	,	,-F	Fi
chonaic	chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
ceangailte	ceangailte	ceangail-A	Av
i	i	i-S	Sp
gcúl	gcúl	cúl-N	Ncmsc
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
capall	capall	capall-N	Ncmsc
dubh	dubh	dubh-A	Aq-msc
Shéarlaí	Shéarlaí	Shéarlaí-N	Npmsc
,	,	,-F	Fi
an	an	an-T	Td-s
capall	capall	capall-N	Ncmsc
ar	ar	ar-Q	Q-is
bhuaigh	bhuaigh	buaigh-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
cliathrás	cliathrás	cliathrás-N	Ncmsc
i	i	i-S	Sp
gCoill	gCoill	coll-N	Ncfsc|Ncmpc
na	na	na-T	Td-p
Baice	Baice	Baice-N	Npmsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
ithe	ithe	ith-N	Nv
coirce	coirce	coirce-N	Ncmsg
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
croitheadh	croitheadh	croith-N	Nv
a	a	a-Q	Q-r
chinn	chinn	cinn-V	Vmis
san	san	i-S	Spa-s
aer	aer	aer-N	Ncmsc
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
léir	léir	léir-A	Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
tagtha	tagtha	tar-A	Av
ar	ar	ar-S	Sp
cuairt	cuairt	cuairt-N	Ncfsc
.	.	.-F	Fe
Léim	Léim	léim-V	Vmip1s|Vmm-2s|Vmis|Ncfsc
croí	croí	croí-N	Ncmsg|Ncmsc
Dhónaill	Dhónaill	Dónall-N	Npfsg|Npm-g
.	.	.-F	Fe
Bheadh	Bheadh	bí-V	Vmc
a	a	a-D	Dp3
uncail	uncail	uncail-N	Ncmsc
ábalta	ábalta	ábalta-A	Aqp
a	a	a-U	U
chur	chur	cuir-N	Nv
ina	ina	i-S	Spp-s|Spp-p
luí	luí	luí-N	Ncmsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
mháthair	mháthair	máthair-N	Ncfsc
gur	gur	is-W	Wsdi|Wpdi
chóir	chóir	cóir-A	Aqp
seans	seans	seans-N	Ncmsg|Ncmsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
dó	dó	do-P	Pr3ms
dul	dul	dul-N	Ncmsc
ag	ag	ag-S	Sp
obair	obair	obair-N	Nv-----n
i	i	i-S	Sp
gCoill	gCoill	coll-N	Ncfsc|Ncmpc
na	na	na-T	Td-p
Baice	Baice	Baice-N	Npmsc
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
é	é	é-P	Pp3ms
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
t	t	t-X	Xl
‑	‑	‑-F	Fb
aon	aon	aon-M	Mc
deartháir	deartháir	deartháir-N	Ncmsc
amháin	amháin	amháin-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
máthair	máthair	máthair-N	Ncfsc
Dhónaill	Dhónaill	Dónall-N	Npfsg|Npm-g
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
meas	meas	meas-N	Ncmsc
mór	mór	mór-A	Aq-msc
aici	aici	ag-P	Pr3fs
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
obair	obair	obair-N	Ncfsc|Nv-----n
d	d	d-X	Xl
’	’	’-F	Fa
athair	athair	athair-N	Ncmsc
Dhónaill	Dhónaill	Dónall-N	Npfsg|Npm-g
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
seisean	seisean	sé-P	Pp3msne
ar ais	ar ais	ar_ais-R	Rd
ó	ó	ó-S	Sp
Albain	Albain	Albain-N	Npfsc
aimsir	aimsir	aimsir-N	Ncfsc
an	an	an-T	Td-s
chogaidh	chogaidh	cogadh-N	Ncmsg
.	.	.-F	Fe
Fear	Fear	fear-N	Ncmsc
beag	beag	beag-A	Aq-msc
anbhann	anbhann	bann-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
i	i	i-S	Sp
Sean	Sean	Sean-N	Npmsc
‑	‑	‑-F	Fb
Dónall	Dónall	Dónall-N	Npmsc
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
in ann	in ann	in_ann-S	Spc
d	d	d-X	Xl
’	’	’-F	Fa
obair	obair	obair-N	Ncfsc
throm	throm	trom-A	Aq-fsc
seachas	seachas	seachas-S	Sp
giollacht	giollacht	giollacht-N	Ncfsc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
ar	ar	ar-S	Sp
na	na	na-T	Td-p
capaill	capaill	capall-N	Ncmpc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
eolach	eolach	eolach-A	Aqp
go	go	go-U	Ua
maith	maith	maith-A	Aqp
ar	ar	ar-S	Sp
chapaill	chapaill	capall-N	Ncmpc
rása	rása	rás-N	Ncmsg
mar	mar	mar-C	Cs
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
na	na	na-T	Td-p
blianta	blianta	bliain-N	Ncfpc
fada	fada	fada-A	Aqp
caite	caite	caith-A	Av
aige	aige	ag-P	Pr3ms
ag	ag	ag-S	Sp
obair	obair	obair-N	Nv-----n
mar	mar	mar-S	Sp
chléireach	chléireach	cléireach-N	Ncmsc
oifige	oifige	oifig-N	Ncfsg
i	i	i-S	Sp
ráschúrsa	ráschúrsa	ráschúrsa-N	Ncmsc
mór	mór	mór-A	Aq-msc
in	in	i-S	Sp
Albain	Albain	Albain-N	Npfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ráite	ráite	abair-A	Av
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
go leor	go leor	go_leor-A	Aq|Ns-s|Rg
airgid	airgid	airgead-N	Ncmsg
buaite	buaite	buaigh-A	Av
aige	aige	ag-P	Pr3ms
ar	ar	ar-S	Sp
na	na	na-T	Td-p
capaill	capaill	capall-N	Ncmpc
,	,	,-F	Fi
cé	cé	cé-C	Cs
go	go	go-Q	Q
ndeireadh	ndeireadh	abair-V	Vmih
a	a	a-D	Dp3
bhean	bhean	bean-N	Ncfsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
go leor	go leor	go_leor-A	Aq|Ns-s|Rg
caillte	caillte	caill-N	Ncmsg|Nv--g
aige	aige	ag-P	Pr3ms
orthu	orthu	ar-P	Pr3-p
fosta	fosta	fosta-A	Aqp|Rg
.	.	.-F	Fe
'	'	'-F	Fa
Ní	Ní	ní-Q	Qn
chreidim	chreidim	creid-V	Vmip1s-n
,	,	,-F	Fi
a	a	a-U	Uv
Shéarlaí	Shéarlaí	Shéarlaí-N	Npmsc
,	,	,-F	Fi
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
Traenálaí	Traenálaí	traenálaí-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
Choill	Choill	Coill-N	Npfsg
na	na	na-T	Td-p
Baice	Baice	Baice-N	Npmsc
sásta	sásta	sásta-A	Aqp
gasúr	gasúr	gasúr-N	Ncmsc
óg	óg	óg-A	Aq-msc
mar	mar	mar-S	Sp
seo	seo	seo-P	Pd
a	a	a-U	U
fhostú	fhostú	fostaigh-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
Máire	Máire	Máire-N	Npfsc
Rua	Rua	Rua-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Ach	Ach	ach-C	Cs
gheall	gheall	geall-V	Vmis
sé	sé	sé-P	Pp3msn
post	post	post-N	Ncmsc
dó	dó	do-P	Pr3ms
,	,	,-F	Fi
a	a	a-U	Uv
Mháire	Mháire	Máire-N	Npf-v
,	,	,-F	Fi
agus	agus	agus-C	Cc
is	is	is-W	Wpri
fear	fear	fear-N	Ncmsc
ionraic	ionraic	ionraic-A	Aq-msc
é	é	é-P	Pp3ms
George	George	George-N	Npmsc
Brown	Brown	Brown-N	Npmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Muintir	Muintir	muintir-N	Ncfsc
Choill	Choill	Coill-N	Npfsg
na	na	na-T	Td-p
Baice	Baice	Baice-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Máire	Máire	Máire-N	Npfsc
.	.	.-F	Fe
'	'	'-F	Fa
Níor	Níor	is-W	Ws-in
cheart	cheart	ceart-A	Aqp
dár	dár	do-S	Spp-p
leithéidne	leithéidne	leithéidne-N	Ncfsc
baint	baint	bain-N	Ncfsc|Nv
ná	ná	ná-C	Cc
páirt	páirt	páirt-N	Ncfsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
againn	againn	ag-P	Pr1-p
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
Dream	Dream	dream-N	Ncmsc
garbh	garbh	garbh-A	Aq-msc
coimhthíoch	coimhthíoch	coimhthíoch-A	Aq-msc
atá	atá	bí-V	Vmip---r
iontu	iontu	i-P	Pr3-p
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
B	B	B-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
é	é	é-P	Pp3ms
,	,	,-F	Fi
ach	ach	ach-C	Cs
is	is	is-W	Wpri
dream	dream	dream-N	Ncmsc
dá	dá	do-S	Spp-p
bhfocal	bhfocal	focal-N	Ncmsc
iad	iad	iad-P	Pp3-p
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
Máire	Máire	Máire-N	Npfsc
Rua	Rua	Rua-N	Npmsg|Npmsc
buailte	buailte	buail-A	Av
go	go	go-U	Ua
fóill	fóill	fóill-A	Aqp
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
go leor	go leor	go_leor-A	Aq|Ns-s|Rg
rudaí	rudaí	rud-N	Ncmpg
fiúntacha	fiúntacha	fiúntach-A	Aq--pg
le	le	le-S	Sp
déanamh	déanamh	déan-N	Nv
ag	ag	ag-S	Sp
Dónall	Dónall	Dónall-N	Npmsc
Óg	Óg	óg-A	Aq-msc
sa	sa	i-S	Spa-s
bhaile	bhaile	baile-N	Ncmsc
,	,	,-F	Fi
go	go	go-U	Ua
háirithe	háirithe	áirithe-A	Aqp
agus	agus	agus-C	Cc
a	a	a-D	Dp3
athair	athair	athair-N	Ncmsc
mar	mar	mar-C	Cs
atá	atá	bí-V	Vmip---r
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
'	'	'-F	Fa
Chuala	Chuala	clois-V	Vmis
Dónall	Dónall	Dónall-N	Npmsc
an	an	an-T	Td-s
chuid	chuid	cuid-N	Ncfsc
dheireanach	dheireanach	deireanach-A	Aq-fsc
den	den	de-S	Spa-s
chaint	chaint	caint-N	Ncfsc
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ar	ar	ar-N	Ncmsc
a	a	a-D	Dp3
bhealach	bhealach	bealach-N	Ncmsc
isteach	isteach	isteach-R	Rd
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
féin	féin	féin-P	Px
a	a	a-D	Dp3
ladar	ladar	ladar-N	Ncmsc
isteach	isteach	isteach-R	Rd
.	.	.-F	Fe
'	'	'-F	Fa
Beidh	Beidh	bí-V	Vmif
mé	mé	mé-P	Pp1-s
in ann	in ann	in_ann-S	Spc
mo	mo	mo-D	Dp1-s
chuid	chuid	cuid-N	Ncfsc
oibre	oibre	obair-N	Ncfsg|Nv--g--n
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
sa	sa	i-S	Spa-s
bhaile	bhaile	baile-N	Ncmsc
go	go	go-U	Ua
fóill	fóill	fóill-A	Aqp
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
ndóigh	ndóigh	dóigh-N	Ncfsc
,	,	,-F	Fi
ní	ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
ach	ach	ach-S	Sp|Cs
trí	trí	trí-M	Mc|Sp
thráthnóna	thráthnóna	tráthnóna-N	Ncmsc
sa	sa	i-S	Spa-s
tseachtain	tseachtain	seachtain-N	Ncfsc
le	le	le-S	Sp
déanamh	déanamh	déan-N	Nv
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Cad	Cad	cad-W	W--q
é	é	é-P	Pp3ms
fán	fán	faoi-S	Spa-s
obair	obair	obair-N	Ncfsc
scoile	scoile	scoil-N	Ncfsg
?	?	?-F	Fq
Nach	Nach	nach-Q	Qnq
bhfuil	bhfuil	bí-V	Vmip---d
scoláireacht	scoláireacht	scoláireacht-N	Ncfsc
go dtí	go dtí	go_dtí-S	Spc
Coláiste	Coláiste	coláiste-N	Ncmsc
Choilm	Choilm	colm-N	Ncmsg
ag	ag	ag-S	Sp
an	an	an-T	Td-s
Máistir	Máistir	Máistir-N	Npmsc
Mac	Mac	mac-N	Ncmsc
an	an	an-T	Td-s
tSaoir	tSaoir	Saoir-N	Npmsg
duit	duit	do-P	Pr2-s
?	?	?-F	Fq
'	'	'-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
a	a	a-D	Dp3
mháthair	mháthair	máthair-N	Ncfsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
dá	dá	dó-M	Mc
dhorn	dhorn	dorn-N	Ncmsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
cromán	cromán	cromán-N	Ncmsc
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
'	'	'-F	Fa
Déanfaidh	Déanfaidh	déan-V	Vmif
mé	mé	mé-P	Pp1-s
staidéar	staidéar	staidéar-N	Ncmsc|Nv-----n
san	san	i-S	Spa-s
oíche	oíche	oíche-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Staidéar	Staidéar	staidéar-N	Ncmsc|Nv-----n
!	!	!-F	Fe
'	'	'-F	Fa
Chroith	Chroith	croith-V	Vmis
an	an	an-T	Td-s
mháthair	mháthair	máthair-N	Ncfsc
a	a	a-D	Dp3
ceann	ceann	ceann-N	Ncmsc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
ardaigh	ardaigh	ardaigh-V	Vmis
a	a	a-D	Dp3
súile	súile	súil-N	Ncfpc
chun	chun	chun-S	Sp
na	na	na-T	Tdfsg
spéire	spéire	spéir-N	Ncfsg
.	.	.-F	Fe
'	'	'-F	Fa
Ní	Ní	ní-Q	Qn
thig	thig	tar-V	Vmip---n
leat	leat	le-P	Pr2-s
an	an	an-T	Td-s
dá	dá	dó-M	Mc
thrá	thrá	trá-N	Ncfsc
a	a	a-U	U
fhreastal	fhreastal	freastail-N	Nv
,	,	,-F	Fi
a	a	a-U	Uv
mhic	mhic	mac-N	Ncmsv
.	.	.-F	Fe
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
ag	ag	ag-S	Sp
Dónall	Dónall	Dónall-N	Npmsc
ina	ina	i-S	Spp-s
chroí	chroí	croí-N	Ncmsc
istigh	istigh	istigh-R	Rl
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
sé	sé	sé-P	Pp3msn
deacair	deacair	deacair-A	Aqp
go leor	go leor	go_leor-A	Aq
an	an	an-T	Td-s
scoláireacht	scoláireacht	scoláireacht-N	Ncfsc
a	a	a-U	U
bhaint	bhaint	bain-N	Nv
amach	amach	amach-R	Rd
fiú	fiú	fiú-N	Ns-s|Ncmsc|Rg
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
staidéir	staidéir	staidéar-N	Ncmsg|Nv--g--n|Ncmsg|Nv--g--n
ar	ar	ar-S	Sp
theann	theann	teann-N	Ncmsc
a	a	a-D	Dp3
dhíchill	dhíchill	dícheall-N	Ncmpc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bheadh	bheadh	bí-V	Vmc
sé	sé	sé-P	Pp3msn
ionann	ionann	ionann-A	Aqp
is	is	is-U	U
dodhéanta	dodhéanta	dodhéanta-A	Aqc
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
obair	obair	obair-N	Nv-----n
trí	trí	trí-M	Mc|Sp
thráthnóna	thráthnóna	tráthnóna-N	Ncmsc
sa	sa	i-S	Spa-s
tseachtain	tseachtain	seachtain-N	Ncfsc
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
bheag	bheag	beag-A	Aqp
an	an	an-T	Td-s
spéis	spéis	spéis-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
aige	aige	ag-P	Pr3ms
,	,	,-F	Fi
i	i	i-S	Sp
ndáiríre	ndáiríre	dáiríre-N	Ncmsc
,	,	,-F	Fi
dul	dul	téigh-N	Ncmsc|Nv
go dtí	go dtí	go_dtí-S	Spc
scoil	scoil	scoil-N	Ncfsc
chónaithe	chónaithe	cónaigh-A	Av
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
ó	ó	ó-S	Sp
bhaile	bhaile	baile-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ar	ar	ar-S	Sp|Ncmsc
a	a	a-D	Dp3
iúl	iúl	iúl-N	Ncmsc
ach	ach	ach-C	Cs
a	a	a-U	U
bheith	bheith	bí-N	Nv
ina	ina	i-S	Spp-s
mharcach	mharcach	marcach-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
fhéadfadh	fhéadfadh	féad-V	Vmc----n
sé	sé	sé-P	Pp3msn
sin	sin	sin-P	Pd
a	a	a-U	U
rá	rá	abair-N	Nv
lena	lena	le-S	Spp-s
mháthair	mháthair	máthair-N	Ncfsc
,	,	,-F	Fi
ar	ar	ar-S	Sp
ndóigh	ndóigh	dóigh-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
cinnte	cinnte	cinnte-A	Av|Aqp
go	go	go-Q	Q
mbeidh	mbeidh	bí-V	Vmif
Mr	Mr	Mr-Y	Y
Brown	Brown	Brown-N	Npmsc
sásta	sásta	sásta-A	Aqp
cúpla	cúpla	cúpla-N	Ncmsg|Ncmsc|Dq
seachtaine	seachtaine	seachtain-N	Ncfsg
saoire	saoire	saor-A	Aq-fsg
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
dom	dom	do-P	Pr1-s
aimsir	aimsir	aimsir-N	Ncfsc
an	an	an-T	Td-s
scrúdaithe	scrúdaithe	scrúdú-N	Ncmsg
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-U	Ua
tapa	tapa	tapa-A	Aqp
.	.	.-F	Fe
'	'	'-F	Fa
Beagán	Beagán	beagán-N	Ncmsc
seanchainte	seanchainte	seanchaint-N	Ncfsg
uait	uait	ó-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
mháthair	mháthair	máthair-N	Ncfsc
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
anois	anois	anois-R	Rt
ag	ag	ag-S	Sp
éirí	éirí	éirigh-N	Nv
gairgeach	gairgeach	gairgeach-A	Aqp
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
t	t	t-X	Xl
‑	‑	‑-F	Fb
uncail	uncail	uncail-N	Ncmsc
leid	leid	leid-N	Ncfsc
don	don	do-S	Spa-s
ghasúr	ghasúr	gasúr-N	Ncmsc
dul	dul	téigh-N	Ncmsc|Nv
amach	amach	amach-R	Rd
.	.	.-F	Fe
Bhain	Bhain	bain-V	Vmis
sé	sé	sé-P	Pp3msn
fada	fada	fada-A	Aqp
go leor	go leor	go_leor-A	Aq
as	as	as-N	Ncmpg
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
a	a	a-U	U
chur	chur	cuir-N	Nv
ina	ina	i-S	Spp-s|Spp-p
luí	luí	luí-N	Ncmsc
ar	ar	ar-S	Sp
Mháire	Mháire	Máire-N	Npfsc
gur	gur	is-W	Wsdi
cheart	cheart	ceart-A	Aqp
di	di	de-P	Pr3fs
cead	cead	cead-N	Ncmsc
a	a	a-Q	Q-r
chinn	chinn	cinn-V	Vmis
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
do	do	do-S	Sp
Dhónall	Dhónall	Dónall-N	Npmsc
Óg	Óg	óg-A	Aq-msc
.	.	.-F	Fe
I	I	i-S	Sp
ndiaidh	ndiaidh	diaidh-N	Ns-s
di	di	do-P	Pr3fs
go leor	go leor	go_leor-N	Ns-s
gearán	gearán	gearán-N	Ncmpg
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
ghéill	ghéill	géill-V	Vmis
sí	sí	sí-P	Pp3fsn
sa	sa	i-S	Spa-s
deireadh	deireadh	deireadh-N	Ncmsc
.	.	.-F	Fe
Níor	Níor	is-W	Ws-in
mhaith	mhaith	maith-A	Aqp
léi	léi	le-P	Pr3fs
a	a	a-D	Dp3
deartháir	deartháir	deartháir-N	Ncmsc
a	a	a-U	U
dhiúltú	dhiúltú	diúltaigh-N	Nv
.	.	.-F	Fe
'	'	'-F	Fa
Thig	Thig	tar-V	Vmip
leis	leis	le-P	Pr3ms
triail	triail	triail-N	Nv
a	a	a-U	U
bhaint	bhaint	bain-N	Nv
as	as	as-N	Ncmpg|Ncmsc|Pr3ms
go ceann	go ceann	go_ceann-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
ach	ach	ach-S	Sp|Cs
é	é	é-P	Pp3ms
staidéar	staidéar	staidéar-N	Ncmsc|Nv-----n
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
sa	sa	i-S	Spa-s
bhaile	bhaile	baile-N	Ncmsc
agus	agus	agus-C	Cc
cuidiú	cuidiú	cuidigh-N	Ncmsc|Nv
lena	lena	le-S	Spp-s
athair	athair	athair-N	Ncmsc
.	.	.-F	Fe
Sin	Sin	sin-W	W
sin	sin	sin-P	Pd
!	!	!-F	Fe
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
Traenálaí	Traenálaí	traenálaí-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
ag	ag	ag-S	Sp
fanacht	fanacht	fan-N	Nv
le	le	le-S	Sp
Dónall	Dónall	Dónall-N	Npmsc
sa	sa	i-S	Spa-s
chlós	chlós	clós-N	Ncmsc
.	.	.-F	Fe
Fear	Fear	fear-N	Ncmsc
mór	mór	mór-A	Aq-msc
láidir	láidir	láidir-A	Aq-msc
ba	ba	is-W	Wsri
ea	ea	ea-P	Pp3-s
é	é	é-P	Pp3ms
,	,	,-F	Fi
aghaidh	aghaidh	aghaidh-N	Ncfsc
dhearg	dhearg	dearg-A	Aq-fsc
air	air	ar-P	Pr3ms
agus	agus	agus-C	Cc
gach	gach	gach-D	Dq
aon	aon	aon-D	Dq
gháire	gháire	gáire-N	Ncmsc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
glór	glór	glór-N	Ncmsc
mór	mór	mór-A	Aq-msc
garbh	garbh	garbh-A	Aq-msc
aige	aige	ag-P	Pr3ms
agus	agus	agus-C	Cc
blas	blas	blas-N	Ncmsc
na	na	na-T	Tdfsg
hAlban	hAlban	Albain-N	Npf-g
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
chuid	chuid	cuid-N	Ncfsc
cainte	cainte	caint-N	Ncfsg|Nv--g--n
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
fáilte	fáilte	fáilte-N	Ncfsc
chroíúil	chroíúil	croíúil-A	Aq-fsc
roimh	roimh	roimh-S	Sp
Dhónall	Dhónall	Dónall-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Bulaí	Bulaí	bulaí-N	Ncmsc
gasúir	gasúir	gasúr-N	Ncmsg|Ncmpc
atá	atá	bí-V	Vmip---r
ionat	ionat	i-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
bhuachaill	bhuachaill	buachaill-N	Ncmsv
!	!	!-F	Fe
Bulaí	Bulaí	bulaí-N	Ncmsc
gasúir	gasúir	gasúr-N	Ncmsg|Ncmpc
!	!	!-F	Fe
Seo	Seo	seo-W	W
leat	leat	le-P	Pr2-s
anois	anois	anois-R	Rt
go	go	go-Q	Q
bhfeicfidh	bhfeicfidh	feic-V	Vmif
tú	tú	tú-P	Pp2-s
na	na	na-T	Td-p
stáblaí	stáblaí	stábla-N	Ncmpc
.	.	.-F	Fe
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
dhá	dhá	dó-M	Mc
shúil	shúil	súil-N	Ncfsc
Dhónaill	Dhónaill	Dónall-N	Npfsg|Npm-g
chomh	chomh	chomh-R	Ri
mór	mór	mór-A	Aqp
le	le	le-S	Sp
prátaí	prátaí	práta-N	Ncmpc
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
amharc	amharc	amharc-N	Nv
thart	thart	thart-R	Rd
.	.	.-F	Fe
Thaispeáin	Thaispeáin	taispeáin-V	Vmis
an	an	an-T	Td-s
Traenálaí	Traenálaí	traenálaí-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
dó	dó	do-P	Pr3ms
an	an	an-T	Td-s
líneáil	líneáil	líneáil-N	Ncfsc
rubair	rubair	rubar-N	Ncmsg|Ncmpc|Ncmsg
ar	ar	ar-S	Sp
na	na	na-T	Td-p
boscaí	boscaí	bosca-N	Ncmpc
stábla	stábla	stábla-N	Ncmsg|Ncmsc|Ncmsg
agus	agus	agus-C	Cc
na	na	na-T	Td-p
sliseoga	sliseoga	sliseog-N	Ncfpc
adhmaid	adhmaid	adhmad-N	Ncmsg|Ncmpc|Ncmsg
ar	ar	ar-S	Sp
an	an	an-T	Td-s
urlár	urlár	urlár-N	Ncmsc
.	.	.-F	Fe
Mhínigh	Mhínigh	mínigh-V	Vmis
sé	sé	sé-P	Pp3msn
dó	dó	do-P	Pr3ms
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
siad	siad	siad-P	Pp3-pn
ann	ann	i-R	Rl|Pr3ms
le	le	le-S	Sp
nach	nach	nach-Q	Qnr
mbeadh	mbeadh	bí-V	Vmc
na	na	na-T	Td-p
capaill	capaill	capall-N	Ncmpc
ábalta	ábalta	ábalta-A	Aqp
iad	iad	iad-P	Pp3-p
féin	féin	féin-P	Px
a	a	a-U	U
ghortú	ghortú	gortaigh-N	Nv
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
Dónall	Dónall	Dónall-N	Npmsc
Óg	Óg	óg-A	Aq-msc
suim	suim	suim-N	Ncfsc
sa	sa	i-S	Spa-s
cheol	cheol	ceol-N	Ncmsc
fífe	fífe	fíf-N	Ncfsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
ó	ó	ó-S	Sp
stábla	stábla	stábla-N	Ncmsc
in aice	in aice	in_aice-S	Spc
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
Lig	Lig	lig-V	Vmis|Vmm-2s
an	an	an-T	Td-s
Traenálaí	Traenálaí	traenálaí-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
scairt	scairt	scairt-V	Vmis
gháire	gháire	gáire-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Ná	Ná	ná-Q	Qnm
cuireadh	cuireadh	cuir-V	Vmis0--n
an	an	an-T	Td-s
ceol	ceol	ceol-N	Ncmsc
sin	sin	sin-D	Dd
as	as	as-P	Pr3ms
duit	duit	do-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
bhuachaill	bhuachaill	buachaill-N	Ncmsv
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
sé	sé	is-W	Wp-i-3
maith	maith	maith-A	Aqp
leis	leis	le-P	Pr3ms
na	na	na-T	Td-p
capaill	capaill	capall-N	Ncmpc
a	a	a-U	U
shocrú	shocrú	socraigh-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
'	'	'-F	Fa
Bíonn	Bíonn	bí-V	Vmig
cuid	cuid	cuid-N	Ncfsc
de	de	de-S	Sp
na	na	na-T	Td-p
capaill	capaill	capall-N	Ncmsg
neirbhíseach	neirbhíseach	neirbhíseach-A	Aq-msc
agus	agus	agus-C	Cc
caithfear	caithfear	caith-V	Vmif0
a	a	a-U	U
bheith	bheith	bí-N	Nv
cineálta	cineálta	cineálta-A	Aqp
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
'	'	'-F	Fa
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
gach	gach	gach-D	Dq
rud	rud	rud-N	Ncmsc
feicthe	feicthe	feic-A	Av
ag	ag	ag-S	Sp
Dónall	Dónall	Dónall-N	Npmsc
,	,	,-F	Fi
suas	suas	suas-R	Rd
leo	leo	le-P	Pr3-p
ansin	ansin	ansin-R	Rt|Rl
chuig	chuig	chuig-S	Sp
stábla	stábla	stábla-N	Ncmsc
eile	eile	eile-D	Dd
gur	gur	gur-Q	Q--s
chuir	chuir	cuir-V	Vmis
an	an	an-T	Td-s
Traenálaí	Traenálaí	traenálaí-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
é	é	é-P	Pp3ms
in	in	i-S	Sp
aithne	aithne	aithne-N	Ncfsc
do	do	do-S	Sp
William	William	William-N	Npmsc
.	.	.-F	Fe
Stócach	Stócach	Stóc-N	Npmsc
sé	sé	sé-M	Mc
bliana	bliana	bliain-N	Ncfpc
déag	déag	déag-N	Ns-s
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
grágán	grágán	grágán-N	Ncmsc
de	de	de-S	Sp
ghruaig	ghruaig	gruaig-N	Ncfsc
throm	throm	trom-A	Aq-fsc
dhubh	dhubh	dubh-A	Aq-fsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
'	'	'-F	Fa
Beidh	Beidh	bí-V	Vmif
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
obair	obair	obair-N	Nv-----n
leis	leis	le-S	Sp
an	an	an-T	Td-s
leaid	leaid	leaid-N	Ncmsc
seo	seo	seo-D	Dd
.	.	.-F	Fe
Cuideoidh	Cuideoidh	cuidigh-V	Vmif
tú	tú	tú-P	Pp2-s
leis	leis	le-S	Sp
na	na	na-T	Td-p
capaill	capaill	capall-N	Ncmpc
a	a	a-U	U
chothú	chothú	cothaigh-N	Nv
agus	agus	agus-C	Cc
na	na	na-T	Td-p
boscaí	boscaí	bosca-N	Ncmpc
a	a	a-U	U
ghlanadh	ghlanadh	glan-N	Nv
amach	amach	amach-R	Rd
.	.	.-F	Fe
Caithfidh	Caithfidh	caith-V	Vmif
gach	gach	gach-D	Dq
aon	aon	aon-D	Dq
áit	áit	áit-N	Ncfsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
nite	nite	nigh-A	Av
glan	glan	glan-A	Aqp
.	.	.-F	Fe
Sin	Sin	sin-W	W
cuid	cuid	cuid-N	Ncfsc
den	den	de-S	Spa-s
traenáil	traenáil	traenáil-N	Ncfsc
le	le	le-S	Sp
bheith	bheith	bí-N	Nv
i	i	i-S	Sp
do	do	do-D	Dp2-s
mharcach	mharcach	marcach-N	Ncmsc
,	,	,-F	Fi
tá	tá	bí-V	Vmip
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agat	agat	ag-P	Pr2-s
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
fada	fada	fada-A	Aqp
go	go	go-Q	Q
mbeidh	mbeidh	bí-V	Vmif
tú	tú	tú-P	Pp2-s
ábalta	ábalta	ábalta-A	Aqp
na	na	na-T	Td-p
capaill	capaill	capall-N	Ncmpc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
amach	amach	amach-R	Rd
ag	ag	ag-S	Sp
sodar	sodar	sodar-N	Ncmsc
.	.	.-F	Fe
Buail	Buail	buail-V	Vmm-2s
síos	síos	síos-R	Rd
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
oifig	oifig	oifig-N	Ncfsc
Dé	Dé	Dé-N	Ns-s
hAoine	hAoine	Aoine-N	Ncfsg
agus	agus	agus-C	Cc
beidh	beidh	bí-V	Vmif
cúpla	cúpla	cúpla-D	Dq|Ncmsc
scilling	scilling	scilling-N	Ncfpg|Ncfsc|Ncfpg
acu	acu	ag-P	Pr3-p
duit	duit	do-P	Pr2-s
.	.	.-F	Fe
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
Dónall	Dónall	Dónall-N	Npmsc
Óg	Óg	óg-A	Aq-msc
chomh	chomh	chomh-R	Ri
sásta	sásta	sásta-A	Aqp
le	le	le-S	Sp
rí	rí	rígh-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
obair	obair	obair-N	Nv-----n
le	le	le-S	Sp
Traenálaí	Traenálaí	traenálaí-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
Choill	Choill	Coill-N	Npfsg
na	na	na-T	Td-p
Baice	Baice	Baice-N	Npmsc
,	,	,-F	Fi
agus	agus	agus-C	Cc
,	,	,-F	Fi
dá	dá	de-S	Spp-s
n	n	n-X	Xl
‑	‑	‑-F	Fb
oibreodh	oibreodh	oibrigh-V	Vmc
rudaí	rudaí	rud-N	Ncmpc
amach	amach	amach-R	Rd
go	go	go-U	Ua
maith	maith	maith-A	Aqp
,	,	,-F	Fi
bheadh	bheadh	bí-V	Vmc
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
mharcach	mharcach	marcach-N	Ncmsc
déanta	déanta	déan-A	Aqp|Av
sula	sula	sula-C	Cs
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
.	.	.-F	Fe
Anuas	Anuas	anuas-R	Rd
air	air	ar-P	Pr3ms
sin	sin	sin-P	Pd
bheadh	bheadh	bí-V	Vmc
sé	sé	sé-P	Pp3msn
ábalta	ábalta	ábalta-A	Aqp
airgead	airgead	airgead-N	Ncmsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
dá	dá	do-S	Spp-s
mháthair	mháthair	máthair-N	Ncfsc
.	.	.-F	Fe
Cinnte	Cinnte	cinn-A	Av
ní	ní	ní-Q	Qn
chuirfeadh	chuirfeadh	cuir-V	Vmc----n
sí	sí	sí-P	Pp3fsn
ina	ina	i-S	Spp-s
éadan	éadan	éadan-N	Ncmsc
ansin	ansin	ansin-R	Rt|Rl
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
William	William	William-N	Npmsc
cineál	cineál	cineál-R	Ri
tostach	tostach	tostach-A	Aqp
ar	ar	ar-S	Sp
dtús	dtús	tús-N	Ncmsc
ach	ach	ach-C	Cs
níorbh	níorbh	is-W	Ws-in
fhada	fhada	fada-A	Aqc|Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
míniú	míniú	mínigh-N	Nv
gach	gach	gach-D	Dq
aon	aon	aon-D	Dq
sórt	sórt	sórt-N	Ncmsc
fá	fá	faoi-P	Pr3ms
chapaill	chapaill	capall-N	Ncmpc
do	do	do-S	Sp
Dhónall	Dhónall	Dónall-N	Npmsc
Óg	Óg	óg-A	Aq-msc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
inis	inis	inis-V	Vmis
sé	sé	sé-P	Pp3msn
ainmneacha	ainmneacha	ainm-N	Ncmpc
na	na	na-T	Td-p
gcapall	gcapall	capall-N	Ncmpg
dó	dó	do-P	Pr3ms
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
comhairle	comhairle	comhairle-N	Ncfsc
fá	fá	faoi-P	Pr3ms
chinn	chinn	ceann-N	Ncmpc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
neirbhíseach	neirbhíseach	neirbhíseach-A	Aqp
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
labhair	labhair	labhair-V	Vmis
sé	sé	sé-P	Pp3msn
fán	fán	fán-S	Spa-s|Ncmsc
liosta	liosta	liosta-N	Ncmsg|Ncmsc|Ncmsg|Aqp
bia	bia	bia-N	Ncmsg|Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
thuas	thuas	thuas-R	Rd
ar	ar	ar-S	Sp
bhalla	bhalla	balla-N	Ncmsc
an	an	an-T	Td-s
stábla	stábla	stábla-N	Ncmsg
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
léir	léir	léir-A	Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
meas	meas	meas-N	Ncmsc
mór	mór	mór-A	Aq-msc
ag	ag	ag-S	Sp
William	William	William-N	Npmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
Traenálaí	Traenálaí	traenálaí-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
.	.	.-F	Fe
Mhol	Mhol	mol-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-S	Sp
barr	barr	barr-N	Ncmsc
bata	bata	bata-N	Ncmsg
é	é	é-P	Pp3ms
.	.	.-F	Fe
'	'	'-F	Fa
Thiocfadh	Thiocfadh	tar-V	Vmc
le	le	le-S	Sp
Mr	Mr	Mr-Y	Y
Brown	Brown	Brown-N	Npmsc
gabhar	gabhar	gabhar-N	Ncmpg|Ncmsc
a	a	a-U	U
thraenáil	thraenáil	traenáil-N	Nv
le	le	le-S	Sp
rás	rás	rás-N	Ncmsc
capall	capall	capall-N	Ncmpg
a	a	a-U	U
bhuachan	bhuachan	buaigh-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
glacadh	glacadh	glac-N	Nv
ceapaire	ceapaire	ceapaire-N	Ncmsg
iad	iad	iad-P	Pp3-p
féin	féin	féin-P	Px
sa	sa	i-S	Spa-s
stábla	stábla	stábla-N	Ncmsc
bhí	bhí	bí-V	Vmis
Dónall	Dónall	Dónall-N	Npmsc
Óg	Óg	óg-A	Aq-msc
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
ar	ar	ar-S	Sp
pheil	pheil	peil-N	Ncfsc
agus	agus	agus-C	Cc
iomáint	iomáint	iomáin-N	Nv
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
William	William	William-N	Npmsc
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
ar	ar	ar-S	Sp
chruicéad	chruicéad	cruicéad-N	Ncmsc
agus	agus	agus-C	Cc
snúcar	snúcar	snúcar-N	Ncmpg|Ncmsc|Ncmpg
.	.	.-F	Fe
Cé	Cé	cé-C	Cs
nár	nár	is-W	Wsdin
léirigh	léirigh	léirigh-V	Vmis
éinne	éinne	duine-N	Ncmsc
thart	thart	thart-R	Rd
fá	fá	faoi-P	Pr3ms
Dhroichead	Dhroichead	droichead-N	Ncmsc
Thuama	Thuama	Tuama-N	Npfsg
suim	suim	suim-N	Ncfsc
riamh	riamh	riamh-R	Rg
sa	sa	i-S	Spa-s
snúcar	snúcar	snúcar-N	Ncmsc
bhí	bhí	bí-V	Vmis
go leor	go leor	go_leor-A	Aq|Ns-s|Rg
ceisteanna	ceisteanna	ceist-N	Ncfpg
ag	ag	ag-S	Sp
Dónall	Dónall	Dónall-N	Npmsc
Óg	Óg	óg-A	Aq-msc
fá	fá	faoi-P	Pr3ms
dtaobh	dtaobh	taobh-N	Ncmsc
de	de	de-P	Pr3ms
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
William	William	William-N	Npmsc
cuireadh	cuireadh	cuir-V	Vmis0
dó	dó	do-P	Pr3ms
bualadh	bualadh	bualadh-N	Ncmsc
síos	síos	síos-R	Rd
chuig	chuig	chuig-S	Sp
Tábhairne	Tábhairne	tábhairne-N	Ncmsc
an	an	an-T	Td-s
Tairbh	Tairbh	tarbh-N	Ncmsg
Dhuibh	Dhuibh	Duibh-N	Npfsg
i	i	i-S	Sp
gCoill	gCoill	coll-N	Ncfsc|Ncmpc
na	na	na-T	Td-p
Baice	Baice	Baice-N	Npmsc
an	an	an-T	Td-s
tseachtain	tseachtain	seachtain-N	Ncfsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|Dd
.	.	.-F	Fe
Dar	Dar	dar-V	Vmip
le	le	le-S	Sp
William	William	William-N	Npmsc
bhí	bhí	bí-V	Vmis
cúlsheomra	cúlsheomra	cúlsheomr-N	Ncmpc
deas	deas	deas-A	Aq--pg
snúcair	snúcair	snúcar-N	Ncmsg|Ncmpc
ansin	ansin	ansin-R	Rt|Rl
agus	agus	agus-C	Cc
bheadh	bheadh	bí-V	Vmc
seans	seans	seans-N	Ncmsc
ag	ag	ag-S	Sp
Dónall	Dónall	Dónall-N	Npmsc
triail	triail	triail-N	Ncfsc|Nv
a	a	a-U	U
bhaint	bhaint	bain-N	Nv
as	as	as-S	Sp
an	an	an-T	Td-s
snúcar	snúcar	snúcar-N	Ncmsc
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
an	an	an-T	Td-s
obair	obair	obair-N	Ncfsc
sa	sa	i-S	Spa-s
stábla	stábla	stábla-N	Ncmsc
ar	ar	ar-S	Sp
aghaidh	aghaidh	aghaidh-N	Ncfsc
go	go	go-U	Ua
maith	maith	maith-A	Aqp
agus	agus	agus-C	Cc
gach	gach	gach-D	Dq
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
ag	ag	ag-S	Sp
obair	obair	obair-N	Nv-----n
go	go	go-U	Ua
crua	crua	crua-A	Aqp
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
as	as	as-P	Pr3ms
Coill	Coill	Coill-N	Npmsc
na	na	na-T	Td-p
Baice	Baice	Baice-N	Npmsc
na	na	na-T	Td-p
gasúir	gasúir	gasúr-N	Ncmpc
eile	eile	eile-D	Dd
uilig	uilig	uile-D	Dq
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
obair	obair	obair-N	Nv-----n
ann	ann	i-P	Pr3ms
,	,	,-F	Fi
agus	agus	agus-C	Cc
,	,	,-F	Fi
seachas	seachas	seachas-S	Sp
William	William	William-N	Npmsc
,	,	,-F	Fi
níor	níor	níor-Q	Qn-s
bhac	bhac	bac-V	Vmis---n
siad	siad	siad-P	Pp3-pn
le	le	le-S	Sp
Dónall	Dónall	Dónall-N	Npmsc
Óg	Óg	óg-A	Aq-msc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ba	ba	is-W	Ws|Ws-i
chuma	chuma	cuma-A	Aqp
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
le	le	le-S	Sp
croí	croí	croí-N	Ncmsc
éadrom	éadrom	éadrom-A	Aq-msc
a	a	a-Q	Q-r
chuaigh	chuaigh	téigh-V	Vmis
sé	sé	sé-P	Pp3msn
síos	síos	síos-R	Rd
tráthnóna	tráthnóna	tráthnóna-N	Ncmsc
Dé	Dé	Dé-N	Ns-s
hAoine	hAoine	Aoine-N	Ncfsg
chuig	chuig	chuig-S	Sp
an	an	an-T	Td-s
oifig	oifig	oifig-N	Ncfsc
gur	gur	gur-W	Wsdi|Q--s
shín	shín	sín-V	Vmis|Ncfsc
cailín	cailín	cailín-N	Ncmsc
na	na	na-T	Tdfsg
hoifige	hoifige	oifig-N	Ncfsg
clúdach	clúdach	clúdach-N	Ncmsc
donn	donn	donn-A	Aq-msc
chuige	chuige	chuig-R	Rg|Pr3ms
lena	lena	le-S	Spp-s
ainm	ainm	ainm-N	Ncmsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Sháigh	Sháigh	sáigh-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
phóca	phóca	póca-N	Ncmsc
é	é	é-P	Pp3ms
,	,	,-F	Fi
suas	suas	suas-R	Rd
leis	leis	le-P	Pr3ms
go	go	go-U	Ua
gasta	gasta	gasta-A	Aqp
ar	ar	ar-S	Sp
dhroim	dhroim	droim-N	Ncmsc
an	an	an-T	Td-s
phónaí	phónaí	pónaí-N	Ncmsg
agus	agus	agus-C	Cc
shín	shín	sín-V	Vmis
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Siúd	Siúd	siúd-P	Pd
amach	amach	amach-R	Rd
é	é	é-P	Pp3ms
trí	trí	trí-M	Mc|Sp
Bhaile	Bhaile	Baile-N	Npmsc
Uí	Uí	Uí-U	Up
Chinnéide	Chinnéide	Cinnéide-N	Npmsc
agus	agus	agus-C	Cc
síos	síos	síos-R	Rd
feadh	feadh	feadh-N	Ncmsc
bhruach	bhruach	bruach-N	Ncmsc
na	na	na-T	Td-p
Banna	Banna	banna-N	Ncmsg
chomh	chomh	chomh-R	Ri
fada	fada	fada-A	Aqp
le	le	le-S	Sp
Loch	Loch	loch-N	Ncmsc
Beag	Beag	beag-A	Aq-msc
.	.	.-F	Fe
Stop	Stop	stop-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
crann	crann	crann-N	Ncmsc
mór	mór	mór-A	Aq-msc
darach	darach	dair-N	Ncfsg
.	.	.-F	Fe
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
leis	leis	le-P	Pr3ms
an	an	an-T	Td-s
clúdach	clúdach	clúdach-N	Ncmsc
a	a	a-U	U
oscailt	oscailt	oscail-N	Nv
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
shuaimhneas	shuaimhneas	suaimhneas-N	Ncmsc
sula	sula	sula-C	Cs
mbainfeadh	mbainfeadh	bain-V	Vmc
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
baile	baile	baile-N	Ncmsc
amach	amach	amach-R	Rd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
dhá	dhá	dó-M	Mc
leathchoróin	leathchoróin	leathchoróin-N	Ncfsc
agus	agus	agus-C	Cc
cúpla	cúpla	cúpla-N	Ncmsg|Ncmsc|Dq
bonn	bonn	bonn-N	Ncmpg|Ncmsc
eile	eile	eile-D	Dd
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Léim	Léim	léim-V	Vmip1s|Vmis
a	a	a-D	Dp3
chroí	chroí	croí-N	Ncmsc
le	le	le-S	Sp
háthas	háthas	áthas-N	Ncmsc
nó	nó	nó-C	Cc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
an	an	an-T	Td-s
méid	méid	méid-N	Ncmsc
sin	sin	sin-D	Dd
airgid	airgid	airgead-N	Ncmsg
ina	ina	i-S	Spp-s
ghlac	ghlac	glac-N	Ncfsc
riamh	riamh	riamh-R	Rg
roimhe	roimhe	roimh-P	Pr3ms
sin	sin	sin-P	Pd|W
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Léim	Léim	léim-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-U	Ua
bródúil	bródúil	bródúil-A	Aqp
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
phónaí	phónaí	póna-N	Ncmsc|Ncmpc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
chuirfeadh	chuirfeadh	cuir-V	Vmc----n
a	a	a-D	Dp3
mháthair	mháthair	máthair-N	Ncfsc
ina	ina	i-S	Spp-s
éadan	éadan	éadan-N	Ncmsc
anois	anois	anois-R	Rt
!	!	!-F	Fe
Tháinig	Tháinig	tar-V	Vmis
na	na	na-T	Td-p
deora	deora	deoir-N	Ncfpc
le	le	le-S	Sp
Máire	Máire	Máire-N	Npfsc
Rua	Rua	Rua-N	Npmsg
Uí	Uí	Uí-U	Up
Scolláin	Scolláin	Scolláin-N	Npmsg
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
shín	shín	sín-V	Vmis
Dónall	Dónall	Dónall-N	Npmsc
Óg	Óg	óg-A	Aq-msc
a	a	a-D	Dp3
chéadtuarastal	chéadtuarastal	tuarastal-N	Ncmsc
chuici	chuici	chuig-P	Pr3fs
.	.	.-F	Fe
Tharraing	Tharraing	tarraing-V	Vmis
sí	sí	sí-P	Pp3fsn
chuici	chuici	chuig-P	Pr3fs
a	a	a-D	Dp3
sparán	sparán	sparán-N	Ncmsc
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
dhá	dhá	dó-M	Mc
scilling	scilling	scilling-N	Ncfsc
do	do	do-S	Sp
Dhónall	Dhónall	Dónall-N	Npmsc
Óg	Óg	óg-A	Aq-msc
dó	dó	do-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
gliondar	gliondar	gliondar-N	Ncmsc
ar	ar	ar-S	Sp
chroí	chroí	croí-N	Ncmsc
an	an	an-T	Td-s
ghasúir	ghasúir	gasúr-N	Ncmsg
aoibh	aoibh	aoibh-N	Ncfsc
an	an	an-T	Td-s
gháire	gháire	gáir-N	Nv
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
ar	ar	ar-S	Sp
aghaidh	aghaidh	aghaidh-N	Ncfsc
a	a	a-D	Dp3
mháthar	mháthar	máthair-N	Ncfsg
.	.	.-F	Fe
An	An	an-T	Td-s
lá	lá	lá-N	Ncmsc
arna	arna	arna-S	Spc
mhárach	mhárach	márach-N	Ns-s
chuaigh	chuaigh	téigh-V	Vmis
Máire	Máire	Máire-N	Npfsc
Rua	Rua	Rua-N	Npmsc
go dtí	go dtí	go_dtí-S	Spc
na	na	na-T	Td-p
siopaí	siopaí	siopa-N	Ncmpc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
Bhaile	Bhaile	Baile-N	Npmsc
Mheánach	Mheánach	meánach-A	Aq-msc
,	,	,-F	Fi
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
dhéanadh	dhéanadh	déan-V	Vmih
sí	sí	sí-P	Pp3fsn
gach	gach	gach-D	Dq
Satharn	Satharn	Satharn-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Dónall	Dónall	Dónall-N	Npmsc
Óg	Óg	óg-A	Aq-msc
ag	ag	ag-S	Sp
bualadh	bualadh	buail-N	Nv
sliotair	sliotair	sliotar-N	Ncmsg
lena	lena	le-S	Spp-s
chamán	chamán	camán-N	Ncmsc
in aghaidh	in aghaidh	in_aghaidh-S	Spc
bhinn	bhinn	binn-N	Ncfsc
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
nuair	nuair	nuair-C	Cs
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmis
a	a	a-D	Dp3
mháthair	mháthair	máthair-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
aige	aige	ag-P	Pr3ms
nach	nach	nach-Q	Qnr
mbeadh	mbeadh	bí-V	Vmc
sí	sí	sí-P	Pp3fsn
ar ais	ar ais	ar_ais-R	Rd
go dtí	go dtí	go_dtí-S	Spc
go	go	go-U	Ua
mall	mall	mall-A	Aqp
tráthnóna	tráthnóna	tráthnóna-N	Ncmsg|Ncmsc
.	.	.-F	Fe
Shocraigh	Shocraigh	socraigh-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-Q	Q
rachadh	rachadh	téigh-V	Vmc
sé	sé	sé-P	Pp3msn
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
phónaí	phónaí	pónaí-N	Ncmsc
liath	liath	liath-A	Aq-msc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
cuairte	cuairte	cuairt-N	Ncfsg
ar	ar	ar-S	Sp
Shéarlaí	Shéarlaí	séarlaí-N	Npmsc
i	i	i-S	Sp
mBaile	mBaile	Baile-N	Npmsc
an	an	an-T	Td-s
Easa	Easa	eas-N	Ncmsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
seachtain	seachtain	seachtain-N	Ncfsc
ann	ann	i-P	Pr3ms
ó	ó	ó-C	Cs
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
tigh	tigh	teach-N	Ncmsd
Shéarlaí	Shéarlaí	Shéarlaí-N	Npmsc
roimhe	roimhe	roimh-P	Pr3ms
sin	sin	sin-P	Pd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
dúil	dúil	dúil-N	Ncfsc
lena	lena	le-S	Spp-s
uncail	uncail	uncail-N	Ncmsc
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
agus	agus	agus-C	Cc
dreas	dreas	dreas-N	Ncmpg|Ncmsc|Ncfsc|Ncfpg
marcaíochta	marcaíochta	marcaigh-N	Ncfsg|Nv--g|Ncfsg|Nv--g
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
chapall	chapall	capall-N	Ncmsc
dhubh	dhubh	dubh-A	Aq-msc
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
t	t	t-X	Xl
‑	‑	‑-F	Fb
adhastar	adhastar	adhastar-N	Ncmsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
srian	srian	srian-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
phónaí	phónaí	pónaí-N	Ncmsg
liath	liath	liath-A	Aq-msg
agus	agus	agus-C	Cc
ar	ar	ar-S	Sp
shiúl	shiúl	siúl-N	Ncmsc
leis	leis	le-P	Pr3ms
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
an	an	an-T	Td-s
ghaoth	ghaoth	gaoth-N	Ncfsc
Mhárta	Mhárta	Márta-N	Ncmsg
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Cé	Cé	cé-C	Cs
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
pónaí	pónaí	pónaí-N	Ncmsc
liath	liath	liath-A	Aq-msc
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
in	in	i-S	Sp
aois	aois	aois-N	Ncfsc
léim	léim	léim-V	Vmis
sí	sí	sí-P	Pp3fsn
thar	thar	thar-S	Sp
chlaí	chlaí	claí-N	Ncmsc
agus	agus	agus-C	Cc
thar	thar	thar-S	Sp
dhíog	dhíog	díog-N	Ncfsc
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
cat	cat	cat-X	Xfen|Ncmsc
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
Dónall	Dónall	Dónall-N	Npmsc
Óg	Óg	óg-A	Aq-msc
toit	toit	toit-N	Ncfsc
ag	ag	ag-S	Sp
éirí	éirí	éirigh-N	Nv
as	as	as-S	Sp
teach	teach	teach-N	Ncmsc
a	a	a-D	Dp3
uncail	uncail	uncail-N	Ncmsc
cois	cois	cois-S	Sp
na	na	na-T	Td-p
Banna	Banna	banna-N	Ncmsc
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
chomh	chomh	chomh-R	Ri
sásta	sásta	sásta-A	Aqp
le	le	le-S	Sp
píobaire	píobaire	píobaire-N	Ncmsc
.	.	.-F	Fe
B	B	B-X	Xl
’	’	’-F	Fa
fhada	fhada	fada-A	Aqc
leis	leis	le-P	Pr3ms
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
insint	insint	inis-N	Nv
dá	dá	do-S	Spp-s
uncail	uncail	uncail-N	Ncmsc
fá	fá	faoi-P	Pr3ms
dtaobh	dtaobh	taobh-N	Ncmsc
dá	dá	do-S	Spp-s
chuid	chuid	cuid-N	Ncfsc
oibre	oibre	obair-N	Ncfsg|Nv--g--n
leis	leis	le-S	Sp
an	an	an-T	Td-s
Traenálaí	Traenálaí	traenálaí-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
bhac	bhac	bac-V	Vmis---n
sé	sé	sé-P	Pp3msn
leis	leis	le-S	Sp
an	an	an-T	Td-s
lána	lána	lána-N	Ncmsc
a	a	a-U	U
ghlacadh	ghlacadh	glac-N	Nv
ach	ach	ach-C	Cs
ghabh	ghabh	gabh-V	Vmis
sé	sé	sé-P	Pp3msn
aicearra	aicearra	aicearra-N	Ncmsc
trasna	trasna	trasna-S	Sp
na	na	na-T	Tdfsg
páirce	páirce	páirc-N	Ncfsg
.	.	.-F	Fe
Ghríosaigh	Ghríosaigh	gríosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
seanphónaí	seanphónaí	pónaí-N	Ncmsc
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
fágtha	fágtha	fág-A	Av
idir	idir	idir-S	Sp
iad	iad	iad-P	Pp3-p
agus	agus	agus-C	Cc
teach	teach	teach-N	Ncmsc
Shéarlaí	Shéarlaí	Shéarlaí-N	Npmsc
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
t	t	t-X	Xl
‑	‑	‑-F	Fb
aon	aon	aon-M	Mc
chlaí	chlaí	claí-N	Ncmsc
amháin	amháin	amháin-A	Aqp
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
Beití	Beití	beití-N	Ncmsc
léim	léim	léim-V	Vmip1s|Ncfsc|Nv
mhór	mhór	mór-V	Vmis|Ncmpg
.	.	.-F	Fe
Faraor	Faraor	faraor-X	Xsc
géar	géar	géar-N	Ncmsc
,	,	,-F	Fi
ba	ba	is-W	Wsri
é	é	é-P	Pp3ms
seo	seo	seo-P	Pd
an	an	an-T	Td-s
chéad	chéad	céad-M	Mo
uair	uair	uair-N	Ncfsc
a	a	a-Q	Q-r
léim	léim	léim-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
claí	claí	claí-N	Ncmsc
áirithe	áirithe	áirigh-A	Aqp|Av
seo	seo	seo-D	Dd
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
dréim	dréim	dréim-N	Nv
leis	leis	le-S	Sp
an	an	an-T	Td-s
díog	díog	díog-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
taobh	taobh	taobh-N	Ncmsc
eile	eile	eile-D	Dd
.	.	.-F	Fe
Chuala	Chuala	clois-V	Vmis
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
an	an	an-T	Td-s
troistneach	troistneach	troistneach-N	Ncfsc
agus	agus	agus-C	Cc
tháinig	tháinig	tar-V	Vmis
sé	sé	sé-P	Pp3msn
amach	amach	amach-R	Rd
fá	fá	faoi-P	Pr3ms
dheifir	dheifir	deifir-N	Ncfsc
.	.	.-F	Fe
Cad	Cad	cad-W	W--q
é	é	é-P	Pp3ms
an	an	an-T	Td-s
alltacht	alltacht	alltacht-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
air	air	ar-P	Pr3ms
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
Dónall	Dónall	Dónall-N	Npmsc
Óg	Óg	óg-A	Aq-msc
gafa	gafa	gabh-A	Av
i	i	i-S	Sp
dtom	dtom	tom-N	Ncmsc
aitinn	aitinn	aiteann-N	Ncmsg
,	,	,-F	Fi
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
screadach	screadach	scread-N	Nv
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
caoineadh	caoineadh	caoin-N	Nv
le	le	le-S	Sp
huafás	huafás	uafás-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
pónaí	pónaí	pónaí-N	Ncmsc
liath	liath	liath-A	Aq-msc
bocht	bocht	bocht-A	Aq-msc
ina	ina	i-S	Spp-s|Spp-p
luí	luí	luí-N	Ncmsc
go	go	go-U	Ua
hanásta	hanásta	anásta-A	Aqp
i mbun	i mbun	i_mbun-S	Spc
na	na	na-T	Tdfsg
díge	díge	díog-N	Ncfsg
agus	agus	agus-C	Cc
a	a	a-D	Dp3
cosa	cosa	cos-N	Ncfpc
in	in	i-S	Sp
airde	airde	airde-N	Ncfpc|Ncfsc
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
le	le	le-S	Sp
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
de	de	de-S	Sp
léim	léim	léim-N	Ncfsc
sa	sa	i-S	Spa-s
díog	díog	díog-N	Ncfsc
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
sé	sé	sé-P	Pp3msn
aghaidh	aghaidh	aghaidh-N	Ncfsc
ar	ar	ar-S	Sp
Dhónall	Dhónall	Dónall-N	Npmsc
ar	ar	ar-S	Sp
dtús	dtús	tús-N	Ncmsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
cinnte	cinnte	cinnte-A	Av|Aqp
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
cnámh	cnámh	cnámh-N	Ncfsc
briste	briste	bris-A	Av
aige	aige	ag-P	Pr3ms
thóg	thóg	tóg-V	Vmis
sé	sé	sé-P	Pp3msn
suas	suas	suas-R	Rd
go	go	go-U	Ua
cúramach	cúramach	cúramach-A	Aqp
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhruach	bhruach	bruach-N	Ncmsc
é	é	é-P	Pp3ms
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
a	a	a-D	Dp3
sheaicéad	sheaicéad	seaicéad-N	Ncmsc
timpeall	timpeall	timpeall-S	Sp
air	air	ar-N	Ncmsg
chun	chun	chun-S	Sp
é	é	é-P	Pp3ms
a	a	a-U	U
choinneáil	choinneáil	coinnigh-N	Nv
teolaí	teolaí	teolaí-A	Aqp
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
d	d	d-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
le	le	le-S	Sp
cuidiú	cuidiú	cuidigh-N	Nv
leis	leis	le-S	Sp
an	an	an-T	Td-s
phónaí	phónaí	pónaí-N	Ncmsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Dónall	Dónall	Dónall-N	Npmsc
ag	ag	ag-S	Sp
caoineadh	caoineadh	caoin-N	Nv
go	go	go-U	Ua
fóill	fóill	fóill-A	Aqp
.	.	.-F	Fe
'	'	'-F	Fa
A	A	a-U	Uv
Bheití	Bheití	beití-N	Ncmsv
!	!	!-F	Fe
A	A	a-U	Uv
Bheití	Bheití	beití-N	Ncmsv
!	!	!-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Bí	Bí	bí-V	Vmm-2s
i	i	i-S	Sp
do	do	do-Q	Q
thost	thost	tost-V	Vmis
,	,	,-F	Fi
a	a	a-D	Dp3
leanbh	leanbh	leanbh-N	Ncmsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
pónaí	pónaí	pónaí-N	Ncmsc
greamaithe	greamaithe	greamaigh-A	Av
go	go	go-U	Ua
holc	holc	olc-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
.	.	.-F	Fe
Stop	Stop	stop-V	Vmis
Dónall	Dónall	Dónall-N	Npmsc
den	den	de-S	Spa-s
olagón	olagón	olagón-N	Ncmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
thuig	thuig	tuig-V	Vmip|Vmis
sé	sé	sé-P	Pp3msn
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-V	Vmis
sé	sé	sé-P	Pp3msn
síos	síos	síos-R	Rd
agus	agus	agus-C	Cc
a	a	a-D	Dp3
chroí	chroí	croí-N	Ncmsc
ina	ina	i-S	Spp-s
bhéal	bhéal	béal-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
deacracht	deacracht	deacracht-N	Ncfsc
ag	ag	ag-S	Sp
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
an	an	an-T	Td-s
pónaí	pónaí	pónaí-N	Ncmsc
a	a	a-U	U
chur	chur	cuir-N	Nv
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
cosa	cosa	cos-N	Ncfpc
mar	mar	mar-C	Cs
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
ceaptha	ceaptha	ceap-A	Av
idir	idir	idir-S	Sp
tortóga	tortóga	tortóg-N	Ncfpc
móra	móra	mór-A	Aq--pv|Aq--pg|Aq--pc
.	.	.-F	Fe
Bhrúigh	Bhrúigh	brúigh-V	Vmis
sé	sé	sé-P	Pp3msn
agus	agus	agus-C	Cc
tharraing	tharraing	tarraing-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
t	t	t-X	Xl
‑	‑	‑-F	Fb
allas	allas	allas-N	Ncmsc
ag	ag	ag-S	Sp
titim	titim	tit-N	Nv
de	de	de-P	Pr3ms
,	,	,-F	Fi
é	é	é-P	Pp3ms
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
an	an	an-T	Td-s
pónaí	pónaí	pónaí-N	Ncmsg|Ncmsc
ina	ina	i-S	Spp-s|Spp-p
líbíní	líbíní	líbín-N	Ncmpc
báite	báite	báigh-A	Av
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
dreach	dreach	dreach-N	Ncmsc
an	an	an-T	Td-s
bháis	bháis	bás-N	Ncmsg
ar	ar	ar-S	Sp
Dhónall	Dhónall	Dónall-N	Npmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
eagla	eagla	eagla-N	Ncfsc
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhruach	bhruach	bruach-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
sa	sa	i-S	Spa-s
deireadh	deireadh	deireadh-N	Ncmsc
,	,	,-F	Fi
d	d	d-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmm-2s
leis	leis	le-S	Sp
an	an	an-T	Td-s
phónaí	phónaí	pónaí-N	Ncmsg
na	na	na-T	Td-p
cosa	cosa	cos-N	Ncfpc
a	a	a-U	U
chur	chur	cuir-N	Nv
fúithi	fúithi	faoi-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
t	t	t-X	Xl
‑	‑	‑-F	Fb
ainmhí	ainmhí	ainmhí-N	Ncmsc
bocht	bocht	bocht-A	Aq-msc
tugtha	tugtha	tugtha-A	Av|Aqp
traochta	traochta	traoch-A	Aqp|Av
,	,	,-F	Fi
ach	ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
slán	slán	slán-A	Aqp
.	.	.-F	Fe
Mhothaigh	Mhothaigh	mothaigh-V	Vmis
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
cosa	cosa	cos-N	Ncfpc
an	an	an-T	Td-s
phónaí	phónaí	pónaí-N	Ncmsg
go	go	go-U	Ua
cúramach	cúramach	cúramach-A	Aqp
le	le	le-S	Sp
bheith	bheith	bí-N	Nv
cinnte	cinnte	cinn-A	Av
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
sí	sí	sí-P	Pp3fsn
gortaithe	gortaithe	gortaigh-A	Av
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmis
sé	sé	sé-P	Pp3msn
óna	óna	ó-S	Spp-s|Spp-p
leathghlúin	leathghlúin	leathghlúin-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
sí	sí	sí-P	Pp3fsn
ceart	ceart	ceart-A	Aqp
go leor	go leor	go_leor-A	Aq
,	,	,-F	Fi
buíochas	buíochas	buíochas-N	Ncmsc
do	do	do-S	Sp
Dhia	Dhia	dia-N	Ncmsc
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
agus	agus	agus-C	Cc
crith	crith	crith-V	Vmm-2s
ina	ina	i-S	Spp-s
ghlór	ghlór	glór-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Dá	Dá	dá-C	Cs
mbeadh	mbeadh	bí-V	Vmc
clocha	clocha	cloch-N	Ncfpc
sa	sa	i-S	Spa-s
díog	díog	díog-N	Ncfsc
bheadh	bheadh	bí-V	Vmc
a	a	a-D	Dp3
droim	droim	droim-N	Ncmsc
briste	briste	bris-A	Aqp|Av
.	.	.-F	Fe
'	'	'-F	Fa
Ghlan	Ghlan	Glan-N	Npmsc
sé	sé	sé-W	Wp-i-3|Pp3msn
a	a	a-D	Dp3
lámha	lámha	lámh-N	Ncfpc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
fhéar	fhéar	féar-N	Ncmsc
fhliuch	fhliuch	fliuch-A	Aq-msc
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
leis	leis	le-S	Sp
an	an	an-T	Td-s
pónaí	pónaí	pónaí-N	Ncmsc
isteach	isteach	isteach-R	Rd
chun	chun	chun-S	Sp
an	an	an-T	Td-s
stábla	stábla	stábla-N	Ncmsg
.	.	.-F	Fe
Nigh	Nigh	nigh-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
pónaí	pónaí	pónaí-N	Ncmsc
go	go	go-U	Ua
gasta	gasta	gasta-A	Aqp
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
uisce	uisce	uisce-N	Ncmsc
agus	agus	agus-C	Cc
coirce	coirce	coirce-N	Ncmsg|Ncmsc
di	di	do-P	Pr3fs
.	.	.-F	Fe
'	'	'-F	Fa
Shíl	Shíl	síl-V	Vmis
mé	mé	mé-P	Pp1-s
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
do	do	do-S	Sp
phort	phort	port-N	Ncmsc
seinnte	seinnte	seinn-A	Av
ansin	ansin	ansin-R	Rt|Rl
,	,	,-F	Fi
a	a	a-U	Uv
chapaillín	chapaillín	capaillín-N	Ncmsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
go	go	go-U	Ua
cineálta	cineálta	cineálta-A	Aqp
le	le	le-S	Sp
Beití	Beití	beití-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Ach	Ach	ach-C	Cs
beidh	beidh	bí-V	Vmif
tú	tú	tú-P	Pp2-s
go	go	go-U	Ua
breá	breá	breá-A	Aqp
.	.	.-F	Fe
'	'	'-F	Fa
Chuir	Chuir	cuir-V	Vmis
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
Dónall	Dónall	Dónall-N	Npmsc
ina	ina	i-S	Spp-s
shuí	shuí	suí-N	Ncmsc
in aice	in aice	in_aice-S	Spc
na	na	na-T	Tdfsg
tine	tine	tine-N	Ncfsg
sa	sa	i-S	Spa-s
teach	teach	teach-N	Ncmsc
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
sé	sé	sé-P	Pp3msn
muga	muga	muga-N	Ncmsc
mór	mór	mór-A	Aq-msc
tae	tae	tae-N	Ncmsg|Ncmsc
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
chuma	chuma	cuma-N	Ncfsc
ar	ar	ar-S	Sp
Dhónall	Dhónall	Dónall-N	Npmsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
corraithe	corraithe	corraigh-A	Av
go	go	go-U	Ua
fóill	fóill	fóill-A	Aqp
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
crua	crua	crua-N	Ncmsg|Ncfsg
air	air	ar-N	Ncmsg
cluain	cluain	cluain-N	Ncfsc
a	a	a-U	U
choinneáil	choinneáil	coinnigh-N	Nv
ar	ar	ar-S	Sp
na	na	na-T	Td-p
deora	deora	deoir-N	Ncfpc
.	.	.-F	Fe
'	'	'-F	Fa
Caithfidh	Caithfidh	caith-V	Vmif
tú	tú	tú-P	Pp2-s
a	a	a-U	U
bheith	bheith	bí-N	Nv
cróga	cróga	cróga-A	Aqp
,	,	,-F	Fi
a	a	a-U	Uv
Dhónaill	Dhónaill	Dónall-N	Npm-v
,	,	,-F	Fi
’	’	’-F	Fa
'	'	'-F	Fa
Nach	Nach	nach-Q	Qnr
dtiteann	dtiteann	tit-V	Vmip
gach	gach	gach-D	Dq
aon	aon	aon-D	Dq
inteacht	inteacht	teacht-N	Ncmsc
?	?	?-F	Fq
Sin	Sin	sin-W	W
cuid	cuid	cuid-N	Ncfsc
den	den	de-S	Spa-s
arsa	arsa	arsa-V	Vmis
Séarlaí	Séarlaí	Séarlaí-N	Npmsc
.	.	.-F	Fe
mharcach	mharcach	marcach-N	Ncmsc
am	am	am-N	Ncmsc
traenáil	traenáil	traenáil-N	Ncfsc|Nv
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Ach	Ach	ach-C	Cs
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
faoi	faoi	faoi-P	Pr3ms
mo	mo	mo-D	Dp1-s
mháthair	mháthair	máthair-N	Ncfsc
?	?	?-F	Fq
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
níos	níos	níos-U	Uc
mó	mó	mór-A	Aqc
eagla	eagla	eagla-N	Ncfsg
air	air	ar-N	Ncmsg|Pr3ms|Ncmsg
roimh	roimh	roimh-S	Sp
a	a	a-D	Dp3
mháthair	mháthair	máthair-N	Ncfsc
ná	ná	ná-C	Cc
roimh	roimh	roimh-S	Sp
thitim	thitim	tit-N	Nv
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
t	t	t-X	Xl
‑	‑	‑-F	Fb
uncail	uncail	uncail-N	Ncmsc
suas	suas	suas-R	Rd
a	a	a-D	Dp3
dhá	dhá	dó-M	Mc
lámh	lámh	lámh-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
Ná	Ná	ná-Q	Qnm
habair	habair	abar-N	Ncmpc
a	a	a-Q	Q-r
dhath	dhath	dath-V	Vmis
faoi	faoi	faoi-P	Pr3ms
.	.	.-F	Fe
Gabh	Gabh	gabh-V	Vmm-2s
tusa	tusa	tú-P	Pp2-s-e
ar ais	ar ais	ar_ais-R	Rd
go	go	go-S	Sp
Coill	Coill	Coill-N	Npmsc
na	na	na-T	Td-p
Baice	Baice	Baice-N	Npmsc
tráthnóna	tráthnóna	tráthnóna-N	Ncmsg|Ncmsc
Dé	Dé	Dé-N	Ns-s
Luain	Luain	Luan-N	Ncmsg
,	,	,-F	Fi
mar	mar	mar-C	Cs
is	is	is-W	Wpri
gnách	gnách	gnách-A	Aqp
.	.	.-F	Fe
Siúil	Siúil	siúl-N	Ncmsg
leat	leat	le-P	Pr2-s
,	,	,-F	Fi
a	a	a-D	Dp3
leanbh	leanbh	leanbh-N	Ncmsc
,	,	,-F	Fi
agus	agus	agus-C	Cc
glan	glan	glan-V	Vmm-2s
tú	tú	tú-P	Pp2-s
féin	féin	féin-P	Px
.	.	.-F	Fe
'	'	'-F	Fa
Tábhairne	Tábhairne	tábhairne-N	Ncmsc
an	an	an-T	Td-s
Tairbh	Tairbh	tarbh-N	Ncmsg
Dhuibh	Dhuibh	Duibh-N	Npfsg
Maidin	Maidin	maidin-N	Ncfsc
Dé	Dé	Dé-N	Ns-s
Luain	Luain	Luan-N	Ncmsg
bhí	bhí	bí-V	Vmis
Dónall	Dónall	Dónall-N	Npmsc
Óg	Óg	óg-A	Aq-msc
agus	agus	agus-C	Cc
William	William	William-N	Npmsg|Npmsc
ag	ag	ag-S	Sp
glanadh	glanadh	glan-N	Nv
amach	amach	amach-R	Rd
na	na	na-T	Td-p
stáblaí	stáblaí	stábla-N	Ncmpg|Ncmpc
,	,	,-F	Fi
mar	mar	mar-C	Cs
ba	ba	is-W	Wsri
ghnách	ghnách	gnách-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Dónall	Dónall	Dónall-N	Npmsc
ag	ag	ag-S	Sp
breathnú	breathnú	breathnaigh-N	Nv
amach	amach	amach-R	Rd
ar	ar	ar-S	Sp
na	na	na-T	Td-p
páirceanna	páirceanna	páirc-N	Ncfpc
móra	móra	mór-A	Aq--pc
glasa	glasa	glas-A	Aq--pc
agus	agus	agus-C	Cc
ar	ar	ar-S	Sp
na	na	na-T	Td-p
capaill	capaill	capall-N	Ncmsg
bhreátha	bhreátha	breá-A	Aq-fsv
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
le	le	le-S	Sp
feiceáil	feiceáil	feic-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
súil	súil	súil-N	Nv-----n
go	go	go-U	Ua
mór	mór	mór-A	Aqp
le	le	le-S	Sp
fáil	fáil	faigh-N	Nv
sa	sa	i-S	Spa-s
diallait	diallait	diallait-N	Ncfsc
ar	ar	ar-S	Sp
cheann	cheann	ceann-N	Ncmsc
de	de	de-S	Sp
na	na	na-T	Td-p
capaill	capaill	capall-N	Ncmpc
rása	rása	rás-N	Ncmsg
.	.	.-F	Fe
'	'	'-F	Fa
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liom	liom	le-P	Pr1-s
marcaíocht	marcaíocht	marcaigh-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
chapall	chapall	capall-N	Ncmsc
bhán	bhán	bán-A	Aq-msc
sin	sin	sin-D	Dd
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
le	le	le-S	Sp
William	William	William-N	Npmsc
.	.	.-F	Fe
Rinne	Rinne	déan-V	Vmis
William	William	William-N	Npmsc
draothadh	draothadh	draothadh-N	Ns-s
gáire	gáire	gáir-N	Ncfsg|Nv|Ncmsg|Ncmsc|Nv--g
.	.	.-F	Fe
'	'	'-F	Fa
Ná	Ná	ná-Q	Qnm
gabh	gabh	gabh-V	Vmm-2s-n
in aice	in aice	in_aice-S	Spc
léi	léi	le-P	Pr3fs
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
sí	sí	sí-P	Pp3fsn
neirbhíseach	neirbhíseach	neirbhíseach-A	Aqp
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
‑	‑	‑-F	Fb
deacair	deacair	deacair-N	Ncfsc
a	a	a-U	U
smachtú	smachtú	smachtaigh-N	Nv
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
go leor	go leor	go_leor-A	Aq|Ns-s|Rg
capall	capall	capall-N	Ncmpg
eile	eile	eile-D	Dd
ann	ann	i-R	Rl|Pr3ms
seachas	seachas	seachas-S	Sp
ise	ise	í-P	Pp3fs-e
.	.	.-F	Fe
Gheobhaidh	Gheobhaidh	faigh-V	Vmif
tú	tú	tú-P	Pp2-s
do	do	do-S	Sp
seans	seans	seans-N	Ncmsc
luath	luath	luath-A	Aq-msc
go leor	go leor	go_leor-A	Aq
.	.	.-F	Fe
Caithfidh	Caithfidh	caith-V	Vmif
tú	tú	tú-P	Pp2-s
a	a	a-U	U
bheith	bheith	bí-N	Nv
foighneach	foighneach	foighneach-A	Aqp
.	.	.-F	Fe
'	'	'-F	Fa
I	I	i-S	Sp
ndiaidh	ndiaidh	diaidh-N	Ns-s
na	na	na-T	Tdfsg
hoibre	hoibre	obair-N	Ncfsg
thug	thug	tabhair-V	Vmis
William	William	William-N	Npmsc
leis	leis	le-P	Pr3ms
Dónall	Dónall	Dónall-N	Npmsc
Óg	Óg	óg-A	Aq-msc
síos	síos	síos-R	Rd
chuig	chuig	chuig-S	Sp
Tábhairne	Tábhairne	tábhairne-N	Ncmsc
an	an	an-T	Td-s
Tairbh	Tairbh	tarbh-N	Ncmsg
Dhuibh	Dhuibh	Duibh-N	Npfsg
i	i	i-S	Sp
gCoill	gCoill	coll-N	Ncfsc|Ncmpc
na	na	na-T	Td-p
Baice	Baice	Baice-N	Npmsc
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
socraithe	socraithe	socraigh-A	Av
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
acu	acu	ag-P	Pr3-p
ag	ag	ag-S	Sp
imirt	imirt	imir-N	Nv
snúcair	snúcair	snúcar-N	Ncmsg
ag	ag	ag-S	Sp
tábla	tábla	tábla-N	Ncmsc
beag	beag	beag-A	Aq-msc
sa	sa	i-S	Spa-s
chúlsheomra	chúlsheomra	chúlsheomr-N	Ncmpc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
gasúir	gasúir	gasúr-N	Ncmpc
ó	ó	ó-S	Sp
stáblaí	stáblaí	stábla-N	Ncmpc
eile	eile	eile-D	Dd
an	an	an-T	Td-s
Traenálaí	Traenálaí	traenálaí-N	Ncmsg
Mhóir	Mhóir	mór-A	Aq-msg
ag	ag	ag-S	Sp
imirt	imirt	imir-N	Nv
ag	ag	ag-S	Sp
an	an	an-T	Td-s
phríomhthábla	phríomhthábla	tábla-N	Ncfsc
agus	agus	agus-C	Cc
gach	gach	gach-D	Dq
aon	aon	aon-D	Dq
rois	rois	ros-N	Ncfsc|Ncmpc
de	de	de-S	Sp
mhionnaí	mhionnaí	mionn-N	Ncmpc
móra	móra	mór-A	Aq--pc
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Bheannaigh	Bheannaigh	beannaigh-V	Vmis
siad	siad	siad-P	Pp3-pn
go	go	go-U	Ua
beoga	beoga	beoga-A	Aqp
do	do	do-S	Sp
William	William	William-N	Npmsc
ach	ach	ach-C	Cs
níor	níor	is-W	Ws-in
thug	thug	tabhair-V	Vmis
siad	siad	siad-P	Pp3-pn
aird	aird	aird-N	Ncfsc
dá	dá	do-S	Spp-s|Spp-p
laghad	laghad	laghad-N	Ncmsc
ar	ar	ar-S	Sp
Dhónall	Dhónall	Dónall-N	Npmsc
Óg	Óg	óg-A	Aq-msc
.	.	.-F	Fe
Cé	Cé	cé-C	Cs
gur	gur	is-W	Wsdi|Wpdi
mar	mar	mar-C	Cs|Sp
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
a	a	a-Q	Q-r
chaithidís	chaithidís	caith-V	Vmih3p
leis	leis	le-P	Pr3ms
ag	ag	ag-S	Sp
stáblaí	stáblaí	stábla-N	Ncmpc
an	an	an-T	Td-s
Traenálaí	Traenálaí	traenálaí-N	Ncmsg
Mhóir	Mhóir	mór-A	Aq-msg
chuir	chuir	cuir-V	Vmis
a	a	a-D	Dp3
n	n	n-X	Xl
‑	‑	‑-F	Fb
iompar	iompar	iompair-N	Ncmsc|Nv
sa	sa	i-S	Spa-s
tábhairne	tábhairne	tábhairne-N	Ncmsc
míshuaimhneas	míshuaimhneas	míshuaimhneas-N	Ncmpg|Ncmsc
ar	ar	ar-S	Sp
Dhónall	Dhónall	Dónall-N	Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
pictiúr	pictiúr	pictiúr-N	Ncmsc
de	de	de-S	Sp
bhanríon	bhanríon	banríon-N	Ncfsc
agus	agus	agus-C	Cc
de	de	de-S	Sp
bhrat	bhrat	brat-N	Ncmsc
Shasana	Shasana	Sasana-N	Npfsc|Npmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhalla	bhalla	balla-N	Ncmsg
fosta	fosta	fosta-A	Aqp
,	,	,-F	Fi
rud	rud	rud-N	Ncmsc
nach	nach	nach-Q	Qnr
bhfeicfeadh	bhfeicfeadh	feic-V	Vmc
Dónall	Dónall	Dónall-N	Npmsc
Óg	Óg	óg-A	Aq-msc
sa	sa	i-S	Spa-s
bhaile	bhaile	baile-N	Ncmsc
fá	fá	faoi-P	Pr3ms
Dhroichead	Dhroichead	droichead-N	Ncmsc
Thuama	Thuama	Tuama-N	Npfsg
riamh	riamh	riamh-R	Rg
.	.	.-F	Fe
Thuig	Thuig	tuig-V	Vmis
Dónall	Dónall	Dónall-N	Npmsc
go	go	go-U	Ua
maith	maith	maith-A	Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
in	in	i-S	Sp
áit	áit	áit-N	Ncfsc
nár	nár	nár-W	Wsrin|Wsdin|Wssin|Qn-s|Qnrs
bhain	bhain	bain-V	Vmis|Vmis---n|Npmsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Smaoinigh	Smaoinigh	smaoinigh-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
na	na	na-T	Td-p
rudaí	rudaí	rud-N	Ncmpc
a	a	a-Q	Q-r
deireadh	deireadh	abair-V	Vmih
a	a	a-D	Dp3
mháthair	mháthair	máthair-N	Ncfsc
fá	fá	faoi-P	Pr3ms
mhuintir	mhuintir	muintir-N	Ncfsc
Choill	Choill	Coill-N	Npfsg
na	na	na-T	Td-p
Baice	Baice	Baice-N	Npmsc
.	.	.-F	Fe
B	B	B-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
gurbh	gurbh	is-W	Wsdi
fhíor	fhíor	fíor-A	Aqp
di	di	do-P	Pr3fs
fá	fá	faoi-P	Pr3ms
iad	iad	iad-P	Pp3-p
a	a	a-U	U
bheith	bheith	bí-N	Nv
coimhthíoch	coimhthíoch	coimhthíoch-A	Aqp
!	!	!-F	Fe
Ba	Ba	is-W	Ws|Ws-i
mhór	mhór	mór-A	Aqp
an	an	an-T	Td-s
faoiseamh	faoiseamh	faoiseamh-N	Ncmsc
dó	dó	do-P	Pr3ms
sa	sa	i-S	Spa-s
deireadh	deireadh	deireadh-N	Ncmsc
an	an	an-T	Td-s
teach	teach	teach-N	Ncmsc
tábhairne	tábhairne	tábhairne-N	Ncmsg|Ncmsc
a	a	a-U	U
fhágáil	fhágáil	fág-N	Nv
agus	agus	agus-C	Cc
an	an	an-T	Td-s
baile	baile	baile-N	Ncmsc
a	a	a-U	U
bhaint	bhaint	bain-N	Nv
amach	amach	amach-R	Rd
.	.	.-F	Fe
Iontach	Iontach	iontach-R	Ri
Sásta	Sásta	sásta-A	Aqp
In	In	sin-P	Pd
ainneoin	ainneoin	ainneoin-C	Cs
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
Dónall	Dónall	Dónall-N	Npmsc
ina	ina	i-S	Spp-s
éan	éan	éan-N	Ncmsc
sna	sna	i-S	Spa-p
stáblaí	stáblaí	stábla-N	Ncmpc
i	i	i-S	Sp
gCoill	gCoill	coll-N	Ncfsc|Ncmpc
na	na	na-T	Td-p
Baice	Baice	Baice-N	Npmsc
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
baint	baint	bain-N	Nv
taitnimh	taitnimh	taitin-N	Ncmsg|Nv--g
as	as	as-S	Sp
an	an	an-T	Td-s
obair	obair	obair-N	Ncfsc
.	.	.-F	Fe
Tráthnóna	Tráthnóna	tráthnóna-N	Ncmsc
amháin	amháin	amháin-A	Aqp
,	,	,-F	Fi
mí	mí	mí-N	Ncfsc|Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|Dd
,	,	,-F	Fi
tháinig	tháinig	tar-V	Vmis
an	an	an-T	Td-s
Traenálaí	Traenálaí	traenálaí-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
de	de	de-S	Sp
rúid	rúid	rúid-N	Ncfsc
isteach	isteach	isteach-R	Rd
sna	sna	i-S	Spa-p
stáblaí	stáblaí	stábla-N	Ncmpc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
iarr	iarr	iarr-V	Vmis
ar	ar	ar-S	Sp
William	William	William-N	Npmsc
ceann	ceann	ceann-N	Ncmpg
de	de	de-S	Sp
na	na	na-T	Td-p
capaill	capaill	capall-N	Ncmpc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
réidh	réidh	réidh-A	Aqp
.	.	.-F	Fe
Capall	Capall	capall-N	Ncmsc
donn	donn	donn-A	Aq-msc
le	le	le-S	Sp
moing	moing	moing-N	Ncfsc
fhada	fhada	fada-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sa	sa	i-S	Spa-s
chapall	chapall	capall-N	Ncmsc
seo	seo	seo-D	Dd
,	,	,-F	Fi
capall	capall	capall-N	Ncmsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
go leor	go leor	go_leor-A	Aq|Ns-s|Rg
rásaí	rásaí	rásaí-N	Ncmpg|Ncmsg|Ncmpg|Ncmsg
bainte	bainte	bain-A	Av
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
'	'	'-F	Fa
Seo	Seo	seo-W	W
capall	capall	capall-N	Ncmsc
maith	maith	maith-A	Aq-msc
,	,	,-F	Fi
a	a	a-U	Uv
ghasúir	ghasúir	gasúr-N	Ncmsv
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
Traenálaí	Traenálaí	traenálaí-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
le	le	le-S	Sp
Dónall	Dónall	Dónall-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Beidh	Beidh	bí-V	Vmif
William	William	William-N	Npmsc
ábalta	ábalta	ábalta-A	Aqp
a	a	a-U	U
insint	insint	inis-N	Nv
duit	duit	do-P	Pr2-s
fán	fán	faoi-S	Spa-s
dóigh	dóigh	dóigh-N	Ncfsc
le	le	le-S	Sp
dul	dul	téigh-N	Nv
sa	sa	i-S	Spa-s
diallait	diallait	diallait-N	Ncfsc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
cosa	cosa	cos-N	Ncfpc
a	a	a-U	U
shocrú	shocrú	socraigh-N	Nv
i	i	i-S	Sp
gceart	gceart	ceart-N	Ncmsc
sna	sna	i-S	Spa-p
stíoróipí	stíoróipí	stíoróip-N	Ncfpc
.	.	.-F	Fe
Thig	Thig	tar-V	Vmip
leat	leat	le-P	Pr2-s
sodar	sodar	sodar-N	Ncmsc
gairid	gairid	gairid-A	Aq-msc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
le	le	le-S	Sp
dul	dul	téigh-N	Nv
i	i	i-S	Sp
dtaithí	dtaithí	taithí-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
chapall	chapall	capall-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
Traenálaí	Traenálaí	traenálaí-N	Ncmsc
Mór	Mór	mór-A	Aq-msc
ar	ar	ar-S	Sp
tí	tí	tí-N	Ncfsc
imeacht	imeacht	imigh-N	Ncmsc|Nv
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhuail	bhuail	buail-V	Vmis
smaoineamh	smaoineamh	smaoinigh-N	Ncmsc|Nv
é	é	é-P	Pp3ms
.	.	.-F	Fe
'	'	'-F	Fa
Fan	Fan	fan-V	Vmm-2s
bomaite	bomaite	bomaite-N	Ncmsc
,	,	,-F	Fi
a	a	a-U	Uv
ghasúir	ghasúir	gasúr-N	Ncmsv
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
capall	capall	capall-N	Ncmsc
rása	rása	rás-N	Ncmsg
nua	nua	nua-A	Aqp
ceannaithe	ceannaithe	ceannaigh-A	Av
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
Beidh	Beidh	bí-V	Vmif
giolla	giolla	giolla-N	Ncmsc
de	de	de-S	Sp
dhíth	dhíth	díth-N	Ncfsc
orm	orm	ar-P	Pr1-s
chun	chun	chun-S	Sp
aire	aire	aire-N	Ncfsg|Ncmsg
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
dó	dó	do-P	Pr3ms
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
a	a	a-U	U
thraenáil	thraenáil	traenáil-N	Nv
.	.	.-F	Fe
Feicim	Feicim	feic-V	Vmip1s
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
go	go	go-U	Ua
maith	maith	maith-A	Aqp
i gceann	i gceann	i_gceann-S	Spc
do	do	do-D	Dp2-s
chuid	chuid	cuid-N	Ncfsc
oibre	oibre	obair-N	Ncfsg|Nv--g--n
.	.	.-F	Fe
An	An	an-Q	Qq
mbeifeá	mbeifeá	bí-V	Vmc-2s
sásta	sásta	sásta-A	Aqc
an	an	an-T	Td-s
tseachtain	tseachtain	seachtain-N	Ncfsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
a	a	a-U	U
oibriú	oibriú	oibrigh-N	Nv
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bheas	bheas	bí-V	Vmif---r
an	an	an-T	Td-s
scoil	scoil	scoil-N	Ncfsc
druidte	druidte	druid-A	Av
sa	sa	i-S	Spa-s
samhradh	samhradh	samhradh-N	Ncmsc
?	?	?-F	Fq
'	'	'-F	Fa
'	'	'-F	Fa
Iontach	Iontach	iontach-R	Ri
sásta	sásta	sásta-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Dónall	Dónall	Dónall-N	Npmsc
Óg	Óg	óg-A	Aq-msc
,	,	,-F	Fi
agus	agus	agus-C	Cc
gliondar	gliondar	gliondar-N	Ncmpg|Ncmsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
chroí	chroí	croí-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
míle	míle	míle-M	Mc
maith	maith	maith-N	Ncfsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
dhuine	dhuine	duine-N	Ncmsv
uasail	uasail	uasal-A	Aq-msv|Aq-msg
.	.	.-F	Fe
'	'	'-F	Fa
