 Ard	Ard	-X	Xx
an	an	an-T	Td-s
Chnámharlaigh	Chnámharlaigh	cnámharlach-N	Ncmpc
.	.	.-F	Fe
B	B	B-X	Xl
’	’	’-F	Fa
fhada	fhada	fada-A	Aqc
ó	ó	ó-C	Cs
bhí	bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
thíos	thíos	thíos-R	Rd
Faoi	Faoi	faoi-S	Sp
na	na	na-T	Td-p
Beanna	Beanna	beann-N	Ncfpc
.	.	.-F	Fe
Blianta	Blianta	bliain-N	Ncfpc
,	,	,-F	Fi
b	b	b-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
.	.	.-F	Fe
ó	ó	ó-C	Cs
,	,	,-F	Fi
blianta	blianta	bliain-N	Ncfpc
,	,	,-F	Fi
cinnte	cinnte	cinn-A	Aqp|Av
.	.	.-F	Fe
'	'	'-F	Fa
Faoi	Faoi	faoi-S	Sp
na	na	na-T	Td-p
Beanna	Beanna	beann-N	Ncfpc
’	’	’-F	Fa
t	t	t-X	Xl
‑	‑	‑-F	Fb
ainm	ainm	ainm-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
againn	againn	ag-P	Pr1-p
ar	ar	ar-S	Sp
an	an	an-T	Td-s
phíosa	phíosa	píosa-N	Ncmsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
síneadh	síneadh	sín-N	Nv
ó	ó	ó-S	Sp
bhun	bhun	bun-N	Ncmsc
na	na	na-T	Td-p
mbeann	mbeann	beann-N	Ncfpg
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
cladach	cladach	cladach-N	Ncmsc
.	.	.-F	Fe
Na	Na	na-T	Td-p
beanna	beanna	beann-N	Ncfpc
seo	seo	seo-D	Dd
,	,	,-F	Fi
tá	tá	bí-V	Vmip
siad	siad	siad-P	Pp3-pn
thart	thart	thart-R	Rd
fá	fá	faoi-P	Pr3ms
dhá	dhá	dó-M	Mc
fhichead	fhichead	fiche-N	Ncmsg
troigh	troigh	troigh-N	Ncfsc
ar	ar	ar-S	Sp
airde	airde	airde-N	Ncfpc|Ncfsc
agus	agus	agus-C	Cc
gan	gan	gan-S	Sp
ach	ach	ach-S	Sp
cosán	cosán	cosán-N	Ncmsc
cúng	cúng	cúng-A	Aq-msc
coise	coise	cos-N	Ncfsg
síos	síos	síos-R	Rd
go	go	go-S	Sp
dtína	dtína	dtín-N	Ncfpc
.	.	.-F	Fe
Mar	Mar	mar-C	Cs
sin	sin	sin-W	W
de	de	de-P	Pr3ms
,	,	,-F	Fi
rinne	rinne	déan-V	Vmis
na	na	na-T	Td-p
beanna	beanna	beann-N	Ncfpc
seo	seo	seo-D	Dd
idirdhealú	idirdhealú	idirdhealaigh-N	Ncmsc|Nv
idir	idir	idir-S	Sp
an	an	an-T	Td-s
chuid	chuid	cuid-N	Ncfsc
sin	sin	sin-D	Dd
den	den	de-S	Spa-s
fheirm	fheirm	feirm-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
taobh	taobh	taobh-N	Ncmsc
thíos	thíos	thíos-R	Rd
díobh	díobh	de-P	Pr3-p
agus	agus	agus-C	Cc
an	an	an-T	Td-s
chuid	chuid	cuid-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ar	ar	ar-S	Sp
uachtar	uachtar	uachtar-N	Ncmsc
.	.	.-F	Fe
Beag	Beag	beag-N	Ncmsc
is	is	agus-W	Wp-i|Wpri|Cc
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Faoi	Faoi	faoi-S	Sp
na	na	na-T	Td-p
Beanna	Beanna	beann-N	Ncfpc
bhí	bhí	bí-V	Vmis
a	a	a-D	Dp3
ainm	ainm	ainm-N	Ncmsc
féin	féin	féin-P	Px
ar	ar	ar-S	Sp
achan	achan	gach-D	Dq
phíosa	phíosa	píosa-N	Ncmsc
de	de	de-P	Pr3ms
.	.	.-F	Fe
Ceann	Ceann	ceann-N	Ncmsc
de	de	de-S	Sp
na	na	na-T	Td-p
píosaí	píosaí	píosa-N	Ncmpc
sin	sin	sin-D	Dd
ba	ba	is-W	Wsri
ea	ea	ea-P	Pp3-s
Ard	Ard	ard-N	Ncmsc
an	an	an-T	Td-s
Chnámharlaigh	Chnámharlaigh	cnámharlach-N	Ncmsg
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
thuig	thuig	tuig-V	Vmip---n|Vmis---n
mé	mé	mé-P	Pp1-s
riamh	riamh	riamh-R	Rg
ná	ná	ná-C	Cs
níor	níor	is-W	Ws-in
chuala	chuala	cual-N	Ncmpv
mé	mé	mé-P	Pp1-s
riamh	riamh	riamh-R	Rg
cad	cad	cad-P	Pq|W--q
chuige	chuige	chuig-P	Pr3ms
ar	ar	ar-Q	Q-is
tugadh	tugadh	tabhair-V	Vmis0
t	t	t-X	Xl
‑	‑	‑-F	Fb
ainm	ainm	ainm-N	Ncmsc
sin	sin	sin-P	Pd|W|Dd
air	air	ar-P	Pr3ms
nó	nó	nó-C	Cc
ní	ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
mise	mise	mé-P	Pp1-s-e
riamh	riamh	riamh-R	Rg
aon	aon	aon-D	Dq
rian	rian	rian-N	Ncmsc
de	de	de-S	Sp
chnámharlach	chnámharlach	cnámharlach-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
ardán	ardán	ardán-N	Ncmsc
chéanna	chéanna	céanna-A	Aqp
.	.	.-F	Fe
Ardán	Ardán	ardán-N	Ncmsc
creagach	creagach	creagach-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
agus	agus	agus-C	Cc
crainn	crainn	crann-N	Ncmpc
choill	choill	coill-V	Vmis
ag	ag	ag-S	Sp
fás	fás	fás-N	Nv
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Mar	Mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
is	is	is-W	Wp-i
annamh	annamh	annamh-A	Aqp
a	a	a-Q	Q-r
chuaigh	chuaigh	téigh-V	Vmis
muid	muid	muid-P	Pp1-p
a	a	a-D	Dp3
chóir	chóir	cóir-N	Ns-s
.	.	.-F	Fe
Le	Le	le-S	Sp
himeacht	himeacht	imigh-N	Nv
ama	ama	ama-N	Ncmsg|Ncmsc
stad	stad	stad-N	Nv|Ncmsc|Nv--g|Ncmsg|Nv--g|Nv|Ncmsg
an	an	an-T	Td-s
churaíocht	churaíocht	curaíocht-N	Ncfsc
.	.	.-F	Fe
Stad	Stad	stad-V	Vmis
muid	muid	muid-P	Pp1-p
a	a	a-U	U
bhaint	bhaint	bain-N	Nv
úsáide	úsáide	úsáid-N	Nv--g|Ncfsg|Nv--g
as	as	as-S	Sp
an	an	an-T	Td-s
talamh	talamh	talamh-N	Ncfsc
.	.	.-F	Fe
Stad	Stad	stad-V	Vmis
muid	muid	muid-P	Pp1-p
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
síos	síos	síos-R	Rd
Faoi	Faoi	faoi-S	Sp
na	na	na-T	Td-p
Beanna	Beanna	beann-N	Ncfpc
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
blianta	blianta	bliain-N	Ncfpc
thart	thart	thart-R	Rd
.	.	.-F	Fe
Fuair	Fuair	faigh-V	Vmis
mo	mo	mo-D	Dp1-s
mhuintir	mhuintir	muintir-N	Ncfsc
bás	bás	bás-N	Ncmsc
.	.	.-F	Fe
Druideadh	Druideadh	druid-V	Vmis0
an	an	an-T	Td-s
teach	teach	teach-N	Ncmsc
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
Faoi	Faoi	faoi-S	Sp
na	na	na-T	Td-p
Beanna	Beanna	beann-N	Ncfpc
i	i	i-S	Sp
bhfiáin	bhfiáin	fián-N	Ncmsg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhás	fhás	fás-N	Ncmsc
slatacha	slatacha	slatach-A	Aq--pc
dubha	dubha	dubh-A	Aq--pc
,	,	,-F	Fi
crainn	crainn	crann-N	Ncmpc
choill	choill	coill-V	Vmis
,	,	,-F	Fi
driseoga	driseoga	driseog-N	Ncfpc
,	,	,-F	Fi
raithneach	raithneach	raithneach-N	Ncfsc
agus	agus	agus-C	Cc
achan	achan	gach-D	Dq
chineál	chineál	cineál-N	Ncmsc
féir	féir	féar-N	Ncmsg
agus	agus	agus-C	Cc
lustain	lustain	lustan-N	Ncmsg|Ncmpc|Ncmsg
go dtí	go dtí	go_dtí-S	Spc
nach	nach	nach-Q	Qnr
dtiocfadh	dtiocfadh	tar-V	Vmc
le	le	le-S	Sp
duine	duine	duine-N	Ncmsc
daonna	daonna	daonna-A	Aqp
a	a	a-D	Dp3
bhealach	bhealach	bealach-N	Ncmsc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
síos	síos	síos-R	Rd
chun	chun	chun-S	Sp
an	an	an-T	Td-s
chladaigh	chladaigh	cladach-N	Ncmsg
.	.	.-F	Fe
Rinne	Rinne	déan-V	Vmis
éanacha	éanacha	éan-N	Ncmpc
na	na	na-T	Tdfsg
spéire	spéire	spéir-N	Ncfsg
agus	agus	agus-C	Cc
ainmhithe	ainmhithe	ainmhí-N	Ncmpc
fiáine	fiáine	fiáin-A	Aq--pc
a	a	a-U	U
gcónaí	gcónaí	cónaigh-N	Nv
ann	ann	ann-R	Rl
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
mise	mise	mé-P	Pp1-s-e
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
é	é	é-P	Pp3ms
a	a	a-U	U
fhágáil	fhágáil	fág-N	Nv
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
lá	lá	lá-N	Ncmsc
amháin	amháin	amháin-A	Aqp
cúpla	cúpla	cúpla-N	Ncmsg|Ncmsc|Dq
bliain	bliain	bliain-N	Ncfsc
ó	ó	ó-S	Sp
shin	shin	sin-P	Pd
,	,	,-F	Fi
agus	agus	agus-C	Cc
mé	mé	mé-P	Pp1-s
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
sheasamh	sheasamh	seas-N	Ncmsc|Nv
ag	ag	ag-S	Sp
amharc	amharc	amharc-N	Nv
síos	síos	síos-R	Rd
,	,	,-F	Fi
dar	dar	dar-V	Vmip
liom	liom	le-P	Pr1-s
nár	nár	is-W	Wsrin
dheas	dheas	deas-A	Aqp
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
síos	síos	síos-R	Rd
arís	arís	arís-R	Rg
,	,	,-F	Fi
síos	síos	síos-R	Rd
agus	agus	agus-C	Cc
amach	amach	amach-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
trá	trá	trá-N	Ncfsc
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
mé	mé	mé-P	Pp1-s
liom	liom	le-P	Pr1-s
bata	bata	bata-N	Ncmsc
agus	agus	agus-C	Cc
síos	síos	síos-R	Rd
liom	liom	le-P	Pr1-s
.	.	.-F	Fe
Leis	Leis	le-S	Sp
an	an	an-T	Td-s
bhata	bhata	bata-N	Ncmsg
bhuail	bhuail	buail-V	Vmis
mé	mé	mé-P	Pp1-s
agus	agus	agus-C	Cc
bhris	bhris	bris-V	Vmis
mé	mé	mé-P	Pp1-s
driseoga	driseoga	driseog-N	Ncfpc
as	as	as-P	Pr3ms
mo	mo	mo-D	Dp1-s
bhealach	bhealach	bealach-N	Ncmsc
.	.	.-F	Fe
Thóg	Thóg	tóg-V	Vmis
mé	mé	mé-P	Pp1-s
mo	mo	mo-D	Dp1-s
chosa	chosa	cos-N	Ncfpc
breá	breá	breá-R	Ri
ard	ard	ard-A	Aqp
agus	agus	agus-C	Cc
bhrúigh	bhrúigh	brúigh-V	Vmis
síos	síos	síos-R	Rd
cibé	cibé	cibé-P	Pi|Dq
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhéadfainn	fhéadfainn	féad-V	Vmc-1s
.	.	.-F	Fe
De réir	De réir	de_réir-C	Cs|Spc
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
rinne	rinne	déan-V	Vmis
mé	mé	mé-P	Pp1-s
mo	mo	mo-D	Dp1-s
bhealach	bhealach	bealach-N	Ncmsc
a	a	a-D	Dp3
fhad	fhad	fad-N	Ncmsc
le	le	le-S	Sp
hArd	hArd	ard-N	Ncmsc
an	an	an-T	Td-s
Chnámharlaigh	Chnámharlaigh	cnámharlach-N	Ncmsg
.	.	.-F	Fe
Sheas	Sheas	seas-V	Vmis
mé	mé	mé-P	Pp1-s
ar	ar	ar-S	Sp
bharr	bharr	barr-N	Ncmsc
an	an	an-T	Td-s
aird	aird	ard-N	Ncmsg
ag	ag	ag-S	Sp
amharc	amharc	amharc-N	Nv
uaim	uaim	ó-P	Pr1-s
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
thug	thug	tabhair-V	Vmis
mé	mé	mé-P	Pp1-s
rud	rud	rud-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
fá	fá	faoi-P	Pr3ms
deara	deara	deara-N	Ns-s
–	–	–-X	Xx
ón	ón	ó-S	Spa-s
ard	ard	ard-N	Ncmsc
síos	síos	síos-R	Rd
chun	chun	chun-S	Sp
an	an	an-T	Td-s
chladaigh	chladaigh	cladach-N	Ncmsg
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
féar	féar	féar-N	Ncmsc
,	,	,-F	Fi
feagacha	feagacha	feag-N	Ncfpc
ná	ná	ná-C	Cc
rud	rud	rud-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
ag	ag	ag-S	Sp
fás	fás	fás-N	Nv
ach	ach	ach-S	Sp
eidheann	eidheann	eidheann-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
talamh	talamh	talamh-N	Ncfsc
,	,	,-F	Fi
ar	ar	ar-S	Sp
na	na	na-T	Td-p
carraigeacha	carraigeacha	carraig-N	Ncfpc
agus	agus	agus-C	Cc
ar	ar	ar-S	Sp
na	na	na-T	Td-p
crainn	crainn	crann-N	Ncmpc
.	.	.-F	Fe
Eidheann	Eidheann	eidheann-N	Ncmsc
,	,	,-F	Fi
eidheann	eidheann	eidheann-N	Ncmsc
achan	achan	gach-D	Dq
áit	áit	áit-N	Ncfsc
,	,	,-F	Fi
rud	rud	rud-N	Ncmsc
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhág	fhág	fág-V	Vmis
an	an	an-T	Td-s
talamh	talamh	talamh-N	Ncfsc
chomh	chomh	chomh-R	Ri
mín	mín	mín-A	Aqp
réidh	réidh	réidh-A	Aqp
le	le	le-S	Sp
tábla	tábla	tábla-N	Ncfsc|Ncmsc
snúcair	snúcair	snúcar-N	Ncmsg
.	.	.-F	Fe
'	'	'-F	Fa
Nach	Nach	is-C	Cs|Wpdin|Wpsin
deas	deas	deas-N	Ns-s|Aqp
sin	sin	sin-P	Pd|W
anois	anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
dar	dar	dar-V	Vmip
liom	liom	le-P	Pr1-s
.	.	.-F	Fe
'	'	'-F	Fa
Is	Is	is-W	Wp-i
furasta	furasta	furasta-A	Aqp
siúl	siúl	siúil-N	Ncmsc|Nv
thart	thart	thart-R	Rd
anseo	anseo	anseo-R	Rl
agus	agus	agus-C	Cc
síos	síos	síos-R	Rd
chun	chun	chun-S	Sp
an	an	an-T	Td-s
chladaigh	chladaigh	cladach-N	Ncmsg
.	.	.-F	Fe
'	'	'-F	Fa
Ansin	Ansin	ansin-R	Rt|Rl
shíl	shíl	síl-V	Vmis
mé	mé	mé-P	Pp1-s
gur	gur	gur-Q	Q--s
chuala	chuala	clois-V	Vmis
mé	mé	mé-P	Pp1-s
duine	duine	duine-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
ag	ag	ag-S	Sp
tabhairt	tabhairt	tabhair-N	Nv
m	m	m-X	Xl
’	’	’-F	Fa
ainm	ainm	ainm-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Mo	Mo	mo-D	Dp1-s
bhean	bhean	bean-N	Ncfsc
,	,	,-F	Fi
is	is	is-W	Wpri
dóigh	dóigh	dóigh-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
dar	dar	dar-V	Vmip
liom	liom	le-P	Pr1-s
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ansin	ansin	ansin-R	Rt|Rl
tá	tá	bí-V	Vmip
difear	difear	difear-N	Ncmsc
idir	idir	idir-S	Sp
glór	glór	glór-N	Ncmsc
duine	duine	duine-N	Ncmsg
ag	ag	ag-S	Sp
scairteadh	scairteadh	scairt-N	Nv
ó	ó	ó-S	Sp
bharr	bharr	barr-N	Ncmsc
na	na	na-T	Td-p
mbeann	mbeann	beann-N	Ncfpg
agus	agus	agus-C	Cc
an	an	an-T	Td-s
glór	glór	glór-N	Ncmsc
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
mise	mise	mé-P	Pp1-s-e
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
mé	mé	mé-P	Pp1-s
cluas	cluas	cluas-N	Ncfsc
le	le	le-S	Sp
héisteacht	héisteacht	éist-N	Nv
orm	orm	ar-P	Pr1-s
féacháil	féacháil	féacháil-N	Nv
an	an	an-Q	Qq
gcloisfinn	gcloisfinn	clois-V	Vmc-1s
arís	arís	arís-R	Rg
é	é	é-P	Pp3ms
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
chuala	chuala	clois-V	Vmis
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
cá	cá	cá-R	Rq
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
as	as	as-P	Pr3ms
?	?	?-F	Fq
D	D	D-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-V	Vmm-2s
mé	mé	mé-P	Pp1-s
thart	thart	thart-R	Rd
.	.	.-F	Fe
'	'	'-F	Fa
Anseo	Anseo	anseo-R	Rl
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
glór	glór	glór-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-V	Vmm-2s
mé	mé	mé-P	Pp1-s
síos	síos	síos-R	Rd
agus	agus	agus-C	Cc
ansin	ansin	ansin-R	Rt|Rl
ag	ag	ag-S	Sp
mo	mo	mo-D	Dp1-s
chosa	chosa	cos-N	Ncfpc
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
beag	beag	beag-A	Aq-msc
is	is	is-U	U
lú	lú	beag-A	Aqc
dá	dá	dá-C	Cs
bhfaca	bhfaca	feic-V	Vmis---d
mé	mé	mé-P	Pp1-s
riamh	riamh	riamh-R	Rg
.	.	.-F	Fe
Má	Má	má-C	Cs
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ocht	ocht	ocht-M	Mc
n	n	n-X	Xl
‑	‑	‑-F	Fb
orlaí	orlaí	orla-N	Ncmsc|Ncmpc
déag	déag	déag-N	Ns-s
,	,	,-F	Fi
sin	sin	sin-P	Pd|W
an	an	an-T	Td-s
méid	méid	méid-N	Ncmsg|Ncmsc
.	.	.-F	Fe
Baineadh	Baineadh	bain-V	Vmis0
stad	stad	stad-N	Ncmsc
asam	asam	as-P	Pr1-s
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
dúil	dúil	dúil-N	Ncfsc
lena	lena	le-S	Spp-s|Spp-p
leithéid	leithéid	leithéid-N	Ncfsc
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
shíl	shíl	síl-V	Vmis---n
mé	mé	mé-P	Pp1-s
ná	ná	ná-C	Cs
níor	níor	is-W	Ws-in
chreid	chreid	creid-V	Vmis
mé	mé	mé-P	Pp1-s
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
a	a	a-D	Dp3
leithéid	leithéid	leithéid-N	Ncfsc
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
'	'	'-F	Fa
Abair	Abair	abair-V	Vmm-2s
rud	rud	rud-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
mé	mé	mé-P	Pp1-s
ach	ach	ach-C	Cs
ní	ní	is-W	Wp-in
thiocfadh	thiocfadh	tar-V	Vmc
na	na	na-T	Td-p
focla	focla	focl-N	Ncmpc
liom	liom	le-P	Pr1-s
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
mé	mé	mé-P	Pp1-s
ábalta	ábalta	ábalta-A	Aqp
deireadh	deireadh	deireadh-V	Vmih|Ncmsc
iontais	iontais	iontas-N	Ncmsg|Ncmpc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
de	de	de-P	Pr3ms
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sé	sé	sé-P	Pp3msn
a	a	a-Q	Q-r
dhath	dhath	dath-V	Vmis
níos	níos	níos-U	Uc
airde	airde	ard-A	Aqc
ná	ná	ná-C	Cc
mo	mo	mo-D	Dp1-s
ghlúin	ghlúin	glúin-N	Ncfsc
ach	ach	ach-S	Sp|Cs
é	é	é-P	Pp3ms
cumtha	cumtha	cumtha-A	Av|Aqp
cosúil	cosúil	cosúil-A	Aqp
le	le	le-S	Sp
fear	fear	fear-N	Ncmsc
fásta	fásta	fás-N	Nv--g
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
bríste	bríste	bríste-N	Ncmsc
dubh	dubh	dubh-A	Aq-msc
air	air	ar-N	Ncmsg|Pr3ms
an	an	an-T	Td-s
méid	méid	méid-N	Ncmsg|Ncmsc
de	de	de-P	Pr3ms
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
le	le	le-S	Sp
feiceáil	feiceáil	feic-N	Nv
agus	agus	agus-C	Cc
cóta	cóta	cóta-N	Ncmsg|Ncmsc
cineál	cineál	cineál-R	Ri
glas	glas	glas-A	Aqp
síos	síos	síos-R	Rd
chóir	chóir	cóir-N	Ns-s
a	a	a-U	U
bheith	bheith	bí-N	Nv
go dtí	go dtí	go_dtí-S	Spc
a	a	a-D	Dp3
chuid	chuid	cuid-N	Ncfsc
glún	glún	glúin-N	Ncfpg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
péire	péire	péire-N	Ncmsc
bróg	bróg	bróg-N	Ncfpg
air	air	ar-N	Ncmsg
chóir	chóir	cóir-A	Aqp
a	a	a-U	U
bheith	bheith	bí-N	Nv
suas	suas	suas-R	Rd
go dtí	go dtí	go_dtí-S	Spc
na	na	na-T	Td-p
glúine	glúine	glúin-N	Ncfpc
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
ceangailte	ceangailte	ceangail-A	Av
le	le	le-S	Sp
hiallacha	hiallacha	iall-N	Ncfpc
.	.	.-F	Fe
Ar	Ar	is-W	Wssi|Wpsi
a	a	a-D	Dp3
cheann	cheann	ceann-N	Ncmsc
bhí	bhí	bí-V	Vmis
bairéad	bairéad	bairéad-N	Ncmsc
dearg	dearg	dearg-A	Aq-msc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ba	ba	is-W	Ws|Ws-i
í	í	í-P	Pp3fs
a	a	a-D	Dp3
aghaidh	aghaidh	aghaidh-N	Ncfsc
ba	ba	is-W	Wsri
shonraíche	shonraíche	shonraíche-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
roicneach	roicneach	roicneach-A	Aqp
dorcha	dorcha	dorcha-A	Aqp
cosúil	cosúil	cosúil-A	Aqp
le	le	le-S	Sp
seanphráta	seanphráta	práta-N	Ncmsc
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
ina	ina	i-S	Spp-s|Spp-p
luí	luí	luí-N	Ncmsc
thart	thart	thart-R	Rd
le	le	le-S	Sp
bliain	bliain	bliain-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
féasóg	féasóg	féasóg-N	Ncfsc
fhada	fhada	fada-A	Aqp
liath	liath	liath-A	Aqp
air	air	ar-P	Pr3ms
agus	agus	agus-C	Cc
malaíocha	malaíocha	malaíoch-N	Ncmpc
bána	bána	bán-A	Aq--pc|Aq--pv|Aq--pg
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
dhá	dhá	dó-M	Mc
shúil	shúil	súil-N	Ncfsc
dhorcha	dhorcha	dorcha-A	Aqp
dhonna	dhonna	donn-A	Aq--pc
ghéara	ghéara	géar-A	Aq--pc
aige	aige	ag-P	Pr3ms
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-V	Vmm-2s
fríom	fríom	fríom-N	Ncmsc
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
snáthaidí	snáthaidí	snáthaid-N	Ncfpc
iontu	iontu	i-P	Pr3-p
.	.	.-F	Fe
Sa	Sa	i-S	Spa-s
deireadh	deireadh	deireadh-N	Ncmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
fuair	fuair	faigh-V	Vmis
mé	mé	mé-P	Pp1-s
an	an	is-W	Wpdq|Wp-q
chaint	chaint	caint-N	Nv-----n|Ncfsc
liom	liom	le-P	Pr1-s
,	,	,-F	Fi
'	'	'-F	Fa
Is	Is	is-W	Wpri
ea	ea	ea-P	Pp3-s
,	,	,-F	Fi
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
mise	mise	mé-P	Pp1-s-e
.	.	.-F	Fe
'	'	'-F	Fa
Is	Is	is-W	Wp-i
ea	ea	ea-P	Pp3-s
,	,	,-F	Fi
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
seisean	seisean	sé-P	Pp3msne
ag	ag	ag-S	Sp
aithris	aithris	aithris-N	Nv
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
'	'	'-F	Fa
Abair	Abair	abair-V	Vmm-2s
fáilte	fáilte	fáilte-N	Ncfsc
romhat	romhat	roimh-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Mhánais	Mhánais	Mánas-N	Npm-v
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
'	'	'-F	Fa
Fáilte	Fáilte	fáilte-N	Ncfsc
romhat	romhat	roimh-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Mhánais	Mhánais	Mánas-N	Npm-v
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
mé	mé	mé-P	Pp1-s
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
gan	gan	gan-S	Sp
mé	mé	mé-P	Pp1-s
chugam	chugam	chuig-P	Pr1-s
féin	féin	féin-P	Px
go	go	go-U	Ua
fóill	fóill	fóill-A	Aqp
.	.	.-F	Fe
'	'	'-F	Fa
Sin	Sin	sin-P	Pd|W
níos	níos	níos-U	Uc
fearr	fearr	maith-A	Aqc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
Chuala	Chuala	clois-V	Vmis
mé	mé	mé-P	Pp1-s
riamh	riamh	riamh-R	Rg
,	,	,-F	Fi
má	má	má-C	Cs
chastar	chastar	cas-V	Vmip0
taibhse	taibhse	taibhse-N	Ncfsc
nó	nó	nó-C	Cc
spiorad	spiorad	spiorad-N	Ncmpg|Ncmsc|Ncmpg
neamhshaolta	neamhshaolta	neamhshaolta-A	Aqp
ort	ort	ar-P	Pr2-s
gur	gur	is-W	Wsdi|Wpdi
cheart	cheart	ceart-A	Aqp
duit	duit	do-P	Pr2-s
fiafraí	fiafraí	fiafraí-N	Ncmsc
de	de	de-P	Pr3ms
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
atá	atá	bí-V	Vmip---r
sé	sé	sé-P	Pp3msn
a	a	a-U	U
iarraidh	iarraidh	iarr-N	Nv
.	.	.-F	Fe
Phioc	Phioc	pioc-V	Vmis
mé	mé	mé-P	Pp1-s
suas	suas	suas-R	Rd
uchtach	uchtach	uchtach-N	Ncmsc
agus	agus	agus-C	Cc
arsa	arsa	arsa-V	Vmis
mé	mé	mé-P	Pp1-s
féin	féin	féin-P	Px
,	,	,-F	Fi
'	'	'-F	Fa
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
a	a	a-D	Dp3
dhath	dhath	dath-N	Ncmsc
a	a	a-Q	Q-r
thig	thig	tar-V	Vmip
liom	liom	le-P	Pr1-s
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
duit	duit	do-P	Pr2-s
?	?	?-F	Fq
'	'	'-F	Fa
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
,	,	,-F	Fi
cinnte	cinnte	cinnte-A	Av|Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
seisean	seisean	sé-P	Pp3msne
,	,	,-F	Fi
'	'	'-F	Fa
agus	agus	agus-C	Cc
sin	sin	sin-P	Pd|W
an	an	an-T	Td-s
tuige	tuige	tuige-N	Ncmsc
a	a	a-Q	Q-i
dtáinig	dtáinig	tar-V	Vmis
mé	mé	mé-P	Pp1-s
i	i	i-S	Sp
d	d	d-X	Xl
’	’	’-F	Fa
araicis	araicis	araicis-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Cad	Cad	cad-W	W--q
é	é	é-P	Pp3ms
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhéadfainnse	fhéadfainnse	féad-V	Vmc-1s--e
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
duitse	duitse	do-P	Pr2-s-e
nach	nach	nach-Q	Qnr
bhfuil	bhfuil	bí-V	Vmip---n
tú	tú	tú-P	Pp2-s
féin	féin	féin-P	Px
ábalta	ábalta	ábalta-A	Aqp
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
?	?	?-F	Fq
Ar	Ar	ar-S	Sp
ndóigh	ndóigh	dóigh-N	Ncfsc
,	,	,-F	Fi
nach	nach	nach-Q	Qnr|Qnq
bhfuil	bhfuil	bí-V	Vmip---d|Vmip---n
draíocht	draíocht	draíocht-N	Ncfsc
agaibhse	agaibhse	ag-P	Pr2-p-e
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
mise	mise	mé-P	Pp1-s-e
agus	agus	agus-C	Cc
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
éirí	éirí	éirigh-N	Nv
dána	dána	dána-A	Aqp
anois	anois	anois-R	Rt
.	.	.-F	Fe
'	'	'-F	Fa
Níl	Níl	bí-V	Vmip---n
draíocht	draíocht	draíocht-N	Ncfsc
ná	ná	ná-C	Cs|Cc
draíocht	draíocht	draíocht-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
seisean	seisean	sé-P	Pp3msne
,	,	,-F	Fi
'	'	'-F	Fa
ach	ach	ach-C	Cs
tá	tá	bí-V	Vmip
cuid	cuid	cuid-N	Ncfsc
mhór	mhór	mór-N	Ncmpg
eolais	eolais	eolas-N	Ncmsg
againn	againn	ag-P	Pr1-p
agus	agus	agus-C	Cc
tá	tá	bí-V	Vmip
muid	muid	muid-P	Pp1-p
iontach	iontach	iontach-R	Ri
cliste	cliste	cliste-A	Aqp
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
againn	againn	ag-P	Pr1-p
dóigheanna	dóigheanna	dóigh-N	Ncfpc
le	le	le-S	Sp
cuid	cuid	cuid-N	Ncfsc
mhór	mhór	mór-N	Ncmpg
rudaí	rudaí	rud-N	Ncmpg|Ncmpc|Ncmpg
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
,	,	,-F	Fi
rudaí	rudaí	rud-N	Ncmpc
nach	nach	nach-Q	Qnr
bhfuil	bhfuil	bí-V	Vmip---n
sibhse	sibhse	sibh-P	Pp2-p-e
ábalta	ábalta	ábalta-A	Aqp
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
agus	agus	agus-C	Cc
sin	sin	sin-P	Pd|W
an	an	an-T	Td-s
tuige	tuige	tuige-N	Ncmsc|Ncmsg
a	a	a-Q	Q-i
síleann	síleann	síl-V	Vmip
sibhse	sibhse	sibh-P	Pp2-p-e
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
draíocht	draíocht	draíocht-N	Ncfsc
againn	againn	ag-P	Pr1-p
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
thuigeann	thuigeann	tuig-V	Vmip---n
sibh	sibh	sibh-P	Pp2-p
dóigheanna	dóigheanna	dóigh-N	Ncfpc
seo	seo	seo-P	Pd|Dd
againne	againne	ag-P	Pr1-p-e
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Agus	Agus	agus-C	Cc
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
an	an	an-W	Wpdq|Wp-q|Td-s
gar	gar	gar-N	Ncmsc|Aqp
atá	atá	bí-V	Vmip---r
tú	tú	tú-P	Pp2-s
a	a	a-U	U
iarraidh	iarraidh	iarr-N	Nv
ormsa	ormsa	ar-P	Pr1-s-e
anois	anois	anois-R	Rt
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
mise	mise	mé-P	Pp1-s-e
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
,	,	,-F	Fi
'	'	'-F	Fa
an	an	an-Q	Qq
bhfeiceann	bhfeiceann	feic-V	Vmip
tú	tú	tú-P	Pp2-s
an	an	is-W	Wpdq|Wp-q
t	t	t-X	Xl
‑	‑	‑-F	Fb
eidheann	eidheann	eidheann-N	Ncmsc
sin	sin	sin-P	Pd|Dd
atá	atá	bí-V	Vmip---r
ar fud	ar fud	ar_fud-S	Spc
na	na	na-T	Tdfsg
háite	háite	áit-N	Ncfsg
?	?	?-F	Fq
'	'	'-F	Fa
'	'	'-F	Fa
Tchím	Tchím	tchí-V	Vmip1s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
mise	mise	mé-P	Pp1-s-e
.	.	.-F	Fe
'	'	'-F	Fa
Bhuel	Bhuel	bhuel-X	Xsc
,	,	,-F	Fi
tá	tá	bí-V	Vmip
sin	sin	sin-P	Pd
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
an	an	an-T	Td-s
saol	saol	saol-N	Ncmsc
iontach	iontach	iontach-R	Ri
crua	crua	crua-A	Aqp
dúinne	dúinne	do-P	Pr1-p-e
agus	agus	agus-C	Cc
bheadh	bheadh	bí-V	Vmc
muid	muid	muid-P	Pp1-p
fíorbhuíoch	fíorbhuíoch	buíoch-A	Aqp
díot	díot	de-P	Pr2-s
ach	ach	ach-S	Sp|Cs
é	é	é-P	Pp3ms
a	a	a-Q	Q-r
ghlanadh	ghlanadh	glan-V	Vmih
ar	ar	ar-S	Sp
shiúl	shiúl	siúl-N	Ncmsc
as	as	as-S	Sp
an	an	an-T	Td-s
áit	áit	áit-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Agus	Agus	agus-C	Cc
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
an	an	an-T	Td-s
dochar	dochar	dochar-N	Ncmsc
atá	atá	bí-V	Vmip---r
t	t	t-X	Xl
‑	‑	‑-F	Fb
eidheann	eidheann	eidheann-N	Ncmsc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
daoibh	daoibh	do-P	Pr2-p
?	?	?-F	Fq
'	'	'-F	Fa
'	'	'-F	Fa
Níl	Níl	bí-V	Vmip---n
muid	muid	muid-P	Pp1-p
ábalta	ábalta	ábalta-A	Aqp
siúl	siúl	siúil-N	Ncmsc|Nv
fríd	fríd	fríd-N	Ncfsc
.	.	.-F	Fe
B	B	B-X	Xl
’	’	’-F	Fa
fhearr	fhearr	maith-A	Aqc
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
féar	féar	féar-N	Ncmpg
fada	fada	fada-A	Aqp
agus	agus	agus-C	Cc
feagacha	feagacha	feag-N	Ncfpg|Ncfpc
agus	agus	agus-C	Cc
driseoga	driseoga	driseog-N	Ncfpc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéadfadh	fhéadfadh	féad-V	Vmc
muid	muid	muid-P	Pp1-p
siúl	siúl	siúil-N	Ncmsc|Nv
fríothu	fríothu	fríothu-N	Ncmsc
,	,	,-F	Fi
deacair	deacair	deacair-A	Aqp
is	is	agus-W	Wp-i|Wpri|Cc
uile	uile	uile-N	Ns-s|Dq
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
t	t	t-X	Xl
‑	‑	‑-F	Fb
eidheann	eidheann	eidheann-N	Ncmsc
,	,	,-F	Fi
téann	téann	téigh-V	Vmip
sé	sé	sé-P	Pp3msn
i	i	i-S	Sp
bhfostú	bhfostú	fostú-N	Ncmsc
inár	inár	i-S	Spp-p
gcosa	gcosa	cos-N	Ncfpc
agus	agus	agus-C	Cc
níl	níl	bí-V	Vmip---n
muid	muid	muid-P	Pp1-p
ábalta	ábalta	ábalta-A	Aqp
siúl	siúl	siúil-N	Ncmsc|Nv
ná	ná	nach-Q	Qnr
rith	rith	rith-V	Vmm-2s-n
faoi	faoi	faoi-S	Sp
shult	shult	sult-N	Ncmsc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
níos	níos	níos-U	Uc
measa	measa	olc-A	Aqc
ná	ná	ná-C	Cs|Cc
sin	sin	sin-W	W
,	,	,-F	Fi
i ndiaidh	i ndiaidh	i_ndiaidh-S	Spc
a	a	a-Q	Q-p
bhfuil	bhfuil	bí-V	Vmip---d
muid	muid	muid-P	Pp1-p
ábalta	ábalta	ábalta-A	Aqp
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
níl	níl	bí-V	Vmip---n
muid	muid	muid-P	Pp1-p
ábalta	ábalta	ábalta-A	Aqp
fáil	fáil	faigh-N	Ncfsc|Nv
réitithe	réitithe	réitigh-A	Av
den	den	de-S	Spa-s
eidheann	eidheann	eidheann-N	Ncmsc
damanta	damanta	damanta-A	Aqp
sin	sin	sin-D	Dd
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Bhuel	Bhuel	bhuel-X	Xsc
anois	anois	anois-R	Rt
,	,	,-F	Fi
a	a	a-U	Uv
Mhánais	Mhánais	Mánas-N	Npm-v
,	,	,-F	Fi
thig	thig	tar-V	Vmip
liomsa	liomsa	le-P	Pr1-s-e
an	an	is-W	Wpdq|Wp-q
t	t	t-X	Xl
‑	‑	‑-F	Fb
eidheann	eidheann	eidheann-N	Ncmsc
a	a	a-Q	Q-r
chartadh	chartadh	cart-V	Vmih
ar	ar	ar-S	Sp
shiúl	shiúl	siúl-N	Ncmsc
ach	ach	ach-C	Cs
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
an	an	an-T	Td-s
luach	luach	luach-N	Ncmsc
saothair	saothair	saothar-N	Ncmsg|Ncmpc
a	a	a-Q	Q-i|Q-r
gheobhas	gheobhas	faigh-V	Vmif---r
mise	mise	mé-P	Pp1-s-e
?	?	?-F	Fq
Cluinim	Cluinim	cluin-V	Vmip1s
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
pota	pota	pota-N	Ncmsc
óir	óir	ór-C	Cs|Ncmsg|Ncmpc
ag	ag	ag-S	Sp
achan	achan	gach-D	Dq
duine	duine	duine-N	Ncmsc
de	de	de-P	Pr3ms
bhur	bhur	bhur-D	Dp2-p
gcine	gcine	cine-N	Ncmsc
.	.	.-F	Fe
Bheinnse	Bheinnse	bí-V	Vmc-1s--e
ag	ag	ag-S	Sp
súil	súil	súil-N	Nv-----n
le	le	le-S	Sp
gráinnín	gráinnín	gráinnín-N	Ncmsc
den	den	de-S	Spa-s
ór	ór	ór-N	Ncmsc
sin	sin	sin-D	Dd
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Níl	Níl	bí-V	Vmip---n
ór	ór	ór-N	Ncmsc
ná	ná	ná-C	Cs|Cc
ór	ór	ór-N	Ncmpg|Ncmsc
againn	againn	ag-P	Pr1-p
ná	ná	ná-C	Cs|Cc
gnoithe	gnoithe	gnoithe-A	Av
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
againn	againn	ag-P	Pr1-p
le	le	le-S	Sp
hór	hór	ór-N	Ncmsc
ach	ach	ach-C	Cs
béarfaidh	béarfaidh	beir-V	Vmif
muid	muid	muid-P	Pp1-p
íocaíocht	íocaíocht	íocaíocht-N	Ncfsc
duit	duit	do-P	Pr2-s
,	,	,-F	Fi
cinnte	cinnte	cinn-A	Aqp|Av
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mánas	Mánas	Mánas-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
rud	rud	rud-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
faoi	faoi	faoi-S	Sp
leith	leith	leith-N	Ncfsc
ba	ba	is-W	Wsri
mhaith	mhaith	maith-A	Aqp
leat	leat	le-P	Pr2-s
?	?	?-F	Fq
'	'	'-F	Fa
Thosaigh	Thosaigh	tosaigh-V	Vmis
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
smaoineamh	smaoineamh	smaoinigh-N	Nv
go	go	go-U	Ua
gasta	gasta	gasta-A	Aqp
.	.	.-F	Fe
'	'	'-F	Fa
A	A	a-U	Uv
Mhánais	Mhánais	Mánas-N	Npm-v
,	,	,-F	Fi
sula	sula	sula-C	Cs
dtéann	dtéann	téigh-V	Vmip
muid	muid	muid-P	Pp1-p
níos	níos	níos-U	Uc
faide	faide	fada-A	Aqc
leis	leis	le-S	Sp
an	an	an-T	Td-s
mhargadh	mhargadh	margadh-N	Ncmsc
an	an	an-Q	Qq
dtiocfadh	dtiocfadh	tar-V	Vmc
linn	linn	linn-N	Ncfsc
seal	seal	seal-N	Ncmsc
comhrá	comhrá	comhrá-N	Ncmsc|Nv-----n|Ncmsg
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
?	?	?-F	Fq
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
liomsa	liomsa	le-P	Pr1-s-e
rud	rud	rud-N	Ncmsc
beag	beag	beag-A	Aq-msc
eolais	eolais	eolas-N	Ncmsg
fá	fá	faoi-P	Pr3ms
dtaobh	dtaobh	taobh-N	Ncmsc
díot	díot	de-P	Pr2-s
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
do	do	do-S	Sp
dhream	dhream	dream-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Cinnte	Cinnte	cinn-A	Av
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Mánas	Mánas	Mánas-N	Npmsc
,	,	,-F	Fi
'	'	'-F	Fa
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
ba	ba	is-W	Wsri
mhaith	mhaith	maith-A	Aqp
leat	leat	le-P	Pr2-s
a	a	a-U	U
fháil	fháil	faigh-N	Nv
amach	amach	amach-R	Rd
?	?	?-F	Fq
'	'	'-F	Fa
'	'	'-F	Fa
Cad	Cad	cad-W	W--q
é	é	é-P	Pp3ms
an	an	an-T	Td-s
aois	aois	aois-N	Ncfsc
tú	tú	tú-P	Pp2-s
?	?	?-F	Fq
'	'	'-F	Fa
'	'	'-F	Fa
Céad	Céad	céad-M	Mc
agus	agus	agus-C	Cc
trí	trí	trí-M	Mc|Sp
scór	scór	scór-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Céad	Céad	céad-M	Mc
seasca	seasca	seasca-M	Mc
bliain	bliain	bliain-N	Ncfsc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
mise	mise	mé-P	Pp1-s-e
agus	agus	agus-C	Cc
iontas	iontas	iontas-N	Ncmsc
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
'	'	'-F	Fa
Áhá	Áhá	Áhá-N	Npmsc
!	!	!-F	Fe
Anois	Anois	anois-R	Rt
ní	ní	is-W	Wp-in
hionann	hionann	ionann-A	Aqp
bliain	bliain	bliain-N	Ncfsc
seo	seo	seo-P	Pd|Dd
againne	againne	ag-P	Pr1-p-e
agus	agus	agus-C	Cc
bliain	bliain	bliain-N	Ncfsc
seo	seo	seo-P	Pd|Dd
agaibhse	agaibhse	ag-P	Pr2-p-e
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
bliain	bliain	bliain-N	Ncfsc
seo	seo	seo-P	Pd|Dd
agaibhse	agaibhse	ag-P	Pr2-p-e
ag	ag	ag-S	Sp
brath	brath	braith-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
ghrian	ghrian	grian-N	Ncfsc
ach	ach	ach-C	Cs
tá	tá	bí-V	Vmip
bliain	bliain	bliain-N	Ncfsc
seo	seo	seo-P	Pd|Dd
againne	againne	ag-P	Pr1-p-e
ceangailte	ceangailte	ceangail-A	Av
leis	leis	le-S	Sp
an	an	an-T	Td-s
lán	lán	lán-N	Ncmsc
mara	mara	muir-N	Ncfsg|Ncfpg
.	.	.-F	Fe
Is	Is	is-W	Wp-i
ionann	ionann	ionann-A	Aqp
bliain	bliain	bliain-N	Ncfsc
seo	seo	seo-P	Pd|Dd
againne	againne	ag-P	Pr1-p-e
agus	agus	agus-C	Cc
leathchéad	leathchéad	leathchéad-N	Ncmsc
ré	ré	ré-N	Ncfsg|Ncfsc|Ncmsg|Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Caoga	Caoga	caoga-N	Ncmsc|Mc
ré	ré	ré-N	Ncmsg|Ncfsg|Ncmsg|Ncmsc|Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
mé	mé	mé-P	Pp1-s
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
cuntas	cuntas	cuntais-N	Nv
,	,	,-F	Fi
'	'	'-F	Fa
sin	sin	sin-P	Pd|W
thart	thart	thart-R	Rd
fá	fá	faoi-P	Pr3ms
cheithre	cheithre	ceathair-M	Mc
bliana	bliana	bliain-N	Ncfpc
dár	dár	do-S	Spp-p
gcuid	gcuid	cuid-N	Ncfsc
seo	seo	seo-P	Pd|Dd
againne	againne	ag-P	Pr1-p-e
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhágfadh	fhágfadh	fág-V	Vmc
sin	sin	sin-P	Pd
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
tusa	tusa	tú-P	Pp2-s-e
thart	thart	thart-R	Rd
fá	fá	faoi-P	Pr3ms
sé	sé	sé-W	Wp-i-3|Pp3msn
chéad	chéad	céad-N	Ncmsc
go	go	go-S	Sp
leith	leith	leith-N	Ncfsc
bliain	bliain	bliain-N	Ncfsc
d	d	d-X	Xl
’	’	’-F	Fa
aois	aois	aois-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
B	B	B-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
an	an	an-T	Td-s
ceart	ceart	ceart-N	Ncmsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
seisean	seisean	sé-P	Pp3msne
agus	agus	agus-C	Cc
nuair	nuair	nuair-C	Cs
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-V	Vmm-2s
mé	mé	mé-P	Pp1-s
arís	arís	arís-R	Rg
air	air	ar-P	Pr3ms
dar	dar	dar-V	Vmip
liom	liom	le-P	Pr1-s
go	go	go-C	Cs
mb	mb	mb-Y	Y
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
.	.	.-F	Fe
'	'	'-F	Fa
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
cuimhne	cuimhne	cuimhne-N	Ncfsc
agat	agat	ag-P	Pr2-s
ar	ar	ar-S	Sp
Aodh	Aodh	Aodh-N	Npmsc
Rua	Rua	Rua-N	Npmsg
ó	ó	ó-S	Sp
Domhnaill	Domhnaill	Domhnaill-N	Npmsc
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
mé	mé	mé-P	Pp1-s
féin	féin	féin-P	Px
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
,	,	,-F	Fi
cinnte	cinnte	cinnte-A	Av|Aqp
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
'	'	'-F	Fa
Is	Is	is-W	Wp-i
minic	minic	minic-A	Aqp
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
mé	mé	mé-P	Pp1-s
é	é	é-P	Pp3ms
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
cuimhne	cuimhne	cuimhne-N	Ncfsc
agat	agat	ag-P	Pr2-s
ar	ar	ar-S	Sp
Bhrian	Bhrian	Brian-N	Ncmsc|Npmsc
Bóramha	Bóramha	Bóramha-N	Npmsc
?	?	?-F	Fq
'	'	'-F	Fa
'	'	'-F	Fa
Níl	Níl	bí-V	Vmip---n
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ann	ann	i-R	Rl|Pr3ms
roimh	roimh	roimh-S	Sp
m	m	m-X	Xl
’	’	’-F	Fa
amsa	amsa	am-N	Ncmsc-e
ach	ach	ach-C	Cs
is	is	is-W	Wpri
minic	minic	minic-A	Aqp
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
mé	mé	mé-P	Pp1-s
na	na	na-T	Td-p
seandaoine	seandaoine	seanduine-N	Ncmpc
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
air	air	ar-P	Pr3ms
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Ar	Ar	ar-Q	Qq-s
chuala	chuala	clois-V	Vmis
tú	tú	tú-P	Pp2-s
riamh	riamh	riamh-R	Rg
iomrá	iomrá	iomrá-N	Ncmsc
ar	ar	ar-S	Sp
Thaisce	Thaisce	taisce-N	Ncfsc
an	an	an-T	Td-s
Úcaire	Úcaire	Úcaire-N	Npmsg|Npfsg
?	?	?-F	Fq
'	'	'-F	Fa
'	'	'-F	Fa
Chuala	Chuala	clois-V	Vmis
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agat	agat	ag-P	Pr2-s
cá	cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
sí	sí	sí-P	Pp3fsn
i	i	i-S	Sp
bhfolach	bhfolach	folach-N	Ncmsc
?	?	?-F	Fq
'	'	'-F	Fa
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Bhuel	Bhuel	bhuel-X	Xsc
,	,	,-F	Fi
inis	inis	inis-V	Vmm-2s
dom	dom	do-P	Pr1-s
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Inis	Inis	inis-V	Vmm-2s
duit	duit	do-P	Pr2-s
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
?	?	?-F	Fq
'	'	'-F	Fa
'	'	'-F	Fa
Cá	Cá	cá-R	Rq
háit	háit	áit-N	Ncfsc
a	a	a-Q	Q-i
bhfuil	bhfuil	bí-V	Vmip---d
sí	sí	sí-P	Pp3fsn
i	i	i-S	Sp
bhfolach	bhfolach	folach-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Inseoidh	Inseoidh	inis-V	Vmif
agus	agus	agus-C	Cc
fáilte	fáilte	fáilte-N	Ncfsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bheas	bheas	bí-V	Vmif---r
do	do	do-S	Sp
chuid	chuid	cuid-N	Ncfsc
féin	féin	féin-P	Px
den	den	de-S	Spa-s
mhargadh	mhargadh	margadh-N	Ncmsc
comhlíonta	comhlíonta	comhlíon-A	Av
agatsa	agatsa	ag-P	Pr2-s-e
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
'	'	'-F	Fa
Fan	Fan	fan-V	Vmm-2s
bomaite	bomaite	bomaite-N	Ncmsc
,	,	,-F	Fi
anois	anois	anois-R	Rt
.	.	.-F	Fe
Chuala	Chuala	clois-V	Vmis
mise	mise	mé-P	Pp1-s-e
riamh	riamh	riamh-R	Rg
nár	nár	is-W	Wsrin
cheart	cheart	ceart-A	Aqp
domsa	domsa	do-P	Pr1-s-e
súil	súil	súil-N	Ncfsc
a	a	a-U	U
thógáil	thógáil	tóg-N	Nv
ó	ó	ó-C	Cs|Sp
do	do	do-S	Sp
leithéidse	leithéidse	leithéid-N	Ncfsc-e
má	má	má-C	Cs
bhí	bhí	bí-V	Vmis
súil	súil	súil-N	Ncfsc
agam	agam	ag-P	Pr1-s
luach	luach	luach-N	Ncmsc
saothair	saothair	saothar-N	Ncmsg|Ncmpc
ar	ar	ar-N	Ncmsc
bith	bith	bith-N	Ncmsc
a	a	a-U	U
fháil	fháil	faigh-N	Nv
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Chuala	Chuala	clois-V	Vmis
tú	tú	tú-P	Pp2-s
cuid	cuid	cuid-N	Ncfsc
mhór	mhór	mór-N	Ncmpg
amaidí	amaidí	amaideach-A	Aq-fsg
.	.	.-F	Fe
Am	Am	am-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
a	a	a-Q	Q-i
bhfuil	bhfuil	bí-V	Vmip---d
tusa	tusa	tú-P	Pp2-s-e
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
mise	mise	mé-P	Pp1-s-e
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
tar	tar	thar-S	Sp
anuas	anuas	anuas-R	Rd
anseo	anseo	anseo-R	Rl
agus	agus	agus-C	Cc
scairt	scairt	scairt-V	Vmm-2s
faoi	faoi	faoi-P	Pr3ms
d	d	d-X	Xl
’	’	’-F	Fa
anáil	anáil	anáil-N	Ncfsc
,	,	,-F	Fi
Mánas	Mánas	Mánas-N	Npmsc
a	a	a-D	Dp3
’	’	’-F	Fa
tSeabhaic	tSeabhaic	seabhac-N	Ncmsg
,	,	,-F	Fi
Mánas	Mánas	Mánas-N	Npmsc
a	a	a-D	Dp3
’	’	’-F	Fa
tSeabhaic	tSeabhaic	seabhac-N	Ncmsg
,	,	,-F	Fi
Mánas	Mánas	Mánas-N	Npmsc
a	a	a-D	Dp3
’	’	’-F	Fa
tSeabhaic	tSeabhaic	seabhac-N	Ncmsg
,	,	,-F	Fi
agus	agus	agus-C	Cc
beidh	beidh	bí-V	Vmif
mise	mise	mé-P	Pp1-s-e
ag	ag	ag-S	Sp
do	do	do-D	Dp2-s
thaobh	thaobh	taobh-N	Ncmsc
i	i	i-S	Sp
bhfaiteadh	bhfaiteadh	faiteadh-N	Ncmsc
na	na	na-T	Td-p
súl	súl	súil-N	Ncfpg
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
d	d	d-X	Xl
’	’	’-F	Fa
fhocal	fhocal	focal-N	Ncmsc
agam	agam	ag-P	Pr1-s
air	air	ar-P	Pr3ms
sin	sin	sin-P	Pd
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
mise	mise	mé-P	Pp1-s-e
.	.	.-F	Fe
'	'	'-F	Fa
Chomh	Chomh	chomh-R	Ri
cinnte	cinnte	cinnte-A	Aqp
is	is	agus-C	Cc
atá	atá	bí-V	Vmip---r
tú	tú	tú-P	Pp2-s
i	i	i-S	Sp
do	do	do-D	Dp2-s
sheasamh	sheasamh	seas-N	Ncmsc|Nv
ansin	ansin	ansin-R	Rt|Rl
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
'	'	'-F	Fa
Maith	Maith	Maith-N	Npmsc
go leor	go leor	go_leor-A	Aq
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
mé	mé	mé-P	Pp1-s
féin	féin	féin-P	Px
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
ar	ar	ar-S	Sp
shiúl	shiúl	siúl-N	Ncmsc
fá choinne	fá choinne	fá_choinne-S	Spc
mo	mo	mo-D	Dp1-s
chuid	chuid	cuid-N	Ncfsc
acraí	acraí	acra-N	Ncmpg
.	.	.-F	Fe
'	'	'-F	Fa
Agus	Agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmm-2s
mé	mé	mé-P	Pp1-s
.	.	.-F	Fe
Is	Is	is-W	Wp-i
mé	mé	mé-P	Pp1-s
a	a	a-Q	Q-r
chuaigh	chuaigh	téigh-V	Vmis
suas	suas	suas-R	Rd
na	na	na-T	Td-p
beanna	beanna	beann-N	Ncfpc
go	go	go-U	Ua
haerach	haerach	aerach-A	Aqp
aigeanta	aigeanta	aigeanta-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
éisteacht	éisteacht	éist-N	Nv
le	le	le-S	Sp
scéalta	scéalta	scéal-N	Ncmpc
fá	fá	faoi-P	Pr3ms
Thaisce	Thaisce	taisce-N	Ncfsc
an	an	an-T	Td-s
Úcaire	Úcaire	Úcaire-N	Npmsg|Npfsg
ó	ó	ó-C	Cs
tháinig	tháinig	tar-V	Vmis
ann	ann	i-R	Rl|Pr3ms
dom	dom	do-P	Pr1-s
.	.	.-F	Fe
Anois	Anois	anois-R	Rt
ní	ní	ní-Q	Qn
bheadh	bheadh	bí-V	Vmc----n
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
sí	sí	sí-P	Pp3fsn
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
Anois	Anois	anois-R	Rt
,	,	,-F	Fi
caithfidh	caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
a	a	a-U	U
rá	rá	abair-N	Nv
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
mé	mé	mé-P	Pp1-s
cinnte	cinnte	cinnte-A	Av|Aqp
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
go	go	go-U	Ua
díreach	díreach	díreach-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sa	sa	i-S	Spa-s
taisce	taisce	taisce-N	Ncfsc
chéanna	chéanna	céanna-A	Aqp
ach	ach	ach-C	Cs
caithfidh	caithfidh	caith-V	Vmif
sé	sé	sé-P	Pp3msn
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
tábhachtach	tábhachtach	tábhachtach-A	Aqp
,	,	,-F	Fi
de réir	de réir	de_réir-C	Cs
an	an	is-W	Wpdq|Wp-q
méid	méid	méid-N	Ncmsc|Ncfsc|Ncmsc|Ncfsc
cainte	cainte	caint-N	Ncfsg|Nv--g--n
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
déanta	déanta	déan-A	Av
uirthi	uirthi	ar-P	Pr3fs
leis	leis	le-S	Sp
na	na	na-T	Td-p
blianta	blianta	bliain-N	Ncfpc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhain	bhain	bain-V	Vmis
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
baile	baile	baile-N	Ncmsc
amach	amach	amach-R	Rd
níor	níor	níor-Q	Qn-s
dhúirt	dhúirt	abair-V	Vmis---n
mé	mé	mé-P	Pp1-s
focal	focal	focal-N	Ncmsc
fá	fá	faoi-P	Pr3ms
Mhánas	Mhánas	Mánas-N	Npmsc
ach	ach	ach-S	Sp
greim	greim	greim-N	Ncmsc
bia	bia	bia-N	Ncmsg
a	a	a-U	U
ithe	ithe	ith-N	Nv
,	,	,-F	Fi
spád	spád	spád-N	Ncfsc
,	,	,-F	Fi
agus	agus	agus-C	Cc
ráca	ráca	ráca-N	Ncmsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
liom	liom	le-P	Pr1-s
agus	agus	agus-C	Cc
déanamh	déanamh	déan-N	Ncmpg|Ncmsc|Nv
síos	síos	síos-R	Rd
Faoi	Faoi	faoi-S	Sp
na	na	na-T	Td-p
Beanna	Beanna	beann-N	Ncfpc
arís	arís	arís-R	Rg
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
mé	mé	mé-P	Pp1-s
leis	leis	le-S	Sp
an	an	an-T	Td-s
ráca	ráca	ráca-N	Ncmsc
agus	agus	agus-C	Cc
rois	rois	rois-V	Vmis
mé	mé	mé-P	Pp1-s
t	t	t-X	Xl
‑	‑	‑-F	Fb
eidheann	eidheann	eidheann-N	Ncmsc
den	den	de-S	Spa-s
talamh	talamh	talamh-N	Ncfsc
agus	agus	agus-C	Cc
tharraing	tharraing	tarraing-V	Vmis
é	é	é-P	Pp3ms
ina	ina	i-S	Spp-s|Spp-p
rollóga	rollóga	rollóg-N	Ncfpc
síos	síos	síos-R	Rd
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
chladach	chladach	cladach-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmm-2s
na	na	na-T	Td-p
rollóga	rollóga	rollóg-N	Ncfpc
níos	níos	níos-U	Uc
mó	mó	mór-A	Aqc
agus	agus	agus-C	Cc
níos	níos	níos-U	Uc
mó	mó	mór-A	Aqc
.	.	.-F	Fe
I	I	i-S	Sp
gceann	gceann	ceann-N	Ncmsc
gach	gach	gach-D	Dq
tamaill	tamaill	tamall-N	Ncmpc
b	b	b-X	Xl
’	’	’-F	Fa
éigean	éigean	éigean-N	Ncmsc
dom	dom	do-P	Pr1-s
toiseacht	toiseacht	toiseacht-N	Ncfsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
chorrán	chorrán	corrán-N	Ncmsc
agus	agus	agus-C	Cc
t	t	t-X	Xl
‑	‑	‑-F	Fb
eidheann	eidheann	eidheann-N	Ncmsc
a	a	a-U	U
ghearradh	ghearradh	gearr-N	Nv
ag	ag	ag-S	Sp
bun	bun	bun-N	Ncmsc
na	na	na-T	Tdfsg
rollóige	rollóige	rollóg-N	Ncfsg
sa	sa	i-S	Spa-s
dóigh	dóigh	dóigh-N	Ncfsc
is	is	agus-C	Cc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
mé	mé	mé-P	Pp1-s
ábalta	ábalta	ábalta-A	Aqp
an	an	an-T	Td-s
rollóg	rollóg	rollóg-N	Ncfsc
a	a	a-U	U
rolláil	rolláil	rolláil-N	Nv
síos	síos	síos-R	Rd
agus	agus	agus-C	Cc
isteach	isteach	isteach-R	Rd
san	san	i-S	Spa-s
fharraige	fharraige	farraige-N	Ncfsc
,	,	,-F	Fi
ansin	ansin	ansin-R	Rt|Rl
toiseacht	toiseacht	toiseacht-N	Ncfsc
arís	arís	arís-R	Rg
ar	ar	ar-S	Sp
rollóg	rollóg	rollóg-N	Ncfsc
eile	eile	eile-D	Dd
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
obair	obair	obair-N	Ncfsc|Nv-----n
mé	mé	mé-P	Pp1-s
mar	mar	mar-C	Cs
sin	sin	sin-W	W
i rith	i rith	i_rith-S	Spc
an	an	an-T	Td-s
lae	lae	lá-N	Ncmsg
go dtí	go dtí	go_dtí-S	Spc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
píosa	píosa	píosa-N	Ncmsc
deireanach	deireanach	deireanach-A	Aq-msc
den	den	de-S	Spa-s
eidheann	eidheann	eidheann-N	Ncmsc
glanta	glanta	glan-A	Av
ar	ar	ar-S	Sp
shiúl	shiúl	siúl-N	Ncmsc
agam	agam	ag-P	Pr1-s
agus	agus	agus-C	Cc
mise	mise	mé-P	Pp1-s-e
marbh	marbh	marbh-N	Ncmsc|Aqp
tuirseach	tuirseach	tuirseach-A	Aqp|Aq-msc
.	.	.-F	Fe
Anois	Anois	anois-R	Rt
,	,	,-F	Fi
dar	dar	dar-V	Vmip
liom	liom	le-P	Pr1-s
,	,	,-F	Fi
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
mo	mo	mo-D	Dp1-s
chuidse	chuidse	cuid-N	Ncfsc-e
den	den	de-S	Spa-s
mhargadh	mhargadh	margadh-N	Ncmsc
déanta	déanta	déan-A	Aqp|Av
agus	agus	agus-C	Cc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
in	in	i-S	Sp
am	am	am-N	Ncmsc
ag	ag	ag-S	Sp
Mánas	Mánas	Mánas-N	Npmsc
mo	mo	mo-D	Dp1-s
luach	luach	luach-N	Ncmsc
saothair	saothair	saothar-N	Ncmsg|Ncmpc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
dom	dom	do-P	Pr1-s
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
shocraigh	shocraigh	socraigh-V	Vmis
muid	muid	muid-P	Pp1-p
.	.	.-F	Fe
'	'	'-F	Fa
Mánas	Mánas	Mánas-N	Npmsc
a	a	a-D	Dp3
’	’	’-F	Fa
tSeabhaic	tSeabhaic	seabhac-N	Ncmsg
,	,	,-F	Fi
Mánas	Mánas	Mánas-N	Npmsc
a	a	a-D	Dp3
’	’	’-F	Fa
tSeabhaic	tSeabhaic	seabhac-N	Ncmsg
,	,	,-F	Fi
Mánas	Mánas	Mánas-N	Npmsc
a	a	a-D	Dp3
’	’	’-F	Fa
tSeabhaic	tSeabhaic	seabhac-N	Ncmsg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
mé	mé	mé-P	Pp1-s
féin	féin	féin-P	Px
os	os	os-N	Ncmsc|Sp
íseal	íseal	íseal-N	Ncmpg|Aq-msc|Ncmsc|Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
lena	lena	le-S	Spp-s
fhocal	fhocal	focal-N	Ncmsc
;	;	;-F	Fi
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
mo	mo	mo-D	Dp1-s
thaobh	thaobh	taobh-N	Ncmsc
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bhuailfeá	bhuailfeá	buail-V	Vmc-2s
do	do	do-S	Sp
dhá	dhá	dó-M	Mc
bhos	bhos	bos-N	Ncfsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
sásta	sásta	sásta-A	Aqp
leis	leis	le-S	Sp
an	an	an-T	Td-s
obair	obair	obair-N	Ncfsc
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
mé	mé	mé-P	Pp1-s
féin	féin	féin-P	Px
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
'	'	'-F	Fa
Bhuel	Bhuel	bhuel-X	Xsc
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
fá	fá	faoi-P	Pr3ms
do	do	do-S	Sp
chuidse	chuidse	cuid-N	Ncfsc-e
den	den	de-S	Spa-s
mhargadh	mhargadh	margadh-N	Ncmsc
?	?	?-F	Fq
'	'	'-F	Fa
'	'	'-F	Fa
Gheall	Gheall	geall-V	Vmis
mise	mise	mé-P	Pp1-s-e
go	go	go-C	Cs
n	n	n-X	Xl
‑	‑	‑-F	Fb
inseoinn	inseoinn	inis-V	Vmc-1s
duit	duit	do-P	Pr2-s
cá	cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
Taisce	Taisce	taisce-N	Ncfsc
an	an	an-T	Td-s
Úcaire	Úcaire	Úcaire-N	Npmsg|Npfsg
i	i	i-S	Sp
bhfolach	bhfolach	folach-N	Ncmsc
agus	agus	agus-C	Cc
déanfaidh	déanfaidh	déan-V	Vmif
mé	mé	mé-P	Pp1-s
sin	sin	sin-P	Pd
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
sí	sí	sí-P	Pp3fsn
i	i	i-S	Sp
bhfolach	bhfolach	folach-N	Ncmsc
ar	ar	ar-S	Sp
bhruach	bhruach	bruach-N	Ncmsc
Loch	Loch	loch-N	Ncmsc
an	an	an-T	Td-s
Mhuilinn	Mhuilinn	Muilinn-N	Npfsg
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
sin	sin	sin-P	Pd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
mise	mise	mé-P	Pp1-s-e
.	.	.-F	Fe
'	'	'-F	Fa
Chuala	Chuala	clois-V	Vmis
mé	mé	mé-P	Pp1-s
go	go	go-U	Ua
minic	minic	minic-A	Aqp
sa	sa	i-S	Spa-s
tseanchas	tseanchas	seanchas-N	Ncfsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
cheist	cheist	ceist-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
–	–	–-X	Xx
cá	cá	cá-R	Rq
háit	háit	áit-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhruach	bhruach	bruach-N	Ncmsc
?	?	?-F	Fq
'	'	'-F	Fa
'	'	'-F	Fa
Siúil	Siúil	siúl-N	Ncmsg
thusa	thusa	tú-P	Pp2-s-e
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
do	do	do-S	Sp
dheiseal	dheiseal	deiseal-N	Ncmsc
thar	thar	thar-S	Sp
bhruach	bhruach	bruach-N	Ncmsc
an	an	an-T	Td-s
locha	locha	loch-N	Ncmsg
go	go	go-Q	Q
dtiocfaidh	dtiocfaidh	tar-V	Vmif
tú	tú	tú-P	Pp2-s
a	a	a-D	Dp3
fhad	fhad	fad-N	Ncmsc
le	le	le-S	Sp
sruthán	sruthán	sruthán-N	Ncmsc
ag	ag	ag-S	Sp
sileadh	sileadh	sil-N	Nv
amach	amach	amach-R	Rd
as	as	as-P	Pr3ms
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
lean	lean	lean-V	Vmis
an	an	an-T	Td-s
sruthán	sruthán	sruthán-N	Ncmsc
trí	trí	trí-M	Mc|Sp
choiscéim	choiscéim	coiscéim-N	Ncfsc
.	.	.-F	Fe
Tiontaigh	Tiontaigh	tiontaigh-V	Vmm-2s
do	do	do-S	Sp
chúl	chúl	cúl-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
tsruthán	tsruthán	sruthán-N	Ncfsc
agus	agus	agus-C	Cc
tabhair	tabhair	tabhair-V	Vmm-2s
trí	trí	trí-M	Mc|Sp
choiscéim	choiscéim	coiscéim-N	Ncfsc
eile	eile	eile-D	Dd
.	.	.-F	Fe
Stad	Stad	stad-V	Vmm-2s
.	.	.-F	Fe
Tosaigh	Tosaigh	tosaigh-V	Vmm-2s
ag	ag	ag-S	Sp
tochailt	tochailt	tochail-N	Nv
ag	ag	ag-S	Sp
barr	barr	barr-N	Ncmsc
do	do	do-S	Sp
ladhaire	ladhaire	ladhaire-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
bhí	bhí	bí-V	Vmis
Mánas	Mánas	Mánas-N	Npmsc
ar	ar	ar-S	Sp
shiúl	shiúl	siúl-N	Ncmsc
as	as	as-S	Sp
amharc	amharc	amharc-N	Ncmsc
.	.	.-F	Fe
Tuirseach	Tuirseach	tuirseach-N	Ncmsc
is	is	agus-W	Wp-i|Wpri|Cc
uile	uile	uile-N	Ns-s|Dq
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
rinne	rinne	déan-V	Vmis
mé	mé	mé-P	Pp1-s
suas	suas	suas-R	Rd
chun	chun	chun-S	Sp
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
,	,	,-F	Fi
chuir	chuir	cuir-V	Vmis
ar	ar	ar-S	Sp
shiúl	shiúl	siúl-N	Ncmsc
an	an	an-T	Td-s
ráca	ráca	ráca-N	Ncmsg
agus	agus	agus-C	Cc
an	an	an-T	Td-s
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
spád	spád	spád-N	Ncfsc
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
mbúit	mbúit	mbúit-N	Ncfsc
an	an	an-T	Td-s
chairr	chairr	carr-N	Ncmsg
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmm-2s
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
ar	ar	ar-S	Sp
Loch	Loch	loch-N	Ncmsc
an	an	an-T	Td-s
Mhuilinn	Mhuilinn	Muilinn-N	Npfsg
.	.	.-F	Fe
Anois	Anois	anois-R	Rt
bhí	bhí	bí-V	Vmis
titim	titim	titim-N	Ncfsc
na	na	na-T	Tdfsg
hoíche	hoíche	oíche-N	Ncfsg
ann	ann	ann-R	Rl
,	,	,-F	Fi
rud	rud	rud-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
maith	maith	maith-N	Ncfsc
nó	nó	nó-C	Cc
níor	níor	is-W	Ws-in
mhaith	mhaith	maith-A	Aqp
liom	liom	le-P	Pr1-s
go	go	go-Q	Q
bhfeicfí	bhfeicfí	feic-V	Vmc-0
mé	mé	mé-P	Pp1-s
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhág	fhág	fág-V	Vmis
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
carr	carr	carr-N	Ncmsc|Ncfsc
ar	ar	ar-S	Sp
thaobh	thaobh	taobh-N	Ncmsc
bhealaigh	bhealaigh	bealaigh-V	Vmis
mhóir	mhóir	mór-A	Aq-msv|Aq-msg
,	,	,-F	Fi
thug	thug	tabhair-V	Vmis
liom	liom	le-P	Pr1-s
an	an	an-T	Td-s
spád	spád	spád-N	Ncfsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
lampa	lampa	lampa-N	Ncmsg
,	,	,-F	Fi
agus	agus	agus-C	Cc
rinne	rinne	déan-V	Vmis
ar	ar	ar-S	Sp
an	an	an-T	Td-s
loch	loch	loch-N	Ncmsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
shroich	shroich	sroich-V	Vmis
mé	mé	mé-P	Pp1-s
cladach	cladach	cladach-N	Ncmsc
an	an	an-T	Td-s
locha	locha	loch-N	Ncmsg
rinne	rinne	déan-V	Vmis
mé	mé	mé-P	Pp1-s
mar	mar	mar-C	Cs|Sp
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
iarr	iarr	iarr-V	Vmm-2s
Mánas	Mánas	Mánas-N	Npmsc
agus	agus	agus-C	Cc
shiúil	shiúil	siúil-V	Vmis
mé	mé	mé-P	Pp1-s
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
mo	mo	mo-D	Dp1-s
dheiseal	dheiseal	deiseal-N	Ncmsc
thart	thart	thart-R	Rd
an	an	an-T	Td-s
cladach	cladach	cladach-N	Ncmsc
.	.	.-F	Fe
Tuairim	Tuairim	tuairim-N	Ncfsc
is	is	agus-C	Cc
ar	ar	ar-S	Sp
leathmhíle	leathmhíle	leathmhíle-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
siúlta	siúlta	siúil-A	Av
agam	agam	ag-P	Pr1-s
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
mé	mé	mé-P	Pp1-s
a	a	a-D	Dp3
fhad	fhad	fad-N	Ncmsc
le	le	le-S	Sp
sruthán	sruthán	sruthán-N	Ncmsc
ag	ag	ag-S	Sp
sileadh	sileadh	sil-N	Nv
amach	amach	amach-R	Rd
as	as	as-S	Sp
an	an	an-T	Td-s
loch	loch	loch-N	Ncmsc
.	.	.-F	Fe
Stad	Stad	stad-V	Vmis
mé	mé	mé-P	Pp1-s
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-V	Vmm-2s
mé	mé	mé-P	Pp1-s
thart	thart	thart-R	Rd
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
duine	duine	duine-N	Ncmsc
le	le	le-S	Sp
feiceáil	feiceáil	feic-N	Nv
.	.	.-F	Fe
Char	Char	char-Q	Qn
mhaith	mhaith	maith-V	Vmis---n
liom	liom	le-P	Pr1-s
go	go	go-Q	Q
bhfeicfeadh	bhfeicfeadh	feic-V	Vmc
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
leis	leis	le-S	Sp
an	an	an-T	Td-s
talamh	talamh	talamh-N	Ncfsc
mé	mé	mé-P	Pp1-s
ná	ná	ná-C	Cc
duine	duine	duine-N	Ncmsc|Ncmsg
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
eile	eile	eile-D	Dd
ach	ach	ach-S	Sp
oiread	oiread	oiread-N	Ns-s
.	.	.-F	Fe
Ghlac	Ghlac	glac-V	Vmis
mé	mé	mé-P	Pp1-s
na	na	na-T	Tdfsg
sé	sé	sé-W	Wp-i-3|Pp3msn
chéim	chéim	céim-N	Ncfsc
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
ordaíodh	ordaíodh	ordaigh-V	Vmis0
.	.	.-F	Fe
Stad	Stad	stad-V	Vmis
mé	mé	mé-P	Pp1-s
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-V	Vmm-2s
mé	mé	mé-P	Pp1-s
thart	thart	thart-R	Rd
.	.	.-F	Fe
Ciúnas	Ciúnas	ciúnas-N	Ncmsc
!	!	!-F	Fe
Suaimhneas	Suaimhneas	suaimhneas-N	Ncmsc
!	!	!-F	Fe
Uaigneas	Uaigneas	uaigneas-N	Ncmsc
!	!	!-F	Fe
Cé	Cé	cé-P	Pq
a	a	a-Q	Q-r
chuir	chuir	cuir-V	Vmis
an	an	an-T	Td-s
taisce	taisce	taisce-N	Ncfsc
i	i	i-S	Sp
bhfolach	bhfolach	folach-N	Ncmsc
anseo	anseo	anseo-R	Rl
?	?	?-F	Fq
Cad	Cad	cad-W	W--q
chuige	chuige	chuig-P	Pr3ms
?	?	?-F	Fq
Cérbh	Cérbh	cé-W	W--q
é	é	é-P	Pp3ms
an	an	is-W	Wpdq|Wp-q
t	t	t-X	Xl
‑	‑	‑-F	Fb
úcaire	úcaire	úcaire-N	Ncmsc
?	?	?-F	Fq
Thosaigh	Thosaigh	tosaigh-V	Vmis
na	na	na-T	Td-p
ceisteanna	ceisteanna	ceist-N	Ncfpc
seo	seo	seo-D	Dd
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
fríd	fríd	trí-N	Ncfsc|Sp
mo	mo	mo-D	Dp1-s
cheann	cheann	ceann-N	Ncmsc
.	.	.-F	Fe
Cad	Cad	cad-W	W--q
chuige	chuige	chuig-P	Pr3ms
nár	nár	nár-Q	Qnrs
baineadh	baineadh	bain-V	Vmis0--n
riamh	riamh	riamh-R	Rg
í	í	í-P	Pp3fs
?	?	?-F	Fq
B	B	B-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
gur	gur	gur-Q	Q--s
baineadh	baineadh	bain-V	Vmis0
agus	agus	agus-C	Cc
nach	nach	nach-Q	Qnr
bhfuil	bhfuil	bí-V	Vmip---n
dada	dada	dada-N	Ncmsc
ansin	ansin	ansin-R	Rt|Rl
anois	anois	anois-R	Rt
!	!	!-F	Fe
An	An	an-Q	Qq
raibh	raibh	bí-V	Vmis---d
Mánas	Mánas	Mánas-N	Npmsc
ag	ag	ag-S	Sp
inseacht	inseacht	inis-N	Nv
na	na	na-T	Tdfsg
fírinne	fírinne	fírinne-N	Ncfsg
?	?	?-F	Fq
An	An	an-Q	Qq
raibh	raibh	bí-V	Vmis---d
mallacht	mallacht	mallacht-N	Ncfsc
ag	ag	ag-S	Sp
gabháil	gabháil	gabh-N	Nv
leis	leis	le-S	Sp
an	an	an-T	Td-s
taisce	taisce	taisce-N	Ncfsc
seo	seo	seo-D	Dd
?	?	?-F	Fq
Is	Is	is-W	Wp-i
minic	minic	minic-A	Aqp
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
mé	mé	mé-P	Pp1-s
go	go	go-Q	Q
mbíonn	mbíonn	bí-V	Vmig
.	.	.-F	Fe
Cad	Cad	cad-W	W--q
chuige	chuige	chuig-P	Pr3ms
nár	nár	nár-Q	Qnrs
iarr	iarr	iarr-V	Vmis---n
mé	mé	mé-P	Pp1-s
rud	rud	rud-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
eile	eile	eile-D	Dd
?	?	?-F	Fq
An	An	an-Q	Qq
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
rómhall	rómhall	mall-A	Aqp
?	?	?-F	Fq
An	An	an-Q	Qq
dtiocfadh	dtiocfadh	tar-V	Vmc
liom	liom	le-P	Pr1-s
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
ar ais	ar ais	ar_ais-R	Rd
síos	síos	síos-R	Rd
Faoi	Faoi	faoi-S	Sp
na	na	na-T	Td-p
Beanna	Beanna	beann-N	Ncfpc
agus	agus	agus-C	Cc
luach	luach	luach-N	Ncmsc
saothair	saothair	saothar-N	Ncmsg
éigin	éigin	éigin-A	Aq-msg
eile	eile	eile-D	Dd
a	a	a-U	U
iarraidh	iarraidh	iarr-N	Nv
ar	ar	ar-S	Sp
Mhánas	Mhánas	Mánas-N	Npmsc
?	?	?-F	Fq
Sin	Sin	sin-W	W
an	an	an-T	Td-s
rud	rud	rud-N	Ncmsc
a	a	a-Q	Q-r
dhéanfainn	dhéanfainn	déan-V	Vmc-1s
.	.	.-F	Fe
'	'	'-F	Fa
Níor	Níor	níor-W	Ws-in|Qn-s
bhain	bhain	bain-V	Vmis|Vmis---n|Npmsc
mé	mé	mé-P	Pp1-s
dó	dó	do-P	Pr3ms
a	a	a-Q	Q-r
dhath	dhath	dath-V	Vmis
go	go	go-U	Ua
fóill	fóill	fóill-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
mise	mise	mé-P	Pp1-s-e
liom	liom	le-P	Pr1-s
féin	féin	féin-P	Px
.	.	.-F	Fe
'	'	'-F	Fa
Déarfaidh	Déarfaidh	abair-V	Vmif
mé	mé	mé-P	Pp1-s
leis	leis	le-P	Pr3ms
nach	nach	nach-Q	Qnr
bhfuil	bhfuil	bí-V	Vmip---n
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
an	an	an-T	Td-s
taisce	taisce	taisce-N	Ncfsg
ach	ach	ach-C	Cs
gurbh	gurbh	is-W	Wsdi
fhearr	fhearr	maith-A	Aqc
liom	liom	le-P	Pr1-s
rud	rud	rud-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
eile	eile	eile-D	Dd
.	.	.-F	Fe
Anois	Anois	anois-R	Rt
ó	ó	ó-C	Cs
tá	tá	bí-V	Vmip
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
cá	cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
an	an	an-T	Td-s
taisce	taisce	taisce-N	Ncfsc
thig	thig	tar-V	Vmip
liom	liom	le-P	Pr1-s
teacht	teacht	tar-N	Nv
am	am	am-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
a	a	a-U	U
fháil	fháil	faigh-N	Nv
.	.	.-F	Fe
Sin	Sin	sin-W	W
má	má	má-C	Cs
tá	tá	bí-V	Vmip
sí	sí	sí-P	Pp3fsn
ansin	ansin	ansin-R	Rt|Rl
.	.	.-F	Fe
'	'	'-F	Fa
Ach	Ach	ach-C	Cs
nár	nár	is-W	Wssin|Wsdin
mhór	mhór	mór-A	Aqp
an	an	an-T	Td-s
trua	trua	trua-N	Ncfsc
imeacht	imeacht	imigh-N	Ncmsc|Nv
anois	anois	anois-R	Rt
agus	agus	agus-C	Cc
mé	mé	mé-P	Pp1-s
chomh	chomh	chomh-R	Ri
deas	deas	deas-A	Aqp
sin	sin	sin-W	W
don	don	do-S	Spa-s
taisce	taisce	taisce-N	Ncfsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
mhinic	mhinic	minic-A	Aqp
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
mé	mé	mé-P	Pp1-s
daoine	daoine	duine-N	Ncmpc
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
fán	fán	faoi-S	Spa-s
taisce	taisce	taisce-N	Ncfsc
ach	ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
acusan	acusan	ag-P	Pr3-p-e
an	an	an-T	Td-s
áit	áit	áit-N	Ncfsc
cheart	cheart	ceart-A	Aq-fsc
–	–	–-X	Xx
bhí	bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agamsa	agamsa	ag-P	Pr1-s-e
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
spád	spád	spád-N	Ncfsc
sa	sa	i-S	Spa-s
talamh	talamh	talamh-N	Ncfsc
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
mé	mé	mé-P	Pp1-s
mo	mo	mo-D	Dp1-s
chos	chos	cos-N	Ncfsc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Bhrúigh	Bhrúigh	brúigh-V	Vmis
mé	mé	mé-P	Pp1-s
síos	síos	síos-R	Rd
í	í	í-P	Pp3fs
go	go	go-U	Ua
faichilleach	faichilleach	faichilleach-A	Aqp
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
mhothaigh	mhothaigh	mothaigh-V	Vmis---n
mé	mé	mé-P	Pp1-s
a	a	a-Q	Q-r
dhath	dhath	dath-V	Vmis
.	.	.-F	Fe
Bhain	Bhain	bain-V	Vmis
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
phreab	phreab	preab-N	Ncfsc
sin	sin	sin-D	Dd
agus	agus	agus-C	Cc
preab	preab	preab-N	Ncfpg|Ncfsc
eile	eile	eile-D	Dd
agus	agus	agus-C	Cc
preab	preab	preab-N	Ncfpg|Ncfsc
eile	eile	eile-D	Dd
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
thosaigh	thosaigh	tosaigh-V	Vmis
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
tochailt	tochailt	tochail-N	Nv
níos	níos	níos-U	Uc
doimhne	doimhne	domhain-A	Aqc
.	.	.-F	Fe
Go	Go	go-U	Ua
tobann	tobann	tobann-A	Aqp
bhuail	bhuail	buail-V	Vmis
barr	barr	barr-N	Ncmsc
na	na	na-T	Tdfsg
spáide	spáide	spád-N	Ncfsg
rud	rud	rud-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
crua	crua	crua-A	Aqp
.	.	.-F	Fe
Chaith	Chaith	caith-V	Vmis
mé	mé	mé-P	Pp1-s
uaim	uaim	ó-N	Ncfsc|Pr1-s
an	an	an-T	Td-s
spád	spád	spád-N	Ncfsc
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
tochailt	tochailt	tochail-N	Nv
le	le	le-S	Sp
mo	mo	mo-D	Dp1-s
dhá	dhá	dó-M	Mc
lámh	lámh	lámh-N	Ncfsc
.	.	.-F	Fe
Leac	Leac	leac-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
barr	barr	barr-N	Ncmsc
na	na	na-T	Tdfsg
leice	leice	leac-N	Ncfsg
glanta	glanta	glan-A	Av
agam	agam	ag-P	Pr1-s
.	.	.-F	Fe
Go	Go	go-U	Ua
cúramach	cúramach	cúramach-A	Aqp
chuir	chuir	cuir-V	Vmis
mé	mé	mé-P	Pp1-s
mo	mo	mo-D	Dp1-s
mhéara	mhéara	méara-N	Ncfpc|Ncmsc
thart	thart	thart-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
leac	leac	leac-N	Ncfsc
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
á	á	do-S	Spo-s
tarraingt	tarraingt	tarraing-N	Nv
chugam	chugam	chuig-P	Pr1-s
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
sí	sí	sí-P	Pp3fsn
liom	liom	le-P	Pr1-s
.	.	.-F	Fe
Thóg	Thóg	tóg-V	Vmis
mé	mé	mé-P	Pp1-s
amach	amach	amach-R	Rd
í	í	í-P	Pp3fs
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
fhág	fhág	fág-V	Vmis
ina	ina	i-S	Spp-s|Spp-p
luí	luí	luí-N	Ncmsc
ag	ag	ag-S	Sp
mo	mo	mo-D	Dp1-s
thaobh	thaobh	taobh-N	Ncmsc
í	í	í-P	Pp3fs
.	.	.-F	Fe
Fuair	Fuair	faigh-V	Vmis
mé	mé	mé-P	Pp1-s
mo	mo	mo-D	Dp1-s
lampa	lampa	lampa-N	Ncmsc
,	,	,-F	Fi
las	las	las-V	Vmis
mé	mé	mé-P	Pp1-s
í	í	í-P	Pp3fs
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-V	Vmm-2s
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
pholl	pholl	poll-N	Ncmsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
os	os	os-N	Ncmsc|Sp
mo	mo	mo-D	Dp1-s
choinne	choinne	coinne-N	Ncfsc
bhí	bhí	bí-V	Vmis
poll	poll	poll-N	Ncmsc|Xfen
fá	fá	faoi-P	Pr3ms
mhéid	mhéid	méid-N	Ncfsc|Ncmsc
buicéid	buicéid	buicéad-N	Ncmsg
agus	agus	agus-C	Cc
mála	mála	mála-N	Ncmsc|Ncmsg
de	de	de-S	Sp
chineál	chineál	cineál-N	Ncmsc
éigin	éigin	éigean-N	Ncmsg
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Thóg	Thóg	tóg-V	Vmis
mé	mé	mé-P	Pp1-s
amach	amach	amach-R	Rd
an	an	an-T	Td-s
mála	mála	mála-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
bhéal	bhéal	béal-N	Ncmsc
ceangailte	ceangailte	ceangail-A	Av
le	le	le-S	Sp
sreangán	sreangán	sreangán-N	Ncmsc
.	.	.-F	Fe
Scaoil	Scaoil	scaoil-V	Vmis
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
sreangán	sreangán	sreangán-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-V	Vmm-2s
mé	mé	mé-P	Pp1-s
isteach	isteach	isteach-R	Rd
.	.	.-F	Fe
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
féin	féin	féin-P	Px
chuala	chuala	clois-V	Vmis
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
uaill	uaill	uaill-N	Ncfsc
ba	ba	is-U	U
mhó	mhó	mór-A	Aqc
dár	dár	do-S	Spp-p
chuala	chuala	clois-V	Vmis
mé	mé	mé-P	Pp1-s
riamh	riamh	riamh-R	Rg
.	.	.-F	Fe
Bhain	Bhain	bain-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
croí	croí	croí-N	Ncmsc
asam	asam	as-P	Pr1-s
.	.	.-F	Fe
Leis	Leis	le-S	Sp
an	an	an-T	Td-s
scanradh	scanradh	scanradh-N	Ncmsc
a	a	a-Q	Q-i|Q-r
fuair	fuair	faigh-V	Vmis
mé	mé	mé-P	Pp1-s
lig	lig	lig-V	Vmis
mé	mé	mé-P	Pp1-s
don	don	do-S	Spa-s
mhála	mhála	mála-N	Ncmsc
titim	titim	titim-N	Nv|Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
leac	leac	leac-N	Ncfsc
agus	agus	agus-C	Cc
…	…	…-F	Fi
mhúscail	mhúscail	múscail-V	Vmis
mise	mise	mé-P	Pp1-s-e
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
shuí	shuí	suí-N	Nv|Ncmsc
in	in	i-S	Sp
Ard	Ard	ard-N	Ncmsc
an	an	an-T	Td-s
Chnámharlaigh	Chnámharlaigh	cnámharlach-N	Ncmsg
agus	agus	agus-C	Cc
asal	asal	asal-N	Ncmpg|Ncmsc
ag	ag	ag-S	Sp
búireadh	búireadh	búir-N	Nv
fá	fá	faoi-P	Pr3ms
dheich	dheich	deich-N	Ncmsc
slat	slat	slat-N	Ncfsc|Ncfpg
díom	díom	de-P	Pr1-s
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
croí	croí	croí-N	Ncmsc
scanraithe	scanraithe	scanraigh-A	Av
asam	asam	as-P	Pr1-s
.	.	.-F	Fe
Chruinnigh	Chruinnigh	cruinnigh-V	Vmis
mé	mé	mé-P	Pp1-s
mé	mé	mé-P	Pp1-s
féin	féin	féin-P	Px
i gceann	i gceann	i_gceann-S	Spc
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
agus	agus	agus-C	Cc
rinne	rinne	déan-V	Vmis
mo	mo	mo-D	Dp1-s
bhealach	bhealach	bealach-N	Ncmsc
ar ais	ar ais	ar_ais-R	Rd
aníos	aníos	aníos-R	Rd
na	na	na-T	Td-p
beanna	beanna	beann-N	Ncfpc
chun	chun	chun-S	Sp
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
.	.	.-F	Fe
Díreach	Díreach	díreach-N	Ncmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
ar	ar	ar-S	Sp
bharr	bharr	barr-N	Ncmsc
na	na	na-T	Td-p
mbeann	mbeann	beann-N	Ncfpg
d	d	d-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-V	Vmm-2s
mé	mé	mé-P	Pp1-s
síos	síos	síos-R	Rd
agus	agus	agus-C	Cc
chonaic	chonaic	feic-V	Vmis
mé	mé	mé-P	Pp1-s
rud	rud	rud-N	Ncmsc
a	a	a-Q	Q-r
chuir	chuir	cuir-V	Vmis
iontas	iontas	iontas-N	Ncmsc
orm	orm	ar-P	Pr1-s
.	.	.-F	Fe
San	San	i-S	Spa-s
áit	áit	áit-N	Ncfsc
ar	ar	ar-S	Sp
shíl	shíl	síol-N	Ncmsg
mé	mé	mé-P	Pp1-s
eidheann	eidheann	eidheann-N	Ncmsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
fás	fás	fás-N	Nv
bhí	bhí	bí-V	Vmis
féar	féar	féar-N	Ncmsc
deas	deas	deas-R	Ri
bog	bog	bog-A	Aqp
glas	glas	glas-A	Aqp
.	.	.-F	Fe
'	'	'-F	Fa
Bíonn	Bíonn	bí-V	Vmig
na	na	na-T	Td-p
hiontais	hiontais	iontas-N	Ncmpc
ann	ann	i-P	Pr3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
mé	mé	mé-P	Pp1-s
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmm-2s
mé	mé	mé-P	Pp1-s
liom	liom	le-P	Pr1-s
chun	chun	chun-S	Sp
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
.	.	.-F	Fe
