 Marbhánach	Marbhánach	-X	Xx
Beo	Beo	beo-A	Aqc
Tráthnóna	Tráthnóna	tráthnóna-N	Ncmsc
fuar	fuar	fuar-A	Aq-msc
i	i	i-S	Sp
ndeireadh	ndeireadh	deireadh-N	Ncmsc
mhí	mhí	mí-N	Ncmsg
Dheireadh Fómhair	Dheireadh Fómhair	Deireadh_Fómhair-N	Ncmsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
fuair	fuair	faigh-V	Vmis
Tarlach	Tarlach	Tarlach-N	Npmsc
Rua	Rua	Rua-N	Npmsc
an	an	an-T	Td-s
scéala	scéala	scéala-N	Ncmsg
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
a	a	a-D	Dp3
dheartháir	dheartháir	deartháir-N	Ncmsc
,	,	,-F	Fi
Peadar	Peadar	Peadar-N	Ncmsc|Npmsc
,	,	,-F	Fi
i ndiaidh	i ndiaidh	i_ndiaidh-S	Spc
bás	bás	bás-N	Ncmsc
a	a	a-U	U
fháil	fháil	faigh-N	Nv
san	san	sin-S	Spa-s|Pd
otharlann	otharlann	otharlann-N	Ncfpg|Ncfsc
i	i	i-S	Sp
Srath	Srath	Srath-N	Npmsc
an	an	an-T	Td-s
Urláir	Urláir	urlár-N	Ncmsg
.	.	.-F	Fe
Léigh	Léigh	léigh-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
sreangscéal	sreangscéal	sreangscéal-N	Ncmsc
trí	trí	trí-M	Mc
nó	nó	nó-C	Cc
ceithre	ceithre	ceathair-M	Mc
huaire	huaire	uair-N	Ncfsg
le	le	le-S	Sp
bheith	bheith	bí-N	Nv
cinnte	cinnte	cinn-A	Av
fán	fán	faoi-S	Spa-s
scéal	scéal	scéal-N	Ncmsc
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
ndóigh	ndóigh	dóigh-N	Ncfsc
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
cineál	cineál	cineál-N	Ncmsc
ag	ag	ag-S	Sp
súil	súil	súil-N	Nv-----n
leis	leis	le-P	Pr3ms
seo	seo	seo-P	Pd
le	le	le-S	Sp
tamall	tamall	tamall-N	Ncmsc
nó	nó	nó-C	Cc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
an	an	an-T	Td-s
tsláinte	tsláinte	sláinte-N	Ncfsc
go	go	go-U	Ua
maith	maith	maith-A	Aqp
ag	ag	ag-S	Sp
an	an	an-T	Td-s
Pheadar	Pheadar	Peadar-N	Ncmsc|Npmsc
chéanna	chéanna	céanna-A	Aqp
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
an	an	an-T	Td-s
chuma	chuma	cuma-N	Ncfsc
air	air	ar-P	Pr3ms
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
biseach	biseach	biseach-N	Ncmsc
i	i	i-S	Sp
ndán	ndán	dán-N	Ncmsc
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
Tarlach	Tarlach	Tarlach-N	Npmsc
thart	thart	thart-R	Rd
ar	ar	ar-S	Sp
chúpla	chúpla	cúpla-N	Ncmsc
duine	duine	duine-N	Ncmsg
de	de	de-S	Sp
na	na	na-T	Td-p
comharsana	comharsana	comharsa-N	Ncfpc
gur	gur	gur-Q	Q--s
inis	inis	inis-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
dóibh	dóibh	do-P	Pr3-p
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
aige	aige	ag-P	Pr3ms
go	go	go-Q	Q
gcruinneodh	gcruinneodh	cruinnigh-V	Vmc
siadsan	siadsan	siad-P	Pp3-pne
leis	leis	le-S	Sp
an	an	an-T	Td-s
teach	teach	teach-N	Ncmsc
a	a	a-U	U
fháil	fháil	faigh-N	Nv
réidh	réidh	réidh-A	Aqp
fá choinne	fá choinne	fá_choinne-S	Spc
na	na	na-T	Tdfsg
faire	faire	faire-N	Ncfsg
a	a	a-D	Dp3
fhad	fhad	fad-N	Ncmsc
is	is	agus-C	Cc
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
seisean	seisean	sé-P	Pp3msne
ag	ag	ag-S	Sp
gabháil	gabháil	gabh-N	Nv
go	go	go-S	Sp
Srath	Srath	Srath-N	Npmsc
an	an	an-T	Td-s
Urláir	Urláir	urlár-N	Ncmsg
fá choinne	fá choinne	fá_choinne-S	Spc
an	an	an-T	Td-s
choirp	choirp	corp-N	Ncmsg
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
phill	phill	pill-V	Vmis
Tarlach	Tarlach	Tarlach-N	Npmsc
chun	chun	chun-S	Sp
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
rinne	rinne	déan-V	Vmis
sé	sé	sé-P	Pp3msn
cinnte	cinnte	cinnte-A	Av|Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
achan	achan	gach-D	Dq
rud	rud	rud-N	Ncmsc
in	in	i-S	Sp
ord	ord	ord-N	Ncmsc
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
airgead	airgead	airgead-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ina	ina	i-S	Spp-s|Spp-p
luí	luí	luí-N	Ncmsc
thart	thart	thart-R	Rd
agus	agus	agus-C	Cc
rudaí	rudaí	rud-N	Ncmpc
príobháideacha	príobháideacha	príobháideach-A	Aq--pc
i	i	i-S	Sp
bhfolach	bhfolach	folach-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
hé	hé	é-P	Pp3ms
nár	nár	nár-Q	Qnrs
thrust	thrust	trust-V	Vmis---n
sé	sé	sé-P	Pp3msn
na	na	na-T	Td-p
comharsana	comharsana	comharsa-N	Ncfpc
ach	ach	ach-C	Cs
san	san	i-S	Spa-s
am	am	am-N	Ncmsc
chéanna	chéanna	céanna-A	Aqp
b	b	b-X	Xl
’	’	’-F	Fa
fhearr	fhearr	maith-A	Aqc
a	a	a-U	U
bheith	bheith	bí-N	Nv
cinnte	cinnte	cinn-A	Av
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
nigh	nigh	nigh-V	Vmis
sé	sé	sé-P	Pp3msn
agus	agus	agus-C	Cc
bhearr	bhearr	bearr-V	Vmis
sé	sé	sé-P	Pp3msn
agus	agus	agus-C	Cc
chóirigh	chóirigh	cóirigh-V	Vmis
sé	sé	sé-P	Pp3msn
é	é	é-P	Pp3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sin	sin	sin-P	Pd
uile	uile	uile-N	Ns-s|Dq
déanta	déanta	déan-A	Av
aige	aige	ag-P	Pr3ms
thug	thug	tabhair-V	Vmis
sé	sé	sé-P	Pp3msn
léim	léim	léim-N	Ncfsc|Nv
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
rothar	rothar	rothar-N	Ncmsc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
tarraingt	tarraingt	tarraing-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhaile	bhaile	baile-N	Ncmsg
mhór	mhór	mór-A	Aq-msc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmm-2s
leis	leis	le-S	Sp
na	na	na-T	Tdfsg
ceithre	ceithre	ceathair-M	Mc
mhíle	mhíle	míle-N	Ncmsc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
gan	gan	gan-S	Sp
chith	chith	cith-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
ceathanna	ceathanna	cith-N	Ncmpc
troma	troma	trom-A	Aq--pc
cloch	cloch	cloch-N	Ncfpg|Ncfsc
sneachta	sneachta	sneachta-N	Ncmsg|Ncmsc
ann	ann	i-R	Rl|Pr3ms
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
sin	sin	sin-D	Dd
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
shroich	shroich	sroich-V	Vmis
Tarlach	Tarlach	Tarlach-N	Npmsc
tábhairne	tábhairne	tábhairne-N	Ncmsc
Phádraig	Phádraig	Pádraig-N	Npm-g|Npfsg
d	d	d-X	Xl
’	’	’-F	Fa
fhág	fhág	fág-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
rothar	rothar	rothar-N	Ncmsc
i	i	i-S	Sp
gcúl	gcúl	cúl-N	Ncmsc
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
agus	agus	agus-C	Cc
isteach	isteach	isteach-R	Rd
leis	leis	le-S	Sp
sa	sa	i-S	Spa-s
bheár	bheár	beár-N	Ncmsc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
ordaigh	ordaigh	ordaigh-V	Vmm-2s
leathcheann	leathcheann	leathcheann-N	Ncmsc
uisce	uisce	uisce-N	Ncmsg|Ncmsc
beatha	beatha	beatha-N	Ncmsg|Ncfsg|Ncfsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
fuair	fuair	faigh-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
deoch	deoch	deoch-N	Ncfsc
bhain	bhain	bain-V	Vmis
sé	sé	sé-P	Pp3msn
slog	slog	slog-N	Ncmsc|Xfen
as	as	as-P	Pr3ms
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
den	den	de-S	Spa-s
chailín	chailín	cailín-N	Ncmsc
an	an	an-Q	Qq
raibh	raibh	bí-V	Vmis---d
Pádraig	Pádraig	Pádraig-N	Npmsc
thart	thart	thart-R	Rd
.	.	.-F	Fe
Dúirt	Dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmis
sí	sí	sí-P	Pp3fsn
suas	suas	suas-R	Rd
chun	chun	chun-S	Sp
na	na	na-T	Tdfsg
cisteanadh	cisteanadh	cisteanadh-N	Ncmsc
.	.	.-F	Fe
I	I	i-S	Sp
gceann	gceann	ceann-N	Ncmsc
bomaite	bomaite	bomaite-N	Ncmsg
anuas	anuas	anuas-R	Rd
le	le	le-S	Sp
Pádraig	Pádraig	Pádraig-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Is	Is	is-W	Wp-i
é	é	é-P	Pp3ms
do	do	do-S	Sp
bheatha	bheatha	beatha-N	Ncfsc
chun	chun	chun-S	Sp
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
seisean	seisean	sé-P	Pp3msne
ag	ag	ag-S	Sp
síneadh	síneadh	sín-N	Nv
amach	amach	amach-R	Rd
a	a	a-D	Dp3
lámh	lámh	lámh-N	Ncfsc
chuig	chuig	chuig-S	Sp
Tarlach	Tarlach	Tarlach-N	Npmsc
.	.	.-F	Fe
Chroith	Chroith	croith-V	Vmis
Tarlach	Tarlach	Tarlach-N	Npmsc
a	a	a-D	Dp3
lámh	lámh	lámh-N	Ncfsc
agus	agus	agus-C	Cc
arsa	arsa	arsa-V	Vmis
seisean	seisean	sé-P	Pp3msne
,	,	,-F	Fi
'	'	'-F	Fa
Faraor	Faraor	faraor-X	Xsc
,	,	,-F	Fi
ní	ní	ní-W	Wp-in|Nv|Ncmsc
le	le	le-S	Sp
dea	dea	dea-N	Ns-s
‑	‑	‑-F	Fb
scéala	scéala	scéala-N	Ncmsc
a	a	a-Q	Q-r
thagaim	thagaim	tar-V	Vmip1s
.	.	.-F	Fe
'	'	'-F	Fa
Agus	Agus	agus-C	Cc
thosaigh	thosaigh	tosach-N	Ncmpc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
inis	inis	inis-V	Vmm-2s
dó	dó	do-P	Pr3ms
fána	fána	faoi-S	Spp-s
dheartháir	dheartháir	deartháir-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
ó	ó	ó-C	Cs
,	,	,-F	Fi
tá	tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
buartha	buartha	buair-A	Av
fá	fá	faoi-P	Pr3ms
do	do	do-S	Sp
thrioblóid	thrioblóid	trioblóid-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Pádraig	Pádraig	Pádraig-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
a	a	a-D	Dp3
dhath	dhath	dath-N	Ncmsc
a	a	a-Q	Q-r
thig	thig	tar-V	Vmip
liom	liom	le-P	Pr1-s
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
duit	duit	do-P	Pr2-s
?	?	?-F	Fq
'	'	'-F	Fa
Ar	Ar	ar-S	Sp
ndóigh	ndóigh	dóigh-N	Ncfsc
bhí	bhí	bí-V	Vmis
fios	fios	fios-N	Ncmsc
maith	maith	maith-A	Aq-msc
ag	ag	ag-S	Sp
Pádraig	Pádraig	Pádraig-N	Npmsc
gurbh	gurbh	is-W	Wsdi
é	é	é-P	Pp3ms
sin	sin	sin-P	Pd|W
an	an	an-T	Td-s
tuige	tuige	tuige-N	Ncmsc|Ncmsg
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
Tarlach	Tarlach	Tarlach-N	Npmsc
sa	sa	i-S	Spa-s
teach	teach	teach-N	Ncmsc
nó	nó	nó-C	Cc
ní	ní	ní-W	Wp-in|Nv|Ncmsg|Nv|Ncmsg|Ncmsc
rómhinic	rómhinic	minic-A	Aqp
riamh	riamh	riamh-R	Rg
a	a	a-Q	Q-r
dhall	dhall	dall-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
dhoras	dhoras	doras-N	Ncmsc
.	.	.-F	Fe
Adhlacóir	Adhlacóir	adhlacóir-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
i	i	i-S	Sp
bPádraig	bPádraig	Pádraig-N	Npmsc
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
le	le	le-S	Sp
teach	teach	teach-N	Ncmsc
tábhairne	tábhairne	tábhairne-N	Ncmsg
a	a	a-U	U
bheith	bheith	bí-N	Nv
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Sin	Sin	sin-W	W
dá	dá	dá-C	Cs
dtiocfadh	dtiocfadh	tar-V	Vmc
leat	leat	le-P	Pr2-s
'	'	'-F	Fa
adhlacóir	adhlacóir	adhlacóir-N	Ncmsc
’	’	’-F	Fa
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
air	air	ar-P	Pr3ms
nó	nó	nó-C	Cc
is	is	agus-W	Wp-i|Wpri|Cc
beag	beag	beag-N	Ncmsc|Aqp
a	a	a-Q	Q-r
níodh	níodh	nigh-V	Vmih
a	a	a-D	Dp3
leithéid	leithéid	leithéid-N	Ncfsc
san	san	i-S	Spa-s
am	am	am-N	Ncmsc
sin	sin	sin-D	Dd
le	le	le-S	Sp
taobh	taobh	taobh-N	Ncmsc
dualgaisí	dualgaisí	dualgais-N	Ncfpc
adhlacóra	adhlacóra	adhlacóir-N	Ncmsg
inniu	inniu	inniu-R	Rt
.	.	.-F	Fe
'	'	'-F	Fa
Bhuel	Bhuel	bhuel-X	Xsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Tarlach	Tarlach	Tarlach-N	Npmsc
,	,	,-F	Fi
'	'	'-F	Fa
ba	ba	is-W	Wsri
mhaith	mhaith	maith-A	Aqp
liom	liom	le-P	Pr1-s
cónra	cónra	cónra-N	Ncfsc
a	a	a-U	U
cheannach	cheannach	ceannaigh-N	Nv
agus	agus	agus-C	Cc
tú	tú	tú-P	Pp2-s
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
liom	liom	le-P	Pr1-s
go	go	go-S	Sp
Srath	Srath	Srath-N	Npmsc
an	an	an-T	Td-s
Urláir	Urláir	urlár-N	Ncmsg
fá choinne	fá choinne	fá_choinne-S	Spc
an	an	an-T	Td-s
choirp	choirp	corp-N	Ncmsg
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Déanfaidh	Déanfaidh	déan-V	Vmif
,	,	,-F	Fi
cinnte	cinnte	cinnte-A	Av|Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Pádraig	Pádraig	Pádraig-N	Npmsc
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
gloine	gloine	gloine-N	Ncfsc
eile	eile	eile-D	Dd
uisce	uisce	uisce-N	Ncmsc
beatha	beatha	beatha-N	Ncmsg|Ncfsg|Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
chuntar	chuntar	cuntar-N	Ncmsc
os coinne	os coinne	os_coinne-S	Spc
Tharlaigh	Tharlaigh	tarlach-N	Ncmsg
.	.	.-F	Fe
'	'	'-F	Fa
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bheas	bheas	bí-V	Vmif---r
sin	sin	sin-P	Pd
ólta	ólta	ól-A	Av
agat	agat	ag-P	Pr2-s
rachaidh	rachaidh	téigh-V	Vmif
muid	muid	muid-P	Pp1-p
thart	thart	thart-R	Rd
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
clós	clós	clós-N	Ncmsc
go	go	go-Q	Q
gcuirfidh	gcuirfidh	cuir-V	Vmif
muid	muid	muid-P	Pp1-p
cónra	cónra	cónra-N	Ncfsc
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
charr	charr	carr-N	Ncmsc|Ncfsc
.	.	.-F	Fe
Díreach	Díreach	díreach-N	Ncmsc
anois	anois	anois-R	Rt
caithfidh	caithfidh	caith-V	Vmif
mise	mise	mé-P	Pp1-s-e
mo	mo	mo-D	Dp1-s
fhroc	fhroc	froc-N	Ncmsc
a	a	a-U	U
fháil	fháil	faigh-N	Nv
agus	agus	agus-C	Cc
féacháil	féacháil	féacháil-N	Nv
go	go	go-Q	Q
mbeidh	mbeidh	bí-V	Vmif
duine	duine	duine-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
anseo	anseo	anseo-R	Rl
i rith	i rith	i_rith-S	Spc
an	an	an-T	Td-s
tráthnóna	tráthnóna	tráthnóna-N	Ncmsg
le	le	le-S	Sp
hamharc	hamharc	amharc-N	Nv
i ndiaidh	i ndiaidh	i_ndiaidh-S	Spc
rudaí	rudaí	rud-N	Ncmpg
.	.	.-F	Fe
'	'	'-F	Fa
Agus	Agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmis
sé	sé	sé-P	Pp3msn
suas	suas	suas-R	Rd
chun	chun	chun-S	Sp
na	na	na-T	Tdfsg
cisteanadh	cisteanadh	cisteanadh-N	Ncmsc
.	.	.-F	Fe
Shuigh	Shuigh	suigh-V	Vmis
Tarlach	Tarlach	Tarlach-N	Npmsc
ansin	ansin	ansin-R	Rt|Rl
ag	ag	ag-S	Sp
ól	ól	ól-N	Nv
.	.	.-F	Fe
Smaoinigh	Smaoinigh	smaoinigh-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
am	am	am-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
a	a	a-D	Dp3
dheartháir	dheartháir	deartháir-N	Ncmsc
óg	óg	óg-A	Aq-msc
agus	agus	agus-C	Cc
ar	ar	ar-S	Sp
na	na	na-T	Td-p
rudaí	rudaí	rud-N	Ncmpc
a	a	a-Q	Q-r
rinne	rinne	déan-V	Vmis
siad	siad	siad-P	Pp3-pn
.	.	.-F	Fe
'	'	'-F	Fa
Ba	Ba	is-W	Ws|Ws-i
dheas	dheas	deas-A	Aqp
t	t	t-X	Xl
‑	‑	‑-F	Fb
am	am	am-N	Ncmsc
é	é	é-P	Pp3ms
,	,	,-F	Fi
’	’	’-F	Fa
dar	dar	dar-V	Vmip
le	le	le-S	Sp
Tarlach	Tarlach	Tarlach-N	Npmsc
,	,	,-F	Fi
'	'	'-F	Fa
ach	ach	ach-C	Cs
tagann	tagann	tar-V	Vmip
an	an	an-T	Td-s
aois	aois	aois-N	Ncfsc
,	,	,-F	Fi
faraor	faraor	faraor-X	Xsc
,	,	,-F	Fi
agus	agus	agus-C	Cc
an	an	an-T	Td-s
bás	bás	bás-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Ansin	Ansin	ansin-R	Rt|Rl
thosaigh	thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
amach	amach	amach-R	Rd
gnoithe	gnoithe	gnoithe-A	Av
na	na	na-T	Tdfsg
faire	faire	faire-N	Ncfsg
agus	agus	agus-C	Cc
an	an	an-T	Td-s
tórraimh	tórraimh	tórramh-N	Ncmsg
.	.	.-F	Fe
An	An	an-T	Td-s
chéad	chéad	céad-M	Mo
rud	rud	rud-N	Ncmsc
eile	eile	eile-D	Dd
chuala	chuala	clois-V	Vmis
sé	sé	sé-P	Pp3msn
Pádraig	Pádraig	Pádraig-N	Npmsc
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
anuas	anuas	anuas-R	Rd
as	as	as-S	Sp
an	an	an-T	Td-s
chistineach	chistineach	each-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Siúil	Siúil	siúl-N	Ncmsg
leat	leat	le-P	Pr2-s
anois	anois	anois-R	Rt
,	,	,-F	Fi
a	a	a-Q	Q-r
Tharlaigh	Tharlaigh	tarlaigh-V	Vmis
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
seisean	seisean	sé-P	Pp3msne
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
amach	amach	amach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
cúil	cúil	cúl-N	Ncfsc|Ncmsg|Ncmpc
.	.	.-F	Fe
Síos	Síos	síos-R	Rd
leo	leo	le-P	Pr3-p
go dtí	go dtí	go_dtí-S	Spc
stór	stór	stór-N	Ncmsc
mór	mór	mór-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
bun	bun	bun-N	Ncmsc
an	an	an-T	Td-s
chlóis	chlóis	clós-N	Ncmsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
carr	carr	carr-N	Ncmsc|Ncfsc
Phádraig	Phádraig	Pádraig-N	Npm-g|Npfsg
ansin	ansin	ansin-R	Rt|Rl
cheana	cheana	cheana-R	Rg
féin	féin	féin-P	Px
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmm-2s
Pádraig	Pádraig	Pádraig-N	Npmsc
an	an	an-T	Td-s
búit	búit	búit-N	Ncfsc
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
amach	amach	amach-R	Rd
cúpla	cúpla	cúpla-D	Dq|Ncmsc
seanmhála	seanmhála	mála-N	Ncmsc
saic	saic	sac-N	Ncmsg|Ncmpc
agus	agus	agus-C	Cc
píosa	píosa	píosa-N	Ncmsg|Ncmsc
rópa	rópa	rópa-N	Ncmsg
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
mála	mála	mála-N	Ncmsc
amháin	amháin	amháin-A	Aqp
ar	ar	ar-S	Sp
urlár	urlár	urlár-N	Ncmsc
an	an	an-T	Td-s
bhúit	bhúit	bhúit-N	Ncfsc
sa	sa	i-S	Spa-s
dóigh	dóigh	dóigh-N	Ncfsc
is	is	agus-C	Cc
nach	nach	nach-Q	Qnr
ndéanfadh	ndéanfadh	déan-V	Vmc
sé	sé	sé-P	Pp3msn
dochar	dochar	dochar-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
don	don	do-S	Spa-s
chónra	chónra	cónra-N	Ncfsc
.	.	.-F	Fe
Anonn	Anonn	anonn-R	Rd
leo	leo	le-P	Pr3-p
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
stór	stór	stór-N	Ncmsc
.	.	.-F	Fe
Bhrúigh	Bhrúigh	brúigh-V	Vmis
Pádraig	Pádraig	Pádraig-N	Npmsc
siar	siar	siar-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
mór	mór	mór-A	Aq-msc
agus	agus	agus-C	Cc
isteach	isteach	isteach-R	Rd
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
cineál	cineál	cineál-R	Ri
dorcha	dorcha	dorcha-A	Aqp
istigh	istigh	istigh-R	Rl
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
solas	solas	solas-N	Ncmsc
leictreach	leictreach	leictreach-A	Aq-msc
ná	ná	ná-C	Cs|Cc
solas	solas	solas-N	Ncmsc
de	de	de-S	Sp
chineál	chineál	cineál-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
eile	eile	eile-D	Dd
sa	sa	i-S	Spa-s
stór	stór	stór-N	Ncmsc
ach	ach	ach-C	Cs
i gceann	i gceann	i_gceann-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
d	d	d-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmis
a	a	a-D	Dp3
súile	súile	súil-N	Ncfpc
cleachtaithe	cleachtaithe	aithe-N	Ncfsc|Ncfsg
leis	leis	le-S	Sp
an	an	an-T	Td-s
dorchadas	dorchadas	dorchadas-N	Ncmsc
.	.	.-F	Fe
Anonn	Anonn	anonn-R	Rd
leo	leo	le-P	Pr3-p
go dtí	go dtí	go_dtí-S	Spc
coirnéal	coirnéal	coirnéal-N	Ncmsc
,	,	,-F	Fi
áit	áit	áit-N	Ncfsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
trí	trí	trí-M	Mc|Sp
chónra	chónra	cónra-N	Ncfsc
–	–	–-X	Xx
ceann	ceann	ceann-N	Ncmsc
i	i	i-S	Sp
mullach	mullach	mullach-N	Ncmsc
an	an	an-T	Td-s
chinn	chinn	ceann-N	Ncmsg
eile	eile	eile-D	Dd
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
bheag	bheag	beag-A	Aqp
difear	difear	difear-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
eatarthu	eatarthu	idir-P	Pr3-p
ach	ach	ach-C	Cs
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
féin	féin	féin-P	Px
,	,	,-F	Fi
thug	thug	tabhair-V	Vmis
Pádraig	Pádraig	Pádraig-N	Npmsc
a	a	a-D	Dp3
rogha	rogha	rogha-N	Ncfsc
do	do	do-S	Sp
Tharlach	Tharlach	tarlach-N	Npmsc
.	.	.-F	Fe
'	'	'-F	Fa
Á	Á	Á-I	I
,	,	,-F	Fi
nach	nach	is-C	Cs|Wpdin|Wpsin
cuma	cuma	cuma-N	Ncfsc|Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Tarlach	Tarlach	Tarlach-N	Npmsc
agus	agus	agus-C	Cc
bheir	bheir	bí-V	Vmif2s
sé	sé	sé-P	Pp3msn
greim	greim	greim-N	Ncmsc
ar	ar	ar-S	Sp
chosa	chosa	cos-N	Ncfpc
an	an	an-T	Td-s
chinn	chinn	ceann-N	Ncmsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ar	ar	ar-S	Sp
uachtar	uachtar	uachtar-N	Ncmsc
.	.	.-F	Fe
Fuair	Fuair	faigh-V	Vmis
Pádraig	Pádraig	Pádraig-N	Npmsc
greim	greim	greim-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
cheann	cheann	ceann-N	Ncmsv
agus	agus	agus-C	Cc
amach	amach	amach-R	Rd
leo	leo	le-P	Pr3-p
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
carr	carr	carr-N	Ncmsc|Ncfsc
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
siad	siad	siad-P	Pp3-pn
an	an	an-T	Td-s
ceann	ceann	ceann-N	Ncmsc
isteach	isteach	isteach-R	Rd
ar	ar	ar-S	Sp
dtús	dtús	tús-N	Ncmsc
mar	mar	mar-C	Cs
gurbh	gurbh	is-W	Wsdi
é	é	é-P	Pp3ms
ba	ba	is-U	U
throime	throime	trom-A	Aqc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
chuir	chuir	cuir-V	Vmis
Pádraig	Pádraig	Pádraig-N	Npmsc
mála	mála	mála-N	Ncmsc|Ncmsg
saic	saic	sac-N	Ncmsg|Ncmpc
ar	ar	ar-S	Sp
bharr	bharr	barr-N	Ncmsc
na	na	na-T	Tdfsg
cónra	cónra	cónra-N	Ncfsg
agus	agus	agus-C	Cc
tharraing	tharraing	tarraing-V	Vmis
anuas	anuas	anuas-R	Rd
doras	doras	doras-N	Ncmsc
an	an	an-T	Td-s
bhúit	bhúit	bhúit-N	Ncfsc
.	.	.-F	Fe
Leis	Leis	le-S	Sp
an	an	an-T	Td-s
rópa	rópa	rópa-N	Ncmsc
cheangail	cheangail	ceangail-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
chónra	chónra	cónra-N	Ncfsc
den	den	de-S	Spa-s
charr	charr	carr-N	Ncmsc|Ncfsc
agus	agus	agus-C	Cc
ansin	ansin	ansin-R	Rt|Rl
cheangail	cheangail	ceangail-V	Vmis
sé	sé	sé-P	Pp3msn
doras	doras	doras-N	Ncmsc
an	an	an-T	Td-s
bhúit	bhúit	bhúit-N	Ncfsc
anuas	anuas	anuas-R	Rd
teannta	teannta	teann-A	Av
ar	ar	ar-S	Sp
an	an	an-T	Td-s
chónra	chónra	cónra-N	Ncfsc
.	.	.-F	Fe
Sin	Sin	sin-W	W
mar	mar	mar-C	Cs|Sp
a	a	a-D	Dp3
nítí	nítí	nít-N	Ncmpc
san	san	i-S	Spa-s
am	am	am-N	Ncmsc
agus	agus	agus-C	Cc
muna	muna	muna-C	Cs
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
búit	búit	búit-N	Ncfsc
fada	fada	fada-A	Aqp
go leor	go leor	go_leor-A	Aq
an	an	an-T	Td-s
chónra	chónra	cónra-N	Ncfsc
ar	ar	ar-S	Sp
bharr	bharr	barr-N	Ncmsc
an	an	an-T	Td-s
chairr	chairr	carr-N	Ncmsg
.	.	.-F	Fe
Amach	Amach	amach-R	Rd
sna	sna	i-S	Spa-p
seascaidí	seascaidí	seasca-N	Ncmpc
tháinig	tháinig	tar-V	Vmis
an	an	an-T	Td-s
chéad	chéad	céad-M	Mo
eileatram	eileatram	eileatram-N	Ncmsc
chun	chun	chun-S	Sp
na	na	na-T	Tdfsg
háite	háite	áit-N	Ncfsg
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
sula	sula	sula-C	Cs
raibh	raibh	bí-V	Vmis---d
carranna	carranna	carr-N	Ncmpc
coitianta	coitianta	coitianta-A	Aqp
is	is	agus-W	Wp-i|Wpri|Cc
le	le	le-S	Sp
capall	capall	capall-N	Ncmsc
agus	agus	agus-C	Cc
carr	carr	carr-N	Ncmsc|Ncfsc
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
an	an	an-T	Td-s
chónra	chónra	cónra-N	Ncfsc
.	.	.-F	Fe
Anois	Anois	anois-R	Rt
bhí	bhí	bí-V	Vmis
achan	achan	gach-D	Dq
rud	rud	rud-N	Ncmsc
réidh	réidh	réidh-A	Aq-msc
.	.	.-F	Fe
Dhruid	Dhruid	druid-V	Vmis
Pádraig	Pádraig	Pádraig-N	Npmsc
doras	doras	doras-N	Ncmsc
an	an	an-T	Td-s
stóir	stóir	stór-N	Ncmsg
,	,	,-F	Fi
thug	thug	tabhair-V	Vmis
léim	léim	léim-N	Ncfsc
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
charr	charr	carr-N	Ncmsc|Ncfsc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmis
siad	siad	siad-P	Pp3-pn
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
acu	acu	ag-P	Pr3-p
le	le	le-S	Sp
gabháil	gabháil	gabh-N	Nv
fríd	fríd	trí-S	Sp
an	an	an-T	Td-s
Dúchoraidh	Dúchoraidh	Dúchoraidh-N	Npmsc
agus	agus	agus-C	Cc
Baile	Baile	Baile-N	Npmsc
na	na	na-T	Tdfsg
Finne	Finne	finne-N	Ncfsg
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
tarra	tarra	tarra-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhealach	bhealach	bealach-N	Ncmsc
sin	sin	sin-D	Dd
san	san	sin-P	Pd
am	am	am-N	Ncmsc
ach	ach	ach-S	Sp
gairbhéal	gairbhéal	gairbhéal-N	Ncmsc
garbh	garbh	garbh-A	Aq-msc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
poill	poill	poll-N	Ncmpc
uisce	uisce	uisce-N	Ncmsg|Ncmsc|Ncmsg
in	in	i-S	Sp
achan	achan	gach-D	Dq
ísleacht	ísleacht	ísleacht-N	Ncfsc
agus	agus	agus-C	Cc
clocha	clocha	cloch-N	Ncfpc
garbha	garbha	garbh-A	Aq--pc
ar	ar	ar-S	Sp
achan	achan	gach-D	Dq
ardán	ardán	ardán-N	Ncmsc
.	.	.-F	Fe
Ar	Ar	is-W	Wssi|Wpsi
a	a	a-D	Dp3
suaimhneas	suaimhneas	suaimhneas-N	Ncmsc
rinne	rinne	déan-V	Vmis
siad	siad	siad-P	Pp3-pn
a	a	a-D	Dp3
mbealach	mbealach	bealach-N	Ncmsc
síos	síos	síos-R	Rd
lúbacha	lúbacha	lúbach-N	Ncfpc
an	an	an-T	Td-s
Dúchoraidh	Dúchoraidh	Dúchoraidh-N	Npmsc
,	,	,-F	Fi
fríd	fríd	trí-S	Sp
an	an	an-T	Td-s
tsráidbhaile	tsráidbhaile	sráidbhaile-N	Ncmsg
agus	agus	agus-C	Cc
trasna	trasna	trasna-S	Sp
an	an	an-T	Td-s
droichid	droichid	droichead-N	Ncmsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
anois	anois	anois-R	Rt
mala	mala	mala-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
fhada	fhada	fada-A	Aqp
le	le	le-S	Sp
tógáil	tógáil	tóg-N	Nv
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
chuid	chuid	cuid-N	Ncfsc
seo	seo	seo-D	Dd
den	den	de-S	Spa-s
bhealach	bhealach	bealach-N	Ncmsc
cnapánach	cnapánach	cnapánach-A	Aq-msc
go	go	go-U	Ua
maith	maith	maith-A	Aqp
.	.	.-F	Fe
Ó	Ó	ó-C	Cs
d	d	d-X	Xl
’	’	’-F	Fa
fhág	fhág	fág-V	Vmis
siad	siad	siad-P	Pp3-pn
an	an	an-T	Td-s
Clochán	Clochán	clochán-N	Ncmsc
Liath	Liath	Liath-N	Npmsc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
ag	ag	ag-S	Sp
ceachtar	ceachtar	ceachtar-P	Pi
acu	acu	ag-P	Pr3-p
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
rópa	rópa	rópa-N	Ncmsc
á	á	do-S	Spo-s
ghearradh	ghearradh	gearr-N	Nv
,	,	,-F	Fi
áit	áit	áit-N	Ncfsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
cuimilt	cuimilt	cuimil-N	Nv
in éadan	in éadan	in_éadan-S	Spc
géar	géar	géar-A	Aqp
.	.	.-F	Fe
Leis	Leis	le-S	Sp
an	an	an-T	Td-s
síorchroitheadh	síorchroitheadh	croith-N	Nv
anois	anois	anois-R	Rt
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
gearradh	gearradh	gearr-N	Nv
níos	níos	níos-U	Uc
gaiste	gaiste	gais-N	Ncmsc|Av
agus	agus	agus-C	Cc
le	le	le-S	Sp
meáchan	meáchan	meáchan-N	Ncmsc
na	na	na-T	Tdfsg
cónra	cónra	cónra-N	Ncfsg
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mhala	mhala	mala-N	Ncfsc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
gur	gur	is-W	Wsdi|Wpdi
bhris	bhris	bris-N	Ncfsc
an	an	an-T	Td-s
rópa	rópa	rópa-N	Ncmsg
.	.	.-F	Fe
Ag	Ag	ag-S	Sp
an	an	an-T	Td-s
am	am	am-N	Ncmsc
sin	sin	sin-D	Dd
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
carr	carr	carr-N	Ncmsc|Ncfsc
ag	ag	ag-S	Sp
gabháil	gabháil	gabh-N	Nv
thart	thart	thart-R	Rd
coradh	coradh	coradh-V	Vmis0|Nv|Ncmsc
géar	géar	géar-N	Ncmpg|Ncmsc|Aqp|Aq-msc
.	.	.-F	Fe
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
féin	féin	féin-P	Px
amach	amach	amach-R	Rd
leis	leis	le-S	Sp
an	an	an-T	Td-s
chónra	chónra	cónra-N	Ncfsc
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
urchar	urchar	urchar-N	Ncmsc
as	as	as-S	Sp
gunna	gunna	gunna-N	Ncmsc
agus	agus	agus-C	Cc
shleamhnaigh	shleamhnaigh	sleamhnaigh-V	Vmis
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
dtaobh	dtaobh	taobh-N	Ncmsc
bhealaigh	bhealaigh	bealaigh-V	Vmis
mhóir	mhóir	mór-A	Aq-msv|Aq-msg
gur	gur	is-W	Wsdi|Wpdi
stad	stad	stad-N	Nv|Ncmsc
tom	tom	tom-N	Ncmpg|Ncmsc
feagacha	feagacha	feag-N	Ncfpg|Ncfpc
í	í	í-P	Pp3fs
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
chuala	chuala	clois-V	Vmis
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sa	sa	i-S	Spa-s
charr	charr	carr-N	Ncmsc|Ncfsc
dada	dada	dada-N	Ncmsc|Ncmsg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmis
siad	siad	siad-P	Pp3-pn
leo	leo	le-P	Pr3-p
agus	agus	agus-C	Cc
píosa	píosa	píosa-N	Ncmsc
rópa	rópa	rópa-N	Ncmsg
ina	ina	i-S	Spp-s|Spp-p
streachlán	streachlán	streachlán-N	Ncmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
.	.	.-F	Fe
Thart	Thart	thart-R	Rd
fán	fán	faoi-S	Spa-s
am	am	am-N	Ncmsc
seo	seo	seo-D	Dd
bhí	bhí	bí-V	Vmis
solas	solas	solas-N	Ncmsc
an	an	an-T	Td-s
lae	lae	lá-N	Ncmsg
ag	ag	ag-S	Sp
meath	meath	meath-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
ceathanna	ceathanna	cith-N	Ncmpc
troma	troma	trom-A	Aq--pc
clocha	clocha	cloch-N	Ncfpc
sneachta	sneachta	sneachta-N	Ncmsg|Ncmsc
ann	ann	i-R	Rl|Pr3ms
ó	ó	ó-S	Sp
am	am	am-N	Ncmsc
go	go	go-S	Sp
ham	ham	am-N	Ncmsc
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
ghealach	ghealach	gealach-N	Ncfsc
ag	ag	ag-S	Sp
briseadh	briseadh	bris-N	Nv
amach	amach	amach-R	Rd
fríd	fríd	trí-S	Sp
na	na	na-T	Td-p
néalta	néalta	néal-N	Ncmpc
idir	idir	idir-S	Sp
na	na	na-T	Td-p
ceathanna	ceathanna	cith-N	Ncmpc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
'	'	'-F	Fa
Micheál	Micheál	Micheál-N	Ncmsc
na	na	na-T	Td-p
bPingneach	bPingneach	Pingneach-N	Npmsc
’	’	’-F	Fa
i ndiaidh	i ndiaidh	i_ndiaidh-S	Spc
an	an	an-T	Td-s
Dúchoraidh	Dúchoraidh	Dúchoraidh-N	Npmsc
a	a	a-U	U
fhágáil	fhágáil	fág-N	Nv
,	,	,-F	Fi
áit	áit	áit-N	Ncfsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
cruinniú	cruinniú	cruinnigh-N	Nv
déirce	déirce	déirc-N	Ncfsg
ó	ó	ó-S	Sp
mhaidin	mhaidin	maidin-N	Ncfsc
.	.	.-F	Fe
Pingineacha	Pingineacha	pingin-N	Ncfpc
ab	ab	is-W	Wsri
fhearr	fhearr	maith-A	Aqc
leis	leis	le-P	Pr3ms
agus	agus	agus-C	Cc
sin	sin	sin-P	Pd|W
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
fuair	fuair	faigh-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
leasainm	leasainm	leasainm-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
braon	braon	braon-N	Ncmsc
maith	maith	maith-A	Aq-msc
ólta	ólta	ól-A	Av
aige	aige	ag-P	Pr3ms
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bhíodh	bhíodh	bí-V	Vmih
de	de	de-S	Sp
ghnáth	ghnáth	gnáth-N	Ncmsc
.	.	.-F	Fe
Sin	Sin	sin-W	W
an	an	an-T	Td-s
tuige	tuige	tuige-N	Ncmsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
de	de	de-S	Sp
na	na	na-T	Td-p
pingineacha	pingineacha	pingin-N	Ncfpc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
anois	anois	anois-R	Rt
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
a	a	a-D	Dp3
bhealach	bhealach	bealach-N	Ncmsc
go	go	go-S	Sp
Baile	Baile	Baile-N	Npmsc
na	na	na-T	Tdfsg
Finne	Finne	finne-N	Ncfsg
agus	agus	agus-C	Cc
súil	súil	súil-N	Ncfsc|Nv-----n
aige	aige	ag-P	Pr3ms
a	a	a-U	U
bheith	bheith	bí-N	Nv
ansin	ansin	ansin-R	Rt
roimh	roimh	roimh-S	Sp
am	am	am-N	Ncmsc
luí	luí	luí-N	Ncmsg
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
dá	dá	dá-C	Cs
mbeadh	mbeadh	bí-V	Vmc
sé	sé	sé-P	Pp3msn
mall	mall	mall-A	Aqp
féin	féin	féin-P	Px
nár	nár	is-W	Wsrin
chuma	chuma	cuma-A	Aqp
.	.	.-F	Fe
B	B	B-X	Xl
’	’	’-F	Fa
in	in	i-S	Sp
rud	rud	rud-N	Ncmsc
maith	maith	maith-A	Aq-msc
amháin	amháin	amháin-A	Aqp
fána	fána	faoi-S	Spp-s
shaol	shaol	saol-N	Ncmsc
–	–	–-X	Xx
thiocfadh	thiocfadh	tar-V	Vmc
leis	leis	le-P	Pr3ms
a	a	a-D	Dp3
am	am	am-N	Ncmsc
féin	féin	féin-P	Px
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhainfeadh	bhainfeadh	bain-V	Vmc
sé	sé	sé-P	Pp3msn
Baile	Baile	Baile-N	Npmsc
na	na	na-T	Tdfsg
Finne	Finne	finne-N	Ncfsg
amach	amach	amach-R	Rd
gheobhadh	gheobhadh	faigh-V	Vmc
sé	sé	sé-P	Pp3msn
foscadh	foscadh	foscadh-N	Ncmsc
go	go	go-S	Sp
maidin	maidin	maidin-N	Ncfsc
i	i	i-S	Sp
mbóitheach	mbóitheach	bóitheach-N	Ncmsc
,	,	,-F	Fi
i	i	i-S	Sp
scioból	scioból	scioból-N	Ncmsc
,	,	,-F	Fi
nó	nó	nó-C	Cc
dá	dá	dá-C	Cs
mbeadh	mbeadh	bí-V	Vmc
rudaí	rudaí	rud-N	Ncmpc
go	go	go-U	Ua
dona	dona	dona-A	Aqp
,	,	,-F	Fi
i	i	i-S	Sp
gcruach	gcruach	cruach-N	Ncfsc
fhéir	fhéir	féar-N	Ncmsg
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
an	an	an-T	Td-s
dea	dea	dea-N	Ns-s
‑	‑	‑-F	Fb
chuma	chuma	cuma-N	Ncfsc
ar	ar	ar-S	Sp
Mhicheál	Mhicheál	Micheál-N	Ncmsc
bocht	bocht	bocht-A	Aq-msc
lá	lá	lá-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
den	den	de-S	Spa-s
bhliain	bhliain	bliain-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
féasóg	féasóg	féasóg-N	Ncfsc
ghiobach	ghiobach	giobach-A	Aq-fsc
air	air	ar-P	Pr3ms
agus	agus	agus-C	Cc
a	a	a-D	Dp3
chuid	chuid	cuid-N	Ncfsc
gruaige	gruaige	gruaig-N	Ncfsg
ina	ina	i-S	Spp-s
clibíní	clibíní	clibín-N	Ncmpc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ach	ach	ach-S	Sp
fiacail	fiacail	fiacail-N	Ncfsc
amháin	amháin	amháin-A	Aqp
fágtha	fágtha	fág-A	Av
ina	ina	i-S	Spp-s
bhéal	bhéal	béal-N	Ncmsc
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
scéin	scéin	scéin-N	Ncfsc
ina	ina	i-S	Spp-s
shúile	shúile	súil-N	Ncfpc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
chuid	chuid	cuid-N	Ncfsc
éadaigh	éadaigh	éadaigh-V	Vmis
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
leis	leis	le-S	Sp
an	an	an-T	Td-s
chuid	chuid	cuid-N	Ncfsc
eile	eile	eile-D	Dd
de	de	de-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Micheál	Micheál	Micheál-N	Ncmsc
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
choradh	choradh	cor-N	Nv
nuair	nuair	nuair-C	Cs
an	an	is-W	Wpdq|Wp-q
chéad	chéad	céad-M	Mc
rud	rud	rud-N	Ncmsc
eile	eile	eile-D	Dd
,	,	,-F	Fi
le	le	le-S	Sp
solas	solas	solas-N	Ncmsc
na	na	na-T	Tdfsg
gealaí	gealaí	gealach-N	Ncfsg
,	,	,-F	Fi
tchí	tchí	tchí-V	Vmip
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
chónra	chónra	cónra-N	Ncfsc
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
dócha	dócha	dócha-A	Aqp|Aqc
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
duine	duine	duine-N	Ncmsc
beo	beo	beo-A	Aqp
a	a	a-Q	Q-r
shiúlfadh	shiúlfadh	siúil-V	Vmc
thart	thart	thart-R	Rd
le	le	le-S	Sp
cónra	cónra	cónra-N	Ncfsc
caite	caite	caith-A	Av
ar	ar	ar-S	Sp
thaobh	thaobh	taobh-N	Ncmsc
bhealaigh	bhealaigh	bealaigh-V	Vmis
mhóir	mhóir	mór-A	Aq-msv|Aq-msg
gan	gan	gan-S	Sp
sonrú	sonrú	sonraigh-N	Nv
a	a	a-U	U
chur	chur	cuir-N	Nv
inti	inti	i-P	Pr3fs
.	.	.-F	Fe
Anonn	Anonn	anonn-R	Rd
le	le	le-S	Sp
Micheál	Micheál	Micheál-N	Ncmsc
go	go	go-U	Ua
faichilleach	faichilleach	faichilleach-A	Aqp
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
fear	fear	fear-N	Ncmsc
é	é	é-P	Pp3ms
riamh	riamh	riamh-R	Rg
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
eagla	eagla	eagla-N	Ncfsc
air	air	ar-P	Pr3ms
ach	ach	ach-C	Cs
san	san	i-S	Spa-s
am	am	am-N	Ncmsc
chéanna	chéanna	céanna-A	Aqp
tugtar	tugtar	tabhair-V	Vmip0
meas	meas	meas-N	Ncmsc
do	do	do-S	Sp
na	na	na-T	Td-p
mairbh	mairbh	marbh-N	Ncmpc
agus	agus	agus-C	Cc
de	de	de-S	Sp
ghnáth	ghnáth	gnáth-N	Ncmsc
is	is	agus-W	Wp-i|Wpri|Cc
marbhán	marbhán	marbhán-N	Ncmpg|Ncmsc|Ncmpg
a	a	a-Q	Q-r
bhíonn	bhíonn	bí-V	Vmig
i	i	i-S	Sp
gcónra	gcónra	cónra-N	Ncfsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
cad	cad	cad-W	W--q
chuige	chuige	chuig-P	Pr3ms
a	a	a-Q	Q-i
mbeadh	mbeadh	bí-V	Vmc
cónra	cónra	cónra-N	Ncfsc
caite	caite	caith-A	Aqp|Av
go	go	go-U	Ua
hamscaí	hamscaí	amscaí-A	Aqp
ar	ar	ar-S	Sp
fhód	fhód	fód-N	Ncmsc
an	an	an-T	Td-s
bhealaigh	bhealaigh	bealach-N	Ncmsg
mhóir	mhóir	mór-N	Ncmsg
?	?	?-F	Fq
Bhuail	Bhuail	buail-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
chónra	chónra	cónra-N	Ncfsc
lena	lena	le-S	Spp-s
chos	chos	cos-N	Ncfsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
aithin	aithin	aithin-V	Vmis
sé	sé	sé-P	Pp3msn
láithreach	láithreach	láithreach-N	Ncmsc|Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
folamh	folamh	folamh-A	Aqp
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
cad	cad	cad-W	W--q
chuige	chuige	chuig-P	Pr3ms
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
ansin	ansin	ansin-R	Rt
?	?	?-F	Fq
Díreach	Díreach	díreach-N	Ncmsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
bhomaite	bhomaite	bomaite-N	Ncmsg
sin	sin	sin-D	Dd
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmm-2s
an	an	an-T	Td-s
ghealach	ghealach	gealach-N	Ncfsc
agus	agus	agus-C	Cc
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bhuailfeá	bhuailfeá	buail-V	Vmc-2s
do	do	do-S	Sp
dhá	dhá	dó-M	Mc
bhos	bhos	bos-N	Ncfsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
thosaigh	thosaigh	tosach-V	Vmis|Ncmsg
na	na	na-T	Td-p
clocha	clocha	cloch-N	Ncfpc
sneachta	sneachta	sneachta-N	Ncmsg|Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-V	Vmm-2s
Micheál	Micheál	Micheál-N	Ncmsc
thart	thart	thart-R	Rd
ach	ach	ach-C	Cs
sa	sa	i-S	Spa-s
dorchadas	dorchadas	dorchadas-N	Ncmsc
féin	féin	féin-P	Px
thuig	thuig	tuig-V	Vmis
sé	sé	sé-P	Pp3msn
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
foscadh	foscadh	foscadh-N	Ncmsc
fá	fá	faoi-P	Pr3ms
bhúirthe	bhúirthe	búir-A	Av
asail	asail	asal-N	Ncmsg|Ncmpc|Ncmsg
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
bhain	bhain	bain-V	Vmis---n
sé	sé	sé-P	Pp3msn
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
as	as	as-N	Ncmpg
Micheál	Micheál	Micheál-N	Ncmsc
na	na	na-T	Tdfsg
ceithre	ceithre	ceathair-M	Mc
scriú	scriú	scriú-N	Ncmsc
a	a	a-U	U
chasadh	chasadh	cas-N	Nv
amach	amach	amach-R	Rd
,	,	,-F	Fi
an	an	an-T	Td-s
clár	clár	clár-N	Ncmsc
a	a	a-U	U
bhaint	bhaint	bain-N	Nv
den	den	de-S	Spa-s
chónra	chónra	cónra-N	Ncfsc
,	,	,-F	Fi
léim	léim	léim-V	Vmip1s|Vmis
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
isteach	isteach	isteach-R	Rd
agus	agus	agus-C	Cc
an	an	an-T	Td-s
clár	clár	clár-N	Ncmsc
a	a	a-U	U
ligean	ligean	lig-N	Nv
anuas	anuas	anuas-R	Rd
ina	ina	i-S	Spp-s
mhullach	mhullach	mullach-N	Ncmsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
é	é	é-P	Pp3ms
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
go	go	go-U	Ua
seascair	seascair	seascair-A	Aqp
.	.	.-F	Fe
Ach	Ach	ach-S	Sp|Cs
leis	leis	le-S	Sp
an	an	an-T	Td-s
deoch	deoch	deoch-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
istigh	istigh	istigh-R	Rl
,	,	,-F	Fi
an	an	an-T	Td-s
siúl	siúl	siúl-N	Ncmsc
as	as	as-S	Sp
an	an	an-T	Td-s
Dúchoraidh	Dúchoraidh	Dúchoraidh-N	Npmsc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
clocha	clocha	cloch-N	Ncfpc
sneachta	sneachta	sneachta-N	Ncmsg|Ncmsc
ag	ag	ag-S	Sp
greadadh	greadadh	gread-N	Nv
chlár	chlár	clár-N	Ncmsc
na	na	na-T	Tdfsg
cónra	cónra	cónra-N	Ncfsg
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bheifeá	bheifeá	bí-V	Vmc-2s
istigh	istigh	istigh-R	Rl
i	i	i-S	Sp
ndruma	ndruma	druma-N	Ncmsc
,	,	,-F	Fi
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sé	sé	sé-P	Pp3msn
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
gur	gur	gur-Q	Q--s
thit	thit	tit-V	Vmis
Micheál	Micheál	Micheál-N	Ncmsc
na	na	na-T	Td-p
bPingneach	bPingneach	Pingneach-N	Npmsc
ina	ina	i-S	Spp-s
chnap	chnap	cnap-N	Ncmsc
codlata	codlata	codail-A	Av
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
fios	fios	fios-N	Ncmsc
cá	cá	cá-R	Rq
fhad	fhad	fad-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ansin	ansin	ansin-R	Rt|Rl
ach	ach	ach-S	Sp|Cs
ag	ag	ag-S	Sp
tarraingt	tarraingt	tarraing-N	Nv
ar	ar	ar-S	Sp
leath	leath	leath-N	Ncfsc
i ndiaidh	i ndiaidh	i_ndiaidh-S	Spc
a	a	a-U	Um
seacht	seacht	seacht-M	Mc
bhí	bhí	bí-N	Ncfsc
beirt	beirt	beirt-N	Ncfsc
bhan	bhan	bean-N	Ncfpg
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
a	a	a-D	Dp3
mbealach	mbealach	bealach-N	Ncmsc
síos	síos	síos-R	Rd
chun	chun	chun-S	Sp
an	an	an-T	Td-s
Dúchoraidh	Dúchoraidh	Dúchoraidh-N	Npmsc
chuig	chuig	chuig-S	Sp
an	an	an-T	Td-s
phaidrín	phaidrín	paidrín-N	Ncmsg
.	.	.-F	Fe
Mí	Mí	Mí-N	Npfsc
an	an	an-T	Td-s
phaidrín	phaidrín	paidrín-N	Ncmsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
de	de	de-S	Sp
ghnás	ghnás	gnás-N	Ncmsc|Ncfsc
an	an	an-T	Td-s
paidrín	paidrín	paidrín-N	Ncmsc
a	a	a-U	U
rá	rá	abair-N	Nv
achan	achan	gach-D	Dq
oíche	oíche	oíche-N	Ncfsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-U	Um
hocht	hocht	ocht-M	Mc
a	a	an-T	Td-s
chlog	chlog	clog-N	Ncmsc
i	i	i-S	Sp
dteach	dteach	teach-N	Ncmsc
an	an	an-T	Td-s
phobail	phobail	pobal-N	Ncmsg
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
ghnách	ghnách	gnách-A	Aqp
le	le	le-S	Sp
achan	achan	gach-D	Dq
duine	duine	duine-N	Ncmsc
freastal	freastal	freastail-N	Ncmpg|Ncmsc|Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
phaidrín	phaidrín	paidrín-N	Ncmsg
deich	deich	deich-N	Ncmsg|Ncmsc
n	n	n-X	Xl
‑	‑	‑-F	Fb
oíche	oíche	oíche-N	Ncfsc
i rith	i rith	i_rith-S	Spc
na	na	na-T	Tdfsg
míosa	míosa	mí-N	Ncfsg
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
níor	níor	is-W	Ws-in
éirigh	éirigh	éirigh-V	Vmm-2s
le	le	le-S	Sp
Nóra	Nóra	Nóra-N	Npfsc
agus	agus	agus-C	Cc
Máire	Máire	Máire-N	Npf-g|Npfsc
sin	sin	sin-P	Pd|W|Dd
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
mar	mar	mar-C	Cs
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
slaghdán	slaghdán	slaghdán-N	Ncmsc
ar	ar	ar-S	Sp
Nóra	Nóra	Nóra-N	Npfsc
an	an	an-T	Td-s
chéad	chéad	céad-M	Mo
choicís	choicís	coicís-N	Ncfsc
agus	agus	agus-C	Cc
anois	anois	anois-R	Rt
chaithfeadh	chaithfeadh	caith-V	Vmc
siad	siad	siad-P	Pp3-pn
achan	achan	gach-D	Dq
oíche	oíche	oíche-N	Ncfsc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
lena	lena	le-S	Spp-s
ndualgaisí	ndualgaisí	ndualgais-N	Ncfpc
a	a	a-U	U
chomhlíonadh	chomhlíonadh	comhlíon-N	Nv
.	.	.-F	Fe
Sin	Sin	sin-W	W
an	an	an-T	Td-s
fáth	fáth	fáth-N	Ncmsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
tarraingt	tarraingt	tarraing-N	Nv
ar	ar	ar-S	Sp
theach	theach	teach-N	Ncmsc
an	an	an-T	Td-s
phobail	phobail	pobal-N	Ncmsg
an	an	an-T	Td-s
oíche	oíche	oíche-N	Ncfsc
seo	seo	seo-D	Dd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
dorcha	dorcha	dorcha-A	Aqp
fán	fán	faoi-S	Spa-s
am	am	am-N	Ncmsc
seo	seo	seo-D	Dd
ach	ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
lampa	lampa	lampa-N	Ncmsc
le	le	le-S	Sp
Nóra	Nóra	Nóra-N	Npfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
taispeáint	taispeáint	taispeáin-N	Nv
bhealaigh	bhealaigh	bealaigh-V	Vmis
dóibh	dóibh	do-P	Pr3-p
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
in	in	i-S	Sp
uillinn	uillinn	uillinn-N	Ncfsc
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
ag	ag	ag-S	Sp
comhrá	comhrá	comhrá-N	Nv-----n
fá	fá	faoi-P	Pr3ms
rudaí	rudaí	rud-N	Ncmpc
beaga	beaga	beag-A	Aq--pc
ina	ina	i-S	Spp-p|Spp-s
saol	saol	saol-N	Ncmsc
.	.	.-F	Fe
Comharsana	Comharsana	comharsa-N	Ncfpc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
iontu	iontu	i-P	Pr3-p
a	a	a-Q	Q-r
chaith	chaith	caith-V	Vmis
saol	saol	saol-N	Ncmsc
suaimhneach	suaimhneach	suaimhneach-A	Aq-msc
cneasta	cneasta	cneasta-A	Aqp
ar	ar	ar-S	Sp
thaobh	thaobh	taobh-N	Ncmsc
an	an	an-T	Td-s
chnoic	chnoic	cnoc-N	Ncmsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
oiread	oiread	oiread-N	Ns-s
frocanna	frocanna	froc-N	Ncmpg|Ncmpc
agus	agus	agus-C	Cc
clupaidí	clupaidí	clupaid-N	Ncfsg|Ncfpc|Ncfpg
orthu	orthu	ar-P	Pr3-p
is	is	agus-C	Cc
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
le	le	le-S	Sp
feiceáil	feiceáil	feic-N	Nv
díobh	díobh	de-P	Pr3-p
ach	ach	ach-S	Sp|Cs
ó	ó	ó-S	Sp
smig	smig	smig-N	Ncfsc
go	go	go-S	Sp
héadan	héadan	éadan-N	Ncmsc
.	.	.-F	Fe
Cé	Cé	cé-C	Cs
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
oíche	oíche	oíche-N	Ncfsc
fuar	fuar	fuar-A	Aqp
choinnigh	choinnigh	coinnigh-V	Vmis
t	t	t-X	Xl
‑	‑	‑-F	Fb
éadach	éadach	éadach-N	Ncmsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
siúl	siúl	siúl-N	Ncmsc
te	te	te-A	Aq-msc
iad	iad	iad-P	Pp3-p
.	.	.-F	Fe
Ceann	Ceann	ceann-N	Ncmsc
de	de	de-S	Sp
na	na	na-T	Td-p
huaireanta	huaireanta	uair-N	Ncfpc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
turadh	turadh	turadh-N	Ncmsc
ann	ann	i-P	Pr3ms
agus	agus	agus-C	Cc
ga	ga	ga-N	Ns-s
solais	solais	solas-N	Ncmsg
ón	ón	ó-S	Spa-s
ghealach	ghealach	gealach-N	Ncfsc
tharla	tharla	tarlaigh-V	Vmis
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
thart	thart	thart-R	Rd
coradh	coradh	cor-V	Vmis0
ina	ina	i-S	Spr
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
chónra	chónra	cónra-N	Ncfsc
.	.	.-F	Fe
Nóra	Nóra	Nóra-N	Npfsc
an	an	an-T	Td-s
chéad	chéad	céad-M	Mo
duine	duine	duine-N	Ncmsc|Ncmsg
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
í	í	í-P	Pp3fs
.	.	.-F	Fe
Solas	Solas	solas-N	Ncmsc
na	na	na-T	Tdfsg
gealaí	gealaí	gealach-N	Ncfsg
ag	ag	ag-S	Sp
lonrú	lonrú	lonraigh-N	Nv
ar	ar	ar-S	Sp
na	na	na-T	Td-p
píosaí	píosaí	píosa-N	Ncmpc
práis	práis	prás-N	Ncmsg
a	a	a-Q	Q-r
thóg	thóg	tóg-V	Vmis
a	a	a-D	Dp3
súile	súile	súil-N	Ncfpc
.	.	.-F	Fe
Rinneadh	Rinneadh	déan-V	Vmis0
staic	staic	staic-N	Ncfsc
di	di	do-P	Pr3fs
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
sí	sí	sí-P	Pp3fsn
labhairt	labhairt	labhair-N	Ncfsc|Nv
ach	ach	ach-C	Cs
ní	ní	is-W	Wp-in
thiocfadh	thiocfadh	tar-V	Vmc
an	an	an-T	Td-s
focal	focal	focal-N	Ncmsc
amach	amach	amach-R	Rd
.	.	.-F	Fe
'	'	'-F	Fa
Cad	Cad	cad-W	W--q
é	é	é-P	Pp3ms
atá	atá	bí-V	Vmip---r
ort	ort	ar-P	Pr2-s
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Máire	Máire	Máire-N	Npfsc
a	a	a-Q	Q-r
thug	thug	tabhair-V	Vmis
fá	fá	faoi-P	Pr3ms
deara	deara	deara-N	Ns-s
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
rud	rud	rud-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
contráilte	contráilte	contráilte-A	Aqp
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
'	'	'-F	Fa
Cróchnaid	Cróchnaid	Cróchnaid-N	Npmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Nóra	Nóra	Nóra-N	Npfsc
faoi	faoi	faoi-S	Sp
dheireadh	dheireadh	deireadh-N	Ncmsc
agus	agus	agus-C	Cc
le	le	le-S	Sp
hobair	hobair	obair-N	Nv-----n
mhór	mhór	mór-V	Vmis
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmm-2s
léi	léi	le-P	Pr3fs
an	an	an-T	Td-s
méid	méid	méid-N	Ncmsc
sin	sin	sin-P	Pd
féin	féin	féin-P	Px
a	a	a-U	U
rá	rá	abair-N	Nv
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-N	Ncmsc|Nv
Máire	Máire	Máire-N	Npf-g|Npfsc
sa	sa	i-S	Spa-s
treo	treo	treo-N	Ncmsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
Nóra	Nóra	Nóra-N	Npfsc
ag	ag	ag-S	Sp
stánadh	stánadh	stán-N	Nv
.	.	.-F	Fe
'	'	'-F	Fa
A	A	a-U	Uv
Athair	Athair	athair-N	Ncmsv
Shíoraí	Shíoraí	síoraí-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
sise	sise	sí-P	Pp3fsne
,	,	,-F	Fi
'	'	'-F	Fa
cá	cá	cá-R	Rq
has	has	as-X	Xfev|Ncmsc
a	a	a-Q	Q-i
dtáinig	dtáinig	tar-V	Vmis
sin	sin	sin-P	Pd
?	?	?-F	Fq
'	'	'-F	Fa
'	'	'-F	Fa
Cróchnaid	Cróchnaid	Cróchnaid-N	Npmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Nóra	Nóra	Nóra-N	Npfsc
arís	arís	arís-R	Rg
.	.	.-F	Fe
'	'	'-F	Fa
Bhuel	Bhuel	bhuel-X	Xsc
,	,	,-F	Fi
ní	ní	nigh-W	Wp-in|Nv|Ns-s|Ncmsc|Nv
cróchnaid	cróchnaid	cróchnaid-N	Ncfsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
é	é	é-P	Pp3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Máire	Máire	Máire-N	Npfsc
,	,	,-F	Fi
'	'	'-F	Fa
ach	ach	ach-S	Sp
cónra	cónra	cónra-N	Ncfsc
,	,	,-F	Fi
cibé	cibé	cibé-P	Pi|Dq
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
atá	atá	bí-V	Vmip---r
sí	sí	sí-P	Pp3fsn
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
anseo	anseo	anseo-R	Rl
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Do	Do	do-S	Sp
bharúil	bharúil	barúil-N	Ncfsc
an	an	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
corp	corp	corp-N	Ncmsc
inti	inti	i-P	Pr3fs
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Nóra	Nóra	Nóra-N	Npfsc
agus	agus	agus-C	Cc
gan	gan	gan-S	Sp
í	í	í-P	Pp3fs
saor	saor	saor-N	Ncmsc|Aqp
ó	ó	ó-S	Sp
eagla	eagla	eagla-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
Níl	Níl	bí-V	Vmip---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Máire	Máire	Máire-N	Npfsc
,	,	,-F	Fi
'	'	'-F	Fa
ach	ach	ach-C	Cs
thig	thig	tar-V	Vmip
linn	linn	linn-N	Ncfsc
fáil	fáil	faigh-N	Nv
amach	amach	amach-R	Rd
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Cad	Cad	cad-W	W--q
é	é	é-P	Pp3ms
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
dhéanfaidh	dhéanfaidh	déan-V	Vmif
muid	muid	muid-P	Pp1-p
sin	sin	sin-P	Pd
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Nóra	Nóra	Nóra-N	Npfsc
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
,	,	,-F	Fi
siúil	siúil	siúil-V	Vmm-2s
leat	leat	le-P	Pr2-s
agus	agus	agus-C	Cc
bainfidh	bainfidh	bain-V	Vmif
muid	muid	muid-P	Pp1-p
di	di	de-P	Pr3fs
an	an	an-T	Td-s
clár	clár	clár-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Ó	Ó	Ó-I	I
,	,	,-F	Fi
a	a	a-U	Uv
Dhia	Dhia	dia-N	Ncmsv
,	,	,-F	Fi
níor	níor	is-W	Ws-in
mhaith	mhaith	maith-A	Aqp
liom	liom	le-P	Pr1-s
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
a	a	a-D	Dp3
cóir	cóir	cór-N	Ncfsc|Ns-s|Ncmpc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Nóra	Nóra	Nóra-N	Npfsc
.	.	.-F	Fe
'	'	'-F	Fa
An	An	an-Q	Qq
bhfeiceann	bhfeiceann	feic-V	Vmip
tú	tú	tú-P	Pp2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Máire	Máire	Máire-N	Npfsc
,	,	,-F	Fi
'	'	'-F	Fa
níl	níl	bí-V	Vmip---n
scriú	scriú	scriú-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
sa	sa	i-S	Spa-s
chlár	chlár	clár-N	Ncmsc
.	.	.-F	Fe
Buailfidh	Buailfidh	buail-V	Vmif
an	an	an-T	Td-s
bheirt	bheirt	beirt-N	Ncfsc
againn	againn	ag-P	Pr1-p
an	an	an-T	Td-s
clár	clár	clár-N	Ncmsc
le	le	le-S	Sp
barr	barr	barr-N	Ncmsc
ár	ár	ár-N	Ncmsc|Dp1-p
mbróige	mbróige	bróg-N	Ncfsg
ag	ag	ag-S	Sp
an	an	an-T	Td-s
am	am	am-N	Ncmsc
chéanna	chéanna	céanna-N	Ncfpg|Ncmsg
.	.	.-F	Fe
Tabhair	Tabhair	tabhair-V	Vmm-2s
dom	dom	do-P	Pr1-s
do	do	do-S	Sp
lámh	lámh	lámh-N	Ncfsc
.	.	.-F	Fe
Seas	Seas	seas-V	Vmm-2s
le	le	le-S	Sp
mo	mo	mo-D	Dp1-s
thaobh	thaobh	taobh-N	Ncmsc
.	.	.-F	Fe
Coinnigh	Coinnigh	Coinnigh-N	Npmsc
an	an	an-T	Td-s
solas	solas	solas-N	Ncmsc
ar	ar	ar-S	Sp
cheann	cheann	ceann-N	Ncmsc
na	na	na-T	Tdfsg
cónra	cónra	cónra-N	Ncfsg
.	.	.-F	Fe
Anois	Anois	anois-R	Rt
,	,	,-F	Fi
in	in	i-S	Sp
ainm	ainm	ainm-N	Ncmsc
Dé	Dé	dia-N	Ncmsg
.	.	.-F	Fe
A	A	a-U	Um
haon	haon	aon-M	Mc
,	,	,-F	Fi
a	a	a-U	Um
dó	dó	dó-M	Mc
,	,	,-F	Fi
a	a	a-U	Um
trí	trí	trí-M	Mc
.	.	.-F	Fe
'	'	'-F	Fa
Agus	Agus	agus-C	Cc
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
chaith	chaith	caith-V	Vmis
siad	siad	siad-P	Pp3-pn
siar	siar	siar-R	Rd
an	an	an-T	Td-s
clár	clár	clár-N	Ncmsc
.	.	.-F	Fe
Díreach	Díreach	díreach-N	Ncmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
clár	clár	clár-N	Ncmsc
ag	ag	ag-S	Sp
titim	titim	tit-N	Nv
d	d	d-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmm-2s
'	'	'-F	Fa
corp	corp	corp-N	Ncmsc
’	’	’-F	Fa
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sa	sa	i-S	Spa-s
chónra	chónra	cónra-N	Ncfsc
ina	ina	i-S	Spp-s
shuí	shuí	suí-N	Ncmsc
agus	agus	agus-C	Cc
lig	lig	lig-V	Vmis
sé	sé	sé-P	Pp3msn
búirthe	búirthe	búir-A	Av
.	.	.-F	Fe
I	I	i-S	Sp
solas	solas	solas-N	Ncmsc
an	an	an-T	Td-s
lampa	lampa	lampa-N	Ncmsg
b	b	b-X	Xl
’	’	’-F	Fa
uafásach	uafásach	uafásach-A	Aqp
an	an	an-T	Td-s
radharc	radharc	radharc-N	Ncmsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
Micheál	Micheál	Micheál-N	Ncmsc
na	na	na-T	Td-p
bPingneach	bPingneach	Pingneach-N	Npmsc
amach	amach	amach-R	Rd
le	le	le-S	Sp
rois	rois	rois-N	Ncfsc
mionnaí	mionnaí	mionn-N	Ncmpg
móra	móra	mór-A	Aq--pg
agus	agus	agus-C	Cc
achan	achan	gach-D	Dq
chineál	chineál	cineál-N	Ncmsc
mallachtaí	mallachtaí	mallachtach-N	Ncfpg|Ncfsg
ar	ar	ar-S	Sp
an	an	an-T	Td-s
té	té	té-N	Ncmsc
a	a	a-Q	Q-r
mhúscail	mhúscail	múscail-V	Vmis
é	é	é-P	Pp3ms
as	as	as-P	Pr3ms
a	a	a-D	Dp3
shuan	shuan	suan-N	Ncmsc
ach	ach	ach-C	Cs
níor	níor	is-W	Ws-in
chuala	chuala	cual-N	Ncmpv
na	na	na-T	Tdfsg
mná	mná	bean-N	Ncfsg
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
nó	nó	nó-C	Cc
bhí	bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
cheana	cheana	cheana-R	Rg
féin	féin	féin-P	Px
ar	ar	ar-S	Sp
cosa	cosa	cos-N	Ncfpc
in	in	i-S	Sp
airde	airde	airde-N	Ncfpc|Ncfsc
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
síos	síos	síos-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
Dúchoraidh	Dúchoraidh	Dúchoraidh-N	Npmsc
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
chreid	chreid	creid-V	Vmis---n
siad	siad	siad-P	Pp3-pn
riamh	riamh	riamh-R	Rg
gur	gur	is-W	Wsdi
a	a	a-D	Dp3
dhath	dhath	dath-N	Ncmsc
eile	eile	eile-D	Dd
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
diabhal	diabhal	diabhal-N	Ncmsc
.	.	.-F	Fe
