Luchóg	Luchóg	luchóg-N	Ncfsc
na	na	na-T	Tdfsg
Gaeilge	Gaeilge	Gaeilge-N	Npfsg
Bhíodh	Bhíodh	bí-V	Vmih
sé	sé	sé-P	Pp3msn
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
ag	ag	ag-S	Sp
coirnéal	coirnéal	coirnéal-N	Ncmsc
an	an	an-T	Td-s
choláiste	choláiste	coláiste-N	Ncmsg
ag	ag	ag-S	Sp
am	am	am-N	Ncmsc
sosa	sosa	sos-N	Ncmsg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fheiceadh	fheiceadh	feic-V	Vmih
Brídín	Brídín	Brídín-N	Npfsc
é	é	é-P	Pp3ms
ón	ón	ó-S	Spa-s
seomra	seomra	seomra-N	Ncmsc
thuas	thuas	thuas-R	Rd
staighre	staighre	staighre-N	Ncmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhíodh	bhíodh	bí-V	Vmih
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
cuidiú	cuidiú	cuidigh-N	Nv
lena	lena	le-S	Spp-p|Spp-s
mamaí	mamaí	mamaí-N	Ncfsc|Ncmpc|Ncfsc
an	an	an-T	Td-s
teach	teach	teach-N	Ncmsc
a	a	a-U	U
ghlanadh	ghlanadh	glan-N	Nv
.	.	.-F	Fe
Buachaill	Buachaill	buachaill-N	Ncmsc
beag	beag	beag-A	Aq-msc
faiteach	faiteach	faiteach-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
luchóg	luchóg	luchóg-N	Ncfsc
i	i	i-S	Sp
gcuimhne	gcuimhne	cuimhne-N	Ncfsc
di	di	do-P	Pr3fs
.	.	.-F	Fe
Cailíní	Cailíní	cailín-N	Ncmpc
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
a	a	a-Q	Q-r
bhíodh	bhíodh	bí-V	Vmih
ag	ag	ag-S	Sp
stopadh	stopadh	stop-N	Nv
tigh	tigh	teach-N	Ncmsd
Bhrídín	Bhrídín	Brídín-N	Npf-g
.	.	.-F	Fe
Bhíodh	Bhíodh	bí-V	Vmih
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
glanadh	glanadh	glan-V	Vmis0
le	le	le-S	Sp
déanamh	déanamh	déan-N	Nv
ina	ina	i-S	Spp-p
ndiaidh	ndiaidh	diaidh-N	Ns-s
.	.	.-F	Fe
Gach	Gach	gach-D	Dq
samhradh	samhradh	samhradh-N	Ncmsc
déarfadh	déarfadh	abair-V	Vmc
a	a	a-D	Dp3
máthair	máthair	máthair-N	Ncfsc
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
a	a	a-U	U
choinneáil	choinneáil	coinnigh-N	Nv
cailíní	cailíní	cailín-N	Ncmpg|Ncmpc
arís	arís	arís-R	Rg
mar	mar	mar-C	Cs
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
barraíocht	barraíocht	barraíocht-N	Ncfsc
oibre	oibre	obair-N	Ncfsg|Nv--g--n
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
Ach	Ach	ach-S	Sp
gach	gach	gach-D	Dq
earrach	earrach	earrach-N	Ncmsc
d	d	d-X	Xl
’	’	’-F	Fa
athraíodh	athraíodh	athraigh-V	Vmih
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
hintinn	hintinn	intinn-N	Ncfsc
arís	arís	arís-R	Rg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
eagla	eagla	eagla-N	Ncfsc
uirthi	uirthi	ar-P	Pr3fs
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
na	na	na-T	Td-p
buachaillí	buachaillí	buachaill-N	Ncmpc
‘	‘	‘-X	Xx
rógharbh	rógharbh	garbh-A	Aqp
’	’	’-F	Fa
.	.	.-F	Fe
Shíl	Shíl	síl-V	Vmis
Brídín	Brídín	Brídín-N	Npfsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
cuid	cuid	cuid-N	Ncfsc
de	de	de-S	Sp
na	na	na-T	Td-p
buachaillí	buachaillí	buachaill-N	Ncmpc
sa	sa	i-S	Spa-s
choláiste	choláiste	coláiste-N	Ncmsc
garbh	garbh	garbh-A	Aq-msc
,	,	,-F	Fi
ceart	ceart	ceart-A	Aqp
go leor	go leor	go_leor-A	Aq
,	,	,-F	Fi
ach	ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
rud	rud	rud-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
garbh	garbh	garbh-A	Aq-msc
faoin	faoin	faoi-S	Spa-s
luchóg	luchóg	luchóg-N	Ncfsc
.	.	.-F	Fe
Chonacthas	Chonacthas	feic-V	Vmis0
di	di	do-P	Pr3fs
gur	gur	is-W	Wsdi
ghasúr	ghasúr	gasúr-N	Ncmsc
beag	beag	beag-A	Aq-msc
séimh	séimh	séimh-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
hé	hé	é-P	Pp3ms
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
aithne	aithne	aithne-N	Ncfsc
aici	aici	ag-P	Pr3fs
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Le	Le	le-S	Sp
fírinne	fírinne	fírinne-N	Ncfsc
níor	níor	níor-Q	Qn-s
labhair	labhair	labhair-V	Vmis---n
sí	sí	sí-P	Pp3fsn
leis	leis	le-P	Pr3ms
riamh	riamh	riamh-R	Rg
,	,	,-F	Fi
fiú	fiú	fiú-N	Ns-s|Ncmsc|Rg
.	.	.-F	Fe
B	B	B-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
caint	caint	caint-N	Ncfsc|Nv-----n
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
chuimhnigh	chuimhnigh	cuimhnigh-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
phríomhoide	phríomhoide	príomhoide-N	Ncmsc
an	an	an-T	Td-s
choláiste	choláiste	coláiste-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Labhraígí	Labhraígí	labhair-V	Vmm-2p
Gaeilge	Gaeilge	Gaeilge-N	Npfsc
!	!	!-F	Fe
MAIDIN	MAIDIN	maidin-N	Ncfsc
,	,	,-F	Fi
NÓIN	NÓIN	nóin-N	Ncfsc
AGUS	AGUS	agus-C	Cc
OÍCHE	OÍCHE	oíche-N	Ncfsc|Ncfsg
!	!	!-F	Fe
’	’	’-F	Fa
a	a	a-Q	Q-r
screadadh	screadadh	scread-V	Vmih
sé	sé	sé-P	Pp3msn
ón	ón	ó-S	Spa-s
ardán	ardán	ardán-N	Ncmsc
gach	gach	gach-D	Dq
tráthnóna	tráthnóna	tráthnóna-N	Ncmsc
i ndiaidh	i ndiaidh	i_ndiaidh-S	Spc
an	an	an-T	Td-s
chéilí	chéilí	céilí-N	Ncmsg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
éiríodh	éiríodh	éirigh-V	Vmih
a	a	a-D	Dp3
aghaidh	aghaidh	aghaidh-N	Ncfsc
chomh	chomh	chomh-R	Ri
dearg	dearg	dearg-A	Aqp
le	le	le-S	Sp
traidhfil	traidhfil	traidhfil-N	Ncfsc
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
búireadh	búireadh	búir-N	Nv
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
na	na	na-T	Td-p
scoláirí	scoláirí	scoláire-N	Ncmpc
‘	‘	‘-X	Xx
an	an	an-T	Td-s
mharóg	mharóg	maróg-N	Ncfsc
’	’	’-F	Fa
air	air	air-V	Vmm-2s
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
dá	dá	dá-C	Cs
mbeadh	mbeadh	bí-V	Vmc
an	an	an-T	Td-s
luchóg	luchóg	luchóg-N	Ncfsc
balbh	balbh	balbh-A	Aqp
ní	ní	ní-Q	Qn
bheadh	bheadh	bí-V	Vmc----n
sé	sé	sé-P	Pp3msn
ábalta	ábalta	ábalta-A	Aqp
Gaeilge	Gaeilge	Gaeilge-N	Npfsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
a	a	a-U	U
labhairt	labhairt	labhair-N	Nv
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
shásódh	shásódh	sásaigh-V	Vmc----n
sé	sé	sé-P	Pp3msn
sin	sin	sin-P	Pd
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
.	.	.-F	Fe
Dhéanadh	Dhéanadh	déan-V	Vmih
na	na	na-T	Td-p
scoláirí	scoláirí	scoláire-N	Ncmpc
eile	eile	eile-D	Dd
neamhaird	neamhaird	neamhaird-N	Ncfsc
de	de	de-P	Pr3ms|Sp
ag	ag	ag-S	Sp
an	an	an-T	Td-s
chéilí	chéilí	céilí-N	Ncmsg
mar	mar	mar-S	Sp
luchóg	luchóg	luchóg-N	Ncfsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
Brídín	Brídín	Brídín-N	Npfsc
duine	duine	duine-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
acu	acu	ag-P	Pr3-p
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
leis	leis	le-P	Pr3ms
riamh	riamh	riamh-R	Rg
.	.	.-F	Fe
B	B	B-X	Xl
’	’	’-F	Fa
as	as	as-S	Sp
Baile	Baile	Baile-N	Npmsc
Átha Cliath	Átha Cliath	Átha_Cliath-N	Npmsg
an	an	an-T	Td-s
mhórchuid	mhórchuid	mórchuid-N	Ncfsc
de	de	de-S	Sp
na	na	na-T	Td-p
gasúraí	gasúraí	gasúra-N	Ncmpc
agus	agus	agus-C	Cc
bhíodh	bhíodh	bí-V	Vmih
siad	siad	siad-P	Pp3-pn
i	i	i-S	Sp
dtólamh	dtólamh	tólamh-N	Ns-s
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
a	a	a-U	U
bheith	bheith	bí-N	Nv
‘	‘	‘-X	Xx
fionnuar	fionnuar	fionnuar-A	Aqp
’	’	’-F	Fa
(	(	(-F	Fp
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
déarfadh	déarfadh	abair-V	Vmc
siad	siad	siad-P	Pp3-pn
féin	féin	féin-P	Px
)	)	)-F	Fp
os comhair	os comhair	os_comhair-S	Spc
na	na	na-T	Td-p
gcailíní	gcailíní	cailín-N	Ncmpg
.	.	.-F	Fe
Baineadh	Baineadh	bain-V	Vmis0
geit	geit	geit-N	Ncfsc
as	as	as-S	Sp
Brídín	Brídín	Brídín-N	Npfsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
sí	sí	sí-P	Pp3fsn
gáire	gáire	gáire-N	Ncmsc
mór	mór	mór-A	Aq-msc
taobh amuigh	taobh amuigh	taobh_amuigh-R	Rl
den	den	de-S	Spa-s
choláiste	choláiste	coláiste-N	Ncmsc
.	.	.-F	Fe
Lig	Lig	lig-V	Vmis
sí	sí	sí-P	Pp3fsn
don	don	do-S	Spa-s
bhraillín	bhraillín	braillín-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ina	ina	i-S	Spp-s|Spp-p
lámh	lámh	lámh-N	Ncfsc
titim	titim	titim-N	Nv|Ncfsc
agus	agus	agus-C	Cc
dhearc	dhearc	dearc-V	Vmis|Ncfpg
an	an	an-T	Td-s
fhuinneog	fhuinneog	fuinneog-N	Ncfsc
amach	amach	amach-R	Rd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
cúpla	cúpla	cúpla-D	Dq|Ncmsc
cailín	cailín	cailín-N	Ncmsg|Ncmsc
i ndiaidh	i ndiaidh	i_ndiaidh-S	Spc
beannú	beannú	beannú-N	Ncmsg
don	don	do-S	Spa-s
luchóg	luchóg	luchóg-N	Ncfsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
rith	rith	rith-V	Vmis
siad	siad	siad-P	Pp3-pn
ar	ar	ar-S	Sp
shiúl	shiúl	siúl-N	Ncmsc
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
ag	ag	ag-S	Sp
gáire	gáire	gáir-N	Nv
.	.	.-F	Fe
Na	Na	na-T	Td-p
cailíní	cailíní	cailín-N	Ncmpc
céanna	céanna	céanna-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
stopadh	stopadh	stop-N	Nv
tigh	tigh	teach-N	Ncmsd
Bhrídín	Bhrídín	Brídín-N	Npf-g
,	,	,-F	Fi
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
teach	teach	teach-N	Ncmsc
don	don	do-S	Spa-s
lón	lón	lón-N	Ncmsc
.	.	.-F	Fe
Rith	Rith	rith-V	Vmis
Brídín	Brídín	Brídín-N	Npfsc
síos	síos	síos-R	Rd
an	an	an-T	Td-s
staighre	staighre	staighre-N	Ncmsg
sular	sular	sula-C	Csws|Cs-s
bhain	bhain	bain-V	Vmis|Npmsc
na	na	na-T	Td-p
cailíní	cailíní	cailín-N	Ncmpc
an	an	an-T	Td-s
teach	teach	teach-N	Ncmsc
amach	amach	amach-R	Rd
.	.	.-F	Fe
Níor	Níor	is-W	Ws-in
mhaith	mhaith	maith-A	Aqp
léi	léi	le-P	Pr3fs
go	go	go-Q	Q
dtiocfadh	dtiocfadh	tar-V	Vmc
siad	siad	siad-P	Pp3-pn
uirthi	uirthi	ar-P	Pr3fs
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
go	go	go-U	Ua
fóill	fóill	fóill-A	Aqp
sa	sa	i-S	Spa-s
seomra	seomra	seomra-N	Ncmsc
seo	seo	seo-D	Dd
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
hé	hé	é-P	Pp3ms
go	go	go-Q	Q
mbíodh	mbíodh	bí-V	Vmih
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
aon	aon	aon-D	Dq
rud	rud	rud-N	Ncmsc
as	as	as-S	Sp
áit	áit	áit-N	Ncfsc
,	,	,-F	Fi
ach	ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
rabhadh	rabhadh	rabhadh-N	Ncmsc
a	a	a-D	Dp3
máthar	máthar	máthair-N	Ncfsg
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
ina	ina	i-S	Spp-s
ceann	ceann	ceann-N	Ncmsc
:	:	:-F	Fi
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
bain	bain	bain-V	Vmm-2s-n
do	do	do-S	Sp
stuif	stuif	stuif-N	Ncmsc
na	na	na-T	Td-p
gcailíní	gcailíní	cailín-N	Ncmpg
in	in	i-S	Sp
am	am	am-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Dia	Dia	dia-N	Ncmsc
gwitch	gwitch	gwitch-X	Xf
,	,	,-F	Fi
Bean	Bean	bean-N	Ncfsc
an	an	an-T	Td-s
Tí	Tí	teach-N	Ncmsg
!	!	!-F	Fe
’	’	’-F	Fa
a	a	a-Q	Q-r
scairt	scairt	scairt-V	Vmis
siad	siad	siad-P	Pp3-pn
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
siad	siad	siad-P	Pp3-pn
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
isteach	isteach	isteach-R	Rd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Maith	Maith	Maith-N	Npmsc
sibh	sibh	sibh-P	Pp2-p
,	,	,-F	Fi
a	a	a-U	Uv
chailíní	chailíní	cailín-N	Ncmpv
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhreagair	fhreagair	freagair-V	Vmis
máthair	máthair	máthair-N	Ncfsc
Bhrídín	Bhrídín	Brídín-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
ocras	ocras	ocras-N	Ncmsc
oraibh	oraibh	ar-P	Pr2-p
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
is	is	is-W	Wp-i
ea	ea	ea-P	Pp3-s
,	,	,-F	Fi
Bean	Bean	bean-N	Ncfsc
an	an	an-T	Td-s
Tí	Tí	teach-N	Ncmsg
,	,	,-F	Fi
’	’	’-F	Fa
an	an	an-T	Td-s
freagra	freagra	freagra-N	Ncmsg|Ncmsc
a	a	a-Q	Q-i|Q-r
fuair	fuair	faigh-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
Chonacthas	Chonacthas	feic-V	Vmis0
do	do	do-S	Sp
Bhrídín	Bhrídín	Brídín-N	Npfsc
gurbh	gurbh	is-W	Wsdi
in	in	sin-P	Pd
an	an	an-T	Td-s
freagra	freagra	freagra-N	Ncmsg|Ncmsc
a	a	a-Q	Q-r
thugadh	thugadh	tabhair-V	Vmih
na	na	na-T	Td-p
cailíní	cailíní	cailín-N	Ncmpc
ar	ar	ar-S	Sp
achan	achan	gach-D	Dq
cheist	cheist	ceist-N	Ncfsc
.	.	.-F	Fe
Smaoinigh	Smaoinigh	smaoinigh-V	Vmis
sí	sí	sí-P	Pp3fsn
fosta	fosta	fosta-A	Aqp|Rg
gur	gur	is-W	Wsdi
dóiche	dóiche	dóiche-N	Ncfsc
gurbh	gurbh	is-W	Wsdi
in	in	sin-P	Pd
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
de	de	de-S	Sp
Ghaeilge	Ghaeilge	Gaeilge-N	Npfsc
ag	ag	ag-S	Sp
cuid	cuid	cuid-N	Ncfsc
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Dá	Dá	dá-C	Cs
dtiocfaí	dtiocfaí	tar-V	Vmc-0
Gaeilge	Gaeilge	Gaeilge-N	Npfsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Samhradh	Samhradh	samhradh-N	Ncmsc
i ndiaidh	i ndiaidh	i_ndiaidh-S	Spc
samhraidh	samhraidh	samhradh-N	Ncmsg
thagadh	thagadh	tar-V	Vmih
siad	siad	siad-P	Pp3-pn
go	go	go-S	Sp
Baile	Baile	Baile-N	Npmsc
na	na	na-T	Tdfsg
hÁille	hÁille	áille-N	Ncfsg
,	,	,-F	Fi
ach	ach	ach-C	Cs
ní	ní	is-W	Wp-in
thógadh	thógadh	tóg-V	Vmih
siad	siad	siad-P	Pp3-pn
leo	leo	le-P	Pr3-p
Gaeilge	Gaeilge	Gaeilge-N	Npfsc
na	na	na-T	Tdfsg
Gaeltachta	Gaeltachta	gaeltacht-N	Ncfsg
riamh	riamh	riamh-R	Rg
.	.	.-F	Fe
Ar	Ar	is-W	Wssi|Wpsi
a	a	a-D	Dp3
laghad	laghad	laghad-N	Ncmsc
,	,	,-F	Fi
áfach	áfach	áfach-R	Rg
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
cuideachta	cuideachta	cuideachta-N	Ncfsc
sna	sna	i-S	Spa-p
cailíní	cailíní	cailín-N	Ncmpc
seo	seo	seo-D	Dd
,	,	,-F	Fi
agus	agus	agus-C	Cc
tréan	tréan	tréan-N	Ncmpg|Ncmsc|Aqp
cainte	cainte	caint-N	Ncfsg|Nv--g--n
acu	acu	ag-P	Pr3-p
,	,	,-F	Fi
má	má	má-C	Cs
bhí	bhí	bí-V	Vmis
a	a	a-D	Dp3
gcuid	gcuid	cuid-N	Ncfsc
Gaeilge	Gaeilge	Gaeilge-N	Npfsg
briotach	briotach	briotach-A	Aqp
achrannach	achrannach	achrannach-A	Aqp
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
tú	tú	tú-P	Pp2-s
le	le	le-S	Sp
Brian	Brian	Brian-N	Ncmsc|Npmsc
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
duine	duine	duine-N	Ncmsc
acu	acu	ag-P	Pr3-p
den	den	de-S	Spa-s
chailín	chailín	cailín-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
leis	leis	le-S	Sp
an	an	an-T	Td-s
luchóg	luchóg	luchóg-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Dúirt	Dúirt	abair-V	Vmis
mé	mé	mé-P	Pp1-s
,	,	,-F	Fi
“	“	“-F	Fa
Are	Are	are-X	Xfev
you	you	you-X	Xf
going	going	going-X	Xfev
to	to	to-X	Xfes
the	the	the-X	Xfe
céilí	céilí	céile-N	Ncmsc|Ncmpc
tonight	tonight	tonight-X	Xfer
?	?	?-F	Fq
”	”	”-F	Fa
’	’	’-F	Fa
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
cad	cad	cad-P	Pq
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Dúirt	Dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
,	,	,-F	Fi
“	“	“-F	Fa
Tá	Tá	bí-V	Vmip
brón	brón	brón-N	Ncmsc
orm	orm	ar-P	Pr1-s
ach	ach	ach-C	Cs
ní	ní	is-W	Wp-in
labhraím	labhraím	labhair-V	Vmip1s
Béarla	Béarla	béarla-N	Ncmsc
.	.	.-F	Fe
”	”	”-F	Fa
’	’	’-F	Fa
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
fágadh	fágadh	fág-V	Vmis0
t	t	t-X	Xl
‑	‑	‑-F	Fb
iomlán	iomlán	iomlán-N	Ncmsc
acu	acu	ag-P	Pr3-p
sna	sna	i-S	Spa-p
trithí	trithí	tritheamh-N	Ncmpc
gáire	gáire	gáir-N	Ncfsg|Nv|Ncmsg|Ncmsc|Nv--g
.	.	.-F	Fe
t	t	t-X	Xl
‑	‑	‑-F	Fb
iomlán	iomlán	iomlán-N	Ncmsc
acu	acu	ag-P	Pr3-p
seachas	seachas	seachas-S	Sp
Brídín	Brídín	Brídín-N	Npfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
dúil	dúil	dúil-N	Ncfsc
aici	aici	ag-P	Pr3fs
sna	sna	i-S	Spa-p
cailíní	cailíní	cailín-N	Ncmpc
ach	ach	ach-C	Cs
níor	níor	is-W	Ws-in
thaitin	thaitin	taitin-V	Vmis
an	an	an-T	Td-s
cineál	cineál	cineál-N	Ncmsc
sin	sin	sin-D	Dd
magaidh	magaidh	magadh-N	Ncmpc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
dhá	dhá	dó-M	Mc
rud	rud	rud-N	Ncmsc
ar	ar	ar-S	Sp
eolas	eolas	eolas-N	Ncmsc
aici	aici	ag-P	Pr3fs
anois	anois	anois-R	Rt
.	.	.-F	Fe
Brian	Brian	Brian-N	Ncmsc|Npmsc
t	t	t-X	Xl
‑	‑	‑-F	Fb
ainm	ainm	ainm-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ar	ar	ar-S	Sp
an	an	an-T	Td-s
luchóg	luchóg	luchóg-N	Ncfsc
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
cairde	cairde	cairde-N	Ncmpc|Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
aige	aige	ag-P	Pr3ms
ó	ó	ó-C	Cs
tharla	tharla	tarlaigh-V	Vmis
gur	gur	gur-Q	Q--s
dhiúltaigh	dhiúltaigh	diúltaigh-V	Vmis
sé	sé	sé-P	Pp3msn
Béarla	Béarla	béarla-N	Ncmsc
a	a	a-U	U
labhairt	labhairt	labhair-N	Nv
.	.	.-F	Fe
Fear	Fear	fear-N	Ncmsc
beag	beag	beag-A	Aq-msc
suimiúil	suimiúil	suimiúil-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
.	.	.-F	Fe
Chonacthas	Chonacthas	feic-V	Vmis0
do	do	do-S	Sp
Bhrídín	Bhrídín	Brídín-N	Npfsc
gur	gur	is-W	Wsdi|Wpdi
mhaith	mhaith	maith-A	Aqp
léi	léi	le-P	Pr3fs
aithne	aithne	aithne-N	Ncfsc
a	a	a-U	U
chur	chur	cuir-N	Nv
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
cead	cead	cead-N	Ncmsc
ag	ag	ag-S	Sp
muintir	muintir	muintir-N	Ncfsc
an	an	an-T	Td-s
bhaile	bhaile	baile-N	Ncmsg
dul	dul	téigh-N	Ncmsc|Nv
go dtí	go dtí	go_dtí-S	Spc
na	na	na-T	Td-p
céilithe	céilithe	céilí-N	Ncmpc
sa	sa	i-S	Spa-s
halla	halla	halla-N	Ncmsc
.	.	.-F	Fe
An	An	an-T	Td-s
oíche	oíche	oíche-N	Ncfsc
sin	sin	sin-D	Dd
chuaigh	chuaigh	téigh-V	Vmis
Brídín	Brídín	Brídín-N	Npfsc
ann	ann	i-P	Pr3ms
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
le	le	le-S	Sp
duine	duine	duine-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
dúil	dúil	dúil-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
aici	aici	ag-P	Pr3fs
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
damhsa	damhsa	damhsaigh-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
IONSAÍ	IONSAÍ	ionsaí-N	Ncmsc
NA	NA	na-T	Tdfsg
hINSE	hINSE	inis-N	Ncfsg
ANOIS	ANOIS	anois-N	Npmsc
!	!	!-F	Fe
CEATHRAR	CEATHRAR	ceathrar-N	Ncmsc
OS	OS	os-S	Sp
COMHAIR	COMHAIR	comhair-N	Ns-s
CEATHRAIR	CEATHRAIR	ceathrar-N	Ncmsg
.	.	.-F	Fe
ISTEACH	ISTEACH	isteach-R	Rd
AGUS	AGUS	agus-C	Cc
AMACH	AMACH	amach-R	Rd
,	,	,-F	Fi
ISTEACH	ISTEACH	isteach-R	Rd
AGUS	AGUS	agus-C	Cc
AMACH	AMACH	amach-R	Rd
!	!	!-F	Fe
’	’	’-F	Fa
Scairt	Scairt	scairt-V	Vmis|Vmm-2s|Ncfsc
an	an	an-T	Td-s
múinteoir	múinteoir	múinteoir-N	Ncmsc
damhsa	damhsa	damhsa-N	Nv|Nv--g|Ncmsg|Ncmsc
treoracha	treoracha	treoir-N	Ncfpc
an	an	an-T	Td-s
damhsa	damhsa	damhsa-N	Ncmsg
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
mhicreafón	mhicreafón	micreafón-N	Ncmsc
ach	ach	ach-C	Cs
,	,	,-F	Fi
dar	dar	dar-V	Vmip
le	le	le-S	Sp
Brídín	Brídín	Brídín-N	Npfsc
,	,	,-F	Fi
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
micreafón	micreafón	micreafón-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
a	a	a-Q	Q-r
dhíobháil	dhíobháil	díobháil-V	Vmis
air	air	ar-P	Pr3ms
nó	nó	nó-C	Cc
thiocfadh	thiocfadh	tar-V	Vmc
leat	leat	le-P	Pr2-s
é	é	é-P	Pp3ms
a	a	a-U	U
chluinstin	chluinstin	cluin-N	Nv
i	i	i-S	Sp
Leitir	Leitir	leitir-N	Ncfsc
Ceanainn	Ceanainn	cean-V	Vmih1s
gan	gan	gan-S	Sp
é	é	é-P	Pp3ms
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
nár	nár	is-W	Wsdqn
chuma	chuma	cuma-A	Aqp
?	?	?-F	Fq
Bhí	Bhí	bí-V	Vmis
Brídín	Brídín	Brídín-N	Npfsc
ag	ag	ag-S	Sp
damhsa	damhsa	damhsaigh-N	Nv
leis	leis	le-S	Sp
na	na	na-T	Td-p
scoláirí	scoláirí	scoláire-N	Ncmpc
óna	óna	ó-S	Spp-s
teach	teach	teach-N	Ncmsc
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
am	am	am-N	Ncmsc
ar	ar	ar-S	Sp
dóigh	dóigh	dóigh-N	Ncfsc
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
Lean	Lean	Lean-N	Npmsc
an	an	an-T	Td-s
múinteoir	múinteoir	múinteoir-N	Ncmsc
damhsa	damhsa	damhsa-N	Nv|Nv--g|Ncmsg|Ncmsc
leis	leis	le-S	Sp
na	na	na-T	Td-p
treoracha	treoracha	treoir-N	Ncfpc
,	,	,-F	Fi
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsg|Ncmsc
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
taobh	taobh	taobh-N	Ncmsc
leis	leis	le-P	Pr3ms
ag	ag	ag-S	Sp
coinneáil	coinneáil	coinnigh-N	Nv
súile	súile	súil-N	Ncfsg|Nv--g--n|Ncfsg|Nv--g--n
ar	ar	is-W	Wssi|Wpdi|Wpsi
chúrsaí	chúrsaí	cúrsach-A	Aqc
.	.	.-F	Fe
‘	‘	‘-X	Xx
BUACHAILLÍ	BUACHAILLÍ	buachaill-N	Ncmpc
TRASNA	TRASNA	trasna-R	Rd
.	.	.-F	Fe
CAILÍNÍ	CAILÍNÍ	cailín-N	Ncmpc
TRASNA	TRASNA	trasna-R	Rd
.	.	.-F	Fe
ANOIS	ANOIS	anois-N	Npmsc
LUASCAIGÍ	LUASCAIGÍ	luasc-V	Vmm-2p
.	.	.-F	Fe
FAIGH	FAIGH	faigh-V	Vmm-2s
GREIM	GREIM	greim-N	Ncmsc
AR	AR	ar-S	Sp
AN	AN	an-T	Td-s
UILLINN	UILLINN	uillinn-N	Ncfsc
!	!	!-F	Fe
’	’	’-F	Fa
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
damhsa	damhsa	damhsa-N	Ncmsc
thart	thart	thart-R	Rd
bhí	bhí	bí-V	Vmis
tuirse	tuirse	tuirse-N	Ncfsc
ar	ar	ar-S	Sp
Bhrídín	Bhrídín	Brídín-N	Npfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
spás	spás	spás-N	Ncmsc
taobh	taobh	taobh-N	Ncmsc
le	le	le-S	Sp
Brian	Brian	Brian-N	Ncmsc|Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
ina	ina	i-S	Spp-s
shuí	shuí	suí-N	Ncmsc
ansin	ansin	ansin-R	Rt|Rl
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
sí	sí	sí-P	Pp3fsn
de	de	de-P	Pr3ms
agus	agus	agus-C	Cc
a	a	a-D	Dp3
hanáil	hanáil	anáil-N	Ncfsc
i	i	i-S	Sp
mbarr	mbarr	barr-N	Ncmsc
a	a	a-D	Dp3
goib	goib	gob-N	Ncmsg
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Chan	Chan	can-V	Vmis
fhuil	fhuil	fuil-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhreagair	fhreagair	freagair-V	Vmis
Brian	Brian	Brian-N	Ncmsc|Npmsc
go	go	go-U	Ua
faiteach	faiteach	faiteach-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
mise	mise	mé-P	Pp1-s-e
Brídín	Brídín	Brídín-N	Npfsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
a	a	a-D	Dp3
hanáil	hanáil	anáil-N	Ncfsc
léi	léi	le-P	Pr3fs
arís	arís	arís-R	Rg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
mise	mise	mé-P	Pp1-s-e
Brian	Brian	Brian-N	Ncmsc|Npmsc
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhreagair	fhreagair	freagair-V	Vmis
an	an	an-T	Td-s
luchóg	luchóg	luchóg-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
sin	sin	sin-P	Pd|W|Dd
ag	ag	ag-S	Sp
Brídín	Brídín	Brídín-N	Npfsc
cheana	cheana	cion-N	Ncmsg
féin	féin	féin-P	Px
,	,	,-F	Fi
ar	ar	ar-S	Sp
ndóigh	ndóigh	dóigh-N	Ncfsc
,	,	,-F	Fi
ach	ach	ach-C	Cs
ní	ní	is-W	Wp-in
dúirt	dúirt	abair-V	Vmis
sí	sí	sí-P	Pp3fsn
rud	rud	rud-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfaca	bhfaca	feic-V	Vmis---d
tú	tú	tú-P	Pp2-s
sinn	sinn	sinn-P	Pp1-p
ag	ag	ag-S	Sp
damhsa	damhsa	damhsaigh-N	Nv
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
Brídín	Brídín	Brídín-N	Npfsc
den	den	de-S	Spa-s
luchóg	luchóg	luchóg-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Chonaic	Chonaic	feic-V	Vmis
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
go	go	go-U	Ua
maith	maith	maith-A	Aqp
ag	ag	ag-S	Sp
damhsa	damhsa	damhsaigh-N	Nv
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
tá	tá	bí-V	Vmip
Gaeilge	Gaeilge	Gaeilge-N	Npfsc
mhaith	mhaith	maith-A	Aq-fsc
agat	agat	ag-P	Pr2-s
fosta	fosta	fosta-A	Aqp|Rg
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Bhuel	Bhuel	bhuel-X	Xsc
,	,	,-F	Fi
tá	tá	bí-V	Vmip
súil	súil	súil-N	Ncfsc
agam	agam	ag-P	Pr1-s
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
.	.	.-F	Fe
Rugadh	Rugadh	beir-V	Vmis0
agus	agus	agus-C	Cc
tógadh	tógadh	tóg-V	Vmm-3s
anseo	anseo	anseo-R	Rl
i	i	i-S	Sp
mBaile	mBaile	Baile-N	Npmsc
na	na	na-T	Tdfsg
hÁille	hÁille	áille-N	Ncfsg
mé	mé	mé-P	Pp1-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
ag	ag	ag-S	Sp
gáire	gáire	gáir-N	Nv
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
luchóg	luchóg	luchóg-N	Ncfsc
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
aoibh	aoibh	aoibh-N	Ncfsc
an	an	an-T	Td-s
gháire	gháire	gáire-N	Ncmsg
airsean	airsean	ar-P	Pr3ms-e
fosta	fosta	fosta-A	Aqp|Rg
.	.	.-F	Fe
Chaith	Chaith	caith-V	Vmis
Brídín	Brídín	Brídín-N	Npfsc
agus	agus	agus-C	Cc
Brian	Brian	Brian-N	Ncmsc|Npmsc
tamall	tamall	tamall-N	Ncmpg|Ncmsc
fada	fada	fada-A	Aqp
ag	ag	ag-S	Sp
comhrá	comhrá	comhrá-N	Nv-----n
.	.	.-F	Fe
Dúirt	Dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
léi	léi	le-P	Pr3fs
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
deartháir	deartháir	deartháir-N	Ncmsc
ná	ná	ná-C	Cc
deirfiúr	deirfiúr	deirfiúr-N	Ncfsc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Tógadh	Tógadh	tóg-V	Vmm-3s
le	le	le-S	Sp
Gaeilge	Gaeilge	Gaeilge-N	Npfsc
é	é	é-P	Pp3ms
ach	ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
duine	duine	duine-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
dá	dá	do-S	Spp-s
chairde	chairde	cairde-N	Ncmpc|Ncmsc
sásta	sásta	sásta-A	Aqp
Gaeilge	Gaeilge	Gaeilge-N	Npfsc|Npfsg
a	a	a-U	U
labhairt	labhairt	labhair-N	Nv
leis	leis	le-P	Pr3ms
,	,	,-F	Fi
fiú	fiú	fiú-N	Ns-s|Ncmsc|Rg
sa	sa	i-S	Spa-s
Ghaelscoil	Ghaelscoil	gaelscoil-N	Npmsc
sa	sa	i-S	Spa-s
bhaile	bhaile	baile-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
‑	‑	‑-F	Fb
sásta	sásta	sásta-A	Aqc
bualadh	bualadh	buail-N	Ncmsc|Nv
le	le	le-S	Sp
Brídín	Brídín	Brídín-N	Npfsc
.	.	.-F	Fe
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
tháinig	tháinig	tar-V	Vmis
scoláirí	scoláirí	scoláire-N	Ncmpc
an	an	an-T	Td-s
tí	tí	teach-N	Ncmsg
anall	anall	anall-R	Rd
chucu	chucu	chuig-P	Pr3-p
agus	agus	agus-C	Cc
tharraing	tharraing	tarraing-V	Vmis
siad	siad	siad-P	Pp3-pn
Brídín	Brídín	Brídín-N	Npfsc
amach	amach	amach-R	Rd
ag	ag	ag-S	Sp
damhsa	damhsa	damhsaigh-N	Nv
leo	leo	le-P	Pr3-p
arís	arís	arís-R	Rg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tchífidh	Tchífidh	tchí-V	Vmif
mé	mé	mé-P	Pp1-s
arís	arís	arís-R	Rg
thú	thú	tú-P	Pp2-s
,	,	,-F	Fi
a	a	a-U	Uv
Bhriain	Bhriain	Brian-N	Ncmsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Brídín	Brídín	Brídín-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tchífidh	Tchífidh	tchí-V	Vmif
,	,	,-F	Fi
cinnte	cinnte	cinnte-A	Av|Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Brian	Brian	Brian-N	Ncmsc|Npmsc
agus	agus	agus-C	Cc
aoibh	aoibh	aoibh-N	Ncfsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Tonnta	Tonnta	tonn-A	Av|Ncfpc
Thoraí	Thoraí	toradh-N	Ncmpg
an	an	an-T	Td-s
chéad	chéad	céad-M	Mo
damhsa	damhsa	damhsa-N	Ncmsg|Ncmsc
eile	eile	eile-D	Dd
.	.	.-F	Fe
Rinne	Rinne	déan-V	Vmis
Brídín	Brídín	Brídín-N	Npfsc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
cailíní	cailíní	cailín-N	Ncmpc
an	an	an-T	Td-s
oiread	oiread	oiread-N	Ns-s
gáire	gáire	gáir-N	Ncfsg|Nv|Ncmsg|Ncmsc|Nv--g
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
na	na	na-T	Td-p
deora	deora	deoir-N	Ncfpc
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
damhsa	damhsa	damhsa-N	Ncmsc
thart	thart	thart-R	Rd
tháinig	tháinig	tar-V	Vmis
sí	sí	sí-P	Pp3fsn
ar ais	ar ais	ar_ais-R	Rd
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
áit	áit	áit-N	Ncfsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
Brian	Brian	Brian-N	Ncmsc|Npmsc
ina	ina	i-S	Spp-s
shuí	shuí	suí-N	Ncmsc
ach	ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
imithe	imithe	imigh-A	Av
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
Brídín	Brídín	Brídín-N	Npfsc
amach	amach	amach-R	Rd
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
leithreas	leithreas	leithreas-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
díreach	díreach	díreach-A	Aqp
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
bealach	bealach	bealach-N	Ncmsc
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
halla	halla	halla-N	Ncmsc
mór	mór	mór-A	Aq-msc
arís	arís	arís-R	Rg
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
béicíl	béicíl	béicíl-N	Nv-----n
in	in	sin-S	Sp|Pd
ard	ard	ard-N	Ncmsc|Aqp
a	a	a-Q	Q-r
chinn	chinn	cinn-V	Vmis
.	.	.-F	Fe
‘	‘	‘-X	Xx
Focal	Focal	focal-N	Ncmsc
amháin	amháin	amháin-A	Aqp
eile	eile	eile-D	Dd
Béarla	Béarla	béarla-N	Ncmsc
uaitse	uaitse	ó-P	Pr2-s-e
agus	agus	agus-C	Cc
beidh	beidh	bí-V	Vmif
tú	tú	tú-P	Pp2-s
ar	ar	ar-S	Sp
bhus	bhus	bus-N	Ncmsc
Bhaile	Bhaile	Baile-N	Npmsg
Átha Cliath	Átha Cliath	Átha_Cliath-N	Npmsc
sula	sula	sula-C	Cs
dtig	dtig	teach-N	Ncmsd
leat	leat	le-P	Pr2-s
Molly	Molly	Molly-N	Npfsc
Malone	Malone	Malone-N	Npmsc
a	a	a-U	U
rá	rá	abair-N	Nv
!	!	!-F	Fe
’	’	’-F	Fa
Níorbh	Níorbh	is-W	Ws-in
é	é	é-P	Pp3ms
sin	sin	sin-P	Pd|W
an	an	an-T	Td-s
chéad	chéad	céad-M	Mo
uair	uair	uair-N	Ncfsc
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
mharóg	mharóg	maróg-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
téad	téad	téad-N	Ncfsc
sin	sin	sin-D	Dd
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-V	Vmis
sí	sí	sí-P	Pp3fsn
thart	thart	thart-R	Rd
an	an	an-T	Td-s
coirnéal	coirnéal	coirnéal-N	Ncmsc
go	go	go-Q	Q
bhfeicfeadh	bhfeicfeadh	feic-V	Vmc
sí	sí	sí-P	Pp3fsn
cé	cé	cé-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
gaibhte	gaibhte	gaibhte-A	Av
anois	anois	anois-R	Rt
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
doras	doras	doras-N	Ncmsc
na	na	na-T	Tdfsg
hoifige	hoifige	oifig-N	Ncfsg
oscailte	oscailte	oscail-A	Aqp|Av
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
Brídín	Brídín	Brídín-N	Npfsc
in ann	in ann	in_ann-S	Spc
é	é	é-P	Pp3ms
a	a	a-U	U
chreidiúint	chreidiúint	creid-N	Nv
.	.	.-F	Fe
Brian	Brian	Brian-N	Ncmsc|Npmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
glacadh	glacadh	glac-N	Nv
leis	leis	le-S	Sp
an	an	an-T	Td-s
íde	íde	íde-N	Ncfsc|Npfsc
béil	béil	béal-N	Ncmsg|Ncmpc
.	.	.-F	Fe
Brian	Brian	Brian-N	Ncmsc|Npmsc
ag	ag	ag-S	Sp
labhairt	labhairt	labhair-N	Nv
Béarla	Béarla	béarla-N	Ncmsg
?	?	?-F	Fq
I	I	i-S	Sp
ndiaidh	ndiaidh	diaidh-N	Ns-s
an	an	an-T	Td-s
chomhrá	chomhrá	comhrá-N	Ncmsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
aici	aici	ag-P	Pr3fs
leis	leis	le-P	Pr3ms
,	,	,-F	Fi
ní	ní	ní-Q	Qn
chreidfeadh	chreidfeadh	creid-V	Vmc----n
sí	sí	sí-P	Pp3fsn
é	é	é-P	Pp3ms
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
lean	lean	lean-V	Vmis
an	an	an-T	Td-s
mharóg	mharóg	maróg-N	Ncfsc
leis	leis	le-P	Pr3ms
:	:	:-F	Fi
‘	‘	‘-X	Xx
Nach	Nach	nach-Q	Qnrs
bhfaca	bhfaca	feic-V	Vmis---d
mé	mé	mé-P	Pp1-s
le	le	le-S	Sp
mo	mo	mo-D	Dp1-s
shúile	shúile	súil-N	Ncfpc
cinn	cinn	ceann-N	Ncmsg|Ncmpc
féin	féin	féin-P	Px
thú	thú	tú-P	Pp2-s
agus	agus	agus-C	Cc
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
geabaireacht	geabaireacht	geabaireacht-N	Ncfsc
leat	leat	le-P	Pr2-s
sa	sa	i-S	Spa-s
halla	halla	halla-N	Ncmsc
!	!	!-F	Fe
Ná	Ná	ná-Q	Qnm
habair	habair	abair-V	Vmm-2s-n
liom	liom	le-P	Pr1-s
gur	gur	is-W	Wsdi
i	i	i-S	Sp
nGaeilge	nGaeilge	Gaeilge-N	Npfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
leis	leis	le-S	Sp
an	an	an-T	Td-s
chailín	chailín	cailín-N	Ncmsg
rua	rua	rua-A	Aqp
sin	sin	sin-D	Dd
.	.	.-F	Fe
Samhlaigh	Samhlaigh	samhlaigh-V	Vmm-2s
é	é	é-P	Pp3ms
!	!	!-F	Fe
Bleá	Bleá	Bleá-N	Npmsc
Cliathach	Cliathach	cliathach-A	Aq-msc
cosúil	cosúil	cosúil-A	Aq-msc
leatsa	leatsa	le-P	Pr2-s-e
a	a	a-U	U
bheith	bheith	bí-N	Nv
in ann	in ann	in_ann-S	Spc
labhairt	labhairt	labhair-N	Nv
mar	mar	mar-C	Cs
sin	sin	sin-W	W
i	i	i-S	Sp
nGaeilge	nGaeilge	Gaeilge-N	Npfsc
!	!	!-F	Fe
’	’	’-F	Fa
Tuigeadh	Tuigeadh	tuig-V	Vmm-3s
do	do	do-S	Sp
Bhrídín	Bhrídín	Brídín-N	Npfsc
ansin	ansin	ansin-R	Rt|Rl
gurbh	gurbh	is-W	Wsdi
í	í	í-P	Pp3fs
féin	féin	féin-P	Px
ba	ba	is-W	Wsri
chúis	chúis	cúis-N	Ncfsc
le	le	le-S	Sp
barúil	barúil	barúil-N	Ncfsc
an	an	an-T	Td-s
phríomhoide	phríomhoide	príomhoide-N	Ncmsg
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
sí	sí	sí-P	Pp3fsn
abhaile	abhaile	abhaile-R	Rd
agus	agus	agus-C	Cc
croí	croí	croí-N	Ncmsc
trom	trom	trom-A	Aq-msc
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
máthair	máthair	máthair-N	Ncfsc
roimpi	roimpi	roimh-P	Pr3fs
sa	sa	i-S	Spa-s
chistin	chistin	cistin-N	Ncfsc
ag	ag	ag-S	Sp
réiteach	réiteach	réitigh-N	Nv
an	an	an-T	Td-s
tsuipéir	tsuipéir	suipéar-N	Ncmsg
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
Brídín	Brídín	Brídín-N	Npfsc
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
ina	ina	i-S	Spp-s|Spp-p
láthairse	láthairse	láthair-N	Ncfsc-e
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
sé	sé	sé-P	Pp3msn
cothrom	cothrom	cothrom-A	Aqp
,	,	,-F	Fi
a	a	a-U	Uv
Mhamaí	Mhamaí	mama-N	Ncfsv|Ncmpv
.	.	.-F	Fe
Is	Is	is-W	Wp-i
é	é	é-P	Pp3ms
Brian	Brian	Brian-N	Ncmsc|Npmsc
t	t	t-X	Xl
‑	‑	‑-F	Fb
aon	aon	aon-D	Dq
scoláire	scoláire	scoláire-N	Ncmsc
a	a	a-Q	Q-r
labhraíonn	labhraíonn	labhair-V	Vmip
Gaeilge	Gaeilge	Gaeilge-N	Npfsc
t	t	t-X	Xl
‑	‑	‑-F	Fb
am	am	am-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
agus	agus	agus-C	Cc
tá	tá	bí-V	Vmip
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
anuas	anuas	anuas-R	Rd
air	air	ar-P	Pr3ms
as	as	as-P	Pr3ms
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
labhairt	labhairt	labhair-N	Nv
Béarla	Béarla	béarla-N	Ncmsg
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
chuala	chuala	clois-V	Vmis
mise	mise	mé-P	Pp1-s-e
aon	aon	aon-D	Dq
fhocal	fhocal	focal-N	Ncmsc
Béarla	Béarla	béarla-N	Ncmsc|Ncmsg
uaidh	uaidh	ó-P	Pr3ms
agus	agus	agus-C	Cc
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
ceart	ceart	ceart-N	Ncmsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
thaisce	thaisce	taisce-N	Ncfsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
a	a	a-U	Ud|Dp3
mamaí	mamaí	mamaí-N	Ncmpc|Aqc|Ncfsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
ach	ach	ach-C	Cs
is	is	is-W	Wpri
minic	minic	minic-A	Aqp
éagóir	éagóir	éagóir-A	Aqp
déanta	déanta	déan-A	Av
ar	ar	ar-S	Sp
dhuine	dhuine	duine-N	Ncmsc
neamhurchóideach	neamhurchóideach	neamhurchóideach-A	Aq-msc
.	.	.-F	Fe
’	’	’-F	Fa
An	An	an-T	Td-s
oíche	oíche	oíche-N	Ncfsc
sin	sin	sin-D	Dd
chuaigh	chuaigh	téigh-V	Vmis
Brídín	Brídín	Brídín-N	Npfsc
a	a	a-U	U
smaoineamh	smaoineamh	smaoinigh-N	Nv
ar	ar	ar-S	Sp
Bhrian	Bhrian	Brian-N	Ncmsc|Npmsc
agus	agus	agus-C	Cc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
méid	méid	méid-N	Ncmsc
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
a	a	a-U	Ud|Dp3
mamaí	mamaí	mamaí-N	Ncmpc|Aqc|Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
éagóra	éagóra	éagóir-N	Ncfsg
air	air	ar-P	Pr3ms
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
a	a	a-Q	Q-r
dhath	dhath	dath-V	Vmis
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
faoi	faoi	faoi-S	Sp
dtaobh	dtaobh	taobh-N	Ncmsc
de	de	de-P	Pr3ms
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
an	an	an-T	Td-s
dara	dara	dara-M	Mo
suí	suí	suí-N	Ncmsc
sa	sa	i-S	Spa-s
bhuaile	bhuaile	buaile-N	Ncfsc
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
Bheadh	Bheadh	bí-V	Vmc
uirthi	uirthi	ar-P	Pr3fs
an	an	an-T	Td-s
fhadhb	fhadhb	fadhb-N	Ncfsc
seo	seo	seo-D	Dd
a	a	a-U	U
chur	chur	cuir-N	Nv
i	i	i-S	Sp
gceart	gceart	ceart-N	Ncmsc
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
maidin	maidin	maidin-N	Ncfsc
bhuail	bhuail	buail-V	Vmis
Brídín	Brídín	Brídín-N	Npfsc
cnag	cnag	cnag-N	Ncmsc
ar	ar	ar-S	Sp
dhoras	dhoras	doras-N	Ncmsc
oifig	oifig	oifig-N	Ncfsc
an	an	an-T	Td-s
choláiste	choláiste	coláiste-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
ISTEACH	ISTEACH	isteach-R	Rd
.	.	.-F	Fe
’	’	’-F	Fa
Baineadh	Baineadh	bain-V	Vmis0
stad	stad	stad-N	Ncmsc
aisti	aisti	as-P	Pr3fs
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
thóg	thóg	tóg-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
ceann	ceann	ceann-N	Ncmsc
,	,	,-F	Fi
bhrúigh	bhrúigh	brúigh-V	Vmis
sí	sí	sí-P	Pp3fsn
siar	siar	siar-R	Rd
a	a	a-D	Dp3
guaillí	guaillí	gualainn-N	Ncmsc|Ncfpc
agus	agus	agus-C	Cc
rug	rug	beir-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
bhoschrann	bhoschrann	boschrann-N	Ncmsc
an	an	an-T	Td-s
dorais	dorais	doras-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cé	Cé	cé-N	Ncfsc|Cs
thusa	thusa	tú-P	Pp2-s-e
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
an	an	an-T	Td-s
mharóg	mharóg	maróg-N	Ncfsc
di	di	do-P	Pr3fs
,	,	,-F	Fi
a	a	a-U	Uv|Dp3
athsmig	athsmig	athsmig-N	Ncfsc|Ncfsv
ag	ag	ag-S	Sp
brú	brú	brúigh-N	Nv
thar	thar	thar-S	Sp
bhóna	bhóna	bóna-N	Ncmsc
a	a	a-D	Dp3
léine	léine	léine-N	Ncfsc
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
dearcadh	dearcadh	dearc-N	Nv
go	go	go-U	Ua
grinn	grinn	grinn-A	Aqp
ar	ar	ar-S	Sp
Bhrídín	Bhrídín	Brídín-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Brídín	Brídín	Brídín-N	Npfsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cén	Cén	cé-W	W--q
rang	rang	rang-N	Ncmsc
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
mé	mé	mé-P	Pp1-s
i	i	i-S	Sp
rang	rang	rang-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
as	as	as-P	Pr3ms
an	an	an-T	Td-s
bhaile	bhaile	baile-N	Ncmsg
mé	mé	mé-P	Pp1-s
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Cé	Cé	cé-P	Pq
leis	leis	le-P	Pr3ms
thú	thú	tú-P	Pp2-s
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Le	Le	le-S	Sp
Mary	Mary	Mary-N	Npfsc
Eoghain	Eoghain	Eoghan-N	Npmsg|Npm-g
Shéamais	Shéamais	Séamais-N	Npfsg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Brídín	Brídín	Brídín-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
anois	anois	anois-R	Rt
cé	cé	cé-C	Cs|Ncfsc
thú	thú	tú-P	Pp2-s
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
seanaithne	seanaithne	seanaithne-N	Ncfsc
agam	agam	ag-P	Pr1-s
ar	ar	ar-N	Ncmsc
do	do	do-S	Sp
mháthair	mháthair	máthair-N	Ncfsc
,	,	,-F	Fi
Mary	Mary	Mary-N	Npfsc
Eoghain	Eoghain	Eoghan-N	Npmsg|Npm-g
Shéamais	Shéamais	Séamais-N	Npfsg
Mháire	Mháire	Máire-N	Npf-g
Dhonnchaidh	Dhonnchaidh	Donnchaidh-N	Npfsg
Mhóir	Mhóir	mór-N	Ncmsg
.	.	.-F	Fe
’	’	’-F	Fa
Níor	Níor	níor-Q	Qn-s
thug	thug	tabhair-V	Vmis---n
Brídín	Brídín	Brídín-N	Npfsc
freagra	freagra	freagra-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
de	de	de-S	Sp
nós	nós	nós-N	Ncmsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
mharóg	mharóg	maróg-N	Ncfsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
maíomh	maíomh	maígh-N	Nv
as	as	as-S	Sp
an	an	an-T	Td-s
aithne	aithne	aithne-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
aige	aige	ag-P	Pr3ms
ar	ar	ar-S	Sp
mhuintir	mhuintir	muintir-N	Ncfsc
an	an	an-T	Td-s
bhaile	bhaile	baile-N	Ncmsg
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
thuig	thuig	tuig-V	Vmip---n|Vmis---n
sé	sé	sé-P	Pp3msn
féin	féin	féin-P	Px
,	,	,-F	Fi
áfach	áfach	áfach-R	Rg
,	,	,-F	Fi
gur	gur	is-W	Wsdi|Wpdi
duine	duine	duine-N	Ncmsc
as	as	as-S	Sp
baile	baile	baile-N	Ncmsc
isteach	isteach	isteach-R	Rd
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
ann	ann	i-P	Pr3ms
cé	cé	cé-C	Cs
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
le	le	le-S	Sp
caoga	caoga	caoga-N	Ncmsc
samhradh	samhradh	samhradh-N	Ncmsc
caite	caite	caith-A	Av
aige	aige	ag-P	Pr3ms
i	i	i-S	Sp
mBaile	mBaile	Baile-N	Npmsc
na	na	na-T	Tdfsg
hÁille	hÁille	áille-N	Ncfsg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-N	Ncmsc|Nv
Brídín	Brídín	Brídín-N	Npf-g|Npfsc
thart	thart	thart-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
oifig	oifig	oifig-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
cuma	cuma	cuma-N	Ncfsc
‑	‑	‑-F	Fb
néata	néata	néata-A	Aqc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
áit	áit	áit-N	Ncfsc
.	.	.-F	Fe
Smaoinigh	Smaoinigh	smaoinigh-V	Vmis
sí	sí	sí-P	Pp3fsn
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
chuma	chuma	cuma-N	Ncfsc
uirthi	uirthi	ar-P	Pr3fs
nach	nach	nach-Q	Qnr|Qnrs
mórán	mórán	mórán-N	Ncmsc
oibre	oibre	obair-N	Nv--g--n|Ncfsg
inti	inti	i-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
atá	atá	bí-V	Vmip---r
tú	tú	tú-P	Pp2-s
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
anseo	anseo	anseo-R	Rl
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Tháinig	Tháinig	tar-V	Vmis
mé	mé	mé-P	Pp1-s
a	a	a-U	U
labhairt	labhairt	labhair-N	Nv
leat	leat	le-P	Pr2-s
faoi	faoi	faoi-S	Sp
scoláire	scoláire	scoláire-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhreagair	fhreagair	freagair-V	Vmis
Brídín	Brídín	Brídín-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
bean	bean	bean-N	Ncfsc
de	de	de-S	Sp
na	na	na-T	Td-p
cailíní	cailíní	cailín-N	Ncmpc
sin	sin	sin-D	Dd
ag	ag	ag-S	Sp
tabhairt	tabhairt	tabhair-N	Nv
trioblóide	trioblóide	trioblóid-N	Ncfsg
sa	sa	i-S	Spa-s
teach	teach	teach-N	Ncmsc
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhiafraigh	fhiafraigh	fiafraigh-V	Vmis
an	an	an-T	Td-s
mharóg	mharóg	maróg-N	Ncfsc
di	di	do-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Abair	Abair	abar-N	Ncmpc
liom	liom	le-P	Pr1-s
cé	cé	cé-W	W--q
hí	hí	í-N	Ncfsg
agus	agus	agus-C	Cc
…	…	…-F	Fi
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ní	Ní	Ní-W	Wp-in|Up
cailín	cailín	cailín-N	Ncmsc
atá	atá	bí-V	Vmip---r
ann	ann	i-P	Pr3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Brídín	Brídín	Brídín-N	Npfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
duine	duine	duine-N	Ncmsc
de	de	de-S	Sp
na	na	na-T	Td-p
buachaillí	buachaillí	buachaill-N	Ncmpc
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
isteach	isteach	isteach-R	Rd
ort	ort	ar-P	Pr2-s
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhreagair	fhreagair	freagair-V	Vmis
Brídín	Brídín	Brídín-N	Npfsc
.	.	.-F	Fe
Tharraing	Tharraing	tarraing-V	Vmis
sí	sí	sí-P	Pp3fsn
anáil	anáil	anáil-N	Ncfsc
agus	agus	agus-C	Cc
shocraigh	shocraigh	socraigh-V	Vmis
sí	sí	sí-P	Pp3fsn
í	í	í-P	Pp3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tusa	tusa	tú-P	Pp2-s-e
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
isteach	isteach	isteach-R	Rd
ar	ar	ar-S	Sp
dhuine	dhuine	duine-N	Ncmsc
de	de	de-S	Sp
na	na	na-T	Td-p
buachaillí	buachaillí	buachaill-N	Ncmpc
.	.	.-F	Fe
’	’	’-F	Fa
Bhí	Bhí	bí-V	Vmis
tost	tost	tost-N	Ncmsc
sa	sa	i-S	Spa-s
seomra	seomra	seomra-N	Ncmsc
ar feadh	ar feadh	ar_feadh-S	Spc
cúpla	cúpla	cúpla-N	Ncmsg
soicind	soicind	soicind-N	Ncmsg|Ncmsc
,	,	,-F	Fi
ach	ach	ach-C	Cs
mhothaigh	mhothaigh	mothaigh-V	Vmis
Brídín	Brídín	Brídín-N	Npfsc
gur	gur	gur-Q	Q--s
mhair	mhair	mair-V	Vmis
sé	sé	sé-P	Pp3msn
deich	deich	deich-M	Mc|Ncmsc
mbomaite	mbomaite	bomaite-N	Ncmsg|Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cad	Cad	cad-W	W--q
é	é	é-P	Pp3ms
atá	atá	bí-V	Vmip---r
i	i	i-S	Sp
gceist	gceist	ceist-N	Ncfsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
chailín	chailín	cailín-N	Ncmsv
?	?	?-F	Fq
’	’	’-F	Fa
a	a	a-Q	Q-r
bhéic	bhéic	béic-V	Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Thug	Thug	tabhair-V	Vmis
tú	tú	tú-P	Pp2-s
amach	amach	amach-R	Rd
do	do	do-S	Sp
Bhrian	Bhrian	Brian-N	Ncmsc|Npmsc
Ó	Ó	Ó-U	Up
Buachalla	Buachalla	Buachalla-N	Npmsc
as	as	as-P	Pr3ms
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
labhairt	labhairt	labhair-N	Nv
Béarla	Béarla	béarla-N	Ncmsg
ag	ag	ag-S	Sp
an	an	an-T	Td-s
chéilí	chéilí	céilí-N	Ncmsg
aréir	aréir	aréir-A	Aqp
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	is-W	Wp-in
Béarla	Béarla	béarla-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
á	á	do-S	Spo-s
labhairt	labhairt	labhair-N	Nv
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Cad	Cad	cad-W	W--q
é	é	é-P	Pp3ms
?	?	?-F	Fq
’	’	’-F	Fa
Bhí	Bhí	bí-V	Vmis
leathshúil	leathshúil	leathshúil-N	Ncfsc
ag	ag	ag-S	Sp
éirí	éirí	éirigh-N	Nv
mór	mór	mór-A	Aqp
agus	agus	agus-C	Cc
an	an	an-T	Td-s
leathshúil	leathshúil	leathshúil-N	Ncfsc
eile	eile	eile-D	Dd
beagnach	beagnach	beagnach-R	Rg
druidte	druidte	druid-A	Av
ag	ag	ag-S	Sp
an	an	an-T	Td-s
phríomhoide	phríomhoide	príomhoide-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Gaeilge	Gaeilge	Gaeilge-N	Npfsc
a	a	a-Q	Q-r
labhraíonn	labhraíonn	labhair-V	Vmip
Brian	Brian	Brian-N	Ncmsc|Npmsc
t	t	t-X	Xl
‑	‑	‑-F	Fb
am	am	am-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
mar	mar	mar-C	Cs
atá	atá	bí-V	Vmip---r
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agatsa	agatsa	ag-P	Pr2-s-e
sin	sin	sin-P	Pd
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Mar	Mar	mar-C	Cs
gur	gur	is-W	Wsdi
Gaeilge	Gaeilge	Gaeilge-N	Npfsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
a	a	a-Q	Q-r
labhair	labhair	labhair-V	Vmis
sé	sé	sé-P	Pp3msn
liom	liom	le-P	Pr1-s
aréir	aréir	aréir-N	Ns-s
ag	ag	ag-S	Sp
an	an	an-T	Td-s
chéilí	chéilí	céilí-N	Ncmsg
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
na	na	na-T	Td-p
cailíní	cailíní	cailín-N	Ncmpc
sa	sa	i-S	Spa-s
teach	teach	teach-N	Ncmsc
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
ag	ag	ag-S	Sp
gáire	gáire	gáir-N	Nv
faoi	faoi	faoi-S	Sp
cionn	cionn	ceann-N	Ncfsd
is	is	agus-C	Cc
nach	nach	nach-Q	Qnr
labhróidh	labhróidh	labhair-V	Vmif---n
sé	sé	sé-P	Pp3msn
Béarla	Béarla	béarla-N	Ncmsc
leo	leo	le-P	Pr3-p
!	!	!-F	Fe
’	’	’-F	Fa
Agus	Agus	agus-C	Cc
Brídín	Brídín	Brídín-N	Npfsc
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
ar ais	ar ais	ar_ais-R	Rd
chun	chun	chun-S	Sp
tí	tí	teach-N	Ncmsg
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
rud	rud	rud-N	Ncmsc
beag	beag	beag-A	Aq-msc
imní	imní	imní-N	Ncfsg|Ncfsc
uirthi	uirthi	ar-P	Pr3fs
go	go	go-C	Cs
mb	mb	mb-Y	Y
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
nár	nár	nár-Q	Qnrs
chreid	chreid	creid-V	Vmis---n
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
í	í	í-P	Pp3fs
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
fiú	fiú	fiú-N	Ns-s|Ncmsc|Rg
má	má	má-C	Cs
chreid	chreid	creid-V	Vmis
,	,	,-F	Fi
b	b	b-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
go	go	go-Q	Q
gcaithfeadh	gcaithfeadh	caith-V	Vmc
sé	sé	sé-P	Pp3msn
níos	níos	níos-U	Uc
measa	measa	olc-A	Aqc
le	le	le-S	Sp
Brian	Brian	Brian-N	Ncmsc|Npmsc
mar	mar	mar-S	Sp
gheall	gheall	geall-N	Ncmsc
ar	ar	is-N	Ncmsc|Wpsi|Wssi|Wpdi
gur	gur	gur-Q	Q--s
labhair	labhair	labhair-V	Vmis
sí	sí	sí-P	Pp3fsn
chomh	chomh	chomh-R	Ri
díreach	díreach	díreach-A	Aqp
sin	sin	sin-P	Pd|W|Dd
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
dúil	dúil	dúil-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
ag	ag	ag-S	Sp
Brian	Brian	Brian-N	Ncmsc|Npmsc
i	i	i-S	Sp
ranganna	ranganna	rang-N	Ncmpc
na	na	na-T	Tdfsg
maidine	maidine	maidin-N	Ncfsg
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
é	é	é-P	Pp3ms
a	a	a-D	Dp3
is	is	is-W	Wpri
a	a	a-U	U
fhónamh	fhónamh	fóin-N	Nv
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
tógáil	tógáil	tóg-N	Nv
nathanna	nathanna	nath-N	Ncmpg
agus	agus	agus-C	Cc
leaganacha	leaganacha	leagan-N	Ncmpc
maithe	maithe	maith-A	Aq--pc
cainte	cainte	caint-N	Ncfsg|Nv--g--n
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
níorbh	níorbh	is-W	Ws-in
amhlaidh	amhlaidh	amhlaidh-R	Rg
do	do	do-S	Sp
bhunús	bhunús	bunús-N	Ncmsc
na	na	na-T	Td-p
scoláirí	scoláirí	scoláire-N	Ncmpg
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
siadsan	siadsan	siad-P	Pp3-pne
ach	ach	ach-C	Cs
ar	ar	is-W	Wpdi|Wpsi|Wssi
mhaithe	mhaithe	maithe-N	Ncfsc
le	le	le-S	Sp
craic	craic	craic-N	Ncfsc
agus	agus	agus-C	Cc
cuideachta	cuideachta	cuideachta-N	Ncfsg|Ncfsc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
an	an	an-T	Td-s
múinteoir	múinteoir	múinteoir-N	Ncmsc
ag	ag	ag-S	Sp
scríobh	scríobh	scríobh-N	Nv
ar	ar	is-W	Wpsi|Ncmsc|Wssi|Wpdi
chuala	chuala	clois-V	Vmis
sé	sé	sé-P	Pp3msn
scríobadh	scríobadh	scríob-N	Nv|Ncmsc|Nv
ó	ó	ó-S	Sp
chúl	chúl	cúl-N	Ncmsc
an	an	an-T	Td-s
tseomra	tseomra	seomra-N	Ncmsg
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-V	Vmis
sé	sé	sé-P	Pp3msn
síos	síos	síos-R	Rd
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ach	ach	ach-S	Sp
duine	duine	duine-N	Ncmsc
amháin	amháin	amháin-A	Aqp
ag	ag	ag-S	Sp
amharc	amharc	amharc-N	Nv
ina	ina	i-S	Spp-s
threo	threo	treo-N	Ncmsc
,	,	,-F	Fi
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
,	,	,-F	Fi
Brian	Brian	Brian-N	Ncmsc|Npmsc
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
ndóigh	ndóigh	dóigh-N	Ncfsc
bhí	bhí	bí-V	Vmis
,	,	,-F	Fi
mar	mar	mar-C	Cs
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
a	a	a-Q	Q-r
dhath	dhath	dath-V	Vmis
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
a	a	a-Q	Q-r
scríobhfadh	scríobhfadh	scríobh-V	Vmc
an	an	an-T	Td-s
múinteoir	múinteoir	múinteoir-N	Ncmsc
a	a	a-U	U
chailleadh	chailleadh	caill-N	Nv
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhuail	bhuail	buail-V	Vmis
an	an	an-T	Td-s
cloigín	cloigín	cloigín-N	Ncmsc
rith	rith	rith-N	Ncmsc
na	na	na-T	Td-p
scoláirí	scoláirí	scoláire-N	Ncmpg
amach	amach	amach-R	Rd
chomh	chomh	chomh-R	Ri
tiubh	tiubh	tiubh-A	Aqp
géar	géar	géar-A	Aqp
agus	agus	agus-C	Cc
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
leo	leo	le-P	Pr3-p
ach	ach	ach-C	Cs
lean	lean	lean-V	Vmis
Brian	Brian	Brian-N	Ncmsc|Npmsc
air	air	ar-P	Pr3ms
ag	ag	ag-S	Sp
críochnú	críochnú	críochnaigh-N	Nv
a	a	a-D	Dp3
nótaí	nótaí	nóta-N	Ncmpc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
fágtha	fágtha	fág-A	Av
ach	ach	ach-S	Sp|Cs
é	é	é-P	Pp3ms
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
an	an	an-T	Td-s
múinteoir	múinteoir	múinteoir-N	Ncmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
tí	tí	tí-N	Ncfsc
imeacht	imeacht	imigh-N	Ncmsc|Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bomaite	Bomaite	bomaite-N	Ncmsc
beag	beag	beag-A	Aq-msc
amháin	amháin	amháin-A	Aqp
,	,	,-F	Fi
a	a	a-U	Uv|Dp3
mhic	mhic	mac-N	Ncmsv
Uí	Uí	Uí-U	Up
Bhuachalla	Bhuachalla	Buachalla-N	Npfsg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
múinteoir	múinteoir	múinteoir-N	Ncmsc
,	,	,-F	Fi
‘	‘	‘-X	Xx
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ar	ar	ar-S	Sp
bun	bun	bun-N	Ncmsc
agatsa	agatsa	ag-P	Pr2-s-e
i rith	i rith	i_rith-S	Spc
an	an	an-T	Td-s
ranga	ranga	rang-N	Ncmsg
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Bhí	Bhí	bí-V	Vmis
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
éisteacht	éisteacht	éist-N	Nv
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
scríobh	scríobh	scríobh-N	Nv
,	,	,-F	Fi
sin	sin	sin-P	Pd|W
an	an	an-T	Td-s
méid	méid	méid-N	Ncmsg|Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhreagair	fhreagair	freagair-V	Vmis
Brian	Brian	Brian-N	Ncmsc|Npmsc
.	.	.-F	Fe
Shiúil	Shiúil	siúil-V	Vmis
an	an	an-T	Td-s
múinteoir	múinteoir	múinteoir-N	Ncmsc
síos	síos	síos-R	Rd
a	a	a-D	Dp3
fhad	fhad	fad-N	Ncmsc
leis	leis	le-P	Pr3ms
agus	agus	agus-C	Cc
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
ach	ach	ach-S	Sp
ainm	ainm	ainm-N	Ncmsc
Bhriain	Bhriain	Brian-N	Npfsg|Ncmsg
scríofa	scríofa	scríobh-A	Av
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhinse	bhinse	binse-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Chonaic	Chonaic	feic-V	Vmis
mé	mé	mé-P	Pp1-s
do	do	do-S	Sp
leithéidse	leithéidse	leithéid-N	Ncfsc-e
roimhe	roimhe	roimh-P	Pr3ms
.	.	.-F	Fe
Chomh	Chomh	chomh-R	Ri
ciúin	ciúin	ciúin-A	Aqp
sin	sin	sin-P	Pd|W|Dd
nach	nach	nach-Q	Qnr
leáfadh	leáfadh	leáigh-V	Vmc----n
im	im	i-D	Dp1-s
i	i	i-S	Sp
do	do	do-D	Dp2-s
bhéal	bhéal	béal-N	Ncmsc
ach	ach	ach-S	Sp|Cs
ag	ag	ag-S	Sp
briseadh	briseadh	bris-N	Nv
rialacha	rialacha	riail-N	Ncfpg
an	an	an-T	Td-s
choláiste	choláiste	coláiste-N	Ncmsg
i rith	i rith	i_rith-S	Spc
an	an	an-T	Td-s
ama	ama	ama-N	Ncmsg
.	.	.-F	Fe
Is	Is	is-W	Wp-i
ea	ea	ea-P	Pp3-s
,	,	,-F	Fi
chuala	chuala	clois-V	Vmis
mé	mé	mé-P	Pp1-s
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
labhairt	labhairt	labhair-N	Nv
Béarla	Béarla	béarla-N	Ncmsg
ag	ag	ag-S	Sp
an	an	an-T	Td-s
chéilí	chéilí	céilí-N	Ncmsg
aréir	aréir	aréir-A	Aqp
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
amharc	amharc	amharc-N	Ncmsc|Nv
a	a	a-Q	Q-i
bhfuil	bhfuil	bí-V	Vmip---d
déanta	déanta	déan-A	Av
agat	agat	ag-P	Pr2-s
anois	anois	anois-R	Rt
!	!	!-F	Fe
Cluinfidh	Cluinfidh	cluin-V	Vmif
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
faoi	faoi	faoi-S	Sp
dtaobh	dtaobh	taobh-N	Ncmsc
de	de	de-S	Sp
seo	seo	seo-P	Pd
.	.	.-F	Fe
Beidh	Beidh	bí-V	Vmif
daor	daor	daor-N	Ncmsc
ort	ort	ar-P	Pr2-s
as	as	as-S	Sp
damáiste	damáiste	damáiste-N	Ncmsc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
do	do	do-S	Sp
throscán	throscán	troscán-N	Ncmsc
an	an	an-T	Td-s
choláiste	choláiste	coláiste-N	Ncmsg
.	.	.-F	Fe
’	’	’-F	Fa
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
,	,	,-F	Fi
chuir	chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
cheann	cheann	ceann-N	Ncmsc
amach	amach	amach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
agus	agus	agus-C	Cc
ghlaoigh	ghlaoigh	glaoigh-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
phríomhoide	phríomhoide	príomhoide-N	Ncmsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ar	ar	ar-S	Sp
dualgas	dualgas	dualgas-N	Ncmsc
sosa	sosa	sos-N	Ncmsg
sa	sa	i-S	Spa-s
dorchla	dorchla	dorchla-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cad	Cad	cad-W	W--q
é	é	é-P	Pp3ms
a	a	a-Q	Q-r
rinne	rinne	déan-V	Vmis
sé	sé	sé-P	Pp3msn
?	?	?-F	Fq
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
i ndiaidh	i ndiaidh	i_ndiaidh-S	Spc
dó	dó	do-P	Pr3ms
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
leis	leis	le-S	Sp
an	an	an-T	Td-s
mhúinteoir	mhúinteoir	múinteoir-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
,	,	,-F	Fi
a	a	a-U	Uv|Dp3
ainm	ainm	ainm-N	Ncmsc|Ncmsv
a	a	a-Q	Q-r
scríobh	scríobh	scríobh-V	Vmis
ar	ar	ar-S	Sp
cheann	cheann	ceann-N	Ncmsc
de	de	de-S	Sp
na	na	na-T	Td-p
suíocháin	suíocháin	suíochán-N	Ncmpc
sa	sa	i-S	Spa-s
seomra	seomra	seomra-N	Ncmsc
ranga	ranga	rang-N	Ncmsg
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
an	an	an-Q	Qq
bhfaca	bhfaca	feic-V	Vmis---d
tú	tú	tú-P	Pp2-s
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
gabháil	gabháil	gabh-N	Nv
dó	dó	do-P	Pr3ms
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
,	,	,-F	Fi
ach	ach	ach-S	Sp
ainm	ainm	ainm-N	Ncmsc
seo	seo	seo-P	Pd|Dd
aige	aige	ag-P	Pr3ms
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
scríofa	scríofa	scríobh-A	Av
agus	agus	agus-C	Cc
chuala	chuala	clois-V	Vmis
mé	mé	mé-P	Pp1-s
scríobadh	scríobadh	scríob-V	Vmis0
le	le	le-S	Sp
mo	mo	mo-D	Dp1-s
dhá	dhá	dó-M	Mc
chluas	chluas	cluas-N	Ncfsc
!	!	!-F	Fe
’	’	’-F	Fa
Rinneadh	Rinneadh	déan-V	Vmis0
staic	staic	staic-N	Ncfsc
de	de	de-S	Sp
Bhrian	Bhrian	Brian-N	Ncmsc|Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
aghaidh	aghaidh	aghaidh-N	Ncfsc
lasta	lasta	las-A	Aqp|Av
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
eagla	eagla	eagla-N	Ncfsc
air	air	ar-P	Pr3ms
go	go	go-Q	Q
mbrisfeadh	mbrisfeadh	bris-V	Vmc
a	a	a-U	U
ghol	ghol	goil-N	Nv
air	air	ar-N	Ncmsg|Pr3ms|Ncmsg
dá	dá	de-S	Spp-s
n	n	n-X	Xl
‑	‑	‑-F	Fb
osclódh	osclódh	oscail-V	Vmc
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
bhéal	bhéal	béal-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
iontas	iontas	iontas-N	Ncmsc
orm	orm	ar-P	Pr1-s
faoi	faoi	faoi-S	Sp
seo	seo	seo-P	Pd
,	,	,-F	Fi
a	a	a-U	Uv
Bhriain	Bhriain	Brian-N	Ncmsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
scríobhfá	scríobhfá	scríobh-V	Vmc-2s
ar	ar	ar-S	Sp
an	an	an-T	Td-s
troscán	troscán	troscán-N	Ncmsc
sa	sa	i-S	Spa-s
bhaile	bhaile	baile-N	Ncmsc
?	?	?-F	Fq
’	’	’-F	Fa
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
scríobhfainn	scríobhfainn	scríobh-V	Vmc-1s-n
,	,	,-F	Fi
a	a	a-U	Uv
mháistir	mháistir	máistir-N	Ncmsv
,	,	,-F	Fi
agus	agus	agus-C	Cc
níor	níor	níor-W	Ws-in|Qn-s
scríobh	scríobh	scríobh-N	Ncmsc|Nv|Ncmsc|Nv|Vmis|Vmis---n
mé	mé	mé-P	Pp1-s
ar	ar	ar-S	Sp
an	an	an-T	Td-s
troscán	troscán	troscán-N	Ncmsc
anseo	anseo	anseo-R	Rl
ach	ach	ach-S	Sp
oiread	oiread	oiread-N	Ns-s
.	.	.-F	Fe
’	’	’-F	Fa
‘	‘	‘-X	Xx
Taispeáin	Taispeáin	taispeáin-V	Vmm-2s
an	an	an-T	Td-s
damáiste	damáiste	damáiste-N	Ncmsc
dom	dom	do-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhi	Bhi	Bhi-N	Npmsc
brian	brian	brian-N	Ncmsc
O	O	O-U	Up
’	’	’-F	Fa
BUAKLA	BUAKLA	BUAKLA-N	Nc
aNSeo	aNSeo	aNSeo-N	Nc
’	’	’-F	Fa
na	na	na-T	Td-p
focail	focail	focal-N	Ncmpc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
scríofa	scríofa	scríobh-A	Av
.	.	.-F	Fe
Thóg	Thóg	tóg-V	Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
cóipleabhar	cóipleabhar	cóipleabhar-N	Ncmpg|Ncmsc
Bhriain	Bhriain	Brian-N	Npfsg|Ncmsg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
ainm	ainm	ainm-N	Ncmsc
agus	agus	agus-C	Cc
ar	ar	ar-S	Sp
na	na	na-T	Td-p
nótaí	nótaí	nóta-N	Ncmpc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
scríofa	scríofa	scríobh-A	Av
ag	ag	ag-S	Sp
Brian	Brian	Brian-N	Ncmsc|Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cibé	Cibé	cibé-P	Pi|Dq
duine	duine	duine-N	Ncmsc
a	a	a-U	U
scríobh	scríobh	scríobh-N	Nv
seo	seo	seo-P	Pd|Dd
,	,	,-F	Fi
ní	ní	is-W	Wp-in
hé	hé	é-P	Pp3ms
an	an	an-T	Td-s
gasúr	gasúr	gasúr-N	Ncmsc
seo	seo	seo-D	Dd
a	a	a-Q	Q-r
rinne	rinne	déan-V	Vmis
é	é	é-P	Pp3ms
,	,	,-F	Fi
ar	ar	ar-S	Sp
scor	scor	scoir-N	Nv
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
.	.	.-F	Fe
Amharc	Amharc	amharc-N	Ncmsc
,	,	,-F	Fi
a	a	a-U	Uv
mháistir	mháistir	máistir-N	Ncmsv
,	,	,-F	Fi
tá	tá	bí-V	Vmip
gach	gach	gach-D	Dq
rud	rud	rud-N	Ncmsc
sa	sa	i-S	Spa-s
chóipleabhar	chóipleabhar	cóipleabhar-N	Ncmsc
litrithe	litrithe	litrigh-A	Av
go	go	go-U	Ua
foirfe	foirfe	foirfe-A	Aqp
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Caithfimid	Caithfimid	caith-V	Vmif1p
a	a	a-U	U
bheith	bheith	bí-N	Nv
cúramach	cúramach	cúramach-A	Aqp
sula	sula	sula-C	Cs
gcuirimid	gcuirimid	cuir-V	Vmip1p
rudaí	rudaí	rud-N	Ncmpc
i	i	i-S	Sp
leith	leith	leith-N	Ncfsc
daoine	daoine	duine-N	Ncmpg
.	.	.-F	Fe
’	’	’-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
amharc	amharc	amharc-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
Bhrian	Bhrian	Brian-N	Ncmsc|Npmsc
agus	agus	agus-C	Cc
chaoch	chaoch	caoch-V	Vmis
sé	sé	sé-P	Pp3msn
súil	súil	súil-N	Ncfsc|Nv-----n
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
Brídín	Brídín	Brídín-N	Npfsc
mórán	mórán	mórán-N	Ncmsc
eile	eile	eile-D	Dd
den	den	de-S	Spa-s
luchóg	luchóg	luchóg-N	Ncfsc
an	an	an-T	Td-s
chuid	chuid	cuid-N	Ncfsc
eile	eile	eile-D	Dd
den	den	de-S	Spa-s
tseachtain	tseachtain	seachtain-N	Ncfsc
sin	sin	sin-D	Dd
mar	mar	mar-C	Cs
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
cúrsa	cúrsa	cúrsa-N	Ncmsc
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
chun	chun	chun-S	Sp
deiridh	deiridh	deireadh-N	Ncmsg
agus	agus	agus-C	Cc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
gnóthach	gnóthach	gnóthach-A	Aqp
ag	ag	ag-S	Sp
cuidiú	cuidiú	cuidigh-N	Nv
lena	lena	le-S	Spp-p|Spp-s
Mamaí	Mamaí	mamaí-N	Ncmpc|Ncfsc|Ncmpc|Ncfsc
ag	ag	ag-S	Sp
déanamh	déanamh	déanamh-N	Ncmsc
réidh	réidh	réidh-A	Aq-msc
don	don	do-S	Spa-s
chéad	chéad	céad-M	Mo
chúrsa	chúrsa	cúrsa-N	Ncmsg|Ncmsc
eile	eile	eile-D	Dd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
na	na	na-T	Td-p
scoláirí	scoláirí	scoláire-N	Ncmpc
gnóthach	gnóthach	gnóthach-A	Aq--pg
fosta	fosta	fosta-A	Aqp
mar	mar	mar-C	Cs
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
coirm	coirm	coirm-N	Ncfsc
cheoil	cheoil	ceol-N	Nv--g--n|Ncmsg
le	le	le-S	Sp
bheith	bheith	bí-N	Nv
acu	acu	ag-P	Pr3-p
an	an	an-T	Td-s
oíche	oíche	oíche-N	Ncfsc
roimh	roimh	roimh-S	Sp
an	an	an-T	Td-s
Chéilí	Chéilí	céilí-N	Ncmsg
Mhór	Mhór	mór-A	Aq-msc
agus	agus	agus-C	Cc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
cleachtadh	cleachtadh	cleacht-N	Nv
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
agus	agus	agus-C	Cc
amhrán	amhrán	amhrán-N	Ncmpg
agus	agus	agus-C	Cc
drámaí	drámaí	dráma-N	Ncmpc
beaga	beaga	beag-A	Aq--pg|Aq--pc|Aq--pv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
na	na	na-T	Td-p
duaiseanna	duaiseanna	duais-N	Ncfpc
le	le	le-S	Sp
bronnadh	bronnadh	bronn-N	Nv
ag	ag	ag-S	Sp
an	an	an-T	Td-s
choirm	choirm	coirm-N	Ncfsc
cheoil	cheoil	ceol-N	Nv--g--n|Ncmsg
fosta	fosta	fosta-A	Aqp|Rg
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
na	na	na-T	Td-p
scoláirí	scoláirí	scoláire-N	Ncmpc
uilig	uilig	uile-D	Dq
ag	ag	ag-S	Sp
dúil	dúil	dúil-N	Ncfsc
go	go	go-U	Ua
mór	mór	mór-A	Aqp
leis	leis	le-S	Sp
sin	sin	sin-P	Pd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
lánscoláireacht	lánscoláireacht	scoláireacht-N	Ncfsc
mar	mar	mar-S	Sp
dhuais	dhuais	duais-N	Ncfsc
don	don	do-S	Spa-s
duine	duine	duine-N	Ncmsc
is	is	is-U	U
mó	mó	mór-A	Aqc
a	a	a-Q	Q-r
ghlac	ghlac	glac-V	Vmis
páirt	páirt	páirt-N	Ncfsc
i	i	i-S	Sp
saol	saol	saol-N	Ncmsc
an	an	an-T	Td-s
choláiste	choláiste	coláiste-N	Ncmsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
scoláirí	scoláirí	scoláire-N	Ncmpc
tigh	tigh	teach-N	Ncmsd
Bhrídín	Bhrídín	Brídín-N	Npf-g
lánchinnte	lánchinnte	lánchinnte-A	Aqp
de	de	de-P	Pr3ms
go	go	go-Q	Q
bhfaigheadh	bhfaigheadh	faigh-V	Vmc----d|Vmih
duine	duine	duine-N	Ncmsc
acu	acu	ag-P	Pr3-p
féin	féin	féin-P	Px
an	an	an-T	Td-s
duais	duais	duais-N	Ncfsc
.	.	.-F	Fe
Nárbh	Nárbh	is-W	Wssin
iadsan	iadsan	iad-P	Pp3-p-e
an	an	an-T	Td-s
dream	dream	dream-N	Ncmsc
ba	ba	is-U	U
mhó	mhó	mór-A	Aqc
craic	craic	craic-N	Ncfsc
agus	agus	agus-C	Cc
cuideachta	cuideachta	cuideachta-N	Ncfsg|Ncfsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
!	!	!-F	Fe
Oíche	Oíche	oíche-N	Ncfsc
na	na	na-T	Tdfsg
coirme	coirme	coirm-N	Ncfsg
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
bhí	bhí	bí-V	Vmis
cuid	cuid	cuid-N	Ncfsc
de	de	de-S	Sp
na	na	na-T	Td-p
míreanna	míreanna	mír-N	Ncfpg
sultmhar	sultmhar	sultmhar-A	Aq--pg
go leor	go leor	go_leor-A	Aq
.	.	.-F	Fe
Cuid	Cuid	cuid-N	Ncfsc
eile	eile	eile-D	Dd
acu	acu	ag-P	Pr3-p
,	,	,-F	Fi
áfach	áfach	áfach-R	Rg
,	,	,-F	Fi
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
siad	siad	siad-P	Pp3-pn
thar	thar	thar-S	Sp
mholadh	mholadh	moladh-N	Ncmsc
beirte	beirte	beirt-N	Ncfsg
.	.	.-F	Fe
Faoi	Faoi	faoi-S	Sp
dheireadh	dheireadh	deireadh-N	Ncmsc
tháinig	tháinig	tar-V	Vmis
am	am	am-N	Ncmsc
bronnta	bronnta	bronn-A	Av
na	na	na-T	Td-p
nduaiseanna	nduaiseanna	duais-N	Ncfpg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
ciúnas	ciúnas	ciúnas-N	Ncmsc
sa	sa	i-S	Spa-s
halla	halla	halla-N	Ncmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
shiúil	shiúil	siúil-V	Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
amach	amach	amach-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
ardán	ardán	ardán-N	Ncmsc
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
faoin	faoin	faoi-S	Spa-s
tábhacht	tábhacht	tábhacht-N	Ncfsc
a	a	a-Q	Q-r
bhain	bhain	bain-V	Vmis
le	le	le-S	Sp
bheith	bheith	bí-N	Nv
páirteach	páirteach	páirteach-A	Aqp
in	in	i-S	Sp
imeachtaí	imeachtaí	imeacht-N	Ncmsc|Ncmpc
uile	uile	uile-N	Ns-s|Dq
an	an	an-T	Td-s
choláiste	choláiste	coláiste-N	Ncmsg
,	,	,-F	Fi
idir	idir	idir-S	Sp
spórt	spórt	spórt-N	Ncmsc
,	,	,-F	Fi
spraoi	spraoi	spraoi-N	Ncmsc|Nv-----n
agus	agus	agus-C	Cc
ranganna	ranganna	rang-N	Ncmpg|Ncmpc|Ncmpg
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
d	d	d-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmis
sé	sé	sé-P	Pp3msn
clúdach	clúdach	clúdach-N	Ncmsc
litreach	litreach	litreach-A	Aq-msc
.	.	.-F	Fe
Léigh	Léigh	léigh-V	Vmis
sé	sé	sé-P	Pp3msn
amach	amach	amach-R	Rd
ainm	ainm	ainm-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
é	é	é-P	Pp3ms
scoláire	scoláire	scoláire-N	Ncmsc
an	an	an-T	Td-s
chúrsa	chúrsa	cúrsa-N	Ncmsg
i	i	i-S	Sp
mbliana	mbliana	bliain-N	Ncfpc
ná	ná	ná-C	Cs|Cc
…	…	…-F	Fi
’	’	’-F	Fa
Tost	Tost	tost-V	Vmm-2s|Nv|Ncmsc
iomlán	iomlán	iomlán-N	Ncmpg|Aq-msc|Ncmsc|Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
…	…	…-F	Fi
Cillian	Cillian	Cillian-N	Npmsc
de	de	de-U	Up
Búrca	Búrca	Búrca-N	Npmsc
!	!	!-F	Fe
’	’	’-F	Fa
Lig	Lig	lig-V	Vmis|Vmm-2s
buachaillí	buachaillí	buachaill-N	Ncmpc
Bhaile	Bhaile	Baile-N	Npmsg
Átha Cliath	Átha Cliath	Átha_Cliath-N	Npmsc
liú	liú	liú-N	Ncmsc
millteanach	millteanach	millteanach-A	Aq-msc
áthais	áthais	áthas-N	Ncmsg|Ncmpc
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
béicíl	béicíl	béicíl-N	Nv-----n
‘	‘	‘-X	Xx
Cillian	Cillian	Cillian-N	Npmsc
!	!	!-F	Fe
Cillian	Cillian	Cillian-N	Npmsc
!	!	!-F	Fe
Cillian	Cillian	Cillian-N	Npmsc
!	!	!-F	Fe
’	’	’-F	Fa
Rogha	Rogha	rogha-N	Ncfsc
na	na	na-T	Tdfsg
coitiantachta	coitiantachta	coitiantacht-N	Ncfsg
,	,	,-F	Fi
gan	gan	gan-S	Sp
amhras	amhras	amhras-N	Ncmsc
ar	ar	is-W	Wssi|Wpdi|Wpsi
bith	bith	bith-N	Ncmsc|Ns-s
.	.	.-F	Fe
I	I	i-S	Sp
ndiaidh	ndiaidh	diaidh-N	Ns-s
tamaillín	tamaillín	tamall-N	Ncmsc|Ncmpc
shíothlaigh	shíothlaigh	síothlaigh-V	Vmis
an	an	an-T	Td-s
gleo	gleo	gleo-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ciúnas	Ciúnas	ciúnas-N	Ncmsc
anois	anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
príomhoide	príomhoide	príomhoide-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
duais	duais	duais-N	Ncfsc
speisialta	speisialta	speisialta-A	Aqp
le	le	le-S	Sp
tabhairt	tabhairt	tabhair-N	Nv
agam	agam	ag-P	Pr1-s
i	i	i-S	Sp
mbliana	mbliana	bliain-N	Ncfpc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
chúrsa	chúrsa	cúrsa-N	Ncmsg
seo	seo	seo-D	Dd
,	,	,-F	Fi
mar	mar	mar-C	Cs
atá	atá	bí-V	Vmip---r
bonn	bonn	bonn-N	Ncmsc
agus	agus	agus-C	Cc
scoláireacht	scoláireacht	scoláireacht-N	Ncfsc
don	don	do-S	Spa-s
scoláire	scoláire	scoláire-N	Ncmsc
is	is	is-U	U
fearr	fearr	maith-A	Aqc
ó	ó	ó-S	Sp
thaobh	thaobh	taobh-N	Ncmsc
labhairt	labhairt	labhairt-N	Ncfsc
na	na	na-T	Tdfsg
Gaeilge	Gaeilge	Gaeilge-N	Npfsg
de	de	de-P	Pr3ms
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
duais	duais	duais-N	Ncfsc
seo	seo	seo-D	Dd
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
…	…	…-F	Fi
do	do	do-S	Sp
Bhrian	Bhrian	Brian-N	Ncmsc|Npmsc
Ó	Ó	Ó-U	Up
Buachalla	Buachalla	Buachalla-N	Npmsc
!	!	!-F	Fe
’	’	’-F	Fa
Bhí	Bhí	bí-V	Vmis
bualadh	bualadh	bualadh-N	Ncmsc
bos	bos	bos-N	Ncfpg|Ncfsc
chomh	chomh	chomh-R	Ri
mór	mór	mór-A	Aqp
sin	sin	sin-P	Pd|W|Dd
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
shiúil	shiúil	siúil-V	Vmis
Brian	Brian	Brian-N	Ncmsc|Npmsc
suas	suas	suas-R	Rd
leis	leis	le-S	Sp
an	an	an-T	Td-s
duais	duais	duais-N	Ncfsc
a	a	a-U	U
thógáil	thógáil	tóg-N	Nv
,	,	,-F	Fi
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
eagla	eagla	eagla-N	Ncfsc
ar	ar	ar-S	Sp
Bhrídín	Bhrídín	Brídín-N	Npfsc
go	go	go-Q	Q
dtógfaí	dtógfaí	tóg-V	Vmc-0
an	an	an-T	Td-s
díon	díon	díon-N	Ncmsc
den	den	de-S	Spa-s
choláiste	choláiste	coláiste-N	Ncmsc
.	.	.-F	Fe
Mhothaigh	Mhothaigh	mothaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
féin	féin	féin-P	Px
deora	deora	deora-N	Ncfpc|Ncfsc
ag	ag	ag-S	Sp
éirí	éirí	éirigh-N	Nv
ina	ina	i-S	Spp-p|Spp-s
súile	súile	súil-N	Ncfpc
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
ach	ach	ach-C	Cs
thuig	thuig	tuig-V	Vmis
sí	sí	sí-P	Pp3fsn
gur	gur	is-W	Wsdi
deora	deora	deora-N	Ncfpc|Ncfsc
sonais	sonais	sonas-N	Ncmsg|Ncmpc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
iontu	iontu	i-P	Pr3-p
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
aitheantas	aitheantas	aitheantas-N	Ncmsc
mar	mar	mar-C	Cs
is	is	is-W	Wpri
ceart	ceart	ceart-A	Aqp
faighte	faighte	faigh-A	Av
ag	ag	ag-S	Sp
a	a	a-D	Dp3
cara	cara	cara-N	Ncmsc
sa	sa	i-S	Spa-s
deireadh	deireadh	deireadh-N	Ncmsc
.	.	.-F	Fe
