Na	Na	na-T	Td-p
Laethanta	Laethanta	lá-N	Ncmpc
Órga	Órga	órga-A	Aqp
Ar	Ar	ar-Q	Qq-s
thug	thug	tabhair-V	Vmis
tú	tú	tú-P	Pp2-s
faoi	faoi	faoi-S	Sp
deara	deara	deara-N	Ns-s
go	go	go-Q	Q
mbíonn	mbíonn	bí-V	Vmig
aimsir	aimsir	aimsir-N	Ncfsc
dheas	dheas	deas-A	Aq-fsc
chiúin	chiúin	ciúin-A	Aq-fsc
ann	ann	i-R	Rl|Pr3ms
roimh	roimh	roimh-S	Sp
an	an	an-T	Td-s
Nollaig	Nollaig	Nollaig-N	Ncfsc
?	?	?-F	Fq
Ag	Ag	ag-S	Sp
an	an	an-T	Td-s
tráth	tráth	tráth-N	Ncmsc
sin	sin	sin-D	Dd
bliana	bliana	bliain-N	Ncfpc
,	,	,-F	Fi
sula	sula	sula-C	Cs
dtosaíonn	dtosaíonn	tosaigh-V	Vmip
ghrian	ghrian	grian-V	Vmis
ag	ag	ag-S	Sp
casadh	casadh	cas-N	Nv
ar ais	ar ais	ar_ais-R	Rd
arís	arís	arís-R	Rg
agus	agus	agus-C	Cc
sula	sula	sula-C	Cs
dtosaíonn	dtosaíonn	tosaigh-V	Vmip
fad	fad	fad-C	Cs|Ncmsc
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
,	,	,-F	Fi
bíonn	bíonn	bí-V	Vmig
an	an	an-T	Td-s
aimsir	aimsir	aimsir-N	Ncfsc
geal	geal	geal-A	Aqp
agus	agus	agus-C	Cc
go	go	go-U	Ua
breá	breá	breá-A	Aqp
uaireanta	uaireanta	uaireanta-N	Ncfpg|Ncfpc|Rg
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
an	an	an-T	Td-s
fharraige	fharraige	farraige-N	Ncfsc
ina	ina	i-S	Spp-s
gloine	gloine	gloine-N	Ncfsc
,	,	,-F	Fi
agus	agus	agus-C	Cc
bádóirí	bádóirí	bádóir-N	Ncmpg|Ncmpc
agus	agus	agus-C	Cc
iascairí	iascairí	iascaire-N	Ncmpg|Ncmpc
in ann	in ann	in_ann-S	Spc
dul	dul	téigh-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhfarraige	bhfarraige	farraige-N	Ncfsc
gan	gan	gan-S	Sp
fuacht	fuacht	fuacht-N	Ncmsc
gan	gan	gan-S	Sp
faitíos	faitíos	faitíos-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cén	Cén	cé-D	Dw--s
fáth	fáth	fáth-N	Ncmsc
é	é	é-P	Pp3ms
sin	sin	sin-W	W
?	?	?-F	Fq
'	'	'-F	Fa
a	a	a-Q	Q-r
deir	deir	abair-V	Vmip
tú	tú	tú-P	Pp2-s
.	.	.-F	Fe
Bhuel	Bhuel	bhuel-X	Xsc
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
cailín	cailín	cailín-N	Ncmsc
ann	ann	i-P	Pr3ms
fadó	fadó	fadó-R	Rg
agus	agus	agus-C	Cc
Ailcín	Ailcín	ailcín-N	Ncfsc
t	t	t-X	Xl
‑	‑	‑-F	Fb
ainm	ainm	ainm-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
B	B	B-X	Xl
’	’	’-F	Fa
iníon	iníon	iníon-N	Ncfsc
le	le	le-S	Sp
hAeólas	hAeólas	hAeólas-N	Nc
í	í	í-P	Pp3fs
agus	agus	agus-C	Cc
ba	ba	is-W	Wsri
é	é	é-P	Pp3ms
Aeólas	Aeólas	Aeólas-N	Npmsc
a	a	a-Q	Q-r
bhíodh	bhíodh	bí-V	Vmih
ag	ag	ag-S	Sp
faire	faire	fair-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
ngaoth	ngaoth	gaoth-N	Ncmsc|Ncfsc
.	.	.-F	Fe
Dia	Dia	dia-N	Ncmsc
na	na	na-T	Td-p
Gaoithe	Gaoithe	Gaoithe-N	Npmsg
a	a	a-Q	Q-r
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Na	Na	na-T	Td-p
Laethanta	Laethanta	lá-N	Ncmpc
Órga	Órga	órga-A	Aqp
Máire	Máire	Máire-N	Npf-g|Npfsc
Ní	Ní	Ní-U	Up
Chualáin	Chualáin	Chualáin-N	Npmsc
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Ailcín	Ailcín	ailcín-N	Ncfsc
ina	ina	i-S	Spp-s
gearrchaile	gearrchaile	gearrchaile-N	Ncmsc
thit	thit	tit-V	Vmis
sí	sí	sí-P	Pp3fsn
i	i	i-S	Sp
ngrá	ngrá	grá-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
rí	rí	rí-N	Ncmsc
Céacs	Céacs	Céacs-N	Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
mór	mór	mór-A	Aqp
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
ar feadh	ar feadh	ar_feadh-S	Spc
bliain	bliain	bliain-N	Ncfsc
nó	nó	nó-C	Cc
dhó	dhó	dó-M	Mc
agus	agus	agus-C	Cc
ansin	ansin	ansin-R	Rt|Rl
phós	phós	pós-V	Vmis
siad	siad	siad-P	Pp3-pn
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
sona	sona	sona-A	Aqp
sásta	sásta	sásta-A	Aqp
ar feadh	ar feadh	ar_feadh-S	Spc
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
.	.	.-F	Fe
Théadh	Théadh	téigh-V	Vmih
siad	siad	siad-P	Pp3-pn
chuile	chuile	cuile-N	Ncfsc
áit	áit	áit-N	Ncfsc
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
agus	agus	agus-C	Cc
bhíodh	bhíodh	bí-V	Vmih
‑	‑	‑-F	Fb
spraoi	spraoi	spraoi-N	Ncmsc|Nv-----n
agus	agus	agus-C	Cc
spórt	spórt	spórt-N	Ncmpg|Ncmsc|Ncmpg
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Lá	Lá	lá-N	Ncmsc
amháin	amháin	amháin-A	Aqp
dúirt	dúirt	abair-V	Vmis
Céacs	Céacs	Céacs-N	Npmsc
le	le	le-S	Sp
hAilcín	hAilcín	ailcín-N	Ncfsc
go	go	go-Q	Q
gcaithfeadh	gcaithfeadh	caith-V	Vmc
sé	sé	sé-P	Pp3msn
dul	dul	téigh-N	Ncmsc|Nv
ar	ar	ar-S	Sp
aistear	aistear	aistear-N	Ncmsc
agus	agus	agus-C	Cc
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
sé	sé	sé-P	Pp3msn
imithe	imithe	imigh-A	Av
ar feadh	ar feadh	ar_feadh-S	Spc
scaithimh	scaithimh	scaitheamh-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
orm	orm	ar-P	Pr1-s
imeacht	imeacht	imeacht-N	Ncmsc
go	go	go-U	Ua
gairid	gairid	gairid-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
dul	dul	téigh-N	Ncmsc|Nv
ar	ar	ar-S	Sp
thuras	thuras	turas-N	Ncmsc
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
ó	ó	ó-S	Sp
bhaile	bhaile	baile-N	Ncmsc
.	.	.-F	Fe
Beidh	Beidh	bí-V	Vmif
mé	mé	mé-P	Pp1-s
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhfarraige	bhfarraige	farraige-N	Ncfsc
ar feadh	ar feadh	ar_feadh-S	Spc
cúpla	cúpla	cúpla-N	Ncmsg
seachtain	seachtain	seachtain-N	Ncfsc
,	,	,-F	Fi
ach	ach	ach-C	Cs
tiocfaidh	tiocfaidh	tar-V	Vmif
mé	mé	mé-P	Pp1-s
ar ais	ar ais	ar_ais-R	Rd
chomh	chomh	chomh-R	Ri
sciobtha	sciobtha	sciobtha-A	Aqp
agus	agus	agus-C	Cc
is	is	is-W	Wpri
féidir	féidir	féidir-N	Ns-s
liom	liom	le-P	Pr1-s
.	.	.-F	Fe
'	'	'-F	Fa
Níor	Níor	níor-Q	Qn-s
thaitin	thaitin	taitin-V	Vmis---n
an	an	an-T	Td-s
chaint	chaint	caint-N	Ncfsc
seo	seo	seo-D	Dd
le	le	le-S	Sp
hAilcín	hAilcín	ailcín-N	Ncfsc
ar	ar	ar-S	Sp
chor	chor	cor-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
.	.	.-F	Fe
Shocraigh	Shocraigh	socraigh-V	Vmis
sí	sí	sí-P	Pp3fsn
labhairt	labhairt	labhair-N	Ncfsc|Nv
lena	lena	le-S	Spp-s
hathair	hathair	athair-N	Ncmsc
faoin	faoin	faoi-S	Spa-s
scéal	scéal	scéal-N	Ncmsc
mar	mar	mar-C	Cs
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
imní	imní	imní-N	Ncfsc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
gach	gach	gach-D	Dq
eolas	eolas	eolas-N	Ncmsc
ag	ag	ag-S	Sp
Aeólas	Aeólas	Aeólas-N	Npmsc
faoin	faoin	faoi-S	Spa-s
aimsir	aimsir	aimsir-N	Ncfsc
,	,	,-F	Fi
ar	ar	ar-S	Sp
ndóigh	ndóigh	dóigh-N	Ncfsc
,	,	,-F	Fi
mar	mar	mar-C	Cs
gurbh	gurbh	is-W	Wsdi
é	é	é-P	Pp3ms
Dia	Dia	dia-N	Ncmsc
na	na	na-T	Td-p
Gaoithe	Gaoithe	Gaoithe-N	Npmsg
é	é	é-P	Pp3ms
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
haon	haon	aon-M	Mc
dea	dea	dea-N	Ns-s
‑	‑	‑-F	Fb
scéala	scéala	scéala-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
a	a	a-D	Dp3
hathair	hathair	athair-N	Ncmsc
di	di	do-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
drochaimsir	drochaimsir	drochaimsir-N	Ncfsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
gála	gála	gála-N	Ncmsc
agus	agus	agus-C	Cc
stoirm	stoirm	stoirm-N	Ncfsc
geallta	geallta	geall-A	Av
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
caint	caint	caint-N	Ncfsc
a	a	a-D	Dp3
hathar	hathar	athair-N	Ncmsg
scéin	scéin	scéin-N	Ncfsc
in	in	i-S	Sp
Ailcín	Ailcín	ailcín-N	Ncfsc
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
impí	impí	impigh-N	Nv
ar	ar	ar-S	Sp
Chéacs	Chéacs	céacs-N	Npmsc
gan	gan	gan-S	Sp
imeacht	imeacht	imigh-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
barúil	barúil	barúil-N	Ncfsc
mhaith	mhaith	maith-A	Aq-fsc
aici	aici	ag-P	Pr3fs
dá	dá	de-S	Spp-s
n	n	n-X	Xl
‑	‑	‑-F	Fb
imeodh	imeodh	imigh-V	Vmc
sé	sé	sé-P	Pp3msn
nach	nach	nach-Q	Qnr
dtiocfadh	dtiocfadh	tar-V	Vmc
sé	sé	sé-P	Pp3msn
slán	slán	slán-A	Aqp|Ncmsc
abhaile	abhaile	abhaile-R	Rd
go	go	go-U	Ua
brách	brách	brách-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
bíodh	bíodh	bí-V	Vmm-3s-n
faitíos	faitíos	faitíos-N	Ncmsc
ort	ort	ar-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
mé	mé	mé-P	Pp1-s
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
,	,	,-F	Fi
a	a	a-U	Uv
stóirín	stóirín	stór-N	Ncmsv
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
aireoidh	aireoidh	airigh-V	Vmif---n
tú	tú	tú-P	Pp2-s
t	t	t-X	Xl
‑	‑	‑-F	Fb
am	am	am-N	Ncmsc
ag	ag	ag-S	Sp
imeacht	imeacht	imigh-N	Nv
agus	agus	agus-C	Cc
beidh	beidh	bí-V	Vmif
mé	mé	mé-P	Pp1-s
ar ais	ar ais	ar_ais-R	Rd
go	go	go-U	Ua
luath	luath	luath-A	Aqp
agus	agus	agus-C	Cc
mé	mé	mé-P	Pp1-s
slán	slán	slán-A	Aqp|Ncmsc
sábháilte	sábháilte	sábháil-A	Aqp|Av
.	.	.-F	Fe
Beidh	Beidh	bí-V	Vmif
muid	muid	muid-P	Pp1-p
chomh	chomh	chomh-R	Ri
sásta	sásta	sásta-A	Aqp
agus	agus	agus-C	Cc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
riamh	riamh	riamh-R	Rg
.	.	.-F	Fe
Tabharfaidh	Tabharfaidh	tabhair-V	Vmif
mé	mé	mé-P	Pp1-s
chuile	chuile	cuile-N	Ncfsc
chineál	chineál	cineál-N	Ncmsc
seodra	seodra	seodra-N	Ncmsg
ar ais	ar ais	ar_ais-R	Rd
liom	liom	le-P	Pr1-s
.	.	.-F	Fe
Fan	Fan	fan-V	Vmm-2s
go	go	go-Q	Q
bhfeicfidh	bhfeicfidh	feic-V	Vmif
tú	tú	tú-P	Pp2-s
na	na	na-T	Td-p
torthaí	torthaí	toradh-N	Ncmpc
,	,	,-F	Fi
na	na	na-T	Td-p
cnónna	cnónna	cnó-N	Ncmpc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
spíosraí	spíosraí	spíosra-N	Ncmpc
áille	áille	álainn-A	Aq--pv|Aq--pc|Aq--pg|Aq--pc
a	a	a-Q	Q-r
bheas	bheas	bí-V	Vmif---r
agam	agam	ag-P	Pr1-s
duit	duit	do-P	Pr2-s
!	!	!-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
a	a	a-U	U
ghrá	ghrá	gráigh-N	Nv
geal	geal	geal-N	Ncmsc
mo	mo	mo-D	Dp1-s
chroí	chroí	croí-N	Ncmsc
,	,	,-F	Fi
tá	tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
scanraithe	scanraithe	scanraigh-A	Aqp|Av
.	.	.-F	Fe
Lig	Lig	lig-V	Vmm-2s
dom	dom	do-P	Pr1-s
dul	dul	dul-N	Ncmsc
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
leat	leat	le-P	Pr2-s
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
faitíos	faitíos	faitíos-N	Ncmsc
orm	orm	ar-P	Pr1-s
nach	nach	nach-Q	Qnr
bhfeicfidh	bhfeicfidh	feic-V	Vmif
mé	mé	mé-P	Pp1-s
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
arís	arís	arís-R	Rg
thú	thú	tú-P	Pp2-s
.	.	.-F	Fe
Céard	Céard	cé-W	W--q
a	a	a-Q	Q-r
dhéanfaidh	dhéanfaidh	déan-V	Vmif
mé	mé	mé-P	Pp1-s
má	má	má-C	Cs
tharlaíonn	tharlaíonn	tarlaigh-V	Vmip
tada	tada	tada-N	Ncmsc
duit	duit	do-P	Pr2-s
,	,	,-F	Fi
má	má	má-C	Cs
bháitear	bháitear	báigh-V	Vmip0
thú	thú	tú-P	Pp2-s
?	?	?-F	Fq
Cé	Cé	cé-P	Pq
a	a	a-Q	Q-r
bheas	bheas	bí-V	Vmif---r
anseo	anseo	anseo-R	Rl
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
liom	liom	le-P	Pr1-s
agus	agus	agus-C	Cc
tusa	tusa	tú-P	Pp2-s-e
thíos	thíos	thíos-R	Rd
ar	ar	ar-S	Sp
ghrinneall	ghrinneall	grinneall-N	Ncmsc
na	na	na-T	Tdfsg
farraige	farraige	farraige-N	Ncfsg
?	?	?-F	Fq
'	'	'-F	Fa
‘	‘	‘-X	Xx
Stop	Stop	stop-V	Vmis|Ncmsc
den	den	de-S	Spa-s
chaint	chaint	caint-N	Ncfsc
sin	sin	sin-D	Dd
,	,	,-F	Fi
a	a	a-U	Uv
Ailcín	Ailcín	ailcín-N	Ncfsv
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agat	agat	ag-P	Pr2-s
go	go	go-U	Ua
maith	maith	maith-A	Aqp
nach	nach	nach-Q	Qnr
dtarlóidh	dtarlóidh	tarlaigh-V	Vmif
aon	aon	aon-D	Dq
rud	rud	rud-N	Ncmsc
mar	mar	mar-C	Cs
sin	sin	sin-W	W
dom	dom	do-P	Pr1-s
.	.	.-F	Fe
Is	Is	is-W	Wp-i
dócha	dócha	dócha-A	Aqp|Aqc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
le	le	le-S	Sp
d	d	d-X	Xl
’	’	’-F	Fa
athair	athair	athair-N	Ncmsc
arís	arís	arís-R	Rg
!	!	!-F	Fe
Bíonn	Bíonn	bí-V	Vmig
tú	tú	tú-P	Pp2-s
ag	ag	ag-S	Sp
tabhairt	tabhairt	tabhair-N	Nv
an	an	an-T	Td-s
iomarca	iomarca	iomarca-N	Ncfsg
airde	airde	airde-N	Ncfsg
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Ná	Ná	ná-Q	Qnm
bac	bac	bac-V	Vmm-2s-n
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
an	an	an-T	Td-s
aimsir	aimsir	aimsir-N	Ncfsc
leath	leath	leath-V	Vmis
chomh	chomh	chomh-R	Ri
dona	dona	dona-A	Aqp
agus	agus	agus-C	Cc
atá	atá	bí-V	Vmip---r
sé	sé	sé-P	Pp3msn
a	a	a-U	U
rá	rá	abair-N	Nv
.	.	.-F	Fe
'	'	'-F	Fa
Thuig	Thuig	tuig-V	Vmis
Ailcín	Ailcín	ailcín-N	Ncfsc
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
mhaith	mhaith	maith-N	Ncfsc
di	di	do-P	Pr3fs
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
agus	agus	agus-C	Cc
go	go	go-Q	Q
gcaithfeadh	gcaithfeadh	caith-V	Vmc
sí	sí	sí-P	Pp3fsn
scaoileadh	scaoileadh	scaoil-V	Vmis0
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
a	a	a-D	Dp3
croí	croí	croí-N	Ncmsc
briste	briste	bris-A	Aqp|Av
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
trína	trína	trí-S	Spp-s
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Chaith	Chaith	caith-V	Vmis
siad	siad	siad-P	Pp3-pn
an	an	an-T	Td-s
chuid	chuid	cuid-N	Ncfsc
eile	eile	eile-D	Dd
de	de	de-S	Sp
na	na	na-T	Td-p
laethanta	laethanta	lá-N	Ncmpc
ag	ag	ag-S	Sp
baint	baint	bain-N	Nv
sásaimh	sásaimh	sásamh-N	Nv--g|Ncmsg
as	as	as-S	Sp
comhluadar	comhluadar	comhluadar-N	Ncmsc
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
go dtí	go dtí	go_dtí-S	Spc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
air	air	ar-P	Pr3ms
imeacht	imeacht	imeacht-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
seisean	seisean	sé-P	Pp3msne
ag	ag	ag-S	Sp
fáil	fáil	fáil-N	Ncfsc
réidh	réidh	réidh-A	Aq-fsc
dá	dá	do-S	Spp-s
aistear	aistear	aistear-N	Ncmsc
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
t	t	t-X	Xl
‑	‑	‑-F	Fb
am	am	am-N	Ncmsc
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
ag	ag	ag-S	Sp
sleamhnú	sleamhnú	sleamhnaigh-N	Nv
thart	thart	thart-R	Rd
.	.	.-F	Fe
Róluath	Róluath	luath-A	Aqp
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ar	ar	ar-S	Sp
Chéacs	Chéacs	céacs-N	Npmsc
imeacht	imeacht	imigh-N	Ncmsc|Nv
.	.	.-F	Fe
Síos	Síos	síos-R	Rd
le	le	le-S	Sp
hAilcín	hAilcín	ailcín-N	Ncfsc
chuig	chuig	chuig-S	Sp
an	an	an-T	Td-s
trá	trá	trá-N	Ncfsc
in	in	i-S	Sp
éineacht	éineacht	éineacht-N	Ns-s
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
shearbhóntaí	shearbhóntaí	searbhónta-N	Ncmpc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
chomrádaithe	chomrádaithe	comrádaí-N	Ncmpc
ag	ag	ag-S	Sp
fanacht	fanacht	fan-N	Nv
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
ghearr	ghearr	gearr-A	Aqp
gur	gur	gur-Q	Q--s
chroch	chroch	croch-V	Vmis
siad	siad	siad-P	Pp3-pn
a	a	a-D	Dp3
gcuid	gcuid	cuid-N	Ncfsc
seolta	seolta	seol-N	Ncmsg|Ncmpg|Nv--g
agus	agus	agus-C	Cc
gur	gur	gur-Q	Q--s
imigh	imigh	imigh-V	Vmis
siad	siad	siad-P	Pp3-pn
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
cuma	cuma	cuma-N	Ncfsc
thruamhéalach	thruamhéalach	truamhéalach-A	Aq-fsc
ar	ar	ar-S	Sp
Ailcín	Ailcín	ailcín-N	Ncfsc
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
croitheadh	croitheadh	croith-N	Nv
láimhe	láimhe	lámh-N	Ncfsg
ar	ar	ar-S	Sp
Chéacs	Chéacs	céacs-N	Npmsc
go	go	go-Q	Q
ndeachaigh	ndeachaigh	téigh-V	Vmis---d
an	an	an-T	Td-s
bád	bád	bád-N	Ncmsc
as	as	as-S	Sp
amharc	amharc	amharc-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhan	fhan	fan-V	Vmis
sí	sí	sí-P	Pp3fsn
ina	ina	i-S	Spp-p|Spp-s
seasamh	seasamh	seasamh-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcladach	gcladach	cladach-N	Ncmsc
ar feadh	ar feadh	ar_feadh-S	Spc
píosa	píosa	píosa-N	Ncmsg
fada	fada	fada-A	Aqp
,	,	,-F	Fi
ag	ag	ag-S	Sp
cuimhneamh	cuimhneamh	cuimhnigh-N	Nv
uirthi	uirthi	ar-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
chaoin	chaoin	caoin-V	Vmis
sí	sí	sí-P	Pp3fsn
uisce	uisce	uisce-N	Ncmsc
a	a	a-D	Dp3
cinn	cinn	ceann-N	Ncmpc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
cúpla	cúpla	cúpla-D	Dq|Ncmsc
lá	lá	lá-N	Ncmsc
maith	maith	maith-A	Aq-msc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhfarraige	bhfarraige	farraige-N	Ncfsc
ag	ag	ag-S	Sp
na	na	na-T	Td-p
bádóirí	bádóirí	bádóir-N	Ncmpc
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
ag	ag	ag-S	Sp
seoladh	seoladh	seol-N	Nv
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
dheas	dheas	deas-A	Aqp
chóir	chóir	chóir-R	Ri
ghaoithe	ghaoithe	gaoth-N	Ncfsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
acu	acu	ag-P	Pr3-p
ag	ag	ag-S	Sp
tús	tús	tús-N	Ncmsc
aimsire	aimsire	aimsir-N	Ncfsg
.	.	.-F	Fe
Chiúnaigh	Chiúnaigh	ciúnaigh-V	Vmis
cúrsaí	cúrsaí	cúrsa-N	Ncmpc
ansin	ansin	ansin-R	Rt|Rl
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
chalm	chalm	calm-N	Ncmsc
ar feadh	ar feadh	ar_feadh-S	Spc
lá	lá	lá-N	Ncmsc
nó	nó	nó-C	Cc
dhó	dhó	dó-M	Mc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ba	ba	is-W	Ws|Ws-i
ghearr	ghearr	gearr-A	Aqp
gur	gur	gur-Q	Q--s
tháinig	tháinig	tar-V	Vmis
sé	sé	sé-P	Pp3msn
garbh	garbh	garbh-A	Aqp
agus	agus	agus-C	Cc
gur	gur	gur-Q	Q--s
réab	réab	réab-V	Vmis
an	an	an-T	Td-s
stoirm	stoirm	stoirm-N	Ncfsc
agus	agus	agus-C	Cc
gur	gur	gur-W	Wsdi|Q--s
thosaigh	thosaigh	tosach-V	Vmis|Ncmpc
an	an	an-T	Td-s
fharraige	fharraige	farraige-N	Ncfsc
cháite	cháite	cáith-A	Av
ag	ag	ag-S	Sp
bualadh	bualadh	buail-N	Nv
an	an	an-T	Td-s
bháid	bháid	bád-N	Ncmsg
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
mullach	mullach	mullach-N	Ncmsc
orthu	orthu	ar-P	Pr3-p
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
tuile	tuile	tuile-N	Ncfsc
báistí	báistí	báistigh-A	Av
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
lasracha	lasracha	lasair-N	Ncfpc
agus	agus	agus-C	Cc
toirneach	toirneach	toirneach-N	Ncfpg|Ncfsc
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
thar	thar	thar-S	Sp
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Bhíodh	Bhíodh	bí-V	Vmih
Ailcín	Ailcín	ailcín-N	Ncfsc
seasta	seasta	seas-A	Aqp|Av
síoraí	síoraí	síoraí-A	Aqp
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
ceisteanna	ceisteanna	ceist-N	Ncfpg
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
hathair	hathair	athair-N	Ncmsc
faoin	faoin	faoi-S	Spa-s
aimsir	aimsir	aimsir-N	Ncfsc
.	.	.-F	Fe
Bhíodh	Bhíodh	bí-V	Vmih
sí	sí	sí-P	Pp3fsn
á	á	do-S	Spo-s
bhodhrú	bhodhrú	bodhraigh-N	Nv
de	de	de-S	Sp
lá	lá	lá-N	Ncmsc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
oíche	oíche	oíche-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cén	Cén	cé-D	Dw--s
chaoi	chaoi	caoi-N	Ncfsc
a	a	a-Q	Q-i
bhfuil	bhfuil	bí-V	Vmip---d
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
inniu	inniu	inniu-R	Rt
acu	acu	ag-P	Pr3-p
?	?	?-F	Fq
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
an	an	an-T	Td-s
stoirm	stoirm	stoirm-N	Ncfsc
ag	ag	ag-S	Sp
maolú	maolú	maolaigh-N	Nv
?	?	?-F	Fq
An	An	an-Q	Qq
mbeidh	mbeidh	bí-V	Vmif
sé	sé	sé-P	Pp3msn
tada	tada	tada-N	Ncmsc
níos	níos	níos-U	Uc
fearr	fearr	maith-A	Aqc
tráthnóna	tráthnóna	tráthnóna-N	Ncmsc
?	?	?-F	Fq
An	An	an-Q	Qq
mairfidh	mairfidh	mair-V	Vmif
an	an	an-T	Td-s
doineann	doineann	doineann-N	Ncfsc
seo	seo	seo-D	Dd
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
?	?	?-F	Fq
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
trua	trua	trua-N	Ncfsc
ag	ag	ag-S	Sp
Aeólas	Aeólas	Aeólas-N	Npmsc
dá	dá	do-S	Spp-s
iníon	iníon	iníon-N	Ncfsc
ach	ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
olc	olc	olc-N	Ncmsc
aige	aige	ag-P	Pr3ms
dá	dá	do-S	Spp-s
chliamhain	chliamhain	cliamhain-N	Ncmsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
am	am	am-N	Ncmsc
céanna	céanna	céanna-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cén	Cén	cé-W	W--q|Dw--s
cineál	cineál	cineál-N	Ncmsc
fir	fir	fear-N	Ncmsg
é	é	é-P	Pp3ms
sin	sin	sin-P	Pd
,	,	,-F	Fi
ar	ar	ar-S	Sp
aon	aon	aon-D	Dq
nós	nós	nós-N	Ncmsc
,	,	,-F	Fi
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
imeodh	imeodh	imigh-V	Vmc
leis	leis	le-P	Pr3ms
mar	mar	mar-C	Cs
sin	sin	sin-W	W
tar éis	tar éis	tar_éis-S	Spc
a	a	a-Q	Q-i
ndúirt	ndúirt	abair-V	Vmis
mé	mé	mé-P	Pp1-s
leis	leis	le-P	Pr3ms
?	?	?-F	Fq
Nach	Nach	is-W	Wpsin
amaideach	amaideach	amaideach-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
á	á	do-S	Spo-s
chur	chur	cuir-N	Nv
féin	féin	féin-P	Px
sa	sa	i-S	Spa-s
gcontúirt	gcontúirt	contúirt-N	Ncfsc
sin	sin	sin-D	Dd
agus	agus	agus-C	Cc
do	do	do-D	Dp2-s
d	d	d-X	Xl
’	’	’-F	Fa
fhágáilse	fhágáilse	fágáil-N	Ncfsc-e
anseo	anseo	anseo-R	Rl
i	i	i-S	Sp
do	do	do-D	Dp2-s
chadhan	chadhan	cadhan-N	Ncmsc
aonraic	aonraic	aonraic-A	Aq-msc
!	!	!-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
a	a	a-U	Uv
Dheaide	Dheaide	Dheaide-N	Npmsc
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
air	air	ar-P	Pr3ms
dul	dul	dul-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
aistear	aistear	aistear-N	Ncmsc
sin	sin	sin-D	Dd
.	.	.-F	Fe
Dúirt	Dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
liom	liom	le-P	Pr1-s
go	go	go-Q	Q
dtiocfadh	dtiocfadh	tar-V	Vmc
sé	sé	sé-P	Pp3msn
ar ais	ar ais	ar_ais-R	Rd
slán	slán	slán-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
fhreagair	fhreagair	freagair-V	Vmis
sí	sí	sí-P	Pp3fsn
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
ligean	ligean	lig-N	Nv
uirthi	uirthi	ar-P	Pr3fs
féin	féin	féin-P	Px
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
‑	‑	‑-F	Fb
chróga	chróga	cróga-A	Aqc
agus	agus	agus-C	Cc
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
isteach	isteach	isteach-R	Rd
ná	ná	ná-C	Cc
amach	amach	amach-R	Rd
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Le	Le	le-S	Sp
himeacht	himeacht	imigh-N	Nv
aimsire	aimsire	aimsir-N	Ncfsg
bhí	bhí	bí-V	Vmis
barúil	barúil	barúil-N	Ncfsc
mhaith	mhaith	maith-A	Aq-fsc
ag	ag	ag-S	Sp
Ailcín	Ailcín	ailcín-N	Ncfsc
nach	nach	nach-Q	Qnr
mbeadh	mbeadh	bí-V	Vmc
Céacs	Céacs	Céacs-N	Npmsc
ar ais	ar ais	ar_ais-R	Rd
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
airigh	airigh	airigh-V	Vmis
sí	sí	sí-P	Pp3fsn
uaithi	uaithi	ó-P	Pr3fs
go	go	go-U	Ua
mór	mór	mór-A	Aqp
é	é	é-P	Pp3ms
.	.	.-F	Fe
Is	Is	is-W	Wp-i
í	í	í-P	Pp3fs
a	a	a-Q	Q-r
bhíodh	bhíodh	bí-V	Vmih
tromchroíoch	tromchroíoch	tromchroíoch-A	Aqp
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhreathnaíodh	bhreathnaíodh	breathnaigh-V	Vmih
sí	sí	sí-P	Pp3fsn
amach	amach	amach-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcuan	gcuan	cuan-N	Ncmsc
agus	agus	agus-C	Cc
gan	gan	gan-S	Sp
dé	dé	dé-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbád	mbád	bád-N	Ncmsc
ná	ná	ná-C	Cs
ar	ar	is-W	Wpdi|Wpsi|Wssi
na	na	na-T	Td-p
fir	fir	fear-N	Ncmpc
.	.	.-F	Fe
Bhíodh	Bhíodh	bí-V	Vmih
sí	sí	sí-P	Pp3fsn
le	le	le-S	Sp
cloisteáil	cloisteáil	clois-N	Nv
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
is	is	agus-C	Cc
i	i	i-S	Sp
ngearr	ngearr	gearr-N	Ncmsc
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
olagón	olagón	olagón-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
,	,	,-F	Fi
a	a	a-U	Uv|Dp3
stór	stór	stór-N	Ncmsv
mo	mo	mo-D	Dp1-s
chroí	chroí	croí-N	Ncmsc
?	?	?-F	Fq
Tá	Tá	bí-V	Vmip
mé	mé	mé-P	Pp1-s
uaigneach	uaigneach	uaigneach-A	Aqp
i	i	i-S	Sp
d	d	d-X	Xl
’	’	’-F	Fa
uireasa	uireasa	uireasa-N	Ncfsc
.	.	.-F	Fe
Tar	Tar	tar-V	Vmm-2s
ar ais	ar ais	ar_ais-R	Rd
.	.	.-F	Fe
Lig	Lig	lig-V	Vmm-2s
dom	dom	do-P	Pr1-s
lán	lán	lán-N	Ncmsc
na	na	na-T	Td-p
súl	súl	súil-N	Ncfpg
a	a	a-U	U
bhaint	bhaint	bain-N	Nv
asat	asat	as-P	Pr2-s
uair	uair	uair-N	Ncfsc
amháin	amháin	amháin-A	Aqp
eile	eile	eile-D	Dd
.	.	.-F	Fe
'	'	'-F	Fa
Lean	Lean	Lean-N	Npmsc
an	an	an-T	Td-s
doineann	doineann	doineann-N	Ncfsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
drochaimsir	drochaimsir	drochaimsir-N	Ncfsc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
fir	fir	fear-N	Ncmpc
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
gach	gach	gach-N	Ns-s
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
siad	siad	siad-P	Pp3-pn
in ann	in ann	in_ann-S	Spc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
le	le	le-S	Sp
fanacht	fanacht	fan-N	Nv
beo	beo	beo-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
cuimhneamh	cuimhneamh	cuimhnigh-N	Nv
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
muintir	muintir	muintir-N	Ncfsc
agus	agus	agus-C	Cc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
gcairde	gcairde	cairde-N	Ncmpc|Ncmsc
sa	sa	i-S	Spa-s
mbaile	mbaile	baile-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Céacs	Céacs	Céacs-N	Npmsc
ag	ag	ag-S	Sp
cuimhneamh	cuimhneamh	cuimhnigh-N	Nv
ar	ar	ar-S	Sp
Ailcín	Ailcín	ailcín-N	Ncfsc
,	,	,-F	Fi
ar	ar	ar-S	Sp
ndóigh	ndóigh	dóigh-N	Ncfsc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
é	é	é-P	Pp3ms
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sásta	sásta	sásta-A	Aqc
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
sí	sí	sí-P	Pp3fsn
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Neartaigh	Neartaigh	neartaigh-V	Vmis|Vmm-2s
an	an	an-T	Td-s
gála	gála	gála-N	Ncmsc
,	,	,-F	Fi
laghdaigh	laghdaigh	laghdaigh-V	Vmis
siad	siad	siad-P	Pp3-pn
na	na	na-T	Td-p
seolta	seolta	seol-N	Ncmpc
agus	agus	agus-C	Cc
rinne	rinne	déan-V	Vmis
siad	siad	siad-P	Pp3-pn
a	a	a-U	Um
seacht	seacht	seacht-M	Mc
ndícheall	ndícheall	dícheall-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
fuair	fuair	faigh-V	Vmis
an	an	an-T	Td-s
nádúr	nádúr	nádúr-N	Ncmsc
an	an	an-T	Td-s
ceann	ceann	ceann-N	Ncmsc
is	is	is-U	U
fearr	fearr	maith-A	Aqc
orthu	orthu	ar-P	Pr3-p
.	.	.-F	Fe
Cuireadh	Cuireadh	cuir-V	Vmis0|Ncmsc|Vmm-3s
an	an	an-T	Td-s
bád	bád	bád-N	Ncmsc
dá	dá	de-S	Spp-s
cúrsa	cúrsa	cúrsa-N	Ncmsc
agus	agus	agus-C	Cc
b	b	b-X	Xl
’	’	’-F	Fa
éigean	éigean	éigean-N	Ncmsc
dóibh	dóibh	do-P	Pr3-p
géilleadh	géilleadh	géilleadh-N	Ncmsc
agus	agus	agus-C	Cc
imeacht	imeacht	imigh-N	Ncmsc|Nv
le	le	le-S	Sp
sruth	sruth	sruth-N	Ncmsc
.	.	.-F	Fe
Idir	Idir	idir-S	Sp
an	an	an-T	Td-s
dá	dá	dó-M	Mc
linn	linn	linn-N	Ncfsc
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
Ailcín	Ailcín	ailcín-N	Ncfsc
sa	sa	i-S	Spa-s
mbaile	mbaile	baile-N	Ncmsc
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
cráite	cráite	cráigh-A	Av
le	le	le-S	Sp
himní	himní	imní-N	Ncfsc
.	.	.-F	Fe
Maidin	Maidin	maidin-N	Ncfsc
amháin	amháin	amháin-A	Aqp
rith	rith	rith-V	Vmis
sí	sí	sí-P	Pp3fsn
síos	síos	síos-R	Rd
chuig	chuig	chuig-S	Sp
an	an	an-T	Td-s
áit	áit	áit-N	Ncfsc
ar	ar	ar-Q	Q-is
imigh	imigh	imigh-V	Vmis
an	an	an-T	Td-s
bád	bád	bád-N	Ncmsc
as	as	as-P	Pr3ms
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
breathnú	breathnú	breathnaigh-N	Nv
amach	amach	amach-R	Rd
ar	ar	ar-S	Sp
bhun	bhun	bun-N	Ncmsc
na	na	na-T	Tdfsg
spéire	spéire	spéir-N	Ncfsg
mar	mar	mar-C	Cs
ba	ba	is-W	Wsri
ghnách	ghnách	gnách-A	Aqp
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Céard	Céard	cé-W	W--q
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
ina	ina	i-S	Spp-s
treo	treo	treo-N	Ncmsc
ar	ar	ar-S	Sp
bharr	bharr	barr-N	Ncmsc
an	an	an-T	Td-s
uisce	uisce	uisce-N	Ncmsg
ach	ach	ach-S	Sp
corp	corp	corp-N	Ncmsc
a	a	a-D	Dp3
fir	fir	fear-N	Ncmpc
chéile	chéile	céile-N	Ncmsg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmis
sí	sí	sí-P	Pp3fsn
as	as	as-P	Pr3ms
a	a	a-D	Dp3
meabhair	meabhair	meabhair-N	Ncfsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
.	.	.-F	Fe
Rith	Rith	rith-V	Vmis
sí	sí	sí-P	Pp3fsn
amach	amach	amach-R	Rd
ar	ar	ar-S	Sp
bharr	bharr	barr-N	Ncmsc
na	na	na-T	Td-p
gcarraigeacha	gcarraigeacha	carraig-N	Ncfpg
agus	agus	agus-C	Cc
chaith	chaith	caith-V	Vmis
sí	sí	sí-P	Pp3fsn
í	í	í-P	Pp3fs
féin	féin	féin-P	Px
san	san	i-S	Spa-s
fharraige	fharraige	farraige-N	Ncfsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
chomh	chomh	chomh-R	Ri
luath	luath	luath-A	Aqp
agus	agus	agus-C	Cc
a	a	a-Q	Q-r
theagmhaigh	theagmhaigh	teagmhaigh-V	Vmis
Ailcín	Ailcín	ailcín-N	Ncfsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
uisce	uisce	uisce-N	Ncmsc
tháinig	tháinig	tar-V	Vmis
claochlú	claochlú	claochlú-N	Ncmsc
uirthi	uirthi	ar-P	Pr3fs
,	,	,-F	Fi
is	is	is-W	Wpri
é	é	é-P	Pp3ms
sin	sin	sin-P	Pd|W
gur	gur	gur-W	Wsdi|Q--s
fhás	fhás	fás-V	Vmis|Nv|Ncmsc
sciatháin	sciatháin	sciathán-N	Ncmsg|Ncmpc|Ncmsg
uirthi	uirthi	ar-P	Pr3fs
agus	agus	agus-C	Cc
gur	gur	gur-Q	Q--s
athraigh	athraigh	athraigh-V	Vmis
sí	sí	sí-P	Pp3fsn
ina	ina	i-S	Spp-s
héan	héan	éan-N	Ncmsc
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
foluain	foluain	foluain-N	Ncfsc
thart	thart	thart-R	Rd
timpeall	timpeall	timpeall-R	Rd|Ncmsc|Sp
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
a	a	a-D	Dp3
bealach	bealach	bealach-N	Ncmsc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
chomh	chomh	chomh-R	Ri
fada	fada	fada-A	Aqp
le	le	le-S	Sp
Céacs	Céacs	Céacs-N	Npmsc
,	,	,-F	Fi
agus	agus	agus-C	Cc
gach	gach	gach-D	Dq
aon	aon	aon-D	Dq
scréach	scréach	scréach-N	Ncfsc
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
Sa	Sa	i-S	Spa-s
deireadh	deireadh	deireadh-N	Ncmsc
,	,	,-F	Fi
d	d	d-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmm-2s
léi	léi	le-P	Pr3fs
teacht	teacht	tar-N	Nv
chomh	chomh	chomh-R	Ri
fada	fada	fada-A	Aqp
leis	leis	le-P	Pr3ms
agus	agus	agus-C	Cc
barróg	barróg	barróg-N	Ncfsc
a	a	a-U	U
bhreith	bhreith	beir-N	Nv
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
mhór	mhór	mór-A	Aqp
an	an	an-T	Td-s
díol	díol	díol-N	Ncmsc
trua	trua	trua-A	Aqp
iad	iad	iad-P	Pp3-p
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
na	na	na-T	Td-p
déithe	déithe	dé-N	Ncmpc|Ncfpc
ag	ag	ag-S	Sp
breathnú	breathnú	breathnaigh-N	Nv
anuas	anuas	anuas-R	Rd
orthu	orthu	ar-P	Pr3-p
agus	agus	agus-C	Cc
ghlac	ghlac	glac-V	Vmis
siad	siad	siad-P	Pp3-pn
trua	trua	trua-N	Ncfsc|Aqp
dóibh	dóibh	do-P	Pr3-p
,	,	,-F	Fi
áfach	áfach	áfach-R	Rg
.	.	.-F	Fe
Leis	Leis	le-S	Sp
an	an	an-T	Td-s
gcumhacht	gcumhacht	cumhacht-N	Ncfsc
agus	agus	agus-C	Cc
leis	leis	le-S	Sp
an	an	an-T	Td-s
draíocht	draíocht	draíocht-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
acu	acu	ag-P	Pr3-p
bhí	bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
in ann	in ann	in_ann-S	Spc
Céacs	Céacs	Céacs-N	Npmsc
a	a	a-U	U
athrú	athrú	athraigh-N	Nv
ina	ina	i-S	Spp-s
éan	éan	éan-N	Ncmsc
freisin	freisin	freisin-R	Rg
,	,	,-F	Fi
rud	rud	rud-N	Ncmsc
a	a	a-Q	Q-r
rinne	rinne	déan-V	Vmis
siad	siad	siad-P	Pp3-pn
.	.	.-F	Fe
Is	Is	is-W	Wp-i
dhá	dhá	dó-M	Mc
éan	éan	éan-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
le	le	le-S	Sp
feiceáil	feiceáil	feic-N	Nv
amuigh	amuigh	amuigh-R	Rl
ar	ar	ar-S	Sp
an	an	an-T	Td-s
domhain	domhain	domhain-N	Ncfsc
anois	anois	anois-R	Rt
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
ghearr	ghearr	gearr-A	Aqp
gur	gur	gur-Q	Q--s
éirigh	éirigh	éirigh-V	Vmis
agus	agus	agus-C	Cc
gur	gur	gur-Q	Q--s
eitil	eitil	eitil-V	Vmis
siad	siad	siad-P	Pp3-pn
suas	suas	suas-R	Rd
sa	sa	i-S	Spa-s
spéir	spéir	spéir-N	Ncfsc
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
ag	ag	ag-S	Sp
casadh	casadh	cas-N	Nv
ceoil	ceoil	ceol-N	Ncmsg|Nv--g--n
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cheap	Cheap	ceap-V	Vmis
mé	mé	mé-P	Pp1-s
nach	nach	nach-Q	Qnr
dtiocfá	dtiocfá	tar-V	Vmc-2s
ar ais	ar ais	ar_ais-R	Rd
chugam	chugam	chuig-P	Pr1-s
go	go	go-U	Ua
brách	brách	brách-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
Ailcín	Ailcín	ailcín-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Féach	Féach	féach-V	Vmm-2s
muid	muid	muid-P	Pp1-p
anois	anois	anois-R	Rt
agus	agus	agus-C	Cc
muid	muid	muid-P	Pp1-p
chomh	chomh	chomh-R	Ri
sásta	sásta	sásta-A	Aqp
lena	lena	le-S	Spr
bhfaca	bhfaca	feic-V	Vmis---d
tú	tú	tú-P	Pp2-s
riamh	riamh	riamh-R	Rg
.	.	.-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Nach	Nach	nach-Q	Qnrs
ndúirt	ndúirt	abair-V	Vmis
mé	mé	mé-P	Pp1-s
leat	leat	le-P	Pr2-s
go	go	go-Q	Q
mbeinn	mbeinn	bí-V	Vmc-1s
ar ais	ar ais	ar_ais-R	Rd
?	?	?-F	Fq
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
sin	sin	sin-D	Dd
ar	ar	ar-Q	Q-p
imigh	imigh	imigh-V	Vmis
mé	mé	mé-P	Pp1-s
ón	ón	ó-S	Spa-s
gcladach	gcladach	cladach-N	Ncmsc
agus	agus	agus-C	Cc
muid	muid	muid-P	Pp1-p
ag	ag	ag-S	Sp
fágáil	fágáil	fág-N	Nv
slán	slán	slán-N	Ncmpg
lena	lena	le-S	Spp-s
chéile	chéile	céile-N	Ncmsc
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
muid	muid	muid-P	Pp1-p
i dteannta	i dteannta	i_dteannta-S	Spc
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
arís	arís	arís-R	Rg
.	.	.-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Nach	Nach	nach-Q	Qnr
bhfuil	bhfuil	bí-V	Vmip---n
sé	sé	sé-P	Pp3msn
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
níos	níos	níos-U	Uc
fearr	fearr	maith-A	Aqc
a	a	a-U	U
bheith	bheith	bí-N	Nv
abhus	abhus	abhus-R	Rd
anseo	anseo	anseo-R	Rl
ag	ag	ag-S	Sp
breathnú	breathnú	breathnaigh-N	Nv
síos	síos	síos-R	Rd
ar	ar	ar-S	Sp
chuile	chuile	cuile-N	Ncfsc
dhuine	dhuine	duine-N	Ncmsg
ná	ná	ná-C	Cc
a	a	a-U	U
bheith	bheith	bí-N	Nv
thíos	thíos	thíos-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
talamh	talamh	talamh-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
,	,	,-F	Fi
muise	muise	muise-X	Xsc
,	,	,-F	Fi
agus	agus	agus-C	Cc
is	is	is-W	Wp-i
anseo	anseo	anseo-R	Rl
a	a	a-Q	Q-r
fhanfaidh	fhanfaidh	fan-V	Vmif
muid	muid	muid-P	Pp1-p
chomh	chomh	chomh-R	Ri
fada	fada	fada-A	Aqp
agus	agus	agus-C	Cc
is	is	is-W	Wpri
féidir	féidir	féidir-N	Ns-s
.	.	.-F	Fe
Beidh	Beidh	bí-V	Vmif
muid	muid	muid-P	Pp1-p
ag	ag	ag-S	Sp
coinneáil	coinneáil	coinnigh-N	Nv
súil	súil	súil-N	Ncfsc
ghéar	ghéar	géar-A	Aq-fsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
dream	dream	dream-N	Ncmsc
thíos	thíos	thíos-R	Rd
!	!	!-F	Fe
'	'	'-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
fhan	fhan	fan-V	Vmis
siad	siad	siad-P	Pp3-pn
thuas	thuas	tuaigh-R	Rd|Vmip---r
sna	sna	i-S	Spa-p
spéartha	spéartha	spéir-N	Ncfpc
agus	agus	agus-C	Cc
bíonn	bíonn	bí-V	Vmig
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
guairdeall	guairdeall	guairdeall-N	Ncmsc
thart	thart	thart-R	Rd
ann	ann	i-P	Pr3ms
fós	fós	fós-R	Rg
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
éanacha	éanacha	éan-N	Ncmpc
óga	óga	óg-A	Aq--pc
acu	acu	ag-P	Pr3-p
chuile	chuile	cuile-N	Ncfsc
bhliain	bhliain	bliain-N	Ncfsc
roimh	roimh	roimh-S	Sp
aimsir	aimsir	aimsir-N	Ncfsc
na	na	na-T	Tdfsg
Nollag	Nollag	Nollaig-N	Ncfsg
.	.	.-F	Fe
Sin	Sin	sin-W	W
t	t	t-X	Xl
‑	‑	‑-F	Fb
am	am	am-N	Ncmsc
a	a	a-Q	Q-i
dtagann	dtagann	tar-V	Vmip
na	na	na-T	Td-p
laethanta	laethanta	lá-N	Ncmpc
deasa	deasa	deas-A	Aq--pc
,	,	,-F	Fi
órga	órga	órga-A	Aqp
agus	agus	agus-C	Cc
an	an	an-T	Td-s
aimsir	aimsir	aimsir-N	Ncfsc
bhreá	bhreá	breá-A	Aq-fsc
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
ag	ag	ag-S	Sp
Ailcín	Ailcín	ailcín-N	Ncfsc
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
Céacs	Céacs	Céacs-N	Npmsc
nach	nach	nach-Q	Qnr
ligfidh	ligfidh	lig-V	Vmif---n
Aeólas	Aeólas	Aeólas-N	Npmsc
d	d	d-X	Xl
’	’	’-F	Fa
aon	aon	aon-D	Dq
stoirm	stoirm	stoirm-N	Ncfsc
séideadh	séideadh	séid-V	Vmis0
ag	ag	ag-S	Sp
an	an	an-T	Td-s
am	am	am-N	Ncmsc
sin	sin	sin-D	Dd
bliana	bliana	bliain-N	Ncfpc
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
Dia	Dia	dia-N	Ncmsc
na	na	na-T	Td-p
Gaoithe	Gaoithe	Gaoithe-N	Npmsg
ag	ag	ag-S	Sp
faire	faire	fair-N	Nv
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
iníon	iníon	iníon-N	Ncfsc
agus	agus	agus-C	Cc
ar	ar	ar-S	Sp
na	na	na-T	Td-p
gearrcaigh	gearrcaigh	gearrcach-N	Ncmpc
óga	óga	óg-N	Ncmpc
a	a	a-Q	Q-r
bhíonn	bhíonn	bí-V	Vmig
sa	sa	i-S	Spa-s
nead	nead	nead-N	Ncfsc
léi	léi	le-P	Pr3fs
ar	ar	ar-N	Ncmsc
bharr	bharr	barr-N	Ncmsc
an	an	an-T	Td-s
uisce	uisce	uisce-N	Ncmsg
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
bhíonn	bhíonn	bí-V	Vmig---n
puth	puth	puth-N	Ncfsc
as	as	as-S	Sp
aer	aer	aer-N	Ncmsc
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
an	an	an-T	Td-s
aimsir	aimsir	aimsir-N	Ncfsc
deas	deas	deas-R	Ri
ciúin	ciúin	ciúin-A	Aqp
agus	agus	agus-C	Cc
bíonn	bíonn	bí-V	Vmig
an	an	an-T	Td-s
fharraige	fharraige	farraige-N	Ncfsc
ina	ina	i-S	Spp-s
clár	clár	clár-N	Ncmsc
i lár	i lár	i_lár-S	Spc
ghearróga	ghearróga	gearróg-N	Ncfpc
dubha	dubha	dubh-A	Aq--pc
na	na	na-T	Tdfsg
Nollag	Nollag	Nollaig-N	Ncfsg
.	.	.-F	Fe
