 Bean	Bean	-X	Xx
Phortaigh	Phortaigh	portach-N	Ncmpc
Mhín	Mhín	Mín-N	Npfsg
na	na	na-T	Td-p
mBradán	mBradán	bradán-N	Ncmpg
Tús	Tús	tús-N	Ncmsc
mhí	mhí	mí-N	Ncfsc|Ncmsc
na	na	na-T	Tdfsg
Bealtaine	Bealtaine	Bealtaine-N	Ncfsg
1978	1978	1978-M	Mn
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
meitheal	meitheal	meitheal-N	Ncfsc
fear	fear	fear-N	Ncmsc|Ncmpg
ag	ag	ag-S	Sp
baint	baint	bain-N	Nv
móna	móna	móin-N	Ncfsg
sa	sa	i-S	Spa-s
phortach	phortach	portach-N	Ncmsc
leath	leath	leath-N	Ncfpg|Dq|Ncfsc
bealaigh	bealaigh	bealach-N	Ncmsg
idir	idir	idir-S	Sp
Inbhear	Inbhear	inbhear-N	Ncmsc
agus	agus	agus-C	Cc
Ard	Ard	ard-N	Ncmsc
an	an	an-T	Td-s
Rátha	Rátha	ráth-N	Ncmsg
.	.	.-F	Fe
I	I	i-S	Sp
dtrátha	dtrátha	tráth-N	Ncmsg
am	am	am-N	Ncmsc
lóin	lóin	lón-N	Ncmsg
chuaigh	chuaigh	téigh-V	Vmis
Charlie	Charlie	Charlie-N	Npmsc
a	a	a-D	Dp3
fhad	fhad	fad-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
teach	teach	teach-N	Ncmsc
ba	ba	is-U	U
chóngaraí	chóngaraí	cóngarach-A	Aqc
le	le	le-S	Sp
citeal	citeal	citeal-N	Ncmsc
uisce	uisce	uisce-N	Ncmsg
a	a	a-D	Dp3
ghail	ghail	gail-N	Ncfsc
.	.	.-F	Fe
Le	Le	le-S	Sp
linn	linn	linn-N	Ncfsc
dó	dó	dóigh-N	Nv
a	a	a-U	U
bheith	bheith	bí-N	Nv
ar	ar	ar-S	Sp
shiúl	shiúl	siúl-N	Ncmsc
bhí	bhí	bí-V	Vmis
Francie	Francie	Francie-N	Npmsc
ag	ag	ag-S	Sp
baint	baint	bain-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
tríú	tríú	trí-M	Mo
hurlár	hurlár	urlár-N	Ncmpg|Ncmsc
.	.	.-F	Fe
Uair	Uair	uair-N	Ncfsc
dár	dár	do-S	Spp-p
chuir	chuir	cur-N	Ncmsg
Francie	Francie	Francie-N	Npmsc
síos	síos	síos-R	Rd
an	an	an-T	Td-s
sleán	sleán	sleán-N	Ncmsc
mhothaigh	mhothaigh	mothaigh-V	Vmis
sé	sé	sé-P	Pp3msn
rud	rud	rud-N	Ncmsc
inteacht	inteacht	tar-N	Ncmsc|Nv
crua	crua	crua-N	Ncmsg|Aqp|Ncmsc|Ncfsc|Ncfsg
.	.	.-F	Fe
Dar	Dar	dar-V	Vmip
leis	leis	le-P	Pr3ms
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
seo	seo	seo-P	Pd
neamhghnách	neamhghnách	neamhghnách-A	Aqp
.	.	.-F	Fe
Díreach	Díreach	díreach-N	Ncmsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
bhomaite	bhomaite	bomaite-N	Ncmsg
sin	sin	sin-D	Dd
phill	phill	pill-V	Vmis
Charlie	Charlie	Charlie-N	Npmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
chiteal	chiteal	citeal-N	Ncmsc
agus	agus	agus-C	Cc
stad	stad	stad-V	Vmis|Vmm-2s
an	an	an-T	Td-s
obair	obair	obair-N	Ncfsc
.	.	.-F	Fe
Shuigh	Shuigh	suigh-V	Vmis
siad	siad	siad-P	Pp3-pn
síos	síos	síos-R	Rd
ar	ar	ar-S	Sp
ardán	ardán	ardán-N	Ncmsc
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
amach	amach	amach-R	Rd
a	a	a-D	Dp3
gcuid	gcuid	cuid-N	Ncfsc
ceapairí	ceapairí	ceapaire-N	Ncmpg
a	a	a-D	Dp3
fhad	fhad	fad-N	Ncmsc
is	is	agus-C	Cc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Charlie	Charlie	Charlie-N	Npmsc
ag	ag	ag-S	Sp
ullmhú	ullmhú	ullmhaigh-N	Nv
an	an	an-T	Td-s
tae	tae	tae-N	Ncmsg
.	.	.-F	Fe
Shuigh	Shuigh	suigh-V	Vmis
siad	siad	siad-P	Pp3-pn
ansin	ansin	ansin-R	Rt|Rl
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
a	a	a-D	Dp3
lóin	lóin	lón-N	Ncmsg
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
dheas	dheas	deas-A	Aqp
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
baint	baint	bain-N	Nv
suilt	suilt	sult-N	Ncmsg
as	as	as-S	Sp
an	an	an-T	Td-s
timpeallacht	timpeallacht	timpeallacht-N	Ncfsc
–	–	–-X	Xx
aer	aer	aer-N	Ncmsc
an	an	an-T	Td-s
chaoráin	chaoráin	caorán-N	Ncmsg
,	,	,-F	Fi
an	an	an-T	Td-s
fhuiseog	fhuiseog	fuiseog-N	Ncfsc
,	,	,-F	Fi
an	an	an-T	Td-s
gabhar	gabhar	gabhar-N	Ncmsc
deorach	deorach	deorach-A	Aq-msc
agus	agus	agus-C	Cc
chuach	chuach	cuach-V	Vmis
ag	ag	ag-S	Sp
seinm	seinm	seinn-N	Nv
agus	agus	agus-C	Cc
níl	níl	bí-V	Vmip---n
tae	tae	tae-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
comh	comh	chomh-R	Ri
blasta	blasta	blasta-A	Aqp
le	le	le-S	Sp
tae	tae	tae-N	Ncmsc
a	a	a-D	Dp3
nítear	nítear	nítear-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
chaorán	chaorán	caorán-N	Ncmsc
.	.	.-F	Fe
Francie	Francie	Francie-N	Npmsc
is	is	agus-W	Wp-i|Wpri|Cc
túisce	túisce	túisce-R	Rt
a	a	a-Q	Q-r
chríochnaigh	chríochnaigh	críochnaigh-V	Vmis
a	a	a-D	Dp3
lón	lón	lón-N	Ncmsc
agus	agus	agus-C	Cc
chuaigh	chuaigh	téigh-V	Vmis
sé	sé	sé-P	Pp3msn
caol	caol	caol-N	Ncmsc|Aqp
díreach	díreach	díreach-A	Aqp|Aq-msc
a	a	a-D	Dp3
fhad	fhad	fad-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
bhachta	bhachta	bachta-N	Ncmsg
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
áit	áit	áit-N	Ncfsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
baint	baint	bain-N	Nv
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-U	U
thochailt	thochailt	tochail-N	Nv
lena	lena	le-S	Spp-s
mhéara	mhéara	méara-N	Ncfpc|Ncmsc
go	go	go-Q	Q
bhfeicfeadh	bhfeicfeadh	feic-V	Vmc
sé	sé	sé-P	Pp3msn
cad	cad	cad-W	W--q
é	é	é-P	Pp3ms
a	a	a-Q	Q-r
bhuail	bhuail	buail-V	Vmis
an	an	an-T	Td-s
sleán	sleán	sleán-N	Ncmsc
.	.	.-F	Fe
An	An	an-T	Td-s
chéad	chéad	céad-M	Mo
rud	rud	rud-N	Ncmsc
a	a	a-Q	Q-i
dtáinig	dtáinig	tar-V	Vmis
sé	sé	sé-P	Pp3msn
air	air	ar-P	Pr3ms
ná	ná	ná-C	Cc
éadach	éadach	éadach-N	Ncmsc
.	.	.-F	Fe
Faoin	Faoin	faoi-S	Spa-s
am	am	am-N	Ncmsc
seo	seo	seo-D	Dd
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
triúr	triúr	triúr-N	Ncmsc
eile	eile	eile-D	Dd
ag	ag	ag-S	Sp
a	a	a-D	Dp3
thaobh	thaobh	taobh-N	Ncmsc
.	.	.-F	Fe
Thochail	Thochail	tochail-V	Vmis
Francie	Francie	Francie-N	Npmsc
ar	ar	ar-S	Sp
shiúl	shiúl	siúl-N	Ncmsc
tuilleadh	tuilleadh	tuilleadh-N	Ncmsc|Nv-----n
den	den	de-S	Spa-s
chaorán	chaorán	caorán-N	Ncmsc
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
gur	gur	gur-Q	Q--s
tuigeadh	tuigeadh	tuig-V	Vmis0
daofa	daofa	do-P	Pr3-p
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
rud	rud	rud-N	Ncmsc
inteacht	inteacht	tar-N	Ncmsc|Nv
istigh	istigh	istigh-R	Rl
san	san	i-S	Spa-s
éadach	éadach	éadach-N	Ncmsc
.	.	.-F	Fe
Tharla	Tharla	tarlaigh-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
scoilt	scoilt	scoilt-N	Ncfsc
san	san	i-S	Spa-s
éadach	éadach	éadach-N	Ncmsc
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ceangailte	ceangailte	ceangail-A	Av
le	le	le-S	Sp
sreangán	sreangán	sreangán-N	Ncmsc
den	den	de-S	Spa-s
ábhar	ábhar	ábhar-N	Ncmsc
chéanna	chéanna	céanna-A	Aqp
leis	leis	le-S	Sp
an	an	an-T	Td-s
éadach	éadach	éadach-N	Ncmsc
.	.	.-F	Fe
Scaoil	Scaoil	scaoil-V	Vmis
siad	siad	siad-P	Pp3-pn
an	an	an-T	Td-s
sreangán	sreangán	sreangán-N	Ncmsc
agus	agus	agus-C	Cc
nocht	nocht	nocht-V	Vmis|Aqp|Ncmsc|Ncmpg|Vmm-2s|Ncmpg
lámh	lámh	lámh-N	Ncfpg|Ncfsc|Ncfpg
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
leor	leor	leor-A	Aqp
sin	sin	sin-W	W
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
acu	acu	ag-P	Pr3-p
gur	gur	is-W	Wsdi
corp	corp	corp-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Stadaigí	Stadaigí	stad-V	Vmm-2p
.	.	.-F	Fe
Ná	Ná	ná-Q	Qnm
déanaigí	déanaigí	déan-V	Vmm-2p-n
níos	níos	níos-U	Uc
mó	mó	mór-A	Aqc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Charlie	Charlie	Charlie-N	Npmsc
arbh	arbh	is-W	Wpsi|Wssi
leis	leis	le-S	Sp
an	an	an-T	Td-s
caorán	caorán	caorán-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
cás	cás	cás-N	Ncmsc
do	do	do-S	Sp
na	na	na-T	Td-p
gardaí	gardaí	garda-N	Ncmpc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Tomás	Tomás	Tomás-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
B	B	B-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
gur	gur	is-W	Wsdi
cheart	cheart	ceart-A	Aqp
dúinn	dúinn	do-P	Pr1-p
cur	cur	cur-N	Ncmsc
fá choinne	fá choinne	fá_choinne-S	Spc
an	an	an-T	Td-s
tsagairt	tsagairt	sagart-N	Ncmsg
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
duine	duine	duine-N	Ncmsc
eile	eile	eile-D	Dd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhuel	Bhuel	bhuel-X	Xsc
,	,	,-F	Fi
a	a	a-U	Uv
fheara	fheara	fear-N	Ncmpv
,	,	,-F	Fi
is	is	is-W	Wpri
cosúil	cosúil	cosúil-A	Aqp
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
deireadh	deireadh	deireadh-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
obair	obair	obair-N	Ncfsc
inniu	inniu	inniu-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Charlie	Charlie	Charlie-N	Npmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
súil	súil	súil-N	Nv-----n
lena	lena	le-S	Spp-s
chuid	chuid	cuid-N	Ncfsc
móna	móna	móin-N	Ncfsg
a	a	a-U	U
bheith	bheith	bí-N	Nv
bainte	bainte	bain-A	Av
roimh	roimh	roimh-S	Sp
an	an	an-T	Td-s
tráthnóna	tráthnóna	tráthnóna-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
háit	háit	áit-N	Ncfsc
a	a	a-Q	Q-i
bhfaighidh	bhfaighidh	faigh-V	Vmif---d
muid	muid	muid-P	Pp1-p
fón	fón	fón-N	Ncmsc
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Francie	Francie	Francie-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
mise	mise	mé-P	Pp1-s-e
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
fón	fón	fón-N	Ncmsc
i gceann	i gceann	i_gceann-S	Spc
de	de	de-P	Pr3ms
na	na	na-T	Td-p
tithe	tithe	teach-N	Ncmpc
sin	sin	sin-D	Dd
thoir	thoir	thoir-R	Rd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Tomás	Tomás	Tomás-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agat	agat	ag-P	Pr2-s
féin	féin	féin-P	Px
,	,	,-F	Fi
ar	ar	ar-S	Sp
ndóigh	ndóigh	dóigh-N	Ncfsc
.	.	.-F	Fe
Tchífidh	Tchífidh	tchí-V	Vmif
tú	tú	tú-P	Pp2-s
cuaile	cuaile	cuaile-N	Ncmsc
agus	agus	agus-C	Cc
sreang	sreang	sreang-V	Vmm-2s
ag	ag	ag-S	Sp
gabháil	gabháil	gabh-N	Nv
a	a	a-D	Dp3
fhad	fhad	fad-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
teach	teach	teach-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmm-2s
Francie	Francie	Francie-N	Npmsc
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
go	go	go-Q	Q
bhfuair	bhfuair	faigh-V	Vmis
sé	sé	sé-P	Pp3msn
teach	teach	teach-N	Ncmsc
le	le	le-S	Sp
fón	fón	fón-N	Ncmsc
.	.	.-F	Fe
Fuair	Fuair	faigh-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
Garda	Garda	garda-N	Ncmsc
Feeney	Feeney	Feeney-N	Npmsc
i	i	i-S	Sp
nDún	nDún	dún-N	Ncmsc
Cionnaola	Cionnaola	Cionnaola-N	Npmsc
ach	ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sé	sé	sé-P	Pp3msn
furasta	furasta	furasta-A	Aqp
a	a	a-U	U
mhíniú	mhíniú	mínigh-N	Nv
díreach	díreach	díreach-N	Ncmpg|Ncmsc
cá	cá	cá-R	Rq
háit	háit	áit-N	Ncfsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
corp	corp	corp-N	Ncmsc
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
scor	scor	scor-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
,	,	,-F	Fi
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
garda	garda	garda-N	Ncmsc
nach	nach	nach-Q	Qnr
mbeadh	mbeadh	bí-V	Vmc
sé	sé	sé-P	Pp3msn
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
iarr	iarr	iarr-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
Francie	Francie	Francie-N	Npmsc
seasamh	seasamh	seas-N	Ncmsc|Nv
ar	ar	ar-S	Sp
thaobh	thaobh	taobh-N	Ncmsc
bhealaigh	bhealaigh	bealaigh-V	Vmis
mhóir	mhóir	mór-A	Aq-msv|Aq-msg
ag	ag	ag-S	Sp
an	an	an-T	Td-s
áit	áit	áit-N	Ncfsc
ba	ba	is-U	U
dheise	dheise	deas-A	Aqc
don	don	do-S	Spa-s
chorp	chorp	corp-N	Ncmsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
scairt	scairt	scairt-V	Vmis
Francie	Francie	Francie-N	Npmsc
ar	ar	ar-S	Sp
shagart	shagart	sagart-N	Ncmsc
paróiste	paróiste	paróiste-N	Ncmsg
Inbhir	Inbhir	inbhear-N	Ncmpc|Ncmsg
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
inis	inis	inis-V	Vmis|Npmsc|Ncfsc|Vmm-2s
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhuel	Bhuel	bhuel-X	Xsc
,	,	,-F	Fi
cá	cá	cá-R	Rq
háit	háit	áit-N	Ncfsc
go	go	go-U	Ua
díreach	díreach	díreach-A	Aqp
a	a	a-Q	Q-i
bhfuil	bhfuil	bí-V	Vmip---d
an	an	an-T	Td-s
corp	corp	corp-N	Ncmsc
seo	seo	seo-D	Dd
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
sagart	sagart	sagart-N	Ncmsc
.	.	.-F	Fe
Rinne	Rinne	déan-V	Vmis
Francie	Francie	Francie-N	Npmsc
a	a	a-D	Dp3
dhícheall	dhícheall	dícheall-N	Ncmsc
sin	sin	sin-P	Pd|W|Dd
a	a	a-U	U
mhíniú	mhíniú	mínigh-N	Nv
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sin	sin	sin-P	Pd
furasta	furasta	furasta-A	Aqp
mar	mar	mar-C	Cs
gur	gur	is-W	Wsdi
ceantar	ceantar	ceantar-N	Ncmsc
sléibhe	sléibhe	sliabh-N	Ncmsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
gan	gan	gan-S	Sp
tithe	tithe	teach-N	Ncmpc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
sagart	sagart	sagart-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Sílimse	Sílimse	síl-V	Vmip1s--e
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
an	an	an-T	Td-s
áit	áit	áit-N	Ncfsc
sin	sin	sin-D	Dd
i	i	i-S	Sp
bparóiste	bparóiste	paróiste-N	Ncmsc
Ard	Ard	ard-A	Aq-msc
an	an	an-T	Td-s
Rátha	Rátha	ráth-N	Ncmsg
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
bheadh	bheadh	bí-V	Vmc----n
sé	sé	sé-P	Pp3msn
de	de	de-S	Sp
cheart	cheart	ceart-N	Ncmsc
agamsa	agamsa	ag-P	Pr1-s-e
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
bparóiste	bparóiste	paróiste-N	Ncmsc
eile	eile	eile-D	Dd
.	.	.-F	Fe
'	'	'-F	Fa
Mar	Mar	mar-C	Cs
sin	sin	sin-W	W
de	de	de-P	Pr3ms
,	,	,-F	Fi
b	b	b-X	Xl
’	’	’-F	Fa
éigean	éigean	éigean-N	Ncmsc
do	do	do-S	Sp
Francie	Francie	Francie-N	Npmsc
scairt	scairt	scairt-V	Vmis
a	a	a-U	U
chur	chur	cuir-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
tsagart	tsagart	sagart-N	Ncfsc
paróiste	paróiste	paróiste-N	Ncmsg|Ncmsc
in	in	i-S	Sp
Ard	Ard	ard-N	Ncmsc
an	an	an-T	Td-s
Rátha	Rátha	ráth-N	Ncmsg
.	.	.-F	Fe
Dúirt	Dúirt	abair-V	Vmis
seisean	seisean	sé-P	Pp3msne
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
sé	sé	sé-P	Pp3msn
amach	amach	amach-R	Rd
gan	gan	gan-S	Sp
mhoill	mhoill	moill-N	Ncfsc
ach	ach	ach-S	Sp
duine	duine	duine-N	Ncmsc
inteacht	inteacht	tar-N	Ncmsc|Nv
seasamh	seasamh	seas-N	Ncmsc|Nv
ar	ar	ar-S	Sp
thaobh	thaobh	taobh-N	Ncmsc
an	an	an-T	Td-s
bhealaigh	bhealaigh	bealach-N	Ncmsg
san	san	i-S	Spa-s
áit	áit	áit-N	Ncfsc
ba	ba	is-U	U
chóngaraí	chóngaraí	cóngarach-A	Aqc
don	don	do-S	Spa-s
chorp	chorp	corp-N	Ncmsc
.	.	.-F	Fe
Taobh	Taobh	taobh-N	Ncmsc
istigh	istigh	istigh-R	Rl
de	de	de-S	Sp
leathuair	leathuair	leathuair-N	Ncfsc
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
Garda	Garda	garda-N	Ncmsc
Feeney	Feeney	Feeney-N	Npmsc
agus	agus	agus-C	Cc
gardaí	gardaí	garda-N	Ncmpg|Ncmpc
as	as	as-S	Sp
Ard	Ard	ard-N	Ncmsc
an	an	an-T	Td-s
Rátha	Rátha	ráth-N	Ncmsg
ar	ar	ar-S	Sp
an	an	an-T	Td-s
láthair	láthair	láthair-N	Ncfsc
.	.	.-F	Fe
I	I	i-S	Sp
ndiaidh	ndiaidh	diaidh-N	Ns-s
scrúdú	scrúdú	scrúdaigh-N	Ncmsc|Nv
gasta	gasta	gasta-A	Aqp
dúirt	dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
,	,	,-F	Fi
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
mé	mé	mé-P	Pp1-s
cuidiú	cuidiú	cuidigh-N	Ncmsc|Nv
a	a	a-U	U
fháil	fháil	faigh-N	Nv
.	.	.-F	Fe
'	'	'-F	Fa
Ar ais	Ar ais	ar_ais-R	Rd
leis	leis	le-P	Pr3ms
go dtí	go dtí	go_dtí-S	Spc
a	a	a-D	Dp3
charr	charr	carr-N	Ncmsc|Ncfsc
agus	agus	agus-C	Cc
labhair	labhair	labhair-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
raidió	raidió	raidió-N	Ncmsc
le	le	le-S	Sp
ceannphort	ceannphort	ceannphort-N	Ncmsc
na	na	na-T	Td-p
ngardaí	ngardaí	garda-N	Ncmpg
i	i	i-S	Sp
mBéal	mBéal	béal-N	Ncmsc
Átha	Átha	Átha-N	Npmsg
Seanaidh	Seanaidh	Seanaidh-N	Npmsg|Npmsc
.	.	.-F	Fe
I	I	i-S	Sp
gceann	gceann	ceann-N	Ncmsc
uaire	uaire	uair-N	Ncfsg
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
áit	áit	áit-N	Ncfsc
lán	lán	lán-A	Aq-fsc
gardaí	gardaí	garda-N	Ncmpg
agus	agus	agus-C	Cc
bleachtairí	bleachtairí	bleachtaire-N	Ncmpg|Ncmpc
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
ceannphort	ceannphort	ceannphort-N	Ncmsc
na	na	na-T	Td-p
ngardaí	ngardaí	garda-N	Ncmpg
as	as	as-S	Sp
Béal	Béal	béal-N	Ncmsc
Átha	Átha	Átha-N	Npmsg
Seanaidh	Seanaidh	Seanaidh-N	Npmsg|Npmsc
i	i	i-S	Sp
héileacaptar	héileacaptar	héileacaptar-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
fhacthas	fhacthas	feic-V	Vmis0--n
a	a	a-D	Dp3
leithéid	leithéid	leithéid-N	Ncfsc
de	de	de-S	Sp
scaifte	scaifte	scaifte-N	Ncmsc
riamh	riamh	riamh-R	Rg
ar	ar	ar-S	Sp
bhachta	bhachta	bachta-N	Ncmsc
portaigh	portaigh	portach-N	Ncmsg
i	i	i-S	Sp
Mín	Mín	Mín-N	Npmsc
na	na	na-T	Td-p
mBradán	mBradán	bradán-N	Ncmpg
.	.	.-F	Fe
Bhuel	Bhuel	bhuel-X	Xsc
,	,	,-F	Fi
tharraing	tharraing	tarraing-V	Vmis
siad	siad	siad-P	Pp3-pn
pictiúracha	pictiúracha	pictiúr-A	Aq--p|Ncmpc
,	,	,-F	Fi
scrúdaigh	scrúdaigh	scrúdaigh-V	Vmis
siad	siad	siad-P	Pp3-pn
an	an	an-T	Td-s
timpeallacht	timpeallacht	timpeallacht-N	Ncfsc
,	,	,-F	Fi
ghlac	ghlac	glac-V	Vmis
siad	siad	siad-P	Pp3-pn
samplaí	samplaí	sampla-N	Ncmpc
,	,	,-F	Fi
thóg	thóg	tóg-V	Vmis
siad	siad	siad-P	Pp3-pn
miosúir	miosúir	miosúr-N	Ncmpc
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
siad	siad	siad-P	Pp3-pn
na	na	na-T	Td-p
céadta	céadta	céad-N	Ncmpc
ceist	ceist	ceist-N	Ncfsc
ar	ar	ar-S	Sp
na	na	na-T	Td-p
fir	fir	fear-N	Ncmpc
a	a	a-Q	Q-i|Q-r
fuair	fuair	faigh-V	Vmis
an	an	an-T	Td-s
corp	corp	corp-N	Ncmsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
thosaigh	thosaigh	tosaigh-V	Vmis
siad	siad	siad-P	Pp3-pn
a	a	a-U	U
thochailt	thochailt	tochail-N	Nv
síos	síos	síos-R	Rd
gur	gur	gur-Q	Q--s
nocht	nocht	nocht-V	Vmis
siad	siad	siad-P	Pp3-pn
an	an	an-T	Td-s
corp	corp	corp-N	Ncmsc
.	.	.-F	Fe
Ghlan	Ghlan	Glan-N	Npmsc
siad	siad	siad-P	Pp3-pn
ar	ar	ar-S	Sp
shiúl	shiúl	siúl-N	Ncmsc
an	an	an-T	Td-s
caorán	caorán	caorán-N	Ncmsc
go	go	go-U	Ua
cúramach	cúramach	cúramach-A	Aqp
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhoscail	fhoscail	fhoscail-N	Ncfsc
siad	siad	siad-P	Pp3-pn
t	t	t-X	Xl
‑	‑	‑-F	Fb
éadach	éadach	éadach-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
thart	thart	thart-R	Rd
uirthi	uirthi	ar-P	Pr3fs
agus	agus	agus-C	Cc
,	,	,-F	Fi
cinnte	cinnte	cinnte-A	Av|Aqp
go leor	go leor	go_leor-A	Aq
,	,	,-F	Fi
corp	corp	corp-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
–	–	–-X	Xx
corp	corp	corp-N	Ncmsc
mná	mná	bean-N	Ncfpc|Ncfsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
gruaig	gruaig	gruaig-N	Ncfsc
dhubh	dhubh	dubh-A	Aq-fsc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Faoin	Faoin	faoi-S	Spa-s
ghréasan	ghréasan	ghréasan-N	Ncmsc
éadaí	éadaí	éadach-N	Ncmpc|Ncmpg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
thart	thart	thart-R	Rd
uirthi	uirthi	ar-P	Pr3fs
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
tarnocht	tarnocht	tarnocht-A	Aqp
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
bróg	bróg	bróg-N	Ncfsc
ná	ná	ná-C	Cc
seodra	seodra	seodra-N	Ncmsg|Ncmsc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
craiceann	craiceann	craiceann-N	Ncmsc
donn	donn	donn-A	Aq-msc
agus	agus	agus-C	Cc
ba	ba	is-W	Wsri
dheacair	dheacair	deacair-A	Aqp
a	a	a-D	Dp3
haois	haois	aois-N	Ncfsc
a	a	a-D	Dp3
inse	inse	inse-N	Ncfsc|Ncmsc
ná	ná	ná-C	Cs|Cc
cá	cá	cá-R	Rq
fhad	fhad	fad-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
curtha	curtha	cuir-A	Av
anseo	anseo	anseo-R	Rl
.	.	.-F	Fe
Gan	Gan	gan-S	Sp
mhoill	mhoill	moill-N	Ncfsc
tháinig	tháinig	tar-V	Vmis
eileatram	eileatram	eileatram-N	Ncmsc
,	,	,-F	Fi
cuireadh	cuireadh	cuir-V	Vmis0|Ncmsc|Vmm-3s
an	an	an-T	Td-s
corp	corp	corp-N	Ncmsc
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
gcónair	gcónair	ar-N	Ncmsg
agus	agus	agus-C	Cc
tugadh	tugadh	tabhair-V	Vmis0
ar	ar	ar-S	Sp
shiúl	shiúl	siúl-N	Ncmsc
go	go	go-S	Sp
stáisiún	stáisiún	stáisiún-N	Ncmsc
na	na	na-T	Td-p
ngardaí	ngardaí	garda-N	Ncmpg
i	i	i-S	Sp
mBéal	mBéal	béal-N	Ncmsc
Átha	Átha	Átha-N	Npmsg
Seanaidh	Seanaidh	Seanaidh-N	Npmsg|Npmsc
í	í	í-P	Pp3fs
.	.	.-F	Fe
Rinne	Rinne	déan-V	Vmis
na	na	na-T	Td-p
gardaí	gardaí	garda-N	Ncmpc
tamall	tamall	tamall-N	Ncmpg|Ncmsc
eile	eile	eile-D	Dd
cuartaigh	cuartaigh	cuartaigh-V	Vmis
agus	agus	agus-C	Cc
iniúchadh	iniúchadh	iniúch-V	Vmm-3s|Nv|Ncmsc|Vmih
fán	fán	faoi-S	Spa-s
áit	áit	áit-N	Ncfsc
agus	agus	agus-C	Cc
ansin	ansin	ansin-R	Rt|Rl
de réir	de réir	de_réir-C	Cs|Spc
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmis
siad	siad	siad-P	Pp3-pn
.	.	.-F	Fe
Chruinnigh	Chruinnigh	cruinnigh-V	Vmis
meitheal	meitheal	meitheal-N	Ncfsc
na	na	na-T	Td-p
bhfear	bhfear	fear-N	Ncmpg
a	a	a-D	Dp3
gcuid	gcuid	cuid-N	Ncfsc
acraí	acraí	acra-N	Ncmpg
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmis
siadsan	siadsan	siad-P	Pp3-pne
chun	chun	chun-S	Sp
an	an	an-T	Td-s
bhaile	bhaile	baile-N	Ncmsg
gan	gan	gan-S	Sp
mórán	mórán	mórán-N	Ncmsc
móna	móna	móin-N	Ncfsg
bainte	bainte	bain-A	Av
acu	acu	ag-P	Pr3-p
ach	ach	ach-S	Sp
scéal	scéal	scéal-N	Ncmsc
mór	mór	mór-A	Aq-msc
le	le	le-S	Sp
hinse	hinse	inse-N	Ncfsc|Ncmsc
.	.	.-F	Fe
An	An	an-T	Td-s
lá	lá	lá-N	Ncmsc
arna	arna	arna-S	Spc
mhárach	mhárach	márach-N	Ns-s
tháinig	tháinig	tar-V	Vmis
an	an	an-T	Td-s
Dr	Dr	Dr-Y	Y
John	John	John-N	Npmsc
Harbison	Harbison	Harbison-N	Npmsc
go	go	go-S	Sp
Béal	Béal	béal-N	Ncmsc
Átha	Átha	Átha-N	Npmsg
Seanaidh	Seanaidh	Seanaidh-N	Npmsg|Npmsc
gur	gur	gur-Q	Q--s
chuir	chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
scrúdú	scrúdú	scrúdaigh-N	Ncmsc|Nv
iarbháis	iarbháis	iarbháis-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
chorp	chorp	corp-N	Ncmsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
tugadh	tugadh	tabhair-V	Vmis0
go	go	go-S	Sp
Baile	Baile	Baile-N	Npmsc
Átha Cliath	Átha Cliath	Átha_Cliath-N	Npmsg
í	í	í-P	Pp3fs
áit	áit	áit-N	Ncfsc
ar	ar	ar-Q	Q-is
coinníodh	coinníodh	coinnigh-V	Vmis0
i	i	i-S	Sp
reoiteoir	reoiteoir	iteoir-N	Ncmsc
í	í	í-P	Pp3fs
go dtí	go dtí	go_dtí-S	Spc
go	go	go-Q	Q
bhfaighfí	bhfaighfí	faigh-V	Vmc-0--d
faill	faill	faill-N	Ncfsc
scrúdú	scrúdú	scrúdú-N	Ncmsc
iomlán	iomlán	iomlán-A	Aq-msc
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
‘	‘	‘-X	Xx
Bean	Bean	bean-N	Ncfsc
Phortaigh	Phortaigh	portach-N	Ncmsg
Mhín	Mhín	Mín-N	Npfsg
na	na	na-T	Td-p
mBradán	mBradán	bradán-N	Ncmpg
’	’	’-F	Fa
ar	ar	ar-S	Sp
shiúl	shiúl	siúl-N	Ncmsc
as	as	as-S	Sp
an	an	an-T	Td-s
cheantar	cheantar	ceantar-N	Ncmsc
agus	agus	agus-C	Cc
daoine	daoine	duine-N	Ncmpg|Ncmpc
eile	eile	eile-D	Dd
ag	ag	ag-S	Sp
plé	plé	pléigh-N	Nv
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Ach	Ach	ach-S	Sp|Cs
i	i	i-S	Sp
bParóiste	bParóiste	paróiste-N	Ncmsc
Inbhir	Inbhir	inbhear-N	Ncmsg
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
ag	ag	ag-S	Sp
méadú	méadú	méadaigh-N	Nv
.	.	.-F	Fe
Cérbh	Cérbh	cé-W	W--q
í	í	í-P	Pp3fs
féin	féin	féin-P	Px
?	?	?-F	Fq
Cad	Cad	cad-W	W--q
é	é	é-P	Pp3ms
thug	thug	tabhair-V	Vmis
a	a	a-D	Dp3
bás	bás	bás-N	Ncmsc
?	?	?-F	Fq
Cé	Cé	cé-P	Pq
a	a	a-Q	Q-r
chuir	chuir	cuir-V	Vmis
sa	sa	i-S	Spa-s
chaorán	chaorán	caorán-N	Ncmsc
í	í	í-P	Pp3fs
agus	agus	agus-C	Cc
cad	cad	cad-P	Pq|W--q
chuige	chuige	chuig-P	Pr3ms
?	?	?-F	Fq
Ceisteanna	Ceisteanna	ceist-N	Ncfpc
,	,	,-F	Fi
ceisteanna	ceisteanna	ceist-N	Ncfpc
,	,	,-F	Fi
ceisteanna	ceisteanna	ceist-N	Ncfpc
.	.	.-F	Fe
Is	Is	agus-C	Cc
gearr	gearr	gearr-V	Vmm-2s
gur	gur	gur-W	Wsdi|Q--s
thosaigh	thosaigh	tosach-V	Vmis|Ncmpc
na	na	na-T	Td-p
ráflaí	ráflaí	ráfla-N	Ncmpc|Ncmpg
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
cuimhne	cuimhne	cuimhne-N	Ncfsc
agat	agat	ag-P	Pr2-s
ar	ar	ar-N	Ncmsc
a	a	a-D	Dp3
leithéid	leithéid	leithéid-N	Ncfsc
siúd	siúd	siúd-P	Pd|Dd
de	de	de-S	Sp
bhean	bhean	bean-N	Ncfsc
a	a	a-Q	Q-r
chuaigh	chuaigh	téigh-V	Vmis
ar	ar	ar-S	Sp
iarraidh	iarraidh	iarr-N	Nv
i	i	i-S	Sp
Sligeach	Sligeach	Sligeach-N	Npmsc
tá	tá	bí-V	Vmip
bliain	bliain	bliain-N	Ncfsc
ó	ó	ó-S	Sp
shin	shin	sin-P	Pd
?	?	?-F	Fq
Bíodh	Bíodh	bí-V	Vmm-3s
geall	geall	geall-N	Ncmsc
gurb	gurb	is-W	Wpdi
in	in	sin-P	Pd
í	í	í-P	Pp3fs
í	í	í-P	Pp3fs
?	?	?-F	Fq
'	'	'-F	Fa
‘	‘	‘-X	Xx
Chuala	Chuala	clois-V	Vmis
mise	mise	mé-P	Pp1-s-e
fá	fá	faoi-P	Pr3ms
fhear	fhear	fear-N	Ncmsc
as	as	as-S	Sp
na	na	na-T	Tdfsg
Sé	Sé	Sé-N	Npmsc
Chontae	Chontae	contae-N	Ncmsg
a	a	a-Q	Q-r
mharaigh	mharaigh	maraigh-V	Vmis
a	a	a-D	Dp3
bhean	bhean	bean-N	Ncfsc
,	,	,-F	Fi
a	a	a-Q	Q-r
chuir	chuir	cuir-V	Vmis
a	a	a-D	Dp3
corp	corp	corp-N	Ncmsc
isteach	isteach	isteach-R	Rd
ina	ina	i-S	Spp-s
charr	charr	carr-N	Ncmsc|Ncfsc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmm-2s
léi	léi	le-P	Pr3fs
bealach	bealach	bealach-N	Ncmsc
inteacht	inteacht	tar-N	Ncmsc|Nv
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
gheall	gheall	geall-N	Ncmsc
gurb	gurb	is-W	Wpdi
in	in	sin-P	Pd
í	í	í-P	Pp3fs
.	.	.-F	Fe
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
na	na	na-T	Td-p
ráflaí	ráflaí	ráfla-N	Ncmpc
ag	ag	ag-S	Sp
éirí	éirí	éirigh-N	Nv
ní	ní	ní-N	Ncmsg
b	b	b-X	Xl
’	’	’-F	Fa
fhearr	fhearr	maith-A	Aqc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
sa	sa	i-S	Spa-s
deireadh	deireadh	deireadh-N	Ncmsc
tháinig	tháinig	tar-V	Vmis
ceann	ceann	ceann-N	Ncmsc
amháin	amháin	amháin-A	Aqp
ar	ar	ar-S	Sp
an	an	an-T	Td-s
tsaol	tsaol	saol-N	Ncfsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
craiceann	craiceann	craiceann-N	Ncmsc
na	na	na-T	Tdfsg
fírinne	fírinne	fírinne-N	Ncfsg
air	air	ar-P	Pr3ms
agus	agus	agus-C	Cc
creideadh	creideadh	creid-V	Vmis0
é	é	é-P	Pp3ms
.	.	.-F	Fe
Seo	Seo	seo-W	W
cnámha	cnámha	cnámh-N	Ncfpc
an	an	an-T	Td-s
scéil	scéil	scéal-N	Ncmsg
sin	sin	sin-D	Dd
:	:	:-F	Fi
Fear	Fear	fear-N	Ncmsc
as	as	as-S	Sp
ceantar	ceantar	ceantar-N	Ncmsc
scoite	scoite	scoith-A	Av
sa	sa	i-S	Spa-s
pharóiste	pharóiste	paróiste-N	Ncmsc
,	,	,-F	Fi
darbh	darbh	dar-W	Wpsi|Csws
ainm	ainm	ainm-N	Ncmsc
Seán	Seán	Seán-N	Npmsc
,	,	,-F	Fi
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ar	ar	ar-S	Sp
an	an	an-T	Td-s
choigríoch	choigríoch	coigríoch-N	Ncfsc
le	le	le-S	Sp
blianta	blianta	bliain-N	Ncfpc
,	,	,-F	Fi
phill	phill	pill-V	Vmis
sé	sé	sé-P	Pp3msn
agus	agus	agus-C	Cc
bean	bean	bean-N	Ncfsc
strainséartha	strainséartha	strainséartha-A	Aqp
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
siad	siad	siad-P	Pp3-pn
a	a	a-U	U
chónaí	chónaí	cónaigh-N	Nv
i	i	i-S	Sp
dteach	dteach	teach-N	Ncmsc
a	a	a-D	Dp3
mhuintire	mhuintire	muintir-N	Ncfsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
marbh	marbh	marbh-N	Ncmsc
le	le	le-S	Sp
fada	fada	fada-A	Aqp
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
cónaí	cónaí	cónaí-N	Ncmsc
sa	sa	i-S	Spa-s
teach	teach	teach-N	Ncmsc
le	le	le-S	Sp
blianta	blianta	bliain-N	Ncfpc
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
cóiriú	cóiriú	cóiriú-N	Ncmsc
a	a	a-D	Dp3
dhíth	dhíth	díth-N	Ncfsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Fuair	Fuair	faigh-V	Vmis
Seán	Seán	Seán-N	Npmsc
fear	fear	fear-N	Ncmsc
ceirde	ceirde	ceird-N	Ncfsg
leis	leis	le-S	Sp
an	an	an-T	Td-s
chóiriú	chóiriú	cóirigh-N	Nv
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
.	.	.-F	Fe
Lá	Lá	lá-N	Ncmsc
amháin	amháin	amháin-A	Aqp
phlástráil	phlástráil	plástráil-V	Vmis
siad	siad	siad-P	Pp3-pn
an	an	an-T	Td-s
simléir	simléir	simléar-N	Ncmpc
agus	agus	agus-C	Cc
díreach	díreach	díreach-N	Ncmpg|Ncmsc|Aqp
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
críochnaithe	críochnaithe	críochnaithe-A	Av|Aqp
thosaigh	thosaigh	tosaigh-V	Vmis
deora	deora	deora-N	Ncfpc|Ncfsc
fearthainne	fearthainne	fearthainn-N	Ncfsg|Nv--g--n
ag	ag	ag-S	Sp
titim	titim	tit-N	Nv
.	.	.-F	Fe
Isteach	Isteach	isteach-R	Rd
le	le	le-S	Sp
Seán	Seán	Seán-N	Npmsc
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
amach	amach	amach-R	Rd
píosa	píosa	píosa-N	Ncmsc
mór	mór	mór-N	Ncmpg
éadaigh	éadaigh	éadaigh-V	Vmis
–	–	–-X	Xx
bréidín	bréidín	bréidín-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Is	Is	is-W	Wp-i
cosúil	cosúil	cosúil-A	Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
duine	duine	duine-N	Ncmsc
inteacht	inteacht	tar-N	Ncmsc|Nv
sa	sa	i-S	Spa-s
teach	teach	teach-N	Ncmsc
ag	ag	ag-S	Sp
fíodóireacht	fíodóireacht	fíodóireacht-N	Ncfsc
tráth	tráth	tráth-N	Ncmsc
agus	agus	agus-C	Cc
nár	nár	nár-Q	Qnrs
críochnaíodh	críochnaíodh	críochnaigh-V	Vmis0--n
an	an	an-T	Td-s
gréasán	gréasán	gréasán-N	Ncmsc
seo	seo	seo-D	Dd
riamh	riamh	riamh-R	Rg
.	.	.-F	Fe
Cuireadh	Cuireadh	cuir-V	Vmis0|Ncmsc|Vmm-3s
an	an	an-T	Td-s
bréidín	bréidín	bréidín-N	Ncmsg|Ncmsc
thart	thart	thart-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
tsimléir	tsimléir	simléar-N	Ncmsg
lena	lena	le-S	Spp-s
chosaint	chosaint	cosain-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
fhearthainn	fhearthainn	fearthainn-N	Ncfsc
.	.	.-F	Fe
Oíche	Oíche	oíche-N	Ncfsc
amháin	amháin	amháin-A	Aqp
cúpla	cúpla	cúpla-N	Ncmsg|Ncmsc|Dq
mí	mí	mí-N	Ncfsc|Ncmsc|Ncmsg
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|Dd
bhí	bhí	bí-V	Vmis
fear	fear	fear-N	Ncmsc
as	as	as-S	Sp
Inbhear	Inbhear	inbhear-N	Ncmsc
ag	ag	ag-S	Sp
pilleadh	pilleadh	pill-N	Nv
chun	chun	chun-S	Sp
an	an	an-T	Td-s
bhaile	bhaile	baile-N	Ncmsg
as	as	as-S	Sp
Ard	Ard	ard-N	Ncmsc
an	an	an-T	Td-s
Rátha	Rátha	ráth-N	Ncmsg
agus	agus	agus-C	Cc
i	i	i-S	Sp
Mín	Mín	Mín-N	Npmsc
na	na	na-T	Td-p
mBradán	mBradán	bradán-N	Ncmpg
bhí	bhí	bí-V	Vmis
fear	fear	fear-N	Ncmsc
amuigh	amuigh	amuigh-R	Rl
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhealach	bhealach	bealach-N	Ncmsc
mhór	mhór	mór-A	Aq-msc
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
air	air	ar-P	Pr3ms
stad	stad	stad-V	Vmis
.	.	.-F	Fe
Seán	Seán	Seán-N	Npmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Dúirt	Dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
gur	gur	gur-Q	Q--s
chúlaigh	chúlaigh	cúlaigh-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
charr	charr	carr-N	Ncmsc|Ncfsc
suas	suas	suas-R	Rd
an	an	an-T	Td-s
portach	portach	portach-N	Ncmsc
áit	áit	áit-N	Ncfsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
dumpáil	dumpáil	dumpáil-N	Nv
bruscair	bruscair	bruscar-N	Ncmsg
ach	ach	ach-C	Cs
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
fágáil	fágáil	fág-N	Nv
go	go	go-Q	Q
deachaigh	deachaigh	deachaigh-V	Vmm-2s
an	an	an-T	Td-s
carr	carr	carr-N	Ncmsc|Ncfsc
in	in	i-S	Sp
abar	abar	abar-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
leantóir	leantóir	leantóir-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
charr	charr	carr-N	Ncfsc
ina	ina	i-S	Spr
raibh	raibh	bí-V	Vmis---d
spád	spád	spád-N	Ncfsc
agus	agus	agus-C	Cc
sluasaid	sluasaid	sluasaid-N	Ncfsc
agus	agus	agus-C	Cc
cuma	cuma	cuma-N	Ncfsg|Aqp|Ncfsc
orthu	orthu	ar-P	Pr3-p
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
siad	siad	siad-P	Pp3-pn
in	in	i-S	Sp
úsáid	úsáid	úsáid-N	Ncfsc
sa	sa	i-S	Spa-s
chaorán	chaorán	caorán-N	Ncmsc
gan	gan	gan-S	Sp
mhoill	mhoill	moill-N	Ncfsc
roimhe	roimhe	roimh-P	Pr3ms
sin	sin	sin-P	Pd
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
carr	carr	carr-N	Ncmsc|Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhealach	bhealach	bealach-N	Ncmsc
arís	arís	arís-R	Rg
acu	acu	ag-P	Pr3-p
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmm-2s
achan	achan	gach-D	Dq
a	a	a-D	Dp3
bhealach	bhealach	bealach-N	Ncmsc
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
sin	sin	sin-P	Pd|W
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
de	de	de-S	Sp
sin	sin	sin-P	Pd
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
fhacthas	fhacthas	feic-V	Vmis0--n
Seán	Seán	Seán-N	Npmsc
ní ba	ní ba	ní_ba-N	Ns-s
mhó	mhó	mór-A	Aqc
i	i	i-S	Sp
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd|Dd
.	.	.-F	Fe
I	I	i-S	Sp
dtaca	dtaca	taca-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
de	de	de-P	Pr3ms
ní	ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
duine	duine	duine-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
mórán	mórán	mórán-N	Ncmsc
di	di	do-P	Pr3fs
in	in	i-S	Sp
am	am	am-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
mar	mar	mar-C	Cs
nach	nach	is-W	Wprin
ndeachaigh	ndeachaigh	téigh-V	Vmis---d
sí	sí	sí-P	Pp3fsn
amach	amach	amach-R	Rd
i	i	i-S	Sp
measc	measc	measc-N	Ncmsc
an	an	an-T	Td-s
phobail	phobail	pobal-N	Ncmsg
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
fhacthas	fhacthas	feic-V	Vmis0--n
ise	ise	í-P	Pp3fs-e
ní ba	ní ba	ní_ba-N	Ns-s
mhó	mhó	mór-A	Aqc
ach	ach	ach-S	Sp
oiread	oiread	oiread-N	Ns-s
.	.	.-F	Fe
B	B	B-X	Xl
’	’	’-F	Fa
in	in	i-S	Sp
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
agus	agus	agus-C	Cc
scéal	scéal	scéal-N	Ncmsc
maith	maith	maith-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Glacadh	Glacadh	glac-V	Vmm-3s
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
ceisteanna	ceisteanna	ceist-N	Ncfpc
ag	ag	ag-S	Sp
gabháil	gabháil	gabh-N	Nv
thart	thart	thart-R	Rd
–	–	–-X	Xx
‘	‘	‘-X	Xx
Do	Do	do-S	Sp
bharúil	bharúil	barúil-N	Ncfsc
cá	cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
sé	sé	sé-P	Pp3msn
anois	anois	anois-R	Rt
?	?	?-F	Fq
'	'	'-F	Fa
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfaighfear	bhfaighfear	faigh-V	Vmif0--d
greim	greim	greim-N	Ncmsc
air	air	ar-P	Pr3ms
?	?	?-F	Fq
'	'	'-F	Fa
‘	‘	‘-X	Xx
An	An	an-Q	Qq
dtabharfar	dtabharfar	tabhair-V	Vmif0
ar ais	ar ais	ar_ais-R	Rd
go	go	go-S	Sp
hÉirinn	hÉirinn	Éire-N	Npfsd
é	é	é-P	Pp3ms
lena	lena	le-S	Spr
thriail	thriail	triail-V	Vmis
?	?	?-F	Fq
'	'	'-F	Fa
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfaighidh	bhfaighidh	faigh-V	Vmif---d
sé	sé	sé-P	Pp3msn
príosún	príosún	príosún-N	Ncmsc
?	?	?-F	Fq
'	'	'-F	Fa
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
go leor	go leor	go_leor-A	Aq|Ns-s|Rg
fianaise	fianaise	fianaise-N	Ncfsg
lena	lena	le-S	Spp-s
fháil	fháil	faigh-N	Nv
ciontach	ciontach	ciontach-N	Ncmpg|Ncmsc
?	?	?-F	Fq
'	'	'-F	Fa
…	…	…-F	Fi
agus	agus	agus-C	Cc
mar	mar	mar-C	Cs
sin	sin	sin-W	W
de	de	de-P	Pr3ms
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
anois	anois	anois-R	Rt
an	an	an-T	Td-s
fhírinne	fhírinne	fírinne-N	Ncfsc
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
le	le	le-S	Sp
cúpla	cúpla	cúpla-N	Ncmsc
bliain	bliain	bliain-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
seo	seo	seo-D	Dd
curtha	curtha	cuir-A	Av
ach	ach	ach-S	Sp|Cs
le	le	le-S	Sp
cúpla	cúpla	cúpla-N	Ncmsc
céad	céad	céad-N	Ncmsc|Mc
bliain	bliain	bliain-N	Ncfsc
.	.	.-F	Fe
Fágfaidh	Fágfaidh	fág-V	Vmif
muid	muid	muid-P	Pp1-p
an	an	an-T	Td-s
chuid	chuid	cuid-N	Ncfsc
eile	eile	eile-D	Dd
ag	ag	ag-S	Sp
an	an	an-T	Td-s
Dr	Dr	Dr-Y	Y
Raghnall	Raghnall	Raghnall-N	Np
Ó	Ó	Ó-U	Up
Floinn	Floinn	Floinn-N	Npmsc
,	,	,-F	Fi
Ard	Ard	ard-A	Aqp
‑	‑	‑-F	Fb
Mhúsaem	Mhúsaem	músaem-N	Ncmsc
na	na	na-T	Tdfsg
hÉireann	hÉireann	Éire-N	Npfsg
.	.	.-F	Fe
Seo	Seo	seo-W	W
a	a	a-D	Dp3
thuairisc	thuairisc	tuairisc-N	Ncfsc
:	:	:-F	Fi
Tugadh	Tugadh	tabhair-V	Vmis0
an	an	an-T	Td-s
corp	corp	corp-N	Ncmsc
go	go	go-S	Sp
Baile	Baile	Baile-N	Npmsc
Átha Cliath	Átha Cliath	Átha_Cliath-N	Npmsg
áit	áit	áit-N	Ncfsc
ar	ar	ar-S	Sp
tús	tús	tús-N	Ncmsc
le	le	le-S	Sp
scrúdú	scrúdú	scrúdaigh-N	Nv
níos	níos	níos-U	Uc
iomláine	iomláine	iomlán-A	Aqc
.	.	.-F	Fe
Sa	Sa	i-S	Spa-s
scrúdú	scrúdú	scrúdú-N	Ncmsc
sin	sin	sin-D	Dd
rinneadh	rinneadh	déan-V	Vmis0
x	x	x-Y	Y
‑	‑	‑-F	Fb
ghathú	ghathú	gathaigh-N	Nv
,	,	,-F	Fi
scanadh	scanadh	scan-V	Vmm-3s
CT	CT	CT-Y	Y
,	,	,-F	Fi
ionscópacht	ionscópacht	ionscópacht-N	Ncfsc
agus	agus	agus-C	Cc
anailís	anailís	anailís-N	Ncfsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
craiceann	craiceann	craiceann-N	Ncmsc
,	,	,-F	Fi
a	a	a-D	Dp3
cuid	cuid	cuid-N	Ncfsc
gruaige	gruaige	gruaig-N	Ncfsg
,	,	,-F	Fi
a	a	a-D	Dp3
cuid	cuid	cuid-N	Ncfsc
fiacla	fiacla	fiacail-N	Ncfpg
agus	agus	agus-C	Cc
páirteanna	páirteanna	páirt-N	Ncfpg|Ncfpc
eile	eile	eile-D	Dd
den	den	de-S	Spa-s
chorp	chorp	corp-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	is-W	Wp-in
bhfuarthas	bhfuarthas	faigh-V	Vmis0
amach	amach	amach-R	Rd
cúis	cúis	cúis-N	Ncfsc
a	a	a-D	Dp3
báis	báis	bás-N	Ncmsg
ná	ná	ná-C	Cs
ní	ní	is-W	Wp-in
bhfuarthas	bhfuarthas	faigh-V	Vmis0
aon	aon	aon-D	Dq
mhórchuid	mhórchuid	mórchuid-N	Ncfsc
eolais	eolais	eolas-N	Ncmsg
fána	fána	faoi-S	Spp-p|Spp-s
saol	saol	saol-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
soiléir	soiléir	soiléir-A	Aqp
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
díobháil	díobháil	díobháil-N	Ncfsc|Nv
a	a	a-D	Dp3
coda	coda	cuid-N	Ncfsg
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Ó	Ó	ó-S	Sp
scrúdú	scrúdú	scrúdú-N	Ncmsc
a	a	a-D	Dp3
cuid	cuid	cuid-N	Ncfsc
ingne	ingne	ionga-N	Ncfpg
ba	ba	is-W	Wsri
chosúil	chosúil	cosúil-A	Aqp
nach	nach	nach-Q	Qnrs
ndearna	ndearna	déan-V	Vmis---d
sí	sí	sí-P	Pp3fsn
obair	obair	obair-N	Ncfsc|Nv-----n
chrua	chrua	crua-A	Aqp|Ncmsg|Ncfsg
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
chosúil	chosúil	cosúil-A	Aqp
fosta	fosta	fosta-A	Aqp
gur	gur	gur-Q	Q--s
chónaigh	chónaigh	cónaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
in	in	i-S	Sp
áit	áit	áit-N	Ncfsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
toit	toit	toit-N	Ncfsc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
fhéadfadh	fhéadfadh	féad-V	Vmc
sé	sé	sé-P	Pp3msn
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
galar	galar	galar-N	Ncmsc
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
cuid	cuid	cuid-N	Ncfsc
scamhán	scamhán	scamhán-N	Ncmsc
.	.	.-F	Fe
chaomhnú	chaomhnú	caomhnú-N	Ncmsc
.	.	.-F	Fe
Le	Le	le-S	Sp
linn	linn	linn-N	Ncfsc
dó	dó	dóigh-N	Nv
a	a	a-U	U
bheith	bheith	bí-N	Nv
ansin	ansin	ansin-R	Rt|Rl
rinneadh	rinneadh	déan-V	Vmis0
dátú	dátú	dátaigh-N	Nv
carbóin	carbóin	carbón-N	Ncmsg|Ncmpc
air	air	ar-P	Pr3ms
agus	agus	agus-C	Cc
rinneadh	rinneadh	déan-V	Vmis0
amach	amach	amach-R	Rd
gur	gur	gur-Q	Q--s
mhair	mhair	mair-V	Vmis
sí	sí	sí-P	Pp3fsn
thart	thart	thart-R	Rd
fán	fán	fán-S	Spa-s|Ncmsc
seisiú	seisiú	seisiú-N	Nv
nó	nó	nó-C	Cc
an	an	an-T	Td-s
seachtú	seachtú	seacht-M	Mo
haois	haois	aois-N	Ncfsc
déag	déag	déag-N	Ns-s
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
corp	corp	corp-N	Ncmsc
faoi	faoi	faoi-S	Sp
láthair	láthair	láthair-N	Ncfsc
in	in	sin-S	Sp|Pd
Ard	Ard	ard-N	Ncmsc|Aqp
‑	‑	‑-F	Fb
Mhúsaem	Mhúsaem	músaem-N	Ncmsc
na	na	na-T	Tdfsg
hÉireann	hÉireann	Éire-N	Npfsg
ach	ach	ach-C	Cs
is	is	is-W	Wpri
annamh	annamh	annamh-A	Aqp
a	a	a-Q	Q-r
bhíonn	bhíonn	bí-V	Vmig
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
taispeáint	taispeáint	taispeáin-N	Nv
.	.	.-F	Fe
An	An	an-T	Td-s
chuid	chuid	cuid-N	Ncfsc
is	is	is-U	U
mó	mó	mór-A	Aqc
den	den	de-S	Spa-s
am	am	am-N	Ncmsc
bíonn	bíonn	bí-V	Vmig
sé	sé	sé-P	Pp3msn
thíos	thíos	thíos-R	Rd
sa	sa	i-S	Spa-s
siléar	siléar	siléar-N	Ncmsc
mar	mar	mar-C	Cs
nach	nach	is-W	Wprin
bhfuil	bhfuil	fuil-N	Ncfsc
go leor	go leor	go_leor-A	Aq
spáis	spáis	spás-N	Ncmsg
sna	sna	i-S	Spa-p
seomraí	seomraí	seomra-N	Ncmpc
taispeántais	taispeántais	taispeántas-N	Ncmsg|Ncmpc
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
baineadh	baineadh	bain-V	Vmis0--n
an	an	an-T	Td-s
bachta	bachta	bachta-N	Ncmsc
sin	sin	sin-D	Dd
den	den	de-S	Spa-s
phortach	phortach	portach-N	Ncmsc
ó	ó	ó-S	Sp
shin	shin	sin-P	Pd
.	.	.-F	Fe
