 Cian	Cian	-X	Xx
agus	agus	agus-C	Cc
an	an	an-T	Td-s
Bainisteoir	Bainisteoir	bainisteoir-N	Ncmsc
Bacach	Bacach	bacach-A	Aq-msc
Bhí	Bhí	bí-V	Vmis
Cian	Cian	Cian-N	Npmsc
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
taobhlíne	taobhlíne	taobhlíne-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
fuar	fuar	fuar-A	Aqp
agus	agus	agus-C	Cc
fliuch	fliuch	fliuch-V	Vmm-2s
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ba	ba	is-W	Ws|Ws-i
chuma	chuma	cuma-A	Aqp
.	.	.-F	Fe
Thaitin	Thaitin	taitin-V	Vmis
an	an	an-T	Td-s
iománaíocht	iománaíocht	iománaíocht-N	Ncfsc
leis	leis	le-P	Pr3ms
thar	thar	thar-S	Sp
aon	aon	aon-D	Dq
ní	ní	ní-N	Ncmsc
eile	eile	eile-D	Dd
ar	ar	ar-S	Sp
domhan	domhan	domhan-N	Ncmsc
.	.	.-F	Fe
Gleo	Gleo	gleo-N	Ncmsc
na	na	na-T	Td-p
gcamán	gcamán	camán-N	Ncmpg
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
ag	ag	ag-S	Sp
bualadh	bualadh	buail-N	Nv
in éadan	in éadan	in_éadan-S	Spc
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
An	An	an-T	Td-s
sliotar	sliotar	sliotar-N	Ncmsc
ag	ag	ag-S	Sp
eitilt	eitilt	eitil-N	Nv
ar	ar	ar-S	Sp
luas	luas	luas-N	Ncmsc
lasrach	lasrach	lasrach-A	Aq-msc
tríd	tríd	trí-S	Sp
an	an	an-T	Td-s
aer	aer	aer-N	Ncmsc
.	.	.-F	Fe
Na	Na	na-T	Td-p
himreoirí	himreoirí	imreoir-N	Ncmpc
,	,	,-F	Fi
báite	báite	báigh-A	Av
le	le	le-S	Sp
hallas	hallas	allas-N	Ncmsc
,	,	,-F	Fi
ag	ag	ag-S	Sp
béicíl	béicíl	béicíl-N	Nv-----n
go	go	go-U	Ua
bagrach	bagrach	bagrach-A	Aqp
ar	ar	is-W	Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
ag	ag	ag-S	Sp
screadaíl	screadaíl	screadaíl-N	Ncfsc
leo	leo	le-P	Pr3-p
in	in	sin-S	Sp|Pd
ard	ard	ard-N	Ncmsc|Aqp
a	a	a-D	Dp3
ghutha	ghutha	guth-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
sa	sa	i-S	Spa-s
bhaile	bhaile	baile-N	Ncmsc
ag	ag	ag-S	Sp
cniotáil	cniotáil	cniotáil-N	Nv
atá	atá	bí-V	Vmip---r
sibh	sibh	sibh-P	Pp2-p
anois	anois	anois-R	Rt
,	,	,-F	Fi
a	a	a-U	Uv
leisceoirí	leisceoirí	leisceoir-N	Ncmpv
lofa	lofa	lobh-A	Aqp|Av
!	!	!-F	Fe
'	'	'-F	Fa
Seachas	Seachas	seachas-S	Sp
Cian	Cian	Cian-N	Npmsc
agus	agus	agus-C	Cc
cúpla	cúpla	cúpla-N	Ncmsg|Ncmsc|Dq
seanóir	seanóir	seanóir-N	Ncmsc
,	,	,-F	Fi
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
mórán	mórán	mórán-N	Ncmsc
lucht	lucht	lucht-N	Ncmsc
leanúna	leanúna	lean-N	Ncfsg|Nv--g
ag	ag	ag-S	Sp
foireann	foireann	foireann-N	Ncfsc
na	na	na-T	Td-p
bhfear	bhfear	fear-N	Ncmpg
den	den	de-S	Spa-s
chlub	chlub	club-N	Ncmsc
iománaíochta	iománaíochta	iománaíocht-N	Ncfsg
Setanta	Setanta	Setanta-N	Npm-g|Npmsc
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
nach	nach	is-W	Wpsin|Wpdin
ionadh	ionadh	ionadh-N	Ncmsc
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
bhain	bhain	bain-V	Vmis---n
siad	siad	siad-P	Pp3-pn
cluiche	cluiche	cluiche-N	Ncmsc
le	le	le-S	Sp
haois	haois	aois-N	Ncfsc
cait	cait	cat-N	Ncmsg
.	.	.-F	Fe
Rith	Rith	rith-V	Vmm-2s|Vmis
na	na	na-T	Td-p
himreoirí	himreoirí	imreoir-N	Ncmpc
suas	suas	suas-R	Rd
síos	síos	síos-R	Rd
an	an	an-T	Td-s
pháirc	pháirc	páirc-N	Ncfsc
chuile	chuile	cuile-N	Ncfsg
Dhomhnach	Dhomhnach	Domhnach-N	Ncmsc
,	,	,-F	Fi
gan	gan	gan-S	Sp
ord	ord	ord-N	Ncmsc
gan	gan	gan-S	Sp
eagar	eagar	eagar-N	Ncmsc
,	,	,-F	Fi
go dtí	go dtí	go_dtí-S	Spc
gur	gur	gur-W	Wsdi|Q--s
séideadh	séideadh	séideadh-V	Vmis0|Nv|Ncmsc
an	an	an-T	Td-s
fhead	fhead	fead-N	Ncfsc
deiridh	deiridh	deireadh-N	Ncmsg
.	.	.-F	Fe
Chrom	Chrom	crom-V	Vmis
Cian	Cian	Cian-N	Npmsc
a	a	a-D	Dp3
cheann	cheann	ceann-N	Ncmsc
le	le	le-S	Sp
náire	náire	náire-N	Ncfsc
.	.	.-F	Fe
Cluiche	Cluiche	cluiche-N	Ncmsc
eile	eile	eile-D	Dd
caillte	caillte	caill-A	Av
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
ag	ag	ag-S	Sp
eascainí	eascainí	eascainigh-N	Nv
gan	gan	gan-S	Sp
náire	náire	náire-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	a-D	Dp3
leisceoirí	leisceoirí	leisceoir-N	Ncmpc
lofa	lofa	lobh-A	Av
!	!	!-F	Fe
Táim	Táim	bí-V	Vmip1s
náirithe	náirithe	náirigh-N	Ncmpc|Av
ceart	ceart	ceart-A	Aqp|Aq--pg|Aq-msc
agaibh	agaibh	ag-P	Pr2-p
!	!	!-F	Fe
Mise	Mise	mé-P	Pp1-s-e
!	!	!-F	Fe
An	An	an-T	Td-s
fear	fear	fear-N	Ncmsc
a	a	a-Q	Q-r
bhuaigh	bhuaigh	buaigh-V	Vmis
trófaí	trófaí	tró-V	Vmc-0
Chú	Chú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
tráth	tráth	tráth-N	Ncmsc
!	!	!-F	Fe
Náirithe	Náirithe	náiriú-A	Av|Ncmpc
glan	glan	glan-A	Aq-msc|Aq--pg|Aqp
agaibh	agaibh	ag-P	Pr2-p
!	!	!-F	Fe
'	'	'-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
Cian	Cian	Cian-N	Npmsc
ar	ar	ar-S	Sp
na	na	na-T	Td-p
himreoirí	himreoirí	imreoir-N	Ncmpc
bochta	bochta	bocht-A	Aq--pc
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
ag	ag	ag-S	Sp
fágáil	fágáil	fág-N	Nv
na	na	na-T	Tdfsg
páirce	páirce	páirc-N	Ncfsg
.	.	.-F	Fe
Cibé	Cibé	cibé-P	Pi|Dq
díograis	díograis	díograis-N	Ncfsc
agus	agus	agus-C	Cc
cibé	cibé	cibé-P	Pi|Dq
spreacadh	spreacadh	spreacadh-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
iontu	iontu	i-P	Pr3-p
an	an	an-T	Td-s
mhaidin	mhaidin	maidin-N	Ncfsc
sin	sin	sin-D	Dd
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
ídithe	ídithe	ídigh-A	Av
anois	anois	anois-R	Rt
.	.	.-F	Fe
Bhuail	Bhuail	buail-V	Vmis
taom	taom	taom-N	Ncmsc
feirge	feirge	fearg-N	Ncfsg
Cian	Cian	Cian-N	Npm-g|Npmsc
.	.	.-F	Fe
Theastaigh	Theastaigh	teastaigh-V	Vmis
uaidh	uaidh	ó-P	Pr3ms
focal	focal	focal-N	Ncmsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
aige	aige	ag-P	Pr3ms
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbainisteoir	mbainisteoir	bainisteoir-N	Ncmsc
.	.	.-F	Fe
Theastaigh	Theastaigh	teastaigh-V	Vmis
uaidh	uaidh	ó-P	Pr3ms
a	a	a-D	Dp3
leabhar	leabhar	leabhar-N	Ncmsc
beag	beag	beag-A	Aq-msc
dubh	dubh	dubh-A	Aq-msc
a	a	a-U	U
thaispeáint	thaispeáint	taispeáin-N	Nv
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
Leabhar	Leabhar	leabhar-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
lán	lán	lán-N	Ncmsc
le	le	le-S	Sp
straitéisí	straitéisí	straitéis-N	Ncmsc|Ncfpc
imeartha	imeartha	imir-A	Aqp|Av
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
oibrithe	oibrithe	oibriú-N	Ncmpc|Av|Ncmpc
amach	amach	amach-R	Rd
go	go	go-U	Ua
cúramach	cúramach	cúramach-A	Aqp
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Straitéisí	Straitéisí	straitéis-N	Ncmsc|Ncfpc
a	a	a-Q	Q-r
thógfadh	thógfadh	tóg-V	Vmc
foireann	foireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npmsc
chuig	chuig	chuig-S	Sp
Páirc	Páirc	páirc-N	Ncfsc
an	an	an-Q	Qq
Chrócaigh	Chrócaigh	crócaigh-V	Vmis
go	go	go-U	Ua
cinnte	cinnte	cinnte-A	Av|Aqp
!	!	!-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
eagla	eagla	eagla-N	Ncfsc
ar	ar	ar-S	Sp
Chian	Chian	Cian-N	Npmsc
labhairt	labhairt	labhair-N	Ncfsc|Nv
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbainisteoir	mbainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
.	.	.-F	Fe
Fear	Fear	fear-N	Ncmsc
crosta	crosta	cros-A	Aqp|Av
bagrach	bagrach	bagrach-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
in	in	i-S	Sp
amanna	amanna	am-N	Ncmpc
.	.	.-F	Fe
Fear	Fear	fear-N	Ncmsc
dímhúinte	dímhúinte	dímhúinte-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
trófaí	trófaí	tró-V	Vmc-0
Chú	Chú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
gnóthaithe	gnóthaithe	gnóthaigh-A	Av
aige	aige	ag-P	Pr3ms
ina	ina	i-S	Spp-s
óige	óige	óige-N	Ncfsc
,	,	,-F	Fi
trófaí	trófaí	tró-V	Vmc-0
a	a	a-D	Dp3
chruthaigh	chruthaigh	cruthach-A	Aq-msg|Aq-msv
,	,	,-F	Fi
dar	dar	dar-V	Vmip
leis	leis	le-P	Pr3ms
,	,	,-F	Fi
gur	gur	is-W	Wsdi|Wpdi
saineolaí	saineolaí	saineolach-A	Aqc
é	é	é-P	Pp3ms
ar	ar	ar-S	Sp
chúrsaí	chúrsaí	cúrsa-N	Ncmpc
iománaíochta	iománaíochta	iománaíocht-N	Ncfsg
.	.	.-F	Fe
In	In	sin-P	Pd
ainneoin	ainneoin	ainneoin-C	Cs
a	a	a-Q	Q-r
thrófaí	thrófaí	tró-V	Vmc-0
cháiliúil	cháiliúil	cáiliúil-A	Aqp
,	,	,-F	Fi
áfach	áfach	áfach-R	Rg
,	,	,-F	Fi
ba	ba	is-W	Wsri
léir	léir	léir-A	Aqp
do	do	do-S	Sp
Chian	Chian	Cian-N	Npmsc
agus	agus	agus-C	Cc
do	do	do-S	Sp
mhórán	mhórán	mórán-N	Ncmsc
den	den	de-S	Spa-s
phobal	phobal	pobal-N	Ncmsc
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
a	a	a-Q	Q-r
chumas	chumas	cum-V	Vmis1s
straitéisí	straitéisí	straitéis-N	Ncmsc|Ncfpc
imeartha	imeartha	imir-A	Aqp|Av
a	a	a-U	U
oibriú	oibriú	oibrigh-N	Nv
amach	amach	amach-R	Rd
d	d	d-X	Xl
’	’	’-F	Fa
fhoireann	fhoireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g|Npmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
Cian	Cian	Cian-N	Npmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbainisteoir	mbainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
bís	bís	bís-N	Ncfsc
le	le	le-S	Sp
dul	dul	téigh-N	Nv
chun	chun	chun-S	Sp
cainte	cainte	caint-N	Ncfsg|Nv--g--n
leis	leis	le-P	Pr3ms
ach	ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
a	a	a-D	Dp3
chosa	chosa	cos-N	Ncfpc
greamaithe	greamaithe	greamaigh-A	Av
den	den	de-S	Spa-s
spota	spota	spota-N	Ncmsc
.	.	.-F	Fe
Cén	Cén	cé-D	Dw--s
fáth	fáth	fáth-N	Ncmsc
a	a	a-Q	Q-i
n	n	n-X	Xl
‑	‑	‑-F	Fb
éisteodh	éisteodh	éistigh-V	Vmc
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
le	le	le-S	Sp
buachaill	buachaill	buachaill-N	Ncmsc
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
ach	ach	ach-S	Sp
dhá	dhá	dó-M	Mc
bhliain	bhliain	bliain-N	Ncfsc
déag	déag	déag-N	Ns-s
d	d	d-X	Xl
’	’	’-F	Fa
aois	aois	aois-N	Ncfsc
?	?	?-F	Fq
Chun	Chun	chun-S	Sp
comhairle	comhairle	comhairle-N	Ncfsg
a	a	a-U	U
chur	chur	cuir-N	Nv
air	air	ar-N	Ncmsg|Pr3ms|Ncmsg
maidir le	maidir le	maidir_le-S	Sp
foireann	foireann	foireann-N	Ncfsc
daoine	daoine	duine-N	Ncmpg|Ncmpc
fásta	fásta	fás-A	Aqp|Av
!	!	!-F	Fe
Buachaill	Buachaill	buachaill-N	Ncmsc
nár	nár	nár-Q	Qnrs
éirigh	éirigh	éirigh-V	Vmis---n
leis	leis	le-P	Pr3ms
áit	áit	áit-N	Ncfsc
a	a	a-U	U
fháil	fháil	faigh-N	Nv
ar	ar	ar-S	Sp
fhoireann	fhoireann	foireann-N	Ncfsc
B	B	B-X	Xl
na	na	na-T	Tdfsg
scoile	scoile	scoil-N	Ncfsg
fiú	fiú	fiú-N	Ncmsg|Ncmsc|Rg|Ns-s
!	!	!-F	Fe
Cé	Cé	cé-C	Cs
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
mhaith	mhaith	maith-N	Ncfsc
le	le	le-S	Sp
Cian	Cian	Cian-N	Npmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bpáirc	bpáirc	páirc-N	Ncfsc
imeartha	imeartha	imir-A	Aqp|Av
,	,	,-F	Fi
áfach	áfach	áfach-R	Rg
,	,	,-F	Fi
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
tada	tada	tada-N	Ncmsc
faoin	faoin	faoi-S	Spa-s
iománaíocht	iománaíocht	iománaíocht-N	Ncfsc
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
ar	ar	ar-S	Sp
eolas	eolas	eolas-N	Ncmsc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
éist	éist	éist-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-U	Ua
cúramach	cúramach	cúramach-A	Aqp
leis	leis	le-S	Sp
na	na	na-T	Td-p
saineolaithe	saineolaithe	saineolaí-N	Ncmpc
spóirt	spóirt	spórt-N	Ncmsg|Ncmpc|Ncmsg
ar	ar	ar-S	Sp
an	an	an-T	Td-s
raidió	raidió	raidió-N	Ncmsc
agus	agus	agus-C	Cc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
teilifís	teilifís	teilifís-N	Ncfsc
.	.	.-F	Fe
Léigh	Léigh	léigh-V	Vmis
sé	sé	sé-P	Pp3msn
na	na	na-T	Td-p
leathanaigh	leathanaigh	leathanach-N	Ncmpc
spóirt	spóirt	spórt-N	Ncmsg|Ncmpc|Ncmsg
sna	sna	i-S	Spa-p
nuachtáin	nuachtáin	nuachtán-N	Ncmpc
.	.	.-F	Fe
Chuartaigh	Chuartaigh	cuartaigh-V	Vmis
sé	sé	sé-P	Pp3msn
blaganna	blaganna	blag-N	Ncmpc
faoin	faoin	faoi-S	Spa-s
gcluiche	gcluiche	cluiche-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
idirlíon	idirlíon	idirlíon-N	Ncmsc
.	.	.-F	Fe
Níorbh	Níorbh	is-W	Ws-in
fhada	fhada	fada-A	Aqc|Aqp
gur	gur	gur-Q	Q--s
thuig	thuig	tuig-V	Vmip|Vmis
sé	sé	sé-P	Pp3msn
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
in	in	i-S	Sp
easnamh	easnamh	easnamh-N	Ncmsc
ar	ar	ar-S	Sp
fhoireann	fhoireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g
ach	ach	ach-S	Sp
beagáinín	beagáinín	beagán-N	Ncmsc|Ncmpc
treorach	treorach	treorach-N	Ncfsg|Ncmpg
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
Cian	Cian	Cian-N	Npmsc
ag	ag	ag-S	Sp
oibriú	oibriú	oibrigh-N	Nv
amach	amach	amach-R	Rd
straitéisí	straitéisí	straitéisí-N	Ncfpc|Ncmsc
imeartha	imeartha	imir-A	Av
don	don	do-S	Spa-s
fhoireann	fhoireann	foireann-N	Ncfsc
.	.	.-F	Fe
Oíche	Oíche	oíche-N	Ncfsc
i ndiaidh	i ndiaidh	i_ndiaidh-S	Spc
oíche	oíche	oíche-N	Ncfsg
,	,	,-F	Fi
d	d	d-X	Xl
’	’	’-F	Fa
oibrigh	oibrigh	oibrigh-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-U	Ua
crua	crua	crua-A	Aqp
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
chuid	chuid	cuid-N	Ncfsc
pleananna	pleananna	plean-N	Ncmpg
.	.	.-F	Fe
Tharraing	Tharraing	tarraing-V	Vmis
sé	sé	sé-P	Pp3msn
léaráidí	léaráidí	léaráid-N	Ncfpc
móra	móra	mór-A	Aq--pc
agus	agus	agus-C	Cc
léaráidí	léaráidí	léaráid-N	Ncfpc
beaga	beaga	beag-A	Aq--pg|Aq--pc|Aq--pv
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
Mac	Mac	mac-N	Ncmsc
an	an	an-T	Td-s
Easpaig	Easpaig	Easpaig-N	Npmsg|Npfsg
sa	sa	i-S	Spa-s
chúl	chúl	cúl-N	Ncmsc
.	.	.-F	Fe
Tharraing	Tharraing	tarraing-V	Vmis
sé	sé	sé-P	Pp3msn
siar	siar	siar-R	Rd
Ó	Ó	Ó-U	Up
Tuama	Tuama	Tuama-N	Npmsc
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
Ó	Ó	Ó-U	Up
Dubhthaigh	Dubhthaigh	Dubhthaigh-N	Np
i lár	i lár	i_lár-S	Spc
na	na	na-T	Tdfsg
páirce	páirce	páirc-N	Ncfsg
is	is	agus-C	Cc
thug	thug	tabhair-V	Vmis
sé	sé	sé-P	Pp3msn
bata	bata	bata-N	Ncmsc
is	is	agus-C	Cc
bóthar	bóthar	bóthar-N	Ncmsc
do	do	do-S	Sp
Liam	Liam	Liam-N	Npmsc
Ó	Ó	Ó-U	Up
Cualáin	Cualáin	Cualáin-N	Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
na	na	na-T	Td-p
straitéisí	straitéisí	straitéis-N	Ncfpc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
scríofa	scríofa	scríobh-A	Av
síos	síos	síos-R	Rd
aige	aige	ag-P	Pr3ms
ina	ina	i-S	Spp-s|Spp-p
leabhar	leabhar	leabhar-N	Ncmsc
beag	beag	beag-A	Aq-msc
dubh	dubh	dubh-A	Aq-msc
.	.	.-F	Fe
Shiúil	Shiúil	siúil-V	Vmis
Cian	Cian	Cian-N	Npmsc
i	i	i-S	Sp
dtreo	dtreo	treo-N	Ncmsc
an	an	an-T	Td-s
bhainisteora	bhainisteora	bainisteoir-N	Ncmsg
.	.	.-F	Fe
Stop	Stop	stop-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
fhéadfadh	fhéadfadh	féad-V	Vmc----n
seisean	seisean	sé-P	Pp3msne
comhairle	comhairle	comhairle-N	Ncfsc
a	a	a-U	U
chur	chur	cuir-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhfear	bhfear	fear-N	Ncmsc
a	a	a-Q	Q-r
ghnóthaigh	ghnóthaigh	gnóthaigh-V	Vmis
trófaí	trófaí	tró-V	Vmc-0
Chú	Chú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
tráth	tráth	tráth-N	Ncmsc
!	!	!-F	Fe
Chaith	Chaith	caith-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
leabhar	leabhar	leabhar-N	Ncmsc
beag	beag	beag-A	Aq-msc
dubh	dubh	dubh-A	Aq-msc
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
mbosca	mbosca	bosca-N	Ncmsc
bruscair	bruscair	bruscar-N	Ncmsg
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
sé	sé	sé-P	Pp3msn
aghaidh	aghaidh	aghaidh-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbaile	mbaile	baile-N	Ncmsc
agus	agus	agus-C	Cc
croí	croí	croí-N	Ncmsc
trom	trom	trom-A	Aq-msc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Sheas	Sheas	seas-V	Vmis
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
ina	ina	i-S	Spp-s
aonar	aonar	aonar-N	Ncmsc
ag	ag	ag-S	Sp
taobh	taobh	taobh-N	Ncmsc
na	na	na-T	Tdfsg
páirce	páirce	páirc-N	Ncfsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
chuile	chuile	gach-D	Dq
dhuine	dhuine	duine-N	Ncmsc
eile	eile	eile-D	Dd
imithe	imithe	imigh-A	Av
abhaile	abhaile	abhaile-R	Rd
faoi	faoi	faoi-S	Sp
seo	seo	seo-P	Pd
.	.	.-F	Fe
Cluiche	Cluiche	cluiche-N	Ncmsc
eile	eile	eile-D	Dd
caillte	caillte	caill-A	Av
.	.	.-F	Fe
Domhnach	Domhnach	Domhnach-N	Ncmsc
eile	eile	eile-D	Dd
curtha	curtha	cuir-A	Av
amú	amú	amaigh-R	Rg|Nv
.	.	.-F	Fe
Smaoinigh	Smaoinigh	smaoinigh-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-N	Ncmsc
an	an	an-Q	Qq
trófaí	trófaí	tró-V	Vmc-0
a	a	a-D	Dp3
bhí	bhí	bí-N	Ncfsc
ina	ina	i-S	Spp-s
shuí	shuí	suí-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
matal	matal	matal-N	Ncmsc
sa	sa	i-S	Spa-s
bhaile	bhaile	baile-N	Ncmsc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Trófaí	Trófaí	tró-V	Vmc-0
Chú	Chú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
,	,	,-F	Fi
t	t	t-X	Xl
‑	‑	‑-F	Fb
iománaí	iománaí	iománaí-N	Ncmsc
is	is	is-U	U
fearr	fearr	maith-A	Aqc
a	a	a-Q	Q-r
thóg	thóg	tóg-V	Vmis
camán	camán	camán-N	Ncmsc
ina	ina	i-S	Spp-s|Spp-p
lámh	lámh	lámh-N	Ncfsc
riamh	riamh	riamh-R	Rg
.	.	.-F	Fe
Lig	Lig	lig-V	Vmis
sé	sé	sé-P	Pp3msn
osna	osna	osna-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
tada	tada	tada-N	Ncmsc
ar	ar	ar-S	Sp
domhan	domhan	domhan-N	Ncmsc
ab	ab	is-W	Wsri
fhearr	fhearr	maith-A	Aqc
leis	leis	le-P	Pr3ms
ach	ach	ach-S	Sp
foireann	foireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
chomh	chomh	chomh-R	Ri
fada	fada	fada-A	Aqp
le	le	le-S	Sp
Páirc	Páirc	páirc-N	Ncfsc
an	an	an-Q	Qq
Chrócaigh	Chrócaigh	crócaigh-V	Vmis
lá	lá	lá-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
.	.	.-F	Fe
Rug	Rug	beir-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
chamán	chamán	camán-N	Ncmsc
is	is	agus-C	Cc
thug	thug	tabhair-V	Vmis
poc	poc	poc-N	Ncmsc
mór	mór	mór-A	Aq-msc
fada	fada	fada-A	Aqp
trasna	trasna	trasna-S	Sp
na	na	na-T	Tdfsg
páirce	páirce	páirc-N	Ncfsg
dá	dá	do-S	Spp-s
shliotar	shliotar	sliotar-N	Ncmsc
.	.	.-F	Fe
Suas	Suas	suas-R	Rd
,	,	,-F	Fi
suas	suas	suas-R	Rd
,	,	,-F	Fi
suas	suas	suas-R	Rd
san	san	i-S	Spa-s
aer	aer	aer-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
sliotar	sliotar	sliotar-N	Ncmsc
gur	gur	gur-Q	Q--s
thit	thit	tit-V	Vmis
sé	sé	sé-P	Pp3msn
faoi	faoi	faoi-S	Sp
dheireadh	dheireadh	deireadh-N	Ncmsc
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
mbosca	mbosca	bosca-N	Ncmsc
bruscair	bruscair	bruscar-N	Ncmsg
.	.	.-F	Fe
Shiúil	Shiúil	siúil-V	Vmis
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
trasna	trasna	trasna-S	Sp
na	na	na-T	Tdfsg
páirce	páirce	páirc-N	Ncfsg
lena	lena	le-S	Spp-s
shliotar	shliotar	sliotar-N	Ncmsc
a	a	a-U	U
fháil	fháil	faigh-N	Nv
ar ais	ar ais	ar_ais-R	Rd
.	.	.-F	Fe
Nach	Nach	is-W	Wpsin
air	air	ar-P	Pr3ms
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
t	t	t-X	Xl
‑	‑	‑-F	Fb
iontas	iontas	iontas-N	Ncmsc
leabhar	leabhar	leabhar-N	Ncmsc
beag	beag	beag-A	Aq-msc
dubh	dubh	dubh-A	Aq-msc
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
sa	sa	i-S	Spa-s
bhosca	bhosca	bosca-N	Ncmsc
bruscair	bruscair	bruscar-N	Ncmsg|Ncmpc
taobh	taobh	taobh-N	Ncmsc
lena	lena	le-S	Spp-s
shliotar	shliotar	sliotar-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
sé	sé	sé-P	Pp3msn
mórthimpeall	mórthimpeall	mórthimpeall-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
éinne	éinne	duine-N	Ncmsc
le	le	le-S	Sp
feiceáil	feiceáil	feic-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
aonar	aonar	aonar-N	Ncmsc
.	.	.-F	Fe
Go	Go	go-U	Ua
sciobtha	sciobtha	sciob-A	Aqp|Av
,	,	,-F	Fi
phioc	phioc	pioc-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
leabhar	leabhar	leabhar-N	Ncmsc
beag	beag	beag-A	Aq-msc
dubh	dubh	dubh-A	Aq-msc
amach	amach	amach-R	Rd
as	as	as-S	Sp
an	an	an-T	Td-s
mbosca	mbosca	bosca-N	Ncmsc
bruscair	bruscair	bruscar-N	Ncmsg|Ncmpc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
oscail	oscail	oscail-V	Vmm-2s
é	é	é-P	Pp3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
léaráidí	léaráidí	léaráid-N	Ncfpc
tarraingthe	tarraingthe	tarraing-A	Av
ar	ar	ar-S	Sp
chuile	chuile	cuile-N	Ncfsc
leathanach	leathanach	leathanach-N	Ncmpg
.	.	.-F	Fe
Léaráidí	Léaráidí	léaráid-N	Ncfpc
móra	móra	mór-A	Aq--pc
agus	agus	agus-C	Cc
léaráidí	léaráidí	léaráid-N	Ncfpc
beaga	beaga	beag-A	Aq--pg|Aq--pc|Aq--pv
.	.	.-F	Fe
Léaráidí	Léaráidí	léaráid-N	Ncfpc
a	a	a-Q	Q-r
thaispeáin	thaispeáin	taispeáin-V	Vmis
an	an	an-T	Td-s
áit	áit	áit-N	Ncfsc
is	is	is-U	U
fearr	fearr	maith-A	Aqc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bpáirc	bpáirc	páirc-N	Ncfsc
do	do	do-S	Sp
chuile	chuile	cuile-N	Ncfsc
imreoir	imreoir	imreoir-N	Ncmsc
as	as	as-S	Sp
foireann	foireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g
i lár	i lár	i_lár-S	Spc
cluiche	cluiche	cluiche-N	Ncmsg
.	.	.-F	Fe
Straitéisí	Straitéisí	straitéis-N	Ncmsc|Ncfpc
imeartha	imeartha	imir-A	Aqp|Av
chuile	chuile	cuile-N	Ncfsg
cheann	cheann	ceann-N	Ncmpg
acu	acu	ag-P	Pr3-p
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
oibrithe	oibrithe	oibriú-N	Ncmpc|Av|Ncmpc
amach	amach	amach-R	Rd
go	go	go-U	Ua
cúramach	cúramach	cúramach-A	Aqp
néata	néata	néata-A	Aqp
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
mbainisteoir	mbainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
an	an	an-Q	Qq
raibh	raibh	bí-V	Vmis---d
aon	aon	aon-D	Dq
mhaith	mhaith	maith-N	Ncfsc
leo	leo	le-P	Pr3-p
nó	nó	nó-C	Cc
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
aige	aige	ag-P	Pr3ms
rud	rud	rud-N	Ncmsc
amháin	amháin	amháin-A	Aqp
.	.	.-F	Fe
B	B	B-X	Xl
’	’	’-F	Fa
fhiú	fhiú	fiú-N	Ns-s
iad	iad	iad-P	Pp3-p
a	a	a-U	U
thriail	thriail	triail-N	Nv
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
fhéadfadh	fhéadfadh	féad-V	Vmc----n
cúrsaí	cúrsaí	cúrsa-N	Ncmpc
éirí	éirí	éirigh-N	Nv|Ncmsg|Nv--g|Ncmsg|Ncmsc|Nv|Nv--g
faic	faic	faic-N	Ncfsg|Ncfsc
níos	níos	níos-U	Uc
measa	measa	olc-A	Aqc
ná	ná	ná-C	Cs|Cc
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
,	,	,-F	Fi
ar	ar	ar-S	Sp
aon	aon	aon-D	Dq
chaoi	chaoi	caoi-N	Ncfsc
.	.	.-F	Fe
I	I	i-S	Sp
bpreab	bpreab	preab-N	Ncfsc
na	na	na-T	Td-p
súl	súl	súil-N	Ncfpg
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
leabhar	leabhar	leabhar-N	Ncmsc
beag	beag	beag-A	Aq-msc
dubh	dubh	dubh-A	Aq-msc
ina	ina	i-S	Spp-s
phóca	phóca	póca-N	Ncmsc
aige	aige	ag-P	Pr3ms
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbaile	mbaile	baile-N	Ncmsc
.	.	.-F	Fe
Den	Den	de-S	Spa-s
chéad	chéad	céad-M	Mo
uair	uair	uair-N	Ncfsc
le	le	le-S	Sp
blianta	blianta	bliain-N	Ncfpc
fada	fada	fada-A	Aqp
d	d	d-X	Xl
’	’	’-F	Fa
fhan	fhan	fan-V	Vmis
Cian	Cian	Cian-N	Npmsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
mbaile	mbaile	baile-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
Domhnach	Domhnach	Domhnach-N	Ncmsc
in	in	i-S	Sp
áit	áit	áit-N	Ncfsc
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
chuig	chuig	chuig-S	Sp
an	an	an-T	Td-s
gcluiche	gcluiche	cluiche-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
iontas	iontas	iontas-N	Ncmsc
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
mham	mham	mam-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
iontas	iontas	iontas-N	Ncmsc
níos	níos	níos-U	Uc
mó	mó	mór-A	Aqc
uirthi	uirthi	ar-P	Pr3fs
nuair	nuair	nuair-C	Cs
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
inis	inis	inis-N	Npmsc
Cian	Cian	Cian-N	Npm-g|Npmsc
di	di	do-P	Pr3fs
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
réidh	réidh	réidh-A	Aqp
leis	leis	le-S	Sp
an	an	an-T	Td-s
iománaíocht	iománaíocht	iománaíocht-N	Ncfsc
agus	agus	agus-C	Cc
le	le	le-S	Sp
foireann	foireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ba	ba	is-W	Ws|Ws-i
ar	ar	ar-S	Sp
Chian	Chian	Cian-N	Npmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
t	t	t-X	Xl
‑	‑	‑-F	Fb
iontas	iontas	iontas-N	Ncmsc
ba	ba	is-U	U
mhó	mhó	mór-A	Aqc
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
sin	sin	sin-D	Dd
.	.	.-F	Fe
Mar	Mar	mar-C	Cs
,	,	,-F	Fi
ar	ar	ar-S	Sp
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
sin	sin	sin-D	Dd
,	,	,-F	Fi
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
ar	ar	ar-Q	Q-is
fhan	fhan	fan-V	Vmis
Cian	Cian	Cian-N	Npmsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
mbaile	mbaile	baile-N	Ncmsc
is	is	agus-C	Cc
nach	nach	nach-Q	Qnrs
ndeachaigh	ndeachaigh	téigh-V	Vmis---d
sé	sé	sé-P	Pp3msn
chuig	chuig	chuig-S	Sp
an	an	an-T	Td-s
gcluiche	gcluiche	cluiche-N	Ncmsc
,	,	,-F	Fi
bhain	bhain	bain-V	Vmis
foireann	foireann	foireann-N	Ncfsc
An	An	an-T	Td-s
Domhnach	Domhnach	Domhnach-N	Ncmsc
dár	dár	de-S	Spp-p
gcionn	gcionn	ceann-N	Ncfsd
bhí	bhí	bí-V	Vmis
Cian	Cian	Cian-N	Npmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcéad	gcéad	céad-M	Mo
duine	duine	duine-N	Ncmsc|Ncmsg
ar	ar	ar-S	Sp
an	an	an-T	Td-s
taobhlíne	taobhlíne	taobhlíne-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
céilí	céilí	céile-N	Ncmsc|Ncmpc
ar	ar	ar-S	Sp
siúl	siúl	siúil-N	Nv
ina	ina	i-S	Spp-s
bholg	bholg	bolg-N	Ncmsc
is	is	agus-C	Cc
bhí	bhí	bí-V	Vmis
t	t	t-X	Xl
‑	‑	‑-F	Fb
allas	allas	allas-N	Ncmsc
ina	ina	i-S	Spp-s|Spp-p
rith	rith	rith-N	Ncmsc
lena	lena	le-S	Spp-s
bhosa	bhosa	bos-N	Ncfpc
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
an	an	an-T	Td-s
cluiche	cluiche	cluiche-N	Ncmsc
faoi	faoi	faoi-S	Sp
dheireadh	dheireadh	deireadh-N	Ncmsc
.	.	.-F	Fe
Níorbh	Níorbh	is-W	Ws-in
fhada	fhada	fada-A	Aqc|Aqp
gur	gur	gur-Q	Q--s
thuig	thuig	tuig-V	Vmip|Vmis
Cian	Cian	Cian-N	Npmsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
rud	rud	rud-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
difriúil	difriúil	difriúil-A	Aq-msc
faoi	faoi	faoi-S	Sp
fhoireann	fhoireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
plean	plean	plean-N	Ncmsc
ag	ag	ag-S	Sp
na	na	na-T	Td-p
himreoirí	himreoirí	imreoir-N	Ncmpc
,	,	,-F	Fi
murab	murab	mura-C	Csws
ionann	ionann	ionann-A	Aqp
is	is	is-U	U
cluichí	cluichí	cluicheach-A	Aqc
eile	eile	eile-D	Dd
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
rith	rith	rith-N	Nv
suas	suas	suas-R	Rd
síos	síos	síos-R	Rd
an	an	an-T	Td-s
pháirc	pháirc	páirc-N	Ncfsc
gan	gan	gan-S	Sp
ord	ord	ord-N	Ncmsc
gan	gan	gan-S	Sp
eagar	eagar	eagar-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
imreoirí	imreoirí	imreoir-N	Ncmpc
na	na	na-T	Td-p
foirne	foirne	foireann-N	Ncfpg
eile	eile	eile-D	Dd
á	á	do-S	Spo-s
marcáil	marcáil	marcáil-N	Nv
go	go	go-U	Ua
cúramach	cúramach	cúramach-A	Aqp
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
straitéisí	straitéisí	straitéis-N	Ncmsc|Ncfpc
imeartha	imeartha	imir-A	Aqp|Av
éagsúla	éagsúla	éagsúil-A	Aq-fsg
á	á	do-S	Spo-p
gcleachtadh	gcleachtadh	cleacht-N	Nv
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Ó	Ó	Ó-U	Up
Dubhthaigh	Dubhthaigh	Dubhthaigh-N	Np
i lár	i lár	i_lár-S	Spc
na	na	na-T	Tdfsg
páirce	páirce	páirc-N	Ncfsg
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
Ó	Ó	Ó-U	Up
Cualáin	Cualáin	Cualáin-N	Npmsc
le	le	le-S	Sp
feiceáil	feiceáil	feic-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Mac	Mac	mac-N	Ncmsc
an	an	an-T	Td-s
Easpaig	Easpaig	Easpaig-N	Npmsg|Npfsg
sa	sa	i-S	Spa-s
chúl	chúl	cúl-N	Ncmsc
…	…	…-F	Fi
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
Cian	Cian	Cian-N	Npmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbainisteoir	mbainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
leabhar	leabhar	leabhar-N	Ncmsc
beag	beag	beag-A	Aq-msc
dubh	dubh	dubh-A	Aq-msc
ag	ag	ag-S	Sp
gobadh	gobadh	gob-N	Nv
amach	amach	amach-R	Rd
as	as	as-P	Pr3ms
a	a	a-D	Dp3
chúlpóca	chúlpóca	chúlpóc-N	Ncmpc
.	.	.-F	Fe
Arbh	Arbh	is-W	Ws-q
fhéidir	fhéidir	féidir-N	Ns-s
gurbh	gurbh	is-W	Wsdi
é	é	é-P	Pp3ms
sin	sin	sin-P	Pd|W
an	an	an-T	Td-s
leabhar	leabhar	leabhar-N	Ncmsc
beag	beag	beag-A	Aq-msc
dubh	dubh	dubh-A	Aq-msc
a	a	a-Q	Q-r
chaith	chaith	caith-V	Vmis
Cian	Cian	Cian-N	Npmsc
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
bhosca	bhosca	bosca-N	Ncmsc
bruscair	bruscair	bruscar-N	Ncmsg|Ncmpc
dhá	dhá	dó-M	Mc
sheachtain	sheachtain	seachtain-N	Ncfsc
roimhe	roimhe	roimh-P	Pr3ms
sin	sin	sin-P	Pd
?	?	?-F	Fq
An	An	an-T	Td-s
leabhar	leabhar	leabhar-N	Ncmsc
ina	ina	i-S	Spr
raibh	raibh	bí-V	Vmis---d
a	a	a-D	Dp3
chuid	chuid	cuid-N	Ncfsc
straitéisí	straitéisí	straitéisí-N	Ncfpg|Ncmsg|Ncfpg|Ncmsg
imeartha	imeartha	imir-A	Av
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
scríofa	scríofa	scríobh-A	Av
?	?	?-F	Fq
Ní	Ní	ní-Q	Qn
fhéadfadh	fhéadfadh	féad-V	Vmc----n
sé	sé	sé-P	Pp3msn
…	…	…-F	Fi
An	An	an-Q	Qq
bhféadfadh	bhféadfadh	féad-V	Vmc
?	?	?-F	Fq
Leag	Leag	leag-V	Vmis|Vmm-2s
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
lámh	lámh	lámh-N	Ncfpg|Ncfsc
chosanta	chosanta	cosain-A	Av
ar	ar	ar-S	Sp
an	an	an-T	Td-s
leabhar	leabhar	leabhar-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
Chian	Chian	Cian-N	Npmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
stánadh	stánadh	stán-N	Nv
go	go	go-U	Ua
géar	géar	géar-A	Aqp
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
chúlpóca	chúlpóca	chúlpóc-N	Ncmpc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
cluiche	cluiche	cluiche-N	Ncmsc
thart	thart	thart-R	Rd
d	d	d-X	Xl
’	’	’-F	Fa
fhan	fhan	fan-V	Vmis
Cian	Cian	Cian-N	Npmsc
le	le	le-S	Sp
labhairt	labhairt	labhair-N	Nv
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbainisteoir	mbainisteoir	bainisteoir-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Comhghairdeas	Comhghairdeas	comhghairdeas-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
go leor	go leor	go_leor-A	Aq|Ns-s|Rg
athruithe	athruithe	athrú-N	Ncmpg
curtha	curtha	cuir-A	Av
i	i	i-S	Sp
bhfeidhm	bhfeidhm	feidhm-N	Ncfsc
agat	agat	ag-P	Pr2-s
ó	ó	ó-S	Sp
thaobh	thaobh	taobh-N	Ncmsc
straitéisí	straitéisí	straitéis-N	Ncmsg|Ncfpg
imeartha	imeartha	imir-A	Av
le	le	le-S	Sp
coicís	coicís	coicís-N	Ncfsc
anuas	anuas	anuas-R	Rd
.	.	.-F	Fe
Feicim	Feicim	feic-V	Vmip1s
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
Mac	Mac	mac-N	Ncmsc
an	an	an-T	Td-s
Easpaig	Easpaig	Easpaig-N	Npmsg|Npfsg
curtha	curtha	cuir-A	Av
sa	sa	i-S	Spa-s
chúl	chúl	cúl-N	Ncmsc
agat	agat	ag-P	Pr2-s
.	.	.-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
maith	maith	maith-N	Ncfsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
go	go	go-U	Ua
gealgháireach	gealgháireach	gealgháireach-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
is	is	is-W	Wp-i
ea	ea	ea-P	Pp3-s
.	.	.-F	Fe
Is	Is	agus-W	Wp-i|Cc
maith	maith	maith-V	Vmm-2s|Aqp|Ncfsc
an	an	an-T	Td-s
rud	rud	rud-N	Ncmsc
é	é	é-P	Pp3ms
an	an	an-T	Td-s
straitéis	straitéis	straitéis-N	Ncfsc
imeartha	imeartha	imir-A	Aqp|Av
a	a	a-U	U
athrú	athrú	athraigh-N	Nv
anois	anois	anois-R	Rt
is	is	agus-C	Cc
arís	arís	arís-R	Rg
.	.	.-F	Fe
'	'	'-F	Fa
Ach	Ach	ach-C	Cs
ba	ba	is-W	Ws|Ws-i
léir	léir	léir-A	Aqp
gur	gur	gur-Q	Q--s
mhothaigh	mhothaigh	mothaigh-V	Vmis
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
míchompordach	míchompordach	míchompordach-A	Aq-msc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
aige	aige	ag-P	Pr3ms
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
a	a	a-D	Dp3
rún	rún	rún-N	Ncmsc
ar	ar	ar-S	Sp
eolas	eolas	eolas-N	Ncmsc
ar	ar	ar-S	Sp
chaoi	chaoi	caoi-N	Ncfsc
éigin	éigin	éigin-A	Aq-fsc
ag	ag	ag-S	Sp
Cian	Cian	Cian-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agat	agat	ag-P	Pr2-s
gur	gur	is-W	Wsdi
liomsa	liomsa	le-P	Pr1-s-e
an	an	an-T	Td-s
leabhar	leabhar	leabhar-N	Ncmsc
beag	beag	beag-A	Aq-msc
…	…	…-F	Fi
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cian	Cian	Cian-N	Npmsc
ach	ach	ach-C	Cs
shlog	shlog	slog-V	Vmis
an	an	an-T	Td-s
slua	slua	slua-N	Ncmsc
é	é	é-P	Pp3ms
sula	sula	sula-C	Cs
bhféadfadh	bhféadfadh	féad-V	Vmc
sé	sé	sé-P	Pp3msn
níos	níos	níos-U	Uc
mó	mó	mór-A	Aqc
a	a	a-U	U
rá	rá	abair-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
líon	líon	líon-N	Ncmsc
mór	mór	mór-A	Aq-msc
grianghrafadóirí	grianghrafadóirí	grianghrafadóir-N	Ncmpg|Ncmpc
ann	ann	i-R	Rl|Pr3ms
ó	ó	ó-S	Sp
na	na	na-T	Td-p
páipéir	páipéir	páipéar-N	Ncmsg
áitiúla	áitiúla	áitiúil-A	Aq-fsg
.	.	.-F	Fe
Iad	Iad	iad-P	Pp3-p
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
grianghraf	grianghraf	grianghraf-N	Ncmpg
a	a	a-U	U
thógáil	thógáil	tóg-N	Nv
den	den	de-S	Spa-s
bhainisteoir	bhainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
.	.	.-F	Fe
A	A	an-T	Td-s
gcuid	gcuid	cuid-N	Ncfsc
ceamaraí	ceamaraí	ceamara-N	Ncmpg
móra	móra	mór-A	Aq--pg
ag	ag	ag-S	Sp
clic	clic	clic-N	Ncmsc
‑	‑	‑-F	Fb
clic	clic	clic-N	Ncmsc
‑	‑	‑-F	Fb
cliceáil	cliceáil	cliceáil-V	Vmm-2s
.	.	.-F	Fe
Is	Is	is-W	Wp-i
beag	beag	beag-A	Aqp
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
Cian	Cian	Cian-N	Npmsc
dallta	dallta	dalladh-N	Ncmsg
ag	ag	ag-S	Sp
na	na	na-T	Td-p
soilse	soilse	solas-N	Ncmpc
geala	geala	geal-A	Aq--pg|Aq--pc|Aq--pv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Mise	Mise	mé-P	Pp1-s-e
a	a	a-Q	Q-r
chum	chum	cum-V	Vmis
na	na	na-T	Td-p
straitéisí	straitéisí	straitéis-N	Ncfpc
imeartha	imeartha	imir-A	Aqp|Av
sin	sin	sin-D	Dd
atá	atá	bí-V	Vmip---r
in	in	i-S	Sp
úsáid	úsáid	úsáid-N	Ncfsc
agat	agat	ag-P	Pr2-s
le	le	le-S	Sp
foireann	foireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
scread	scread	scread-V	Vmis
sé	sé	sé-P	Pp3msn
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbainisteoir	mbainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
in	in	sin-S	Sp|Pd
ard	ard	ard-N	Ncmsc|Aqp
a	a	a-D	Dp3
ghutha	ghutha	guth-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
bí	bí	bí-V	Vmm-2s-n
ag	ag	ag-S	Sp
ligean	ligean	lig-N	Nv
ort	ort	ar-P	Pr2-s
gur	gur	is-W	Wsdi
tú	tú	tú-P	Pp2-s
féin	féin	féin-P	Px
a	a	a-Q	Q-r
chum	chum	cum-V	Vmis
iad	iad	iad-P	Pp3-p
!	!	!-F	Fe
'	'	'-F	Fa
Lig	Lig	lig-V	Vmis|Vmm-2s
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
air	air	ar-P	Pr3ms
nár	nár	nár-Q	Qnrs
chuala	chuala	clois-V	Vmis
sé	sé	sé-P	Pp3msn
Cian	Cian	Cian-N	Npmsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
rug	rug	beir-V	Vmis
sé	sé	sé-P	Pp3msn
greim	greim	greim-N	Ncmsc
air	air	ar-P	Pr3ms
agus	agus	agus-C	Cc
bhrúigh	bhrúigh	brúigh-V	Vmis
isteach	isteach	isteach-R	Rd
ina	ina	i-S	Spp-s
charr	charr	carr-N	Ncmsc|Ncfsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
iompaigh	iompaigh	iompaigh-V	Vmm-2s
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
ar ais	ar ais	ar_ais-R	Rd
i	i	i-S	Sp
dtreo	dtreo	treo-N	Ncmsc
na	na	na-T	Td-p
ngrianghrafadóirí	ngrianghrafadóirí	grianghrafadóir-N	Ncmpg
ansin	ansin	ansin-R	Rt|Rl
agus	agus	agus-C	Cc
rinne	rinne	déan-V	Vmis
gáire	gáire	gáire-N	Ncmsc
mór	mór	mór-A	Aq-msc
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
Lean	Lean	Lean-N	Npmsc
siad	siad	siad-P	Pp3-pn
orthu	orthu	ar-P	Pr3-p
ag	ag	ag-S	Sp
tógáil	tógáil	tóg-N	Nv
pictiúr	pictiúr	pictiúr-N	Ncmpg
.	.	.-F	Fe
Clic	Clic	clic-N	Ncmsc
‑	‑	‑-F	Fb
clic	clic	clic-N	Ncmsc
‑	‑	‑-F	Fb
cleaic	cleaic	cleaic-N	Ncfsc
!	!	!-F	Fe
Faoi	Faoi	faoi-S	Sp
dheireadh	dheireadh	deireadh-N	Ncmsc
d	d	d-X	Xl
’	’	’-F	Fa
imigh	imigh	imigh-V	Vmm-2s
na	na	na-T	Td-p
grianghrafadóirí	grianghrafadóirí	grianghrafadóir-N	Ncmpc
agus	agus	agus-C	Cc
shuigh	shuigh	suigh-V	Vmis
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
charr	charr	carr-N	Ncmsc|Ncfsc
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
dhúirt	dhúirt	abair-V	Vmis---n
sé	sé	sé-P	Pp3msn
tada	tada	tada-N	Ncmsc
ar feadh	ar feadh	ar_feadh-S	Spc
nóiméid	nóiméid	nóiméad-N	Ncmsg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbuachaill	mbuachaill	buachaill-N	Ncmsc
beag	beag	beag-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ina	ina	i-S	Spp-s
shuí	shuí	suí-N	Ncmsc
i	i	i-S	Sp
suíochán	suíochán	suíochán-N	Ncmsc
an	an	an-T	Td-s
phaisinéara	phaisinéara	paisinéir-N	Ncmsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
buachaill	buachaill	buachaill-N	Ncmsc
seo	seo	seo-D	Dd
cliste	cliste	clis-A	Av
gan	gan	gan-S	Sp
aon	aon	aon-D	Dq
amhras	amhras	amhras-N	Ncmsc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
‑	‑	‑-F	Fb
tuiscint	tuiscint	tuig-N	Ncfsc|Nv
aige	aige	ag-P	Pr3ms
ar	ar	ar-S	Sp
an	an	an-T	Td-s
iománaíocht	iománaíocht	iománaíocht-N	Ncfsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
ag	ag	ag-S	Sp
deireadh	deireadh	deireadh-N	Ncmsc
an	an	an-T	Td-s
lae	lae	lá-N	Ncmsg
,	,	,-F	Fi
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ann	ann	i-R	Rl|Pr3ms
ach	ach	ach-S	Sp
buachaill	buachaill	buachaill-N	Ncmsc
dhá	dhá	dó-M	Mc
bhliain	bhliain	bliain-N	Ncfsc
déag	déag	déag-N	Ns-s
d	d	d-X	Xl
’	’	’-F	Fa
aois	aois	aois-N	Ncfsc
.	.	.-F	Fe
Buachaill	Buachaill	buachaill-N	Ncmsc
nár	nár	nár-Q	Qnrs
éirigh	éirigh	éirigh-V	Vmis---n
leis	leis	le-P	Pr3ms
fiú	fiú	fiú-N	Ncmsc
áit	áit	áit-N	Ncfsc
a	a	a-U	U
fháil	fháil	faigh-N	Nv
ar	ar	ar-S	Sp
fhoireann	fhoireann	foireann-N	Ncfsc
B	B	B-X	Xl
na	na	na-T	Tdfsg
scoile	scoile	scoil-N	Ncfsg
!	!	!-F	Fe
Fear	Fear	fear-N	Ncmsc
mór	mór	mór-A	Aq-msc
fásta	fásta	fás-A	Aqp|Av
ba	ba	is-W	Wsri
ea	ea	ea-P	Pp3-s
eisean	eisean	é-P	Pp3ms-e
.	.	.-F	Fe
Fear	Fear	fear-N	Ncmsc
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
a	a	a-U	U
shárú	shárú	sáraigh-N	Nv
le	le	le-S	Sp
fáil	fáil	faigh-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bpáirc	bpáirc	páirc-N	Ncfsc
imeartha	imeartha	imir-A	Aqp|Av
…	…	…-F	Fi
tráth	tráth	tráth-N	Ncmsc
.	.	.-F	Fe
Fear	Fear	fear-N	Ncmsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
trófaí	trófaí	tró-V	Vmc-0
Chú	Chú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
suite	suite	suigh-A	Av
ar	ar	ar-S	Sp
an	an	an-T	Td-s
matal	matal	matal-N	Ncmsc
sa	sa	i-S	Spa-s
bhaile	bhaile	baile-N	Ncmsc
aige	aige	ag-P	Pr3ms
!	!	!-F	Fe
Thaitin	Thaitin	taitin-V	Vmis
an	an	an-T	Td-s
ghlóir	ghlóir	glóir-N	Ncfsc
agus	agus	agus-C	Cc
moladh	moladh	mol-V	Vmis0
go	go	go-U	Ua
mór	mór	mór-A	Aqp
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
theastaigh	theastaigh	teastaigh-V	Vmis---n
uaidh	uaidh	ó-P	Pr3ms
pilleadh	pilleadh	pill-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
sean	sean	sean-N	Ncmsc
‑	‑	‑-F	Fb
am	am	am-N	Ncmsc
,	,	,-F	Fi
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcáineadh	gcáineadh	cáineadh-N	Ncmsc
agus	agus	agus-C	Cc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
ngráin	ngráin	gráin-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
mbainisteoir	mbainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
céard	céard	cé-W	W--q
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
le	le	le-S	Sp
déanamh	déanamh	déan-N	Nv
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Tharraing	Tharraing	tarraing-V	Vmis
sé	sé	sé-P	Pp3msn
anáil	anáil	anáil-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
cheolmhar	cheolmhar	ceolmhar-A	Aq-fsc
trína	trína	trí-S	Spp-s
fhiacla	fhiacla	fiacail-N	Ncfpc
briste	briste	bris-A	Aqp|Av
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agat	agat	ag-P	Pr2-s
nach	nach	nach-Q	Qnr
gcreidfidh	gcreidfidh	creid-V	Vmif
lucht	lucht	lucht-N	Ncmsc
na	na	na-T	Td-p
bpáipéar	bpáipéar	páipéar-N	Ncmpg
mé	mé	mé-P	Pp1-s
má	má	má-C	Cs
deirim	deirim	abair-V	Vmip1s
leo	leo	le-P	Pr3-p
gur	gur	is-W	Wsdi|Wpdi
buachaill	buachaill	buachaill-N	Ncmsc
dhá	dhá	dó-M	Mc
bhliain	bhliain	bliain-N	Ncfsc
déag	déag	déag-N	Ns-s
atá	atá	bí-V	Vmip---r
taobh	taobh	taobh-N	Ncmsc
thiar	thiar	thiar-R	Rd
de	de	de-S	Sp
na	na	na-T	Td-p
straitéisí	straitéisí	straitéis-N	Ncfpc
imeartha	imeartha	imir-A	Aqp|Av
nua	nua	nua-A	Aqp
ag	ag	ag-S	Sp
foireann	foireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sé	sé	sé-P	Pp3msn
faoi	faoi	faoi-S	Sp
dheireadh	dheireadh	deireadh-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Go	Go	go-S	Sp
háirithe	háirithe	áirí-N	Ncfpc
buachaill	buachaill	buachaill-N	Ncmsc
nach	nach	nach-Q	Qnr
bhfuil	bhfuil	bí-V	Vmip---n
mórán	mórán	mórán-N	Ncmsc
maitheasa	maitheasa	maitheas-N	Ncfsg
ann	ann	i-R	Rl|Pr3ms
chun	chun	chun-S	Sp
iomána	iomána	iomáin-N	Ncfsg|Nv--g
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
cad	cad	cad-W	W--q
faoi	faoi	faoi-P	Pr3ms
seo	seo	seo-P	Pd
.	.	.-F	Fe
Má	Má	má-C	Cs
éiríonn	éiríonn	éirigh-V	Vmip
le	le	le-S	Sp
foireann	foireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g
dul	dul	téigh-N	Ncmsc|Nv
chomh	chomh	chomh-R	Ri
fada	fada	fada-A	Aqp
le	le	le-S	Sp
Páirc	Páirc	páirc-N	Ncfsc
an	an	an-Q	Qq
Chrócaigh	Chrócaigh	crócaigh-V	Vmis
,	,	,-F	Fi
eagróidh	eagróidh	eagraigh-V	Vmif
mise	mise	mé-P	Pp1-s-e
preasócáid	preasócáid	ócáid-N	Ncfsc
speisialta	speisialta	speisialta-A	Aqp
leis	leis	le-S	Sp
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
go	go	go-U	Ua
léir	léir	léir-A	Aqp
a	a	a-U	U
mhíniú	mhíniú	mínigh-N	Nv
agus	agus	agus-C	Cc
lena	lena	le-S	Spp-s
rá	rá	abair-N	Nv
gur	gur	is-W	Wsdi|Wpdi
tusa	tusa	tú-P	Pp2-s-e
,	,	,-F	Fi
agus	agus	agus-C	Cc
nach	nach	nach-W	Wprin|Wpdin|Wpsin|Cs
mise	mise	mé-P	Pp1-s-e
,	,	,-F	Fi
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
oibrigh	oibrigh	oibrigh-V	Vmm-2s
amach	amach	amach-R	Rd
na	na	na-T	Td-p
straitéisí	straitéisí	straitéis-N	Ncfpc
imeartha	imeartha	imir-A	Aqp|Av
nua	nua	nua-A	Aqp
.	.	.-F	Fe
Ceart	Ceart	ceart-N	Ncmsc
go leor	go leor	go_leor-A	Aq
?	?	?-F	Fq
'	'	'-F	Fa
Níor	Níor	níor-Q	Qn-s
dhúirt	dhúirt	abair-V	Vmis---n
Cian	Cian	Cian-N	Npmsc
tada	tada	tada-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
bís	bís	bís-N	Ncfsc
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
saol	saol	saol-N	Ncmsc
mór	mór	mór-A	Aq-msc
gur	gur	is-W	Wsdi
mar	mar	mar-S	Sp
gheall	gheall	geall-N	Ncmsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
chuid	chuid	cuid-N	Ncfsc
straitéisí	straitéisí	straitéisí-N	Ncfpg|Ncmsg|Ncfpg|Ncmsg
imeartha	imeartha	imir-A	Aqp|Av
siúd	siúd	siúd-P	Pd|Dd
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
foireann	foireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g|Npmsc
ag	ag	ag-S	Sp
baint	baint	bain-N	Nv
a	a	a-D	Dp3
gcuid	gcuid	cuid-N	Ncfsc
cluichí	cluichí	cluiche-N	Ncmpg
le gairid	le gairid	le_gairid-R	Rt|Spc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
féin	féin	féin-P	Px
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
aige	aige	ag-P	Pr3ms
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
ceart	ceart	ceart-N	Ncmsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
mbainisteoir	mbainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
.	.	.-F	Fe
Cé	Cé	cé-C	Cs
a	a	a-Q	Q-r
chreidfeadh	chreidfeadh	creid-V	Vmc
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
gurbh	gurbh	is-W	Wsdi
eisean	eisean	é-P	Pp3ms-e
a	a	a-Q	Q-r
chum	chum	cum-V	Vmis
na	na	na-T	Td-p
straitéisí	straitéisí	straitéis-N	Ncfpc
nua	nua	nua-A	Aqp
!	!	!-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
go	go	go-U	Ua
mífhoighdeach	mífhoighdeach	mífhoighdeach-A	Aqp
idir	idir	idir-S	Sp
an	an	an-T	Td-s
dá	dá	dó-M	Mc
shúil	shúil	súil-N	Ncfsc
air	air	ar-N	Ncmsg|Pr3ms|Ncmsg
ag	ag	ag-S	Sp
fanacht	fanacht	fan-N	Nv
le	le	le-S	Sp
freagra	freagra	freagra-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ar	Ar	ar-S	Sp
choinníoll	choinníoll	coinníoll-N	Ncmsc
amháin	amháin	amháin-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cian	Cian	Cian-N	Npmsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
ardaigh	ardaigh	ardaigh-V	Vmm-2s
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
a	a	a-U	Ud|Dp3
mhalaí	mhalaí	malach-A	Aqc
go	go	go-U	Ua
ceisteach	ceisteach	ceisteach-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Go	Go	go-Q	Q
ligfidh	ligfidh	lig-V	Vmif
tú	tú	tú-P	Pp2-s
dom	dom	do-P	Pr1-s
tuilleadh	tuilleadh	tuilleadh-N	Ncmsc
straitéisí	straitéisí	straitéisí-N	Ncfpg|Ncmsg
imeartha	imeartha	imir-A	Aqp|Av
a	a	a-U	U
oibriú	oibriú	oibrigh-N	Nv
amach	amach	amach-R	Rd
don	don	do-S	Spa-s
fhoireann	fhoireann	foireann-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cian	Cian	Cian-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cinnte	Cinnte	cinn-A	Av
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
.	.	.-F	Fe
Is	Is	agus-C	Cc
tuige	tuige	cad_chuige-W	W--q
nach	nach	nach-Q	Qnr
ligfeadh	ligfeadh	lig-V	Vmc----n
?	?	?-F	Fq
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ar	ar	ar-S	Sp|Ncmsc
a	a	a-Q	Q-r
chumas	chumas	cum-V	Vmis1s
féin	féin	féin-P	Px
iad	iad	iad-P	Pp3-p
a	a	a-U	U
oibriú	oibriú	oibrigh-N	Nv
amach	amach	amach-R	Rd
.	.	.-F	Fe
Buachaill	Buachaill	buachaill-N	Ncmsc
cliste	cliste	clis-A	Aqp|Av
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sa	sa	i-S	Spa-s
leaid	leaid	leaid-N	Ncmsc
óg	óg	óg-A	Aq-msc
seo	seo	seo-D	Dd
,	,	,-F	Fi
gan	gan	gan-S	Sp
dabht	dabht	dabht-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ba	ba	is-W	Ws|Ws-i
léir	léir	léir-A	Aqp
nach	nach	nach-W	Wprin|Wpdin|Wpsin|Cs
buachaill	buachaill	buachaill-N	Ncmsc
glic	glic	glic-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Shín	Shín	Sín-N	Npfsc
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
amach	amach	amach-R	Rd
a	a	a-D	Dp3
lámh	lámh	lámh-N	Ncfsc
chuig	chuig	chuig-S	Sp
Cian	Cian	Cian-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bíodh	Bíodh	bí-V	Vmm-3s
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
mhargadh	mhargadh	margadh-N	Ncmsc
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Rug	Rug	beir-V	Vmis
Cian	Cian	Cian-N	Npmsc
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
lámh	lámh	lámh-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bíodh	Bíodh	bí-V	Vmm-3s
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
mhargadh	mhargadh	margadh-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-U	Ua
sásta	sásta	sásta-A	Aqp
agus	agus	agus-C	Cc
chroith	chroith	croith-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
lámh	lámh	lámh-N	Ncfsc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
sin	sin	sin-P	Pd|W
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ar feadh	ar feadh	ar_feadh-S	Spc
an	an	an-T	Td-s
tséasúir	tséasúir	séasúr-N	Ncmsg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
oibrigh	oibrigh	oibrigh-V	Vmm-2s
Cian	Cian	Cian-N	Npmsc
amach	amach	amach-R	Rd
straitéisí	straitéisí	straitéisí-N	Ncfpc|Ncmsc
imeartha	imeartha	imir-A	Aqp|Av
d	d	d-X	Xl
’	’	’-F	Fa
fhoireann	fhoireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g|Npmsc
chuile	chuile	cuile-N	Ncfsg
sheachtain	sheachtain	seachtain-N	Ncfsc
agus	agus	agus-C	Cc
chuir	chuir	cur-V	Vmis|Ncmsg
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
i láthair	i láthair	i_láthair-S	Spc
na	na	na-T	Tdfsg
n	n	n-X	Xl
‑	‑	‑-F	Fb
imreoirí	imreoirí	imreoir-N	Ncmpc
iad	iad	iad-P	Pp3-p
ar nós	ar nós	ar_nós-S	Spc
gur	gur	is-W	Wsdi|Wpdi
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
iad	iad	iad-P	Pp3-p
.	.	.-F	Fe
Ghnóthaigh	Ghnóthaigh	gnóthaigh-V	Vmis
foireann	foireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npmsc
chuile	chuile	cuile-N	Ncfsg
chluiche	chluiche	cluiche-N	Ncmsg
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
imir	imir	imir-V	Vmis
siad	siad	siad-P	Pp3-pn
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
contae	contae	contae-N	Ncmsc
go	go	go-U	Ua
léir	léir	léir-A	Aqp
ag	ag	ag-S	Sp
tabhairt	tabhairt	tabhair-N	Nv
tacaíochta	tacaíochta	tacaíocht-N	Ncfsg
dóibh	dóibh	do-P	Pr3-p
sula	sula	sula-C	Cs
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
a	a	a-D	Dp3
sárú	sárú	sárú-N	Ncmsc
le	le	le-S	Sp
fáil	fáil	faigh-N	Nv
sa	sa	i-S	Spa-s
cheantar	cheantar	ceantar-N	Ncmsc
ná	ná	ná-C	Cc
sa	sa	i-S	Spa-s
chontae	chontae	contae-N	Ncmsc
.	.	.-F	Fe
Sa	Sa	i-S	Spa-s
chúige	chúige	cúige-N	Ncmsc
,	,	,-F	Fi
fiú	fiú	fiú-N	Ns-s|Ncmsc|Rg
!	!	!-F	Fe
Faoi	Faoi	faoi-S	Sp
dheireadh	dheireadh	deireadh-N	Ncmsc
tháinig	tháinig	tar-V	Vmis
lá	lá	lá-N	Ncmsc
an	an	an-T	Td-s
chluiche	chluiche	cluiche-N	Ncmsg
leathcheannais	leathcheannais	ceannais-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Cian	Cian	Cian-N	Npmsc
ar	ar	ar-S	Sp
bís	bís	bís-N	Ncfsc
.	.	.-F	Fe
Dá	Dá	dá-C	Cs
mbainfeadh	mbainfeadh	bain-V	Vmc
siad	siad	siad-P	Pp3-pn
inniu	inniu	inniu-R	Rt
bheadh	bheadh	bí-V	Vmc
foireann	foireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g|Npmsc
ag	ag	ag-S	Sp
imirt	imirt	imir-N	Nv
sa	sa	i-S	Spa-s
chluiche	chluiche	cluiche-N	Ncmsc
ceannais	ceannais	ceannais-A	Aq-msc
i	i	i-S	Sp
bPáirc	bPáirc	páirc-N	Ncfsc
an	an	an-Q	Qq
Chrócaigh	Chrócaigh	crócaigh-V	Vmis
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
,	,	,-F	Fi
níos	níos	níos-U	Uc
fearr	fearr	maith-A	Aqc
fós	fós	fós-R	Rg
,	,	,-F	Fi
bheadh	bheadh	bí-V	Vmc
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
ag	ag	ag-S	Sp
chuile	chuile	cuile-N	Ncfsc
dhuine	dhuine	duine-N	Ncmsg
beo	beo	beo-A	Aqp
gur	gur	is-W	Wsdi|Wpdi
mar	mar	mar-S	Sp
gheall	gheall	geall-N	Ncmsc
airsean	airsean	ar-P	Pr3ms-e
,	,	,-F	Fi
Cian	Cian	Cian-N	Npmsc
Ó	Ó	Ó-U	Up
Buacháin	Buacháin	Buacháin-N	Npmsc
,	,	,-F	Fi
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
imirt	imirt	imir-N	Nv
ann	ann	ann-R	Rl
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
margadh	margadh	margadh-N	Ncmsc
déanta	déanta	déan-A	Av
aige	aige	ag-P	Pr3ms
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbainisteoir	mbainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
.	.	.-F	Fe
Dá	Dá	dá-C	Cs
mbainfeadh	mbainfeadh	bain-V	Vmc
foireann	foireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npmsc
inniu	inniu	inniu-R	Rt
,	,	,-F	Fi
d	d	d-X	Xl
’	’	’-F	Fa
inseodh	inseodh	inis-V	Vmc
seisean	seisean	sé-P	Pp3msne
do	do	do-S	Sp
chách	chách	cách-N	Ncmsc
gurbh	gurbh	is-W	Wsdi
é	é	é-P	Pp3ms
Cian	Cian	Cian-N	Npmsc
fear	fear	fear-N	Ncmsc
na	na	na-T	Tdfsg
straitéise	straitéise	straitéis-N	Ncfsg
i	i	i-S	Sp
ndáiríre	ndáiríre	dáiríre-N	Ncmsc
.	.	.-F	Fe
Sheas	Sheas	seas-V	Vmis
Cian	Cian	Cian-N	Npmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
taobhlíne	taobhlíne	taobhlíne-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
trasna	trasna	trasna-R	Rd|Sp
uaidh	uaidh	ó-P	Pr3ms
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
ardaigh	ardaigh	ardaigh-V	Vmm-2s
Cian	Cian	Cian-N	Npmsc
a	a	a-D	Dp3
ordóg	ordóg	ordóg-N	Ncfsc
leis	leis	le-P	Pr3ms
chun	chun	chun-S	Sp
ádh	ádh	ádh-N	Ncmpg
maith	maith	maith-A	Aqp
a	a	a-U	U
ghuí	ghuí	guigh-N	Nv
leis	leis	le-P	Pr3ms
ach	ach	ach-C	Cs
níor	níor	is-W	Ws-in
thug	thug	tabhair-V	Vmis
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
aon	aon	aon-D	Dq
aird	aird	aird-N	Ncfsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
iontas	iontas	iontas-N	Ncmsc
ar	ar	ar-S	Sp
Chian	Chian	Cian-N	Npmsc
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
beagáinín	beagáinín	beagán-N	Ncmsc|Ncmpc
imní	imní	imní-N	Ncfsg
.	.	.-F	Fe
An	An	is-W	Wp-q
é	é	é-P	Pp3ms
nach	nach	nach-Q	Qnrs
bhfaca	bhfaca	feic-V	Vmis---d
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
i	i	i-S	Sp
measc	measc	measc-N	Ncmsc
na	na	na-T	Td-p
sluaite	sluaite	slua-N	Ncmpg
é	é	é-P	Pp3ms
?	?	?-F	Fq
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
imní	imní	imní-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbainisteoir	mbainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
freisin	freisin	freisin-R	Rg
.	.	.-F	Fe
Cé	Cé	cé-C	Cs
gur	gur	is-W	Wsdi
theastaigh	theastaigh	teastaigh-V	Vmis
uaidh	uaidh	ó-P	Pr3ms
an	an	an-T	Td-s
cluiche	cluiche	cluiche-N	Ncmsc
seo	seo	seo-D	Dd
a	a	a-U	U
bhaint	bhaint	bain-N	Nv
níor	níor	níor-Q	Qn-s
theastaigh	theastaigh	teastaigh-V	Vmis---n
uaidh	uaidh	ó-P	Pr3ms
a	a	a-U	U
insint	insint	inis-N	Nv
d	d	d-X	Xl
’	’	’-F	Fa
éinne	éinne	duine-N	Ncmsc
nach	nach	is-W	Wprin
é	é	é-P	Pp3ms
féin	féin	féin-P	Px
a	a	a-Q	Q-r
chum	chum	cum-V	Vmis
na	na	na-T	Td-p
straitéisí	straitéisí	straitéis-N	Ncfpc
nua	nua	nua-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
foireann	foireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g
an	an	an-T	Td-s
séasúr	séasúr	séasúr-N	Ncmsc
sin	sin	sin-D	Dd
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
b	b	b-X	Xl
’	’	’-F	Fa
in	in	sin-S	Sp|Pd
é	é	é-P	Pp3ms
an	an	an-T	Td-s
margadh	margadh	margadh-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
déanta	déanta	déan-A	Av
aige	aige	ag-P	Pr3ms
le	le	le-S	Sp
Cian	Cian	Cian-N	Npmsc
.	.	.-F	Fe
Chaithfeadh	Chaithfeadh	caith-V	Vmc
sé	sé	sé-P	Pp3msn
smaoineamh	smaoineamh	smaoinigh-N	Ncmsc|Nv
ar	ar	ar-S	Sp
phlean	phlean	plean-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
roimh	roimh	roimh-S	Sp
dheireadh	dheireadh	deireadh-N	Ncmsc
an	an	an-T	Td-s
chluiche	chluiche	cluiche-N	Ncmsg
.	.	.-F	Fe
Plean	Plean	plean-N	Ncmsc
a	a	a-Q	Q-r
chinnteodh	chinnteodh	cinntigh-V	Vmc
gurbh	gurbh	is-W	Wsdi
eisean	eisean	é-P	Pp3ms-e
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
mar	mar	mar-S	Sp
laoch	laoch	laoch-N	Ncmsc
an	an	an-T	Td-s
lae	lae	lá-N	Ncmsg
.	.	.-F	Fe
Amach	Amach	amach-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bpáirc	bpáirc	páirc-N	Ncfsc
le	le	le-S	Sp
foireann	foireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
chuile	chuile	gach-D	Dq
liú	liú	liúigh-N	Ncmsc|Nv
as	as	as-S	Sp
an	an	an-T	Td-s
lucht	lucht	lucht-N	Ncmsc
leanúna	leanúna	lean-N	Ncfsg|Nv--g
le	le	le-S	Sp
háthas	háthas	áthas-N	Ncmsc
agus	agus	agus-C	Cc
le	le	le-S	Sp
bród	bród	bród-N	Ncmsc
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
an	an	an-T	Td-s
cluiche	cluiche	cluiche-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
chroí	chroí	croí-N	Ncmsc
ina	ina	i-S	Spp-s
bhéal	bhéal	béal-N	Ncmsc
ag	ag	ag-S	Sp
Cian	Cian	Cian-N	Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
chroí	chroí	croí-N	Ncmsc
ina	ina	i-S	Spp-s
bhéal	bhéal	béal-N	Ncmsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
mbainisteoir	mbainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
.	.	.-F	Fe
Pocanna	Pocanna	Pocanna-N	Npmsc
arda	arda	ard-N	Ncmpc
,	,	,-F	Fi
pocanna	pocanna	poc-N	Ncmpc
ísle	ísle	íseal-A	Aq--pc
,	,	,-F	Fi
pocanna	pocanna	poc-N	Ncmpc
fada	fada	fada-A	Aqp
agus	agus	agus-C	Cc
pocanna	pocanna	poc-N	Ncmpc
gearra	gearra	gearr-A	Aq--pg|Aq--pc|Aq--pv
.	.	.-F	Fe
Cúilín	Cúilín	cúilín-N	Ncmsc|Ncfsc
agus	agus	agus-C	Cc
cúilín	cúilín	cúilín-N	Ncmsg|Ncmsc|Ncfsc|Ncfsg
eile	eile	eile-D	Dd
.	.	.-F	Fe
Suas	Suas	suas-R	Rd
síos	síos	síos-R	Rd
an	an	an-T	Td-s
pháirc	pháirc	páirc-N	Ncfsc
le	le	le-S	Sp
foireann	foireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g
ar nós	ar nós	ar_nós-S	Spc
na	na	na-T	Tdfsg
lasrach	lasrach	lasair-N	Ncfsg
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
seans	seans	seans-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
bhfoireann	bhfoireann	foireann-N	Ncfsc
eile	eile	eile-D	Dd
.	.	.-F	Fe
Séideadh	Séideadh	séideadh-V	Vmis0|Vmm-3s|Ncmsc
an	an	an-T	Td-s
fhead	fhead	fead-N	Ncfsc
deiridh	deiridh	deireadh-N	Ncmsg
.	.	.-F	Fe
Bhéic	Bhéic	béic-V	Vmis
lucht	lucht	lucht-N	Ncmsc
leanúna	leanúna	lean-N	Ncfsg|Nv--g
Setanta	Setanta	Setanta-N	Npm-g|Npmsc
amach	amach	amach-R	Rd
in	in	sin-S	Sp|Pd
ard	ard	ard-N	Ncmsc|Aqp
a	a	a-D	Dp3
ngutha	ngutha	guth-N	Ncmsg
.	.	.-F	Fe
Léim	Léim	léim-V	Vmip1s|Vmm-2s|Vmis|Ncfsc
na	na	na-T	Td-p
himreoirí	himreoirí	imreoir-N	Ncmpc
i	i	i-S	Sp
mullach	mullach	mullach-N	Ncmsc
a	a	a-D	Dp3
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Léim	Léim	léim-V	Vmip1s|Vmm-2s|Vmis|Ncfsc
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
leathchos	leathchos	cos-N	Ncfsc
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
bheag	bheag	beag-A	Aqp
nár	nár	nár-W	Wsrin|Wsdin|Wssin|Qnrs
léim	léim	léim-V	Vmip1s|Ncfsc|Vmip1s-n|Nv|Ncfsc|Nv|Vmis|Vmis---n
croí	croí	croí-N	Ncmsg|Ncmsc
Chéin	Chéin	Céin-N	Npfsg
amach	amach	amach-R	Rd
as	as	as-P	Pr3ms
a	a	a-D	Dp3
bhéal	bhéal	béal-N	Ncmsc
le	le	le-S	Sp
bród	bród	bród-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
foireann	foireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g|Npmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbealach	mbealach	bealach-N	Ncmsc
go	go	go-S	Sp
Páirc	Páirc	páirc-N	Ncfsc
an	an	an-Q	Qq
Chrócaigh	Chrócaigh	crócaigh-V	Vmis
a	a	a-D	Dp3
bhuíochas	bhuíochas	buíochas-N	Ncmsc
dósan	dósan	do-P	Pr3ms-e
!	!	!-F	Fe
Rug	Rug	beir-V	Vmis
na	na	na-T	Td-p
himreoirí	himreoirí	imreoir-N	Ncmpc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbainisteoir	mbainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
foireann	foireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g|Npmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbealach	mbealach	bealach-N	Ncmsc
go	go	go-S	Sp
Páirc	Páirc	páirc-N	Ncfsc
an	an	an-Q	Qq
Chrócaigh	Chrócaigh	crócaigh-V	Vmis
a	a	a-D	Dp3
bhuíochas	bhuíochas	buíochas-N	Ncmsc
dósan	dósan	do-P	Pr3ms-e
!	!	!-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
Cian	Cian	Cian-N	Npmsc
suas	suas	suas-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbainisteoir	mbainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
anuas	anuas	anuas-R	Rd
ar	ar	ar-S	Sp
Chian	Chian	Cian-N	Npmsc
.	.	.-F	Fe
Rinne	Rinne	déan-V	Vmis
Cian	Cian	Cian-N	Npmsc
a	a	a-D	Dp3
bhealach	bhealach	bealach-N	Ncmsc
chuige	chuige	chuig-R	Rg|Pr3ms
tríd	tríd	trí-S	Sp
na	na	na-T	Td-p
hiriseoirí	hiriseoirí	iriseoir-N	Ncmpc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
grianghrafadóirí	grianghrafadóirí	grianghrafadóir-N	Ncmpc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
bailithe	bailithe	bailigh-N	Ncmpc|Av
thart	thart	thart-R	Rd
air	air	ar-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cén	Cén	cé-W	W--q|Dw--s
t	t	t-X	Xl
‑	‑	‑-F	Fb
am	am	am-N	Ncmsc
a	a	a-Q	Q-r
bheas	bheas	bí-V	Vmif---r
an	an	an-T	Td-s
phreasócáid	phreasócáid	ócáid-N	Ncfsc
lena	lena	le-S	Spp-s
fhógairt	fhógairt	fógair-N	Nv
gur	gur	is-W	Wsdi|Wpdi
mise	mise	mé-P	Pp1-s-e
,	,	,-F	Fi
agus	agus	agus-C	Cc
nach	nach	nach-W	Wprin|Wpdin|Wpdqn|Wp-qn|Wpsin|Cs
tusa	tusa	tú-P	Pp2-s-e
,	,	,-F	Fi
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
oibrigh	oibrigh	oibrigh-V	Vmm-2s
amach	amach	amach-R	Rd
na	na	na-T	Td-p
straitéisí	straitéisí	straitéis-N	Ncfpc
imeartha	imeartha	imir-A	Aqp|Av
?	?	?-F	Fq
'	'	'-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
de	de	de-S	Sp
chogar	chogar	cogar-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	is-W	Wpdq|Wp-q
phreasócáid	phreasócáid	ócáid-N	Ncfsc
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cén	Cén	cé-W	W--q
phreasócáid	phreasócáid	ócáid-N	Ncfsc
?	?	?-F	Fq
Imigh	Imigh	imigh-V	Vmm-2s
thusa	thusa	tú-P	Pp2-s-e
abhaile	abhaile	abhaile-R	Rd
anois	anois	anois-R	Rt
,	,	,-F	Fi
maith	maith	maith-A	Aqp
an	an	an-T	Td-s
buachaill	buachaill	buachaill-N	Ncmsc
.	.	.-F	Fe
Beidh	Beidh	bí-V	Vmif
do	do	do-S	Sp
mhamaí	mhamaí	mamaí-N	Ncmpc|Ncfsc
ag	ag	ag-S	Sp
fanacht	fanacht	fan-N	Nv
ort	ort	ar-P	Pr2-s
.	.	.-F	Fe
'	'	'-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
iompaigh	iompaigh	iompaigh-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
dhroim	dhroim	droim-N	Ncmsc
le	le	le-S	Sp
Cian	Cian	Cian-N	Npmsc
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
meangaireacht	meangaireacht	meangaireacht-N	Ncfsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
slua	slua	slua-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
rinne	rinne	déan-V	Vmis
tú	tú	tú-P	Pp2-s
margadh	margadh	margadh-N	Ncmsc
liom	liom	le-P	Pr1-s
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Cian	Cian	Cian-N	Npmsc
,	,	,-F	Fi
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
os	os	os-S	Sp
ard	ard	ard-N	Ncmsc
an	an	an-T	Td-s
uair	uair	uair-N	Ncfsc
seo	seo	seo-D	Dd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Gheall	Gheall	geall-V	Vmis
tú	tú	tú-P	Pp2-s
dá	dá	dá-C	Cs
mbuafadh	mbuafadh	buaigh-V	Vmc
Setanta	Setanta	Setanta-N	Npmsc
an	an	an-T	Td-s
cluiche	cluiche	cluiche-N	Ncmsg
seo	seo	seo-D	Dd
go	go	go-C	Cs
n	n	n-X	Xl
‑	‑	‑-F	Fb
inseofá	inseofá	inis-V	Vmc-2s
don	don	do-S	Spa-s
saol	saol	saol-N	Ncmsc
mór	mór	mór-A	Aq-msc
gur	gur	is-W	Wsdi|Wpdi
liomsa	liomsa	le-P	Pr1-s-e
na	na	na-T	Td-p
straitéisí	straitéisí	straitéis-N	Ncfpg|Ncfpc
imeartha	imeartha	imir-A	Aqp|Av
agus	agus	agus-C	Cc
nach	nach	nach-W	Wprin|Wpdin|Wpsin|Cs
leatsa	leatsa	le-P	Pr2-s-e
iad	iad	iad-P	Pp3-p
!	!	!-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Margadh	Margadh	margadh-N	Ncmsc
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
cuimhin	cuimhin	cuimhin-N	Ns-s
liomsa	liomsa	le-P	Pr1-s-e
aon	aon	aon-D	Dq
chaint	chaint	caint-N	Ncfsc
ar	ar	ar-S	Sp
mhargadh	mhargadh	margadh-N	Ncmsc
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
aghaidh	aghaidh	aghaidh-N	Ncfsc
leat	leat	le-P	Pr2-s
abhaile	abhaile	abhaile-R	Rd
anois	anois	anois-R	Rt
,	,	,-F	Fi
maith	maith	maith-A	Aqp
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
iompaigh	iompaigh	iompaigh-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
droim	droim	droim-N	Ncmsc
le	le	le-S	Sp
Cian	Cian	Cian-N	Npmsc
arís	arís	arís-R	Rg
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
an	an	an-T	Td-s
iarraidh	iarraidh	iarraidh-N	Ncfsc
seo	seo	seo-D	Dd
,	,	,-F	Fi
thosaigh	thosaigh	tosaigh-V	Vmis
Cian	Cian	Cian-N	Npmsc
ag	ag	ag-S	Sp
béicíl	béicíl	béicíl-N	Nv-----n
leis	leis	le-S	Sp
an	an	an-T	Td-s
slua	slua	slua-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Mise	Mise	mé-P	Pp1-s-e
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
oibrigh	oibrigh	oibrigh-V	Vmm-2s
amach	amach	amach-R	Rd
na	na	na-T	Td-p
straitéisí	straitéisí	straitéis-N	Ncfpc
imeartha	imeartha	imir-A	Aqp|Av
d	d	d-X	Xl
’	’	’-F	Fa
fhoireann	fhoireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g|Npmsc
!	!	!-F	Fe
Ní	Ní	is-W	Wp-in
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
.	.	.-F	Fe
Is	Is	is-W	Wp-i
fealltóir	fealltóir	fealltóir-N	Ncmsc
agus	agus	agus-C	Cc
bréagadóir	bréagadóir	bréagadóir-N	Ncmsc
bradach	bradach	bradach-A	Aq-msc
é	é	é-P	Pp3ms
!	!	!-F	Fe
'	'	'-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
iompaigh	iompaigh	iompaigh-V	Vmm-2s
na	na	na-T	Td-p
grianghrafadóirí	grianghrafadóirí	grianghrafadóir-N	Ncmpc
a	a	a-D	Dp3
gceamaraí	gceamaraí	ceamara-N	Ncmpg
ar	ar	ar-S	Sp
Chian	Chian	Cian-N	Npmsc
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
clic	clic	clic-N	Ncmsc
‑	‑	‑-F	Fb
clic	clic	clic-N	Ncmsc
‑	‑	‑-F	Fb
cliceáil	cliceáil	cliceáil-V	Vmm-2s
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Cian	Cian	Cian-N	Npmsc
dallta	dallta	dalladh-N	Ncmsg
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Siúd	Siúd	siúd-P	Pd
leis	leis	le-S	Sp
na	na	na-T	Td-p
hiriseoirí	hiriseoirí	iriseoir-N	Ncmpc
ag	ag	ag-S	Sp
scríobh	scríobh	scríobh-N	Nv
ina	ina	i-S	Spp-s|Spp-p
leabhar	leabhar	leabhar-N	Ncmsc
nótaí	nótaí	nóta-N	Ncmpg|Ncmpc
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
dhúirt	dhúirt	abair-V	Vmis---n
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
tada	tada	tada-N	Ncmsc|Ncmsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
ciúnas	ciúnas	ciúnas-N	Ncmsc
ann	ann	i-P	Pr3ms
(	(	(-F	Fp
ach	ach	ach-R	Ri
amháin	amháin	amháin-A	Aqp
clic	clic	clic-N	Ncmsg|Ncmsc
‑	‑	‑-F	Fb
clic	clic	clic-N	Ncmsc
‑	‑	‑-F	Fb
cliceáil	cliceáil	cliceáil-V	Vmm-2s|Nv
na	na	na-T	Td-p
gceamaraí	gceamaraí	ceamara-N	Ncmpg
)	)	)-F	Fp
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
lig	lig	lig-V	Vmis
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
gáire	gáire	gáire-N	Ncmsc
mór	mór	mór-A	Aq-msc
millteach	millteach	millteach-A	Aq-msc
.	.	.-F	Fe
Gáire	Gáire	gáire-N	Ncmsc
mór	mór	mór-A	Aq-msc
gránna	gránna	gránna-A	Aqp
.	.	.-F	Fe
Gáire	Gáire	gáire-N	Ncmsc
mór	mór	mór-A	Aq-msc
fealltach	fealltach	fealltach-A	Aq-msc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-T	Td-s
gcluin	gcluin	gcluin-N	Ncfsc
sibh	sibh	sibh-P	Pp2-p
é	é	é-P	Pp3ms
!	!	!-F	Fe
Há	Há	Há-N	Npmsc
!	!	!-F	Fe
Há	Há	Há-N	Npmsc
!	!	!-F	Fe
Há	Há	Há-N	Npmsc
!	!	!-F	Fe
A	A	a-U	Uv
leithéid	leithéid	leithéid-N	Ncfsv
!	!	!-F	Fe
Buachaill	Buachaill	buachaill-N	Ncmsc
dhá	dhá	dó-M	Mc
bhliain	bhliain	bliain-N	Ncfsc
déag	déag	déag-N	Ns-s
d	d	d-X	Xl
’	’	’-F	Fa
aois	aois	aois-N	Ncfsc
ag	ag	ag-S	Sp
oibriú	oibriú	oibrigh-N	Nv
amach	amach	amach-R	Rd
straitéisí	straitéisí	straitéisí-N	Ncfpc|Ncmsc
imeartha	imeartha	imir-A	Aqp|Av
d	d	d-X	Xl
’	’	’-F	Fa
fhoireann	fhoireann	foireann-N	Ncfsc
daoine	daoine	duine-N	Ncmpg|Ncmpc
fásta	fásta	fás-A	Aqp|Av
!	!	!-F	Fe
Sin	Sin	sin-W	W
ceann	ceann	ceann-N	Ncmsc
maith	maith	maith-A	Aq-msc
daoibh	daoibh	do-P	Pr2-p
anois	anois	anois-R	Rt
!	!	!-F	Fe
'	'	'-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
na	na	na-T	Td-p
hiriseoirí	hiriseoirí	iriseoir-N	Ncmpc
ag	ag	ag-S	Sp
gáire	gáire	gáir-N	Nv
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
na	na	na-T	Td-p
grianghrafadóirí	grianghrafadóirí	grianghrafadóir-N	Ncmpc
ag	ag	ag-S	Sp
gáire	gáire	gáir-N	Nv
.	.	.-F	Fe
Níorbh	Níorbh	is-W	Ws-in
fhada	fhada	fada-A	Aqc|Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
slua	slua	slua-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
ag	ag	ag-S	Sp
gáire	gáire	gáir-N	Nv
.	.	.-F	Fe
Chuile	Chuile	gach-D	Dq
dhuine	dhuine	duine-N	Ncmsg
ag	ag	ag-S	Sp
gáire	gáire	gáir-N	Nv
ach	ach	ach-R	Ri
amháin	amháin	amháin-A	Aqp
Cian	Cian	Cian-N	Npm-g|Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
seisean	seisean	sé-P	Pp3msne
náirithe	náirithe	náirigh-A	Av
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbainisteoir	mbainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
.	.	.-F	Fe
Líon	Líon	líon-V	Vmis
a	a	a-D	Dp3
chroí	chroí	croí-N	Ncmsc
le	le	le-S	Sp
fuath	fuath	fuath-N	Ncmsc
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
fonn	fonn	fonn-N	Ncmsc
air	air	ar-N	Ncmsg
dorn	dorn	dorn-N	Ncmpg|Ncmsc
sa	sa	i-S	Spa-s
phus	phus	pus-N	Ncmsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
dó	dó	do-P	Pr3ms
ach	ach	ach-C	Cs
níor	níor	is-W	Ws-in
thug	thug	tabhair-V	Vmis
.	.	.-F	Fe
Chrom	Chrom	crom-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
cheann	cheann	ceann-N	Ncmsc
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
aghaidh	aghaidh	aghaidh-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbaile	mbaile	baile-N	Ncmsc
agus	agus	agus-C	Cc
macalla	macalla	macalla-N	Ncmsc
an	an	an-T	Td-s
gháire	gháire	gáire-N	Ncmsg
fós	fós	fós-R	Rg
ina	ina	i-S	Spp-s
chluasa	chluasa	cluas-N	Ncfpc
.	.	.-F	Fe
Lig	Lig	lig-V	Vmis|Vmm-2s
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
osna	osna	osna-N	Ncmsg|Ncmsc
faoisimh	faoisimh	faoiseamh-N	Ncmsg|Ncmpc
.	.	.-F	Fe
Nach	Nach	is-W	Wpsin
air	air	ar-P	Pr3ms
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
t	t	t-X	Xl
‑	‑	‑-F	Fb
ádh	ádh	ádh-N	Ncmsc
nár	nár	nár-W	Wsrin|Wsdin|Wssin|Qn-s|Qnrs
scaoileadh	scaoileadh	scaoil-N	Ncmsc|Nv|Ncmsc|Vmih---n|Nv|Vmis0|Vmis0--n|Vmih|Nv
a	a	a-D	Dp3
rún	rún	rún-N	Ncmsc
faoi	faoi	faoi-S	Sp
na	na	na-T	Td-p
straitéisí	straitéisí	straitéis-N	Ncfpc
imeartha	imeartha	imir-A	Aqp|Av
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
clú	clú	clú-N	Ncmsc
agus	agus	agus-C	Cc
cáil	cáil	cál-N	Ncfsc|Ncmsg|Ncmpc
air	air	ar-P	Pr3ms
anois	anois	anois-R	Rt
mar	mar	mar-S	Sp
bhainisteoir	bhainisteoir	bainisteoir-N	Ncmsc
iománaíochta	iománaíochta	iománaíocht-N	Ncfsg
den	den	de-S	Spa-s
scoth	scoth	scoth-N	Ncfsc
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
lena	lena	le-S	Spp-s
chlú	chlú	clú-N	Ncmsc
mar	mar	mar-S	Sp
shárimreoir	shárimreoir	imreoir-N	Ncmsc
!	!	!-F	Fe
Smaoinigh	Smaoinigh	smaoinigh-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-Q	Q-p
thrófaí	thrófaí	tró-V	Vmc-0
Chú	Chú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
suite	suite	suigh-A	Av
ar	ar	ar-S	Sp
an	an	an-T	Td-s
matal	matal	matal-N	Ncmsc
sa	sa	i-S	Spa-s
bhaile	bhaile	baile-N	Ncmsc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
feadh	feadh	feadh-N	Ncmsc
nóiméidín	nóiméidín	nóiméad-N	Ncmsc|Ncmpc
tháinig	tháinig	tar-V	Vmis
náire	náire	náire-N	Ncfsc
air	air	ar-P	Pr3ms
toisc	toisc	toisc-C	Cs
an	an	is-W	Wpdq|Wp-q
rud	rud	rud-N	Ncmsc
a	a	a-Q	Q-r
rinne	rinne	déan-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
Chian	Chian	Cian-N	Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
trua	trua	trua-N	Ncfsc
aige	aige	ag-P	Pr3ms
do	do	do-S	Sp
Chian	Chian	Cian-N	Npmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
samhlaigh	samhlaigh	samhlaigh-V	Vmm-2s
dá	dá	de-S	Spp-s
n	n	n-X	Xl
‑	‑	‑-F	Fb
inseodh	inseodh	inis-V	Vmc
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
fhírinne	fhírinne	fírinne-N	Ncfsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
bheadh	bheadh	bí-V	Vmc----n
meas	meas	meas-N	Ncmsc
air	air	ar-N	Ncmsg|Pr3ms
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
arís	arís	arís-R	Rg
!	!	!-F	Fe
Sin	Sin	sin-W	W
rud	rud	rud-N	Ncmsc
nach	nach	nach-Q	Qnr
bhféadfadh	bhféadfadh	féad-V	Vmc
sé	sé	sé-P	Pp3msn
a	a	a-U	U
sheasamh	sheasamh	seas-N	Nv
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
na	na	na-T	Td-p
grianghrafadóirí	grianghrafadóirí	grianghrafadóir-N	Ncmpc
ag	ag	ag-S	Sp
glaoch	glaoch	glaoigh-N	Nv
air	air	ar-P	Pr3ms
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
clic	clic	clic-N	Ncmsc
‑	‑	‑-F	Fb
clic	clic	clic-N	Ncmsc
‑	‑	‑-F	Fb
cliceáil	cliceáil	cliceáil-V	Vmm-2s|Nv
an	an	an-T	Td-s
athuair	athuair	athuair-N	Ns-s
.	.	.-F	Fe
Rinne	Rinne	déan-V	Vmis
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
dearmad	dearmad	dearmad-N	Ncmsc
glan	glan	glan-A	Aq-msc
ar	ar	ar-S	Sp
Chian	Chian	Cian-N	Npmsc
agus	agus	agus-C	Cc
ar	ar	is-W	Wpsi|Ncmsc|Wssi|Wpdi
chomh	chomh	chomh-R	Ri
gránna	gránna	gránna-A	Aqp
is	is	agus-C	Cc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-U	Ua
sásta	sásta	sásta-A	Aqp
ar	ar	ar-S	Sp
an	an	an-T	Td-s
slua	slua	slua-N	Ncmsc
agus	agus	agus-C	Cc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhfoireann	bhfoireann	foireann-N	Ncfsc
bhuacach	bhuacach	buacach-A	Aq-fsc|Aq-fsv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Hurá	Hurá	hurá-I	I
!	!	!-F	Fe
Hurá	Hurá	hurá-I	I
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-Q	Q-r
chan	chan	can-V	Vmis
an	an	an-T	Td-s
slua	slua	slua-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Táimid	Táimid	bí-V	Vmip1p
ar	ar	is-S	Sp|Ncmsc|Wssi|Wpdi|Wpsi
ár	ár	ár-D	Dp1-p
mbealach	mbealach	bealach-N	Ncmsc
go	go	go-S	Sp
Páirc	Páirc	páirc-N	Ncfsc
an	an	an-Q	Qq
Chrócaigh	Chrócaigh	crócaigh-V	Vmis
a	a	a-D	Dp3
bhuíochas	bhuíochas	buíochas-N	Ncmsc
don	don	do-S	Spa-s
bhainisteoir	bhainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
!	!	!-F	Fe
Hurá	Hurá	hurá-I	I
!	!	!-F	Fe
Hurá	Hurá	hurá-I	I
!	!	!-F	Fe
'	'	'-F	Fa
Shiúil	Shiúil	siúil-V	Vmis
Cian	Cian	Cian-N	Npmsc
thar	thar	thar-S	Sp
na	na	na-T	Td-p
carranna	carranna	carr-N	Ncmpc
uilig	uilig	uile-D	Dq
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
páirceáilte	páirceáilte	páirceáil-A	Av
ar	ar	ar-S	Sp
thaobh	thaobh	taobh-N	Ncmsc
an	an	an-T	Td-s
bhóthair	bhóthair	bóthar-N	Ncmsg
.	.	.-F	Fe
Dathanna	Dathanna	dath-N	Ncmpc
fhoireann	fhoireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g|Npmsc
crochta	crochta	croch-A	Av
ar	ar	ar-S	Sp
gach	gach	gach-D	Dq
aon	aon	aon-D	Dq
cheann	cheann	ceann-N	Ncmsc
acu	acu	ag-P	Pr3-p
nach	nach	is-W	Wprin
mór	mór	mór-A	Aqp
.	.	.-F	Fe
Shiúil	Shiúil	siúil-V	Vmis
sé	sé	sé-P	Pp3msn
síos	síos	síos-R	Rd
an	an	an-T	Td-s
tsráid	tsráid	sráid-N	Ncfsc
thréigthe	thréigthe	tréig-A	Av
.	.	.-F	Fe
Póstaeir	Póstaeir	póstaer-N	Ncmpc
mhóra	mhóra	mór-A	Aq--pc
le	le	le-S	Sp
beannachtaí	beannachtaí	beannacht-N	Ncfpc
daite	daite	daite-A	Aqp
crochta	crochta	croch-A	Av
as	as	as-S	Sp
chuile	chuile	cuile-N	Ncfsc
fhuinneog	fhuinneog	fuinneog-N	Ncfpg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Cian	Cian	Cian-N	Npmsc
ar	ar	ar-S	Sp
buile	buile	buile-N	Ncfsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbainisteoir	mbainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
ann	ann	i-R	Rl|Pr3ms
ach	ach	ach-S	Sp
bréagadóir	bréagadóir	bréagadóir-N	Ncmsc
bradach	bradach	bradach-A	Aq-msc
.	.	.-F	Fe
É	É	é-P	Pp3ms
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
a	a	a-Q	Q-r
sheantrófaí	sheantrófaí	seantraigh-V	Vmc-0
lofa	lofa	lobh-A	Av
!	!	!-F	Fe
‘	‘	‘-X	Xx
Seans	Seans	seans-N	Ncmsc
nár	nár	nár-Q	Qnrs
bhain	bhain	bain-V	Vmis---n
sé	sé	sé-P	Pp3msn
in	in	i-S	Sp
aon	aon	aon-D	Dq
chor	chor	cor-N	Ncmsc
é	é	é-P	Pp3ms
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cian	Cian	Cian-N	Npmsc
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seans	Seans	seans-N	Ncmsc
gur	gur	gur-Q	Q--s
ghoid	ghoid	goid-V	Vmis
sé	sé	sé-P	Pp3msn
ó	ó	ó-S	Sp
bhuachaill	bhuachaill	buachaill-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
eile	eile	eile-D	Dd
é	é	é-P	Pp3ms
!	!	!-F	Fe
Buachaill	Buachaill	buachaill-N	Ncmsc
cosúil	cosúil	cosúil-A	Aq-msc
liomsa	liomsa	le-P	Pr1-s-e
.	.	.-F	Fe
Seans	Seans	seans-N	Ncmsc
gur	gur	is-W	Wsdi
…	…	…-F	Fi
’	’	’-F	Fa
Stop	Stop	stop-V	Vmis|Ncmsc
Cian	Cian	Cian-N	Npm-g|Npmsc
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
taobh amuigh	taobh amuigh	taobh_amuigh-R	Rl
de	de	de-S	Sp
theach	theach	teach-N	Ncmsc
an	an	an-T	Td-s
bhainisteora	bhainisteora	bainisteoir-N	Ncmsg
bhacaigh	bhacaigh	bacach-A	Aq-msg
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
na	na	na-T	Td-p
heochracha	heochracha	eochair-N	Ncfpc
fágtha	fágtha	fág-A	Av
sa	sa	i-S	Spa-s
doras	doras	doras-N	Ncmsc
!	!	!-F	Fe
An	An	an-T	Td-s
iomarca	iomarca	iomarca-N	Ncfsc
deifre	deifre	deifre-N	Ncfsc
chun	chun	chun-S	Sp
na	na	na-T	Tdfsg
páirce	páirce	páirc-N	Ncfsg
is	is	is-W	Wpri
cosúil	cosúil	cosúil-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Cian	Cian	Cian-N	Npmsc
ar	ar	ar-S	Sp
tí	tí	tí-N	Ncfsc
imeacht	imeacht	imigh-N	Ncmsc|Nv
arís	arís	arís-R	Rg
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhuail	bhuail	buail-V	Vmis
smaoineamh	smaoineamh	smaoinigh-N	Ncmsc|Nv
é	é	é-P	Pp3ms
.	.	.-F	Fe
Smaoineamh	Smaoineamh	smaoineamh-N	Ncmsc
dána	dána	dána-A	Aqp
.	.	.-F	Fe
Smaoineamh	Smaoineamh	smaoineamh-N	Ncmsc
gránna	gránna	gránna-A	Aqp
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
sé	sé	sé-P	Pp3msn
mórthimpeall	mórthimpeall	mórthimpeall-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
éinne	éinne	duine-N	Ncmsc
le	le	le-S	Sp
feiceáil	feiceáil	feic-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
tsráid	tsráid	sráid-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
chuile	chuile	gach-D	Dq
dhuine	dhuine	duine-N	Ncmsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
bpáirc	bpáirc	páirc-N	Ncfsc
imeartha	imeartha	imir-A	Aqp|Av
,	,	,-F	Fi
fós	fós	fós-R	Rg
ag	ag	ag-S	Sp
ceiliúradh	ceiliúradh	ceiliúir-N	Nv
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbainisteoir	mbainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
,	,	,-F	Fi
dar	dar	dar-S	Sp
ndóigh	ndóigh	dóigh-N	Ncfsc
!	!	!-F	Fe
Go	Go	go-U	Ua
sciobtha	sciobtha	sciob-A	Aqp|Av
,	,	,-F	Fi
chas	chas	cas-A	Aqp
Cian	Cian	Cian-N	Npmsc
an	an	an-T	Td-s
eochair	eochair	eochair-N	Ncfsc
sa	sa	i-S	Spa-s
ghlas	ghlas	glas-N	Ncmsc|Ncfsc
agus	agus	agus-C	Cc
isteach	isteach	isteach-R	Rd
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
teach	teach	teach-N	Ncmsc
trína	trína	trí-S	Spp-s
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Éadach	Éadach	éadach-N	Ncmsc
agus	agus	agus-C	Cc
bruscar	bruscar	bruscar-N	Ncmpg|Ncmsc
caite	caite	caith-A	Aqp|Av
chuile	chuile	cuile-N	Ncfsg
áit	áit	áit-N	Ncfsc
.	.	.-F	Fe
Ach	Ach	ach-R	Ri
amháin	amháin	amháin-A	Aqp
sa	sa	i-S	Spa-s
seomra	seomra	seomra-N	Ncmsc
suite	suite	suigh-A	Av
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
seomra	seomra	seomra-N	Ncmsc
suite	suite	suigh-A	Aqp|Av
chomh	chomh	chomh-R	Ri
slachtmhar	slachtmhar	slachtmhar-A	Aqp
néata	néata	néata-A	Aqp
lena	lena	le-S	Spr
bhfaca	bhfaca	feic-V	Vmis---d
tú	tú	tú-P	Pp2-s
riamh	riamh	riamh-R	Rg
.	.	.-F	Fe
I	I	i-S	Sp
lár	lár	lár-N	Ncmsc
an	an	an-T	Td-s
mhatail	mhatail	matal-N	Ncmsg
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
trófaí	trófaí	tró-V	Vmc-0
Chú	Chú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
go	go	go-U	Ua
bródúil	bródúil	bródúil-A	Aqp
ina	ina	i-S	Spp-s
aonar	aonar	aonar-N	Ncmsc
.	.	.-F	Fe
An	An	an-Q	Qq
trófaí	trófaí	tró-V	Vmc-0
a	a	a-D	Dp3
chruthaigh	chruthaigh	cruthach-A	Aq-msg|Aq-msv
gur	gur	is-W	Wsdi|Wpdi
saineolaí	saineolaí	saineolach-A	Aqc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
iománaíocht	iománaíocht	iománaíocht-N	Ncfsc
é	é	é-P	Pp3ms
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
Cian	Cian	Cian-N	Npmsc
ar	ar	ar-N	Ncmsc
an	an	an-Q	Qq
trófaí	trófaí	tró-V	Vmc-0
.	.	.-F	Fe
Cú	Cú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
,	,	,-F	Fi
leath	leath	leath-V	Vmm-2s
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
,	,	,-F	Fi
ceangailte	ceangailte	ceangail-A	Av
de	de	de-S	Sp
chloch	chloch	cloch-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
ar	ar	ar-S	Sp
eagla	eagla	eagla-N	Ncfsc
go	go	go-Q	Q
dtitfeadh	dtitfeadh	tit-V	Vmc
sé	sé	sé-P	Pp3msn
go	go	go-S	Sp
talamh	talamh	talamh-N	Ncfsc
roimh	roimh	roimh-S	Sp
a	a	a-D	Dp3
namhaid	namhaid	namhaid-N	Ncmsc
.	.	.-F	Fe
A	A	a-U	Uv
cheann	cheann	ceann-N	Ncmsv
cromtha	cromtha	crom-A	Av
go	go	go-U	Ua
brónach	brónach	brónach-A	Aqp
.	.	.-F	Fe
Fiach	Fiach	fiach-V	Vmm-2s
dubh	dubh	dubh-N	Ncmsc
ar	ar	ar-N	Ncmsc|Sp
a	a	a-D	Dp3
ghualainn	ghualainn	gualainn-N	Ncfsc
.	.	.-F	Fe
Cú	Cú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
.	.	.-F	Fe
t	t	t-X	Xl
‑	‑	‑-F	Fb
iománaí	iománaí	iománaí-N	Ncmsc
is	is	is-U	U
fearr	fearr	maith-A	Aqc
a	a	a-Q	Q-r
thóg	thóg	tóg-V	Vmis
camán	camán	camán-N	Ncmsc
ina	ina	i-S	Spp-s|Spp-p
lámh	lámh	lámh-N	Ncfsc
riamh	riamh	riamh-R	Rg
.	.	.-F	Fe
Fear	Fear	fear-N	Ncmsc
a	a	a-Q	Q-r
thuig	thuig	tuig-V	Vmip|Vmis
ceart	ceart	ceart-N	Ncmsc
agus	agus	agus-C	Cc
cóir	cóir	cóir-N	Ncfsc|Ncmsg|Ncmpc|Aqp|Ns-s
.	.	.-F	Fe
Lig	Lig	lig-V	Vmis
Cian	Cian	Cian-N	Npmsc
osna	osna	osna-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
a	a	a-D	Dp3
leithéid	leithéid	leithéid-N	Ncfsc
de	de	de-P	Pr3ms
thrófaí	thrófaí	tró-V	Vmc-0
tuillte	tuillte	tuill-A	Av
ag	ag	ag-S	Sp
an	an	an-T	Td-s
mbainisteoir	mbainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sé	sé	sé-P	Pp3msn
ceart	ceart	ceart-A	Aqp
ná	ná	ná-C	Cc
cóir	cóir	cóir-N	Ncfsc|Ns-s|Ncmpc|Aqp
ag	ag	ag-S	Sp
Cian	Cian	Cian-N	Npmsc
é	é	é-P	Pp3ms
a	a	a-U	U
ghoid	ghoid	goid-N	Nv
uaidh	uaidh	ó-P	Pr3ms
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
oiread	oiread	oiread-N	Ns-s
.	.	.-F	Fe
Chas	Chas	Cas-N	Npfsg
Cian	Cian	Cian-N	Npm-g|Npmsc
ar	ar	is-W	Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
sháil	sháil	sáil-N	Ncfsc
agus	agus	agus-C	Cc
amach	amach	amach-R	Rd
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Thit	Thit	tit-V	Vmis
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
ina	ina	i-S	Spp-s
chnap	chnap	cnap-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcathaoir	gcathaoir	cathaoir-N	Ncfsc
bhog	bhog	bog-A	Aq-fsc
sa	sa	i-S	Spa-s
seomra	seomra	seomra-N	Ncmsc
suite	suite	suigh-A	Aqp|Av
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
sé	sé	sé-P	Pp3msn
trasna	trasna	trasna-R	Rd
ar	ar	ar-Q	Q-p
a	a	a-Q	Q-r
thrófaí	thrófaí	tró-V	Vmc-0
luachmhar	luachmhar	luachmhar-A	Aqp
.	.	.-F	Fe
Trófaí	Trófaí	tró-V	Vmc-0
Chú	Chú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
.	.	.-F	Fe
t	t	t-X	Xl
‑	‑	‑-F	Fb
iománaí	iománaí	iománaí-N	Ncmsc
is	is	is-U	U
fearr	fearr	maith-A	Aqc
a	a	a-Q	Q-r
thóg	thóg	tóg-V	Vmis
camán	camán	camán-N	Ncmsc
ina	ina	i-S	Spp-s|Spp-p
lámh	lámh	lámh-N	Ncfsc
riamh	riamh	riamh-R	Rg
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
náire	náire	náire-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbainisteoir	mbainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
breathnaigh	breathnaigh	breathnaigh-V	Vmm-2s-n
orm	orm	ar-P	Pr1-s
mar	mar	mar-C	Cs
sin	sin	sin-W	W
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sé	sé	sé-P	Pp3msn
le	le	le-S	Sp
trófaí	trófaí	tró-V	Vmc-0
Chú	Chú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bheinn	Bheinn	bí-V	Vmc-1s
i	i	i-S	Sp
mo	mo	mo-D	Dp1-s
cheap	cheap	ceap-N	Ncmsc
magaidh	magaidh	magadh-N	Ncmsg
ceart	ceart	ceart-A	Aq-msc
i	i	i-S	Sp
measc	measc	measc-N	Ncmsc
an	an	an-T	Td-s
phobail	phobail	pobal-N	Ncmsg
dá	dá	de-S	Spp-s
n	n	n-X	Xl
‑	‑	‑-F	Fb
inseoinn	inseoinn	inis-V	Vmc-1s
dóibh	dóibh	do-P	Pr3-p
gurb	gurb	is-W	Wpdi
é	é	é-P	Pp3ms
Cian	Cian	Cian-N	Npmsc
is	is	agus-C	Cc
nach	nach	nach-W	Wprin|Wpdin|Wpsin|Cs
mise	mise	mé-P	Pp1-s-e
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
oibrigh	oibrigh	oibrigh-V	Vmm-2s
amach	amach	amach-R	Rd
na	na	na-T	Td-p
straitéisí	straitéisí	straitéis-N	Ncfpc
imeartha	imeartha	imir-A	Av
don	don	do-S	Spa-s
fhoireann	fhoireann	foireann-N	Ncfsc
!	!	!-F	Fe
Samhlaigh	Samhlaigh	samhlaigh-V	Vmm-2s
é	é	é-P	Pp3ms
!	!	!-F	Fe
'	'	'-F	Fa
Thóg	Thóg	tóg-V	Vmis
Cú	Cú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
a	a	a-D	Dp3
cheann	cheann	ceann-N	Ncmsc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
idir	idir	idir-S	Sp
an	an	an-T	Td-s
dá	dá	dó-M	Mc
shúil	shúil	súil-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbainisteoir	mbainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
cuma	cuma	cuma-A	Aqp
má	má	má-C	Cs
fhaighim	fhaighim	faigh-V	Vmip1s
bás	bás	bás-N	Ncmsc
inniu	inniu	inniu-R	Rt
nó	nó	nó-C	Cc
amárach	amárach	amárach-A	Aqp|Rt|Ns-s
,	,	,-F	Fi
chomh	chomh	chomh-R	Ri
fada	fada	fada-A	Aqp
is	is	agus-C	Cc
go	go	go-Q	Q
mairfidh	mairfidh	mair-V	Vmif
mo	mo	mo-D	Dp1-s
chlú	chlú	clú-N	Ncmsc
is	is	agus-C	Cc
mo	mo	mo-D	Dp1-s
cháil	cháil	cáil-N	Ncmpc|Ncfsc
?	?	?-F	Fq
'	'	'-F	Fa
ar	ar	ar-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Léim	Léim	léim-V	Vmip1s|Vmm-2s|Vmis
croí	croí	croí-N	Ncmsc
an	an	an-T	Td-s
bhainisteora	bhainisteora	bainisteoir-N	Ncmsg
bhacaigh	bhacaigh	bacach-A	Aq-msv|Aq-msg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Sin	Sin	sin-W	W
é	é	é-P	Pp3ms
go	go	go-U	Ua
díreach	díreach	díreach-A	Aqp
é	é	é-P	Pp3ms
!	!	!-F	Fe
'	'	'-F	Fa
ar	ar	ar-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-U	Ua
sásta	sásta	sásta-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
go	go	go-Q	Q
dtuigfeá	dtuigfeá	tuig-V	Vmc-2s
mo	mo	mo-D	Dp1-s
chás	chás	cás-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Mo	Mo	mo-D	Dp1-s
náire	náire	náire-N	Ncfsc
thú	thú	tú-P	Pp2-s
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
trófaí	trófaí	tró-V	Vmc-0
Chú	Chú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
agus	agus	agus-C	Cc
nimh	nimh	nimh-N	Ncfsc
ina	ina	i-S	Spp-s
ghlór	ghlór	glór-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agat	agat	ag-P	Pr2-s
nach	nach	nach-Q	Qnr
bhfuil	bhfuil	bí-V	Vmip---n
ionat	ionat	i-P	Pr2-s
ach	ach	ach-S	Sp
feallaire	feallaire	feallaire-N	Ncmsc
lofa	lofa	lobh-A	Aqp|Av
agus	agus	agus-C	Cc
bréagadóir	bréagadóir	bréagadóir-N	Ncmsc
bradach	bradach	bradach-A	Aq-msc
!	!	!-F	Fe
'	'	'-F	Fa
Chrom	Chrom	crom-V	Vmis
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
a	a	a-D	Dp3
cheann	cheann	ceann-N	Ncmsc
le	le	le-S	Sp
náire	náire	náire-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Aclaíocht	Aclaíocht	aclaíocht-N	Ncfsc
!	!	!-F	Fe
Dílseacht	Dílseacht	dílseacht-N	Ncfsc
!	!	!-F	Fe
Ónóir	Ónóir	ónóir-N	Ncmsc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-Q	Qq
trófaí	trófaí	tró-V	Vmc-0
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
leor	leor	leor-A	Aqp
ceann	ceann	ceann-N	Ncmsc
amháin	amháin	amháin-A	Aqp
d	d	d-X	Xl
’	’	’-F	Fa
uireasa	uireasa	uireasa-N	Ncfsc
na	na	na-T	Td-p
gceann	gceann	ceann-N	Ncmpg
eile	eile	eile-D	Dd
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
leatsa	leatsa	le-P	Pr2-s-e
an	an	an-T	Td-s
clú	clú	clú-N	Ncmsc
is	is	agus-W	Wp-i|Wpri|Cc
an	an	an-T	Td-s
cháil	cháil	cál-N	Ncmsg
má	má	má-C	Cs
ghoid	ghoid	goid-V	Vmis
tú	tú	tú-P	Pp2-s
ó	ó	ó-S	Sp
dhuine	dhuine	duine-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
eile	eile	eile-D	Dd
é	é	é-P	Pp3ms
.	.	.-F	Fe
'	'	'-F	Fa
Chrom	Chrom	crom-V	Vmis
Cú	Cú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
a	a	a-D	Dp3
cheann	cheann	ceann-N	Ncmsc
agus	agus	agus-C	Cc
sheas	sheas	seas-N	Ncmsc
balbh	balbh	balbh-A	Aq-msc
arís	arís	arís-R	Rg
ar	ar	ar-S	Sp
an	an	an-T	Td-s
matal	matal	matal-N	Ncmsc
.	.	.-F	Fe
Thuig	Thuig	tuig-V	Vmis
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
céard	céard	cé-W	W--q
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
le	le	le-S	Sp
déanamh	déanamh	déan-N	Nv
anois	anois	anois-R	Rt
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
mórán	mórán	mórán-N	Ncmsc
cuir	cuir	cur-N	Ncmsg
agus	agus	agus-C	Cc
cúitimh	cúitimh	cúitigh-N	Ncmsg|Ncmpc|Nv--g
bheartaigh	bheartaigh	beartaigh-V	Vmis
Cian	Cian	Cian-N	Npmsc
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
chuig	chuig	chuig-S	Sp
an	an	an-T	Td-s
gcluiche	gcluiche	cluiche-N	Ncmsc
ceannais	ceannais	ceannais-A	Aq-msc
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
theastaigh	theastaigh	teastaigh-V	Vmis---n
uaidh	uaidh	ó-P	Pr3ms
gan	gan	gan-S	Sp
foireann	foireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
ag	ag	ag-S	Sp
imirt	imirt	imir-N	Nv
i	i	i-S	Sp
bPáirc	bPáirc	páirc-N	Ncfsc
an	an	an-Q	Qq
Chrócaigh	Chrócaigh	crócaigh-V	Vmis
.	.	.-F	Fe
Nár	Nár	is-W	Wssin
chuma	chuma	cuma-A	Aqp
mura	mura	mura-C	Cs
raibh	raibh	bí-V	Vmis---d
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
acu	acu	ag-P	Pr3-p
gur	gur	is-W	Wsdi
mar	mar	mar-S	Sp
gheall	gheall	geall-N	Ncmsc
airsean	airsean	ar-P	Pr3ms-e
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
aige	aige	ag-P	Pr3ms
féin	féin	féin-P	Px
gurbh	gurbh	is-W	Wsdi
in	in	sin-P	Pd
an	an	an-T	Td-s
cás	cás	cás-N	Ncmsc
.	.	.-F	Fe
B	B	B-X	Xl
’	’	’-F	Fa
in	in	i-S	Sp
an	an	an-T	Td-s
rud	rud	rud-N	Ncmsc
ba	ba	is-U	U
thábhachtaí	thábhachtaí	tábhachtach-A	Aqc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Páirc	Páirc	páirc-N	Ncfsc
an	an	an-Q	Qq
Chrócaigh	Chrócaigh	crócaigh-V	Vmis
ag	ag	ag-S	Sp
damhsa	damhsa	damhsaigh-N	Nv
le	le	le-S	Sp
lucht	lucht	lucht-N	Ncmsc
leanúna	leanúna	lean-N	Ncfsg|Nv--g
Setanta	Setanta	Setanta-N	Npm-g|Npmsc
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
siad	siad	siad-P	Pp3-pn
ó	ó	ó-S	Sp
gach	gach	gach-D	Dq
cearn	cearn	cearn-N	Ncfsc
den	den	de-S	Spa-s
chontae	chontae	contae-N	Ncmsc
.	.	.-F	Fe
Chuile	Chuile	gach-D	Dq
dhuine	dhuine	duine-N	Ncmsg
acu	acu	ag-P	Pr3-p
ag	ag	ag-S	Sp
caitheamh	caitheamh	caith-N	Nv
dathanna	dathanna	dath-N	Ncmpg
an	an	an-T	Td-s
chlub	chlub	club-N	Ncmsg
go	go	go-U	Ua
mórtasach	mórtasach	mórtasach-A	Aqp
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
Cian	Cian	Cian-N	Npmsc
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
ina	ina	i-S	Spp-s
sheasamh	sheasamh	seasamh-N	Ncmsc
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
ar	ar	ar-S	Sp
an	an	an-T	Td-s
taobhlíne	taobhlíne	taobhlíne-N	Ncfsc
.	.	.-F	Fe
Amach	Amach	amach-R	Rd
leis	leis	le-S	Sp
na	na	na-T	Td-p
himreoirí	himreoirí	imreoir-N	Ncmpc
.	.	.-F	Fe
Séideadh	Séideadh	séideadh-V	Vmis0|Vmm-3s|Ncmsc
an	an	an-T	Td-s
fheadóg	fheadóg	feadóg-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
cluiche	cluiche	cluiche-N	Ncmsc
tosaithe	tosaithe	tosaigh-A	Av
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
suas	suas	suas-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
slua	slua	slua-N	Ncmsc
mór	mór	mór-A	Aq-msc
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
chun	chun	chun-S	Sp
tacaíocht	tacaíocht	tacaíocht-N	Ncfsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
d	d	d-X	Xl
’	’	’-F	Fa
fhoireann	fhoireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g|Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
cuartú	cuartú	cuartú-N	Nv
aghaidh	aghaidh	aghaidh-N	Ncfsc
amháin	amháin	amháin-A	Aqp
ina	ina	i-S	Spp-p|Spp-s
measc	measc	measc-N	Ncmsc
.	.	.-F	Fe
Aghaidh	Aghaidh	aghaidh-N	Ncfsc
buachalla	buachalla	buachaill-N	Ncmsg
dhá	dhá	dó-M	Mc
bhliain	bhliain	bliain-N	Ncfsc
déag	déag	déag-N	Ns-s
d	d	d-X	Xl
’	’	’-F	Fa
aois	aois	aois-N	Ncfsc
.	.	.-F	Fe
Buachaill	Buachaill	buachaill-N	Ncmsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
‑	‑	‑-F	Fb
tuiscint	tuiscint	tuig-N	Ncfsc|Nv
aige	aige	ag-P	Pr3ms
ar	ar	ar-S	Sp
an	an	an-T	Td-s
iománaíocht	iománaíocht	iománaíocht-N	Ncfsc
,	,	,-F	Fi
cé	cé	cé-C	Cs
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
ar	ar	ar-S	Sp|Ncmsc
a	a	a-Q	Q-r
chumas	chumas	cum-V	Vmis1s
an	an	an-T	Td-s
cluiche	cluiche	cluiche-N	Ncmsc
a	a	a-U	U
imirt	imirt	imir-N	Nv
go	go	go-U	Ua
maith	maith	maith-A	Aqp
é	é	é-P	Pp3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
Is	Is	is-W	Wp-i
ansin	ansin	ansin-R	Rt|Rl
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
é	é	é-P	Pp3ms
.	.	.-F	Fe
Cian	Cian	Cian-N	Npmsc
Ó	Ó	Ó-U	Up
Buacháin	Buacháin	Buacháin-N	Npmsc
ag	ag	ag-S	Sp
béicíl	béicíl	béicíl-N	Nv-----n
is	is	agus-C	Cc
ag	ag	ag-S	Sp
screadaíl	screadaíl	screadaíl-N	Ncfsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
bhfoireann	bhfoireann	foireann-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Suas	Suas	suas-R	Rd
an	an	an-T	Td-s
pháirc	pháirc	páirc-N	Ncfsc
libh	libh	le-P	Pr2-p
,	,	,-F	Fi
a	a	a-U	Uv
leisceoirí	leisceoirí	leisceoir-N	Ncmpv
lofa	lofa	lobh-A	Aqp|Av
!	!	!-F	Fe
Ní	Ní	is-W	Wp-in
sa	sa	i-S	Spa-s
bhaile	bhaile	baile-N	Ncmsc
ag	ag	ag-S	Sp
cniotáil	cniotáil	cniotáil-N	Nv
atá	atá	bí-V	Vmip---r
sibh	sibh	sibh-P	Pp2-p
anois	anois	anois-R	Rt
!	!	!-F	Fe
'	'	'-F	Fa
ar	ar	ar-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Rinne	Rinne	déan-V	Vmis
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
gáire	gáire	gáire-N	Ncmsc
beag	beag	beag-A	Aq-msc
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
‑	‑	‑-F	Fb
sásta	sásta	sásta-A	Aqc
gur	gur	gur-Q	Q--s
sheol	sheol	seol-V	Vmis
sé	sé	sé-P	Pp3msn
ticéad	ticéad	ticéad-N	Ncmsc
don	don	do-S	Spa-s
chluiche	chluiche	cluiche-N	Ncmsc
chuig	chuig	chuig-S	Sp
Cian	Cian	Cian-N	Npmsc
.	.	.-F	Fe
Rith	Rith	rith-V	Vmm-2s|Vmis
na	na	na-T	Td-p
himreoirí	himreoirí	imreoir-N	Ncmpc
suas	suas	suas-R	Rd
síos	síos	síos-R	Rd
an	an	an-T	Td-s
pháirc	pháirc	páirc-N	Ncfsc
gan	gan	gan-S	Sp
stad	stad	stad-N	Nv
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
a	a	a-D	Dp3
sárú	sárú	sárú-N	Ncmsc
le	le	le-S	Sp
fáil	fáil	faigh-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
slua	slua	slua-N	Ncmsc
ag	ag	ag-S	Sp
screadaíl	screadaíl	screadaíl-N	Ncfsc
is	is	agus-C	Cc
ag	ag	ag-S	Sp
béicíl	béicíl	béicíl-N	Nv-----n
in	in	sin-S	Sp|Pd
ard	ard	ard-N	Ncmsc|Aqp
a	a	a-D	Dp3
ngutha	ngutha	guth-N	Ncmsg
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
séideadh	séideadh	séid-V	Vmis0
an	an	an-T	Td-s
fhead	fhead	fead-N	Ncfsc
deiridh	deiridh	deireadh-N	Ncmsg
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
amhras	amhras	amhras-N	Ncmsc
ann	ann	i-P	Pr3ms
ach	ach	ach-C	Cs
gurbh	gurbh	is-W	Wsdi
í	í	í-P	Pp3fs
foireann	foireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g|Npmsc
an	an	an-T	Td-s
fhoireann	fhoireann	foireann-N	Ncfsc
ab	ab	is-U	U
fhearr	fhearr	maith-A	Aqc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
lá	lá	lá-N	Ncmsc
.	.	.-F	Fe
Cheap	Cheap	ceap-V	Vmis
Cian	Cian	Cian-N	Npmsc
go	go	go-Q	Q
bpléascfadh	bpléascfadh	pléasc-V	Vmc
a	a	a-D	Dp3
chroí	chroí	croí-N	Ncmsc
le	le	le-S	Sp
háthas	háthas	áthas-N	Ncmsc
agus	agus	agus-C	Cc
le	le	le-S	Sp
bród	bród	bród-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcaptaen	gcaptaen	captaen-N	Ncmsc
,	,	,-F	Fi
Aodh	Aodh	Aodh-N	Npmsc
Ó	Ó	Ó-U	Up
Dubhthaigh	Dubhthaigh	Dubhthaigh-N	Np
,	,	,-F	Fi
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
anois	anois	anois-R	Rt
ag	ag	ag-S	Sp
glacadh	glacadh	glac-N	Nv
an	an	an-T	Td-s
choirn	choirn	corn-N	Ncmsg
ar son	ar son	ar_son-S	Spc
na	na	na-T	Td-p
foirne	foirne	foireann-N	Ncfpg
.	.	.-F	Fe
Ba	Ba	is-W	Ws|Ws-i
chuma	chuma	cuma-A	Aqp
anois	anois	anois-R	Rt
cén	cén	cé-D	Dw--s
chaoi	chaoi	caoi-N	Ncfsc
ar	ar	ar-Q	Q-is
éirigh	éirigh	éirigh-V	Vmis
le	le	le-S	Sp
foireann	foireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g
a	a	a-U	U
theacht	theacht	tar-N	Nv
go	go	go-S	Sp
Páirc	Páirc	páirc-N	Ncfsc
an	an	an-Q	Qq
Chrócaigh	Chrócaigh	crócaigh-V	Vmis
,	,	,-F	Fi
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
corn	corn	corn-N	Ncmsc|Xfen
a	a	a-U	U
bheith	bheith	bí-N	Nv
leo	leo	le-P	Pr3-p
chun	chun	chun-S	Sp
an	an	an-T	Td-s
bhaile	bhaile	baile-N	Ncmsg
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
an	an	an-T	Td-s
captaen	captaen	captaen-N	Ncmsc
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
agus	agus	agus-C	Cc
thit	thit	tit-V	Vmis
tost	tost	tost-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
slua	slua	slua-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
mór	mór	mór-A	Aqp
an	an	an-T	Td-s
onóir	onóir	onóir-N	Ncfsc
domsa	domsa	do-P	Pr1-s-e
an	an	an-T	Td-s
corn	corn	corn-N	Ncmsc
seo	seo	seo-D	Dd
a	a	a-U	U
ghlacadh	ghlacadh	glac-N	Nv
ar son	ar son	ar_son-S	Spc
fhoireann	fhoireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g|Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
Phléasc	Phléasc	pléasc-V	Vmis
an	an	an-T	Td-s
slua	slua	slua-N	Ncmsc
.	.	.-F	Fe
Lean	Lean	Lean-N	Npmsc
an	an	an-T	Td-s
captaen	captaen	captaen-N	Ncmsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Murach	Murach	murach-C	Cs
fear	fear	fear-N	Ncmsc
amháin	amháin	amháin-A	Aqp
,	,	,-F	Fi
ní	ní	ní-Q	Qn
bheadh	bheadh	bí-V	Vmc----n
muid	muid	muid-P	Pp1-p
anseo	anseo	anseo-R	Rl
inniu	inniu	inniu-R	Rt
.	.	.-F	Fe
A	A	a-U	Uv
dhaoine	dhaoine	duine-N	Ncmpv
uaisle	uaisle	uasal-A	Aq--pv
,	,	,-F	Fi
Seán	Seán	Seán-N	Npmsc
de	de	de-U	Up
Paor	Paor	Paor-N	Npmsc
,	,	,-F	Fi
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
!	!	!-F	Fe
'	'	'-F	Fa
Shiúil	Shiúil	siúil-V	Vmis
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
i	i	i-S	Sp
dtreo	dtreo	treo-N	Ncmsc
an	an	an-T	Td-s
chaptaein	chaptaein	captaen-N	Ncmsg
.	.	.-F	Fe
Thóg	Thóg	tóg-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
corn	corn	corn-N	Ncmsc
ina	ina	i-S	Spp-s|Spp-p
lámh	lámh	lámh-N	Ncfsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
sé	sé	sé-P	Pp3msn
idir	idir	idir-S	Sp
an	an	an-T	Td-s
dá	dá	dó-M	Mc
shúil	shúil	súil-N	Ncfsc
ar	ar	ar-S	Sp
Chian	Chian	Cian-N	Npmsc
agus	agus	agus-C	Cc
tharraing	tharraing	tarraing-V	Vmis
anáil	anáil	anáil-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
cheolmhar	cheolmhar	ceolmhar-A	Aq-fsc
trína	trína	trí-S	Spp-s
fhiacla	fhiacla	fiacail-N	Ncfpc
briste	briste	bris-A	Aqp|Av
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	an-T	Td-s
bhuíochas	bhuíochas	buíochas-N	Ncmsc
do	do	do-S	Sp
Chian	Chian	Cian-N	Npmsc
Ó	Ó	Ó-U	Up
Buacháin	Buacháin	Buacháin-N	Npmsc
atáimid	atáimid	bí-V	Vmip1p-r
anseo	anseo	anseo-R	Rl
inniu	inniu	inniu-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sé	sé	sé-P	Pp3msn
amach	amach	amach-R	Rd
go	go	go-U	Ua
hard	hard	ard-X	Xfea|Aqp
.	.	.-F	Fe
Thit	Thit	tit-V	Vmis
tost	tost	tost-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
slua	slua	slua-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
chuile	chuile	gach-D	Dq
dhuine	dhuine	duine-N	Ncmsc
ar	ar	ar-S	Sp
Chian	Chian	Cian-N	Npmsc
.	.	.-F	Fe
Céard	Céard	cé-W	W--q
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
i	i	i-S	Sp
gceist	gceist	ceist-N	Ncfsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
mbainisteoir	mbainisteoir	bainisteoir-N	Ncmsc
?	?	?-F	Fq
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
hionann	hionann	ionann-A	Aqp
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
imreoir	imreoir	imreoir-N	Ncmsc
maith	maith	maith-A	Aq-msc
agus	agus	agus-C	Cc
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
cumasach	cumasach	cumasach-A	Aq-msc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
b	b	b-X	Xl
’	’	’-F	Fa
in	in	sin-P	Pd
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sa	sa	i-S	Spa-s
chás	chás	cás-N	Ncmsc
agamsa	agamsa	ag-P	Pr1-s-e
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
fear	fear	fear-N	Ncmsc
óg	óg	óg-A	Aq-msc
seo	seo	seo-D	Dd
,	,	,-F	Fi
Cian	Cian	Cian-N	Npmsc
Ó	Ó	Ó-U	Up
Buacháin	Buacháin	Buacháin-N	Npmsc
,	,	,-F	Fi
tar éis	tar éis	tar_éis-S	Spc
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
obair	obair	obair-N	Nv-----n
liom	liom	le-P	Pr1-s
t	t	t-X	Xl
‑	‑	‑-F	Fb
am	am	am-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
ag	ag	ag-S	Sp
cur	cur	cuir-N	Nv
straitéisí	straitéisí	straitéis-N	Ncmsg|Ncfpg|Ncmsc|Ncfpg|Ncfpc
imeartha	imeartha	imir-A	Aqp|Av
cruinne	cruinne	cruinn-A	Aq-fsg
,	,	,-F	Fi
cliste	cliste	clis-A	Aqp|Av
,	,	,-F	Fi
cumasacha	cumasacha	cumasach-A	Aq--pg|Aq--pc|Aq--pv
ar	ar	ar-S	Sp
fáil	fáil	faigh-N	Nv
d	d	d-X	Xl
’	’	’-F	Fa
fhoireann	fhoireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g|Npmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
dhearna	dhearna	déan-V	Vmis---n
mise	mise	mé-P	Pp1-s-e
ach	ach	ach-S	Sp|Cs
iad	iad	iad-P	Pp3-p
a	a	a-U	U
chur	chur	cuir-N	Nv
i láthair	i láthair	i_láthair-S	Spc
na	na	na-T	Td-p
foirne	foirne	foireann-N	Ncfpg
.	.	.-F	Fe
Is	Is	is-W	Wp-i
é	é	é-P	Pp3ms
Cian	Cian	Cian-N	Npmsc
a	a	a-Q	Q-r
rinne	rinne	déan-V	Vmis
an	an	an-T	Td-s
obair	obair	obair-N	Ncfsc
chrua	chrua	crua-A	Aqp
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
.	.	.-F	Fe
A	A	a-U	Uv
dhaoine	dhaoine	duine-N	Ncmpv
uaisle	uaisle	uasal-A	Aq--pv
,	,	,-F	Fi
cuirim	cuirim	cuir-V	Vmip1s
in	in	sin-P	Pd
bhur	bhur	bhur-D	Dp2-p
láthair	láthair	láthair-N	Ncfsc
sárstraitéisí	sárstraitéisí	straitéisí-N	Ncmsc
fhoireann	fhoireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g|Npmsc
,	,	,-F	Fi
Cian	Cian	Cian-N	Npmsc
Ó	Ó	Ó-U	Up
Buacháin	Buacháin	Buacháin-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
,	,	,-F	Fi
shín	shín	sín-V	Vmis
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
an	an	an-T	Td-s
corn	corn	corn-N	Ncmsc
chuig	chuig	chuig-S	Sp
Cian	Cian	Cian-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
fíorbhrón	fíorbhrón	brón-N	Ncmsc
orm	orm	ar-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sé	sé	sé-P	Pp3msn
de	de	de-S	Sp
chogar	chogar	cogar-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Rinne	Rinne	déan-V	Vmis
mé	mé	mé-P	Pp1-s
feall	feall	feall-N	Ncmsc
uafásach	uafásach	uafásach-A	Aq-msc
ort	ort	ar-P	Pr2-s
.	.	.-F	Fe
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
iontas	iontas	iontas-N	Ncmsc
an	an	an-T	Td-s
domhain	domhain	domhan-N	Ncmsg
ar	ar	ar-S	Sp
Chian	Chian	Cian-N	Npmsc
.	.	.-F	Fe
Ghlac	Ghlac	glac-V	Vmis
sé	sé	sé-P	Pp3msn
leis	leis	le-S	Sp
an	an	an-T	Td-s
gcorn	gcorn	corn-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
trom	trom	trom-A	Aqp
.	.	.-F	Fe
Thóg	Thóg	tóg-V	Vmis
na	na	na-T	Td-p
himreoirí	himreoirí	imreoir-N	Ncmpc
Cian	Cian	Cian-N	Npm-g|Npmsc
in	in	i-S	Sp
airde	airde	airde-N	Ncfpc|Ncfsc
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
nguaillí	nguaillí	gualainn-N	Ncmsc|Ncfpc
agus	agus	agus-C	Cc
d	d	d-X	Xl
’	’	’-F	Fa
iompar	iompar	iompair-N	Ncmsc|Nv
timpeall	timpeall	timpeall-S	Sp
na	na	na-T	Tdfsg
páirce	páirce	páirc-N	Ncfsg
é	é	é-P	Pp3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
slua	slua	slua-N	Ncmsc
ar	ar	ar-S	Sp
bís	bís	bís-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Hurá	Hurá	hurá-I	I
!	!	!-F	Fe
Hurá	Hurá	hurá-I	I
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
siad	siad	siad-P	Pp3-pn
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	an-T	Td-s
bhuíochas	bhuíochas	buíochas-N	Ncmsc
do	do	do-S	Sp
Chian	Chian	Cian-N	Npmsc
atáimid	atáimid	bí-V	Vmip1p-r
anseo	anseo	anseo-R	Rl
!	!	!-F	Fe
'	'	'-F	Fa
Siúd	Siúd	siúd-P	Pd
leis	leis	le-S	Sp
na	na	na-T	Td-p
hiriseoirí	hiriseoirí	iriseoir-N	Ncmpc
ag	ag	ag-S	Sp
scríobh	scríobh	scríobh-N	Nv
ina	ina	i-S	Spp-s|Spp-p
leabhar	leabhar	leabhar-N	Ncmsc
nótaí	nótaí	nóta-N	Ncmpg|Ncmpc
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
clic	clic	clic-N	Ncmsc
‑	‑	‑-F	Fb
clic	clic	clic-N	Ncmsc
‑	‑	‑-F	Fb
cliceáil	cliceáil	cliceáil-V	Vmm-2s|Nv
na	na	na-T	Td-p
gceamaraí	gceamaraí	ceamara-N	Ncmpg
arís	arís	arís-R	Rg
.	.	.-F	Fe
Theastaigh	Theastaigh	teastaigh-V	Vmis
ó	ó	ó-S	Sp
gach	gach	gach-D	Dq
éinne	éinne	duine-N	Ncmsc
grianghraf	grianghraf	grianghraf-N	Ncmpg|Ncmsc
a	a	a-U	U
fháil	fháil	faigh-N	Nv
de	de	de-S	Sp
Chian	Chian	Cian-N	Npmsc
.	.	.-F	Fe
Rinneadh	Rinneadh	déan-V	Vmis0
dearmad	dearmad	dearmad-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbainisteoir	mbainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
.	.	.-F	Fe
Sheas	Sheas	seas-V	Vmis
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
ag	ag	ag-S	Sp
geataí	geataí	geata-N	Ncmpc
Pháirc	Pháirc	páirc-N	Ncfsc
an	an	an-Q	Qq
Chrócaigh	Chrócaigh	crócaigh-V	Vmis
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
fanacht	fanacht	fan-N	Nv
leis	leis	le-S	Sp
an	an	an-T	Td-s
mbus	mbus	bus-N	Ncmsc
le	le	le-S	Sp
hé	hé	é-P	Pp3ms
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
chun	chun	chun-S	Sp
an	an	an-T	Td-s
bhaile	bhaile	baile-N	Ncmsg
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
Cian	Cian	Cian-N	Npmsc
é	é	é-P	Pp3ms
agus	agus	agus-C	Cc
chuaigh	chuaigh	téigh-V	Vmis
anonn	anonn	anonn-R	Rd
chuige	chuige	chuig-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Go	Go	go-Q	Q-s
raibh	raibh	bí-V	Vmsp
maith	maith	maith-N	Ncfsc
agat	agat	ag-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
‘	‘	‘-X	Xx
Go	Go	go-Q	Q-s
ndéana	ndéana	déan-V	Vmsp
a	a	a-D	Dp3
mhaith	mhaith	maith-N	Ncfsc
duit	duit	do-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
.	.	.-F	Fe
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
tháinig	tháinig	tar-V	Vmis
an	an	an-T	Td-s
bus	bus	bus-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Inis	Inis	inis-V	Vmis
seo	seo	seo-P	Pd
dom	dom	do-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Cian	Cian	Cian-N	Npmsc
agus	agus	agus-C	Cc
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
ar	ar	ar-S	Sp
tí	tí	tí-N	Ncfsc
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbus	mbus	bus-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cad	Cad	cad-P	Pq
a	a	a-Q	Q-r
thug	thug	tabhair-V	Vmis
ort	ort	ar-P	Pr2-s
an	an	an-T	Td-s
fhírinne	fhírinne	fírinne-N	Ncfsc
a	a	a-U	U
insint	insint	inis-N	Nv
?	?	?-F	Fq
'	'	'-F	Fa
‘	‘	‘-X	Xx
Don	Don	do-S	Spa-s
aclaíocht	aclaíocht	aclaíocht-N	Ncfsc
,	,	,-F	Fi
don	don	do-S	Spa-s
dílseacht	dílseacht	dílseacht-N	Ncfsc
agus	agus	agus-C	Cc
don	don	do-S	Spa-s
onóir	onóir	onóir-N	Ncfsc
a	a	a-Q	Q-r
sheasann	sheasann	seas-V	Vmip
trófaí	trófaí	tró-V	Vmc-0
Chú	Chú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
,	,	,-F	Fi
an	an	an-Q	Qq
dtuigeann	dtuigeann	tuig-V	Vmip
tú	tú	tú-P	Pp2-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Dá	Dá	de-S	Spp-s
n	n	n-X	Xl
‑	‑	‑-F	Fb
uireasa	uireasa	uireasa-N	Ncfsc
níor	níor	is-W	Ws-in
cheart	cheart	ceart-A	Aqp
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
sé	sé	sé-P	Pp3msn
suite	suite	suigh-A	Av
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
do	do	do-S	Sp
mhatal	mhatal	matal-N	Ncmsc
agat	agat	ag-P	Pr2-s
sa	sa	i-S	Spa-s
bhaile	bhaile	baile-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Léim	Léim	léim-V	Vmip1s|Vmm-2s|Nv|Ncfsc|Vmis|Nv
an	an	an-T	Td-s
bainisteoir	bainisteoir	bainisteoir-N	Ncmsc
bacach	bacach	bacach-A	Aq-msc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbus	mbus	bus-N	Ncmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
Cian	Cian	Cian-N	Npmsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
.	.	.-F	Fe
Má	Má	má-N	Ncfsc|Cs
b	b	b-X	Xl
’	’	’-F	Fa
in	in	i-S	Sp
an	an	an-T	Td-s
cás	cás	cás-N	Ncmsc
,	,	,-F	Fi
b	b	b-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
trófaí	trófaí	tró-V	Vmc-0
Chú	Chú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
suite	suite	suigh-A	Av
ar	ar	ar-S	Sp
an	an	an-T	Td-s
matal	matal	matal-N	Ncmsc
aigesean	aigesean	ag-P	Pr3ms-e
lá	lá	lá-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
amach	amach	amach-R	Rd
anseo	anseo	anseo-R	Rl
.	.	.-F	Fe
‘	‘	‘-X	Xx
Hurá	Hurá	hurá-I	I
!	!	!-F	Fe
Hurá	Hurá	hurá-I	I
!	!	!-F	Fe
’	’	’-F	Fa
a	a	a-Q	Q-r
chan	chan	can-V	Vmis
an	an	an-T	Td-s
slua	slua	slua-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	an-T	Td-s
bhuíochas	bhuíochas	buíochas-N	Ncmsc
d	d	d-X	Xl
’	’	’-F	Fa
fhoireann	fhoireann	foireann-N	Ncfsc
Setanta	Setanta	Setanta-N	Npm-g|Npmsc
tá	tá	bí-V	Vmip
an	an	an-T	Td-s
corn	corn	corn-N	Ncmsc
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
linn	linn	linn-N	Ncfpg|Pr1-p|Ncfpg|Ncfsc
chun	chun	chun-S	Sp
an	an	an-T	Td-s
bhaile	bhaile	baile-N	Ncmsg
!	!	!-F	Fe
Hurá	Hurá	hurá-I	I
!	!	!-F	Fe
Hurá	Hurá	hurá-I	I
!	!	!-F	Fe
’	’	’-F	Fa
