Carraigín	Carraigín	carraigín-N	Ncmsc
Cén	Cén	cé-W	W--q|Dw--s
tóin	tóin	tóin-N	Ncfsc
a	a	a-Q	Q-r
bhíonn	bhíonn	bí-V	Vmig
fliuch	fliuch	fliuch-A	Aqp
i	i	i-S	Sp
gcónaí	gcónaí	cónaí-N	Ncmsc
?	?	?-F	Fq
Tóin	Tóin	Tón-N	Npmsg
na	na	na-T	Tdfsg
farraige	farraige	farraige-N	Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Fuuuuuiisssss	Fuuuuuiisssss	Fuuuuuiisssss-N	Nc
!	!	!-F	Fe
Úúúúúúúúúú	Úúúúúúúúúú	Úúúúúúúúúú-N	Npmsc
!	!	!-F	Fe
’	’	’-F	Fa
a	a	a-U	Uv|Dp3
scréach	scréach	scréach-N	Ncfsc|Ncfsv
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
.	.	.-F	Fe
Gheit	Gheit	geit-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
,	,	,-F	Fi
an	an	an-T	Td-s
mhaighdean	mhaighdean	maighdean-N	Ncfsc
mhara	mhara	muir-N	Ncfpg|Ncfsg
.	.	.-F	Fe
Rug	Rug	beir-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
sciathán	sciathán	sciathán-N	Ncmsc
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	is-W	Wpdq|Wp-q
Ghaoth	Ghaoth	gaoth-A	Aqp
Aduaidh	Aduaidh	aduaidh-A	Aqp
?	?	?-F	Fq
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sí	sí	sí-P	Pp3fsn
go	go	go-U	Ua
heaglach	heaglach	eaglach-A	Aqp
ag	ag	ag-S	Sp
féachaint	féachaint	féach-N	Nv
i	i	i-S	Sp
dtreo	dtreo	treo-N	Ncmsc
dhoras	dhoras	doras-N	Ncmsc
na	na	na-T	Tdfsg
pluaise	pluaise	pluais-N	Ncfsg
.	.	.-F	Fe
Scaoil	Scaoil	scaoil-V	Vmis|Vmm-2s
an	an	an-T	Td-s
faoileán	faoileán	faoileán-N	Ncmsc
beag	beag	beag-A	Aq-msc
an	an	an-T	Td-s
greim	greim	greim-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
a	a	a-D	Dp3
chara	chara	cara-N	Ncmsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Anois	Anois	anois-R	Rt
,	,	,-F	Fi
anois	anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
ansin	ansin	ansin-R	Rt|Rl
ach	ach	ach-S	Sp
na	na	na-T	Td-p
maighdeana	maighdeana	maighdean-N	Ncfpc
mara	mara	muir-N	Ncfpc|Cs|Ncfpg|Ncfsg
eile	eile	eile-D	Dd
.	.	.-F	Fe
Ag	Ag	ag-S	Sp
caoineadh	caoineadh	caoin-N	Nv
faoina	faoina	faoi-S	Spp-p
gcuid	gcuid	cuid-N	Ncfsc
gruaige	gruaige	gruaig-N	Ncfsg
arís	arís	arís-R	Rg
,	,	,-F	Fi
is	is	is-U	U
dócha	dócha	dócha-A	Aqc
!	!	!-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
hea	hea	ea-P	Pp3-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
atá	atá	bí-V	Vmip---r
ann	ann	i-P	Pr3ms
go	go	go-U	Ua
cinnte	cinnte	cinnte-A	Av|Aqp
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
fhios	fhios	fios-N	Ncmsc
agam	agam	ag-P	Pr1-s
é	é	é-P	Pp3ms
!	!	!-F	Fe
'	'	'-F	Fa
Chroith	Chroith	croith-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
a	a	a-D	Dp3
cheann	cheann	ceann-N	Ncmsc
gobach	gobach	gobach-A	Aq-msc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
féidir	féidir	féidir-N	Ns-s
léi	léi	le-P	Pr3fs
thú	thú	tú-P	Pp2-s
a	a	a-U	U
ghortú	ghortú	gortaigh-N	Nv
agus	agus	agus-C	Cc
tú	tú	tú-P	Pp2-s
istigh	istigh	istigh-R	Rl
anseo	anseo	anseo-R	Rl
sa	sa	i-S	Spa-s
phluais	phluais	pluais-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
bíodh	bíodh	bí-V	Vmm-3s-n
aon	aon	aon-D	Dq
fhaitíos	fhaitíos	faitíos-N	Ncmsc
ort	ort	ar-P	Pr2-s
.	.	.-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
faitíos	faitíos	faitíos-N	Ncmsc
orm	orm	ar-P	Pr1-s
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
a	a	a-D	Dp3
heireaball	heireaball	eireaball-N	Ncmsc
ag	ag	ag-S	Sp
crith	crith	crith-N	Nv
leis	leis	le-S	Sp
an	an	an-T	Td-s
eagla	eagla	eagla-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bíonn	Bíonn	bí-V	Vmig
faitíos	faitíos	faitíos-N	Ncmsc
ar	ar	ar-S	Sp
chuile	chuile	cuile-N	Ncfsc
dhuine	dhuine	duine-N	Ncmsg
roimh	roimh	roimh-S	Sp
rud	rud	rud-N	Ncmsc
eicínt	eicínt	eicínt-A	Aq-msc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
smaoineamh	smaoineamh	smaoinigh-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
am	am	am-N	Ncmsc
deireanach	deireanach	deireanach-A	Aq-msc
ar	ar	ar-Q	Q-p
thriail	thriail	triail-V	Vmis
sé	sé	sé-P	Pp3msn
féin	féin	féin-P	Px
eitilt	eitilt	eitil-N	Ncfsc|Nv
suas	suas	suas-R	Rd
go	go	go-U	Ua
hard	hard	ard-X	Xfea|Aqp
sa	sa	i-S	Spa-s
spéir	spéir	spéir-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Fuuuuuiisssss	Fuuuuuiisssss	Fuuuuuiisssss-N	Nc
!	!	!-F	Fe
Úúúúúúúúúú	Úúúúúúúúúú	Úúúúúúúúúú-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
arís	arís	arís-R	Rg
.	.	.-F	Fe
Chroith	Chroith	croith-V	Vmis
ballaí	ballaí	balla-N	Ncmpc
na	na	na-T	Tdfsg
pluaise	pluaise	pluais-N	Ncfsg
.	.	.-F	Fe
Thit	Thit	tit-V	Vmis
píosa	píosa	píosa-N	Ncmsc
den	den	de-S	Spa-s
seancatapult	seancatapult	seancatapult-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
á	á	do-S	Spo-s
stóráil	stóráil	stóráil-N	Nv
acu	acu	ag-P	Pr3-p
sa	sa	i-S	Spa-s
phluais	phluais	pluais-N	Ncfsc
anuas	anuas	anuas-R	Rd
sa	sa	i-S	Spa-s
mhullach	mhullach	mullach-N	Ncmsc
ar	ar	ar-S	Sp
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Áááááábhuitse	Áááááábhuitse	Áááááábhuitse-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
ar	ar	ar-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Lig	Lig	lig-V	Vmis|Vmm-2s
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
béic	béic	béic-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
fhíochmhar	fhíochmhar	fíochmhar-A	Aq-fsc
eile	eile	eile-D	Dd
aisti	aisti	as-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cuidigh	Cuidigh	cuidigh-V	Vmm-2s
linn	linn	le-P	Pr1-p
,	,	,-F	Fi
a	a	a-U	Uv
Charraigín	Charraigín	carraigín-N	Ncmsv
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-U	Uv
scread	scread	scread-N	Ncfsv
na	na	na-T	Td-p
maighdeana	maighdeana	maighdean-N	Ncfpc
mara	mara	muir-N	Ncfpc|Cs|Ncfpg|Ncfsg
ón	ón	ó-S	Spa-s
stoirm	stoirm	stoirm-N	Ncfsc
amuigh	amuigh	amuigh-R	Rl
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
na	na	na-T	Td-p
hiascairí	hiascairí	iascaire-N	Ncmpc
i	i	i-S	Sp
mbaol	mbaol	baol-N	Ncmsc
ón	ón	ó-S	Spa-s
nGaoth	nGaoth	gaoth-N	Ncmsc|Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
!	!	!-F	Fe
'	'	'-F	Fa
Líon	Líon	líon-V	Vmis|Ncmsc|Vmm-2s
an	an	an-T	Td-s
phluais	phluais	pluais-N	Ncfsc
le	le	le-S	Sp
loinnir	loinnir	loinnir-N	Ncfsc
dhearg	dhearg	dearg-A	Aq-fsc
sholas	sholas	solas-N	Ncmsc
tarrthála	tarrthála	tarrtháil-N	Ncfsg|Nv--g
na	na	na-T	Tdfsg
n	n	n-X	Xl
‑	‑	‑-F	Fb
iascairí	iascairí	iascaire-N	Ncmpc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
ar	ar	ar-S	Sp
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
dabht	dabht	dabht-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
i mbun	i mbun	i_mbun-S	Spc
a	a	a-D	Dp3
cuid	cuid	cuid-N	Ncfsc
cleasaíochta	cleasaíochta	cleasaíocht-N	Ncfsg
arís	arís	arís-R	Rg
.	.	.-F	Fe
Cé	Cé	cé-W	W--q
hé	hé	é-P	Pp3ms
an	an	an-T	Td-s
ceoltóir	ceoltóir	ceoltóir-N	Ncmsc
is	is	is-U	U
fearr	fearr	maith-A	Aqc
san	san	i-S	Spa-s
fharraige	fharraige	farraige-N	Ncfsc
?	?	?-F	Fq
An	An	an-T	Td-s
PorTán	PorTán	PorTán-N	Nc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Dar	Dar	dar-C	Csw
‑	‑	‑-F	Fb
mo	mo	mo-D	Dp1-s
‑	‑	‑-F	Fb
ghob	ghob	gob-V	Vmis
‑	‑	‑-F	Fb
géar	géar	géar-N	Ncmsc
‑	‑	‑-F	Fb
tá	tá	bí-V	Vmip
‑	‑	‑-F	Fb
mo	mo	mo-D	Dp1-s
‑	‑	‑-F	Fb
thóin	thóin	tóin-N	Ncfsc
‑	‑	‑-F	Fb
san	san	sin-P	Pd
‑	‑	‑-F	Fb
aer	aer	aer-N	Ncmsc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
rith	rith	rith-N	Nv
go	go	go-S	Sp
béal	béal	béal-N	Ncmsc
na	na	na-T	Tdfsg
pluaise	pluaise	pluais-N	Ncfsg
.	.	.-F	Fe
Shín	Shín	Sín-N	Npfsc
sé	sé	is-W	Wp-i-3
a	a	a-D	Dp3
mhuineál	mhuineál	muineál-N	Ncmsc
amach	amach	amach-R	Rd
go	go	go-U	Ua
cúramach	cúramach	cúramach-A	Aqp
.	.	.-F	Fe
Bhuail	Bhuail	buail-V	Vmis
tonn	tonn	tonn-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
mhillteach	mhillteach	millteach-A	Aq-fsc
sa	sa	i-S	Spa-s
phus	phus	pus-N	Ncmsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Áááááábhuitse	Áááááábhuitse	Áááááábhuitse-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
ar	ar	ar-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfeiceann	bhfeiceann	feic-V	Vmip
tú	tú	tú-P	Pp2-s
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
ó	ó	ó-S	Sp
chúl	chúl	cúl-N	Ncmsc
na	na	na-T	Tdfsg
pluaise	pluaise	pluais-N	Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Feicim	Feicim	feic-V	Vmip1s
na	na	na-T	Td-p
maighdeana	maighdeana	maighdean-N	Ncfpc
mara	mara	muir-N	Ncfpc|Cs|Ncfpg|Ncfsg
eile	eile	eile-D	Dd
ag	ag	ag-S	Sp
snámh	snámh	snámh-N	Nv
i	i	i-S	Sp
dtreo	dtreo	treo-N	Ncmsc
na	na	na-T	Tdfsg
n	n	n-X	Xl
‑	‑	‑-F	Fb
iascairí	iascairí	iascaire-N	Ncmpc
.	.	.-F	Fe
'	'	'-F	Fa
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
,	,	,-F	Fi
phléasc	phléasc	pléasc-V	Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
anuas	anuas	anuas-R	Rd
ón	ón	ó-S	Spa-s
spéir	spéir	spéir-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Fuuuuuiisssss	Fuuuuuiisssss	Fuuuuuiisssss-N	Nc
!	!	!-F	Fe
Úúúúúúúúúú	Úúúúúúúúúú	Úúúúúúúúúú-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
ar	ar	ar-V	Vmis
sí	sí	sí-P	Pp3fsn
go	go	go-U	Ua
gránna	gránna	gránna-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	a-D	Dp3
fhaoileáin	fhaoileáin	faoileán-N	Ncmpc
mhara	mhara	muir-N	Ncfpg|Ncfsg
,	,	,-F	Fi
cá	cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
do	do	do-S	Sp
chara	chara	cara-N	Ncmsc
?	?	?-F	Fq
'	'	'-F	Fa
Shnámh	Shnámh	snámh-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
de	de	de-S	Sp
rúid	rúid	rúid-N	Ncfsc
go	go	go-S	Sp
béal	béal	béal-N	Ncmsc
na	na	na-T	Tdfsg
pluaise	pluaise	pluais-N	Ncfsg
is	is	agus-C	Cc
tharraing	tharraing	tarraing-V	Vmis
sí	sí	sí-P	Pp3fsn
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
isteach	isteach	isteach-R	Rd
arís	arís	arís-R	Rg
díreach	díreach	díreach-N	Ncmsc
sula	sula	sula-C	Cs
bhfuair	bhfuair	faigh-V	Vmis
an	an	an-T	Td-s
ghaoth	ghaoth	gaoth-N	Ncfsc
aduaidh	aduaidh	aduaidh-A	Aqp
greim	greim	greim-N	Ncmsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Dar	Dar	dar-C	Csw
‑	‑	‑-F	Fb
mo	mo	mo-D	Dp1-s
‑	‑	‑-F	Fb
sciathán	sciathán	sciathán-N	Ncmsc
‑	‑	‑-F	Fb
clé	clé	clé-N	Ncfsc
‑	‑	‑-F	Fb
cheap	cheap	ceap-V	Vmis
‑	‑	‑-F	Fb
mé	mé	mé-P	Pp1-s
‑	‑	‑-F	Fb
go	go	go-C	Cs
‑	‑	‑-F	Fb
raibh	raibh	bí-V	Vmis---d
‑	‑	‑-F	Fb
mé	mé	mé-P	Pp1-s
‑	‑	‑-F	Fb
réidh	réidh	réidh-A	Aqp
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
amach	amach	amach-R	Rd
go	go	go-U	Ua
cúramach	cúramach	cúramach-A	Aqp
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
na	na	na-T	Td-p
maighdeana	maighdeana	maighdean-N	Ncfpc
mara	mara	muir-N	Ncfpc|Cs|Ncfpg|Ncfsg
eile	eile	eile-D	Dd
í	í	í-P	Pp3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-T	Td-s
rópa	rópa	rópa-N	Ncmsc
,	,	,-F	Fi
a	a	a-U	Uv
Charraigín	Charraigín	carraigín-N	Ncmsv
!	!	!-F	Fe
Beir	Beir	bí-V	Vmif2s
ar	ar	ar-S	Sp
an	an	an-T	Td-s
rópa	rópa	rópa-N	Ncmsc
agus	agus	agus-C	Cc
tarraing	tarraing	tarraing-V	Vmm-2s
isteach	isteach	isteach-R	Rd
na	na	na-T	Td-p
hiascairí	hiascairí	iascaire-N	Ncmpc
,	,	,-F	Fi
’	’	’-F	Fa
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
impigh	impigh	impigh-V	Vmis
siad	siad	siad-P	Pp3-pn
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
agus	agus	agus-C	Cc
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
rópa	rópa	rópa-N	Ncmsc
tarrthála	tarrthála	tarrtháil-N	Ncfsg|Nv--g
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
bobáil	bobáil	bobáil-N	Nv
ar	ar	ar-S	Sp
bharr	bharr	barr-N	Ncmsc
na	na	na-T	Td-p
dtonn	dtonn	tonn-N	Ncfpg
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
a	a	a-D	Dp3
lámh	lámh	lámh-N	Ncfsc
amach	amach	amach-R	Rd
go	go	go-U	Ua
cúramach	cúramach	cúramach-A	Aqp
.	.	.-F	Fe
Rinne	Rinne	déan-V	Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
iarracht	iarracht	iarracht-N	Ncfsc
breith	breith	beir-N	Ncfsc|Nv
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Fuuuuuiisssss	Fuuuuuiisssss	Fuuuuuiisssss-N	Nc
!	!	!-F	Fe
Úúúúúúúúúú	Úúúúúúúúúú	Úúúúúúúúúú-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
Tharraing	Tharraing	tarraing-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
a	a	a-D	Dp3
lámh	lámh	lámh-N	Ncfsc
isteach	isteach	isteach-R	Rd
arís	arís	arís-R	Rg
go	go	go-U	Ua
tapa	tapa	tapa-A	Aqp
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-T	Td-s
rópa	rópa	rópa-N	Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sí	sí	sí-P	Pp3fsn
faoi	faoi	faoi-S	Sp
dheifir	dheifir	deifir-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Faigh	Faigh	faigh-V	Vmm-2s
é	é	é-P	Pp3ms
!	!	!-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Mise	Mise	mé-P	Pp1-s-e
?	?	?-F	Fq
'	'	'-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ag	Ag	ag-S	Sp
magadh	magadh	magadh-N	Nv-----n
atá	atá	bí-V	Vmip---r
tú	tú	tú-P	Pp2-s
!	!	!-F	Fe
'	'	'-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
amach	amach	amach-R	Rd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
bád	bád	bád-N	Ncmpg
na	na	na-T	Tdfsg
n	n	n-X	Xl
‑	‑	‑-F	Fb
iascairí	iascairí	iascaire-N	Ncmpc
a	a	a-Q	Q-r
scrios	scrios	scrios-V	Vmis
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
na	na	na-T	Td-p
maighdeana	maighdeana	maighdean-N	Ncfpc
mara	mara	mara-C	Cs
eile	eile	eile-D	Dd
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
stop	stop	stop-V	Vmis
a	a	a-U	U
chur	chur	cuir-N	Nv
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cuidigh	Cuidigh	cuidigh-V	Vmm-2s
linn	linn	le-P	Pr1-p
,	,	,-F	Fi
a	a	a-U	Uv
Charraigín	Charraigín	carraigín-N	Ncmsv
!	!	!-F	Fe
'	'	'-F	Fa
ar	ar	ar-V	Vmis
siad	siad	siad-P	Pp3-pn
arís	arís	arís-R	Rg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nílim	Nílim	bí-V	Vmip1s-n
in ann	in ann	in_ann-S	Spc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
deora	deora	deoir-N	Ncfpc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nílim	Nílim	bí-V	Vmip1s-n
in ann	in ann	in_ann-S	Spc
.	.	.-F	Fe
'	'	'-F	Fa
Cén	Cén	cé-W	W--q|Dw--s
capall	capall	capall-N	Ncmsc
nach	nach	is-W	Wprin
féidir	féidir	féidir-N	Ns-s
leis	leis	le-P	Pr3ms
rith	rith	rith-V	Vmis
?	?	?-F	Fq
Capall	Capall	capall-N	Ncmsc
mara	mara	muir-N	Ncfpc|Cs|Ncfpg|Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Fuuuuuiisssss	Fuuuuuiisssss	Fuuuuuiisssss-N	Nc
!	!	!-F	Fe
Úúúúúúúúúú	Úúúúúúúúúú	Úúúúúúúúúú-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
caitheamh	caitheamh	caith-N	Nv
tonnta	tonnta	tonn-A	Av
móra	móra	mór-A	Aq--pv|Aq--pg|Aq--pc
fíochmhara	fíochmhara	fíochmhar-A	Aq--pg|Aq--pc|Aq--pv
le	le	le-S	Sp
bád	bád	bád-N	Ncmsc
na	na	na-T	Tdfsg
n	n	n-X	Xl
‑	‑	‑-F	Fb
iascairí	iascairí	iascaire-N	Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Gread	Gread	Gread-N	Npmsc
leat	leat	le-P	Pr2-s
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
na	na	na-T	Td-p
maighdeana	maighdeana	maighdean-N	Ncfpc
mara	mara	muir-N	Ncfpc|Cs|Ncfpg|Ncfsg
ach	ach	ach-S	Sp|Cs
scairt	scairt	scairt-V	Vmis|Ncfsc
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
amach	amach	amach-R	Rd
ag	ag	ag-S	Sp
gáire	gáire	gáir-N	Nv
agus	agus	agus-C	Cc
bhuail	bhuail	buail-V	Vmis
a	a	a-D	Dp3
dorn	dorn	dorn-N	Ncmsc
in éadan	in éadan	in_éadan-S	Spc
chlár	chlár	clár-N	Ncmpg
na	na	na-T	Tdfsg
farraige	farraige	farraige-N	Ncfsg
.	.	.-F	Fe
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
,	,	,-F	Fi
bhuail	bhuail	buail-V	Vmis
smaoineamh	smaoineamh	smaoineamh-N	Ncmsc
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-T	Td-s
tseanslat	tseanslat	slat-N	Ncfsc
iascaireachta	iascaireachta	iascaire-N	Ncfsg|Nv--g--n
!	!	!-F	Fe
'	'	'-F	Fa
ar	ar	ar-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-U	Ua
sciobtha	sciobtha	sciob-A	Av
.	.	.-F	Fe
Rug	Rug	beir-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
tseanslat	tseanslat	slat-N	Ncfsc
iascaireachta	iascaireachta	iascaire-N	Ncfsg|Nv--g--n
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
crochta	crochta	croch-A	Av
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mballa	mballa	balla-N	Ncmsc
agus	agus	agus-C	Cc
cheangail	cheangail	ceangail-V	Vmis
sí	sí	sí-P	Pp3fsn
le	le	le-S	Sp
tóin	tóin	tóin-N	Ncfsc
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
í	í	í-P	Pp3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Áááááábhuitse	Áááááábhuitse	Áááááábhuitse-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
.	.	.-F	Fe
Níorbh	Níorbh	is-W	Ws-in
in	in	sin-P	Pd
go	go	go-U	Ua
baileach	baileach	baileach-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
i	i	i-S	Sp
gceist	gceist	ceist-N	Ncfsc
aige	aige	ag-P	Pr3ms
!	!	!-F	Fe
‘	‘	‘-X	Xx
Beir	Beir	bí-V	Vmif2s
ar	ar	ar-S	Sp
an	an	an-T	Td-s
rópa	rópa	rópa-N	Ncmsc
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-U	Uv
bhéic	bhéic	béic-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
agus	agus	agus-C	Cc
chaith	chaith	caith-V	Vmis
sí	sí	sí-P	Pp3fsn
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
amach	amach	amach-R	Rd
san	san	i-S	Spa-s
fharraige	fharraige	farraige-N	Ncfsc
.	.	.-F	Fe
Thriail	Thriail	triail-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
breith	breith	beir-N	Ncfsc|Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
rópa	rópa	rópa-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Háháááááá	Háháááááá	Háháááááá-N	Npmsc
!	!	!-F	Fe
Háháááááá	Háháááááá	Háháááááá-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
agam	agam	ag-P	Pr1-s
anois	anois	anois-R	Rt
,	,	,-F	Fi
a	a	a-U	Uv
phleota	phleota	pleota-N	Ncmsv
.	.	.-F	Fe
'	'	'-F	Fa
Sciob	Sciob	sciob-V	Vmis
sí	sí	sí-P	Pp3fsn
an	an	an-T	Td-s
faoileán	faoileán	faoileán-N	Ncmsc
beag	beag	beag-A	Aq-msc
suas	suas	suas-R	Rd
,	,	,-F	Fi
suas	suas	suas-R	Rd
,	,	,-F	Fi
suas	suas	suas-R	Rd
go	go	go-S	Sp
barr	barr	barr-N	Ncmsc
na	na	na-T	Tdfsg
spéire	spéire	spéir-N	Ncfsg
.	.	.-F	Fe
Tharraing	Tharraing	tarraing-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
tslat	tslat	slat-N	Ncfsc
iascaireachta	iascaireachta	iascaire-N	Ncfsg|Nv--g--n
.	.	.-F	Fe
Tharraing	Tharraing	tarraing-V	Vmis
sí	sí	sí-P	Pp3fsn
agus	agus	agus-C	Cc
tharraing	tharraing	tarraing-V	Vmis
sí	sí	sí-P	Pp3fsn
ach	ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
mhaith	mhaith	maith-N	Ncfsc
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
róláidir	róláidir	láidir-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cuidigh	Cuidigh	cuidigh-V	Vmm-2s
liom	liom	le-P	Pr1-s
,	,	,-F	Fi
a	a	a-U	Uv
Charraigín	Charraigín	carraigín-N	Ncmsv
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-U	Uv
scréach	scréach	scréach-N	Ncfsv
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cuidigh	Cuidigh	cuidigh-V	Vmm-2s
linn	linn	le-P	Pr1-p
,	,	,-F	Fi
a	a	a-U	Uv
Charraigín	Charraigín	carraigín-N	Ncmsv
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-U	Uv
scréach	scréach	scréach-N	Ncfsv
na	na	na-T	Td-p
maighdeana	maighdeana	maighdean-N	Ncfpc
mara	mara	muir-N	Ncfpc|Cs|Ncfpg|Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cuidigh	Cuidigh	cuidigh-V	Vmm-2s
linn	linn	le-P	Pr1-p
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-U	Uv
scréach	scréach	scréach-N	Ncfsv
na	na	na-T	Td-p
hiascairí	hiascairí	iascaire-N	Ncmpg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
a	a	a-Q	Q-r
dhéanfas	dhéanfas	déan-V	Vmif---r
mé	mé	mé-P	Pp1-s
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
deora	deora	deoir-N	Ncfpc
léi	léi	le-P	Pr3fs
arís	arís	arís-R	Rg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Fuuuuuiisssss	Fuuuuuiisssss	Fuuuuuiisssss-N	Nc
!	!	!-F	Fe
Úúúúúúúúúú	Úúúúúúúúúú	Úúúúúúúúúú-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
fhaigheann	fhaigheann	faigh-V	Vmip---n
éinne	éinne	duine-N	Ncmsc
an	an	an-T	Td-s
ceann	ceann	ceann-N	Ncmsc
is	is	is-U	U
fearr	fearr	maith-A	Aqc
ormsa	ormsa	ar-P	Pr1-s-e
,	,	,-F	Fi
a	a	a-U	Uv
Charraigín	Charraigín	carraigín-N	Ncmsv
Chatach	Chatach	catach-A	Aq-msc
!	!	!-F	Fe
Háháááááá	Háháááááá	Háháááááá-N	Npmsc
!	!	!-F	Fe
Háháááááá	Háháááááá	Háháááááá-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
,	,	,-F	Fi
chonaic	chonaic	feic-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
an	an	an-T	Td-s
Réalta	Réalta	réaladh-N	Ncmsg
Thuaidh	Thuaidh	tuaidh-A	Aqp
ag	ag	ag-S	Sp
soilsiú	soilsiú	soilsigh-N	Nv
trí	trí	trí-S	Sp
na	na	na-T	Td-p
scamaill	scamaill	scamall-N	Ncmpc
dhorcha	dhorcha	dorcha-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	a-T	Td-s|Dp3|U|Ud
Réalta	Réalta	réalta-A	Aqc|Ncfsc|Av|Ncfsc
Thuaidh	Thuaidh	tuaidh-A	Aqp
,	,	,-F	Fi
éist	éist	éist-V	Vmm-2s
le	le	le-S	Sp
mo	mo	mo-D	Dp1-s
ghuí	ghuí	guí-N	Nv|Ncfsc
.	.	.-F	Fe
Sábháil	Sábháil	sábháil-V	Vmm-2s
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
is	is	agus-W	Wp-i|Wpri|Cc
na	na	na-T	Td-p
hiascairí	hiascairí	iascaire-N	Ncmpc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
an	an	an-T	Td-s
Réalta	Réalta	réalta-N	Ncfsc
Thuaidh	Thuaidh	tuaidh-A	Aqp
ag	ag	ag-S	Sp
luascadh	luascadh	luasc-N	Nv
anonn	anonn	anonn-R	Rd
is	is	agus-C	Cc
anall	anall	anall-R	Rd
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
,	,	,-F	Fi
sula	sula	sula-C	Cs
raibh	raibh	bí-V	Vmis---d
seans	seans	seans-N	Ncmsc
ag	ag	ag-S	Sp
Carraigín	Carraigín	carraigín-N	Ncmsc
anáil	anáil	anáil-N	Ncfsc
a	a	a-U	U
tharraingt	tharraingt	tarraing-N	Nv
,	,	,-F	Fi
thuirling	thuirling	tuirling-V	Vmis
an	an	an-T	Td-s
réalta	réalta	réalta-N	Ncfsc
síos	síos	síos-R	Rd
,	,	,-F	Fi
síos	síos	síos-R	Rd
,	,	,-F	Fi
síos	síos	síos-R	Rd
i	i	i-S	Sp
dtreo	dtreo	treo-N	Ncmsc
na	na	na-T	Tdfsg
farraige	farraige	farraige-N	Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhóóóóááááábh	Bhóóóóááááábh	Bhóóóóááááábh-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
.	.	.-F	Fe
Splais	Splais	splais-N	Ncfsc
!	!	!-F	Fe
Thit	Thit	tit-V	Vmis
an	an	an-T	Td-s
Réalta	Réalta	réalta-N	Ncfsc
Thuaidh	Thuaidh	tuaidh-A	Aqp
isteach	isteach	isteach-R	Rd
san	san	i-S	Spa-s
fharraige	fharraige	farraige-N	Ncfsc
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
ag	ag	ag-S	Sp
titim	titim	tit-N	Nv
í	í	í-P	Pp3fs
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	is-W	Wp-in
fhaca	fhaca	feic-V	Vmis---n
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
ná	ná	ná-C	Cc
a	a	a-D	Dp3
searbhónta	searbhónta	searbhónta-N	Ncmsc
,	,	,-F	Fi
an	an	an-T	Td-s
smugairle	smugairle	smugairle-N	Ncmsg
róin	róin	rón-N	Ncmsg
,	,	,-F	Fi
í	í	í-P	Pp3fs
.	.	.-F	Fe
Cad	Cad	cad-P	Pq
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
roimh	roimh	roimh-S	Sp
an	an	an-T	Td-s
ochtapas	ochtapas	ochtapas-N	Ncmsc
?	?	?-F	Fq
An	An	an-T	Td-s
seachtapas	seachtapas	seachtapas-N	Ncmsc
!	!	!-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
éirigh	éirigh	éirigh-V	Vmm-2s
súnámaí	súnámaí	súnámaí-N	Ncmsc
mór	mór	mór-A	Aq-msc
aníos	aníos	aníos-R	Rd
san	san	i-S	Spa-s
uisce	uisce	uisce-N	Ncmsc
san	san	i-S	Spa-s
áit	áit	áit-N	Ncfsc
ar	ar	ar-Q	Q-p
thit	thit	tit-V	Vmis
an	an	an-T	Td-s
Réalta	Réalta	réalta-N	Ncfsc
Thuaidh	Thuaidh	tuaidh-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhóóóóááááábhóóóóó	Bhóóóóááááábhóóóóó	Bhóóóóááááábhóóóóó-X	Xf
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-U	Uv
scread	scread	scread-N	Ncfsv
na	na	na-T	Td-p
hiascairí	hiascairí	iascaire-N	Ncmpg
agus	agus	agus-C	Cc
a	a	a-D	Dp3
mbád	mbád	bád-N	Ncmpg
ag	ag	ag-S	Sp
surfáil	surfáil	surfáil-N	Nv
ar	ar	ar-S	Sp
bharr	bharr	barr-N	Ncmsc
na	na	na-T	Td-p
dtonn	dtonn	tonn-N	Ncfpg
.	.	.-F	Fe
Chaith	Chaith	caith-V	Vmis
an	an	an-T	Td-s
súnámaí	súnámaí	súnámaí-N	Ncmsc
an	an	an-T	Td-s
bád	bád	bád-N	Ncmsc
isteach	isteach	isteach-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
trá	trá	trá-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Stop	Stop	stop-V	Vmis
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-Q	Q-r
bhéic	bhéic	béic-V	Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
leis	leis	le-S	Sp
an	an	an-T	Td-s
súnámaí	súnámaí	súnámaí-N	Ncmsc
.	.	.-F	Fe
Scaoil	Scaoil	scaoil-V	Vmis
sí	sí	sí-P	Pp3fsn
le	le	le-S	Sp
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
agus	agus	agus-C	Cc
thit	thit	tit-V	Vmis
seisean	seisean	sé-P	Pp3msne
bunoscionn	bunoscionn	bunoscionn-N	Ncmsc
isteach	isteach	isteach-R	Rd
san	san	i-S	Spa-s
uisce	uisce	uisce-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Dar	Dar	dar-C	Csw
‑	‑	‑-F	Fb
mo	mo	mo-D	Dp1-s
‑	‑	‑-F	Fb
ghob	ghob	gob-V	Vmis
‑	‑	‑-F	Fb
géar	géar	géar-N	Ncmsc
‑	‑	‑-F	Fb
’	’	’-F	Fa
‘	‘	‘-X	Xx
Fuuuuuiisssss	Fuuuuuiisssss	Fuuuuuiisssss-N	Nc
!	!	!-F	Fe
Úúúúúúúúúú	Úúúúúúúúúú	Úúúúúúúúúú-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
go	go	go-U	Ua
crosta	crosta	cros-A	Aqp|Av
.	.	.-F	Fe
Rinne	Rinne	déan-V	Vmis
sí	sí	sí-P	Pp3fsn
iarracht	iarracht	iarracht-N	Ncfsc
na	na	na-T	Td-p
hiascairí	hiascairí	iascaire-N	Ncmpc
a	a	a-U	U
tharraingt	tharraingt	tarraing-N	Nv
ar ais	ar ais	ar_ais-R	Rd
isteach	isteach	isteach-R	Rd
san	san	i-S	Spa-s
fharraige	fharraige	farraige-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Gread	Gread	Gread-N	Npmsc
leat	leat	le-P	Pr2-s
abhaile	abhaile	abhaile-R	Rd
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
na	na	na-T	Td-p
maighdeana	maighdeana	maighdean-N	Ncfpc
mara	mara	muir-N	Ncfpc|Cs|Ncfpg|Ncfsg
agus	agus	agus-C	Cc
rinne	rinne	déan-V	Vmis
siad	siad	siad-P	Pp3-pn
balla	balla	balla-N	Ncmsc
cosanta	cosanta	cosain-A	Av
lena	lena	le-S	Spp-s
n	n	n-X	Xl
‑	‑	‑-F	Fb
eireaball	eireaball	eireaball-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcladach	gcladach	cladach-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
na	na	na-T	Td-p
hiascairí	hiascairí	iascaire-N	Ncmpc
seo	seo	seo-D	Dd
slán	slán	slán-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Fuuuuuiisssss	Fuuuuuiisssss	Fuuuuuiisssss-N	Nc
!	!	!-F	Fe
Úúúúúúúúúú	Úúúúúúúúúú	Úúúúúúúúúú-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
Lig	Lig	lig-V	Vmis|Vmm-2s
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
scread	scread	scread-N	Ncfsc
mhór	mhór	mór-N	Ncmpg
mhillteach	mhillteach	millteach-N	Ncmpg
amháin	amháin	amháin-A	Aqp
eile	eile	eile-D	Dd
aisti	aisti	as-P	Pr3fs
sular	sular	sula-C	Cs-s
imigh	imigh	imigh-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
Lean	Lean	Lean-N	Npmsc
an	an	an-T	Td-s
smugairle	smugairle	smugairle-N	Ncmsg
róin	róin	rón-N	Ncmsg
í	í	í-P	Pp3fs
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
Carraigín	Carraigín	carraigín-N	Ncmsc
ag	ag	ag-S	Sp
imeacht	imeacht	imigh-N	Nv
iad	iad	iad-P	Pp3-p
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sise	sise	sí-P	Pp3fsne
ag	ag	ag-S	Sp
breathnú	breathnú	breathnaigh-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
Réalta	Réalta	réalta-N	Ncfsc
Thuaidh	Thuaidh	tuaidh-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
anois	anois	anois-R	Rt
ag	ag	ag-S	Sp
bobáil	bobáil	bobáil-N	Nv
suas	suas	suas-R	Rd
agus	agus	agus-C	Cc
anuas	anuas	anuas-R	Rd
san	san	i-S	Spa-s
uisce	uisce	uisce-N	Ncmsc
in aice	in aice	in_aice-S	Spc
le	le	le-S	Sp
béal	béal	béal-N	Ncmsc
na	na	na-T	Tdfsg
pluaise	pluaise	pluais-N	Ncfsg
.	.	.-F	Fe
Cén	Cén	cé-W	W--q
madra	madra	madra-N	Ncmsc
nach	nach	is-W	Wprin
féidir	féidir	féidir-N	Ns-s
leis	leis	le-P	Pr3ms
tafann	tafann	tafainn-N	Nv
?	?	?-F	Fq
Cú	Cú	cú-N	Ncmsc
mara	mara	muir-N	Ncfpc|Cs|Ncfpg|Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhóóóóááááábh	Bhóóóóááááábh	Bhóóóóááááábh-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nach	Nach	is-W	Wpsin|Wpdin
álainn	álainn	álainn-A	Aqp
í	í	í-P	Pp3fs
.	.	.-F	Fe
'	'	'-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
Réalta	Réalta	réalta-N	Ncfsc
Thuaidh	Thuaidh	tuaidh-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
anois	anois	anois-R	Rt
ina	ina	i-S	Spp-p|Spp-s
suí	suí	suí-N	Ncmsc
leo	leo	le-P	Pr3-p
sa	sa	i-S	Spa-s
phluais	phluais	pluais-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
sé	sé	sé-P	Pp3msn
seo	seo	seo-P	Pd
ceart	ceart	ceart-A	Aqp|Ncmsc
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
Carraigín	Carraigín	carraigín-N	Ncmsc
ag	ag	ag-S	Sp
éisteacht	éisteacht	éist-N	Nv
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
faoi	faoi	faoi-S	Sp
dhraíocht	dhraíocht	draíocht-N	Ncfsc
ag	ag	ag-S	Sp
loinnir	loinnir	loinnir-N	Ncfsc
ghleoite	ghleoite	gleoite-A	Aqp
na	na	na-T	Tdfsg
réalta	réalta	réalta-N	Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
féidir	féidir	féidir-N	Ns-s
leat	leat	le-P	Pr2-s
í	í	í-P	Pp3fs
a	a	a-U	U
choinneáil	choinneáil	coinnigh-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Lá	Lá	lá-N	Ncmsc
amháin	amháin	amháin-A	Aqp
eile	eile	eile-D	Dd
agus	agus	agus-C	Cc
beidh	beidh	bí-V	Vmif
an	an	an-T	Td-s
ghealach	ghealach	gealach-N	Ncfsc
lán	lán	lán-A	Aq-fsc
arís	arís	arís-R	Rg
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
mór	mór	mór-A	Aqp
dúinn	dúinn	do-P	Pr1-p
an	an	an-T	Td-s
Réalta	Réalta	réalta-N	Ncfsc
Thuaidh	Thuaidh	tuaidh-A	Aqp
a	a	a-U	U
chur	chur	cuir-N	Nv
ar ais	ar ais	ar_ais-R	Rd
sa	sa	i-S	Spa-s
spéir	spéir	spéir-N	Ncfsc
gan	gan	gan-S	Sp
mhoill	mhoill	moill-N	Ncfsc
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
agat	agat	ag-P	Pr2-s
a	a	a-Q	Q-r
deirtear	deirtear	abair-V	Vmip0
faoin	faoin	faoi-S	Spa-s
Réalta	Réalta	réalta-N	Ncfsc
Thuaidh	Thuaidh	tuaidh-A	Aqp
:	:	:-F	Fi
an	an	an-T	Td-s
té	té	té-N	Ncmsc
a	a	a-Q	Q-r
fheicfeas	fheicfeas	feic-V	Vmif---r
ag	ag	ag-S	Sp
titim	titim	tit-N	Nv
í	í	í-P	Pp3fs
,	,	,-F	Fi
is	is	is-W	Wpri
é	é	é-P	Pp3ms
a	a	a-Q	Q-i|Q-r
chuirfeas	chuirfeas	cuir-V	Vmif---r
sa	sa	i-S	Spa-s
spéir	spéir	spéir-N	Ncfsc
arís	arís	arís-R	Rg
í	í	í-P	Pp3fs
.	.	.-F	Fe
'	'	'-F	Fa
Chuir	Chuir	cuir-V	Vmis
na	na	na-T	Td-p
focail	focail	focal-N	Ncmpc
‘	‘	‘-X	Xx
gealach	gealach	gealach-N	Ncfsc
lán	lán	lán-A	Aq-fsc
’	’	’-F	Fa
critheagla	critheagla	critheagla-N	Ncfsc
ar	ar	ar-S	Sp
Charraigín	Charraigín	carraigín-N	Ncmsc
.	.	.-F	Fe
Thuig	Thuig	tuig-V	Vmis
sí	sí	sí-P	Pp3fsn
go	go	go-U	Ua
maith	maith	maith-A	Aqp
an	an	an-T	Td-s
dainséar	dainséar	dainséar-N	Ncmsc
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
ann	ann	i-R	Rl|Pr3ms
di	di	do-P	Pr3fs
féin	féin	féin-P	Px
agus	agus	agus-C	Cc
do	do	do-S	Sp
na	na	na-T	Td-p
maighdeana	maighdeana	maighdean-N	Ncfpc
mara	mara	muir-N	Ncfpc|Cs|Ncfpg|Ncfsg
eile	eile	eile-D	Dd
dá	dá	dá-C	Cs
mbeadh	mbeadh	bí-V	Vmc
gealach	gealach	gealach-N	Ncfsc
lán	lán	lán-A	Aq-fsc
ann	ann	i-P	Pr3ms
agus	agus	agus-C	Cc
nach	nach	nach-Q	Qnr
mbeadh	mbeadh	bí-V	Vmc
an	an	an-T	Td-s
Réalta	Réalta	réalta-N	Ncfsc
Thuaidh	Thuaidh	tuaidh-A	Aqp
sa	sa	i-S	Spa-s
spéir	spéir	spéir-N	Ncfsc
.	.	.-F	Fe
Fós	Fós	fós-R	Rg
féin	féin	féin-P	Px
,	,	,-F	Fi
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
fonn	fonn	fonn-N	Ncmsc
uirthi	uirthi	ar-P	Pr3fs
scaoileadh	scaoileadh	scaoileadh-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
réalta	réalta	réalta-N	Ncfsc
go	go	go-U	Ua
fóill	fóill	fóill-A	Aqp
beag	beag	beag-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
tada	tada	tada-N	Ncmsc
gur	gur	is-W	Wsdi
féidir	féidir	féidir-N	Ns-s
linn	linn	le-P	Pr1-p
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
faoi	faoi	faoi-S	Sp
anocht	anocht	anocht-N	Ns-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sí	sí	sí-P	Pp3fsn
faoi	faoi	faoi-S	Sp
dheireadh	dheireadh	deireadh-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Beidh	Beidh	bí-V	Vmif
an	an	an-T	Td-s
réalta	réalta	réalta-N	Ncfsc
togha	togha	togha-N	Ncmsg|Ncmsc
anseo	anseo	anseo-R	Rl
go	go	go-S	Sp
maidin	maidin	maidin-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
imní	imní	imní-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
ar	ar	ar-S	Sp
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
.	.	.-F	Fe
Ag	Ag	ag-S	Sp
teach	teach	teach-N	Ncmsc
na	na	na-T	Td-p
Gaoithe	Gaoithe	Gaoithe-N	Npmsg
Aduaidh	Aduaidh	aduaidh-A	Aqp
i	i	i-S	Sp
gcroílár	gcroílár	croílár-N	Ncmsc
Chnoc	Chnoc	Cnoc-N	Npfsg
na	na	na-T	Td-p
Fola	Fola	fuil-N	Ncfpg
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
smugairle	smugairle	smugairle-N	Ncmsc
róin	róin	rón-N	Ncmsg
ag	ag	ag-S	Sp
cuntas	cuntas	cuntais-N	Nv
anamnacha	anamnacha	anamn-N	Ncmpc
na	na	na-T	Tdfsg
n	n	n-X	Xl
‑	‑	‑-F	Fb
iascairí	iascairí	iascaire-N	Ncmpc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
gafa	gafa	gabh-A	Av
acu	acu	ag-P	Pr3-p
go dtí	go dtí	go_dtí-S	Spc
sin	sin	sin-P	Pd
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	a-U	Um
haon	haon	aon-M	Mc
is	is	agus-C	Cc
a	a	a-U	Um
dó	dó	dó-M	Mc
,	,	,-F	Fi
sin	sin	sin-W	W
a	a	a-D	Dp3
ceathar	ceathar	ceathar-N	Ncmsc
,	,	,-F	Fi
a	a	a-D	Dp3
ceathar	ceathar	ceathar-N	Ncmsc
is	is	is-W	Wpri
a	a	a-U	Um
dó	dó	dó-M	Mc
,	,	,-F	Fi
sin	sin	sin-W	W
a	a	a-U	Um
seacht	seacht	seacht-M	Mc
.	.	.-F	Fe
'	'	'-F	Fa
Ach	Ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
ag	ag	ag-S	Sp
éisteacht	éisteacht	éist-N	Nv
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
smaoineamh	smaoineamh	smaoinigh-N	Nv
ar	ar	ar-S	Sp
na	na	na-T	Td-p
maighdeana	maighdeana	maighdean-N	Ncfpc
mara	mara	muir-N	Ncfpc|Cs|Ncfpg|Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Sin	Sin	sin-P	Pd|W
an	an	an-T	Td-s
tríú	tríú	trí-M	Mo
bád	bád	bád-N	Ncmsc
iascaigh	iascaigh	iascach-A	Aq-msg|Aq-msv
a	a	a-Q	Q-r
sciob	sciob	sciob-V	Vmis
siad	siad	siad-P	Pp3-pn
uaim	uaim	ó-N	Ncfsc|Pr1-s
le	le	le-S	Sp
mí	mí	mí-N	Ncfsc|Ncmsc
anuas	anuas	anuas-R	Rd
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sí	sí	sí-P	Pp3fsn
go	go	go-U	Ua
fíochmhar	fíochmhar	fíochmhar-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Na	Na	na-T	Td-p
caimiléirí	caimiléirí	caimiléir-N	Ncmpc
bradacha	bradacha	bradach-A	Aq--pc|Aq--pv|Aq--pg
!	!	!-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
San	San	i-S	Spa-s
oíche	oíche	oíche-N	Ncfsc
amárach	amárach	amárach-A	Aqp
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
thitfeas	thitfeas	tit-V	Vmif---r
an	an	an-T	Td-s
Réalta	Réalta	réalta-N	Ncfsc
Thuaidh	Thuaidh	tuaidh-A	Aqp
ón	ón	ó-S	Spa-s
spéir	spéir	spéir-N	Ncfsc
,	,	,-F	Fi
a	a	a-U	Uv
Mháistreás	Mháistreás	máistreás-N	Ncfsv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
smugairle	smugairle	smugairle-N	Ncmsc
róin	róin	rón-N	Ncmsg
go	go	go-U	Ua
sleamhain	sleamhain	sleamhain-A	Aqp
,	,	,-F	Fi
‘	‘	‘-X	Xx
ní	ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
aon	aon	aon-D	Dq
chosaint	chosaint	cosaint-N	Ncfsc
ag	ag	ag-S	Sp
na	na	na-T	Td-p
maighdeana	maighdeana	maighdean-N	Ncfpc
mara	mara	mara-C	Cs
ar	ar	is-W	Wpdi|Wpsi|Wssi
dhraíocht	dhraíocht	draíocht-N	Ncfsc
na	na	na-T	Tdfsg
lánghealaí	lánghealaí	gealach-N	Ncfsg
!	!	!-F	Fe
'	'	'-F	Fa
Bhreathnaigh	Bhreathnaigh	breathnaigh-V	Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
ar	ar	ar-S	Sp
an	an	an-T	Td-s
smugairle	smugairle	smugairle-N	Ncmsc
róin	róin	rón-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Oíche	Oíche	oíche-N	Ncfsc
amháin	amháin	amháin-A	Aqp
eile	eile	eile-D	Dd
,	,	,-F	Fi
a	a	a-U	Uv
Mháistreás	Mháistreás	máistreás-N	Ncfsv
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
,	,	,-F	Fi
‘	‘	‘-X	Xx
agus	agus	agus-C	Cc
beidh	beidh	bí-V	Vmif
smacht	smacht	smacht-N	Ncmsc
iomlán	iomlán	iomlán-A	Aq-msc
agat	agat	ag-P	Pr2-s
orthu	orthu	ar-P	Pr3-p
.	.	.-F	Fe
'	'	'-F	Fa
Den	Den	de-S	Spa-s
chéad	chéad	céad-M	Mo
uair	uair	uair-N	Ncfsc
le	le	le-S	Sp
fada	fada	fada-A	Aqp
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
sásta	sásta	sásta-A	Aqp
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Háháááááá	Háháááááá	Háháááááá-N	Npmsc
!	!	!-F	Fe
Háháááááá	Háháááááá	Háháááááá-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
ar	ar	ar-V	Vmis
sí	sí	sí-P	Pp3fsn
agus	agus	agus-C	Cc
ríméad	ríméad	ríméad-N	Ncmsc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
ní	ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
srian	srian	srian-N	Ncmsc
le	le	le-S	Sp
mo	mo	mo-D	Dp1-s
chumhacht	chumhacht	cumhacht-N	Ncfsc
ansin	ansin	ansin-R	Rt|Rl
!	!	!-F	Fe
'	'	'-F	Fa
Chroith	Chroith	croith-V	Vmis
an	an	an-T	Td-s
cnoc	cnoc	cnoc-N	Ncmsc
.	.	.-F	Fe
Chroith	Chroith	croith-V	Vmis
an	an	an-T	Td-s
smugairle	smugairle	smugairle-N	Ncmsc
róin	róin	rón-N	Ncmsg
.	.	.-F	Fe
Chroith	Chroith	croith-V	Vmis
eireaball	eireaball	eireaball-N	Ncmsc
Charraigín	Charraigín	carraigín-N	Ncmsc
ar	ar	ar-S	Sp
urlár	urlár	urlár-N	Ncmsc
na	na	na-T	Tdfsg
pluaise	pluaise	pluais-N	Ncfsg
.	.	.-F	Fe
Cén	Cén	cé-W	W--q
t	t	t-X	Xl
‑	‑	‑-F	Fb
iasc	iasc	iasc-V	Vmm-2s
is	is	is-U	U
luachmhaire	luachmhaire	luachmhar-A	Aqc
?	?	?-F	Fq
t	t	t-X	Xl
‑	‑	‑-F	Fb
iasc	iasc	iasc-N	Ncmsc
órga	órga	órga-A	Aqp
.	.	.-F	Fe
Lá	Lá	lá-N	Ncmsc
arna	arna	arna-S	Spc
mhárach	mhárach	márach-N	Ns-s
dhúisigh	dhúisigh	dúisigh-V	Vmis
ceiliúradh	ceiliúradh	ceiliúradh-N	Ncmsc
na	na	na-T	Td-p
maighdean	maighdean	maighdean-N	Ncfpg
mara	mara	muir-N	Ncfpc|Cs|Ncfpg|Ncfsg|Ncfpg|Ncfsg
eile	eile	eile-D	Dd
Carraigín	Carraigín	carraigín-N	Ncmsc
agus	agus	agus-C	Cc
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Maith	Maith	Maith-N	Npmsc
sinn	sinn	sinn-P	Pp1-p
!	!	!-F	Fe
Maith	Maith	Maith-N	Npmsc
sinn	sinn	sinn-P	Pp1-p
!	!	!-F	Fe
'	'	'-F	Fa
ar	ar	ar-V	Vmis
siad	siad	siad-P	Pp3-pn
.	.	.-F	Fe
‘	‘	‘-X	Xx
Murach	Murach	murach-C	Cs
muide	muide	muid-P	Pp1-p-e
bheadh	bheadh	bí-V	Vmc
anamnacha	anamnacha	anamn-N	Ncmpc
na	na	na-T	Tdfsg
n	n	n-X	Xl
‑	‑	‑-F	Fb
iascairí	iascairí	iascaire-N	Ncmpc
sin	sin	sin-P	Pd|W|Dd
ag	ag	ag-S	Sp
an	an	an-T	Td-s
nGaoth	nGaoth	gaoth-N	Ncmsc|Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
.	.	.-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Huth	Huth	Huth-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nach	Nach	is-C	Cs|Wpdin|Wpsin
mise	mise	mé-P	Pp1-s-e
seachas	seachas	seachas-S	Sp
iadsan	iadsan	iad-P	Pp3-p-e
a	a	a-Q	Q-r
shábháil	shábháil	sábháil-V	Vmis
na	na	na-T	Td-p
hiascairí	hiascairí	iascaire-N	Ncmpc
.	.	.-F	Fe
Mise	Mise	mé-P	Pp1-s-e
a	a	a-Q	Q-r
rinne	rinne	déan-V	Vmis
mo	mo	mo-D	Dp1-s
ghuí	ghuí	guí-N	Nv|Ncfsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
Réalta	Réalta	réalta-N	Ncfsc
Thuaidh	Thuaidh	tuaidh-A	Aqp
.	.	.-F	Fe
Murach	Murach	murach-C	Cs
mise	mise	mé-P	Pp1-s-e
ní	ní	ní-Q	Qn
bheadh	bheadh	bí-V	Vmc----n
aon	aon	aon-D	Dq
súnámaí	súnámaí	súnáma-N	Ncmsc|Ncmpc
ann	ann	i-P	Pr3ms
!	!	!-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
bac	bac	bac-V	Vmm-2s-n
leo	leo	le-P	Pr3-p
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhfarraige	bhfarraige	farraige-N	Ncfsc
cheana	cheana	cion-R	Rg|Ncmsg
féin	féin	féin-P	Px
.	.	.-F	Fe
‘	‘	‘-X	Xx
Coinnigh	Coinnigh	Coinnigh-N	Npmsc
do	do	do-Q	Q
ghob	ghob	gob-V	Vmis
dúnta	dúnta	dún-N	Ncmpc
faoin	faoin	faoi-S	Spa-s
réalta	réalta	réalta-N	Ncfsc
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-U	Uv
scréach	scréach	scréach-N	Ncfsv
Jimí	Jimí	Jimí-N	Npmsc
ach	ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
bailithe	bailithe	bailigh-A	Av
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Shnámh	Shnámh	snámh-V	Vmis
sí	sí	sí-P	Pp3fsn
anonn	anonn	anonn-R	Rd
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
Charraig	Charraig	carraig-N	Ncfsc
Mhór	Mhór	mór-A	Aq-fsv|Aq-fsc
.	.	.-F	Fe
Theastaigh	Theastaigh	teastaigh-V	Vmis
uaithi	uaithi	ó-P	Pr3fs
,	,	,-F	Fi
thar	thar	thar-S	Sp
aon	aon	aon-D	Dq
ní	ní	ní-N	Ncmsc
eile	eile	eile-D	Dd
,	,	,-F	Fi
a	a	a-U	U
bheith	bheith	bí-N	Nv
páirteach	páirteach	páirteach-A	Aqp
sa	sa	i-S	Spa-s
cheiliúradh	cheiliúradh	ceiliúradh-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Maith	Maith	Maith-N	Npmsc
sinn	sinn	sinn-P	Pp1-p
!	!	!-F	Fe
Maith	Maith	Maith-N	Npmsc
sinn	sinn	sinn-P	Pp1-p
!	!	!-F	Fe
'	'	'-F	Fa
ar	ar	ar-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
‘	‘	‘-X	Xx
Murach	Murach	murach-C	Cs
mise	mise	mé-P	Pp1-s-e
agus	agus	agus-C	Cc
mo	mo	mo-D	Dp1-s
ghuí	ghuí	guí-N	Nv|Ncfsc
bheadh	bheadh	bí-V	Vmc
anamnacha	anamnacha	anamn-N	Ncmpc
na	na	na-T	Tdfsg
n	n	n-X	Xl
‑	‑	‑-F	Fb
iascairí	iascairí	iascaire-N	Ncmpc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
nGaoth	nGaoth	gaoth-N	Ncmsc|Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
!	!	!-F	Fe
'	'	'-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
na	na	na-T	Td-p
maighdeana	maighdeana	maighdean-N	Ncfpc
mara	mara	muir-N	Ncfpc|Cs|Ncfpg|Ncfsg
eile	eile	eile-D	Dd
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Ní	Ní	is-W	Wp-in
mó	mó	mó-A	Aqc|Aqp
ná	ná	ná-C	Cs|Cc
sásta	sásta	sásta-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
.	.	.-F	Fe
‘	‘	‘-X	Xx
Gread	Gread	Gread-N	Npmsc
leat	leat	le-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
scraiste	scraiste	scraiste-N	Ncmsv
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
duine	duine	duine-N	Ncmsc
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ghlaoigh	Ghlaoigh	glaoigh-V	Vmis
muid	muid	muid-P	Pp1-p
ort	ort	ar-P	Pr2-s
ach	ach	ach-C	Cs
níor	níor	is-W	Ws-in
tháinig	tháinig	tar-V	Vmis
tú	tú	tú-P	Pp2-s
i	i	i-S	Sp
gcabhair	gcabhair	cabhar-N	Ncfsc|Ncmpc
orainn	orainn	ar-P	Pr1-p
.	.	.-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
ionat	ionat	i-P	Pr2-s
ach	ach	ach-C	Cs
…	…	…-F	Fi
ach	ach	ach-C	Cs
…	…	…-F	Fi
meatachán	meatachán	meatachán-N	Ncmsc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
duine	duine	duine-N	Ncmsc
eile	eile	eile-D	Dd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
maighdean	maighdean	maighdean-N	Ncfsc
mhara	mhara	muir-N	Ncfsg
cheart	cheart	ceart-A	Aq-fsc|Aq-fsv
thú	thú	tú-P	Pp2-s
in	in	i-S	Sp
aon	aon	aon-D	Dq
chor	chor	cor-N	Ncmsc
!	!	!-F	Fe
'	'	'-F	Fa
ar	ar	ar-V	Vmis
siad	siad	siad-P	Pp3-pn
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
,	,	,-F	Fi
shnámh	shnámh	snámh-V	Vmis
siad	siad	siad-P	Pp3-pn
uaithi	uaithi	ó-P	Pr3fs
.	.	.-F	Fe
Bhain	Bhain	bain-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
croitheadh	croitheadh	croith-V	Vmis0
as	as	as-P	Pr3ms
a	a	a-D	Dp3
heireaball	heireaball	eireaball-N	Ncmsc
go	go	go-U	Ua
mall	mall	mall-A	Aqp
brónach	brónach	brónach-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
,	,	,-F	Fi
ach	ach	ach-C	Cs
…	…	…-F	Fi
’	’	’-F	Fa
a	a	a-Q	Q-r
chaoin	chaoin	caoin-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
Theastaigh	Theastaigh	teastaigh-V	Vmis
uaithi	uaithi	ó-P	Pr3fs
a	a	a-U	U
insint	insint	inis-N	Nv
dóibh	dóibh	do-P	Pr3-p
faoin	faoin	faoi-S	Spa-s
Réalta	Réalta	réalta-N	Ncfsc
Thuaidh	Thuaidh	tuaidh-A	Aqp
ach	ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
bailithe	bailithe	bailigh-A	Av
leo	leo	le-P	Pr3-p
faoin	faoin	faoi-S	Spa-s
uisce	uisce	uisce-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tar	Tar	thar-S	Sp
uait	uait	ó-P	Pr2-s
abhaile	abhaile	abhaile-R	Rd
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
mór	mór	mór-A	Aqp
dúinn	dúinn	do-P	Pr1-p
an	an	an-T	Td-s
Réalta	Réalta	réalta-N	Ncfsc
Thuaidh	Thuaidh	tuaidh-A	Aqp
a	a	a-U	U
chur	chur	cuir-N	Nv
ar ais	ar ais	ar_ais-R	Rd
sa	sa	i-S	Spa-s
spéir	spéir	spéir-N	Ncfsc
roimh	roimh	roimh-S	Sp
thitim	thitim	tit-N	Nv
na	na	na-T	Tdfsg
hoíche	hoíche	oíche-N	Ncfsg
.	.	.-F	Fe
'	'	'-F	Fa
Cén	Cén	cé-W	W--q
charraig	charraig	carraig-N	Ncfsc
is	is	is-U	U
boige	boige	bog-A	Aqc
san	san	i-S	Spa-s
fharraige	fharraige	farraige-N	Ncfsc
?	?	?-F	Fq
Carraigín	Carraigín	carraigín-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
cinnte	cinnte	cinnte-A	Av|Aqp
gur	gur	is-W	Wsdi|Wpdi
anocht	anocht	anocht-N	Ns-s|Rt
a	a	a-Q	Q-i|Q-r
thitfeas	thitfeas	tit-V	Vmif---r
sí	sí	sí-P	Pp3fsn
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
leis	leis	le-S	Sp
an	an	an-T	Td-s
smugairle	smugairle	smugairle-N	Ncmsc
róin	róin	rón-N	Ncmsg
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
stánadh	stánadh	stán-N	Nv
go	go	go-U	Ua
mífhoighneach	mífhoighneach	mífhoighneach-A	Aqp
ar	ar	ar-S	Sp
an	an	an-T	Td-s
spéir	spéir	spéir-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
fós	fós	fós-R	Rg
geal	geal	geal-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cinnte	Cinnte	cinn-A	Av
,	,	,-F	Fi
táim	táim	bí-V	Vmip1s
cinnte	cinnte	cinn-A	Av
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
smugairle	smugairle	smugairle-N	Ncmsc
róin	róin	rón-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Titeann	Titeann	tit-V	Vmip
an	an	an-T	Td-s
Réalta	Réalta	réalta-N	Ncfsc
Thuaidh	Thuaidh	tuaidh-A	Aqp
ón	ón	ó-S	Spa-s
spéir	spéir	spéir-N	Ncfsc
uair	uair	uair-N	Ncfsc
éigin	éigin	éigin-A	Aq-fsc
tar éis	tar éis	tar_éis-S	Spc
thitim	thitim	tit-N	Nv
na	na	na-T	Tdfsg
hoíche	hoíche	oíche-N	Ncfsg
ar	ar	ar-S	Sp
an	an	an-T	Td-s
tríú	tríú	trí-M	Mo
lá	lá	lá-N	Ncmsc
den	den	de-S	Spa-s
tríú	tríú	trí-M	Mo
mí	mí	mí-N	Ncfsc|Ncmsc|Ncmsg
,	,	,-F	Fi
chuile	chuile	gach-D	Dq
trí	trí	trí-M	Mc
mhíle	mhíle	míle-M	Mc
bliain	bliain	bliain-N	Ncfsc
!	!	!-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Ar	Ar	ar-S	Sp
an	an	an-T	Td-s
tríú	tríú	trí-M	Mo
lá	lá	lá-N	Ncmsc
?	?	?-F	Fq
'	'	'-F	Fa
a	a	a-Q	Q-r
bhéic	bhéic	béic-V	Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
agus	agus	agus-C	Cc
a	a	a-D	Dp3
bolg	bolg	bolg-N	Ncmsc
lán	lán	lán-A	Aq-msc
le	le	le-S	Sp
fearg	fearg	fearg-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-S	Sp
seo	seo	seo-P	Pd
an	an	an-T	Td-s
ceathrú	ceathrú	ceathair-M	Mo
lá	lá	lá-N	Ncmsc
,	,	,-F	Fi
a	a	a-U	Uv
phleota	phleota	pleota-N	Ncmsv
!	!	!-F	Fe
Táimid	Táimid	bí-V	Vmip1p
ródhéanach	ródhéanach	déanach-A	Aqp
anois	anois	anois-R	Rt
le	le	le-S	Sp
breith	breith	beir-N	Nv
uirthi	uirthi	ar-P	Pr3fs
!	!	!-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Úúúúúps	Úúúúúps	Úúúúúps-N	Npmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
smugairle	smugairle	smugairle-N	Ncmsc
róin	róin	rón-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
trua	trua	trua-A	Aqc|Aqp
nach	nach	nach-Q	Qnr
bhfuil	bhfuil	bí-V	Vmip---n
méara	méara	méara-N	Ncfpc|Ncmsc
agam	agam	ag-P	Pr1-s
le	le	le-S	Sp
cuntas	cuntas	cuntais-N	Nv
.	.	.-F	Fe
'	'	'-F	Fa
Ar ais	Ar ais	ar_ais-R	Rd
sa	sa	i-S	Spa-s
phluais	phluais	pluais-N	Ncfsc
bhí	bhí	bí-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
agus	agus	agus-C	Cc
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
ag	ag	ag-S	Sp
tarraingt	tarraingt	tarraing-N	Nv
an	an	an-T	Td-s
tseancatapult	tseancatapult	seancatapult-N	Ncfsc
go	go	go-S	Sp
béal	béal	béal-N	Ncmsc
na	na	na-T	Tdfsg
pluaise	pluaise	pluais-N	Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Faigh	Faigh	faigh-V	Vmm-2s
thusa	thusa	tú-P	Pp2-s-e
an	an	an-T	Td-s
réalta	réalta	réalta-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
le	le	le-S	Sp
Jimí	Jimí	Jimí-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Má	Má	má-C	Cs
fhaigheann	fhaigheann	faigh-V	Vmip
éinne	éinne	duine-N	Ncmsc
amach	amach	amach-R	Rd
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
Réalta	Réalta	réalta-N	Ncfsc
Thuaidh	Thuaidh	tuaidh-A	Aqp
againn	againn	ag-P	Pr1-p
thar	thar	thar-S	Sp
oíche	oíche	oíche-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
go	go	go-U	Ua
neirbhíseach	neirbhíseach	neirbhíseach-A	Aqp
,	,	,-F	Fi
‘	‘	‘-X	Xx
beidh	beidh	bí-V	Vmif
ár	ár	ár-N	Ncmsc|Dp1-p
bport	bport	port-N	Ncmsc|Ncmpg
seinnte	seinnte	seinn-A	Av
.	.	.-F	Fe
'	'	'-F	Fa
Bhain	Bhain	bain-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
cóta	cóta	cóta-N	Ncmsc
feamainne	feamainne	feamainn-N	Ncfsg
den	den	de-S	Spa-s
Réalta	Réalta	réalta-N	Ncfsc
Thuaidh	Thuaidh	tuaidh-A	Aqp
.	.	.-F	Fe
Scairt	Scairt	scairt-V	Vmis|Vmm-2s
loinnir	loinnir	loinnir-N	Ncfsc
ghleoite	ghleoite	gleoite-A	Aqp
na	na	na-T	Tdfsg
réalta	réalta	réalta-N	Ncfsg
amach	amach	amach-R	Rd
trí	trí	trí-M	Mc|Sp
bhéal	bhéal	béal-N	Ncmsc
na	na	na-T	Tdfsg
pluaise	pluaise	pluais-N	Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Dá	Dá	dá-C	Cs
mbeadh	mbeadh	bí-V	Vmc
tusa	tusa	tú-P	Pp2-s-e
sásta	sásta	sásta-A	Aqp
eitilt	eitilt	eitil-N	Ncfsc|Nv
suas	suas	suas-R	Rd
go	go	go-U	Ua
hard	hard	ard-X	Xfea|Aqp
bheadh	bheadh	bí-V	Vmc
sí	sí	sí-P	Pp3fsn
ar ais	ar ais	ar_ais-R	Rd
sa	sa	i-S	Spa-s
spéir	spéir	spéir-N	Ncfsc
againn	againn	ag-P	Pr1-p
faoi	faoi	faoi-S	Sp
seo	seo	seo-P	Pd
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
go	go	go-U	Ua
mífhoighneach	mífhoighneach	mífhoighneach-A	Aqp
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
an	an	an-T	Td-s
réalta	réalta	réaladh-N	Ncmsg
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
catapult	catapult	catapult-X	Xfen
.	.	.-F	Fe
Tharraing	Tharraing	tarraing-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
siar	siar	siar-R	Rd
,	,	,-F	Fi
siar	siar	siar-R	Rd
,	,	,-F	Fi
siar	siar	siar-R	Rd
é	é	é-P	Pp3ms
chomh	chomh	chomh-R	Ri
fada	fada	fada-A	Aqp
is	is	agus-C	Cc
a	a	a-Q	Q-r
rachadh	rachadh	téigh-V	Vmc
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
scaoil	scaoil	scaoil-V	Vmis
sí	sí	sí-P	Pp3fsn
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Suas	Suas	suas-R	Rd
i	i	i-S	Sp
dtreo	dtreo	treo-N	Ncmsc
na	na	na-T	Tdfsg
spéire	spéire	spéir-N	Ncfsg
leis	leis	le-S	Sp
an	an	an-T	Td-s
Réalta	Réalta	réalta-N	Ncfsc
Thuaidh	Thuaidh	tuaidh-A	Aqp
.	.	.-F	Fe
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
,	,	,-F	Fi
chuala	chuala	clois-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
guth	guth	guth-N	Ncmsc
a	a	a-D	Dp3
d	d	d-X	Xl
’	’	’-F	Fa
aithin	aithin	aithin-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
rómhall	rómhall	mall-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Féach	Féach	féach-V	Vmm-2s
,	,	,-F	Fi
a	a	a-U	Uv
Mháistreás	Mháistreás	máistreás-N	Ncfsv
!	!	!-F	Fe
An	An	an-T	Td-s
Réalta	Réalta	réalta-N	Ncfsc
Thuaidh	Thuaidh	tuaidh-A	Aqp
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
smugairle	smugairle	smugairle-N	Ncmsc
róin	róin	rón-N	Ncmsg
.	.	.-F	Fe
Thuirling	Thuirling	tuirling-V	Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
anuas	anuas	anuas-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
réalta	réalta	réalta-N	Ncfsc
agus	agus	agus-C	Cc
sciob	sciob	sciob-V	Vmm-2s
léi	léi	le-P	Pr3fs
í	í	í-P	Pp3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Háháááááá	Háháááááá	Háháááááá-N	Npmsc
!	!	!-F	Fe
Háháááááá	Háháááááá	Háháááááá-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
go	go	go-U	Ua
gránna	gránna	gránna-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
fada	fada	fada-A	Aqp
anois	anois	anois-R	Rt
go	go	go-Q	Q
mbeidh	mbeidh	bí-V	Vmif
titim	titim	titim-N	Ncfsc
na	na	na-T	Tdfsg
hoíche	hoíche	oíche-N	Ncfsg
ann	ann	i-P	Pr3ms
agus	agus	agus-C	Cc
an	an	an-T	Td-s
ghealach	ghealach	gealach-N	Ncfsc
lán	lán	lán-A	Aq-fsv|Aq-fsc
.	.	.-F	Fe
Gan	Gan	gan-S	Sp
cosaint	cosaint	cosaint-N	Ncfsc
na	na	na-T	Tdfsg
Réalta	Réalta	réalta-N	Ncfsg
Thuaidh	Thuaidh	tuaidh-A	Aqp
beidh	beidh	bí-V	Vmif
deireadh	deireadh	deireadh-N	Ncmsc
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
le	le	le-S	Sp
ré	ré	ré-N	Ncfsc|Ncmsc
na	na	na-T	Td-p
maighdean	maighdean	maighdean-N	Ncfpg
mara	mara	muir-N	Ncfpc|Cs|Ncfpg|Ncfsg|Ncfpg|Ncfsg
.	.	.-F	Fe
Háháááááá	Háháááááá	Háháááááá-N	Npmsc
!	!	!-F	Fe
Háháááááá	Háháááááá	Háháááááá-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
Céard	Céard	cé-W	W--q
a	a	a-Q	Q-r
thugann	thugann	tabhair-V	Vmip
sairdíní	sairdíní	sairdín-N	Ncmpc
ar	ar	ar-S	Sp
fhomhuireáin	fhomhuireáin	fomhuireán-N	Ncmpc
?	?	?-F	Fq
Cannaí	Cannaí	canna-N	Ncmpc
lán	lán	lán-A	Aq--pg
daoine	daoine	duine-N	Ncmpg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Dar	Dar	dar-C	Csw
‑	‑	‑-F	Fb
mo	mo	mo-D	Dp1-s
‑	‑	‑-F	Fb
sciathán	sciathán	sciathán-N	Ncmsc
‑	‑	‑-F	Fb
clé	clé	clé-N	Ncfsc
‑	‑	‑-F	Fb
is	is	is-W	Wpri
‑	‑	‑-F	Fb
léir	léir	léir-A	Aqp
‑	‑	‑-F	Fb
go	go	go-C	Cs
‑	‑	‑-F	Fb
bhfuil	bhfuil	fuil-N	Ncfsc
‑	‑	‑-F	Fb
muid	muid	muid-P	Pp1-p
‑	‑	‑-F	Fb
réidh	réidh	réidh-A	Aqp
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
níos	níos	níos-U	Uc
measa	measa	olc-A	Aqc
fiú	fiú	fiú-N	Ns-s|Ncmsc|Rg
ná	ná	ná-C	Cs|Cc
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
cheap	cheap	ceap-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Nach	Nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
chuile	chuile	gach-D	Dq
shórt	shórt	sórt-N	Ncmsc
feicthe	feicthe	feic-A	Av
ag	ag	ag-S	Sp
na	na	na-T	Td-p
maighdeana	maighdeana	maighdean-N	Ncfpc
mara	mara	muir-N	Ncfpc|Cs|Ncfpg|Ncfsg
eile	eile	eile-D	Dd
!	!	!-F	Fe
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
atá	atá	bí-V	Vmip---r
déanta	déanta	déan-A	Av
agat	agat	ag-P	Pr2-s
anois	anois	anois-R	Rt
,	,	,-F	Fi
a	a	a-U	Uv
Charraigín	Charraigín	carraigín-N	Ncmsv
!	!	!-F	Fe
'	'	'-F	Fa
ar	ar	ar-V	Vmis
siad	siad	siad-P	Pp3-pn
agus	agus	agus-C	Cc
uafás	uafás	uafás-N	Ncmsc
orthu	orthu	ar-P	Pr3-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
nach	nach	is-W	Wpsin|Wpdin
í	í	í-P	Pp3fs
Carraigín	Carraigín	carraigín-N	Ncmsc
a	a	a-Q	Q-r
shábháil	shábháil	sábháil-V	Vmis
na	na	na-T	Td-p
hiascairí	hiascairí	iascaire-N	Ncmpc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
í	í	í-P	Pp3fs
Carraigín	Carraigín	carraigín-N	Ncmsc
a	a	a-Q	Q-r
ghoid	ghoid	goid-V	Vmis
an	an	an-T	Td-s
Réalta	Réalta	réalta-N	Ncfsc
Thuaidh	Thuaidh	tuaidh-A	Aqp
agus	agus	agus-C	Cc
a	a	a-Q	Q-r
thug	thug	tabhair-V	Vmis
don	don	do-S	Spa-s
Ghaoth	Ghaoth	gaoth-N	Ncmsc|Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
í	í	í-P	Pp3fs
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
na	na	na-T	Td-p
maighdeana	maighdeana	maighdean-N	Ncfpc
mara	mara	muir-N	Ncfpc|Cs|Ncfpg|Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Táimid	Táimid	bí-V	Vmip1p
réidh	réidh	réidh-A	Aqp
!	!	!-F	Fe
Táimid	Táimid	bí-V	Vmip1p
réidh	réidh	réidh-A	Aqp
!	!	!-F	Fe
'	'	'-F	Fa
ar	ar	ar-V	Vmis
siad	siad	siad-P	Pp3-pn
agus	agus	agus-C	Cc
thosaigh	thosaigh	tosaigh-V	Vmis
siad	siad	siad-P	Pp3-pn
ag	ag	ag-S	Sp
caoineadh	caoineadh	caoin-N	Nv
.	.	.-F	Fe
Chrom	Chrom	crom-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
a	a	a-D	Dp3
ceann	ceann	ceann-N	Ncmsc
le	le	le-S	Sp
náire	náire	náire-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
‑	‑	‑-F	Fb
sásta	sásta	sásta-A	Aqc
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
Réalta	Réalta	réalta-N	Ncfsc
Thuaidh	Thuaidh	tuaidh-A	Aqp
tugtha	tugtha	tugtha-A	Av|Aqp
abhaile	abhaile	abhaile-R	Rd
chuig	chuig	chuig-S	Sp
Cnoc	Cnoc	Cnoc-N	Npmsc
na	na	na-T	Td-p
Fola	Fola	fuil-N	Ncfpg
aici	aici	ag-P	Pr3fs
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
curtha	curtha	cuir-A	Av
faoi	faoi	faoi-S	Sp
ghlas	ghlas	glas-N	Ncfsc|Ncmsc
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Anois	Anois	anois-R	Rt
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sí	sí	sí-P	Pp3fsn
,	,	,-F	Fi
‘	‘	‘-X	Xx
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bheas	bheas	bí-V	Vmif---r
deireadh	deireadh	deireadh-N	Ncmsc
leis	leis	le-S	Sp
na	na	na-T	Td-p
maighdeana	maighdeana	maighdean-N	Ncfpc
mara	mara	muir-N	Ncfpc|Cs|Ncfpg|Ncfsg
féadfaidh	féadfaidh	féad-V	Vmif
mé	mé	mé-P	Pp1-s
an	an	an-T	Td-s
oiread	oiread	oiread-N	Ns-s
iascairí	iascairí	iascaire-N	Ncmpg|Ncmpc
agus	agus	agus-C	Cc
is	is	is-W	Wpri
mian	mian	mian-N	Ncfsc
liom	liom	le-P	Pr1-s
a	a	a-U	U
sciobadh	sciobadh	sciob-N	Nv
ón	ón	ó-S	Spa-s
bhfarraige	bhfarraige	farraige-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
Idir	Idir	idir-S	Sp
an	an	an-T	Td-s
dá	dá	dó-M	Mc
linn	linn	linn-N	Ncfsc
bhí	bhí	bí-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
agus	agus	agus-C	Cc
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
i	i	i-S	Sp
bhfolach	bhfolach	folach-N	Ncmsc
sa	sa	i-S	Spa-s
phluais	phluais	pluais-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
‑	‑	‑-F	Fb
fuath	fuath	fuath-N	Ncmsc
‑	‑	‑-F	Fb
liom	liom	le-P	Pr1-s
‑	‑	‑-F	Fb
géilleadh	géilleadh	géill-V	Vmm-3s
‑	‑	‑-F	Fb
ach	ach	ach-C	Cs
‑	‑	‑-F	Fb
caithfimid	caithfimid	caith-V	Vmif1p
‑	‑	‑-F	Fb
éalú	éalú	éalaigh-N	Ncmsc|Nv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
éalú	éalú	éalú-N	Ncmsc
ón	ón	ó-S	Spa-s
nGaoth	nGaoth	gaoth-N	Ncmsc|Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
sí	sí	sí-P	Pp3fsn
chuile	chuile	gach-D	Dq
áit	áit	áit-N	Ncfsc
!	!	!-F	Fe
'	'	'-F	Fa
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
ag	ag	ag-S	Sp
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
ceart	ceart	ceart-N	Ncmsc
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhan	fhan	fan-V	Vmis
siad	siad	siad-P	Pp3-pn
beirt	beirt	beirt-N	Ncfsc
ina	ina	i-S	Spp-p
dtost	dtost	tost-N	Ncmsc
ar feadh	ar feadh	ar_feadh-S	Spc
tamaillín	tamaillín	tamall-N	Ncmsc|Ncmpc
.	.	.-F	Fe
Amuigh	Amuigh	amuigh-R	Rl
ar	ar	ar-S	Sp
an	an	an-T	Td-s
bhfarraige	bhfarraige	farraige-N	Ncfsc
bhí	bhí	bí-V	Vmis
na	na	na-T	Td-p
maighdeana	maighdeana	maighdean-N	Ncfpc
mara	mara	mara-C	Cs
eile	eile	eile-D	Dd
fós	fós	fós-R	Rg
ag	ag	ag-S	Sp
caoineadh	caoineadh	caoin-N	Nv
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
ag	ag	ag-S	Sp
fanacht	fanacht	fan-N	Nv
le	le	le-S	Sp
titim	titim	tit-N	Nv
na	na	na-T	Tdfsg
hoíche	hoíche	oíche-N	Ncfsg
.	.	.-F	Fe
Faoi	Faoi	faoi-S	Sp
dheireadh	dheireadh	deireadh-N	Ncmsc
labhair	labhair	labhair-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
ach	ach	ach-S	Sp
rogha	rogha	rogha-N	Ncfsc
amháin	amháin	amháin-A	Aqp
againn	againn	ag-P	Pr1-p
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfimid	Caithfimid	caith-V	Vmif1p
a	a	a-U	U
ghabháil	ghabháil	gabh-N	Nv
go dtí	go dtí	go_dtí-S	Spc
Cnoc	Cnoc	Cnoc-N	Npmsc
na	na	na-T	Td-p
Fola	Fola	fuil-N	Ncfpg
agus	agus	agus-C	Cc
an	an	an-T	Td-s
Réalta	Réalta	réaladh-N	Ncmsg
Thuaidh	Thuaidh	tuaidh-A	Aqp
a	a	a-U	U
fháil	fháil	faigh-N	Nv
ar ais	ar ais	ar_ais-R	Rd
.	.	.-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
céard	céard	cé-W	W--q
faoin	faoin	faoi-S	Spa-s
nGaoth	nGaoth	gaoth-N	Ncmsc|Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
agus	agus	agus-C	Cc
alltacht	alltacht	alltacht-N	Ncfsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Céard	Céard	cé-W	W--q
fúithi	fúithi	faoi-P	Pr3fs
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
fhaitíos	fhaitíos	faitíos-N	Ncmsc
ormsa	ormsa	ar-P	Pr1-s-e
roimh	roimh	roimh-S	Sp
an	an	an-T	Td-s
nGaoth	nGaoth	gaoth-N	Ncmsc|Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
.	.	.-F	Fe
'	'	'-F	Fa
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
ag	ag	ag-S	Sp
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
nárbh	nárbh	is-W	Wsrin
fhíor	fhíor	fíor-A	Aqp
é	é	é-P	Pp3ms
sin	sin	sin-P	Pd
.	.	.-F	Fe
Cé	Cé	cé-P	Pq
acu	acu	ag-P	Pr3-p
is	is	is-U	U
minice	minice	minic-A	Aqc
a	a	a-Q	Q-i
mbíonn	mbíonn	bí-V	Vmig
ocras	ocras	ocras-N	Ncmsc
uirthi	uirthi	ar-P	Pr3fs
,	,	,-F	Fi
an	an	an-T	Td-s
ghealach	ghealach	gealach-N	Ncfsc
nó	nó	nó-C	Cc
an	an	an-T	Td-s
ghrian	ghrian	grian-N	Ncfsc
?	?	?-F	Fq
ghrian	ghrian	grian-V	Vmis
.	.	.-F	Fe
Bíonn	Bíonn	bí-V	Vmig
an	an	an-T	Td-s
ghealach	ghealach	gealach-N	Ncfsc
lán	lán	lán-A	Aq-fsc
ó	ó	ó-S	Sp
am	am	am-N	Ncmsc
go	go	go-S	Sp
chéile	chéile	céile-N	Ncmsc
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
ghrian	ghrian	grian-V	Vmis
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
a	a	a-U	U
luí	luí	luigh-N	Nv
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
shroich	shroich	sroich-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
agus	agus	agus-C	Cc
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
Cnoc	Cnoc	Cnoc-N	Npmsc
na	na	na-T	Td-p
Fola	Fola	fuil-N	Ncfpg
.	.	.-F	Fe
Chuala	Chuala	clois-V	Vmis
siad	siad	siad-P	Pp3-pn
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
agus	agus	agus-C	Cc
an	an	an-T	Td-s
smugairle	smugairle	smugairle-N	Ncmsg
róin	róin	rón-N	Ncmsg
ag	ag	ag-S	Sp
comhrá	comhrá	comhrá-N	Nv-----n
taobh istigh	taobh istigh	taobh_istigh-R	Rl
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
croí	croí	croí-N	Ncmsc
Charraigín	Charraigín	carraigín-N	Ncmsg
ag	ag	ag-S	Sp
bualadh	bualadh	buail-N	Nv
go	go	go-U	Ua
tapa	tapa	tapa-A	Aqp
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
nod	nod	nod-X	Xfev
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
réidh	réidh	réidh-A	Aqp
?	?	?-F	Fq
'	'	'-F	Fa
ar	ar	ar-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
‘	‘	‘-X	Xx
Seo	Seo	seo-W	W
linn	linn	le-P	Pr1-p
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
agus	agus	agus-C	Cc
tharraing	tharraing	tarraing-V	Vmis
sé	sé	sé-P	Pp3msn
meigeafón	meigeafón	meigeafón-N	Ncmsc
mór	mór	mór-A	Aq-msc
amach	amach	amach-R	Rd
as	as	as-P	Pr3ms
a	a	a-D	Dp3
mhála	mhála	mála-N	Ncmsc
droma	droma	droim-N	Ncmsg
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
sé	sé	sé-P	Pp3msn
do	do	do-S	Sp
Charraigín	Charraigín	carraigín-N	Ncmsc
é	é	é-P	Pp3ms
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
sise	sise	sí-P	Pp3fsne
lena	lena	le-S	Spp-s
béal	béal	béal-N	Ncmsc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Siúd	Siúd	siúd-P	Pd
léi	léi	le-P	Pr3fs
ag	ag	ag-S	Sp
béicíl	béicíl	béicíl-N	Nv-----n
in	in	sin-S	Sp|Pd
ard	ard	ard-N	Ncmsc|Aqp
a	a	a-D	Dp3
gutha	gutha	guth-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cuidígí	Cuidígí	cuidigh-V	Vmm-2p
linn	linn	le-P	Pr1-p
!	!	!-F	Fe
Cuidígí	Cuidígí	cuidigh-V	Vmm-2p
linn	linn	le-P	Pr1-p
!	!	!-F	Fe
Tá	Tá	bí-V	Vmip
iascairí	iascairí	iascaire-N	Ncmpc
i	i	i-S	Sp
mbaol	mbaol	baol-N	Ncmsc
!	!	!-F	Fe
'	'	'-F	Fa
Tháinig	Tháinig	tar-V	Vmis
na	na	na-T	Td-p
maighdeana	maighdeana	maighdean-N	Ncfpc
mara	mara	muir-N	Ncfpc|Cs|Ncfpg|Ncfsg
eile	eile	eile-D	Dd
faoi	faoi	faoi-S	Sp
dheifir	dheifir	deifir-N	Ncfsc
,	,	,-F	Fi
deora	deora	deora-N	Ncfpc|Ncfsc
fós	fós	fós-R	Rg
ina	ina	i-S	Spp-p|Spp-s
súile	súile	súil-N	Ncfpc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
siad	siad	siad-P	Pp3-pn
mórthimpeall	mórthimpeall	mórthimpeall-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
aon	aon	aon-D	Dq
iascairí	iascairí	iascaire-N	Ncmpc
le	le	le-S	Sp
feiceáil	feiceáil	feic-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cad	Cad	cad-P	Pq
atá	atá	bí-V	Vmip---r
ar	ar	ar-S	Sp
siúl	siúl	siúil-N	Nv
ag	ag	ag-S	Sp
Carraigín	Carraigín	carraigín-N	Ncmsc
anois	anois	anois-R	Rt
?	?	?-F	Fq
'	'	'-F	Fa
ar	ar	ar-V	Vmis
siad	siad	siad-P	Pp3-pn
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	is-W	Wpdq|Wp-q
é	é	é-P	Pp3ms
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
sí	sí	sí-P	Pp3fsn
faoi	faoi	faoi-S	Sp
dhraíocht	dhraíocht	draíocht-N	Ncfsc
na	na	na-T	Tdfsg
lánghealaí	lánghealaí	gealach-N	Ncfsg
cheana	cheana	cion-R	Rg|Ncmsg
féin	féin	féin-P	Px
?	?	?-F	Fq
'	'	'-F	Fa
Lean	Lean	Lean-N	Npmsc
Carraigín	Carraigín	carraigín-N	Ncmsc|Ncmsg
agus	agus	agus-C	Cc
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
orthu	orthu	ar-P	Pr3-p
ag	ag	ag-S	Sp
béicíl	béicíl	béicíl-N	Nv-----n
.	.	.-F	Fe
Istigh	Istigh	istigh-R	Rl
i	i	i-S	Sp
gCnoc	gCnoc	cnoc-N	Ncmsc
na	na	na-T	Td-p
Fola	Fola	fuil-N	Ncfpg
léim	léim	léim-V	Vmip1s|Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
ina	ina	i-S	Spp-p|Spp-s
seasamh	seasamh	seasamh-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Iascairí	Iascairí	iascaire-N	Ncmpc
!	!	!-F	Fe
'	'	'-F	Fa
ar	ar	ar-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
‘	‘	‘-X	Xx
Iascairí	Iascairí	iascaire-N	Ncmpc
i	i	i-S	Sp
mbaol	mbaol	baol-N	Ncmsc
?	?	?-F	Fq
'	'	'-F	Fa
‘	‘	‘-X	Xx
Sin	Sin	sin-P	Pd|W
jab	jab	jab-N	Ncmsc
dúinne	dúinne	do-P	Pr1-p-e
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
smugairle	smugairle	smugairle-N	Ncmsc
róin	róin	rón-N	Ncmsg
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
ar	ar	ar-S	Sp
luas	luas	luas-N	Ncmsc
lasrach	lasrach	lasrach-A	Aq-msc
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
bailithe	bailithe	bailigh-A	Av
léi	léi	le-P	Pr3fs
as	as	as-S	Sp
Cnoc	Cnoc	Cnoc-N	Npmsc
na	na	na-T	Td-p
Fola	Fola	fuil-N	Ncfpg
agus	agus	agus-C	Cc
an	an	an-T	Td-s
smugairle	smugairle	smugairle-N	Ncmsg
róin	róin	rón-N	Ncmsg
sna	sna	i-S	Spa-p
sála	sála	sáil-N	Ncfpc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Chomh	Chomh	chomh-R	Ri
luath	luath	luath-A	Aqp
is	is	agus-C	Cc
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
ag	ag	ag-S	Sp
teacht	teacht	tar-N	Nv
ina	ina	i-S	Spp-s
treo	treo	treo-N	Ncmsc
iad	iad	iad-P	Pp3-p
thum	thum	tum-V	Vmis
sí	sí	sí-P	Pp3fsn
faoin	faoin	faoi-S	Spa-s
uisce	uisce	uisce-N	Ncmsc
.	.	.-F	Fe
Lean	Lean	Lean-N	Npmsc
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
í	í	í-P	Pp3fs
.	.	.-F	Fe
Céard	Céard	cé-W	W--q
atá	atá	bí-V	Vmip---r
dubh	dubh	dubh-N	Ncmsc
agus	agus	agus-C	Cc
bán	bán	bán-N	Ncmpg|Ncmsc|Aqp
agus	agus	agus-C	Cc
dubh	dubh	dubh-N	Ncmsc|Aqp
agus	agus	agus-C	Cc
bán	bán	bán-N	Ncmpg|Ncmsc|Aqp
agus	agus	agus-C	Cc
dubh	dubh	dubh-N	Ncmsc|Aqp
agus	agus	agus-C	Cc
bán	bán	bán-N	Ncmpg|Ncmsc|Aqp
?	?	?-F	Fq
Piongain	Piongain	piongain-N	Ncfsc
ag	ag	ag-S	Sp
titim	titim	tit-N	Nv
anuas	anuas	anuas-R	Rd
an	an	an-T	Td-s
staighre	staighre	staighre-N	Ncmsg
.	.	.-F	Fe
Shleamhnaigh	Shleamhnaigh	sleamhnaigh-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
agus	agus	agus-C	Cc
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
amach	amach	amach-R	Rd
as	as	as-S	Sp
an	an	an-T	Td-s
bpoll	bpoll	poll-N	Ncmsc
uisce	uisce	uisce-N	Ncmsg|Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
i	i	i-S	Sp
gcroílár	gcroílár	croílár-N	Ncmsc
Chnoc	Chnoc	Cnoc-N	Npfsg
na	na	na-T	Td-p
Fola	Fola	fuil-N	Ncfpg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
siad	siad	siad-P	Pp3-pn
timpeall	timpeall	timpeall-R	Rd
ar	ar	ar-S	Sp
theach	theach	teach-N	Ncmsc
na	na	na-T	Td-p
Gaoithe	Gaoithe	Gaoithe-N	Npmsg
Aduaidh	Aduaidh	aduaidh-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
chomh	chomh	chomh-R	Ri
slachtmhar	slachtmhar	slachtmhar-A	Aqp
néata	néata	néata-A	Aqp
lena	lena	le-S	Spr
bhfaca	bhfaca	feic-V	Vmis---d
tú	tú	tú-P	Pp2-s
riamh	riamh	riamh-R	Rg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhóóóóááááábh	Bhóóóóááááábh	Bhóóóóááááábh-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Déan	Déan	déan-N	Ncmsc
deifir	deifir	deifir-N	Ncfsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
de	de	de-S	Sp
chogar	chogar	cogar-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ní	Ní	ní-Q	Qn
thógfaidh	thógfaidh	tóg-V	Vmif---n
sé	sé	sé-P	Pp3msn
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
orthu	orthu	ar-P	Pr3-p
a	a	a-U	U
oibriú	oibriú	oibrigh-N	Nv
amach	amach	amach-R	Rd
gur	gur	gur-Q	Q--s
bhuail	bhuail	buail-V	Vmis
muid	muid	muid-P	Pp1-p
bob	bob	bob-X	Xfev
orthu	orthu	ar-P	Pr3-p
.	.	.-F	Fe
'	'	'-F	Fa
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
an	an	an-T	Td-s
Réalta	Réalta	réalta-N	Ncfsc
Thuaidh	Thuaidh	tuaidh-A	Aqp
le	le	le-S	Sp
feiceáil	feiceáil	feic-N	Nv
in	in	i-S	Sp
aon	aon	aon-D	Dq
áit	áit	áit-N	Ncfsc
.	.	.-F	Fe
Chuartaigh	Chuartaigh	cuartaigh-V	Vmis
siad	siad	siad-P	Pp3-pn
thuas	thuas	tuaigh-V	Vmip---r
agus	agus	agus-C	Cc
chuartaigh	chuartaigh	cuartaigh-V	Vmis
siad	siad	siad-P	Pp3-pn
thíos	thíos	thíos-R	Rd
.	.	.-F	Fe
Chuartaigh	Chuartaigh	cuartaigh-V	Vmis
siad	siad	siad-P	Pp3-pn
thall	thall	tall-V	Vmis
agus	agus	agus-C	Cc
chuartaigh	chuartaigh	cuartaigh-V	Vmis
siad	siad	siad-P	Pp3-pn
abhus	abhus	abhus-R	Rd
.	.	.-F	Fe
Ach	Ach	ach-R	Ri
réalta	réalta	réalta-A	Aqp
ná	ná	ná-C	Cs|Cc
réalta	réalta	réal-A	Aqp|Ncfsc|Av
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
le	le	le-S	Sp
fáil	fáil	faigh-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
sí	sí	sí-P	Pp3fsn
anseo	anseo	anseo-R	Rl
áit	áit	áit-N	Ncfsc
éigin	éigin	éigin-A	Aq-fsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
B	B	B-X	Xl
’	’	’-F	Fa
fhéidir	fhéidir	féidir-N	Ns-s
gur	gur	gur-Q	Q--s
thug	thug	tabhair-V	Vmis
siad	siad	siad-P	Pp3-pn
leo	leo	leo-N	Ncmsc
í	í	í-P	Pp3fs
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Níl	Níl	bí-V	Vmip---n
mé	mé	mé-P	Pp1-s
ag	ag	ag-S	Sp
fágáil	fágáil	fág-N	Nv
gan	gan	gan-S	Sp
í	í	í-P	Pp3fs
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
agus	agus	agus-C	Cc
bhuail	bhuail	buail-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
heireaball	heireaball	eireaball-N	Ncmsc
le	le	le-S	Sp
fearg	fearg	fearg-N	Ncfsc
in éadan	in éadan	in_éadan-S	Spc
an	an	an-T	Td-s
bhalla	bhalla	balla-N	Ncmsg
.	.	.-F	Fe
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
,	,	,-F	Fi
bhog	bhog	bog-A	Aqp
carraig	carraig	carraig-N	Ncfsc
mhór	mhór	mór-A	Aq-fsv|Aq-fsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
in aice	in aice	in_aice-S	Spc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Scairt	Scairt	scairt-V	Vmis|Vmm-2s
solas	solas	solas-N	Ncmsc
na	na	na-T	Tdfsg
Réalta	Réalta	réalta-N	Ncfsg
Thuaidh	Thuaidh	tuaidh-A	Aqp
amach	amach	amach-R	Rd
as	as	as-S	Sp
seomra	seomra	seomra-N	Ncmsc
rúnda	rúnda	rúnda-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
taobh	taobh	taobh-N	Ncmsc
thiar	thiar	thiar-R	Rd
den	den	de-S	Spa-s
charraig	charraig	carraig-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhóóóóááááábh	Bhóóóóááááábh	Bhóóóóááááábh-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Húrá	Húrá	Húrá-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Is	Is	is-W	Wp-i
anseo	anseo	anseo-R	Rl
atá	atá	bí-V	Vmip---r
sí	sí	sí-P	Pp3fsn
!	!	!-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Agus	Agus	agus-C	Cc
is	is	is-W	Wp-i
anseo	anseo	anseo-R	Rl
a	a	a-Q	Q-r
fhanfaidh	fhanfaidh	fan-V	Vmif
sí	sí	sí-P	Pp3fsn
,	,	,-F	Fi
a	a	a-U	Uv
Charraigín	Charraigín	carraigín-N	Ncmsv
Chatach	Chatach	catach-A	Aq-msc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
go	go	go-U	Ua
fíochmhar	fíochmhar	fíochmhar-A	Aqp
feargach	feargach	feargach-A	Aqp
taobh	taobh	taobh-N	Ncmsc
thiar	thiar	thiar-R	Rd
di	di	do-P	Pr3fs
.	.	.-F	Fe
Cén	Cén	cé-D	Dw--s
fáth	fáth	fáth-N	Ncmsc
a	a	a-Q	Q-i
n	n	n-X	Xl
‑	‑	‑-F	Fb
eitlíonn	eitlíonn	eitil-V	Vmip
na	na	na-T	Td-p
héin	héin	éan-N	Ncmpc
ó	ó	ó-S	Sp
dheas	dheas	deas-N	Ns-s
sa	sa	i-S	Spa-s
gheimhreadh	gheimhreadh	geimhreadh-N	Ncmsc
?	?	?-F	Fq
Thógfadh	Thógfadh	tóg-V	Vmc
sé	sé	sé-P	Pp3msn
rófhada	rófhada	fada-A	Aqp
orthu	orthu	ar-P	Pr3-p
siúl	siúl	siúl-N	Ncmsc
.	.	.-F	Fe
Chas	Chas	Cas-N	Npfsg
Carraigín	Carraigín	carraigín-N	Ncmsc|Ncmsg
timpeall	timpeall	timpeall-N	Ncmpg|Ncmsc|Rd
agus	agus	agus-C	Cc
réalta	réalta	réal-A	Av
ina	ina	i-S	Spp-s
glac	glac	glac-N	Ncfsc
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
ag	ag	ag-S	Sp
stánadh	stánadh	stán-N	Nv
uirthi	uirthi	ar-P	Pr3fs
,	,	,-F	Fi
a	a	a-D	Dp3
bolg	bolg	bolg-N	Ncmsc
lán	lán	lán-A	Aq-msc
le	le	le-S	Sp
fearg	fearg	fearg-N	Ncfsc
.	.	.-F	Fe
Chroith	Chroith	croith-V	Vmis
eireaball	eireaball	eireaball-N	Ncmsc
Charraigín	Charraigín	carraigín-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Dar	Dar	dar-C	Csw
‑	‑	‑-F	Fb
mo	mo	mo-D	Dp1-s
‑	‑	‑-F	Fb
sciathán	sciathán	sciathán-N	Ncmsc
‑	‑	‑-F	Fb
clé	clé	clé-N	Ncfsc
…	…	…-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
go	go	go-U	Ua
faiteach	faiteach	faiteach-A	Aqp
.	.	.-F	Fe
Chaith	Chaith	caith-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
slám	slám	slám-N	Ncmsc|Ncmsg
gainimhe	gainimhe	gainimhe-N	Ncfsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
nGaoth	nGaoth	gaoth-N	Ncmsc|Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Áááááábhuitse	Áááááábhuitse	Áááááábhuitse-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-Q	Q-r
scread	scread	scread-V	Vmis
an	an	an-T	Td-s
ghaoth	ghaoth	gaoth-N	Ncfsc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
súile	súile	súil-N	Ncfpc
lán	lán	lán-A	Aqp
gainimh	gainimh	gaineamh-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tabhair	Tabhair	tabhair-V	Vmm-2s
dom	dom	do-P	Pr1-s
an	an	an-T	Td-s
réalta	réalta	réalta-N	Ncfsc
,	,	,-F	Fi
a	a	a-U	Uv
Charraigín	Charraigín	carraigín-N	Ncmsv
Chatach	Chatach	catach-A	Aq-msc
,	,	,-F	Fi
nó	nó	nó-C	Cc
gearrfaidh	gearrfaidh	gearr-V	Vmif
mé	mé	mé-P	Pp1-s
t	t	t-X	Xl
‑	‑	‑-F	Fb
eireaball	eireaball	eireaball-N	Ncmsc
díot	díot	de-P	Pr2-s
!	!	!-F	Fe
'	'	'-F	Fa
ar	ar	ar-V	Vmis
sí	sí	sí-P	Pp3fsn
go	go	go-U	Ua
fíochmhar	fíochmhar	fíochmhar-A	Aqp
.	.	.-F	Fe
Rug	Rug	beir-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
eireaball	eireaball	eireaball-N	Ncmsc
Charraigín	Charraigín	carraigín-N	Ncmsg
agus	agus	agus-C	Cc
tharraing	tharraing	tarraing-V	Vmis
chuici	chuici	chuig-P	Pr3fs
í	í	í-P	Pp3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	an-T	Td-s
Charraigín	Charraigín	carraigín-N	Ncmsc
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-U	Uv
bhéic	bhéic	béic-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
chroí	chroí	croí-N	Ncmsc
lán	lán	lán-A	Aq-msc
eagla	eagla	eagla-N	Ncfsg
.	.	.-F	Fe
Chaith	Chaith	caith-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
réalta	réalta	réal-A	Av
i	i	i-S	Sp
dtreo	dtreo	treo-N	Ncmsc
a	a	a-D	Dp3
cara	cara	cara-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cuir	Cuir	cur-N	Ncmsg
ar ais	ar ais	ar_ais-R	Rd
sa	sa	i-S	Spa-s
spéir	spéir	spéir-N	Ncfsc
go	go	go-U	Ua
sciobtha	sciobtha	sciob-A	Aqp|Av
í	í	í-P	Pp3fs
,	,	,-F	Fi
a	a	a-U	Uv
Jimí	Jimí	Jimí-N	Npmsc
!	!	!-F	Fe
Níl	Níl	bí-V	Vmip---n
nóiméad	nóiméad	nóiméad-N	Ncmsc
le	le	le-S	Sp
spáráil	spáráil	spáráil-N	Nv
!	!	!-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
cén	cén	cé-W	W--q
chaoi	chaoi	caoi-N	Ncfsc
a	a	a-Q	Q-i
gcuirfidh	gcuirfidh	cuir-V	Vmif
mé	mé	mé-P	Pp1-s
ar ais	ar ais	ar_ais-R	Rd
í	í	í-P	Pp3fs
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
catapult	catapult	catapult-X	Xfen
sa	sa	i-S	Spa-s
phluais	phluais	pluais-N	Ncfsc
!	!	!-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Eitil	Eitil	eitil-N	Ncfsc
,	,	,-F	Fi
a	a	a-U	Uv
Jimí	Jimí	Jimí-N	Npmsc
!	!	!-F	Fe
Caithfidh	Caithfidh	caith-V	Vmif
tú	tú	tú-P	Pp2-s
eitilt	eitilt	eitil-N	Ncfsc|Nv
suas	suas	suas-R	Rd
sa	sa	i-S	Spa-s
spéir	spéir	spéir-N	Ncfsc
léi	léi	le-P	Pr3fs
!	!	!-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Eitilt	Eitilt	eitil-N	Ncfsc|Nv
!	!	!-F	Fe
Mise	Mise	mé-P	Pp1-s-e
?	?	?-F	Fq
Suas	Suas	suas-R	Rd
sa	sa	i-S	Spa-s
spéir	spéir	spéir-N	Ncfsc
?	?	?-F	Fq
'	'	'-F	Fa
Thit	Thit	tit-V	Vmis
an	an	an-T	Td-s
Réalta	Réalta	réalta-N	Ncfsc
Thuaidh	Thuaidh	tuaidh-A	Aqp
ag	ag	ag-S	Sp
cosa	cosa	cos-N	Ncfpc
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
sé	sé	sé-P	Pp3msn
uirthi	uirthi	ar-P	Pr3fs
go	go	go-U	Ua
heaglach	heaglach	eaglach-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Háháááááá	Háháááááá	Háháááááá-N	Npmsc
!	!	!-F	Fe
Háháááááá	Háháááááá	Háháááááá-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
ag	ag	ag-S	Sp
eitilt	eitilt	eitil-N	Nv
!	!	!-F	Fe
Samhlaigh	Samhlaigh	samhlaigh-V	Vmm-2s
é	é	é-P	Pp3ms
!	!	!-F	Fe
Nach	Nach	nach-Q	Qnr
bhfuil	bhfuil	bí-V	Vmip---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
ag	ag	ag-S	Sp
madraí	madraí	madra-N	Ncmpc
na	na	na-T	Td-p
mara	mara	muir-N	Ncfpg
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
faitíos	faitíos	faitíos-N	Ncmsc
ar	ar	ar-S	Sp
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
roimh	roimh	roimh-S	Sp
eitilt	eitilt	eitil-N	Nv
suas	suas	suas-R	Rd
go	go	go-U	Ua
hard	hard	ard-X	Xfea|Aqp
!	!	!-F	Fe
'	'	'-F	Fa
Rinne	Rinne	déan-V	Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
iarracht	iarracht	iarracht-N	Ncfsc
an	an	an-T	Td-s
réalta	réalta	réalta-N	Ncfsc
a	a	a-U	U
sciobadh	sciobadh	sciob-N	Nv
ón	ón	ó-S	Spa-s
talamh	talamh	talamh-N	Ncfsc
ach	ach	ach-C	Cs
ní	ní	is-W	Wp-in
fhéadfadh	fhéadfadh	féad-V	Vmc
sí	sí	sí-P	Pp3fsn
é	é	é-P	Pp3ms
sin	sin	sin-P	Pd|W
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
agus	agus	agus-C	Cc
greim	greim	greim-N	Ncmsc
a	a	a-Q	Q-r
choimeád	choimeád	coimeád-V	Vmis
ar	ar	ar-S	Sp
eireaball	eireaball	eireaball-N	Ncmsc
sleamhain	sleamhain	sleamhain-A	Aq-msc
Charraigín	Charraigín	carraigín-N	Ncmsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
in ann	in ann	in_ann-S	Spc
chuige	chuige	chuig-P	Pr3ms
,	,	,-F	Fi
a	a	a-U	Uv
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
in ann	in ann	in_ann-S	Spc
!	!	!-F	Fe
'	'	'-F	Fa
Rug	Rug	beir-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
ar	ar	is-N	Ncmsc|Wpsi|Wssi|Wpdi
réalta	réalta	réal-A	Av
ina	ina	i-S	Spp-s
ghob	ghob	gob-N	Ncmsc
agus	agus	agus-C	Cc
suas	suas	suas-R	Rd
,	,	,-F	Fi
suas	suas	suas-R	Rd
,	,	,-F	Fi
suas	suas	suas-R	Rd
leis	leis	le-P	Pr3ms
trí	trí	trí-M	Mc|Sp
shimléar	shimléar	simléar-N	Ncmsc
an	an	an-T	Td-s
chnoic	chnoic	cnoc-N	Ncmsg
agus	agus	agus-C	Cc
amach	amach	amach-R	Rd
san	san	i-S	Spa-s
oíche	oíche	oíche-N	Ncfsc
dhorcha	dhorcha	dorcha-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
ghealach	ghealach	gealach-N	Ncfsc
lán	lán	lán-A	Aq-fsc
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
déanamh	déanamh	déan-N	Nv
iarrachta	iarrachta	iarracht-N	Ncfsg
briseadh	briseadh	bris-V	Vmis0
amach	amach	amach-R	Rd
trí	trí	trí-S	Sp
na	na	na-T	Td-p
scamaill	scamaill	scamall-N	Ncmpc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
na	na	na-T	Td-p
maighdeana	maighdeana	maighdean-N	Ncfpc
mara	mara	mara-C	Cs
eile	eile	eile-D	Dd
fós	fós	fós-R	Rg
ag	ag	ag-S	Sp
caoineadh	caoineadh	caoin-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Táimid	Táimid	bí-V	Vmip1p
réidh	réidh	réidh-A	Aqp
!	!	!-F	Fe
'	'	'-F	Fa
ar	ar	ar-V	Vmis
siad	siad	siad-P	Pp3-pn
.	.	.-F	Fe
‘	‘	‘-X	Xx
Táimid	Táimid	bí-V	Vmip1p
réidh	réidh	réidh-A	Aqp
!	!	!-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Coinnigh	Coinnigh	Coinnigh-N	Npmsc
ort	ort	ar-P	Pr2-s
,	,	,-F	Fi
a	a	a-U	Uv
Jimí	Jimí	Jimí-N	Npmsc
.	.	.-F	Fe
Coinnigh	Coinnigh	Coinnigh-N	Npmsc
ort	ort	ar-P	Pr2-s
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-U	Uv
bhéic	bhéic	béic-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
.	.	.-F	Fe
Cén	Cén	cé-W	W--q
t	t	t-X	Xl
‑	‑	‑-F	Fb
ainm	ainm	ainm-N	Ncmsc
is	is	is-W	Wpri
féidir	féidir	féidir-N	Ns-s
a	a	a-U	U
ithe	ithe	ith-N	Nv
?	?	?-F	Fq
Carraigín	Carraigín	carraigín-N	Ncmsc
.	.	.-F	Fe
Scaoil	Scaoil	scaoil-V	Vmis|Vmm-2s
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
le	le	le-S	Sp
Carraigín	Carraigín	carraigín-N	Ncmsc
.	.	.-F	Fe
Suas	Suas	suas-R	Rd
léi	léi	le-P	Pr3fs
in	in	i-S	Sp
airde	airde	aird-N	Ncfsc|Ncfpc
sa	sa	i-S	Spa-s
spéir	spéir	spéir-N	Ncfsc
sa	sa	i-S	Spa-s
tóir	tóir	tóir-N	Ncfsc
ar	ar	ar-S	Sp
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
ag	ag	ag-S	Sp
imeacht	imeacht	imigh-N	Nv
iad	iad	iad-P	Pp3-p
agus	agus	agus-C	Cc
sciatháin	sciatháin	sciathán-N	Ncmsg|Ncmpc|Ncmsg
a	a	a-D	Dp3
carad	carad	cara-N	Ncmsg
dílis	dílis	dílis-A	Aq-msc
ag	ag	ag-S	Sp
bualadh	bualadh	buail-N	Nv
go	go	go-U	Ua
tréan	tréan	tréan-A	Aqp
.	.	.-F	Fe
‘	‘	‘-X	Xx
Maith	Maith	Maith-N	Npmsc
thú	thú	tú-P	Pp2-s
!	!	!-F	Fe
Coinnigh	Coinnigh	Coinnigh-N	Npmsc
ort	ort	ar-P	Pr2-s
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-S	Sp|Cs
stop	stop	stop-V	Vmis|Ncmsc
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
ag	ag	ag-S	Sp
eitilt	eitilt	eitil-N	Nv
.	.	.-F	Fe
‘	‘	‘-X	Xx
Há	Há	Há-N	Npmsc
!	!	!-F	Fe
Há	Há	Há-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
an	an	an-T	Td-s
smugairle	smugairle	smugairle-N	Ncmsc
róin	róin	rón-N	Ncmsg
agus	agus	agus-C	Cc
shleamhnaigh	shleamhnaigh	sleamhnaigh-V	Vmis
sé	sé	sé-P	Pp3msn
isteach	isteach	isteach-R	Rd
san	san	i-S	Spa-s
uisce	uisce	uisce-N	Ncmsc
.	.	.-F	Fe
Lean	Lean	Lean-N	Npmsc
Carraigín	Carraigín	carraigín-N	Ncmsc|Ncmsg
é	é	é-P	Pp3ms
.	.	.-F	Fe
Thuas	Thuas	tuaigh-R	Rd|Vmip---r
sa	sa	i-S	Spa-s
spéir	spéir	spéir-N	Ncfsc
,	,	,-F	Fi
shéid	shéid	séid-V	Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
cléití	cléití	cléit-N	Ncmpc
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
,	,	,-F	Fi
anonn	anonn	anonn-R	Rd
is	is	agus-C	Cc
anall	anall	anall-R	Rd
,	,	,-F	Fi
anoir	anoir	anoir-A	Aqp
is	is	agus-C	Cc
aniar	aniar	aniar-A	Aqp|Rd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
réalta	réalta	réalta-N	Ncfsc
fós	fós	fós-R	Rg
ina	ina	i-S	Spp-s
ghob	ghob	gob-N	Ncmsc
aige	aige	ag-P	Pr3ms
ach	ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
scéin	scéin	scéin-N	Ncfsc
ina	ina	i-S	Spp-s
shúile	shúile	súil-N	Ncfpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
tú	tú	tú-P	Pp2-s
agam	agam	ag-P	Pr1-s
anois	anois	anois-R	Rt
,	,	,-F	Fi
a	a	a-U	Uv
phleota	phleota	pleota-N	Ncmsv
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-Q	Q-r
gháir	gháir	gáir-V	Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
.	.	.-F	Fe
Thíos	Thíos	thíos-R	Rd
fúthu	fúthu	faoi-P	Pr3-p
,	,	,-F	Fi
ghlaoigh	ghlaoigh	glaoigh-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
ar	ar	ar-S	Sp
na	na	na-T	Td-p
maighdeana	maighdeana	maighdean-N	Ncfpc
mara	mara	muir-N	Ncfpc|Cs|Ncfpg|Ncfsg
eile	eile	eile-D	Dd
le	le	le-S	Sp
cabhrú	cabhrú	cabhraigh-N	Nv
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Caithfidh	Caithfidh	caith-V	Vmif
muid	muid	muid-P	Pp1-p
tacú	tacú	tacaigh-N	Nv
le	le	le-S	Sp
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
ar	ar	ar-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
níor	níor	is-W	Ws-in
thug	thug	tabhair-V	Vmis
siad	siad	siad-P	Pp3-pn
aon	aon	aon-N	Ncmsc
aird	aird	ard-A	Aq-msg|Aq-msv
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bíodh	Bíodh	bí-V	Vmm-3s
agaibh	agaibh	ag-P	Pr2-p
,	,	,-F	Fi
mar	mar	mar-C	Cs
sin	sin	sin-W	W
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Déanfaidh	Déanfaidh	déan-V	Vmif
mé	mé	mé-P	Pp1-s
féin	féin	féin-P	Px
é	é	é-P	Pp3ms
!	!	!-F	Fe
'	'	'-F	Fa
Thosaigh	Thosaigh	tosaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
bualadh	bualadh	buail-N	Nv
a	a	a-D	Dp3
heireaball	heireaball	eireaball-N	Ncmsc
ar	ar	ar-S	Sp
chlár	chlár	clár-N	Ncmsc
na	na	na-T	Tdfsg
farraige	farraige	farraige-N	Ncfsg
.	.	.-F	Fe
‘	‘	‘-X	Xx
Jim	Jim	Jim-N	Npmsc
‑	‑	‑-F	Fb
í	í	í-P	Pp3fs
!	!	!-F	Fe
Jim	Jim	Jim-N	Npmsc
‑	‑	‑-F	Fb
í	í	í-P	Pp3fs
!	!	!-F	Fe
Jim	Jim	Jim-N	Npmsc
‑	‑	‑-F	Fb
í	í	í-P	Pp3fs
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-Q	Q-r
bhéic	bhéic	béic-V	Vmis
sí	sí	sí-P	Pp3fsn
in	in	sin-S	Sp|Pd
ard	ard	ard-N	Ncmsc|Aqp
a	a	a-D	Dp3
gutha	gutha	guth-N	Ncmsg
.	.	.-F	Fe
Chuala	Chuala	clois-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
í	í	í-P	Pp3fs
.	.	.-F	Fe
Siúd	Siúd	siúd-P	Pd
leis	leis	le-P	Pr3ms
ag	ag	ag-S	Sp
eitilt	eitilt	eitil-N	Nv
arís	arís	arís-R	Rg
.	.	.-F	Fe
Suas	Suas	suas-R	Rd
,	,	,-F	Fi
suas	suas	suas-R	Rd
,	,	,-F	Fi
suas	suas	suas-R	Rd
leis	leis	le-P	Pr3ms
i	i	i-S	Sp
dtreo	dtreo	treo-N	Ncmsc
na	na	na-T	Tdfsg
gealaí	gealaí	gealach-N	Ncfsg
agus	agus	agus-C	Cc
an	an	an-T	Td-s
Réalta	Réalta	réaladh-N	Ncmsg
Thuaidh	Thuaidh	tuaidh-A	Aqp
ag	ag	ag-S	Sp
lonrú	lonrú	lonraigh-N	Nv
ina	ina	i-S	Spp-s
ghob	ghob	gob-N	Ncmsc
.	.	.-F	Fe
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
,	,	,-F	Fi
chuala	chuala	clois-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
glórtha	glórtha	glór-N	Ncmpc
na	na	na-T	Td-p
maighdean	maighdean	maighdean-N	Ncfpg
mara	mara	muir-N	Ncfpc|Ncfpg|Ncfsg|Ncfpg|Ncfsg
eile	eile	eile-D	Dd
taobh	taobh	taobh-N	Ncmsc
thiar	thiar	thiar-R	Rd
di	di	do-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Jim	Jim	Jim-N	Npmsc
‑	‑	‑-F	Fb
í	í	í-P	Pp3fs
!	!	!-F	Fe
Jim	Jim	Jim-N	Npmsc
‑	‑	‑-F	Fb
í	í	í-P	Pp3fs
!	!	!-F	Fe
'	'	'-F	Fa
ar	ar	ar-V	Vmis
siad	siad	siad-P	Pp3-pn
go	go	go-U	Ua
bríomhar	bríomhar	bríomhar-A	Aqp
.	.	.-F	Fe
Is	Is	is-W	Wp-i
ar	ar	ar-S	Sp
éigean	éigean	éigean-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
in ann	in ann	in_ann-S	Spc
eitilt	eitilt	eitil-N	Nv
i gcoinne	i gcoinne	i_gcoinne-S	Spc
na	na	na-T	Td-p
Gaoithe	Gaoithe	Gaoithe-N	Npmsg
Aduaidh	Aduaidh	aduaidh-A	Aqp
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
choinnigh	choinnigh	coinnigh-V	Vmis
sé	sé	sé-P	Pp3msn
air	air	ar-P	Pr3ms
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
thuas	thuas	thuas-R	Rd
i	i	i-S	Sp
measc	measc	measc-N	Ncmsc
na	na	na-T	Td-p
scamall	scamall	scamall-N	Ncmpg
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
rud	rud	rud-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
le	le	le-S	Sp
feiceáil	feiceáil	feic-N	Nv
ach	ach	ach-C	Cs
an	an	is-W	Wpdq|Wp-q
dorchadas	dorchadas	dorchadas-N	Ncmsc
agus	agus	agus-C	Cc
loinnir	loinnir	loinnir-N	Ncfsc
lag	lag	lag-A	Aq-fsc
na	na	na-T	Tdfsg
lánghealaí	lánghealaí	gealach-N	Ncfsg
taobh	taobh	taobh-N	Ncmsc
thiar	thiar	thiar-R	Rd
de	de	de-S	Sp
na	na	na-T	Td-p
scamaill	scamaill	scamall-N	Ncmpc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ó	Ó	Ó-I	I
,	,	,-F	Fi
a	a	a-U	Uv
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
de	de	de-S	Sp
chogar	chogar	cogar-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cá	Cá	cá-R	Rq
bhfuil	bhfuil	bí-V	Vmip---d
tú	tú	tú-P	Pp2-s
?	?	?-F	Fq
'	'	'-F	Fa
Dhruid	Dhruid	druid-V	Vmis
na	na	na-T	Td-p
maighdeana	maighdeana	maighdean-N	Ncfpc
mara	mara	muir-N	Ncfpc|Cs|Ncfpg|Ncfsg
eile	eile	eile-D	Dd
isteach	isteach	isteach-R	Rd
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-Q	Qnm
bíodh	bíodh	bí-V	Vmm-3s-n
imní	imní	imní-N	Ncfsc
ort	ort	ar-P	Pr2-s
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
siad	siad	siad-P	Pp3-pn
.	.	.-F	Fe
‘	‘	‘-X	Xx
Rinne	Rinne	déan-V	Vmis
tú	tú	tú-P	Pp2-s
do	do	do-S	Sp
dhícheall	dhícheall	dícheall-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Thosaigh	Thosaigh	tosaigh-V	Vmis
na	na	na-T	Td-p
maighdeana	maighdeana	maighdean-N	Ncfpc
mara	mara	muir-N	Ncfpc|Cs|Ncfpg|Ncfsg
eile	eile	eile-D	Dd
ag	ag	ag-S	Sp
canadh	canadh	can-N	Nv
go	go	go-U	Ua
híseal	híseal	íseal-A	Aqp
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
cinnte	cinnte	cinnte-A	Av|Aqp
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
deireadh	deireadh	deireadh-N	Ncmsc
le	le	le-S	Sp
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
.	.	.-F	Fe
Shéid	Shéid	séid-V	Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
fágtha	fágtha	fág-A	Av
ina	ina	i-S	Spp-s
bolg	bolg	bolg-N	Ncmsc
leis	leis	le-S	Sp
na	na	na-T	Td-p
scamaill	scamaill	scamall-N	Ncmpc
dhorcha	dhorcha	dorcha-A	Aqp
agus	agus	agus-C	Cc
scaip	scaip	scaip-V	Vmis|Vmm-2s
iad	iad	iad-P	Pp3-p
go	go	go-S	Sp
bun	bun	bun-N	Ncmsc
na	na	na-T	Tdfsg
spéire	spéire	spéir-N	Ncfsg
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
an	an	an-T	Td-s
ghealach	ghealach	gealach-N	Ncfsc
lán	lán	lán-A	Aq-fsc
,	,	,-F	Fi
í	í	í-P	Pp3fs
chomh	chomh	chomh-R	Ri
bán	bán	bán-A	Aqp
le	le	le-S	Sp
péarla	péarla	péarla-N	Ncmsc
agus	agus	agus-C	Cc
dreach	dreach	dreach-N	Ncmsc
draíochtach	draíochtach	draíochtach-A	Aq-msc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
In	In	i-S	Sp
aice	aice	aice-N	Ncfsc
léi	léi	le-P	Pr3fs
,	,	,-F	Fi
áfach	áfach	áfach-R	Rg
,	,	,-F	Fi
shoilsigh	shoilsigh	soilsigh-V	Vmis
an	an	an-T	Td-s
Réalta	Réalta	réalta-N	Ncfsc
Thuaidh	Thuaidh	tuaidh-A	Aqp
,	,	,-F	Fi
a	a	a-U	Uv
loinnir	loinnir	loinnir-N	Ncfsv
aoibhinn	aoibhinn	aoibhinn-A	Aq-fsv
álainn	álainn	álainn-A	Aq-fsc|Aq-fsv
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
seoid	seoid	seoid-N	Ncfsc
luachmhar	luachmhar	luachmhar-A	Aq-fsc
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
ag	ag	ag-S	Sp
tabhairt	tabhairt	tabhair-N	Nv
cosaint	cosaint	cosain-N	Ncfsc|Nv
do	do	do-S	Sp
na	na	na-T	Td-p
maighdeana	maighdeana	maighdean-N	Ncfpc
mara	mara	muir-N	Ncfpc|Cs|Ncfpg|Ncfsg
.	.	.-F	Fe
Thuirling	Thuirling	tuirling-V	Vmis
éan	éan	éan-N	Ncmsc
beag	beag	beag-A	Aq-msc
bán	bán	bán-A	Aq-msc
i	i	i-S	Sp
dtreo	dtreo	treo-N	Ncmsc
na	na	na-T	Tdfsg
farraige	farraige	farraige-N	Ncfsg
,	,	,-F	Fi
a	a	a-U	Uv|Dp3
sciatháin	sciatháin	sciathán-N	Ncmsv|Ncmpc
ag	ag	ag-S	Sp
bualadh	bualadh	buail-N	Nv
go	go	go-U	Ua
tréan	tréan	tréan-A	Aqp
agus	agus	agus-C	Cc
a	a	a-Q	Q-r
ghob	ghob	gob-V	Vmis
folamh	folamh	folamh-A	Aqp
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
spíonta	spíonta	spíon-A	Av
.	.	.-F	Fe
Shleamhnaigh	Shleamhnaigh	sleamhnaigh-V	Vmis
an	an	an-T	Td-s
smugairle	smugairle	smugairle-N	Ncmsc
róin	róin	rón-N	Ncmsg
leis	leis	le-P	Pr3ms
abhaile	abhaile	abhaile-R	Rd
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
an	an	an-T	Td-s
samhradh	samhradh	samhradh-N	Ncmsc
go	go	go-U	Ua
luath	luath	luath-A	Aqp
an	an	an-T	Td-s
bhliain	bhliain	bliain-N	Ncfsc
sin	sin	sin-D	Dd
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
amach	amach	amach-R	Rd
béal	béal	béal-N	Ncmsc
na	na	na-T	Tdfsg
pluaise	pluaise	pluais-N	Ncfsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
ghrian	ghrian	grian-V	Vmis
go	go	go-U	Ua
hard	hard	ard-X	Xfea|Aqp
sa	sa	i-S	Spa-s
spéir	spéir	spéir-N	Ncfsc
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
fharraige	fharraige	farraige-N	Ncfsc
ciúin	ciúin	ciúin-A	Aqp
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
na	na	na-T	Td-p
maighdeana	maighdeana	maighdean-N	Ncfpc
mara	mara	muir-N	Ncfpc|Cs|Ncfpg|Ncfsg
eile	eile	eile-D	Dd
í	í	í-P	Pp3fs
.	.	.-F	Fe
‘	‘	‘-X	Xx
A	A	an-T	Td-s
Charraigín	Charraigín	carraigín-N	Ncmsc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
duine	duine	duine-N	Ncmsc
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cabhraigh	Cabhraigh	cabhraigh-V	Vmm-2s
liom	liom	le-P	Pr1-s
mo	mo	mo-D	Dp1-s
ghruaig	ghruaig	gruaig-N	Ncfsc
a	a	a-U	U
chíoradh	chíoradh	cíor-N	Nv
.	.	.-F	Fe
Tá	Tá	bí-V	Vmip
sí	sí	sí-P	Pp3fsn
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
cnap	cnap	cnap-N	Ncmsc
feamainne	feamainne	feamainn-N	Ncfsg
!	!	!-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Cabhraigh	Cabhraigh	cabhraigh-V	Vmm-2s
liomsa	liomsa	le-P	Pr1-s-e
amhrán	amhrán	amhrán-N	Ncmsc
nua	nua	nua-A	Aqp
a	a	a-U	U
chumadh	chumadh	cum-N	Nv
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
duine	duine	duine-N	Ncmsc
eile	eile	eile-D	Dd
.	.	.-F	Fe
Phreab	Phreab	preab-V	Vmis
eireaball	eireaball	eireaball-N	Ncmsc
Charraigín	Charraigín	carraigín-N	Ncmsg
le	le	le-S	Sp
háthas	háthas	áthas-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
ina	ina	i-S	Spp-p|Spp-s
maighdean	maighdean	maighdean-N	Ncfsc
mhara	mhara	muir-N	Ncfsg
cheart	cheart	ceart-A	Aq-fsc|Aq-fsv
faoi	faoi	faoi-S	Sp
dheireadh	dheireadh	deireadh-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Cááááá	Cááááá	Cááááá-N	Npmsc
!	!	!-F	Fe
Cááááá	Cááááá	Cááááá-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
in	in	i-S	Sp
airde	airde	airde-N	Ncfpc|Ncfsc
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
sí	sí	sí-P	Pp3fsn
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
thuas	thuas	tuaigh-R	Rd|Vmip---r
sa	sa	i-S	Spa-s
spéir	spéir	spéir-N	Ncfsc
ghorm	ghorm	gorm-A	Aq-fsc
ag	ag	ag-S	Sp
casadh	casadh	cas-N	Nv
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
roth	roth	roth-N	Ncmsc
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Thurling	Thurling	Thurling-N	Npmsc
sé	sé	is-W	Wp-i-3
in aice	in aice	in_aice-S	Spc
le	le	le-S	Sp
Carraigín	Carraigín	carraigín-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
An	An	an-Q	Qq
bhfaca	bhfaca	feic-V	Vmis---d
tú	tú	tú-P	Pp2-s
mé	mé	mé-P	Pp1-s
?	?	?-F	Fq
'	'	'-F	Fa
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
.	.	.-F	Fe
‘	‘	‘-X	Xx
Chonaic	Chonaic	feic-V	Vmis
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhí	Bhí	bí-V	Vmis
tú	tú	tú-P	Pp2-s
go	go	go-U	Ua
hiontach	hiontach	iontach-A	Aqp
!	!	!-F	Fe
'	'	'-F	Fa
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
rith	rith	rith-N	Ncmsc|Nv|Vmis|Nv
scamaill	scamaill	scamall-N	Ncmsg|Ncmpc|Ncmsg
dhorcha	dhorcha	dorcha-A	Aqp
thar	thar	thar-S	Sp
éadan	éadan	éadan-N	Ncmsc
na	na	na-T	Tdfsg
gréine	gréine	grian-N	Ncfsg
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
mórthimpeall	mórthimpeall	mórthimpeall-N	Ncmsc
.	.	.-F	Fe
Tada	Tada	tada-N	Ncmsc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt|Rl
chuala	chuala	clois-V	Vmis
sí	sí	sí-P	Pp3fsn
é	é	é-P	Pp3ms
!	!	!-F	Fe
‘	‘	‘-X	Xx
Fuuuuuiisssss	Fuuuuuiisssss	Fuuuuuiisssss-N	Nc
!	!	!-F	Fe
Úúúúúúúúúú	Úúúúúúúúúú	Úúúúúúúúúú-N	Npmsc
!	!	!-F	Fe
'	'	'-F	Fa
An	An	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
D	D	D-X	Xl
’	’	’-F	Fa
fhéach	fhéach	féach-V	Vmis
chuile	chuile	gach-D	Dq
dhuine	dhuine	duine-N	Ncmsc
ar	ar	ar-S	Sp
Charraigín	Charraigín	carraigín-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bhuel	Bhuel	bhuel-X	Xsc
!	!	!-F	Fe
Bhuel	Bhuel	bhuel-X	Xsc
!	!	!-F	Fe
'	'	'-F	Fa
ar	ar	ar-V	Vmis
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ár	Ár	ár-D	Dp1-p
seanchara	seanchara	cara-N	Ncmsc
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
!	!	!-F	Fe
Ní	Ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
muid	muid	muid-P	Pp1-p
ise	ise	í-P	Pp3fs-e
le	le	le-S	Sp
fada	fada	fada-A	Aqp
.	.	.-F	Fe
'	'	'-F	Fa
‘	‘	‘-X	Xx
Ní	Ní	is-W	Wp-in
maith	maith	maith-A	Aqp
léi	léi	le-P	Pr3fs
ghrian	ghrian	grian-V	Vmis
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Tá	Tá	bí-V	Vmip
faitíos	faitíos	faitíos-N	Ncmsc
uirthi	uirthi	ar-P	Pr3fs
roimpi	roimpi	roimh-P	Pr3fs
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
na	na	na-T	Td-p
maighdeana	maighdeana	maighdean-N	Ncfpc
mara	mara	muir-N	Ncfpc|Cs|Ncfpg|Ncfsg
eile	eile	eile-D	Dd
.	.	.-F	Fe
‘	‘	‘-X	Xx
Bíonn	Bíonn	bí-V	Vmig
faitíos	faitíos	faitíos-N	Ncmsc
ar	ar	ar-S	Sp
chuile	chuile	cuile-N	Ncfsc
dhuine	dhuine	duine-N	Ncmsg
roimh	roimh	roimh-S	Sp
rud	rud	rud-N	Ncmsc
eicínt	eicínt	eicínt-A	Aq-msc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ach	Ach	ach-C	Cs
níl	níl	bí-V	Vmip---n
aon	aon	aon-D	Dq
fhaitíos	fhaitíos	faitíos-N	Ncmsc
ortsa	ortsa	ar-P	Pr2-s-e
roimh	roimh	roimh-S	Sp
an	an	an-T	Td-s
Ghaoth	Ghaoth	gaoth-N	Ncfsc
Aduaidh	Aduaidh	aduaidh-A	Aqp
níos	níos	níos-U	Uc
mó	mó	mór-A	Aqc
,	,	,-F	Fi
’	’	’-F	Fa
arsa	arsa	arsa-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Ná	Ná	ná-C	Cs|Cc
ortsa	ortsa	ar-P	Pr2-s-e
roimh	roimh	roimh-S	Sp
eitilt	eitilt	eitil-N	Nv
suas	suas	suas-R	Rd
go	go	go-U	Ua
hard	hard	ard-X	Xfea|Aqp
,	,	,-F	Fi
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sise	sise	sí-P	Pp3fsne
ar ais	ar ais	ar_ais-R	Rd
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
‘	‘	‘-X	Xx
Dar	Dar	dar-C	Csw
‑	‑	‑-F	Fb
oíche	oíche	oíche-N	Ncfsc
‑	‑	‑-F	Fb
is	is	is-W	Wpri
‑	‑	‑-F	Fb
lá	lá	lá-N	Ncmsc
‑	‑	‑-F	Fb
nach	nach	nach-C	Cs
‑	‑	‑-F	Fb
orainne	orainne	ar-P	Pr1-p-e
‑	‑	‑-F	Fb
atá	atá	bí-V	Vmip---r
‑	‑	‑-F	Fb
‑	‑	‑-F	Fb
t	t	t-X	Xl
‑	‑	‑-F	Fb
ádh	ádh	ádh-N	Ncmsc
!	!	!-F	Fe
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Jimí	Jimí	Jimí-N	Npmsc
‑	‑	‑-F	Fb
Joe	Joe	Joe-N	Npmsc
‑	‑	‑-F	Fb
Jeaic	Jeaic	Jeaic-N	Npmsc
agus	agus	agus-C	Cc
suas	suas	suas-R	Rd
leis	leis	le-P	Pr3ms
go	go	go-S	Sp
barr	barr	barr-N	Ncmsc
na	na	na-T	Tdfsg
spéire	spéire	spéir-N	Ncfsg
.	.	.-F	Fe
Thum	Thum	tum-V	Vmis
Carraigín	Carraigín	carraigín-N	Ncmsc
faoin	faoin	faoi-S	Spa-s
uisce	uisce	uisce-N	Ncmsc
agus	agus	agus-C	Cc
meangadh	meangadh	meangadh-V	Vmis0|Vmm-3s|Ncmsc
mór	mór	mór-A	Aq-msc|Aqp|Ncmpg|Ncmsc|Ncmpg
gáire	gáire	gáir-N	Ncfsg|Nv|Ncmsg|Ncmsc|Nv--g
ar	ar	is-N	Ncmsc|Sp|Wssi|Wpdi|Wpsi
a	a	a-D	Dp3
haghaidh	haghaidh	aghaidh-N	Ncfsc
.	.	.-F	Fe
‘	‘	‘-X	Xx
Nach	Nach	is-C	Cs|Wpdin|Wpsin
orainn	orainn	ar-P	Pr1-p
atá	atá	bí-V	Vmip---r
!	!	!-F	Fe
’	’	’-F	Fa
ar	ar	ar-V	Vmis
sí	sí	sí-P	Pp3fsn
de	de	de-S	Sp
chogar	chogar	cogar-N	Ncmsc
.	.	.-F	Fe
