Bhí	Bhí	bí-V	Vmis
ochtapas	ochtapas	ochtapas-N	Ncmsc
óg	óg	óg-A	Aq-msc
ina	ina	i-S	Spp-s
chónaí	chónaí	cónaí-N	Ncmsc
san	san	i-S	Spa-s
fharraige	fharraige	farraige-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
dath	dath	dath-N	Ncmsc
oráiste	oráiste	oráiste-A	Aq-msc
air	air	ar-P	Pr3ms
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
in ann	in ann	in_ann-S	Spc
snámh	snámh	snámh-N	Nv
go	go	go-U	Ua
tapa	tapa	tapa-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
ocht	ocht	ocht-M	Mc
gcos	gcos	cos-N	Ncfsc
air	air	ar-P	Pr3ms
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an-fhada	an-fhada	fada-A	Aqp
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
an	an	an-T	Td-s
t-ochtapas	t-ochtapas	ochtapas-N	Ncmsc
amach	amach	amach-R	Rd
maidin	maidin	maidin-N	Ncfsc
amháin	amháin	amháin-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
snámh	snámh	snámh-N	Nv
leis	leis	le-P	Pr3ms
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
súgradh	súgradh	súgradh-N	Nv
lena	lena	le-S	Spp-s
chairde	chairde	cara-N	Ncmpc
.	.	.-F	Fe
Ansin	Ansin	ansin-R	Rt
,	,	,-F	Fi
tháinig	tháinig	tar-V	Vmis
ocras	ocras	ocras-N	Ncmsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
bia	bia	bia-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
aige	aige	ag-P	Pr3ms
ach	ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
bia	bia	bia-N	Ncmsc
ag	ag	ag-S	Sp
a	a	a-D	Dp3
chairde	chairde	cara-N	Ncmpc
.	.	.-F	Fe
D'iarr	D'iarr	iarr-V	Vmis
sé	sé	sé-P	Pp3msn
orthu	orthu	ar-P	Pr3-p
an	an	an-T	Td-s
bia	bia	bia-N	Ncmsc
a	a	a-U	U
roinnt	roinnt	roinn-N	Nv
leis	leis	le-P	Pr3ms
ach	ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
siad	siad	siad-P	Pp3-pn
sásta	sásta	sásta-A	Aqp
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
roinnt	roinnt	roinn-N	Nv
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
sin	sin	sin-P	Pd
brón	brón	brón-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
ochtapas	ochtapas	ochtapas-N	Ncmsc
óg	óg	óg-A	Aq-msc
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
sé	sé	sé-P	Pp3msn
ar ais	ar ais	ar_ais-R	Rd
abhaile	abhaile	abhaile-R	Rd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
mhamaí	mhamaí	mamaí-N	Ncfsc
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Dúirt	Dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
lena	lena	le-S	Spp-s
mhamaí	mhamaí	mamaí-N	Ncfsc
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
duine	duine	duine-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
sásta	sásta	sásta-A	Aqp
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
roinnt	roinnt	roinn-N	Nv
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
sí	sí	sí-P	Pp3fsn
bia	bia	bia-N	Ncmsc
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
an-sásta	an-sásta	sásta-A	Aqp
ansin	ansin	ansin-R	Rt
.	.	.-F	Fe
Go	Go	go-U	Ua
tobann	tobann	tobann-A	Aqp
,	,	,-F	Fi
bhuail	bhuail	buail-V	Vmis
duine	duine	duine-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
doras	doras	doras-N	Ncmsc
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
an	an	an-T	Td-s
t-ochtapas	t-ochtapas	ochtapas-N	Ncmsc
óg	óg	óg-A	Aq-msc
amach	amach	amach-R	Rd
.	.	.-F	Fe
A	A	an-T	Td-s
chara	chara	cara-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Dúirt	Dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
brón	brón	brón-N	Ncmsc
air	air	ar-P	Pr3ms
faoin	faoin	faoi-S	Spa-s
mbia	mbia	bia-N	Ncmsc
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
sin	sin	sin-P	Pd
áthas	áthas	áthas-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
ochtapas	ochtapas	ochtapas-N	Ncmsc
óg	óg	óg-A	Aq-msc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
cairdiúil	cairdiúil	cairdiúil-A	Aqp
arís	arís	arís-R	Rg
agus	agus	agus-C	Cc
chuaigh	chuaigh	téigh-V	Vmis
siad	siad	siad-P	Pp3-pn
amach	amach	amach-R	Rd
ag	ag	ag-S	Sp
snámh	snámh	snámh-N	Nv
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
súgradh	súgradh	súgradh-N	Nv
.	.	.-F	Fe
