Fadó	Fadó	fadó-R	Rt
in	in	i-S	Sp
Éirinn	Éirinn	Éire-N	Npfsd
bhí	bhí	bí-V	Vmis
fear	fear	fear-N	Ncmsc
ann	ann	ann-R	Rl
darbh	darbh	is-W	Wpsi
ainm	ainm	ainm-N	Ncmsc
Culann	Culann	Culann-N	Npmsc
.	.	.-F	Fe
Lá	Lá	lá-N	Ncmsc
amháin	amháin	amháin-A	Aqp
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
féasta	féasta	féasta-N	Ncmsc
aige	aige	ag-P	Pr3ms
ina	ina	i-S	Spp-s
chaisleán	chaisleán	caisleán-N	Ncmsc
lena	lena	le-S	Spp-s
chairde	chairde	cara-N	Ncmpc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
cú	cú	cú-N	Ncmsc
mór	mór	mór-A	Aq-msc
fíochmhar	fíochmhar	fíochmhar-A	Aq-msc
mar	mar	mar-S	Sp
gharda	gharda	garda-N	Ncmsc
aige	aige	ag-P	Pr3ms
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
dath	dath	dath-N	Ncmsc
dubh	dubh	dubh-A	Aq-msc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
cú	cú	cú-N	Ncmsc
taobh amuigh	taobh amuigh	taobh_amuigh-R	Rl
den	den	de-S	Spa-s
chaisleán	chaisleán	caisleán-N	Ncmsc
ar	ar	ar-S	Sp
faire	faire	fair-N	Nv
agus	agus	agus-C	Cc
an	an	an-T	Td-s
féasta	féasta	féasta-N	Ncmsc
ar	ar	ar-S	Sp
siúl	siúl	siúil-N	Nv
.	.	.-F	Fe
Chonaic	Chonaic	feic-V	Vmis
an	an	an-T	Td-s
cú	cú	cú-N	Ncmsc
buachaill	buachaill	buachaill-N	Ncmsc
óg	óg	óg-A	Aq-msc
darbh	darbh	is-W	Wpsi
ainm	ainm	ainm-N	Ncmsc
Setanta	Setanta	Setanta-N	Npmsc
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
chuig	chuig	chuig-S	Sp
an	an	an-T	Td-s
gcaisleán	gcaisleán	caisleán-N	Ncmsc
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
tafann	tafann	tafainn-N	Nv
go	go	go-U	Ua
fíochmhar	fíochmhar	fíochmhar-A	Aqp
agus	agus	agus-C	Cc
rith	rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
i	i	i-S	Sp
dtreo	dtreo	treo-N	Ncmsc
Shetanta	Shetanta	Setanta-N	Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
fearg	fearg	fearg-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcú	gcú	cú-N	Ncmsc
ach	ach	ach-C	Cs
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
eagla	eagla	eagla-N	Ncfsc
ar	ar	ar-S	Sp
Shetanta	Shetanta	Setanta-N	Npmsc
roimhe	roimhe	roimh-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
smaoineamh	smaoineamh	smaoineamh-N	Ncmsc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Thaitin	Thaitin	taitin-V	Vmis
an	an	an-T	Td-s
iomáint	iomáint	iomáint-N	Ncfsm
go	go	go-U	Ua
mór	mór	mór-A	Aqp
leis	leis	le-P	Pr3ms
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
camán	camán	camán-N	Ncmsc
agus	agus	agus-C	Cc
sliotar	sliotar	sliotar-N	Ncmsc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Bhuail	Bhuail	buail-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
sliotar	sliotar	sliotar-N	Ncmsc
go	go	go-U	Ua
crua	crua	crua-A	Aqp
agus	agus	agus-C	Cc
chuaigh	chuaigh	téigh-V	Vmis
sé	sé	sé-P	Pp3msn
díreach	díreach	díreach-R	Rg
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
mbéal	mbéal	béal-N	Ncmsc
an	an	an-T	Td-s
chú	chú	cú-N	Ncmsg
.	.	.-F	Fe
Thit	Thit	tit-V	Vmis
an	an	an-T	Td-s
cú	cú	cú-N	Ncmsc
go	go	go-S	Sp
talamh	talamh	talamh-N	Ncfsc
agus	agus	agus-C	Cc
fuair	fuair	faigh-V	Vmis
sé	sé	sé-P	Pp3msn
bás	bás	bás-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
Culann	Culann	Culann-N	Npmsc
sásta	sásta	sásta-A	Aqc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
a	a	a-D	Dp3
chú	chú	cú-N	Ncmsc
marbh	marbh	marbh-A	Aq-msc
ach	ach	ach-C	Cs
thuig	thuig	tuig-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
Setanta	Setanta	Setanta-N	Npmsc
ina	ina	i-S	Spp-s
bhuachaill	bhuachaill	buachaill-N	Ncmsc
cróga	cróga	cróga-A	Aqp
láidir	láidir	láidir-A	Aqp
D'iarr	D'iarr	iarr-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
Shetanta	Shetanta	Setanta-N	Npmsc
bheith	bheith	bí-N	Nv
mar	mar	mar-S	Sp
gharda	gharda	garda-N	Ncmsc
aige	aige	ag-P	Pr3ms
agus	agus	agus-C	Cc
is	is	is-W	Wpri
mar	mar	mar-S	Sp
sin	sin	sin-P	Pd
a	a	a-Q	Q-r
fuair	fuair	faigh-V	Vmis
Setanta	Setanta	Setanta-N	Npmsc
an	an	an-T	Td-s
t-ainm	t-ainm	ainm-N	Ncmsc
Cú	Cú	cú-N	Ncmsc
Chulainn	Chulainn	Culann-N	Npm-g
.	.	.-F	Fe
