Fadó	Fadó	fadó-R	Rt
fadó	fadó	fadó-R	Rt
in	in	i-S	Sp
Éirinn	Éirinn	Éire-N	Npfsd
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
fear	fear	fear-N	Ncmsc
ann	ann	ann-R	Rl
darbh	darbh	is-W	Wpsi
ainm	ainm	ainm-N	Ncmsc
Oisín	Oisín	Oisín-N	Npmsc
.	.	.-F	Fe
Fionn	Fionn	Fionn-N	Npmsc
an	an	an-T	Td-s
t-ainm	t-ainm	ainm-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ar	ar	ar-S	Sp
a	a	a-D	Dp3
athair	athair	athair-N	Ncmsc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
Fianna	Fianna	Fiann-N	Ncfpc
an	an	an-T	Td-s
t-ainm	t-ainm	ainm-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ar	ar	ar-S	Sp
na	na	na-T	Td-p
saighdiúirí	saighdiúirí	saighdiúir-N	Ncmpc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
acu	acu	ag-P	Pr3-p
.	.	.-F	Fe
Lá	Lá	lá-N	Ncmsc
amháin	amháin	amháin-A	Aqp
,	,	,-F	Fi
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
go	go	go-U	Ua
léir	léir	léir-A	Aqp
amuigh	amuigh	amuigh-R	Rl
ag	ag	ag-S	Sp
fiach	fiach	fiach-N	Nv
,	,	,-F	Fi
chonaic	chonaic	feic-V	Vmis
siad	siad	siad-P	Pp3-pn
capall	capall	capall-N	Ncmsc
bán	bán	bán-A	Aq-msc
agus	agus	agus-C	Cc
cailín	cailín	cailín-N	Ncmsc
álainn	álainn	álainn-A	Aq-msc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Niamh	Niamh	Niamh-N	Npfsc
an	an	an-T	Td-s
t-ainm	t-ainm	ainm-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ar	ar	ar-S	Sp
an	an	an-T	Td-s
chailín	chailín	cailín-N	Ncmsc
.	.	.-F	Fe
Chomh	Chomh	chomh-R	Ri
luath	luath	luath-A	Aqp
agus	agus	agus-C	Cc
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
Oisín	Oisín	Oisín-N	Npmsc
Niamh	Niamh	Niamh-N	Npfsc
thit	thit	tit-V	Vmis
sé	sé	sé-P	Pp3msn
i	i	i-S	Sp
ngrá	ngrá	grá-N	Ncmsc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Niamh	Niamh	Niamh-N	Npfsc
ina	ina	i-S	Spp-s
cónaí	cónaí	cónaí-N	Ncmsc
in	in	i-S	Sp
áit	áit	áit-N	Ncfsc
darbh	darbh	is-W	Wpsi
ainm	ainm	ainm-N	Ncmsc
Tír na nÓg	Tír na nÓg	Tír_na_nÓg-N	Ncfsc
.	.	.-F	Fe
Áit	Áit	áit-N	Ncfsc
an-speisialta	an-speisialta	speisialta-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
mar	mar	mar-C	Cs
níor	níor	níor-Q	Qn-s
éirigh	éirigh	éirigh-V	Vmis---n
daoine	daoine	duine-N	Ncmpc
sean	sean	sean-A	Aqp
ansin	ansin	ansin-R	Rt
.	.	.-F	Fe
D'iarr	D'iarr	iarr-V	Vmis
Niamh	Niamh	Niamh-N	Npfsc
ar	ar	ar-S	Sp
Oisín	Oisín	Oisín-N	Npmsc
dul	dul	téigh-N	Nv
go	go	go-S	Sp
Tír na nÓg	Tír na nÓg	Tír_na_nÓg-N	Ncfsc
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Léim	Léim	léim-V	Vmis
Oisín	Oisín	Oisín-N	Npmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcapall	gcapall	capall-N	Ncmsc
le	le	le-S	Sp
Niamh	Niamh	Niamh-N	Npfsc
agus	agus	agus-C	Cc
d'imigh	d'imigh	imigh-V	Vmis
siad	siad	siad-P	Pp3-pn
leo	leo	le-P	Pr3-p
go	go	go-S	Sp
Tír na nÓg	Tír na nÓg	Tír_na_nÓg-N	Ncfsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
Fionn	Fionn	Fionn-N	Npmsc
ná	ná	ná-C	Cc
na	na	na-T	Td-p
Fianna	Fianna	Fiann-N	Ncfpc
Oisín	Oisín	Oisín-N	Npmsc
arís	arís	arís-R	Rg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Oisín	Oisín	Oisín-N	Npmsc
agus	agus	agus-C	Cc
Niamh	Niamh	Niamh-N	Npfsc
an-sásta	an-sásta	sásta-A	Aqp
i	i	i-S	Sp
dTír na nÓg	dTír na nÓg	Tír_na_nÓg-N	Ncfsc
ar	ar	ar-S	Sp
deireadh	deireadh	deireadh-N	Ncmsc
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
Oisín	Oisín	Oisín-N	Npmsc
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
dul	dul	téigh-N	Nv
ar ais	ar ais	ar_ais-R	Rd
abhaile	abhaile	abhaile-R	Rd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
faoi	faoi	faoi-S	Sp
bhrón	bhrón	brón-N	Ncmsc
mór	mór	mór-A	Aq-msc
.	.	.-F	Fe
Theastaigh	Theastaigh	teastaigh-V	Vmis
uaidh	uaidh	ó-P	Pr3ms
a	a	a-D	Dp3
chairde	chairde	cara-N	Ncmpc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
Fianna	Fianna	Fiann-N	Ncfpc
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
arís	arís	arís-R	Rg
.	.	.-F	Fe
Léim	Léim	léim-V	Vmis
sé	sé	sé-P	Pp3msn
suas	suas	suas-R	Rd
ar	ar	ar-S	Sp
an	an	an-T	Td-s
gcapall	gcapall	capall-N	Ncmsc
bán	bán	bán-A	Aq-msc
agus	agus	agus-C	Cc
d'imigh	d'imigh	imigh-V	Vmis
sé	sé	sé-P	Pp3msn
leis	leis	le-P	Pr3ms
abhaile	abhaile	abhaile-R	Rd
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
d'fhill	d'fhill	fill-V	Vmis
Oisín	Oisín	Oisín-N	Npmsc
abhaile	abhaile	abhaile-R	Rd
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
iontas	iontas	iontas-N	Ncmsc
an	an	an-T	Td-s
domhain	domhain	domhan-N	Ncmsg
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
aithin	aithin	aithin-V	Vmis---n
sé	sé	sé-P	Pp3msn
duine	duine	duine-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
athair	athair	athair-N	Ncmsc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
Fianna	Fianna	Fiann-N	Ncfpc
go	go	go-U	Ua
léir	léir	léir-A	Aqp
marbh	marbh	marbh-A	Aqp
le	le	le-S	Sp
fada	fada	fada-A	Aqp
.	.	.-F	Fe
Fuair	Fuair	faigh-V	Vmis
sé	sé	sé-P	Pp3msn
amach	amach	amach-R	Rd
ansin	ansin	ansin-R	Rt
gur	gur	gur-Q	Q--s
chaith	chaith	caith-V	Vmis
sé	sé	sé-P	Pp3msn
trí	trí	trí-M	Mc
chéad	chéad	céad-N	Ncmsc
bliain	bliain	bliain-N	Ncfsc
i	i	i-S	Sp
dTír na nÓg	dTír na nÓg	Tír_na_nÓg-N	Ncfsc
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
sé	sé	sé-P	Pp3msn
anuas	anuas	anuas-R	Rd
den	den	de-S	Spa-s
chapall	chapall	capall-N	Ncmsc
,	,	,-F	Fi
ach	ach	ach-C	Cs
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuir	chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
chos	chos	cos-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
talamh	talamh	talamh-N	Ncfsc
,	,	,-F	Fi
d'éirigh	d'éirigh	éirigh-V	Vmis
sé	sé	sé-P	Pp3msn
an-sean	an-sean	sean-A	Aqp
go	go	go-U	Ua
tobann	tobann	tobann-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
sheanduine	sheanduine	seanduine-N	Ncmsc
anois	anois	anois-R	Rt
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
breis	breis	breis-N	Ncfsc
is	is	agus-C	Cc
trí	trí	trí-M	Mc
chéad	chéad	céad-N	Ncmsc
bliain	bliain	bliain-N	Ncfsc
d'	d'	de-S	Sp
aois	aois	aois-N	Ncfsc
agus	agus	agus-C	Cc
fuair	fuair	faigh-V	Vmis
sé	sé	sé-P	Pp3msn
bás	bás	bás-N	Ncmsc
.	.	.-F	Fe
