Fadó	Fadó	fadó-R	Rt
fadó	fadó	fadó-R	Rt
in	in	i-S	Sp
Éirinn	Éirinn	Éire-N	Npfsd
bhí	bhí	bí-V	Vmis
rí	rí	rí-N	Ncmsc
ann	ann	ann-R	Rl
darbh	darbh	dar-W	Wpsi
ainm	ainm	ainm-N	Ncmsc
Lear	Lear	Lear-N	Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
ceathrar	ceathrar	ceathrar-N	Ncmsc
páistí	páistí	páiste-N	Ncmpg
aige	aige	ag-P	Pr3ms
;	;	;-F	Fi
Conn	Conn	Conn-N	Npmsc
,	,	,-F	Fi
Fionnuala	Fionnuala	Fionnuala-N	Npmsc
,	,	,-F	Fi
Fiachra	Fiachra	Fiachra-N	Npmsc
agus	agus	agus-C	Cc
Aodh	Aodh	Aodh-N	Npmsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
óg	óg	óg-A	Aq--pg
,	,	,-F	Fi
fuair	fuair	faigh-V	Vmis
a	a	a-D	Dp3
mamaí	mamaí	mamaí-N	Ncfsc
bás	bás	bás-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
brón	brón	brón-N	Ncmsc
an	an	an-T	Td-s
domhain	domhain	domhan-N	Ncmsg
orthu	orthu	ar-P	Pr3-p
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
,	,	,-F	Fi
phós	phós	pós-V	Vmis
Lear	Lear	Lear-N	Npmsc
bean	bean	bean-N	Ncfsc
eile	eile	eile-D	Dd
.	.	.-F	Fe
Aoife	Aoife	Aoife-N	Npfsc
ab	ab	is-W	Wsri
ainm	ainm	ainm-N	Ncmsc
di	di	do-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
grá	grá	grá-N	Ncmsc
aici	aici	ag-P	Pr3fs
do	do	do-S	Sp
Lear	Lear	Lear-N	Npmsc
ach	ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
fuath	fuath	fuath-N	Ncmsc
aici	aici	ag-P	Pr3fs
do	do	do-S	Sp
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
.	.	.-F	Fe
Lá	Lá	lá-N	Ncmsc
amháin	amháin	amháin-A	Aqp
,	,	,-F	Fi
chuaigh	chuaigh	téigh-V	Vmis
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
ar	ar	ar-S	Sp
thuras	thuras	turas-N	Ncmsc
le	le	le-S	Sp
hAoife	hAoife	Aoife-N	Npfsc
go dtí	go dtí	go_dtí-S	Spc
loch	loch	loch-N	Ncmsc
in aice	in aice	in_aice-S	Spc
leo	leo	le-P	Pr3-p
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
plean	plean	plean-N	Ncmsc
aici	aici	ag-P	Pr3fs
.	.	.-F	Fe
D'úsáid	D'úsáid	úsáid-V	Vmis
sí	sí	sí-P	Pp3fsn
slat	slat	slat-N	Ncfsc
draíochta	draíochta	draíocht-N	Ncfsg
agus	agus	agus-C	Cc
rinne	rinne	déan-V	Vmis
sí	sí	sí-P	Pp3fsn
ealaí	ealaí	eala-N	Ncfpc
de	de	de-S	Sp
na	na	na-T	Td-p
páistí	páistí	páiste-N	Ncmpc
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
ag	ag	ag-S	Sp
súgradh	súgradh	súgradh-N	Nv
san	san	i-S	Spa-s
uisce	uisce	uisce-N	Ncmsc
.	.	.-F	Fe
Bheadh	Bheadh	bí-V	Vmc
orthu	orthu	ar-P	Pr3-p
900	900	900-M	Mn
bliain	bliain	bliain-N	Ncfsc
a	a	a-U	U
chaitheamh	chaitheamh	caith-N	Nv
mar	mar	mar-S	Sp
ealaí	ealaí	eala-N	Ncfpc
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
bheadh	bheadh	bí-V	Vmc----n
deireadh	deireadh	deireadh-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
ngeis	ngeis	geis-N	Ncfsc
go dtí	go dtí	go_dtí-S	Spc
go	go	go-Q	Q
gcloisfidís	gcloisfidís	clois-V	Vmc-3p
clog	clog	clog-N	Ncmsc
ag	ag	ag-S	Sp
bualadh	bualadh	buail-N	Nv
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
chuala	chuala	clois-V	Vmis
Lear	Lear	Lear-N	Npmsc
cad	cad	cad-P	Pq
a	a	a-Q	Q-r
rinne	rinne	déan-V	Vmis
Aoife	Aoife	Aoife-N	Npfsc
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
an-fheargach	an-fheargach	feargach-A	Aqp
léi	léi	le-P	Pr3fs
.	.	.-F	Fe
Rinne	Rinne	déan-V	Vmis
sé	sé	sé-P	Pp3msn
éan	éan	éan-N	Ncmsc
gránna	gránna	gránna-A	Aqp
di	di	do-P	Pr3fs
agus	agus	agus-C	Cc
d'eitil	eitil	eitil-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
shiúl	shiúl	siúl-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
na	na	na-T	Td-p
healaí	healaí	eala-N	Ncfpc
in ann	in ann	in_ann-S	Spc
labhairt	labhairt	labhair-N	Nv
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
Lear	Lear	Lear-N	Npmsc
chuig	chuig	chuig-S	Sp
an	an	an-T	Td-s
loch	loch	loch-N	Ncmsc
bhí	bhí	bí-V	Vmis
iontas	iontas	iontas-N	Ncmsc
air	air	ar-P	Pr3ms
.	.	.-F	Fe
D'inis	D'inis	inis-V	Vmis
siad	siad	siad-P	Pp3-pn
gach	gach	gach-D	Dq
rud	rud	rud-N	Ncmsc
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
Thóg	Thóg	tóg-V	Vmis
Lear	Lear	Lear-N	Npmsc
teach	teach	teach-N	Ncmsc
cóngarach	cóngarach	cóngarach-A	Aq-msc
don	don	do-S	Spa-s
loch	loch	loch-N	Ncmsc
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
sé	sé	sé-P	Pp3msn
aire	aire	aire-N	Ncfsc
do	do	do-S	Sp
na	na	na-T	Td-p
healaí	healaí	eala-N	Ncfpc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
fuair	fuair	faigh-V	Vmis
Lear	Lear	Lear-N	Npmsc
bás	bás	bás-N	Ncmsc
cúpla	cúpla	cúpla-D	Dq
bliain	bliain	bliain-N	Ncfsc
tar éis	tar éis	tar_éis-S	Spc
sin	sin	sin-P	Pd
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
900	900	900-M	Mn
bliain	bliain	bliain-N	Ncfsc
chuala	chuala	clois-V	Vmis
na	na	na-T	Td-p
healaí	healaí	eala-N	Ncfpc
clog	clog	clog-N	Ncmsc
an	an	an-T	Td-s
tséipéil	tséipéil	séipéal-N	Ncmsg
ag	ag	ag-S	Sp
bualadh	bualadh	buail-N	Nv
agus	agus	agus-C	Cc
d'athraigh	d'athraigh	athraigh-V	Vmis
siad	siad	siad-P	Pp3-pn
ar ais	ar ais	ar_ais-R	Rd
.	.	.-F	Fe
Ní	Ní	Ní-W	WN
ealaí	ealaí	eala-N	Ncfpc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
iontu	iontu	i-P	Pr3-p
níos	níos	níos-U	Uc
mó	mó	mór-A	Aqc
ach	ach	ach-S	Sp
daoine	daoine	duine-N	Ncmpc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
siad	siad	siad-P	Pp3-pn
an-sean	an-sean	sean-A	Aqp
agus	agus	agus-C	Cc
fuair	fuair	faigh-V	Vmis
siad	siad	siad-P	Pp3-pn
bás	bás	bás-N	Ncmsc
go	go	go-U	Ua
gairid	gairid	gairid-A	Aqp
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-D	Dd
.	.	.-F	Fe
