Fadó	Fadó	fadó-R	Rt
in	in	i-S	Sp
Éirinn	Éirinn	Éire-N	Npfsd
bhí	bhí	bí-V	Vmis
fear	fear	fear-N	Ncmsc
ann	ann	ann-R	Rl
darbh	darbh	dar-W	Wpsi
ainm	ainm	ainm-N	Ncmsc
Finnéagas	Finnéagas	Finnéagas-N	Npmsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Fionn	Fionn	Fionn-N	Npmsc
Mac	Mac	Mac-U	Up
Cumhaill	Cumhaill	Cumhaill-N	Npmsg
óg	óg	óg-A	Aq-msc
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
an-chairdiúil	an-chairdiúil	cairdiúil-A	Aqp
le	le	le-S	Sp
Finnéagas	Finnéagas	Finnéagas-N	Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Finnéagas	Finnéagas	Finnéagas-N	Npmsc
an-chliste	an-chliste	cliste-A	Aqp
ach	ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
gach	gach	gach-D	Dq
rud	rud	rud-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
domhan	domhan	domhan-N	Ncmsc
bheith	bheith	bí-N	Nv
ar	ar	ar-S	Sp
eolas	eolas	eolas-N	Ncmsc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
iasc	iasc	iasc-N	Ncmsc
draíochta	draíochta	draíocht-N	Ncfsg
san	san	i-S	Spa-s
abhainn	abhainn	abhainn-N	Ncfsc
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
gach	gach	gach-D	Dq
rud	rud	rud-N	Ncmsc
ar	ar	ar-S	Sp
eolas	eolas	eolas-N	Ncmsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
iasc	iasc	iasc-N	Ncmsc
seo	seo	seo-D	Dd
.	.	.-F	Fe
An	An	an-T	Td-s
Bradán	Bradán	bradán-N	Ncmsc
Feasa	Feasa	fios-N	Ncmsg
an	an	an-T	Td-s
t-ainm	t-ainm	ainm-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Theastaigh	Theastaigh	teastaigh-V	Vmis
ó	ó	ó-S	Sp
Fhinnéagas	Fhinnéagas	finnéagas-N	Npmsc
an	an	an-T	Td-s
Bradán	Bradán	bradán-N	Ncmsc
Feasa	Feasa	fios-N	Ncmsg
a	a	a-U	U
fháil	fháil	faigh-N	Nv
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
a	a	a-U	U
ithe	ithe	ith-N	Nv
.	.	.-F	Fe
Lá	Lá	lá-N	Ncmsc
amháin	amháin	amháin-A	Aqp
bhí	bhí	bí-V	Vmis
Finnéagas	Finnéagas	Finnéagas-N	Npmsc
ag	ag	ag-S	Sp
iascaireacht	iascaireacht	iascaire-N	Nv-----n
agus	agus	agus-C	Cc
rug	rug	beir-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mBradán	mBradán	bradán-N	Ncmsc
Feasa	Feasa	fios-N	Ncmsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
an-sásta	an-sásta	sásta-A	Aqp
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
Las	Las	las-V	Vmis
sé	sé	sé-P	Pp3msn
tine	tine	tine-N	Ncfsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
iasc	iasc	iasc-N	Ncmsc
a	a	a-U	U
chócaráil	chócaráil	cócaráil-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ag	ag	ag-S	Sp
tnúth	tnúth	tnúth-N	Nv
go	go	go-U	Ua
mór	mór	mór-A	Aqp
leis	leis	le-S	Sp
an	an	an-T	Td-s
mBradán	mBradán	bradán-N	Ncmsc
Feasa	Feasa	fios-N	Ncmsg
a	a	a-U	U
ithe	ithe	ith-N	Nv
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
sé	sé	sé-P	Pp3msn
amach	amach	amach-R	Rd
le	le	le-S	Sp
huisce	huisce	uisce-N	Ncmsc
a	a	a-U	U
fháil	fháil	faigh-N	Nv
agus	agus	agus-C	Cc
d'fhág	d'fhág	fág-V	Vmis
sé	sé	sé-P	Pp3msn
Fionn	Fionn	Fionn-N	Npmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
mBradán	mBradán	bradán-N	Ncmsc
Feasa	Feasa	fios-N	Ncmsg
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
cead	cead	cead-N	Ncmsc
aige	aige	ag-P	Pr3ms
é	é	é-P	Pp3ms
a	a	a-U	U
ithe	ithe	ith-N	Nv
!	!	!-F	Fe
Chuir	Chuir	cuir-V	Vmis
Fionn	Fionn	Fionn-N	Npmsc
a	a	a-D	Dp3
ordóg	ordóg	ordóg-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbradán	mbradán	bradán-N	Ncmsc
lena	lena	le-S	Spp-s
fháil	fháil	faigh-N	Nv
amach	amach	amach-R	Rd
an	an	an-Q	Qq
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
réidh	réidh	réidh-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
an	an	an-T	Td-s
bradán	bradán	bradán-N	Ncmsc
an-te	an-te	te-A	Aqp
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
agus	agus	agus-C	Cc
dhóigh	dhóigh	dóigh-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
ordóg	ordóg	ordóg-N	Ncfsc
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
ordóg	ordóg	ordóg-N	Ncfsc
isteach	isteach	isteach-R	Rd
ina	ina	i-S	Spp-s
bhéal	bhéal	béal-N	Ncmsc
láithreach	láithreach	láithreach-R	Rt
.	.	.-F	Fe
Ba	Ba	is-W	Ws
é	é	é-P	Pp3ms
Fionn	Fionn	Fionn-N	Npmsc
an	an	an-T	Td-s
chéad	chéad	céad-M	Mo
duine	duine	duine-N	Ncmsc
a	a	a-Q	Q-r
bhlais	bhlais	blais-V	Vmis
an	an	an-T	Td-s
Bradán	Bradán	bradán-N	Ncmsc
Feasa	Feasa	fios-N	Ncmsg
agus	agus	agus-C	Cc
is	is	is-W	Wpri
ag	ag	ag-S	Sp
Fionn	Fionn	Fionn-N	Npmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
t-eolas	t-eolas	eolas-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
!	!	!-F	Fe
