Tráthnóna	Tráthnóna	tráthnóna-N	Ncmsc
breá	breá	breá-A	Aq-msc
samhraidh	samhraidh	samhradh-N	Ncmsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
scamall	scamall	scamall-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
le	le	le-S	Sp
feiceáil	feiceáil	feic-N	Nv
sa	sa	i-S	Spa-s
spéir	spéir	spéir-N	Ncfsc
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
Lára	Lára	Lára-N	Npfsc
amach	amach	amach-R	Rd
ar	ar	ar-S	Sp
shiúlóid	shiúlóid	siúlóid-N	Ncfsc
chuig	chuig	chuig-S	Sp
an	an	an-T	Td-s
gcoill	gcoill	coill-N	Ncfsc
lena	lena	le-S	Spp-s
madra	madra	madra-N	Ncmsc
Róló	Róló	lá-N	Npmsc
.	.	.-F	Fe
Ba	Ba	is-W	Ws
bhreá	bhreá	breá-A	Aqp
le	le	le-S	Sp
Lára	Lára	Lára-N	Npfsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
amuigh	amuigh	amuigh-R	Rl
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
agus	agus	agus-C	Cc
ag	ag	ag-S	Sp
féachaint	féachaint	féach-N	Nv
ar	ar	ar-S	Sp
na	na	na-T	Td-p
huain	huain	uan-N	Ncmpc
óga	óga	óg-A	Aq-pc
ag	ag	ag-S	Sp
rith	rith	rith-N	Nv
trí	trí	trí-S	Sp
na	na	na-T	Td-p
páirceanna	páirceanna	páirc-N	Ncfpc
.	.	.-F	Fe
Ba	Ba	is-W	Ws
bhreá	bhreá	breá-A	Aqp
le	le	le-S	Sp
Róló	Róló	lá-N	Npmsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
ag	ag	ag-S	Sp
rith	rith	rith-N	Nv
i ndiaidh	i ndiaidh	i_ndiaidh-S	Spc
na	na	na-T	Td-p
bhféileacán	bhféileacán	féileacán-N	Ncmpg
daite	daite	daite-A	Aqp
agus	agus	agus-C	Cc
iad	iad	iad-P	Pp3-p
ag	ag	ag-S	Sp
eitilt	eitilt	eitil-N	Nv
timpeall	timpeall	timpeall-S	Sp
na	na	na-T	Td-p
mbláthanna	mbláthanna	bláth-N	Ncmpg
.	.	.-F	Fe
Go	Go	go-U	Ua
tobann	tobann	tobann-A	Aqp
,	,	,-F	Fi
thosaigh	thosaigh	tosaigh-V	Vmis
Róló	Róló	lá-N	Npmsc
ag	ag	ag-S	Sp
tafann	tafann	tafainn-N	Nv
mar	mar	mar-C	Cs
chonaic	chonaic	feic-V	Vmis
sé	sé	sé-P	Pp3msn
rud	rud	rud-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
ag	ag	ag-S	Sp
bogadh	bogadh	bog-N	Nv
sa	sa	i-S	Spa-s
choill	choill	coill-N	Ncfsc
.	.	.-F	Fe
Coinín	Coinín	Coinín-N	Npmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Rith	Rith	rith-V	Vmis
Róló	Róló	lá-N	Npmsc
ar	ar	ar-S	Sp
shiúl	shiúl	siúl-N	Nv
ó	ó	ó-S	Sp
Lára	Lára	Lára-N	Npfsc
agus	agus	agus-C	Cc
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
choill	choill	coill-N	Ncfsc
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Ghlaoigh	Ghlaoigh	glaoigh-V	Vmis
Lára	Lára	Lára-N	Npfsc
air	air	ar-P	Pr3ms
ach	ach	ach-C	Cs
níor	níor	níor-Q	Qn-s
thug	thug	tabhair-V	Vmis---n
sé	sé	sé-P	Pp3msn
aird	aird	aird-N	Ncfsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
uirthi	uirthi	ar-P	Pr3fs
agus	agus	agus-C	Cc
rith	rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
aghaidh	aghaidh	aghaidh-N	Ncfsc
.	.	.-F	Fe
Rith	Rith	rith-V	Vmis
Lára	Lára	Lára-N	Npfsc
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
an	an	an-T	Td-s
mbealach	mbealach	bealach-N	Ncmsc
isteach	isteach	isteach-R	Rd
chuig	chuig	chuig-S	Sp
an	an	an-T	Td-s
gcoill	gcoill	coill-N	Ncfsc
bhuail	bhuail	buail-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
cos	cos	cos-N	Ncfsc
ar	ar	ar-S	Sp
rud	rud	rud-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ina	ina	i-S	Spp-s
luí	luí	luí-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
talamh	talamh	talamh-N	Ncfsc
.	.	.-F	Fe
Thit	Thit	tit-V	Vmis
sí	sí	sí-P	Pp3fsn
agus	agus	agus-C	Cc
ghortaigh	ghortaigh	gortaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
a	a	a-D	Dp3
cos	cos	cos-N	Ncfsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
drochphian	drochphian	pian-N	Ncfsc
ina	ina	i-S	Spp-s
cos	cos	cos-N	Ncfsc
.	.	.-F	Fe
Rinne	Rinne	déan-V	Vmis
sí	sí	sí-P	Pp3fsn
iarracht	iarracht	iarracht-N	Ncfsc
seasamh	seasamh	seas-N	Nv
ach	ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
róphianmhar	róphianmhar	pianmhar-A	Aqp
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sí	sí	sí-P	Pp3fsn
in ann	in ann	in_ann-S	Spc
bogadh	bogadh	bog-N	Nv
.	.	.-F	Fe
Ghlaoigh	Ghlaoigh	glaoigh-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
Róló	Róló	lá-N	Npmsc
agus	agus	agus-C	Cc
sa	sa	i-S	Spa-s
deireadh	deireadh	deireadh-N	Ncmsc
tháinig	tháinig	tar-V	Vmis
Róló	Róló	lá-N	Npmsc
ar ais	ar ais	ar_ais-R	Rd
chuici	chuici	chuig-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Lára	Lára	Lára-N	Npfsc
ag	ag	ag-S	Sp
éirí	éirí	éirigh-N	Nv
imníoch	imníoch	imníoch-A	Aqp
mar	mar	mar-C	Cs
bhí	bhí	bí-V	Vmis
an	an	an-T	Td-s
ghrian	ghrian	grian-N	Ncfsc
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
faoi	faoi	faoi-P	Pr3ms
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
ag	ag	ag-S	Sp
Mamaí	Mamaí	mamaí-N	Ncfsc
cá	cá	cá-R	Rq
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
sí	sí	sí-P	Pp3fsn
ag	ag	ag-S	Sp
caoineadh	caoineadh	caoin-N	Nv
.	.	.-F	Fe
Leis	Leis	le-S	Sp
sin	sin	sin-P	Pd
,	,	,-F	Fi
thosaigh	thosaigh	tosaigh-V	Vmis
Róló	Róló	lá-N	Npmsc
ag	ag	ag-S	Sp
tafann	tafann	tafainn-N	Nv
agus	agus	agus-C	Cc
rith	rith	rith-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
shiúl	shiúl	siúl-N	Nv
arís	arís	arís-R	Rg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
eagla	eagla	eagla-N	Ncfsc
ar	ar	ar-S	Sp
Lára	Lára	Lára-N	Npfsc
agus	agus	agus-C	Cc
í	í	í-P	Pp3fs
sa	sa	i-S	Spa-s
choill	choill	coill-N	Ncfsc
léi	léi	le-P	Pr3fs
féin	féin	féin-P	Px
.	.	.-F	Fe
Go	Go	go-U	Ua
gearr	gearr	gearr-A	Aqp
ina	ina	i-S	Spp-s
dhiaidh	dhiaidh	diaidh-N	Ns-s
sin	sin	sin-P	Pd
,	,	,-F	Fi
cheap	cheap	ceap-V	Vmis
Lára	Lára	Lára-N	Npfsc
gur	gur	gur-Q	Q--s
chuala	chuala	clois-V	Vmis
sí	sí	sí-P	Pp3fsn
duine	duine	duine-N	Ncmsc
ag	ag	ag-S	Sp
glaoch	glaoch	glaoigh-N	Nv
agus	agus	agus-C	Cc
madra	madra	madra-N	Ncmsc
ag	ag	ag-S	Sp
tafann	tafann	tafainn-N	Nv
.	.	.-F	Fe
'	'	'-F	Fa
Chabhraigh	Chabhraigh	cabhraigh-V	Vmis
liom	liom	le-P	Pr1-s
!	!	!-F	Fe
'	'	'-F	Fa
a	a	a-U	Uv
scread	scread	scread-N	Ncfsv
Lára	Lára	Lára-N	Npfsc
agus	agus	agus-C	Cc
d'éist	d'éist	éist-V	Vmis
sí	sí	sí-P	Pp3fsn
go	go	go-U	Ua
cúramach	cúramach	cúramach-A	Aqp
leis	leis	le-S	Sp
an	an	an-T	Td-s
nguth	nguth	guth-N	Ncmsc
eile	eile	eile-D	Dd
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
glaoch	glaoch	glaoigh-N	Nv
.	.	.-F	Fe
Guth	Guth	guth-N	Ncmsc
a	a	a-D	Dp3
Mamaí	Mamaí	mamaí-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
!	!	!-F	Fe
Ghlaoigh	Ghlaoigh	glaoigh-V	Vmis
Lára	Lára	Lára-N	Npfsc
arís	arís	arís-R	Rg
agus	agus	agus-C	Cc
arís	arís	arís-R	Rg
eile	eile	eile-D	Dd
.	.	.-F	Fe
Níorbh	Níorbh	is-W	Ws-in
fhada	fhada	fada-A	Aqp
go	go	go-Q	Q
bhfaca	bhfaca	feic-V	Vmis---d
sí	sí	sí-P	Pp3fsn
Mamaí	Mamaí	mamaí-N	Ncfsc
agus	agus	agus-C	Cc
cé	cé	cé-P	Pq
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
in aice	in aice	in_aice-S	Spc
le	le	le-S	Sp
Mamaí	Mamaí	mamaí-N	Ncfsc
ach	ach	ach-S	Sp
Róló	Róló	lá-N	Npmsc
?	?	?-F	Fq
D'imigh	D'imigh	imigh-V	Vmis
Róló	Róló	lá-N	Npmsc
abhaile	abhaile	abhaile-R	Rd
le	le	le-S	Sp
Mamaí	Mamaí	mamaí-N	Ncfsc
Lára	Lára	Lára-N	Npf-g
a	a	a-U	U
fháil	fháil	faigh-N	Nv
!	!	!-F	Fe
D'inis	D'inis	inis-V	Vmis
Lára	Lára	Lára-N	Npfsc
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
faoi	faoi	faoi-S	Sp
Róló	Róló	lá-N	Npmsc
agus	agus	agus-C	Cc
faoin	faoin	faoi-S	Spa-s
gcoinín	gcoinín	coinín-N	Ncmsc
do	do	do-S	Sp
Mhamaí	Mhamaí	mamaí-N	Ncfsc
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
Mamaí	Mamaí	mamaí-N	Ncfsc
glaoch	glaoch	glaoigh-N	Ncmsc
ar	ar	ar-S	Sp
Dhaidí	Dhaidí	daidí-N	Ncmsc
agus	agus	agus-C	Cc
tháinig	tháinig	tar-V	Vmis
sé	sé	sé-P	Pp3msn
ina	ina	i-S	Spp-s
charr	charr	carr-N	Ncmsc
le	le	le-S	Sp
Lára	Lára	Lára-N	Npfsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
chuig	chuig	chuig-S	Sp
an	an	an-T	Td-s
dochtúir	dochtúir	dochtúir-N	Ncmsc
.	.	.-F	Fe
'	'	'-F	Fa
Nach	Nach	is-W	Wp-qn
tusa	tusa	tú-P	Pp2-s-e
atá	atá	bí-V	Vmip---r
cliste	cliste	clis-A	Av
?	?	?-F	Fq
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
le	le	le-S	Sp
Róló	Róló	lá-N	Npmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
shroich	shroich	sroich-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
choill	choill	coill-N	Ncfsc
.	.	.-F	Fe
'	'	'-F	Fa
Tá	Tá	bí-V	Vmip
an	an	an-T	Td-s
t-ádh	t-ádh	ádh-N	Ncmsc
orm	orm	ar-P	Pr1-s
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
sé	sé	sé-P	Pp3msn
chomh	chomh	chomh-R	Ri
cliste	cliste	cliste-A	Aqp
sin	sin	sin-D	Dd
,	,	,-F	Fi
'	'	'-F	Fa
arsa	arsa	arsa-V	Vmis
Lára	Lára	Lára-N	Npfsc
'	'	'-F	Fa
agus	agus	agus-C	Cc
as	as	as-S	Sp
seo	seo	seo-P	Pd
amach	amach	amach-R	Rd
ní	ní	ní-Q	Qn
rachaidh	rachaidh	téigh-V	Vmif
mé	mé	mé-P	Pp1-s
áit	áit	áit-N	Ncfsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
eile	eile	eile-D	Dd
liom	liom	le-P	Pr1-s
féin	féin	féin-P	Px
gan	gan	gan-S	Sp
Róló	Róló	lá-N	Npmsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
liom	liom	le-P	Pr1-s
!	!	!-F	Fe
'	'	'-F	Fa
'	'	'-F	Fa
Ach	Ach	ach-C	Cs
is	is	agus-W	Wp-i
cuma	cuma	cuma-N	Ncfsc
cé	cé	cé-C	Cs
chomh	chomh	chomh-R	Ri
cliste	cliste	cliste-A	Aqp
is	is	agus-C	Cc
atá	atá	bí-V	Vmip---r
madra	madra	madra-N	Ncmsc
,	,	,-F	Fi
níor	níor	is-W	Ws-in
chóir	chóir	cóir-A	Aqp
duit	duit	do-P	Pr2-s
dul	dul	dul-N	Nv
áit	áit	áit-N	Ncfsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
leat	leat	le-P	Pr2-s
féin	féin	féin-P	Px
in	in	i-S	Sp
aon	aon	aon-D	Dq
chor	chor	cor-N	Ncmsc
'	'	'-F	Fa
,	,	,-F	Fi
arsa	arsa	arsa-V	Vmis
Daidí	Daidí	daidí-N	Ncmsc
.	.	.-F	Fe
