Fadó	Fadó	fadó-R	Rt
fadó	fadó	fadó-R	Rt
in	in	i-S	Sp
Éirinn	Éirinn	Éire-N	Npfsd
bhí	bhí	bí-V	Vmis
rí	rí	rí-N	Ncmsc
an-tábhachtach	an-tábhachtach	tábhachtach-A	Aqp
ann	ann	ann-R	Rl
darbh	darbh	dar-W	Wpsi
ainm	ainm	ainm-N	Ncmsc
Conchúr	Conchúr	Conchúr-N	Npmsc
Mac	Mac	Mac-U	Up
Neasa	Neasa	Neasa-N	Npfsc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
seoda	seoda	seod-N	Ncmpc
luachmhara	luachmhara	luachmhar-A	Aq--pc
aige	aige	ag-P	Pr3ms
.	.	.-F	Fe
Ardrí	Ardrí	ardrí-N	Ncmsc
Uladh	Uladh	Uladh-N	Npmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
cónaí	cónaí	cónaí-N	Ncmsc
air	air	ar-P	Pr3ms
in	in	i-S	Sp
Eamhain	Eamhain	Eamhain-N	Npmsc
Mhacha	Mhacha	Macha-N	Npmsg
,	,	,-F	Fi
cóngarach	cóngarach	cóngarach-A	Aqp
do	do	do-S	Sp
chathair	chathair	cathair-N	Ncfsc
Ard Mhacha	Ard Mhacha	Ard_Mhacha-N	Npmsg
sa	sa	i-S	Spa-s
lá	lá	lá-N	Ncmsc
atá	atá	bí-V	Vmip---r
inniu	inniu	inniu-R	Rt
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Lá	Lá	lá-N	Ncmsc
amháin	amháin	amháin-A	Aqp
,	,	,-F	Fi
chuala	chuala	clois-V	Vmis
Conchúr	Conchúr	Conchúr-N	Npmsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
plean	plean	plean-N	Ncmsc
ag	ag	ag-S	Sp
daoine	daoine	duine-N	Ncmpc
a	a	a-D	Dp3
chuid	chuid	cuid-N	Ncfsc
seod	seod	seod-N	Ncmsc
a	a	a-U	U
ghoid	ghoid	goid-N	Nv
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
an-imníoch	an-imníoch	imníoch-A	Aqp
faoi	faoi	faoi-S	Sp
seo	seo	seo-P	Pd
.	.	.-F	Fe
Tamall	Tamall	tamall-N	Ncmsc
tar éis	tar éis	tar_éis-S	Spc
sin	sin	sin-P	Pd
,	,	,-F	Fi
agus	agus	agus-C	Cc
é	é	é-P	Pp3ms
ag	ag	ag-S	Sp
siúl	siúl	siúil-N	Nv
timpeall	timpeall	timpeall-R	Rd
a	a	a-D	Dp3
pháláis	pháláis	pálás-N	Ncmpc
,	,	,-F	Fi
chuala	chuala	clois-V	Vmis
sé	sé	sé-P	Pp3msn
ceoltóir	ceoltóir	ceoltóir-N	Ncmsc
iontach	iontach	iontach-A	Aq-msc
lasmuigh	lasmuigh	lasmuigh-A	Aqp
.	.	.-F	Fe
Thosaigh	Thosaigh	tosaigh-V	Vmis
Conchúr	Conchúr	Conchúr-N	Npmsc
ag	ag	ag-S	Sp
caint	caint	caint-N	Nv-----n
leis	leis	le-P	Pr3ms
agus	agus	agus-C	Cc
d'inis	d'inis	inis-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
dó	dó	do-P	Pr3ms
faoi	faoi	faoi-S	Sp
na	na	na-T	Td-p
daoine	daoine	duine-N	Ncmpc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
a	a	a-D	Dp3
chuid	chuid	cuid-N	Ncfsc
seod	seod	seod-N	Ncmsc
a	a	a-U	U
ghoid	ghoid	goid-N	Nv
.	.	.-F	Fe
D'inis	D'inis	inis-V	Vmis
an	an	an-T	Td-s
ceoltóir	ceoltóir	ceoltóir-N	Ncmsc
dó	dó	do-P	Pr3ms
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
tír	tír	tír-N	Ncfsc
ann	ann	i-P	Pr3ms
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
an-fhada	an-fhada	fada-A	Aqp
ar	ar	ar-S	Sp
shiúl	shiúl	siúl-N	Nv
agus	agus	agus-C	Cc
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
dragan	dragan	dragan-N	Ncmsc
fíochmhar	fíochmhar	fíochmhar-A	Aq-msc
ina	ina	i-S	Spp-s
chónaí	chónaí	cónaí-N	Ncmsc
inti	inti	i-P	Pr3fs
.	.	.-F	Fe
D'fhéadfadh	D'fhéadfadh	féad-V	Vmc
an	an	an-T	Td-s
dragan	dragan	dragan-N	Ncmsc
seo	seo	seo-D	Dd
súil	súil	súil-N	Ncfsc
a	a	a-Q	Q-r
choimeád	choimeád	coimeád-V	Vmis
ar	ar	ar-S	Sp
a	a	a-D	Dp3
chuid	chuid	cuid-N	Ncfsc
seod	seod	seod-N	Ncmpg
b'	b'	is-W	Ws
fhéidir	fhéidir	féidir-N	Ns-s
.	.	.-F	Fe
Cheap	Cheap	ceap-V	Vmis
Conchúr	Conchúr	Conchúr-N	Npmsc
gur	gur	is-W	Wsdi
smaoineamh	smaoineamh	smaoineamh-N	Ncmsc
thar	thar	thar-S	Sp
barr	barr	barr-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
Conchúr	Conchúr	Conchúr-N	Npmsc
saighdiúirí	saighdiúirí	saighdiúir-N	Ncmpc
chuig	chuig	chuig-S	Sp
an	an	an-T	Td-s
tír	tír	tír-N	Ncfsc
sin	sin	sin-D	Dd
agus	agus	agus-C	Cc
thóg	thóg	tóg-V	Vmis
siad	siad	siad-P	Pp3-pn
an	an	an-T	Td-s
dragan	dragan	dragan-N	Ncmsc
ar ais	ar ais	ar_ais-R	Rd
leo	leo	le-P	Pr3-p
go	go	go-S	Sp
hEamhain	hEamhain	hEamhain-N	Nc
Mhacha	Mhacha	Macha-N	Npmsg
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
siad	siad	siad-P	Pp3-pn
ar ais	ar ais	ar_ais-R	Rd
,	,	,-F	Fi
áfach	áfach	áfach-R	Rg
,	,	,-F	Fi
léim	léim	léim-V	Vmis
an	an	an-T	Td-s
dragan	dragan	dragan-N	Ncmsc
isteach	isteach	isteach-R	Rd
i	i	i-S	Sp
loch	loch	loch-N	Ncmsc
beag	beag	beag-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
in aice	in aice	in_aice-S	Spc
leis	leis	le-S	Sp
an	an	an-T	Td-s
bpálás	bpálás	pálás-N	Ncmsc
.	.	.-F	Fe
D'fhan	D'fhan	fan-V	Vmis
an	an	an-T	Td-s
dragan	dragan	dragan-N	Ncmsc
faoin	faoin	faoi-S	Spa-s
uisce	uisce	uisce-N	Ncmsc
an	an	an-T	Td-s
t-am	t-am	am-N	Ncmsc
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Conchúr	Conchúr	Conchúr-N	Npmsc
an-mhíshásta	an-mhíshásta	míshásta-A	Aqp
ach	ach	ach-C	Cs
sheinn	sheinn	seinn-V	Vmis
an	an	an-T	Td-s
ceoltóir	ceoltóir	ceoltóir-N	Ncmsc
tiúin	tiúin	tiúin-N	Ncfsc
ar	ar	ar-S	Sp
a	a	a-D	Dp3
fheadóg	fheadóg	feadóg-N	Ncfsc
stáin	stáin	stán-N	Ncmsg
agus	agus	agus-C	Cc
tháinig	tháinig	tar-V	Vmis
an	an	an-T	Td-s
dragan	dragan	dragan-N	Ncmsc
aníos	aníos	aníos-R	Rd
as	as	as-S	Sp
an	an	an-T	Td-s
loch	loch	loch-N	Ncmsc
agus	agus	agus-C	Cc
shuigh	shuigh	suigh-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-U	Ua
socair	socair	socair-A	Aqp
ar	ar	ar-S	Sp
an	an	an-T	Td-s
talamh	talamh	talamh-N	Ncfsc
.	.	.-F	Fe
Thuig	Thuig	tuig-V	Vmis
Conchúr	Conchúr	Conchúr-N	Npmsc
ansin	ansin	ansin-R	Rt
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
an	an	an-T	Td-s
ceoltóir	ceoltóir	ceoltóir-N	Ncmsc
in ann	in ann	in_ann-S	Spc
an	an	an-T	Td-s
dragan	dragan	dragan-N	Ncmsc
a	a	a-U	U
choimeád	choimeád	coimeád-N	Nv
faoi	faoi	faoi-S	Sp
dhraíocht	dhraíocht	draíocht-N	Ncfsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
gceol	gceol	ceol-N	Ncmsc
álainn	álainn	álainn-A	Aq-msc
a	a	a-Q	Q-r
sheinn	sheinn	seinn-V	Vmis
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
thiocfadh	thiocfadh	tar-V	Vmc----n
sé	sé	sé-P	Pp3msn
amach	amach	amach-R	Rd
as	as	as-S	Sp
an	an	an-T	Td-s
uisce	uisce	uisce-N	Ncmsc
ach	ach	ach-R	Ri
amháin	amháin	amháin-A	Aqp
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chloisfeadh	chloisfeadh	clois-V	Vmc
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
ceol	ceol	ceol-N	Ncmsc
álainn	álainn	álainn-A	Aq-msc
ón	ón	ó-S	Spa-s
gceoltóir	gceoltóir	ceoltóir-N	Ncmsc
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
Conchúr	Conchúr	Conchúr-N	Npmsc
a	a	a-D	Dp3
sheoda	sheoda	sheod-N	Ncmpc
ar	ar	ar-S	Sp
mhuineál	mhuineál	muineál-N	Ncmsc
an	an	an-T	Td-s
dragain	dragain	dragan-N	Ncmsg
agus	agus	agus-C	Cc
d'imigh	d'imigh	imigh-V	Vmis
an	an	an-T	Td-s
dragan	dragan	dragan-N	Ncmsc
leis	leis	le-P	Pr3ms
go	go	go-S	Sp
bun	bun	bun-N	Ncmsc
an	an	an-T	Td-s
locha	locha	loch-N	Ncmsg
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
na	na	na-T	Td-p
blianta	blianta	bliain-N	Ncfpc
thart	thart	thart-R	Rd
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
saol	saol	saol-N	Ncmsc
sona	sona	sona-A	Aqp
sásta	sásta	sásta-A	Aqp
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
gceoltóir	gceoltóir	ceoltóir-N	Ncmsc
sa	sa	i-S	Spa-s
phálás	phálás	pálás-N	Ncmsc
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
ar	ar	ar-S	Sp
an	an	an-T	Td-s
drochuair	drochuair	drochuair-N	Ncfsc
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
timpiste	timpiste	timpiste-N	Ncfsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
gceoltóir	gceoltóir	ceoltóir-N	Ncmsc
agus	agus	agus-C	Cc
fuair	fuair	faigh-V	Vmis
sé	sé	sé-P	Pp3msn
bás	bás	bás-N	Ncmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
duine	duine	duine-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
eile	eile	eile-D	Dd
sa	sa	i-S	Spa-s
tír	tír	tír-N	Ncfsc
in ann	in ann	in_ann-S	Spc
ceol	ceol	ceol-N	Nv-----n
chomh	chomh	chomh-R	Ri
maith	maith	maith-A	Aqp
céanna	céanna	céanna-A	Aqp
a	a	a-U	U
sheinm	sheinm	seinn-N	Nv
,	,	,-F	Fi
agus	agus	agus-C	Cc
dá bharr sin	dá bharr sin	dá_bharr_sin-R	Rg
,	,	,-F	Fi
ní	ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
duine	duine	duine-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
riamh	riamh	riamh-R	Rg
an	an	an-T	Td-s
dragan	dragan	dragan-N	Ncmsc
ná	ná	ná-C	Cc
na	na	na-T	Td-p
seoda	seoda	seod-N	Ncmpc
ó	ó	ó-S	Sp
shin	shin	sin-P	Pd
.	.	.-F	Fe
Tugann	Tugann	tabhair-V	Vmip
daoine	daoine	duine-N	Ncmpc
Loch	Loch	loch-N	Ncmsc
na	na	na-T	Td-p
Séad	Séad	séad-N	Ncmpg
ar	ar	ar-S	Sp
an	an	an-T	Td-s
loch	loch	loch-N	Ncmsc
agus	agus	agus-C	Cc
deir	deir	abair-V	Vmip
siad	siad	siad-P	Pp3-pn
go	go	go-Q	Q
bhfuil	bhfuil	bí-V	Vmip---d
an	an	an-T	Td-s
dragan	dragan	dragan-N	Ncmsc
agus	agus	agus-C	Cc
na	na	na-T	Td-p
seoda	seoda	seod-N	Ncmpc
go	go	go-U	Ua
fóill	fóill	fóill-A	Aqp
ag	ag	ag-S	Sp
bun	bun	bun-N	Ncmsc
an	an	an-T	Td-s
locha	locha	loch-N	Ncmsg
.	.	.-F	Fe
