Blianta	Blianta	bliain-N	Ncfpc
fada	fada	fada-A	Aqp
ó	ó	ó-S	Sp
shin	shin	sin-P	Pd
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
fathach	fathach	fathach-N	Ncmsc
mór	mór	mór-A	Aq-msc
ina	ina	i-S	Spp-s
chónaí	chónaí	cónaí-N	Ncmsc
ar	ar	ar-S	Sp
Oileán	Oileán	oileán-N	Ncmsc
Thoraí	Thoraí	toradh-N	Ncmpg
i	i	i-S	Sp
nDún na nGall	nDún na nGall	Dún_na_nGall-N	Npmsc
.	.	.-F	Fe
Balor	Balor	Balor-N	Npmsc
an	an	an-T	Td-s
t-ainm	t-ainm	ainm-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Fathach	Fathach	fathach-N	Ncmsc
fíochmhar	fíochmhar	fíochmhar-A	Aq-msc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
súil	súil	súil-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
aige	aige	ag-P	Pr3ms
i lár	i lár	i_lár-S	Spc
a	a	a-D	Dp3
éadain	éadain	éadan-N	Ncmpc
.	.	.-F	Fe
Súil	Súil	súil-N	Ncfsc
draíochta	draíochta	draíocht-N	Ncfsg
lán	lán	lán-A	Aq-fsc
de	de	de-S	Sp
nimh	nimh	nimh-N	Ncfsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
agus	agus	agus-C	Cc
d'fhéadfadh	d'fhéadfadh	féad-V	Vmc
sé	sé	sé-P	Pp3msn
daoine	daoine	duine-N	Ncmpc
a	a	a-U	U
mharú	mharú	maraigh-N	Nv
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
d'fhéach	d'fhéach	féach-V	Vmis
sé	sé	sé-P	Pp3msn
orthu	orthu	ar-P	Pr3-p
.	.	.-F	Fe
Sin	Sin	sin-W	W
an	an	an-T	Td-s
fáth	fáth	fáth-N	Ncmsc
ar	ar	ar-Q	Q-is
tugadh	tugadh	tabhair-V	Vmis0
an	an	an-T	Td-s
t-ainm	t-ainm	ainm-N	Ncmsc
Balor	Balor	Balor-N	Npmsc
na	na	na-T	Tdfsg
Súile	Súile	súil-N	Ncfsg
Nimhe	Nimhe	nimh-N	Ncfsg
air	air	ar-P	Pr3ms
.	.	.-F	Fe
Ba	Ba	is-W	Ws
mhaith	mhaith	maith-A	Aqp
le	le	le-S	Sp
Balor	Balor	Balor-N	Npmsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
beo	beo	beo-A	Aqp
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
bean	bean	bean-N	Ncfsc
feasa	feasa	fios-N	Ncmsg
ann	ann	ann-R	Rl
darbh	darbh	dar-W	Wpsi
ainm	ainm	ainm-N	Ncmsc
Bioróg	Bioróg	bioróg-N	Ncfsc
agus	agus	agus-C	Cc
chuir	chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
ceist	ceist	ceist-N	Ncfsc
uirthi	uirthi	ar-P	Pr3fs
an	an	an-Q	Qq
mbeadh	mbeadh	bí-V	Vmc
sé	sé	sé-P	Pp3msn
in ann	in ann	in_ann-S	Spc
a	a	a-U	U
bheith	bheith	bí-N	Nv
beo	beo	beo-A	Aqp
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
.	.	.-F	Fe
Dúirt	Dúirt	abair-V	Vmis
sise	sise	sí-P	Pp3fsne
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
cinnte	cinnte	cinn-A	Av
agus	agus	agus-C	Cc
nach	nach	nach-Q	Qnr
bhféadfadh	bhféadfadh	féad-V	Vmc
duine	duine	duine-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
é	é	é-P	Pp3ms
a	a	a-U	U
mharú	mharú	maraigh-N	Nv
ach	ach	ach-C	Cs
a	a	a-D	Dp3
gharmhac	gharmhac	mac-N	Ncmsc
féin	féin	féin-P	Px
.	.	.-F	Fe
Cheap	Cheap	ceap-V	Vmis
Balor	Balor	Balor-N	Npmsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sin	sin	sin-P	Pd
ar	ar	ar-S	Sp
fheabhas	fheabhas	feabhas-N	Ncmsc
toisc	toisc	toisc-C	Cs
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
garmhac	garmhac	mac-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
aige	aige	ag-P	Pr3ms
ag	ag	ag-S	Sp
an	an	an-T	Td-s
am	am	am-N	Ncmsc
sin	sin	sin-D	Dd
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
iníon	iníon	iníon-N	Ncfsc
amháin	amháin	amháin-A	Aqp
aige	aige	ag-P	Pr3ms
darbh	darbh	dar-W	Wpsi
ainm	ainm	ainm-N	Ncmsc
Eithne	Eithne	Eithne-N	Npfsc
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
imníoch	imníoch	imníoch-A	Aqp
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
páiste	páiste	páiste-N	Ncmsc
aici	aici	ag-P	Pr3fs
am	am	am-N	Ncmsc
éigin	éigin	éigin-A	Aq-msc
.	.	.-F	Fe
Dúirt	Dúirt	abair-V	Vmis
sé	sé	sé-P	Pp3msn
léi	léi	le-P	Pr3fs
nach	nach	nach-Q	Qnr
mbeadh	mbeadh	bí-V	Vmc
cead	cead	cead-N	Ncmsc
aici	aici	ag-P	Pr3fs
leanbh	leanbh	leanbh-N	Ncmsc
a	a	a-U	U
bheith	bheith	bí-N	Nv
aici	aici	ag-P	Pr3fs
ach	ach	ach-C	Cs
níor	níor	níor-Q	Qn-s
éist	éist	éist-V	Vmis---n
sí	sí	sí-P	Pp3fsn
lena	lena	le-S	Spp-s
daidí	daidí	daidí-N	Ncmsc
in	in	i-S	Sp
aon	aon	aon-D	Dq
chor	chor	cor-N	Ncmsc
.	.	.-F	Fe
Rugadh	Rugadh	beir-V	Vmis0
leanbh	leanbh	leanbh-N	Ncmsc
beag	beag	beag-A	Aq-msc
d'	d'	de-S	Sp
iníon	iníon	iníon-N	Ncfsc
Bhaloir	Bhaloir	Balor-N	Npmsg
tamall	tamall	tamall-N	Ncmsc
tar éis	tar éis	tar_éis-S	Spc
sin	sin	sin-P	Pd
.	.	.-F	Fe
De	De	de-S	Sp
ghnáth	ghnáth	gnáth-N	Ncmsc
bíonn	bíonn	bí-V	Vmig
daideo	daideo	daideo-N	Ncmsc
sona	sona	sona-A	Aqp
sásta	sásta	sásta-A	Aqp
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
thagann	thagann	tar-V	Vmip
garmhac	garmhac	mac-N	Ncmsc
nó	nó	nó-C	Cc
gariníon	gariníon	gariníon-N	Ncfsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
saol	saol	saol-N	Ncmsc
,	,	,-F	Fi
ach	ach	ach-S	Sp
ní	ní	ní-N	Ncmsc
mar	mar	mar-S	Sp
sin	sin	sin-P	Pd
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Balor	Balor	Balor-N	Npmsc
.	.	.-F	Fe
Tugadh	Tugadh	tabhair-V	Vmis0
Lugh	Lugh	Lugh-N	Npmsc
mar	mar	mar-S	Sp
ainm	ainm	ainm-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
leanbh	leanbh	leanbh-N	Ncmsc
beag	beag	beag-A	Aq-msc
gleoite	gleoite	gleoite-A	Aqp
seo	seo	seo-D	Dd
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
a	a	a-D	Dp3
mhamaí	mhamaí	mamaí-N	Nsfsc
fíorbhródúil	fíorbhródúil	bródúil-A	Aqp
as	as	as-P	Pr3ms
.	.	.-F	Fe
Faraor	Faraor	faraor-X	Xsc
,	,	,-F	Fi
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
Balor	Balor	Balor-N	Npmsc
chomh	chomh	chomh-R	Ri
bródúil	bródúil	bródúil-A	Aqp
sin	sin	sin-P	Pd
as	as	as-P	Pr3ms
agus	agus	agus-C	Cc
cad	cad	cad-P	Pq
a	a	a-Q	Q-r
rinne	rinne	déan-V	Vmis
sé	sé	sé-P	Pp3msn
ach	ach	ach-S	Sp
an	an	an-T	Td-s
leanbh	leanbh	leanbh-N	Ncmsc
beag	beag	beag-A	Aq-msc
a	a	a-U	U
chur	chur	cuir-N	Nv
i	i	i-S	Sp
mála	mála	mála-N	Ncmsc
agus	agus	agus-C	Cc
a	a	a-U	U
chaitheamh	chaitheamh	caith-N	Nv
isteach	isteach	isteach-R	Rd
san	san	i-S	Spa-s
fharraige	fharraige	farraige-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
!	!	!-F	Fe
Bhí	Bhí	bí-V	Vmis
Balor	Balor	Balor-N	Npmsc
breá	breá	breá-R	Ri
sásta	sásta	sásta-A	Aqp
leis	leis	le-P	Pr3ms
féin	féin	féin-P	Px
anois	anois	anois-R	Rt
mar	mar	mar-C	Cs
bheadh	bheadh	bí-V	Vmc
sé	sé	sé-P	Pp3msn
beo	beo	beo-A	Aqp
go	go	go-S	Sp
deo	deo	deo-N	Ns-s
na	na	na-T	Td-p
ndeor	ndeor	deoir-N	Ncfpg
,	,	,-F	Fi
dar	dar	dar-V	Vmip
leis	leis	le-P	Pr3ms
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
bhí	bhí	bí-V	Vmis
rud	rud	rud-N	Ncmsc
amháin	amháin	amháin-A	Aqp
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
ag	ag	ag-S	Sp
Balor	Balor	Balor-N	Npmsc
,	,	,-F	Fi
is	is	is-W	Wpri
é	é	é-P	Pp3ms
sin	sin	sin-P	Pd
go	go	go-Q	Q
bhfaca	bhfaca	feic-V	Vmis---d
Bioróg	Bioróg	bioróg-N	Npfsc
,	,	,-F	Fi
an	an	an-T	Td-s
bhean	bhean	bean-N	Ncfsc
feasa	feasa	fios-N	Ncmsg
,	,	,-F	Fi
an	an	an-T	Td-s
leanbh	leanbh	leanbh-N	Ncmsc
ina	ina	i-S	Spp-s
luí	luí	luí-N	Nv
san	san	i-S	Spa-s
fharraige	fharraige	farraige-N	Ncfsc
mhór	mhór	mór-A	Aq-fsc
agus	agus	agus-C	Cc
gur	gur	gur-Q	Q--s
thóg	thóg	tóg-V	Vmis
sí	sí	sí-P	Pp3fsn
amach	amach	amach-R	Rd
slán	slán	slán-N	Ncmsc
sábháilte	sábháilte	sábháil-A	Aqp
é	é	é-P	Pp3ms
as	as	as-S	Sp
an	an	an-T	Td-s
uisce	uisce	uisce-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
garmhac	garmhac	mac-N	Ncmsc
Bhaloir	Bhaloir	Balor-N	Npmsg
,	,	,-F	Fi
Lugh	Lugh	Lugh-N	Np
,	,	,-F	Fi
beo	beo	beo-A	Aqp
go	go	go-U	Ua
fóill	fóill	fóill-A	Aqp
!	!	!-F	Fe
Tugadh	Tugadh	tabhair-V	Vmis0
Lugh	Lugh	Lugh-N	Np
go dtí	go dtí	go_dtí-S	Spc
an	an	an-T	Td-s
mhórthír	mhórthír	mórthír-N	Ncfsc
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
ag	ag	ag-S	Sp
mórán	mórán	mórán-N	Ncmsc
daoine	daoine	duine-N	Ncmpg
cá	cá	cá-R	Rq
raibh	raibh	bí-V	Vmis---d
sé	sé	sé-P	Pp3msn
.	.	.-F	Fe
Blianta	Blianta	bliain-N	Ncfpc
tar éis	tar éis	tar_éis-S	Spc
sin	sin	sin-P	Pd
,	,	,-F	Fi
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Lugh	Lugh	Lugh-N	Np
ina	ina	i-S	Spp-s
fhear	fhear	fear-N	Ncmsc
óg	óg	óg-A	Aq-msc
,	,	,-F	Fi
bhuail	bhuail	buail-V	Vmis
Balor	Balor	Balor-N	Npmsc
agus	agus	agus-C	Cc
Lugh	Lugh	Lugh-N	Np
lena	lena	le-S	Spp-s
chéile	chéile	céile-N	Ncmsc
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
aithin	aithin	aithin-V	Vmis---n
Balor	Balor	Balor-N	Npmsc
Lugh	Lugh	Lugh-N	Np
ach	ach	ach-C	Cs
d'aithin	d'aithin	aithin-V	Vmis
Lugh	Lugh	Lugh-N	Np
Balor	Balor	Balor-N	Npmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
d'inis	d'inis	inis-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
faoin	faoin	faoi-S	Spa-s
rud	rud	rud-N	Ncmsc
a	a	a-Q	Q-r
rinne	rinne	déan-V	Vmis
sé	sé	sé-P	Pp3msn
lena	lena	le-S	Spp-s
gharmhac	gharmhac	mac-N	Ncmsc
.	.	.-F	Fe
Thuig	Thuig	tuig-V	Vmis
Lugh	Lugh	Lugh-N	Np
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
air	air	ar-P	Pr3ms
Balor	Balor	Balor-N	Npmsc
a	a	a-U	U
mharú	mharú	maraigh-N	Nv
ansin	ansin	ansin-R	Rt
.	.	.-F	Fe
Fuair	Fuair	faigh-V	Vmis
sé	sé	sé-P	Pp3msn
biorán	biorán	biorán-N	Ncmsc
te	te	te-A	Aq-msc
agus	agus	agus-C	Cc
sháigh	sháigh	sáigh-V	Vmis
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
biorán	biorán	biorán-N	Ncmsc
trí	trí	trí-S	Sp
shúil	shúil	súil-N	Ncfsc
nimhe	nimhe	nimh-N	Ncfsg
Bhaloir	Bhaloir	Balor-N	Npmsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Balor	Balor	Balor-N	Npmsc
na	na	na-T	Tdfsg
Súile	Súile	súil-N	Ncfsg
Nimhe	Nimhe	nimh-N	Ncfsg
marbh	marbh	marbh-A	Aqp
anois	anois	anois-R	Rt
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
Lugh	Lugh	Lugh-N	Np
beo	beo	beo-A	Aqc
go	go	go-U	Ua
fóill	fóill	fóill-A	Aqp
.	.	.-F	Fe
