Fadó	Fadó	fadó-R	Rt
fadó	fadó	fadó-R	Rt
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
rí	rí	rí-N	Ncmsc
ann	ann	i-R	Rl
i	i	i-S	Sp
gCúige	gCúige	cúige-N	Ncmsc
Uladh	Uladh	Uladh-N	Npfsg
darbh	darbh	dar-W	Wpsi
ainm	ainm	ainm-N	Ncmsc
Conchúr	Conchúr	Conchúr-N	Npmsc
Mac	Mac	Mac-U	Up
Neasa	Neasa	Neasa-N	Npfsc
.	.	.-F	Fe
Oíche	Oíche	oíche-N	Ncfsc
amháin	amháin	amháin-A	Aqp
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
cóisir	cóisir	cóisir-N	Ncfsc
ag	ag	ag-S	Sp
Conchúr	Conchúr	Conchúr-N	Npmsc
ina	ina	i-S	Spp-s
chaisleán	chaisleán	caisleán-N	Ncmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
scéalaí	scéalaí	scéalaí-N	Ncmsc
ag	ag	ag-S	Sp
an	an	an-T	Td-s
gcóisir	gcóisir	cóisir-N	Ncfsc
darbh	darbh	is-W	Wpsi
ainm	ainm	ainm-N	Ncmsc
Feidhlimidh	Feidhlimidh	Feidhlimidh-N	Npmsc
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
lena	lena	le-S	Spp-s
bhean	bhean	bean-N	Ncfsc
chéile	chéile	céile-N	Ncmsg
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
iompar	iompar	iompair-N	Nv
clainne	clainne	clann-N	Ncfsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
draoi	draoi	draoi-N	Ncmsc
sa	sa	i-S	Spa-s
chaisleán	chaisleán	caisleán-N	Ncmsc
an	an	an-T	Td-s
oíche	oíche	oíche-N	Ncfsc
sin	sin	sin-D	Dd
freisin	freisin	freisin-R	Rg
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
in ann	in ann	in_ann-S	Spc
rudaí	rudaí	rud-N	Ncmpc
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
nár	nár	nár-Q	Qnrs
tharla	tharla	tarlaigh-V	Vmis---n
go	go	go-U	Ua
fóill	fóill	fóill-A	Aqp
.	.	.-F	Fe
Labhair	Labhair	labhair-V	Vmis
an	an	an-T	Td-s
draoi	draoi	draoi-N	Ncmsc
le	le	le-S	Sp
Feidhlimidh	Feidhlimidh	Feidhlimidh-N	Npmsc
agus	agus	agus-C	Cc
a	a	a-D	Dp3
bhean	bhean	bean-N	Ncfsc
chéile	chéile	céile-N	Ncmsg
agus	agus	agus-C	Cc
ar	ar	ar-V	Vmis
seisean	seisean	sé-P	Pp3msne
leo	leo	le-P	Pr3-p
:	:	:-F	Fi
'	'	'-F	Fa
Beidh	Beidh	bí-V	Vmif
cailín	cailín	cailín-N	Ncmsc
agaibh	agaibh	ag-P	Pr2-p
sula	sula	sula-C	Cs
i	i	i-S	Sp
bhfad	bhfad	fad-N	Ncmsc
agus	agus	agus-C	Cc
Deirdre	Deirdre	Deirdre-N	Np
an	an	an-T	Td-s
t-ainm	t-ainm	ainm-N	Ncmsc
a	a	a-Q	Q-r
bheidh	bheidh	bí-V	Vmif
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Beidh	Beidh	bí-V	Vmif
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
an	an	an-T	Td-s
mbean	mbean	bean-N	Ncfsc
is	is	is-U	U
áille	áille	álainn-A	Aqc
sa	sa	i-S	Spa-s
tír	tír	tír-N	Ncfsc
seo	seo	seo-D	Dd
.	.	.-F	Fe
Pósfaidh	Pósfaidh	pós-V	Vmif
sí	sí	sí-P	Pp3fsn
duine	duine	duine-N	Ncmsc
den	den	de-S	Spa-s
Chraobh	Chraobh	craobh-N	Npfsc
Rua	Rua	Rua-N	Npmsg
ach	ach	ach-C	Cs
gheobhaidh	gheobhaidh	faigh-V	Vmif
a lán	a lán	a_lán-N	Ns-s
daoine	daoine	duine-N	Ncmpg
bás	bás	bás-N	Ncmsc
i	i	i-S	Sp
gCúige	gCúige	cúige-N	Ncmsc
Uladh	Uladh	Uladh-N	Npfsg
mar	mar	mar-S	Sp
gheall	gheall	geall-N	Ncmsc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
'	'	'-F	F
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
Feidhlimidh	Feidhlimidh	Feidhlimidh-N	Npmsc
ná	ná	ná-C	Cc
a	a	a-D	Dp3
bhean	bhean	bean-N	Ncfsc
chéile	chéile	céile-N	Ncmsg
sásta	sásta	sásta-A	Aqp
leis	leis	le-S	Sp
an	an	an-T	Td-s
draoi	draoi	draoi-N	Ncmsc
faoi	faoi	faoi-S	Sp
seo	seo	seo-P	Pd
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
an	an	an-T	Td-s
draoi	draoi	draoi-N	Ncmsc
eagla	eagla	eagla-N	Ncfsc
ar	ar	ar-S	Sp
a lán	a lán	a_lán-N	Ns-s
daoine	daoine	duine-N	Ncmpg
eile	eile	eile-D	Dd
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sa	sa	i-S	Spa-s
chaisleán	chaisleán	caisleán-N	Ncmsc
an	an	an-T	Td-s
oíche	oíche	oíche-N	Ncfsg
sin	sin	sin-D	Dd
.	.	.-F	Fe
Tar éis	Tar éis	tar_éis-S	Spc
tamaill	tamaill	tamall-N	Ncmsg
,	,	,-F	Fi
rugadh	rugadh	beir-V	Vmis0
cailín	cailín	cailín-N	Ncmsc
do	do	do-S	Sp
bhean	bhean	bean-N	Ncfsc
chéile	chéile	céile-N	Ncmsg
Fheidhlimidh	Fheidhlimidh	Feidhlimidh-N	Npfsg
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a lán	a lán	a_lán-N	Ns-s
daoine	daoine	duine-N	Ncmpg
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
an	an	an-T	Td-s
cailín	cailín	cailín-N	Ncmsc
a	a	a-U	U
mharú	mharú	maraigh-N	Nv
mar	mar	mar-S	Sp
gheall	gheall	geall-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
rud	rud	rud-N	Ncmsc
a	a	a-Q	Q-r
dúirt	dúirt	abair-V	Vmis
an	an	an-T	Td-s
draoi	draoi	draoi-N	Ncmsc
.	.	.-F	Fe
Níor	Níor	níor-Q	Qn-s
lig	lig	lig-V	Vmis---n
Conchúr	Conchúr	Conchúr-N	Npmsc
dóibh	dóibh	do-P	Pr3-p
sin	sin	sin-P	Pd
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
áfach	áfach	áfach-R	Rg
,	,	,-F	Fi
mar	mar	mar-C	Cs
ba	ba	is-W	Wsri
mhaith	mhaith	maith-A	Aqp
leis	leis	le-P	Pr3ms
í	í	í-P	Pp3fs
a	a	a-U	U
bheith	bheith	bí-N	Nv
aige	aige	ag-P	Pr3ms
féin	féin	féin-P	Px
mar	mar	mar-S	Sp
bhean	bhean	bean-N	Ncfsc
chéile	chéile	céile-N	Ncmsg
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
sí	sí	sí-P	Pp3fsn
níos	níos	níos-U	Uc
sine	sine	sean-A	Aqc
.	.	.-F	Fe
D'iarr	D'iarr	iarr-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
Leabharcam	Leabharcam	Leabharcam-N	Npmsc
,	,	,-F	Fi
a	a	a-U	Uv
bhanaltra	bhanaltra	banaltra-N	Ncfsc
,	,	,-F	Fi
aire	aire	aire-N	Ncfsc
a	a	a-U	U
thabhairt	thabhairt	tabhair-N	Nv
do	do	do-S	Sp
Dheirdre	Dheirdre	Deirdre-N	Npfsc
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
óg	óg	óg-A	Aqp
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
Deirdre	Deirdre	Deirdre-N	Np
ina	ina	i-S	Spp-s
cónaí	cónaí	cónaí-N	Ncmsc
ag	ag	ag-S	Sp
Leabharcam	Leabharcam	Leabharcam-N	Npmsc
i	i	i-S	Sp
dteach	dteach	teach-N	Ncmsc
beag	beag	beag-A	Aq-msc
i lár	i lár	i_lár-S	Spc
na	na	na-T	Tdfsg
coille	coille	coill-N	Ncfsg
.	.	.-F	Fe
D'fhás	D'fhás	fás-V	Vmis
sí	sí	sí-P	Pp3fsn
aníos	aníos	aníos-R	Rd
ina	ina	i-S	Spp-s
bean	bean	bean-N	Ncfsc
álainn	álainn	álainn-A	Aq-fsc
rua	rua	rua-A	Aqp
.	.	.-F	Fe
Lá	Lá	lá-N	Ncmsc
amháin	amháin	amháin-A	Aqp
,	,	,-F	Fi
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
Deirdre	Deirdre	Deirdre-N	Np
amuigh	amuigh	amuigh-R	Rl
sa	sa	i-S	Spa-s
choill	choill	coill-N	Ncfsc
,	,	,-F	Fi
chonaic	chonaic	feic-V	Vmis
sí	sí	sí-P	Pp3fsn
triúr	triúr	triúr-N	Ncmsc
fear	fear	fear-N	Ncmpg
ón	ón	ó-S	Spa-s
gCraobh	gCraobh	craobh-N	Ncfsc
Rua	Rua	Rua-A	Aqp
ag	ag	ag-S	Sp
seilg	seilg	seilg-N	Nv
.	.	.-F	Fe
D'fhéach	D'fhéach	féach-V	Vmis
sí	sí	sí-P	Pp3fsn
ar	ar	ar-S	Sp
dhuine	dhuine	duine-N	Ncmsc
acu	acu	ag-P	Pr3-p
darbh	darbh	dar-W	Wpsi
ainm	ainm	ainm-N	Ncmsc
Naoise	Naoise	Naoise-N	Npmsc
agus	agus	agus-C	Cc
thit	thit	tit-V	Vmis
sí	sí	sí-P	Pp3fsn
i	i	i-S	Sp
ngrá	ngrá	grá-N	Ncmsc
leis	leis	le-P	Pr3ms
láithreach	láithreach	láithreach-R	Rg
.	.	.-F	Fe
Agus	Agus	agus-C	Cc
chomh	chomh	chomh-R	Ri
luath	luath	luath-A	Aqp
is	is	agus-C	Cc
a	a	a-Q	Q-r
chonaic	chonaic	feic-V	Vmis
Naoise	Naoise	Naoise-N	Npmsc
Deirdre	Deirdre	Deirdre-N	Npfsc
,	,	,-F	Fi
thit	thit	tit-V	Vmis
seisean	seisean	sé-P	Pp3msne
i	i	i-S	Sp
ngrá	ngrá	grá-N	Ncmsc
léise	léise	le-P	Pr3fs-e
.	.	.-F	Fe
Go	Go	go-U	Ua
luath	luath	luath-A	Aqp
tar éis	tar éis	tar_éis-S	Spc
sin	sin	sin-P	Pd
,	,	,-F	Fi
phós	phós	pós-V	Vmis
siad	siad	siad-P	Pp3-pn
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
a	a	a-D	Dp3
fhios	fhios	fios-N	Ncmsc
ag	ag	ag-S	Sp
Naoise	Naoise	Naoise-N	Npmsc
agus	agus	agus-C	Cc
Deirdre	Deirdre	Deirdre-N	Npfsc
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
Conchúr	Conchúr	Conchúr-N	Npmsc
ag	ag	ag-S	Sp
dul	dul	téigh-N	Nv
a	a	a-U	U
bheith	bheith	bí-N	Nv
an-mhíshásta	an-mhíshásta	míshásta-A	Aqp
leo	leo	le-P	Pr3-p
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
chloisfeadh	chloisfeadh	clois-V	Vmc
sé	sé	sé-P	Pp3msn
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
gur	gur	gur-Q	Q--s
phós	phós	pós-V	Vmis
siad	siad	siad-P	Pp3-pn
.	.	.-F	Fe
Mar	Mar	mar-S	Sp
gheall	gheall	geall-N	Ncmsc
air	air	ar-S	Sp
sin	sin	sin-P	Pd
,	,	,-F	Fi
d'imigh	d'imigh	imigh-V	Vmis
siad	siad	siad-P	Pp3-pn
leo	leo	le-P	Pr3-p
go	go	go-S	Sp
hAlbain	hAlbain	Albain-N	Np
.	.	.-F	Fe
Chaith	Chaith	caith-V	Vmis
Conchúr	Conchúr	Conchúr-N	Npmsc
tamall	tamall	tamall-N	Ncmsc
fada	fada	fada-A	Aqp
ag	ag	ag-S	Sp
smaoineamh	smaoineamh	smaoinigh-N	Nv
ar	ar	ar-S	Sp
phlean	phlean	plean-N	Ncmsc
le	le	le-S	Sp
Deirdre	Deirdre	Deirdre-N	Np
a	a	a-U	U
fháil	fháil	faigh-N	Nv
ar ais	ar ais	ar_ais-R	Rd
arís	arís	arís-R	Rg
dó	dó	do-P	Pr3ms
féin	féin	féin-P	Px
.	.	.-F	Fe
Shocraigh	Shocraigh	socraigh-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
scéal	scéal	scéal-N	Ncmsc
a	a	a-U	U
chur	chur	cuir-N	Nv
chuig	chuig	chuig-S	Sp
Deirdre	Deirdre	Deirdre-N	Np
agus	agus	agus-C	Cc
Naoise	Naoise	Naoise-N	Npmsc
go	go	go-Q	Q
mbeadh	mbeadh	bí-V	Vmc
fáilte	fáilte	fáilte-N	Ncfsc
rompu	rompu	roimh-P	Pr3-p
teacht	teacht	tar-N	Nv
ar ais	ar ais	ar_ais-R	Rd
go	go	go-S	Sp
hÉirinn	hÉirinn	Éire-N	Npfsd
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
áthas	áthas	áthas-N	Ncmsc
an	an	an-T	Td-s
domhain	domhain	domhan-N	Ncmsg
ar	ar	ar-S	Sp
Dheirdre	Dheirdre	Deirdre-N	Np
agus	agus	agus-C	Cc
ar	ar	ar-S	Sp
Naoise	Naoise	Naoise-N	Npmsc
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
fuair	fuair	faigh-V	Vmis
siad	siad	siad-P	Pp3-pn
an	an	an-T	Td-s
scéal	scéal	scéal-N	Ncmsc
seo	seo	seo-D	Dd
agus	agus	agus-C	Cc
tháinig	tháinig	tar-V	Vmis
siad	siad	siad-P	Pp3-pn
abhaile	abhaile	abhaile-R	Rd
.	.	.-F	Fe
Ach	Ach	ach-C	Cs
d'imir	d'imir	imir-V	Vmm-2s
Conchúr	Conchúr	Conchúr-N	Npmsc
feall	feall	feall-N	Ncmsc
orthu	orthu	ar-P	Pr3-p
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
tháinig	tháinig	tar-V	Vmis
siad	siad	siad-P	Pp3-pn
ar ais	ar ais	ar_ais-R	Rd
go	go	go-S	Sp
hÉirinn	hÉirinn	Éire-N	Npfsd
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
saighdiúirí	saighdiúirí	saighdiúir-N	Ncmpc
Chonchúir	Chonchúir	Conchúr-N	Npmsg
ag	ag	ag-S	Sp
fanacht	fanacht	fan-N	Nv
leo	leo	le-P	Pr3-p
agus	agus	agus-C	Cc
mharaigh	mharaigh	maraigh-V	Vmis
siad	siad	siad-P	Pp3-pn
Naoise	Naoise	Naoise-N	Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
Deirdre	Deirdre	Deirdre-N	Np
an-fheargach	an-fheargach	feargach-A	Aqp
le	le	le-S	Sp
Conchúr	Conchúr	Conchúr-N	Npmsc
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
raibh	raibh	bí-V	Vmis---n
sí	sí	sí-P	Pp3fsn
sásta	sásta	sásta-A	Aqp
é	é	é-P	Pp3ms
a	a	a-U	U
phósadh	phósadh	pós-N	Nv
in	in	i-S	Sp
aon	aon	aon-D	Dq
chor	chor	cor-N	Ncmsc
.	.	.-F	Fe
Níorbh	Níorbh	is-W	Ws-in
fhada	fhada	fada-A	Aqp
tar éis	tar éis	tar_éis-S	Spc
sin	sin	sin-P	Pd
go	go	go-Q	Q
bhfuair	bhfuair	faigh-V	Vmis
Deirdre	Deirdre	Deirdre-N	Np
bás	bás	bás-N	Ncmsc
mar	mar	mar-C	Cs
bhí	bhí	bí-V	Vmis
sí	sí	sí-P	Pp3fsn
croíbhriste	croíbhriste	croíbhriste-A	Aqp
.	.	.-F	Fe
