Fadó	Fadó	fadó-R	R
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
arracht	arracht	arracht-N	Ncmsc
gránna	gránna	gránna-A	Aqp
sa	sa	i-S	Spa-s
Ghréig	Ghréig	Gréig-N	Npfsc
a	a	a-Q	Q-r
chónaigh	chónaigh	cónaigh-V	Vmis
i	i	i-S	Sp
bpluais	bpluais	pluais-N	Ncfsc
sna	sna	i-S	Spa-p
sléibhte	sléibhte	sliabh-N	Ncmpc
.	.	.-F	Fe
Meadúsa	Meadúsa	Meadúsa-N	Npmsc
an	an	an-T	Td-s
t-ainm	t-ainm	ainm-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ar	ar	ar-S	Sp
an	an	an-T	Td-s
arracht	arracht	arracht-N	Ncmsc
scanrúil	scanrúil	scanrúil-A	Aq-msc
seo	seo	seo-D	Dd
,	,	,-F	Fi
agus	agus	agus-C	Cc
cé	cé	cé-C	Cs
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
cosúil	cosúil	cosúil-A	Aqp
le	le	le-S	Sp
bean	bean	bean-N	Ncfsc
ar	ar	ar-S	Sp
bhealach	bhealach	bealach-N	Ncmsc
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
nathracha	nathracha	nathair-N	Ncfpc
ag	ag	ag-S	Sp
fás	fás	fás-N	Nv
as	as	as-P	Pr3ms
a	a	a-D	Dp3
ceann	ceann	ceann-N	Ncmsc
mar	mar	mar-C	Cs
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
gruaig	gruaig	gruaig-N	Ncfsc
ann	ann	i-P	Pr3ms
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
súile	súile	súil-N	Ncfpc
buí	buí	buí-A	Aqp
fiata	fiata	fiata-A	Aqp
aici	aici	ag-P	Pr3fs
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
a	a	a-D	Dp3
haghaidh	haghaidh	aghaidh-N	Ncfsc
glas	glas	glas-A	Aqp
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
draíocht	draíocht	draíocht-N	Ncfsc
ar	ar	ar-S	Sp
leith	leith	leith-N	Ncfsc
aici	aici	ag-P	Pr3fs
freisin	freisin	freisin-R	Rg
,	,	,-F	Fi
is	is	is-W	Wpri
é	é	é-P	Pp3ms
sin	sin	sin-P	Pd
go	go	go-Q	Q
raibh	raibh	bí-V	Vmis---d
sí	sí	sí-P	Pp3fsn
ábalta	ábalta	ábalta-A	Aqp
dealbh	dealbh	dealbh-N	Nsfsc
chloiche	chloiche	cloch-N	Ncfsg
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
den	den	de-S	Spa-s
duine	duine	duine-N	Ncmsc
a	a	a-Q	Q-r
bheadh	bheadh	bí-V	Vmc
amaideach	amaideach	amaideach-A	Aqp
go leor	go leor	go_leor-A	Aq
le	le	le-S	Sp
féachaint	féachaint	féach-N	Nv
go	go	go-U	Ua
díreach	díreach	díreach-A	Aqp
sna	sna	i-S	Spa-p
súile	súile	súil-N	Ncfpc
uirthi	uirthi	ar-P	Pr3fs
.	.	.-F	Fe
Le	Le	le-S	Sp
himeacht	himeacht	imigh-N	Nv
ama	ama	ama-N	Ncmsg
,	,	,-F	Fi
rinne	rinne	déan-V	Vmis
a lán	a lán	a_lán-N	Ns-s
daoine	daoine	duine-N	Ncmpg
iarracht	iarracht	iarracht-N	Ncfsc
an	an	an-T	Td-s
t-arracht	t-arracht	arracht-N	Ncmsc
scanrúil	scanrúil	scanrúil-A	Aq-msc
seo	seo	seo-D	Dd
a	a	a-U	U
mharú	mharú	maraigh-N	Nv
ach	ach	ach-S	Sp
theip	theip	teip-V	Vmis
orthu	orthu	ar-P	Pr3-p
ar	ar	ar-S	Sp
fad	fad	fad-N	Ncmsc
mar	mar	mar-C	Cs
,	,	,-F	Fi
nuair	nuair	nuair-C	Cs
a	a	a-Q	Q-r
d'fhéach	d'fhéach	féach-V	Vmis
siad	siad	siad-P	Pp3-pn
uirthi	uirthi	ar-P	Pr3fs
,	,	,-F	Fi
rinne	rinne	déan-V	Vmis
sí	sí	sí-P	Pp3fsn
dealbh	dealbh	dealbh-N	Ncfsc
díobh	díobh	de-P	Pr3-p
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
dhá	dhá	dó-M	Mc
gharda	gharda	garda-N	Ncmsc
uafásacha	uafásacha	uafásach-A	Aq--pc
ag	ag	ag-S	Sp
Meadúsa	Meadúsa	Meadúsa-N	Npmsc
nár	nár	nár-Q	Qnrs
lig	lig	lig-V	Vmis---n
do	do	do-S	Sp
dhuine	dhuine	duine-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
teacht	teacht	tar-N	Nv
isteach	isteach	isteach-R	Rd
ina	ina	i-S	Spp-s
pluais	pluais	pluais-N	Ncfsc
.	.	.-F	Fe
San	San	i-S	Spa-s
am	am	am-N	Ncmsc
seo	seo	seo-D	Dd
sa	sa	i-S	Spa-s
Ghréig	Ghréig	Gréig-N	Npfsc
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
fear	fear	fear-N	Ncmsc
láidir	láidir	láidir-A	Aq-msc
cróga	cróga	cróga-A	Aqp
ann	ann	ann-R	Rl
darbh	darbh	dar-W	Wpsi
ainm	ainm	ainm-N	Ncmsc
Perseus	Perseus	Perseus-N	Npmsc
,	,	,-F	Fi
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ag	ag	ag-S	Sp
iarraidh	iarraidh	iarr-N	Nv
Meadúsa	Meadúsa	Meadúsa-N	Npmsg
a	a	ag-S	Sp
mharú	mharú	marú-N	Nv
.	.	.-F	Fe
D'iarr	D'iarr	iarr-V	Vmis
sé	sé	sé-P	Pp3msn
cabhair	cabhair	cabhair-N	Ncfsc
ar	ar	ar-S	Sp
na	na	na-T	Td-p
déithe	déithe	dia-N	Ncmpc
sa	sa	i-S	Spa-s
Ghréig	Ghréig	Gréig-N	Npfsc
le	le	le-S	Sp
Meadúsa	Meadúsa	Meadúsa-N	Npmsc
a	a	a-U	U
mharú	mharú	maraigh-N	Nv
.	.	.-F	Fe
Tháinig	Tháinig	tar-V	Vmis
na	na	na-T	Td-p
déithe	déithe	dia-N	Ncmpc
le	le	le-S	Sp
chéile	chéile	céile-N	Ncmsc
le	le	le-S	Sp
cabhrú	cabhrú	cabhraigh-N	Nv
leis	leis	le-P	Pr3ms
agus	agus	agus-C	Cc
thug	thug	tabhair-V	Vmis
gach	gach	gach-D	Dq
dia	dia	dia-N	Ncmsc
acu	acu	ag-P	Pr3-p
bronntanas	bronntanas	bronntanas-N	Ncmsc
cumhachtach	cumhachtach	cumhachtach-A	Aq-msc
draíochtach	draíochtach	draíochtach-A	Aq-msc
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
an	an	an-T	Td-s
chéad	chéad	céad-M	Mo
dia	dia	dia-N	Ncmsc
claíomh	claíomh	claíomh-N	Ncmsc
géar	géar	géar-A	Aq-msc
dó	dó	do-P	Pr3ms
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
an	an	an-T	Td-s
dara	dara	dara-M	Mo
dia	dia	dia-N	Ncmsc
cuaráin	cuaráin	cuarán-N	Ncmpc
dó	dó	do-P	Pr3ms
a	a	a-Q	Q-i
raibh	raibh	bí-V	Vmis---d
sciatháin	sciatháin	sciathán-N	Ncmpc
orthu	orthu	ar-P	Pr3-p
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
an	an	an-T	Td-s
tríú	tríú	trí-M	Mo
dia	dia	dia-N	Ncmsc
clogad	clogad	clogad-N	Ncmsc
dó	dó	do-P	Pr3ms
a	a	a-Q	Q-r
rinne	rinne	déan-V	Vmis
dofheicthe	dofheicthe	dofheicthe-A	Aqp
é	é	é-P	Pp3ms
.	.	.-F	Fe
Thug	Thug	tabhair-V	Vmis
an	an	an-T	Td-s
ceathrú	ceathrú	ceathair-M	Mo
dia	dia	dia-N	Ncmsc
sciath	sciath	sciath-N	Ncfsc
dó	dó	do-P	Pr3ms
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
cosúil	cosúil	cosúil-A	Aqp
le	le	le-S	Sp
scáthán	scáthán	scáthán-N	Ncmsc
ar	ar	ar-S	Sp
an	an	an-T	Td-s
taobh	taobh	taobh-N	Nsmcs
istigh	istigh	istigh-R	Rl
.	.	.-F	Fe
Nuair	Nuair	nuair-C	Cs
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
sin	sin	sin-P	Pd
déanta	déanta	déan-A	Av
acu	acu	ag-P	Pr3-p
,	,	,-F	Fi
ar	ar	ar-V	Vmis
siadsan	siadsan	siad-P	Pp3-pne
le	le	le-S	Sp
Perseus	Perseus	Perseus-N	Npmsc
,	,	,-F	Fi
Is	Is	is-W	Wpri
féidir	féidir	féidir-N	Ns-s
leat	leat	le-P	Pr2-s
eitilt	eitilt	eitil-N	Nv
go	go	go-U	Ua
díreach	díreach	díreach-A	Aqp
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
phluais	phluais	pluais-N	Ncfsc
leis	leis	le-S	Sp
na	na	na-T	Td-p
cuaráin	cuaráin	cuarán-N	Ncmpc
speisialta	speisialta	speisialta-A	Aqp
seo	seo	seo-D	Dd
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
fheicfidh	fheicfidh	feic-V	Vmif---n
na	na	na-T	Td-p
gardaí	gardaí	garda-N	Ncmpc
thú	thú	tú-P	Pp2-s
.	.	.-F	Fe
Cuir	Cuir	cuir-V	Vmm-2s
ort	ort	ar-P	Pr2-s
do	do	do-S	Sp
chlogad	chlogad	clogad-N	Ncmsc
ansin	ansin	ansin-R	Rt
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
bheidh	bheidh	bí-V	Vmif---n
Meadúsa	Meadúsa	Meadúsa-N	Npmsc
ábalta	ábalta	ábalta-A	Aqp
tú	tú	tú-P	Pp2-s
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
ach	ach	ach-S	Sp
oiread	oiread	oiread-N	Ns-s
.	.	.-F	Fe
Ná	Ná	ná-Q	Qnm
féach	féach	féach-V	Vmm-2s-n
go	go	go-U	Ua
díreach	díreach	díreach-A	Aqp
sna	sna	i-S	Spa-p
súile	súile	súil-N	Ncfpc
ar	ar	ar-S	Sp
Mheadúsa	Mheadúsa	Meadúsa-N	Npmsc
in	in	i-S	Sp
am	am	am-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
.	.	.-F	Fe
Ina	Ina	i-S	Spp-s
áit	áit	áit-N	Ncfsc
sin	sin	sin-D	Dd
,	,	,-F	Fi
coimeád	coimeád	coimeád-V	Vmm-2s
do	do	do-S	Sp
dhroim	dhroim	droim-N	Ncmsc
léi	léi	le-P	Pr3fs
agus	agus	agus-C	Cc
feicfidh	feicfidh	feic-V	Vmif
tú	tú	tú-P	Pp2-s
a	a	a-D	Dp3
scáth	scáth	scáth-N	Ncmsc
sa	sa	i-S	Spa-s
sciath	sciath	sciath-N	Ncfsc
.	.	.-F	Fe
Ar	Ar	ar-S	Sp
an	an	an-T	Td-s
mbealach	mbealach	bealach-N	Ncmsc
sin	sin	sin-D	Dd
beidh	beidh	bí-V	Vmif
tú	tú	tú-P	Pp2-s
slán	slán	slán-A	Aqp
sábháilte	sábháilte	sábháil-A	Aqp
.	.	.-F	Fe
Chuaigh	Chuaigh	téigh-V	Vmis
Perseus	Perseus	Perseus-N	Npmsc
go dtí	go dtí	go_dtí-S	Spc
pluais	pluais	pluais-N	Ncfsc
Mheadúsa	Mheadúsa	Meadúsa-N	Npmsg
sna	sna	i-S	Spa-p
sléibhte	sléibhte	sliabh-N	Ncmpc
.	.	.-F	Fe
D'eitil	D'eitil	eitil-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-U	Ua
cúramach	cúramach	cúramach-A	Aqp
thar	thar	thar-S	Sp
na	na	na-T	Td-p
dealbha	dealbha	dealbh-N	Ncfpc
go	go	go-U	Ua
léir	léir	léir-A	Aqp
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
agus	agus	agus-C	Cc
isteach	isteach	isteach-R	Rd
sa	sa	i-S	Spa-s
phluais	phluais	pluais-N	Ncfsc
leis	leis	le-P	Pr3ms
sular	sular	sula-C	Cs-s
thug	thug	tabhair-V	Vmis
aon	aon	aon-D	Dq
duine	duine	duine-N	Ncmsc
faoi	faoi	faoi-S	Sp
deara	deara	deara-N	Ns-s
é	é	é-P	Pp3ms
.	.	.-F	Fe
Ní	Ní	ní-Q	Qn
fhaca	fhaca	feic-V	Vmis---n
agus	agus	agus-C	Cc
níor	níor	níor-Q	Qn-s
chuala	chuala	clois-V	Vmis
na	na	na-T	Td-p
gardaí	gardaí	garda-N	Ncmpc
é	é	é-P	Pp3ms
.	.	.-F	Fe
Chuir	Chuir	cuir-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
chlogad	chlogad	clogad-N	Ncmsc
air	air	ar-P	Pr3ms
ansin	ansin	ansin-R	Rt
ionas	ionas	ionas-N	Ns-s
nach	nach	nach-Q	Qnrs
raibh	raibh	bí-V	Vmis---n
Meadúsa	Meadúsa	Meadúsa-N	Npmsc
ábalta	ábalta	ábalta-A	Aqp
é	é	é-P	Pp3ms
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
.	.	.-F	Fe
Choimeád	Choimeád	coimeád-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
dhroim	dhroim	droim-N	Ncmsc
léi	léi	le-P	Pr3fs
,	,	,-F	Fi
d'fhéach	d'fhéach	féach-V	Vmis
sé	sé	sé-P	Pp3msn
ar	ar	ar-S	Sp
a	a	a-Q	Q-r
sciath	sciath	sciath-N	Ncfsc
agus	agus	agus-C	Cc
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
in ann	in ann	in_ann-S	Spc
scáil	scáil	scál-N	Ncmsg
Mheadúsa	Mheadúsa	Meadúsa-N	Npmsg
a	a	a-U	U
fheiceáil	fheiceáil	feic-N	Nv
.	.	.-F	Fe
Gan	Gan	gan-S	Sp
mórán	mórán	mórán-N	Ncmsc
moille	moille	moill-N	Ncfsg
,	,	,-F	Fi
bhí	bhí	bí-V	Vmis
sé	sé	sé-P	Pp3msn
ábalta	ábalta	ábalta-A	Aqp
teacht	teacht	tar-N	Nv
aniar	aniar	aniar-R	Rd
aduaidh	aduaidh	aduaidh-R	Rd
ar	ar	ar-S	Sp
Mheadúsa	Mheadúsa	Meadúsa-N	Npmsc
i	i	i-S	Sp
ngan fhios	ngan fhios	fios-N	Ncmsc
di	di	do-P	Pr3fs
.	.	.-F	Fe
Thóg	Thóg	tóg-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
chlaíomh	chlaíomh	claíomh-N	Ncmsc
,	,	,-F	Fi
bhuail	bhuail	buail-V	Vmis
sé	sé	sé-P	Pp3msn
go	go	go-U	Ua
trom	trom	trom-A	Aqp
í	í	í-P	Pp3fs
agus	agus	agus-C	Cc
bhain	bhain	bain-V	Vmis
sé	sé	sé-P	Pp3msn
a	a	a-D	Dp3
ceann	ceann	ceann-N	Ncmsc
di	di	de-P	Pr3fs
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
éacht	éacht	éacht-N	Ncmsc
déanta	déanta	déan-A	Av
aige	aige	ag-P	Pr3ms
nár	nár	nár-Q	Qnrs
éirigh	éirigh	éirigh-V	Vmis---n
le	le	le-S	Sp
duine	duine	duine-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
eile	eile	eile-D	Dd
a	a	a-U	U
dhéanamh	dhéanamh	déan-N	Nv
roimhe	roimhe	roimh-P	Pr3ms
sin	sin	sin-P	Pd
.	.	.-F	Fe
Laoch	Laoch	laoch-N	Ncmsc
a	a	a-Q	Q-r
bhí	bhí	bí-V	Vmis
ann	ann	i-P	Pr3ms
anois	anois	anois-R	Rt
mar	mar	mar-C	Cs
bhí	bhí	bí-V	Vmis
gach	gach	gach-D	Dq
duine	duine	duine-N	Ncmsc
an-sásta	an-sásta	sásta-A	Aqp
leis	leis	le-P	Pr3ms
gur	gur	gur-Q	Q--s
mharaigh	mharaigh	maraigh-V	Vmis
sé	sé	sé-P	Pp3msn
Meadúsa	Meadúsa	Meadúsa-N	Npmsc
.	.	.-F	Fe
Bhí	Bhí	bí-V	Vmis
deireadh	deireadh	deireadh-N	Ncmsc
leis	leis	le-S	Sp
an	an	an-T	Td-s
arracht	arracht	arracht-N	Ncmsc
gránna	gránna	gránna-A	Aqp
scanrúil	scanrúil	scanrúil-A	Aqp
faoi	faoi	faoi-S	Sp
dheireadh	dheireadh	deireadh-N	Ncmsc
agus	agus	agus-C	Cc
ní	ní	ní-Q	Qn
dhéanfadh	dhéanfadh	déan-V	Vmc----n
sí	sí	sí-P	Pp3fsn
dealbh	dealbh	dealbh-N	Ncfsc
chloiche	chloiche	cloch-N	Ncfsg
de	de	de-S	Sp
dhuine	dhuine	duine-N	Ncmsc
ar	ar	ar-S	Sp
bith	bith	bith-N	Ncmsc
eile	eile	eile-D	Dd
choíche	choíche	choíche-R	Rg
arís	arís	arís-R	Rg
.	.	.-F	Fe
